### ISSUE TITLE
save() function replaces forward slash with dashes when trying to save to absolute path

### ISSUE THREAD

**Issue by slegroux** [processing/p5.js#1000]
I'm trying to save an audio file in a specific folder on OS X (using p5.SoundFile and save() function)

Neither of these options work: 
``` javascript
save(soundFile, "/tmp/tmp.wav"); 
save(soundFile, "\/tmp\/tmp.wav");
```
It looks like the save function automatically replaces foward slashes by dashes when saving to folder (the audio file ends up beeing saved in ~/Download/-tmp-tmp.wav)

Any idea what I should do to solve this? Thank you! S.

**Comment by laurentoget** [comment]
This is a limitation of the html download attribute. This attribute is a file name, not a file path, and the browser is editing the name accordingly. There is a security reason for this. Cannot let js scripts write wherever they want.

Maybe a workaround would be to create a link to the blob which the user can then save using 'Save Link As'.

**Comment by lmccart** [comment]
thanks @laurentoget, this is correct. however, I think saving to a blob is a bit beyond the scope of the p5.js API, we already have a lot of save functions. if a user really wants to do this, they have access to `canvas` and can save it any way they like using the HTMLCanvasElement API. there are also a few libraries that can help with this:
* https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob
* https://github.com/blueimp/JavaScript-Canvas-to-Blob
