### ISSUE TITLE
Auto Resize Canvas with Browser

### ISSUE THREAD

**Issue by zettam** [processing/p5.js#1001]
I've been trying to make this work:
http://p5js.org/reference/#p5/resizeCanvas

The resize works, owevr, scrollbars are always there (canvas is always slightly bigger)

What should I to make it fit?

**Comment by lmccart** [comment]
many browsers have default padding or margin on a page, making the canvas overflow past the window if it's the size of the window.

you can add this line to the head of your html:
`<style> body{padding:0; margin:0;} </style>`
see more explanation in the p5.js overview tutorial: https://github.com/processing/p5.js/wiki/p5.js-overview#createcanvas

in general, this type of question is better for the forum, the issues are mostly for reporting bugs or discussing new features.
http://forum.processing.org/two/
