### ISSUE TITLE
splitTokens() with [ ] as delimiters bug

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js#1004]
I'm working on #422 and wanted to make a note here that if you try to use a `[` or `]` as a delimiter with `splitTokens()` there's a bug due to the way I am forming a regular expression behind the scenes.  This will come up rarely, but still needs to be fixed.  I shall do so soon!

**Comment by DarkPrince304** [comment]
Hello, I have fixed this issue and it has passed all the checks too.

Kindly have a look at my PR here : processing/p5.js#1015

**Comment by shiffman** [comment]
@lmccart I've reviewed this pull request and the behavior for `split()` and `splitTokens()` is correct.

**Comment by lmccart** [comment]
closed with https://github.com/processing/p5.js/pull/1023
