### ISSUE TITLE
error using ambientLight();

### ISSUE THREAD

**Issue by Diex** [processing/p5.js#1009]
when trying to use ambientLight() I get this error:

[GroupMarkerNotSet(crbug.com/242999)!:D0DC16BED47F0000]GL ERROR :GL_INVALID_OPERATION : glDrawArrays: attempt to render with no buffer attached to enabled attribute 2

Google Chrome 
Version 46.0.2490.64 beta (64-bit)
 

 Model Name:	Mac mini
  Model Identifier:	Macmini5,2
  Processor Name:	Intel Core i5
  Processor Speed:	2.5 GHz
  Number of Processors:	1
  Total Number of Cores:	2
AMD Radeon HD 6630M:

  Chipset Model:	AMD Radeon HD 6630M
  Type:	GPU
  Bus:	PCIe
  PCIe Lane Width:	x8
  VRAM (Total):	256 MB
  Vendor:	ATI (0x1002)
  Device ID:	0x6741
  Revision ID:	0x0000
  ROM Revision:	113-C0171H-561
  EFI Driver Version:	01.00.561

**Comment by indefinit** [comment]
@Diex Do you have sample code you might be able to provide?  I'm currently not able to replicate.  Do you see the same error when running the documentation page: http://p5js.org/reference/#p5/ambientLight

**Comment by Diex** [comment]
nevermind by now.  I think it was just something I can figure out right now. it's working fine.
I re-code my sketch and voila. I thought maybe it was because of instance mode... but no.
kind regards.

**Comment by Diex** [comment]
sorry: I found it.
it's about line();

```
var canvas;

var sketch = function(p) {
        
    p.setup = function() {
        canvas = p.createCanvas(p.windowWidth, p.windowHeight, p.WEBGL);
        canvas.parent('myContainer');        
        p.background(0);
        p.frameRate(25);
    };



    p.draw = function() {
        
        p.background(0);
        p.ambientLight(125);        
        p.pointLight(250, 250, 250, p.width / 2 , 0, 0);
        
        // p.sphere(10); // this works
        p.line(0,0,0, 100, 100, 100);        // this does not work

        // p.beginShape();             // this does not work either
        // p.vertex(0,0,0);
        // p.vertex(100, 100, 100);
        // p.endShape();

    };


};


var myp5 = new p5(sketch);

```

**Comment by indefinit** [comment]
Sorry for the delay on this.  I found the bug but the fix is part of a larger upcoming refactor.  Will keep you posted.

**Comment by Diex** [comment]
nice !

**Comment by indefinit** [comment]
closing this issue since ambientLight is known to be working.  The issue has to do with a future full featured implementation of line() which will come in the next round of updates to webgl.  Feel free to reopen at a later time.  Thanks!
