### ISSUE TITLE
Clarify contributing to website and hello.p5?

### ISSUE THREAD

**Issue by peteruithoven** [processing/p5.js#1011]
I had a hard time finding the repo for the [hello.p5](https://github.com/scottgarner/p5.js-video) website and can't find the repo for the p5js.org website, could links to these repo's be added to pages like the [Development page](https://github.com/processing/p5.js/wiki/Development)?

**Comment by limzykenneth** [comment]
Hi, the p5js.org website repo is available here: https://github.com/processing/p5.js-website it is just under the processing group which is the same as this p5.js repo.

**Comment by lmccart** [comment]
thanks @peteruithoven, I just added a "repositories" section to the dev page. please let me know if any of this needs further clarification, or feel free to make small edits as you see fit.
https://github.com/processing/p5.js/wiki/Development#repositories
