### ISSUE TITLE
parent() / child() and '#'

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js#1014]
The question came up in class today as to why one says:

```javascript
select('#id');
```

but only:

```javascript
element.parent('id');
```

I explained (correctly?) that you can only `parent()` or `child()` with an `id` so the `#` is assumed.  Whereas you can `select()` an `id`, `class` or `tag`.  My questions are:

1. Is that correct?
2. Should we support both?

```javascript
element.parent('id');
element.parent('#id');
```

**Comment by lmccart** [comment]
yes, that is correct explanation. it does seem weird though, let's support both.

**Comment by limzykenneth** [comment]
Just a question, any reason why `parent()` `child()` only works with id? Can it be extended to work like `select()`? Coming from a jQuery background I'm used to having these taken care of for me so I'm terribly not familiar with native JS selector. :P

**Comment by lmccart** [comment]
I'm not sure I understand. Is this an example of something you're imagining?

```html
<body>
<div class='apples'></div>
<div class='apples'></div>
</body>
```
```javascript
function setup() {
  var c = createCanvas(100, 100);
  c.parent('.apples');
}
```

wouldn't this cause confusion about which div to append to? currently, we only support ID because you would only be able to append an element to one parent.

**Comment by futuremarc** [comment]
I guess it's a bit confusing, might as well support it

**Comment by limzykenneth** [comment]
I was thinking maybe it would select all instance of class `.apples` and either somehow iterate through them or (perhaps a very bad idea) append to all of them. However, I agree that might make it confusing. Just thinking about how to use `.child()` or `parent()` to iterate through a larger number of elements without having unique id for all of them.
