### ISSUE TITLE
Preload function in different sketches

### ISSUE THREAD

**Issue by mjanssen** [processing/p5.js#1018]
We're trying to create multiple sketches (based on https://github.com/processing/p5.js/wiki/p5.js-overview#instantiation--namespace). Preloading audio files does return the error `loadSound is not a function`.

The setup is as follows:

```
this.initSketch = function ()
    {
        var p5sketch = function (s)
        {
            s.sounds = [];

            s.preload = function ()
            {
                if (typeof sounds != 'undefined' && sounds.length > 0) {
                    for (var i = 0; i < sounds.length; i++) {
                        s.sounds[i] = loadSound(sounds[i]);
                    }
                }
            };

            s.setup = function ()
            {
                canvas = createGraphics($(parent).width(), $(parent).height());
            };

            s.draw = function ()
            {

            };
        };

        sketch = new p5(p5sketch);
    };
```

The setup function is initialized before all sounds are loaded (getting a buffer error when playing a sound in the setup()).

Is it even possible to have different preload function within different sketches? This would be a handy feature :)

**Comment by lmccart** [comment]
you will need to say s.loadSound() and make sure the p5.sound.js library is included in your project.

**Comment by mjanssen** [comment]
Oh wow, that solved it! Thank you!
