### ISSUE TITLE
Scrubbing video

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js#1020]
I'm trying again from #1019 (here's some advice to myself -- read the reference before filing an issue!).

I'm trying to create a "video scrubbing" example and am running into some issues.  I'm not sure if this is a p5.js specific issue of an HTML5 media element issue, I will continue to investigate.   `p5.MediaElement` cannot seem to keep up with this:

``` javascript
var fingers;

function setup() {
  noCanvas();
  fingers = createVideo('fingers.mov');
}

function draw() {
  if (fingers.duration()) {
    var t = map(mouseX, 0, width, 0, fingers.duration());
    fingers.time(t);
  }
}
```

Certainly I could turn on the controls, but I was looking to show how to control this with a variable.  Is this a bug or a limitation of HTML5 video?

**Comment by lmccart** [comment]
looking at the code, I can't see anything that seems wrong with the `time()` method, we're just setting the `currentTime` property of the underlying HTMLMediaElement (https://github.com/processing/p5.js/blob/master/lib/addons/p5.dom.js#L1497).

there is some seek time involved with jumping to a time, you can actually track the parameter "seeking" to see if it is in the process of seeking. [this demo page](http://www.w3.org/2010/05/video/mediaevents.html) might give you a sense of this delay as well. as far as I can tell though, this is not a bug with the library.

**Comment by shiffman** [comment]
Yes, I see what you mean.  That page is super helpful.  I think there may be an issue with attempting to scrub to points that haven't "loaded" yet.  I believe I could maybe add some more checks to an example.  I'll leave this open and self-assign to examine further, but agree there isn't a "bug" here with p5.

**Comment by DarkPrince304** [comment]
Do you plan to add a scrubbing feature to any video element that is added to the canvas using the `createVideo()` function?

So that whenever a user creates a `video` using `createVideo()` then a scrubbing feature will already be there in it?

**Comment by shiffman** [comment]
Here is an example that I am using to test:

https://github.com/processing/p5.js/pull/1082

The idea is for this to work more smoothly, currently it's a bit jerky and I'm not able to smoothly scrub.  Again, this is likely due to how HTMLMediaElement works and not a p5 bug.  Some clues for now to better handle/think about this are [may be found here](http://www.w3.org/2010/05/video/mediaevents.html).

**Comment by SetupandDraw** [comment]
Hi there! I have a question regarding Video DOM element in P5JS:
is it possible to use Video DOM buffered property in #P5js? 

Let's say for example I want to jump to a random frame of my video and play it; 
If I could have 100% of the video immediately loaded, no problem... I would go:

var randomF = floor(random(0, myVideo.duration()));
myVideo.time(randomF);

But myVideo could be still loading and so I need to jump only in the range of frames I am sure are already loaded.
Using buffered.start(0), buffered.end(0) seems to make sense but... I fear it is not possible in P5JS (yet). Am I wrong?

Thank you very much!﻿

**Comment by mwylegly** [comment]
I've noticed that video elements don't provide a duration unless the video has started playing. I'm trying to build a custom seekbar, but without being able to get the video duration beforehand it's creating some issues with mapping values.

Any solutions or workarounds to this?

**Comment by lmccart** [comment]
@shiffman where are we on this one? is it ok to close this or are you still noticing problems?

**Comment by shiffman** [comment]
I've looked into this a bit more. It's actually working quite a bit better than it did originally. (There is also a major mistake in my example code in that with `noCanvas()` the `width` parameter is nonsensical.) Testing it again with a slider, it mostly works but has some stuttering / performance problems. As far as I can tell, however, these are not p5 issues but rather just the result of trying to set `currentTime` of an `HTMLMediaElement` over and over again. Ultimately there's probably a more elegant way to implement scrubbing that someone else will come along and show me someday. But yes, closing!
