### ISSUE TITLE
capture, size(), and loadPixels()

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js#1022]
I'm working on some examples that use the following idea:

1. Open a capture with `createCapture(VIDEO);`
2. Size that capture down to lower resolution with `size()`.
3. Examine the pixels at that lower resolution.

It looks like to me that the current behavior of `p5.MediaElement` is to only change the DOM element size with `size()` and that the underlying canvas that is used with `loadPixels()` stays at the original size.  I propose changing the underlying canvas to match the `size()` arguments as this I think is more intuitive (as well as useful for performance with various "video mirror" examples.)

**Comment by shiffman** [comment]
I'm working on some examples that use the following idea:

1. Open a capture with `createCapture(VIDEO);`
2. Size that capture down to lower resolution with `size()`.
3. Examine the pixels at that lower resolution.

It looks like to me that the current behavior of `p5.MediaElement` is to only change the DOM element size with `size()` and that the underlying canvas that is used with `loadPixels()` stays at the original size.  I propose changing the underlying canvas to match the `size()` arguments as this I think is more intuitive (as well as useful for performance with various "video mirror" examples.)

**Comment by shiffman** [comment]
I've looked into this a bit more and pinpointed that this can be fixed by changing the following:

https://github.com/processing/p5.js/blob/master/lib/addons/p5.dom.js#L1513

```javascript
        this.canvas.width = this.width;
        this.canvas.height = this.height;
```

to:

```javascript
        this.canvas.width = this.elt.clientWidth;
        this.canvas.height = this.elt.clientHeight;
```

@lmccart shall I got ahead and implement this?

**Comment by lmccart** [comment]
yes that'd be great!

**Comment by lmccart** [comment]
closed with https://github.com/processing/p5.js/pull/1033
