### ISSUE TITLE
p5.MediaElement and rate/speed

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js#1026]
I don't see functionality to adjust the rate or speed of playback in `p5.MediaElement`.  (This came up in class today when looking at video files.)  Is this something we can easily add and/or is there a reason not to?

**Comment by DarkPrince304** [comment]
I guess the todo here would be to just access the `video.elt.playbackRate` and set it accordingly. I would like to work on it if you could tell me how do you want its implementation to be done?

**Comment by shiffman** [comment]
Ideally I'd like to mirror this functionality (if possible).

https://www.processing.org/reference/libraries/video/Movie_speed_.html

If this does not make sense in the web context, however, I am open to other ideas.

**Comment by DarkPrince304** [comment]
This would be nice too. But I was thinking what if the user needs to change the playback speed while watching the video. What do you think of a speed button similar to the play button?

**Comment by PaliwalSparsh** [comment]
@shiffman @lmccart The pushed PR adds functionality to adjust speed of playback, also I have added a manual-test-example as video_speed. Please review and provide feedback.
