### ISSUE TITLE
dist() and 3D coordinates

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js#1028]
Now that we have `WEBGL` support I think that `dist()` should be expanding to accomodate 3D coordinates, i.e.

```javascript
dist(x1, y1, x2, y2);
dist(x1, y1, z1, x2, y2, z2);
```

This is also particularly useful for comparing RGB colors.

I'm happy to submit a pull request for this feature assuming everyone agrees.

**Comment by lmccart** [comment]
sounds great

**Comment by indefinit** [comment]
Thanks for this!
