### ISSUE TITLE
lerpColor in colorMode(HSB)

### ISSUE THREAD

**Issue by b-g** [processing/p5.js#1029]
lerpColor() in colorMode(HSB) produces unexpected results. 

Output p5.js (note the black rects in the 2nd row):
![screen shot 2015-10-22 at 13 11 23](https://cloud.githubusercontent.com/assets/480224/10663904/7725ae68-78bf-11e5-8457-22ff52c5294b.png)

Output processing 3:
![screen shot 2015-10-22 at 13 20 46](https://cloud.githubusercontent.com/assets/480224/10663959/bba7aee2-78bf-11e5-89ee-f373f7ad8b8e.png)

Here is an example to reproduce:

```javascript
stroke(255);
background(51);
colorMode(HSB);
from = color(0, 100, 100);
to = color(180, 100, 100);

colorMode(RGB);
interA = lerpColor(from, to, .33);
interB = lerpColor(from, to, .66);
colorMode(HSB);

fill(from);
rect(10, 20, 20, 30);
fill(interA);
rect(30, 20, 20, 30);
fill(interB);
rect(50, 20, 20, 30);
fill(to);
rect(70, 20, 20, 30);

interA = lerpColor(from, to, .33);
interB = lerpColor(from, to, .66);

fill(from);
rect(10, 20+40, 20, 30);
fill(interA);
rect(30, 20+40, 20, 30);
fill(interB);
rect(50, 20+40, 20, 30);
fill(to);
rect(70, 20+40, 20, 30);
```

**Comment by joecridge** [comment]
I’ll take a look at this in the next day or two.

**Comment by lmccart** [comment]
great, thanks!

**Comment by joecridge** [comment]
The [documentation](http://p5js.org/reference/#/p5/lerpColor) for `lerpColor()` implies that interpolation is always done in the RGBA space. Should I change the documentation to match Processing 3, or the implementation to match the documentation (ie make `lerpColor()` `colorMode()` independent)?

**Comment by b-g** [comment]
@joecridge, Many thanks for chasing this up!

I personally don't see a point why lerpColor() should just be used in RGBA space. Interpolating through HSB space is often handy to generate "rainbow color palettes" (think of heatmaps). IMO users coming from Processing will expect that lerpColor() delivers the same results, also in HSB space. BTW the [Processing lerpColor()](https://processing.org/reference/lerpColor_.html) docs don't mention the RGBA color space limitation.

Hence I would vote for making the behavior similar/identical to Processing and to soften "lerpColor first transforms colors into the linear color space before blending, to correctly mix the colors as two rays of light"

**Comment by joecridge** [comment]
That makes sense to me.

**Comment by lmccart** [comment]
I recall some discussion of this from the conference this summer. @sarahgp I believe you worked on this and I thought I remembered you had a good reason why it converts to RGB first, can you elaborate?

**Comment by joecridge** [comment]
I think the code has been changed since the documentation was written because there currently is no conversion to RGB or gamma correction in the implementation.

**Comment by lmccart** [comment]
ah ok, then I think it makes sense to match Processing 3 and update the documentation. and to look into a fix to correctly reproduce results from Processing 3 in HSB mode.

**Comment by joecridge** [comment]
Okay :). The HSB issue is caused by assuming the internal RGB values are still 0-255 after the utility functions have converted them (which actually makes them 0-1). It looks like a few of the colour functions make assumptions like that (and don't take into account custom maximums either) so I'm currently passing through the whole module to make everything consistent.

**Comment by b-g** [comment]
Great! 👍

**Comment by sarahgp** [comment]
Everything was converting to RGB because that value was necessary to pass to the canvas element. When @xyfeng updated the color conversion, he normalized everything from 0 to 1, so I imagine this bug is now an artifact of that change. All of which is to say, this update appears to be on the right track. :smile_cat:

**Comment by xyfeng** [comment]
@joecridge Thanks so much for tidying up and fixing my messy code. When I added the HSB support for lerpColor, I haven't normalized everything from 0 to 1. After I refactor the color classes and adding testing units, I totally forgot about the normalization will affect lerpColor. 

Anyway, all your changes look great, make sense to me. One small thing, when you rename the file name from 'color_utils' to 'color_conversion', you might want to double check with @lmccart & @sarahgp. 

@b-g, I'm a big fan of your book!

**Comment by joecridge** [comment]
No worries, I actually found it really interesting to work through :smiley:. Yeah I didn’t really think about that, I’ve made a note of it in the pull request.
