### ISSUE TITLE
class() vs. addClass()

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js#1031]
I am having a deja vu moment here.  So apologies in advance if we already had this conversation. (I search old issues and read the reference this time!)   If I'm right the current behavior in p5.dom is as follows:

```javascript
elt.class('apple');       // add the class "apple"
elt.addClass('apple');    // add the class "apple"
elt.removeClass('apple'); // removes the class "apple"
```

At the moment `class()` and `addClass()` are doing the same thing.  I am wondering if the `class()` function should wipe the existing classes and make that element a member of only what is passed in.

I have a feeling there are good reasons why this is a terrible idea.  However, I created an example the other day where I toggled an element between the two classes and I got tripped up on `class()` vs. `addClass()`.

Thoughts?

**Comment by lmccart** [comment]
this makes sense to me, I don't think there was a good reason for this except that it was created before we had addClass, so it was more often the case that you'd want to add a class vs overwrite.
but I agree now it makes sense to change the behavior to just set (overwrite) the class, I'll make this change.
