### ISSUE TITLE
loadPixels() failing on DOM elements if the element is hidden

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js#1034]
For example, this works:

```javascript
var capture;

function setup() {
  createCanvas(320, 240);
  capture = createCapture(VIDEO);
}

function draw() {
  capture.loadPixels();
}
```

But this produces an error:

```javascript
var capture;

function setup() {
  createCanvas(320, 240);
  capture = createCapture(VIDEO);
  capture.hide(); // breaks loadPixels()!
}

function draw() {
  capture.loadPixels();
}
```

<img width="676" alt="screen shot 2015-10-23 at 8 22 36 pm" src="https://cloud.githubusercontent.com/assets/191758/10707662/d7c5d0cc-79c3-11e5-8556-47bd2b299711.png">

Happy to investigate this.

**Comment by lmccart** [comment]
hm I'm not able to reproduce, can you confirm this breaks with the most recent src code in the repo?

**Comment by shiffman** [comment]
Hmmm, weird, yes I am still seeing this issue and just pulled and rebuilt the lib.  Let me try on a different machine tomorrow.

**Comment by toolness** [comment]
For what it's worth, I'm able to reproduce this error on Chrome 48.0.2550.0 canary (64-bit) on Windows 10, as of the current master (3e3ba6beae711afaac847f420bfcc1230b16fc6c).
