### ISSUE TITLE
Enable draw(); on trigger

### ISSUE THREAD

**Issue by mjanssen** [processing/p5.js#1037]
Is it possible, when creating a new sketch with the following code:

```
var campaignSketch = function (s) { ... }
new p5(campaignSketch);
```

to enable the draw function when something happened (user clicked on something e.g.). Currently there is a noLoop(); function which disables drawing, but still loops trough it one single time, which is causing problems within our application. We could work with an s.shouldDraw property, but is there an other 'cleaner' way to fix this?

Thanks :)

**Comment by lmccart** [comment]
I would create a boolean variable that wraps what is inside draw, then set that to true when you want to run draw. In general, this kind of question is better for the forum, the github issues are the place to post bugs found in the library. http://forum.processing.org/two/categories/p5-js

var doDraw = false;

function draw() {
  if (doDraw) {
    // do stuff
  }
}
