### ISSUE TITLE
p5.Renderer2D.get() partially handles overlapping and does not handle cropping

### ISSUE THREAD

**Issue by Ucodia** [processing/p5.js#1038]
There is 2 aspects to this issue but they are both tightly related, therefore I open a single issue for this.

* First of all there is an inconsistency on how `get(x, y, w, h)` lets you select a portion of the canvas.

In the case that the capture top/left coordinate (x/y) is inside the canvas but area overflows outside the right or bottom side, a non cropped `p5.Image` is returned. That is somewhat expected.

![overlap2](https://cloud.githubusercontent.com/assets/1795860/10748803/0d8f640a-7c64-11e5-8a43-23d54c378306.png)

But in the case the capture  top/left coordinate is outside the canvas, no `p5.Image` is returned at all. Instead it returns `[0, 0, 0, 255]`, which is inconsistent with the previous case.

![overlap1](https://cloud.githubusercontent.com/assets/1795860/10748858/88a823ac-7c64-11e5-8a63-4e3898724cf4.png)

* Second aspect is that `get(x, y, w, h)` return a portion of screen that does not exists if the selected section overflows outside the canvas because there is no cropping in place.

In the case of an overflow on the left/top or the right/bottom, no cropping is currently applied and a set of transparent pixels is returned in place of the non existent area. I propose that this non existent area should be cropped off the returned Image.

![crop1](https://cloud.githubusercontent.com/assets/1795860/10748947/557d8638-7c65-11e5-9a07-a404a9b1fe18.png) ![crop2](https://cloud.githubusercontent.com/assets/1795860/10748949/5805b196-7c65-11e5-9994-51450aab841d.png)

**Comment by Ucodia** [comment]
I realized that it is probably a bad idea to actually crop the area. It is non intuitive to return an area of a different size than what the user asked for. I am gonna close the issue and rework for a better approach to the initial problem.

**Comment by limzykenneth** [comment]
I wonder if simply not allowing someone to select outside the canvas will be a good idea. So to implement will be just generating an friendly error message whenever someone tried to select outside the canvas. Thinking out loud here, maybe we could use your solution but generate a message to warn user of the different sizes.

**Comment by Ucodia** [comment]
Sorry @limzykenneth I did close this issue early because I realized that cropping did not make much sense. Therefore I reworked the issue with a different and simpler approach: https://github.com/processing/p5.js/issues/1040. Let's move the discussion there.
