### ISSUE TITLE
p5.Renderer2D.get() not working with bounds outside the top or left side of canvas

### ISSUE THREAD

**Issue by Ucodia** [processing/p5.js#1040]
Currently when we use `get(x, y, w, h)` to select a `p5.Image` that overlaps the canvas but has bounds outside the canvas, the selection is not treated consistently whether the bounds is outside the top/left sides or the bottom/right sides.

For example if we try to select this portion
![overlap2](https://cloud.githubusercontent.com/assets/1795860/10758817/fe3ce8ba-7cb3-11e5-9f88-9c3e2930db7d.png)
We are returned a `p5.Image` with transparent pixels for those that are outside the canvas. That is expected behavior.

But if we try to select this portion
![overlap1](https://cloud.githubusercontent.com/assets/1795860/10758819/0210a5f8-7cb4-11e5-9338-ff97624c66f6.png)
We are returned a single transparent pixel `[0, 0, 0, 255]`. This is not the expected behavior and inconsistent with the previous case.

I think that the return of the transparent pixel `[0, 0, 0, 255]` should only occur if the selection does not overlap at all with the canvas.

**Comment by lmccart** [comment]
fixed with https://github.com/processing/p5.js/pull/1041
