### ISSUE TITLE
mouseIsPressed returns true after release

### ISSUE THREAD

**Issue by antiboredom** [processing/p5.js#1042]
mouseIsPressed will continue to return true if the user has clicked and dragged over an image.

```
var img;

function setup() {
  createCanvas(800, 800);
  img = createImg('someimage.jpg');
}

function draw() {

  if (mouseIsPressed) {
    print('pressed')
  } else {
    print('not pressed')
  }
}
```

**Comment by lmccart** [comment]
I guess the fix is to add listeners for 'dragover' and 'dragleave' to fire the same events as 'mousemoved' and 'mouseup'
http://stackoverflow.com/questions/10103298/detecting-the-current-state-of-a-mouse-in-javascript-or-jquery-i-e-wheather-its
