### ISSUE TITLE
Sketches in 0.4.17 running much slower than 0.4.9 when using images

### ISSUE THREAD

**Issue by golanlevin** [processing/p5.js#1048]
Sketches linked to 0.4.17 run much slower (like 100x slower) in the browser when loading/displaying images, compared to performance in 0.4.9.

**Comment by Jared-Sprague** [comment]
There have been a lot of releases since 0.4.9.  Can you narrow it down to which release caused the performance drop?

**Comment by golanlevin** [comment]
Reasonable request. That will take a bit of testing, I'll get to it this weekend. 
Thanks!

**Comment by lmccart** [comment]
hi @golanlevin, if you can post some simple sample code that illustrates the issue when switching p5 versions, I can have a look.

**Comment by golanlevin** [comment]
Yes, have been traveling and meaning to do this, sorry for the delay...

**Comment by lmccart** [comment]
hi @golanlevin, I'm going to close this issue as it may be a little confusing for people to know how to proceed with this one until the sample code is posted. please feel free to reopen whenever you have this code handy. no need to track down the exact version that broke things, I can figure it out, with a test sketch to compare against.
