### ISSUE TITLE
p5.js

### ISSUE THREAD

**Issue by xesign** [processing/p5.js#1057]
hello. how can assign a slider for example to change the value of a variable?
so that the user can change for example the direction or speed of an ellipse?
thank you

**Comment by limzykenneth** [comment]
I don't have a short answer for that but I'll direct you to [a tutorial](https://www.youtube.com/watch?v=ZEy0_NLhdSE) by Daniel @shiffman himself explaining what might be useful for you. Do check out the previous videos if that one seems a bit confusing.

Ultimately, I think this is a question for the [forum](https://forum.processing.org/two/categories/p5-js). The github issue tracker is more of a place for bug reporting etc. If you have further question do post it there and I'm sure you'll get help there as well.

Hope that helps. Cheers.

**Comment by limzykenneth** [comment]
I don't have a short answer for that but I'll direct you to [a tutorial](https://www.youtube.com/watch?v=ZEy0_NLhdSE) by Daniel @shiffman himself explaining what might be useful for you. Do check out the previous videos if that one seems a bit confusing.

Ultimately, I think this is a question for the [forum](https://forum.processing.org/two/categories/p5-js). The github issue tracker is more of a place for bug reporting etc. If you have further question do post it there and I'm sure you'll get help there as well.

Hope that helps. Cheers.

**Comment by lmccart** [comment]
thanks @limzykenneth!
