### ISSUE TITLE
Fill specified after drawing commands is ignored.

### ISSUE THREAD

**Issue by dhowe** [processing/p5.js#1058]
Appears a fill() specified after drawing commands in draw() is ignored. Example below (v0.4.17)...

````js
    function setup() {
      createCanvas(400, 400);
    }

    function draw() {
        background(230);
        ellipse(200, 200, 100, 100);
        fill(200, 0, 0);
    }
````
p5js:
![screen shot 2015-11-01 at 7 18 14 pm](https://cloud.githubusercontent.com/assets/737638/10868602/5fafab74-80cd-11e5-88a1-001a050885db.png)

Processing:
![screen shot 2015-11-01 at 7 16 06 pm](https://cloud.githubusercontent.com/assets/737638/10868599/5978b2b4-80cd-11e5-9f77-aaef7821aef0.png)

**Comment by lmccart** [comment]
ah yes, so here's what's happening with this one.
in processing, the matrix is reset at the end of draw, so transformations don't accumulate over draw calls. essentially it's the equivalent of `push/popMatrix()` wrapping draw.

in p5.js there's not a separation of `push/popMatrix()` and `push/popStyle()`, there's just `push/pop()`. so the draw loop is wrapped in `push/pop()` and the fill and other properties are getting reset. I think the change to be made is to not use the push/pop calls and just to manually reset the matrix of the canvas at the end of draw. I can work on a fix for this.

**Comment by lmccart** [comment]
@indefinit I tried to make this change, because in 2D mode push()/pop() affects both transform and style, and we only want to reset transform after the draw loop. however, this turned out to be a breaking change for WEBGL mode (sorry! will post a fixed v0.4.19 soon). when you have a chance, can you take a look? I believe resetMatrix() should just reset the matrix, while push()/pop() should reset both matrix and style. https://github.com/processing/p5.js/commit/a8f9bb0beb091a7d86c9d988ca7e893363b8d7cd

**Comment by debone** [comment]
I have a maybe related issue with text, fill and push/pop

If there is no fill initially, the push/pop behave strangely to texts

```javascript
function setup() {
  background(215);

  // Normal black filled text
  text("black",50,25);
  rect(0,0,25,25);

  //Pushing state
  push();
    fill(255,0,0);  
    text("red",50,50);
    rect(0,25,25,25);
  pop();

  // Should be black again, but something is lost
  text("black",50,75);
  rect(0,50,25,25);
}
´´´

Result
![image](https://cloud.githubusercontent.com/assets/763457/14210150/1e96aebe-f7fe-11e5-9daa-f88109bba0d1.png)

**Comment by lmccart** [comment]
Thanks. This has been fixed in the latest version of the library, expect to see it in the next release of the library and the editor. :)

**Comment by lmccart** [comment]
Oops didn't mean to close the whole issue, first part still needs a fix.

**Comment by cpirich** [comment]
This fix appears to have a bug, because the call to `this.resetMatrix.bind(this);` doesn't actually call `resetMatrix`, but simply binds `resetMatrix` without storing the return value or calling the function.
