### ISSUE TITLE
Examples - p5.js not included in /lib

### ISSUE THREAD

**Issue by alijaffar** [processing/p5.js#1060]
I added p5.js and it resolved this issue for me, when I was going through the demos. I think it may help others who are new to p5 also. Awesome work, guys.

**Comment by lmccart** [comment]
the examples in the repo are intended only for testing, as a complement to the automated unit tests. examples for learning are posted herep5js.org/examples/.

**Comment by lmccart** [comment]
this makes me think, perhaps we should move this examples folder inside the test/ directory, to reduce confusion. will make this change on the next push.

**Comment by alijaffar** [comment]
Good thinking, thanks for the clarity.
