### ISSUE TITLE
Unit test suite for p5.dom?

### ISSUE THREAD

**Issue by toolness** [processing/p5.js#1061]
While working on #1047 and #1049 I noticed that there don't seem to be any unit tests for p5.dom--am I correct, or did I miss it somewhere?

If there is indeed no test suite for p5.dom, would you accept a PR for one?

**Comment by lmccart** [comment]
hi @toolness, yes, we would definitely accept one! there are guidelines here on how to add tests: https://github.com/processing/p5.js/wiki/Development#testing
