### ISSUE TITLE
Background Alpha value broken for WEBGL canvas

### ISSUE THREAD

**Issue by camerenisonfire** [processing/p5.js#1064]
I am currently using p5.js v0.4.17

```javascript
function setup()
{
    createCanvas(windowWidth,windowHeight, WEBGL);
}

function draw() {
    background(0,0,0,0);
}
```
Just makes a black background. Adjusting the alpha value for background has no effect with WEBGL is enabled. This is not an issue when WEBGL is not enabled. 

I need to make the canvas transparent as it is over-layed on top of another element. Is there some other way to achieve a clear canvas with WEBGL on?

**Comment by indefinit** [comment]
Thanks for this.  Found the bug.  Renderer3D was defaulting to alpha: false.  Setting this to true enables the alpha value in glClear.  I have a quick patch I'm submitting now.
