### ISSUE TITLE
usable delay() function in p5

### ISSUE THREAD

**Issue by sunwangshu** [processing/p5.js#1068]
I found this piece of code here: http://stackoverflow.com/a/24488671/4539578

It worked all fine in my p5 sketch, and since I use Arduino a lot, I find this delay() function really in need whenever I think about animation and so on.

function delay(ms) {
    var cur_d = new Date();
    var cur_ticks = cur_d.getTime();
    var ms_passed = 0;
    while(ms_passed < ms) {
        var d = new Date();  // Possible memory leak?
        var ticks = d.getTime();
        ms_passed = ticks - cur_ticks;
        // d = null;  // Prevent memory leak?
    }
}

**Comment by limzykenneth** [comment]
I'm not sure if having a built in blocking delay function would be necessary for the API, kinda defeat the purpose of asynchronicity in javascript. For arduino there is the p5bots library which in turn uses Firmata (I feel that is itself a bit troublesome to set up though). I'm not sure how you will be using the `delay()` function so I might be wrong. ; )

**Comment by lmccart** [comment]
hey @sunwangshu I image this could be helpful in some cases. in others, as @limzykenneth mentions, it might be preferable to follow the patterns of javascript. I'd suggest posting it in the [forum](forum.processing.org/two/categories/p5-js) in case others are searching for something similar. thanks again for posting!

**Comment by sunwangshu** [comment]
Got that. Thanks!
