### ISSUE TITLE
Unit tests fail on non-PhantomJS browsers

### ISSUE THREAD

**Issue by toolness** [processing/p5.js#1070]
The [Running tests in the browser](https://github.com/processing/p5.js/wiki/Development#running-tests-in-the-browser) section of the development guide seems to imply that unit tests should work out-of-the-box, but I'm finding on 9f2d6e01724c48c8166c73368855c303a47e7834 that:

* Chrome 46.0.2490.80, Opera, and IE Edge fail on the same 3 tests
* Safar 9.0.1 fails the same tests as Chrome/Opera/IE but also fails an additional one
* Firefox 41.0.2 **only runs 20 tests** instead of 289, and fails 4 of them

Particularly as the [DOM test suite](https://github.com/processing/p5.js/issues/1061) and other suites for which browser idiosyncrasies come into play, it seems like it will be useful to have the tests pass on more than PhantomJS in the future (integrating Travis jobs with [Sauce Labs](http://saucelabs.com/) or a similar service would be awesome!).

I'm interested in fixing these tests but don't want to step on any toes... Let me know if you want me to take a closer look!

**Comment by lmccart** [comment]
please go for it!
