### ISSUE TITLE
WEBGL mode beginShape() - only works with 3 vertices

### ISSUE THREAD

**Issue by pbogdan03** [processing/p5.js#1071]

**Comment by lmccart** [comment]
@pbogdan03 can you elaborate a bit? could you include a bit of sample code that illustrates the issue?

**Comment by pbogdan03** [comment]
Hello @lmccart, 

It's simply the function beginShape() in 

```
function setup() {
  createCanvas(400, 400, WEBGL);
}

function draw() {
  background(0, 0, 0);
  fill(255);

  beginShape();
      vertex(0, 0, 0);
      vertex(50, 0, 0);
      vertex(50, 50, 0);
      vertex(0, 50, 0);
      endShape(CLOSE);
}
```
doesn't display a square, it stops after the first 3 vertices and displays a triangle.

Any insight?

**Comment by indefinit** [comment]
@pbogdan03 does this code work?

```
function setup() {
  createCanvas(400, 400, WEBGL);
}

function draw() {
  background(0, 0, 0);
  fill(255);

  beginShape(TRIANGLE_STRIP);
  vertex(0, 0, 0);
  vertex(50, 0, 0);
  vertex(50, 50, 0);
  vertex(0, 50, 0);
  endShape(CLOSE);
}
```

The default webgl mode of beginShape is TRIANGLES so it needs multiples of 3 vertices to produce an accurate shape.  I'm currently working on a geometry primitives refactor which will clear up some of the issues around 2D drawing in webgl.

**Comment by pbogdan03** [comment]
Hi @indefinit,
No, it doesn't seem to work, still renders only the first 3 vertices, I've tried using 6 vertices but still the same problem occurs.

**Comment by indefinit** [comment]
Ah ok, I found the problem.  The bug has to do with the webgl primitives constants TRIANGLES and TRIANGLE_STRIP, not mapping properly in a switch case statement, which is problematic on this line in the p5.js src:  https://github.com/processing/p5.js/blob/d1a42f56ee51a92946ec97d7d1aec110c782dfec/src/3d/immediateMode3D.js#L102

Will work on the patch later today.

**Comment by parsoyaarihant** [comment]
I guess they have made it this way because in 3D, if all the vertices are not in the same plane then it will be a problem to render. Hence, the default shape is Triangle. We can improve this mode by making sure that all the vertices lie in a plane.
