### ISSUE TITLE
Array / Object / Json

### ISSUE THREAD

**Issue by fredericpierron** [processing/p5.js#1072]
Object in array can not be accessed.

```Javascript
var reserve;

function preload() {
  var fichier = '2014_reserve.json';
  reserve = loadJSON(fichier, fichierOK);
}

function setup() {
  createCanvas(500, 500);
  var test = reserve.length;
}

function draw() {
  background(200);
  

}

function fichierOK() {
  println("Le fichier est chargé");
  background(255);
  
  var depenseTotale = 0;
  
  for (i=0; i<=reserve.length; i++){
    depense = reserve[i]["Montant"];
    depenseTotale += depense;
  }

}
````
Here's the Json

```json
[
  {
    "Bénéficiaire":"Télé Bocal",
    "Adresse":"Maison des associations\n1/3 rue Frédérique Lemaître\n75020 Paris",
    "Descriptif":"Mise en œuvre d'ateliers de production locale proposant d’utiliser l'image comme une valorisation du travail des artistes",
    "Montant":5000,
    "Nom":"BAUPIN",
    "Prénom":"Denis",
    "Département":"Paris",
    "Groupe":"Ecolo",
    "Programme budgétaire":"313-03",
    "ID_Acteur":"PO609016"
  },
  {
    "Bénéficiaire":"Mieux se déplacer à Bicyclette",
    "Adresse":"MDB –\n37 boulevard Bourdon\n75004 Paris",
    "Descriptif":"Réalisation des supports de communication pour faire connaître ses nouvelles dispositions sur l'usage de la bicyclette et diffusion",
    "Montant":4000,
    "Nom":"BAUPIN",
    "Prénom":"Denis",
    "Département":"Paris",
    "Groupe":"Ecolo",
    "Programme budgétaire":"203-15",
    "ID_Acteur":"PO609016"
  }
]
```

The problem is here:
```Javascript
  for (i=0; i<=reserve.length; i++){
    depense = reserve[i]["Montant"];
    depenseTotale += depense;
  }
````
It should be possible to access to any value of the object by using:
```Javascript
depense = reserve[i]["Montant"];
```
or 
```Javascript
depense=reserve[i].Montant;
````
In both cases, I get an error 
```
Uncaught TypeError: Cannot read property 'Montant' of undefined
```

**Comment by lmccart** [comment]
looking quickly, this line should probably be < instead of <=.
`for (i=0; i<=reserve.length; i++){`

code questions like these are better for the [forum](forum.processing.org/two/categories/p5-js), the github issues are just for bugs with the library.

**Comment by fredericpierron** [comment]
Ok, sorry, but why it does not raise an error as it goes further than the length value ? The error string that appears is not the right one (in my humble understanding). It should raise an "undefined" message, like in console.

**Comment by lmccart** [comment]
confusing, I know, but this is just the way that javascript behaves. and this is not p5 error reporting, but javascript itself. the clue is that it says "cannot read property 'montant' of undefined", telling you that the object you are trying to access the property montant of is undefined / nonexisting, so a starting place would be to go back and try to figure out why this is.

**Comment by fredericpierron** [comment]
Ok, I will try to think like a javascripted program ;)

**Comment by lmccart** [comment]
also, this tutorial might be helpful for more general strategies for debugging:
p5js.org/tutorials/debugging/
