### ISSUE TITLE
How to use preload() when writing an external library with async functions

### ISSUE THREAD

**Issue by bmoren** [processing/p5.js#1074]
I'm trying to write a function that can be used in preload() to return data without using a callback, similar to how loadJSON works.

for example:

```javascript
p5.prototype.getCoolData = function(callback){
  var ret = false;
  getExternalData(function(data){
    ret = data;
    if (typeof callback == 'function'){
      callback(data)
    }
  })
  return ret;
}

p5.prototype.registerPreloadMethod('getCoolData'); 
```

The above code will return `false` when used in preload() like this:

```javascript
var cool_data;
function preload(){
  cool_data = getCoolData();
}

function setup(){
  print(cool_data);
}
```

I was looking through the source code for p5 and couldn't understand how you are doing this with the `load` methods, like loadJSON and loadXML. I would like to replicate the style in the load methods of supporting both [preload & callback](http://p5js.org/reference/#/p5/loadJSON). Is there a simple example of setting up a function with async data to use either a callback or the preload() and a variable.

**Comment by lmccart** [comment]
i believe this has to do with the immutability of boolean vars. all of the load methods in p5 return an object that is later modified, so the pointer to the original object remains intact.
seems like the same issue is described here: https://github.com/processing/p5.js/issues/815#issuecomment-150131420.

this should be better documented, sorry.

**Comment by bmoren** [comment]
this worked! Its true, don't rewrite the data, just update it!

**Comment by bmoren** [comment]
```javascript
//example async function for use in preload() or with callback
p5.prototype.getData = function(callback){
  //create an object to hold some data. We will need to update this data below, not overwrite it. It is crucial to the preload() to keep the original pointer.
  var ret = {};

  //some async fucntion you are working with
  loadDataFromSpace(function(data){

    //loop through the properties in data
    for( prop in data){
      //set the ret proporties to be the data properties ( update the empty ret object with the properties from data )
      // you CANNOT overwrite ret with another object, it must be updated with the data.
      ret[prop] = data[prop];
    }
    //check if the callback is a function
    if (typeof callback == 'function'){
      //do the callback
      callback(data)
    }
  })
  //return the object which has been filled with data above
  return ret;
}
```

**Comment by bmoren** [comment]
Added example to the Libraries Wiki page

**Comment by lmccart** [comment]
thank you!

**Comment by dhowe** [comment]
Again, if we stick with this mechanism for preload we should make it very clear in the docs that NONE of the primitive types (boolean, string, or number) will work as return values for preload registered functions.
