### ISSUE TITLE
p5.DOM documentation: add reminder to include dom library

### ISSUE THREAD

**Issue by indefinit** [processing/p5.js#1075]
I always find myself falling for this, and am not sure if others do as well.  Is there a way we can remind users they must include the DOM library if they want to use DOM functions?  I know we have this written in the tutorials but it would be great if there could be 1 or 2 sentences on each docs page with something like this:

``` 
This function requires you include the p5.DOM library.  To include the p5.DOM library add:
<script language="javascript" type="text/javascript" src="path/to/p5.dom.js"></script>
in index.html
```

**Comment by toolness** [comment]
Good suggestion! I noticed #645 is about migrating p5.DOM into the core, though, so perhaps doing that sooner rather than later is another alternative?

**Comment by lmccart** [comment]
regarding #645 we've decided to hold off just a bit on that to make sure we give p5.dom the space to be experimental with the API... we will merge it in when we feel the API is a little more tested and stable.
in the meantime, I agree this documentation addition would be useful. I'm going to look into adding a task to the doc generation that automatically adds this so we don't have to manually add it for each entry.

**Comment by hellonearthis** [comment]
I see this reference to the p5.dom has been added to the top of the reference page.
Wouldn't it be better places at the https://p5js.org/reference/#group-DOM section.
If there a way to add to these groups to add this kind of reference information?
