### ISSUE TITLE
image.width and image.height gives same value for a rectangular image while making it as a texture for a plane

### ISSUE THREAD

**Issue by suhailsulu** [processing/p5.js#1078]

**Comment by lmccart** [comment]
thanks, could you a little sample code that illustrates the issue, for testing?

**Comment by suhailsulu** [comment]
var img;
function setup() {
	myCanvas = createCanvas(window.innerWidth,500,WEBGL);
	myCanvas.parent('canvas');
	img=loadImage('dog.jpg');
}

function draw(){
background(255);
texture(img);
//console.log(img.width + "   " +img.height);  // gives 512*512 as width and height
plane(img.width,img.height);
}

**Comment by limzykenneth** [comment]
Did you preload the image? You will need to do loadImage in `function preload()` as Javascript is asynchronous, when you call img.width and img.height the image isn't loaded in yet so it just gives you default value. I think that's what's happening anyway...

**Comment by suhailsulu** [comment]
when i logged the image width and height before the texture(img) method it gives the correct value. the value changes after the call of texture(img) and then in the further loops the value is wrong... 
its my new edited code

var img;
function preload(){
img=loadImage('dog.jpg');
}
function setup() {
myCanvas = createCanvas(window.innerWidth,500,WEBGL);
myCanvas.parent('canvas');


}

function draw(){

background(255);
console.log(img.width + " " +img.height);
texture(img);
console.log(img.width + " " +img.height); // gives 512*512 as width and height
plane(img.width,img.height);
}



the output is 
![screenshot from 2015-11-11 17 45 39](https://cloud.githubusercontent.com/assets/15671227/11090930/354db34a-889c-11e5-80de-af3795304ee0.png)

**Comment by lmccart** [comment]
I'm not able to reproduce, could you please include a link to the image file you're using, and confirm you're using v0.4.18?

**Comment by suhailsulu** [comment]
/*    sketch.js file    */

var img;
function preload(){
img=loadImage('dog.jpg');
}
function setup() {
myCanvas = createCanvas(window.innerWidth,500,WEBGL);
myCanvas.parent('canvas');


}

function draw(){

background(255);
console.log(img.width + " " +img.height);
texture(img);
console.log(img.width + " " +img.height); // gives 512*512 as width and height
plane(img.width,img.height);
}



the image   
![dog](https://cloud.githubusercontent.com/assets/15671227/11091185/082c518a-889e-11e5-87cf-34a4f7028726.jpg)

**Comment by suhailsulu** [comment]
I have used version 17 and 18

**Comment by lmccart** [comment]
this is printing 497x330 for me on chrome, safari, and firefox on macbook pro. maybe it is the device you're using, can you specify? is anyone else able to reproduce?

**Comment by suhailsulu** [comment]
i am using chrome 45.0.2454.101 on Ubuntu 15.04 (64-bit)

**Comment by limzykenneth** [comment]
chrome, safari, firefox on macbook osx 10.7, I'm not able to reproduce this, values logged are correct.

**Comment by suhailsulu** [comment]
in v.18 values are correct but its not rendering.. in version 17 values are wrong but its rendering

**Comment by limzykenneth** [comment]
Same as above, not rendering but values correct (I thought it was something wrong with my set up) XD

**Comment by limzykenneth** [comment]
I've tested all webgl primitives and all of them are rendering weirdly, this is what I get with the above code but with cylinder(200,200) instead of plane, others are similar as well:

![screen shot 2015-11-11 at 13 08 44](https://cloud.githubusercontent.com/assets/7543950/11091737/78404d06-8875-11e5-8967-c4d9551b47f1.png)

**Comment by lmccart** [comment]
yeah I was just noticing the same thing! will investigate. looks like the image loading width/height error is resolved though.

**Comment by lmccart** [comment]
found the error, will post a fixed version 0.4.19 soon, but images should now be reading correct dimensions and rendering as textures in latest patch.
