### ISSUE TITLE
Documentation on soundFormats browser support may be inaccurate

### ISSUE THREAD

**Issue by toolness** [processing/p5.js#1083]
The [soundFormats example page](http://p5js.org/examples/examples/Sound_soundFormats.php) opens with:

> There is no single sound format that is supported by all web browsers. For example, mp3 support is not native to Firefox and Opera because the mp3 codec is patented.

However, this doesn't actually seem to be the case any longer, [according to caniuse.com](http://caniuse.com/#feat=mp3). I confirmed this by removing the `'ogg'` argument from the call to `soundFormats()` in the example and everything still works on Firefox and Opera.

That said, the mp3 format *is* still patented in the US and some lesser-known browsers/linux distros might not support it... And it's certainly still the case that really old versions of Firefox/Opera don't support mp3.

That said, the sentence above might want to be reworded a bit to reflect the current reality. Perhaps it could even link to something like http://caniuse.com/#search=audio%20format so devs can easily make their own decisions about what formats to support.

**Comment by lmccart** [comment]
great suggestion. would you like to submit a pull request with this change? the examples text is contained in this repo: https://github.com/lmccart/p5.js-website in the folder /examples/examples_src

**Comment by toolness** [comment]
Sure, I will write something up and send a PR! Sorry I didn't file this one in the proper repo.

**Comment by lmccart** [comment]
thanks! and no worries :)
