### ISSUE TITLE
p5.Element.child() should return the children elements if no arguments provided?

### ISSUE THREAD

**Issue by futuremarc** [processing/p5.js#1084]
Similar to parent() with no args. thoughts?

**Comment by lmccart** [comment]
seems reasonable

**Comment by shiffman** [comment]
Indeed.  It's a little bit confusing b/c "child" is singular and will return an array, but I think adding an entire extra method called `children()` is worse, so let's do it!

**Comment by darkcoderrises** [comment]
Hi, I am new in here. Can I work on this?

**Comment by lmccart** [comment]
sure, go for it!
the relevant info is in the [developer doc](https://github.com/processing/p5.js/wiki/Development)

**Comment by lmccart** [comment]
closed with https://github.com/processing/p5.js/pull/1125
