### ISSUE TITLE
Is get(x,y) broken?

### ISSUE THREAD

**Issue by molleindustria** [processing/p5.js#1086]
(I thought I posted this before but I can't find my previous issue)

Get, when used to retrieve one color at the coordinate x,y, doesn't seem to work anymore. 
The example in the reference doesn't work:
http://p5js.org/reference/#/p5/get

It throws errors like:
13480: Uncaught TypeError: Cannot read property '0' of undefined

The undefined object is the pixels array
this.pixels[pd*4*(y*this.width+x)],
It doesn't work even after a loadPixels. 

I even tried the alternate method with loadpixels and the formula mentioned in the reference 
[pixels[(y*width*d+x)*d], pixels[(y*width*d+x)*d+1], pixels[(y*width*d+x)*d+2], pixels[(y*width*d+x)*d+3] ].
with no luck. The colors in this case appear to be part of the image but they are offset.
Also, the reference mentions a getColor function that doesn't exist.

On the other hand image.get(x,y) works fine.

**Comment by limzykenneth** [comment]
Can you post what browsers and OS you are using? At least the examples are working on my side. Cheers.

**Comment by molleindustria** [comment]
The second example here always outputs a white square on Chrome
http://p5js.org/reference/#/p5/get

and a blank canvas on Firefox.

When tested locally the console error is something like:
13480: Uncaught TypeError: Cannot read property '36200' of undefined

I'm on a non-retina MacBookPro (pixelDensity = 1). Interestingly on my iPhone 5 the example works. On Android (Samsung Galaxy 5) it looks like it always returns primary green. 
I was wondering if fixing device scaling issues for retina displays broke things for normal displays.

**Comment by lmccart** [comment]
hm I don't think the new device scaling fixes are up on the website yet, it should be the latest release that is also running the examples on site. I can take a look at this.

**Comment by molleindustria** [comment]
Oh wait, the problem is scaling here too. If I open the window at 100% zoom everything works! I'm guessing it's very similar to the set() issue that was closed last night.

**Comment by lmccart** [comment]
ah if it's related to scaling, it may have been fixed with the set patch. I'll post a new version tomorrow and ask you to check again then to see if it fixes things. :)

**Comment by lmccart** [comment]
this is looking better to me with the new version 0.4.18 now posted, but let me know if you still see issues.
