### ISSUE TITLE
beginShape() with multiple fill values

### ISSUE THREAD

**Issue by pbogdan03** [processing/p5.js#1090]
I cannot seem to replicate the following Processing behaviour in p5.js, is there any specific reason for this?
```javascript
void setup() {
  size(128, 128, OPENGL);
  background(128);
  noStroke();
  beginShape();
  fill(0);
  vertex(30, 20);
  vertex(85, 20);
  fill(0,255,0);
  vertex(85, 75);
  vertex(30, 75);
  endShape();
}
```

**Comment by limzykenneth** [comment]
Did you directly use the above code in p5.js? It sounds like you rewritten the above code in p5.js but if not then there's a few problems there as Processing and p5.js is not quite the same.

Details [here](https://github.com/processing/p5.js/wiki/Processing-transition).

**Comment by pbogdan03** [comment]
Hello @limzykenneth,
I replicated the above code in p5.js with the necessary changes, but the functionality of multiple fills on the same shape doesn't work, any idea why?

**Comment by lmccart** [comment]
this is not currently supported in p5.js. there's not exactly parity between processing and p5.js, instead p5.js takes inspiration and guidance from the processing api. in this case, we have not implemented support for this yet.
