### ISSUE TITLE
MediaElement.prototype.loadPixels() throws a TypeError

### ISSUE THREAD

**Issue by toolness** [processing/p5.js#1091]
While fiddling with #1087 I ran into the following bug.

Given the following sketch:

```js
var cam;

function setup() {
  cam = createCapture(VIDEO);
  cam.size(320, 240);
}

function draw() {
  cam.loadPixels();
}
```

Running it throws `Uncaught TypeError: Cannot read property '_pixelDensity' of undefined`, coming from `p5.Renderer2D.loadPixels`, which is being called from `p5.MediaElement.loadPixels`.

**Comment by lmccart** [comment]
I think I may have just fixed this in the latest version posted yesterday (v0.4.18), or is this the version you're currently testing with?

**Comment by toolness** [comment]
Ack, facepalm! I was on a8f9bb0beb091a7d86c9d988ca7e893363b8d7cd and forgot to do a `git pull` before running the sketch. The latest master does indeed fix this problem--my bad!
