### ISSUE TITLE
WEBGL - stroke() & noFill()

### ISSUE THREAD

**Issue by brondbjerg** [processing/p5.js#1093]
This may well not be an "issue" and just not yet implemented... if so, apologies! 

When creating a sphere() for example, you can't stroke() the wireframe mesh, and also can't apply noFill() to create a hollow mesh.

Maybe this is not something that you are going to support, but fairly common in Processing?!?

Thanks

**Comment by indefinit** [comment]
Currently we don't have wireframe primitives implemented, but it is definitely something we're planning on supporting in the near future!

**Comment by brondbjerg** [comment]
Great! Look forward to it!
Good luck :)

**Comment by faaip** [comment]
I'd love to help with p5js. Is there any one could help with creating such feature?

**Comment by DarkPrince304** [comment]
@indefinit : I would like to confirm whether this behavior is only with `sphere()` ? Because `noFill()` works as expected with `rect()` .

**Comment by indefinit** [comment]
As of now, noFill shouldn't have any effect on any of the 3D primitives, which includes:

sphere
box
torus
ellipsoid
cone
cylinder

**Comment by DarkPrince304** [comment]
http://p5js.org/reference/#p5/box
In this when I try noFill() nothing happens, same goes for sphere, torus, etc, so noFill() doesn't has any effect on the mentioned shapes. Did you mean that in the future, the mentioned 3D Primitives should support the wireframe functionality?

**Comment by indefinit** [comment]
Hi @DarkPrince304, yes sorry I wasn't clearer.  Right now we don't have wireframe functionality for 3D primitives.  I know it's not ideal, but you can draw wireframes manually using beginShape() and endShape().

That said, wireframe 3d primitives is definitely something we're eager to implement (in fact if you want to take a stab at it in the very near future, feel free to PR the webgl-geometry-refactor branch: https://github.com/processing/p5.js/tree/webgl-geometry-refactor and either I or someone else will take a look at the code).

**Comment by indefinit** [comment]
Closing this for administrative purposes.  I have added stroke() / noFill() implementation as a todo on our Development checklist.  Feel free to reopen this issue in the future.  Thanks!

https://github.com/processing/p5.js/wiki/Development---Checklist

**Comment by joncodo** [comment]
If I build this, will you merge it?
