### ISSUE TITLE
Graphics cropped when page is zoomed

### ISSUE THREAD

**Issue by law0102** [processing/p5.js#1094]
There is currently an issue when placing images inside of graphics when the page is zoomed. I have created a [repository](https://github.com/law0102/p5jsZoomBug) demonstrating the issue.

When you load [this](http://law0102.github.io/p5jsZoomBug/) page from a web browser, it shows normally. If you zoom in your web browser and refresh the page, the image will become cropped. Once you zoom in very far, the image will disappear all together.

This is a major issue when browsing from mobile devices, as they generally start zoomed. I have seen this bug on a Samsung Galaxy S4 and an iPhone 6S, and I'm sure it will also be present in other devices.

The code for this page is as follows:
```javascript
var cat,graph;
function preload() {
	cat=loadImage('cat.jpg');
}
function setup() {
	createCanvas(574, 710);
	graph=createGraphics(574,710);
}
function draw() {
	graph.image(cat,0,0);
	image(graph,0,0);
}
```
Zoom at 100%:
![100% zoom](https://dl.dropboxusercontent.com/u/32400917/ShareX/2015-11-11_16-11-13.png)

Zoom at 110%:
![110% zoom](https://dl.dropboxusercontent.com/u/32400917/ShareX/2015-11-11_16-11-38.png)

**Comment by lmccart** [comment]
try turning off the automatic scaling based on pixel density. because the device is zoomed, this changes the pixel density of your browser and can return weird results. if you add the line `pixelDensity(1)` at the beginning of setup(), it will lock the sketch to normal density instead of trying to scale with the zoom.

**Comment by law0102** [comment]
Thank you, that has fixed it.
