### ISSUE TITLE
Incorrect amount of arguments for 3D primitives crash browser

### ISSUE THREAD

**Issue by limzykenneth** [processing/p5.js#1096]
This is more of a feature suggestion so might not be the priorities at the moment. What happens is if  using a 3D primitive shapes and more than the required amount of arguments are passed into the function, it caused the browser to crash (or just the tab). This was on chrome on mac, I have yet to test other browsers.

Ideally it would give an error message instead of crashing.

**Comment by lmccart** [comment]
I think it would be good if it could just fail gracefully, and we mark the error message with a //TODO comment. the error system itself needs some general working out still, so I think it's best to wait on putting error messages in the code until a unified system for this is figured out.

**Comment by limzykenneth** [comment]
Agreed, at least it should not crash the browser or it will get rather frustrating. : )

**Comment by limzykenneth** [comment]
I just found [#175](https://github.com/processing/p5.js-website/issues/175) in p5.js-website repo and I went digging into the documentation source, I think I know what's the problem in both cases:

The example in the documentation is providing a second argument for the `sphere()` function and according to the documentation, it will be treated as detail level. A detail level of 128 is obviously too large for most system to render and they just crash, which might explain my problem as well (I was plugging in value of 200 XD). We should use default value in the examples and also add a warning about excessively high detail level in the documentation I think.

**Comment by indefinit** [comment]
I agree.  We could also limit detail level inside the sphere function, but making a note in the inline docs seems like a simple win.

**Comment by limzykenneth** [comment]
I should be able to make some changes this week (fixing the reference examples etc.) but how would we want to deal with the detail level? Do we want checks for a certain amount or just change the docs?

**Comment by lmccart** [comment]
@indefinit does it make sense to limit the detail level? or would you prefer to just make the docs more clear?

**Comment by indefinit** [comment]
I think I'd prefer to make the docs more clear.  Limiting the detail is obviously possible, implementation-wise, but I'd hate to prevent someone from trying something, even if it isn't a great performance decision.

**Comment by limzykenneth** [comment]
I agree on not limiting the detail level. Although it can be quite frustrating for the browser to crash but it's hard for us to know what limits we should set. Also browsers and webgl might become faster overtime and obviously we need to constantly check for that as well.

Ideally it would be best to do some test on the capability of the particular client so if the detail level is too high it just fail and not crash the browser, but "ideally"...

**Comment by hkirat** [comment]
I can add inline docs to all primitives and submit for a pr...if no one else is working on it.

**Comment by limzykenneth** [comment]
I'm not working on that at the moment, quite tied up I'm afraid. Do go ahead and add them and submit a PR. Cheers!
