### ISSUE TITLE
Run tests during CI on non-phantomJS browsers

### ISSUE THREAD

**Issue by toolness** [processing/p5.js#1101]
As I mentioned in #1070, I think it'd be great to use a service like Sauce Labs to run the tests on multiple browsers during travis runs. I think this will help ensure that p5 works well on all the latest browsers and also gracefully degrades on the older ones (or at least provides [helpful errors](https://github.com/processing/p5.js/issues/657)) as it grows.

Sauce Labs in particular has a program called [Open Sauce](https://saucelabs.com/opensauce/) which, for open source projects, "provides unlimited testing minutes on up to five parallel VMs and access to all our features, including 500+ OS/browser combos, screenshots, debugging tools and more."

Is this something that's desirable?

**Comment by lmccart** [comment]
sounds awesome
