### ISSUE TITLE
Cross-platform packaging of p5.js program

### ISSUE THREAD

**Issue by ylh888** [processing/p5.js#1103]
I need to distribute a p5.js app.I use socket.io and serial port to facilitate access to the USB port. The idea is to package a small proxy server to my users for each of OS X, Linux, Windows environment and be able to provide upgradable p5.js application over time, served over the internet. My app works in node.js.

However, I have encountered a bunch of issues trying to turn the server part 'native' using nw.js and jxcore.

I'm now looking into putting my p5.js code in a Chrome app.

Is there a better way to accomplish what I'm trying to do?

**Comment by toolness** [comment]
Have you looked at http://electron.atom.io/ ? I've never used it myself, but it was the first thing that came to mind...

**Comment by ylh888** [comment]
Thanks I will take a look.
