### ISSUE TITLE
The Drop feature (with gotFile function) is not working.

### ISSUE THREAD

**Issue by hellwoodfire** [processing/p5.js#1105]
See
http://p5js.org/examples/examples/Dom_Drop.php
.. and try to drop an image on the canvas...

This feature was working properly a few month ago, I think a bug was introduced in the library.

**Comment by DarkPrince304** [comment]
I am not able to reproduce that bug. I am able to see the image after dropping it on the canvas.

**Comment by lmccart** [comment]
seems to work fine testing on recent versions of chrome, firefox, safari.
can you give us more info about which browser / device / OS you're using?

**Comment by hellwoodfire** [comment]
Yes it work! Sorry!
It was caused by adblock.

**Comment by hellwoodfire** [comment]
Yes it work! Sorry!
It was caused by adblock.

**Comment by hellwoodfire** [comment]
However it could be great to understand which keyword is unfortunately detected by Adblock... because the example is not working when adblock is activated.

**Comment by hellwoodfire** [comment]
Sanchit, I just proformed more tests and now I'm happy that I reproduced
the exact problem I was looking for and that I did not describe correctly.
Now I think I have a better description :
https://forum.processing.org/two/discussion/13650/dropped-image-not-showing-in-the-draw-loop-gotfile-createimg-image

2015-11-13 14:05 GMT-05:00 Sanchit Kapoor <notifications@github.com>:
