### ISSUE TITLE
p5.Element size properties are not refreshed when id or class changes

### ISSUE THREAD

**Issue by Ucodia** [processing/p5.js#1109]
Fairly easy to reproduce.

Consider you have these styles.

```css
.my-class {
  width: 600px;
}

#my-id {
  height: 50px;
}
```

Just create an element and compare `p5.Element` size properties with internal DOM element properties.

```javascript
var myInput = createInput('');
console.log('(' + myInput.width + ', ' + myInput.height + ') / ' +
            '(' + myInput.elt.offsetWidth + ', ' + myInput.elt.offsetHeight + ')');
```
`(173, 21) / (173, 21)`

Then change the width by applying the class.

```javascript
myInput.class('my-class');
console.log('(' + myInput.width + ', ' + myInput.height + ') / ' +
            '(' + myInput.elt.offsetWidth + ', ' + myInput.elt.offsetHeight + ')');
```
`(173, 21) / (600, 21)`

You can already notice that the size is not updated on `p5.Element`. Same thing with id changes.

```javascript
myInput.id('my-id');
console.log('(' + myInput.width + ', ' + myInput.height + ') / ' +
            '(' + myInput.elt.offsetWidth + ', ' + myInput.elt.offsetHeight + ')');
```
`(173, 21) / (600, 50)`

This makes it impractical to place styled elements within a sketch.

**Comment by lmccart** [comment]
closed with https://github.com/processing/p5.js/pull/1108

**Comment by Ajayneethikannan** [comment]
@lmccart I think this issue is present in the current version, as the change made in this code is absent for p5.Element.prototype.class function.
I think it should also be added for removeClass() and addClass() methods in p5.Element.prototype in 
p5.dom.js
