### ISSUE TITLE
Protect for in loops from Object.prototype pollution

### ISSUE THREAD

**Issue by blindfish3** [processing/p5.js#1110]
There are for in loops (e.g. in preload) that don't check hasOwnProperty and so are at risk of breaking when code pollutes the Object.prototype.  Whilst the latter is obviously very bad practice it's unfortunately the sort of error less experienced coders and naive newbies will miss - e.g. copy pasting bad practice from elsewhere or using scripts that are badly written; as demonstrated in [this thread](https://forum.processing.org/two/discussion/13501/p5-js-crash-when-including-a-new-js-file-packman-js-in-the-same-html-file).  To guard against this it's easy to add a condition to check array.hasOwnProperty(element)...

**Comment by lmccart** [comment]
yes I think that'd be a good idea, do you want to take a crack at this?

**Comment by PaliwalSparsh** [comment]
@blindfish3 [I guess this is the place](https://github.com/processing/p5.js/blob/b37e850adb636a4df53992f090387e3163aa8196/src/core/core.js#L227) ie whole file you were referring in the thread you have linked for preload(). I guess we need to fix almost all the for...in with hasOwnProperty.
I feel I can fix this. Anything you would like to tell before I give it a try.

**Comment by blindfish3** [comment]
@PaliwalSparsh: for..in loops are known to be risky _if_ it's likely that the content being iterated over has inherited properties.  If there's any doubt about inheritable properties it's safer to add the check wherever you use for...in.  See [for...in on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in#Iterating_over_own_properties_only).
Alternatively use a standard for loop.

**Comment by lmccart** [comment]
I think these have all been addressed now, thanks everyone.
