### ISSUE TITLE
3D primitives examples broken?

### ISSUE THREAD

**Issue by toolness** [processing/p5.js#1111]
I'm not sure if this is something weird on my end, but on p5js.org, as well as on master as of 661805d99048951df57cadb3f023960fb6844c5c, all the 3d primitives examples (plane, sphere, cylinder, cone, torus, box) don't seem to do anything on Firefox or Chrome for me:

![2015-11-15_7-11-40](https://cloud.githubusercontent.com/assets/124687/11168688/462b7e4e-8b68-11e5-8549-57d3274a863e.png)

The only thing logged to the console is `p5.Renderer3D: enabled webgl context` and `The deviceorientation event is deprecated on insecure origins` (twice).

Is this happening for anyone else?

**Comment by joecridge** [comment]
Yes! I noticed this last week (Chrome 46) but thought it was just me doing something silly ’cause I’d never used WEBGL before.

**Comment by limzykenneth** [comment]
Have the latest version been pushed to the site yet? It might be related to #1092 and later parts of #1078

**Comment by yumengwang03** [comment]
Yes, same for me. Tried all the 3d examples and of them works. I can't find an answer to this...

**Comment by toolness** [comment]
Yay thanks @lmccart!
