### ISSUE TITLE
Official releases don't include minified p5.dom.js

### ISSUE THREAD

**Issue by alignedleft** [processing/p5.js#1119]
This is super minor, but I just noticed that the official ZIP (from Github or on p5js.org/download) include minified versions of p5.js and p5.sound.js, but not p5.dom.js.

Is there a reason for this (minor) inconsistency? p5.dom.min.js is available on the CDN, just not in the regular download.

**Comment by lmccart** [comment]
huh as far as i remember, i've never made any minified version of p5.dom.js. and i'm actually not sure how the generated one is getting to cdn. @futuremarc do you know more about this?

**Comment by lmccart** [comment]
i've added a task to generate the minified version as well, all future zip packages will now have both included.

**Comment by alignedleft** [comment]
Fantastic. Thank you, @lmccart!

**Comment by PixsaOJ** [comment]
Now it is removed again.  :-1:

**Comment by lmccart** [comment]
p5.dom has been merged into the main library, so there's no longer any need to link a separate file :)

**Comment by PixsaOJ** [comment]
Oh, Thank you. So I can use every function normally? Great!
