### ISSUE TITLE
Documentation for resizeCanvas() is confusing

### ISSUE THREAD

**Issue by toolness** [processing/p5.js#1120]
Currently the documentation for [`resizeCanvas()`](http://p5js.org/reference/#/p5/resizeCanvas) is:

> Resizes the canvas to given width and height. Note that the canvas will be cleared so anything drawn previously in setup or draw will disappear on resize. Setup will not be called again.

I find this confusing for a number of reasons:

* "anything drawn previously in setup or draw will disappear on resize" seems misleading because, while technically true, `resizeCanvas()` also calls `draw()` again, so everything that was drawn previously will likely re-appear.
* "Setup will not be called again" is a bit confusing in this context. I'm not entirely sure why anyone would expect setup to be called, but I guess the statement is true, so there's no harm in leaving it in.
* It's not mentioned that `resizeCanvas()` will call `draw()` again, and this is totally not obvious to me. In fact, for various reasons, I was calling `resizeCanvas()` in the middle of my `setup()` function, and was very confused as to why my `draw()` function was suddenly being called before `setup()` finished. For a long time I thought my `setup()` was somehow being prematurely terminated, and it took reading p5's source code to realize that `resizeCanvas()` was actually calling `draw()`.

Based on my brief use of `resizeCanvas`, I think it might make more sense to have documentation like this:

> Resizes the canvas to given width and height. The canvas will be cleared and draw will be called immediately, allowing the sketch to re-render itself in the resized canvas.

If that seems reasonable, I'm happy to issue a PR.

Also, as an aside, is it ok to show `draw` in a monospaced font in the docs, maybe even with a set of parenthesis after it (e.g. `draw()`) so it looks like code and readers immediately know what we're referring to? I'd like to do that but I also don't want to be inconsistent with the current typographic style.

**Comment by lmccart** [comment]
yes this makes sense, great suggestion! this also pertains to #905. while you're at it, it might be nice to add one more example that demonstrates the technique of creating an init() function to reinstate properties set in setup() on resize. something like this: https://github.com/processing/p5.js/issues/905#issuecomment-139829242.

and yes, it's fine to add "<code></code>" tags around words to render them in monospace.

**Comment by lmccart** [comment]
I think given https://github.com/processing/p5.js/commit/dad98d6728e2c7a6ceb10d6c0affcd0ea55a6d44, your proposed documentation revision above still makes sense (actually makes more sense now). I'll go ahead and add it in while I've got the file open now...

**Comment by toolness** [comment]
Cool, thanks!
