### ISSUE TITLE
Provide friendly error help when sketches use p5 functions outside of setup/draw

### ISSUE THREAD

**Issue by toolness** [processing/p5.js#1121]
(This is basically a re-post of https://github.com/processing/p5.js/pull/1106#issuecomment-156714155, which was a comment in a closed issue that might have gone unnoticed.)

@lmccart [wrote](https://github.com/processing/p5.js/pull/1106#issuecomment-156696614):

> no p5 functions work outside of setup/draw... if you can think of any good way to catch this error it'd be wonderful, but I haven't come up with anything yet. the main issue is that calling p5 functions before setup fails because p5 hasn't been instantiated yet (this non-automatic global binding of p5 functions is in place to support instance mode, where p5 is wrapped up in one object so as not to pollute the global namespace. so we have to wait to be sure we are working in global mode before adding all the p5 functions). so i'm not how we could catch errors when p5 isn't running? but any thoughts welcome!

It's a bit hacky, but what if we added an `onerror` event handler that caught errors during page load and offered help if possible?

Here's an example: http://jsbin.com/riyaco/2/edit?html,console,output

Again, it's hacky, and I'm not sure how many false positives it'd trigger...

**Comment by lmccart** [comment]
hmm, interesting... I can't think of any major downsides to giving it a shot? if it seems to cause more confusion than it's worth we can always remove it.
