### ISSUE TITLE
Mobile examples not working on Chrome phone browser

### ISSUE THREAD

**Issue by srinivasmangipudi** [processing/p5.js#1127]
The mobile examples are not working on the phone. The display is all messed up.

**Comment by limzykenneth** [comment]
Hi @srinivasmangipudi, thanks for the report but I'm afraid you need to be a bit more specific than that. It will be ideal if you can provide the phones models, OS (including versions) and perhaps some screenshot of how it looks like then we will be able to fix it faster. Cheers.

**Comment by lmccart** [comment]
closing this as it's too vague to solve right now. please feel free to reopen with more specific details as @limzykenneth describes.
