### ISSUE TITLE
translate() behavior is confusing when called w/ 2 args in 3D

### ISSUE THREAD

**Issue by toolness** [processing/p5.js#1137]
The following results in a blank sketch:

```js
// draw a sphere with radius 200
function setup(){
  createCanvas(100, 100, WEBGL);
}

function draw(){
  background(200);
  translate(0, 0);
  sphere(200);
}
```

The sketch works fine, though, if a third (z) argument is passed to `translate()`:

```diff
   background(200);
-  translate(0, 0);
+  translate(0, 0, 0);
   sphere(200);
```

To fix this, I propose:

* Adding at least one 3D example to the [documentation on `translate()`](http://p5js.org/reference/#/p5/translate), and also documenting the `z` parameter.
* Either making the third argument default to `0` if it's not present in 3D sketches, or throwing an exception.

I'm happy to submit a PR to fix this one!

**Comment by lmccart** [comment]
sounds great! let's default to 0 if no third arg is included.

**Comment by karenpeng** [comment]
Thanks for the advice.
