### ISSUE TITLE
Reference is unclear that library is required for functions

### ISSUE THREAD

**Issue by dhowe** [processing/p5.js#1142]
As example, if one searches for createDiv, then views the page that comes up, it is not specified anywhere that p5.dom is required for the function to work.

<img width="1170" alt="screen shot 2015-11-29 at 5 39 38 pm" src="https://cloud.githubusercontent.com/assets/737638/11456300/0bb67de6-96c0-11e5-97f5-9de68a9a69f0.png">

**Comment by lmccart** [comment]
indeed! it is on my todo list, in fact there's an issue open for it here: https://github.com/processing/p5.js/issues/1075. closing this one since it seems to be a duplicate.
