### ISSUE TITLE
The method p5-Element.class() does not return the class for that element.

### ISSUE THREAD

**Issue by rscharfer** [processing/p5.js#1149]
I am not sure if this is a bug or not, but I was told to file this as a bug.  When you do not pass in an argument into the .class method of p5.Element, you do NOT get the current CSS class(es) of that element.  Instead the entire p5 element object is returned. Or is there an easy way to get the current class(es) of a p5.Element that I am missing?

**Comment by lmccart** [comment]
this does sound like a bug, thanks! i'll take a look.
