### ISSUE TITLE
image(img, sx, sy, sw, sh, dx, dy, dw, dh) seems to work as image(img, dx, dy, dw, dh, sx, sy, sw, sh)

### ISSUE THREAD

**Issue by vanevery** [processing/p5.js#1158]
Perhaps I am crazy but when I draw an image with all of the parameters it seems to function with the canvas positions first then the portion of the image to draw rather than the other way around.

**Comment by vanevery** [comment]
I am happy to do a pull request to either fix documentation or fix functionality if anyone can confirm that this is a bug and I am not crazy.

**Comment by lmccart** [comment]
I realized processing doesn't cover this case: https://processing.org/reference/image_.html. but I think the args should probably align with the native drawImage() method in canvas http://www.w3schools.com/tags/canvas_drawimage.asp. I believe this is how the documentation describes it, so I guess it is a matter of making sure the code actually does that. weirdly at quick glance the code looks right... I haven't tested it though.

**Comment by VinaySingh035** [comment]
I would like to work on this issue, as I'm a newbie here so will be good to start with.
@vanevery can you please elaborate the issue a bit more and help me here in grabbing some understanding here.

**Comment by timglorioso** [comment]
It's working as expected for me, and there's already a test for this. Maybe @vanevery could provide an example of it not working?

**Comment by vanevery** [comment]
Hi @timglorioso and @VinaySingh035 

Here is a quick example illustrating the problem:
http://www.walking-productions.com/icm_2015/imagetest/

var img;

function preload() {
  img = loadImage("100x100black_square.png");
}

function setup() {
  createCanvas(200,200);
}

function draw() {
  background(128);
  //image(img, sx, sy, sw, sh, dx, dy, dw, dh);
  
  // IMHO Should stretch the source image to fill the canvas (200x200) but it draws at 100x100
  image(img, 0, 0, 100, 100, 0, 0, 200, 200);
  
  // Stretches source image to fill the canvas when it shouldn't
  //image(img, 0, 0, 200, 200, 0, 0, 100, 100);
}

**Comment by timglorioso** [comment]
Okay, I think it's because you're using 0.4.13 and this functionality was added in 0.4.14.

**Comment by vanevery** [comment]
Hot diggity dog, you are right.  It is working as it should with 0.4.17.  Sorry for the time waste
