### ISSUE TITLE
Flat Shader Model

### ISSUE THREAD

**Issue by fkolev** [processing/p5.js#1160]
Hey,

I'm sorry if this shouldn't be here, however I don't know where else to address this. My question pertains to flat shading. I want to have a flat-shader, so that object face has a sightly different color. 

Example: http://matthew.wagerfield.com/flat-surface-shader/ (for more clarifcation)

However I don't think there are any shader options in P5. Is there any current way to achieve a flat shade? I know WebGL has a shader function, are there any plans to implement this?

Thanks

**Comment by indefinit** [comment]
Thanks for your interest.  Custom shaders in p5 are in the pipeline, but aren't quite ready for prime time.  Right now the following material shaders are supported:

basicMaterial() which is an rgba pixel shader
specularMaterial() for specular
ambientMaterial() for ambient rgba + light model

For your use case, you might be able to get away with ambient and specular materials + directional and point lights.  

Check out the webgl getting started guide for more info:
https://github.com/processing/p5.js/wiki/Getting-started-with-WebGL-in-p5
