### ISSUE TITLE
.obj loader for p5.js

### ISSUE THREAD

**Issue by hkirat** [processing/p5.js#1161]
How about an .obj loader for p5.js?
It is a very common 3d Modelling format and would help people render any model they want to the canvas in 3-D.
I have already started working on it.( Attached screenshot of the Blender Monkey Suzzanne)
I would like to know what structure to follow while making this loader?
A new p5.js-loaders library?Since we will be needing a saperate cpp or python file to convert obj to js and then load the js into the canvas.
Or adding a new function to p5.js?
![screenshot from 2015-12-03 00 27 29](https://cloud.githubusercontent.com/assets/8079861/11540780/c09e65ac-9954-11e5-93a0-09ae76f181b4.png)

**Comment by lmccart** [comment]
indeed! @mindofmatthew has been working on this.

**Comment by hkirat** [comment]
Is there any other thread where discussion is going on regarding this?

**Comment by indefinit** [comment]
This is something @mindofmatthew has been working on. Perhaps you two could team up?

**Comment by indefinit** [comment]
Whoops didn't see Lauren's response. Please ignore.

**Comment by hkirat** [comment]
@mindofmatthew : Could I join you in this?

**Comment by mindofmatthew** [comment]
@hkirat: Sure! Right now, I've got rough versions of vertex, face, normal, and UV parsing, but there are still gaps and bugs. Was there some specific aspect you wanted to work on?

All of my work is in this file:

https://github.com/mindofmatthew/p5.js/blob/3d-model-loading/src/3d/loading.js

**Comment by hkirat** [comment]
I wanted to work on both parsing and rendering..
But everything looks nice in your fork.
I'll contribute directly to it..
