### ISSUE TITLE
pMouseX/Y only updates on mouse movement and not with new frame

### ISSUE THREAD

**Issue by KingWalrus** [processing/p5.js#1162]
Not sure if this is a bug but it seems there are some different behaviors between the latest p5 libraries (starting with 0.4.18) and the version that comes with the p5 editor. 

When developing using the editor, pmouseX/Y seems to update with the new frame so if the mouse stops moving pmouseX/Y will equal mouseX/Y on the next frame. However, with 0.4.18 and 0.4.19, when the mouse stops moving pmouseX/Y does not equal the current mouseX/Y values. 

Is this the desired behavior?

**Comment by limzykenneth** [comment]
From what I understand, if the mouse is not moving, `pMouseX/Y` should equal to `mouseX/Y`. Can you give an example of what the values of `pMouseX/Y` and `mouseX/Y` are respectively with 0.4.19 when the mouse is not moving?

**Comment by KingWalrus** [comment]
Yeah. 

From what I can tell the pmouseX/Y values update only when the mouse moves and not on the frame as stated in the reference. 

After not moving the mouse this was the values of mouseX, mouseY, pmouseX, pmouseY when using 0.4.19:

417 148 417 150
