### ISSUE TITLE
updatePixels() throws an unhelpful error if not preceded by set() or loadPixels()

### ISSUE THREAD

**Issue by toolness** [processing/p5.js#1163]
Consider the following sketch, which is just meant to show dots where the user has clicked:

```js
var points = [];

function setup() {
  createCanvas(100, 100);
  background("black");
}

function mouseReleased() {
  points.push({x: Math.floor(mouseX), y: Math.floor(mouseY)});
}

function draw() {
  points.forEach(function(point) {
    set(point.x, point.y, color(255, 0, 0));
  });

  updatePixels();
}
```

By itself, this sketch doesn't actually work, because the following exception is thrown on the first frame:

```
Uncaught TypeError: Failed to execute 'putImageData' on 'CanvasRenderingContext2D': parameter 1 is not of type 'ImageData'.
```

Altering the sketch so `updatePixels()` isn't called if there are no points in our array (i.e., when no calls to `set()` have been made) fixes things:

```diff
-  updatePixels();
+  if (points.length > 0) updatePixels();
 }
```

At the very least, I think that `updatePixels()` should throw a more helpful error.

However, having to guard `updatePixels()` with a conditional, seems like it *should* be unnecessary. Maybe `updatePixels()` should simply do nothing if no calls to `set()` or `loadPixels()` have been made before it?

**Comment by lmccart** [comment]
I think the graceful do nothing fail makes sense!
