### ISSUE TITLE
get() returns unpredictiable results for non-integer values

### ISSUE THREAD

**Issue by gtoast** [processing/p5.js#1167]
Started investigating this after  noticing this example for the p5.play framework was broken:
http://p5play.molleindustria.org/examples/index.html?fileName=collisions5.js That triangle is supposed to rest on that turquoise cloud thing.

The crux of the problem is illustrated here:

```
function setup() {
  createCanvas(50, 50);

// First, create a 50 x 50 red image.
  img = createImage(50, 50);
  img.loadPixels();
  for (i = 0; i < img.width; i++) {
    for (j = 0; j < img.height; j++) {
        img.set(i, j, color(255, 0, 0));
    }
  }
  img.updatePixels();

  image(img, 0, 0);

// Then take 3 color samples from your red image.
  println(img.get(25, 25));
  println(img.get(25, 25.53));
  println(img.get(25, 26));
}
``` 

this returns
```
[255,0,0,255]
[0,255,255,0] <-- Oops, not red!
[255,0,0,255]
```

Mess around with the decimal number to get even stranger results. (I've also seen it return [null, null, null, null] before.) That p5.play example above looks for non-alpha pixels using get(), and the values get switched around such that the alpha value returned is less than 255 so the triangle falls right through. 

Calling Math.round on the arguments to get() will fix this. I'll try to submit a patch later today.

**Comment by lmccart** [comment]
great, thank you!

**Comment by lmccart** [comment]
closed with https://github.com/processing/p5.js/pull/1169
