### ISSUE TITLE
grunt command failing on PhantomJS

### ISSUE THREAD

**Issue by evejweinberg** [processing/p5.js#1172]
when running grunt, I get this error:

Warning: PhantomJS unable to load "http://localhost:9001/test/test.html" URI. Used --force, continuing.

I followed the steps here: https://github.com/processing/p5.js/wiki/Development#setup

**Comment by limzykenneth** [comment]
Can you post the whole terminal output here? Thanks.

**Comment by evejweinberg** [comment]
after getting the error I tried to install as sudo, and also used --debug:


HiEve p5.js 💗  sudo npm install
Password:
HiEve p5.js 💗  grunt test --debug
Running "jshint:build" (jshint) task
[D] Task source: /Users/NeverOdd/Desktop/p5.js/node_modules/grunt-contrib-jshint/tasks/jshint.js
>> 2 files lint free.

Running "jshint:source" (jshint) task
[D] Task source: /Users/NeverOdd/Desktop/p5.js/node_modules/grunt-contrib-jshint/tasks/jshint.js
>> 59 files lint free.

Running "jshint:test" (jshint) task
[D] Task source: /Users/NeverOdd/Desktop/p5.js/node_modules/grunt-contrib-jshint/tasks/jshint.js
>> 21 files lint free.

Running "jscs:build" (jscs) task
[D] Task source: /Users/NeverOdd/Desktop/p5.js/node_modules/grunt-jscs/tasks/jscs.js
No code style errors found.
>> 2 files without code style errors.

Running "jscs:source" (jscs) task
[D] Task source: /Users/NeverOdd/Desktop/p5.js/node_modules/grunt-jscs/tasks/jscs.js
No code style errors found.
>> 59 files without code style errors.

Running "jscs:test" (jscs) task
[D] Task source: /Users/NeverOdd/Desktop/p5.js/node_modules/grunt-jscs/tasks/jscs.js
No code style errors found.
>> 21 files without code style errors.

Running "browserify" task
[D] Task source: build/tasks/browserify.js
>> Bundle lib/p5.js created.

Running "uglify:build" (uglify) task
[D] Task source: /Users/NeverOdd/Desktop/p5.js/node_modules/grunt-contrib-uglify/tasks/uglify.js
>> 1 file created.

Running "requirejs:yuidoc_theme" (requirejs) task
[D] Task source: /Users/NeverOdd/Desktop/p5.js/node_modules/grunt-contrib-requirejs/tasks/requirejs.js

Running "connect:server" (connect) task
[D] Task source: /Users/NeverOdd/Desktop/p5.js/node_modules/grunt-contrib-connect/tasks/connect.js
Started connect web server on http://0.0.0.0:9001

Running "mocha:test" (mocha) task
[D] Task source: /Users/NeverOdd/Desktop/p5.js/node_modules/grunt-mocha/tasks/mocha.js
Testing: http://localhost:9001/test/test.html
[D] ["/Users/NeverOdd/Desktop/p5.js/node_modules/grunt-mocha/phantomjs/main.js","/var/folders/kd/b1gc6xvd6qsbzv8c2vhkl0_w0000gn/T/1449856637993.2783","http://localhost:9001/test/test.html","{\"timeout\":5000,\"inject\":\"/Users/NeverOdd/Desktop/p5.js/node_modules/grunt-mocha/phantomjs/bridge.js\",\"phantomScript\":\"/Users/NeverOdd/Desktop/p5.js/node_modules/grunt-mocha/phantomjs/main.js\",\"logErrors\":true,\"growlOnSuccess\":true,\"run\":true}"]
[D] ["phantomjs","private","version",{"major":1,"minor":9,"patch":8}]
[D] ["phantomjs","onResourceRequested","http://localhost:9001/test/test.html"]
[D] ["phantomjs","onResourceError","http://localhost:9001/test/test.html","Host localhost not found"]
[D] ["phantomjs","onResourceReceived","http://localhost:9001/test/test.html"]
[D] ["phantomjs","onLoadFinished","fail"]
[D] ["phantomjs","fail.load","http://localhost:9001/test/test.html"]
...ERROR
Warning: PhantomJS unable to load "http://localhost:9001/test/test.html" URI. Use --force to continue.

**Comment by limzykenneth** [comment]
At first glance it seems to be a timeout problem with PhantomJS (which I knew nothing about). Someone else will need to pick up on this. It isn't happening on my side though.

In the mean time you can skip the linting and testing steps by running `grunt build`, might not be a good idea but at least you get to build the library from source with this.

**Comment by toolness** [comment]
Hmm, I just noticed the "Host localhost not found" line of your output... What happens if you run `ping localhost`?

Also, can you run `grunt connect --keepalive` and then visit http://localhost:9001/ in your browser? Does it show a directory listing, or does it not load?

**Comment by lmccart** [comment]
hi @evejweinberg I'm going to close this one for organizational purposes. seems like debugging via github isn't working... maybe we can try in person if you're still having issues.
