### ISSUE TITLE
Tint problem after upgrading from 0.4.19 to 0.4.20

### ISSUE THREAD

**Issue by riebschlager** [processing/p5.js#1181]
I have a sketch (instance mode) that is using tint like this:

```js
this.init = function() {
  this.canvas = p.createGraphics(this.w, this.h);
  this.canvas.tint(255, this.alpha);
  this.canvas.image(this.wheatImage, 0, 0, this.w, this.h);
};
```
It had been working fine, but 0.4.20 doesn't like it very much. It's hitting an error in `p5.Renderer2D.prototype.image` which is around line 85 in `p5.Renderer2D.js`

The error is `Uncaught TypeError: Expecting a function in instanceof check, but got undefined`

I'm not really sure why the `instanceof` call is failing like this.

**Comment by lmccart** [comment]
I tried to piece together an example from what you posted, an came up with something like this, does this represent the problem?
```javascript
var s = function(p) {
  var img;
  var w = 600;
  var h = 400;
  var c;

  p.preload = function() {
    img = p.loadImage('assets/cat.jpg');
  }
  p.setup = function() {
    p.createCanvas(w, h);
    c = p.createGraphics(w, h);
    c.tint(255, 100);
    c.image(img, 0, 0, 100, 100);
    p.background(0);
    p.image(c);
  }
}

new p5(s);
```

however, the output looks like this, which seems fine?
<img width="609" alt="screen shot 2015-12-22 at 8 23 48 pm" src="https://cloud.githubusercontent.com/assets/191056/11969604/f013c10c-a8e9-11e5-841d-2e8ba9e0031a.png">


if this is not correct, could you please post a full sketch example?

**Comment by riebschlager** [comment]
Sure thing. Here is a fiddle using that same code with 0.4.20:

https://jsfiddle.net/riebschlager/hvbekfxv/

And one with 0.4.19:

https://jsfiddle.net/riebschlager/j4ysrcc4/

I've tried each version in Chrome, Firefox and Safari and it's still erroring out at the 'instanceof' check on `p5.MediaElement`

**Comment by lmccart** [comment]
aha perfect thank you! i wasn't seeing it before because i was including the p5.dom library as well, which stops the error from occurring. i just added a check so the function should work properly now.
