### ISSUE TITLE
p5.sound - Multiple concurrent oscillators and envelopes, triggerRelease not executing

### ISSUE THREAD

**Issue by evesira** [processing/p5.js#1182]
Today I started building an app that involves playing chords with button presses. Ran into some problems, looked at my code for a long time to figure out what was wrong, until I boiled it down to the following code which doesn't work but should:

```
env1 = new p5.Env(0.010, 1.000, 0.000, 1.000, 0.000, 1.000, 0.500);
env2 = new p5.Env(0.010, 1.000, 0.000, 1.000, 0.000, 1.000, 0.500);
env3 = new p5.Env(0.010, 1.000, 0.000, 1.000, 0.000, 1.000, 0.500);

osc1 = new p5.SinOsc();
osc1.freq(MidiToFrequency(63));
osc1.start();
env1.triggerAttack(osc1);

osc2 = new p5.SinOsc();
osc2.freq(MidiToFrequency(67));
osc2.start();
env2.triggerAttack(osc2);

osc3 = new p5.SinOsc();
osc3.freq(MidiToFrequency(70));
osc3.start();
env3.triggerAttack(osc3);

env1.triggerRelease(osc1,2); // E flat
env2.triggerRelease(osc2,2); // G
env3.triggerRelease(osc3,2); // B flat
```

In Chrome, Firefox, and Opera, this consistently doesn't work on my machine. Only the first note called to be released is actually released. The other two keep playing. If I rearrange the releases like so, only the G will release:

```
env2.triggerRelease(osc2,2); // G
env1.triggerRelease(osc1,2); // E flat
env3.triggerRelease(osc3,2); // B flat
```

The weird thing is, if the triggerRelease call is moved to immediately after the triggerAttack call for each oscillator, they all release correctly. I should be able to call the triggerRelease for any or all of the notes at any time after, not having to plan the release at the same moment as the attack, yes?

Am I missing something here? These oscillators and envelopes should be able to operate independently right?

**Comment by therewasaguy** [comment]
Thanks for this! Just pushed a fix to the p5.sound repo, you can get the latest version of the library here:
https://github.com/processing/p5.js-sound/tree/master/lib

If you find more issues related to p5.sound, feel free to post them on the p5.sound repo
