### ISSUE TITLE
translate() in v0.4.20

### ISSUE THREAD

**Issue by schuelaw** [processing/p5.js#1183]
In the [reference for the translate function](http://p5js.org/reference/#/p5/translate), it states that translations are cumulative, but that they are reset after each draw(). This is certainly the behavior that I was seeing up until I updated my lib this afternoon to v0.4.20. This [simple sketch](http://carrot.whitman.edu/P5JS/Test-0.4.20/), indicates that the translations are cumulative even between draw()'s (i.e. the translation is not reset after each draw()).
```javascript
var i;
function setup() {
 // put setup code here
 createCanvas(600,600);
 ellipseMode(RADIUS);
 i=0;
}
 
function draw() {
 translate(i,i);
 ellipse(0,0,20,20);
 i+=1;
}
```

**Comment by lmccart** [comment]
tthanks. this has been fixed (https://github.com/processing/p5.js/issues/1174), it will be included in the next release.
