### ISSUE TITLE
[website] PHP warnings

### ISSUE THREAD

**Issue by vieks** [processing/p5.js#1184]
http://p5js.org/tutorials/trigonometry/

**Comment by limzykenneth** [comment]
Seems to be several links broken, I'll try to fix this but I'm not sure how complete this tutorial really is but I can at least fix the PHP errors.

**Comment by lmccart** [comment]
yes this is an in progress tutorial (it's not listed on the tutorials page yet), but if you'd like to fix I think the php links just need an extra "../". otherwise I'll be back at this in a few days and can fix it then. thanks!
