### ISSUE TITLE
Documentation style guide and YUIDoc markdown

### ISSUE THREAD

**Issue by limzykenneth** [processing/p5.js#1190]
To build on the point about style guide for the inline documentation mentioned in #1173, at the moment the way to add line breaks or create new paragraphs is only by adding `<br />` tags. I think that's too messy and way too easy to miss.

According to YUIDoc's [syntax reference](http://yui.github.io/yuidoc/syntax/index.html#basic-requirements), YUIDoc supports markdown and also recognizes two line breaks as start of a new paragraph. 

I'm not that familiar with YUIDoc myself but if possible I think it will be great to minimize the amount of html tags that needs to be inserted into the inline docs, removing the need for the `<br />` tags.

On a side note, I was thinking about removing the need for the `<div>` and `<code>` tags for the example but I think that means we cannot have a `norender` class on the example code `<div>` tags?

**Comment by toolness** [comment]
Yeah, a style guide would be great! One of the particular things that always gnaws at me is the fact that JS symbols like functions/variables/constants are never `monospaced` when they're used in sentences. Most of the time this is just my OCD at work, but sometimes I think it genuinely hampers readability and makes things a bit confusing.

I generally agree regarding the `<div>` and `<code>` stuff but as you mentioned, we'd need to figure out what to do about `norender`. One option is to add a specially-formatted comment to the beginning of the sample like `// NORENDER`, which our documentation pipeline notices, removes from the code shown to the user, and then adds to the rendered HTML.

I also address some of this in https://github.com/processing/p5.js/pull/1144#issuecomment-160419254, regarding browser capabilities required for certain examples to run.

**Comment by kaganjd** [comment]
+1 to documentation style guide! I'm working on autocomplete this summer. The YUIDoc data.json file is the starting point of a process for generating the file that Tern.js uses to do autocomplete. 

In data.json, I'm running into lots of typos (#2042, #2016 ), missing fields ([color_conversion](https://github.com/processing/p5.js/blob/37f1e69e8027c1745adfb7c18c50b1fbbb7c0d49/src/color/color_conversion.js), for example, doesn't list any `@method`s which means that when I generate the Tern.js file, color_conversion methods don't show up), and inline HTML tags that all ultimately affect how autocomplete works.

**Comment by anhtuann** [comment]
@kaganjd any news on the tern autocompletion file ? I would love to get it to work with p5js
