### ISSUE TITLE
improve camera api

### ISSUE THREAD

**Issue by karenpeng** [processing/p5.js#1194]
should add eye position in vertex shader so that the [camera](http://p5js.org/reference/#/p5/camera) api has direct control of world position, instead of controlling model view matrix.

**Comment by indefinit** [comment]
hey @karenpeng just wanted to follow up with you on this issue.  Do you have a status update?  One option instead of including a fully-formed camera api in p5 is to build this as a p5 library a la [PeasyCam](http://mrfeinberg.com/peasycam/) and the library would hook into the MVMatrix and PMatrix default uniforms respectively.

**Comment by karenpeng** [comment]
@indefinit, thanks for the reference, as in #1431 view matrix is separated with model matrix, meaning we could control the camera without affecting the push and pop matrix world. In terms of whether to build a camera api or an external library, I need to do more experiments and testing to see how the api should go, will keep you updated :)

**Comment by swirly** [comment]
Hello. Interested in having a camera a bit more refined. Particulary, the "Getting started with WebGL in p5" article refers to p3d mode in processing, where camera is defined with 9 coordinates (position, point of view and axis)
This should, in term of api, be the bar minimum for a usable camera.
May be a 
camera()
cameraLookAt()
cameraRotation() should also be used ?
Anyway, I find that without this p5 webgl is barely usable.
The question of one or two repo is another matter.

**Comment by kjhollen** [comment]
We implemented the 9-argument version of camera() to match the Processing implementation as part of the google summer of code work on WebGL. I am going to close this issue for now as I think the minimum solution has been implemented. We can leave #2161 open as a placeholder for possible future work with rotation and lookAt—I think these are both good suggestions!
