### ISSUE TITLE
Implementing surface in WebGL

### ISSUE THREAD

**Issue by parsoyaarihant** [processing/p5.js#1198]
Hi,
    I think it will be cool if there is a way to render surface in 3D. Similar to beginShape, if the user is able 
to input the boundary and few coordinates which lie inside the surface, depending on the property of the surface(elastic/non-elastic) we can render the surface to a good approximation. I feel this can have many applications and will be fun to use. Please give feedback :)

Thanks.

**Comment by indefinit** [comment]
Sounds very interesting!  It would be great to see some more examples of this so others can weigh in.  Related to this topic, what do you think about something like axis aligned bounding box and point-plane intersection or line-plane intersection?  From a high level, this is how I imagine how a user would work with a bounding box api:
```
//draw a geometry's axis aligned bounding box
aabb(sphere(100));  
```

```
//draw a geometry's axis aligned bounding sphere
aabs(cone(100,10));
```

**Comment by parsoyaarihant** [comment]
Yeah @indefinit , I think using this concept we can improve 3D functionalities such as simulations and interactive animation in the canvas. One potential application which can be evoked by implementing intersection is that user too can interact with the 3D objects in the canvas. It can be done if we consider a line normal to the computer screen(which is camera in WebGL) at the point where the mouse cursor is located, the intersection of that line with any 'aligned bounding box' would mean that user is pointing to that object which is enclosed by the 'aligned bounding box'. If possible, we could click in 3D!

**Comment by parsoyaarihant** [comment]
re @indefinit : I have few questions regarding this:
we cannot define and store a new model in immediate mode, hence the user won't be able to use the bounding box method for the shape drawn in immediate mode. I would be better if we define our own model and input vertices or load models from .obj file and then implement aligned bounding box in p5.

**Comment by indefinit** [comment]
We should really be using retained mode instead of immediate for bounding box operations, or any operations where we need to store reference to the model itself.  In this way, a method like aabb() (axis aligned bounding box) would be called on the p5.Geometry object.

**Comment by indefinit** [comment]
Hi there, I'm going to close this issue for administrative purposes.  Feel free to reopen in the future.  I think the major takeaway is that whenever possible, use the p5.Geometry object as part of retainedMode.  p5.Geometry contains vertices, vertexNormals, and faces which form both 2d and 3d surfaces.
