### ISSUE TITLE
fullscreen issue on firefox

### ISSUE THREAD

**Issue by autumna** [processing/p5.js#1199]
on firefox, fullScreen() function is broken. Workaround is to rename fullScreen() function to "fullscreen()" or  "afullScreen()" etc in the p5.js file and the relevant sketch. The sketch that is broken in Firefox works fine in Chrome. 

Possible firefox namespace conflict?

**Comment by opg7371** [comment]
We can solve the problem by skipping js alert on Firefox browsers.
I will be fixing it soon.

**Comment by hkirat** [comment]
fullScreen is a global boolean variable in Mozilla
Renaming fullScreen() -> fulllscreen() works fine
