### ISSUE TITLE
Custom Debugger for p5.

### ISSUE THREAD

**Issue by hkirat** [processing/p5.js#1201]
I would like to mention #971 over here..
How about a custom Debugger for p5.js
By custom Debugger I mean rather than having Custom messages in the right of the screen inside the browser.
It can include functionality like colors for different messages..
If the debug mode is on the console messages would appear on the screen hence saving the developer from opening the js console in the browser..

**Comment by lmccart** [comment]
hi @hkirat thanks for your suggestion and ideas! we actually have the beginnings of a system like this in place already, and are thinking about ways to incorporate it into the editor and workflow once it's complete. you can follow along here: https://github.com/processing/p5.js/issues/971.
i'm going to close this issue so the conversation doesn't get split across threads. feel free to post more thoughts on the other issue.
