### ISSUE TITLE
MouseX, MouseY don't work in latest p5 release with noLoop()

### ISSUE THREAD

**Issue by brig002** [processing/p5.js#1205]
Hi all.  
With noLoop() turned on and mouse coordinate detection happening in the mouseMoved() method, mouse coordinates don't get updated in the latest p5 release (downloaded today, versus the last one I was using downloaded in Aug 2015). 

Here is an example. Loading the same sketch.js, just switching the p5 library releases: 
http://dfilm.com/lucs/mousetest/index.mousetest.2015.html  (works)
http://dfilm.com/lucs/mousetest/index.mousetest.2016.html (doesn't work)

Something change or is this a bug? 
-ben

**Comment by lmccart** [comment]
yes, I reworked the mouse stuff to deal with issues mentioned here: https://github.com/processing/p5.js/issues/1176. now, mouse coords are updated in draw, rather than directly on mousemove. this means that with noLoop() set, you will not see continued effects from mouse input. this matches the behavior of processing I believe?

**Comment by brig002** [comment]
Ah, shoot. Was trying to avoid looping for performance reasons. Will go back to setting a slow framerate instead. Thanks for the quick response.

**Comment by lmccart** [comment]
perhaps a workaround is to grab the coords from the mouse event directly?
something like this:
```javascript
function setup() {
  noLoop();
}

function mouseMoved(e) {
  //console.log(e);
  //ellipse(mouseX, mouseY, 10, 10);
  ellipse(e.clientX, e.clientY, 10, 10);
}
```

**Comment by brig002** [comment]
Oh yea, that'll do the trick! Nice one. Thx. 
-ben

ps. I'm 1000% in love with p5js. Have been rueing the death of Flash for many years until a few months ago when I discovered p5. It's put a spring in my step. Thx.
