### ISSUE TITLE
Why are bezierDetail() / curveDetail() separate functions from bezier() and curve()?

### ISSUE THREAD

**Issue by indefinit** [processing/p5.js#1207]
Investigating these functions recently I realized both exist in the Processing Java api, however I wonder if we really need separate detail functions in p5.  A more javascript-y way would be to pass the detail as an optional parameter to the respective bezier or curve function, instead of storing the variable globally.  A large benefit of not storing bezier and curve details globally would be more testable/modular code.  That said, there could be something really obvious I'm missing which requires the storing of bezierDetail and curveDetail outside the function call.

**Comment by lmccart** [comment]
I agree, in terms of JS, I think this makes more sense to just pass it in. What does this mean for `curveTightness()`? I wonder if it gets confusing with so many arguments for the `curve()` or `bezier()` function for the user? Or does it make the optional args tricky to distinguish on the library side? @shiffman do you have any more insight into the decision to make these functions separate in Processing API?

**Comment by shiffman** [comment]
I don't, my guess is that it was just simpler to maintain and document in terms of having so many arguments (and the fact that multiple versions of the function have to be declared in Java as opposed to JS).   I suppose the code is probably a bit more readable with the separate function?   I'm not at all opposed to doing it differently here.

**Comment by indefinit** [comment]
Going to close this issue for now.  Maybe we can revisit down the line when a few of the other big tickets are closed :)  Thanks!
