### ISSUE TITLE
using beginShape() for both vertex and curveVertex in Webgl

### ISSUE THREAD

**Issue by parsoyaarihant** [processing/p5.js#1214]
It seems there is no provision to use curveVertex in p5 WEBGL mode.Hence, I would like to implement this functionality in p5 immediate mode. I submitted a PR( #1185 ) and need feedback if I can use the same approach as used in p5 2D mode.

**Comment by karenpeng** [comment]
@parsoyaarihant thanks! may I ask if it's based on @indefinit 's refactor?

**Comment by parsoyaarihant** [comment]
Yeah its related to webgl-geomerty-refractor branch

**Comment by indefinit** [comment]
Hi there.  Closing this Issue for administrative purposes.  Feel free to submit a PR for curveVertex() and bezierVertex().

**Comment by nippotam** [comment]
How to reopen it ?

**Comment by stalgiag** [comment]
Hi @nippotam `curveVertex()` works in WEBGL mode currently. [Here is the reference example running in WEBGL](https://editor.p5js.org/stalgiag/sketches/yAXEk9pO5). If you are having an issue with this feature you can open a new issue.

**Comment by nippotam** [comment]
Thank you @stalgiag  I will check and tell you
