### ISSUE TITLE
keyPressed event firing on each loop

### ISSUE THREAD

**Issue by indefinit** [processing/p5.js#1215]
I'm not sure if this is expected behavior but should the keyPressed() callback method be firing once per loop if a single key is pressed and held?  For example if I press and hold the 'o' key, my expectation is that the keyPressed() method will be called once and then when I release the 'o' key, the keyReleased() callback will fire once.  The actual behavior is that keyPressed() keeps firing as long as the key is down.

**Comment by limzykenneth** [comment]
I think it made sense to have it fire only once. This is also the behaviour described by the docs.

**Comment by lmccart** [comment]
yes this is a bug. keyIsPressed variable should be used to track constant state, keyPressed() should fire only once. I can look into this.

**Comment by lmccart** [comment]
just adding a test example here in case it's helpful
```javascript
function setup() {
  createCanvas(400, 400);
  background(200);
}

function keyPressed() {
  ellipse(random(width), random(height), 50, 50);
  console.log('press');
}

function keyTyped() {
  text(key, random(width), random(height));
  console.log('type');
}
```
