### ISSUE TITLE
feedback (previous frame)?

### ISSUE THREAD

**Issue by artofmus** [processing/p5.js#1217]
is it possible feedback texture in p5.js (get previous frame) for create dynamic system like CA or reaction diffusion? Thanks!

**Comment by lmccart** [comment]
you could save out the canvas image from the previous frame using get() and then do whatever you like with that. http://p5js.org/reference/#/p5/get

this sort of question is best posted in the forum: https://forum.processing.org/two/categories/p5-js, the github issues are just for code bugs. thanks!

**Comment by artofmus** [comment]
Ok. Thanks!
