### ISSUE TITLE
text() errors when font is loaded outside of preload() && preload() exists

### ISSUE THREAD

**Issue by brig002** [processing/p5.js#1218]
Hi. I'm getting the following error when loading a font outside of preload() and using loadFont() callback method to evaluate load complete:
Uncaught TypeError: Cannot read property '_renderer' of undefined

The error does NOT happen when preload() is NOT defined. Here's sample code demonstrating (what I think is) a bug: 

<pre>
//----------------DOES NOT WORK----------------
var isLoaded;
var myfonthandle;
function preload() {
 //do nothing
}
function setup() {
  var mycanvas = createCanvas(200, 200);
  myfonthandle = loadFont('assets/fonts/proxima-nova-bold.ttf', assetloaded); 
}
function draw() {
  if (isLoaded){
    textFont(myfonthandle);
    text("test", 100,100);
  }
}
function assetloaded(){
  isLoaded = true;
}
//----------------WORKS----------------
var isLoaded;
var myfonthandle;
function setup() {
  var mycanvas = createCanvas(200, 200);
  myfonthandle = loadFont('assets/fonts/proxima-nova-bold.ttf', assetloaded); 
}
function draw() {
  if (isLoaded){
    textFont(myfonthandle);
    text("test", 100,100);
  }
}
function assetloaded(){
  isLoaded = true;
}
</pre>

Issue described here in forum: https://forum.processing.org/two/discussion/14543/text-throws-an-error-when-font-loaded-outside-of-preload

**Comment by dhowe** [comment]
The error is due to a null _renderer here: https://github.com/processing/p5.js/blob/master/src/typography/p5.Font.js#L224, though not sure why an empty preload() function would result in a null renderer.

**Comment by dhowe** [comment]
The error is due to 'this' being undefined here: https://github.com/processing/p5.js/blob/master/src/io/files.js#L105 , though not sure why an empty preload() function would cause such a thing

**Comment by lmccart** [comment]
@dhowe's patch seems to have addressed this.
