### ISSUE TITLE
Chrome warning: security

### ISSUE THREAD

**Issue by arashsa** [processing/p5.js#1220]
When I use a p5js sketch on my website, I get the following error message when using chrome. 

"The deviceorientation event is deprecated on insecure origins, and support will be removed in the future. You should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details."

**Comment by limzykenneth** [comment]
This has been around for some time now, I was thinking about what we can do about this a few months ago and to be honest I don't think there is much we can do on our side. 

My prediction is that chrome won't be removing this support in the short term as too much stuff is dependent on all the mentioned events over HTTP. New services like https://letsencrypt.org will push it in the direction of removing support for it but not any time soon I think, given that Let's Encrypt only just entered public beta for less than two months and the other certificate authorities are still charging for signing certificates.

**Comment by arashsa** [comment]
Well, as long it is a warning, I guess it doesn't matter. I'll keep this open for more input on the matter.

**Comment by lmccart** [comment]
Yeah, I don't think there is much we can do. Chrome has already removed support for getUserMedia (capture), except on HTTPS or localhost. We should rethink the examples though, maybe moving p5js.org to HTTPS, and adding a note on affected example that they won't run on HTTP.
