### ISSUE TITLE
Inline documentation examples for p5.image methods

### ISSUE THREAD

**Issue by PaliwalSparsh** [processing/p5.js#1222]
There are no examples for many methods of p5.image. 
This is followup on issue https://github.com/processing/p5.js-website/issues/216.

**Comment by PaliwalSparsh** [comment]
@lmccart I have added almost all methods of p5.image. I would be thankful if you can suggest changes, if it needs some.
Also I would like to bring to you notice that Development Checklist is not fully up to date. These should be marked as done there -
save()
anglemode()
print()
loadJSON()
loadTable()
and also the ones in this PR if they get successfully merged :smile: .

**Comment by lmccart** [comment]
thanks! i've just updated this list based on your notes. also please feel free to edit directly in the future if you like. :)
