### ISSUE TITLE
Stability issues in Windows version

### ISSUE THREAD

**Issue by p5k12** [processing/p5.js#1224]
I'm running the latest version downloaded from p5js.org (0.5.7) on Windows 8 laptops and my students and I are finding that the program either locks  or stops producing output in the canvas  (a window opens but it doesn't even have a canvas in it).  In the latest case for me, I restarted the IDE and the code then worked fine.  It's so intermittent I don't know how to describe the problem usefully and I don't see where to pull an error message or 'status indicator' from.

**Comment by limzykenneth** [comment]
Seem like an editor issue, please post this to [the editor's repo](https://github.com/processing/p5.js-editor/issues) so they can be notified about this. Thanks.

**Comment by p5k12** [comment]
yup.  sorry.
