### ISSUE TITLE
contour plotting

### ISSUE THREAD

**Issue by rain1024** [processing/p5.js#1225]
It's would be great if you can support contour plotting like matplotlib

http://matplotlib.org/examples/pylab_examples/contour_demo.html

With this function, I can plot any function f(x, y), for example, draw egg curves http://www.mathematische-basteleien.de/eggcurves.htm

**Comment by lmccart** [comment]
interesting idea @rain1024. this is a bit beyond the limits of the p5.js core api, we like to keep it as simple and lean as possible, but this could be a great starting point for an addon library that does more complex plotting like this. if you're interested in making one of these, you can check out the tutorial here: https://github.com/processing/p5.js/wiki/Libraries
