### ISSUE TITLE
updatePixels(), createImage() and pixels[] reference example not working

### ISSUE THREAD

**Issue by PaliwalSparsh** [processing/p5.js#1226]
Example on reference page of
1. updatePixels() (http://p5js.org/reference/#p5/updatePixels)
2. createImage() (http://p5js.org/reference/#p5/createImage) third example is not working.
3. pixels (http://p5js.org/reference/#p5/pixels[])
All share same problem of using pixelDensity instead of pixelDensity().

@lmccart I feel I can fix this.

**Comment by PaliwalSparsh** [comment]
@lmccart I have sent a PR to fix this small issue.

**Comment by lmccart** [comment]
fixed with https://github.com/processing/p5.js/pull/1227
