### ISSUE TITLE
createGraphics() undefined

### ISSUE THREAD

**Issue by Triveri** [processing/p5.js#1237]
createGraphics() will be undefined unless used in setup() making it unusable in objects and other things

**Comment by limzykenneth** [comment]
As I remember, createGraphics() should work in other p5 methods such as draw() and mousePressed() as well. The problem you have might be you are trying to access p5 methods before p5 is initialized (in setup() usually). You can try ensuring the p5 object is initialized either with instance mode or by making sure setup is called before making other calls to createGraphics() in other objects etc. You can look at #903 about this. 

Let me know if that's not the case.

**Comment by toolness** [comment]
Hmm, it sounds like we should add `createGraphics` and, given #903, all of P5's constants to the list of symbols we provide error help for in #1130... And we should probably add a link in the friendly error message to the [FAQ question](https://github.com/processing/p5.js/wiki/Frequently-Asked-Questions#why-cant-i-assign-variables-using-p5-functions-and-variables-before-setup) that @limzykenneth just linked to!

**Comment by lmccart** [comment]
great. it sounds like the issue here is now covered in #1247, so i'm going to close this one.
