### ISSUE TITLE
Ctrl T reformat but don't open everything

### ISSUE THREAD

**Issue by rich-gg** [processing/p5.js#1239]
Spending a lot of time in P5 these days and it fell to me very painful have all my closed sections open each time I "Ctrl T".
What about having Ctrl-shift T to open everything and have Ctrl T  reformatting only open code ?

(this is my first ever contribution on GitHub, I wish I'm not messing around)

**Comment by limzykenneth** [comment]
Hello @rich-gg! Correct me if I'm wrong, I think you're referring to the p5 editor? If so there is a separate repo for it, you can copy and paste this issue [here](https://github.com/processing/p5.js-editor/issues) so that the editor team is notified of this. Thanks.

**Comment by rich-gg** [comment]
oops my mistake

thank you @limzykenneth
