### ISSUE TITLE
Installing  npm modules

### ISSUE THREAD

**Issue by GABBAR1947** [processing/p5.js#1240]
"https://github.com/processing/p5.js/wiki/Development " in the setup section, only asks to install grunt and npm. However there are several other npm and grunt modules to be downloaded in order to run the tests( or test online using connect -keepalive) . So why don't we add these modules to the page or run a script so that these modules get easily installed and the developers can easily get through the dev environment without facing many issues.
npm install browserify  derequire  jscs-stylish grunt-saucelebs
npm install jshint  --save dev jshint  brfs@1.0.2  lodash@4.0.0

**Comment by lmccart** [comment]
the line in step 4 `npm install` should handle installing all these modules for you automatically. did this not work?

**Comment by GABBAR1947** [comment]
no it doesn't .. It gives error later on when running grunt.

**Comment by lmccart** [comment]
hm im not able to reproduce. could you tell me more about the system you're working on? did you see an output like this when you ran `npm install`?
<img width="179" alt="screen shot 2016-02-09 at 10 11 53 pm" src="https://cloud.githubusercontent.com/assets/191056/12937791/3b6caafe-cf7a-11e5-88b2-7af5b261b521.png">

**Comment by GABBAR1947** [comment]
I use Ubuntu and the output was not in the same fashion as the snippet posted above. It didn't have so many modules and was limited to quite a few.

**Comment by lmccart** [comment]
could you paste the output here?

**Comment by GABBAR1947** [comment]
well, I've already installed the modules on my system. I'll do the same on some other system and paste the output.

**Comment by toolness** [comment]
Hmm, my [p5.js-docker](https://github.com/toolness/p5.js-docker) setup uses a debian image (Ubuntu is also debian-based) and it doesn't have this issue.

In general I'm surprised by the behavior of @GABBAR1947's system, as the way p5's package.json is doing things is generally an accepted convention...

**Comment by kadamwhite** [comment]
Could you try deleting the node_modules folder and running NPM install again?
