### ISSUE TITLE
Installing P5 through package.json

### ISSUE THREAD

**Issue by Z3R0c007** [processing/p5.js#1242]
After failed attempts installing p5 in the command line with npm, installing in the package.json also is failing. Win 10, Visual Studio 2015

`{
    "name": "BlankCordovaApp2",
    "version": "1.0.0",
    "dependencies": {
   "p5":"<latest stable version of package>"
    }
}`

error output

====Executing command 'npm install'====

npm WARN package.json BlankCordovaApp2@1.0.0 No description
npm WARN package.json BlankCordovaApp2@1.0.0 No repository field.
npm WARN package.json BlankCordovaApp2@1.0.0 No README data
npm http GET https://registry.npmjs.org/p5
npm http 200 https://registry.npmjs.org/p5
npm ERR! notarget No compatible version found: p5@'<latest stable version of package>'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.2.1","0.2.2","0.2.3","0.2.4","0.2.5","0.2.6","0.2.7","0.2.8","0.2.9","0.2.10","0.2.11","0.2.12","0.2.13","0.2.14","0.2.15","0.2.16","0.2.17","0.2.18","0.2.19","0.2.20","0.2.21","0.2.22","0.2.23","0.3.0","0.3.1","0.3.2","0.3.3","0.3.4","0.3.5","0.3.6","0.3.7","0.3.8","0.3.9","0.3.10","0.3.11","0.3.12","0.3.13","0.3.14","0.3.15","0.3.16","0.4.0","0.4.1","0.4.2","0.4.3","0.4.4","0.4.5","0.4.6","0.4.7","0.4.8","0.4.9","0.4.10","0.4.11","0.4.12","0.4.13","0.4.14","0.4.15","0.4.16","0.4.17","0.4.18","0.4.19","0.4.20","0.4.21","0.4.22"]
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\IDE\\Extensions\\Microsoft\\Web Tools\\External\\\\node\\node" "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\IDE\\Extensions\\Microsoft\\Web Tools\\External\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd M:\p5Test\BlankCordovaApp2\BlankCordovaApp2
npm ERR! node -v v0.10.31
npm ERR! npm -v 1.4.9
npm ERR! code ETARGET
npm

====npm command completed with exit code 1====

**Comment by kadamwhite** [comment]
Where did you get your package.json content from? `<latest stable version>` is meant to be a placeholder; the latest release I believe to be `0.4.22` at present, so you could try replacing `<latest stable version>` with `^0.4` and try again.

**Comment by Z3R0c007** [comment]
The json is loaded when you begin a Cordova project in Visual Studio 2015

I am a noob whenit comes to coding. Failing fast and faster. This the first time I have had to load a lib.

I did as you said and so far so good.

`{
    "name": "BlankCordovaApp2",
    "version": "1.0.0",
    "dependencies": {
   "p5":"~0.4.22"
    }
}`

error output
====Executing command 'npm install'====


npm WARN package.json BlankCordovaApp2@1.0.0 No description
npm WARN package.json BlankCordovaApp2@1.0.0 No repository field.
npm WARN package.json BlankCordovaApp2@1.0.0 No README data
npm http GET https://registry.npmjs.org/p5
npm http 304 https://registry.npmjs.org/p5
npm http GET https://registry.npmjs.org/brfs
npm http GET https://registry.npmjs.org/opentype.js
npm http GET https://registry.npmjs.org/reqwest
npm http 304 https://registry.npmjs.org/brfs
npm http 304 https://registry.npmjs.org/reqwest
npm http 304 https://registry.npmjs.org/opentype.js
npm http GET https://registry.npmjs.org/resolve
npm http GET https://registry.npmjs.org/through2
npm http GET https://registry.npmjs.org/static-module
npm http GET https://registry.npmjs.org/quote-stream
npm http 304 https://registry.npmjs.org/resolve
npm http 304 https://registry.npmjs.org/through2
npm http 304 https://registry.npmjs.org/quote-stream
npm http 304 https://registry.npmjs.org/static-module
npm http GET https://registry.npmjs.org/xtend
npm http GET https://registry.npmjs.org/readable-stream
npm http GET https://registry.npmjs.org/buffer-equal
npm http GET https://registry.npmjs.org/minimist
npm http 304 https://registry.npmjs.org/xtend
npm http 304 https://registry.npmjs.org/readable-stream
npm http 304 https://registry.npmjs.org/buffer-equal
npm http 200 https://registry.npmjs.org/minimist
npm http GET https://registry.npmjs.org/process-nextick-args
npm http GET https://registry.npmjs.org/isarray
npm http GET https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/core-util-is
npm http GET https://registry.npmjs.org/string_decoder
npm http GET https://registry.npmjs.org/util-deprecate
npm http 304 https://registry.npmjs.org/isarray
npm http 304 https://registry.npmjs.org/process-nextick-args
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/string_decoder
npm http 304 https://registry.npmjs.org/core-util-is
npm http 304 https://registry.npmjs.org/util-deprecate
npm http GET https://registry.npmjs.org/has
npm http GET https://registry.npmjs.org/concat-stream
npm http GET https://registry.npmjs.org/duplexer2
npm http GET https://registry.npmjs.org/object-inspect
npm http GET https://registry.npmjs.org/falafel
npm http GET https://registry.npmjs.org/escodegen
npm http GET https://registry.npmjs.org/shallow-copy
npm http GET https://registry.npmjs.org/static-eval
npm http 304 https://registry.npmjs.org/duplexer2
npm http 304 https://registry.npmjs.org/object-inspect
npm http 304 https://registry.npmjs.org/concat-stream
npm http 304 https://registry.npmjs.org/has
npm http 304 https://registry.npmjs.org/falafel
npm http 304 https://registry.npmjs.org/escodegen
npm http 304 https://registry.npmjs.org/shallow-copy
npm http 304 https://registry.npmjs.org/static-eval
npm http GET https://registry.npmjs.org/typedarray
npm http GET https://registry.npmjs.org/function-bind
npm http 304 https://registry.npmjs.org/typedarray
npm http 304 https://registry.npmjs.org/function-bind
npm http GET https://registry.npmjs.org/foreach
npm http GET https://registry.npmjs.org/acorn
npm http GET https://registry.npmjs.org/object-keys
npm http GET https://registry.npmjs.org/object-keys
npm http 304 https://registry.npmjs.org/foreach
npm http 304 https://registry.npmjs.org/object-keys
npm http 200 https://registry.npmjs.org/acorn
npm http 304 https://registry.npmjs.org/object-keys
npm http GET https://registry.npmjs.org/estraverse
npm http GET https://registry.npmjs.org/estraverse
npm http GET https://registry.npmjs.org/esutils
npm http GET https://registry.npmjs.org/esprima
npm http GET https://registry.npmjs.org/esprima
npm http GET https://registry.npmjs.org/source-map
npm http GET https://registry.npmjs.org/source-map
npm http 304 https://registry.npmjs.org/estraverse
npm http 304 https://registry.npmjs.org/estraverse
npm http 304 https://registry.npmjs.org/esutils
npm http 304 https://registry.npmjs.org/esprima
npm http 304 https://registry.npmjs.org/esprima
npm http 304 https://registry.npmjs.org/source-map
npm http 304 https://registry.npmjs.org/source-map
npm http GET https://registry.npmjs.org/amdefine
npm http 304 https://registry.npmjs.org/amdefine
p5@0.4.22 node_modules\p5
├── opentype.js@0.4.11
├── brfs@1.4.3 (quote-stream@1.0.2, resolve@1.1.7, through2@2.0.1, static-module@1.3.0)
└── reqwest@1.1.6

====npm command completed with exit code 0====

**Comment by limzykenneth** [comment]
@Z3R0c007 I'm not familiar with Cordova or Visual Studio so might want to take what I said with a pinch of salt. You are getting 304 which might be because the required files are cached somehow. Try `npm uninstall p5` then `npm install` again, keeping `package.json` as it is now.

The output should look something like this:

```
npm WARN package.json BlankCordovaApp2@1.0.0 No description
npm WARN package.json BlankCordovaApp2@1.0.0 No repository field.
npm WARN package.json BlankCordovaApp2@1.0.0 No README data
npm WARN package.json BlankCordovaApp2@1.0.0 No license field.
p5@0.4.22 node_modules/p5
├── opentype.js@0.4.11
├── reqwest@1.1.6
└── brfs@1.4.3 (resolve@1.1.7, quote-stream@1.0.2, through2@2.0.1, static-module@1.3.0)
```

**Comment by kadamwhite** [comment]
> `====npm command completed with exit code 0====`

Exit code 0 means "success"; from this output it looks like you ought to be good to go!

**Comment by Z3R0c007** [comment]
All right all good. Thanks @kadamwhite and @limzykenneth
