### ISSUE TITLE
rotationY range is from -90 to 90

### ISSUE THREAD

**Issue by aatishb** [processing/p5.js#1243]
In the p5.js [code](https://github.com/processing/p5.js/blob/master/src/events/acceleration.js) and in the [reference page](http://p5js.org/reference/#/p5/rotationY), the range of `rotationY` is assumed to be between -180 and 180 degrees. However, it looks like this variable is the same as [DeviceOrientationEvent.gamma](https://developer.mozilla.org/en-US/docs/Web/API/DeviceOrientationEvent/gamma), whose range is actually -90 to 90 degrees. That seems to agree with a [simple test](https://stc209.com/aatishb/graph_device_rotation/). I suspect this might also affect the deviceTurned() function.

**Comment by limzykenneth** [comment]
I think you're right, I'll have a closer look soon. Thanks.

**Comment by lmccart** [comment]
interesting.. thanks for reporting @aatishb, and for looking into this @limzykenneth!

**Comment by lmccart** [comment]
closed with https://github.com/processing/p5.js/pull/1258
