### ISSUE TITLE
Some documentation may be inaccessible

### ISSUE THREAD

**Issue by toolness** [processing/p5.js#1252]
I just noticed that the `data.json` blob generated to power the documentation has the following entry under the `classitems` array:

```json
{
    "file": "src/math/p5.Vector.js",
    "line": 976,
    "description": "Calculates the Euclidean distance between two points (considering a\npoint as a vector object).",
    "static": 1,
    "params": [
        {
            "name": "v1",
            "description": "the first p5.Vector",
            "type": "p5.Vector"
        },
        {
            "name": "v2",
            "description": "the second p5.Vector",
            "type": "p5.Vector"
        }
    ],
    "return": {
        "description": "the distance",
        "type": "Number"
    },
    "class": "p5.Vector",
    "module": "Math",
    "submodule": "Math"
}
```

The weird thing about this entry is that there's nothing about it that tells us what the *name* of the method being documented is. Going to the appropriate file and line number indicates that it's the documentation for `p5.Vector.dist`--the *static* method, not the *instance* one--but because it's nowhere in the `classitem` entry, I'm concerned that this may not actually be documented anywhere in the p5 docs... Is this intentional? Or is it actually documented somewhere that I'm unable to find?

If this is unintentional and I'm not mistaken, then I'm a bit surprised that YUIDoc isn't raising some kind of warning about this. I guess I could write an automated test that scours `data.json` to find "doc orphans" like this, if it's useful.

**Comment by lmccart** [comment]
this page is accessible... it pops up in search in the reference and is also linked from the p5.Vector page.
http://p5js.org/reference/#p5.Vector/dist

I think what's happening is that I hacked yuidoc a bit to conform to the format we wanted to match the processing reference. I think a byproduct of this is multiple entries getting added for one reference entry, even though only one is actually linked on the reference. it's worth cleaning up at some point, but I don't think anything is inaccessible right now, at least.

**Comment by lmccart** [comment]
I'm going to close this because I don't think anything is currently inaccessible, but please feel free to open another issue if there is something more specific to be addressed, or if I'm incorrect. :)
