### ISSUE TITLE
get() function for pixel data could be more efficient

### ISSUE THREAD

**Issue by spiricom** [processing/p5.js#1259]
It looks like the get() function (p5.Renderer2D.prototype.get) creates a temporary variable, loads all the pixel data from an image, finds the pixel, and then destroys the temporary array it made. I think it could be handy if you could pass this function the name of an array that you have already filled with the pixel data, which would make it more useful inside a loop (for instance, to downsample an image).

I'm not sure how this would be done in javascript. 

I imagine adding a fifth optional input argument to get(), so you could say 

get(x, y, 1, 1, myPixelArray);

 and it would skip the step of loading the pixel array and use the array reference you passed to it.

**Comment by lmccart** [comment]
get() is admittedly slower, prioritizing ease of use. if you are looking for optimization, i'd recommend accessing the pixel array directly. there is more info here: http://p5js.org/reference/#p5/pixels[]
hope this helps!
