### ISSUE TITLE
No way for add-on libraries to be notified of p5 instance construction

### ISSUE THREAD

**Issue by toolness** [processing/p5.js#1263]
I'm currently adding support for p5 instance mode to the p5.play add-on library at https://github.com/molleindustria/p5.play/pull/22.

At present, the library only supports p5 global mode, and needs to store a number of sketch-wide globals, such as `allSprites`, which is essentially a list of all sprites currently in the sketch. Its current assumptions about p5 always being in global mode means that it can simply use a global variable for this.

However, things get tricky when adding support for p5 instance mode: ideally, the `allSprites` variable should simply be a property of the `p5` instance that is initialized to an empty list when a new `p5` instance is constructed.

However, as far as I can tell, there is actually no way to "hook into" the p5 construction process. While [`registerMethod()` provides a way to register functions with p5 that should be called at various times](https://github.com/processing/p5.js/wiki/Libraries#use-registermethod-to-register-functions-with-p5-that-should-be-called-at-various-times), there does not seem to be a method name that allows the library to execute initialization code when the p5 instance is first created.

Overwriting or "wrapping" the `p5` constructor itself seems error-prone for a number of reasons, which I won't enumerate here.

My current workaround for this limitation is to call [`Object.defineProperty()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty) on `p5.prototype`, and set it up to lazily create `allSprites` when it's first accessed. I guess this is potentially more efficient than initializing the property when a p5 instance is first created, but it's also more work for library authors. It also feels a bit hackish to call `Object.defineProperty()` on a prototype object rather than directly on an object instance, but I could be wrong.

Perhaps an additional `registerMethod()` name should be added, e.g. `"create"`, that allows libraries to execute code on p5 instance construction? Or does some functionality already exist that I'm unaware of? Or, alternatively, should we simply expect library authors to define sketch properties lazily, as I've done with p5.play?

**Comment by lmccart** [comment]
I think an additional `registerMethod()` makes most sense. This part of the API is still in the early stages and welcome to expansion. Do you want to take a crack at this or should I?

Let's be sure to document this method here: https://github.com/processing/p5.js/wiki/Libraries

**Comment by willmartindev** [comment]
Hi @lmccart, I am trying to visit the library documentation link above but it looks like it was removed. Is this method documented anywhere else?

**Comment by limzykenneth** [comment]
@willmartindev Have a look [here](https://github.com/processing/p5.js/blob/main/contributor_docs/creating_libraries.md).
