### ISSUE TITLE
String methods

### ISSUE THREAD

**Issue by PaliwalSparsh** [processing/p5.js#1265]
I was going through the [reference of processing.py](http://py.processing.org/reference/) and saw some String methods that are not here in p5.js. Can we implement them in p5-
find()
upper()
lower()
startswith()
replace()
strip()

**Comment by hkirat** [comment]
I think javascript has some pre built methods.
Eg : toUpperCase(), toLowerCase, split(), substr().
I'm not sure if there exists a pattern matching method like find().
That can be fun to implement.Using string matching algorithms like KMP.

**Comment by lmccart** [comment]
this page you linked it the processing python reference. i don't think they are included in the [processing reference](https://processing.org/reference/). what we've provided in terms of strings feels pretty good right now in terms of scope and matching processing, for any further functionality I would check out the native JS methods that @hkirat points out: http://www.w3schools.com/jsref/jsref_obj_string.asp

**Comment by limzykenneth** [comment]
@hkirat yup, native js have find as well `indexOf()`
