### ISSUE TITLE
Trigonometric functions

### ISSUE THREAD

**Issue by DarkPrince304** [processing/p5.js#1266]
Hello,

I was going through the processing reference and there I found some trigonometric functions like acos, radians, etc

Even though functions for these are there in JavaScript would it make sense to implement these for p5 as well so as to make it more similar to processing?

**Comment by PaliwalSparsh** [comment]
@DarkPrince304 We do have these functions in p5 infact all the trigonometric functions.
[acos](http://p5js.org/reference/#/p5/acos), [radian](http://p5js.org/reference/#p5/radians).
You can find them on the reference page in the Trigonometry subsection under Math section.

**Comment by DarkPrince304** [comment]
Woops my bad! Didnt look hard enough I guess. I'll close this then.
