### ISSUE TITLE
touchX/touchY or mouseX/mouseY reporting wrong in iOS 7.0.x

### ISSUE THREAD

**Issue by noisefactor** [processing/p5.js#1269]
I believe I've discovered a bug that affects iOS (at least version 7.0.x) and possibly other mobile contexts.  When I try to use touchStart() (or mousePressed()) to get the current touchX or mouseX it reports the previous touch position instead of the current touch position.  

Tapping an iPad or iPhone like mine with this simple demo page shows the x and y coordinates reported in the title area.  (The problem doesn't occur in the desktop/laptop view of the page.)

   http://artcontext.org/act/96/draward/foo.html

function setup(){
   createCanvas(500,500);
}
function draw(){
	background("blue");
}
function touchStarted(){
     document.title=(touchX+" "+touchY);
}

**Comment by hkirat** [comment]
you are using the wrong function..
It shouldn't work in any device whatsoever.
Use the touchEnded function instead of touchStarted function..
Should work fine.

**Comment by noisefactor** [comment]
Perhaps some background would help.  My line drawing tools have init() and draw() methods.  What I do (that works for desktop and laptop modes of p5) is I use the mousePressed() function to trigger the init() method and this establishes the current, starting position of the line.  Subsequent mouseMove (drag) events then continue the line until the mouseReleased() event fires.

I think your interpretation of the problem is that I'm just trying to click someplace and find out where the click occurred.  But I am not seeking a position from a tap (click) event, really: I'm seeking the starting point of a new line (and I assume the touch event continues from the point of the tap).  I don't see how your suggestion could solve the problem that I'm having, or why the touchStarted() function should be returning stale positional data. I'm drawing lines and the problem that I have is that (only on iOS that I know of so far) both mousePressed and touchStarted fail to give me the actual position of the touch, which is needed by the line drawing that follows the initial touch.

**Comment by noisefactor** [comment]
Adding the **bold** lines below to p5.js made things work the way I think they should.  It would appear someone thinks it's fine to wait until the draw() method updates these values, but I would tend to disagree with that strategy.  I don't fully understand the event model, but I do think it's logical that the touchX, touchY, mouseX, mouseY variables are updated when the ontouchstart function fires.

p5.prototype._ontouchstart = function(e) {
  var context = this._isGlobal ? window : this;
  var executeDefault;
  this._updateNextTouchCoords(e);
  this._updateNextMouseCoords(e);
  **this._updateMouseCoords(e);
  this._updateTouchCoords(e);**

**Comment by hkirat** [comment]
ok now I got what you are trying to achieve.
found a method to fix this 
Adding the following condition in p5.prototype._updateMouseCoords() makes it work fine
if (e.type === 'mousedown') {
        this._setProperty('touchX', e.clientX);
        this._setProperty('touchY', e.clientY);
    }
Though I'm not sure if this is the right way to fix it

**Comment by hkirat** [comment]
@lmccart Is this the right way to fix this ^ ?

**Comment by lmccart** [comment]
thanks @hkirat and @noisefactor. i'd like to look into this one, because there are some slightly complex dependencies with this. i aim to get to it next week.

**Comment by hamoid** [comment]
Is there a workaround for this we could use until a fix is released?

**Comment by lmccart** [comment]
To give some background, the vars mouseX/Y and touchX/Y are not updated at the time of event, but at the start of the draw call. This was implemented to address this issue. https://github.com/processing/p5.js/issues/1176

I'm not sure what the proper solution to deal with this is, I need to look at all the use cases a little more and figure out when the vars should actually be updated. For now, I think you could manually apply the patch that @hkirat mentions, and this would solve the case mentioned in this issue, it would just add back in the problem from #1176.

**Comment by hamoid** [comment]
Thanks! Knowing that, what I did was to set a flag onTouchStarted(), and only read the coordinates inside draw() if that flag is true. That's a simple workaround. It's just for a one-user control panel of an art installation, so I don't have to break any world records on performance :)

**Comment by lmccart** [comment]
aha great. and thanks for bumping this, it seems to have slipped my todo queue.

**Comment by noisefactor** [comment]
I think maybe it doesn't necessarily reintroduce the old problem because I was only having trouble with touch start events on iOS. The behavior on desktop browsers was right.  Maybe the place to fix/address this is in touch start handling?

**Comment by lmccart** [comment]
fixed with https://github.com/processing/p5.js/pull/1471
