### ISSUE TITLE
CurrentTime is to small on PC

### ISSUE THREAD

**Issue by benoitwimart** [processing/p5.js#1272]
Wish this is the place to report bug.
I make some test and with a window.setTimeout(callback, 1000 / 60) at 60fps.
For a sound with a duration of 30s, last value of `audio.currentTime()` is 28s on PC (30 on Mac), I do a script without  p5js and `audio.currentTime` (not the function) is 30s…

http://jenseign.com/p5test/
http://jenseign.com/p5test/index-2.html (without p5js)

**Comment by limzykenneth** [comment]
Hmm...I don't have a PC so I can't test this and so I can't be sure if it's a problem with `currentTime()` or with `setTimeout()`. In any case this is the place to report bug but this seem to be a problem of p5sound and you'll get better help there. Just copy and paste this issue [here](https://github.com/processing/p5.js-sound/issues) the people working on p5sound should be able to help you there.

**Comment by benoitwimart** [comment]
thank you
