### ISSUE TITLE
Package on NPM is latest?

### ISSUE THREAD

**Issue by mactkg** [processing/p5.js#1273]

**Comment by mactkg** [comment]
oops. I missed operation...
I'm using p5.js with browserify.  So I downloaded p5.js package from npm, but scripts inside package seems to be old.
the big problem to me is transform(x, y) call console.log() every time.

I don't know about admin side of npm, but I think there is something wrong on npm.
Anyone knows an information about that?

**Comment by limzykenneth** [comment]
@mactkg Did you mean `translate(x,y)`? I can't find any console.log statement anywhere in the transform source code though. I think the problem might be somewhere else in the source code as every time I ran the test, the unminified library always throws out some console.log statement and I still couldn't figure out where they are, perhaps this would be a good starting point...

**Comment by mactkg** [comment]
thanks Kenneth! I'll re-check my environment and report the status...

2016年2月26日金曜日、Kenneth Lim<notifications@github.com>さんは書きました:

> @mactkg <https://github.com/mactkg> Did you mean translate(x,y)? I can't
> find any console.log statement anywhere in the transform source code
> though. I think the problem might be somewhere else in the source code as
> every time I ran the test, the unminified library always throws out some
> console.log statement and I still couldn't figure out where they are,
> perhaps this would be a good starting point...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/processing/p5.js/issues/1273#issuecomment-189239343>.
>


-- 
原 健太
明治大学総合数理学部 先端メディアサイエンス学科 渡邊研究室

090-1104-8196
mactkg@gmail.com

**Comment by lmccart** [comment]
hi @mactkg I think I messed up the last npm release and included the old lib. I'll post a new one today or tomorrow.

**Comment by mactkg** [comment]
@lmccart thanks!

**Comment by mactkg** [comment]
I confirmed. thanks.

**Comment by mactkg** [comment]
To avoid same mistakes, we should use some supporting tools such as [semantic-release](https://github.com/semantic-release/semantic-release).
the tool support releasing operation.  If I have a free time, I'll research these goods and make pull-request to use them.

**Comment by lmccart** [comment]
that'd be great. ideally the whole release process (or most of it at least) could be automated. right now there are many steps: https://github.com/processing/p5.js/wiki/Release-steps.

**Comment by mactkg** [comment]
:eyes:

**Comment by lmccart** [comment]
sorry, i didn't mean to suggest that you need to figure out the automation of the whole process. just that is a todo that i'm hoping to conquer at some point. :) any progress in terms of just automating a few of the steps would be helpful.

**Comment by mactkg** [comment]
yeah, Don't worry! (but I'm interested in automation of releasing process.)
