### ISSUE TITLE
get()/loadPixels() with Capture

### ISSUE THREAD

**Issue by keithohara** [processing/p5.js#1274]
I have run into a problem using `get()` with the webcam. It looks like the size of the capture/canvas (`capture.elt.width = 0` in `loadPixels()`) might be the culprit.  Explicitly calling `size()` seems to be a workaround (or maybe that's required). 

Google Chrome gives me:

     Uncaught IndexSizeError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source width is 0.
     p5.Renderer2D.loadPixels @ p5.js:14453
     p5.MediaElement.loadPixels @filip      p5.dom.js:1685
     p5.Renderer2D.get @ p5.js:14417
     p5.MediaElement.get @ p5.dom.js:1697
     mousePressed @ palube.js:17
     p5._onmousedown @ p5.js:18491

https://jsbin.com/palube/edit?js,output

    var capture;
    var last_img = null;

    function setup() {
       createCanvas(640, 480);
       capture = createCapture(VIDEO);
       //capture.size(width, height);  //workaround
       capture.hide();
     }

    function draw() {
      if (last_img) image(last_img, 0, 0, width, height);
      else if (capture) image(capture, 0, 0, width, height);
    }

    function mousePressed() {
      last_img = capture.get(0, 0, width, height);
    }

**Comment by Craigson** [comment]
Reopening the issue until #1079 is solved in such a way that no longer causes the problem referenced in this one.
