### ISSUE TITLE
Latest version failed to load

### ISSUE THREAD

**Issue by karneaud** [processing/p5.js#1277]
Hello,

I'm using the latest CDNJS versions of ** p5j, psjs.dom and p5js.sound** to run my application however. When loading the page in the browser it doesn't execute the `setup`, `preload` or `draw` functions.

If I used a previous version ( 0.4.0) I get it going but with errors. 

It seems that there maybe a bug or some packaging error on the server maybe?

**Comment by karneaud** [comment]
The following combination seemed to have worked

`<script src="//cdnjs.cloudflare.com/ajax/libs/p5.js/0.4.0/p5.js"></script>

		<script src="//cdnjs.cloudflare.com/ajax/libs/p5.js/0.4.0/addons/p5.dom.js"></script>
		<script src="//cdnjs.cloudflare.com/ajax/libs/p5.js/0.4.20/addons/p5.sound.js"></script>`

**Comment by lmccart** [comment]
i'm sorry i'm not able to reproduce. are you running a server? are there any errors in the console?

**Comment by karneaud** [comment]
At the time i was compiling p5j using bower/ node and there were some compiling errors that made it difficult to integrate hence errors with it
