### ISSUE TITLE
Make loadTable work with semicolon separated values

### ISSUE THREAD

**Issue by Niels-NTG** [processing/p5.js#1279]
Currently p5 only supports loading comma and tab separated values with the `loadTable()` function. It would be very useful if this method would also support files that use a semicolon delimiter, since those are quite common.

**Comment by lmccart** [comment]
thanks for the suggestion. for sake of limiting the API and codebase to a maintainable size, I'd prefer to stick with matching the Processing support on this one for now. https://processing.org/reference/loadTable_.html
