### ISSUE TITLE
Refrence index page contains wonky info on Bezier curves and more

### ISSUE THREAD

**Issue by toolness** [processing/p5.js#1289]
It seems like the `<br />`'s in the description for `bezier()` in `src/core/curves.js` is somehow causing some of its documentation to bleed onto the [main reference page](http://p5js.org/reference/):

![2016-03-05_15-32-40](https://cloud.githubusercontent.com/assets/124687/13550263/d6c7c9d6-e2e7-11e5-824e-0848bf5808b4.png)

Removing both the `<br />`'s removes the bug, but it also makes it so there's no visual paragraph break in the documentation for `bezier()` anymore too, so I'm not sure what the best solution is.

It looks like those two `<br />`'s have been there since 22e9318f9604ba8e5f94fc44071afebbdfe23ea3, which was made in August of last year, so whatever's causing the problem is probably somewhere else.

It seems like this kind of thing is causing *lots* of bleeding of other methods' docs onto the main reference page, actually...

This is maybe a bit related to #1190.

**Comment by lmccart** [comment]
interesting... does `<br>` without the / cause the problem as well?

**Comment by toolness** [comment]
Oh! It's due to 83041436015d88da5f654c294b8bbac9c0561fd9 I think.

We're not escaping the descriptions for the tooltips, so the `<br />`'s in the middle of HTML attribute values are making the browser's HTML parser explode.

One way to fix this is to simply HTML-escape the descriptions, but this will make the literal `<br />` show up in the tooltip, which I guess is better than keeping this bug around. Ideally though I guess we'd use something like a [`striptags`](https://docs.djangoproject.com/es/1.9/ref/templates/builtins/#striptags) filter to remove the HTML formatting. Since we're in the browser we could probably just do this with some DOM manipulation but I'm not sure how it would affect performance.

**Comment by toolness** [comment]
> interesting... does `<br>` without the / cause the problem as well?

Yep :frowning:

**Comment by lmccart** [comment]
ah makes sense, ok. thanks for the quick fix.
