### ISSUE TITLE
Interface with intel edison

### ISSUE THREAD

**Issue by rahul2704** [processing/p5.js#1292]
Hello there. I want to pair the intel edision connected to some sensors and peripherals to a computer running p5.js script in browser via node.js/ websocket. 
Any sample code on how to easily acquire values from intel edison board and input directly in p5 script?
Thanks

**Comment by kadamwhite** [comment]
@rahul2704 I'm not sure how you would do this directly from the browser, but what  I would recommend would be to use Johnny Five (http://johnny-five.io/platform-support/#intel-edison-arduino) to communicate with the Edison, then stream those values from a small node server to the browser via a Web socket connection. There may be a way to cut out one of those levels of abstraction, devices aren't my area of expertise; but Johnny Five is your best bet for device communication!

Hope that helps somewhat

**Comment by indefinit** [comment]
Another option would be to look at p5.serial or p5.bots.  You can find out more about these p5 specific libraries here:

http://p5js.org/libraries/

**Comment by rahul2704** [comment]
thanks for the help. I will look into it.
