### ISSUE TITLE
Need suggestion to handle drag and drop on html page that mix up with p5

### ISSUE THREAD

**Issue by stevewmli** [processing/p5.js#1296]
Hi all,

I am trying to add p5  to an existing page with drag and drop function.
I noticed that when we drag and drop on the html page, it trigger some error on the getTouchInfo function in p6:

Uncaught TypeError: Cannot read property '0' of undefined
getTouchInfo @ p5.js:19904
66.p5._updateNextTouchCoords @ p5.js:19881
65.p5._onmousemove @ p5.js:19544 

Is there a way to control p5 not to trigger the drag and drop or only handle the drag and drop in p5 canvas? Thanks.

Best Regards,
Steve

**Comment by lmccart** [comment]
hi, could you please post a minimal code example that illustrates the problem? thanks!

**Comment by stevewmli** [comment]
Hi Imccart,

Could you try this fiddle:
https://jsfiddle.net/steve_wmli/wpuwpgj1/9/

I have setup functions to handle drag and drop. When dragging the "Drag Me" label, you will see the 
TypeError message in Developer Tools. Thanks.

Best Regards,
Steve

**Comment by dereklin** [comment]
+1  I am having the exact problem @stevewmli  thank you for putting together the fiddle
