### ISSUE TITLE
Open previous sketch at startup

### ISSUE THREAD

**Issue by Geoffree3** [processing/p5.js#1297]
It would be nice if the last sketch you were working on opened up when starting the P5 editor, rather than having to selected it from Open Recent and then have to close the default one.  Working on a project with multiple developers (using GitLab), we have to close and reopen the editor everytime a commit has been made.

**Comment by limzykenneth** [comment]
I think it should be possible and would be expected behaviour (for me at least). However, this is the repo for the p5.js library. You can just copy and paste this suggestion over [here](https://github.com/processing/p5.js-editor/issues) at the editors repo.

**Comment by lmccart** [comment]
i believe this is already the current behavior. the only time it won't reopen a sketch is if you close it before closing p5, which makes sense to me. if you are noticing this isn't working, could you note your OS and post it at the link @limzykenneth provided? thanks!

**Comment by Geoffree3** [comment]
Many thanks. As you suspected, I was closing the sketch with the sketch’s close button, which closed the editor!
