### ISSUE TITLE
CheckBox - label does not move when check box is re-positoned

### ISSUE THREAD

**Issue by config2000** [processing/p5.js#1300]
Here, the checkbox is initially located with the label adjacent, but when the check box is re-positioned the label stays in its original place.

var cb;

function setup() {
	cb=createCheckbox('toggle');
	cb.position(50,40);
}

**Comment by limzykenneth** [comment]
Confirmed on my side. I think the reason is that the checkbox and its label are created as two seperate element and when moving one, the other will not moved:

```
<input type="checkbox" id="7bguunz6wya" value="toggle" style="position: absolute; left: 50px; top: 40px;">
<label for="7bguunz6wya">toggle</label>
```

if instead the checkbox is nested in the label, it would work as expected:

```
<label for="73m7x78k7o4" style="position: absolute; left: 50px; top: 40px;"><input type="checkbox" id="73m7x78k7o4" value="toggle">toggle</label>
```

I'll try making this change and see if anything breaks...
