### ISSUE TITLE
Recommend entry for draw()

### ISSUE THREAD

**Issue by limzykenneth** [processing/p5.js#1301]
I just remembered/realized that even if `noLoop()` is called in `setup()`, the `draw()` function will still be called once before stopping. The documentation didn't make it clear I think (same as Processing's). Would it be desired to just add a line about this behaviour or is it just me that's finding it a bit unintuitive? :P

**Comment by lmccart** [comment]
that'd be great. and yes, this does match processing, i believe.

**Comment by limzykenneth** [comment]
Been awhile I encountered this problem in Processing but it's the same behaviour yeah. Just submitted a PR.

**Comment by lmccart** [comment]
closed with #1302
