### ISSUE TITLE
keyCode values

### ISSUE THREAD

**Issue by config2000** [processing/p5.js#1306]
A great and simple site to refer to for keyCode values is:

[keycode.info](url)

The site simply shows the value of the key code when you press a key.

Please add this link to the **KeyPressed()** and **keyIsDown()** help pages, or wherever the keyCode is mentioned.
Thanks in advance, Jim

**Comment by fega** [comment]
awesome! thanks

**Comment by limzykenneth** [comment]
If I'm not wrong the `keyCode` variable is meant to behave a bit differently than the native implementation of JS `keyboardEvent.keyCode` which is used in the site you provided. The p5 implementation uses the variables set out [here](http://p5js.org/reference/#p5/keyCode).

Also, the native JS `keyCode` variable is already [deprecated](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode) and the support across browsers are inconsistent, you should use `charCode` instead if you want a representation of ASCII number with their respective character.

**Comment by limzykenneth** [comment]
If you need representation of ASCII characters and their number code, you can look at [charCodeAt](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/charCodeAt) or [fromCharCode](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/String/fromCharCode)

**Comment by lmccart** [comment]
thanks @limzykenneth your are correct about `keyCode`. helpful links all around. :)

**Comment by lberdugo** [comment]
Is there any support for the 'command' key (U+2318 )? This is excluded from the variable list of [P5's implementation](url).
