### ISSUE TITLE
BezierVertex Broken in WebGL

### ISSUE THREAD

**Issue by thatcort** [processing/p5.js#1307]
When I run the following code I get the exception "p5.js:16790 Uncaught vertex() must be used once before calling bezierVertex()".

```
var s = function(p) {
 
    p.setup = function() {
        p.createCanvas(500, 500, p.WEBGL);
        p.stroke(0); 
        p.fill(150);
    }
 
    p.draw = function() {
        p.background(255);
        p.beginShape();
        p.vertex(30, 20, 0);
        p.bezierVertex(80, 0, 80, 75, 30, 75);
        p.bezierVertex(50, 80, 60, 25, 30, 20);
        p.endShape();
    }
}

``` 
var myp5 = new p5(s);

**Comment by indefinit** [comment]
Thanks for filing.  bezierVertex is not yet implemented in webgl, however it is on our road map.  In the meantime, try the bezier() function, which works like this reference example with the addition of z coords:
http://p5js.org/reference/#/p5/bezier
