### ISSUE TITLE
Video Canvas example not working

### ISSUE THREAD

**Issue by dpren** [processing/p5.js#1309]
[DOM Video Canvas Example](http://p5js.org/examples/examples/Dom_Video_Canvas.php)

The video isn't showing for me. (Chrome, Firefox)

**Comment by limzykenneth** [comment]
I fixed it by adding `fingers.loadPixels()` to the beginning of `draw()`, to be honest I don't know why that works. I think something probably needs changing in the source, I'm not sure.

**Comment by lmccart** [comment]
should be fixed now with the latest lib version
