### ISSUE TITLE
p5.sound.js too much recursion error when calling onended listener

### ISSUE THREAD

**Issue by matomasiar** [processing/p5.js#1310]
I've got an error when trying to call onended listener while playing a soundFile.

Error: too much recursion
Source File: .../p5.sound.js
Line: 1306

This happens when the end of soundFile is reached.

I'm not skilled enough to find a problem or find a solution.

**Comment by limzykenneth** [comment]
@matomasiar Do you have a sample code that this problem is occurring on that we can test? Also there is a dedicated repo for p5-sound, you can just copy and paste this issue over [here](https://github.com/processing/p5.js-sound/issues) to get more specific help on this.

**Comment by matomasiar** [comment]
I found the problem. Unfortunately, it looks like it was my fault. In callback function I called soundFile.stop()
Sorry for wasting your time.
