### ISSUE TITLE
loadPixels() on graphics buffer

### ISSUE THREAD

**Issue by riastroes** [processing/p5.js#1311]
the loadPixels() function on a graphics buffer isn't working.

var pg = createGraphics(100, 100);
pg.loadPixels();
result:    pg.pixels.length = 0

**Comment by lmccart** [comment]
fixed with db5418d54d3c13844bdba1fe679cd80594355ad0

**Comment by riastroes** [comment]
Great! Thanks a lot!
Ria

Op donderdag 28 april 2016 heeft Lauren McCarthy <notifications@github.com>
het volgende geschreven:

> fixed with db5418d
> <https://github.com/processing/p5.js/commit/db5418d54d3c13844bdba1fe679cd80594355ad0>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/processing/p5.js/issues/1311#issuecomment-215506544>
>


-- 

Met vriendelijke groet,


Ria Stroes





De Hege Bouwen 37
8566 JB Nijemirdum

website: www.riastroes.nl
@:         riastroes@gmail.com <rstroes@compano.com>
Tel:        0514 785172
