### ISSUE TITLE
p5 initializes constants on prototype during instantiation

### ISSUE THREAD

**Issue by toolness** [processing/p5.js#1312]
As noted in https://github.com/processing/p5.js/pull/1256#discussion_r52829838, for some reason the constants in [`src/core/constants.js`](https://github.com/processing/p5.js/blob/f1335ba8e65ea391712ff060ffe5c7ee850ba9b9/src/core/constants.js) are added to `p5.prototype` during instantiation of the first p5 sketch, rather than during the definition of `p5.prototype`.

Among other things, this requires workarounds in code that wants to use the constants but executes before the instantiation of the first p5 sketch, such as:

* The friendly error system - https://github.com/processing/p5.js/pull/1256
* Third-party libraries like p5.play - https://github.com/molleindustria/p5.play/pull/52

**Comment by lmccart** [comment]
This patch should address this issue, but I'm wondering if it would make sense for lines [148-180](https://github.com/processing/p5.js/commit/092a7192992eb626b71e18d50f0eb70fc15009af#diff-dfe07c186488ee794e2200e24b2bd54aR148) to also move outside of the constructor, just to have everything in the same place?

**Comment by toolness** [comment]
Oh cool, thanks!

Hmm, aren't lines 148-180 defining properties that are actually specific to p5 instances, rather than attached to the prototype like the constants are? For example, `this._loop` (line 157) might be true for one sketch but false for another... While on the other hand `PI` should always have the same value regardless of the sketch?

That said, I could see an argument for attaching them to the prototype so that new instances inherit their default values, but I feel a bit queasy about doing this with properties that are mutable objects. For instance, moving `this._events` (line 163) to the prototype means that assigning to `this._events.blur` would set it for *all* sketches...

**Comment by lmccart** [comment]
Yes, ah good point. I'll leave as is. I think this one is all set then.
