### ISSUE TITLE
createRadio not working

### ISSUE THREAD

**Issue by murtuza-shergadwala** [processing/p5.js#1315]
Hi,
I am trying to use the dom library and create radio buttons. Could someone please give an example of how to use createradio please?

**Comment by lmccart** [comment]
eek this is not well documented, sorry about that. here is an example for now... I'll post more documentation to the reference later this week.
```javascript
var radio;

function setup() {
  radio = createRadio();
  radio.option("black");
  radio.option("white");
  radio.option("gray");
  textAlign(CENTER);
  fill(255, 0, 0);
}

function draw() {
  var val = radio.value();
  background(val);
  if (val) {
    text(val, width/2, height/2);
  }
}
```
