### ISSUE TITLE
Embedded example link broken on Page: Embedding p5.js 

### ISSUE THREAD

**Issue by rholberton** [processing/p5.js#1323]
On Page: Embedding p5.js
https://github.com/processing/p5.js/wiki/Embedding-p5.js

Broken link:
"And here it is embedded in wordpress using the code below:
http://lauren-mccarthy.com/inmotion/2014/08/test-post-1/“

**Comment by lmccart** [comment]
thanks! updated here: https://github.com/processing/p5.js/wiki/Embedding-p5.js, noting @toolness's latest p5.js-widget option as well.
