### ISSUE TITLE
add example and clearer documentation for saveFrames()

### ISSUE THREAD

**Issue by marcelo-tento** [processing/p5.js#1324]
According to the reference the syntax is this: saveFrames(filename,extension,_duration,_fps,callback)

I can not write with the callback option

pliss example  ;-)

**Comment by limzykenneth** [comment]
@marcelo-tento I might be assuming a lot here so let me know if so :wink: 

`saveFrames()` have quite a specific use case which is when you want more granular control over how you save the images. The callback is actually optional (documentation isn't that clear about it, I'll fix it right away). Without the callback the images will be downloaded much like calling `save()`. With the callback provided the image data isn't saved by default but instead pass as an argument to the callback function as an array of objects, with the size of array equal to the total number of frames. I won't go into much detail here as how you manipulate the objects are quite complicated (I don't even do it myself most of the time :P)

An example with callback function is as follow:

```
function setup() {
  createCanvas(100, 100);
  noStroke();
  fill(0);
  rect(25,25,50,50);
  noLoop();
}

function draw() {
	saveFrames("out", "png", 1, 25, function(data){
		console.log(data);
	});
}
```
This will pass an array of length 25 as the argument `data` in the callback function and log it to the console.

Having said all that, `save()` some times might be a better solution to what you are trying to achieve, it depends. Also this question might be better suited to the [forum](https://forum.processing.org/two/categories/p5-js) unless it's a bug but it's still good that at least we know the documentation is lacking a bit. Cheers.

**Comment by marcelo-tento** [comment]
Many thanks for the reply

**Comment by lmccart** [comment]
thanks @limzykenneth! I'm updating the name of this issue to reflect the todo -- updating the saveFrames documentation.
