### ISSUE TITLE
p5 instance constructor isn't in reference documentation

### ISSUE THREAD

**Issue by toolness** [processing/p5.js#1327]
I was trying to figure out how to tell p5 where to display itself on the page when I realized that it's the second argument to the `p5` constructor itself. However, I had to learn this by looking at [`src/core/core.js`](https://github.com/processing/p5.js/blob/master/src/core/core.js)... It doesn't seem like the `p5` instance constructor has an entry in the reference documentation?

I also looked at the documentation for `createCanvas()`, hoping that it might offer some clues as to where to specify a container element for the canvas or something... If we think others might look there too, we might want to link to the appropriate documentation from there as well, maybe?

**Comment by lmccart** [comment]
Aha yes, it should definitely be there. I wonder if it makes more sense to include it in the reference or to add it to the wiki page about instance mode? (I guess we don't actually have a page just about instance mode, do we need one? Right now we have [instantiation cases](https://github.com/processing/p5.js/wiki/Instantiation-Cases) and a section in [p5.js overview](https://github.com/processing/p5.js/wiki/p5.js-overview#instantiation--namespace).)

In any case, I think we should also try to add more links back to this wiki page in places people might look for this info (`createCanvas()` for example).

**Comment by toolness** [comment]
Hmmmm good question!  Would it be overly redundant to put it in both the reference and the wiki page?  Seems like it might be more likely for others to find it if it's in both places but I dunno.

**Comment by shiffman** [comment]
In case this is helpful, I recorded a video tutorial about "instance mode" which could be added to the wiki?

https://youtu.be/Su792jEauZg

**Comment by Kinrany** [comment]
Added a few lines to [Global and instance mode](https://github.com/processing/p5.js/wiki/Global-and-instance-mode) to mention p5 constructor's second parameter options.
