### ISSUE TITLE
Make it possible to pass a character into keyIsDown()?

### ISSUE THREAD

**Issue by toolness** [processing/p5.js#1332]
I wanted to provide [WASD controls](https://en.wikipedia.org/wiki/Arrow_keys#WASD_keys) in addition to arrow keys for a sketch I was making, and realized that there doesn't seem to be an easy way to detect to see if these alphanumeric keys are pressed, other than logging [`keyCode`](http://p5js.org/reference/#/p5/keyCode) when keys are pressed and using that to figure out what a key you want to use is.

What if we allowed for e.g. `keyIsDown('a')`? Would that be weird?

Another option is to define named constants for every single alphanumeric key, I guess, which is sort of what p5.play does.

**Comment by toolness** [comment]
Oh, I guess what I'm proposing is to make `keyIsDown()` exactly like p5.play's own [`keyDown()`](http://p5play.molleindustria.org/docs/classes/p5.play.html#method-keyDown).

**Comment by lmccart** [comment]
Doesn't seem to be much activity here... are we good to just keep this in p5.play? I'm generally in favor of  keeping things leaner where possible, just to ease maintenance, but I'm open to it if others feel its important to have in the core.

**Comment by toolness** [comment]
Sure, that sounds reasonable to me!  Thanks for asking.

**Comment by kadamwhite** [comment]
I'm +1 for closing in favor of p5.play... I'm get the rationale but I don't think there's tremendous value in having a duplicative interface in this case.

**Comment by lmccart** [comment]
ok sounds good.
