### ISSUE TITLE
p5.Oscillator.freq() does not work in latest version of Chrome

### ISSUE THREAD

**Issue by swirly** [processing/p5.js#1334]
When using p5.Oscillator.freq to change sound frequency on an oscillator, it crashes the script on Chrome with following error :

p5.sound.js:3533 Uncaught TypeError: Failed to execute 'setValueAtTime' on 'AudioParam': The provided float value is non-finite.

context :
var osc;
function setup() {
osc = new p5.oscillator();
osc.type(sin);
osc.freq(440);
osc.amp(0.5);
osc.start();
}

function draw() {
  osc.freq(some new value); // not a null value;
}

works perfectly in firefox

**Comment by limzykenneth** [comment]
@swirly p5.js-sound have it's own repo and if you can copy and paste this issue [here](https://github.com/processing/p5.js-sound/issues) the people working on p5 sound can help you better. Cheers.

**Comment by lmccart** [comment]
thanks! reposted at the p5.js-sound repo:
https://github.com/processing/p5.js-sound/issues/108
