### ISSUE TITLE
Allow cross-references to other parts of the documentation

### ISSUE THREAD

**Issue by toolness** [processing/p5.js#1337]
It would be helpful if there were an easy way to cross-reference to other parts of the documentation from within it. For instance, the documentation for [`fill()`](http://p5js.org/reference/#/p5/fill) mentions [`colorMode()`](http://p5js.org/reference/#/p5/colorMode):

![colormode](https://cloud.githubusercontent.com/assets/124687/14174707/2c48ae8a-f714-11e5-9223-37b963da7fee.png)

It would be great if that was actually a link to the documentation for `colorMode()` rather than just static text.

YUIDoc does seem to have a mechanism for [cross-referencing modules and classes](http://yui.github.io/yuidoc/syntax/index.html#cross-referencing-modules-and-classes), but as far as I can tell, it assumes a certain syntax for documentation URLs that p5 doesn't conform to. I'm also not a huge fan of how verbose it is.

So, one option is to come up with our own alternative formatting. I guess one way we could do it, which might even work without having to write any additional tooling/preprocessing, is simply to use Markdown to relatively link to the appropriate place, e.g.:

```markdown
depending on the current [`colorMode()`](#/p5/colorMode).
```

I like this approach because it takes advantage of the nice URL fragment syntax the docs already use. It also doesn't really require any explicit documentation, and contributors can easily figure out what the fragment is by just visiting the proper section on the website and copy-pasting the fragment.

If we did things this way, I could probably even add a step to our test suite that checks to make sure that none of these relative links are broken.

Thoughts?

**Comment by shiffman** [comment]
I like the idea of using markdown.   We could always create a separate tool that runs over the docs and looks for things that could be linked and adds the markdown, but start with a manual approach.
