### ISSUE TITLE
p5.Vector.angleBetween() docs are inaccurate

### ISSUE THREAD

**Issue by toolness** [processing/p5.js#1338]
The documentation for [`p5.Vector.angleBetween`](http://p5js.org/reference/#/p5.Vector/angleBetween) claims that the angle returned is always in radians, but the implementation near the bottom of [`src/math/p5.Vector.js`](https://github.com/processing/p5.js/blob/master/src/math/p5.Vector.js) seems to actually convert the angle to degrees if the sketch has set `angleMode(DEGREES)`.

If this is indeed the case, I'm happy to fix the docs--probably by changing the description accordingly, but also changing the example sketch to show how the return value can differ based on `angleMode()`?

**Comment by shiffman** [comment]
Yes, this is a mistake.  The docs just weren't updated after being ported from Processing (where there is no `angleMode()`.

**Comment by toolness** [comment]
Ahhh, that's very useful background information to have--didn't realize that some of these docs were ported from Processing. Thanks!

**Comment by toolness** [comment]
Er, wait, based on my realization in https://github.com/processing/p5.js/issues/1336#issuecomment-203954339, I don't think that this method can actually access the current p5 instance to examine its current `angleMode`...

For reference, this is the current implementation of `p5.Vector.angleBetween`:

```js
p5.Vector.angleBetween = function (v1, v2) {
  var angle = Math.acos(v1.dot(v2) / (v1.mag() * v2.mag()));
  if (this.p5) {
    if (this.p5._angleMode === constants.DEGREES) {
      angle = polarGeometry.radiansToDegrees(angle);
    }
  }
  return angle;
};
```

I think the way this is written, it's actually made to be callable either as a static *or* an instance method. If it's called as an instance method, it actually does ultimately have access to the p5 instance the Vector was created with, so it takes `angleMode` into account... But if it's called as a static method, it always uses radians.

The only thing is, `createVector().angleBetween` is undefined, so it can't be called as an instance method, unless we do something weird like `p5.Vector.angleBetween.apply(myVector, v1, v2)`. So I am really, really confused.

In fact, in this context it seems like it'd make sense for `angleBetween` to *only* be an instance method, and take *one* vector argument, e.g. `v1.angleBetween(v2)` instead of `p5.Vector.angleBetween(v1, v2)`. That way the method would be guaranteed (or at least very likely?) to have access to a p5 instance and thus the current `angleMode`.

**Comment by shiffman** [comment]
Yes, I agree I think we should make `angleBetween()` only an instance method!
