### ISSUE TITLE
Make it possible to specify a parent element for canvas in p5 global mode

### ISSUE THREAD

**Issue by toolness** [processing/p5.js#1341]
I'm preparing to write a tutorial on positioning the p5 canvas (#1333) and realized that one thing which *appears* to not be possible right now is explicitly setting a parent element for the p5 canvas in global mode.

In instance mode, the second argument to the p5 constructor can be an `HTMLElement` that serves as the container for the canvas. Awesome!

However, for global mode, there doesn't seem any way to achieve a similar effect. Providing an easy way to do this seems like it would give a lot of power and flexibility to users, as it allows them to position the canvas anywhere in their page's DOM, rather than being forced to append it to the end of `<body>`. It would be nice if they could do this without needing to convert their entire sketch to instance mode.

One possible solution: what if, when p5 global mode is initiated, it looks for a DOM element with id `p5-global-canvas-holder`? If it finds it, it could use that as the parent for the sketch, but otherwise it would fall back to its default behavior?

Or is there already a way to specify the parent element in global mode that I don't know about?

**Comment by lmccart** [comment]
Good question, there is one actually. `parent()`: http://p5js.org/reference/#p5.Element/parent

**Comment by toolness** [comment]
Oh nice!!! Thanks, this is totally awesome.

**Comment by lmccart** [comment]
all the more reason a tutorial will be *so* helpful... users won't have to search around for all these little bits.
