### ISSUE TITLE
Window size not correct with createCanvas and WEBGL argument

### ISSUE THREAD

**Issue by AnneCHPostma** [processing/p5.js#1345]
When I create a 2D canvas using createCanvas([width], [height]), the window that gets created is properly resizing to the width and size of the canvas.

When I create a WebGL canvas using createCanvas([width], [height], WEBGL), the window size is resizing to the width and height of the WebGL canvas. 

To be consistent (and not having me to manually resize) the windows I'd love it if the functionality for the WebGL canvas would work the same as the normal canvas.

**Comment by lmccart** [comment]
Thanks, I posted this on the editor repo:
https://github.com/processing/p5.js-editor/issues/230
