### ISSUE TITLE
createCanvas() not working with variables

### ISSUE THREAD

**Issue by AnneCHPostma** [processing/p5.js#1346]
This issue is related to issue #1345.

When I have the following code:

```
var canvasWidth = 800;
var canvasHeight = 400;
 
function setup() {
  createCanvas(canvasWidth, canvasHeight);
```

The canvas is not accepting the arguments and doesn't resize properly. This issue is only happening in p5 itself. When I do this in CodePen it is working fine. So the arguments seem to get accepted, but when the arguments are not actual numbers, the window somehow doesn't get resized properly.

**Comment by lmccart** [comment]
Thanks! I've reposted this in the repo for the editor, since it seems to be an editor specific issue.
https://github.com/processing/p5.js-editor/issues/229
