### ISSUE TITLE
canvas.image not working

### ISSUE THREAD

**Issue by linux-man** [processing/p5.js#1347]
Although image() and PGraphics.image() methods work, canvas.image() doesn't do anything.
That's unexpected, since rect and ellipse works.

```
var canvas, pg;

function setup() {
  canvas = createCanvas(100, 100);
  pg = createGraphics(100, 100);
  pg.fill(0);
  pg.ellipse(50, 50, 50, 50);
}

function draw() {
  background(128);
  canvas.rect(0, 0, 50, 50);
  canvas.image(pg, 0, 0); // should draw pg
}

```

**Comment by cochsen** [comment]
I didn't debug, but since pg does not belong to your canvas object, this works:

```javascript
var canvas, pg;
function setup() {
  canvas = createCanvas(100, 100);
  pg = createGraphics(100, 100);
  pg.fill(0);
  pg.ellipse(50, 50, 50, 50);
}

function draw() {
  background(128);
  canvas.rect(0, 0, 50, 50);
  image(pg, 0, 0); // does draw pg
}
```

**Comment by nok** [comment]
Both methods of the variable `canvas` don't work, but it seems to be right.

```
var canvas, pg;

function setup() {
  canvas = createCanvas(100, 100);
  pg = createGraphics(100, 100);
  pg.fill(0);
  pg.ellipse(50, 50, 50, 50);
}

function draw() {
  background(128);
  canvas.rect(0, 0, 50, 50);  // <-- doesn't work
  canvas.image(pg, 0, 0);   // <-- doesn't work
}
```

Please read the chapter [Storing pointers and calling methods](https://github.com/processing/p5.js/wiki/Beyond-the-canvas#storing-pointers-and-calling-methods). You can use the [listed methods](http://p5js.org/reference/#/p5.Element) of the `Element` class.

Nevertheless I like the object oriented way storing data and states in uncoupled instances. So if we call `canvas.image()` we will end into the following [line(s) of code](https://github.com/processing/p5.js/blob/657d46e088948c81ebdfb47297dcbd37c79a3cbc/src/core/p5.Renderer2D.js#L98). So far, I am not familiar with the code base, so I can't make any suggestions or refactorings.

**Comment by lmccart** [comment]
I don't think we actually support this functionality with canvas, in the example above, you would want to just call the methods directly
```javascript

**Comment by linux-man** [comment]
That's ok. For me, it's all about coherence (although it would be sometimes useful to use a canvas object).
At 0.5.2, canvas.image and canvas.rect don't work (no warnings also), but canvas.ellipse works!
It's a case of code cleanup?

**Comment by lmccart** [comment]
Yes, it's close but it would require some code reworking to get all the functions working. For maintenance though, I'm going to close this issue since this functionality is not something we're trying to support right now.
