### ISSUE TITLE
Reference to canvas

### ISSUE THREAD

**Issue by linux-man** [processing/p5.js#1348]
Is it possible to create (or use) a default reference to canvas (like the processing "parent.pg")?
It could be useful to create methods that draw to canvas or to a graphic buffer with the same code.

**Comment by lmccart** [comment]
you can store a reference to the canvas in a variable like this:
```javascript
var cnv;

function setup() {
   cnv = createCanvas(100, 100);
}
```

does this do what you want?

**Comment by linux-man** [comment]
Yes, but a hidden and always available reference would be nice to library development.

**Comment by lmccart** [comment]
I agree, it would be helpful, but we also need to balance the ease of use with the size of the API. If it gets too large, the reference becomes kind of overwhelming. I think making it simple enough to get access if you want to, without building into the API is a good compromise in this case.

**Comment by linux-man** [comment]
I can relate to your words.
After some more exploring I found out that I could achieve my intent using "parent" in my library code.
parent.image draw on main canvas.
I'm looking for any drawback.
