### ISSUE TITLE
"MediaStreamTrack.getSources is deprecated" error in chrome 49.0.2623.87

### ISSUE THREAD

**Issue by adamforbes** [processing/p5.js#1352]
Issue:
When loading p5.sound.js, i receive the error "MediaStreamTrack.getSources is deprecated. See https://www.chromestatus.com/feature/4765305641369600 for more details."

Are there any plans to move this over to MediaDevices.enumerateDevices()?

**Comment by lmccart** [comment]
thanks! i've reposted on the p5.js-sound repo here:
https://github.com/processing/p5.js-sound/issues/109
