### ISSUE TITLE
image.resize() doesn't seem to be working in current version of safari (9)

### ISSUE THREAD

**Issue by techbrarian** [processing/p5.js#1353]
I'm working on an image viewer and when I use the resize method the image I draw to the canvas is erased in Safari. I don't see the problem in Chrome or Firefox.

**Comment by techbrarian** [comment]
Okay; I got this sorted out. The issue was in the draw method on an image resize. I was resizing an image and one of my parameters was going in as a float instead of an integer. Chrome and FF sorted it out, but Edge, IE and Safari, not so much. After I added Math.round() everything was copacetic.

**Comment by lmccart** [comment]
ooh interesting. for ease of use, wonder if we should be default call Math.round() behind the scenes?

**Comment by aksperiod** [comment]
Ah, this thread just saved my life.
