### ISSUE TITLE
loadImage not working in Edge

### ISSUE THREAD

**Issue by techbrarian** [processing/p5.js#1354]
A P5.js application I'm building won't work in Edge . . . in tracing out the problem the failure seems to begin at the loadImage method. It never seems to resolve. I'm attempting to load a data uri, but when I tested the problem with a regular image I got the same results.

**Comment by aparms** [comment]
Is there an error that you get in the console?

**Comment by techbrarian** [comment]
No errors appeared originally, but some interesting things happened as I continued to experiment with image uri and image size.

1. A relatively small image loaded with no trouble (from a data uri).
2. Eventually, after some tweaking, the much larger image throws an error (SCRIPT5022: IndexSize Error  p5.js(21030,3))
3. The specific line in p5.js being referenced is the 21030 line that draws an image to the canvas and is commented a "Copy the Image Back".
4. I don't have this trouble in FF or Chrome.

**Comment by techbrarian** [comment]
Okay; I got this sorted out. Turns out I had traced the problem incompletely . . . the issue was in the draw function. I was resizing an image and one of my parameters was going in as a float instead of an integer. Chrome and FF sorted it out, but Edge, IE and Safari, not so much. After I added Math.round() everything was copacetic.
