### ISSUE TITLE
how to change only one word to bold?

### ISSUE THREAD

**Issue by Dazzid** [processing/p5.js#1356]
Hi, 
I have a question in p5js. How to change only one word that is included in a whole text displayed as information? using textStyle(BOLD); change the hole document. Do I have to iterate word by word? thanks for the help 
David

**Comment by lmccart** [comment]
There's not really any way to do just one word, you'd need to make three different text calls, switching up the textStyle() for each. This is a limitation of the underlying HTML5Canvas API. You can manually guess and check the positions, or use textWidth() to figure out the position of the word and advance that much for the next x position of the following word.
