### ISSUE TITLE
p5js sound whileLoadingCallback

### ISSUE THREAD

**Issue by SetupandDraw** [processing/p5.js#1358]
Hi there,

I am working on a small project in P5js including video and sound and I was wondering how I can create a simple preloading showing loaded percentage of the video/audio files.

I saw there are very few info in the P5js.org reference about this topic.
Es. for the sound library: 

`new p5.SoundFile(path,[successCallback],[errorCallback],[whileLoadingCallback])`

`[whileLoadingCallback]` // Function: Name of a function to call while file is loading. That function will    //receive percentage loaded (between 0 and 1) as a parameter.

But this is not enough for my poor coding skills to understand how I can actually use that… 
What if I just want the whileLoadingCallback function and not the errorCallback?
How can I use the percentage loaded received by the whileLoadingCallback function?

Any examples?

Thank you very much!

**Comment by lmccart** [comment]
hi, i've reposted this on the p5.js-sound repo so the people working on this area specifically can hopefully provide help. https://github.com/processing/p5.js-sound/issues/115
