### ISSUE TITLE
Allow p5 to be used in global mode without defining setup/draw functions

### ISSUE THREAD

**Issue by toolness** [processing/p5.js#1359]
When I was helping with Taeyoon's [first Signing Coders workshop](http://taeyoonchoi.com/signing-coders-1/) I noticed that a lot of people got hung up on the concept of functions at the very beginning. They also had a hard time making sure that their code was actually *inside* a function (i.e. before the final closing bracket).

This made me wonder if it would be possible for p5 to *always* export the `createCanvas` function, so that a sketch could actually consist of the following:

```js
createCanvas(100, 100);
fill(255, 0, 200);
```

This would basically mean that calling `createCanvas()` would immediately setup p5 global mode, so that by the time it returns, `fill` and all the other p5 functions would be defined.

I suspect this has been considered before, and it definitely has lots of weird edge cases that could be hard to navigate around, so maybe it's lame. But it could potentially make the very early stages of learning how to code easier.

If this can't be done, I can probably just change [p5.js-widget](https://toolness.github.io/p5.js-widget/) to work this way, so that at least folks using the widget could have an easier time of it. IIRC, this is *almost* how the existing snippet editor on the p5 website works, too: https://github.com/processing/p5.js-website/issues/198#issuecomment-158047751

**Comment by lmccart** [comment]
hi @toolness, good question, you can view previous discussion here:
https://github.com/processing/p5.js/issues/158

we eventually concluded that we would require setup and draw in plain p5.js sketches but might support in the editor. (in the editor, it would basically wrap all global code inside a setup function before running). i think it'd make total sense for the p5.j-widget to do this. this is also what we're doing already with the examples in the reference.

**Comment by toolness** [comment]
Awesome, sounds good--thanks @lmccart! Will close this issue now.

**Comment by toolness** [comment]
@lmccart - I just added the functionality to the widget, you can see it in action here:

https://toolness.github.io/p5.js-widget/#implicit-setup

One thing it doesn't currently detect for is if the user defines setup/draw by assigning to variables (e.g. `var setup = function() {}`), rather than standard function declarations. Have you seen many people do this kind of thing? If so, I can add support for that, although the number of ways of doing it explode with ES2015. :sweat:

**Comment by toolness** [comment]
> One thing it doesn't currently detect for is if the user defines setup/draw by assigning to variables (e.g. `var setup = function() {}`), rather than standard function declarations. Have you seen many people do this kind of thing? 

Ehh, nevermind about that, the [fix](https://github.com/toolness/p5.js-widget/commit/a46d4192b2cc6727a6a2f73f327ddde734d985a2) was easy so it's no longer a concern. :bowtie:
