### ISSUE TITLE
loadTable "header" argument potentially confusing 

### ISSUE THREAD

**Issue by indefinit** [processing/p5.js#1361]
Possible suggestions for tweaking loadTable() function for ease of use:

Working on a lecture using loadTable() I came across the optional third function argument type string: "header".  I feel like it would be clearer to pass in a boolean value rather than a string, since the function just evaluates whether the argument equals "header" anyway, and it's less user-error prone than typing out a string.  Also, why not have the second argument as delimiter instead of file type?  

Usage would therefore look like this:

```
loadTable("assets/mammals.csv", ",", true);
```

and proposed changes in the src would look like this: https://gist.github.com/indefinit/cb4242f0b0c8e842dbc4987393a76826

It's possible we might want to do a deeper dive on loadTable to clean this up some more, but the proposed changes are just a quick fix.

Current location in src: https://github.com/processing/p5.js/blob/8041e8fac8ce0df0f00c8bc3ca1f866766568dac/src/io/files.js#L470

**Comment by shiffman** [comment]
One note I would make about this idea is that beginners are often very confused by boolean arguments when looking at examples.  Although it makes a lot more sense in many ways to implement `loadTable()` as you propose, this can be a lot easier for a beginner to know what is going on. . .

```javascript
loadTable('filename.csv', 'header');
```

vs.

```javascript
loadTable('filename.csv', true);
```

That said I'm not opposed to this change and would love to hear what others think.

I'll note that using a `String` was also chosen in Processing to leave open the possibility of other "options" being passed through.  But JavaScript of course is much more flexible in terms of managing a variable number of arguments.

```java
loadTable("filename.csv", "header option2 option3");
```

**Comment by lmccart** [comment]
I haven't heard further comments on this, so I'm going to close this for now.
