### ISSUE TITLE
table.getColumn(colName) returns empty array

### ISSUE THREAD

**Issue by indefinit** [processing/p5.js#1363]
Can't seem to find where the bug is on this, but getColumn with a string as argument returns an empty array, while table.getColumn(colNumber) with a number argument works as expected.  

Code/data to repro: https://gist.github.com/indefinit/48a01b53f9b929a8da4ecb459716e656

testing on Mac/Chrome, p5.js v0.4.23

**Comment by lmccart** [comment]
I think you just need to specify that there's a header in the loadTable() call, when I do this, the printouts look ok:
```
  table = loadTable("data/antarctica_weather_averages.csv", "csv");
```

**Comment by lmccart** [comment]
seems like this works, and it's more an issue of confusing documentation or p5.Table functionality in general? I'm going to close this issue and link back and leave some comments on https://github.com/processing/p5.js/issues/1361.
