### ISSUE TITLE
No warning for calls with incorrect number of parameters

### ISSUE THREAD

**Issue by jvolker** [processing/p5.js#1364]
No warning or errors appears if a function was called with an incorrect number of parameters.

e.g. `ellipse(mouseX,mouseY,10);` which requires 4 parameters, doesn't show anything, but obviously doesn't run either.

**Comment by lmccart** [comment]
good suggestion. this is one of the annoying things about the JavaScript language itself, it doesn't throw any error when you don't have the right number of arguments so things can fail silently, making things very hard to debug!

luckily @iamjessklein and @toolness are thinking about ways to add functionality to the p5.js library to add warnings and errors that make things friendlier for beginners.
https://github.com/processing/p5.js/issues/971

you can follow along with their research and progress here: http://processing.toolness.org/

stay tuned!
