### ISSUE TITLE
text highlighting

### ISSUE THREAD

**Issue by cymeknate** [processing/p5.js#1366]
Is it possible for there to be a background-color: function for text in p5?
Please let me know if there is a work around already, and just not me searching extensively enough.

**Comment by lmccart** [comment]
hi @cymeknate, the best way to do this would be to use the `textWidth()` function to determine the width of the text and use the `rect()` function to draw text behind it.
```javascript
  textSize(12);
  noStroke();
  var w = textWidth("hello");
  fill(0);
  rect(10, 10, w, 12);
  fill(255);
  text("hello", 10, 22);
```

**Comment by cymeknate** [comment]
Hello Lauren,

Thank you so much for getting back to this, I really appreciate it, and all
the work you are doing in general!

I use p5.js frequently for my projects, and its an amazing tool!

Have an amazing day,

Nate
n8c.work
