### ISSUE TITLE
Cannot read property of 'elt' of undefined

### ISSUE THREAD

**Issue by SaintPepsi** [processing/p5.js#1367]
Hello,
I was working on this cool scenery thing where clouds pass by, but when I add this piece of code:

```
    var randomCld = floor(random(0,6));
    for (var ncl = 0; ncl < randomCld; ncl++) {
        allClouds[ncl] = new spawnCloud(round(random(-100,innerWidth)));
    }
```

It gave the error:

Uncaught TypeError: Cannot read property 'elt' of undefined    p5.js:20418

**Comment by lmccart** [comment]
hm it's a little hard to debug the problem with this snippet. the code here looks good, but maybe there is something inside the spawnCloud() function that is causing a problem. I would suggest you post this on the forum for general debuggin help:
https://forum.processing.org/two/categories/p5-js-programming-questions

if you are able to narrow it down to a specific bug in the library please feel free to reopen or post a new issue. thanks!
