### ISSUE TITLE
I Have head some of beautyful things about processing, But ...

### ISSUE THREAD

**Issue by Acksop** [processing/p5.js#1371]
I'm disapointed,
the actual P5.js -- processing does have time functions, like a setInterval or something else,
CreateCanvas() does have a CSS and placement function like I think it must have...

I don't know how to compile a librairy like processing if I modify or fork the repository...
How sould I do that ?
Have you a link to teach me about this ?

Cheers
Acksop

![capture du 2016-04-23 06 31 23](https://cloud.githubusercontent.com/assets/1587184/14759280/141bbd46-091d-11e6-95b5-28bcb10e20bf.png)

**Comment by limzykenneth** [comment]
I'm not sure I understand your question. p5.js is a library written in javascript and javascript is a interpreted language, which means that it does not need to be compiled, just include it in the html and it will run. If you are asking more about how to build the library from source, have a look at the guide [here](https://github.com/processing/p5.js/wiki/Development#setup).

**Comment by kadamwhite** [comment]
@acksop, qu'est-ce que vous voulez faire avec p5.js? Nous ne comprenons pas votre question. p5.js fait la même chose que le Processing traditionnelle, tout en JavaScript et en natif dans une page Web. (Desolée pour mon français, il y a longtemps depuis qua je l'ai utilisé)

**Comment by Acksop** [comment]
thanks limzykenneth ! I haven't know that before, I will make some research on the web about Grunt next Week, to read a little bit more about ...

@kadamwhite: Il se trouve que j'ai programmé pendant mes études en ActionScript et je me désole de ne pas voir de réelles librairies qui controllent les temps terrestre en Javascript, quand j'ai connu processing ( puis p5.js) et après avoir vu quelques expérimentations dessus ( il y a de cela près de deux ans ), je pensait que ce serait plus simple de manipuler des Objets Image animés aléatoirement, mais avec une constante de temps fixé...

hier soir, j'ai finaliser une chose que je voulais faire depuis peu, quelque chose d'archi-simple mais que j'aurais voulu coder en processing... J'ai du l'implementer en Javascript Natif avec des gifs... je trouve cela néanmoins moins propre que je l'aurais penser...

Voici ce que je voualis faire avec processing: positionner un calque fixe audessus d'un applet ( dans le prochain cas c'est une page entière ) et l'animé jusqu'a disparition à un moment fixé temporellement ( dans ce cas ci les appel successifs en javascript ne fonctionnait pas, je pense néanmoins m'y replonger pour que cela fonctionne en cascade ).

idée étant venu il y a longtemps lorsque je surfait sur les sites Flash du genre de http://conclaveobscurum.ru/ et fluxen.net ( aujourdh'ui indisponible, ainsi que même la version flash n'est plus sur la wayback machine... )

**Comment by Acksop** [comment]
@kadamwhite Je me demande si l'intégration a p5.js d'un déclencheur du genre AtTime(t){ ...poceder à quelquechose... }, pourrais être utile ?

@limzykenneth: May I ask if integrate a Event like AtTime( t ) { ..process something... } can be useful ?

What do you think about it ?

**Comment by limzykenneth** [comment]
@Acksop I think to achieve that you can simply use the `frameCount` variable and a `if` conditional in `draw()` for the same effect.

```javascript
function draw(){
  if(frameCount==50){
    // do something
  }
}

**Comment by lmccart** [comment]
it's also entirely possible to use a setTimeout() call with p5:

```javascript
function setup() {
  createCanvas(100, 100);
  setTimeout(doSomething, 5000);
}

function doSomething() {
  background(100);
}
```

**Comment by Acksop** [comment]
thanks for your replies !
I think i will use the solution of limzykenneth, for this effect and also for an another, I sould control a repeated Jpegs cycle.
@imccart thanks for you reply, it can be usefull for my next experimentation, if I want to add some effect atTime !
