### ISSUE TITLE
p5.js library enhancement for removeElement(element)

### ISSUE THREAD

**Issue by kusha-b-k** [processing/p5.js#1373]
In p5.js  core library removeElements() will remove all the DOM elements, in some cases we want to remove a single DOM element so its very complex to do that , for these reason please include the  **removeElement( element ) ** method or function to the  p5.js core library..

_for example _

function setup() {
  createCanvas(100, 100);
  createDiv('this is some text');
  createP('this is a paragraph');
  createButton( '  hai P5 ' );
}
function mousePressed() {

removeElement( Button );  // it should only remove the Button  element  not the canvas or any other element

}

**Comment by lmccart** [comment]
one way you could do this with the exisiting library is like this:
```javascript
var button;

function setup() {
  createCanvas(100, 100);
  createDiv('this is some text');
  createP('this is a paragraph');
  button = createButton( ' hai P5 ' );
}

function mousePressed() {
  button.remove();
}
```
does this address your issue?
