### ISSUE TITLE
[documentation] push and pop functions

### ISSUE THREAD

**Issue by swirly** [processing/p5.js#1376]
Something is not really clear for me in documentation.
For an exemple of translation, I wrote a really simple script : 
```javascript 
function draw() {
 push();
translate(mouseX,mouseY);
ellipse(0,0,10,10);
pop();
}
```
I thought that if I suppress push and pop it would result in a mess, with multiple translations stacking.
But no. The more simple function
```javascript
function draw() {
translate(mouseX,mouseY);
ellipse(0,0,10,10);
}
```
is working in the same way ...

It's as if the draw() fonction reinitiates the drawing state for coordinates. I'm a missing something ? 
If it's true, it shall be documented in the documentation.

**Comment by cochsen** [comment]
Whatever you do between push() and pop() is not applied to the rest of the draw loop. Your first sketch is doing everything in the push() / pop() block of the draw loop, there's nothing outside of it to save.

In this example  a translation and style change is applied in push() / pop() and the ellipse reflects those state changes. After popping off those changes another ellipse is drawn showing the state before the push(): 
```javascript
function draw() {
  stroke(200, 100, 100);
  fill(100, 200, 200);
  push();
  stroke(100, 200, 200);
  noFill();
  translate(20, 20);
  ellipse(mouseX, mouseY,10,10);
  pop();
  ellipse(mouseX,mouseY,10,10);
}
```

**Comment by swirly** [comment]
That's not the point

the point is that the draw loop restore the transformation to initial state and that is not clear in translation

If you do 
```javascript
function draw() {
translate(1,0);
rect(10,10,10,10);
}
```
you should expect your square to advance because the translation should be cumulative

That's not the case.

The draw loop restore the coordinates system, as if there was a 'push/pop' around the draw loop.

That's not clear in documentation

**Comment by lmccart** [comment]
thanks @swirly. yes, this is the correct behavior, but it should be better documented. I will update this.
