### ISSUE TITLE
shearX() and shearY() does not work with angleMode(DEGREES)

### ISSUE THREAD

**Issue by swirly** [processing/p5.js#1377]
problem:
In documentation, the exemple with shearX is 
```javascript
translate(width/4, height/4);
shearX(PI/4.0);
rect(0, 0, 30, 30);
```
if you replace with
```javascript
angleMode(DEGREES)
translate(width/4, height/4);
shearX(45);
rect(0, 0, 30, 30);
```
it does not work.

It seems that shearX is bugged with something else than RADIANS.

**Comment by limzykenneth** [comment]
when `angleMode` is set to degrees, the angle passed to `shearX/Y()` is passed through the radians conversion multiple times (once in `shear()`, once in `renderer.shear()` and again in `tan()`) the result is almost zero if not zero.

@lmccart Two solutions, either have a check if conversion is already done or make sure in the code base that conversion will only be done once. the second solution seem easier to implement but also easier to miss...

**Comment by swirly** [comment]
Ok. Thank you for your investigation. So the bug is confirmed.

**Comment by lmccart** [comment]
thanks for looking into this @limzykenneth, should be fixed now.
