### ISSUE TITLE
image loading causes massive cpu/memory load

### ISSUE THREAD

**Issue by autonome** [processing/p5.js#1380]
Loading images causes excessive cpu and memory consumption in both Chrome and Firefox.

In Chrome, loading images instantly causes both the UI process and the web content process to start chewing 15% - 20% CPU each. Closing the tab causes it to stop. Same behavior in Firefox, but drastically worse, ranging from 50% to 100+% of CPU (tested with and without e10s enabled - same results).

Even a single image causes load that is far beyond reasonable - seems likely that there is un-optimized code in P5.js somewhere and memory consumption shows possibility of a leak.

Testcase:

```<html>
<script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.4.24/p5.min.js"></script>
<script>

// increase count to increase p5 image instances to increase system load
var count = 5,
    imgs = [];

function setup() {
  createCanvas(720, 400);
  for (var i = 0; i < count; i++) {
    imgs.push(loadImage('https://i.imgur.com/0iJiDGz.png'));
  }
}

function draw() {
  imgs.forEach(function(img, i) {
    image(img, i * 20, i * 20);
  });
}

</script>
</html>
```

**Comment by autonome** [comment]
Sorry, forgot some key information:

* Hardware: MacBook (Retina, 12-inch, Early 2015)
* OS: Mac OS X El Capitan 10.11.4 (15E65)
* Browsers tested: Chrome Canary, Firefox Nightly, Firefox Developer Edition

**Comment by limzykenneth** [comment]
I've optimised the example a bit (just so that we can look at the performance of the image load and not drawing too many image onto the canvas over and over again):

```javascript
var count = 5,
    imgs = [];

function preload(){
	for (var i = 0; i < count; i++) {
	    imgs.push(loadImage('https://i.imgur.com/0iJiDGz.png'));
	}
}

function setup() {
	createCanvas(720, 400);
	imgs.forEach(function(img, i) {
		image(img, i * 20, i * 20);
	});
}
```

I'm not really able to reproduce the CPU and memory consumption you are experiencing with similar setup, although to be fair I'm running on a rather powerful iMac. Chrome, Safari and Firefox on average took about 15% of CPU and maximum 900MB of memory each when I bumped it up to load 500 images. 

Tryout the optimised example, see if it helps. I have a look at the source to make sure no obvious leak is happening somehow.

**Comment by lmccart** [comment]
thanks for creating this simplified example @limzykenneth. I took a really quick look through the code and nothing jumped out at me as a big leak, but let me know if you find anything suspicious.

**Comment by autonome** [comment]
Thanks @limzykenneth! Yes, the optimized example of only drawing the images
once at setup() does not exhibit the performance issues I found when
drawing repeatedly.

However, I want to do interesting things with the images :) Don't I need to
redraw them in order to animate them? Or are you saying there's another way
of doing that without using the image APIs I've used in the example?

**Comment by limzykenneth** [comment]
@autonome Well it depends on what you need. If you just need to draw the same image multiple times with modifications etc. in between, just load the image in once and use the same variable you saved it to to draw it. If you need to load in several different images, one animation trick that might prove useful is the idea of a sprite sheet, have a look at the [reference](http://p5js.org/reference/#p5/image) where you draw with 9 arguments to `image()`. That way, you can just load in one image and draw sections of the image over and over again. The two above should be more efficient as your browser don't need to access a big array every frame to draw.

**Comment by lmccart** [comment]
I'm guessing this was just an example to show the load caused by loading and drawing 5 or more images. I think we should make sure it's possible to load 5+ images and draw them on each draw loop without overloading the CPU. The fact that the load comes from drawing rather than loading seems to be a clue, I will investigate further..

**Comment by lmccart** [comment]
I'm not able to reproduce this, the CPU usage seems to be holding constant for me in chrome. Has anyone else noticed this behavior?

**Comment by autonome** [comment]
Sorry for not replying sooner. I'll re-test in contemporary Chrome and
Firefox and see if I can still reproduce.

You tried with five different images?

Also, I recommend testing with non-Chrome browsers in addition, since
Chrome is only half the users of the web. The other half deserve a web that
works for them as well ;)

**Comment by autonome** [comment]
Oh right, reading earlier comments I guess it doesn't really matter if multiple images or not.

I tested in Firefox nightly and Chrome canary, and not seeing the same behavior. I'm on the 2016 macbook now, which has a much improved CPU than the 2015 model, so perhaps I'm just seeing that.

Either way, closed is fine because I cannot reproduce anymore :)
