### ISSUE TITLE
noSmooth() not working

### ISSUE THREAD

**Issue by noisefactor** [processing/p5.js#1381]
I've been trying to figure out how to achieve pixelated drawing without success.  When I analyze the noSmooth() reference demo for Chrome, Safari, and Epic, there's no difference between the two ellipses.  I'm guessing that the support for aliased lines in modern browsers is non-existent, but I'm just curious if someone can shed some light on this.  Has anyone representing p5js petitioned developers of Webkit, etc. to fix pixelated image-rendering/line-rendering functionality for Canvas?

**Comment by noisefactor** [comment]
According to comment #22 here (http://stackoverflow.com/questions/195262/can-i-turn-off-antialiasing-on-an-html-canvas-element), there's a boolean flag in Firefox (that could be added to the noSmooth function)...

contextXYZ.mozImageSmoothingEnabled = false;

**Comment by limzykenneth** [comment]
I believe that is correct. `smooth()` and `noSmooth()` under the hood is basically calling `imageSmoothingEnabled = true/false` with various vendor prefixes and it seems to work only on image scaling (not line drawing which ellipse is), have a look at the example at the bottom on [MDN's documentation](https://developer.mozilla.org/en/docs/Web/API/CanvasRenderingContext2D/imageSmoothingEnabled).

We might need to edit the example.

**Comment by noisefactor** [comment]
Before changing the example, it might be helpful to submit a feature request to whomever handles these kinds of issues at Mozilla/Webkit citing the noSmooth() documentation as an example of why this type of boolean control for graphics smoothing (not image smoothing) would be practical for developers.
