### ISSUE TITLE
beginShape() doesn't render more than three vertices in WEBGL

### ISSUE THREAD

**Issue by pithonsmear** [processing/p5.js#1383]
Hey

I was having some trouble with custom shapes in WEBGL. I looked around and found [this][1].
The fix seemed to have been merged with master, so I downloaded the newest package, but the problem seems to still exist:

The following code:
```
function setup() {
  createCanvas(200,200,WEBGL);
}

function draw() {
  background(0);

  beginShape();
  vertex(-50, -50, 0);
  vertex(50, -50, 0);
  vertex(50, 50, 0);
  vertex(-50, 50, 0);
  endShape(CLOSE);
}
```

Produces the following image:
![Four vertices producing a triangle][img]

Which should be a square, but is a triangle, so it seems like the fourth vertex is ignored.
The same coordinates (sans z) work fine in 2d (they produce a square), but fail in WEBGL.
Admittedly, I downloaded p5 from p5js.org, but the newest version (0.4.24) was only a couple days old, so I figured the fix would be in it.

[1]: https://github.com/processing/p5.js/issues/1209
[img]: http://i.imgur.com/6mgOLLe.png "Four vertices producing a triangle"

**Comment by limzykenneth** [comment]
From what I found the fix is merged into master right after the version bump so for this fix to appear in the p5.js library you might need to wait till the next release (0.4.25). Or if you are up for it you can build the library from source following instructions [here](https://github.com/processing/p5.js/wiki/Development#setup).

**Comment by lmccart** [comment]
thanks for looking in this @limzykenneth, a new version will be posted by may 1 with this fix included.

**Comment by pithonsmear** [comment]
Wonderful, thanks for the info.
