### ISSUE TITLE
filter commands tax performance on video.  Optimization possibilities?

### ISSUE THREAD

**Issue by indefinit** [processing/p5.js#1388]
I've noticed that frame rate plunges when using filter() commands on canvas video.  For example:

```
var space;
function preload(){
 space = createVideo(['media/anni003.mp4']); 
}

function setup() {
  createCanvas(windowWidth, windowHeight);
  // specify multiple formats for different browsers
  
  space.loop(); // set the video to loop and start playing
  space.hide(); // by default video shows up in separate dom
                  // element. hide it and draw it to the canvas
                  // instead
  space.volume(0);//we set the volume to 0 because we don't want
                  //sound
}

function draw() {
  background(150);
  image(space,10,10); // draw the video frame to canvas
  filter(BLUR);//HELLO SLOWDOWN!
  image(space,150,150); // draw a second copy to canvas
}
```

One likely solution for performance issues is to implement this in a webgl shader, however, I'm curious whether there are other options for optimizing performance in the 2d canvas api as well.  Any thoughts?

**Comment by shiffman** [comment]
I think this is just the reality of pixel based operations being slow (and exponentially more slow the larger the image).   In some sense it's a teaching / documentation issue?    I like the idea of having `filter()` use a shader if `WEBGL` is enabled?

One reason the above is extra slow is that `filter()` is being called on the entire canvas.  Does it work to do something like:

```javascript
  image(space,150,150); // draw a second copy to canvas
  space.filter(BLUR);
  image(space,10,10); // draw the video frame to canvas
```

**Comment by indefinit** [comment]
@shiffman interesting!  space.filter(BLUR) returns the error that filter is not a function.

Re: webgl shader manipulation of video, I definitely want to make this happen this summer.

**Comment by lmccart** [comment]
closing as I don't think this is a bug really, just a limitation of the library.
