### ISSUE TITLE
0.4.24 fails to reset the matrix at the end of draw 

### ISSUE THREAD

**Issue by islemaster** [processing/p5.js#1390]
In #1058 a change is proposed to _only_ reset the transform matrix after each draw (not style properties) to be more like the behavior of processing.  That issue was closed by https://github.com/processing/p5.js/commit/c96f4d5c06cc87bad440cc0e3d3dc52719677b1d - unfortunately that commit binds `resetMatrix` instead of invoking it like it probably intended, resulting in odd behaviors like this one:

![scale](https://cloud.githubusercontent.com/assets/1615761/15030244/09259f28-1206-11e6-8bea-2e7fa56151d5.gif)

Live example here: https://jsbin.com/gebilozimi/1/edit?html,output

**Comment by islemaster** [comment]
Fixing this bug should be fairly easy - simply invoke `resetMatrix`.  Testing it properly may be more difficult, since [reading the canvas context current transform is not well supported](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/currentTransform).  It looks like other libraries implement their own matrix and call [`setTransform`](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/setTransform) to work around this limitation.

**Comment by islemaster** [comment]
@lmccart This bug is not fixed by https://github.com/processing/p5.js/commit/2d3257b05f17ca43cf33a59a5c522e547dbbc644.  The original repro (updated to point at 0.5.0) still demonstrates the incorrect behavior: https://jsbin.com/ziqowateni/1/edit?html,output . Can we re-open this?

**Comment by lmccart** [comment]
sorry, I haven't posted a new build with this fix in it yet (it's not in 0.5.0, but will be in 0.5.1), right now it's just in the source code. will do this as soon as I can.

**Comment by islemaster** [comment]
Ah, I'm sorry. I misread this commit list, I thought it was included
commits. https://github.com/processing/p5.js/compare/0.5.0...master
