### ISSUE TITLE
blended pixels with pixelDensity below 1.0

### ISSUE THREAD

**Issue by whoisbma** [processing/p5.js#1393]
I'm experimenting with pixelDensity values below 1 in order to get a lower resolution render context that is still scaled to an arbitrary canvas size. It results in blended pixel values regardless of noSmooth() being set. 

Is it possible to get clean "pixels" with a pixelDensity value below 1? (or a better workaround?)

**Comment by lmccart** [comment]
Hm, I might suggest just keeping pixelDensity at 1, but then manually scaling up your canvas with css?
For example, to make a 200x200 canvas at half resolution:

```javascript
function setup() {
  createCanvas(100, 100);
  pixelDensity(1);
}

function draw() {
  background(200);
  ellipse(width/2, height/2, 50, 50);
}
```

and in the HTML
```HTML
<style>
    canvas { 
      width: 200px !important;
      height: 200px !important; 
    }
</style>

**Comment by whoisbma** [comment]
it makes a lot more sense to do that. thank you!
