### ISSUE TITLE
Description for matchRow() and matchRows() is the same

### ISSUE THREAD

**Issue by skilfullycurled** [processing/p5.js#1394]
Hi,

On the reference page for [Table](http://p5js.org/reference/#/p5.Table), the description of  matchRow() and matchRows() is the same.  If you go to the specific page for [matchRow()](http://p5js.org/reference/#/p5.Table/matchRow) and [matchRows()](http://p5js.org/reference/#/p5.Table/matchRows), the descriptions are the same, though the parameters and return values are correct respectively.

Thanks!

**Comment by lmccart** [comment]
thanks!
