### ISSUE TITLE
Linking to CDN

### ISSUE THREAD

**Issue by ldlathrop** [processing/p5.js#1398]
I realize this is probably a stupid question, but the data journalism site I'm planning to use for my visualizations requires that p5.js links to an external site. As I don't currently have a website of my own, I'm planning to use CodePen. In your documentation for embedding p5 files, you say "You will need to link to the CDN to include p5.js libraries." But clicking on the `CDN` link takes me to a page with zero instructions regarding what I'm supposed to do. Would very much appreciate some instruction. Thanks!

**Comment by lmccart** [comment]
hi @ldlathrop this file setup section on the getting started page shows how to include a link to the CDN, does this help?
http://p5js.org/get-started/#file-setup

**Comment by ldlathrop** [comment]
Hi @lmccart. Thanks so much! I did read that page early in the process, but failed to make the connection when I read about embedding p5 files. Much appreciated!
