### ISSUE TITLE
loadImage() function not overriding old images

### ISSUE THREAD

**Issue by ckxian** [processing/p5.js#1399]
I'm taking a snapshot of the canvas using save() and then reloading it back onto the canvas on the same sketch using loadImage(). When the canvas is saved, it is saved in my p5 folder as a specified name (For example, "image1.jpg". When my sketch first starts running, everything works fine. It saves as image1.jpg and it loads the correct image. The second time around (same sketch, the code calls save() again),"image1.jpg" in my p5 folder updates, but when it loads, it loads the PREVIOUS image. Why is that?? Doesn't every time loadImage() is called, it grabs whatever is in your folder CURRENTLY? It's displaying an image that previously existed (but has the same name as the current one). Anyone know why??

**Comment by lmccart** [comment]
hi @ckxian could you please post a small code snippet that illustrates the problem you describe?

**Comment by ckxian** [comment]
function setup() {
  var canvas = createCanvas(windowWidth,windowHeight); 
  capture = createCapture(VIDEO); 
}

function draw(){
  takePictures();
 //after takePictures() finishes taking 2 pictures, it'll switch to displayPictures();
  displayPictures(); 
}

function takePictures(){
  save('0myCanvas.jpg');
  save('1myCanvas.jpg');
 //just takes two screenshots every 10 seconds
}

function displayPictures(){
  one = loadImage("0myCanvas.jpg");
  two = loadImage("1myCanvas.jpg");

  image(one,0,0); 
  image(two,100,0);
}

//this is a super simplified code! Just to get the idea across. I just want to take two screenshots, then display them in the end. The problem: When I run the sketch initially, everything works fine. '0myCanvas.jpg' & '1myCanvas.jpg" saves, loads, and displays fine. Assuming, I have a boolean at the end of the sketch that does this whole thing over again (without actually refreshing the sketch), the save('0myCanvas.jpg') works fine (because I see the new screenshot in my p5 file). However, the loadImage("0myCanvas.jpg") somehow loads the OLD '0myCanvas.jpg' picture because it's still displaying the old picture. I even tried setting var one and var two to null when it restarts. Still loads the old picture....

**Comment by lmccart** [comment]
I think the problem here is that the images have not finished loading before you are trying to display them. If you add a callback function into the loadImage() call as the second parameter, you will see everything show up correctly:

```javascript
function displayPictures(){
  one = loadImage("assets/rockies.jpg", function() {
    image(one,0,0); 
  });
  two = loadImage("assets/cat.jpg", function () {
    image(two,100,0);
  }); 
}
```

For further debugging help, it's best to post on the forum:
https://forum.processing.org/two/categories/p5-js-programming-questions
