### ISSUE TITLE
Possible to restrict mousePressed to canvas in instance mode?

### ISSUE THREAD

**Issue by Kadrian** [processing/p5.js#1400]
Hi, I'm trying to trigger mouse actions only when happening on the canvas.

Due to my setup with React / Redux, I'm using instance mode like this, where the mousePressed function is not triggered now.

Any ideas?

```
class MySketch extends React.Component {
  static propTypes = {
    sketchState:  React.PropTypes.object.isRequired,
  }

  componentDidMount() {
    const sketch = new p5(this._sketch.bind(this), 'mysketch');
  }

  _sketch(p) {
    function mousePressed() {
      // This is currently not triggered 
      console.log("down");
    }

    function drawAll() {
        ...
    }

    p.setup = () => {
      const { width, height } = this.props.sketchState;
      cvs = p.createCanvas(width, height);

      cvs.mousePressed(mousePressed); // This won't work, the function is never triggered

      drawAll(this);
    };

    p.draw = () => {
    };
  }
  
  render() {
    return <div id="mysketch"></div>;
  }
}
```

**Comment by lmccart** [comment]
hi @Kadrian here is a simplified example demonstrating how to use instance mode with mousePressed attached to canvas:
```javascript
var sketch = function( p ) {

  p.setup = function() {
    var cnv = p.createCanvas(700, 410);
    cnv.mousePressed(doStuff);
  };

  p.draw = function() {
    p.rect(50, 50,50,50);
  };

  function doStuff() {
    p.background(p.random(255));
  }
};

var myp5 = new p5(sketch);

```

for further debugging help, try posting in the forum:
https://forum.processing.org/two/categories/p5-js-programming-questions

**Comment by Kadrian** [comment]
Thanks, the problem was on my side: I had another element with position absoluted placed in front.
It seems though that mouseDragged may not be attached to only the canvas, can it?

**Comment by simdax** [comment]
+1 for mouseDragged ?

Is there a way to workaround this?

**Comment by lmccart** [comment]
You can attach mousePressed() or mouseDragged() directly to the canvas like this: http://p5js.org/reference/#/p5.Element/mousePressed
