### ISSUE TITLE
createGraphics and loadPixels

### ISSUE THREAD

**Issue by no-carrier** [processing/p5.js#1403]
Hi all,
Not sure if this is a bug, but its not documented and functions very differently than Processing, which is confusing. If you use createGraphics() to draw an off-screen buffer (called buffer below), then use buffer.loadPixels(), the pixels() array gets updated with those pixels, not buffer.pixels() like in Processing. The example below demonstrates this. If this is the intended function -- it would be helpful if it was documented somewhere. Thanks!

Here is an example:

// ----------------------

var buffer;
var d;

function setup() {
  createCanvas(200, 200);
  buffer = createGraphics(width,height);
  d = pixelDensity();
}

function draw() {
  var index = (0 * width + 0) * (d * 4);
  
  buffer.background(0, 0, 0);
  buffer.loadPixels();
  
  background(64, 255, 128);
  
  console.log(buffer.pixels[0]); // should this be 0 (as in Processing)? logs undefined
  console.log(buffer.pixels[1]); // same
  console.log(buffer.pixels[2]); // same
  
  console.log(pixels[0]); // should this be 64? logs as 0
  console.log(pixels[1]); // should this be 255? logs as 0
  console.log(pixels[2]); // should this 128? logs as 0
  
  noLoop();
}

**Comment by Craigson** [comment]
As far as I understand it, loadPixels only works with the default default display window (I think there are plans to change this so that it applies to multiple buffers, @lmccart ? ) so using loadPixels won't have any effect on your buffer object's pixel array.

As an aside, writing to the buffer would require you do to something like this:
<pre> buffer.background(64,255,128); </pre>

**Comment by no-carrier** [comment]
Got it. As I said, I was using it the way I've used it Processing, but now I know it that it doesn't apply to multiple buffers. Thanks!

**Comment by shiffman** [comment]
`loadPixels()` should work with `createGraphics()`.  We went around on this with quite a few issues I recall, @no-carrier can you confirm it's not working for you with [the very latest release](https://github.com/processing/p5.js/releases/tag/0.5.0)?

**Comment by lmccart** [comment]
I have a new release coming hopefully today that includes the latest pixel fixes, so I'd wait a day and try with tthat one.
