### ISSUE TITLE
muting a filter in p5.sound

### ISSUE THREAD

**Issue by ducklin5** [processing/p5.js#1404]
In the my sketch.js file I have to filter a sound coming from the microphone before displaying it with FFT, but I realized, using a filter creates a sound of its own, which then creates a horrid echo. Is it possible to mute this filter, without muting the whole browser?

**Comment by lmccart** [comment]
hi @ducklin5, the forum is a good place to post general how-to questions:
https://forum.processing.org/two/categories/p5-js-programming-questions

if this is a feature request, there is actually a dedicated p5.js-sound repository that you can post to:
https://github.com/processing/p5.js-sound
