### ISSUE TITLE
vertex function moveTo parameter, necessary?

### ISSUE THREAD

**Issue by indefinit** [processing/p5.js#1405]
I'm working on some updates to vertex functions and I noticed in canvas mode, vertex has a third parameter ```moveTo```
https://github.com/processing/p5.js/blob/16f2d3f06f9261c6da9d6aaf29ee7cc728f17a70/src/core/vertex.js#L597

As far as I can tell, moveTo is never actually used within the context of vertex, in which case I plan on cleaning up a bit and removing the param.  Before I do this, however, just a gut check- am I missing something? What the motivation behind having a moveTo in the vertex in addition to the canvas moveTo?

**Comment by lmccart** [comment]
yep looks like this is just vestigial, feel free to remove.

**Comment by indefinit** [comment]
ha great word for this :)  Ok will do.
