### ISSUE TITLE
Set image as background throws an error

### ISSUE THREAD

**Issue by rbostan** [processing/p5.js#1407]
Hi,

When i tried to set image as background, an error occured: 
`p5.js:21213 Uncaught TypeError: this._renderer.image is not a function`

Code :
````
var canvas;
var wall;
function setup() {
	wall=loadImage("/v2/assets/img/bg.jpg");
	canvas=createCanvas(1023,682,WEBGL); // canvas size same as image size 
}

function draw() {
	background(wall);
	box(100,100,100);
}
```

**Comment by lmccart** [comment]
Loading an image as a background is not currently supported in WEBGL mode, if you try this in 2D it should work.
