### ISSUE TITLE
Saving a snapshot of the canvas and then reloading it

### ISSUE THREAD

**Issue by ckxian** [processing/p5.js#1408]
Is there a way to save a snapshot of the screen without the browser downloading it? When run locally, the save() function saves the snapshot in the p5 folder. The snapshot then successfully loads and displays onto the canvas. But when I put it on a browser, it saves the image on the browser. Making it not load-able. 

Maybe there's a way I can save the snapshot without actually saving a .jpg file? 

///////////////////////

function setup() {
  var canvas = createCanvas(windowWidth,windowHeight); //using the webcam
  capture = createCapture(VIDEO); 
}

function draw(){
  if(captureBool == true){ //takes a snapshot of the canvas
   save("MyCanvas.jpg");
 }

function display(){
 if(displayBool == true){
  Image1 = loadImage("assets/MyCanvas.jpg");  //loads the snapshot
  image(Image1,0,0);  //displays the snapshot
}
}
}

**Comment by Craigson** [comment]
You could try drawing to an offscreen buffer.. something like this ( note I'm omitting some of the necessary standard p5 stuff, and there are cleaner ways to do it, but I hope it helps explain the logic) ...

<pre>
var buffer;

function setup()
{
buffer = createGraphics(600,600);
}

//method for writing to the offscreen buffer
function writeBuffer()
{
    //draw whatever you want to draw, for eg.
    buffer.background(100);
    buffer.noStroke();
    buffer.ellipse(pg.width/2, pg.height/2, 50, 50);
}

function draw()
{
   if(captureBool == true) writeBuffer();
   if (displayBool)
   {
       image(buffer, 600, 600);
   } else {
      background(100);
      noStroke();
      ellipse(pg.width/2, pg.height/2, 50, 50);
  }
}
</pre>

**Comment by lmccart** [comment]
thanks @Craigson!
