### ISSUE TITLE
p5.Font.textBounds getting clipped

### ISSUE THREAD

**Issue by mikewesthad** [processing/p5.js#1409]
I was working with p5.Font.textBounds earlier and discovered a bug(?) where the bounds are clipped by forcing the calculated minX and minY to be at least 0 (relevant [lines](https://github.com/processing/p5.js/blob/master/src/typography/p5.Font.js#L128-L131) of code in p5.Font.js).

Here's a codepen [demo](http://codepen.io/mikewesthad/pen/NNJEGr?editors=0010) where I'm running `font.textBounds(...)` and varying the (x, y) coordinates passed in.  The output in the console looks like this:

```
True bounds should be:  46.318359375   x   14.853515625

Clipping in y-axis:
Bounds for (0, 0):      46.318359375   x   0.15625
Bounds for (0, 10):     46.318359375   x   10.15625
Bounds for (0, 20):     46.318359375   x   14.853515625
Bounds for (0, 30):     46.318359375   x   14.853515625

Clipping in x-axis:
Bounds for (-20, 30):   26.318359375   x   14.853515625
Bounds for (-10, 30):   36.318359375   x   14.853515625
Bounds for (0, 30):     46.318359375   x   14.853515625
Bounds for (10, 30):    46.318359375   x   14.853515625
```

I'd propose a solution, but I'm not quite sure why the minX and minY calculated in textBounds are forced to be greater than or equal to 0.  Anyone know?

**Comment by lmccart** [comment]
fixed with https://github.com/processing/p5.js/commit/1fabe53db20e0a7d654c15983d64f8fecb1819d2

**Comment by dhowe** [comment]
Problem/side-effect? 
This is what I see:

![image](https://cloud.githubusercontent.com/assets/737638/15229078/f11baa7c-18c1-11e6-8def-781d74d6bef0.png)
