### ISSUE TITLE
Incorrect vertical alignment of multi-line text

### ISSUE THREAD

**Issue by dhowe** [processing/p5.js#1410]
It appears that multiline text is not following vertical alignment rules.

Image: pink is Processing, bottom is p5js, test code [here](https://github.com/processing/p5.js/blob/master/test/manual-test-examples/p5.Font/custom/sketch.js#L277)...

![screen shot 2016-05-13 at 4 03 52 am](https://cloud.githubusercontent.com/assets/737638/15228784/76ba8222-18c0-11e6-9a49-23212230b1d5.png)

**Comment by mikewesthad** [comment]
@xyfeng - I see @dhowe assigned this to you both. Are you working on it? If not, I'll have some time this weekend to check it out.

**Comment by lmccart** [comment]
fixed with https://github.com/processing/p5.js/pull/1433
