### ISSUE TITLE
add info for establishing a server in OS X El Capitan to wiki page

### ISSUE THREAD

**Issue by ldlathrop** [processing/p5.js#1411]
Hello! So the wiki for setting up an OS X server only instructs for Snow Leopard, not El Capitan. El Capitan no longer has the web sharing function in System Preferences. Instead, one has to buy OS X Server and set it up that way. I've done that and set file sharing with my project folder on the server, but I'm still getting the following message in the Chrome Developer Console when I run my index.html file.

    file:///Volumes/Server/practice/cltop.csv. Cross origin requests are only supported for protocol   
    schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.  
The "cltop.csv" file is what I'm trying to load and I'm using this code in p5:

    var clWords = [];
    var clinton;

    function preload() {
      clinton = loadTable("cltop.csv", "header");
    }

There is an option in OS X Server to set up a local website server, but it's unclear to me whether that would fix the issue, because it's more for building and/or hosting a website. Do you know anything about setting up a server in El Capitan? I realize I could set it up with Python, but your wiki says that loads files pretty slowly, and I don't want that. Any help would be appreciated. Thanks!

**Comment by Craigson** [comment]
Hi,

Creating a local server using Python, using the "python -m SimpleHTTPServer", will solve the Cross origin request issue.  There shouldn't be any performance loss if you're loading a small .CSV file.

**Comment by kadamwhite** [comment]
I believe that El Capitan also ships with PHP, so e.g. `php -S localhost:3000` ought to work as well. Haven't tested w/ cross-origin issues tho

**Comment by limzykenneth** [comment]
@ldlathrop All versions of Macs ship with Apache webserver and the wiki might not be worded well but if you look under [Mac OS X](https://github.com/processing/p5.js/wiki/Local-server#mac-os-x) you will see in step 1 there is instruction for you to type

```
sudo apachectl start
```

which will start the apache server and serve file from `/Library/WebServer/Documents` ("Library" here is at the root ie. your harddisk, not your user account). I have additional setup to overcome the limitations of the next step in the wiki which is permission settings but personally, I would say if you are not planning to use PHP, stick with either python's server or if you are concerned about performance, node's `http-server` is what I use nowadays. All of them are documented in the wiki.

**Comment by Craigson** [comment]
@ldlathrop do any of these solutions solve your problem? Can I close the issue?

**Comment by ldlathrop** [comment]
Thanks for the suggestions, everyone! Got it working with node.js.

**Comment by lmccart** [comment]
thanks all! this is helpful info and should be included on the wiki page. I'm going to reopen this issue until we've added this to the server page.

**Comment by limzykenneth** [comment]
I'm on it, will be editing it a bit later today.

**Comment by limzykenneth** [comment]
Done over [here](https://github.com/processing/p5.js/wiki/Local-server). I'm also wondering whether we need [this page](https://github.com/processing/p5.js/wiki/SimpleHTTPServer) on python's simple http server. I think it would be better to change it into a more generic tutorial about Terminal and command line.

**Comment by lmccart** [comment]
wonderful, looks great. I agree, we could remove or repurpose that page for command line tutorial.
