### ISSUE TITLE
Text size bug when drawing opentype font with multiple renderers

### ISSUE THREAD

**Issue by mikewesthad** [processing/p5.js#1413]
I was using an offscreen renderer with an opentype font and ran into a bug.  When drawing to the offscreen renderer, the text size that is being applied is from the main renderer.  The problem looks to be coming from [here](https://github.com/processing/p5.js/blob/master/src%2Ftypography%2Fp5.Font.js#L228).  When getting path data from the font, the parent of the font is used for the text size - rather than the current renderer.

[Codepen demo](http://codepen.io/mikewesthad/pen/zqXdNQ)

I'll submit a PR with a proposed fix.

**Comment by dhowe** [comment]
I think the way to support more use-cases like your example is to allow a renderer to be passed in (as part of the options object) for all functions in p5.Font, the way it is now in _renderPath, and in your PR. I can't think of any disadvantages to this offhand.

**Comment by mikewesthad** [comment]
@dhowe right, good point.  I just took a look to see what else could use an options parameter:

`p5.Font.textBounds` & `p5.Font.textToPoints` have fontSize as an explicit parameter.  Since those are part of the public API, an options parameter might confuse beginners reading the docs.

`p5.Font._renderPath` has options, and `p5.Font._getPath` will have it if the PR is okay.

`p5.Font._handleAlignment` is being passed a reference to a specific p instance, so in theory, it should have the renderer.  But it is calling `p5.Font._textWidth`, etc. without passing in an argument, so those methods are looking up fontSize from `this.parent` rather than the specific p instance.  That seems like it could be problematic, so fontSize should probably be pulled from the p instance's renderer.  (The p variable here could be nixed in favor of an options parameter - for consistency with _renderPath and _getPath.)

`p5.Font._textWidth`, `p5.Font._textAscent`, `p5.Font._textDescent` &  `p5.Font._scale` already have fontSize as a parameter and don't seem to need a reference to the renderer.  That said p5.Renderer2D is calling those methods without supplying a fontSize.  That also seems like it could be a problem, but since fontSize is a parameter, that seems like a place where the 2D renderer should just pass in its font size.

**Comment by mikewesthad** [comment]
[Codepen demo](http://codepen.io/mikewesthad/pen/NNmYvr) for bug with `p5.Renderer.textWidth`.

[Codepen demo](http://codepen.io/mikewesthad/pen/MyRVEv) for bug with `p5.Font._handleAlignment`.

These all are related to the same issue, so I'm posting them here rather than in a new issue.  I can fix these two in the existing PR.

**Comment by dhowe** [comment]
Sounds good. I'm on deadline for the next 24 hrs, but will get back to this after...

**Comment by mikewesthad** [comment]
Since #1415 is merged, I'm going to close this issue.
