### ISSUE TITLE
p5.Font.textBounds does not take into account text alignment

### ISSUE THREAD

**Issue by mikewesthad** [processing/p5.js#1416]
Hopefully I'm not flooding things with `p5.Font` bugs.  I was working on a demo using a `p5.Font` to create text particles, and I noticed that `p5.Font.textBounds` doesn't adjust the bbox's (x, y) coordinates based on the renderer's text alignment settings.  It defaults to opentype's positioning scheme: left & baseline.

[Codepen demo](http://codepen.io/mikewesthad/pen/QNPxLz).  Below is a snapshot from the demo.  The orange dot is the (x, y) anchor where the text is being drawn.  The orange box is the bbox.  The gray text displays the alignment settings ("horizontal-vertical") for the text.

I'm looking at `p5.Font` now.  I think it's just a matter of shifting the (x, y) at the top of `Font.textBounds` (using `Font._handleAlignment`) and making sure that caching stays intact.  I'll work on a suggested PR.

![image](https://cloud.githubusercontent.com/assets/1131802/15269770/821744ce-19cf-11e6-8039-e110fc71a5f3.png)

**Comment by dhowe** [comment]
Nice work! This looks really close but the dot-position for valign=TOP looks incorrect to me. Here is what we get in Processing (which is our target, but doesn't have a built-in textBounds function):

![screen shot 2016-05-15 at 8 46 50 pm](https://cloud.githubusercontent.com/assets/737638/15274123/5147dc36-1ade-11e6-97d4-6fd6fc93a9b3.png)

**Comment by dhowe** [comment]
I wonder also if we need to consider #766 here...

**Comment by mikewesthad** [comment]
For posterity purposes, summarizing the discussion from #1417 here: Vertical alignment looks to be an independent issue, opened #1421 to deal with that.

**Comment by lmccart** [comment]
closed with https://github.com/processing/p5.js/pull/1417, #1421 remains to address vertical text
