### ISSUE TITLE
createSlider() optional 4th argument (step size) not documented

### ISSUE THREAD

**Issue by Moldy01** [processing/p5.js#1419]
This is a suggestion.  In working with some sliders, I found that things work well if I use whole numbers.  However, when I tried to create a slider going from 1.1 to 3, the slider was non functional.  That is, it either slid to the far left (minimum value) or back to the default value.

I'd like to suggest that some re-work the sliders to allow them to accept decimal values, possibly by adding a 4th parameter "step-size".

**Comment by shiffman** [comment]
Indeed!  This is in fact implemented as a fourth argument.   However, I just checked and it's not in the documentation (http://p5js.org/reference/#/p5/createSlider).  I'll update the title of this issue to reflect this missing info.

**Comment by limzykenneth** [comment]
Done, added an example as well~

**Comment by lmccart** [comment]
closed with https://github.com/processing/p5.js/pull/1426

**Comment by shiffman** [comment]
Thank you!!
