### ISSUE TITLE
Getting error message in console that doesn't make sense

### ISSUE THREAD

**Issue by ldlathrop** [processing/p5.js#1420]
Hello! When I run my sketch in my browser, it doesn't load and I get the following message in my Console:  

    Did you just try to use p5.js's exp() function? If so, you may want to move it into your sketch's setup() function.

    For more details, see: https://github.com/processing/p5.js/wiki/Frequently-Asked-Questions#why-cant-i-assign-variables-using-p5-functions-and-variables-before-setup

But I don't think I'm using an exp() function and everything seems to be in the right place (I think), and the FAQ it directs me to does not seem to relate to what's going on (or, rather, I should say what's NOT going on!).

I've actually submitted this to the Processing/p5.js forum, but haven't received the guidance I need. I'm just learning p5.js, after working in R for years, and I've read both the intro to p5 book and the Processing book, but I'm at a complete loss.

My github repo with the code and files: https://github.com/ldlathrop/p5.js-learning-files

UPDATE: I kept working on the code and can get the canvas to appear, but no words. I'm pretty sure I have an issue with how I've defined the variables in `setup()`, but I can't find any documentation anywhere that addresses how to deal with two related columns of data and to use that in a data viz.

**Comment by lmccart** [comment]
hi @ldlathrop since your code is a bit complicated, it's difficult for me to tell what could be causing the problem here. I'd suggest commenting out parts of your code until you can get something to show up, and then slowly adding them back in until you find the line of code that seems to cause the problem.

**Comment by ldlathrop** [comment]
hi @lmccart. I've been trying that and still can't seem to figure it out. I will keep trying, but could you please tell me if I've written the preload/setup correctly. I've got a csv data set that looks (partially) like this printout from R:

    > head(read.csv("cltop.csv"), 10)
        ID     Words Frequency
    1   45    across        13
    2   99  actually         8
    3   53    always        11
    4    3   america        39
    5   30  american        16
    6   25 americans        18
    7   93    anyone         8
    8   65   believe        10
    9  100      best         8
    10  96    better         8

What I'm trying to do is extract the words and their frequencies into arrays in order to map them through my constructor function with size and color of each word displayed according to its frequency. 

The reason I ask is that on the Processing forum, it was suggested that my `setup() for loops` were probably the cause of the problem, but that person didn't have a solution. I've also been looking through all of the p5 reference material and examples, but I don't see anything that discusses extracting two or more variables of data from a table for use in a sketch. Maybe I'm missing something, but the only text examples I've found discuss text that is manually entered and then printed to the screen. The [p5.js Reference for p5.Table](https://p5js.org/reference/#/p5.Table) lists a lot of different ways to extract columns, rows, strings, etc., but doesn't really say when to use which one.

**Comment by lmccart** [comment]
Here is a basic example that demonstrates printing out the frequency of each row:
```javascript
var clinton;

function preload() {
  clinton = loadTable("cltop.csv", "csv", "header");
}

function setup() {
  console.log(clinton);
  for (var i = 0; i < clinton.getRowCount(); i++) {
    var freq = clinton.getNum(i, "Frequency");
    console.log(freq)
  }
}
```

This seems to work for me when I test it out, I see the frequency column value for each row printed to console. Hope this helps!

I'm going to close this issue since it's not a specific bug with the library, but if you need further help, please feel free to post on the forum.
https://forum.processing.org/two/categories/p5-js-programming-questions
