### ISSUE TITLE
Vertical text alignment doesn't match processing

### ISSUE THREAD

**Issue by mikewesthad** [processing/p5.js#1421]
In #1417, @dhowe pointed out that the vertical alignment (specifically vertical align = TOP) for text in p5 doesn't match processing.

Snapshot from a [codepen demo](http://codepen.io/mikewesthad/pen/QNPxLz) in p5
![image](https://cloud.githubusercontent.com/assets/1131802/15276092/436a26f4-1aa3-11e6-8ab3-8edd1bfc36ef.png)

@dhowe's snapshot from processing
![image](https://cloud.githubusercontent.com/assets/1131802/15276089/2fe68104-1aa3-11e6-8c77-0a75cd5ffe62.png)

I'm checking this out now, but my guess is that the problem comes from this [line](https://github.com/processing/p5.js/blob/master/src%2Ftypography%2Fp5.Font.js#L426) in `p5.Font._handleAlignment`.  When the text is set to be drawn with baseline top, the y coord is shifting by `textHeight` but should instead be shifted by `textAscent`.  As far as I can tell, that's what Processing does.

**Comment by lmccart** [comment]
looks like this one is set then? or is there more to do here still?

**Comment by mikewesthad** [comment]
Yeah, #1421 fixes this for most fonts, so this can be closed. There's still going to be some small amount of inconsistency between processing vs p5 system font vs p5 opentype font since they all use different methods of calculating baselines (sampling a raster vs browser canvas vs values specified by font designer).

**Comment by dhowe** [comment]
I believe that we still need to deal with vertical alignment for multi-line text however (see https://github.com/processing/p5.js/issues/1410)

**Comment by mikewesthad** [comment]
@dhowe, right - yeah this issue/PR was single line focused, so mutli-line is still a problem.  I can pitch in over on that issue if no one else is already working on it.

**Comment by dhowe** [comment]
If you have the bandwidth, that would be great -- I'm in semester grading so won't get to it for a while...
