### ISSUE TITLE
typography functions

### ISSUE THREAD

**Issue by Moldy01** [processing/p5.js#1422]
It would seem that typography functions are NOT available in WEBGL.  I created sliders for a small project, and then attempted to "label" them using text().  Every function that I try out, is "Undefined".

**Comment by jguess** [comment]
I see that currently there is work being done on font and typography features. Any chance to make it work in the 3D renderer ???
Hope so as I have a big project that I've wanted to port to P5 for a long time and the only stumling block is text() in WEBGL.
Thanks !!!

**Comment by karenpeng** [comment]
Hi @Moldy01 @jguess, text geometry in webGL mode is not supported, an easy way for now, could be making the text as a texture and use it on a plane geometry. Will that work for you?

**Comment by jguess** [comment]
yes, i think that’s what i will try to do.
thanks a lot for your response !

**Comment by Moldy01** [comment]
Thanks Karen.

I was must playing around in the p5 arena and found that the text didn't.  I thought that I'd just bring it to someone's attention.

From the Desk of 
Mitch Oldroyd
c-(801) 380-0952
Hope you are having a 
GREAT day  


Date: Sat, 21 May 2016 00:03:40 -0700

**Comment by jguess** [comment]
hmm, i can't seem to figure out how to use text as a texture in p5. any ideas ?

**Comment by indefinit** [comment]
Hi @jguess, functionality for rendering text as a texture is not yet implemented but I know this is an important feature and my next PR will include this functionality.  In the meantime, the only way to render text while drawing in webgl is to use the DOM api and createP() or createSpan() with your text like this:
```
var myP = createP("hello awesome paragraph");
myP.position(width/2, height/2);
```
Thanks for your patience and stay tuned.

**Comment by indefinit** [comment]
Submitted a PR which will implement the functionality of text as a texture.  A future addition will include a full implementation of text() in webgl mode but in the short term once PR #1435 is merged, you will be able to use text as a texture in webgl like this:

```
var pg;
  function setup(){
    createCanvas(100, 100, WEBGL);
    pg = createGraphics(256,256);
  }
  function draw(){
    background(0);
    pg.background(255);
    pg.text('hello world!');
    //pass image as texture
    texture(pg);
    plane(200);
 }
```

**Comment by jguess** [comment]
ok great thanks! that was exactly the approach that i had tried but it wasn’t implemented yet !

**Comment by lmccart** [comment]
closed for now with https://github.com/processing/p5.js/pull/1435
