### ISSUE TITLE
Texture UV coordinates?

### ISSUE THREAD

**Issue by harveymoon** [processing/p5.js#1424]
Processing has the ability to choose UV coords for vertex Pshapes.
`vertex(x, y, u, v)`

How can this work with p5js? Is this possible?

**Comment by indefinit** [comment]
Right now vertex() doesn't support u,v's but this is a good feature request, especially for the webgl renderer.  I'm doing some work on beginShape and endShape now, so this should fit nicely into that upcoming PR.  Use case would look like the example here:  https://processing.org/reference/vertex_.html

We'd also need to implement a textureMode() function for mapping u,v's.

**Comment by JeroenDerks** [comment]
This feature would be so great.
Does anyone have any updates on the matter?

**Comment by dhowe** [comment]
big +1 for this

**Comment by cqx931** [comment]
+1 Need this feature in p5.js for a project.

**Comment by dhowe** [comment]
any progress here?

**Comment by kjhollen** [comment]
added in #2166!
