### ISSUE TITLE
Edge support

### ISSUE THREAD

**Issue by miguelarian** [processing/p5.js#1427]
Does P5 Sound work on Microsoft edge?

Openning this link on Edge does not play the audio :(

https://p5js.org/reference/#/p5.SoundFile

Thanks,
Miguel.

**Comment by lmccart** [comment]
it should. it depends what is natively supported by microsoft edge. you can post further issues regarding this in the p5.js-sound repo: https://github.com/processing/p5.js-sound

**Comment by limzykenneth** [comment]
@miguelarian Not sure what the current WebAudio support on Edge is like but according to the [wiki](https://github.com/processing/p5.js/wiki/Supported-browsers), WebAudio was not supported on Edge as of May 2015
