### ISSUE TITLE
CreateGraphics weirdness

### ISSUE THREAD

**Issue by harveymoon** [processing/p5.js#1429]
After having some sizing issues, i tried to modify the web-tutorial on the createGraphics() function.

Here is a simple sketch of my problems:

The 'pg' var should be exactly the same as the canvas, except for a darker background.
What it seems to do is cut the PG in half. If I try to place the PG in the corner filling the screen, it only shows half.
if I pinch in the pg to .5 of the screen, it looks correct but is not the size I want. 
Is this an issue or on my side?

`
var pg;

function setup() {
  createCanvas(500, 500);
  pg = createGraphics(500, 500); //same exact size as the canvas window.
}

function draw() {
  background(200);
  pg.background(100);

  ellipse(width/2, height/2, 50, 50);
  pg.ellipse(width/2, height/2, 50, 50);

//when below is uncommented:
//should look like a darker version of the background
//image(pg, 0, 0,width,height);

when below is uncommented:
looks like it did ellipse correctly, but sizing is 1/2 real size
// image(pg, 0, 0,width/2,height/2);

}`

**Comment by mikewesthad** [comment]
@harveymoon what effect are you trying to achieve?  Are you trying to get `pg` to cover the entire screen?  If so, and `image(pg, 0, 0, width, height)` is not doing that, then that sounds like a bug.

Maybe this will help clarify what's going on.  [Here](http://codepen.io/mikewesthad/pen/aNgawR) is an online code editor with a script showing the ways you could use `image(pg, ...)`.

The `image(...)` command works like this:

![image](https://cloud.githubusercontent.com/assets/1131802/15446150/6f881c00-1edb-11e6-80dd-eecd4dcb32b8.png)

The source image is your `pg` and the destination image is your canvas.  The p5.js documentation [here](http://p5js.org/reference/#/p5/image) lays out what those parameters mean.

**Comment by harveymoon** [comment]
The issue I am having is also apparent in your code example.

`  pg.ellipse(pg.width/2, pg.height/2, 50, 50);`

This says to me that you are trying to draw an ellipse in the center of the pg space. In your example, a circle should be placed at 100,100 in the 200,200 space of pg.

Why then does the pg look like this?:

<img width="240" alt="screen shot 2016-05-26 at 2 18 40 pm" src="https://cloud.githubusercontent.com/assets/4907971/15590471/d7e2d1b2-234c-11e6-8552-077dca4ee5f4.png">

and not this:

<img width="213" alt="screen shot 2016-05-26 at 2 20 38 pm" src="https://cloud.githubusercontent.com/assets/4907971/15590506/1091b01e-234d-11e6-897b-907c97c85dab.png">

**Comment by mikewesthad** [comment]
@harveymoon, ahh - thanks for taking a snapshot. That is not how it looks on my machine.

I've run into something similar before. Can you check out the [codepen](http://codepen.io/mikewesthad/pen/aNgawR) again?  If you are on a high DPI screen (like a retina mac), this might get things looking like you expected: `pg.pixelDensity(1)`.  I added that to the codepen.

**Comment by harveymoon** [comment]
THATS IT!
I am on a MBP. This is very good to know.
 Thanks Mike!

**Comment by krongeroso** [comment]
Thanks @mikewesthad.
 I was trying to solve this for many hours!! 
pixelDensity(1) was the solution!! :D
