### ISSUE TITLE
Mouse generates touch events but not touches[] entries

### ISSUE THREAD

**Issue by hobzcalvin** [processing/p5.js#1434]
touchStarted(), touchMoved(), and touchEnded() are called when clicking/dragging/releasing the mouse respectively, but the touches[] array is always empty. Compare to real touch events on a mobile device, which work as expected.

The mouse x/y should either appear in the touches[] array OR touchStarted() etc. should not be called for mouse events.

**Comment by lmccart** [comment]
the touches[] array is only populated by actual touches, and includes a data object that includes the x, y, and id of that particular touch. it's useful for tracking fingers for multitouch. this doesn't make as much sense for mouse, so only the mouseX/Y and touchX/Y variables are updated.

**Comment by hobzcalvin** [comment]
I'm writing a p5.js app that wants to work with both multi-touch and mouse events and this confused me for a while. Why trigger touchStarted(), touchMoved(), and touchEnded() at all when a mouse is clicked? Why update touchX/Y? Why do these make any more sense for multitouch when there are already mousePressed(), mouseDragged(), and mouseReleased() events for mouse and mouseX/Y? Simply by naming convention, it's inconsistent for some `touch*` stuff to work the same as `mouse*` stuff but not always.
