### ISSUE TITLE
new feature : mouse event outside canvas should (optionnaly) be ignored

### ISSUE THREAD

**Issue by swirly** [processing/p5.js#1437]
I'm planning to implement some game exemple for my pupils with p5js. I've found a strange issue. mouse events (clicks) outside the canvas are taken into account.

I understand it can be usefull. On the contrary, it can be disturbing.

Planning a small game where you can click on a figure to win, clicking on a button or a menu outside the canvas brings up a fail in the game (unintended)

An optionnal parameter ( canvasClickMode() function ?) should be used.

**Comment by lmccart** [comment]
In p5.js, the entire browser window is considered your sketch, so a click anywhere in it triggers mousePressed() and other mouse listeners. If you'd like to only listen to the canvas, you can do something like:

```javascript
function setup() {
  var c = createCanvas(100, 100);
  c.mousePressed(doStuff);
}

function doStuff() {
  console.log('clicked on canvas');
}
```

http://p5js.org/reference/#p5.Element/mousePressed

**Comment by xavierbacalla** [comment]
I know that issue #1437 is already closed and long overdue but what worked for me was enclosing the event inside an if statement such that it would only run `if (mouseX <= width && mouseY <= height)`.

**Comment by coby1kenobi** [comment]
Worked for me too! Thanks for this
