### ISSUE TITLE
p5 Reference Problems

### ISSUE THREAD

**Issue by alelepd** [processing/p5.js#1441]
Hey there I noticed these problems on the reference/website:
1. There is a serious scrolling problem on the site (but most noticeable on the reference), it constantly stop from scrolling or start to lag.
2. If you open a link and go back, you can not stay at the vertical position you where before (which is considered bad usability).
3. There is a buggy behaviour when trying to copy something from the code examples, its slow and has lag like the scrolling on the site.

I suspect that all these problemas have to do with the js on the page.

Im using a MacBook Pro (Retina, 15-inch, Mid 2014).

**Comment by limzykenneth** [comment]
I can relate to 2 and 3 there, not quite seeing 1 on my side. If I can find some time this week, I'll try to put together a PR that solves 2, @toolness might be working on 3 I'm not sure, just what I saw at p5.js-website [#241](https://github.com/processing/p5.js-website/issues/241)

**Comment by alelepd** [comment]
Great. Hope it can solve! I wish I could help but I am still learning :/

Thanks!

**Comment by toolness** [comment]
Hi! Yeah, these are definitely issues on the site, thanks for reporting them!  Although like @limzykenneth I'm not seeing 1 on my side--what browser/OS are you using, and is there a particular page on which the scrolling is really bad?

**Comment by toolness** [comment]
Oh regarding (3), @limzykenneth, I'm not sure if that's actually the same issue that I'm addressing in https://github.com/processing/p5.js-website/issues/241... It sounds like copying text does *work* for @alelepd, it's just slow and has lag? (In my experience, copying text from the examples requires the user to click "edit" and then copy the text--the non-editable version isn't copyable, which I'd like to fix.)

**Comment by limzykenneth** [comment]
@toolness I think the two are kinda related which I guess if solved one would solve the other. I don't think @alelepd is trying to copy from the edit screen, at least from what I've tried, copying does work without going into edit, it's just as @alelepd mentioned, buggy and maybe a bit of lag, and I can't highlight thus copy any lines overlapping horizontally with the canvas...

![screen shot 2016-06-05 at 7 57 17 pm](https://cloud.githubusercontent.com/assets/7543950/15807502/ba8b6d14-2b57-11e6-988f-37d89eb2608d.png)

**Comment by toolness** [comment]
Oh interesting! My bad... I'll see if I can fix that in https://github.com/processing/p5.js-website/issues/241 !

**Comment by toolness** [comment]
Ok, I think I just made text selection a bit less buggy in https://github.com/processing/p5.js-website/pull/255.

**Comment by omundy** [comment]
Hi, I can attest to the scrolling issue. It makes it very frustrating to use the documentation. It looks like its associated with whatever scripts are moving the navigation. Probably could change those to use CSS? Here's a [video](https://youtu.be/WT42eCwVxoY). Scroll down, then up to replicate.

**Comment by lmccart** [comment]
these issues have been addressed
