### ISSUE TITLE
Weather example on the website is broken

### ISSUE THREAD

**Issue by shirish93** [processing/p5.js#1446]
Hi,

The weather example on the website is broken, since most modern browsers down't allow loading content from non-https sites.

```
p5.min.js:3 Mixed Content:
The page at 'https://p5js.org/examples/demos/Hello_P5_Weather.php' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 
'http://api.openweathermap.org/data/2.5/weather?q=New%20York,NY&units=imperial&APPID=7bbbb47522848e8b9c26ba35c226c734'. 
This request has been blocked; the content must be served over HTTPS.
```
Since it's the less-experienced who are likelier to check the documentation, I imagine this example would only confuse/mislead them.

In case there is any interest in replacing the example (I see the codebase has a spotify example already), I can work on that, if no one else is looking at it. In either case, using something like the following, that serves requests over Https, might be useful:

https://www.omdbapi.com/?t=Frozen&y=&plot=full&r=json

**Comment by toolness** [comment]
Oh, that's unfortunate--I didn't even know that the p5 website was available over HTTPS... It also appears that [OpenWeatherMap only provides HTTPS to paid Professional and Enterprise accounts](https://openweathermap.desk.com/customer/portal/questions/8166727-http-to-https), which is not ideal, especially in this era that encourages people to use HTTPS everywhere.

One workaround here might be to take advantage of the fact that p5js.org is served over *both* http and https, and transparently switch over to http when users are on that particular example. I don't think I like it, though... :disappointed:

**Comment by lmccart** [comment]
interesting... yeah, we added the HTTPS to deal with the fact that most browsers will only allow getUserMedia over HTTPS. if this is the only thing standing in the way of redirecting HTTP -> HTTPS completely, maybe we should look around for another weather API that serves over HTTPS?

**Comment by lmccart** [comment]
well the HTTP/HTTPS confusions and issues still stand, but this example is fixed with https://github.com/processing/p5.js-website/commit/8705f2a3c9e01995a486059d754bf422fb415973
