### ISSUE TITLE
Event type question

### ISSUE THREAD

**Issue by ldlathrop** [processing/p5.js#1447]
I've read all of the documentation on events, and I'm wondering whether it is possible to get an animation to start once it appears on the user's screen, i.e., when they scroll down to it. I'm thinking of something along the lines of how a Facebook video will start running when you scroll to it and then stop when you scroll out. I've looked all over and can't see that as a p5 event feature.

**Comment by lmccart** [comment]
You can wait to call `new p5()` until the moment you want to start the sketch, and you can use `.remove()` to stop and remove the p5 sketch. If you'd like to just toggle the draw loop on and off, it'd be better to use `loop()` and `noLoop()`.
