### ISSUE TITLE
Question about depth

### ISSUE THREAD

**Issue by doylecentral** [processing/p5.js#1450]
I was looking at one of the examples with the button click using the dom lib. Is there a setting that when the background color changes that it doesn't put it on top of already drawn shapes? When I did the demo it covered my shapes.

**Comment by chiunhau** [comment]
@doylecentral what background() does is actually filling the whole canvas with a color, so naturally it will cover anything already drawn before. There's no layer in p5 so you need to redraw everything in the next frame. Hope this help 😄

**Comment by doylecentral** [comment]
Yes and thanks. I was drawing objects on setup but I can put them in the event loop.
