### ISSUE TITLE
loadJSON question

### ISSUE THREAD

**Issue by igarbla** [processing/p5.js#1451]
I'm trying to load a dataset from http://opendata.euskadi.eus/contenidos/ds_eventos/eventos_turisticos/opendata/agenda.json but it fails for some reason.

```js
var values;
var url = "http://opendata.euskadi.eus/contenidos/ds_eventos/eventos_turisticos/opendata/agenda.json";

function setup() {
  createCanvas(600,400);
  loadJSON(url, gotData, "jsonp");
}

function draw() {
  //  Some stuff
}

function gotData(data) {
  values = data;
}
```

I can see in the dev tools of the browser that the data is sent but i have an error saying `TypeError: resp is undefined` referencing p5.js:5209:11

Thank you.

**Comment by igarbla** [comment]
Sorry, the spellchecker has changed the word function. My main language is spanish.
Sorry again.

**Comment by chiunhau** [comment]
Hi @igarbla which version of p5js are you using?

**Comment by igarbla** [comment]
This is at the beginning of the p5.js file:
/*! p5.js v0.5.0 May 02, 2016 */

**Comment by toolness** [comment]
Hi @igarbla! It looks like your code says it's trying to get [JSONP](http://stackoverflow.com/a/3840118/2422398) content:

```js
loadJSON(url, gotData, "jsonp");
```

However, the URL being fetched, [`agenda.json`](http://opendata.euskadi.eus/contenidos/ds_eventos/eventos_turisticos/opendata/agenda.json), is JSON, not JSONP.

I suspect this is why your code is giving the weird unhelpful error--and that's one that we ought to make more helpful in p5, so thanks for reporting this issue!

Ideally, the fix here would be to remove the third argument you're passing to `loadJSON()`.  However, the JSON resource at that URL doesn't appear to support [cross-origin resource sharing](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing), which is what's needed in order for your sketch to access it.

Unfortunately, that means that I'm not sure how your sketch can access the information... If the data at that URL doesn't change often, could you try just copying it to your sketch's directory and loading it from there?

**Comment by igarbla** [comment]
Hi @toolness, thank you for your answer. I'm using the function loadJSON with the "jsonp" argument because if it is not present the response is empty. If i use the function with the argument the data is received but as you have noted is JSON, not JSONP.

Of course i can download the file, in fact i do and it works, but i was playing around with p5js following @shiffman video tutorials and wondering what i was doing wrong.

Maybe i could try to talk with the provider of the datasets.

Again, thank you very much.

**Comment by toolness** [comment]
Oh, gotcha... so the reason that the response is empty is actually because it doesn't have those cross-origin resource sharing (CORS) headers in them, which basically are the signal from the site author that says "i permit code on other websites to access this file". Without that indication, a browser is forced to provide an empty response. :disappointed: 

Talking to the provider of the datasets is definitely an option! All they really have to do is add a HTTP header to that URL that looks something like this:

```http
Access-Control-Allow-Origin: *
```

And your code (without the `"jsonp"` parameter) should be good to go.

**Comment by igarbla** [comment]
HI @toolness , i've just received an email from the provider saying you're right :+1: 
They are going to do the changes and upload them to the server. They will be available the next week.
Again, thank you very much for your help.

**Comment by igarbla** [comment]
Well, they've made the changes and now everything works. They've wrapped the response in a callback instead of adding a HTTP header so now I've to add "?callback=jsonCallback" to the url in order to work.

I think this issue can be closed.

BTW this change has broken my processing sketches but for this i should go to the processing forum.
