### ISSUE TITLE
SoundFile docs are inconsistent.

### ISSUE THREAD

**Issue by meiamsome** [processing/p5.js#1452]
In the description we have:
"Values less than zero will reverse the audio buffer."
In the parameter we have
" Must be greater than zero."

Negative values appear to work for me, but I don't know which is the correct behaviour so I am opening this issue so someone who knows can fix it.

**Comment by limzykenneth** [comment]
I'm not sure about the behaviour of p5.sound but the code and documentation for p5.sound is in another repo, you can copy and paste this issue over [here](https://github.com/processing/p5.js-sound/issues) instead. Cheers.

**Comment by meiamsome** [comment]
Ah, okay, I'll go do that - should this issue be closed? I didn't see it had its own repo. (Also, the docs for the sound library point to here for issues - is that intended?

**Comment by limzykenneth** [comment]
@meiamsome Yeah you can close this and open an issue there instead. Thanks.

Hmm...interesting, I think the docs only point to here generally, it would be great to have it point to the right repo though...
