### ISSUE TITLE
image(src, dest) doesn't seem to work

### ISSUE THREAD

**Issue by Bryce-Summers** [processing/p5.js#1453]
I was trying to draw an entire source image onto a smaller section of screen via something like the following:

image(0, 0, image_w, image_h, 0, 0, screen_w/2, image_h*screen_w/image_w);

The result was that the image was drawn on the region screen_w, screen_h, which was not correct and produced a result that was much too tall.

image(x, y, screen_w/2, image_h*screen_w/image_w) however did produce the correct result. I am assuming that it would have also not worked if I had been trying to draw a sub image, instead of the entire image.

**Comment by hellonearthis** [comment]
If you image is loaded into **img**  then it should look like this  if you were outputting to half the screen size. 
   ` image(img, 0, 0, img.width, img.height, 0, 0, screen.width/2 , screen.height/2)`

**Comment by Bryce-Summers** [comment]
Yep, that is what I had.
The values I pass in for image_w, image_h, screen_w, screen_h are:
2816, 2081, 496, 366.53977272727275

but when I run it on my Google Chrome web browser it draws the image as if I had written:
2816, 2081, 496, 2081

**Comment by Bryce-Summers** [comment]
There is probably an error somewhere inside of p5JS where the value of image_height is used instead of the inputted value of screen_height

**Comment by hellonearthis** [comment]
It could be that float causing issues maybe.   You could try a Bitwise OR operator.
image(0, 0, image_w, image_h, 0, 0, screen_w/2, image_h*screen_w/image_w**| 0**);
http://stackoverflow.com/a/12837315

**Comment by Bryce-Summers** [comment]
I don't think that is the case. I tried it with the bitwise OR operators and good old fashion Math.floor(), but I really think it is a bug in the image drawing function

**Comment by hellonearthis** [comment]
That's rough,  what if you just add the value desired or took the equation
out of the image statement and used a single var.

**Comment by Bryce-Summers** [comment]
That is what I am doing in my actual code. It doesn't work. I found a work around for my particular case though, but this bug should be addressed.

**Comment by lmccart** [comment]
hi @Bryce-Summers, I'm not able to reproduce this. I'm running in chrome the following code:
```javascript
var img;

function preload() {
  img = loadImage('assets/cat.jpg');
}

function setup(){
  createCanvas(windowWidth, windowHeight);
  background(200);

  image(img, 0, 0, img.width, img.height, 0, 0, width/2, width*img.height/img.width);
  //image(img, 0, 0, width/2, img.height*width/img.width)
}

```

Both the last two lines, the original line that wasn't working for you, and the commented out line that did work seem to produce the same results. Are you loading your image in preload() or using a callback? If you aren't doing one of these things it could be that the image isn't loading in time to draw correctly.

**Comment by Bryce-Summers** [comment]
I tested the following code on my machine with Google Chrome version Version 50.0.2661.102 m
`
var img;

function preload()
{
	img = loadImage("images/B.png");
}

function setup(){

  var screen_w = (window.innerWidth  - 1);
  var screen_h = (window.innerHeight - 1);

  createCanvas(screen_w, screen_h);
  background(200);

  image(img, 0, 0, img.width, img.height, 0, 0, screen_w/2, screen_w/2*img.height/img.width);
  //image(img, 0, 0, screen_w/2, img.height*screen_w/2/img.width)
}
`

The first line produced the following visual result:
![line1](https://cloud.githubusercontent.com/assets/7748048/15982114/dc107412-2f34-11e6-8cd7-bfe9e2eca9af.png)

The second line produced the following (correct) result:
![line2](https://cloud.githubusercontent.com/assets/7748048/15982121/ebbed67e-2f34-11e6-8492-6b6de923a127.png)

I haven't updated my version of p5JS in a while, so I will see if updating it to the latest version fixes the issue.

**Comment by Bryce-Summers** [comment]
Ah! My version was outdated and the latest version produces the correct behavior.
