### ISSUE TITLE
Split() function not working

### ISSUE THREAD

**Issue by ldlathrop** [processing/p5.js#1458]
I have a .csv file that I'm calling in JavaScript through a p5.js sketch. One of the fields contains sentences that range from 103 char to 328 char. My script calls the data and displays in randomly on the canvas. Because some of the sentences are very long, they aren't fitting on the canvas properly, so I'd like to split them into 2- or 3-line strings.

I won't post my whole code, but here is the `setup()` snippet:

    function setup() {
      canvas = createCanvas(680, 420);
      canvas.mousePressed(inWidth);
      background(51);
      // Calling noStroke once here to avoid unecessary repeated function calls
      noStroke();
      // iterate over the table rows
      for (var i = 0; i < clContext.getRowCount(); i++) {
        var category = clContext.get(i, "category");
        var statement = clContext.get(i, "statement");
        var polarity = clContext.get(i, "polarity");
     // split long statements that have '\r\n' in them and add the rest as a second or third line
        statement = split(statement, "[\\r\\n]+");
     // creates `display()` object from `Statement` constructor (not shown)
        statements[i] = new Statement(category, polarity, statement);
      }
    }

I have also tried using the code from the p5.js reference for `splitTokens`, i.e., `var stateArr = splitTokens(statement, "\\r\\n");` I have tried various configurations based on native js, e.g., `var array = sentence.split("\n").map(x => x.trim());`, but that just throws an error that `sentence.split is not a function`. And now I've tried what's there now, including putting it in a `for` loop, as well as `String[] list = split(statement, '\\r\\n');` from the [Processing reference](https://processing.org/reference/split_.html), but I have not found a solution that works.

Here is a screenshot of what I'm doing. The sentences for each candidate appear randomly on the screen, colored according to whether they are positive or negative, and they move across the screen.
<img width="200" alt="screen shot 2016-06-11 at 7 27 51 am" src="https://cloud.githubusercontent.com/assets/13222955/15985549/51198a0c-2fa6-11e6-9d11-66d553c4eacf.png">

**Comment by limzykenneth** [comment]
I can't really debug your code because I have no idea where `clContext` came from and what it is. Maybe you can simplify the example? That way we can test it out and it might also help you isolate the problem.

If you get an error with native js saying `sentence.split is not a function` it means `sentence` is probably of the wrong type, ie. not a string. Try do a `console.log(sentence)` and check if the logged item is really a string.

Also `String[] list = split(statement, '\\r\\n');` wouldn't work here since that's Java syntax not javascript syntax. Explicit type conversion in javascript is usually done with `.toString()` although most of the time you don't need to use it.

**Comment by ldlathrop** [comment]
Hi @limzykenneth Thanks. I have checked with `console.log(typeof statement)` and `statement` is a string, though after I run `split` or `splitTokens` on it, it then becomes objects.

`clContext` is a .csv file, with columns for the statements and the polarity, i.e., whether it is positive or negative. This is for a data journalism project about Hillary Clinton's and Donald Trump's speeches. The data files are in a GitHub repo here: http://github.com/ldlathrop/Data-Visualization/tree/master/context-clinton. The sketch.js file has my entire script (including many attempts to split that have been commented out) and there are a couple of functions added from a suggestion in the Processing/p5 forum, functions that didn't accomplish what I need, though. The data file I'm using is the "cl_context_rev.csv" one. 

Any help would be truly appreciated. I spent all day yesterday trying things I found on StackOverflow and elsewhere, but cannot for the life of me get this to work. It seems like it should be easy, but it's not.

**Comment by ldlathrop** [comment]
Also, @limzykenneth , when I run the `splitStringAtSpace` function that I got from the forum and run it through `console.log`, the console shows that the statements have been split, but they don't appear that way on the screen. They're all still showing on a single line.

**Comment by Craigson** [comment]
Hi Lesley,

Not sure if this is helpful, but if you'd like to keep the string together
and avoid the splitting altogether, why not make use of p5's DOM elements?
You could create a an HTML element and add it to the canvas, which would
then allow you to control spacing / textwrapping etc. using CSS...


Something like:

var statement = clContext.get(i, "statement");

var sampleStatement = createP(statement).addClass("someClass");


This example might be useful:
http://p5js.org/examples/examples/Dom_Modifying_the_DOM.php


On Sun, Jun 12, 2016 at 8:15 AM, Lesley Lathrop <notifications@github.com>
wrote:

> Also, @limzykenneth <https://github.com/limzykenneth> , when I run the
> splitStringAtSpace function that I got from the forum and run it through
> console.log, the console shows that the statements have been split, but
> they don't appear that way on the screen. They're all still showing on a
> single line.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/processing/p5.js/issues/1458#issuecomment-225429217>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEbNrPW7BM_7jw50thtpbKDwayimHh_Lks5qK_h0gaJpZM4IzkCk>
> .
>



-- 
--
Craig Pickard
M.P.S Candidate in the Interactive Telecommunications Program, NYU
{ http://craigpickard.net }
{ 929 240 4478 }

**Comment by limzykenneth** [comment]
@ldlathrop Okay, I had a look and the problem might be because of matching against `\r\n` as you may know, `\r` and `\n` have special meanings, one being line return and one being line break. For complicated reason that I have suspicion but no conclusion of, the `\r\n` is either already escaped or not recognised or some other can of worms, which makes it hard to deal with.

What I would suggest are 3 solutions,

1. Use regular expression for the native `split()` function:

```javascript
statement.split(/\\r\\n/gm);
```

2. Use other newline delimiter, `<br>` even.

3. Use p5.dom like @Craigson mentioned, which I think might be the best solution since you don't need to worry about where the line breaks occur.

Let me know if that helps. Cheers

**Comment by ldlathrop** [comment]
Hi @limzykenneth I had tried "statement.split(...)` with various configurations, and always got an error that `statement.split` is not a function. As for @Craigson's suggestion, I'm just not advanced enough with JS or p5 to do something like that. I did try, using the example from the p5 references, but I couldn't make heads or tails of how to go about it **correctly**. I was, however, able to break up and then reassemble on multiple lines the statements in `setup()` with the following code:

    function setup() {
      canvas = createCanvas(680, 420);
      canvas.mousePressed(inWidth);
      background(51);
      noStroke();
      // iterate over the table rows called in 'preload()' from .csv file
      for (var i = 0; i < clContext.getRowCount(); i++) {
        var statement = clContext.get(i, "statement");
        var polarity = clContext.get(i, "polarity");
        }
        var stateSplit = split(statement, "<br>"); // array of split statements
        for (var j = 0; j < stateSplit.length; j++) {
          var stateJoin = join(stateSplit, "\n");  // join the arrays with a line break
    }
    statements[i] = new Statement(polarity, stateJoin);

    console.log(typeof statements)    // returns 'object'
    console.log(typeof stateJoin)       // returns 'string'
    console.log(statements.length)    // returns 20
    console.log(display)                     // Throws 'Uncaught reference error: display is undefined
  }

With my limited JS knowledge, the `Uncaught reference error` suggests to me that the splitting the statements has created a problem with my prototype `display()` function. I'll post it here to save you the trouble of looking up my GitHub repo:

    // Function to align statements, categories, and polarity
    function Statement(polarity, stateJoin) {
     this.stateJoin = stateJoin;
      this.polarity = polarity;
      this.x = random(width);
      this.y = random(height);
      this.dx = random(-speed, speed);
      this.dy = random(-speed, speed);

      // Attach pseudo-class methods to prototype;
      // Maps polarity to color and x,y to random placement on canvas
      Statement.prototype.display = function() {
        this.x += this.dx;
        this.y += this.dy;
        // Wrap statements around canvas
        if(this.x > width+10){
          this.x = -10
        }
        if(this.y > height+10) {
          this.y = -10
        }
        // Color statements as positive or negative
        if(this.polarity === -1){
          fill(229,121,59);
        }
        else if(this.polarity === 1){
          fill(97,93,178);
        }
        textSize(14);
        text(this.stateJoin, this.x, this.y)
    }

I appreciate your suggestions. Any further ones would be appreciated.

**Comment by ldlathrop** [comment]
Wait. Never mind. I figured it out. I needed to put `statements[i] = new Statement(polarity, stateJoin);` up one level so it was within the for loop. Thanks again!

**Comment by lmccart** [comment]
great to hear. :) thanks for all the help and suggestions everyone!
