### ISSUE TITLE
Inconsistent colorMode behavior

### ISSUE THREAD

**Issue by hobzcalvin** [processing/p5.js#1459]
Haven't tried other colorModes but I'm pretty sure this is a bug. Seems that if I pass 1000 the max for all HSB values, passing 1000 for the hue breaks things while passing 1000 for saturation/brightness gets me the max as I expect.
```
// Assume 1000 is the maximum allowed value (that is, inclusive) passed in to color() as docs suggest
colorMode(HSB, 1000, 1000, 1000, 1000);
color(0, 0, 0); // RGB is 0, 0, 0 as expected
color(0, 1000, 1000); // RGB is 255, 0, 0 as expected
color(999, 1000, 1000); // RGB is 255, 0, 1.53; ok
color(1000, 1000, 1000); // RGB is 255, 0, 255. Huh???
// So is 999 the true max allowed value?
color(0, 999, 999); // RGB is 254.745, 0.2547, 0.2547 so that's not right
```

**Comment by joecridge** [comment]
You’re right, this is a bug. HSB colours with hue at max value are being rendered as magenta, regardless of the user-defined maximum. HSL seems to be fine.

I’ll take a look into it.

**Comment by joecridge** [comment]
The `if` statement in `p5.ColorConversion._hsbaToRGBA` didn’t take into account the fact that [`sector`](https://github.com/processing/p5.js/blob/master/src/color/color_conversion.js#L59) could be 6. Should be fixed now. 😅

**Comment by hobzcalvin** [comment]
Great; thanks for the quick response!

**Comment by lmccart** [comment]
thanks both for identifying and fixing!
