### ISSUE TITLE
p5.Color toString has side-effects on alpha value

### ISSUE THREAD

**Issue by leonardo-fernandes** [processing/p5.js#1461]
The toString method of the p5.Color class changes the alpha value of the color:

p5.Color.prototype.toString = function() {
  var a = this.levels;
  a[3] = this._array[3];  // String representation uses normalized alpha.
  return 'rgba('+a[0]+','+a[1]+','+a[2]+','+ a[3] +')';
};

This should never be done, because it has side-effects when reusing a Color object (for example, to make a lerpColor calculation).

**Comment by joecridge** [comment]
Ah good catch! 👍

**Comment by lmccart** [comment]
good one, thanks!
