### ISSUE TITLE
P5.js editor

### ISSUE THREAD

**Issue by NChCab** [processing/p5.js#1467]
I have a problem with the P5.js editor when using Windows.

For an unknown reason it just refuses to open on my laptop (windows 8.1 64 bits) and finds it very difficult to start on my Windows 10 (64 bits) desktop. No problem with my Mac.
If someone has an idea or a piece of advice ...
I badly need it to work on my laptop as that is what I use when away from home.
Thank you for your help.

**Comment by lmccart** [comment]
thanks, I'm tagging this post in an already open issue in the repo for the editor.
https://github.com/processing/p5.js-editor/issues/234
