### ISSUE TITLE
Using Workers in a contributed library

### ISSUE THREAD

**Issue by maniart** [processing/p5.js#1468]
Hello P5!

I'm working on a library that uses a Web Worker to increase performance. The guidelines point out that plugins should be distributed as a single JS file. Wondering it there's any workaround to include a main and a worker file as a packaged contributed library?

Thanks ❇️

**Comment by maniart** [comment]
Ah! As a bower / npm package perhaps? Though I couldn't find anything regarding publishing to registries in [Libraries Tutorial](https://github.com/processing/p5.js/wiki/Libraries#packaging).

**Comment by lmccart** [comment]
hey, sorry for the delay. the single file note is just a guideline, it's no problem to have a worker and main file if that makes more sense for your particular library!
