### ISSUE TITLE
Rotate is not working

### ISSUE THREAD

**Issue by hansiruting** [processing/p5.js#1469]
Hi there, I am testing the rotate function in localhost but it is not working. 
Could you check that? 

The same function works fine in processing. 

The best

function draw() { 
  rotate(mouseX / 100.0); 
  rect(10, 10, 50, 20);
}

**Comment by lmccart** [comment]
hi, this was recently fixed, and will be included in the next release (coming soon!)
https://github.com/processing/p5.js/issues/1465
