### ISSUE TITLE
Cannot draw graphics on canvas

### ISSUE THREAD

**Issue by Mobilpadde** [processing/p5.js#1475]
I'm trying to draw graphics on canvas, but for some reason it won't display?

```javascript
var pg;
function setup() {
  createCanvas(100, 100);
  pg = createGraphics(100, 100, WEBGL);
  pg.fill(10);
  pg.sphere(50);
}

function draw() {
  background(128);
  image(pg, 0, 0); // won't draw anything
}
```

**Comment by lmccart** [comment]
try something like this
```javascript
var pg;
function setup() {
  createCanvas(100, 100);
  pg = createGraphics(100, 100, WEBGL);
}

function draw() {
  pg.background(128);
  pg.sphere(110);
  image(pg, 0, 0);
}
```

`fill()` isn't used in webgl mode, if you want to color an object you can set it's materials and arrange lights. see [`specularMaterial()`](http://p5js.org/reference/#p5/ambientMaterial) example, and check out the  [getting started with webgl tutorial](https://github.com/processing/p5.js/wiki/Getting-started-with-WebGL-in-p5).

also, it's best to do the drawing in draw, if you do it right after creating the graphics buffer, it might not have initialized webgl mode in time to actually draw your object.

**Comment by Mobilpadde** [comment]
Doesn't sphere work with variables? Because that seemed to be my problem?

**Comment by lmccart** [comment]
hm I do notice some differences in webgl mode between the graphics buffer and canvas.
```javascript
var pg;

function setup() {
  createCanvas(100, 100, WEBGL);
  pg = createGraphics(100, 100, WEBGL);
  pg.show();
}

function draw() {
  background(128);
  sphere(100);

  pg.background(128);
  pg.sphere(110);
}
```
<img width="118" alt="screen shot 2016-06-22 at 11 07 57 am" src="https://cloud.githubusercontent.com/assets/191056/16251474/a3406604-3869-11e6-83f0-c7ded84e64c1.png">

```javascript
var pg;

function setup() {
  createCanvas(100, 100, WEBGL);
  pg = createGraphics(100, 100, WEBGL);
  pg.show();
}

function draw() {
  background(128);
  sphere(100);

  pg.background(128);
  pg.sphere(100);
}
```
<img width="141" alt="screen shot 2016-06-22 at 11 08 06 am" src="https://cloud.githubusercontent.com/assets/191056/16251478/aff33e4e-3869-11e6-82b4-d575de29986a.png">

@mindofmatthew @indefinit any thoughts on this?

**Comment by indefinit** [comment]
This could be a limitation of webgl, where having multiple simultaneous webgl contexts is slightly problematic. I seem to recall three.js ran into an issue like this a couple of years ago but I need to look into the solution they came up with.  

Anyhow, coincidentally I was thinking about createGraphics last week and that it might be time for us to change its functionality under the hood to creating an fbo instead of an entirely new webgl graphics context.  This would avoid the multiple gl instances buggy-ness.  

Since the forthcoming updates to photo and video processing with shaders are going to need fbo's anyway, we can work this into the change.

**Comment by lmccart** [comment]
aha, right, that makes sense.
cool, I'd be down to rethink and change up the p5.Graphics model... it feels like one of the less solid parts of this library right now.

**Comment by scottlittle** [comment]
I am getting this image when I run the above code (no spheres):

![image](https://cloud.githubusercontent.com/assets/2524998/23593781/1092dc76-01d9-11e7-91e6-b7555bb162ea.png)
