### ISSUE TITLE
resizeCanvas() does not work when canvas has been assigned to variable

### ISSUE THREAD

**Issue by xinkiknix** [processing/p5.js#1476]
in setup
`canvas = createCanvas(_width, _height);`
 
in draw
`background(imgBck);`

`function windowResized() {
  resizeCanvas(windowWidth, windowHeight);
}`

only the image canvas gets resized, _**canvas**_ in unaffected

**Comment by lmccart** [comment]
does it work if you use another var name besides `canvas`?

**Comment by xinkiknix** [comment]
That does *not *solve the problem.

**Comment by xinkiknix** [comment]
Problem is solved, some height & width values were redefined (by me) and
did not get proper values, renaming these fixed the issue.

**Comment by lmccart** [comment]
ah, great!
