### ISSUE TITLE
Inaccurate documentation for degrees()

### ISSUE THREAD

**Issue by bernhard-hofmann** [processing/p5.js#1482]
The [documentation ](https://p5js.org/reference/#/p5/degrees) states

    println(rad + " radians is " + deg + " degrees");
    // Prints: 45 degrees is 0.7853981633974483 radians

I seriously doubt that println method would produce that output. :)

**Comment by chiunhau** [comment]
@bernhard-hofmann Yes it should be "0.7853981633974483 radians is 45 degrees" XD
