### ISSUE TITLE
can't use noStroke(), round(), etc

### ISSUE THREAD

**Issue by XtremePlayzCODE** [processing/p5.js#1483]
There is a site [here](http://www.khanacademy.org) that uses ProcessingJS to write programs.
Would it be possible to port over ProcessingJS functions like `noStroke()`,`round()`, etc?
Can't be bothered to port my ProcessingJS projects from KhanAcademy into Processing so I can use them on my site since most of them are 2k+ lines so I use p5 editor and copy the HTML :p

**Comment by lmccart** [comment]
p5.js does include `round()` and `noStroke()`, though there are some differences between processingjs and p5.js. we don't plan to align the APIs as they are separate projects.
