### ISSUE TITLE
createCanvas() followed by get() in draw() hogs memory; crashes

### ISSUE THREAD

**Issue by hobzcalvin** [processing/p5.js#1485]
Consider this minimal example:
```
<html>
  <body>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.5.2/p5.js"></script>
    <script type="text/javascript">
      function setup() {
        createCanvas(600, 600);
      }
      function draw() {
        get();
      }
    </script>
  </body>
</html>
```
Running this in Chrome, I see memory usage climb as high as 1GB before dropping to a few hundred MB. Sometimes this crashes with:
`p5.js:15460 Uncaught RangeError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': Out of memory at ImageData creation`
Other times it crashes the whole tab with the "Aw, Snap!" message, no console errors.
It crashes all the time on a Nexus 9 tablet; crashes sometimes on Windows; seems fine on a Mac or iPad. Apparently this is part luck of the draw, part memory limits for the particular browser/device.
Memory usage drops eventually, but it gets dangerously high beforehand.

**Comment by hobzcalvin** [comment]
Sorry, I should've used a hosted p5.js:
`<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.5.2/p5.js"></script>`

I whittled down [a rather large p5js project](http://hobzcalvin.github.io/fadeclient/) with this issue into that minimal example on a Google Nexus 9, but now I can't reproduce it on my Windows machine. However, that large project now crashes on Windows Chrome with this exception (vastly preferable to the whole Chrome tab crashing):
`p5.js:15460 Uncaught RangeError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': Out of memory at ImageData creation`

So, a memory leak, then?

**Comment by limzykenneth** [comment]
I think it is sensible to advise the user against calling memory intensive operations on every frame of the draw calls instead of quietly handling it in the background. There are potentially numerous ways to create memory leaks and to try and account for them all is futile, awareness on the user side, especially the ability to diagnose it is probably more helpful. That's what I think anyway...

**Comment by hobzcalvin** [comment]
Well, as you may see from the feed, I tried [a commit](https://github.com/hobzcalvin/fadeclient/commit/07c9b26de5c3c263411ea221c26e17e3308da805) where I removed the get()/image() calls from my draw() function. But it still crashes on a Nexus 9!

Is the use of loadPixels() and updatePixels() also a memory-intensive operation that should be avoided on each frame? (Given some understanding of how the canvas element works, I could guess that those calls translate to getImageData() and putImageData() respectively.) Well, now I'm doing that twice instead. :-P There are definitely other ways I can get the effect I'm looking for, and I'm down to try them. Perhaps the documentation should warn users against memory-intensive functions. For a creative coding framework, though, the more that "memory management" can be hidden from the user, the better.

**Comment by limzykenneth** [comment]
Hmm...not sure about the Nexus 9 crash, not at all familiar with Android systems. From what I see from your sketch's code, I think you can try instead of using `get()`, use `createGraphics()` instead. A graphics buffer should be lighter than a large array that you get with `get()` (no pun intended 😆). i've not test out how the two compares so let us know whether it did or did not help.

**Comment by hobzcalvin** [comment]
Well, it looks like switching to the use of a second "overlay" canvas will do what I need without calling loadPixels(). Probably for the best.

However, I _do_ see some suspiciously costly code in [p5.Renderer2D.prototype.get](https://github.com/processing/p5.js/blob/master/src/core/p5.Renderer2D.js#L196): loadPixels() is called on the entire canvas, even if we're just trying to get() a small portion, or even a single pixel. In fact, pixels[] is only used in the single-pixel case, which should be a great job for the width/height parameters of [getImageData()](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/getImageData). It seems that when get()ting a region, loadPixels() shouldn't be called at all.

So I guess my summary of this bug is now "get() does some unnecessarily costly things and should be optimized." My analysis may be naive, but I can try submitting a patch.

**Comment by lmccart** [comment]
addressed with https://github.com/processing/p5.js/pull/1488
