### ISSUE TITLE
copy() for console and image

### ISSUE THREAD

**Issue by lowenf** [processing/p5.js#1486]
I tried to copy the console.log output to the clipboard, but was met with the following error:

p5.js:14676 Uncaught TypeError: Cannot read property 'width' of undefined(…)
p5.Renderer2D._copyHelper	@	p5.js:14676
p5.copy	@	p5.js:21457
(anonymous function)

My guess is that the p5 lib overwrote the console copy function?

**Comment by limzykenneth** [comment]
@lowenf Do you have an example sketch of this problem? I'm afraid I don't fully understand the problem...

**Comment by lowenf** [comment]
No problem, I'll illustrate with images what I mean:

This is what the [copy() in Chrome](https://developer.chrome.com/devtools/docs/commandline-api#copyobject) is supposed to do:
So in this screenshot I make a reference to all 'div' tags, I can store as global variable by right clicking and then use the copy() command ([here is an explanation on stackoverflow](https://superuser.com/questions/777213/copy-json-from-console-log-in-developer-tool-to-clipboard)). 
![screen shot 2016-06-26 at 17 50 22](https://cloud.githubusercontent.com/assets/4084169/16363298/8a33deba-3bc6-11e6-9f2a-004fdd4d7bda.png)

But when I try to use copy() (and I also discovered the same for clear()) when thethe P5 library is added I get this:
![screen-shot-2016-06-26-at-17 53 38](https://cloud.githubusercontent.com/assets/4084169/16363324/36dd9656-3bc7-11e6-8f7f-34f75a3e2867.jpg)

So my guess is that p5 lib is overwriting the native console functions. Perhaps these functions should be added to the P5 object? Sorry I'm not familiar with the p5 source code, so I'm just merely guessing here.

**Comment by limzykenneth** [comment]
Huh...I totally did not know chrome have these function in the console, which personally I think is just a bad idea but that's not important 😉  . As you have guessed, p5 does have a `copy()` and `clear()` function that will, in this case, overwrite the console native `copy()` and `clear()` functions. To avoid this kind of collision (which might happen when using other libraries with p5 as well) is to use instance mode, documented [here](https://github.com/processing/p5.js/wiki/Instantiation-Cases).

**Comment by lowenf** [comment]
ahhhh, great! Thanks for supplying a solution :) case closed
