### ISSUE TITLE
Firefox: blank canvas after upgrade to version  0.5.2

### ISSUE THREAD

**Issue by rik-brown** [processing/p5.js#1487]
Hi, I'm aware this is a rather incomplete bug-report but I'm not super-skilled at debugging and have not been able to isolate the likely source of error.

github page: http://rik-brown.github.io/Aybe_Sea/
github repository: https://github.com/rik-brown/Aybe_Sea

I have a sketch which was working OK in both chrome & firefox with p5.js v0.4.23
After upgrading to v0.5.2, however, the sketch still runs OK in chrome (& IE) but displays a white canvas in Firefox (in windows, v47.0) I am using the dat.gui library & this displays OK.  There are no errors logged to the console for the javascript, but there are some css warnings, listed as follows:

Error in parsing value for 'background'.  Declaration dropped. index.html
Expected color but found 'left'.  Error in parsing value for 'background'.  Declaration dropped. index.html
Error in parsing value for 'background'.  Declaration dropped. index.html
Expected color but found 'left'.  Error in parsing value for 'background'.  Declaration dropped.

Added filed with a screenshot from Dan Shiffmans Mac.

<img width="1070" alt="screen shot 2016-06-23 at 10 56 34 pm" src="https://cloud.githubusercontent.com/assets/18113402/16348061/a13f6696-3a50-11e6-8ffb-27f5f0015810.png">

**Comment by rik-brown** [comment]
I have done a bit more testing and it seems that 0.5.0 is the last version for which my sketch worked OK in firefox. Upgrading from 0.5.0 to 0.5.1 causes the issue described above.

**Comment by lmccart** [comment]
It's a bit hard to debug such a big sketch to identify the issue. Could you please try to find a simplified snippet that illustrates the problem? I'd suggest commenting out pieces of the code until you find the piece that creates a problem and making an isolated example from that. Or if you have a hunch where the problem may lie, you could try making an example with just that piece of functionality.

**Comment by rik-brown** [comment]
Yes, I realise that. I'll see what I can do.

**Comment by rik-brown** [comment]
I think I might have found the offending line :-D
If I change:
createCanvas(windowWidth, windowHeight);
to, for example:
createCanvas(800, 600);
the sketch runs OK with 0.5.1 and 0.5.2
Could it have something to do with "fix for capture width/height bug" in 0.5.1?

**Comment by rik-brown** [comment]
Could this be related to #1479 ?
I am running Windows 7 Enterprise btw.

**Comment by nok** [comment]
Yes, it's possible. Can you, @rik-brown, test the referenced library of [p5.js](https://gist.githubusercontent.com/nok/d33e9f1c133c6f4c8e5fab6faee6ac1d/raw/0f087b6215ee4534e1412874bc2c6c3bb3470bb2/p5.js) from the [last comment](https://github.com/processing/p5.js/issues/1479#issuecomment-229769500) please.

**Comment by lmccart** [comment]
should be fixed with https://github.com/processing/p5.js/pull/1494.

**Comment by rik-brown** [comment]
Hi, sorry, I was slow to test this but have done so now, for the record - the referenced library did indeed solve the issue I reported.

**Comment by lmccart** [comment]
great, I'll post a new release in the next day or two!
