### ISSUE TITLE
copy and element created with createCapture

### ISSUE THREAD

**Issue by vanevery** [processing/p5.js#1490]
This issue seems to be related to #995 and could probably be solved in the same way or it could be fixed in the createCapture code in the DOM library.

In any case it _seems_ that this should work but it fails on reading the width capture object.  Perhaps there is a better method to do this that I am missing:

```javascript
var cameraFeed;
var myImage;
var button;

function takeSnapshot() {
    myImage.copy(cameraFeed,0,0,320,240,0,0,320,240);
}

function setup() {
    cameraFeed = createCapture(VIDEO);
//     cameraFeed.size(320,240);
//     cameraFeed.canvas = {width: 320, height: 240};
//     console.log(cameraFeed);
    button = createButton('SNAP');
    button.mousePressed(takeSnapshot);
   
	myImage = createImage(320,240);
}

function draw() {
    image(myImage,0,245,320,240);
}
```

**Comment by lmccart** [comment]
should work now... I just had to change your last line so that it shows up on the canvas (which is 100x100 by default)
`image(myImage, 0, 0, 320, 240);`

**Comment by vanevery** [comment]
Wonderful!  Thanks!
