### ISSUE TITLE
remove print(), use println() only?

### ISSUE THREAD

**Issue by lmccart** [processing/p5.js#1491]
I've had some people mention that having the `print()` function in p5 blocks them from some things they'd like to do, like creating a web project where the `window.print()` command is used to open a print dialogue. The global window print() command gets overwritten whenever you use p5 in global mode (it works ok in instance mode).

I'm proposing to remove `print()` completely and just leave `println()`. In original Processing, `print()` means a call to print with no line break, but in p5 both `print()` and `println()` behave identically and insert a newline, so it is already redundant. On top of all that, we also have `console.log()`. 

Does removing `print()` to prevent overwriting `window.print()` and reduce redundancy sound reasonable to everyone?

**Comment by limzykenneth** [comment]
+1

I think it makes sense

**Comment by shiffman** [comment]
I agree. 👍

**Comment by lmccart** [comment]
ok let's give it a try!

**Comment by BigRex** [comment]
I'm going through the book, running examples and I can't get println() to work.  From section 5-10 (pg 69(pdf)):
  var x = 0;
        var easing = 0.01;
        function setup() {
            createCanvas(220, 120);
        }
        function draw() {
        var targetX = mouseX;
            x += (targetX - x) * easing;
            ellipse(x, 40, 12, 12);
            println(targetX + " : " + x);
        }
