### ISSUE TITLE
createCanvas() documentation is inaccurate

### ISSUE THREAD

**Issue by chiunhau** [processing/p5.js#1493]
The [parameter](https://p5js.org/reference/#/p5/createCanvas) `[renderer]` should not be `String: 'p2d' | 'webgl'`.
It should be a constant, and all caps: `P2D` or `WEBGL`, though it works with lower case string.

By the way, in the whole reference, I found they use `Number/Constant` or `Number|Constant`, or  `String/Constant` for constant parameters. See [this](https://p5js.org/reference/#/p5/rectMode), [this](https://p5js.org/reference/#/p5/colorMode) and [this](https://p5js.org/reference/#/p5/blendMode) for example respectively.

Is that intentional? What are the differences? I first thought like `Number/Constant` means that the constant equals to a number. But looks like not, after I checked src/core/constants.js.

**Comment by nok** [comment]
You can use both variants, as you mentioned: https://github.com/processing/p5.js/blob/master/src/core/constants.js#L12-L13

Maybe it makes more sense for beginners using simple data types like strings? I didn't test the error handling. Maybe the error handling using strings is more helpful and accurate.

Personally I prefer the constant variant.

**Comment by lmccart** [comment]
thanks, these were all typos, and definitely confusing. @nok is correct, the underlying strings will work, but generally we want to direct people to use the constants. I've updated them in the src code and will publish a new version of the reference soon!
https://github.com/processing/p5.js/commit/4429825be9f9b74b58d71953328ca4b03c899e36
