### ISSUE TITLE
Failing to enable a DOM button after disabling it with "disabled" attribute

### ISSUE THREAD

**Issue by sejomagno** [processing/p5.js#1499]
Hi!

I'm having some problems with the `disabled` attribute because I can't find a way of removing it within p5js.

I [can see](http://www.w3schools.com/tags/att_input_disabled.asp) that this attribute is boolean and acts when it is present, regardless of its value.

Using p5js, I can create and disable a button as follows:
```javascript
var button = createButton('Press me');
button.attribute('disabled','true');
```

Something funny is that in the previous snippet, `'true'` could actually be any other word (_including **false** and an empty string_) as the browser apparently will only care about the presence of the `disabled` attribute (I'm using Google Chrome in Ubuntu 16.04, but I guess that's the normal behavior). 

Based on this, apparently there's no way of re-enabling the button using the `attribute` function. Please correct me if I'm wrong or if there's another way.

**Comment by kadamwhite** [comment]
@sejomagno This does indeed look like a bug, I would expect `button.attribute('disabled',null);` or `button.attribute('disabled',false);` to re-enable the button and neither of those appear to be doing so.

There are two (and a half) options I can see to solve this: Either implement `removeAttribute( 'attrName' )`, to mirror the [DOM removeAttribute API](https://developer.mozilla.org/en-US/docs/Web/API/Element/removeAttribute); or implicitly treat `.attribute( 'attrName', null )` as a removeAttribute under the hood (possibly undesirable?); or (the extra half-solution) implement the former and use it to implement the latter.

I'd be in favor of starting by implementing `removeAttribute` on the p5 element API. But, welcome to other thoughts!
