### ISSUE TITLE
sound Env stops working if I try to reset the values

### ISSUE THREAD

**Issue by khakhalin** [processing/p5.js#1504]
It may not be a bug, but rather a gap in documentation, but I am wondering what is the correct way to change envelope parameters on the fly, while the program is running. 

If I follow the sequence in the example and first create an Env, then set it as osc.amp(env), then start the osc, and set its frequency, everything works (Chrome, most recent p5 libs). If however I try to call env.setADSR in the program, even if I call it with same exact set values as it was called in the setup() originally, play() stops producing normal sound (although sometimes I can hear some glitchy clicks).

I also tried to stop the oscillator and then restart it; reset osc.amp to a number and then reset it to env again, or create a new envelope (as an array of objects) every time I need to change it, but neither of these methods works.

Are these values supposed to be changeable through setADSR()? Can they be changed through set()? And if not, should it be possible to create Env objects in an array, linking these new objects to my oscillators as I need them?

**Comment by lmccart** [comment]
thanks, i've posted this on the dedicated p5.js-sound repo:
https://github.com/processing/p5.js-sound/issues/122

**Comment by therewasaguy** [comment]
Hi @khakhalin, I'm not able to reproduce this, can you provide a code example?

It sounds like you want to change the ADSR values on the fly, modifying the example from http://p5js.org/reference/#/p5.Env. It is working for me when I modify the playEnv function like this:

```
function playEnv(){
  env.setADSR(0.1, 0.2, random(), 0.2);
  env.play();
}
```

I'm wondering what values you're passing to setADSR? Send along some code that isn't working as you'd expect and we'll figure it out.
