### ISSUE TITLE
fill not working in webgl mode

### ISSUE THREAD

**Issue by lmccart** [processing/p5.js#1505]
from the fill reference page: http://p5js.org/reference/#p5.RendererGL/fill

```javascript
 function setup(){
   createCanvas(100, 100, WEBGL);
 }

 function draw(){
  background(0);
  fill(250, 0, 0);
  box(200, 200, 200);
 }
```

I'm about to push a fix, just wanted to document what is happening here. @indefinit or @mindofmatthew if you get a chance, can you double check it looks ok?

**Comment by roocster** [comment]
fill() still not working in WEBGL mode. This causes an error "Uncaught TypeError: Cannot read property '_applyColorBlend' of undefined"

**Comment by indefinit** [comment]
Thanks for reporting this.  Any chance you can post some example code?

**Comment by roocster** [comment]
```
function setup() {
  createCanvas(100, 100, WEBGL);
}

function draw() {
  fill('black');
  rect(0, 0, 10, 10);
}
```

User Agent:
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36

**Comment by indefinit** [comment]
@roocster are you running a release version of p5 or are you running the latest from Github master branch?  I can confirm this is working as expected in the master branch but it looks like some changes haven't been included in a release tag yet.

**Comment by roocster** [comment]
I used the release version of p5.js (v0.5.2 June 17, 2016) from http://p5js.org/download/.

I compiled the p5 from master branch source. Now this code does not cause an error. But the black rectangle still does not appear in the viewport. If I remove the WEBGL parameter from createCanvas it works.

**Comment by indefinit** [comment]
Ok, it looks like the problem is actually related to the virtual camera with a 100x100 canvas.  If you enlarge the canvas size > 100 you should see the rectangle appear.  I'm going to open a new Issue referencing this one, since it is more related to camera than it is to fill.  Thanks again for looking into this. Stay tuned...
