### ISSUE TITLE
installation on win7

### ISSUE THREAD

**Issue by yakkov** [processing/p5.js#1506]
Hi
I get the following

![1](https://cloud.githubusercontent.com/assets/20305797/16601582/c9c03328-430d-11e6-9e3d-8ce6dcccb2e2.jpg)
any help ? I run win7 32.

thanks
yakkov

**Comment by marti1125** [comment]
Hi @yakkov  could you give more information about OS please I can run in windows 10
https://support.microsoft.com/en-us/help/15056/windows-7-32-64-bit-faq

**Comment by yakkov** [comment]
Hi

 

Thanks

 

I run win 7 32 , sp1 . what else would you like to know ?

 

I tried every suggestion that I could find on the internet regarding.

  

 

Thanks

 

Regards

Jacob

**Comment by yakkov** [comment]
Hi

 

Please tell me what else you would like to know? I installed a virtual pc aswell trying to run in xt mode , same result.

 

Regards

jacob

**Comment by marti1125** [comment]
Hi, try with http://answers.microsoft.com/en-us/windows/forum/windows_7-windows_programs/this-verison-of-this-file-is-not-compatible-with/0c6a4c8e-1416-47a5-b6b4-6d10a82942da?auth=1

**Comment by yakkov** [comment]
Hi

 

I tried most things on that page, I tried running all compatibilities options , I tried virtual pc with xt, I verified integrity of my win 7 enterprise 32 with sp1.

 

Regards

**Comment by lmccart** [comment]
thanks, you can follow updates here: https://github.com/processing/p5.js-editor/issues/234
