### ISSUE TITLE
Setting magnitude on vector(0, 0) return NaN

### ISSUE THREAD

**Issue by lbineau** [processing/p5.js#1508]
Step to reproduce
```javascript
var thrust = p.createVector(0, 0)
thrust.setMag(10)
console.log(thrust) // => p5.Vector {p5: p5, x: NaN, y: NaN, z: NaN}
```
Correct me if I'm wrong but I don't think it is a normal behavior.

**Comment by shiffman** [comment]
Indeed, this is a bug.  I think the behavior should be to keep `(0,0,0)` as the values.  (This is what Processing does).   I can fix this if someone else doesn't get to it first!  @toolness we could also consider a "friendly error message" to indicate that setting the magnitude of a 0 vector doesn't do anything?

**Comment by chiunhau** [comment]
```js
p5.Vector.prototype.normalize = function () {
  return this.div(this.mag());
};
```
Yes... if mag() returns 0, then normalize() will return infinity.

**Comment by lbineau** [comment]
How can I build and update the package on npm ?

**Comment by limzykenneth** [comment]
@lbineau packages on npm will only be updated when there is a versioned release so this change will probably be on npm for v0.5.3, not sure when that will be released though. if you need the fix now, you can clone this repo and build from source, instructions [here](https://github.com/processing/p5.js/wiki/Development#setup)

**Comment by lmccart** [comment]
thanks @limzykenneth, that's correct, I'll post a new version before the weekend.
