### ISSUE TITLE
New feature: enable() / disable() methods for inputs in p5.dom?

### ISSUE THREAD

**Issue by sejomagno** [processing/p5.js#1511]
Based on #1499, I was thinking that we could add a pair of methods, `enable()` and `disable()` in p5.dom to make easier the enabling and disabling of DOM inputs. I don't know how much this feature is requested/used/known. However, I find it natural and similar to the `show()` and `hide()` methods pair for DOM elements, or the `value()` method for inputs. 

What do you think? I wanted to discuss it here before working on it. I can implement the methods with their inline documentation. I just need to study and understand what to do with unit tests to add them too.

**Comment by lmccart** [comment]
I guess my feeling is that show/hide are more commonly used and the set/removeAttribute methods should be sufficient for additional attributes beyond that. There doesn't seem to be a lot of activity on this thread, so if we are fine leaving it at that, I'd like to just to keep the code more maintainable.

**Comment by sejomagno** [comment]
Yes, I think it's all right leaving it as it is now. I will add the enable/disable example to the reference!

Part of the problem that I had was that there were two buttons in the same text line (just adding them to the container without any newline, p or div), and when I used the `hide()` and `show()` pair in one of them, it moved to a new line because of the `style="display: block;"` attribute... Now that I think about it, that could belong to another issue

**Comment by lmccart** [comment]
hmm instead of `show()`/`hide()` in this case, it might make more sense to use `.css('display', 'inline')` and  `.css('display', 'none')`
