### ISSUE TITLE
Unable to set Radio value to 0

### ISSUE THREAD

**Issue by KyleNehman** [processing/p5.js#1514]
Some example code:
```
function setup() {

  createCanvas(windowWidth, windowHeight);

  var radioOptions = ['radio', 'button', 'test', 'values'];
  var thisRadio = createRadio();
  var x = 100;
  var y = 100;

  for (var i = 0; i < radioOptions.length; i++) {
    var option = radioOptions[i];

    thisRadio.option(option, i);
  }
  thisRadio.position(x, y);

  thisRadio.value(0);
}

```

If the radio buttons' values are set to ints [0, n-1] calling thisRadio.value(0) does nothing. Calling the same function with arguments [1, n-1] works as intended and allows me to set any button besides the first one to be filled.

**Comment by lmccart** [comment]
thanks for the report, fixed with https://github.com/processing/p5.js/pull/1515, it will be in the next release
