### ISSUE TITLE
Color property setters

### ISSUE THREAD

**Issue by Jackbennett** [processing/p5.js#1517]
I had a look around and it seems like I shouldn't go in the the _array object but this creates the effect I was after. It might be nice to open up the color properties to be modified by other code a bit easier. Or perhaps I could have set an `alpha()` value before fill to be more inline with the p5 api?

```
var pallet = {}
var pallet.focus = color(159,39,55)
items.forEach(function(current, index, array){
  pallet.focus._array[4] = map(index, 0, array.length, 0, 1)
  fill(pallet.focus)
  ellipse(current.x, current.y ,15, 15)
})
```

**Comment by nok** [comment]
In your sketch the red, green and blue value are fix. Have a look at the following version:

```javascript
var items = [];

function setup() {
  createCanvas(120, 80);
  background(210);
  stroke(255);
  
  items.push(createVector(30, 40));
  items.push(createVector(50, 40));
  items.push(createVector(70, 40));
  items.push(createVector(90, 40));
  
  items.forEach(function(current, index) {
    var alpha = map(index, 0, items.length-1, 0, 255);  // <--- alpha
    fill(color(159, 39, 55, alpha));                    // <--- r,g,b
    ellipse(current.x, current.y ,15, 15);
  });
}
```
http://codepen.io/nok/pen/qNVPqb

But if you want to store the color values separately, you can create an own class, e.g.:

```javascript
function MyColor (r, g, b, a) {
    this.r = r;
    this.g = g;
    this.b = b;
    this.alpha = a;
}
var c = new MyColor(159, 39, 55, 100);
c.alpha = 200;
color(c.r, c.g, c.b, c.alpha);  // 159, 39, 55, 200
```

**Comment by lmccart** [comment]
I think this is a good idea, I can give it a go next chance I get.

adding this code snipped proposal from @indefinit (https://github.com/processing/p5.js/issues/1566):
```javascript
var myCol = color(100,200,12); //create an opaque color
...
myCol.alpha(40); //set the alpha property to 40
// or
myCol.alpha =  40;
```

**Comment by lmccart** [comment]
closed with https://github.com/processing/p5.js/pull/2143
