### ISSUE TITLE
create wiki/tutorial on performance

### ISSUE THREAD

**Issue by lmccart** [processing/p5.js#1523]
as a starting point for anyone who needs to squeeze more power out of p5
follow up from https://github.com/processing/p5.js/issues/1512

probably best as a p5.js wiki page we link to from the p5js.org/tutorials page and also from key pages in the reference.

@mikewesthad is working on a start to this

**Comment by mikewesthad** [comment]
It took a little while to find the time to start this, but I have a draft going in [this repo](https://github.com/mikewesthad/p5-performance-tips).  I want to fill out a few more sections before migrating it to a p5 wiki.  It's half about profiling and half about optimizations. I tried to keep it beginner-friendly.

I figured I'd share now anyway and see if anyone has any topics or specific performance tips that they think would be smart to include.

**Comment by lmccart** [comment]
This is looking great! Really like the words of caution intro, too.

In the part where you mention profiling and `println()`, it might be good to also mention that `println()` and `console.log()` will slow things down, so you want to remove them all at the end.

Maybe this goes in Image Processing section, but color handling can be sped up by declaring p5.Color objects ahead of time in setup (if they are to be used repeatedly over many frames).
https://github.com/processing/p5.js/blob/master/src/core/p5.Renderer2D.js#L77
https://github.com/processing/p5.js/blob/master/src/color/creating_reading.js#L253

**Comment by mikewesthad** [comment]
Thanks.  Ah, good points - I'll definitely include those.  Things have been a little busy, but I'll hopefully have this migrated over to a p5 wiki page this week.

**Comment by mikewesthad** [comment]
I finished up the last two sections I thought it would be important to have in an initial draft (DOM and image processing) and brought the document over to a p5.js wiki [here](https://github.com/processing/p5.js/wiki/Optimizing-p5.js-Code-for-Performance).

@lmccart I wasn't sure what to do with the images and code samples, so I just dropped them in as absolute links back to my repo.  Is there a place to put them so that anyone can contribute?

**Comment by lmccart** [comment]
this is great! I will get a link up from the p5js.org tutorials page. maybe we could put the images and code samples in a folder named something like "performance-tutorial" here: (https://github.com/processing/p5.js-website/tree/master/tutorials)[https://github.com/processing/p5.js-website/tree/master/tutorials]?

**Comment by lmccart** [comment]
I'm going to close this as I think we're set here: https://github.com/processing/p5.js/wiki/Optimizing-p5.js-Code-for-Performance. thanks @mikewesthad, this is fantastic!
