### ISSUE TITLE
loadPixels() not working in a WEBGL canvas?

### ISSUE THREAD

**Issue by Xeronimo74** [processing/p5.js#1529]
I'm trying to capture the current canvas in an offscreen buffer but I'm not succeeding so far ...

`var buffer = createGraphics(width, height);
bugger = get();`

does not work.

Nor does even loadPixels() ... this throws an error: 19124: Uncaught TypeError: undefined is not a function

**Comment by lmccart** [comment]
hi, these functions are not yet supported in webgl mode. you can follow progress on this over at this issue: https://github.com/processing/p5.js/issues/1502

**Comment by Xeronimo74** [comment]
ok, thank you!
