### ISSUE TITLE
Parameter misnaming in the "sound envelope set" function

### ISSUE THREAD

**Issue by michaelbach** [processing/p5.js#1537]
There is a problem with the sound envelope set function. It is defined like so:
```
p5.Env.prototype.set = function (t1, l1, t2, l2, t3, l3) {
    this.aTime = t1;
    this.aLevel = l1;
    this.dTime = t2 || 0;
    this.dLevel = l2 || 0;
    this.rTime = t4 || 0;
    this.rLevel = l4 || 0;
```
Obviously, "t4" and "l4" should be "t3" and "l3", respectively.
Thanks for a great library! Best, Michael.

**Comment by nok** [comment]
Thanks @michaelbach, I created a PR to solve that issue.

**Comment by lmccart** [comment]
thanks @nok!
