### ISSUE TITLE
p5.Part.removePhrase(name) is not working

### ISSUE THREAD

**Issue by XievenLonger** [processing/p5.js#1538]
There's an error within p5.Sound that prevents the mentioned function from working. 

    p5.Part.prototype.removePhrase = function (name) {
        for (var i in this.phrases) {
            if (this.phrases[i].name === name) {
                this.phrases.split(i, 1); // Should actually be SPLICE - than it works
            }
        }
    };

Sorry, I'm not sure how to create pull requests or anything :(

**Comment by lmccart** [comment]
thanks, i've reposted this on the p5.js-sound repo:
https://github.com/processing/p5.js-sound/issues/127
