### ISSUE TITLE
Page not ok - http://p5js.org/reference/#/p5.SoundFile/pause

### ISSUE THREAD

**Issue by gvitalie** [processing/p5.js#1540]
Page not ok. Text overlaying. http://p5js.org/reference/#/p5.SoundFile/pause

**Comment by gvitalie** [comment]
Hi, P5JS. 

The problem still persist.
Same behavior in FireFox and Chrome.

Thank You.

<a href=http://www.openscreenshot.com/img/579f051e0a3a40-61342146><img src=http://www.openscreenshot.com/i3/579f051e0a3a40-61342146></a><br>Taken with <a href=http://www.openscreenshot.com>Open Screenshot</a>

**Comment by lmccart** [comment]
yes, thanks, it is fixed in the source code and will appear fixed on the website when we publish the next release of p5.js-sound
