### ISSUE TITLE
Is it possible to control p5.Filter frequency with a p5.Oscillator?

### ISSUE THREAD

**Issue by JoshuaStorm** [processing/p5.js#1541]
Just a question:

Hi, sorry if this is a question better asked elsewhere, but:

I want to make a oscillator modulated filter (a la LFO->FilterFreq). Doing something similar with one Oscillator modulating another Oscillator's frequency was fairly straightforward:
```
var lfo = p5.Oscillator();
sawOsc.freq(lfo);
```
but doing 
```
filter.freq(lfo);
```
Does not seem to do anything? Is this functionality just not implemented? Thanks!

**Comment by lmccart** [comment]
thanks, i've posted this on the p5.js-sound specific repo
https://github.com/processing/p5.js-sound/issues/126
