### ISSUE TITLE
Supported browsers wiki

### ISSUE THREAD

**Issue by limzykenneth** [processing/p5.js#1543]
The wiki for [Supported browsers](https://github.com/processing/p5.js/wiki/Supported-browsers) is rather outdated now with versions that's last updated in May 2015. Might be a good time to update it since it's not really reflecting the range of browser support (could include Microsoft Edge in there as well and I don't really understand why Opera wouldn't be supported since underneath it's still Chromium). 

For major browser it probably should just be updating the version number but for others such as IE and mobile browser I'm don't really know the requirements for them so I'm holding off editing it myself.

**Comment by lmccart** [comment]
hey thanks for looking into this. I think we can just update the browser versions, as far as I know nothing major has changed with the handling of most functionality. IE and mobile should be fine, too.

it would be good to add a link to [caniuse.com](http://caniuse.com) as well.

I agree, opera and edge should be in there, I think we can go ahead and add those as well.

**Comment by limzykenneth** [comment]
Just edited.
