### ISSUE TITLE
webgl: 2d primitives disappear with canvas size 100x100

### ISSUE THREAD

**Issue by indefinit** [processing/p5.js#1544]
Referencing: Issue #1505

Seems to be related to camera perspective on canvas sizes exactly less than 116x116.  Sample code:
```
//works!
function setup() {
  createCanvas(116, 116, WEBGL);
}
function draw() {
  fill('black');
  rect(0,0,10,10);
}

//doesn't work
function setup() {
  createCanvas(115, 115, WEBGL);
}
function draw() {
  fill('black');
  rect(0,0,10,10);
}
```
No errors produced.

**Comment by lmccart** [comment]
This was merged but I'm still not able to get the example here to show up. Did this get reverted somehow?

**Comment by lmccart** [comment]
oops, I hadn't pulled the latest. we're all good.
