### ISSUE TITLE
Different origin of coordinates in p2d and webgl mode

### ISSUE THREAD

**Issue by roocster** [processing/p5.js#1545]
The origin of coordinate system in p2d mode is in the upper left corner. But in webgl mode it is in the center of the canvas.

```javascript
function setup() {
  createCanvas(150, 150);
}

function draw() {
  background(0);
  fill(255);
  rect(0, 0, 10, 10);
}
```
![p2d](https://cloud.githubusercontent.com/assets/6066648/17310933/42c8d822-5850-11e6-8aa3-f89461726222.png)

```javascript
function setup() {
  createCanvas(150, 150, WEBGL);
}

function draw() {
  background(0);
  fill(255);
  rect(0, 0, 10, 10);
}
```
![webgl](https://cloud.githubusercontent.com/assets/6066648/17310947/58f641c0-5850-11e6-9424-57cfbbbf7b3b.png)

**Comment by lmccart** [comment]
Yep, this is correct behavior. We felt that the upper left hand corner made sense for 2D, but for 3D it made more sense for it to be in the middle, which aligns more closely with the native WebGL renderer. https://github.com/processing/p5.js/wiki/Getting-started-with-WebGL-in-p5#3d-coordinate-system
