### ISSUE TITLE
Open a gitter chatroom for the p5 library development

### ISSUE THREAD

**Issue by AkashGutha** [processing/p5.js#1549]
let's open a chat room on gitter.

**Comment by lmccart** [comment]
to keep things streamlined and accessible, I'd like to keep all official p5 development discussion to github and the forum, but you're welcome to start any chatrooms you like in other places.

**Comment by kadamwhite** [comment]
What is "the forum" in this case?

**Comment by lmccart** [comment]
the forum is a place for general questions and help, less bug/feature related. there are categories for general p5 questions, p5 development, and p5 libraries.
https://forum.processing.org/two/
