### ISSUE TITLE
Generic LSystem for art

### ISSUE THREAD

**Issue by AkashGutha** [processing/p5.js#1551]
it would be great to have an inbuilt LSystem that can be used create new and interesting art work.
the system should have a basic features like move forward , backward , turn left , turn right , change angle , save position , go back to prev position etc...

**Comment by limzykenneth** [comment]
Might be a feature a bit too specific to be included in core p5.js. That said, it sounds like a great idea for an addon library, it would save a lot of implementation when ever someone wants to implement a generic LSystem!

**Comment by AkashGutha** [comment]
yea . my initial thought was same. i wanted it to be a addon library. @limzykenneth

**Comment by lmccart** [comment]
yes, also check out @rev3rend's [l-system example](http://p5js.org/examples/examples/Simulate_L-Systems.php), could be a good starting point

**Comment by nok** [comment]
... and the official instruction: https://github.com/processing/p5.js/wiki/Libraries#creating-a-new-library

Maybe you can create an abstract basic `core` which can be used to develop new (generic) algorithms.

**Comment by AkashGutha** [comment]
@nok did you mean the the LSystem should be implemented as an abstract core ?

**Comment by nok** [comment]
Sorry, I don't want ro confuse you. Just feel free coding your ideas.

**Comment by lmccart** [comment]
thanks @AkashGutha, I'm going to close this issue since it isn't a bug or feature we're adding directly to the p5.js library, but it could be a great addon library.
