### ISSUE TITLE
basicMaterial missing?

### ISSUE THREAD

**Issue by edwardloveall** [processing/p5.js#1555]
The docs have this page describing all the material examples: https://p5js.org/examples/examples/3D_Materials.php

This example doesn't work for me in Safari 9.1.2 or Chrome 51.0.2704.103. I looked around in the source and [found the other materials](https://github.com/processing/p5.js/blob/master/src/webgl/material.js): normalMaterial, ambientMaterial and spcularMaterial. Not only does there seem to be no basicMaterial, but looking through the history of that file, there doesn't seem to have ever been a reference to it.

What am I missing?

**Comment by limzykenneth** [comment]
If I remember correctly `basicMaterial` has been removed as `fill` does the same job as well. The example is outdated and needed some update (although I recall this issue what brought up before...). I'll make a PR to fix that later today.

**Comment by edwardloveall** [comment]
That looks like the case, thanks!

https://github.com/processing/p5.js-website/issues/256

**Comment by lmccart** [comment]
yep that's correct, thanks @limzykenneth for the fix!
