### ISSUE TITLE
windowHeight / height is broken in Firefox 48 with p5.js 0.52

### ISSUE THREAD

**Issue by i3games** [processing/p5.js#1556]
`windowHeight / height` return 0 when canvas is created with (windowWidth, windowHeight).  Firefox 48.0 / Mac, p5.js 0.52. Works in Chrome 52.

## To reproduce: 

```
function setup() {
  // createCanvas(400, 400);
  createCanvas(windowWidth, windowHeight);
  print(windowWidth);
  print(windowHeight);
  print(width);
  print(height);
  print(displayWidth);
  print(displayHeight);
}

function draw() {
  ellipse(50, 50, 80, 80);
}

function mousePressed() {
  print(windowWidth);
  print(windowHeight);
}
```

## Possible fix:

replace 

```
p5.prototype.windowWidth = document.documentElement.clientWidth;
p5.prototype.windowHeight = document.documentElement.clientHeight;
```

with
 
```
p5.prototype.windowWidth = document.documentElement.clientWidth || document.body.clientWidth;
p5.prototype.windowHeight = document.documentElement.clientHeight ||  document.body.clientHeight;
```

This would require to include p5.js in the body, not in the head, however.

**Comment by AkashGutha** [comment]
@i3games  was unable to reproduce the error on FireFox 48.0 / Windows.

Could you please share more info ?

**Comment by limzykenneth** [comment]
Cannot reproduce on Mac as well

**Comment by nok** [comment]
This is a duplicated and already fixed issue: https://github.com/processing/p5.js/issues/1479

Nevertheless thanks for noticing that issue, @i3games.

I guess, that the fix will roll out with the next release, probably `0.53`?
