### ISSUE TITLE
Getting fonts not working

### ISSUE THREAD

**Issue by Simon-Chase** [processing/p5.js#1560]
I tried copying the font's addresses, but it said `19356: Uncaught Font could not be loaded: Not Found`

**Comment by AkashGutha** [comment]
please post your code or example code.
it would help others a lot in debugging the problem.

**Comment by Simon-Chase** [comment]
I figured out a better way to load fonts.

**Comment by Simon-Chase** [comment]
So my problem is resolved.

**Comment by lmccart** [comment]
glad you figured it out!

**Comment by Simon-Chase** [comment]
Actually, now I have a new problem (:P).
For some reason, after a few seconds of running the code, it goes all white
and freezes, but only when I run it on GitHub Pages.
The code involved is:

function mouseClicked() {
  for (var i in buttons[state]) {
    buttons[state][i].onClick();
  }
}

The message it gives me is:

186: Uncaught TypeError: Cannot read property 'onClick' of undefined

I don't know what the problem is. Nothing (the arrays, state variable,
.onClick() is undefined.

**Comment by lmccart** [comment]
it's a bit hard to figure out without seeing the rest of the code... but the "cannot read property of undefined" part tells me that the object you're trying to call onClick() doesn't exist. I'd suggest posting a longer code snippet on the forum, which is a good place for more general programming help.

forum.processing.org/two

**Comment by Simon-Chase** [comment]
Here:

buttons = {
    "menu": [new Button(-120, 150, "About", "about"), new Button(0, 190,
"Works", "works"), new Button(120, 150, "Contact", "contact")],
    "works": [new Button(-width/2, height/2 - 50, "Back", "menu")],
    "about": [new Button(-width/2, height/2 - 50, "Back", "menu")],
    "contact": [new Button(-width/2, height/2 - 50, "Back", "menu")],
  }

**Comment by Simon-Chase** [comment]
function Button(x, y, txt, dest) {
  this.x = x;
  this.y = y;
  this.txt = txt;
  this.dest = dest;
  this.col = 255;

  this.display = function() {
    noStroke();
    fill(255, 255, 255, 255 - this.col);
    ellipse(this.x, this.y, 110, 110);

    stroke(255);
    noFill();
    strokeWeight(3);
    ellipse(this.x, this.y, 110, 110);

    fill(this.col);
    noStroke();
    textFont("asap");
    textSize(22);
    text(this.txt, this.x, this.y + 1);

    if (dist(this.x, this.y, mouse.x, mouse.y) < 110/2) {
      cursor(HAND);
      this.col -= 15;
    } else {
      this.col += 15;
    }

    this.col = constrain(this.col, 0, 255);
  }

  this.onClick = function() {
    w = 255;
    state = this.dest;
  }
};

**Comment by Simon-Chase** [comment]
You might want to put somewhere in the tutorials that you can load Google
Fonts in the head tag of the index.html file. It would help beginners like
me.

**Comment by limzykenneth** [comment]
@Simon-Chase In your for loop

```javascript
for (var i in buttons[state]) {
  buttons[state][i].onClick();
}
```

There was no prior definition of `state` thus it cannot loop over `buttons[state]`(read `buttons[undefined]`) which throws an error. It's a bit hard to decipher what you are trying to achieve with your code so there's not much I can advise beyond this though. The [forum](https://forum.processing.org/two/categories/p5-js) is a better place to post this question, it's more focus on answering programming questions whereas github issues are more for bug tracking.

**Comment by Simon-Chase** [comment]
State was defined earlier in the program. It is a string equal to the page
of the program.
