### ISSUE TITLE
Reference examples broken or missing

### ISSUE THREAD

**Issue by CleezyITP** [processing/p5.js#1565]
I found some issues with the following examples in the reference:
- [x]  plane() example does not display. 
- [x] texture() -example# 2 is black.
- [x] deviceMoved(), deviceTurned() and deviceShaken() examples do not change on mobile. 
- [x] KeyIsPressed() and keyPressed() examples do not change with interaction.
- [x] keyRelease, mouseRelease and touchEnded() are not registering release

**Comment by limzykenneth** [comment]
`plane()` and `texture()`'s examples all depends on `plane()` which seems to be not working at all even isolated into a sketch itself. After some digging, I've managed to isolate the source back to this [commit](https://github.com/processing/p5.js/pull/1533/commits/4578f6362bb10727b6dc91114820c70a7118e078) which seemed to change how the camera behaves. Looking at `box()`, `cylinder()` and other 3D primitives as well, they all looked wrong (zoomed in too much). My suspicion is on [line 100](https://github.com/processing/p5.js/pull/1533/commits/4578f6362bb10727b6dc91114820c70a7118e078#diff-cf7b699e117a9a29c971f1522616d033R100) of p5.RendererGL.js but I may be wrong.

`deviceMoved()` etc works as expected when isolated into their own sketch so it y have to do with how events are handled and propagated amongst the canvases on the reference page. Same thing with `keyPressed()` and `KeyIsPressed()`. I'll have a dig tomorrow if I have the time.

`keyRelease()` etc are working as expected for me on the reference page and isolated, so might be helpful to have the browser and OS details for this.

**Comment by CleezyITP** [comment]
I've tried using Chrome on OSX (el capitan) and failed

**Comment by limzykenneth** [comment]
Hmm....tried the same setup but I couldn't replicate....
