### ISSUE TITLE
Feature request: writeable color properties

### ISSUE THREAD

**Issue by indefinit** [processing/p5.js#1566]
I often find myself wanting to create a color and then later in my sketch manipulate the alpha value of that color without having to construct a new color.  It would be great to have both get and setable properties in p5.Color so a user can do this:

```
var myCol = color(100,200,12); //create an opaque color
...
myCol.alpha(40); //set the alpha property to 40
// or
myCol.alpha =  40;
```

**Comment by lmccart** [comment]
thanks, good idea! i'm going to close this one and conslidate over https://github.com/processing/p5.js/issues/1517
