### ISSUE TITLE
Is there a way to load an image from a sprite sheet in p5.js?

### ISSUE THREAD

**Issue by mutawa** [processing/p5.js#1567]
I would like to be able to load one single sprite sheet that has many small images, and then be able to assign parts of the big image to several variables (easily done in CSS and browser only loads one image).

**Comment by limzykenneth** [comment]
Yes there is indeed! The syntax is as follows:

```
image(img,[sx=0],[sy=0],[sWidth=img.width],[sHeight=img.height],[dx=0],[dy=0],[dWidth],[dHeight])
```

sx, sy etc are the start position relative to the image, sWidth, sHeight are the width and height of the subset of the image. dx, dy are where you want to draw it on canvas and dWidth, dHeight are how big you want to draw the image.

**Comment by mutawa** [comment]
Thank you so much. That helped me a lot.

**Comment by chrisdothtml** [comment]
For anyone else coming here from google, you can also use `Image.get`:

```javascript
// do this in preload
const spritesheet = loadImage('spritesheet.png')
// get portion of spritesheet image
const sprite = spritesheet.get(x, y, width, height)

// show single sprite
image(sprite, x, y, width, height)
```
