### ISSUE TITLE
rect primitives do not support negative height& widths

### ISSUE THREAD

**Issue by indefinit** [processing/p5.js#1569]
Not sure if this is intentional, but negative width and height values are being rectified with an abs() call in the rect function.

the offending lines are [here](https://github.com/processing/p5.js/blob/master/src/core/2d_primitives.js#L458)

Commenting out those lines allows rectangles to be drawn upside down in canvas and webgl modes.  In my lesson on data visualization, I often make use of negative height values when drawing bar graphs, and drawing rectangles in both directions along the y axis makes things much easier for my students.  I'm happy to submit a PR for this change, but wanted to make sure this was an issue and not intentional functionality.

**Comment by indefinit** [comment]
@lmccart just making sure you see this since the issue is not limited to webgl.

**Comment by lmccart** [comment]
yep sorry I haven't had a chance to look into this yet! will take a closer look this evening.

**Comment by lmccart** [comment]
good call, i just pushed the fix you suggested, thanks
