### ISSUE TITLE
createSprite() and drawSprites() in p5.play.js gives errors with 0.5.3 version of p5.js

### ISSUE THREAD

**Issue by MuhammadZaidIkhlas** [processing/p5.js#1573]
So I was using p5.play.js with p5.js v0.4.23 and it worked perfectly fine. But p5.js' v0.5.3 gives the following error whenever I call the createSprite() function of the p5.play.js: 

`p5 had problems creating the global function "Animation", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.`

Moreover when I call the drawSprite() it gives the following error: 

`Error: "print" is not a p5 method`

I hope this issue gets solved as soon as possible.
Regards.

**Comment by lmccart** [comment]
I'm not sure about "Animation", but `print()` has been removed in 0.5.3 to avoid other browser naming conflicts, please use `println()` instead: http://p5js.org/reference/#p5/println.

**Comment by MuhammadZaidIkhlas** [comment]
@lmccart Okay so i replaced print with println in the p5.play.js library and it worked and the script is working as expected. So that means the p5.play.js needs to updated then. 

On the hand, the "Animation" warning is still there.

**Comment by lmccart** [comment]
great! the p5.play library repo is over here: https://github.com/molleindustria/p5.play if you want to submit a pull request or just open an issue letting the project lead of that one know.

**Comment by shreyas-sovani** [comment]
what about drawSprites() error???

**Comment by bhavya200811** [comment]
Uncaught ReferenceError: createSprite is not defined (sketch: line 28)
this is what p5js says when I write any code. I dont know what to do ?

**Comment by anirban0104** [comment]
> Uncaught ReferenceError: createSprite is not defined (sketch: line 28)
> this is what p5js says when I write any code. I dont know what to do ?

Download p5play.js library and put it in the folder and in index.html, mention the file src. @bhavya200811 

[p5.play.zip](https://github.com/processing/p5.js/files/5800446/p5.play.zip)

**Comment by ChaitanyaChouahn** [comment]
bro the file p5play.js is already there and it is showing a error 
@aniban0104
