### ISSUE TITLE
gif file not working in firefox browser.

### ISSUE THREAD

**Issue by rajtukadia** [processing/p5.js#1574]
p5js gif file perfect working on chrome browser but not working on firefox. So how to fix this problem.

**Comment by limzykenneth** [comment]
Hi @rajtukadia, can you post a simple example code of this problem here so we can test it out and perhaps even the gif file as well. Thanks.

**Comment by rajtukadia** [comment]
<html>
<head>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.5.3/p5.min.js" type="text/javascript"></script>
    <script src="p5.gif.js" type="text/javascript"></script>
</head>
<body>
</body>
<script type="text/javascript">
var gif;

function setup() {
    createCanvas(700, 300);
    gif = loadGif('sorry.gif');
}

function draw() {
    background(0);
    image(gif, 0, 0);
}
</script>
</html>

**Comment by rajtukadia** [comment]
``<html>
<head>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.5.3/p5.min.js" type="text/javascript"></script>
    <script src="p5.gif.js" type="text/javascript"></script>
</head>
<body>
</body>
<script type="text/javascript">
var gif;

function setup() {
    createCanvas(700, 300);
    gif = loadGif('sorry.gif');
}

function draw() {
    background(0);
    image(gif, 0, 0);
}
</script>
</html>

**Comment by rajtukadia** [comment]
`<html>
<head>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.5.3/p5.min.js" type="text/javascript"></script>
    <script src="p5.gif.js" type="text/javascript"></script>
</head>
<body>
</body>
<script type="text/javascript">
var gif;

function setup() {
    createCanvas(700, 300);
    gif = loadGif('sorry.gif');
}

function draw() {
    background(0);
    image(gif, 0, 0);
}
</script>
</html>`

**Comment by rajtukadia** [comment]
var gif;

function setup() {
    createCanvas(700, 300);
    gif = loadGif('sorry.gif');
}

function draw() {
    background(0);
    image(gif, 0, 0);
}

**Comment by rajtukadia** [comment]
the above code is written in `<sctript>` tag and we need to add 2 js file that is > p5.min.js> and > p5.gif.js
>

**Comment by rajtukadia** [comment]
https://github.com/antiboredom/p5.gif.js

**Comment by lmccart** [comment]
Ah ok, I think this is a known firefox issue. The p5.Gif library actually has it's own repo, it is a contributed library, not one directly supported by us. You can follow progress on that issue here: https://github.com/antiboredom/p5.gif.js/issues/1.
