### ISSUE TITLE
Reference: Link for windowResized() is broken

### ISSUE THREAD

**Issue by chiunhau** [processing/p5.js#1575]
- The link for windowResized() in reference doesn't work
- Example for windowResized() is broken too

![2016-08-31 10 05 00](https://cloud.githubusercontent.com/assets/6561433/18113449/8092c61c-6f62-11e6-9cf5-fb83b8a466b0.png)

(Opera 39.0 on Mac OSX 10.11.5)

**Comment by lmccart** [comment]
fixed with https://github.com/processing/p5.js/commit/4af4eeb96b1fdd8fc3318513907d01e0a00efd17
