### ISSUE TITLE
webkitImageSmoothingEnabled is deprecated

### ISSUE THREAD

**Issue by AgentMulder** [processing/p5.js#1576]
FYI

When I call

`pixelDensity(1);` 

on Linux Ubuntu, Chrome version 47.0.2526.111

I get this warning:

p5.js:12091:
'CanvasRenderingContext2D.webkitImageSmoothingEnabled' is deprecated. Please use 'CanvasRenderingContext2D.imageSmoothingEnabled' instead.

**Comment by limzykenneth** [comment]
There are fallbacks to use both. `CanvasRenderingContext2D.webkitImageSmoothingEnabled` is there probably for backwards compatibility and won't break anything. In this case, it's just a deprecation warning and everything should still work as expected.
