### ISSUE TITLE
textWidth("") = NaN

### ISSUE THREAD

**Issue by Bryce-Summers** [processing/p5.js#1578]
It appears that textWidth("") returns NaN with my version of p5 that I downloaded on June 10th, 2016.

I would be happier if it returned 0 for the empty string.

**Comment by lmccart** [comment]
hm i'm having a hard time reproducing... I get 0 in chrome, safari, firefox, and p5 editor on mac using version 0.5.3 of the library. can you give me more information about your setup? are you on linux or pc maybe?

**Comment by lmccart** [comment]
actually, the fix I just pushed should solve this problem regardless of platform as it's just checking for string length 0 before doing any calculation. it will be included in the next version, thanks!

**Comment by Bryce-Summers** [comment]
That look like a good fix to me!
