### ISSUE TITLE
httpGet and httpDo does not execute error

### ISSUE THREAD

**Issue by hiddenenigma** [processing/p5.js#1581]
Hello, this is my first time submitting a bug so let me know if I'm doing this correctly.

I've been trying to execute an error with either httpDo or httpGet functions but I'm not able to. I followed the reference on p5js.org and saw you can use a reqwest object so I tried that but the console says "reqwest is not defined". I did succeed with the reqwest object when I added reqwest.js but the httpDo function did not work.

Here's the code for reference: 

``` javascript
var requestBtn;

function setup() {
  createCanvas(100,100);
  requestBtn = createButton("test");
  requestBtn.mousePressed(makeRequest);
}

function makeRequest() {
  // httpDo("http://ec2-52-27-255-123.us-west-2.compute.amazonaws.com/questions", "GET", null, "jsonp", onDataReceived, onErrorReceived);

  reqwest({
      url: 'http://ec2-52-27-255-123.us-west-2.compute.amazonaws.com/questions'
    , method: 'get'
    , data: []
    , success: onDataReceived
    , error: onErrorReceived
  })
}

function onDataReceived(data) {
  console.log(data);
  console.log("success");
}

function onErrorReceived(response) {
  console.log(response);
  console.log("error!!!!");
}
```

**Comment by limzykenneth** [comment]
Hi @hiddenenigma, there is no wrong way to submit a bug!

The `reqwest` object is not exposed outside of the p5 library so you wouldn't be able to use it directly like the example code you provided and there isn't any mistake in the `httpDo` function you had. p5 is using `reqwest` in the background for the async request but it assumed that `json` and `jsonp` is the same thing where it's not quite, even in reqwest's API.

I assume it's actually quite an easy fix but you never know with such things. I'll see if I can find some  time to fix this but for anyone who wants to jump in front of me, feel free and here's a tip on where the offending code [may be](https://github.com/processing/p5.js/blob/master/src/io/files.js#L879).

**Comment by idori** [comment]
Hi @hiddenenigma  & @limzykenneth. 
I tried to debug this issue and I think the problem is somewhere within reqwest.js library - There is also a similar issue open in the reqwest.js repository:
https://github.com/ded/reqwest/issues/237

**Comment by hiddenenigma** [comment]
Hi @limzykenneth and @idori,

Thank you for your response and thank you for taking a look at the bug. So I guess there isn't anything for us to do if the issue lies with the reqwest.js library?

**Comment by lmccart** [comment]
Yes, I believe that's correct. We do have another issue open about looking into replacing reqwest entirely (https://github.com/processing/p5.js/issues/1694), but for now it's best to follow along with the issue on the reqwest repository.

Thanks @idori for looking into this!
