### ISSUE TITLE
beginShape() and endShape() not working (WEBGL)

### ISSUE THREAD

**Issue by QJjs** [processing/p5.js#1582]
I'm trying to use beginShape()/endShape in WebGL, but whatever I do, I can't get it to work. I've made sure that I've updated the P5.js library, but still no luck. Every time, the dev console gives out uncountable errors about a bunch of things about -1 not being a valid index. I tried the simplest of operations, but the same result occurs. Anyone got any tips?

function setup(){
	createCanvas(windowWidth, windowHeight, WEBGL);
}

function draw() {
	background(0);
	beginShape();
	vertex(0, 0, 0);
	vertex(10, 10, 10);
	endShape();
}

**Comment by indefinit** [comment]
Hmm, I'm not seeing any issues with the master branch, but it looks like the issue might have to do with a missing fill();  command.  Try adding fill(255) before your beginShape call and that should work.  Another issue might have to do with the 3d camera perspective.  To be sure, try both vertices at z=0;

**Comment by QJjs** [comment]
now it shows this in the console:

p5.RendererGL: enabled webgl context            p5.js:30441:7
Error: WebGL: Exceeded 32 live WebGL contexts, losing the least recently used one.          p5.js:30436:27
TypeError: this._renderer is undefined             p5.js:30677:7
