### ISSUE TITLE
resize with 0 entry sets size to zero on safari and iOS

### ISSUE THREAD

**Issue by weymouth** [processing/p5.js#1583]
It seem that resizing an image with a 0 argument (which is supposed to preserve the aspect ratio) doesn't consistently work on safari.

Note that this failure seems to depend on the image. For instance, this code 

    function setup() {
      createCanvas(windowWidth, windowHeight);
      img = loadImage("data/source.png");
    }
    function draw() {
      image(img, 0, 0);
    }
    function mousePressed() {
      img.resize(0,width/2);
    }

(which is basically the resize documentation example with a 0 argument) works for [source.png](https://github.com/weymouth/fluid-dynamics/blob/master/superposition/data/source.png) , but not for [reset.png](https://github.com/weymouth/fluid-dynamics/blob/master/superposition/data/reset.png).

**Comment by limzykenneth** [comment]
Hmm....honestly I have no idea why. As you mentioned it only happens on Safari as well which points towards something in Safari's canvas implementation. If you ever come across any other images with the same behaviour do let us know, we might find some pattern in there.

In the mean time, an more consistent way of doing it might be something like:
```javascript
var w, h, ratio;
w = width/2;
ratio = w/width;
h = height * ratio;
img.resize(w,h);
```

**Comment by lmccart** [comment]
haha good ole safari. I had to round the numbers down to integer pixel values for it to work. that explains why it worked for some images and not others -- it had to do with the calculated values and whether they were integers or not.

https://github.com/processing/p5.js/commit/854cf2389cf581334ac188acab9158fd7ca5d0f1
