### ISSUE TITLE
How to draw without aliasing ?

### ISSUE THREAD

**Issue by orgicus** [processing/p5.js#1585]
Hi,

I'm trying to disable aliasing, but it doesn't seem to work.

Here's the test Processing sketch I started with:
```java
int w = 40;
int h = 10;
int s = 10;

PGraphics buffer;

void setup(){
  size(400,100);
  noSmooth();
  
  buffer = createGraphics(w,h);
  buffer.beginDraw();
  buffer.noSmooth();
  buffer.noFill();
  buffer.endDraw();
  
}
void draw(){
  float r = sin(frameCount * 0.01) * 20;
  buffer.beginDraw();
  buffer.background(255);
  buffer.ellipse(mouseX / s,mouseY / s,r,r);
  buffer.endDraw();
  image(buffer,0,0,width,height);
}
```
This works as expected: [preview](http://imgur.com/a/yMllZ)

Here's the p5.js version:
```javascript
var w = 40;
var h = 10;
var s = 10;

var buffer;
var canvas;

function setup(){
  canvas = createCanvas(400,100);
  noSmooth();
  
  buffer = createGraphics(w,h);
  buffer.noSmooth();
  buffer.noFill();
  
}
function draw(){
  var r = sin(frameCount * 0.01) * 20;
  buffer.background(255);
  buffer.ellipse(mouseX / s,mouseY / s,r,r);
  image(buffer,0,0,width,height);
}
```
This doesn't work as expected: [preview](http://imgur.com/a/IZcxj)

I've also tried checking if ```imageSmoothingEnabled``` is ```false``` on both contexts (```canvas``` and ```buffer```):
```
canvas.drawingContext.imageSmoothingEnabled
false
buffer.elt.getContext('2d').imageSmoothingEnabled
false
```

Am I missing anything ? Can aliasing be disabled using p5.js ?
If so how ?

Thank you ^_^

**Comment by limzykenneth** [comment]
@orgicus Hi, from what I found, it seems that it is not possible to turn off anti-aliasing for line drawings. `imageSmoothingEnabled` is only used when you resize images in the canvas and does not apply to lines. We would need to wait for (if ever) the browsers to implement such an option or roll our own line drawing algorithm.

**Comment by orgicus** [comment]
Just wanted to post a hacky workaround (sampling/redrawing the low-res image): https://editor.p5js.org/george.profenza/sketches/3nLBvI_vA
