### ISSUE TITLE
Is it possible to skew an image?

### ISSUE THREAD

**Issue by mutawa** [processing/p5.js#1587]
I know how to draw an image on a canvas by

`image(spriteSheet,100,140,200,100,x,y,width,height);`

I also know how to rotate the image by essentially rotating the canvas

`roatate(PI/2);`

but is there a way to make the image look like the top of it is further that the bottom? 
what I want to do is make the user think that the image is being flipped, and that requires some 3D visual effects, but I am only interested in working with a 2D canvas.

**Comment by lmccart** [comment]
check out the shear methods

**Comment by Diego-O-Perez** [comment]
It is possible to skew an image in P5.js, processing is, and naitive JavaScript.

I'm not completely sure how to do it but I've seen people accomplish it in a variety of ways with smooth, lag-free rendering.

Some people have used Matrixies and transformed each pixel of the image using loadPixels.

Another approach is to cut the image into strips and place them according to the slope of the image your transforming.

Finnaly, there's an inbuilt function using createGraphics(canvasWidth, canvasHeight, JAVA2D); which let's you shear and skew images using shearX(angle); However I'm not completely sure how to use it.

**Comment by outofambit** [comment]
hey @Diego-O-Perez, could you post this in the p5js forum? there's a new one! https://discourse.processing.org/c/p5js
