### ISSUE TITLE
Arabic characters work in text() but not in Tickle example

### ISSUE THREAD

**Issue by mutawa** [processing/p5.js#1589]
I found an example titled "Tickle" on this url : http://p5js.org/examples/examples/Interaction_Tickle.php

I changed the first line 
`var message = "Tickle";`

to 
`var message = "أحمد";`

When I ran the code, nothing appeared. I tried again using English letters and that worked fine.

This may be a problem with the specified font, not recognizing Arabic characters, but when I remove the text boundary calculation code, the Arabic word does appear as expected.

**Comment by sepans** [comment]
You are right `assets/LeagueGothic-Regular.otf` doesn't support Arabic script but with few tweaks I got the sketch to work with the default font. I am hardcoding the width and height of the string here to make it work but a better solution is to get a reference to the default font which I don't know if that is currently possible in p5.

```javascript
var message = "سپند", // ;)
  font,
  bounds, // holds x, y, w, h of the text's bounding box
  fontsize = 60,
  x, y; // x and y coordinates of the text

function preload() {
  //font = loadFont('assets/LeagueGothic-Regular.otf');
}

function setup() {
  createCanvas(710, 400);

  // set up the font
  //textFont(font);
  textSize(fontsize);

  // get the width and height of the text so we can center it initially
  bounds = {x: 0, y: 0, h: 41.4, w: 94.61999999999999, advance: 0}//font.textBounds(message, 0, 0, fontsize);
  x = width / 2 - bounds.w / 2;
  y = height / 2 - bounds.h / 2;
}

function draw() {
  // instead of clearing the background, fade it by drawing
  // a semi-transparent rectangle on top
  fill(204, 120);
  rect(0, 0, width, height);

  // write the text in black and get its bounding box
  fill(0);
  text(message, x, y);
  bounds = {x: x, y: y, h: 41.4, w: 94.61999999999999, advance: 0}//font.textBounds(message,x,y,fontsize);

  // check if the mouse is inside the bounding box and tickle if so
  if ( mouseX >= bounds.x && mouseX <= bounds.x + bounds.w &&
    mouseY >= bounds.y && mouseY <= bounds.y + bounds.h) {
    x += random(-5, 5);
    y += random(-5, 5);
  }
}
```

**Comment by mutawa** [comment]
Thanks a lot. That worked for me

**Comment by dhowe** [comment]
nice solution @sepans 👍

**Comment by sepans** [comment]
Thanks @dhowe. Wondering if it is possible to somehow get a reference to p5 default font and call `textBounds`? `textBounds` seems to be a very handy function and it would be nice to be able to use it without loading a font.
