### ISSUE TITLE
p5.filter() not working ("TypeError: canvas is undefined")

### ISSUE THREAD

**Issue by alexorex** [processing/p5.js#1591]
Actually, if as in Processing, p5.Renderer object should have all standard methods of the default canvas, but it obviously doesn't. Not a pro programmer myself, but I suppose something is off about general concepts like inheritance. Is it not possible to replicate all properties and methods of the default canvas?

**Comment by lmccart** [comment]
They are not all implemented yet. Can you please post a snippet of example code I can use to test?

**Comment by alexorex** [comment]
here
the error is caused by the pg.filter(INVERT) call at the end

`var pg
function setup() {
    createCanvas(700, 700);
    pg = createGraphics(Math.floor(600), Math.floor(600));
    pg.translate(300, 300);
    noLoop();
}

function draw() {
  pg.background(255);
  pg.ellipseMode(CENTER);
  pg.fill(0);
  pg.noStroke();
  pg.ellipse(0, 0, 200, 200);
  // pg.copy();
  pg.filter(INVERT);
  // pg.image(pg,0,0);
  image(pg,0,0);
}`

**Comment by hkirat** [comment]
Problem is that p5.Graphics doesn't have canvas attribute but has elt instead.

Suggested Fix: 
p5.prototype.filter = function(operation, value) {
 if(this.canvas !==  undefined)
  Filters.apply(this.canvas, Filters[operation.toLowerCase()], value);
 else 
  Filters.apply(this.elt, Filters[operation.toLowerCase()], value);
};

**Comment by alexorex** [comment]
I hoped for an easy porting of my java Processinng object to js, but guess I wanted too much...)

**Comment by lmccart** [comment]
fixed with https://github.com/processing/p5.js/pull/1700
