### ISSUE TITLE
video.get() return empty pixel array

### ISSUE THREAD

**Issue by KHALED-LAKEHEL** [processing/p5.js#1594]
let video;
function setup() {
    video = select("#video"),
        button = select("#snap");
    createCanvas(video.width, video.height).id("canvas");
    button.mousePressed(takesnap);
}

function takesnap() {
    console.log(video.get());
 // affiche p5.Image {width: 1, height: 1, canvas: canvas, drawingContext: CanvasRenderingContext2D, _pixelDensity: 1…} -----pixels:Array[0] 
}

**Comment by lmccart** [comment]
hi, it's a little hard to figure out what's wrong here... could you post the html snippet as well? if this is a general debugging question, it's best to post it on the forum: https://forum.processing.org/two/
