### ISSUE TITLE
Print canvas(div) on printer

### ISSUE THREAD

**Issue by stihilus** [processing/p5.js#1597]
Hello!

I try print canvas from p5js to printer :) 

```
  <div id="sketch-holder">
    <!-- Our sketch will go here! -->
  </div>
```
_https://github.com/processing/p5.js/wiki/Positioning-your-canvas_

I follow this tutorial:
https://www.developphp.com/video/JavaScript/Partial-Print-Document-Tutorial-HTML-div-Content

```
<!DOCTYPE html>
<html>
<head>
<script>
function printContent(el){
	var restorepage = document.body.innerHTML;
	var printcontent = document.getElementById(el).innerHTML;
	document.body.innerHTML = printcontent;
	window.print();
	document.body.innerHTML = restorepage;
}
</script>
</head> 
<body> 
<h1>My page</h1>
<div id="div1">DIV 1 content...</div>
<button onclick="printContent('div1')">Print Content</button>
<div id="div2">DIV 2 content...</div>
<button onclick="printContent('div2')">Print Content</button>
<p id="p1">Paragraph 1 content...</p>
<button onclick="printContent('p1')">Print Content</button>
</body> 
</html>
```

but if i run only code from second tut everything working, but if i put that code and make div id "sketch-holder" in button, when i press button p5 canvas disappears.

**Comment by lmccart** [comment]
it looks like saving the content in document.body.innerHTML and then restoring it likely wipes the canvas clean. a better way to do this would be to use the `save()` method. for future reference, programming questions like these are best posted in the forum: https://forum.processing.org/two/, the github issues are just for library bugs and feature requests. thanks.
