### ISSUE TITLE
Text example in WebGL tutorial broken

### ISSUE THREAD

**Issue by dhowe** [processing/p5.js#1599]
https://github.com/processing/p5.js/wiki/Getting-started-with-WebGL-in-p5

**Comment by jalbert10NJ** [comment]
This open bug report appears pretty fundamental (as it appears at least to me that a lot more than just a single text example is broken -- it's all of WEBGL in p5.js, at least for me) -- readers pls see thread at:

https://forum.processing.org/two/discussion/18291/in-p5-js-webgl-never-ever-stops-loading-for-me-why

**Comment by limzykenneth** [comment]
@jalbert10NJ this is a known issue (see #1565, #1544 and [#266](https://github.com/processing/p5.js-website-OLD/issues/266). It should be fixed in the master branch and should be all fix on the website when the next release (0.5.4) comes out.

**Comment by lmccart** [comment]
thanks @limzykenneth. expect the new version in the next day or two.

**Comment by lmccart** [comment]
this should be fixed now
