### ISSUE TITLE
p5.js mode fails to install in Processing PDE, install always incomplete

### ISSUE THREAD

**Issue by jeremydouglass** [processing/p5.js#1600]
I'm using Processing PDE 3.2.1 on OS X 10.10.5.

1. When I go to "Modes" to add p5.js, it says that p5.js 1.0.2 is available.
2. When I install p5.js, however, it now says 1.0 is installed, an update to 1.0.2 is available.
3. When I update to 1.0.2:  
    a. ...using the Modes tab, it downloads, installs, and then again says 1.0 is installed and 1.0.2 is available.  
    b. ...using the Updates tab / "Update All", it spins and times out.

https://forum.processing.org/two/discussion/18248/p5-js-mode-fails-to-update-install-always-incomplete

**Comment by lmccart** [comment]
I've posted it on the Processing p5.js mode repo:
https://github.com/fathominfo/processing-p5js-mode/issues/11
