### ISSUE TITLE
Examples not showing up on p5.js/examples webpage

### ISSUE THREAD

**Issue by jeremydouglass** [processing/p5.js#1601]
Categories headers (Structure, Simulate) etc. are present, but example links are missing.

http://p5js.org/examples/

Also reported here: https://forum.processing.org/two/discussion/18277/examples-not-showing-on-p5-js-examples-page

Might be related to #1600

**Comment by lmccart** [comment]
fixed with https://github.com/processing/p5.js-website/commit/1f3f9e833a33f5158ec7d005473f393f1873b6f0
