### ISSUE TITLE
Point() and Line() not working in WEBGL mode

### ISSUE THREAD

**Issue by kenthuth** [processing/p5.js#1609]
I've been working with traditional Processing for years, however I'm now switching to p5.js. I cannot get a simple point() or line() to render in WEBGL mode. When I switch to P2D, everything works just find. Please find the console error message attached. Any help would be appreciated!

<img width="445" alt="screen shot 2016-09-30 at 11 11 25 am" src="https://cloud.githubusercontent.com/assets/1275956/18996604/eb5aea48-86fe-11e6-96a2-bd257d8c7fad.png">

Source Code:
-----------------
function setup() {
	getWindowDimensions();	
	createCanvas(width, height, WEBGL);	
}

function getWindowDimensions(){
	width  = window.innerWidth;
	height = window.innerHeight;
}

function draw(){	
	push();
		translate(width/2, height/2, 0);
		strokeWeight(100);
		stroke(0, 0, 0);
		point(0, 0);
	pop();
}

**Comment by lmccart** [comment]
Hi, yes, the point() function has not yet been added to webgl mode, so it will not work until we complete this task. We have a few people working on building out this mode so hopefully it should be there soon!

**Comment by indefinit** [comment]
In the meantime you can use beginShape with the POINTS or LINES flag like this:

beginShape(POINTS)
//points as vertices
endShape()

**Comment by hachpai** [comment]
Any idea on a way to change the stroke weight for lines?
