### ISSUE TITLE
npm package pointing to the source?

### ISSUE THREAD

**Issue by daniloprates** [processing/p5.js#1610]
I'm using P5 via npm and `import` and getting this message from Webpack:

```
[HMR] ./~/p5/lib/p5.js
Critical dependencies:
2:475-482 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/p5/lib/p5.js 2:475-482
```

I'm not sure what would be the consequences of pointing the package to the source, as p5 has lots of dependencies, but it seems to be the [best practice](https://github.com/webpack/webpack/issues/1617#issuecomment-181713671).

**Comment by lmccart** [comment]
Yeah, I think in this case it's rather complicated. There are already many steps to the release process, I'd prefer to continue to post the built file to npm.
