### ISSUE TITLE
Online editor crashes through nested loop

### ISSUE THREAD

**Issue by sebmorales** [processing/p5.js#1612]
Hi,
Fist time here. I am trying to make radial color gradients by mathematically assigning values to every pixel within a circle. I am basically using a big nested loop and it takes a little to run but it only needs to run once.

When I was writing this code on the online editor I got an error saying that my loop was taking too long to run and that it might be an infinite loop.

It works fine on the desktop version.

Here an example of the nested Loop:
https://alpha.editor.p5js.org/projects/Hk3Npc36

Here the gradient code:
https://alpha.editor.p5js.org/projects/HJNqd936

**Comment by lmccart** [comment]
Hi, you can post issues for the web editor here:
https://github.com/processing/p5.js-web-editor/issues

**Comment by sebmorales** [comment]
Oh, sorry. I made a new [issue](https://github.com/processing/p5.js-web-editor/issues/117) on the proper page. Thanks
