### ISSUE TITLE
pixels[ ] reference

### ISSUE THREAD

**Issue by kaganjd** [processing/p5.js#1613]
On [this](https://p5js.org/reference/#/p5/pixels[]) reference page: 
1. The layout of the example code makes the description unreadable 
2. The example code never loads

**Comment by lmccart** [comment]
looks like a problem with pixelDensity()... [this one](https://p5js.org/reference/#/p5/pixelDensity) is broken too

**Comment by lmccart** [comment]
should be fixed now with lib update
