### ISSUE TITLE
Update docs to reflect that println() has been deprecated

### ISSUE THREAD

**Issue by kaganjd** [processing/p5.js#1614]
Starting a list of reference pages that use the println() function in their examples, and which now need to be updated since println() is no longer a thing:

- [ ] https://p5js.org/reference/#/p5/println
- [ ] https://p5js.org/reference/#/p5/blue
- [ ] https://p5js.org/reference/#/p5/green
- [ ] https://p5js.org/reference/#/p5/red

**Comment by lmccart** [comment]
thanks, I think I already updated all these with a find and replace. just need to build a new version and update the libs. I'll do that now.
