### ISSUE TITLE
Links broken on the README file

### ISSUE THREAD

**Issue by pizzels** [processing/p5.js#1617]
The link for the "Learn" list item on the "Learning" section points to the wrong URL. It should link to the tutorials page on the web.

Also does the "contribute section" link under "Get Involved". For what I see all the info to contribute to the project is now on the "Development" wiki page, but maybe the best would be to link to the "Community" page on the website.

**Comment by pizzels** [comment]
I'd like to fix this myself as my first contribution to the project

**Comment by lmccart** [comment]
fixed with https://github.com/processing/p5.js/pull/1618. welcome @pizzels :)
