### ISSUE TITLE
Create a vertex using a vector object

### ISSUE THREAD

**Issue by Niels-NTG** [processing/p5.js#1619]
I'm currently refactoring some old personal project of mine, this time trying to be fully object oriented. I was somewhat disappointed that I couldn't do this:

``` javascript
var someVector = new p5.Vector(4, 1);
beginShape();
vertex(someVector);
endShape();
```

Instead I have to do this:

``` javascript
var someVector = new p5.Vector(4, 1);
beginShape();
vertex(someVector.x, someVector.y);
endShape();
```

Does seem like a missed opportunity to me.

**Comment by joshuaalm** [comment]
Not sure how to connect the issue with my commit, but I copied the code from the current vertex() function and made the args variable contain the contents of vertex.array().  Let my education begin.

**Comment by lmccart** [comment]
thanks for the pull request. after looking into this, I'd like to stick to the original signature and not accept p5.Vector as arguments here. I think it opens a can of worms for maintaining consistency across other methods that I'm not prepared to deal with right now.

**Comment by Niels-NTG** [comment]
Understandably. It seemed like a good idea at the time, but since JavaScript doesn't really have proper support for overloading, the code turns into a big mess.
