### ISSUE TITLE
Add default parameters to perspective() and ortho()

### ISSUE THREAD

**Issue by mindofmatthew** [processing/p5.js#1623]
Right now, the WebGL `perspective()` and `ortho()` camera functions require all of their parameters to be set, even though both have well-defined default values, and should be callable without passing in any parameters.

In addition, the documentation for both of these methods needs to be expanded.

**Comment by hkirat** [comment]
@mindofmatthew Right now the ortho function takes 6 parameters that define the window. 
However, it assumes that we are taking a front view ortho projection. 
However, orthographic projections need not necessarily have the view normal alligned to the z axis as assumed by the ortho function.
Shouldn't the parameters taken by the function be as follows : 
{x, y, z} of the camera
{x1, y1, z1} defining the view normal (z axis in this case)
{x2, y2, z2} defining the view up normal (y axis in this case)
