### ISSUE TITLE
createCanvas after pageload

### ISSUE THREAD

**Issue by ChrisBrittOSU** [processing/p5.js#1625]
I am currently working on developing an application that requires the dynamic execution of p5.js files and for them to be rendered on a page. I am however running into an issue where if createCanvas() is called after the page has finished loading it fails to actually create the canvas element and thus allow the p5.js animation to run. Is there a way to trigger p5js to reinitialize so it will call the setup / draw functions at some later time after the page has already finished loading?
Thank you all for any assistance you would be able to provide.

**Comment by lmccart** [comment]
indeed. see the notes about "on demand global mode" in this section: https://github.com/processing/p5.js/wiki/p5.js-overview#instantiation--namespace
