### ISSUE TITLE
no french letters with xml

### ISSUE THREAD

**Issue by matthieu21** [processing/p5.js#1628]
I manage to extract some sentences from an xml file but french letters (à, ç, é, è ..)  are not visible.
The font is good with all letters, all file are in UTF-8. I don't where is the bug

**Comment by limzykenneth** [comment]
Hi @matthieu21, can you post a sample code just so we have a better idea of what's going wrong? I would say your p5 sketch and XML file are both needed, feel free to simplify it if it contains sensitive information.

**Comment by matthieu21** [comment]
Here's the 2 files :
[codeFrenchCaratcters.zip](https://github.com/processing/p5.js/files/522439/codeFrenchCaratcters.zip)

works good except for special characters

**Comment by matthieu21** [comment]
Sorry, I was in the rush and I give you all code.
My code is a little bit strange because native function loadXml() from p5 never work for me.
So I needed to use javascript
Here's a sumarize
[bugP5loadXml.txt](https://github.com/processing/p5.js/files/532682/bugP5loadXml.txt)
Thanks a lot

**Comment by matthieu21** [comment]
I think it's p5.js bug because I tried just a function like
text("ééé", 150, 50);
And there is no result on the screen.

**Comment by lmccart** [comment]
make sure your js file is saved as utf-8. I initially saw the issue you mentioned, then when I saved the file as utf-8 it rendered correctly.

**Comment by matthieu21** [comment]
Thanks, but I already try it. I don't know where is the problem. I think maybe p5.js library 
doesn't accept all characters because when I do an alert() everything is ok.
But I don't use loadxml native p5.js functions, it's maybe that

**Comment by lmccart** [comment]
I was able to get it display correctly using the file you supplied and forcing my files to utf-8 encoding. I'm afraid since I can't reproduce I'm not able to resolve this one.
