### ISSUE TITLE
Make it clearer that loading the cat image in "p5.js overview" requires a local server

### ISSUE THREAD

**Issue by JGL** [processing/p5.js#1631]
Trying: https://github.com/processing/p5.js/wiki/p5.js-overview works well, but the cat image loading example will not work without running a local server. This should be made explicit with a link to this page: https://github.com/processing/p5.js/wiki/Local-server

**Comment by limzykenneth** [comment]
Hey Joel, Good to see you here! Just edited that, do have a look!

**Comment by JGL** [comment]
It's a wiki of course! (-; Thanks Ken.
