### ISSUE TITLE
Allowing the viewer to browse the assets folder

### ISSUE THREAD

**Issue by CharlesFr** [processing/p5.js#1632]
I'm trying to create a website/portfolio which allows the user to browse through the files and folders inside the "assets" folder which is located on the server.

My question is, how can I retrieve the files/folder names from inside "assets"?

Thanks in advance, 
Charles

**Comment by lmccart** [comment]
if the assets folder is within your project folder you should be able to access it directly like

img = loadImage("assets/myImage.jpg");

in general, the forum is the best place for general programming question: forum.processing.org

**Comment by CharlesFr** [comment]
Sorry perhaps my question wasn't clear - how can I retrieve all the file/folder names inside of "assets".

**Comment by lmccart** [comment]
This can't be done from the client side (using p5.js), you'd need to write some server code using node.js or other.

**Comment by CharlesFr** [comment]
So if I needed to access a number of files, they'd all in to be hardcoded in my P5 sketch?

**Comment by lmccart** [comment]
please follow up on this question on the forum :) thanks!
