### ISSUE TITLE
createGraphics does not work with p5.play in instance mode.

### ISSUE THREAD

**Issue by ycatch** [processing/p5.js#1635]
Hi, there.

I tried p5.js with p5.play.js in instance mode, like this.

	<html>
	<head>
	  <meta charset="UTF-8">
	  <style> body {padding: 50; margin: 0;} </style>
	</head>

	<body>
		<script src="p5.js"></script>
		<script src="p5.play.js"></script>
		<script>
		var s = function(p) {

			var sq;
			var layer;
			p.setup = function() {
				p.createCanvas(800,400);
				p.background(200);
				layer = p.createGraphics(400, 200, 0, 0);
				sq = p.createSprite(400, 200, 50, 50);
			}

			p.draw = function() {
				p.drawSprites();
				p.image(layer);
			}
		}

		var myp5 = new p5(s);
		</script>
	</body>
	</html>

However, I had an error message.

    TypeError: pInst.createVector is not a function

When I commented createGraphics out, it worked.

Does anyone know how to work it with p5.play ?

[p5.play.js issue](https://github.com/molleindustria/p5.play/issues/104)

**Comment by lmccart** [comment]
hi, this issue only seems to come up with p5.play so I'm going to close this here since you've posted this on the p5.play repo already. if you dig deeper and find a specific issue with the way p5 is handling createGraphics that's causing please feel free to post.

**Comment by krongeroso** [comment]
Try this!!
p.createCanvas(800,400);
p.pixelDensity(1);

;)

**Comment by lmccart** [comment]
@krongeroso please see this thread: https://github.com/molleindustria/p5.play/issues/104
