### ISSUE TITLE
p5 AudioIn amp not controllable with envelope 

### ISSUE THREAD

**Issue by bjmk** [processing/p5.js#1642]
I'd like to control the amplitude of the AudioIn object of p5 with an envelope as one can do with an Oscillator.   Since Audio.amp() only takes a real number as a value, this isn't possible. Is there a work around for this?

**Comment by lmccart** [comment]
hi could you please post this on the p5.js sound repo? https://github.com/processing/p5.js-sound/issues

thanks!

**Comment by bjmk** [comment]
sure
