### ISSUE TITLE
DynamicsCompressor.ratio.value 100 outside nominal range [1, 20]; value will be clamped.

### ISSUE THREAD

**Issue by MilesFM** [processing/p5.js#1643]
DynamicsCompressor.ratio.value 100 outside nominal range [1, 20]; value will be clamped. Warning came up when fiddling around. Was not using any function from that file and appeared when only a canvas was drawn along with a background. Appeared in chrome in inspect mode. Using files generated and in p5.exe (latest version of p5.exe when posted).

**Comment by lmccart** [comment]
thanks. could you post the code that triggered this warning?

**Comment by lmccart** [comment]
thanks, I've moved this to the p5.js-sound repository issues: https://github.com/processing/p5.js-sound/issues/153
