### ISSUE TITLE
Online Editor couldn't save large .js files?

### ISSUE THREAD

**Issue by dordorlam** [processing/p5.js#1646]
My online editor is having trouble saving when I tried uploading or adding a new .js file that has many lines of code, i.e. seriously.js

It stays at loading:
![screen shot 2016-10-23 at 10 01 50 pm](https://cloud.githubusercontent.com/assets/22154099/19631622/cbff0e10-996c-11e6-8734-d76f73eb4734.png)

And it won't save my project (when I click the 'save' button) if I created a new file and try to paste the code in so when I refresh the page, the code that was pasted in disappears.

This is the seriously.js code that I was trying to attach to my sketch:

[https://github.com/brianchirls/Seriously.js/edit/master/seriously.js](url)

**Comment by limzykenneth** [comment]
Hi @dordorlam, I may be a bit out of the loop here but what did you mean by "online editor"? I don't remember there being an official online editor for p5.js yet. Can you provide more info about it? Also the link to seriously.js is not working.

Cheers.

**Comment by limzykenneth** [comment]
Huh, I just found it now. Might be more useful to post this issue over on its own repo: https://github.com/processing/p5.js-web-editor/issues

**Comment by lmccart** [comment]
thanks this is being tracked here: https://github.com/processing/p5.js-web-editor/issues/160
