### ISSUE TITLE
loadImage() not working for remote svg's

### ISSUE THREAD

**Issue by catarak** [processing/p5.js#1648]
In the process of trying to work on [processing/p5.js-web-editor/#14](https://github.com/processing/p5.js-web-editor/issues/14) I noticed that when trying to run the following sketch:

``` javascript
var circle;

function setup() { 
  createCanvas(400, 400);
    circle = loadImage('https://s3-us-west-2.amazonaws.com/p5.js-webeditor/77d950cc-326d-4953-9ca2-0c104180db56.svg');
} 

function draw() {
  background(220);
    image(circle, 100, 100);
}
```

the svg wouldn't load unless it was linked to locally, i.e. I was serving a directory and the svg was in that folder. It's not a CORS issue since I have disabled CORS for that S3 bucket while the editor is still in alpha.

**Comment by REAS** [comment]
Thank you for looking into this @catarak

**Comment by lmccart** [comment]
I think this is correct behavior -- loadImage() only works with local files because of cross origin canvas tainting security issues.

**Comment by catarak** [comment]
The strange thing is there's no cross-origin error in the console (see https://alpha.editor.p5js.org/projects/SkNa-q1ex), since I enabled CORS on the S3 url. So I _think_ it's something else, though I'm not sure what...

**Comment by lmccart** [comment]
ah you're right, that should not be a cross origin problem. I edited your example to use a different remote svg and it seems ok:
https://alpha.editor.p5js.org/projects/ry7Yfwbgg

I did find a part in the code that is not properly logging image load errors however, so this could be a reason for lack of info?

**Comment by catarak** [comment]
Yes, maybe it is silently failing... I'll double check all of the permissions on the S3 bucket.
