### ISSUE TITLE
text string element positions on mobile

### ISSUE THREAD

**Issue by Destinyschilde** [processing/p5.js#1649]
I have found that strings of text do not display at the proper position on mobile browsers, however they do display correctly when the devices display is switched off and back on again. The issue returns when the webpage is refreshed. I suspect the issue has something to do with the text size. 

example here: coolboy.online

**Comment by lmccart** [comment]
could you please post a code snippet that shows the problem in isolation? thanks!

**Comment by Destinyschilde** [comment]
HTML:
`<!DOCTYPE html>
<html>
<head>
  <title>who is dat boi?</title>
  <meta charset="UTF-8">
  <script language="javascript" type="text/javascript" src="p5.js"></script>
  <script type='text/javascript' src='addons/p5.dom.js'></script>
  <script language="javascript" type="text/javascript" src="sketch.js"></script>
  <link rel="stylesheet" type="text/css" href="css/template.css">
  <meta name="viewport" content="user-scalable=no,initial-scale=1,maximum-scale=1,minimum-scale=1,width=device-width">
</head>

<body>

  <div id="navo">
  </div>
  <div id="asd">
    <p>who is dat boi? who is dat boi? who is dat boi? who is dat boi? who is dat boi? who is dat boi? who is dat boi? </p>
  </div
</html>
`
JS:
`
function setup() {
  var cnv = createCanvas(displayWidth,displayHeight); /*this is just to nest it in a div*/
  cnv.parent("navo")
colorMode(HSB);

butx=30;
buty=60;

}

function draw() {

noStroke();
fill(frameCount % 360, 255, 255);
triangle(0, 0, 0,110, 110, 0);
textAlign(CENTER);
textSize(80);
fill(0);
fill(255);
text("+", butx, buty);

}
`

link:
coolboy.online/issue.html
