### ISSUE TITLE
WebGL autoclears?

### ISSUE THREAD

**Issue by idontlie** [processing/p5.js#1650]
Can we make WebGl not autoclear?
https://codepen.io/Thisisntme/pen/xEBBVL?editors=0010
This should not clear, and the little particles should leave trails. However, this is not the case. If you have had experience programming processing in 2D, you will remember that a "background(255)" statement is required to clear the screen white. But WebGL seems to do that automatically. Can we please fix this?

For reference, here is the P2D version with trails https://codepen.io/Thisisntme/pen/amrrOW?editors=0010

And, processing behaves like the P2D in p5js

**Comment by epiqueras** [comment]
WebGL has a preserveDrawingBuffer option, but it decreases performance.

https://msdn.microsoft.com/en-us/library/dn302354(v=vs.85).aspx
http://greggman.com/downloads/examples/webgl/lessons/resources/webgl-preservedrawingbuffer-true.html

I think it should be added as an option in the createCanvas function.
