### ISSUE TITLE
Documentation of image()

### ISSUE THREAD

**Issue by jlabgithub** [processing/p5.js#1653]
Hello,

The image function can take up to 9 parameters :
`image(img,sx,sy,sWidth,sHeight,dx,dy,dWidth,dHeight)`
But with only 5 parameters it becomes :
`image(img,dx,dy,dWidth,dHeight)`

It's strange that with 5 parameters it doesn't take the first 5 ones (I was expecting `image(img,sx,sy,sWidth,sHeight`).

It's also strange that you couldn't define sx, sy, sWidth and sHeight without giving all the 9 parameters.

Anyway, maybe it would be great to explain that in the `image()` documentation.

Regards, Julien.

**Comment by lmccart** [comment]
Thanks, great point. I flipped the args completely so it's like this:
```javascript
image(img,dx,dy,dWidth,dHeight,sx,sy,sWidth,sHeight)
```
I also improved the documentation so it is clearer what the options are. Both of these changes will be deployed with the next release.

**Comment by jlabgithub** [comment]
Many thanks.
I found this comment in `p5.prototype.image` : `// set defaults per spec: https://goo.gl/3ykfOq`
It seems that the previous arguments order was chosen to fit HTML standard.
Regards.
