### ISSUE TITLE
fullScreen is now a reserved variable for firefox

### ISSUE THREAD

**Issue by msawired** [processing/p5.js#1658]
p5js throws error on console on Firefox for the reserved word 'window.fullScreen' as "p5 had problems creating the global function "fullScreen", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.".

Apparently, now it is a reserved global variable in Firefox:
https://developer.mozilla.org/en-US/docs/Web/API/Window/fullScreen

I am not sure if this conflict would cause any issues on sketches however. Does this need a fix? Maybe just remove the console message?

**Comment by lmccart** [comment]
hm, fullscreen() method is lowercase in p5, so I think there shouldn't be a conflict. which version of the library are you using?
