### ISSUE TITLE
using the get function with floats doesn't work in safari

### ISSUE THREAD

**Issue by adalberth** [processing/p5.js#1659]
While using a Mac with Safari 10.0 I found out that using floats instead of ints while using the get function doesn't work in safari - but works in firefox and chrome. I know that there is no reason to use floats but I just wanted to let you know. 😄 

```javascript
function setup() {
  createCanvas(200, 200)
  fill(255, 0, 0)
  rect(0, 0, 100, 100)
  var c = get(0.12321, 0.324324, 100.43543543, 100.43543643);
  image(c, 100, 0, 100, 100)
}
```

[Codepen test](http://codepen.io/adalberth/pen/NbGbBJ)

**Comment by lmccart** [comment]
oh strange, I thought that we put a round call in there to convert floats to ints. will take a look again, thanks.

**Comment by lmccart** [comment]
aha we were rounding the x and y but not w and h!
