### ISSUE TITLE
html() and append functionality

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js#1660]
I'm noticing that with p5.dom.js I'm helping students do the following quite a bit:

```javascript
var currenthtml = elt.html();
var newhtml = "some more stuff";
elt.html(currenthtml + newhtml);
```

JQuery I believe has an `append()` function, I wonder if we should consider something like one of the following?

```javascript
elt.appendHtml('some more stuff');
elt.html('some more stuff', APPEND);
```

**Comment by lmccart** [comment]
I like the second version here, I'll add it next chance I get
