### ISSUE TITLE
Canvas resize via CSS and mouse position

### ISSUE THREAD

**Issue by molleindustria** [processing/p5.js#1661]
A canvas element can be stretched via CSS by changing the width and height of the element. That's different from the intrinsic width and height defined by createCanvas, a bit like how you can stretch images in html but their actual pixel size remains the same. It's also different from zooming via browser.

Anyway, that's the only way I was able to have typical pixelart graphics (in combination with crisp image-rendering via css and noSmooth). The idea is to use actual low res assets in an actually low res canvas and scale everything without antialias.

The problem is that the p5.js mouse position doesn't take into account the canvas size in the same way it considers its position so everything mouse-related is mismatched.

Here's an example with the issue and a possible solution. It has a centered and stretched canvas (4X). Move the mouse on the top left of the grey square, the black pixel is drawn at the p5 mouse position, the red one is drawn at the mouse position it should be.
[http://molleindustria.org/p5canvas/
](http://molleindustria.org/p5canvas/)

The example accesses the canvas dom dimensions continuously which is probably an overkill, but at the end of the day it's just a division/multiplication by the scale, which is the canvas.width / sketch width ratio.

Is it this kind of use too exotic to be implemented in p5?

    var realMouseX, realMouseY;
    var pixelScale = 4;
    
    function setup() {
      var canvas = createCanvas(64, 64);
      
      canvas.style("width", width*pixelScale+"px");
      canvas.style("height", height*pixelScale+"px");
      noSmooth();
      
      canvas.elt.addEventListener('mousemove', function(evt) {
        
        var sx = canvas.width / width;
        var sy = canvas.height / height;
        
        var rect = this.getBoundingClientRect();
        
        realMouseX =  (evt.clientX - rect.left) / sx;
        realMouseY =  (evt.clientY - rect.top) / sy;
        
      }, false);
    }

    function draw() {
      background(240);
      
      stroke(0);
      point(mouseX, mouseY);
      
      stroke(255,0,0);
      point(realMouseX, realMouseY);
    }
    
    
      

CSS on the index

    canvas {
      vertical-align: middle;
      margin: auto;
      image-rendering: -moz-crisp-edges;
      image-rendering: -webkit-crisp-edges;
      image-rendering: pixelated;
      
      padding: 0;
      display: block;
      position: absolute;
      margin:auto;
      left: 0;
      right: 0;
      /* remove these two if you don't want vertical alignment */
      top:0;
      bottom: 0;

    }

**Update:** this p5 tweak would fix it. It needs scrollWidth instead of width because the CSS box model was designed by Jorge Luis Borges:

function getMousePos(canvas, evt) {
  var rect = canvas.getBoundingClientRect();
  var sx = canvas.scrollWidth / width;
  var sy = canvas.scrollHeight / height;
  
  return {
    x: (evt.clientX - rect.left) / sx,
    y: (evt.clientY - rect.top) / sy,
    winX: evt.clientX,
    winY: evt.clientY
  };
}

**Comment by lmccart** [comment]
works for me, thanks for the fix too!
