### ISSUE TITLE
Unable to set property 'hidden' in IE10

### ISSUE THREAD

**Issue by i5ar** [processing/p5.js#1663]
There is a bug in Internet Explorer 10 (Windows 8):

**SCRIPT5007: Unable to set property 'hidden' of undefined or null reference** 
[p5.js, line 13596 character 5](https://github.com/processing/p5.js/blob/master/src/core/rendering.js#L86) 

The console is taking me here:

    // set to invisible if still in setup (to prevent flashing with manipulate)
    if (!this._setupDone) {
        c.dataset.hidden = true; // tag to show later
        c.style.visibility='hidden';
    }

The bug started when I downloaded p5.js (v0.5.4 October 01, 2016) from `npm`.
A previous version (v0.4.21 January 22, 2016) did not have this bug and worked smoothly in IE10.

Best regards.

**Comment by i5ar** [comment]
By the way, I restored https://github.com/processing/p5.js/commit/15a2b2791ee3103b98925b25f4ae1cc6c4ed9e5a?diff=split and my script now works (apparently) in IE10 with the last version of p5.js (v0.5.4).

**Comment by limzykenneth** [comment]
On [line 306](https://github.com/processing/p5.js/commit/15a2b2791ee3103b98925b25f4ae1cc6c4ed9e5a?diff=split#diff-dfe07c186488ee794e2200e24b2bd54aR306) and others, the HTML Element property `dataset` is a fairly new one and according to both MDN and Can I Use, it is not supported on IE 10. 

Not sure if there is any intention to have full support on IE 10. Have a look at #1283 for reasoning behind the change.

**Comment by lmccart** [comment]
aha thanks both for looking into this. we aim to support the latest two versions, so I think that would be IE10 and IE11. I'll take a look at this in the next few days unless someone else gets there first.

**Comment by i5ar** [comment]
It's fine, if you plan not to support IE10 I can always use version 0.4.23 which is the last one supporting it.

**Comment by lmccart** [comment]
Starting January 12, 2016, Microsoft stopped supporting all versions of Internet Explorer except the latest version: version 11, so we will likewise target just version 11 from this point forward.
