### ISSUE TITLE
Documentation for sound jump() function seems incorrect

### ISSUE THREAD

**Issue by fiebrink1** [processing/p5.js#1664]
The documentation at http://p5js.org/reference/#/p5.SoundFile/jump says "Move the playhead of the song to a position, in seconds. Start and Stop time..." but the parameters for this method are called cueTime and duration. It's not clear how to use these parameters.

**Comment by b2renger** [comment]
Yes this is confusing, 

The Start time and cueTime are the same thing here, but the second parameter is a duration and **not** a Stop time. 

I submitted an issue and a fix to p5.sound repo : https://github.com/processing/p5.js-sound/issues/149
