### ISSUE TITLE
What does this mean?  Uncaught TypeError: Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by TomTerminator66** [processing/p5.js#1668]

**Comment by lmccart** [comment]
could you post a snippet of the code that is causing this error to appear?

**Comment by krshubham** [comment]
@TomTerminator66 this error comes when you are doing something like object.toString() and in this case object is not defined. You can check this by console.log(object). If it shows undefined then something is wrong with the code where this object is being defined
Make sure to use the name of the object on which you are calling toString() in the console.log(), as here I have taken the name object for the purpose of demonstrating.

**Comment by lmccart** [comment]
I'm going to close this for now, please feel free to reopen if you can post a snippet giving more information.
