### ISSUE TITLE
Safari bug: copy outside of canvas bounderies doesn't draw the copied data

### ISSUE THREAD

**Issue by adalberth** [processing/p5.js#1671]
On Safari Version 10.0 (12602.1.50.0.10) and mobile safari - the following code doesn't work:

```javascript
function setup () {
  createCanvas(400, 200)
  noLoop()
}

function draw () {
  fill(255, 0, 0)
  noStroke()
  rect(0, 0, 200, 200)
  var img = get(0, 100, 200, 200)
  image(img, 200, 0, 200, 200)
}
```

On Chrome/Firefox it shows a rect square on the left and a half red square on the right. But on safari it doesn't show the right half red square.

[codepen example](http://codepen.io/adalberth/pen/RopQaJ?editors=0010)

**Comment by limzykenneth** [comment]
I had a look and the p5 library only accounts for when there are no overlaps between the selected region and the canvas, which it returns a single white pixel. It does not account for partial overlaps and how that is ultimately done is up to the browsers. Safari seems to be more sensitive to it and refuse to work when the requested area is out of range.

A fix might be to manually clamp the value and fill the rest of the buffer with white pixels manually, not sure if it's the most efficient solution though.

**Comment by adalberth** [comment]
Damn you Safari :(

Maybe the ref http://p5js.org/reference/#/p5/get should be updated.

> If the pixel requested is outside of the image window, [0,0,0,255] is returned. To get the numbers scaled according to the current color ranges and taking into account colorMode, use getColor instead of get.

According to your fix, the `img.pixels` array is empty in chrome and safari? So how would you do it?

**Comment by adalberth** [comment]
I found a solution. You can create an offscreen canvas, and then instead of copy outside of the canvas bounderies, you only copy the the edge, and then create the offscreen canvas to the actual copy size. Add the copied image at 0,0 then copy the whole offscreen canvas og return that. The same effect - and it works in safari. 💃

**Comment by limzykenneth** [comment]
@adalberth Yeah, I think that solution should suffice for now. I'm thinking more of a polyfill of some sort in the library itself to take care of that.
