### ISSUE TITLE
add warning about browser support for touches[] array 

### ISSUE THREAD

**Issue by JGL** [processing/p5.js#1672]
I've just made a basic demo to try experimenting with multitouch within p5.js:

https://jgl.github.io/Reactickles3/TouchDemonstration/

You can find the source code below:

https://github.com/JGL/Reactickles3/blob/master/docs/TouchDemonstration/sketch.js

I'm drawing a circle on every touch, but only one ever gets picked up. What am I doing wrong?

**Comment by hkirat** [comment]
Works fine for me.
Browser : Firefox
Android Device

**Comment by limzykenneth** [comment]
Looking at [MDN](https://developer.mozilla.org/en-US/docs/Web/API/TouchEvent/touches) it seems to be only supported on Firefox and Chrome only

**Comment by lmccart** [comment]
aha interesting. we should add a note to the documentation.

**Comment by JGL** [comment]
Is there any way to detect Safari and then use its API?

http://stackoverflow.com/questions/9680656/complex-mobile-safari-multitouch-detection
https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariWebContent/HandlingEvents/HandlingEvents.html

**Comment by limzykenneth** [comment]
Although it's not consistent nor recommended, you can try user agent sniffing.
```javascript
var ua = navigator.userAgent;
var chromeReg = /^((?!chrome).)*$/i;
var safariReg = /safari/i;

if(safariReg.test(ua) && !chromeReg.test(ua)){
  // browser is safari
}
```

Because Chrome's user agent string have "Safari" as well so need to check to make sure it's not Chrome. The regex should checkout though better test it to be sure.

**Comment by mlarghydracept** [comment]
The touches[] array is supported by Safari on mobile according to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Touch_events). It only isn't supported on Safari and IE on touch-based desktops (laptops).

**Comment by mlarghydracept** [comment]
@almchung any interest?

**Comment by almchung** [comment]
I'll add this to the next version of our error messaging system. I'll also update the documentation, like Lauren said. 

Thanks!

**Comment by lmccart** [comment]
fixed with https://github.com/processing/p5.js/pull/1905
