### ISSUE TITLE
keyIsDown() issue

### ISSUE THREAD

**Issue by LeonLenclos** [processing/p5.js#1675]
Hi. So i have this simplified code

    function setup() {
        createCanvas(100, 50);
    }
    function draw() {
        background(51);
        if (keyIsDown(RIGHT_ARROW)) {
            ellipse(33, 25, 10, 10);
            if(keyIsDown(SHIFT)){
                ellipse(66, 25, 10, 10);
            }
    }
    }

It should draw an ellipse when right arrow is down and two ellipses when right arrow and shift are down

But when i do this move : 
- press shift
- press right arrow
- release shift

the to ellipses are still there !
Then i can press  and release right arrow as many time as i want and it is like if shift was still pressed.

So i think there is a problem with the downKeys object but i quickly looked in the p5.js lib and i do not understand nothing :)

Well, thank you for all!
(And sorry my english, i'm french)

Léon.

**Comment by lmccart** [comment]
Hi, I'm not able to reproduce this incorrect behavior. When I do your sequence I see (1) nothing (2) both circles (3) just the first circle. Can you tell me what browser and device you're using?

**Comment by LeonLenclos** [comment]
Thank you for your quick reply.

I'm using Firefox 48.0.2 on OSX 10.6.8
I've just tried on Chrome and Safari and there is no problem...
I should try another way to do what i want on my program.

Thank you again.

**Comment by lmccart** [comment]
Looks like this has to do with firefox behavior with special keys:
http://www.quirksmode.org/dom/events/keys.html

I think because releasing shift while another key is down doesn't change the effect of that key that was pressed in the meantime, no keyup event is fired. Unfortunately, I don't think there's much we can do on the p5 end.
