### ISSUE TITLE
p5sound part::onStep - doesn't loop

### ISSUE THREAD

**Issue by kimon-satan** [processing/p5.js#1676]
When using onStep in conjunction with loop, the call back stops after the first iteration.

**Comment by lmccart** [comment]
could you please post a snippet of code we can use for testing and post this issue to the p5.js-sound issues: https://github.com/processing/p5.js-sound?

thanks!

**Comment by kimon-satan** [comment]
`

var click, myPart, myPhrase;
var myPat = [1,0,0,2,0,2,0,0];

function preload() {
  click =  loadSound("assets/click.mp3");
}

function setup() {


  myPhrase = new p5.Phrase('click', playClick, myPat);

  myPart = new p5.Part();
  myPart.addPhrase(myPhrase);
  myPart.setBPM(60);
  myPart.onStep(function(){
    //only seven values are outputted to the console
    console.log(frameCount);
  })

  myPart.loop();
}

function playClick(time, playbackRate) {
  click.rate(playbackRate);
  click.play(time);
}
`
