### ISSUE TITLE
DIfficult to copy Examples with iOS Safari

### ISSUE THREAD

**Issue by ricardocanada** [processing/p5.js#1677]
When I try to copy example code from https://p5js.org/examples/ in iOS Safari to use in my iPad environment, it is almost impossible to do so unless the example has an Edit button. That seems to put the code in Raw form, and then all of my selection and copy options work. Otherwise it is almost impossible to select text, and when occasionally I do get the menu with a Select All option, the menu with the Copy option does not appear. Very frustrating this morning, and I didn't get the code I wanted. I hope that the webmaster of the site will consider 1. Giving every example an Edit button or 2. GIving examples without an Edit button a Raw button the way GitHub does.

Thanks for listening.

**Comment by hkirat** [comment]
Nice suggestion @ricardocanada . A raw option is a good idea. 
However I think this issue should be opened up [here](https://github.com/processing/p5.js-website/issues) and closed over here.

**Comment by lmccart** [comment]
This issue was moved to processing/p5.js-website#91

**Comment by lmccart** [comment]
fixed with https://github.com/processing/p5.js-website/commit/a9c504409622fbf2e7809ac35f7660306f0a33d8
