### ISSUE TITLE
frameRate drop after using loadFont()

### ISSUE THREAD

**Issue by mohithingorani** [processing/p5.js#1679]
Hey all,
I am noticing that the framerate drops from 60 to 1 if I use an external font that I am loading via loadFont().
I am using the method from the documentation here: https://p5js.org/reference/#/p5/loadFont
Has anyone else witnessed this?

**Comment by mohithingorani** [comment]
Update: the variable declared for holding the new font needs to be passed with quotations into textFont() 

From P5 example: 
`var fontRegular;
function preload() {
   fontRegular = loadFont("assets/Regular.otf");

}
function setup() {
   background(210);
   fill(0).strokeWeight(0).textSize(10);
   textFont(fontRegular);    // should be textFont("fontRegular") instead?
   text("Font Style Normal", 10, 30);
 
}`

**Comment by limzykenneth** [comment]
I could not replicate the issue on my side, I am seeing ~60fps consistently. The argument passed to textFont should be the name of your variable storing your loaded font and not in quote marks (ie. a string). You should pass in a string only when you want to use fonts already installed on the user's computer.

If you can post a more complete code, along with how you log your framerate, we can have a closer look at what the cause might be.

**Comment by lmccart** [comment]
are there any errors in the console? perhaps the file is failing to load and then slowing things down when the program tries to draw text with it?

**Comment by mohithingorani** [comment]
@lmccart @limzykenneth I will post my code example tonight! I am using dat.gui for logging framerate

**Comment by mohithingorani** [comment]
On removing the  "" the code is working fine.
No drop in framerate.
