### ISSUE TITLE
strokeWeight() not working in WebGL mode.

### ISSUE THREAD

**Issue by CosmicChild** [processing/p5.js#1680]
Hi, I'm trying to build some 3D objects in the WebGL mode and I'm having some trouble with the strokes and fills.

When I use the pre-fabd objects, such as Box, Cylinder, Sphere I cannot see the lines that form the skeleton. That is, if I set the fill() to an alpha value of 0 the object disappears completely, even if the stroke() is set to 255 for instance.

Inversely, when I create my own 3D objects using the beginShape() / vertex() / endShape() technique, I can see the edges of the objetcs, colored by the stroke() function, but I cannot fill the sides of the object with the fill() function as I did in Processing.
Moreover, the strokeWeight() function seems to have no effect at all, with a static value of 1 for all lines.

Thank you!

**Comment by CosmicChild** [comment]
I have rechecked and the alpha value problems only seem to occur in HSB color mode.
The edges of the objects are still not visible in RGB mode, but the coloring in general works well.

**Comment by CosmicChild** [comment]
Solved. HSB color mode taking values in a different range..... Sorry

**Comment by mlarghydracept** [comment]
implemented with #2145
