### ISSUE TITLE
randomSeed does not reset the "previous"-variable used by randomGaussian

### ISSUE THREAD

**Issue by highyield** [processing/p5.js#1681]
The randomGaussian-function used in the current version of p5.js is using the polar form of the box muller transformation. In the implementation a boolean called "previous" is used to return a value calculated in the previous call of randomGaussian.

Now the problem with this is that randomSeed is not resetting this "previous"-variable to false. As a result in some cases the first time you call randomGaussian() after calling randomSeed(seed), you retrieve a number that has been calculated on the basis of the previously calculated seed (because "previous" is still set to true) and not on the new one.

I do not know if this is intentional or not, but it can lead to major problems when you expect to get the same random-numbers every time after you have called randomSeed(seed). This has only happened to me in rare cases however and for the bug to show up it relies on how often you call randomGaussian() before calling randomSeed()

**Comment by shiffman** [comment]
@lmccart I believe I implemented this originally and will take a look.

**Comment by lmccart** [comment]
fixed with https://github.com/processing/p5.js/pull/1697
