### ISSUE TITLE
Canvas issues

### ISSUE THREAD

**Issue by gDKdev** [processing/p5.js#1683]
I've found two issues relating to canvasses:
* When adding this to enable some specific HTML5-features:
>  meta http-equiv="X-UA-Compatible" content="IE=Edge"

 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;windowWidth and windowHeight don't work properly anymore (canvas is bigger as the screen)
* When using WEBGL-mode resizeCanvas the rendering is distorted

**Comment by moaiii** [comment]
What is the canvas width and height in px? Are you resizing?

It should also have an aspect width and height which is generally 2 * the css value, though this is not in pixels.

**Comment by lmccart** [comment]
For organizational purposes I'm going to close this for now, please reopen if you can post more details to help us debug. Thanks!
