### ISSUE TITLE
P5js mobile app not opening

### ISSUE THREAD

**Issue by Zelkins12** [processing/p5.js#1688]
I am trying to use the P5js mobile app to test ideas on my iPad if I come up with them on the go, but when the app launches it immediately closes, although it has worked once or twice out of the many times I tried. This happened on IOS 9 and 10.

**Comment by limzykenneth** [comment]
As far as I know there isn't an official p5.js mobile app. Unless there's an unknown alpha project I did not knew about, you should bring this up with the apps respective developers instead.
