### ISSUE TITLE
Changing color of canvas in setup()

### ISSUE THREAD

**Issue by jchani** [processing/p5.js#1689]
According to the reference docs, background() is supposed to be able to change the color of the canvas in setup() but it only works in draw(). Both of the following do not work: 

`function setup() {
  createCanvas(640, 360);
  background("00bfff");
}
`

`function setup() {
  background("00bfff");
  createCanvas(640, 360);
}
`

**Comment by i5ar** [comment]
Hi, I can't try it now, anyway '00bfff' is not a color, '#00bfff' is a color, or 'red'.

**Comment by jchani** [comment]
Right, my mistake. I created the example above just to illustrate the problem more clearly, but it wasn't working in my code for another reason. I've fixed it now, thanks!

**Comment by Caster101** [comment]
Can we change the color drawing on run time
