### ISSUE TITLE
Uncaught TypeError: p5.Vector.copy is not a function

### ISSUE THREAD

**Issue by chrisbamborough** [processing/p5.js#1690]
I'm getting an issue on a sketch which I previously published as was working, has there been a change to this part of the library?
Chris

**Comment by hkirat** [comment]
p5.Vector.array might help
Returns an array of size 3 with x, y and z components of the vector.

**Comment by chrisbamborough** [comment]
Thanks hkirat, using the array worked. Interestingly I used a remote version of p5.js library on cloudflare and the p5.Vector.copy() worked, I'm presuming the remote version is older and something has been changed in the most recent version.

**Comment by lmccart** [comment]
ah, can you tell me what versions you were using? they are listed in the first line of the file, or for the remote versions on cdnjs, they are part of the url path.

**Comment by chrisbamborough** [comment]
Hi Lauren, I've just realised my local file was 0.3.4! I was pointing towards a forked version on my own account which I misunderstood about how it updates. I was trying to be clever in using the development version but it backfired, sorry for the false issue. The remote version was  0.5.2.

**Comment by lmccart** [comment]
oh no problem, glad to hear it still works. :)
