### ISSUE TITLE
perspective() example in the reference section of P5.js site

### ISSUE THREAD

**Issue by LadyK** [processing/p5.js#1693]
the perspective() example in the reference section isn't working. Is there supposed to be a function definition for orbitControl()? Perhaps it utilizes the mouseDragged() function. That's my guess with reference to the comments.

**Comment by hkirat** [comment]
should work by replacing the setup function by the following
  function setup(){
    createCanvas(100, 100, WEBGL);
    perspective(60 / 180  * PI, width/height, 0.0, 100);
  }
This seems to have been changed recently, as it did work a few days back

**Comment by hkirat** [comment]
Also I think this issue should be shifted to https://github.com/processing/p5.js-website and closed over here. 
The example mentioned in the docs is fine. The one on the website has a problem.

**Comment by lmccart** [comment]
thanks, should be set now
