### ISSUE TITLE
Cannot read property .toString() in p5.js

### ISSUE THREAD

**Issue by LittleFireStudio** [processing/p5.js#1695]
On line 13283, error thrown:
`if (typeof str !== 'string') {
    str = str.toString();
  }`

It got thrown when reading text from an array.

`// Draw the grid lines
function DrawGrid() {
  // Define the sizing of the grid
  // Col settings
  ColNum    = XVals.length +1;
  ColWidth  = canvas.width / ColNum;
  // Row settings
  RowNum    = YVals.length +1;
  RowHeight = canvas.height / RowNum;
  // Draw the lines
  // Cols
  for (var i = 1; i < ColNum+1; i++) {
    // Draw the col line
    line(i*ColWidth, 0, i*ColWidth, canvas.height);
    // Draw the col label
    textSize(32);
    text(XVals[i], i*ColWidth, height - RowHeight/2)
  }
  // Rows
  for (var i = 1; i < RowNum+1; i++) {
    // Draw row line
    line(0, i*RowHeight, canvas.width, i*RowHeight);
    // Draw the row label
    text("t", ColWidth, height - RowHeight*i)
  }
}`

**Comment by limzykenneth** [comment]
I think I would need the error message and the contents of `XVals` to be able to know why the error is thrown here.

Also a tip, you can put your code in nice code blocks by putting them between three ` like the following:

```
    ```
    // Your code goes in here
    ```
```

```
    ```javascript
    // this gets syntax highlighting for javascripts
    ```
```

That way we can read your code easier and you can copy them here easier as well.

**Comment by LittleFireStudio** [comment]
It was an error that was thrown by referencing from an array in which the requested object didn't exist, sorry.

**Comment by xupertheo** [comment]
I've got the same error  when I tried to reference a property.  However I don't have any arrays in my code.
Here is my index.html file:
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Bouncy Ball - by xupertheo</title>

    <!-- p5.js -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.5.7/addons/p5.dom.min.js"></script>
    <!--script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.5.7/addons/p5.sound.min.js"></script-->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.5.7/p5.js"></script>

    <!-- my script -->
    <script type="text/javascript" src="../js/main.js"></script>
    <script type="text/javascript" src="../js/level.js"></script>

    <script type="text/javascript" src="script.js"></script>
  </head>
  <body style="margin: 0px;">

  </body>
</html>
```

My main.js file is here:
```
function windowResized() {
  resizeCanvas(windowWidth, windowHeight);
}
```

My script.js file is here:
```

var font;

function preload() {
  // font: comic sans
  //       WTTWmesssy - by What the Teacger Wants
  // http://www.fontspace.com/what-the-teacher-wants/wttwmessy
  font = loadFont("../data/font/WTTWmessy.ttf");

  //img.arrawR = loadImage("../data/img/arrowR.png");
  //img.arrawL = loadImage("../data/img/arrowL.png");
}

var level;
function setup() {
  createCanvas(windowWidth, windowHeight);

  textFont(font, 36);

  level = new Level(0);
  // level.name = "name"
  // level.by = "authour";
}

function draw() {
  background(255);

  fill(0);
  textAlign(CENTER);

  textSize(120);
  text("Level", width / 2, 120);

  textSize(300);
  text(level.num, width / 2, height / 2 + 100);

  textSize(36);
  text(level.name, width / 2, 170);
  text(level.by, width / 2, height / 2 + 200);
}
```

My level.js file:
```
function Level(_num) {
  this.num = _num;

  var path = "../data/level/";
  var ending = ".json";
  this.rawData = loadJSON(path + this.num + ending);

  this.name = this.rawData.name;
  this.by = this.rawData.by;
}
```

At last the json file is here:
```
{
  "name": "Tutorial",
  "by": "xupertheo"
}
```

I know the json file loads, so that is not the error.  If i comment out line 28 and 39 in the script.js file the error dissapears. Can anyone help me?
