### ISSUE TITLE
Rotation in WEBGL is not clockwise, but Counterclockwise 

### ISSUE THREAD

**Issue by technosalon** [processing/p5.js#1696]
Rotations in WEBGL mode should be clockwise, since P5 is on the left-hand system. However, it's been COUNTERCLOCKWISE, I think. You can see it easily by rotating a box along Z axis in a top view. The source code of "p5.Matrix.prototype.rotate" refers to "Toji 's glMatrix library" http://glmatrix.net, and both code seems to be identical, but I guess Toji's library has been on the RIGHT-HAND system, since the normal OpenGL depends on it. So, I guess it might be necessary to invert the direction of angles somewhere in p5... I hope I am wrong... Thank you in advance!

**Comment by lmccart** [comment]
p5 uses the right-hand system, so the rotation is correct. more about webgl in p5 here: https://github.com/processing/p5.js/wiki/Getting-started-with-WebGL-in-p5

**Comment by technosalon** [comment]
Very disappointed answer after 4 months. You should check your reference by yourself. 

![img_3419](https://cloud.githubusercontent.com/assets/18400681/24319212/9608891c-1158-11e7-8dd8-d64572fef37d.PNG)

If p5 is on the "left-hand" sistem, we must change the directions of the x and y axis everywhere in our source codes. You should check what happens now by yourself, since this is the basis of our codes. Therefore, I think that this issue should not be closed.

**Comment by technosalon** [comment]
Dear @lmccart This is the very sad reply after 4 months. The p5 is on "right-handed" system. You should have read your reference by yourself, before answering.

![img_3419](https://cloud.githubusercontent.com/assets/18400681/24319279/230fbc30-115a-11e7-8985-822b560d745c.PNG)

If the p5 is on the "left-handed" system, then, you must change your directions of the x and y axis. I think you should check what happens now on p5's 3D. Therefore, for the future of this lovely p5 to be extended in 3d world, you  should not close this issue, and should ask some 3d experts for what we should fix, I sincerely recommend.  I am sorry that I cannot help this anymore. All the best.

**Comment by technosalon** [comment]
Dear @lmccart this is the sad answer after 4 months. You should have read your reference by yourself, before answering.

![img_3419](https://cloud.githubusercontent.com/assets/18400681/24319335/572df62e-115c-11e7-86f0-38e42399e6d5.PNG)

If p5 is on the "right-handed" system, we must exchange the x and y axis everywhere in our source codes. Therefore, I recommend that you should not close this issue in this manner, and should ask other experts for what you should do. I am sorry that I cannot help on this anymore. I hope that you could do well. All the best.

**Comment by mlarghydracept** [comment]
@technosalon you are right that the rotation is currently on the right-handed rule. This is easy to change but maybe it makes more sense to change the documentation if the right-handed rule is being used anywhere else in the code.

Have you noticed any other kinds of transforms that don't follow the left-handed rule? I am trying to check them all out right now.

**Comment by technosalon** [comment]
@mlarghydracept hello, thanks for your help! That's what I want everyone who uses p5 in 3d to mention on this issue. I didn't test except for rotation. Since Processing is on the right-handed rule, I guess p5 also follows the same way, even though differing from other common 3d apps. I hope what you're trying to check encourage p5 users to discuss on this problem!

**Comment by mlarghydracept** [comment]
fixed with #2139
