### ISSUE TITLE
auto-generate json file with p5 function and var names

### ISSUE THREAD

**Issue by lmccart** [processing/p5.js#1699]
for syntax highlighting reference in web editor:
https://github.com/processing/p5.js-web-editor/issues/211#issuecomment-264021325

**Comment by bmoren** [comment]
+1 on this, I'd love to use this to build an atom.io syntax highlighter as well. 
It might also be nice to have key/value pair for links back to the reference pages on the website for a 'more...' link on the syntax dropdown. 

Example of Kirby CMS syntax highlighter
<img width="629" alt="screen shot 2016-12-07 at 3 33 33 pm" src="https://cloud.githubusercontent.com/assets/1385996/20987537/af64a226-bc92-11e6-85bf-2de3f0aa4560.png">

**Comment by bmoren** [comment]
I thought this was a good follow up to my previous comment:

I've just made a preliminary version of a autocomplete for atom (link below). Perhaps there is still a way the generation of this atom syntax highlighter can happen in the same way you are generating this generic json file? It could really simplify this files generation to start from a clean uniform json file which is supported.

https://atom.io/packages/p5js-snippets
https://github.com/bmoren/p5js-snippets

**Comment by lmccart** [comment]
ideally this would end up in the reference/ folder that is generated by the `grunt yui` command

**Comment by jonohayon** [comment]
So there's the `reference/data.json` file, which already has all of this information, but it's in a big mess. I'm working on some kind of an explanation to the different parts of the file at the moment

**Comment by jonohayon** [comment]
I have started writing the fields' explanation's in this [gist](https://gist.github.com/jonohayon/b059a029755f84f42b29f005323ec165)

**Comment by bmoren** [comment]
@jonohayon this is super helpful, for what ever reason I wasn't able to fond that file. Maybe because github blocks large files from displaying. I wrote my own parser to basically do this task again, but it was a bit clunky and missed a few things. Hoping this is a nice fix for my snippets for atom above! Thanks for th pointer!

**Comment by lmccart** [comment]
@bmoren the file is here: http://p5js.org/reference/data.json it's in the .gitignore so you won't see it in the repo, but it will get generated if you run `grunt yui`.

thanks @jonohayon!

@catarak this is the file to reference for the syntax highlighting. does the info in the gist make sense, and do you have everything you need?

**Comment by jtoy** [comment]
this is great for other programs that want to integrate with p5

**Comment by lmccart** [comment]
I've added a link to this gist here: https://github.com/processing/p5.js/wiki/Development#p5js-api-json-file
