### ISSUE TITLE
focused() in p5.js with sound/dom library

### ISSUE THREAD

**Issue by konstanting3410** [processing/p5.js#1706]
After playing around with sound generating on desktop/mobile browsers. I faced problem that "focused" not always can catch loosing of focus on tab.

different cases on desktop (Chrome):
no dom/sound library, tab switching -- focused seems works 9 of 10.
no dom/sound library, window switching -- focused works perfectly.
dom/sound library, tab switching -- focused catch loosing of focus one or two times
dom/sound library, window switching -- focused works perfectly (p5 tab wasn't switched before)

code used for checking(html code from empty-example):

```
var count = 0;

function setup() {
}

function draw() {
fill(255);
rect(0,0,width,height);
fill(0);
text(count,10,10);
  if (!focused) {
count++;
  } 
}
```
konstantin.

**Comment by lmccart** [comment]
this is at the browser level, and without doing some constant state checking in the background, there's not much we can do about this. the constant checking would slow things down so I'd prefer to leave as is for now, since we haven't heard much more on this topic.
