### ISSUE TITLE
can I has multidimensional support in dist()

### ISSUE THREAD

**Issue by Smilebags** [processing/p5.js#1707]
I am looking at using the dist function in finding the theoretical distance between multidimensional points much like @shiffman used in his video on object tracking by using rgb channels as dimensions in dist().

It would be great to have 4,5,6 (read n)-dimensional support in the function, allowing it to be used in more abstract ways.

I am happy to implement the change in a branch if I could have a discussion with someone about the best way to do this without interfering with the current functionality of the function. I propose the function looks at the number of (dont know the correct term) properties of the objects passed in before deciding the dimension to calculate the distance in.

I am not at home so not sure if this is how the function works but I thought I would throw the idea in there and offer my hand to get it working.

**Comment by limzykenneth** [comment]
@Smilebags Not sure how I missed this but I think this is an interesting idea. I'm not sure if multidimensional distance will be useful enough to be included in the core p5.js library but it definitely can be a useful addon library for some people.

If you are still interested in working on this I don't mind working out some of the details with you. As javascript doesn't have function overloading so yes, looking at the number of arguments passed in is one of the ways to achieve the same effect.

**Comment by Smilebags** [comment]
Yeah, I came to the same conclusion myself; it seems like after looking at the way the code works with the vectors etc, this would be more like an optional extra, but I thought I may as well offer it if I'm going to be writing it anyway.

The conclusion I came to is that it isn't going to play nice with the standard p5 vector, since that only has the 3 dimensions in it. I also noticed the distance function calls the vector subtract function.

The thing I would like to ask is what would be the best format for the object being passed in? Just an object with n properties is assumed to have that many dimensions?

**Comment by limzykenneth** [comment]
If you are thinking of creating an addon library, it would be best to not mess with the existing `dist` function unless you want to optimize the algorithm (but the exposed functionality should not change). It will be much easier to have a create a new function such as `multiDist` or `dist4D`, etc. 

Which leads onto the next point which is you have a few options:
1. Have one function that looks at how many arguments are passed to it and calculate the corresponding distance.
2. Have several functions, one for each dimension, ie. `dist4D`, `dist5D` etc. That way it's a bit more explicit and simpler to implement.

The two above are potentially very messy, ie. distance between 5D vectors will need 10 arguments.

3. You can create new vector objects that can be 4D, 5D or even nD, and write a generic `dist` function to calculate nD distance (you will need to figure out the maths here). This way you can also easily implement other multi-dimensional maths if you so wish.

**Comment by Smilebags** [comment]
After reading your comment I plan on implementing your third option as an addon library, but not sure about how to go about creating an addon library. Could you direct me to some instructions?

I will create an nDdist function which takes objects with n properties and treats them as nD. The distance calculations are relatively simple.

**Comment by limzykenneth** [comment]
Cool, you can start by looking at this page https://github.com/processing/p5.js/wiki/Libraries#creating-a-new-library

**Comment by Smilebags** [comment]
Thanks, I'll create one and get you in on the conversation once I've gotten it to a usable state.
