### ISSUE TITLE
Node.js

### ISSUE THREAD

**Issue by pwichmann** [processing/p5.js#1709]
The library looks fantastic. Thanks to all contributors!

Is there a (simple) way to run processing.js/p5 on **node.js**?
How would I have to do it?

**Comment by Smilebags** [comment]
I've only played with node a bit but I believe without checking my code, you could require it in your node js file. Something like

var p5 = require('./pathto/p5.js');

After that you should be able to use p5 functions, but you might come across some issues if you're trying to create canvases etc on the server side.

**Comment by doxanthropos** [comment]
There are two videotutorials by Dan Shiffman, that cover using p5 with node:
[Introduction to Node - WebSockets and p5.js Tutorial ](https://www.youtube.com/watch?v=bjULmG8fqc8)
and
[What is Node.js? - Twitter Bot Tutorial](https://www.youtube.com/watch?v=RF5_MPSNAtU)

**Comment by limzykenneth** [comment]
@pwichmann Well, it depends on what you mean by running p5.js on node.js. The important difference here is p5.js is mainly a front end library ie. it's meant to run on users' browsers. While node.js is a server environment that uses javascript as its implementation language, it essentially has Chrome's javascript engine V8 and some other C++ bindings to make it work.

The main thing that concern us here is that while on browsers rendering a canvas is pretty intuitive, on a node.js server you don't get a target canvas to render to. If for example you just want to use some utility functions like the math functions then you can do what @Smilebags suggest but often you are better off just using native JS functions in that case.

If you wanted to render the canvas somehow, you will have to either use something like nw.js to make it a native app or render it headless to a remote canvas which I'm not sure myself how to do it.

As I mentioned in the beginning, it all depends on what you want to do with p5.js in node.js

**Comment by lmccart** [comment]
Thanks all for the resources and explanation. I'd like to request that we continue this discussion on the forum, as it's easier for future users with the same question to search the archive and find these answers again. Thanks!
