### ISSUE TITLE
loadPixels() does not work with PGraphics in WEBGL mode

### ISSUE THREAD

**Issue by CosmicChild** [processing/p5.js#1712]
When I call a pg.loadPixels() function, on a PGraphics object created on WEBGL mode, such as this:

function setup() {
  createCanvas(500,500)
  pg = createGraphics(500,500,WEBGL)
}

function draw() {
  pg.loadPixels()
}

I get this error:

20090: Uncaught TypeError: undefined is not a function

When using the P2D renderer the loadPixels() / updatePixels() functions work smoothly

**Comment by limzykenneth** [comment]
@CosmicChild It's a known limitation of WEBGL mode at the moment, have a look at this issue: https://github.com/processing/p5.js/issues/1502 

It's been awhile not, but I'm not sure what the progress on its implementation is though.

**Comment by mlarghydracept** [comment]
Closed with #2074
