### ISSUE TITLE
Firefox - Slow handling of endShape in createGraphics

### ISSUE THREAD

**Issue by chrsmlls333** [processing/p5.js#1716]
Having an oddly slow framerate (0.8 fps) on two different Windows computers when drawing shapes made up of curveVertex points to an offscreen canvas. endShape is calling a doFillStrokeClose function that takes a lot of time specifically when drawing to a buffer created with createGraphics(), I can't get deeper into the performance console than that so I believe it must be the culprit. Slows down the entire firefox UI and everything.

Problem Test: [Aurora 3](http://www.chriseugenemills.com/projects/aurora-3/)
Control (similar algorithm drawing directly to canvas):  [Aurora 2](http://www.chriseugenemills.com/projects/aurora-2/)

Both run regularly in Chrome. Originally I thought this was related to my computer and the webgl/canvas graphics card issue I have been having [here](https://github.com/mrdoob/three.js/issues/10184) but its most definitely unrelated because I was able to replicate on another machine.

**Comment by mlarghydracept** [comment]
@chrsmlls333 Hi thanks for reporting the issue. The URL for the problem test isn't working. Are you still having this problem in Firefox? If so, could you put the link back up or post the code here?

**Comment by chrsmlls333** [comment]
@mlarghydracept Apologies! Here is the updated link: [Aurora 3](http://chriseugenemills.com/projects/aurora-3-holy-generator/)

**Comment by kjhollen** [comment]
@chrsmlls333 thank you! is there a non-minified version of the code that you could share with us?

the speed for immediate mode has been improved a lot this summer! in Firefox it's about half as fast as it is in Chrome, but it should still be workable. I am hopeful this will be resolved when we merge the Web GL work from google summer of code.

**Comment by kjhollen** [comment]
fixed with #2166.
