### ISSUE TITLE
Suddenly “this.audiocontext.createScriptProcessor is not a function” error in p5js-sound

### ISSUE THREAD

**Issue by StupidUserSmartAnswer** [processing/p5.js#1717]
I have a website, that should play mp3 file after clicking on a logo. Problem is with this [line](https://github.com/processing/p5.js/blob/master/lib/addons/p5.sound.js#L2208). Without any reason after two years of proper work it started to give this error. 

> Uncaught TypeError: this.audiocontext.createScriptProcessor is not a function.

I found out that it works in firefox and on some computers with older versions of chrome. How to solve this problem?

**Comment by max0410** [comment]
I found the problem, I will be putting in a PR to fix it.

**Comment by lmccart** [comment]
@max0410 thanks! please submit the PR to this repo: https://github.com/processing/p5.js-sound/blob/master/src/amplitude.js

**Comment by max0410** [comment]
No problem, will do

**Comment by max0410** [comment]
I'm really sorry for this, but looking back to my code, it seems that it  must be reverted. What that code did was to check if the browser supported `audiocontext.createScriptProcessor`, and if it didn't, it would make the function, and equal it to `audiocontext.createJavaScriptNode`, and my code broke that functionality. 

So I am pretty sure that my code is wrong, but It may not be. As I'd have to test the code on a _very_ old browser, and see if it actually helped @StupidUserSmartAnswer. In the meantime, I'll see if can find another solution.

**Comment by lmccart** [comment]
this issue is covered over in the p5.js-sound repo, let's continue working on it there:
https://github.com/processing/p5.js-sound/issues/154
