### ISSUE TITLE
Problem with unused library functions

### ISSUE THREAD

**Issue by hcvazquez** [processing/p5.js#1718]
My name is Hernan; with a group of colleagues we are conducting a research about unused code present in dependencies of JavaScript projects. We call this functions, UFF (Unused foreign functions). We found that in most projects there exist a great amount of UFF that are being included in the final bundle. 
 
In the case of p5 (v 0.5.3) our tools detected approximately 301 unused function in dependencies. Removing those functions, the size of p5 bundled could be reduced at least 26% (All tests passed).  I’m attaching the reduced version of your project. 
[p5(optimized).txt](https://github.com/processing/p5.js/files/671142/p5.optimized.txt)

 
I’ll be very grateful if you can answer me the following questions:
-Did you were aware of the existence of these unused functions in your projects?
-Do you think that this is a problem? 
-Do you think that can be useful a tool for deal with this kind of problem?

Thanks in advance.

Cheers,

**Comment by lmccart** [comment]
Interesting thanks for sharing. 

-Did you were aware of the existence of these unused functions in your projects?
> no
-Do you think that this is a problem?
> I don't know?
-Do you think that can be useful a tool for deal with this kind of problem?
> I don't know enough about this to comment.
