### ISSUE TITLE
quadMode(CENTER) is not defined

### ISSUE THREAD

**Issue by alphydan** [processing/p5.js#1719]
I was hoping that just like it's possible to use:

`rectMode` as described in https://p5js.org/reference/#/p5/rectMode
it would be possible to call it for other shapes, for example:
`quadMode(CENTER);` 

So for example, with code [like this](https://gist.github.com/alphydan/9876a6304181a1430dee75e2f99290b7), I can create:
![circle_of_squares](https://cloud.githubusercontent.com/assets/1044390/21463380/d26e4ba6-c93e-11e6-8cc4-3441f2803371.png)

But if I try to do [the same thing](https://gist.github.com/alphydan/d833c65f10fdd728f947c21a9dd6b138) for a quad, it doesn't work:
![circle_of_quads](https://cloud.githubusercontent.com/assets/1044390/21463410/4681a1dc-c93f-11e6-97ca-a1798f4e6d05.png)

Is there an obvious way to do this rotation that I'm missing? Otherwise, is `quadMode` a future feature?
Thank you for `p5.js` and for your time!

**Comment by lmccart** [comment]
The best way to do this is to use translate() to move the coordinate system, rotate() to rotate the coordinate plane around (0,0), then draw the shape. Consider this example:

```javascript
translate(50, 50);
rotate(PI/3);
quad(-25, -25, -25, 25, 25, 25, 25, -25);
```

Now try changing PI/3 to any angle and you can see the shape rotates about it's center point. Hope that helps! This is a really condensed explanation, but a longer version is in the chapter on transforms in the getting started book...or this [tutorial](https://processing.org/tutorials/transform2d/) from the processing site covers it as well (you have to port some of the examples from processing to p5.js, but it follows the same logic in terms of transforms).

**Comment by lmccart** [comment]
I should mention, if you want to do this for multiple shapes like you have in your example, you can use push() and pop() to reset the coordinate system after each shape has been transformed. Something like this:

```javascript
push();
translate(50, 50);
rotate(PI/3);
quad(-25, -25, -25, 25, 25, 25, 25, -25);
pop();

// repeat for next quad
```
