### ISSUE TITLE
Implement wireframes with noFill() / stroke()

### ISSUE THREAD

**Issue by joncodo** [processing/p5.js#1720]
https://github.com/processing/p5.js/issues/1093

When you use `WEBGL` in createCanvas(), you can not use noFill() or stroke()

```
var a = 0;

function setup() {
  createCanvas(windowWidth, windowHeight, WEBGL);
  translate(width / 2, height / 2);
}

function draw() {
  background(51);

  rotateX(a);
  rotateY(a);
  a += 0.01;

  noFill();
  stroke(255);

  box(200);
}
```

Will add unit test and the like. Thanks for the cool library! 👍

**Comment by lmccart** [comment]
this is covered in https://github.com/processing/p5.js/issues/1680 and https://github.com/processing/p5.js/issues/1703
