### ISSUE TITLE
WEBGL: Rotating the camera?

### ISSUE THREAD

**Issue by 343N** [processing/p5.js#1721]
Sorry if this is obvious, but I can't find out how to rotate the camera when using p5js in WEBGL. I can move the camera fine (with camera(x,y,z) of course) but how would I go about rotating it?

**Comment by joshuaalm** [comment]
Based on my understanding, you would need to rotate based on the motion of
the dragged mouse or touchscreen gesture (or whatever you're using to tell
the camera to move, including scripted instructions)  If you have a library
that can handle manipulating a camera object, you will be able to rotate
that, but if you're using processing to implement an engine you may need to
rotate the scene instead.

**Comment by 343N** [comment]
Ah, so p5.js webgl doesn't come with functions to rotate the camera itself? alright, I'll see what I can do. (but wouldn't this mean i'd have to change 3d libraries completely? or are cameras in WebGL a universal thing?)

**Comment by joshuaalm** [comment]
Looks like there is a function camera(x,y,z) that allows you to move what
would actually be the viewport.

http://p5js.org/reference/#/p5/camera

**Comment by 343N** [comment]
yes but i'm specifically talking about rotating the camera so that the viewport can view objects outside of the camera's field of view

**Comment by joshuaalm** [comment]
Looks like the p5.js library doesn't implement camera operations the way
you might expect three.js for example, to do. This isn't surprising as
Processing has always been about pure graphics operation. That means you'll
have to do the necessary transforms on the objects in your scene in order
to make it appear the camera is moving.

https://processing.org/tutorials/p3d/

**Comment by 343N** [comment]
Ah, alright. Thanks for the clarification.

**Comment by saitogroup** [comment]
So... there is no function you can use to just rotate the camera around an axis e.g.?

**Comment by Spongman** [comment]
the `camera()` function takes three vectors:
- the camera position
- the point to look at
- the 'up' vector for the camera

you should be able to use that to move a camera around and have it point to whatever you want.

**Comment by saitogroup** [comment]
Right, I understand that, but then how would one generate the necessary xyz coordinates for a rotation; have no understanding of how to do that... Seems like you can't just rotateX on a camera...

**Comment by kjhollen** [comment]
@saitogroup maybe try orbitControl() if you want to rotate the camera with the mouse? it's a little limited in what it does, but it's something.

I think there's room for a rethinking of the camera rotation API. the Processing API aimed to match gluLookAt, which I also matched here, but I think other web gl toolkits express the API a little differently. I've been thinking about our 3D work as a bridge to other web gl toolkits, so I think it's appropriate to prioritize that over an exact API match with Processing.

**Comment by saitogroup** [comment]
w/orbit control; conceivably could you replace mouseX/Y/Z w/an incrementing int or float? @kjhollen
