### ISSUE TITLE
Intellisense?

### ISSUE THREAD

**Issue by Stephanevg** [processing/p5.js#1722]
Hi,

Can anyone tell me if there is an IDE that has intellisense for P5.js ?

thx

**Comment by DonKarlssonSan** [comment]
Maybe this can help:
#1339

I love Visual Studio Code, but I have not tried getting Intellisense fro p5.

**Comment by Stephanevg** [comment]
Thanks for pointing that one out. It is actually unclear for me how I should install it, and couldn't find a clear how to guide.

I just noticed that the editor is deprecated, and is not supported anymore and that an online version will be available this year... That is to bad, as I don't have access to the internet each time I want to write code (EG, train /plain) and thought that a downloadable version of the editor was a good idea. The only thing that it was lacking was intelisense support. To bad :(

**Comment by lmccart** [comment]
I don't know of any editors currently that do this, though there is an open issue to create a json file with function names that would help with creating an inteliisense file: https://github.com/processing/p5.js/issues/1699. We hope to build this into the web editor in the future.
