### ISSUE TITLE
Use CodePen for getting started

### ISSUE THREAD

**Issue by DonKarlssonSan** [processing/p5.js#1726]
Hi,

Warning: I'm biased since I am an avid CodePen user.

Since the purpose of p5.js is "make coding accessible", I think the Get Started guide could be improved a bit by also documenting how you can use CodePen when coding with p5.

Right now, Sublime Text 2, Brackets and Atom are mentioned in the guide. But I think a web based code editor/development environment is even easier to get started with. Another big advantage of removing the barrier for publishing p5 sketches online is that it much more fun if you can share your work with others!

CodePen has an "API" for creating a Pen on the fly with options for setting it up just the way you want it. With the `js_external` parameter you can add a reference to p5 and with `js` you add the example code. Details:
 
https://blog.codepen.io/documentation/api/prefill/

I imagine this flow:
 
 * A user reads the Get Started guide
 * The user clicks a "Create Sketch on CodePen"
 * p5 is added as a reference, some sample js code is added 
 * The user can start experimenting immediately on CodePen

This could even be used for all the examples. The example code is already there, just add some sort of template that adds a "Experiment on CodePen" button to each example.

Mozilla Developer Network has already started doing this. Look at this example:
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Animations/Using_CSS_animations
They also provide a link for creating a jsfiddle.

If you think this is a good idea I could start looking into details and start working on a pull request.

**Comment by max-devjs** [comment]
Would "embedded Pens" (/ JSBin / whatever..) be a bad idea?

**Comment by shiffman** [comment]
I didn't realize you could set up an automatic template with CodePen. I agree it's a nice option, and could be useful to point people towards it especially while we transition between supported editor projects.  @lmccart I'm happy to work on this and could add a note to the p5.js-editor repo, and possibly a link from http://p5js.org/get-started/?

**Comment by lmccart** [comment]
I think that's a great idea!

**Comment by shiffman** [comment]
Great!  @DonKarlssonSan I think maybe adding a link to each and every example is too much at the moment (we have our own web editor in the works), but I think a link to create a sketch on CodePen could go in one or more of these places:

* [p5.js editor repo README](https://github.com/processing/p5.js-editor/blob/master/README.md)
* [Getting Started page on website](http://p5js.org/get-started/)
* [Download page on website](http://p5js.org/download/) (likely not to be called download at some point when we link the new web editor).

Let me know what you have interest in working on and I'm happy to help out too.  I have a "PRO" CodePen account should that be of any help.

**Comment by mithru** [comment]
Not entirely sure if this is the ask. I made [this](https://codepen.io/mithru/pen/XdNQZb) a while back as a template for my p5 experiments on codepen before I discovered the alpha editor. 

Also, I just noticed codepen released 'Projects'. I can work on creating a template codepen project and link it to where @shiffman suggested, but I want to make sure this is what the suggestion/ask is.  

One question/doubt that I have is about linking the latest version of p5js - is that something that we'd have to change manually every time there's an update, or is there a more efficient way that I'm not aware of?

**Comment by limzykenneth** [comment]
@mithru For platforms like codepen, there is not easy way to update library versions that I know of. If you have a look at Settings > Javascript > Quick-add, you will see a list of popular libraries, that could be a way to easily add and update library versions but whether a certain library is included in that list or not is entirely up to codepen.

**Comment by DonKarlssonSan** [comment]
@limzykenneth When dynamically creating a new Pen on CodePen with their API you can add whatever external js libraries you want to with the `js_external` parameter.

You can do the same thing manually by going into the Pen Settings and paste an URL to an external js lib. In other words: you are not limited to the few ones that CodePen decided to put in the drop down menu.

**Comment by DonKarlssonSan** [comment]
And a clearification:
I'm proposing to have a "Create Sketch on CodePen" for a few select examples in the Get Started guide. It would take the js code for the current sketch and automatically create a Pen.

Example:
"Your First Sketch" has the following code:

````
  function setup() {
  
  }

  function draw() {
    ellipse(50, 50, 80, 80);
  }
````


Pressing the "Create Sketch on CodePen" button would place that code in a new Pen on CodePen and add a reference to p5.js. So now the user has it's own live sandbox environment and can go off experimenting.

**Comment by limzykenneth** [comment]
@DonKarlssonSan Yeah, I'm aware that you can just add a library link with codepen, just answering @mithru question about updating library version easily on codepen

**Comment by calpa** [comment]
I think codePen or JSFiddle are useful for playing p5.js in sandbox mode, but personally I prefer codePen as it has a better UI...

@DonKarlssonSan MDN has implemented the code as a template, for example, the `openSample()` will clean CSS Code and use it with `openCodepen()`, then submit a form to https://codepen.io/pen/

In this way, the new comers may find it is better to implement the starter template. Here is some code obtained from https://developer.cdn.mozilla.net/static/build/js/wiki.7114338e4daa.js
```
function openCodepen(title, htmlCode, cssCode, jsCode) {
  var $form = $('<form method="post" action="https://codepen.io/pen/define" class="hidden">' + '<input type="hidden" name="data">' + analytics + '<input type="submit" />' + "</form>").appendTo(doc.body);
  var data = {
    title: title,
    html: plug + htmlCode,
    css: cssCode,
    js: jsCode
  };
  $form.find("input[name=data]").val(JSON.stringify(data));
  $form.get(0).submit()
}

function openSample(sampleCodeHost, section, title, htmlCode, cssCode, jsCode) {
  var cssCleanCode = cssCode.replace(/\xA0/g, " ");
  mdn.analytics.trackEvent({
    category: "Samples",
    action: "open-" + sampleCodeHost,
    label: section
  });
  if (win.ga)
    ga("set", "dimension8", "Yes");
  if (sampleCodeHost === "jsfiddle") {
    openJSFiddle(title, htmlCode, cssCleanCode, jsCode)
  } else if (sampleCodeHost === "codepen") {
    openCodepen(title, htmlCode, cssCleanCode, jsCode)
  }
}
```
