### ISSUE TITLE
beginShape is extremly slow with WEBGL

### ISSUE THREAD

**Issue by parnordlund** [processing/p5.js#1727]
Hi,

I'm using beginShape/endShape in WEBGL and its just extremly slow. I can draw 10-15 triangles before it starts to lag down to 20fps. 

Are there any known issues with beginShape and WEBGL atm? I can draw 100 3d boxes without any problems but a single triangle suck out all the juice :)

**Comment by kjhollen** [comment]
Woops, I didn't see this and accidentally opened #2020 for this issue. I think this was resolved in #2031, so I'll close it, but let me know if the problem persists and I'll take another look.
