### ISSUE TITLE
Drawing line on touch screen doesn't work in v0.5.5

### ISSUE THREAD

**Issue by jacorre** [processing/p5.js#1733]
Please take a look at my [pen](http://codepen.io/jacorre/pen/woyNXG?editors=0010) using a touch screen.

In the pen settings for Javascript, if you use version 0.5.4 for p5.js, drawing a line on a touch screen works fine. If you change the version to 0.5.5, you'll see that no line is drawn.

**Comment by scenaristeur** [comment]
confirmed on surface pro. 
with the surface Pen, there is no pb, but with the finger : works in 0.5.4 and not in 0.5.5 (the version can be changed in "Setting" menu)

Have you tried with the "touch events ? "
https://p5js.org/reference/#/p5.Element/touchStarted
https://p5js.org/reference/#/p5.Element/touchMoved
... ?

**Comment by lmccart** [comment]
this has been fixed (the problem 0.5.5 is touchX/Y is not getting updated), it will be in the next release coming later today!

**Comment by jacorre** [comment]
Thank you!
