### ISSUE TITLE
Correct use of p5.js with ES6?

### ISSUE THREAD

**Issue by albertovilva** [processing/p5.js#1734]
So I set up a little starting project with Webpack interpreting ES6 with babel.

Im loving the way to work but I have a question. For example in this sketch:

<img width="595" alt="screen shot 2016-12-31 at 02 11 04" src="https://cloud.githubusercontent.com/assets/8507571/21575041/3fe8eb84-cf00-11e6-8338-32cd5f104f50.png">

As you can see I must prepend "p5" to all functions, since its not in the global namespace, is there a way to avoid this for the shake of cleaner and easier to write code?

**Comment by lmccart** [comment]
I'm sorry, I don't think there is at this time, unless you use p5 in ["global mode"](https://github.com/processing/p5.js/wiki/p5.js-overview#instantiation--namespace)

**Comment by designbyadrian** [comment]
@albertovilva how is your sketch function triggered? How is setup() and draw() called?

**Comment by owlsketch** [comment]
@designbyadrian his code resides in this repository: https://github.com/albertovilva/p5-tests.
His sketch is found [here](https://github.com/albertovilva/p5-tests/blob/master/src/js/sketch.js), ad it is called in [app.js](https://github.com/albertovilva/p5-tests/blob/master/src/app.js)
