### ISSUE TITLE
How to resize canvas with background image size?

### ISSUE THREAD

**Issue by JakubAksamit** [processing/p5.js#1736]
Hi guys, 
I'm drawing canvas, then user chooses image for background and I would like to resize canvas size to match size of the image. How can I do that?

**Comment by lmccart** [comment]
you can use the resize canvas function, something like this after the image has been loaded:

```javascript
resizeCanvas(img.width, img.height);
```

the [forum](https://forum.processing.org/two/) is a good place to post questions like these. :)

**Comment by JakubAksamit** [comment]
Thank you!


W dniu 2017-01-01 o 23:25, Lauren McCarthy pisze:
