### ISSUE TITLE
Whats better p5 dom or jquery for you?

### ISSUE THREAD

**Issue by monikasharma1999** [processing/p5.js#1737]
I am just asking :P I want to make websites and stuff. 
![abbrngmn_700wa_0](https://cloud.githubusercontent.com/assets/24872726/21593520/05f81da6-d13e-11e6-8cde-1f4a0d2c8ca9.gif)

**Comment by lmccart** [comment]
It really depends on what you find more comfortable for yourself and what you're trying to do. p5.dom has a basic set of DOM methods to create and manipulate HTML elements. jQuery has a much more extensive set of features. If you are doing a primarily HTML based project and need to do a lot of intensive DOM manipulation, I would recommend jQuery. If you are just trying to add in some DOM integration to a canvas-based sketch, p5.dom might make more sense.

For future reference, the [forum](https://forum.processing.org/two/) is a great place for questions like these and longer discussions.
