### ISSUE TITLE
Sound recording will not work in 2017 with p5.js?

### ISSUE THREAD

**Issue by mmsmodell** [processing/p5.js#1739]
Dear Developers,

I have been using this very nice feature of P5.js which allowed me to record sound in browsers. However, it seems some key functions will be removed in 2017.

Chrome displays the following message on the Consol, even using P5 JS Example for Recording sounds - 

'MediaStreamTrack.getSources is deprecated and will be removed in M56, around January 2017. See https://www.chromestatus.com/features/4765305641369600 for more details.'

Will there be a workaround to handle this problem? If so, what and how will I have to modify in the code to work again?

Ps. It would also be great that the recording source (Primary Mic, LineIn, Optical In, Webcam Mic, Headset mic), etc, all other such sources would be easily listable-selectable for the Client and there would be a very simple example on how to let the User select the source, maybe included in the 'Recording and Saving / Playing Sound' example on P5 Js's main Examples page.

Awaiting Your kind reply, and appreciate all Your work!
-Gergely Nagy / Hungary

**Comment by bmoren** [comment]
It seems like we will need to replace / rewrite the part of the p5.sound lib that uses the getSources, and instead use the enumerateDevices. I'm guessing that this will also need to be executed on secure origins in the future (read: HTTPS instead of HTTP)

https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/enumerateDevices

There could be some cross browser issues here too that I'm missing, I'm assuming from your comment that you are using chrome, can you possibly test on some other browsers too to see if you replicate the error? I'm pretty sure getSources wont work in firefox, so this might be a good fix to do anyway.

**Comment by mmsmodell** [comment]
Hi, I tested my audio webpage (using p5.js) using Firefox and Microsot Edge as well, and to my surprise, they were working - they recorded the audio and saved it, it was all perfect. Yeah, for Chrome I will need HTTPS, but I guess it's not a developer issue - it's the decision of Chrome, Firefox, etc.

But from the comments left by Google at https://www.chromestatus.com/features/4765305641369600 it seems that there's consent among Chrome Firefox and Ie/Edge to cancel the support for MediaStreamTrack.getSources - so I guess the p5.js recording code will not work in either browsers very soon (Google cite an update expected in January 2017, so pretty much any moment now).

I would wery much like to continue using p5.js, where/hown shoud I address or kindly ask the core developers to handle this issue, if they have the capacity to do so? Really appreciate their efforts.

**Comment by bmoren** [comment]
this is the place to address the 'core team' (using that term very loosely here), I'm sure lauren or others have seen this issue. Perhaps you should make a fork and have a try at it? p5 is about [inclusiveness and getting everyone on board](http://p5js.org/community/). It'd be great if you gave it a try!

**Comment by lmccart** [comment]
yep thanks all! I'm aware of this one and hoping to look into it very soon. :)

**Comment by mmsmodell** [comment]
Hi Guys, Boren, Lauren,

Yes You are right, and if I knew anything more about Javascript/Client side
programming other than how to insert a few, already written examples &
lines to my webpage (for every of which I know covers 1000s of lines of
real code & probably 100s of hours of dedicated work, free of charge, for
the good of the community) - I would.

But the fact is that I am simply underqualified to do so myself - that's
why I was asking if core team members maybe had the capacity to do so. I
know I can not 'request' anyone to do it for me, except that maybe they
would be doing it anyway for the whole commmunity of others who simply
don't have the knowledge (like me).

So - You are perfectly right, and I would be willing to dedicate the time,
but for me it would 1st mean learn JavaScript and in-browser programming ;)

I am very, very grateful if some of You can fix this issue and I can
continue to use p5.js for simple in-broser sound recording ;)

Thanks,
-Gergely / Hungary

2017-01-15 19:07 GMT+01:00 Lauren McCarthy <notifications@github.com>:

**Comment by lmccart** [comment]
fixed with https://github.com/processing/p5.js-sound/pull/160, it will be in the next release of p5.sound.js

**Comment by mmsmodell** [comment]
I am very grateful, thank You very much for the fix! I hope to update my webpage ASAP.

Yours,
-Gergely / Hungary

**Comment by lmccart** [comment]
if you need it sooner than the next release, there's a copy here: https://github.com/processing/p5.js-sound/blob/master/lib/p5.sound.js

**Comment by mmsmodell** [comment]
Could I have ever wished for more? ;) I already start feeling ashamed for
forcing this issue to be solved instead of learning Javascript coding at a
reasonalble level myself... Will test it on all browsers and I will let You
know the results! Thanks again!

2017-01-19 3:19 GMT+01:00 Lauren McCarthy <notifications@github.com>:

**Comment by zahaRala** [comment]
Dear Developer
So, I am using Chrome and I think it still don´t work. Everythink I´ve seen in videos was very good, but in Chrome and Firefox it still don´t work : 

`<script src="http://adi.nicolaiweitkemper.de/p5.sound.js"></script>

<h2 id="text"></h2>

<script>

var mic;

function setup() {
  mic = new p5.AudioIn();
  mic.start();
}

function draw() {
  var vol = mic.getLevel();
  document.getElementById('text').innerHTML = vol;
}

</script>
`

 - but the example of  AudioIn it was working. And in this code, it´s working one time, but the continuoues don´t. 

`<script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.4.5/p5.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.4.5/addons/p5.dom.js"></script>
	<script src="../p5.speech.js"></script>

    <h2 id="result"></h2>

  <script>

	var myRec = new p5.SpeechRec("de-DE"); // new P5.SpeechRec object
	myRec.continuous = true;
	myRec.onResult = showResult;
	myRec.start();

  function showResult() {
   document.getElementById('result').innerHTML = myRec.resultString;
  }

  </script>`

If here´s any coding error, which I could fix, please tell it to me!
PS: Is this webpage (http://ability.nyu.edu/p5.js-speech/) still the latest copy of the library?

**Comment by zahaRala** [comment]
My recording of the sound volume doesn´t work in chrome on PC, on my smartphone and my normal browser on my phone.
I just evven don´t get a request to use the audio.

So, I tryed it with this code : 

`http://adi.nicolaiweitkemper.de/Lautsst%C3%A4rke%20TEST.html`
