### ISSUE TITLE
createCapture and image size

### ISSUE THREAD

**Issue by Holiehandgrenade** [processing/p5.js#1741]
So this is kind of the opposite issue that Dan found here in this video:
[P5 drawing with pixels](http://www.youtube.com/watch?v=bkGf4fEHKak&t=5m50s)

When using video from createCapture with image(), the sizing is off. (The replicated image is too large).

<img width="298" alt="screen shot 2017-01-03 at 8 24 08 am" src="https://cloud.githubusercontent.com/assets/15835877/21609416/4c5429e6-d190-11e6-950e-0b7a7f1f64e7.png">
<img width="629" alt="screen shot 2017-01-03 at 8 24 23 am" src="https://cloud.githubusercontent.com/assets/15835877/21609418/4e02dada-d190-11e6-9178-3b2df30cea79.png">

I found applying any tint scaled it back down to the canvas size. (I used a white tint since that would replicate the same image)

<img width="301" alt="screen shot 2017-01-03 at 8 24 42 am" src="https://cloud.githubusercontent.com/assets/15835877/21609424/53893026-d190-11e6-903b-e5881e744a87.png">
<img width="638" alt="screen shot 2017-01-03 at 8 24 51 am" src="https://cloud.githubusercontent.com/assets/15835877/21609426/57684b64-d190-11e6-9273-156f408372a5.png">

I was using Chrome 55.0.2883.95 on a mac with retina display

Thank you for all of your work. I'm exploring the framework and it's super fun!

**Comment by MichaelPaulukonis** [comment]
@lmccart Should this remain closed, or should the following comments be deleted?

https://github.com/processing/p5.js/blob/a9c0627a4ee2ebb7f28743b5a685b11fc715e4c6/src/image/loading_displaying.js#L269

That code also references https://github.com/processing/p5.js/issues/1673 which has been closed as well.

**Comment by lmccart** [comment]
@MichaelPaulukonis this has been resolved as far as I can tell, and the comments should be removed
