### ISSUE TITLE
image() function possible irregularity

### ISSUE THREAD

**Issue by Alonsoup** [processing/p5.js#1742]
Hi! Please excuse me if this is a waste of your time. I’m a beginner, this is my first issue and I may be wrong.

When I try using the image() function within setup(), the image doesn't get printed in the canvas:

```javascript
function setup() {
  createCanvas(200, 200);
  background(200);

var img = createImg('tao.jpg');
image(img, 0, 0, 200, 200);
}
```

But when I place it inside another function, it does:

```javascript
var img;
function setup() {
  createCanvas(200, 200);
  background(200);

var button = createButton('Print');
button.mousePressed(printImg);
img = createImg('tao.jpg');
}

function printImg() {
  image(img, 0, 0, 200, 200);
}
```

Also, in  [one of his tutorials](https://youtube.com/watch?v=o4UmGrPst_c&feature=youtu.be&t=19m10s), Daniel Shiffman was able to call the hide() function on img to hide the DOM element and then use img as an argument for image(), but, when I do, the image isn’t displayed in the canvas.

```javascript
var img;
function setup() {
  createCanvas(200, 200);
  background(200);

var button = createButton('Print');
button.mousePressed(printImg);
img = createImg('tao.jpg');
img.hide();
}

function printImg() {
  image(img, 0, 0, 200, 200);
}
```
Maybe image() is only supposed to work with objects generated by preload()?

Thank you very much for your time and feedback!

**Comment by limzykenneth** [comment]
```javascript
function setup() {
  createCanvas(200, 200);
  background(200);

  var img = createImg('tao.jpg');
  image(img, 0, 0, 200, 200);
}
```

The line `var img = createImg('tao.jpg');` should have been `var img = loadImage('tao.jpg');`. There's not `createImg` but there is `createImage` which creates a HTML `<img>` element where `loadImage` loads the image data into the variable which can then be drawn onto the canvas. You might also want to use `loadImage` in the preload function.

```javascript
var img;
function preload(){
  img = loadImage('cat.jpg');
}

function setup() {
  createCanvas(200, 200);
  background(200);

  image(img, 0, 0, 200, 200);
}
```

`.hide()` will require that you have included the p5.dom.js library as well so just make sure you have included it in your HTML file kinda like so: `<script src="./lib/addons/p5.dom.js"></script>`

**Comment by lmccart** [comment]
thanks @limzykenneth!

**Comment by Alonsoup** [comment]
Thanks for the answer, @limzykenneth !
 
At the time I was trying not to use loadImage() because Chrome wouldn’t let me access the image that way (CORS policy. Had to run a local server).

Using loadImage (and a local server) solves my problem, but I still think there’s something weird. createImg does exist. I was able to use it, but not within the setup function.
