### ISSUE TITLE
.input(): example code error

### ISSUE THREAD

**Issue by alamius** [processing/p5.js#1747]
On the page 
  [http://p5js.org/reference/#/p5.Element/input](url) 
and on 
[http://p5js.org/reference/#/p5/createInput](url) 
the example code (that might have been used elsewhere too) contains 

> console.log('you are typing: ', this.value());

with "this" being an input element, but with the comma, the .log method with its one argument ignores the input element and just prints the string every time. It should be 

> console.log('you are typing: ' + this.value());

which works fine always because both are strings.

**Comment by limzykenneth** [comment]
Both values are showing up for me on Safari and Chrome but I do agree with your point of using `console.log('you are typing: ' + this.value());` instead as string concat should really just using string concat, the comma notation should be more for logging multiple items at the same time.

**Comment by alamius** [comment]
I've got this snippet for you, coming from my p5.js software itself,
displaying the code
(not all of it, but I took it over and changed nothing despite adding
function draw(){} at the end),
the small "result web page" window displaying the input box
and the console with all the output.
[image: Inline-Bild 1]

Yes, it works fine in the browser as the following snippet shows for my
computer too:
[image: Inline-Bild 2]
​So I don't know ​whether it's neccessary to be able to see the full output
of the .log() in the software as in the browser, as it presumably won't be
used to interact with users at all.

I'm sorry for grammar or ortography mistakes.

Thanks for your attention
Anton Obersteiner


2017-01-07 8:29 GMT+01:00 Kenneth Lim <notifications@github.com>:

**Comment by lmccart** [comment]
If I understand correctly, the code works properly in the browser but not in the pop-up window from the p5 editor? If this is the case, I would suggest moving away from the editor as it has been deprecated. Some other good editor alternatives are listed [here](https://github.com/processing/p5.js-editor/blob/master/README.md).

**Comment by alamius** [comment]
Ok. I'thank you for helping me.
