### ISSUE TITLE
is it possible to use p5js in a wordpress post?

### ISSUE THREAD

**Issue by weegreenblobbie** [processing/p5.js#1749]
I just discovered p5js today and am very excited about it.  I want to write blog posts in wordpress, however, the `createCanvas(w,h)` always appears at the bottom of the website instead of inline with the blog post.

My question, can I create an HTML5 canvas object in the post and then in `setup()` use the already created canvas?  Will multiple canvas objects be okay?

**Comment by weegreenblobbie** [comment]
I found a workaround by using the `<object>` tag, see [my blog post](http://weegreenblobbie.com/?p=212).

```
<object data="p5js/001_bouncing_points/index.html" width="500" height="275">
    ERROR: failed to load html object!
</object>
```

**Comment by lmccart** [comment]
cool! here are some other options too: https://github.com/processing/p5.js/wiki/Embedding-p5.js

**Comment by weegreenblobbie** [comment]
I taught myself some javascript and created this player widget: https://github.com/weegreenblobbie/p5js-player

**Comment by zetec30** [comment]
Use CSS z-, -1
