### ISSUE TITLE
Error windows script host 800a0404

### ISSUE THREAD

**Issue by buke0045** [processing/p5.js#1754]
I just download p5.js and i cant open it

![qweqeqeqe](https://cloud.githubusercontent.com/assets/25016377/21781854/dd12db9a-d676-11e6-87e3-4fccc9941f9e.PNG)

**Comment by lmccart** [comment]
It sound like you are using the p5 desktop editor. This has been deprecated, some other recommended options are [here](https://github.com/processing/p5.js-editor#this-editor-has-been-deprecated-we-will-not-be-making-further-releases-we-are-turning-our-energy-toward-a-web-editor-which-will-be-released-later-this-year-for-now-we-recommend-using-editors-like-brackets-atom-sublime-text-or-openprocessing)
