### ISSUE TITLE
Using saveCanvas() within mouseClicked() creates an infinite loop that downloads a bunch of files

### ISSUE THREAD

**Issue by alterebro** [processing/p5.js#1755]
Hi,
there is some problem with the `saveCanvas()` function that creates a loop when it is called inside the `mouseClicked()` function.
Chrome and Opera (OSX 10.11) download files until the browser throws a `'Maximum call stack size exceeded'` error message but Firefox (OSX and Ubuntu) doesn't stop the execution of the script, it downloads a huge amount of files, it freezes and then gets stuck.
Safari doesn't have the problem as it opens the image in different window.

This is the code that creates the issue :

```js
function mouseClicked() {
	saveCanvas('my_image', 'jpg');
}
```

The following codepen using the latest version of the p5 library (0.5.6) exposes the problem : http://codepen.io/anon/pen/LxpXPa?editors=0010

**Comment by juansrx** [comment]
@alterebro : From this : link https://p5js.org/reference/#/p5/mouseClicked it seems that not all browsers handle this function the same, but they suggest you can "return false" at the end of the method to avoid default behaviors. I tried it on your example and it works (Chromium Version 55.0.2883.87 Built on Ubuntu , running on Ubuntu 16.04 made only one download). I hope this can help you.

**Comment by alterebro** [comment]
Hola @juansrx ,
thanks for the feedback and pointing out the 'return false' thing, that certainly fixes the multiple files download issue which is cool but keeps the loop running :(

**Comment by lmccart** [comment]
fixed in https://github.com/processing/p5.js/pull/1768
