### ISSUE TITLE
Create Dash/Zeal documentation

### ISSUE THREAD

**Issue by schallerala** [processing/p5.js#1757]
Hi,

I'm using Dash for offline documentation and have all my documentation quickly accessible with the different shortcuts that the application provides.
I'm suggesting you make a contribution to it: https://kapeli.com/docsets#contributetodash

That would be awesome!

I know wikis are accessible on Dash, but your wiki is less structured than your documentation / reference and would love to find you there!

Continue with the great job!

**Comment by lmccart** [comment]
Looks interesting. Unfortunately, we're unable to support this as this time.
