### ISSUE TITLE
How to contribute to the wiki (edit/fix/etc)

### ISSUE THREAD

**Issue by max-devjs** [processing/p5.js#1758]
I was reading a page on the wiki and found what seems to be an error. Looking for hints on how to contribute, I did not found something specific.

What would be needed:

- edit the page [wiki/p5.js,-node.js,-socket.io](https://github.com/processing/p5.js/wiki/p5.js,-node.js,-socket.io)
- fix the error [as per provided reference](https://github.com/lmccart/itp-creative-js/blob/master/Spring-2014/week6/03_node_servep5/server.js)
```
var ext = require('ext');
```
would become
```
var fs = require('fs');
```

What would be the correct sequence? Open an issue then edit? Just edit? Ask somewhere else? ...?

Thank you

**Comment by lmccart** [comment]
what you did is perfect, you can go ahead and make the change and then close this issue. thanks!
