### ISSUE TITLE
Typo in href on website

### ISSUE THREAD

**Issue by ssta** [processing/p5.js#1759]
Hi, 

On [the examples page]( https://p5js.org/examples/) it seems that there's a typo in the link for the Noise1D example.  It's pointing at: [https://p5js.org/examples/math--noise1d.html](https://p5js.org/examples/math--noise1d.html) which is a 404; 

[https://p5js.org/examples/math-noise1d.html](https://p5js.org/examples/math-noise1d.html)  (single hyphen) works correctly.

Thanks,
Stephen

**Comment by ssta** [comment]
Oops, just noticed I should have sent this to p5.js-website/issues instead.  Is there a way I can move it?  Sorry about that!

**Comment by bmoren** [comment]
just close this and reopen the issue there.
