### ISSUE TITLE
Element going offscreen when rectMode is set to CENTER

### ISSUE THREAD

**Issue by wahidshafique** [processing/p5.js#1762]
when trying to make a grid, I needed to make my click events correspond to the correct position of the object. `dist()` was giving back offset results. To fix this I set the `rectMode` to `CENTER` but then the canvas elements went off screen. I am very new to p5js and am not sure if this is a error on my part or what. 

Here is my fiddle, showing the issue http://codepen.io/anon/pen/GrqVyq 

PS: When I comment out the canvas, partial elements are still shown, why is that?

**Comment by limzykenneth** [comment]
There shouldn't be a need to use `dist` to detect mouseclick, you can simply check if `mouseX` and `mouseY` is larger than `this.x` and `this.y` while smaller than `this.x + this.size` and `this.y + this.size` respectively (assuming default rectMode). When you draw with rectMode `CENTER` it means the coordinates of the rectangle is in the center of it so when drawing at say `0, 0`, it means the center point of the rectangle will be at `0, 0` and so part of it will be outside the canvas.

When you simply leave out `createCanvas`, a default blank canvas will still be created. If you don't want the canvas you need to call `noCanvas()`.

This kind of question is better suited to the [forum](http://forum.processing.org), github issues are more for bug tracking and feature requests.

**Comment by wahidshafique** [comment]
thank you, point noted about the forums!
