### ISSUE TITLE
issues with loadSound

### ISSUE THREAD

**Issue by visualroam** [processing/p5.js#1763]
I have issues with the loadSound function, Screen("http://puu.sh/tngQ7/8dd7fbd5bc.png")
Line 20, thats https://gist.github.com/visualroam/2889169f15a825443d06285f04069661
Im doing the same thing as in the Example and its not working.
Im Using Chrome.

**Comment by bmoren** [comment]
can you send a screen of your index.html file?

**Comment by visualroam** [comment]
Thanks for the fast anwser, i just found out, that its working on my Webspace. 
When i open it on my local Folder its not working funny, but thanks ;)

**Comment by bmoren** [comment]
It could be the way p5.sound was linked `../` linking can break when using local files
