### ISSUE TITLE
keyIsPressed Issue

### ISSUE THREAD

**Issue by jkrobertson88** [processing/p5.js#1769]
So it seems to recognize when the a single key is still being pressed but not necessarily that a key is still being pressed. 

Example:
I press the up arrow it returns true while I am holding the up arrow down.
While the up arrow is being pressed I press the down arrow.
I release the up arrow but maintain the down arrow being pressed down. 
keyIsPressed now returns false even though the down arrow is pressed.

**Comment by lmccart** [comment]
can you tell me which browser you're using?

**Comment by jkrobertson88** [comment]
Chrome Version 55.0.2883.87 m

**Comment by tstefanich** [comment]
I think this may be a problem with the _keyup function 

```
p5.prototype._onkeyup = function (e) {
  var keyReleased = this.keyReleased || window.keyReleased;
  this._setProperty('isKeyPressed', false);
  this._setProperty('keyIsPressed', false);
  this._setProperty('_lastKeyCodeTyped', null);
  downKeys[e.which] = false;
  //delete this._downKeys[e.which];
  var key = String.fromCharCode(e.which);
  if (!key) {
    key = e.which;
  }
  this._setProperty('key', key);
  this._setProperty('keyCode', e.which);
  if (typeof keyReleased === 'function') {
    var executeDefault = keyReleased(e);
    if(executeDefault === false) {
      e.preventDefault();
    }
  }
};
```

You can see on the 3rd line of the function that it always sets keypressed to false always on key up but it doesn't check to see if any other buttons on still being pressed. I did a small amount of testing and this started to get the correct behavior.  You can see I moved 3 lines of code to the bottom of the function and checked against other key presses. You can see what I added after //TJS 

```
p5.prototype._onkeyup = function (e) {
  var keyReleased = this.keyReleased || window.keyReleased;
  var keysStillPressed = false;
  downKeys[e.which] = false;
  //delete this._downKeys[e.which];
  var key = String.fromCharCode(e.which);
  if (!key) {
    key = e.which;
  }
  this._setProperty('key', key);
  this._setProperty('keyCode', e.which);
  if (typeof keyReleased === 'function') {
    var executeDefault = keyReleased(e);
    if(executeDefault === false) {
      e.preventDefault();
    }
  }

  // TJS
  for (var i in downKeys) {
    console.log(downKeys[i])
    if (downKeys[i] === true) {
        console.log('test');
        keysStillPressed = true;
        //break;
    }
   }
   if(keysStillPressed == false){
    this._setProperty('isKeyPressed', false);
    this._setProperty('keyIsPressed', false);  
    this._setProperty('_lastKeyCodeTyped', null);
  } 
};
```

**Comment by tstefanich** [comment]
Whoops missed the commit..

**Comment by lmccart** [comment]
fixed with https://github.com/processing/p5.js/pull/1783
