### ISSUE TITLE
createCanvas: problem with the default canvas

### ISSUE THREAD

**Issue by taseenb** [processing/p5.js#177]
i am doing some tests for the docs and for a simple live-code example. i found that something looks buggy with `createCanvas()` (manipulate.js).

we first create a default canvas in `_start()` (core.js), and then we destroy it in `createCanvas()` if the user creates one herself. actually, when p5 is first instantiated, it does append a big (800x600) empty canvas to the body (always with the same `id=defaultCanvas`), but in my tests this is not removed correctly in some situations.

probably this is not the best workflow: imagine you use p5 in a website with other elements in the page, you would probably have a flash in the browser because of this big element added to the dom for a few milliseconds.
with a live editor this is even worse, because you have to instantiate p5 several times (unless we change a few things to manage this differently), and the default canvas is added to the dom every time.

the default canvas should probably be created _after_ the `_setup`, only if no canvas was created yet, or should be hidden until the sketch is ready. or even added in `'position:absolute` and outside from the view `top: -9999px; left:9999px; z-index:-9999;`.

btw, i think the default canvas in Processing (Java) is only 200x200px wide. maybe the default canvas should be smaller (probably like the original), to allow multiple tests and examples to be run easily?

**Comment by bluelotusmedia** [comment]
> Also, I wonder if we should have a `noCanvas()` method for the rare case when you want a p5 sketch just for DOM manipulation or some other non-drawing experiment?

So glad you added this feature as I definitely just needed this for an experimental socket.io chat project with p5 dom and html elements only.
