### ISSUE TITLE
WEBGL issues with 2D and FOR

### ISSUE THREAD

**Issue by Leamucho** [processing/p5.js#1772]
After some experimentation, found a For with 2D forms, with WEBGL renderer is quite slow, or basically accelerates and decelerates strangely.
Proofing on the deprecated p5.js app gives me this strange results, as with the p5.js mode, although quite slower on the mode. 
Inside the openprocessing IDE it consoles this:

> Line 30676: Cannot read property '_applyColorBlend' of undefined.

so, i take out the fill, and the crosses made with ellipses become some blue and black triangles... 

```
var gyro = 0; // making the rotation by counting

function setup(){
  createCanvas(1400, 600, WEBGL);
  //frameRate (30);
  angleMode (DEGREES);
  colorMode (HSB,360,100,100); 
  strokeWeight (0.05);
 // posx= width/4;
 // posy= height/4;
}
 
function draw(){
  background(250);
   
  gyro++;
  var on360 = gyro % 360;   
    for (let i= on360 ; i < (on360)+331 ;i+= 30 ){ 
      //to maintain the crosses on sight, till 690 (two rounds-30) 
      // advancing by 30, we make 12 figures. less is more figures
       
      fill (i%360,80,100); //hue advancing by 30 skiping 359 to 690, and noise movement to the saturation
      //var tremx = map (noise(xoff),0,1,15,25);//mapping of noise values for trembling
      //var tremy = map (noise(yoff),0,1,10,20);//mapping of noise values for trembling
      var radius = 100 ;// noise variation for radius, between 70-320
       
      //var x += (i);//trig formulae applied 
      //var y += (i);// and radians conversion 
      rotateZ(i);
      //rotateY(i);
      ellipse (i,i,50,10);// horizontal part of cross
      ellipse (i,i,10,50);// vertical part of cross 
      //xoff += 0.05; //noise val moving
    }
    //yoff += 0.01; //noise val moving
   
}
```
I leave lot of commented commands to show it had some more operations but that the problems seem to be on the renderer wit 2D, and with the FOR.

**Comment by lmccart** [comment]
ellipse() is not currently implemented in webgl, it is in the roadmap:
https://github.com/processing/p5.js/wiki/Getting-started-with-WebGL-in-p5
