### ISSUE TITLE
CSS cursors are not working

### ISSUE THREAD

**Issue by feedzh** [processing/p5.js#1773]
CSS default cursors, like explained here:

http://www.w3schools.com/cssref/pr_class_cursor.asp

Are not working.

**Comment by tstefanich** [comment]
Hello @feedzh, 

Could you share some of your code? This should not be a problem with p5 as this CSS cursor styling is built into all modern browsers, such as Edge, Firefox or Chrome.  So its probably some problem with some html and/or css. I would be happy to advise if you can share your project.

**Comment by feedzh** [comment]
`
    setup=function() {
        canvas = createCanvas(canvasHeight*2, canvasHeight);
        canvas.id(canvasId);
        canvas.mouseMoved(mouseMove);
    }

mouseMove=function(m){
        if(im.profileImage){
            if((m.layerX>=re.rectStart[0])&&(m.layerX<=(re.rectStart[0]+re.selWidth))&&(m.layerY>=re.rectStart[1])&&(m.layerY<=(re.rectStart[1]+re.selHeight))){
                
                if(dist(m.layerX,m.layerY,re.rectStart[0]+2,re.rectStart[1]+3)<cornerDist){
                    cursor("nwse-resize");
                }else if(dist(m.layerX,m.layerY,re.rectStart[0]+re.selWidth-3,re.rectStart[1]+re.selHeight-3)<cornerDist){
                    cursor("nwse-resize");
                }else if(dist(m.layerX,m.layerY,re.rectStart[0]+re.selWidth-3,re.rectStart[1]+3)<cornerDist){
                    cursor("nesw-resize");
                }else if(dist(m.layerX,m.layerY,re.rectStart[0]-2,re.rectStart[1]+re.selHeight-3)<cornerDist){
                    cursor("nesw-resize");
                }else{
                    cursor("move");
                }
                if((re.startRectDrag) || (re.cornerDrag)){
                    calcCoord(m);
                }
            }else{
                if(re.cornerDrag){
                    calcCoord(m);
                }else{
                    cursor(ARROW);
                }
            }
        }
    }`

just a random snippet from my "prototype". cursor(ARROW) is working. Strangely also cursor("move");.  (this might be because there is same cursor constant. All other css defined cursors are not working. It tries to download url(nesw-resize) image. That doesn't exist. Tested in Safari, Firefox, Chrome. As you saw my fix. The if is wrong. It tries to assume that it is URL if it is not constant.

Also url definition doesn't account https. Perhaps it would be better to make search for only http in the beginning.

**Comment by feedzh** [comment]
```javascript
setup=function() {
    canvas = createCanvas(canvasHeight*2, canvasHeight);
    canvas.id(canvasId);
    canvas.mouseMoved(mouseMove);
}

mouseMove=function(m){
      if(im.profileImage){
      if((m.layerX>=re.rectStart[0])&&(m.layerX<=(re.rectStart[0]+re.selWidth))&&(m.layerY>=re.rectStart[1])&&(m.layerY<=(re.rectStart[1]+re.selHeight))){                
          if(dist(m.layerX,m.layerY,re.rectStart[0]+2,re.rectStart[1]+3)<cornerDist){
              cursor("nwse-resize");
          }else if(dist(m.layerX,m.layerY,re.rectStart[0]+re.selWidth-3,re.rectStart[1]+re.selHeight-3)<cornerDist){
              cursor("nwse-resize");
          }else if(dist(m.layerX,m.layerY,re.rectStart[0]+re.selWidth-3,re.rectStart[1]+3)<cornerDist){
              cursor("nesw-resize");
          }else if(dist(m.layerX,m.layerY,re.rectStart[0]-2,re.rectStart[1]+re.selHeight-3)<cornerDist){
              cursor("nesw-resize");
          }else{
              cursor("move");
          }
          if((re.startRectDrag) || (re.cornerDrag)){
              calcCoord(m);
          }
      }else{
          if(re.cornerDrag){
              calcCoord(m);
          }else{
              cursor(ARROW);
          }
      }
  }
```

just a random snippet from my "prototype". cursor(ARROW) is working. Strangely also cursor("move");.  (this might be because there is same cursor constant. All other css defined cursors are not working. It tries to download url(nesw-resize) image. That doesn't exist. Tested in Safari, Firefox, Chrome. As you saw my fix. The if is wrong. It tries to assume that it is URL if it is not constant.

Also url definition doesn't account https. Perhaps it would be better to make search for only http in the beginning.

**Comment by tstefanich** [comment]
Could you send a more complete example. There are many variables that are not included such as im, re, and m. Without these I am unable to debug. The logic in the example seems on the surface mostly correct but without the complete example its hard to debug.

**Comment by feedzh** [comment]
```javascript

function setup() {
    var canvas=createCanvas(400, 400);
    canvas.mouseMoved(mouseMove);
    stroke("#000000");
    rect(0,0,399,399);
}

function draw() {
    fill("#000000");
    rect(150,150,100,100);
}

var mouseMove=function(m){
    if((m.layerX > 150) && (m.layerX < 250) && (m.layerY > 150) && (m.layerY < 250)){
        //cursor("nesw-resize");
        //cursor("move");
        cursor(MOVE);
    }else{
        cursor(ARROW);
    }
}

```

Here is small snipped. Just put it to default projects sketch.js. As you can see "nesw-resize" are not working. Strangely "move" does like MOVE.

![screen shot 2017-01-27 at 20 53 43](https://cloud.githubusercontent.com/assets/378124/22387285/c4a74f90-e4d2-11e6-9eb9-9fbb7f667082.png)

**Comment by limzykenneth** [comment]
@feedzh it is indeed a bug in the library. Just made a PR to fix it. Thanks!

**Comment by tstefanich** [comment]
Good fix!

@feedzh problem is actually that p5 is using the cursor defaults of processing and not the web/css cursor option. And the web has all of these options.

[ auto | default | none | context-menu | help | pointer | progress | wait | cell | crosshair | text | vertical-text | alias | copy | move | no-drop | not-allowed | e-resize | n-resize | ne-resize | nw-resize | s-resize | se-resize | sw-resize | w-resize | ew-resize | ns-resize | nesw-resize | nwse-resize | col-resize | row-resize | all-scroll | zoom-in | zoom-out | grab | grabbing ]

And @feedzh https problem is because he is using a string "nesw-resize" which p5 thinks is image but @feedzh thought it would use css cursor instead. 

I had started working on this locally to have p5 accommodate css cursors but this weekend got away from me.

**Comment by feedzh** [comment]
Thank you tstefanich,

I figured that much out. But this "performance" modification threw me off a bit. I didnt really understood the meaning of that. And overall this small function seemed a bit messy.

I think that if the end is not "cur|jpg|jpeg|gif|png|CUR|JPG|JPEG|GIF|PNG" and/or beginning is not http or https, it should use css cursor instead. The modification that I made fixed css issue. I didnt test the server things. Perhaps it is worth looking for http(s) issues in the other places also. Just to be safe side :D

Reijo

**Comment by limzykenneth** [comment]
@tstefanich it is already possible to use css cursor options in p5.js (all the supported ones in the respective browsers. The reason @feedzh is not seeing the cursor requested is because of the bug fixed in #1789. Using the string "nesw-resize" should bring up the css cursor but p5.js thinks it is an image because there's an error in the inequality check for "http://" substring at the beginning of the string.

How it works currently is that first is looks at if the passed in parameter is a string or not, if not, assume it is a library constant and use it directly. If it is, check if it starts with "http://" (check goes wrong here, it is checking if it didn't start with "http://"), if it did then use it as a URL; if it didn't, then check if it ends in a accepted image subfix, if it did then use that as a URL as well; lastly if it didn't start with "http://" or end in image subfix, then assume it is a css cursor string and use it directly.

**Comment by limzykenneth** [comment]
@feedzh I totally missed your fix, sorry, I'll close mine 😉

**Comment by limzykenneth** [comment]
@feedzh BTW, `"move"` works because of this check `if (standardCursors.indexOf(type) > -1)`

**Comment by feedzh** [comment]
```javascript
p5.prototype.cursor = function(type, x, y) {
  var cursor = 'auto';
  var canvas = this._curElement.elt;
  if (standardCursors.indexOf(type) > -1) {
    // Standard css cursor
    cursor = type;
  } else if (typeof type === 'string') {
    var coords = '';
    if (x && y && (typeof x === 'number' && typeof y === 'number')) {
      // Note that x and y values must be unit-less positive integers < 32
      // https://developer.mozilla.org/en-US/docs/Web/CSS/cursor
      coords = x + ' ' + y;
    }        
    if ((type.substring(0, 7) === 'http://') && (type.substring(0, 8) === 'https://')) {
      // Image (absolute url)
      cursor = 'url(' + type + ') ' + coords + ', auto';
    } else if (/\.(cur|jpg|jpeg|gif|png|CUR|JPG|JPEG|GIF|PNG)$/.test(type)) {
      // Image file (relative path) - Separated for performance reasons
      cursor = 'url(' + type + ') ' + coords + ', auto';
    } else {
      // Any valid string for the css cursor property
      cursor = type;
    }
  }
  canvas.style.cursor = cursor;
};
```

So this is entire fixed function in all its glory :D Substr numbers were also wrong. "http://" is 7 chacters not 6 like proposed in the original.

**Comment by feedzh** [comment]
I also made quick grep to "http" and didn't really see other problems regarding https.

**Comment by feedzh** [comment]
I also tested it in browsers: safari, chrome, firefox. (I dont have IE or Edge). Opera is chrome anyway.

The cursor image is downloaded once and not repeated as it was with 404 case. (Look my inspector above)

Reijo

**Comment by feedzh** [comment]
```javascript
// sketch.js on default project with p5.js fixed with "p5.prototype.cursor" function
function setup() {
    var canvas=createCanvas(400, 400);
    canvas.mouseMoved(mouseMove);
    stroke("#000000");
    rect(0,0,399,399);
}

function draw() {
    fill("#000000");
    rect(150,150,100,100);
}

var mouseMove=function(m){
    if((m.layerX > 150) && (m.layerX < 250) && (m.layerY > 150) && (m.layerY < 250)){
        cursor("http://localhost/test/cursor_error/cursor.png");
        //cursor("nesw-resize");
        //cursor(MOVE);
    }else{
        cursor(ARROW);
    }
}
```

**Comment by limzykenneth** [comment]
@feedzh can you fix the substring number in this PR, after that I believe this is good to merge. @lmccart

**Comment by feedzh** [comment]
@limzykenneth It is fixed.

**Comment by feedzh** [comment]
if you do "http://www.example.com".substring(0, 7) you see, it returns http://

**Comment by feedzh** [comment]
For my part this issue is closed and pull request has been issued.

**Comment by lmccart** [comment]
great!

**Comment by mihkuno** [comment]
There's a bug when I try to use `cursor()` on live server in vscode which says that `Uncaught ReferenceError: cursors is not defined`. Although it works perfectly fine if run on static html.

I managed to get it working by renaming the function `_main.default.prototype.cursor` to something else.
