### ISSUE TITLE
documentation disconnect

### ISSUE THREAD

**Issue by lorankary** [processing/p5.js#1774]
There seems to be a disconnect between the documentation for p5.prototype.image and the code.

https://github.com/processing/p5.js/blob/master/src/image/loading_displaying.js#L127
has the destination parameters first and the source parameters second.

p5.prototype.image =
  function(img, dx, dy, dWidth, dHeight, sx, sy, sWidth, sHeight) {
  // set defaults per spec: https://goo.gl/3ykfOq

But the actual code in p5.js has them reversed.

p5.prototype.image =
  function(img, sx, sy, sWidth, sHeight, dx, dy, dWidth, dHeight) {
  // Temporarily disabling until options for p5.Graphics are added.
  // var args = new Array(arguments.length);

**Comment by lmccart** [comment]
I think you maybe be using an older version of the library? The most recent version (0.5.6) has the same order as the src code and inline documentation. `function(img, dx, dy, dWidth, dHeight, sx, sy, sWidth, sHeight)`

**Comment by lorankary** [comment]
I have 0.5.3

**Comment by lmccart** [comment]
ah ok, try updating to 0.5.6, it should be correct there :)
