### ISSUE TITLE
createImage and texture dont seem to work together

### ISSUE THREAD

**Issue by jtoy** [processing/p5.js#1777]
According to the docs, it seems like I should be able to pass an image from createImage into texture, but when I do,I get an error of "30257: Uncaught TypeError: undefined is not a function"
Not a very easy error to debug. I've included a very simple example that should work. Do the docs need to be updated ? This should work.

```
function setup() {
  
}

function draw() {

  pim = createImage(20,20);
  pim.loadPixels()

  for (var i = 0; i < pim.width; i++) {
    for (var j = 0; j < pim.height; j++) {
      xxx= (noise(i,j)*255)
      pim.set(i,j,color(i,xxx,xxx))
    }
  }
  pim.updatePixels()
  image(pim,10,10)
  
  texture(pim)
  rect(20,20,20,20)

}
```

**Comment by lmccart** [comment]
texture() is meant to be used in webgl mode with 3D forms, see examples [here](http://p5js.org/reference/#/p5/texture), so this won't work correctly with rect().
