### ISSUE TITLE
Support both nonzero and evenodd fill rules

### ISSUE THREAD

**Issue by fogleman** [processing/p5.js#1782]
The "fill rule" is a common parameter in 2D rendering engines to control how overlapping areas in a path are filled.

![](https://i.stack.imgur.com/n5KCK.png)

Examples from other libraries:

- SVG: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/fill-rule
- Canvas: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/fill
- Cairo: https://www.cairographics.org/manual/cairo-cairo-t.html#cairo-set-fill-rule
- CoreGraphics: https://developer.apple.com/reference/coregraphics/1454865-cgcontexteofillpath
- .NET: https://msdn.microsoft.com/en-us/library/system.windows.media.pathgeometry.fillrule(v=vs.110).aspx

Currently, p5.js does not provide control over the fill rule. However, the underlying rendering library supports it, so adding it is relatively easy.

This was implemented in pull request https://github.com/processing/p5.js/pull/1729. This PR added a fillRule function to select NONZERO or EVENODD fill rules. The PR was closed as "out of scope." I am opening this issue to encourage discussion.

**Comment by lmccart** [comment]
Thanks, I hear your request. At this point, however, I would like to focus on fixing bugs and resolving issues with the current API before expanding. Part of this is also thinking about the beginner user that looks at the reference page and needs to be able to figure out where to begin. I think fillRule() is a more advance topic and could add confusion. It is completely possible to access the canvas directly by using the variable `drawingContext`, so users that would like to are still able to set the fill rule.

**Comment by fogleman** [comment]
That workaround could be feasible if the fillRule was a property of the drawingContext, but it's passed in as a parameter to the fill function.

There are literally hundreds of functions on the reference page. I don't really understand how adding fillRule is going to throw off a beginner.

You seem strongly against this. Frankly, I'm less likely to continue using or contributing to p5.js now.

**Comment by fogleman** [comment]
> **Be open minded.** Embrace new people and new ideas.

Not feeling particularly embraced on either front.

You can say "Thanks, I hear your request." while sending a very different message.

I normally wouldn't bother saying that, but the p5.js site and contribution guidelines seem to make a big deal about it - yet I've never been so quickly and repeatedly shut down contributing elsewhere before.

**Comment by lmccart** [comment]
Hey @fogleman I'm so sorry you felt shut down, that was completely not my intention. I apologize. To be honest, this project has become overwhelming in the maintenance and I am struggling to keep it going. It's all done in volunteer hours and I am doing everything I can to address all the issues and requests, but I feel like I'm drowning a bit. For this reason, I'm really worried about adding new features and expanding the API when I can't seem to get the existing API to be nearly as bugfree and resolved as I'd like. I feel that with the limited energy I have, I need to focus on what is here already and begin with fixing that before adding more. I hope that you understand. If given that, this library doesn't work for your purposes, I completely understand, and apologize.

**Comment by fogleman** [comment]
Yes, I sensed "overwhelmed" in your language before, and it did in fact seem to be the real reason that my feature was not truly considered.

Ideally a large open source project won't fall on the hands of a single individual. To that end, I hoped that my contribution would be an easy merge. That is, all the work already done. It doesn't seem you see it that way. But if that's all true, I think a better response would be to delegate and ask for help where needed to get it to a merge-able state.

As a computer graphics person, I still believe that fill rule is *very* in-scope for a project like p5.js. My persistence here was only due to being baffled. But I'll move right along.

**Comment by lmccart** [comment]
Yes, it's not really the work of merging this single request, but the work of maintaining the entire API, fielding questions about each function on github and in the forums, making sure the documentation stays up to date and examples are included for each function, etc. I can assure you I did give it true consideration though.

**Comment by lmccart** [comment]
All right, since you feel so strongly this needs to be in there we can give it a try. If you add [unit tests](https://github.com/processing/p5.js/wiki/Development#testing) and a couple [examples](https://github.com/processing/p5.js/wiki/Inline-documentation) I can merge it in.

**Comment by fogleman** [comment]
🎉  I'll work on it soon.

**Comment by subhog** [comment]
Are there any news about this feature? It's really essential when working with imported graphics.

**Comment by esperanc** [comment]
I, for one, would very much like to add my support for this feature.
