### ISSUE TITLE
grunt hangs on "mocha:yui" (mocha) task on OSX

### ISSUE THREAD

**Issue by kjhollen** [processing/p5.js#1784]
Hi folks! First time building the library from source today in a while. I ran into some issues running grunt—the last thing I see is this:

```
Running "mocha:yui" (mocha) task
Testing: http://localhost:9001/test/test-reference.html
```

and then the build hangs. I let this run for 10 minutes before stopping it. Another participant in the workshop in LA ran into this issue and Lauren said it cropped up last week in NY, too.

More details from a verbose run of grunt:

```
Running "mocha:yui" (mocha) task
Verifying property mocha.yui exists in config...OK
File: [no files]
Options: log, reporter="Nyan", timeout=5000, inject="/Users/kjhollen/src/p5.js/node_modules/grunt-mocha/phantomjs/bridge.js", phantomScript="/Users/kjhollen/src/p5.js/node_modules/grunt-mocha/phantomjs/main.js", urls=["http://localhost:9001/test/test-reference.html"], bail=false, logErrors, growlOnSuccess, run=false
Options: {
  "log": true,
  "reporter": "Nyan",
  "timeout": 5000,
  "inject": "/Users/kjhollen/src/p5.js/node_modules/grunt-mocha/phantomjs/bridge.js",
  "phantomScript": "/Users/kjhollen/src/p5.js/node_modules/grunt-mocha/phantomjs/main.js",
  "urls": [
    "http://localhost:9001/test/test-reference.html"
  ],
  "bail": false,
  "logErrors": true,
  "growlOnSuccess": true,
  "run": false
}
Phantom options: {
  "timeout": 5000,
  "inject": "/Users/kjhollen/src/p5.js/node_modules/grunt-mocha/phantomjs/bridge.js",
  "phantomScript": "/Users/kjhollen/src/p5.js/node_modules/grunt-mocha/phantomjs/main.js",
  "logErrors": true,
  "growlOnSuccess": true,
  "run": false
}
Testing: http://localhost:9001/test/test-reference.html
```

Here are some version numbers that may or may not be relevant:
grunt-cli v1.2.0
grunt v0.4.5
npm 3.10.8

Let me know if there are other helpful details I can provide!

**Comment by aemonm** [comment]
Hi - You need to open that URL in a browser - http://localhost:9001/test/test-reference.html - for the tests to run to completion.

**Comment by limzykenneth** [comment]
Same situation here and opening http://localhost:9001/test/test-reference.html before or after the test is running both did not solve the problem, it is still stuck on that step. I don't think it should have anything to do with opening the page in a browser as the test suite already include phantomjs to simulate a browser environment and the test is supposed to run on that.

**Comment by lmccart** [comment]
hmm i wonder if it could have something to do with the version of phantomjs. i'll take a look into it more this week.

**Comment by limzykenneth** [comment]
Any progress on this one? I'm unable to test the source easily with this problem... 😦

**Comment by lmccart** [comment]
I've tried a lot of things, different machines, and am not able to reproduce at all, so I'm not sure what to do... I'll keep looking around for more computers to test on. was there a point where it stopped working for you or did it never work at all?

**Comment by limzykenneth** [comment]
hmm...could it be I'm using the latest macOS or maybe my node version? I'll try reverting to some commits a few months ago and see if it works.

**Comment by limzykenneth** [comment]
Updating the `grunt-mocha` package to its latest version seem to make it go pass the road block but I hit another...

```
Warning: TypeError: undefined is not a constructor (evaluating 'test.isPending()')   -_|   /\_/\ 
    at undefined (phantomjs://code/bridge.js:47)
    at emit (http://localhost:9001/test/js/mocha.js:588)
    at runSuite (http://localhost:9001/test/js/mocha.js:4720)
    at run (http://localhost:9001/test/js/mocha.js:4795)
    at run (http://localhost:9001/test/js/mocha.js:1701)
    at run (http://localhost:9001/test/js/mocha.js:5584)
    at onload (http://localhost:9001/test/test-reference.html:220) Use --force to continue.
```
```
Warning: PhantomJS timed out, possibly due to a missing Mocha run() call.
```
All tests failed on similar errors like the above and the stack trace mean very little to me...

**Comment by lmccart** [comment]
I updated grunt-mocha and a few other modules and resolved this error and others that came up. @limzykenneth can you confirm the latest works for you?

@kjhollen can you test as well if you have a chance?

**Comment by limzykenneth** [comment]
Seems to be working for me 👍

**Comment by kjhollen** [comment]
Works for me too! 😁

**Comment by lmccart** [comment]
YAY
