### ISSUE TITLE
createGraphics() stays in memory, 1GB+ RAM after a while

### ISSUE THREAD

**Issue by NathanVogel** [processing/p5.js#1785]
I have a sketch that is a visual clock, designed to run on a display for a long time and I make periodic calls to createGraphics().

Even if I'm not referencing the created PGraphics, it stays in memory. 
This example sketch makes the RAM usage climb up and I can't find a way to free it. Is there one ?

```
<html>
  <body>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.5.6/p5.js"></script>
    <script type="text/javascript">
      function setup() {
        createCanvas(600, 600);
        var pg;
      }
      function draw() {
        pg = null;
        pg = createGraphics(1000, 1000);
      }
    </script>
  </body>
</html>
```

(I don't do it every frame in my sketch, but it can become a problem if it runs long enough.)

**Comment by lmccart** [comment]
You should just create the graphics object once:
```
var pg;
function setup() {
  pg = createGraphics(100, 100);
}
```

then if you want to remove it later you can write 
```
pg.remove();
```

**Comment by NathanVogel** [comment]
Thank you for the quick response !
However, `pg.remove()` results in `Uncaught TypeError: pg.remove is not a function`
It's only available on the `_pInst `object it seems...

I need to create different PGraphics of different sizes as the sketch evolves, I don't do it every frame (far from it ! but it can become a problem after a few hours since they're quite big)

**Comment by lmccart** [comment]
Ahh you're right sorry! I've just added one and it will be in the next release. Then something like this should work:

```javascript
var pg;
function setup() {
  pg = createGraphics(100, 100);
  pg.background('blue')
  pg.show();
}

function mousePressed() {
  console.log(pg)
  pg.remove();
  pg = null;
}
```

If you need a quick patch, you can paste this code in after the line in your p5.js file that reads:
```javascript
p5.Graphics.prototype = Object.create(p5.Element.prototype);
```

Here's the patch:
```
p5.Graphics.prototype.remove = function() {
  if (this.elt.parentNode) {
    this.elt.parentNode.removeChild(this.elt);
  }
  for (var elt_ev in this._events) {
    this.elt.removeEventListener(elt_ev, this._events[elt_ev]);
  }
};
```

**Comment by NathanVogel** [comment]
Great ! Thank you very much :) 
I'll look more closely later. 

I don't know how JS garbage collection works, nor if your patch is supposed to let this sketch free the memory, but after this quick test, it seems to stay in memory until the Chrome tab crashes after 2GB. 
The canvas does get removed from the DOM though.

```
var pg;
function setup() {
  createCanvas(600, 600);
}
function draw() {
  if (pg) {
    pg.remove();
  }
  pg = null;
  pg = createGraphics(1, 1);
}
```
