### ISSUE TITLE
p5.Font.textBounds not working for space

### ISSUE THREAD

**Issue by LexusXBox** [processing/p5.js#1788]
Hi,

I am evolving p5 tickle example. using arial.ttf it works but when the string "message" has a space it i get problematic bounds results.

see below

**Comment by LexusXBox** [comment]
Image file can be found at swift-engraving.co.uk/images/Swift 201 Large.jpg



var message = "Swift Engraving",
//var message = "SwiftEngraving",
  font,
  bounds,
  fontsize = 60,
  move,
  input, button,
  x, y;

function preload() {
    font = loadFont('assets/ARIAL.TTF');
    img = loadImage("../images/Swift 201 Large.jpg");

}
function setup() {
  createCanvas(600, 250);
  textFont(font);
  textSize(fontsize);
  bounds = font.textBounds(message);
  x = width / 2 - bounds.w / 2;
  y = height / 2 - bounds.h / 2;

  input = createInput();
  input.position(20, height+10);



  button = createButton('submit');

  button.position(150, height+10);
  button.mousePressed(greet);

  button = createButton('▲');
  button.position(207, height+10);
  button.mousePressed(sizeup);

  button = createButton('▼');
  button.position(239, height+10);
  button.mousePressed(sizedown);

  // set up the font

  move = false;

  // get the width and height of the text so we can center it initially
  // bounds = font.textBounds(message, 0, 0, fontsize);

}

function draw() {
  // for (var i=0; i<=message.length; i++){
  //   message.substring()
  // }
  // instead of clearing the background, fade it by drawing
  // a semi-transparent rectangle on top
  // textAlign(CENTER,CENTER);
  image(img, 0, 0);
  text(message, x, y);
        bounds = font.textBounds(message,x,y,fontsize);
  // rect(bounds.x,bounds.y,bounds.w,bounds.h);
  // console.log(bounds.x,bounds.y,bounds.w,bounds.h);
  // check if the mouse is inside the bounding box and tickle if so

  // Need to move bound box so it is over the text.

if (mouseIsPressed){


    if (move===false){

    if ( mouseX >= bounds.x && mouseX <= bounds.x + bounds.w &&
      mouseY >= bounds.y && mouseY <= bounds.y + bounds.h) {
      console.log(mouseX, x, mouseX-x, mouseY, y, mouseY-y);
      offsX = mouseX-x;//floor( mouseX-x);
      offsY = mouseY-y;// offsX = floor( mouseX-x);
      // offsY = floor( mouseY-y);
      move = true;
    }
  }else{


    x=mouseX-offsX;
    y=mouseY+abs(offsY);
          console.log(mouseX, x, mouseX-x,offsX, mouseY, y, mouseY-y,offsY);
    }

    }

}

function mouseReleased(){
  move = false;
}
function greet(){
 message = input.value();
}

function sizeup(){
fontsize = fontsize+2;
 textSize(fontsize);
}
function sizedown(){
fontsize = fontsize-2;
 textSize(fontsize);
}

**Comment by kingshitonly** [comment]
Fuck u guys

**Comment by dhowe** [comment]
Can you create a minimal test (the smallest program) that still shows the problem?

**Comment by LexusXBox** [comment]
Hi, Thanks for your reply.

Try www.swift-engraving.co.uk/editor/index.html 

It starts with the string "Swift" Bring up console you can see the log the last two variables are bounds.w and bound.h when you change the text in the box to have a space then click submit the bound.h becomes infinity.

The text drops of the screen.

Thanks
Lee

**Comment by tstefanich** [comment]
So something weird happed when you submit text with no space you make it to this chunk of code but not into the if statement that is checking if mouse is inbounds of the text 

```
if (move===false){
//console.log(mouseX, x, mouseX-x,offsX, mouseY, y, mouseY-y,offsY, bounds.w, bounds.h);
    if ( mouseX >= bounds.x && 
      mouseX <= bounds.x + bounds.w &&
      mouseY >= bounds.y && 
      mouseY <= bounds.y + bounds.h) {
      console.log('inbounds');
      offsX = mouseX-x;//floor( mouseX-x);
      offsY = mouseY-y;// offsX = floor( mouseX-x);
      // offsY = floor( mouseY-y);
      move = true;
    }
  } 
```

But if you submit a word with a space for some reason it makes it into this chunk, even though its not technically in bounds. 

```
 if ( mouseX >= bounds.x && 
      mouseX <= bounds.x + bounds.w &&
      mouseY >= bounds.y && 
      mouseY <= bounds.y + bounds.h) {
      console.log('inbounds');
      offsX = mouseX-x;//floor( mouseX-x);
      offsY = mouseY-y;// offsX = floor( mouseX-x);
      // offsY = floor( mouseY-y);
      move = true;
    }
```

But the x and why position does note change ..... but maybe the bounds.x and bounds.y does... 
https://www.dropbox.com/s/n4a4xiollg781di/Screenshot%202017-02-04%2019.25.14.png?dl=0

I'll let you know more once I figure out more....

**Comment by tstefanich** [comment]
Yeah the bounds object changes when test is submitted 
https://www.dropbox.com/s/79qwpc1abe69d5x/Screenshot%202017-02-04%2019.34.34.png?dl=0

The top object is text submitted with no spaces, the bottom object is submitted with spaces.

**Comment by tstefanich** [comment]
I've isolated the problem to something either in the font or how p5 handles fonts. 

If you use League Gothic font, which is free, I did not have this bug happen and the glyphs for each character is found https://www.dropbox.com/s/raoy5s41ysv8is7/Screenshot%202017-02-04%2020.06.27.png?dl=0

but if you are using Arial.ttf p5 never finds the glyph names and it does not correctly calculate the spaces because https://www.dropbox.com/s/uatb8qzjl6ms0ah/Screenshot%202017-02-04%2020.09.37.png?dl=0

and textBounds does use glyph.name to determine how to calculate bounds 
```
p5.Font.prototype.textBounds = function(str, x, y, fontSize, options) {

  x = x !== undefined ? x : 0;
  y = y !== undefined ? y : 0;

  fontSize = fontSize || this.parent._textSize;

  var result = this.cache[cacheKey('textBounds', str, x, y, fontSize)];
  if (!result) {

    var xCoords = [], yCoords = [], self = this,
      scale = this._scale(fontSize), minX, minY, maxX, maxY;

    this.font.forEachGlyph(str, x, y, fontSize, options,
      function(glyph, gX, gY, gFontSize) {

        xCoords.push(gX);
        yCoords.push(gY);
        console.log(glyph);
        if (glyph.name !== 'space') {
          var gm = glyph.getMetrics();

          xCoords.push(gX + (gm.xMax * scale));
          yCoords.push(gY + (-gm.yMin * scale));
          yCoords.push(gY + (-gm.yMax * scale));

        } else {

          xCoords.push(gX + self.font.charToGlyph(' ').advanceWidth *
            self._scale(fontSize));
        }
      });

    minX = Math.max(0, Math.min.apply(null, xCoords));
    minY = Math.max(0, Math.min.apply(null, yCoords));
    maxX = Math.max(0, Math.max.apply(null, xCoords));
    maxY = Math.max(0, Math.max.apply(null, yCoords));
  console.log(minX);
    result = {
      x: minX,
      y: minY,
      h: maxY - minY,
      w: maxX - minX,
      advance: minX - x
    };

    this.cache[cacheKey('textBounds', str, x, y, fontSize)] = result;
  }
  //else console.log('cache-hit');

  return result;
};
```

I'm completely familiar with what is entirely happening on the back end in p5 or completely know that much about different font files.... 

What would be the short coming to change the conditional inside textBounds to not be based on glyph.name !== space to glyph.unicode !== 32 ???

**Comment by tstefanich** [comment]
#1794

**Comment by dhowe** [comment]
looks good to me... thanks @tstefanich !

**Comment by LexusXBox** [comment]
Thank You
Lee

**Comment by tstefanich** [comment]
I'm not sure when the pull request will be merged and not sure when it will be officially release on the website. 

I think you will have to find and replace the line In your own personally copy of p5 until its officially released. 

https://github.com/processing/p5.js/pull/1794/commits/646d51c04097bcbeb29559fcc7c58f777b6ba192

**Comment by lmccart** [comment]
hi @LexusXBox, I'm planning to look at this PR later today and hoping to get a new release out in the next few days.

**Comment by lmccart** [comment]
thanks @tstefanich and @dhowe, PR looks good, merged!
fixed with https://github.com/processing/p5.js/pull/1794
