### ISSUE TITLE
WEBGL canvas problems

### ISSUE THREAD

**Issue by explodingdigg** [processing/p5.js#1791]
Whenever I run a WEBGL sketch with 3D shapes, the browsers crash. i have little info, other than the web p5 editor works fine.
speaking of the editor, every time I run my sketch - the tab freezes

EDIT:
the browser never crashes.
it is only the tab.
and my code is the problem, i made a simple rotating box and it worked fine.
but this code dosen't work:

function newSet(x,y,z){
	for(i = balls.length;i < balls.length + 20;i++){
  	balls[i] = new Ball(x,y,z);
  }
}
function Ball(x,y,z){
	this.pos = createVector(x,y,z);
  this.vel = p5.Vector.random3D();
  this.vel.setMag(random(1,2));
  this.lifetime = random(400,600);
  this.bounce = random(2,3.5);
  this.r = random(20);
  this.frame = function(){
  	//DISPLAY:
    translate(this.pos.x,this.pos.y,this.pos.z);
    sphere(this.r);
    translate(-this.pos.x,-this.pos.y, -this.pos.z);
    //MOVEMENT:
    this.pos.add(this.vel);
    this.vel.add(0,gravity,0);
    //UPDATE:
    for(y = 0; y < balls.length; y++){
     	if(balls[y].pos != this.pos){
      	if(this.pos.dist(balls[y].pos) > (this.r / 2) + (balls[y].r / 2)){
          if(bouncetime == frameCount){
          	this.vel.x = -this.vel.x / 1.3;
          	this.vel.z = -this.vel.z / 1.3;
           	//setTimeout(setBounce(),200);
          }
       	}
   	 	}
    }
    if(this.pos.y > bottom){
      this.pos.y = bottom;
      this.vel.y = (-this.vel.y / 4) * 3;
      this.vel.mult(friction);
    }
  }
}
function setBounce(){
	bouncetime = frameCount;
}
var bouncetime;
var rotation = 0;
var hold;
var balls = [];
var gravity = 0.2;
var bottom;
var friction = 0.85;
function setup() {
	bottom = width;
  createCanvas(400, 400, WEBGL);
  newSet(0,0,0);
}
function mousePressed(){
	newSet(mouseX - (width / 2),mouseY - (width / 2),0);
  // noprotect
}
function draw() {
  if(keyIsDown(RIGHT_ARROW))
  	rotation ++;
  else if(!hold)
    rotation = 0;

  if(keyIsDown(UP_ARROW))
  	hold = true;
  else
    hold = false;

  if(keyIsDown(LEFT_ARROW))
  	rotation --;
  else if(!hold)
    rotation = 0;

  background(220);
//  rotateY((mouseX / (PI * 64)) - width / 2);
  rotateY(rotation / (PI * 2));
  for(i = 0;i < balls.length;i++){
  	balls[i].frame();
    if(balls[i].lifetime <= 0){
      balls.splice(i, 1);
    }
  }
}

**Comment by bulbil** [comment]
3D shapes not rendering for me either -- I've included console logging for both Chrome and Firefox below. Appears to be a dependency blacklisting issue.

Chrome 55
```
Uncaught Error: Error: Error creating webgl context
    at d.RendererGL._initContext (p5.min.js:8)
    at d.RendererGL (p5.min.js:8)
    at e.d.createCanvas (p5.min.js:5)
    at setup (<anonymous>:2:3)
    at e.<anonymous> (p5.min.js:4)
    at e.<anonymous> (p5.min.js:4)
    at new e (p5.min.js:4)
    at <anonymous>:51:1
    at Object.loadExample (examples.js:165)
    at HTMLIFrameElement.<anonymous> (examples.js:37)
```

Firefox 34.0.5

```
Error: WebGL: Refused to create native OpenGL context because of blacklisting. p5.min.js:8
Error: WebGL: WebGL creation failed. p5.min.js:8
Error: WebGL: Refused to create native OpenGL context because of blacklisting. p5.min.js:8
Error: WebGL: WebGL creation failed. p5.min.js:8
Error: Error: Error creating webgl context
```

**Comment by explodingdigg** [comment]
'function newSet(x,y,z){
	for(i = balls.length;i < balls.length + 20;i++){
  	balls[i] = new Ball(x,y,z);
  }
}
function Ball(x,y,z){
	this.pos = createVector(x,y,z);
  this.vel = p5.Vector.random3D();
  this.vel.setMag(random(1,2));
  this.lifetime = random(400,600);
  this.bounce = random(2,3.5);
  this.r = random(20);
  this.frame = function(){
  	//DISPLAY:
    translate(this.pos.x,this.pos.y,this.pos.z);
    sphere(this.r);
    translate(-this.pos.x,-this.pos.y, -this.pos.z);
    //MOVEMENT:
    this.pos.add(this.vel);
    this.vel.add(0,gravity,0);
    //UPDATE:
    for(y = 0; y < balls.length; y++){
     	if(balls[y].pos != this.pos){
      	if(this.pos.dist(balls[y].pos) > (this.r / 2) + (balls[y].r / 2)){
          if(bouncetime == frameCount){
          	this.vel.x = -this.vel.x / 1.3;
          	this.vel.z = -this.vel.z / 1.3;
           	//setTimeout(setBounce(),200);
          }
       	}
   	 	}
    }
    if(this.pos.y > bottom){
      this.pos.y = bottom;
      this.vel.y = (-this.vel.y / 4) * 3;
      this.vel.mult(friction);
    }
  }
}
function setBounce(){
	bouncetime = frameCount;
}
var bouncetime;
var rotation = 0;
var hold;
var balls = [];
var gravity = 0.2;
var bottom;
var friction = 0.85;
function setup() {
	bottom = width;
  createCanvas(400, 400, WEBGL);
  newSet(0,0,0);
}
function mousePressed(){
	newSet(mouseX - (width / 2),mouseY - (width / 2),0);
  // noprotect
}
function draw() {
  if(keyIsDown(RIGHT_ARROW))
  	rotation ++;
  else if(!hold)
    rotation = 0;

  if(keyIsDown(UP_ARROW))
  	hold = true;
  else
    hold = false;

  if(keyIsDown(LEFT_ARROW))
  	rotation --;
  else if(!hold)
    rotation = 0;

  background(220);
//  rotateY((mouseX / (PI * 64)) - width / 2);
  rotateY(rotation / (PI * 2));
  for(i = 0;i < balls.length;i++){
  	balls[i].frame();
    if(balls[i].lifetime <= 0){
      balls.splice(i, 1);
    }
  }
}'

never works on any browser

**Comment by explodingdigg** [comment]
i just get nothing, the page never loads. but when it does it basically says "WEBGL loaded"

**Comment by explodingdigg** [comment]
does p5.min.js change anything? try using regular p5.js, does that still work?

**Comment by lmccart** [comment]
@explodingdigg it's difficult to debug a large block of code like this. please reopen this issue with an isolated snippet of code that illustrates the problem. this debugging guide may be helpful: http://p5js.org/tutorials/debugging.html

**Comment by dg92** [comment]
@bulbil @lmccart I am stuck at this error :  
"Error: Error: Error creating webgl context" 

when i am doing   
createCanvas(800, 600, WEBGL);

please let me know the workaround. I am trying hard to learn this awesome library.
