### ISSUE TITLE
Firefox: Low performance + error on displaying a box with a texture 

### ISSUE THREAD

**Issue by timrodenbroeker** [processing/p5.js#1796]
````
function draw() {
texture(img1png);
box(height/2);
}
````

Hi folks! I get this following error-message in Firefox, when i run my sketch: 

`Error: WebGL: texImage2D: Conversion requires pixel reformatting.` 

The problem seems to cause, that the sketch is rendered on the CPU instead of the GPU. I have tested this with a more complex scene, Firefox i extremely slow in comparison with chrome. 

Looks like p5.js WEBGL-textures are not ready for Firefox, yet?

**Comment by timrodenbroeker** [comment]
<img width="1280" alt="bildschirmfoto 2017-02-05 um 15 25 06" src="https://cloud.githubusercontent.com/assets/6288566/22627135/32cf2a6a-ebbd-11e6-9470-30b4a12333ec.png">

**Comment by mlarghydracept** [comment]
Seems like a common problem that doesn't have a good solution yet. [Three.js](https://github.com/mrdoob/three.js/issues/9109) is having the same problem and [Mozilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1246410) is aware of it.

**Comment by mlarghydracept** [comment]
This issue is no longer popping up on the latest release of Firefox when checked with your example code or the texture test examples for p5. 

I am going to close for now. If I am mistaken and the issue is still present just comment here and I'll reopen.
