### ISSUE TITLE
saveJSON and saveCSV not working

### ISSUE THREAD

**Issue by fepegar** [processing/p5.js#1797]
Hi all!

When I try to save a JSON or a CSV file, my sketch will automatically save an almost empty file (6 B) if I have preloaded something before. I'm using the desktop editor.

Working example: if you set `wontWork = false`, the code will run as expected and the browser will ask me for a location for my file (or, if Chrome, "download" it).

```
var img;
var wontWork = true;

function preload() {
  if(wontWork) {
    img = loadImage('http://hello.p5js.org/assets/p5-sq-reverse.svg');
  }
}

function setup() {
  if(wontWork) {
    createCanvas(img.width, img.height);
    image(img, 0, 0);
  }
  table = new p5.Table();
  table.addColumn('id');
  table.addColumn('species');
  table.addColumn('name');

  var newRow = table.addRow();
  newRow.setNum('id', table.getRowCount() - 1);
  newRow.setString('species', 'Panthera leo');
  newRow.setString('name', 'Lion');

  // To save, un-comment next line then click 'run'
  saveTable(table, 'new.csv');
}
```

Fernando

**Comment by lmccart** [comment]
Yeah, this is a known bug in the editor. :( The editor has been deprecated and is no longer recommended for use, if you are looking for alternatives, you might try some of these: https://github.com/processing/p5.js-editor#this-editor-has-been-deprecated-we-will-not-be-making-further-releases-we-are-turning-our-energy-toward-a-web-editor-which-will-be-released-later-this-year-for-now-we-recommend-using-editors-like-brackets-atom-sublime-text-or-openprocessing
