### ISSUE TITLE
mouseX/mouseY not working in iframe

### ISSUE THREAD

**Issue by epic8009** [processing/p5.js#1798]
Works fine outside of an iframe, but will not work in an iframe!
Using firefox, HTML5, CSS3.
Here is the style used for this iframe:
iframe{
  height:100%;
  width:100%;
  position:fixed;
  z-index:-1;
  margin:0px;
  padding:0px;
}
If there is a solution, let me know, as this is pretty much ruining everything.

**Comment by limzykenneth** [comment]
Hi, @epic8009. What did you mean by not working? Are they not returning any values at all or returning unexpected values or something else? A minimal sample of the code demonstrating the problem would be great as well. Thanks

**Comment by epic8009** [comment]
Returns 0.
```
function draw() {
  background(0);
  var start=millis();
  for(var y=0;y<25;y++){
  for(var x=0;x<25;x++){
    stroke(255,0,0)
    line(x*(width/25),y*(height/25),mouseX,mouseY);
}
}
var end=millis();
console.log(end-start);
}
function windowResized() {
  resizeCanvas(windowWidth, windowHeight);
}

```
Try outside iframe, then try inside iframe. Outside iframe, it works. Inside iframe, it doesnt.

**Comment by feedzh** [comment]
Hi,

Try take "position: absolute;" of the iframe away. It worked for me. If you need it, then perhaps you can set iframe dimensions via JS. This you need to do in the container and not inside the iframe.

**Comment by epic8009** [comment]
ok  but i dont get it

**Comment by epic8009** [comment]
EDIT: tried using position:fixed outside the iframe, it works fine there. the issue is the iframe.

**Comment by feedzh** [comment]
actually the issue is z-index: -1:D If you put it to positive or 0 it works.

**Comment by epic8009** [comment]
wait wat XD

**Comment by epic8009** [comment]
```
div{
  position:absolute;
  margin:0px;
  padding:0px;
  z-index:2;
}
h1{
  color:white;
  margin:0px;
  padding:0px;
  z-index:2;
}
body{
  margin:0px;
  padding:0px;
  width:100%;
  height:300%;
  z-index:2;
}
iframe{
  height:100%;
  width:100%;
  position:fixed;
  z-index:0;
  margin:0px;
  padding:0px;
}
center {
  z-index:2;
}
```
the iframe still covers everything up

**Comment by feedzh** [comment]
center has positioning?

**Comment by epic8009** [comment]
some things are inside a <center>

**Comment by epic8009** [comment]
some things are inside a `center`

**Comment by epic8009** [comment]
idk if it makes a difference

**Comment by feedzh** [comment]
you basically want a background xontent inside center that scrolls ... right?

**Comment by epic8009** [comment]
the bg isnt inside center. but pretty much. and its working, except the iframe covers everything

**Comment by feedzh** [comment]
http://www.w3schools.com/css/css_positioning.asp

`
center {
  position: relative;
  z-index:2;
}
`

**Comment by epic8009** [comment]
now im back to not being able to detect mouseX and mouseY with that line added

**Comment by feedzh** [comment]
And btw this error has nothing to do with p5. The problem is more about how browsers are handling events with z-index: [negative]

**Comment by epic8009** [comment]
ok... but nothings negative anymore, so uhh.

**Comment by feedzh** [comment]
So for others as an explanation:

Somehow when iframe's z-index is negative, global mouse events fail to fire. Including clicks.

Here is fail example. By changing z-index to positive - click fires.

global document:
```html
<html>
<head>
  <style> body {padding: 0; margin: 0;}
  iframe{
      height:100%;
      width:100%;
      position:fixed;
      z-index:-1;
      margin:0px;
      padding:0px;
  }
  </style>
</head>
    <iframe src="index.html" id="myIframe"></iframe>
<body>
</body>
</html>
```

iframe:
```html
<html>
<head>
  <meta charset="UTF-8">
  <script language="javascript" type="text/javascript" src="libraries/p5.js"></script>
  <!-- uncomment lines below to include extra p5 libraries -->
  <script language="javascript" src="libraries/p5.dom.js"></script>
  <!--<script language="javascript" src="libraries/p5.sound.js"></script>-->
  <script language="javascript" type="text/javascript" src="sketch.js"></script>
  <!-- this line removes any default padding and style. you might only need one of these values set. -->
  <style> body {padding: 0; margin: 0;} </style>
  <script>
  function showCoords(event) {
      console.log("click");
      var x = event.clientX;
      var y = event.clientY;
      console.log("x: "+x+" y: "+y);
  }
  </script>
</head>

<body onclick="showCoords(event)">
</body>
</html>
```

**Comment by epic8009** [comment]
but.. for me if its positive it goes over everything regardless of their z index, and if i make the center have a higher z index even with positive it wont fire

**Comment by feedzh** [comment]
@epic8009 do you need a iframe?

On my test it works. But it is better without iframe.

**Comment by feedzh** [comment]
without iframe.

[index.html.zip](https://github.com/processing/p5.js/files/757419/index.html.zip)

**Comment by epic8009** [comment]
id prefer an iframe, so i can easily change the src

**Comment by epic8009** [comment]
heres a zip with everything im doing: the things im talking about are sketch2, bg2 and index2.
[over here](https://github.com/processing/p5.js/files/757480/website-bg.zip)

**Comment by feedzh** [comment]
it is working, except when mouse is over other element.

I dont see the problem of adding 2 lines of script in the head and couple of lines in style.css

Anyway .... i am in the good mood: 
[website-bg.zip](https://github.com/processing/p5.js/files/757513/website-bg.zip)

Better to forget iframes. We are not living in the 90s :P

**Comment by epic8009** [comment]
i like iframes tho :(

**Comment by feedzh** [comment]
then google is your best friend. This thread has gone off topic, since it has nothing to do with p5.

**Comment by epic8009** [comment]
ok srry, and thanks for the help! i probably shouldnt use iframes. guess ill have to find another way to switch bgs!

**Comment by feedzh** [comment]
Ho do you want to switch them ... randomly or ...?

**Comment by epic8009** [comment]
<select>, but i think i already know how to do that

**Comment by lmccart** [comment]
thanks @feedzh!
