### ISSUE TITLE
Offline Reference does not work offline

### ISSUE THREAD

**Issue by jtoy** [processing/p5.js#1799]
in p5js, under the help menu there is a link called Offline Reference. It is not an offline reference as it does not work offline. The docs require an internet connection to work. if there is no internet connection, you cannot use the Offline Reference.
the page tries to load all of these javascript libraries that are online:

```
Failed to load resource: net::ERR_FILE_NOT_FOUND
https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js Failed to load resource: net::ERR_INTERNET_DISCONNECTED
https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js Failed to load resource: net::ERR_INTERNET_DISCONNECTED
https://cdnjs.cloudflare.com/ajax/libs/backbone.js/1.3.3/backbone-min.js Failed to load resource: net::ERR_INTERNET_DISCONNECTED
file:///Applications/p5.app/Contents/Resources/app.nw/mode_assets/p5/p5-reference/js/vendor/jquery-1.9.1.min.js Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///Applications/p5.app/Contents/Resources/app.nw/mode_assets/p5/p5-reference/js/vendor/underscore-min.js Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///Applications/p5.app/Contents/Resources/app.nw/mode_assets/p5/p5-reference/js/vendor/backbone-min.js Failed to load resource: net::ERR_FILE_NOT_FOUND
main.js:1 Uncaught ReferenceError: $ is not defined
reference.js:4765 Uncaught ReferenceError: _ is not defined
require.min.js:8 Uncaught Error: Module name "nw.gui" has not been loaded yet for context: _. Use require([])
```
Here is a picture showing the problem:
https://cl.ly/1B002u3b0l1Q

The Offline Reference mode should work Offline.

**Comment by bmoren** [comment]
Hi, I implemented the offline reference into the p5.js editor, but unfortunately the editor has been deprecated. I suggest that you use the official offline reference available as a standalone .zip archive at the top of the p5 reference page here: http://p5js.org/reference/

Just double click the index.html, and you're good to go!

Seeing as the editor is now deprecated in favor of a upcoming web editor, this will likely be the best way to get offline documentation in the future, especially as this version is rebuilt when p5js is.

**Comment by lmccart** [comment]
thanks @bmoren!
