### ISSUE TITLE
function getMousePos is throwing error when evt.touches.length == 0

### ISSUE THREAD

**Issue by chrisallick** [processing/p5.js#1800]
I noticed that an error was being thrown when i clicked my screen. Specifically inside mobile simulator on Chrome and in Safari simulator. The source of hte problem seems to be the getMousePos function.

Attaching some images. The last image is the fix I added. Not sure it's a robust fix:

```
function getMousePos(canvas, w, h, evt) {
  if (evt && !evt.clientX) { // use touches if touch and not mouse
    if (evt.touches && evt.touches.length > 0) { // check for non-empty array *shrug*
      evt = evt.touches[0];
    } else if (evt.changedTouches) {
      evt = evt.changedTouches[0];
    }
  }
  var rect = canvas.getBoundingClientRect();
  var sx = canvas.scrollWidth / w;
  var sy = canvas.scrollHeight / h;
  return {
    x: (evt.clientX - rect.left) / sx,
    y: (evt.clientY - rect.top) / sy,
    winX: evt.clientX,
    winY: evt.clientY,
    id: evt.identifier
  };
}
```

![screen shot 2017-02-07 at 12 19 25 pm](https://cloud.githubusercontent.com/assets/378073/22702989/917ea74c-ed30-11e6-972b-b897e1191180.png)
![screen shot 2017-02-07 at 12 12 55 pm](https://cloud.githubusercontent.com/assets/378073/22702988/917e86d6-ed30-11e6-83d0-9a4eadd9a663.png)
![screen shot 2017-02-07 at 12 22 43 pm](https://cloud.githubusercontent.com/assets/378073/22702990/9180494e-ed30-11e6-93b3-c0fdf87de068.png)

**Comment by lmccart** [comment]
I think this has been fixed with this pr: https://github.com/processing/p5.js/pull/1787. I'm working on getting a new release out this week.
