### ISSUE TITLE
Dom video capture example and POSTERIZE filter

### ISSUE THREAD

**Issue by jedahan** [processing/p5.js#1801]
The docs say we can use `filter('POSTERIZE')`, but when we tried editing http://p5js.org/examples/dom-video-capture.html it uh, just showed a blank video screen.

**Comment by lmccart** [comment]
posterize requires a second parameter that is the number of colors to limit to. for example:
```javascript
var capture;

function setup() {
  createCanvas(390, 240);
  capture = createCapture(VIDEO);
  capture.size(320, 240);
  //capture.hide();
}

function draw() {
  background(255);
  image(capture, 0, 0, 320, 240);
  filter('POSTERIZE', 3);
}
```

**Comment by jedahan** [comment]
Would you be open to a pull request that sets an arbitrary default to 3? Either way, I should update the filter docs to have a `POSTERIZE` example.

**Comment by lmccart** [comment]
There is an example in the filter docs already. I think a default to 3 and updating the docs to reflect that makes sense, I'd welcome a PR.
