### ISSUE TITLE
textFont(loadedFont) does not work on a created graphics object

### ISSUE THREAD

**Issue by noncom** [processing/p5.js#1805]
Trying to set a font on a graphics, created with `createGraphics()` does not work. Instead it looses the text font and the text size.

PS: Could there be any quick workaround for this?

**Comment by noncom** [comment]
Oops, that's me being noob on web development. Spent like an hour on this. Turns out to be there is some weird delay before the browser loads the fonts. Ugh.

**Comment by limzykenneth** [comment]
If you are loading in external fonts, remember to load them in in the [`preload()`](https://github.com/processing/p5.js/wiki/p5.js-overview#preload) function
