### ISSUE TITLE
rect: left side is fuzzy. Drawn twice?

### ISSUE THREAD

**Issue by ChristerNilsson** [processing/p5.js#1806]
![skarmklipp](https://cloud.githubusercontent.com/assets/3437195/22868270/416e35d4-f194-11e6-8043-341875660489.JPG)

This is reproduced on two different Win7 computers.

**Comment by ChristerNilsson** [comment]
Error reproduced on Chrome.
Works correct on Edge.
Click on image.
![skarmklipp](https://cloud.githubusercontent.com/assets/3437195/22868555/9ecf4cba-f197-11e6-92c8-7002ed0cad75.JPG)

**Comment by limzykenneth** [comment]
Is it possible to be some subpixel rendering issue? @ChristerNilsson Is the screen you are using a high density display, could that be a factor?

**Comment by ChristerNilsson** [comment]
The lowest resolution I'm using is 1920x1080.
The other one is 2560x1440.
iPad rect renders ok in Safari. 768x1024.
Please note: renders ok in Edge at 2560x1440
This seems to be Chrome related.

**Comment by ChristerNilsson** [comment]
Firefox misbehaves in a slightly different way. 
The left edge is ok at the top and the problem grows going south.
1920x1080.
![skarmklipp](https://cloud.githubusercontent.com/assets/3437195/22881410/98904ca6-f1e6-11e6-88e8-05d7bfd58e76.JPG)

**Comment by ChristerNilsson** [comment]
Sorry, I'm using IE11, not Edge. Using W7.

**Comment by ChristerNilsson** [comment]
This problem is only visible using strokeWeight 1

**Comment by giltayar** [comment]
This looks OK on Chrome MacOS (latest version), even when using strokeWeight(1)

**Comment by ChristerNilsson** [comment]
I tried the following non-p5 code in Chrome on W7. No problem.

var c = document.getElementById("myCanvas");
var ctx = c.getContext("2d");
ctx.rect(20, 20, 150, 100);
ctx.stroke();

I also tried original p5 problem on iPad Chrome. No problem

**Comment by lmccart** [comment]
my guess is that this has to do with how antialiasing is approached on different systems. that's vague, I know. but maybe a starting point for investigation.

**Comment by ChristerNilsson** [comment]
I tried smooth() and noSmooth() before rect() on W7 Chrome.
No difference at all.

**Comment by lmccart** [comment]
http://www.mobtowers.com/html5-canvas-crisp-lines-every-time/

**Comment by ChristerNilsson** [comment]
Spot on.

This renders perfect.
rect(30.5, 20, 55.5, 55);

Still, should it be handled by the programmer or p5?

**Comment by lmccart** [comment]
My hunch is leave it to the programmer so we can preserve performance... in many cases this won't be necessary. But it could be good to add a link to one of these:
https://github.com/processing/p5.js/wiki/p5.js-overview
https://github.com/processing/p5.js/wiki/Frequently-Asked-Questions

**Comment by ChristerNilsson** [comment]
StrokeWeight 2 and 3 does not have this problem.

**Comment by ChristerNilsson** [comment]
All four sides blurred: rect(20, 20.5, 55.5, 55);
All four sides perfect: rect(20.5, 20, 55.5, 55);

Would be nice if x and y behaved the same.

Also strange that x=20.5 renders ok, but 20+55.5 does not.

line (20, 20, 20, 55); renders ok.
line (20.5, 20, 20.5, 55); does not.

Strange that this workaround is needed:
rect = (x,y,w,h) ->
	line x,y,x+w,y
	line x,y+h,x+w,y+h
	line x+w,y,x+w,y+h
	line x,y+h,x,y

**Comment by ChristerNilsson** [comment]
p5.js, p5.Renderer2D.prototype.rect

I made this change:

```
    //ctx.rect(vals.x, vals.y, vals.w, vals.h);

    ctx.beginPath();
    ctx.moveTo(_x, _y);
    var _x = vals.x;
    var _y = vals.y;
    var _w = vals.w;
    var _h = vals.h;
    ctx.lineTo(_x + _w, _y, _x + _w, _y + _h); // first call.
    ctx.lineTo(_x + _w, _y + _h, _x, _y + _h);
    ctx.lineTo(_x, _y + _h, _x, _y);
    ctx.lineTo(_x, _y, _x + _w, _y);
    ctx.lineTo(_x + _w, _y, _x + _w, _y + _h); // second call.
    ctx.closePath();
```
This fixes the issue, almost. 
ctx.lineTo is called five times, as the first line is not ok.
But this makes the upper, right corner pixel white.

Anyway, the new code seem to render better.

**Comment by ChristerNilsson** [comment]
I think ctx.rect on W7 is to blame, as my patch solved the Firefox issue as well.

**Comment by lmccart** [comment]
This change works, but I believe it would slow things down considerably, see this performance test:
https://jsperf.com/rect-vs-lineto/1

For now, I'd like to leave things as is and leave it up to the developer to account for this fuzzy edge if it effects what they are doing.
