### ISSUE TITLE
p5.Delay causing audio to stop.

### ISSUE THREAD

**Issue by CosmicChild** [processing/p5.js#1808]
Hi!
I'm getting an error from the sound library when trying to update the feedback value of a p5.delay object, which makes all the sound in my sketch to stop and there's no  way back except for reloading.
Also, the delay object doesn't seem to work properly from the beginning. At times it works and at times it doesn't, but without sending any error messages. Until it really crashes and all audio stops.

This is the error that I see in the console when it happens:

```
p5.sound.js:6460 

NavigatorUserMediaErrorconstraintName: ""
message: "Only secure origins are allowed (see: https://goo.gl/Y0ZkNV).
"name: "PermissionDeniedError"
__proto__: NavigatorUserMediaError

window.navigator.getUserMedia._onStream

Error @ p5.sound.js:6460
```

There are no problems at all when I test it in the p5 editor, only when I load it in a browser.

Thanks!

**Comment by b2renger** [comment]
Hi @CosmicChild 

I ran in the same error when using the delay. I took a look at the implementation but could not really find any clues on how to fix this. I ended up using the delay from tuna.js

@therewasaguy btw about the effect in p5.sound I was wondering how hard it would be to include tuna.js as it is done with tone.js

**Comment by CosmicChild** [comment]
Thankyou @b2renger 
Do you by any chance have an example code on how you integrated tuna.js into a p5 sketch?
Is it enough to just paste the tuna library into my lib folder?

Thank you!

**Comment by b2renger** [comment]
Yep paste the tuna lib and then you can do something like this

``` javascript
    ctx = getAudioContext()
    var tuna = new Tuna(ctx);
    delay = new tuna.Delay({
        feedback: 1, //0 to 1+
        delayTime: 2500, //1 to 10000 milliseconds
        wetLevel: 0.80, //0 to 1+
        dryLevel: 0.80, //0 to 1+
        cutoff: 2500, //cutoff frequency of the built in lowpass-filter. 20 to 22050
        bypass: 0
    });
    delay.disconnect()
    synthOut.connect(this.delay); // connect any object here
    delay.connect(p5.soundOut) 
```

and you can set params like this :
```
 delay.delayTime = 500
``` 

Cheers !

**Comment by CosmicChild** [comment]
Thanks! I've just tried it using the "Load and Play Sound" example in p5 editor, to do something simple.

This is my code:

```
var song;

function setup() {
  song = loadSound('assets/lucky_dragons_-_power_melody.mp3');
  song.disconnect();
  createCanvas(720, 200);
  background(255,0,0);
  var context = getAudioContext();
  var tuna = new Tuna(context);  

  var delay = new tuna.Delay({
        feedback: 0.5, //0 to 1+
        delayTime: 167, //1 to 10000 milliseconds
        wetLevel: 0.80, //0 to 1+
        dryLevel: 0, //0 to 1+
        cutoff: 2000, //cutoff frequency of the built in lowpass-filter. 20 to 22050
        bypass: 0
  });   
  delay.disconnect();
  song.connect(this.delay); // connect any object here
  delay.connect(p5.soundOut); 
}

function mousePressed() {
  if ( song.isPlaying() ) { // .isPlaying() returns a boolean
    song.stop();
    background(255,0,0);
  } else {
    song.play();
    background(0,255,0);
  }
}
```

However, although it doesn't send an error message and the sound actually goes trough the delay (I added a song.disconnect() line), it doesn't create the delay effect. I've tried changing all the values, but no luck....

**Comment by CosmicChild** [comment]
Thanks! I actually needed to change the line

`synthOut.connect(this.delay);`

for

`synthOut.connect(delay.input);`

but it's working now

**Comment by b2renger** [comment]
great ! I actually scraped the code from a class and first time I left the 'this' then edited. So it's my fault sorry :)
