### ISSUE TITLE
Adding functionalities with external libraries

### ISSUE THREAD

**Issue by b2renger** [processing/p5.js#1809]
As I work with p5js and p5.sound I often need to use external libraries. For instance :

- p5.sound doesn't have out of the box polyphonic synth (as it turns out implementing something simple and flexible enough is hard) so I often end up using : https://github.com/danigb/soundfont-player

- we don't have musical theory stuff, like chords, scales etc. I found this : https://github.com/danigb/tonal

- we don't have many effects whether tuna.js has a lot : https://github.com/Theodeus/tuna

The core  is pretty stable and provides many functionnalities and it may be tricky to include that many others libraries that might break at some point. 

Would it be easy to include wrappers for those libs ? or would it make more sense to make other libs ? How could we efficiently share what has to be shared between those (namely the audio context and maybe other stuff).

**Comment by lmccart** [comment]
thanks @limzykenneth!
