### ISSUE TITLE
Providing methods on Sketch

### ISSUE THREAD

**Issue by hughrawlinson** [processing/p5.js#1816]
I'm wondering if there's a documented correct way for a sketch to communicate with the outside world, without relying on global mutable state?

In particular, say I've got a sketch:

```javascript
const sketch = function(p) {
  let onDrawHandler = null;
  p.onDraw = function(handler) {
    onDrawHandler = handler;
  }
  p.draw = function() {
    if (onDrawHandler && typeof onDrawHandler === 'function') {
      onDrawHandler('A frame was drawn');
    }
  }
}
```

instantiated with

```javascript
const sketchInstance = new p5(sketch, 'container');
sketchInstance.onDrawHandler(e=>{
  console.log(e);
});
```

This allows me to register a handler on the sketch (or perform all kinds of other interactions with outside Javascript). I wanted to check if this is considered a feature or a bug? Can I rely on it being available in future versions of p5, or is it a side-effect of the way in which you construct your sketch objects? If the latter, is there a more correct way of having a sketch interact with external code?

Separately, is there documentation for communicating with external code already, or can I help out with that?

**Comment by hughrawlinson** [comment]
Relatedly - is there a way of passing data to the sketch on its construction? Or should I handle that with lexical scoping in the sketch definition?

**Comment by lmccart** [comment]
this behavior is intended, though it is something of a side effect. it becomes especially useful in removing/cleaning up sketches. for instance:

```javascript
const sketchInstance = new p5(sketch, 'container');
setTimeout(function() { sketchInstance.remove() }, 5000);
```

we are still below 1.0 so I wouldn't say "rely on it", but there are no plans to remove it.  any documentation help for this and communicating with external code in general would be much appreciated. I think adding a page to the wiki would make sense, and perhaps linking to it from the setup() reference page.

there's not currently a way to pass data in directly to sketch creation, though there are these hooks which could be useful/related? https://github.com/processing/p5.js/wiki/Libraries#use-registermethod-to-register-functions-with-p5-that-should-be-called-at-various-times
I'm open to adding a hook or way to do it more directly that if you have a proposal.
