### ISSUE TITLE
Problem with ellipse()

### ISSUE THREAD

**Issue by ahenningsson** [processing/p5.js#1821]
Hello,

As the reference in p5.js says "If no height is specified, the value of width is used for both the width and height.". This doesnt work for me. When I write "ellipse(location.x, location.y, diameter);" where the diameter is "float diameter = 48; it doesnt compile.

It says the "The method ellipse(float,float,float,float) etc.". Have I done anything wrong?

**Comment by lmccart** [comment]
are you using processing or p5.js?

**Comment by ahenningsson** [comment]
oh my.. Sorry, my brain is malfunctioning. Never mind, I'll delete this thread! Thank you
