### ISSUE TITLE
textToPoints vs textAlign

### ISSUE THREAD

**Issue by seamiki** [processing/p5.js#1824]
Playing around with a tutorial by Daniel Shiffman I found that the textToPoints function is inconsistent with the textAlign function.
Having the textAlign(CENTER) will not influence the position of the points that will be placed by textTo Points according to the default text allinment.

**Comment by WIPocket** [comment]
Yes, but you only get the points with a set offset, so you can just do that manualy by changing it (or by offseting while drawing)

**Comment by dhowe** [comment]
I'm not sure I agree. My thinking when I wrote this function was that b/c textToPoints is part of the p5.Font object, it should not take the current canvas state into account (it is not using the current textFont, so why use other properties of the drawing state?) If we want a textToPoints() that does use  current state, then I would probably argue for making it a full-fledged p5.js function (p5.Renderer.prototype.textToPoints) called simply as textToPoints(str, x, y). Though this is an API change... @lmccart ?

**Comment by lmccart** [comment]
@dhowe I agree with the thought to make it canvas-agnostic and keep it as part of the p5.Font object. I think it's a fairly specific function and makes more sense within that object rather than at the top level API

**Comment by prtysh** [comment]
If this was the desired function, should this issue be closed?

**Comment by lilijialiang** [comment]
I also have the same question about this problem. When I describe the font, I also want to get the points that coincide with the font. What should I do?

**Comment by dhowe** [comment]
Can you clarify your question @lilijialiang ? Are you saying that you want to draw text with the font at a certain size AND get the points for the same text/size? I think this is what the [reference example](https://p5js.org/reference/#/p5.Font/textBounds) shows...

**Comment by dhowe** [comment]
@prtysh otherwise I think this can be closed
