### ISSUE TITLE
Audio input examples not working - p5.sound.js

### ISSUE THREAD

**Issue by zloysmiertniy** [processing/p5.js#1832]
Crossorigin is one thing, but not allowing audio input to work if the site has no secure http sounds excesive to me. The examples in your page stopped working and I haven't tried locally. So what to do if you have a simple site with examples or some interactive page that required the browser to capture the microphone and now you cant use it?

I get `NavigatorUserMediaError
constraintName
:
""
message
:
"Only secure origins are allowed (see: https://goo.gl/Y0ZkNV)."
name
:
"PermissionDeniedError"`

when calling audioIn(). Is there a workaround?

It seems this only happens in chrome. I am able to call it in Firefox

**Comment by limzykenneth** [comment]
This is a decision made a while ago by the Chrome developers. The main reasoning is user privacy and such not allowing features such as cameras and microphones to be activated without https. It should still work if you are running a local server and p5js.org can be visited on https://p5js.org as well.

If you want to deploy there are a few options. If it is possible for you, getting a certificate to use https is free if you get it from [Let's Encrypt](https://letsencrypt.org), many hosting vendors have it built in as well that can handle all the setup for you. If you don't care about having a custom hosting and a custom domain, I use [surge.sh](https://surge.sh) to deploy front end only sites onto their free `*.surge.sh` domain which all comes with free https already setup.

Other than these, you can run the sketch in Firefox but it's not sure how long Firefox will still allow this...
