### ISSUE TITLE
Adding sound and playing when mousePressed

### ISSUE THREAD

**Issue by benslack** [processing/p5.js#1835]
The error code showing is:

There was no response from the server at 
https://drive.google.com/open?id=0B_lYm3ibm_awNi1rM0xsTEdaZ3M
 Check the url and internet connectivity. The error stack trace includes: loadSound at preload (about:srcdoc:61:10)

I want to make the sound file play when the mouse is Pressed. The canvas screen when running the code just displays Loading. To create the code I am using the alpha editor in p5.

`
// javascript program showing a snakes and ladders game

var counterX = 25; // declaring the beginning of the counters x axis location
var counterY = 475; // declaring the counters starting y axis location
var directionX = 1; // the direction in which the counter travels is from left to right
var diceRoll = 0; // setting the number which the dice rolled to 0 at the start
var gridInterval = 50; // the length between each counter space or grid line is 50
var gridWidth = 500; // how long the grid is
var gridHeight = 500; // how tall the grid is
var jump;

function preload() {
		jump = loadSound("https://drive.google.com/open?id=0B_lYm3ibm_awNi1rM0xsTEdaZ3M");
}

function setup() { // declaring what needs to be done when setting up the game
	  	createCanvas(gridWidth, gridHeight); // creates a canvas with a size of 500x500
    noLoop(); // stops draw() from repeating
}

function draw() { //what needs to be drawn
		    background(200); // sets how dark the canvas is
	    drawGrid(); // says that a grid needs to be drawn
    	counterX = counterX + (directionX * diceRoll * gridInterval); // update counter position along x-axis  = + on how far it needs to move along

if (counterY == 25 & (counterX < gridInterval / 2)) { // if the counter is on the top row and the x co-ordinate is less than 25
		counterX = 25; // change the x co-ordinate to 25 so the counter is in the 100 square
		}

else if (counterX < (gridInterval / 2)) { // if the x co-ordinate is less than 25
	counterX = (gridinterval / 2);
 counterY = counterY - gridInterval; // update y co-ordinate by taking 50 away (moving counter up a row)
	directionX = 1; // direction which counter follows is from left to right
		}
	
	else if (counterX > gridWidth){ // if the x co-ordinate is more than the width of the board
		counterX = gridWidth - (gridInterval / 2); // change the x co-ordinate to 475
		directionX = 1; // change the direction the counter is travelling so it goes from right to left
		counterY = counterY - gridInterval; // move the counter up a row
		}
		
ellipse(counterX, counterY, 20,20); // counters x co-ordinate is counterX, counters y co-ordinate is counterY + width + height of counter are constant
}

function mousePressed() { // only execute draw when mouse is pressed
		jump.play();
		diceRoll = Math.floor(Math.random() * 7); // Math.random takes a decimal below 1 and times it by 7 giving an answer less than 7
		function randomWholeNum() { // this number is then converted into a whole number
				return Math.random() // this is then returned giving the number which the dicerolled
}
		
if (counterX == 25 & counterY == 475) { // if the counter is on space 1
		counterX = counterX + (gridInterval * 2); // adding 100 to the x co-ordinate (moves the counter 2 spaces left)
		counterY = counterY - (gridInterval * 3); // minusing 150 to the y co-ordinate (moves the counter 3 spaces up)
	return counterX & counterY; // updating the new co-ordinates of the counter
} // moves the counter to space 38
else if (counterX == 175 & counterY == 475) { // if the counter is on space 1
		counterX = counterX + (gridInterval * 3); // adding 150 to the x co-ordinate (moves the counter 3 spaces left)
		counterY = counterY - gridInterval; // minusing 50 to the y co-ordinate (moves the counter 1 space up)
	return counterX & counterY; // updating the new co-ordinates of the counter
} // moves the counter to space 14
else if (counterX == 425 & counterY == 475) { //if the counter is on space 9
		counterX = counterX + gridInterval; // adding 50 to the x co-ordinate (moves the counter 1 space left)
		counterY = counterY - (gridInterval * 3); // minusing 150 to the y co-ordinate (moves the counter 3 spaces up)
	return counterX & counterY; // updating the new co-ordinates of the counter
} // moves the counter to space 31
else if (counterX == 175 & counterY == 425) { // if the counter is on space 17
		counterX = counterX + (gridInterval * 3); // adding 150 to the x co-ordinate (moves the counter 3 spaces left)
		counterY = counterY - gridInterval; // minusing 50 to the y co-ordinate (moves the counter 1 space up)
	return counterX & counterY; // updating the new co-ordinates of the counter
} // moves the counter to space 7
else if (counterX == 25 & counterY == 375) { // if the counter is on space 21
		counterX = counterX + gridInterval; // adding 50 to the x co-ordinate (moves the counter 1 space left)
		counterY = counterY - (gridInterval * 2); //minusing 100 to the y co-ordinate (moves the counter 2 spaces up)
	return counterX & counterY; // updating the new co-ordinates of the counter
} // moves the counter to space 42
else if (counterX == 375 & counterY == 375) { // if the counter is on space 28
		counterX = counterX - (gridInterval * 4); // minusing 200 to the x co-ordinate (moves the counter 4 spaces right)
		counterY = counterY - (gridInterval * 6); // minusing 300 to the y co-ordinate (moves the counter 6 spaces up)
	return counterX & counterY; // updating the new co-ordinates of the counter
} // moves the counter to space 84
else if (counterX == 475 & counterY == 225) { // if the counter is on space 51
		counterX = counterX - (gridInterval * 3); // minusing 150 to the x co-ordinate (moves the counter 3 spaces right)
		counterY = counterY - gridInterval; // minusing 50 to the y co-ordinate (moves the counter 1 space up)
		return counterX & counterY; // updating the new co-ordinates of the counter
} // moves the counter to space 67
else if (counterX == 325 & counterY == 225) { // if the counter is on space 54
		// the x co-ordinate stays the same
		counterY = counterY + (gridInterval * 2); // adding 100 to the y co-ordinate (moves the counter 2 spaces down)
		return counterX & counterY; // updating the new co-ordinates of the counter
} // moves the counter to space 34
else if (counterX == 375 & counterY == 175) { // if the counter is on space 63
		// the x co-ordinate stays the same
		counterY = counterY + (gridInterval * 5); // adding 250 to the y co-ordinate (moves the counter 5 spaces down)
		return counterX & counterY; // updating the new co-ordinates of the counter
} // moves the counter to space 18
else if (counterX == 325 & counterY == 175) { // if the counter is on space 64
		counterX = counterX - (gridInterval * 3); // minusing 150 to the x co-ordinate (moves the counter 3 spaces right)
		counterY = counterY + gridInterval; // adding 50 to the y co-ordinate (moves the counter 1 space doewn)		return counterX & counterY; // updating the new co-ordinates of the counter
} // moves the counter to space 60
else if (counterX == 425 & counterY == 125) { // if the counter is on space 72
		counterX = counterX + gridInterval; // adding 50 to the x co-ordinate (moves the counter 1 space right)
		counterY = counterY - (gridInterval * 2); // minusing 100 to the y co-ordinate (moves the counter 2 spaces up)
		return counterX & counterY; // updating the new co-ordinates of the counter
} // moves the counter to space 91
else if (counterX == 25 & counterY == 125) { // if the counter is on space 80
		counterX = counterX + gridInterval; // adding 50 to the x co-ordinate (moves the counter 1 space right)
		counterY = counterY - (gridInterval * 2); // minusing 100 to the y co-ordinate (moves the counter 2 spaces up)
		return counterX & counterY; // updating the new co-ordinates of the counter
} // moves the counter to space 99
else if (counterX == 325 & counterY == 125) { // if the counter is on space 87
		counterX = counterX - (gridInterval * 2); // minusing 100 to the x co-ordinate (moves the counter 2 spaces left)
		counterY = counterY + (gridInterval * 5); // adding 250 to the y co-ordinate (moves the counter 5 spaces down)
		return counterX & counterY; // updating the new co-ordinates of the counter
} // moves the counter to space 36
else if (counterX == 425 & counterY == 25) { // if the counter is on space 92
		counterX = counterX - gridInterval; // minusing 50 to the x co-ordinate (moves the counter 1 space left)
		counterY = counterY + (gridInterval * 2); // adding 100 to the y co-ordinate (moves the counter 2 spaces down)
		return counterX & counterY; // updating the new co-ordinates of the counter
} // moves the counter to space 73
else if (counterX == 275 & counterY == 25) { // if the counter is on space 95
		//the x co-ordinate stays the same
		counterY = counterY + (gridInterval * 2); // adding 100 to the y co-ordinate (moves the counter 2 spaces down)
	return counterX & counterY; // updating the new co-ordinates of the counter
} // moves the counter to space 75
else if (counterX == 125 & counterY == 25) { // if the counter is on space 98
		counterX  = counterX - gridInterval; // minusing 50 to the x co-ordinate (moves the counter 1 space left)
		counterY = counterY + (gridInterval * 2); // adding 100 to the y co-ordinate (moves the counter 2 spaces down)
	return counterX & counterY; // updating the new co-ordinates of the counter
} // moves the counter to space 79
		
redraw(1); // this lets us see what is happening
}

function drawGrid() { // specifies how the grid shall be drawn

	for (var x=-width; x < width; x+=50) { // every 50 in the x axis a line will be drawn
		line(x, -height, x, height);// specifies how the line will be drawn
	}
	for (var y=-height; y < height; y+=50) {// every 50 in the y axis a line will be drawn
		line(-width, y, width, y);// specifies how the line will be drawn 
	}
	text(1,0,460) //the first digit in the bracket is the value which will be shown
	text(2,50,460) //the second digit shows the location in the x axis
	text(3,100,460) //the third digit shows the location in the y axis
	text(4,150,460)
	text(5,200,460)
	text(6,250,460)
	text(7,300,460)
	text(8,350,460)
	text(9,400,460)
	text(10,450,460)
	text(11,450,410)
	text(12,400,410)
	text(13,350,410)
	text(14,300,410)
	text(15,250,410)
	text(16,200,410)
	text(17,150,410)
	text(18,100,410)
	text(19,50,410)
	text(20,0,410)
	text(21,0,360)
	text(22,50,360)
	text(23,100,360)
	text(24,150,360)
	text(25,200,360)
	text(26,250,360)
	text(27,300,360)
	text(28,350,360)
	text(29,400,360)
	text(30,450,360)
	text(31,450,310)
	text(32,400,310)
	text(33,350,310)
	text(34,300,310)
	text(35,250,310)
	text(36,200,310)
	text(37,150,310)
	text(38,100,310)
	text(39,50,310)
	text(40,0,310)
	text(41,0,260)
	text(42,50,260)
	text(43,100,260)
	text(44,150,260)
	text(45,200,260)
	text(46,250,260)
	text(47,300,260)
	text(48,350,260)
	text(49,400,260)
	text(50,450,260)
	text(51,450,210)
	text(52,400,210)
	text(53,350,210)
	text(54,300,210)
	text(55,250,210)
	text(56,200,210)
	text(57,150,210)
	text(58,100,210)
	text(59,50,210)
	text(60,0,210)
	text(61,0,160)
	text(62,50,160)
	text(63,100,160)
	text(64,150,160)
	text(65,200,160)
	text(66,250,160)
	text(67,300,160)
	text(68,350,160)
	text(69,400,160)
	text(70,450,160)
	text(71,450,110)
	text(72,400,110)
	text(73,350,110)
	text(74,300,110)
	text(75,250,110)
	text(76,200,110)
	text(77,150,110)
	text(78,100,110)
	text(79,50,110)
	text(80,0,110)
	text(81,0,60)
	text(82,50,60)
	text(83,100,60)
	text(84,150,60)
	text(85,200,60)
	text(86,250,60)
	text(87,300,60)
	text(88,350,60)
	text(89,400,60)
	text(90,450,60)
	text(91,450,10)
  text(92,400,10)
  text(93,350,10)
	text(94,300,10)
  text(95,250,10)
  text(96,200,10)
  text(97,150,10)
  text(98,100,10)
  text(99,50,10)
  text(100,0,10)
}

`

**Comment by lmccart** [comment]
It's not possible to load a sound from a remote url. You'll need to download the file and place it in the same folder as the project and link to it directly.

**Comment by benslack** [comment]
oooo thank you I shall give it a try now

**Comment by benslack** [comment]
I have just tried what you said and  on the html window it is just stuck saying Loading...

Here is a simplified version of the code I have used (only bits of code used to add sound):

`var gridWidth = 500; // how long the grid is
var gridHeight = 500; // how tall the grid is
var jump;`

`function preload() {
	jump = loadSound("jumpSound.mp3");
}`

`function setup() { // declaring what needs to be done when setting up the game
	createCanvas(gridWidth, gridHeight); // creates a canvas with a size of 500x500
}`

`function mousePressed() { // only execute draw when mouse is pressed
	jump.play();
}`

**Comment by lmccart** [comment]
hi @benslack, it's hard to debug a large project of code like this. could you please post an isolated code snippet that illustrates the problem. I'm going to close this for now, but please reopen this issue when you've updated the code snippet. thanks!
