### ISSUE TITLE
textToPoints does not work with the letter "i"

### ISSUE THREAD

**Issue by davidredsox** [processing/p5.js#1837]
Using `fontVar.textToPoints("i", width/2, height/2, 200)`, activated when a button is pushed, throws this error:

```
Uncaught TypeError: Cannot read property 'push' of undefined
    at f (p5.min.js:7)
    at y.Font.textToPoints (p5.min.js:7)
    at generate (sketch.js:28)
    at HTMLButtonElement.onclick (main.html:14)
```

Of course, this assumes that `fontVar` contains a preloaded and correctly referenced font. Also, the `generate()` function is what transforms the text into points and displays those points.

I want to note though: I'm not *completely* sure that it is a problem with the `.textToPoints()` function, but I am *pretty* sure.

**Comment by dhowe** [comment]
Can you include the full code for the sketch and the font itself (if not restrictively licensed) ?

**Comment by davidredsox** [comment]
Hey, my apologies for taking so long - I haven't checked this in a couple days.

Here's the code: [steering behaviors.zip](https://github.com/processing/p5.js/files/818900/steering.behaviors.zip)

It contains a .html file, sketch.js, vehicle.js (for steering behaviors), the minified version of p5.js, the slim and minified version of JQuery (used for working input), and the font, which is Montserrat Regular (taken from Google Fonts).

I am programming using a Chromebook and am using a local web server, because I couldn't get textToPoints to work without one.

**Comment by feedzh** [comment]
Hello,

I downloaded your example and it runs without errors. Can you post your console error with the code that you posted?

**Comment by davidredsox** [comment]
So for some reason when I unzipped the files onto my Windows PC, it ended up being an older version of the code (I'm gonna have to switch text editors on my Chromebook, I think). I updated it to be correct without the referencing errors.

In response to @feedzh , did you try typing in the character "i" or a word containing the character "i" into the text input and clicking the "Generate" button? The error occurs when you type [an "i" character](http://i.imgur.com/IqPqCXp.png), or when you input a [whitespace character, such as a space](http://i.imgur.com/gFsiBu3.png).

**Comment by JimishF** [comment]
The problem is with the font file which you are using. It is not the issue of p5 at all. <br>
I tried with other bunch of fonts and it is working fine for me.<br>
Here is my [repo](https://github.com/JimishF/streering-behaviours) you can check out.

**Comment by davidredsox** [comment]
I suppose I should have tried that first. Thanks though.
