### ISSUE TITLE
Text is not sub-pixel moveable on the y-axis

### ISSUE THREAD

**Issue by efi** [processing/p5.js#1840]
In the following code the text reacts smoothly to horizontal mouse movements but not vertical ones.

```processing
function draw() {
  clear();
  text("I do not move smoothly on the y axis", 100+0.01*mouseX, 100+0.01*mouseY)
}
```

**Comment by feedzh** [comment]
Hello,

Try to use round. This is calculated with pixels and pixels are integers.

```javascript
text("I do not move smoothly on the y axis", 100+round(0.01*mouseX), 100+round(0.01*mouseY))
```

**Comment by efi** [comment]
Thanks, but that actually makes things worse. Now the text shows abrupt "discrete" movement on both axes whenever the mouse steps over a "100 pixel" boundary. I want the opposite.

**Comment by efi** [comment]
OK, I just checked: This seems to be standard behavior of a canvas `fillText()`. :-1: 

Is there a way to force drawing of text using filled paths instead of `fillText`? Somthing like `textMode(SHAPE)` in processing?

**Comment by lmccart** [comment]
there's not at this time. we've decided to adhere to the behavior of canvas for basic drawing in most cases, so the best workaround is to round the numbers before inputting as @feedzh suggests.
