### ISSUE TITLE
Image resizing with nearest neighbor algorithm

### ISSUE THREAD

**Issue by gncgnc** [processing/p5.js#1845]
Nearest neighbor resizing is a nice feature for user's working with things like pixel art. There is no native way to do this (except writing your own), so maybe it would be a sensible addition to p5. In Processing this can be done with using noSmooth(), but I'm not sure what the best way to implement this would be.

**Comment by lmccart** [comment]
at the moment, it's a bit beyond the capabilities of the core functionality. but this sounds like a great feature for some kind of addon library. see this doc if you're interested in creating one: 
https://github.com/processing/p5.js/wiki/Libraries

**Comment by gncgnc** [comment]
I have implemented this [here](https://gist.github.com/gncgnc/fc645b8db00ec43d43fecef37d58df73), for anyone who might be looking for this in the future. It's slower than the regular resize(), but it gets the job done.

**Comment by egordorichev** [comment]
Any news? :X

**Comment by limzykenneth** [comment]
@egordorichev You can simply copy and paste the code @gncgnc linked to in the previous comment into your sketch and you can call `img.resizeNN` in your sketch.

**Comment by egordorichev** [comment]
It's 10 times slower... And I need to scale up the whole game.

**Comment by limzykenneth** [comment]
@egordorichev There's an untested [optimised version](https://gist.github.com/GoToLoop/2e12acf577506fd53267e1d186624d7c) perhaps give that a go?

**Comment by gncgnc** [comment]
@egordorichev I've looked into it again and it appears this can be done natively in the canvas with `CanvasRenderingContext2D.imageSmoothingEnabled`. See [here](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/imageSmoothingEnabled) for the Mozilla documentation. You will need to access the drawing context p5 is using and set this property to `false`.

Alternatively you can try scaling up the p5 canvas with CSS as seen [here](https://developer.mozilla.org/en-US/docs/Web/CSS/image-rendering), but currently the `image-rendering` CSS property has virtually no support. I'm leaving it here for future reference.

**Comment by GN-c** [comment]
you can use p5 built in function noSmooth();

https://p5js.org/reference/#/p5/noSmooth
