### ISSUE TITLE
video is not playing on mobile devices for the "Video Canvas" example from p5js.org

### ISSUE THREAD

**Issue by carolelambert** [processing/p5.js#1846]
I am not able to have the video on my iPhone 6 (checked with the latest Chrome and Safari browsers) for the "Video Canvas" example from p5js.org (the image is freezed, the video is not played).
It would work if we remove the 'fingers.hide()' call, but it would not hide the 2nd video out of the canvas...Fyi, the "Video" example (without any call to hide()) is working fine.

https://p5js.org/examples/dom-video-canvas.html:
var fingers;
function setup() {
  createCanvas(710, 400);
  // specify multiple formats for different browsers
  fingers = createVideo(['assets/fingers.mov',
                         'assets/fingers.webm']);
  fingers.loop(); // set the video to loop and start playing
  fingers.hide(); // by default video shows up in separate dom
                  // element. hide it and draw it to the canvas
                  // instead
}

function draw() {
  background(150);
  image(fingers,10,10); // draw the video frame to canvas
  filter('GRAY');
  image(fingers,150,150); // draw a second copy to canvas
}

**Comment by michaelByrne** [comment]
Problem is that inline autoplay isn't default in Webkit and the hide() function hides the start arrow. Video needs autoplay, muted, and playsinline attributes. Looking at a fix now.

**Comment by JMandel1027** [comment]
Hmm ya I'm getting the same thing on my pixel running chrome

I think if we add a simple patch to [MediaElement.play()](
https://github.com/processing/p5.js/blob/e3bb58c185cd247950216e76b15268605630a804/lib/addons/p5.dom.js#L1692) to check for touch in that play method that could work, I can run more tests for this this weekend.

Would be killer to get this working since a project I'm working on would benefit from this :)

hope this helps!

**Comment by mlarghydracept** [comment]
**I think it makes sense to activate the playback with touch in your sketch.**

The same thing happens on Android Marshmallow (older phone) but as @michaelByrne said [the newest version of Webkit allows for autoplay](https://webkit.org/blog/6784/new-video-policies-for-ios/) as long as the muted and playsinline attributes are present. 

Commenting out the "fingers.hide()" line doesn't change the issue on my end which makes sense to me. 

So it would theoretically be possible to make the library handle mobile autoplay without input but it would make for confusing design. I think we would have to check whether the call to play a video was made from an input listener and if it wasn't then check if the user's device would support webkit autoplay and then assign the playsinline and mute attributes.

Then some users would have videos that played without input and were inexplicably muted while others still had videos that required input to activate.

**Comment by JMandel1027** [comment]
Oh hey Stalgia! Long time no chat ☺️🖖 

Yea I think so to, having a on touch to play implicitly controlling the play()  method seems to be the best route. I had some notes for adding an event listener checking for touch in the MediaElement.Play(), I was going to test out on my end later.

**Comment by lmccart** [comment]
Yeah, I think for the example, we ought to just move the video.loop() call into a mousePressed() function. I like the magic of handling mobile autoplay, but I think it probably isn't good mobile behavior / would be counterintuitive for p5.js to incorporate this. But by all means, give it a shot in your own project.. it seems feasible.
