### ISSUE TITLE
preventDefault for touch events "not working" in Android Chrome

### ISSUE THREAD

**Issue by kjhollen** [processing/p5.js#1847]
I'm working on some touches array examples for class and noticed that preventDefault doesn't seem to be a reliable way to cancel default touch events on Chrome for Android—which means it's not possible to run p5 multitouch examples without some interference from this particular browser.

It looks like this recent change to Chrome may be to blame:
https://developers.google.com/web/updates/2017/01/scrolling-intervention

I think can be overridden within p5 something like...
`window.addEventListener("touchstart", func, {passive: false} );`

Related to issues #1811 and #1815, I think. I suspect everything is fine with iOS + Safari; I'll test in a couple hours when I have access to an iOS device.

**Comment by lmccart** [comment]
@kjhollen can you test by pulling the latest to see if it fixes your use case? if not, will you post a code snippet that illustrates the behavior? thanks!

**Comment by kjhollen** [comment]
Looks like it's still not working—here's an example I uploaded to the editor site (it has a new p5.min.js build linked locally) http://alpha.editor.p5js.org/full/S1mJochqg

**Comment by kjhollen** [comment]
I just want to update this to say that I tested the solution I suggested here and it's working great on my Android phone. I'll submit a pull request after I get a chance to run the tests and make sure that I haven't messed things up for users of other platforms. :)

**Comment by lmccart** [comment]
I think I may have inadvertently added this patch in just now when I was attempting to fix something else. oops! But please do test if you have time and confirm this is ok to put in the next build.
