### ISSUE TITLE
Video on canvas has incorrect width.

### ISSUE THREAD

**Issue by tamler** [processing/p5.js#1848]
```javascript
var vid;

function setup() {
  createCanvas(320, 240);
  background(51);
  vid = createCapture(VIDEO);
  vid.size(320, 240);
  vid.hide();
}

function draw() {
  image(vid, 0, 0, width, height);
}
```

This is producing a video on canvas with the width of video source divided in half. 
I have the latest version of p5js: 0.5.7
Anyone else see this issue?

**Comment by catarak** [comment]
I also just noticed this issue. However, I noticed that if you do
```javascript
var capture;
function setup() { 
  createCanvas(320, 240);
  capture = createCapture(VIDEO);
  capture.size(320, 240);
  capture.hide();
} 

function draw() { 
  background(255);
  capture.loadPixels();
  image(capture, 0, 0, 320, 240);
}
```
then the width is correct.

**Comment by tamler** [comment]
This works also... 

image(vid, 0, 0, width*2, height); 

So for some reason width is being divided by 2.

**Comment by lmccart** [comment]
@mlarghydracept this is a not too difficult but stickier than it seems issue. if you're interested let's chat about it sometime.

**Comment by lmccart** [comment]
related issues #1745 #1673 #1079 #1022
