### ISSUE TITLE
Error on touch end

### ISSUE THREAD

**Issue by seeme00** [processing/p5.js#1851]
Using a simple sketch:

`function setup(){
  createCanvas(300, 300);
}

function draw(){
  background(90);
}
`

On Android chrome, if I touch the canvas, I get the following error/stack:

> p5.js:16488 Uncaught TypeError: Cannot read property 'clientX' of undefined
>     at getMousePos (p5.js:16488)
>     at p5._updateNextMouseCoords (p5.js:16456)
>     at p5._ontouchend (p5.js:17086)

I'm using the latest version from https://p5js.org/download/
(Android 5.1, Chrome 55)

Thanks

**Comment by lmccart** [comment]
fixed with https://github.com/processing/p5.js/pull/1820
