### ISSUE TITLE
mouseY on IOS not working as intended.

### ISSUE THREAD

**Issue by mwylegly** [processing/p5.js#1852]
Strange issue with the mouseY on ios (iphone 5s, ipad 2) in which the y updates relative to the position where the touch is started. 

mouseX seems to be working as intend.

Also seems to be impacting touches[].

The drawing example ( http://p5js.org/examples/mobile-simple-draw.html ) seems to be exhibiting this issue as well.

**Comment by lmccart** [comment]
i think this is just a problem with the frame of the example and not with the library itself. i'm moving it over here: https://github.com/processing/p5.js-website/issues
