### ISSUE TITLE
calling loadStrings to assign value to variable is inconsistent with the loadStrings callback method

### ISSUE THREAD

**Issue by jshaw** [processing/p5.js#1855]
When using loadString as to load a string from a .txt file and set it as a variable  as so`pubnub_config = loadStrings('pubnub_config.txt');` an array is returned but is inaccessible to access. This is done both in the `preload()` and `setup()` functions.

The returned value is a shown as an array but the `typeof` is an object and has a length is 0.

If I switch to the callback function method it works as expected.

As a reference, the `pubnub_config.txt` file is formatted as two lines both lines are a string with my keys for pubnub.

    key_one_xxxxxxxxxxxxxxxx
    key_two_yyyyyyyyyyyyyyyy

---

Sample code running Version 56.0.2924.87 (64-bit), I am getting an issue is:

    pubnub_config = loadStrings('pubnub_config.txt');
    console.log(pubnub_config);
    // the output is below
    // Array[0]
    // 0: "key_one_xxxxxxxxxxxxxxxx"
    // 1: "key_two_yyyyyyyyyyyyyyyy"
    // length: 2
    // __proto__: Array[0]

    console.log(pubnub_config.length);
    // 0

    pub = pubnub_config[0];
    sub = pubnub_config[1];

    console.log(pub);
    // undefined

    console.log(sub);
    // undefined

    console.log(typeof pubnub_config);
    // object

    console.log(pubnub_config['0']);
    // undefined

    console.log(pubnub_config.toString());
    // 

    console.log(JSON.stringify(pubnub_config));
    // []

Also tried to see if I could put the array into a string by calling both `pubnub_config.toString();` and `join(pubnub_config);`. Both of these return and empty string, not undefined, null.

**Comment by lmccart** [comment]
I'm not able to reproduce. This is the test code I'm using:
```javascript
var data;

function preload() {
  data = loadStrings('assets/test.txt');
}

function setup() {
  console.log(data);
}
```

this is the console output:
<img width="307" alt="screen shot 2017-03-14 at 3 51 27 pm" src="https://cloud.githubusercontent.com/assets/191056/23925809/341a0d44-08ce-11e7-9f93-db46625fe2c1.png">

are you trying to call console.log on the data inside preload? at this point the loading would not be complete, but if you call console.log in setup or draw, it should work.

**Comment by jshaw** [comment]
Your sample code is working for me too. And yeah, I was logging in the preload. I could have sworn that I also tried logging the output in the setup and initialized the pubnub lib with the keys in the setup too. Thanks for looking into this and the quick reply!

**Comment by AswIyer** [comment]
God loves you both! Thanks a bunch for the Q&A! you both saved my Hell Tym!
