### ISSUE TITLE
Suggestion: more information on the p5 dom input webpage

### ISSUE THREAD

**Issue by reteps** [processing/p5.js#1860]
Currently, right [here](http://p5js.org/reference/#/p5/createInput) it says:
```
Parameters
[value]	Number: default value of the input box
[type]	String: type of text, ie text, password etc. Defaults to text
```
I propose you list more types, like text, password, number, date, etc.

I propose it looks like:
```
Parameters
[value]	Number: default value of the input box
[type]	String: type of text, ie text, password, number, etc. Defaults to text, can be any input type.
```
<img width="908" alt="screen shot 2017-03-16 at 7 54 53 pm" src="https://cloud.githubusercontent.com/assets/13869303/24023405/82d8f69c-0a82-11e7-942d-0df155ccf0db.png">

**Comment by lmccart** [comment]
I think what would be best is if
