### ISSUE TITLE
index.html no longer works in any browser

### ISSUE THREAD

**Issue by wapatoecology** [processing/p5.js#1861]
i just had a successful first day learning p5.js on my mac running 10.12 on chrome.

then, out of the blue, the html file no longer works in any browser.
i tried downloading everything again and it didn't work either. old files that worked no longer do.
I've searched and found no similar problems online.

Thank you to anyone who has any help to offer.

**Comment by mlarghydracept** [comment]
There isn't enough information here for us to investigate this as a bug. Seems more likely that you have a problem unrelated to the code of the library. [You should try troubleshooting this with people on the forum](https://forum.processing.org/two/categories/p5-js). Good luck!
