### ISSUE TITLE
P5.js ellipsoid issue

### ISSUE THREAD

**Issue by jricha36** [processing/p5.js#1862]
error on library when creating ellipsoid.
push();
	translate(width/3,height/3);
        fill(255,0,0);
       ellipsoid(20,30,40);
pop();

repeatedly returns error message below

Uncaught TypeError: this._renderer.geometryInHash is not a function      p5.js:32290
    at p5.ellipsoid (p5.js:32290)
    at draw (sharpWet.js:82)
    at p5.redraw (p5.js:14113)
    at p5.<anonymous> (p5.js:9147)
    at p5.<anonymous> (p5.js:9043)
    at new p5 (p5.js:9323)
    at _globalInit (p5.js:5602)

**Comment by lmccart** [comment]
ellipsoid is a 3D object so it only works in webgl mode, are you working in this mode?

**Comment by bmoren** [comment]
You can use webgl mode by creating a canvas with the web gl renderer

`createCanvas(200, 200, WEBGL);`

more info here:
https://github.com/processing/p5.js/wiki/Getting-started-with-WebGL-in-p5

**Comment by jricha36** [comment]
This is the code I am using:

var i = 0 ;
var j = 0;
var k = 0;
var z = 0;

function setup() {
createCanvas(600,600,WEGGL);
//rectMode(CENTER);
frameRate(10);

}

function draw() {



var size = height / 15; // 20
var margin = width / 20; // 15
var x = width - margin - size; // 265
var y = height - margin - size; // 190
background(255,255,103);

push();
translate(width/3,height/3,0);

fill(255,0,0);

ellipsoid(20,30,40);

pop();


push();


translate(50,20,0);
rotate(radians(25));


// sharp shape  knife;

fill(100);
rect(80,115,50,20);
fill(255);
beginShape();
vertex(130,120);
bezierVertex(130,173,180,163,300,120);
endShape();
strokeWeight(5);
line(130.5,120,300,120);

pop();


strokeWeight(5);
line(270,100,270,350);  // wall knife strikes



// wet shape  water tank;

noStroke();
fill(0,120,150);
rect(400,100,150,300);


var top = 100;
var left = 400;

for (i = 0; i < 300; i = i + 20){
top = 100;
top = top + i;
strokeWeight(1);
stroke(0,0,255);
beginShape();
vertex(left,top);
bezierVertex(left,top,left + 20,top - 24,left + 50,top);
bezierVertex(left+ 50,top,left + 70,top - 24,left +100 ,top);
bezierVertex(left+ 100,top,left + 120,top - 24,left +150 ,top);
endShape();
}

stroke(0);
z = z + 1;
fill(255,255,0);
ellipse(200,400,25,25);
fill(100);
ellipse(200+cos(radians(z))*50,400+sin(radians(z))*50,15,15);
ellipse(200+cos(radians(z))*80,400+sin(radians(z))*80,15,15);
ellipse(200+cos(radians(z))*110,400+sin(radians(z))*110,15,15);
if ( z == 360) {z = 0;}






push();
translate(width/3,height/3,0);

fill(255,0,0);

ellipsoid(20,30,40);

pop();


}

**Comment by bmoren** [comment]
it seems there is a typo in your create canvas: `createCanvas(600,600,WEGGL);` should be  `createCanvas(600,600,WEBGL);`

**Comment by jricha36** [comment]
I apologize, this is an error I created during testing. I still get errors
from the P5 library when i run the code in Windows 10.
Thanks to  everyone for the assistance.

**Comment by lmccart** [comment]
can you please post the error you're seeing?
you can mark up your code snippets when you post here on github so they're a little easier to read, see this link:
https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by jricha36** [comment]
new error.

p5.js:31396 p5.RendererGL: enabled webgl context
p5.js:30623 Uncaught TypeError: Cannot read property 'transpose3x3' of null
    at p5.Matrix.inverseTranspose (p5.js:30623)
    at p5.RendererGL._setMatrixUniforms (p5.js:31557)
    at p5.RendererGL.drawBuffers (p5.js:31282)
    at p5.RendererGL.rect (p5.js:32509)
    at p5.rect (p5.js:8157)
    at draw (sharpWet.js:49)
    at p5.redraw (p5.js:14113)
    at p5.<anonymous> (p5.js:9147)
    at p5.<anonymous> (p5.js:9043)
    at new p5 (p5.js:9323)


When I run sketch in 2 D with "ellipsoid" removed sketch is drawn as shown
in the screen shot. After adding WEBGL to createCanvas and drawing
ellipsoid the above error is generated and only the ellipsoid is draw. I
have tried adding "z" position 0 to "line" and other functions. The issue
remains. If I comment out the "rect" funcion the error then moves to the
"line" function.


var i = 0 ;
var j = 0;
var k = 0;
var z = 0;



function setup() {
createCanvas(600,600,WEBGL);
//rectMode(CENTER);
frameRate(10);

}



function draw() {




background(255,255,103);


push(); // draw ellipsoid.... works at start of program but new error
created.
translate(width/3,height/3,0);

fill(255,0,0);

ellipsoid(20,30,40);

pop();


push();



push();


translate(50,20,0);
rotate(radians(25));


// sharp shape  knife;

fill(100);
rect(80,115,50,20);


fill(255);
beginShape();
vertex(130,120);
bezierVertex(130,173,   180,163,   300,120);
endShape();


strokeWeight(5);
line(130.5,120,   300,120);

pop();


strokeWeight(5);
line(270,100,    270,350);  // wall knife strikes



// wet shape  water tank;

noStroke();
fill(0,120,150);
rect(400,100,150,300);


var top = 100;
var left = 400;

for (i = 0; i < 300; i = i + 20){
top = 100;
top = top + i;
strokeWeight(1);
stroke(0,0,255);

beginShape();       // draw a curve to represent knife blade
vertex(left,top);
bezierVertex(left,top,left + 20,top - 24,left + 50,top);
bezierVertex(left+ 50,top,left + 70,top - 24,left +100 ,top);
bezierVertex(left+ 100,top,left + 120,top - 24,left +150 ,top);
endShape();
}

stroke(0);
z = z + 1;


fill(255,255,0);    // draw circle as center of orbit.

ellipse(200,400,25,25);

fill(100);           // draw 3 ellipses orbiting center ellipse.
ellipse(200+cos(radians(z))*50,400+sin(radians(z))*50,15,15);
ellipse(200+cos(radians(z))*80,400+sin(radians(z))*80,15,15);
ellipse(200+cos(radians(z))*110,400+sin(radians(z))*110,15,15);



if ( z == 360) {z = 0;} //   reset rotation degrees at 360 degrees.




}

**Comment by jricha36** [comment]
follow up on error by simplifying the sketch code to make it easier to troubleshoot. When "WEBGL" is removed from the parameter list of createCanvas no errors are generated and the line is drawn.


function setup() {
               createCanvas(600,600,WEBGL);
}

function draw() { 

	     line(100,100,200,100);  // draw a straight line.
}


Error message from console.

p5.js:31396 p5.RendererGL: enabled webgl context
p5.js:7935 Uncaught TypeError: this._renderer.line is not a function
    at p5.line (p5.js:7935)
    at draw (3DTest.js:13)
    at p5.redraw (p5.js:14113)
    at p5.<anonymous> (p5.js:9147)
    at p5.<anonymous> (p5.js:9043)
    at new p5 (p5.js:9323)
    at _globalInit (p5.js:5602)


I am also including the html code which is the basic sample from  P5.js

<html>
<head>
  <meta charset="UTF-8">
  <script language="javascript" type="text/javascript" src="libraries/p5.js"></script>
  
  
  
  <script language="javascript" type="text/javascript" src="3DTest.js"></script>

  
  <style> body {padding: 0; margin: 0;} </style>
</head>

<body>
</body>
</html>

**Comment by lmccart** [comment]
ah, line() is currently not working in webgl mode. we're working on a fix. you can follow progress on this over here: https://github.com/processing/p5.js/issues/1638

**Comment by jricha36** [comment]
the errors are also thrown for other 2D  shapes such as rect. It appears
that 2D cannot be included with WEBGL. I have also seen errors while using
vertex when using WEBGL.

thanks for your help

Jim

**Comment by lmccart** [comment]
this is correct. only 3D shapes can be used right now.
