### ISSUE TITLE
Using saveCanvas() for saving a large picture fails

### ISSUE THREAD

**Issue by MiragePV** [processing/p5.js#1867]
Hey,

Working on 64 bit Windows 7, using Chrome ver. 57.0.xxx

I create 3000x3000 pixels canvas, drawing something on it, then trying to save it (once) as a .jpg/.png picture. However, when the program tries to do so, the picture is not saved. Instead, I get an "Error - Network problem" in Chrome.

Is this a Chrome problem, or a p5.js problem?

var CanvasSize = 3000;
createCanvas(CanvasSize, CanvasSize);
saveCanvas("maze_1", 'jpg');

**Comment by lmccart** [comment]
this is a limitation of the browser, more here: http://stackoverflow.com/questions/16156402/canvas-todataurl-for-large-canvas?noredirect=1&lq=1
