### ISSUE TITLE
color() with 2 arguments throws error

### ISSUE THREAD

**Issue by HtmHell** [processing/p5.js#1869]
It throws an error only when the 1st parameter is a string.
```
color(0, 120) // Ok
color("#000", 120) // Error
```

> Uncaught Error: [object Arguments]is not a valid color representation.
>     at d.Renderer2D.d.Color._parseInputs (p5.min.js:4)
>     at new d.Color (p5.min.js:3)
>     at e.d.color (p5.min.js:3)

**Comment by joecridge** [comment]
Hi @HtmHell, thanks for catching this. I believe that this is the desired behaviour, but the documentation needs updating.
