### ISSUE TITLE
undefined variable error + preload()/loadJSON()

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js#1871]
If I use a variable that I've never defined like so:

```javascript
function setup() {
  var test1 = 5;
  var test3 = test1 + test2;
  console.log(test3);
}
```

I get the error I expect in the console:

<img width="363" alt="screen shot 2017-04-01 at 2 08 19 pm" src="https://cloud.githubusercontent.com/assets/191758/24581184/b37f26cc-16e4-11e7-8501-dffd32ac3e91.png">

However, with that same code plus a call to `loadJSON()` in `preload()`, the error is not reported but rather is (??) bottled up somewhere in the `httpDo()` function:

<img width="304" alt="screen shot 2017-04-01 at 2 09 54 pm" src="https://cloud.githubusercontent.com/assets/191758/24581193/04c4325c-16e5-11e7-9856-f7f24091b59e.png">

The corresponding code at line 23278 is in `src/io/files.js`

https://github.com/processing/p5.js/blob/0efd01151a17770b6c81baa7f338cb90da1c5dba/src/io/files.js#L640

With a complex sketch, this can make finding your typo quite difficult!

**Comment by limzykenneth** [comment]
@shiffman That was originally to catch server errors like 404, I didn't really anticipated other errors, oops. I think we should just remove the else clause and maybe just pass the whole error object to the error callback, let the user decide how to deal with the error, is that reasonable for usability?

**Comment by lmccart** [comment]
that makes sense
