### ISSUE TITLE
in p5.part the onStep function only works the first time the part plays, not on loops. 

### ISSUE THREAD

**Issue by cfboyd** [processing/p5.js#1872]
In p5.part the onStep function only works the first time the part plays, not when looping. How can I create a step counter or whatever otherwise?

**Comment by b2renger** [comment]
Hi @cfboyd 

there is a similar issue on the p5.sound repo here : https://github.com/processing/p5.js-sound/issues/151
I'll close this one and cross-reference it and try to give an answer there.
