### ISSUE TITLE
WebGL texture transparent PNG

### ISSUE THREAD

**Issue by andyinabox** [processing/p5.js#1878]
I'm attempting to use a transparent PNG as a texture, but the alpha channel doesn't register. Is this expected? Here's some sample code:

```javascript
var sketch = function($p5){

  var img;

  $p5.preload = function() {
    img = $p5.loadImage("data/shape3.png");
  }

  $p5.setup = function() {
    $p5.createCanvas(500, 500, $p5.WEBGL);
  }

  $p5.draw = function() {
    $p5.background(200);
    $p5.texture(img);
    $p5.plane(300, 300);
  }
}
new p5(sketch);
```

The image I'm using is:
![shape3](https://cloud.githubusercontent.com/assets/151084/24698429/99371928-19be-11e7-8496-a5116906b5cc.png)

And it renders like this:
![screenshot 2017-04-05 05 10 19](https://cloud.githubusercontent.com/assets/151084/24698460/bd18c63e-19be-11e7-9526-a3f3dd1141d9.png)

As you can see, anything that has an alpha value seems to show up as white.

**Comment by mlarghydracept** [comment]
As far as I can tell this expected behavior. The default material isn't going to detect the alpha of your texture image. You can try using [specularMaterial()](https://p5js.org/reference/#/p5/specularMaterial), but from what I understand this won't necessarily achieve your desired effect either.

**Comment by lmccart** [comment]
Yes, this is currently the intended behavior.

**Comment by sixhat** [comment]
I've been dealing with this for a while and found that you need to enable the Blend mode of your webgl canvas if you need transparent textures to work. 

You can either do 

```javascript
gl = this._renderer.GL;
gl.enable(gl.BLEND);
gl.blendFunc(gl.SRC_ALPHA, gl.ONE_MINUS_SRC_ALPHA);
```
or take advantage that `fill` has a side effect of setting this for you if you issue a `fill` with a color that is not opaque. 

in your code, if you just put `$p5.fill(0,0,0,0);` before `$p5.texture(img);` you should get what you look for. 

The example below produces 

![output-alpha](https://cloud.githubusercontent.com/assets/614881/26454158/1c048f18-415e-11e7-9082-e6405d3a616c.png)

```javascript
function preload(){
	alpha = loadImage('alpha.png');
}

function setup() {
	createCanvas(500,500, WEBGL);
}

function draw (){
	background(100);

	translate(-50,-50,1);
	texture(alpha);
	plane(300,300);

	fill(0,0,0,0); // Side effect = Sets gl.BLEND

	translate(100,100,1);
	texture(alpha);
	plane(300,300);

	noLoop();
}
```

The alpha image is 

![alpha](https://cloud.githubusercontent.com/assets/614881/26454169/27711344-415e-11e7-820d-493ce3f72a46.png)

A permanent solution would be to add the above code to the `texture` function in p5.js, but I don't know if it would conflict with other p5 functionalities.
