### ISSUE TITLE
Unexpected nf()-formatting

### ISSUE THREAD

**Issue by mcsanta** [processing/p5.js#1879]
Hi,

when using the nf()-function, the number gets formatted regardless of scientific notation. This makes very small or very big numbers indistinguishable.

Consider this example
```
function setup() { 
    createCanvas(400, 400);
} 

function draw() {
    background(220);

    smallNumber = 3.8944423423433e-14;
    text(smallNumber, 50, 50);
    text(nf(smallNumber, 1, 3), 50, 65);
	
    mediumNumber = 3.8944423423433;
    text(mediumNumber, 50, 100);
    text(nf(mediumNumber, 1, 3), 50, 115);
	
    bigNumber = 3.8944423423433e+50;
    text(bigNumber, 50, 150);
    text(nf(bigNumber, 1, 3), 50, 165);
}
```

Please let me know if the information provided is sufficient. And since this is my first contribution, I'm also open to general suggestions for improvement.

Best

**Comment by lmccart** [comment]
@mlarghydracept?

**Comment by lmccart** [comment]
after investigating solutions, we've determined there's a significant cost of performance and complexity to the code for a relatively less common use case. as reference, it looks like processing also doesn't support scientific notation in these functions. at this point, we've decided to forgo scientific notation support.

**Comment by mcsanta** [comment]
Thanks for the feedback, this makes sense to me.
