### ISSUE TITLE
Adding a new colormode

### ISSUE THREAD

**Issue by runemadsen** [processing/p5.js#1880]
Hi there!

 I was trying to create an addon that adds a new colormode to P5 based on [HSLUV](http://www.hsluv.org/), but I realized that the colormodes are [harcoded into the source](https://github.com/processing/p5.js/blob/master/src/color/p5.Color.js#L38-L41).

Would you be open to me submitting a pull request that allows for addons to define new color modes? I would need to think about the best way of doing this, but perhaps a small `registerColorMode()` where you can pass in the name, the colorMaxes, and the conversion functions?

Let me know you anyone has any better ideas.

**Comment by lmccart** [comment]
hey @runemadsen sorry for the delay. I don't see any specific issue with this, we can definitely add some kind of registerColorMode function. my only concern is that I have a sense that the color code in general is a bit complex to work with. if you take a look through and feel comfortable with it, please feel free to give it a shot. and let me know if you encounter any issues that I can help resolve.

**Comment by runemadsen** [comment]
Hey @lmccart. No worries at all! I might take a look and try to streamline the color handling a bit while introducing a way to expand the color modes. Thanks!
