### ISSUE TITLE
something strange happens with p5Vector copy() function

### ISSUE THREAD

**Issue by SetupandDraw** [processing/p5.js#1883]
I was playing around with one of Shiffman's NOC examples for p5js: [Combining Behaviors_ Seek and Separate](https://github.com/shiffman/The-Nature-of-Code-Examples-p5.js/tree/master/chp06_agents/NOC_6_08_SeparationAndSeek) I wanted to add mass at play and so I attempted to make a copy of a vector passed in via a function, as I have done dozens of times before, but this time I got this error: "Uncaught TypeError: force.copy is not a function"
```javascript
 this.applyForce = function(force) {
    var f = force.copy();
    console.log(f); /// "Uncaught TypeError: force.copy is not a function"
  }
```

I have no Idea why this is not working, since I am sure I am passing a Vector to the function. Maybe a bug?

**Comment by lmccart** [comment]
what is the output if you console.log(force) just before the line `var f =...`?

**Comment by SetupandDraw** [comment]
vehicle.js:30 n.Vector {p5: o, x: 0, y: 0, z: 0}

**Comment by lmccart** [comment]
hm I'm not able to reproduce. this is my full code, does this snippet work for you?
```javascript

function setup() { 
  var v = createVector(40, 50);
  console.log(v);
  copyVector(v);
} 

function copyVector(vec) {
  var f = vec.copy();
  console.log(f);
}
```

**Comment by SetupandDraw** [comment]
I noticed something similar also with mult() function

if I console log the vector I get: p5.Vector{.....
but if I run forcename.mult(3); for example,
I get an error "Uncought TypeError: Cannot read property "mult" of undefined

**Comment by SetupandDraw** [comment]
Yes your script works for me, I have also tested simple snippets like this and they do work.

maybe the problem occurs when passing the Vector from function to function to function? As in the example I mentioned?

**Comment by lmccart** [comment]
thanks for all the info. this snippet, passing the vector through many functions also works for me.
```javascript

function setup() { 
  var v = createVector(40, 50);
  console.log(v);
  copyVector1(v);
} 

function copyVector1(vec) {
  var f = vec.copy();
  console.log(f);
  copyVector2(f);
}

function copyVector2(vec) {
  var f = vec.copy();
  console.log(f);
  copyVector3(f);
}

function copyVector3(vec) {
  var f = vec.copy();
  console.log(f);
}
```
we're going to need a complete, isolated snippet that demonstrates the problem in order to identify  a bug and fix it. if you need general code help, I'd suggest posting in the forum: http://forum.processing.org

**Comment by SetupandDraw** [comment]
OK, it might be something with the editor... The same code I'm experiencing problems with while testing on Atom (1.15.0), runs perfectly fine on P5js editor. 

If I find more about the problem I will post in on the forum.

Thanks for your help Laura.

**Comment by lmccart** [comment]
huh weird. I was testing the snippets without the editor...just using sublime. maybe it's something happening with atom? I will try to test on atom and see if I can reproduce there.

**Comment by shiffman** [comment]
I doubt this is the issue but originally in Processing the name was `get()` rather than `copy()` it might be that older versions of p5 don't have `copy()`. I tested and my examples are working with recent p5.js, possible you are using an old version?

**Comment by SetupandDraw** [comment]
nope, the problem is with copy() but also with mult() 
Sadly I have spent hours without being able to figure out what is it yet.... 
I have placed a running version of your flocking-system on githhub for you to see:

  [https://setupanddraw.github.io/experiments/Flocking_System/](url)

Same problem also online, with latest libraries linked via cdnjs.cloudflare.com:
`Uncaught TypeError: Cannot read property 'mult' of undefined
    at Vehicle.applyBehaviors`

**Comment by lmccart** [comment]
It looks like this piece of code will either return a p5.Vector or undefined, depending on which logic section it goes through. The error "Uncaught TypeError: Cannot read property 'mult' of undefined" indicates that it is undefined, so it seems this coudl be the source of the bug. I kindly ask that you move this question to the forum at this point, so we can keep the github issues just for isolated bugs in the p5 library. Thanks!

```javascript
   this.separate = function(vehicles) {
        var desiredseparation = slider3.value(); // SETTING THE ACTIVATION RANGE FOR THE BEAVIOR
        var sum = createVector();
        var count = 0;
        // For every boid in the system, check if it's too close
        for (var i = 0; i < vehicles.length; i++) {
            var d = p5.Vector.dist(this.position, vehicles[i].position);
            // If the distance is greater than 0 and less than an arbitrary amount (0 when you are yourself)
            if ((d > 0) && (d < desiredseparation)) {
                // Calculate vector pointing away from neighbor
                var diff = p5.Vector.sub(this.position, vehicles[i].position);
                diff.normalize();
                diff.div(d); // Weight by distance
                sum.add(diff);
                count++; // Keep track of how many
            }
        }
        // Average -- divide by how many
        if (count > 0) {
            sum.div(count);
        }
        if (sum.mag() > 0) {
            // Our desired vector is the average scaled to maximum speed
            sum.normalize();
            sum.mult(this.maxspeed);
            // Implement Reynolds: Steering = Desired - Velocity
            var steer = p5.Vector.sub(sum, this.velocity);
            steer.limit(this.maxforce);
        }
        return steer;
    }

```
