### ISSUE TITLE
millis() not working

### ISSUE THREAD

**Issue by Squishling** [processing/p5.js#1886]
I referenced p5.js:
`<script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.5.8/p5.min.js"></script>`
Then I tried to make a timer, I created a startTime variable:
`var startTime = Math.floor(millis() / 1000);`
I run it in my browser (Firefox) and I get this error message:
`millis is not defined`

**Comment by lmccart** [comment]
is this outside setup? all p5 calls need to happen inside setup or draw or another p5 function, or in a function called by one of these. if you try to do this before setup, p5 is not instantiated yet, so millis won't be defined.

**Comment by Squishling** [comment]
Oh! :P

**Comment by Squishling** [comment]
What do I do if I want millis() inside a prototype object?

**Comment by lmccart** [comment]
you can declare the variable outside of setup, but assign it inside.

```javascript
var startTime;

function setup() {
  startTime = Math.floor(millis() / 1000);
}
```

you can use the same logic with an object constructor as well. for further help with this, I suggest posting on the forum http://forum.processing.org.
