### ISSUE TITLE
I can not use img.loadPixels()

### ISSUE THREAD

**Issue by 19valentin99** [processing/p5.js#1892]
After I made the image with img=createImage(file.data); (is from the video with drag&drop) i can not load pixels from that specific image and be able to manipulate the pixels from the image that I created. what should I do?I have tried to use loadPixels(img) but still dosen't work. My code looks like this: 

var dropzone;
var img;
var d=0;
var t=0;
function setup() {
  createCanvas(650,650);
      pixelDensity(1);
  
  dropzone= select('#dropzone');
  dropzone.dragOver(highlight);
  dropzone.dragLeave(unhighlight);
  dropzone.drop(gotFile, unhighlight);
  background(0);
      
            rSlider=createSlider(-255,255,0);
      rSlider.position(650+100,50);
            gSlider=createSlider(-255,255,0);
      gSlider.position(650+100,150);
            bSlider=createSlider(-255,255,0);
      bSlider.position(650+100,250);
}

function draw() {
      var r=rSlider.value();
      var g=gSlider.value();
      var b=bSlider.value();
      if(d==1)
     {image(img,0,0,width,height);t++;
     loadPixels(img);
     for(y=0;y<height;y++)
            for(x=0;x<width;x++)
            {
                  var index= (x+y*width)*4;
              
                  pixels[index+0]=img.pixels[index+0]+r;//r
                  pixels[index+1]=img.pixels[index+1]+g;//g
                  pixels[index+2]=img.pixels[index+2]+b;//b
                  pixels[index+3]=img.pixels[index+3];//a
            }
     updatePixels();
           
     }
print(t);
}

function highlight()
{
      dropzone.style('background-color','#ADFF2F');
}
function unhighlight()
{
      dropzone.style('background-color','#A9A9A9');
}

function gotFile(file)
{
      //createP(file.name+ " "+ file.size);
      img=createImg(file.data).hide();
      //img.size(450,450);
      d=1;
      
}

**Comment by mlarghydracept** [comment]
Hi! So this isn't a problem with the library. This behavior is as-expected. The issues page on Github is for bugs in the library. For general coding help it is best to go to [this forum and ask your question.](https://forum.processing.org/two/categories/p5-js)

With that said, while trying to evaluate your problem I made a working version of your code. This doesn't use createImg() but instead uses loadImg(). I figured you didn't need the dom element since you were hiding it anyways. For more info on how this is working you can look at [this example](https://p5js.org/examples/color-brightness.html):

```
var dropzone;
var img;
var d=0;
var t=0;


function setup() {
    var dropzone = createCanvas(800,800);
    pixelDensity(1);

    dropzone.dragOver(highlight);
    dropzone.dragLeave(unhighlight);
    dropzone.drop(gotFile, unhighlight);
    background(0);

    rSlider=createSlider(-255,255,0);
    rSlider.position(650+100,50);
    gSlider=createSlider(-255,255,0);
    gSlider.position(650+100,150);
    bSlider=createSlider(-255,255,0);
    bSlider.position(650+100,250);
}

function draw() {
    var r=rSlider.value();
    var g=gSlider.value();
    var b=bSlider.value();
    if(d==1)
    {
        image(img,400,400,img.width,img.height);
        t++;
        img.loadPixels();
        loadPixels();
        for(y=0;y<img.height;y++)
        {
            for(x=0;x<img.width;x++)
            {
            var index = (x +y*img.width)*4;
            var pixIndex = (y*width + x)*4;
            pixels[pixIndex] = img.pixels[index + 0] + r;
            pixels[pixIndex+1] = img.pixels[index + 1] + g;
            pixels[pixIndex+2] = img.pixels[index + 2] + b;
            pixels[pixIndex+3] = 255;
            }

        }

         updatePixels(); 
    }
    //print(t);
}

function highlight()
{
    background(255);
}
function unhighlight()
{
    background(0)
}

function gotFile(file)
{
//createP(file.name+ " "+ file.size);
    img=loadImage(file.data);
    
    d=1;
}
```
**Again, please only use this Github issues section when you are fairly sure there is a bug in the library.** 
 
Happy coding!

**Comment by 19valentin99** [comment]
okey thank you
