### ISSUE TITLE
Suggestion for p5.Vector.angleBetween() change

### ISSUE THREAD

**Issue by claudiohfg** [processing/p5.js#1893]
p5.Vector.angleBetween() is useful for 2D, but not very useful for 3D transformations which require 3 angles. So I suggest creating a 3D version like this one:

_function angleBetween(p1,p2) {
	var rotX = atan2(p2.z - p1.z, p2.y - p1.y);
	var rotY = atan2(p2.x - p1.x, p2.z - p1.z);
	var rotZ = atan2(p2.y - p1.y, p2.x - p1.x);
	var v = createVector(rotX,rotY,rotZ);
	// if angle in degrees
	// v.mult(180/PI);
	return v;
}
rotateX(v.x);
rotateY(v.y);
rotateZ(v.z);_

Regards

**Comment by mlarghydracept** [comment]
@claudiohfg as you say the current angleBetween() doesn't return a vector. We could make it so that the function took into account the z value (which it doesn't currently) with something like:
```
var dot = vectorA.dot(vectorB);
var lengthA = vectorA.length();
var lengthB = vectorB.length();
var angle = Math.acos( dot / (lengthA * lengthB) );
```
but if I understand correctly you are saying that for your uses you need a vector so you can rotate on the different axes. 

Do you suggest that I make a different function, separate from the current p5.Vector.angleBetween()?

**Comment by claudiohfg** [comment]
A different function would do the trick as well, angleBetween3D, perhaps?

**Comment by mlarghydracept** [comment]
@claudiohfg I implemented what you asked for in the above PR and I was about to do finishing touches when I realized that I should see how other libraries have handled this. I found that neither Processing or Three.js has a function specifically for returning vec3's for angle between two vectors in 3d space. Three.js has angleTo() for their Vector3 class but it just returns radians as p5 and processing already do. I feel like we should have a better understanding of anticipated use-cases before implementing a new function. Any thoughts? Also, maybe toy around with the above PR to see if it fulfills your specific needs, then we can go from there.

**Comment by lmccart** [comment]
processing handles 3d vectors, but it returns a float. my intuition says p5.js should do the same? https://processing.org/reference/PVector_angleBetween_.html

**Comment by mlarghydracept** [comment]
p5 already does this with the angleBetween as well if I am not mistaken

**Comment by lmccart** [comment]
@mlarghydracept ah you're right!

**Comment by claudiohfg** [comment]
Just to clarify. When I suggested this function I was implementing a boid simulation in 3D and I needed to know the direction of the collisions. So I designed the function I suggested on top. I thought it would be useful for other people. That's why I made the suggestion here. 

Please, don't feel compeled to include this functionality in p5.js if you don't feel it should be there.

**Comment by lmccart** [comment]
hi @claudiohfg thanks for the suggestion. there doesn't seem to be much comment from others in need of this function so I suggest we hold off on it for now and add it later if it seems to come into higher demand. it could be a great starting point for an addon library of helpful 3d calculation methods. @mlarghydracept don't want to discount the work you've done on this already, happy to merge if you feel it should be in there, what do you think?

**Comment by mlarghydracept** [comment]
@lmccart it is a good suggestion but I think that since p5's webGL is still very much a work in progress that it makes sense to follow in processing's example on this one. Definitely could be an addon library or it might make sense to add later once 3D is more stable generally.

**Comment by lmccart** [comment]
sounds good. let's close for now and revisit after webgl has been developed further, if we feel a need for it then.

**Comment by claudiohfg** [comment]
Thank you for taking the time to analyze my suggestion.  😄 👍
