### ISSUE TITLE
tint() slows my app

### ISSUE THREAD

**Issue by egordorichev** [processing/p5.js#1894]
Hello! I've been searching for image alpha in p5.js. Got to the `tint()` method. 
It works, but it slows my fps so much! Here is my code:

```js
	update() {
		super.update();

		if (!this.active) {
			return;
		}

		if (this.acted) {
			this.alpha = Math.max(0, this.alpha - 1);
		} else {
			this.alpha = Math.min(255, this.alpha + 1);
		}
	}

	drawBackground() {
		tint(255, 255, 255, this.alpha);
		image(textures.blackHole, 200, height / 2 - 128);
		tint(255);
	}
```

If i replace the `tint` call with `fill` call, all works fine, but not the alpha.

**Comment by limzykenneth** [comment]
@egordorichev do you have the app running somewhere? It's a bit hard to tell what the problem is with this snippet.

**Comment by egordorichev** [comment]
Sorry, but I don't. I tried the same code with image without alpha, and it worked fine. Strange..

**Comment by admoure** [comment]
It happens to me too.  If I use tint for applying transparency it slows down the sketch so much.
If I use tint at some point in my code, only one time, for example touching a key or left clicking the mouse it slows the sketch a lot.

**Comment by admoure** [comment]
Ok, you have to disable tint after use it with "noTint()".
