### ISSUE TITLE
Feature Request: p5.Oscillator missing getPhase() or getValue()

### ISSUE THREAD

**Issue by hepiyellow** [processing/p5.js#1895]
I am missing the ability to sample the current value of an oscillator.
Either the value or the phase.

This would allow to make visuals which are synced to the sound.
For example a Freq modulation oscillator , and visuals which modulate in-sync would be very nice to have. I think it is the basic of good audio-visual creations.

**Comment by lmccart** [comment]
This issue was moved to processing/p5.js-sound#167
