### ISSUE TITLE
keyIsDown() problem

### ISSUE THREAD

**Issue by rake146** [processing/p5.js#1896]
Hi, I have written some code in p5.js but detection with a keyDown press is not currently detecting, it just outputs whenever.

I have written this:
  if (keyIsDown(SHIFT));
  {
    console.log(attackCounter);
    splitblobs[0].attack();
    //attackCounter = 0;
  }
but it just outputs to the console regardless without me even pressing a button, any ideas?

**Comment by lmccart** [comment]
if you remove the semicolon at the end of the first line `if (keyIsDown(SHIFT))` it works ok for me

**Comment by rake146** [comment]
Oh yeah, my bad, I just got my syntax wrong

**Comment by rake146** [comment]
How would you check for a key press of a key like 'W'? I have tried entering the ASCII character but it isn't working.

**Comment by rake146** [comment]
Nevermind, I've solved it now!

**Comment by karniol** [comment]
What was the solution?

**Comment by montoyamoraga** [comment]
Hi @karniol!
The correct way to detect a key with an ASCII code like "w" is here
[https://p5js.org/reference/#/p5/keyCode](https://p5js.org/reference/#/p5/keyCode)
and in this site you can check the keycode of any key
[http://keycode.info/](http://keycode.info/)
for W in particular it would be 87
so some p5.js code would be 
```javascript
function keyPressed() {
  if (keyCode == 87) {
    console.log("w");
  }
}
```
