### ISSUE TITLE
httpPost() not passing data

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js#1898]
I believe this commit (c1d70b93632032c99bbcc367d7212cb953694cca) is causing an issue in 0.5.8 not present in 0.5.7. I am making a call to `httpPost()` like so:

```javascript
var data = {
  seed: 'hello'
}
httpPost('/upload', data, success, error);
```

I am console logging `arguments` in `httpDo()` in both 0.5.7 and 0.5.8. Note how the data is missing in 0.5.8.

0.5.7 (correct behavior):
<img width="342" alt="screen shot 2017-04-17 at 7 35 23 pm" src="https://cloud.githubusercontent.com/assets/191758/25108613/0b28f9c6-23a5-11e7-8bbd-7b7514fef8f4.png">

0.5.8 (incorrect behavior):
<img width="289" alt="screen shot 2017-04-17 at 7 36 14 pm" src="https://cloud.githubusercontent.com/assets/191758/25108625/29d89dea-23a5-11e7-981d-8bd51ab357a7.png">

I'm happy to investigate further and/or make a simplified example to test with.  cc @limzykenneth 

Full example is here: https://github.com/shiffman/NOC-S17-2-Intelligence-Learning/tree/master/week5-cnn-rnn-tensorflow/04b_rnn_flask_js

**Comment by limzykenneth** [comment]
@shiffman Yes, I think you are right. I wonder if the latest fix has already fixed the data object missing but actually even then it probably won't work as mentioned in #1812, I forgot to stringify the object into proper JSON so POSTing data won't work yet.

I'm planning to get a PR together today or tomorrow and if there's any more bugs, do let me know. In the meantime, if at all possible, using `httpDo` with native options is one way to get around a lot of the problems.

**Comment by limzykenneth** [comment]
@shiffman the data in your case is missing because the headers content type wasn't explicitly set to `application/json`, I should have known. @lmccart also turns out the data is stringified after all but still expect a PR for this issue.

**Comment by lmccart** [comment]
fixed with https://github.com/processing/p5.js/pull/1900
