### ISSUE TITLE
Need to update included opentype.js to current version

### ISSUE THREAD

**Issue by dhowe** [processing/p5.js#1902]
https://github.com/nodebox/opentype.js/releases

Short-term, this will give us better font-support (specifically fonts using format 12 cmap tables) and thus eliminate at least some of the problems people are having with certain fonts not loading or rendering correctly.

Longer-term, as opentype.js continues to develop (support for Chinese fonts is still weak, for example), we should integrate this into our dev-ops workflow so it happens on a somewhat regular basis.

**Comment by lmccart** [comment]
@mlarghydracept want to take a look? the todo here is to update to remove the current version of opentype we're including in the library and update to the most recent. if you run a python server and look at the examples in this folder, you can do a check that everything still looks ok: /test/manual-test-examples/p5.Font/
