### ISSUE TITLE
p5.sound Delay On Chrome crash audio of tab on Feedback change

### ISSUE THREAD

**Issue by davidrop** [processing/p5.js#1909]
Hi all, 
P5 is great...

i found a bug that happen only on Chrome, not on firefox, didn't test on other browser

if i change delay feedback while delay is processing, the entire tab stop emit sound

i wrote this script to test
https://www.davidrop.com/testdelay/

you have 3 slides that work in little different ways, all 3 slides works as intendeed on firefox. 

slide 1)  disconnect, modify feedback, reconnect
slide 2)  modify feedback without disconnect
slide 3)  disconnect, destroy the p5.Delay object, recreate the object, reconnect

this bug happen only with delay feedback, i tested filter, delay, reverb and distortion and i can update all parameters without any bug both on firefox and chrome.  

Good Work

**Comment by lmccart** [comment]
This issue was moved to processing/p5.js-sound#168
