### ISSUE TITLE
P5j as complete background in html/css webiste

### ISSUE THREAD

**Issue by BLCKPSTV** [processing/p5.js#1912]
How can I get a P5j script to behave at the very and of the background. I want my html page to act over my background P5js script.

You can view what I have here? I've tried the canvas.parent togheter with z-index. But that didn't work out. 

http://dewildequinten.be/Program-O-master/gui/jquery/?

**Comment by mlarghydracept** [comment]
The issues section of the github page is for bugs and problems with the library. If the library is behaving as expected it is better to ask general coding questions over [at the forums.](https://forum.processing.org/two/categories/p5-js) 

With that said, 'position:fixed' should be your friend. [I made an example you can look at here.](http://users.dma.ucla.edu/~stalgiag/p5_tests/p5_CANVAS_BACKGROUND/) If you want to style the site using another method it might be worth putting the canvas in an iframe.

Good luck! And in the future only post here when there are problems with the library.
