### ISSUE TITLE
sketch not playing. 

### ISSUE THREAD

**Issue by finfinwabbit** [processing/p5.js#1914]
I had this project working in Processing 3.3 and am now trying to get this to work in P5, without much success. I'm familiar with Processing but new to P5 so any help would be much appreciated. 

Here's the code, below. I'm getting a blank white page. I'm sure I'm using incorrect code in P5 here. 

var song, analyzer;

function preload() {
  song = loadSound('assets/enzo.mp3');//tis is the audio file, which does work
}
var  r = 200;
var rad = 70;

function setup()
{
  size(displayWidth, displayHeight);
  song.loop();
  // create a new Amplitude analyzer
  analyzer = new p5.Amplitude();

  // Patch the input to an volume analyzer
  analyzer.setInput(song);
  background(1);
  noCursor();
}

function draw()
{ var rms = analyzer.getLevel();
  var t = map(mouseX, 0, width, 0, 1);
  fill(1); 
  noStroke();
  translate(width/2, height/2);
  if (song.isOnset()) rad = rad*0.3;
//not sure what to use instead of isOnset here. Can't find a reference for this in P5
  else rad = 70;
  ellipse(random(10), random(100), 2*rad, 2*rad);
  stroke(10, 50);
  int bsize = player.bufferSize();
  for (int i = 0; i < bsize - 1; i+=5)
  {
    var x = (r)*cos(i*13*PI/bsize);
    var y = (r)*sin(i*14*PI/bsize);
    var x2 = (r + player.left.get(i)*150)*cos(i*12*PI/bsize);
    var y2 = (r + player.left.get(i)*150)*sin(i*12*PI/bsize);
    line(x, y, x2, y2);
  }
  beginShape();
  noFill();
  stroke(random(255), random(255), random(255)); 
  for (int i = 0; i < bsize; i+=1)
  {
    var x2 = (r + player.left.get(i)*100)*cos(i*12*PI/bsize);
    var y2 = (r + player.left.get(i)*100)*sin(i*12*PI/bsize);
    vertex(x2, y2);
    pushStyle();
    stroke(0, 0, random(255));
    strokeWeight(random(21));
    point(x2, y2);
    popStyle();
  }
  endShape(CLOSE);
  if (flag)
  showMeta();
}

void showMeta() {
  int time =  meta.length();
  textSize(50);
  textAlign(CENTER);
  text( (int)(time/1000-millis()/1000)/60 + ":"+ (time/1000-millis()/1000)%60, -7, 21);
}

boolean flag =false;
void mousePressed() {
  if (dist(mouseX, mouseY, width/2, height/2)<150) flag =!flag;
}

//
//boolean sketchFullScreen() {
 // return true;
//}

/*void keyPressed() {
  if(key==' ')exit();
  if(key=='s')saveFrame("###.jpeg");
}*/

**Comment by limzykenneth** [comment]
@finfinwabbit `size(displayWidth, displayHeight);` should be `createCanvas(displayWidth, displayHeight);`. I didn't go through the rest so I'm not sure if you have any other mistakes. This kind of question is better suited to the [forum](https://forum.processing.org), where github issues are more for reporting bugs and feature requests. If you encounter any more problem, it will be better for you to post them over at the forum.
