### ISSUE TITLE
Position Canvas with canvas.parent ERROR

### ISSUE THREAD

**Issue by BLCKPSTV** [processing/p5.js#1915]
Hi, I've made a working canvas.parent whilst also getting the sketch on the background!

Now after several changes in the css part of my page I get an ERROR specified as a P5js error..

```
sketch.js:9 Uncaught TypeError: canvas.parent is not a function
    at setup (sketch.js:9)
    at p5.<anonymous> (p5.js:12317)
    at p5.<anonymous> (p5.js:12260)
    at new p5 (p5.js:12522)
    at _globalInit (p5.js:9042)
```

I don't know this count as a bug or not? But it strange that it worked and/if  the css made it stop working..? Didn't change anything to any part of the js side. And I got a working example as first.

**Comment by lmccart** [comment]
make sure that the p5.dom library is linked in your HTML. please follow up on this question by posting in the forum, the github issues are just for library specific bugs and feature requests.
http://forum.processing.org
