### ISSUE TITLE
nf() should allow formatting numbers without rounding

### ISSUE THREAD

**Issue by yanickrochon** [processing/p5.js#1921]
With a given value `a = 99.99943`, I'd like `nf(a, 0, 3)` to return `99.999` and not `100.000`.

**Comment by limzykenneth** [comment]
@yanickrochon `nf(99.99943, 0, 3)` does return `99.999`, can you show a simple example of it rounding to `100.00`? Thanks.

**Comment by yanickrochon** [comment]
Ah! I wanted to keep the example simple, but here is the actual tipping point (just tested)

```
nf(99.999999999999992, 0, 3)
"99.999"
nf(99.999999999999993, 0, 3)
"100.000"
````

**Comment by limzykenneth** [comment]
@yanickrochon right, that's what I suspected. What you have there is something we call "floating point precision error". I won't go into details of what it means as [this video](https://www.youtube.com/watch?v=PZRI1IfStY0) explains it perfectly.

In short, computers cannot process numbers larger than a certain extend or process numbers smaller than a certain extend, if that happens, binary rounding occurs. Thus, in your case, `99.999999999999992` is interpreted as `99.99999999999999` and `99.999999999999993` as `100`. Run the following code to see what I mean.

```javascript
var a = 99.999999999999992;
var b = 99.999999999999993;

console.log("a = ", a);
console.log("b = ", b);
```

In most cases, you will not require that amount of precision so you don't need to worry about it.

**Comment by yanickrochon** [comment]
I understand IEEE format :smile:  This is why `0.3 - 0.2 = 0.09999999999999998`...

I should try to find the actual value that I had, but it was a computed one which was displayed as `99.99999....` but when calling `.toFixed(3)`, it printed `100.000` (because of rounding up). So I tried `nf` and it behaved the same.

**Comment by limzykenneth** [comment]
@yanickrochon there may be instances in the library where prior to getting the final result the number may have been divided by (let's say) 10 then multiplied by 10 again as part of the algorithm (or something similar), and so became too precise for floating point number. If you can find the offending number, I or someone else can have a look to see if we can prevent rounding from happening.

**Comment by lmccart** [comment]
I'm going to close for now, @yanickrochon please feel free to reopen if you can provide an example number that illustrates this issue. Thanks!
