### ISSUE TITLE
create and maintain a CHANGELOG.md

### ISSUE THREAD

**Issue by 8-uh** [processing/p5.js#1922]
I keep up with p5.js and the community surrounding it. However, it seems like an accident when I notice there's a version bump, and even worse still, I generally have no idea what's changed.

Using the `conventional-changelog-cli` tool, we can easily create a living document. For right now, I propose the following workflow:

Prior to cutting a new tag before the next release:
* bump version in `package.json`
* run `$ conventional-changelog  -i CHANGELOG.md -s` in the repo directory
* commit `package.json` and `CHANGELOG.md`
* Cut a tag
* Push a release

I've gone ahead and created a CHANGELOG.md for the current state of master and will create a PR for it momentarily.

**Comment by lmccart** [comment]
I'm not hearing a lot of other comments on this, so I'm happy to stick with the current changelog we have for now
