### ISSUE TITLE
contouring not working on WEBGL

### ISSUE THREAD

**Issue by dvinazza** [processing/p5.js#1924]
Is contouring supposed to work on WEBGL?

I've taken the beginContour example from the reference. First part works OK (adding the z component to the vertex), but when I add the contour part the following error appears:

> p5.min.js:6 Uncaught TypeError: Cannot read property 'slice' of undefined
>     at e.d.endContour (p5.min.js:6)
>     at draw (p5-sketch.js:61)
>     at e.d.redraw (p5.min.js:6)
>     at e.<anonymous> (p5.min.js:4)
>     at e.<anonymous> (p5.min.js:4)
>     at new e (p5.min.js:5)
>     at e (p5.min.js:4)

I'm using p5.js v0.5.8 March 25, 2017 and Chrome Version 57.0.2987.110 (64-bit).

**Comment by lmccart** [comment]
this is not currently implemented in webgl mode
