### ISSUE TITLE
saveTable function needs three arguments

### ISSUE THREAD

**Issue by stevengreens10** [processing/p5.js#1929]
Currently the saveTable function is used as follows: saveTable(table,filename,options), where options is the type of file you're saving the table as. The options argument seems unnecessary since you can just look at the extension of the filename argument to achieve the same result.

Example usage of saveTable: `saveTable(table,"table.csv","csv");`
Proposed usage: `saveTable(table,"table.csv");`

I can submit a pull request with the necessary changes if desired.

**Comment by lmccart** [comment]
that makes sense to me. should we also remove this argument from the [loadTable()](https://p5js.org/reference/#/p5/loadTable) signature as well then? @limzykenneth has your work on the load methods revealed any reason why we couldn't just grab the "csv" or "tsv" from the filename?

**Comment by stevengreens10** [comment]
@lmccart I suspect that it's possible to remove it for loadTable() as well, but it does take in "header" as one of its options; whereas, saveTable() only takes in the type of file in the options argument. In my pull request (#1930), I made it so saveTable() works when given the options argument and when it's left blank, so something similar could presumably work for loadTable() too.

**Comment by limzykenneth** [comment]
@lmccart @stevengreens10 grabbing the format from the filename will mean that the filename must have an extension. That may not be desired especially when you are loading something over a dynamic link, it may be something like: `www.sometables.com/?tableID=1` you know it will return csv but you need to let the code knows that either by some kind of detection or by explicitly specifying it.

I would prefer overloaded parameters to support both signatures in `loadTable()` at least.

**Comment by lmccart** [comment]
@limzykenneth ah right, that makes sense. @stevengreens10 do you want to look into doing a similar approach of extension grabbing if none is specified for loadTable()?

**Comment by stevengreens10** [comment]
@lmccart Yes I'll do that today
