### ISSUE TITLE
screen.width vs window.innerWidth

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js#193]
As of now `displayWidth` returns `screen.width`.  However I think that a sometimes useful value (for when a browser is not fullscreen) is `window.innerWidth`.  Should we have something like `windowWidth` and `windowHeight`?

Related to this, I'm trying to create an example where a canvas resizes when `onresize` is triggered.  `size()` works but the global `width` and `height` are unaffected.  Not sure if we should have a global `resizeCanvas()` method or just in this situation I should be required to say `ellipse(canvas.width/2,canvas.height/2,100,100);`

Below works FYI.

```
var canvas;

function setup() {
  canvas = createCanvas(window.innerWidth, window.innerHeight);
}

function draw() {
  background(51);
  fill(255);
  ellipse(width/2,height/2,100,100);
}

window.onresize = function() {
  var w = window.innerWidth;
  var h = window.innerHeight;  
  canvas.size(w,h);
  width = w;
  height = h;
};
```

**Comment by webinger** [comment]
Hey I am playing around with this code
<code>
function setup() {
  canvas = createCanvas(window.innerWidth, window.innerHeight);
}

 window.onresize = function() {
  var w = window.innerWidth;
  var h = window.innerHeight;  
  canvas.size(w,h);
  width = w;
  height = h;
};
</code>

But when I resize my browser window it does not set the canvas size instantly. 
What am I doing wrong?

**Comment by lmccart** [comment]
hi @webinger please see the `resizeCanvas()` function: http://p5js.org/reference/#p5/resizeCanvas

**Comment by RGFTheCoder** [comment]
@webinger did you declare the "canvas" object?
```javascript
var canvas = createCanvas(window.innerWidth, window.innerHeight);
```

**Comment by abhi0977** [comment]
> ok, I just pushed some fixes for `windowWidth/Height` and `width` and `height` updating on `size()` call.
> 
> this should work:
> 
> ```js
> var canvas;
> 
> function setup() {
>   canvas = createCanvas(windowWidth,windowHeight);
> }
> 
> function draw() {
>   background(51);
>   ellipse(width/2,height/2,width/2,height/2);
> }
> 
> window.onresize = function() {
>   canvas.size(windowWidth, windowHeight);
> };
> ```

@lmccart In safari when you directly maximise the screen then view will not get updated.

**Comment by Spongman** [comment]
Shouldn’t you be using `resiseCanvas()` if you want the tenderer to resize?

**Comment by entozoon** [comment]
Yes, a more up to date example is:
https://p5js.org/reference/#/p5/resizeCanvas
