### ISSUE TITLE
Nice to have for httpDo

### ISSUE THREAD

**Issue by limzykenneth** [processing/p5.js#1937]
I just noticed some missing feature in `httpDo()` `httpPost()`, specifically the `data` option currently do not accept arrays or numbers which I think it should. 

I can only get to this earliest next week so if anyone else wants to tackle this before I get to it, do feel free.

**Comment by lmccart** [comment]
@mlarghydracept want to check this one out?

**Comment by JMandel1027** [comment]
hi! I had some free time this evening and made a fix on `httpDo()` `httpPost` I'm going to run some more tests and then make a pull request~!! (my first ever n_n)

**Comment by mlarghydracept** [comment]
@jay-manday still want to work this one out? I'll unassign myself if so.

**Comment by jay-manday** [comment]
@mlarghydracept yup! @limzykenneth and I have been working on this 🌮

**Comment by lmccart** [comment]
this should be all set from https://github.com/processing/p5.js/commit/41dfb9a395c55d4170d1cc082ee098bda8d77843. httpGet is covered by the change to httpDo

**Comment by jay-manday** [comment]
yup! thanks again @lmccart & @limzykenneth was great working with you both on this!
