### ISSUE TITLE
remove multiple canvas example from manual-test-examples folder

### ISSUE THREAD

**Issue by Shubham-19** [processing/p5.js#1941]
When I use multiple canvases I get an Uncaught Reference error : Context not defined
Please help

**Comment by bmoren** [comment]
Can you post a simplified/isolated example of the code you are trying to get to work so someone can try to verify whats going on.

**Comment by Shubham-19** [comment]
Please check the code in the link:
https://github.com/processing/p5.js/blob/4dd42f2136400d33b4eca521b218b07636e16011/test/manual-test-examples/tutorials/DOM-extensions/5/sketch.js

**Comment by Shubham-19** [comment]
I'am sending you the link of the code, please see if someone can find some
error:
https://github.com/processing/p5.js/blob/4dd42f2136400d33b4eca521b218b07636e16011/test/manual-test-examples/tutorials/DOM-extensions/5/sketch.js

**Comment by lmccart** [comment]
this is an outdated example. multiple canvases is no longer supported in p5.js. you could use createGraphics() to create the effect of a second drawing surface. sorry for the confusion.
@TODO remove this example from github repository.

**Comment by bmoren** [comment]
you might also look into instance mode which will let you run multiple instances of p5: https://github.com/processing/p5.js/wiki/Global-and-instance-mode

**Comment by Shubham-19** [comment]
Thank u
