### ISSUE TITLE
 Does resizing the canvas work if you scroll the page?

### ISSUE THREAD

**Issue by 1rulesupersedes** [processing/p5.js#1942]
I want to use the canvas as a background. I used this code. Unfortunately when I scroll the page the canvas doesn't cover the scroll.

function windowResized() {
  resizeCanvas(windowWidth, windowHeight);
}

function setup(){
	canvas = createCanvas(windowWidth, windowHeight);
	canvas.position(0,0);
	canvas.style('z-index', '-1');
	background(250,250,250);
}

**Comment by mlarghydracept** [comment]
Hi! The github issues page is for bugs with the library and feature requests. For general coding problems you should [use the forum](https://forum.processing.org/two/categories/p5-js).

With that said, it is hard to tell exactly what you want to do with library from your code but my instinct is to say that you will be better off using the [css position property](https://developer.mozilla.org/en-US/docs/Web/CSS/position?v=control) to keep a full window canvas that isn't effected by scrolling.

Best of luck!
