### ISSUE TITLE
unpredictable behavior with multiple background calls

### ISSUE THREAD

**Issue by lmccart** [processing/p5.js#1946]
```javascript
function setup() { 
  createCanvas(400, 400);
} 

function draw() { 
  background(220);
  //print(mouseIsPressed);
  if (mouseIsPressed == true)
    background('red');

}
```

The above code yields unpredictable results... sometimes you see red, but mostly you see gray. Commenting in the print line fixes the sketch to have expected behavior.

Since both background calls take effect as soon as they are called, I think it is flipping between the two background calls so fast, the result is unpredictable, and the most time actually gets spent in the if statement, resulting in seeing mostly gray.

Is this the intended behavior? Do we just suggest people use if/else instead of overwriting a call with an if? Or is there some change to be made to the library?

I'm not sure this is limited to background, it could affect other functions as well.

**Comment by mikewesthad** [comment]
I tried that snippet out against 0.5.9 in FF/Chrome/Edge on Windows 10, but it just gave me the expected result: red only when any mouse button is currently pressed. Ditto on an emulated mac. What's the machine setup that shows the bug?
