### ISSUE TITLE
mouseDragged event not Firing with version 0.5.10

### ISSUE THREAD

**Issue by seamiki** [processing/p5.js#1953]
Hello,
tried a simple sketch with a mouseDragged event, that was working as of version 0.5.9,
but it seems that the event is not firing with version 0.5.10.
same thing happens with the touchMoved event.

Same behavior with the example in the reference on chromium and firefox.
Did anyone else come across the same issue?

below is a testing example

```
function setup() {
  createCanvas(windowWidth,windowHeight);
  background(255,200,0);
}

function draw() {
}

function mouseDragged(){
  noStroke();
  fill(200, 0, 200,60);
  ellipse(mouseX,mouseY, 30,30);
  return false;
}
```

**Comment by nbogie** [comment]
Hi, see #1949

**Comment by mlarghydracept** [comment]
PR #1952  fixes this issue as well.
