### ISSUE TITLE
reference items that need examples

### ISSUE THREAD

**Issue by lmccart** [processing/p5.js#1954]
[this wiki section](https://github.com/processing/p5.js/wiki/Inline-documentation#adding-example-code) contains info on how to add examples. anyone, please feel free to add to this list with reference entries that could use examples added.

- [ ] https://p5js.org/reference/#/p5.MediaElement/connect
- [ ] https://p5js.org/reference/#/p5.MediaElement/disconnect
- [x] https://p5js.org/reference/#/p5.Graphics/remove
- [x] https://p5js.org/reference/#/p5.PrintWriter/write
- [x] https://p5js.org/reference/#/p5.PrintWriter/print
- [x] https://p5js.org/reference/#/p5.PrintWriter/flush
- [x] https://p5js.org/reference/#/p5.PrintWriter/close
- [ ] https://p5js.org/reference/#/p5/setMoveThreshold
- [ ] https://p5js.org/reference/#/p5/setShakeThreshold
- [ ] https://p5js.org/reference/#/p5/save
- [x] https://p5js.org/reference/#/p5.Table.js:397: method p5.Table.matchRow
- [x] https://p5js.org/reference/#/p5.Table.js:637: method p5.Table.getColumnCount
- [x] https://p5js.org/reference/#/p5.Table.js:647: method p5.Table.getRowCount
- [x] https://p5js.org/reference/#/p5.Table.js:657: method p5.Table.removeTokens
- [x] https://p5js.org/reference/#/p5.Table.js:706: method p5.Table.trim
- [x] https://p5js.org/reference/#/p5.Table.js:907: method p5.Table.setString
- [x] https://p5js.org/reference/#/p5.Table.js/getArray
- [x] https://p5js.org/reference/#/p5.TableRow.js:43: method p5.TableRow.set
- [x] https://p5js.org/reference/#/p5.TableRow.js:74: method p5.TableRow.setNum
- [x] https://p5js.org/reference/#/p5.TableRow.js:89: method p5.TableRow.setString
- [x] https://p5js.org/reference/#/p5.TableRow.js:104: method p5.TableRow.get
- [x] https://p5js.org/reference/#/p5.TableRow/getNum
- [x] https://p5js.org/reference/#/p5.TableRow/getString
- [x] https://p5js.org/reference/#/p5.XML/addChild
- [ ] https://p5js.org/reference/#/p5/orbitControl
- [ ] https://p5js.org/reference/#/p5/loadShader
- [ ] https://p5js.org/reference/#/p5/shader
- [ ] https://p5js.org/reference/#/p5.Geometry/computeFaces
- [ ] https://p5js.org/reference/#/p5.Geometry/computeNormals
- [ ] https://p5js.org/reference/#/p5.Geometry/averageNormals
- [ ] https://p5js.org/reference/#/p5.Geometry/averagePoleNormals
- [ ] https://p5js.org/reference/#/p5.Geometry/normalize
- [ ] https://p5js.org/reference/#/p5.RendererGL/beginShape
- [x] https://p5js.org/reference/#/p5.RendererGL/vertex
- [ ] https://p5js.org/reference/#/p5.RendererGL/get
- [ ] https://p5js.org/reference/#/p5.RendererGL/loadPixels
- [ ] https://p5js.org/reference/#/p5.Shader/setUniform
- [ ] https://p5js.org/reference/#/p5.Texture/update
- [ ] https://p5js.org/reference/#/p5.Texture/bindTexture
- [ ] https://p5js.org/reference/#/p5.Texture/unbindTexture

**Comment by Thzn** [comment]
Hi,

I would like to contribute to p5js by adding examples listed in this issue. I have made an example for httpDo() method as my first contribution. 
But I'm new to this Open Source project related documentation. Can you please give me some guidance.  

Thank You.

**Comment by lmccart** [comment]
@Thzn glad you want to contribute, thanks! In addition to the wiki section listed above, you may first want to check out this [hello world github introduction](https://guides.github.com/activities/hello-world/) and the other [github guides](https://guides.github.com/) and then watch the [looking inside p5.js](http://www.luisapereira.net/teaching/looking-inside-p5/) videos to get an overview of the file structure and tools of p5.js.

[this section of the wiki](https://github.com/processing/p5.js/wiki/Inline-documentation#adding-example-code) explains how to add examples into the source code.

**Comment by Thzn** [comment]
@lmccart 
Thank you for the instructions  ...!. I will finish it soon...

**Comment by outofambit** [comment]
hi! what is the proposed workflow for testing and adding examples? should i write them in a separate context and then copy paste into the inline comments?

i'm trying to build and view the documentation locally (by following https://github.com/processing/p5.js/wiki/Inline-documentation#adding-example-code) to verify that my example works, but am having no luck. (getting this: 
![local reference running](https://user-images.githubusercontent.com/964912/29496850-08964720-85a9-11e7-8ee0-c798f8f94d66.png)
)

am i going about this wrong? thanks!

**Comment by lmccart** [comment]
@outofambit sorry that was out of date. running `grunt yui` should now generate docs that can be viewed at localhost/docs/reference, and are also ready to be copied to p5js.org. the fonts may not link correctly if viewing locally due to cross-origin permissions, but the examples should render.

**Comment by outofambit** [comment]
@lmccart thanks i'll give that a try!

**Comment by austince** [comment]
@Thzn are you still working on the HTTP methods? 

In the meantime, I'd like to contribute the Element/elt, Element/class, and Element/removeClass!

**Comment by Thzn** [comment]
@austince 
No, I'm not working on them right now. I had a problem with the docker. So I posted about it on the page (https://github.com/toolness/p5.js-docker/issues/13) . I think he is working on it. You can implement them as well.....

**Comment by bomoko** [comment]
Been meaning to return to this for a while.
I don't see anyone else working on the MediaElement examples - so I'd like to take them on.

**Comment by hackertron** [comment]
is this issue still open ?

**Comment by lmccart** [comment]
@hackertron yes!

**Comment by odm275** [comment]
#2426 is my first pull request ever. I added an example for the volume method. I ran grunt locally and passed all the tests, but it appears my pull request didn't pass. Additional feedback is appreciated!

**Comment by gr2m** [comment]
@lmccart I think https://p5js.org/reference/#/p5/httpGet & https://p5js.org/reference/#/p5.MediaElement/speed already have example?

But formatting looks off in https://p5js.org/reference/#/p5.MediaElement/speed. We are looking into it with @baconthorpe at the [Fullstack LA meetup](https://www.meetup.com/la-fullstack/events/245681074/) tonight :)

**Comment by gr2m** [comment]
we run into some trouble with generating the docs and seeing it locally. Here is what we did

1. run `./node_modules/.bin/grunt requirejs:yuidoc_theme`
2. run `npm run docs`
3. run `npm run build`
4. copy these files into `docs/reference/assets/js`
  - addons/p5.dom.min.js
  - addons/p5.sound.min.js
  - p5.min.js
5. start http server in `docs/reference` folder, e.g. with `python -m SimpleHTTPServer`

**Comment by lmccart** [comment]
hm that should be the right sequence. what do you see when you visit that file?
it does look like the formatting for speed has an error.

**Comment by Spongman** [comment]
I use 'grunt yui:prod browserify connect watch:yui'

**Comment by gr2m** [comment]
@lmccart the documentation doesn’t mention all these steps: https://github.com/processing/p5.js/wiki/Inline-documentation#generating-documentation

We also had a problem with with the pre commit hook which run linting

<details>
  <summary>
  <code>git commit -m 'blup'</code>
  </summary>
husky > npm run -s precommit (node v8.9.1)

 ↓ Running tasks for Gruntfile.js [skipped]
   → No staged files match Gruntfile.js
 ↓ Running tasks for grunt-karma.js [skipped]
   → No staged files match grunt-karma.js
 ↓ Running tasks for docs/preprocessor.js [skipped]
   → No staged files match docs/preprocessor.js
 ↓ Running tasks for utils/**/*.js [skipped]
   → No staged files match utils/**/*.js
 ↓ Running tasks for tasks/**/*.js [skipped]
   → No staged files match tasks/**/*.js
 ↓ Running tasks for bench/**/*.js [skipped]
   → No staged files match bench/**/*.js
 ↓ Running tasks for test/test-docs-preprocessor/**/*.js [skipped]
   → No staged files match test/test-docs-preprocessor/**/*.js
 ↓ Running tasks for test/node/**/*.js [skipped]
   → No staged files match test/node/**/*.js
 ↓ Running tasks for test/reporter/**/*.js [skipped]
   → No staged files match test/reporter/**/*.js
 ↓ Running tasks for test/unit/**/*.js [skipped]
   → No staged files match test/unit/**/*.js
 ❯ Running tasks for lib/addons/p5.dom.js
   ✖ eslint
     node ./utils/sample-linter.js
 ↓ Running tasks for src/**/*.js [skipped]
   → No staged files match src/**/*.js
✖ eslint found some errors. Please fix them and try committing again.

/Users/gregor/Projects/p5.js/lib/addons/p5.dom.js
    29:25  error  Replace `"function"` with `'function'`                                                                                                                                            prettier/prettier
    30:12  error  Replace `"p5.dom",·["p5"` with `'p5.dom',·['p5'`                                                                                                                                  prettier/prettier
    33:31  error  Replace `"object")·factory(require("../p5"` with `'object')·factory(require('../p5'`                                                                                              prettier/prettier
    34:21  error  Replace `"p5"` with `'p5'`                                                                                                                                                        prettier/prettier
    72:28  error  Replace `"select"` with `'select'`                                                                                                                                                prettier/prettier
    75:18  error  Replace `"."` with `'.'`                                                                                                                                                          prettier/prettier
    83:25  error  Replace `"#"` with `'#'`                                                                                                                                                          prettier/prettier
   143:28  error  Replace `"selectAll"` with `'selectAll'`                                                                                                                                          prettier/prettier
   147:18  error  Replace `"."` with `'.'`                                                                                                                                                          prettier/prettier
   167:22  error  Replace `"string"·&&·p[0]·===·"#"` with `'string'·&&·p[0]·===·'#'`                                                                                                                prettier/prettier
   182:25  error  Replace `"INPUT"·&&·elt.type·===·"checkbox"` with `'INPUT'·&&·elt.type·===·'checkbox'`                                                                                            prettier/prettier
   195:32  error  Replace `"VIDEO"·||·elt.tagName·===·"AUDIO"` with `'VIDEO'·||·elt.tagName·===·'AUDIO'`                                                                                            prettier/prettier
   197:32  error  Replace `"SELECT"` with `'SELECT'`                                                                                                                                                prettier/prettier
   223:28  error  Replace `"removeElements"` with `'removeElements'`                                                                                                                                prettier/prettier
   284:15  error  Replace `"div",·"p",·"span"` with `'div',·'p',·'span'`                                                                                                                            prettier/prettier
   286:18  error  Replace `"create"` with `'create'`                                                                                                                                                prettier/prettier
   289:51  error  Replace `""` with `''`                                                                                                                                                            prettier/prettier
   311:28  error  Replace `"createImg"` with `'createImg'`                                                                                                                                          prettier/prettier
   312:38  error  Replace `"img"` with `'img'`                                                                                                                                                      prettier/prettier
   318:49  error  Replace `"function"` with `'function'`                                                                                                                                            prettier/prettier
   321:56  error  Replace `"function"` with `'function'`                                                                                                                                            prettier/prettier
   327:47  error  Replace `"string"` with `'string'`                                                                                                                                                prettier/prettier
   354:28  error  Replace `"createA"` with `'createA'`                                                                                                                                              prettier/prettier
   355:38  error  Replace `"a"` with `'a'`                                                                                                                                                          prettier/prettier
   407:28  error  Replace `"createSlider"` with `'createSlider'`                                                                                                                                    prettier/prettier
   408:38  error  Replace `"input"` with `'input'`                                                                                                                                                  prettier/prettier
   409:16  error  Replace `"range"` with `'range'`                                                                                                                                                  prettier/prettier
   417:26  error  Replace `"number"` with `'number'`                                                                                                                                                prettier/prettier
   450:28  error  Replace `"createButton"` with `'createButton'`                                                                                                                                    prettier/prettier
   451:38  error  Replace `"button"` with `'button'`                                                                                                                                                prettier/prettier
   484:28  error  Replace `"createCheckbox"` with `'createCheckbox'`                                                                                                                                prettier/prettier
   485:38  error  Replace `"div"` with `'div'`                                                                                                                                                      prettier/prettier
   486:43  error  Replace `"input"` with `'input'`                                                                                                                                                  prettier/prettier
   487:21  error  Replace `"checkbox"` with `'checkbox'`                                                                                                                                            prettier/prettier
   492:46  error  Replace `"input"` with `'input'`                                                                                                                                                  prettier/prettier
   512:42  error  Replace `"label"` with `'label'`                                                                                                                                                  prettier/prettier
   513:29  error  Replace `"id"` with `'id'`                                                                                                                                                        prettier/prettier
   560:28  error  Replace `"createSelect"` with `'createSelect'`                                                                                                                                    prettier/prettier
   563:24  error  Replace `"object"·&&·arg.elt.nodeName·===·"SELECT"` with `'object'·&&·arg.elt.nodeName·===·'SELECT'`                                                                              prettier/prettier
   567:36  error  Replace `"select"` with `'select'`                                                                                                                                                prettier/prettier
   568:33  error  Replace `"boolean"` with `'boolean'`                                                                                                                                              prettier/prettier
   569:26  error  Replace `"multiple",·"true"` with `'multiple',·'true'`                                                                                                                            prettier/prettier
   598:42  error  Replace `"option"` with `'option'`                                                                                                                                                prettier/prettier
   616:35  error  Replace `"multiple"` with `'multiple'`                                                                                                                                            prettier/prettier
   679:28  error  Replace `"createRadio"` with `'createRadio'`                                                                                                                                      prettier/prettier
   680:44  error  Replace `"input[type=radio]"` with `'input[type=radio]'`                                                                                                                          prettier/prettier
   697:38  error  Replace `"div"` with `'div'`                                                                                                                                                      prettier/prettier
   701:40  error  Replace `"input"` with `'input'`                                                                                                                                                  prettier/prettier
   702:18  error  Replace `"radio"` with `'radio'`                                                                                                                                                  prettier/prettier
   706:24  error  Replace `"name",·"defaultradio"` with `'name',·'defaultradio'`                                                                                                                    prettier/prettier
   710:44  error  Replace `"label"` with `'label'`                                                                                                                                                  prettier/prettier
   711:26  error  Replace `"id",·"defaultradio"·+·count·+·"-"` with `'id',·'defaultradio'·+·count·+·'-'`                                                                                            prettier/prettier
   712:25  error  Replace `"defaultradio"·+·count·+·"-"` with `'defaultradio'·+·count·+·'-'`                                                                                                        prettier/prettier
   748:16  error  Replace `""` with `''`                                                                                                                                                            prettier/prettier
   777:28  error  Replace `"createInput"` with `'createInput'`                                                                                                                                      prettier/prettier
   778:38  error  Replace `"input"` with `'input'`                                                                                                                                                  prettier/prettier
   779:30  error  Replace `"text"` with `'text'`                                                                                                                                                    prettier/prettier
   816:28  error  Replace `"createFileInput"` with `'createFileInput'`                                                                                                                              prettier/prettier
   840:28  error  Replace `"text"` with `'text'`                                                                                                                                                    prettier/prettier
   850:40  error  Replace `"input"` with `'input'`                                                                                                                                                  prettier/prettier
   851:18  error  Replace `"file"` with `'file'`                                                                                                                                                    prettier/prettier
   857:24  error  Replace `"multiple"` with `'multiple'`                                                                                                                                            prettier/prettier
   861:28  error  Replace `"change"` with `'change'`                                                                                                                                                prettier/prettier
   865:9   error  Replace `"The·File·APIs·are·not·fully·supported·in·this·browser.·Cannot·create·element."` with `'The·File·APIs·are·not·fully·supported·in·this·browser.·Cannot·create·element.'`  prettier/prettier
   876:18  error  Replace `""` with `''`                                                                                                                                                            prettier/prettier
   877:24  error  Replace `"string"` with `'string'`                                                                                                                                                prettier/prettier
   881:43  error  Replace `"source"` with `'source'`                                                                                                                                                prettier/prettier
   885:29  error  Replace `"undefined"` with `'undefined'`                                                                                                                                          prettier/prettier
   888:33  error  Replace `"canplaythrough"` with `'canplaythrough'`                                                                                                                                prettier/prettier
   890:28  error  Replace `"canplaythrough"` with `'canplaythrough'`                                                                                                                                prettier/prettier
   896:26  error  Replace `"loadedmetadata"` with `'loadedmetadata'`                                                                                                                                prettier/prettier
   930:28  error  Replace `"createVideo"` with `'createVideo'`                                                                                                                                      prettier/prettier
   931:30  error  Replace `"video"` with `'video'`                                                                                                                                                  prettier/prettier
   970:28  error  Replace `"createAudio"` with `'createAudio'`                                                                                                                                      prettier/prettier
   971:30  error  Replace `"audio"` with `'audio'`                                                                                                                                                  prettier/prettier
   976:24  error  Replace `"video"` with `'video'`                                                                                                                                                  prettier/prettier
   977:24  error  Replace `"audio"` with `'audio'`                                                                                                                                                  prettier/prettier
   998:21  error  Replace `"getUserMedia·is·not·implemented·in·this·browser"` with `'getUserMedia·is·not·implemented·in·this·browser'`                                                              prettier/prettier
  1063:28  error  Replace `"createCapture"` with `'createCapture'`                                                                                                                                  prettier/prettier
  1073:42  error  Replace `"object"` with `'object'`                                                                                                                                                prettier/prettier
  1075:42  error  Replace `"function"` with `'function'`                                                                                                                                            prettier/prettier
  1080:40  error  Replace `"video"` with `'video'`                                                                                                                                                  prettier/prettier
  1089:17  error  Replace `"srcObject"` with `'srcObject'`                                                                                                                                          prettier/prettier
  1106:13  error  Replace `"getUserMedia·not·supported·in·this·browser"` with `'getUserMedia·not·supported·in·this·browser'`                                                                        prettier/prettier
  1111:26  error  Replace `"loadedmetadata"` with `'loadedmetadata'`                                                                                                                                prettier/prettier
  1140:28  error  Replace `"createElement"` with `'createElement'`                                                                                                                                  prettier/prettier
  1142:28  error  Replace `"undefined"` with `'undefined'`                                                                                                                                          prettier/prettier
  1170:49  error  Replace `"·"` with `'·'`                                                                                                                                                          prettier/prettier
  1203:28  error  Replace `"(?:^|\\s)"·+·c·+·"(?!\\S)"` with `'(?:^|\\s)'·+·c·+·'(?!\\S)'`                                                                                                          prettier/prettier
  1204:60  error  Replace `""` with `''`                                                                                                                                                            prettier/prettier
  1205:67  error  Replace `""` with `''`                                                                                                                                                            prettier/prettier
  1238:22  error  Replace `"undefined"` with `'undefined'`                                                                                                                                          prettier/prettier
  1241:22  error  Replace `"string"` with `'string'`                                                                                                                                                prettier/prettier
  1242:20  error  Replace `"#"` with `'#'`                                                                                                                                                          prettier/prettier
  1273:45  error  Replace `"none"` with `'none'`                                                                                                                                                    prettier/prettier
  1274:56  error  Replace `"none"` with `'none'`                                                                                                                                                    prettier/prettier
  1279:30  error  Replace `"block"` with `'block'`                                                                                                                                                  prettier/prettier
  1282:53  error  Replace `"block"` with `'block'`                                                                                                                                                  prettier/prettier
  1289:19  error  Replace `"both"` with `'both'`                                                                                                                                                    prettier/prettier
  1291:26  error  Replace `"horizontal"` with `'horizontal'`                                                                                                                                        prettier/prettier
  1293:26  error  Replace `"vertical"` with `'vertical'`                                                                                                                                            prettier/prettier
  1297:16  error  Replace `"display"` with `'display'`                                                                                                                                              prettier/prettier
  1301:53  error  Replace `"none"` with `'none'`                                                                                                                                                    prettier/prettier
  1366:33  error  Replace `"absolute"` with `'absolute'`                                                                                                                                            prettier/prettier
  1367:44  error  Replace `"px"` with `'px'`                                                                                                                                                        prettier/prettier
  1368:43  error  Replace `"px"` with `'px'`                                                                                                                                                        prettier/prettier
  1377:31  error  Replace `"absolute"` with `'absolute'`                                                                                                                                            prettier/prettier
  1379:21  error  Replace `""` with `''`                                                                                                                                                            prettier/prettier
  1381:74  error  Replace `""` with `''`                                                                                                                                                            prettier/prettier
  1382:63  error  Replace `""` with `''`                                                                                                                                                            prettier/prettier
  1386:9   error  Replace `"translate("·+·arguments[0]·+·"px,·"·+·arguments[1]·+·"px)"` with `'translate('·+·arguments[0]·+·'px,·'·+·arguments[1]·+·'px)'`                                          prettier/prettier
  1389:9   error  Replace `"translate3d("` with `'translate3d('`                                                                                                                                    prettier/prettier
  1391:9   error  Replace `"px,"` with `'px,'`                                                                                                                                                      prettier/prettier
  1393:9   error  Replace `"px,"` with `'px,'`                                                                                                                                                      prettier/prettier
  1395:9   error  Replace `"px)"` with `'px)'`                                                                                                                                                      prettier/prettier
  1397:52  error  Replace `"1000px"` with `'1000px'`                                                                                                                                                prettier/prettier
  1399:67  error  Replace `"px"` with `'px'`                                                                                                                                                        prettier/prettier
  1410:21  error  Replace `""` with `''`                                                                                                                                                            prettier/prettier
  1412:71  error  Replace `""` with `''`                                                                                                                                                            prettier/prettier
  1413:60  error  Replace `""` with `''`                                                                                                                                                            prettier/prettier
  1417:34  error  Replace `"rotate("·+·arguments[0]·+·"deg)"` with `'rotate('·+·arguments[0]·+·'deg)'`                                                                                              prettier/prettier
  1420:9   error  Replace `"rotate("·+·arguments[0]·+·"deg,·"·+·arguments[1]·+·"deg)"` with `'rotate('·+·arguments[0]·+·'deg,·'·+·arguments[1]·+·'deg)'`                                            prettier/prettier
  1422:34  error  Replace `"rotateX("·+·arguments[0]·+·"deg)"` with `'rotateX('·+·arguments[0]·+·'deg)'`                                                                                            prettier/prettier
  1423:35  error  Replace `"rotateY("·+·arguments[1]·+·"deg)"` with `'rotateY('·+·arguments[1]·+·'deg)'`                                                                                            prettier/prettier
  1424:35  error  Replace `"rotateZ("·+·arguments[2]·+·"deg)"` with `'rotateZ('·+·arguments[2]·+·'deg)'`                                                                                            prettier/prettier
  1482:9   error  Replace `"rgba("` with `'rgba('`                                                                                                                                                  prettier/prettier
  1484:9   error  Replace `","` with `','`                                                                                                                                                          prettier/prettier
  1486:9   error  Replace `","` with `','`                                                                                                                                                          prettier/prettier
  1488:9   error  Replace `","` with `','`                                                                                                                                                          prettier/prettier
  1490:9   error  Replace `")"` with `')'`                                                                                                                                                          prettier/prettier
  1493:24  error  Replace `"undefined"` with `'undefined'`                                                                                                                                          prettier/prettier
  1494:24  error  Replace `":"` with `':'`                                                                                                                                                          prettier/prettier
  1499:32  error  Replace `";"` with `';'`                                                                                                                                                          prettier/prettier
  1501:38  error  Replace `":"` with `':'`                                                                                                                                                          prettier/prettier
  1508:20  error  Replace `"rotate"·||·prop·===·"translate"·||·prop·===·"position"` with `'rotate'·||·prop·===·'translate'·||·prop·===·'position'`                                                  prettier/prettier
  1510:37  error  Replace `"_"` with `'_'`                                                                                                                                                          prettier/prettier
  1515:20  error  Replace `"width"` with `'width'`                                                                                                                                                  prettier/prettier
  1516:20  error  Replace `"height"` with `'height'`                                                                                                                                                prettier/prettier
  1517:20  error  Replace `"left"` with `'left'`                                                                                                                                                    prettier/prettier
  1518:20  error  Replace `"top"` with `'top'`                                                                                                                                                      prettier/prettier
  1520:44  error  Replace `""` with `''`                                                                                                                                                            prettier/prettier
  1550:37  error  Replace `"checkbox"` with `'checkbox'`                                                                                                                                            prettier/prettier
  1551:38  error  Replace `"radio"` with `'radio'`                                                                                                                                                  prettier/prettier
  1553:28  error  Replace `"undefined"` with `'undefined'`                                                                                                                                          prettier/prettier
  1560:33  error  Replace `"undefined"` with `'undefined'`                                                                                                                                          prettier/prettier
  1602:37  error  Replace `"checkbox"` with `'checkbox'`                                                                                                                                            prettier/prettier
  1603:38  error  Replace `"radio"` with `'radio'`                                                                                                                                                  prettier/prettier
  1649:29  error  Replace `"range"` with `'range'`                                                                                                                                                  prettier/prettier
  1669:30  error  Replace `"block"` with `'block'`                                                                                                                                                  prettier/prettier
  1685:30  error  Replace `"none"` with `'none'`                                                                                                                                                    prettier/prettier
  1721:39  error  Replace `"2d"` with `'2d'`                                                                                                                                                        prettier/prettier
  1726:33  error  Replace `"width"` with `'width'`                                                                                                                                                  prettier/prettier
  1727:33  error  Replace `"height"` with `'height'`                                                                                                                                                prettier/prettier
  1729:13  error  Replace `"style"` with `'style'`                                                                                                                                                  prettier/prettier
  1730:13  error  Replace `"width:"·+·aW·+·"px;·height:"·+·aH·+·"px"` with `'width:'·+·aW·+·'px;·height:'·+·aH·+·'px'`                                                                              prettier/prettier
  1737:33  error  Replace `"2d"` with `'2d'`                                                                                                                                                        prettier/prettier
  1740:39  error  Replace `"px"` with `'px'`                                                                                                                                                        prettier/prettier
  1741:40  error  Replace `"px"` with `'px'`                                                                                                                                                        prettier/prettier
  1754:38  error  Replace `"width"` with `'width'`                                                                                                                                                  prettier/prettier
  1755:38  error  Replace `"height"` with `'height'`                                                                                                                                                prettier/prettier
  1801:28  error  Replace `"anonymous"` with `'anonymous'`                                                                                                                                          prettier/prettier
  1847:33  error  Replace `"src"` with `'src'`                                                                                                                                                      prettier/prettier
  1850:62  error  Replace `""` with `''`                                                                                                                                                            prettier/prettier
  1859:45  error  Replace `"source"` with `'source'`                                                                                                                                                prettier/prettier
  2106:27  error  Replace `"loop"` with `'loop'`                                                                                                                                                    prettier/prettier
  2158:27  error  Replace `"loop"` with `'loop'`                                                                                                                                                    prettier/prettier
  2170:27  error  Replace `"autoplay"` with `'autoplay'`                                                                                                                                            prettier/prettier
  2207:24  error  Replace `"undefined"` with `'undefined'`                                                                                                                                          prettier/prettier
  2285:24  error  Replace `"undefined"` with `'undefined'`                                                                                                                                          prettier/prettier
  2340:24  error  Replace `"undefined"` with `'undefined'`                                                                                                                                          prettier/prettier
  2381:44  error  Replace `"canvas"` with `'canvas'`                                                                                                                                                prettier/prettier
  2382:52  error  Replace `"2d"` with `'2d'`                                                                                                                                                        prettier/prettier
  2416:29  error  Replace `"undefined"` with `'undefined'`                                                                                                                                          prettier/prettier
  2514:49  error  Replace `"function"` with `'function'`                                                                                                                                            prettier/prettier
  2522:15  error  Replace `"connect()·is·meant·to·be·used·with·Web·Audio·API·or·p5.sound.js"` with `'connect()·is·meant·to·be·used·with·Web·Audio·API·or·p5.sound.js'`                              prettier/prettier
  2558:13  error  Replace `"nothing·to·disconnect"` with `'nothing·to·disconnect'`                                                                                                                  prettier/prettier
  2591:20  error  Replace `"text-align"]·=·"inherit"` with `'text-align']·=·'inherit'`                                                                                                              prettier/prettier
  2820:36  error  Replace `"/"` with `'/'`                                                                                                                                                          prettier/prettier

✖ 178 problems (178 errors, 0 warnings)
  178 errors, 0 warnings potentially fixable with the `--fix` option.
</details>

**Comment by lmccart** [comment]
#2492

**Comment by eJohnstonePhd1991** [comment]
This section https://p5js.org/reference/#/p5/createVideo also lacks an example, which may also relate to #1844

**Comment by carolinehermans** [comment]
First time contributing to p5.js and open source in general! Thanks for making all the documentation so friendly :)

#2569

**Comment by faithwyu** [comment]
Hi! I will be working on the p5.Table.js and p5.TableRow.js references. Please let me know if you already started working on any of them so we can work together!

**Comment by AdilRabbani** [comment]
Hi! I added some new reference examples for loadPixels(). #2793

**Comment by AdilRabbani** [comment]
Hello, I would like to add examples to renderer methods (beginShape, vertex). But as they won't be appearing in the reference docs as suggested by @Spongman in #2793 , should I go for it?

**Comment by limzykenneth** [comment]
@AdilRabbani those functions will be called when the sketch is in WebGL mode, so maybe you can create WebGL versions of those examples. Get concensus with @Spongman or @kjhollen first maybe as they may still be working on those functionalities.

**Comment by kjhollen** [comment]
@AdilRabbani documentation for the renderer doesn't appear in the user facing documentation, so I don't think it's necessary to write examples there. However, the vertex method in general only has one example at the moment, and doesn't show any of the configurations for webGL. Maybe you can work on adding some there? in core/vertex.js.

**Comment by Spongman** [comment]
just be aware that WebGL-mode support for some of the beginShape modes is a little spotty right now. hopefully this should improve a little with #2670.

----
the current list of methods missing examples is:
```
src\events\acceleration.js:350: method p5.setMoveThreshold missing example
src\events\acceleration.js:363: method p5.setShakeThreshold missing example
src\io\files.js:1329: method p5.save missing example
src\webgl\material.js:14: method p5.loadShader missing example
src\webgl\material.js:123: method p5.shader missing example
src\webgl\p5.Geometry.js:54: method p5.Geometry.computeFaces missing example
src\webgl\p5.Geometry.js:96: method p5.Geometry.computeNormals missing example
src\webgl\p5.Geometry.js:135: method p5.Geometry.averageNormals missing example
src\webgl\p5.Geometry.js:156: method p5.Geometry.averagePoleNormals missing example
src\webgl\p5.Geometry.js:249: method p5.Geometry.normalize missing example
src\webgl\p5.Shader.js:270: method p5.Shader.setUniform missing example
```

**Comment by AdilRabbani** [comment]
Added examples for vertex method. #2798

**Comment by aatishb** [comment]
Hi, I'd like to add some simple visual interactive examples for the p5.Vector methods.

**Comment by Spongman** [comment]
@aatishb nice, could use a little `toFixed()` here & there.

**Comment by lmccart** [comment]
thanks for the help everyone! closing this one as https://github.com/processing/p5.js/issues/2865 seems to cover this with clearer explanations

**Comment by jatin33** [comment]
Is this issue still opened? Is anyone else working on it?

**Comment by lmccart** [comment]
Yes, here's a more up to date issue: https://github.com/processing/p5.js/issues/2865
You can get a partial list of missing examples by running `grunt`. Here's the current list:
```
src/dom/dom.js:2615: method p5.MediaElement.autoplay missing example
src/dom/dom.js:3032: method p5.MediaElement.connect missing example
src/dom/dom.js:3081: method p5.MediaElement.disconnect missing example
src/io/files.js:1395: method p5.save missing example
src/webgl/material.js:270: method p5.resetShader missing example
src/webgl/p5.Camera.js:298: method p5.createCamera missing example
src/webgl/p5.Camera.js:409: method p5.Camera.perspective missing example
src/webgl/p5.Camera.js:489: method p5.Camera.ortho missing example
src/webgl/p5.Camera.js:548: method p5.Camera.frustum missing example
src/webgl/p5.Camera.js:837: method p5.Camera.camera missing example
src/webgl/p5.Geometry.js:72: method p5.Geometry.computeFaces missing example
src/webgl/p5.Geometry.js:114: method p5.Geometry.computeNormals missing example
src/webgl/p5.Geometry.js:153: method p5.Geometry.averageNormals missing example
src/webgl/p5.Geometry.js:174: method p5.Geometry.averagePoleNormals missing example
src/webgl/p5.Geometry.js:267: method p5.Geometry.normalize missing example
```
