### ISSUE TITLE
Unit Testing instructions... chai not found

### ISSUE THREAD

**Issue by kfrajer** [processing/p5.js#1956]
Hi
I am following the instructions to get started with Unit Testing from https://p5js.org/tutorials/tdd.html

I am working on Windows 10. I have node  installed("node -v" returns v6.10.2) and, as instructed, I proceeded to do this next:

npm install npm@latest -g
npm install chai -g
npm install mocha -g

Then I moved to my unit_test directory to run my first test (I am just following the instructions there) and this is what I get:

> C:\Users\C\Desktop\moreDocuments\mySandBox\nodejs\unit_test>mocha
> module.js:471
>     throw err;
>     ^
> 
> Error: Cannot find module 'chai'
>     at Function.Module._resolveFilename (module.js:469:15)
>     at Function.Module._load (module.js:417:25)
>     at Module.require (module.js:497:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (C:\Users\C\Desktop\moreDocuments\mySandBox\nodejs\unit_test\test\test.js:3:29)
>     at Module._compile (module.js:570:32)
>     at Object.Module._extensions..js (module.js:579:10)
>     at Module.load (module.js:487:32)
>     at tryModuleLoad (module.js:446:12)
>     at Function.Module._load (module.js:438:3)
>     at Module.require (module.js:497:17)
>     at require (internal/module.js:20:19)
>     at C:\Users\C\AppData\Roaming\npm\node_modules\mocha\lib\mocha.js:230:27
>     at Array.forEach (native)
>     at Mocha.loadFiles (C:\Users\C\AppData\Roaming\npm\node_modules\mocha\lib\mocha.js:227:14)
>     at Mocha.run (C:\Users\C\AppData\Roaming\npm\node_modules\mocha\lib\mocha.js:495:10)
>     at Object.<anonymous> (C:\Users\C\AppData\Roaming\npm\node_modules\mocha\bin\_mocha:469:18)
>     at Module._compile (module.js:570:32)
>     at Object.Module._extensions..js (module.js:579:10)
>     at Module.load (module.js:487:32)
>     at tryModuleLoad (module.js:446:12)
>     at Function.Module._load (module.js:438:3)
>     at Module.runMain (module.js:604:10)
>     at run (bootstrap_node.js:393:7)
>     at startup (bootstrap_node.js:150:9)
>     at bootstrap_node.js:508:3
> 
> C:\Users\C\Desktop\moreDocuments\mySandBox\nodejs\unit_test>

Based on this stackoverflow post, it seems the problem is that I am setting a global environment: https://stackoverflow.com/questions/36838834/node-js-cannot-find-module-chai

So instead of -g, I should be using --save-dev  but then I run into another wall:

> C:\>npm install --save-dev npm@latest
> npm WARN saveError ENOENT: no such file or directory, open 'C:\package.json'
> C:\
> `-- npm@4.6.1
> 
> npm WARN enoent ENOENT: no such file or directory, open 'C:\package.json'
> npm WARN !invalid#1 No description
> npm WARN !invalid#1 No repository field.
> npm WARN !invalid#1 No README data
> npm WARN !invalid#1 No license field.
> 
> 

My question is, this section needs some revision. I believe I have seen how to create a package.json file from the twitter bot tutorial and that was created in the local directory of the bot. My question is, following this, do I need to create a package.json in every test directory? Would that mean I need to run the above commands in each directory, or is it just enough to define them in the package.json file?

kfrajer

**Comment by limzykenneth** [comment]
I have not tried using global `chai` in code, that might be some old API or something. You don't need to install `chai` in every test folder, just install it in the project root folder and run `mocha` from that folder, `mocha` should find `test.js` automatically and run it with the locally installed `chai`.

**Comment by lmccart** [comment]
@kfrajer the github issues here are a good place for bugs and issues with the p5.js library itself. for questions about writing your own code, tests, or following tutorials, the [forum](https://forum.processing.org/two/) is the best place to post. thanks!
