### ISSUE TITLE
Monospace font doesn't rendered correctly when loaded from file

### ISSUE THREAD

**Issue by cqx931** [processing/p5.js#1957]
The monospace font is copy pasted from my default font folder on mac, so the file itself should be correct. However, the text width for each character rendered from p5.js are not the same.
Please see the test sketch here: http://chenqianxun.com/testcases/monoSpaceFontTest/
I tried many different monospace font, otf,ttf, but none of them can get same character width when rendered from p5.js.

If I use the default monospace font in browser  `textFont("courier",100);`, the text width for each character is rendered correctly.

**Comment by dhowe** [comment]
I am not sure this is a bug. I don't think that we can assume any font is true monospace, just from the name. One way to check is to use the same font file in some other environment, then compare the displayed widths of the glyphs...
