### ISSUE TITLE
mouseClicked() not trigered by right Click in chrome and safari (work on firefox)

### ISSUE THREAD

**Issue by TitouanT** [processing/p5.js#1960]
I think this the minimum code to show the issue:
```js
function setup () {
	background(72);
}

function mouseClicked () {
	console.log(mouseButton, RIGHT, LEFT, CENTER);
}
```

**Comment by mikewesthad** [comment]
@TitouanT, hmm. This appears to be a browser inconsistency. Verified on machine: on chrome/edge only left click triggers mouseClicked, and on FF left/middle/right clicks all trigger mouseClicked. Here's a [codepen](https://codepen.io/mikewesthad/pen/gWypwJ) comparing p5 vs corresponding native JS code. p5 is just wrapping around the underlying javascript "click" event, so it will inherit the browser inconsistency.

The [W3C working draft](https://w3c.github.io/uievents/#event-type-click) suggests that "click" is only supposed to be triggered from the left mouse button. I think the best fix for p5 would be to clarify in the docs that `mouseClicked` is only guaranteed to be triggered by the left mouse button and suggest `mousePressed` or `mouseReleased` when other mouse buttons are needed.

**Comment by lmccart** [comment]
closed with https://github.com/processing/p5.js/pull/1965
