### ISSUE TITLE
DOM library .attribute("disabled", true); on radiobutton/checkbox don't work properly

### ISSUE THREAD

**Issue by BitterBaam** [processing/p5.js#1968]
Example:
```javascript
// if i have a radio element with some options
Radio = createRadio()
Radio.option("HV")
Radio.option("HØ")
Radio.option("HL")
Radio.option("EG")
Radio.option("UC")

//then try to disable them with this
Radio.attribute("disabled", true)
```
The attribute is added to the div element instead of the individual input elements.
![p5 js dom issue](https://cloud.githubusercontent.com/assets/4765651/26513405/9da91ec2-426b-11e7-88cc-2918fafc47ff.png)

i have noticed that the same thing is happending with checkboxes

Possible fixes:

* One thing you could do to fix this issue would be to behind the scenes when an attribute is added to a radio/checkbox element it adds it to the individual elements themselves instead of the div element.
* Second thing a can think of right now is to make a function in the library specifically to radio/checkbox elements that make it possible to when you want to add an attribute you can target individual options

for example:
```javascript
Radio.radio_attribute("HV", disabled, true)
```

I hope this makes sense to other people please write a comment if anything is confusing and I will elaborate :)
thanks for taking the time to read this.

now back to fixing my problem manually :p

**Comment by lmccart** [comment]
I think the first suggestion (add to individual elements rather than the div behind the scense) makes sense and seems simple and intuitive.

**Comment by BitterBaam** [comment]
It is so nice to see that you were so quick to fix the problem. The only thing is that you may have been too quick. I downloaded the updated code from lib/addons/p5.dom.js and triple checked that it had the changes and the problem is still there :/ It still puts the attribute on the div element instead of the actual radio/checkbox elements :/ If there is anything I can do to help I will happily help out :)

**Comment by mlarghydracept** [comment]
@BitterBaam oh you are right two line changes that I made didn't actually make it into that PR. I'll submit another right now. Sorry about that!

**Comment by lmccart** [comment]
whoops sorry @BitterBaam should've checked that closer before merge. thanks @mlarghydracept!
