### ISSUE TITLE
Add note about where to look when build fails

### ISSUE THREAD

**Issue by dhowe** [processing/p5.js#1971]
Perhaps a note in the output after a failed test to reload in the browser (localhost:9001/test/test.html or test-minified.html) with --keepalive ?

<br>

![image](https://cloud.githubusercontent.com/assets/737638/26519269/fa6fd864-42f0-11e7-95a6-290affad243a.png)

**Comment by dhowe** [comment]
FYI, these are the errors I see in 3fff3f6f45

![image](https://cloud.githubusercontent.com/assets/737638/26519282/31d55b44-42f1-11e7-97e2-56d956da91c9.png)

**Comment by limzykenneth** [comment]
@dhowe this is related to #1881. I first saw this a couple months back but couldn't decipher what it means, I may have hunt down the source of the error in the test code but couldn't make sense of it either. If you run the test again it probably will pass which makes the whole thing even more mystifying...

**Comment by dhowe** [comment]
yes, i also found that re-running results in passing tests -- perhaps we simply need to raise the timeout value (at least as a tmp fix) ?

**Comment by sakshamsaxena** [comment]
Interesting! So apparently, the failure is observed only in the case of non-existing URLs. As HttpDo uses Request, some preliminary search on the same resulted that there's no default timeout to any request, so they're likely to be left pending especially in our case where the URL does not exist. 

Found [this](https://github.com/request/request/issues/2358) slightly similar. So this could be completely random or some lower level unhandled sorcery in Request, I think.

**Comment by lmccart** [comment]
I think it is a case of the request to the URL timing out or just not connecting.. maybe we just need better error messaging? Or a longer timeout?

**Comment by sakshamsaxena** [comment]
Request [says](https://github.com/request/request/blob/master/README.md#requestoptions-callback) that it's configuration's timeout is always ignored in case of failed TCP connection which is handled by the OS only. It somehow tries to look for the URL maybe beyond a context or something, which delays it significantly to cause the test to timeout. All of this, is dependent on Request module only though. The best we can do is to add a timeout for getting __Response Headers__, which can really be 1000-1500 milliseconds at max.

**Comment by lmccart** [comment]
this has been addressed, unit test names are now printed
<img width="484" alt="screen shot 2017-12-14 at 7 21 30 pm" src="https://user-images.githubusercontent.com/191056/34022283-05507f5c-e104-11e7-9731-97b99d8e244e.png">
