### ISSUE TITLE
Function for converting polar coordinates to cartesian coordinates and the opposite

### ISSUE THREAD

**Issue by SaarLevy** [processing/p5.js#1973]
This an extremely useful utility that is needed in many projects.

I shall start working on it. Expect a pull request soon enough.

**Comment by StanLepunK** [comment]
I work on it for Processing, if that can help you 
https://github.com/StanLepunK/Math_rope/blob/master/Math_method/Z_Rope_Math.pde
start from line 91, but if I remender i'm lock on a few point, so if you improve it of find a perfect solution to switch from polar to cartesian and the reverse keep me in touch

**Comment by lmccart** [comment]
hi @SaarLevy this is an interesting suggestion. I think it's beyond the scope of the core p5 library right now, but could be a really great starting point for an [addon library](https://github.com/processing/p5.js/wiki/Libraries)
