### ISSUE TITLE
Cannot load in local CSV/Text/JSON files

### ISSUE THREAD

**Issue by Archadia** [processing/p5.js#1975]
Using Electron 1.6.10 and p5.js v0.5.10, when ever I try to use `loadTable("level/level1.csv", loadLevel)` an error occurs as follows: 
```
Fetch API cannot load file:///C:/Users/Ashigaru/Documents/Programming/JS/Game/level/level1.csv. URL scheme "file" is not supported.
p5.httpDo @ p5.js:23274

p5.js:23274 Uncaught (in promise) TypeError: Failed to fetch
    at Object.p5.httpDo (p5.js:23274)
    at p5.loadTable (p5.js:22847)
    at p5.<anonymous> (p5.js:11529)
    at preload (sketch.js:4)
    at p5.<anonymous> (p5.js:11491)
    at new p5 (p5.js:11776)
    at _globalInit (p5.js:8048)
```

There is nothing perticularly special about the csv file, so I am puzzled as to why this is occuring

**Comment by limzykenneth** [comment]
@Archadia You need to be running a server to use loading functions. Have a look at how to do that [here](https://github.com/processing/p5.js/wiki/Local-server)

**Comment by Archadia** [comment]
Thank you, all sorted.
