### ISSUE TITLE
LoadTable cvs keeps getting error Fetch API cannot load.

### ISSUE THREAD

**Issue by harrysayers** [processing/p5.js#1980]
I've tried several variations of the code below and none of them fixes the issue of getting the error: Fetch API cannot load and Uncaught (in promise) TypeError: failed to fetch. Am I doing something wrong or is this an issue with P5? (code below) .

```javascript
var table;

function preload() {
  table = loadTable("data/test.csv", "csv", "header");

}

function setup() {

  print(table.getRowCount() + " total rows in table");
  print(table.getColumnCount() + " total columns in table");
  print(table.getColumn("name"));
  for (var r = 0; r < table.getRowCount(); r++)
    for (var c = 0; c < table.getColumnCount(); c++) {
      print(table.getString(r, c));
    }
}
```

**Comment by lmccart** [comment]
is test.csv inside a folder called data in your project folder?

**Comment by harrysayers** [comment]
Yeah, test.csv is inside a folder called "data".

**Comment by limzykenneth** [comment]
@harrysayers Are you running a local server?

**Comment by harrysayers** [comment]
I was running a Python server but I switched to Mamp and now I don't get the errors.

Thanks, I'll close this now.
