### ISSUE TITLE
Re-assigning value twice... 

### ISSUE THREAD

**Issue by kfrajer** [processing/p5.js#1981]
https://github.com/processing/p5.js/blob/master/lib/addons/p5.dom.js#L459

Is this common to do?

>     elt.value = value;
>     if (value) elt.value = value;

or should it just be the second line? Should I make a pull request?

kfrajer

**Comment by lmccart** [comment]
that'd be great, thanks!

**Comment by lmccart** [comment]
fixed with https://github.com/processing/p5.js/pull/1982
