### ISSUE TITLE
color() not working in on-demand global mode outside setup()/draw()

### ISSUE THREAD

**Issue by jessebrennan** [processing/p5.js#1983]
I was using on-demand global mode as described [here](https://github.com/processing/p5.js/wiki/p5.js-overview#instantiation--namespace) in the documentation as a workaround to allow using p5 functions outside setup and draw.

This works fine for random as in the documentation, but using color throws an error. Here is a sample
```
new p5();

var w = random(100);
var c = color(100);

function setup() {
   createCanvas(100, 100);
   fill(c);
   rect(25, 25, w, 25);
} 
```
The error message:
```
Uncaught TypeError: Cannot read property '_colorMode' of undefined
    at new p5.Color (p5.js:6482)
    at p5.color (p5.js:6174)
    at sketch.js:4
```

**Comment by JimishF** [comment]
Making a color requires to pull information from an instance of **p5.Renderer**, which is going to be undefined since canvas is not created yet.

**Comment by JimishF** [comment]
Making a color requires to pull information like color Mode and color maxes from an instance of **p5.Renderer**, which is going to be declared while creating a canvas & it will going to be undefined in this case because canvas is not created yet.

And personally i can't think of any usecase where i need to declare a p5-instance of color outside of setup function.

**Comment by jessebrennan** [comment]
I was using it to store a color variable used in both setup and draw. The
workaround is easy though, just initialize the color in set up.

Another use case: imagine making a class with a display function, such as a
Person. You may want to initialize the person object with a color, but as I
understand it this wouldn't be possible currently with a constructor
defined outside of setup.

It's not a show stopping bug by any means and it is relatively easy to work
around, but it didn't seem like the expected behavior given what I had read
in the documentation.


On Jun 5, 2017 6:20 AM, "Jimish Fotariya" <notifications@github.com> wrote:

Making a color requires to pull information like color Mode and color maxes
from an instance of *p5.Renderer*, which is going to be declared while
creating a canvas & it will going to be undefined in this case because
canvas is not created yet.

And personally i can't think of any usecase where i need to declare a
p5-instance of color outside of setup function.

—
You are receiving this because you authored the thread.

Reply to this email directly, view it on GitHub
<https://github.com/processing/p5.js/issues/1983#issuecomment-306185420>,
or mute the thread

**Comment by limzykenneth** [comment]
@jessebrennan I didn't test out anything but looking at your use case you can just do
```
var c;

function setup() {
  c = color(100)
  createCanvas(100, 100);
  fill(c);
  rect(25, 25, w, 25);
} 
```
which let's you have `c` in the global scope accessible by other functions such as `draw` or `mouseclicked` etc. As far as I can remember, you can use the `color` function in externally defined constructor as well as long as the constructor is called after setup is called and a canvas is created, by then the `color` function is in the global scope and the custom constructor outside of `setup` will have it defined correctly as well.

**Comment by jessebrennan** [comment]
Cool. Then should this be closed?

**Comment by limzykenneth** [comment]
If there's no further problem yeah, you can close this. Thanks
