### ISSUE TITLE
I can't load p5.dom.js properly!!

### ISSUE THREAD

**Issue by stavzog** [processing/p5.js#1984]
when I try to load p5.dom.js it says:
## 

> **Uncaught TypeError: Cannot read property 'prototype' of undefined
    at p5.dom.js:71
    at p5.dom.js:34
    at p5.dom.js:35
(anonymous) @ p5.dom.js:71
(anonymous) @ p5.dom.js:34
(anonymous) @ p5.dom.js:35
sketch.js:67 Uncaught TypeError: boost.hide is not a function
    at draw (sketch.js:67)
    at e.d.redraw (p5.min.js:6)
    at e.<anonymous> (p5.min.js:4)
    at e.<anonymous> (p5.min.js:4)
    at new e (p5.min.js:5)
    at e (p5.min.js:4)
draw @ sketch.js:67
d.redraw @ p5.min.js:6
(anonymous) @ p5.min.js:4
(anonymous) @ p5.min.js:4
e @ p5.min.js:5
e @ p5.min.js:4**

**Comment by limzykenneth** [comment]
@stavzog there probably a problem with a variable called `boost` in your code. Please post this question in the [forum](https://forum.processing.org/two/categories/p5-js) instead as github issues are more for feature requests and bug tracking. Thanks

**Comment by DerEddie** [comment]
same here! feels like p5 is just a buggy useless library which just wastes ur time....

**Comment by vamshi9666** [comment]
i am acing this problem too . any update ?

**Comment by lmccart** [comment]
hi @vamshi9666 please post in the forum for more help:
https://forum.processing.org/two/

**Comment by marcrleonard** [comment]
For what it's worth, it seemed to go away when I switched the script tag order. First, p5. Then, p5.dom

**Comment by alator21** [comment]
@marcrleonard  That worked for me too.Thank you.
