### ISSUE TITLE
Saving canvas to img with all p5 elements

### ISSUE THREAD

**Issue by archasek** [processing/p5.js#1987]
Is it possible to save canvas with all custom elements like divs, p, a, etc. created and positioned on the canvas?
The simple `text()` function was quite buggy for me, I decided to use `createElement` to simulate text on a canvas with possibility to edit it and change its position.

**Comment by limzykenneth** [comment]
I'm not quite sure what you are looking for but perhaps the p5.dom library would do what you need to do? Anyway, questions like this are better suited for the [forum](https://forum.processing.org/two/categories/p5-js), github issues are more for feature requests and reporting bugs.

**Comment by archasek** [comment]
OK, I'll write the issue there. Thanks

**Comment by limzykenneth** [comment]
Please close this issue as well, it helps us keep track of things. Thanks!
