### ISSUE TITLE
A better example for dealing with pixels array on different pixelDensity would be great!

### ISSUE THREAD

**Issue by SetupandDraw** [processing/p5.js#1988]
Hi there,
I think the reference at p5js.org is lacking of sufficient info/examples for dealing with pixels array on different pixelDenisty displays. In fact I find the following example on the [p5.Image](https://p5js.org/reference/#/p5.Image) reference page quite obscure.

`var d = pixelDensity;
for (var i = 0; i < d; i++) {
  for (var j = 0; j < d; j++) {
    // loop over
    idx = 4 * ((y * d + j) * width * d + (x * d + i));
    pixels[idx] = r;
    pixels[idx+1] = g;
    pixels[idx+2] = b;
    pixels[idx+3] = a;
  }
}`

I would like to have a reference page at p5js.org that show an example on how I can deal with each pixel, like I normally do on "standard density displays" like this:

`function setup(){
  createCanvas(600, 600);
  pixelDensity(1);
  background(0);
  loadPixels();
  for (var y = 0; y < height; y++) {
    for (var x = 0; x < width; x++) {
      // loop over
      var index = (x + (y * width)) * 4;
      pixels[index+0] = random(255);
      pixels[index+1] = random(255);
      pixels[index+2] = random(255);
      pixels[index+3] = 255;
    }
  }
  updatePixels();
}`

I think this would help many not super expert programmers better understanding the topic.

Thanks!

**Comment by lmccart** [comment]
@mlarghydracept
