### ISSUE TITLE
.obj model not loading on mobile devices

### ISSUE THREAD

**Issue by juliansharifi** [processing/p5.js#1991]
Playing around with WebGL 3d model loading and for some reason, .obj models don't seem to load on mobile devices (though the one in my example loads successfully on safari using the iOS simulator).  

Example here: https://juliansharifi.github.io/june3rd2017/ 

Source here: https://github.com/juliansharifi/june3rd2017

**Comment by lmccart** [comment]
are there any errors in console?
you can use https://jsconsole.com/ to log console output from your phone to a browser window

**Comment by juliansharifi** [comment]
That's a great tool!

No errors though - just repeated reloads i.e. 

"remote console.loglink
"p5.RendererGL: enabled webgl context"
remote console.loglink
"p5.RendererGL: enabled webgl context""

**Comment by lmccart** [comment]
this example runs ok on mobile: https://p5js.org/reference/#/p5/loadModel
the problem could be that you need to load your model in preload() instead of setup(). it could be crashing because you are trying to draw it before it's fully loaded.

**Comment by juliansharifi** [comment]
@lmccart thanks! Still having issues even with pre-load - might be an object with the .obj file. Gonna try a few other things and see if i can get it working.
