### ISSUE TITLE
mouseIsPressed is not a fallback on touch devices

### ISSUE THREAD

**Issue by msawired** [processing/p5.js#1992]
The fact that touchStarted(), touchMoved(), touchEnded() have all fallbacks to mouse functions if they are not defined is great: it makes most sketches work smoothly on both screen and touch devices without making additional definitions. However, I noticed mouseIsPressed stays false on touch devices. MouseIsPressed is used as a common alternative to mousePressed(), I believe it would be expected behavior to have it also work on touch devices. 
I believe the fallback could be established if mouseIsPressed is set to true on touch start event, and set to false on touch end event. If you can guide me to where to make the edit in the code, I can edit and test.

**Comment by lmccart** [comment]
makes sense, that'd be great.
it should probably go in here: https://github.com/processing/p5.js/blob/master/src/events/touch.js#L60
similar to this file:
https://github.com/processing/p5.js/blob/master/src/events/touch.js#L571

**Comment by msawired** [comment]
Actually, on line 99 and 223, mouseIsPressed seems to be updated.
https://github.com/processing/p5.js/blob/master/src/events/touch.js#L99
https://github.com/processing/p5.js/blob/master/src/events/touch.js#L223

Sorry about that, I was looking at a previous release (and using a previous version). Thank you for the update!
