### ISSUE TITLE
How to add p5.dom to p5.js in instance mode

### ISSUE THREAD

**Issue by fcin** [processing/p5.js#1996]
I'm using requirejs to bundle my files. I've used `p5.js` for some time, but I need to add `p5.dom` now. The problem is I don't know how to do it with my requirejs. I couldn't find any information how to do it with bundling.
I tried many combinations, but `p5.dom` is always `undefined`
This is what I have so far:
```
require(['lib/p5js/lib/p5', 'lib/p5js/lib/addons/lib/p5.dom'], function (p5) {
    var myp5 = new p5(function (_sketch) {
        _sketch.setup = function() {
           _sketch.createButton('click me'); // _sketch doesn't have createButton function
       }
    });
});
```

**Comment by aswathkk** [comment]
Same Issue here.
How to use `p5.dom.js` in `p5.js` instance mode?
If I include `p5.dom`,
Methods specified in `p5.dom` is present at `p5.prototype`.
I'm not able to use those methods directly like `p5.createP()`, But I can call it like `p5.prototype.createP()`
By the way, I'm using babel with webpack.

**Comment by jay-manday** [comment]
Hi! What exactly are you trying to do? when working with p5.dom your working with not only your sketch but the whole stack of client side code (index.html, sketch.js, css, etc). My suggestion would be to just use something like this in the header of your html page. 

`<script type='text/javascript' src='relative/path/to/your/p5.dom.js'>`

This is a good link to check out for a overview of working w/ the dom + p5. also Daniel Shiffman has some great videos explaining it as well. 
(https://github.com/processing/p5.js/wiki/Beyond-the-canvas)
