### ISSUE TITLE
heading() doesn't follow angleMode()

### ISSUE THREAD

**Issue by JWStone** [processing/p5.js#1998]
As per examples this gives results between -PI and PI.  Seems like with angleMode(DEGREES); it should be giving 0 to 360

**Comment by sixhat** [comment]
@JWStone hm? Shouldn't it be doing ]-180..180]? Seems the most natural to me.

**Comment by JWStone** [comment]
Sorry, yes

**Comment by sixhat** [comment]
@JWStone I've just tested with 0.5.11 and seems to be working (and respecting) angleMode.

**Comment by JWStone** [comment]
Ok thanks I'll get a new version. Not sure how old mine is.
