### ISSUE TITLE
[P5 Feature Request]: clip (using the html canvas clip property after specifying a path)

### ISSUE THREAD

**Issue by criticalhits** [processing/p5.js#2003]
[The HTML Canvas API](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Compositing) has a page on "Compositing and clipping".

The clip property allows us to hide unwanted parts of shapes. See screenshot from the Canvas API:
![image](https://user-images.githubusercontent.com/28786457/27139096-b13d91ae-50e7-11e7-9c4b-ba971427f042.png)

It would be nice to have a clip function in the P5 API that can be used, as per the example from the above link, the usage seems as simple as stroke and fill. What do you think?

**Comment by lmccart** [comment]
I think this is currently beyond the scope of p5.js as we're still trying to get it to a point where the existing functionality is performant and bug-free, and I'm not hearing others on this thread. however, you can use native canvas methods, and can access the drawing context by using the variable `drawingContext`, so you can mix it together with p5.js in this way.
