### ISSUE TITLE
update documentation for loadXX() methods to note that callbacks should not be combined with preload

### ISSUE THREAD

**Issue by therealgambo** [processing/p5.js#2005]
Trying to load a sound file in chrome, the file loads successfully but the loading element never gets removed and the canvas is never drawn.

```
var song;

function preload(){
   console.log('Executing preload();');
   song = loadSound('test.mp3', soundready, sounderror, soundloading);
}

function soundready() {
  console.log('Sound file ready.');

  // hack for chrome to play songs
  this._decrementPreload();
}

function sounderror() {
  console.log('Error loading sound file.');
}

function soundloading() {
  console.log('Loading sound file...');
}
```

I managed to remove it by calling `this._decrementPreload();` from within the onload callback method. This removes the loading element and executes the expected methods to initiate the canvas.

I'm not sure what is the cause of this perhaps the preload handling method isn't recognising a successful load?, nor do I have the time to investigate further but this is the hacky fix that works for me right now.

__p5.js version:__ v0.5.11
__p5.dom.js version:__ v0.3.3
__p5.sound.js version:__ v0.3.3

**Comment by bomoko** [comment]
Hi @therealgambo 

I'm just starting to get my head around the p5.js source, but I'm sure you're experiencing this because you're calling loadSound with callbacks _inside_ "preload".

"load" functions called inside of _preload_ are wrapped in another function that fills in the successCallback argument automatically (with _decrementPreload(), actually).

I believe the right way of dealing with this is simply calling loadSound like this:
`song = loadSound('test.mp3');`

**Comment by bomoko** [comment]
I have to wonder if wouldn't make sense for this to be addressed a little more clearly in the documentation (if it isn't somewhere already?)
It's not clear to me from reading the reference docs that what @therealgambo has done above makes perfect sense. Without making it clearer, we can get some very weird behaviour.

Here's an example with the code above, just with a little tweak:

```
var song;

function preload(){
  console.log('Executing preload();');
  song = loadSound('test.mp3', soundready, sounderror);
}

function setup() {
  background(200);
  song.setVolume(0.1);
  song.play();
}
function soundready() {
  console.log('Sound file ready.');
  // hack for chrome to play songs
  this._decrementPreload();
}

function sounderror() {
  console.log('Error loading sound file.');
}
```
Now, given the way that __wrapPreload_ works, it's going to automatically add __decrementPreload_ as the _fourth_ argument to loadSound which is the "whileLoading" callback. "whileLoading" is called several times during the loading of a sound file. If __decrementPreload_ is called as "whileLoading" before the file is loaded,  the rest of the script will run and the call to song.setVolume (above) will fail (and it does).

**Comment by lmccart** [comment]
Yes, I agree, it would be a good idea to make it clearer in the docs that callbacks should not be included with calls to loadSound() or any other load method in preload.

**Comment by therealgambo** [comment]
I should mention that the only reason why the callbacks were added was purely for increased verbosity whilst debugging why 'Loading...' was not being removed.

Originally I had `song = loadSound('test.mp3');` in the preload() method which was not throwing any noticeable errors in the console.

I think this issue is now trying to cover two problems.
1. Better documentation around where the callback functions can be used.
2. The original problem as mentioned in the first post,

**Comment by limzykenneth** [comment]
Not sure about implementation of callbacks in `loadSound`/`loadImage` but I think `loadJSON` and the others that uses `httpDo` are able to take callbacks even in `preload`. They have extra checks to make sure the `_decrementPreload` callback doesn't conflict with user provided callbacks. I'll have a look at the implementation of `loadImage` as part of #2007 while I'm at it to confirm.

**Comment by bomoko** [comment]
@limzykenneth thanks for that, absolutely right!
They call _getDecrementPreload() (loadImage() does too). Or, at least, they should.

Just digging into it a little, I see that this was addressed in p5.js ([way back in 2015](https://github.com/processing/p5.js/pull/956)), but is still an issue in p5.sound.js.

I'm going to take a swing at [this](https://github.com/processing/p5.js-sound/issues/97) and see if I can sort it out.

**Comment by Jared-Sprague** [comment]
@bomoko @limzykenneth I remember adding the ability to use callbacks in preload to fix #949,  I remember it was to make spritesheet loading work in p5.play.  

I also added a unit tests and examples as part of the pull request:
https://github.com/processing/p5.js/pull/956/commits/378efbdd20677a5f5ae856351d0073fefe64b397

We intentionally added the ability to use callbacks in load* functions in preload() just a warning if we remove that I'm pretty sure it will break p5.play.

Let me know if I can help!

**Comment by limzykenneth** [comment]
@Jared-Sprague I don't think that ability should be removed as well and there probably is no need for that. If you like to help, you can test out the PR at #2008 and let me know if there's any problem with it. Thanks!

**Comment by Jared-Sprague** [comment]
@limzykenneth Sure! Checkout my comment on #2008
