### ISSUE TITLE
tic-tac-toe game and buttons inside the canvas

### ISSUE THREAD

**Issue by Alex92rus** [processing/p5.js#2006]
Hey p5.js community,

Alex here! In the last couple of weeks, I was looking at p5.js and to put it into practice, decided to make a simple [tic-tac-toe game](https://alex92rus.github.io/p5_tic_tac_toe/index.html). So far so good. At some point, I thought that it might be good to make graphical buttons in the canvas (rectangles, triangles etc) like in many other games for example - [here](http://cache.hackedfreegames.com/uploads/games/pictures/918/pMJ7M3BLCDGNE.jpg )*, to improve the functionality and the user experience with reset option,  board variation, help logs and others.  Is there an easy way to do these types of buttons?* Currently, I check if the mouse has been clicked inside the button area and then trigger a routine. All this is part of the mousePressed function. For now, there is just one button - the 'start' button, as the number of buttons, grow the code will get larger and larger. Instead, I propose to have a lookup table of button objects that is inspected on mouseClicked or/and mousPressed that checks whether the user clicked on a button or not. This feature will allow a lot of functionality like active/inactive buttons, faster button search as well as convenience for applications with menus and game development.

PS*. I do know that there is a create button function in p5.js DOM, but it responds to a button in the DOM that is outside the canvas and the feel is different, better to have the button option within the active element.

PS*. The tic-tac-toe game is already on GitHub - [here](https://alex92rus.github.io/p5_tic_tac_toe/index.html). For now, it is just the most basic version.  I would love to sort the buttons issue before moving on. Any feedback highly appreciated.

PS. mouseClicked() may be more convenient than mousePressed().

Thank you for your time.

Kind Regards,
Aleksandar Rusinov

**Comment by lmccart** [comment]
Hi Alex, I would suggest making a JavaScript object that encapsulates the concept of a clickable button. You could have methods on this object like button.detect() and button.isPressed(). If you stored them in an array, you could easily iterate through all of them and call detect on each one to see if any were pressed.

These videos about JS objects may be helpful:
https://www.youtube.com/watch?v=-e5h4IGKZRY
https://www.youtube.com/watch?v=F3GeM_KrGjI

And this series on objects and arrays (6.1-6.4):
https://www.youtube.com/watch?v=VIQoUghHSxU

**Comment by Alex92rus** [comment]
Hello Lauren,

Thank you for your advice. It sounds great. Maybe at some point, we could implement that inside p5.js . I expect a lot of people require it. Will implement it in my game.
