### ISSUE TITLE
decrementPreload set to failureCallback, even though loadImages() called from setup() or later

### ISSUE THREAD

**Issue by mjvDEV** [processing/p5.js#2007]
A little bit of context: I'm using the preload function to load two batches of strings: one is an array of filenames for the images I'm going to be loading, the other is an array of timestamps corresponding to the images. I do not use callback functions with loadStrings() inside preload(). I mention this just so you know that I do have a preload() function, in case that helps.

I'm writing a program that can frequently load and display then dump images based on user interactions. To do this I use loadImage() wrapped inside some control functions that figure out which images to load and when. I noticed that my failureCallback is consistently called after every image is loaded, even though the image displays correctly.

I did a little digging in the debugger, and found that even though I'm calling loadImages() inside setup(), (then later from mousePressed(), keyPressed, etc), the logic inside the function behaves as though I'd called it from preload(). So it treats the last argument, my failureCallback, as though it were decrementPreload, even though decrementPreload has not been pushed into the argument list (I believe that's what happens when you call a load function from preload?). Therefore my failureCallback is called despite no error occurring.

This could be a bit of a problem, because looking at the logic inside loadImage(), I don't think my failureCallback would ever be called if there actually was an error. Worse, if I hadn't included a failureCallback, I suspect that it would call my successCallback regardless of whether the load succeeded.

For now, I'm suppressing the behaviour inside my failureCallback by telling it not to do anything if it doesn't receive an error event argument, but this means I literally just have the failureCallback there as a blank placeholder.

Has anyone else encountered something like this?

**Comment by limzykenneth** [comment]
I think I know what is happening here, I'll have a look and fix it if I can. However, if you can provide a minimal example demonstrating the problem it would help greatly.

**Comment by mjvDEV** [comment]
Hi, sorry for the delay I was away from my desk over the weekend.

This code replicates the error. The file given to loadStrings() contains an array of image file names, which as you can see I use in loadImages():

<pre>
var files;

function preload() {
    files = loadStrings( "./data/summer-day-frames.txt" );
}

function setup() {
    canvas = createCanvas( 640, 360 );
    loadImage( "./img/plot_1207/half/" + files[0], loadSuccess, loadFail );
}

function loadSuccess( img ) {
    console.log( "p5 reports that the load succeeded: " + img );
    if (img) {
        image( img, 0, 0, 640, 360 );
    }
}

function loadFail( e ) {
    console.log( "p5 reports that the load failed: " + e );
}

</pre>

Replace the files and paths with valid ones on your end and you should see the image display correctly, plus the following in the console:

<pre>
p5 reports that the load succeeded: [object Object]
p5 reports that the load failed: undefined
</pre>

**Comment by lmccart** [comment]
fixed with https://github.com/processing/p5.js/pull/2008
