### ISSUE TITLE
Getting started - ellipse returns white screen 

### ISSUE THREAD

**Issue by rajsodhi** [processing/p5.js#2013]
#### Nature of issue?

- [ X] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [X ] Core
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [ X] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: p5.js v0.5.11 June 01, 2017
- Web browser and it's version:58.0.3029.110 (64-bit)
- Operating System: windows 10
- Steps to reproduce this:
downloaded p5.zip from main site
Tried introductory 'draw ellipse' example.

found a blank (white) screen from index.html.

tried to troubleshoot using Chrome dev tools.
![image](https://user-images.githubusercontent.com/5482289/27407234-6882e202-568c-11e7-92c4-6ba432df22a3.png)

function setup() {

}

function draw() {
  background(204);
  ellipse(50, 50, 80, 80);
}

**Comment by bomoko** [comment]
Hi @rajsodhi 

I'm trying to reproduce here - when you say you tried the 'draw ellipse' example, how did you try it?
I've just done the following

1. downloaded p5.zip
2. opened the directory I downloaded it into
3. went to the "empty-example" directory
4. copied the code you've pasted above into the "sketch.js" file
5. opened the index.html file in the "empty-example" directly in chrome.
6. saw the ellipse output without an issue.

Is this what you did?
Thanks!

**Comment by lmccart** [comment]
@rajsodhi from the error messages it sounds like you need to run a local server in order for the p5.js library paths to work. there are instructions here: https://github.com/processing/p5.js/wiki/Local-server
