### ISSUE TITLE
can createGraphics() be enhanced to adjust for pixel density?

### ISSUE THREAD

**Issue by mjvDEV** [processing/p5.js#2019]
#### Nature of issue?

- [ ] Found a bug
- [x] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Rendering

#### Which platform were you using when you encountered this?

- [x] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Feature enhancement details:

I noticed that the p5 canvas automatically resizes itself correctly for varying pixel densities, but the graphics created with createGraphics() do not, so any combination of canvas a graphical elements becomes completely screwed up on any pixel density other than 1. Currently I'm trying to fix this manually by resizing everything I draw in a graphics object according to the current pixel density, but if it is possible to get graphics elements to do this automatically that would be awesome! (Or have an option to do this that can be turned on, if one doesn't exist already - apologies if it does!).

**Comment by rockfarmor** [comment]
I also have this problem! I've also noticed that when rendering more complex shapes to the object, that the quality is really bad. Etc. text

**Comment by mjvDEV** [comment]
If anyone is working on this, the workaround solution I've been using is to do the following:

```
// Assuming 'w' and 'h' are previously declared width and height.
let d = window.pixelDensity();
let gfx = createGraphics(w * d, h * d);
```

Strangely enough that seems to be all that is necessary, at least so far in terms of simply rendering and displaying content. I haven't had any problems since I did this. Resizing is still a bit odd with p5.Graphics, but that's a separate issue, with an easy enough workaround.

**Comment by lmccart** [comment]
closing this one as duplicate, will follow up here https://github.com/processing/p5.js/issues/2077
