### ISSUE TITLE
Immediate mode performance

### ISSUE THREAD

**Issue by kjhollen** [processing/p5.js#2020]
I did some profiling of the GL immediate mode today (for calls to `beginShape`, `vertex`, etc. in WEBGL mode) and found that `p5.RendererGL.prototype._getCurShaderId` seems to be one of the slow steps.

`p5.RendererGL.prototype._getCurShaderId` always creates a new shader and does not check to see if one already exists for the constructed material ID constructed from the immediate mode vertex + fragment shader defaults.

In some early tests, I can see a huge improvement for immediate mode rendering speeds by replacing calls to `_initShaders` in `_getCurShaderId` with `_getShader` (note that `_getShader` will call `_initShaders` only if it can't find a cached one). 

Test program for reference, below. As it is now, just drawing 10 triangles drops the sketch framerate significantly. 

```
function setup(){
  createCanvas(710, 400, WEBGL);
}

function draw(){
  background(250);

  randomSeed(1);

  for (var i = 0  ;  i < 1000 ;  i++) {
    push();
    translate(random(-width/2, width/2), random(-height/2, height/2));
    rotateZ(random(0, 2 * PI) + frameCount * 0.1);
    fill(random(128, 255), 0, random(128, 255));
    beginShape(TRIANGLES);
    vertex(0, 25, 0);
    vertex(-25, -25, 0);
    vertex(25, -25, 0);
    endShape();
    pop();
  }

  console.log(frameRate());
}
```
Using the cache, it looks like I can get the performance to be faster than the 2D renderer, at least in this case. So far I've only tested on Chrome for macOS. I'll submit a pull request later after I do some testing. More soon!

**Comment by lmccart** [comment]
fixed with #2031
