### ISSUE TITLE
[GSoC] [Discussion] Some individual tests rely on other general parts of p5, which result in failure of such test cases while modularising components of p5

### ISSUE THREAD

**Issue by sakshamsaxena** [processing/p5.js#2023]
#### Nature of issue?

- [X] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [X] Core
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL

#### Details about the bug: 

- p5.js version: 0.5.11
- Operating System: Ubuntu 14.04
- Steps to reproduce this:

After bundling the "core" files, the tests for those fail at certain points where those features/functions/variables of p5 are used which are out of core. As of now, identified and corrected two such instances in `error_helpers`: [random](https://github.com/processing/p5.js/blob/master/test/unit/core/error_helpers.js#L23) is a `math` function and [mouseX](https://github.com/processing/p5.js/blob/master/test/unit/core/error_helpers.js#L30) is an `event` variable, neither of which are bundled with core. Replaced former with `smooth` and latter with `focused` and the tests are passing for those now.

Will be pointing out more such cases with possible alternatives. Looking forward to some feedback in this!

**Comment by sakshamsaxena** [comment]
Bundling core with events (fairly reasonable) helps a lot (even though a single mouse event was failing around 10-15 tests earlier). Still seeing some dependency on Color ..

**Comment by lmccart** [comment]
can we just run the tests on the full build of the library? and not run the tests on individual modules?

**Comment by lmccart** [comment]
ah ok, I misunderstood this issue. after discussing with @sakshamsaxena we have realized that these failing tests can be very useful in helping us restructure parts of the code to be more modular and organized. we can open issues for the various tests that fail and address each problematic area individually.
