### ISSUE TITLE
pan() does not pan 100%

### ISSUE THREAD

**Issue by nbrosowsky** [processing/p5.js#2024]
#### Nature of issue?

- [x ] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [ x] Desktop/Laptop
- [ ] Others (specify if possible)

There seems to be an issue with the pan method in p5.sound. Panning left or right using -1 to 1 does not pan 100% to the left or right speaker. Despite being fully panned you can still hear the sound in the other speaker. 

This is the case even in your demo (https://p5js.org/reference/#/p5.SoundFile/pan). I tested this on my macbook using the latest Chrome and Firefox, also tried it on Windows 10, Chrome.

Is there a way to get sounds 100% in one, and 0% in the other?

**Comment by lmccart** [comment]
This issue was moved to processing/p5.js-sound#190
