### ISSUE TITLE
Accessing elements via event listeners attached to functions

### ISSUE THREAD

**Issue by radialBlur050116** [processing/p5.js#2025]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [x ] Core
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x ] Desktop/Laptop
- [ ] Others (specify if possible)

#### Feature enhancement details:

There might already be a way to do this, but I have a single method attached to several elements via event listeners and it would be awesome if there were a way to determine which element the method was accessed from.  I know there are easy ways to do it in native js, but after searching through the core sub-area, the farthest I got was finding where the element was bound to the function:
```
function attachListener(ev, fxn, ctx) {
  var f = fxn.bind(ctx);
  ctx.elt.addEventListener(ev, f, false);
  ctx._events[ev] = f;
}
```
Since the element is bound to the function and not the other way around, it seems like there should be a way to access a single method's bound elements?

**Comment by limzykenneth** [comment]
I may have misunderstood you but when a method is called with the context bound, it means you can access the caller context in said method through the `this` keyword, which should give you what you are looking for.

**Comment by lmccart** [comment]
you can also get acces to the event itself like this:

```javascript
function mousePressed(e) {
  console.log(e);
}
```
