### ISSUE TITLE
Access pen pressure or buttons

### ISSUE THREAD

**Issue by schuesslerf** [processing/p5.js#2026]
Hello,

is it possible to access the pen pressure or clicked buttons from example from a surface pen? So you can define the thickness of the drawing over the pen pressure, or something like clicking the button on a surface pen is the eraser or something like that? The problem is not, how to set the thickness then, but is it possible to access the pressure? Normally, its the PointerEvent and theree you can access pressure and buttons as well, but how can I access this PointerEvent with p5.js?

Thank you

**Comment by lmccart** [comment]
this is not currently supported. I might suggest incorporating a library such as https://pressurejs.com/ which provides a nice wrapper for this... or you can add event listeners directly like this:

```javascript
var cnv = createCanvas(300, 300);
cnv.elt.addEventListener('pointerdown', function(e) {
  // do stuff
});
```
