### ISSUE TITLE
Double Click Events

### ISSUE THREAD

**Issue by limzykenneth** [processing/p5.js#2038]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [x] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [x] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### New feature details:
For one of my projects I'm working on, I need to listen for double click event and there isn't an implementation in p5.js yet, however I found out that all major browsers support the `dblclick` [event](https://developer.mozilla.org/en-US/docs/Web/Events/dblclick). It would be nice to have this implemented as well into p5.js and p5.dom.js

Eventually it would be nice to have feature parity with native browsers events I think.

**Comment by lmccart** [comment]
I agree with this specific proposal and the general strategy to provide parity with native browser events. I will take a look at this in two weeks when I return from travels if no one else gets there first. :)

**Comment by jay-manday** [comment]
Hi @limzykenneth, I have some time this week while prepping some beginner level p5 classes i'll be teaching kids this summer. It'd be fun to help out w/ this n and other things now that things have settled down a bit 👩‍🔬  

Are you proposing a dedicated `ondblclick` function to handle this or were you thinking of adding this onto the `_onclick` function in `src/events/mouse.js` as well as in p5.dom?

**Comment by limzykenneth** [comment]
@jay-manday Sorry, a bit late on the reply, this got buried in my email and I forgot about it for a moment.

I was thinking more on the line of creating a `doubleClicked()` function much like `mouseClicked()` so you would use it like so:

```
function doubleClicked(){
  // do something
}
```

and also the same for p5.dom:
```
p5Elt.doubleClicked(function(){
  // do something
});
```

It should be separate from `onclick` as it is listening to a separate event from the browser. You can have a look at the implementation of the events currently and just a matter of adding doubleclick into there.

**Comment by jay-manday** [comment]
@limzykenneth no problemo! I've just submitted a pr for the main p5 lib first, I was a little unsure of where to add this functionality to the `p5.dom` add on. 

But hopefully my changes are  ok and will look further into it. I used the `dblclick` event listener for this method (https://developer.mozilla.org/en-US/docs/Web/Events/dblclick)

**Comment by limzykenneth** [comment]
@jay-manday The source for p5.dom is available over [here](https://github.com/processing/p5.js/blob/master/src/core/p5.Element.js), do go ahead an include the changes in p5.dom in the same PR, you will need to build and commit the p5.dom.js file in the `lib/addons` folder as well after you have changed the file above.

**Comment by lmccart** [comment]
closed with https://github.com/processing/p5.js/pull/2059
