### ISSUE TITLE
clarify API reference for color(), fill(), stroke() to specify CSS string + alpha value is not supported

### ISSUE THREAD

**Issue by pehagg** [processing/p5.js#2041]
#### Nature of issue?

- [X] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [X] Color
- [ ] Core
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [X] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.5.11
- Web browser and it's version: Chrome 59.0.3071.115
- Operating System: macOS
- Steps to reproduce this:

Both

```javascript
var color = color("#010203", 200);
```

and 

```javascript
fill("#010203", 200);
```

result in:

```
p5.js:9499 Uncaught Error: [object Arguments]is not a valid color representation.
    at p5.Renderer2D.p5.Color._parseInputs (p5.js:9499)
    at new p5.Color (p5.js:8937)
    at p5.color (p5.js:8620)
    at <anonymous>:1:1
```

**Comment by with-a-k** [comment]
I'd like to take a look at this one.
