### ISSUE TITLE
Remove parentheses from YUIDoc params?

### ISSUE THREAD

**Issue by kaganjd** [processing/p5.js#2042]
#### Nature of issue?

- [X] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Events
- [X] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [X] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

Not sure if this is technically a bug but something about having parentheses inside the YUIDoc params isn't working with the script I'm using to generate the Tern.js autocomplete/code hints file. Would it break anything if we change the following things?

1.  **src/webgl/loading.js**
[Here](https://github.com/processing/p5.js/blob/5ad15eecc37fec2ca2fb6559acc4309f70b32363/src/webgl/loading.js#L28-L31) and [here](https://github.com/processing/p5.js/blob/5ad15eecc37fec2ca2fb6559acc4309f70b32363/src/webgl/loading.js#L38-L39), either make both params`{Function}` **or** `{p5.Geometry}` and `{Event}` **instead of** `{Function(p5. Geometry)}` and `{Function(Event)}`

2.  **src/image/loading_displaying.js**
[Here](https://github.com/processing/p5.js/blob/6ff044d351d662c90a103da9c93d7b5e4037917e/src/image/loading_displaying.js#L32-L35), either make both params `{Function}` **or** `{p5.Image}` and `{Event}` **instead of** `{Function(p5.Image)}` and `{Function(Event)}` 

3.  **lib/addons/p5.sound.js**
[Here](https://github.com/processing/p5.js/blob/004ba93e2ecfe4f7c5c7323eac6c07b8a801cef1/lib/addons/p5.sound.js#L8432), remove parentheses from param description (`part(s)`)

**Comment by lmccart** [comment]
yes that would be totally fine, and an improvement

**Comment by kaganjd** [comment]
I hadn't pulled the latest in a while, and I believe 1 and 3 above were fixed with #2037. 

2 is still causing a problem though. I'm wondering if it's a YUIDoc type problem like the others, not a punctuation problem. I'll look at this today and update.

**Comment by kaganjd** [comment]
I think this commit will fix 2: https://github.com/kaganjd/p5.js/commit/4300ad2651c748434d3fc68d953c86a6da7a869a

I'll submit a PR after #2056 is merged

**Comment by kaganjd** [comment]
Closing this. #2056 fixed 2 and created a new problem for the Tern.js script, so I think I was wrong about parentheses being the problem.
