### ISSUE TITLE
Remove "If you are using the p5 editor, you can skip to the Your First Sketch section" from the get started page

### ISSUE THREAD

**Issue by DexterShepherd** [processing/p5.js#2044]
Hello :)

Was reading through the Get Started doc here https://p5js.org/get-started/ while researching a workshop and noticed this. 

It seems like referencing an editor that is not easily accessible on the first lines of the getting started document might be more confusing than helpful for the people that document is intended for. As a new user with no programming experience I would be unsure whether I should have this editor before starting the guide. 

If this is just being left in until the web editor is released that makes total sense, just bringing it up if it happens to be an oversight. 

Thanks for all the hard work.

Dex

<img width="743" alt="screen shot 2017-07-05 at 5 17 09 pm" src="https://user-images.githubusercontent.com/7800175/27890171-da963a64-61a5-11e7-9b4a-53b2241c6728.png">

**Comment by limzykenneth** [comment]
Hi @DexterShepherd, I believe that was left in when there was a standalone p5 editor which was deprecated a while ago and this part of the site was not updated to reflect that. I'll post this issue over at [p5.js-website](https://github.com/processing/p5.js-website/issues)'s issue page as this change will be taking place there.

Thanks!

**Comment by DexterShepherd** [comment]
Thanks for checking this out and moving it on. I didn't realize there was a separate repo for the website itself. :)
