### ISSUE TITLE
Keyboard input wont work

### ISSUE THREAD

**Issue by kino2007** [processing/p5.js#2045]
#### Nature of issue?

- [x ] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x ] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 
- Web browser and it's version:
- Operating System:
- Steps to reproduce this:

**Comment by limzykenneth** [comment]
Hi @kino2007 

I'm afraid you will have to be more specific about your issue. There's not much we can do from just your title alone. Please at least provide a brief description of what exactly is or isn't happening, and a sample code to demonstrate the problem. Thanks.

**Comment by kino2007** [comment]
Here's the code with an issue:
[code]
function keyPressed() {
  if(key === 'w'){cy -= 1}
  if(key === 's'){cy += 1}
  if(key === 'a'){cx -= 1}
  if(key === 'd'){cx += 1}
  if(key === 'e'){cz -= 1}
  if(key === 'z'){cz += 1}
}
function keyReleased() {
  if(key === 's'){cy -= 1}
  if(key === 'w'){cy += 1}
  if(key === 'd'){cx -= 1}
  if(key === 'a'){cx += 1}
  if(key === 'z'){cz -= 1}
  if(key === 'e'){cz += 1}
}
[/code]
Where cx, cy, and cz are variables.

**Comment by kino2007** [comment]
For some reason it only works with those non ASCII codes.

**Comment by lmccart** [comment]
Depending on your browser, the key value may contain a capitalized key. ie changing your logic to if (key === 'W') should work. To get the proper capitalization, it is best to use it within keyTyped().

**Comment by kino2007** [comment]
a
