### ISSUE TITLE
Add support for creating color objects with #rgba and #rrggbbaa hex strings

### ISSUE THREAD

**Issue by with-a-k** [processing/p5.js#2046]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [x] New feature request

#### Most appropriate sub-area of p5.js?

- [x] Color
- [ ] Core
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL

#### Feature enhancement details:

Add two new valid color representations for creating new colors:

- `#rgba`, equivalent to `#rgb` with an extra hex digit to set the alpha value
- `#rrggbbaa`, equivalent to `#rrggbb` with two extra hex digits to set the alpha value.

These representations appear in W3 color Level 4 specifications.

**Comment by lmccart** [comment]
fixed with https://github.com/processing/p5.js/pull/2048
