### ISSUE TITLE
Add constants for RAD_TO_DEG, DEG_TO_RAD

### ISSUE THREAD

**Issue by golanlevin** [processing/p5.js#2047]
#### Nature of issue?
- [X] New feature request

#### Most appropriate sub-area of p5.js?
- [x] Core
- [X] Math
- [X] Utilities

#### Which platform were you using when you encountered this?
- [X] Desktop/Laptop

#### New feature details:
Please add constants for RAD_TO_DEG, DEG_TO_RAD. These are common in creative-coding toolkits, such as Processing and openFrameworks. Having them in p5.js would make porting between these environments easier. 

RAD_TO_DEG is a constant which converts Radians to Degrees. Multiplying an angle (in Radians) by this constant produces its value in Degrees. It is precisely equal to 180.0/PI, or approximately 57. 

DEG_TO_RAD is its reciprocal, precisely equal to PI/180.0. 
Thanks.

**Comment by lmccart** [comment]
closed with https://github.com/processing/p5.js/pull/2068
