### ISSUE TITLE
sketch does not keep drawing if the tab is not active

### ISSUE THREAD

**Issue by zepadovani** [processing/p5.js#2057]
I'm not sure if this is a bug or a feature, but converting a sketch from the older processing.js to p5.js I've noticed that if I change the tab of my browser, the sketch frame flow is freezed until I return to the tab.

I've noticed that simpler examples in p5js (https://p5js.org/reference/#/p5/frameCount, for instance) also present this behaviour and, if it is not a bug as I suspect, I suggest to have an option (inside the draw() function, perhaps) that allows the configuration of a continuous draw behaviour, regardless of the tab being or not active/focused.

**Comment by kadamwhite** [comment]
Hey @zepadovani, thanks for the question! p5.js uses the [`requestAnimationFrame`](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame) browser API method to [run the draw loop](https://github.com/processing/p5.js/blob/ed94431045900c61cb1f78942a64e0f2a623df69/src/core/core.js#L377), and unfortunately `requestAnimationFrame` was explicitly designed to not run when the tab is backgrounded. I understand the situations where this can be frustrating, but it was a decision the browser vendors made to avoid having average websites needlessly drain battery or consume power when not active in the browser.

There are ways you can work around this yourself by using `setInterval` to control your own draw loop, but you'll be working partially outside of p5's core constructs should you wish to do so; I suspect the decision to have `draw` depend on `requestAnimationFrame` is long set at this point.

**Comment by dhowe** [comment]
I also ran into this problem in a project, specifically the fact that timers (setInterval, etc.) continue to run though draw is not being called, so it is not as if the entire program pauses (which would be preferable, at least for my case). I ended up having to implement event listeners for all the different kind of events that caused requestAnimationFrame to stop calling draw (tab-change, window-change, sleep, screensaver, etc.) and then pausing all of the objects in the sketch, so that they could then resume (together) when the sketch became active again. 

Perhaps there is a better way to do this... I'm not sure, but one (unconsidered) thought is to implement wrappers for setInterval and setTimeout in p5, which are automatically paused/resumed whenever draw stops being called...

**Comment by limzykenneth** [comment]
I think this problem probably would have been encountered by other drawing/animation libraries, does anyone know how (if at all) do they deal with this problem?

**Comment by Torpexx** [comment]
I have the same problem. Any insight would be very much appreciated.

**Comment by kadamwhite** [comment]
@dhowe This isn't a complete fix but it's possible to use `requestAnimationFrame` directly within our own sketch code; if we're using that for our own timers in lieu of `setInterval` then at least they should behave in the similar fashion to the regular draw loop.

**Comment by zepadovani** [comment]
Any hint on how to implement this solution? Digging the web I saw a lot of developers that could not use requestAnimationFrame to solve this (it seems to work only when tab is active). My old processing.js sketch renders continuosly (see: http://josehenriquepadovani.com/) but I want to update it to have a better graphic quality in high pixel density screens (retina).

**Comment by zepadovani** [comment]
Oh, perhaps not! Just saw this (https://stackoverflow.com/questions/5927284/how-can-i-make-setinterval-also-work-when-a-tab-is-inactive-in-chrome) but I'm still trying to figure out how to adapt a drawing loop to this logic. :/

**Comment by lmccart** [comment]
I'm going to say this is expected behavior, though not necessarily ideal for some cases, it follows the way that requestAnimationFrame works, which makes sense to me. there are not currently plans to change this behavior though workarounds posted here are appreciated.

**Comment by wolfy01** [comment]
There's also another way... If the tab is playing audio, the interval should not slow down.
