### ISSUE TITLE
Making a simple drawing web thing and got error: Uncaught TypeError: Cannot read property 'show' of undefined

### ISSUE THREAD

**Issue by Ryzon3** [processing/p5.js#2061]
I have investigated this it says it is on line 10 but I can not find the error
<br></br>
Here is my code:
var pixels = [];
var drawing = false;

`

function setup() {
    createCanvas(windowWidth, windowHeight);
}
function draw() {
    background(0);
    for(var i = pixels.length - 1;i >= 0;i++) {
        pixels[i].show();
    }
    if(drawing) {
        var nP = new Pixel(mouseX, mouseY);
        pixels.push(nP);
    }
}

function mousePressed() {
    drawing = true;
}
function mouseReleased() {
    drawing = false;
}

function Pixel(x, y) {
    this.x = x;
    this.y = y;
    
    this.show = function() {
        push();
        noStroke();
        fill(255);
        rect(this.x, this.y, 10, 10);
        pop();
    }
}

**Comment by limzykenneth** [comment]
Instead of
```
for(var i = pixels.length - 1; i >= 0; i++)
```
you probably meant
```
for(var i = pixels.length - 1; i >= 0; i--)
```
instead, as you are iterating the array in reverse.

In general, this kind of question is more suitable for the [forum](https://forum.processing.org/two/) as github issues are more for bug tracking and feature requests. Thanks.
