### ISSUE TITLE
p5dom library cant create textarea

### ISSUE THREAD

**Issue by jtoy** [processing/p5.js#2062]
The p5 dom library allows creating most form elements except for a textarea. Textarea is needed for large amount of text that could be used for form processing.

**Comment by lmccart** [comment]
the `createElement()` method lets you create any HTML element that doesn't have it's own p5 creator method. to further modify, you can access the underlying element created use the .elt property. for example: 

```javascript
function setup() {
  var area = createElement('textarea');
  area.elt.placeholder = 'hint text';
}
```
https://p5js.org/reference/#/p5/createElement
