### ISSUE TITLE
width and height of p5.Graphics object not adjusted when resized

### ISSUE THREAD

**Issue by mjvDEV** [processing/p5.js#2064]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [x] Core
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

As best I can tell, when `resizeCanvas(w,h);` is called on a graphics buffer created with `createGraphics(w,h);` the width and height of the p5.Graphics object are not adjusted, only the lower level width and height values. This causes the graphics to be displayed at the wrong size.

The code I've provided below demonstrates this. After 5 seconds, the graphics buffer is supposed to be resized to half the size, but instead displays at one quarter of its original size. 5 seconds later I adjust the width and height of the p5.Graphics object to the correct values, and the graphics buffer is then displayed at the correct size.

Apologies if this has already been brought up.

- p5.js version: /*! p5.js v0.5.11 June 01, 2017 */
- Web browser and it's version: Chromium Version 59.0.3071.109 (Developer Build) Built on Ubuntu , running on Ubuntu 16.04 (64-bit)
- Operating System: Ubuntu 16.04 LTS
- Steps to reproduce this: 

```
var graphics; 
var gWidth = 400;
var gHeight = 200;

function setup() {
    createCanvas(600,400);
    graphics = createGraphics(gWidth, gHeight);
    graphics.background(0,255,0);

    // Resize to half size in 5 seconds.
    setTimeout( function() {
        gWidth /= 2;
        gHeight /= 2;
        graphics.resizeCanvas(gWidth, gHeight);
        graphics.background(0,255,0);

        // 5 seconds later, correct the width and height.
        setTimeout( function() {
            graphics.width = gWidth;
            graphics.height = gHeight;
        }, 5000 );
    }, 5000 );
}

function draw() {
    background(155);
    image(graphics, 100, 100, gWidth, gHeight);
}
```

**Comment by limzykenneth** [comment]
I don't think `resizeCanvas` is a method of `p5.Graphics` which is why it has no effect. However, when `resizeCanvas` is called on `p5.Graphics` when it doesn't exist, I expect it to throw an error which it doesn't seem to. In any case, for now I would suggest using

```
graphics.width = gWidth;
graphics.height = gHeight;
```

to change `p5.Graphics` size but a utility method would certainly be nice to have.

**Comment by lmccart** [comment]
This is correct, resizeCanvas() is only for canvas, but you can use the .size() method. Something like this:
```javascript
var g;

function setup() { 
  createCanvas(600,400);
  g = createGraphics(200, 200);
} 

function draw() { 
  background(220);
	g.background(255, 0, 0);
	image(g, 0, 0);
}

function windowResized() {
	g.size(50, 50);
}
```

**Comment by mjvDEV** [comment]
I tried that, but all I got was an exception stating that "size() is not a valid p5 function, to set the size of the drawing canvas, please use createCanvas() instead." Has something changed since the last release?

I should mention that when I used resizeCanvas(), the problem was not that it had no effect- it did in fact change the size of the underlying canvas, as well as all other places where the width and height exist _except_ for inside the graphics object itself. If I call image() with only the buffer and x and y values, instead of also specifying the width and height at which to display the image, it displays as though correctly resized - but this means that resized images can only be shown correctly at a 1:1 resolution.

**Comment by lmccart** [comment]
Have you included the p5.dom library? See the instructions here:https://p5js.org/reference/#/p5.Element/size

**Comment by mjvDEV** [comment]
Oh! I didn't realize that was a dependency- the graphics buffer, for the most part, seems to work fine without the dom library.

So that does properly resize the buffer, but it did expose a different problem though: The buffer was no longer hidden after I called size()! I did some debugging and I think I found the line in p5.dom.js that changed the "display" style setting from "none" to "":

https://github.com/processing/p5.js/blob/d50d364956be09c798ac27f739aa3877d27265c5/lib/addons/p5.dom.js#L1643

I'm definitely a bit of a newbie here though, so I'm not set up yet to do my own editing and testing, but is there a reason this line is used:

```
this.elt.setAttribute('style', 'width:' + aW + 'px; height:' + aH + 'px');
```

instead of something like this (from p5.Rendered.prototype.resize):

```
this.elt.style.width = w +'px';
this.elt.style.height = h + 'px';
```

**Comment by uberubert** [comment]
I struggled with resizeCanvas for a long while when working with graphics objects created with "createGraphics". The answer by limzykenneth, suggesting to simply set the width and height properties directly, worked perfectly!

I would suggest adding an entry to the reference on resizeCanvas about this or, alternatively, add a utility function called "resizeGraphics" if only to make this intuitive for future graphics object resizers.
