### ISSUE TITLE
how i got a random INT in p5.js?

### ISSUE THREAD

**Issue by matteboro** [processing/p5.js#2066]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [ ] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 
- Web browser and it's version:
- Operating System:
- Steps to reproduce this:

**Comment by limzykenneth** [comment]
You can simply do
```
var x = round(random(0, 50));
```
to get a whole number between 0 and 50.

In future, this kind of programming related question is better suited for the [forum](https://forum.processing.org/two/). Github issues are more for bug reporting and feature requests. Thanks.

**Comment by sixhat** [comment]
One must be careful with the quick recipes. 

`round(random(0, 50));` gives you a number in the range [0–50] with 0 and 50 occurring half of the times of the remaining numbers. 

It is more normal/correct to use 

`floor(random(0, 50));` 

this gives you a random number in the range [0-49] with equal probability of occurrence of each number.

**Comment by limzykenneth** [comment]
@sixhat Good catch, thanks!
