### ISSUE TITLE
Disable the "text"-cursor when hovering text

### ISSUE THREAD

**Issue by rockfarmor** [processing/p5.js#2067]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [? ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [x ] Typography
- [ ] Utilities
- [ ] WebGL

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [ x] Desktop/Laptop
- [ ] Others (specify if possible)
#### New feature details:

When hovering over a text rendered with p5, the I-cursor (text-cursor) appears. This should indicate that the text can be highlighted or edited. Is it possible to deactivated this I-cursor when hovering text? I'm currently on a Macbook with Chrome, I don't know if this is reproducible on windows or any other browser.

**Comment by lmccart** [comment]
can you give an example snippet of code, or link to an example where you see this behavior?

**Comment by rockfarmor** [comment]
This includes every p5.text where no cursor has been forced. My current workaround is to force the cursor to Cursor(ARROW).

Link to example: [](https://p5js.org/reference/#/p5/text)

Screenshot of behaviour:
<img width="412" alt="test" src="https://user-images.githubusercontent.com/10855270/28294275-4060f1d8-6b59-11e7-8fce-90618c028f78.png">

**Comment by limzykenneth** [comment]
I cannot replicate this problem on macOS (10.12.5) on all latest versions of Safari (10.1.1), Chrome (59.0.3071.115) and Firefox (54.0.1). It's pretty weird to be honest as there's no reason why the browser would use the text cursor on a canvas element. My hypothesis would be some kind of layout error that puts a text field or similar on top of the canvas element causing it. @rockfarmor can you try disabling any browser extensions, if any, and see if the problem persists?

**Comment by rockfarmor** [comment]
I have no extensions activated, try to mark the text on the canvas and see if the problem occurs

**Comment by lmccart** [comment]
as far as I can tell, this is just the default behavior of clicking and dragging over a page that contains text on it somewhere. since the reference page contains text in the description and other areas, the text icon is displayed. this occurs on examples that do not contain the text() command in them as well. however, if you make a p5.js sketch of your own with just a canvas, you will not see this behavior. so I don't think this is library specific.
