### ISSUE TITLE
width / height don't change if canvas element is resized

### ISSUE THREAD

**Issue by antiboredom** [processing/p5.js#207]
The width and height variables don't seem to get updated if the canvas element's size is changed.

**Comment by typio** [comment]
This is really late but window.onresize doesn't work because if the browser is maximized it doesn't get called. Instead just putting c.size(windowWidth, windowHeight) in the draw loop works without any noticeable lag.

**Comment by clankill3r** [comment]
Wouldn't it be good if p5 checks if it is in fullscreen in the pre draw, and if so set the w and h accordingly?
