### ISSUE TITLE
Calls to texture() are slow

### ISSUE THREAD

**Issue by mlarghydracept** [processing/p5.js#2072]
#### Nature of issue?

- [ ] Found a bug
- [x] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

When working on #2071 I noticed that calls to `texture()` are really expensive. Rendering 20 textured boxes will grind the framerate to a halt after a few minutes. Looking at the performance graphs this is all happening in the `_bind` function and more specifically within that  `gl.texImage2D` and subsequent garbage collection. 

After some research I found that `gl.texImage2D` should only be used for initialization and in the draw loop we need to be using `gl.texSubImage2D`. The difference being that the former allocates memory for and creates a new object, whereas the latter just makes changes to the existing object.

The problem comes with checking to see if `gl.texImage2D` has been run and then switching over to the other. GL doesn't provide any methods or parameters for finding that out from what I can tell. 

But the even bigger issue I hit came when I did something hacky to test my hypothesis (put a boolean 'switcher' in the renderer) - I got errors in the console related to `gl.texSubImage2D` and nothing displayed. 

> [.Offscreen-For-WebGL-0x7fd9ea057400]GL ERROR :GL_INVALID_OPERATION : glCopySubTextureCHROMIUM: destination texture is not defined
> [.Offscreen-For-WebGL-0x7fd9ea057400]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.

These errors seem to imply that the first call to `gl.texImage2D` did not take but this doesn't make sense because I was checking to see if the switcher was working using console.logs.

Anyways I'll keep working on this but I just wanted to put this up here in case someone has information or opinions.

**Comment by DoubleJump** [comment]
You're correct that gl.texImage2D should only be called as infrequently as possible, that sends the pixels to graphics card so can be quite slow. gl.texImage2D lets you upload a portion of an image (say the top-right corner). Once an image is uploaded to the GPU you should only need to bind the texture unit to use it in a shader.

It sounds like one thing to try would be to add a flag to an image to say whether it needs uploading or updating.

Something else I've noticed is that some p5 shaders are using if statements to say whether there is a texture present. You'll end up with a warning when a texture isn't used as all shader branches are always executed (and the results masked out).  One way to fix that is to have a dummy texture always bound to unit 0.

Hope that helps.

**Comment by mlarghydracept** [comment]
Yeah that is helpful! Though I realize now after further testing that while this is a performance hit. It doesn't seem to be as big of an issue as I thought. Performance is fine in anything but edge cases with texturing use. 

Setting the flag to check whether an image needs uploading or updating makes for a pretty big design challenge. Because as far I know there is no simple way to know if this is a different texture than the last one that the user passed into texture, or even the same texture call as the last draw loop. Comparison would be way slower. Still interested in handling this at some point if a good solution is found but because it seems fast enough for anything but edge cases I think it isn't a priority.

Going to close for organizational purposes but if any new info is presented I am up for reopening.

**Comment by Sblob1** [comment]
Hi. I get this issue in android when lots of shapes are having same texture added to them. I get the following error: [.WebGL-0xe73dd700]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
But only on android, as the same code works fine and with no errors on desktop.
