### ISSUE TITLE
syntax error: unexpected token ILLEGAL

### ISSUE THREAD

**Issue by MatthewEE97** [processing/p5.js#2085]
#### Nature of issue?

- [y ] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ y] Core
- [ ] Events
- [ ] Image
- [ ] IO
- [ y] Math
- [y ] Typography
- [ ] Utilities
- [ ] WebGL

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [y ] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: i dont know if its much of a bug but i followed the lesson for trying to create a walker using a vector but it kept saying there was an error and that it needed to be in a function with setup or something like that. in the video he never did that, i followed it to the T and still comes uo as an error, the error accured when i started putting the ".pos" into my code.

- p5.js version: unknown
- Web browser and it's version:
- Operating System: windows 10 , 64 bit
- Steps to reproduce this:

this.walk = function() {
   this.pos = this.pos + ________;
   
   this.pos.x = this.pos.x + random(-5, 5);
   this.pos.y = this.pos.y + random(-5, 5);
 }

**Comment by lmccart** [comment]
hi @MatthewEE97 it's a little hard to tell from the partial code snippet, but I would suggest looking at this line

```javascript
this.pos = this.pos + ________;
```

there shouldn't be any underlines in your code like this, so I would look again at the tutorial video. you might go to earlier in the series if you are having trouble following this one.

in general, github issues are just for bugs with the p5.js library itself, it's best to post issues likes these on the [forum](http://forum.processing.org) which is the place to get programming and debugging help with your own code.
