### ISSUE TITLE
Friendly Error System: implementations

### ISSUE THREAD

**Issue by almchung** [processing/p5.js#2089]
Candidate functions and common error lists related to implementation of FES.

#### color/creating_reading.js
- [x] `alpha()`: replace [LN54](https://github.com/processing/p5.js/blob/friendly-err-sys/src/color/creating_reading.js#L54) with `validateParameter()`
- [x] `blue()`: replace [LN85](https://github.com/processing/p5.js/blob/friendly-err-sys/src/color/creating_reading.js#L85) with `validateParameter()`
- [x] `green()`: replace [LN335](https://github.com/processing/p5.js/blob/friendly-err-sys/src/color/creating_reading.js#L335) with `validateParameter()`
- [x] `red()`
- [x] `brightness()`: replace [LN116](https://github.com/processing/p5.js/blob/friendly-err-sys/src/color/creating_reading.js#L116) with `validateParameter()`
- [x] `hue()`: replace [LN373](https://github.com/processing/p5.js/blob/friendly-err-sys/src/color/creating_reading.js#L373) with `validateParameter()`
- [x] `saturation()`
- [x] `lightness()`
- [x] `color()`
- [x] `lerpColor()`: add `validateParameter()`
- [x] passed all old unit tests
- [x] updated documentation
- [x] add additional unit tests?

#### core/curves.js
- [x] `bezier()` : add `validateParameter()`
- [x] `curve()` : add `validateParameter()`
- [x] `bezierPoint()`, `bezierTangent()`, `curvePoint()`, `curveTangent()`: ignore vs re-write to match the other function design?
- [x] added unit tests

#### src/utilities/string_functions.js
- [x] `join()` `match()` `matchAll()` `nf()` `nfc()` `nfp()` `nfs()` `split()`  `splitTokens()`  `trim()`
- [x] added unit tests

**Comment by almchung** [comment]
@lmccart  I have some function-specific design questions.

1. `lerpColor(c1, c2, amt)`: this one currently forces numerical boundary for `amt` parameter using `min()`,` max()`. Should we consider producing FE for `amt` out of boundary error instead of this method?

2. `bezierPoint()`, `bezierTangent()`, `curvePoint()`, `curveTangent()`: these functions re-assign variable names for individual parameters. Should I re-write them to match the other function style (using `arg` array)?

**Comment by lmccart** [comment]
1. I think it's fine to use as it. It's kind of a hassle to do the min/max manually, and I could imagine cases where amt would need to be capped that's not necessarily a user error. This also aligns with the processing treatment.
2. That would be great.

**Comment by almchung** [comment]
## Recurring error types
#### core/vertex.js
- [ ] `bezierVertex()`, `quadraticVertex()`: [LN315](https://github.com/processing/p5.js/blob/friendly-err-sys/src/core/vertex.js#L315) [LN574](https://github.com/processing/p5.js/blob/friendly-err-sys/src/core/vertex.js#L574) common err type - required object not initiated 
#### src/utilities/string_functions.js
- [ ] Checking that a number positive for `nf()` `nfc()` `nfp()` `nfs()`

**Comment by almchung** [comment]
closing with #2115
