### ISSUE TITLE
Dispose texture function?

### ISSUE THREAD

**Issue by TheChilliPL** [processing/p5.js#2094]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Events
- [x] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL

When I will use
`img = loadImage('assets/someAsset.png');`
How can I unload that asset? In pixi.js there are destroy and dispose functions. Are there any similar?

**Comment by lmccart** [comment]
you can delete the reference to it:

`delete(img)`

**Comment by TheChilliPL** [comment]
I mean removing it from memory

**Comment by TheChilliPL** [comment]
So if I'd create a game, I'd load some textures for some map, and after going to another map, unload from memory old textures

**Comment by lmccart** [comment]
if you just set the variable to null, this will free the memory.
`img = null;`

**Comment by DoubleJump** [comment]
There are gl specific functions for that I dont think have been implemented yet. would mean keeping a reference to the gltexture id around too. doable though.

**Comment by TheChilliPL** [comment]
@lmccart Alright

Well, if that'll work, I'm gonna love this library.

**Comment by TheChilliPL** [comment]
@lmccart How to check if image (and pixels) are already loaded?
And why didn't chrome inspector memory snapshot show up image?
(It's 40 MB image for memory test)

**Comment by TheChilliPL** [comment]
@lmccart Open issue, Chrome task manager shows that it don't work always. Usually after setting it to null it persists in memory
