### ISSUE TITLE
inverseLerp() function

### ISSUE THREAD

**Issue by mzaidikhlas** [processing/p5.js#2100]
#### Nature of issue?
- [x] New feature request

#### Most appropriate sub-area of p5.js?
- [x] Math

#### New feature details:
I would like to add the `inverseLerp()` function which calculates the amount to interpolate between a range (two values) with a provided increment. 

_Example_
`lerp(5, 10, 0.5) // 7.5`
`inverseLerp(5, 10, 7.5) // 0.5`

I have implemented it. If approved I would proceed and write tests + doc

**Comment by lmccart** [comment]
I'm not seeing a lot of energy around this one so towards the goal of keeping the API manageable, I'm going to close this for now and suggest users implement it in their own sketches
