### ISSUE TITLE
Support for mouse events

### ISSUE THREAD

**Issue by libasoles** [processing/p5.js#2101]
#### Nature of issue?
- [ x] New feature request

#### Most appropriate sub-area of p5.js?
- [x ] Events

#### Which platform were you using when you encountered this?
- [x ] Desktop/Laptop

#### New feature details:
I'm interested in mouse events. Particularly, in the ability to subscribe to them from ES6 custom classes.
I'm working with a p5 instance, not using global methods, so I need to be able to do this: 

`p5.registerMethod("mouseEvent", this);`

Or this (for any particular mouse event):

`p5.registerMethod("mouseClicked", this);`
  
I have a draft for the implementation. But no time for tests and documentation. 

See: 

mouse.js
``` javascript

p5.prototype.broadcastMouseEvent = function(context, event) {
 
  const acceptedMethods = {
            mousedown: 'mousePressed', 
            mouseup: 'mouseReleased', 
            click: 'mouseClicked', 
            wheel: 'mouseWheel', 
            mousemove: 'mouseMoved'};

  var method = acceptedMethods[event.type];

  // call generic method
  context._registeredMethods.mouseEvent.forEach(function (obj) {
      obj['mouseEvent'](event);
  }, context);

  // call any particular method if exists
  if (typeof context._registeredMethods[method] !== 'undefined') {

      // call any registered mouse functions subscriber
      context._registeredMethods[method].forEach(function (obj) {

          // call method if exists (as public method)
          switch (event.type) {
              case 'mousedown':
                // call mouse pressed
                obj['mousePressed'](event);
                break;
              case 'mouseup':
                // call mouse released
                obj['mouseReleased'](event);
                break;
              case 'click':
                // call mouse clicked
                obj['mouseClicked'](event);
                break;  
              case 'wheel':
                // call mouse wheel
                obj['mouseWheel'](event);
                break;
              case 'mousemove': 
                // call mouse moved
                obj['mouseMoved'](event);
                break;          
          }
      }, context);
  }
}
```

Implemented like:

```

p5.prototype._onmousedown = function(e) {
  ...
  context.broadcastMouseEvent(context, e); 
  ...
};

```

 For original processing implementation, see: 
 https://github.com/processing/processing/wiki/Library-Basics

This is working. And tested (no unitested, but tested in my project)
So, I need a hand with **testing** and code review. Also, to update docs if PR is approved.

**Comment by libasoles** [comment]
Actually there's no need for the switch. Here's a succinct draft:

```javascript

p5.prototype.broadcastMouseEvent = function(context, event) {
 
  const acceptedMethods = {
            mousedown: 'mousePressed', 
            mouseup: 'mouseReleased', 
            click: 'mouseClicked', 
            wheel: 'mouseWheel', 
            mousemove: 'mouseMoved'};

  var method = acceptedMethods[event.type];

  // call generic method
  context._registeredMethods.mouseEvent.forEach(function (obj) {
      obj['mouseEvent'](event);
  }, context);

  // call any particular method if exists (as public method)
  if (typeof context._registeredMethods[method] !== 'undefined') {

      // call any registered subscriber
      context._registeredMethods[method].forEach(function (obj) {          
          obj[method](event);              
      }, context);
  }
}

```

**Comment by limzykenneth** [comment]
Sorry but this slipped through me so didn't get a chance to look at it. I may not understand this correctly but what I don't understand is why do you need p5 to broadcast the mouse events when the browser already does so? You can directly listen to the browser mouse events like so: 

```
target.addEventListener("click", listener);
```

Or is there some other use you have in mind?

**Comment by lmccart** [comment]
hi @libasoles can you reopen if you have further clarification here? for organizational purposes, I'm going to close the open PR until we finish this discussion. thanks!
