### ISSUE TITLE
strokeWeight() errantly applied to previous shape

### ISSUE THREAD

**Issue by wjmoner** [processing/p5.js#2104]
When working with strokeWeight(), I discovered a bug where strokeWeight is applied in the wrong order. 

#### Nature of issue?

- [ x ] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ x ] Core
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [ x ] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: p5.min.js version v.0.5.11
- Web browser and it's version: Chrome Version 59.0.3071.115 (Official Build) (64-bit) & Firefox 54.0.1 (64-bit)
- Operating System: Mac OSX
- Steps to reproduce this:

function setup() {
  createCanvas(480, 120);
}

function draw() {
  background(204);
  ellipse (75,60,90,90);
  strokeWeight(8); // improperly applies to the prior ellipse
}

#### Feature enhancement details:

The order of operations needs to be corrected in the library.

**Comment by wjmoner** [comment]
A little bit more about this.
The first shape seems to be taking on the last strokeWeight() setting in the sequence.

This code will produce a strokeWeight(20) on the first item in the sequence, then two ellipses with strokeWeight(5), then one with strokeWeight(20).

function setup() {
  createCanvas(480, 120);
}

function draw() {
  background(204);
  ellipse (75,60,90,90);
  strokeWeight(8); // buggy, waiting on correction
  ellipse (175,60,90,90);
  ellipse (279,60,90,90);
  strokeWeight(20);
  ellipse (389,60,90,90);
}

**Comment by lmccart** [comment]
This is the correct behavior. In the first frame, before the first ellipse will get drawn with default stroke weight 1. After that, the stroke weight will follow whatever is set most recently. So at the end of draw, the stroke weight is 20, then it loops back to the beginning of draw, but the stroke weight never gets reset to 1 again so it continues to draw with stroke weight 20. I like to think of it as picking up markers. When you call strokeWeight(20), you have picked up the 20 pixel marker, and your program will continue to hold it until another weight is specified. To say it another way, from the reference entry from [draw](https://p5js.org/reference/#/p5/draw):

"It is important to note that the drawing coordinate system will be reset at the beginning of each draw() call. If any transformations are performed within draw() (ex: scale, rotate, translate, their effects will be undone at the beginning of draw(), so transformations will not accumulate over time. On the other hand, styling applied (ex: fill, stroke, etc) will remain in effect."

**Comment by wjmoner** [comment]
Lauren, thank you for the quick reply. This does make sense, and so closing the issue would be OK.

For your reference, I'm following the code in Make: Getting Started with p5.js, and the code in exercises 3-12 and 3-20 in the book do not work properly. I'll submit a pull request on the code in the book repo: https://github.com/lmccart/gswp5.js-code

**Comment by lmccart** [comment]
@wjmoner ah thanks for letting me know about the examples and sorry for the confusion. a pull request would be happily accepted.
