### ISSUE TITLE
webgl: add object/abstraction for textures (p5.Texture)

### ISSUE THREAD

**Issue by kjhollen** [processing/p5.js#2109]
#### Nature of issue?

- [x] Existing feature enhancement

#### Most appropriate sub-area of p5.js?

- [x] WebGL

#### New feature details:
Create a p5.Texture object that can be used to track various GL state affiliated with textures. At the moment, this would only be used for texture() but could be extended to handle font textures or other ideas in the future. Renderer would handle collections of textures & tying them to shaders. This is the next step in the shader refactor.

I'm working on this as a next step in the architecture refactor. I think this could be a good way to build some architecture to resolve #2072, too—I'll keep that in mind as I'm working on this.

**Comment by DoubleJump** [comment]
I did a little bit on texture samplers over the weekend (#2091). Not sure if it's of any use to you but it might make more sense to be included as part of a Texture object.

**Comment by kjhollen** [comment]
@DoubleJump hey, yes, I saw your post and am sorry that I didn't get to comment sooner! I will review this more closely to see what can be pulled into the Texture object. in the mean time, I've opened a pull request for our WebGL_GSOC17 branch that has a preview of what the Texture object might look like and you're welcome to comment!

**Comment by kjhollen** [comment]
Implemented in #2166!
