### ISSUE TITLE
loadModel cannot load

### ISSUE THREAD

**Issue by jay-manday** [processing/p5.js#2111]
#### Nature of issue?

- [X] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Events
- [ ] Image
- [X] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [X] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.5.11
- Web browser and it's version: Chrome Version 59.0.3071.115 (Official Build) (64-bit)
- Operating System: Mac OS 10.12.5
- Steps to reproduce this: (https://github.com/jay-manday/p5-loadModel-errorCase)

#### New feature details:

Hi my friend @edouerd and I were working on a project and we came across a bug in `loadModel()` but for some reason the console has been logging `Fetch API cannot load file://../assets/wormie.obj. URL scheme must be "http" or "https" for CORS request.` 
which is weird because it's a local file and cors shouldn't be called?

This was also part of the console error:

`Uncaught (in promise) TypeError: Failed to fetch
    at Object.p5.httpDo (p5.js:23279)
    at p5.loadStrings (p5.js:22699)
    at p5.loadModel (p5.js:32064)
    at setup (sketch.js:6)
    at p5.<anonymous> (p5.js:11564)
    at p5.<anonymous> (p5.js:11494)
    at new p5 (p5.js:11776)
    at _globalInit (p5.js:8048)`

anyway, I'm flummoxed as to the cause and curious to see how we can patch. I've included a link in the form to a repo with a simple sketch reproducing the error. Thanks guys!

**Comment by mlarghydracept** [comment]
I cloned your repo have no errors when running this off of a [local server](https://github.com/processing/p5.js/wiki/Local-server)
(note: I passed in true as a second parameter to loadModel in order to normalize the size of your model so that it is visible)

![screen shot 2017-08-07 at 9 57 49 pm](https://user-images.githubusercontent.com/10382506/29056955-aa48682a-7bbb-11e7-8b44-970a721153c9.png)

closing for now because I think this was just a CORS problem.

**Comment by jay-manday** [comment]
ahhhhh yes this did the trick! thanks Stalgia :)

**Comment by edouerd** [comment]
Thank you so much @mlarghydracept !
