### ISSUE TITLE
in p5.js v0.5.11 June 01, 2017, touchIsDown does not work

### ISSUE THREAD

**Issue by wjmoner** [processing/p5.js#2114]
#### Nature of issue?

- [ ] Found a bug

#### Most appropriate sub-area of p5.js?

- [x ] Events

#### Which platform were you using when you encountered this?

- [x ] Mobile/Tablet (touch devices)
- [x ] Desktop/Laptop

#### Details about the bug: 

- p5.js version: 0.5.11
- Web browser and it's version: Chrome (both mobile & desktop)
- Operating System: Mac OSX
- Steps to reproduce this:

function setup() {
  createCanvas(240, 120);
}

function draw() {
  background(204);
  line(20,20,220,100);
  if(touchIsDown) { // returns an error, pasted below
    line(220,20,20,100);
  }
}

Uncaught ReferenceError: touchIsDown is not defined
    at draw (sketch.js:8)
    at e.d.redraw (p5.min.js:6)
    at e.<anonymous> (p5.min.js:4)
    at e.<anonymous> (p5.min.js:4)
    at new e (p5.min.js:5)
    at e (p5.min.js:4)

**Comment by wjmoner** [comment]
Strangely, touch events seem to be missing in this version of p5js. touchIsDown, touchX, and touchY all throw errors. 

function setup() {
  createCanvas(240, 120);
  fill(0, 102);
  noStroke();
}

function draw() {
  background(204);
  ellipse(touchX, touchY, 15, 15);
}

**Comment by lmccart** [comment]
touchIsDown, touchX and touchY have been removed, you can use the mouse versions instead they will update with touch

**Comment by wjmoner** [comment]
Thank you @lmccart
