### ISSUE TITLE
p5.sound.js as module in webpack. p5sound initialization is not fully extending p5

### ISSUE THREAD

**Issue by Izzaki** [processing/p5.js#2117]
Hello,
Im using p5 instance against global accessing.
My angular4 app (webpack) doesn't merge p5.sound addon with p5 fully.
At some point i can use p5.sound extended functions like p5.loadSound();
but i can't use p5.FFT and many more.

Should i include p5.sound in different way?
Or is it p5.sound modularity issue?

#### Nature of issue?

- [ ] maybe found a bug
- [ ] or new feature request

#### Most appropriate sub-area of p5.js?

- [ ] p5.sound

#### Which platform were you using when you encountered this?

- [ ] Desktop/Laptop

#### Details: 

version: p5.js v0.5.11 June 01, 2017
framework: angular4

	import * as p5module from 'p5/lib/p5';
	import * as p5moduleSound from 'p5/lib/addons/p5.sound';

	constructor(){
		var p5start = function(p5){

		/**
		@p5moduleSound is an empty object, but putting it here is like calling the module
		- so at this point, this just extends p5 object.
		*/
		p5moduleSound;
		
		var song = null;
		var fft = new p5.FFT(0, 20); // p5.FFT is UNDEFINED!
		
		p5.preload = function() {
			song = p5.loadSound('assets/song.mp3'); // works well!
		}
		
		p5.setup = function() {
			p5.createCanvas(400, 200);
		}

		p5.draw = function() {
			p5.background(125, 0);
		};
		var p5instance = new p5module(p5start, 'music-visualizator');
 	}

**Comment by lmccart** [comment]
This issue was moved to processing/p5.js-sound#212
