### ISSUE TITLE
unknown getColor function

### ISSUE THREAD

**Issue by disambiguator** [processing/p5.js#2118]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [x] Color
- [ ] Core
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 
- Web browser and it's version:
- Operating System:
- Steps to reproduce this:

I'm seeing references to a function called "getColor" here, but I don't see it anywhere in the API. Am I missing something?
https://github.com/processing/p5.js/blob/0a65b8081c02a95059302e4e46abca511248a575/src/image/pixels.js#L400

Thanks!

**Comment by yatriks** [comment]
Hey,
Looks like it was removed in this 'refactor' in July 2014: https://github.com/processing/p5.js/commit/001cda2a2ba3b219dbc585a799fb2629aa45934a#diff-fecaef9926a3d9ed7f9ac61c8e72e2f0L243

It doesn't appear that the renderer's `get()` takes [colorMode()](https://p5js.org/reference/#/p5/colorMode) into account.

At the discretion of developers, the choice can be made to remove `p5.js/src/image/pixels.js:400` alone, or remove it and update the `get()` method to take `colorMode` into account. Happy to take on either task.

**Comment by disambiguator** [comment]
Cool! Just wanted to make sure y'all knew that the documentation was a little out of date (on the website as well). Both solutions make sense to me.

Cheers.

**Comment by lmccart** [comment]
@yatriks could you investigate whether there's any performance or technical issue with taking colorMode into account in get()? I'm trying to figure out why we had getColor() at one point. if there seems to be no issue or slowdown with considering colorMode in get(), that would be the preferred fix. otherwise, we can add the getColor() function back in. thanks!

**Comment by yatriks** [comment]
@lmccart 👍 I'll get back to you.

**Comment by yatriks** [comment]
@lmccart Hey so, sorry this is later than I expected. 
From what I can tell, it's relatively straightforward to take colorMode into account in get() by returning a p5 Color – but that sounds breaking, as the output of get() is always expected to be an array right now.

Maybe adding a new `getColor` that starts with the output of `get` and converts it by `colorMode` is the right move here?

**Comment by lmccart** [comment]
thanks for looking into this. sounds good, let's go ahead with `getColor()`
