### ISSUE TITLE
saveTable() issue

### ISSUE THREAD

**Issue by currymike123** [processing/p5.js#2121]
#### Nature of issue?

- [x ] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Events
- [ ] Image
- [x ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [ x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.5.7
- Web browser and it's version: Chrome 60.0.3112.90
- Operating System: 10.10.5
- Steps to reproduce this:
----------
```javascript
var table;

//Photoville.csv contains following:
//ID,NAME,EMAIL

function preload() {
  table = loadTable("DATA/photoville.csv", "csv", "header");
}

//The program receives user name and user email values through createInput() and sends them to submit().

function submit() {
    var name = username.value();   
    var email = useremail.value();   
    var NRow = table.addRow();
    NRow.setNum('ID', (table.getRowCount() - 1));
    NRow.setString('NAME', name);
    NRow.setString('EMAIL', email);
    print(table);
    saveTable(table, 'photoville.csv');
}
```
----------

The table that is is printed to the console looks as follows:
ID,NAME,EMAIL
0,Mike,mike@mike.com

The table saved to the csv file looks as follows:
ID
NAME
EMAIL
0
Mike
mike@mike.com

Is there a bug or a problem with my code?  Any help would be greatly appreciated.

**Comment by lmccart** [comment]
this was fixed since 0.5.7. it should work with the latest, 0.5.12
