### ISSUE TITLE
Build instructions on wiki need updating?

### ISSUE THREAD

**Issue by kjhollen** [processing/p5.js#2125]
@outofambit and I were following the [build instructions on the wiki](https://github.com/processing/p5.js/wiki/Development) during a workshop and noticed that first time devs couldn't build the project as instructed. The first call to `grunt` in step 5) fails if the docs haven't been built before because the `docs/reference/data.json` file is missing. We worked around it with `npm run docs` and then continuing through the instructions as indicated.

Filing an issue in case this change is not expected—but maybe all that's needed is updating the wiki?

**Comment by limzykenneth** [comment]
Is it possible to build the `docs/reference/data.json` if missing just so running grunt directly after npm installing will build everything? Having to run docs then run grunt seems a bit redundant to me.

**Comment by outofambit** [comment]
@limzykenneth yep! and it looks to me like that is the intention of the gruntfile. the tasks might be out of order for `grunt` (and `grunt test`). See https://github.com/processing/p5.js/blob/5199e03530cba58ed72e0ead3b4821e4906f4d61/Gruntfile.js#L373 where `build` happens before `yuidoc:dev`.

**Comment by lmccart** [comment]
fix #2127 is perfect. this recently became necessary because we just merged the friendly error features which ingests the reference to use as the check for correct parameters in function calls. so swapping the order in the build task accommodates this and is actually useful for every build to be accurate in terms of parameter checking.

**Comment by lmccart** [comment]
thanks for finding and fixing this!
