### ISSUE TITLE
403 Error when using p5.Vector

### ISSUE THREAD

**Issue by stoufa** [processing/p5.js#2126]
#### Nature of issue?

- [x ] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Events
- [ ] Image
- [ ] IO
- [x ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x ] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: v0.5.11
- Web browser and it's version: Google Chrome Version 60.0.3112.101 (Build officiel) (64 bits)
- Operating System: Windows 8.1 Professional
- Steps to reproduce this:

#### Code:

var location, velocity, acceleration;

function setup() {
	createCanvas( 400, 400 );
	location = createVector( 0, 0 );
	velocity = createVector( 0, 0 );
	acceleration = createVector( 0, 0 );
	print( location );
}

function draw() {
	background( 0 );
	location.add( velocity );
	velocity.add( acceleration );
	velocity.limit( 5 );
	ellipse( location.x, location.y, 5, 5 );
}

#### Problem:
I get a 403 Forbidden error saying :
_You don't have permission to access /sketchDirectory/p5.Vector Object : [0, 0, 0] on this server._

Why's that ?

**Comment by stoufa** [comment]
I figured out the problem !
I was using a processing example as a reference !
`location` is a built-in global object used to get the current page address ( URL ) and to redirect the browser to a new page, so, I can't name my variable location ;)

**Comment by limzykenneth** [comment]
@stoufa This is likely a clash with some native API called `location`, probably [this one](https://developer.mozilla.org/en-US/docs/Web/API/Window/location). Simply renaming your variable `location` to something else (`position` for example) should solve the problem.
