### ISSUE TITLE
saveFrames() limited to 15 seconds ?

### ISSUE THREAD

**Issue by commonpike** [processing/p5.js#2128]
#### saveFrames seems to behave erratically

- [x] Found a bug

I'm trying to create exact (frame-by-frame) animations from p5.js in either GIF or MP4. saveFrames() seems to be the way to go: https://p5js.org/reference/#/p5/saveFrames

saveFrames() has two timing arguments, duration (in seconds) and framerate (per second). You would expect the total of saved frames to be duration*framerate. This seems to be correct up to a duration of 15 seconds. After that, frames are always flushed to disk. With a framerate of 1, I never get more than 15 frames, with a framerate of 3 never more than 45.  With framerates above 3, my mac has problems saving the files ('File system busy'), which is another issue.

My animation lasts up to 600 frames. I would have to use a framerate of 20 to get it to play in 15 seconds, but that is too fast, processor can't handle it and neither can the disk.

#### Which platform were you using when you encountered this?

- [x] Desktop/Laptop

#### Details about the bug: 

- p5.js version: openprocessing.org
- Web browser and it's version: chrome Version 60.0.3112.101 (Official Build) (64-bit)
- Operating System: MaxOSX 10.11.6 (15G1611)
- Steps to reproduce this: https://www.openprocessing.org/sketch/444380

**Comment by lmccart** [comment]
I think you may be hitting the browser limits of number of file downloads that can be initiated at one time. I'd suggest using the method with a callback function that can pass off the data to download to a server that can zip all the files together for easier download, or to another process that can handle all the data.

**Comment by commonpike** [comment]
I did that. Check the link again, saveFrames() now has a callback that dumps the data in your console. The sketch has a duration of 32 and framerate of 2, so you would expect 64 frames, but the callback parameter only saves 30 (=2*15) frames. 

Try and fiddle with the duration and framerate: with any duration above 15 seconds the number of frames is only dependant on the framerate. 

Or put differently, the number of frames output is always
`min(15*framerate,duration*framerate)`

Or put differently, after 15 seconds, saveFrames() triggers a flush if it hasn't already flushed, regardless of duration and framerate.

That's on my browser/os, of course.

**Comment by commonpike** [comment]
Which all makes sense if I read, in 
https://github.com/processing/p5.js/blob/master/src/image/image.js
```
  duration = p5.prototype.constrain(duration, 0, 15);
  duration = duration * 1000;
  var fps = _fps || 15;
  fps = p5.prototype.constrain(fps, 0, 22);
```
So ... the code is silently limiting the operands, and that's not in the documentation either.

But trying to render at a high framerate fails more easily, so for exporting i am tempted to lower the framerate to 1 or 2 per second; nice and easy. And anyway, with both limits in place, one can never export more than 360 frames :-/

A feature request - remove those limits, and (if needed at all), only if `duration*fps` is bigger than 3600 or something fail, or warn the user, verbose. And add those limits to the docs. 

I can create a PR if you agree.

**Comment by limzykenneth** [comment]
Quite awhile a go I came across this constrain as well but didn't figure out why exactly they are there. A possible theory is to prevent crashing the browser with download requests (or maybe even the OS if severe enough). Why the exact number I'm not sure and whether can they be higher, I'm not sure as well. Different computers and different browsers may give up separately and as I remember saving to Safari is a pain.

After that I forgot about it... 😛

**Comment by commonpike** [comment]
@limzykenneth perhaps you're right. at a second thought, I would change the feature request to just put the limits in the documentation, and perhaps add a line it's an 'easy but not perfect way' to export.

Because .. I managed to export a frameperfect movie yesterday, by overwriting the source code, but there were more issues than just the limits

 - all images are downloaded at once. depending on your os/hardware, this may start failing (disk busy, etc). i worked around it by adding an incremental timeout to the downloads (in saveFrames()) , but it would depend on your hardware/os and the size of the export what exactly that timeout would be
 - saveFrames will always ignore the first frame, it starts saving its first frame at '1000/fps' milliseconds. this is hard to work around, because it is instantiated before the first draw() method happens, and doesn't have a handle to the draw() event. I manually added the first frame myself.
 - the output numbering should be zero padded. I think this is already a feature request.

**Comment by limzykenneth** [comment]
I agree in general. The most important thing in this case I think is to figure out and make clear in the documentation, the use case for this function. Because this function (or even javascript in general) isn't designed to handle constant frame exports and saving to disk like this. It is nice to export a short 10-15 second 12fps animation but for longer ones, using something like Processing may already be a significant enough improvement and warrant serious consideration.

**Comment by lmccart** [comment]
updated docs with https://github.com/processing/p5.js/commit/e8782a28433c52892e4aa1eeb2723e06dc91d998
