### ISSUE TITLE
Firefox support ?

### ISSUE THREAD

**Issue by commonpike** [processing/p5.js#2129]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

I haven't yet seen one single working sketch on processing.org on my up-to-date firefox. I copied some code from the reference and created this tester: https://www.openprocessing.org/sketch/444408
That draws a line on firefox, but it's not moving.

The browser support list doesn't clearly specify what is and isn't supported on Firefox
https://github.com/processing/p5.js/wiki/Supported-browsers

WEBGL does not seem to be an issue anymore ? 
http://caniuse.com/#search=webgl

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: openprocessing.org
- Web browser and it's version: Firefox 55.0.2 (64-bit)
- Operating System: MacOSX 10.11.6 (15G1611)
- Steps to reproduce this:
https://www.openprocessing.org/sketch/444408

**Comment by lmccart** [comment]
Hm, I'm not able to reproduce. When I open the link in firefox I see the line move. Can you open the console and see if there are any errors logged? 
https://developer.mozilla.org/en-US/docs/Tools/Web_Console/Opening_the_Web_Console

**Comment by commonpike** [comment]
Yes, did that, no errors. I'm vaguely suspecting something with ff/macbook and webgl. it seems webgl is somehow disabled on chrome on this machine too (allthough everything works fine there until I specify WEBGL in createCanvas(), which fails - with console errors). 

So perhaps something with the videocard. It's a very common macbook though; It would be good to see if other people have this.

**Comment by kjhollen** [comment]
I've got a 2015 MacBook Pro and am able to see the example animating in Firefox.
OS Version: macOS Sierra 10.12.4

Are you able to see the line move before specifying WEBGL? I also see an error in the console when switching to WEBGL mode, in both Firefox and Chrome: `this._renderer.line` is not a function and `errorObj` is null—but as given in the link (in 2D/canvas mode), everything is working as expected on my end.

**Comment by juniorxsound** [comment]
Hi @commonpike the browsers might have flagged your graphics card as not suitable for WebGL. Luckily if it is that, it's pretty easy to override.

Try this: https://superuser.com/questions/836832/how-can-i-enable-webgl-in-my-browser

**Comment by kjhollen** [comment]
Looks like this has been resolved; it's still broken in the original link on Open Processing but is working in the alpha editor with an updated p5.js version: http://alpha.editor.p5js.org/kjhollen/sketches/BkeCOAHxX
