### ISSUE TITLE
createGraphic scale on canvas issue

### ISSUE THREAD

**Issue by unbenjami** [processing/p5.js#2133]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [ X] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Events
- [ X] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [ X] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

Hello, 

Although I'm a bit new in P5, I've been trying different ways of scaling a graphic on canvas as I did with image and it seems it does not work.

I mean, my idea is to create a graphic bigger than canvas, but I want it to be seen entirely on it. When I do so, the graphic can not be seen entirely.

For example, and following (more or less) the example as it can be found on reference, I want to create a graphic 1000x1000 pixels, but I want to it to be shown on a canvas 100x100, so I did this:

var pg;
function setup() {
  createCanvas(100, 100);
  pg = createGraphics(1000, 1000);
}
function draw() {
  background(200);
  pg.background(100);
  pg.noStroke();
  pg.ellipse(pg.width/2-25, pg.height/2-25, 50, 50);

  image(pg, 0, 0, 50, 50); // I want to see it on position 0,0 but in 50 width and 50 heigth size. If "pg" it's not an image but a graphic it seems like it's not entirely shown
}

So as I can see, the graphic it looks like it's been cut.

Is there any way to create a graphic bigger than the canvas but to show it scaled on the canvas? After I'll need it to be on its entirely size.

Thank you very much!

**Comment by limzykenneth** [comment]
@unbenjami I'm guessing you are on a high density display? (Retina display or similar) I'm seeing your problem on a high density display and it works as intended on a regular display. On high density display the graphics created with `createGraphics` will actually have extra pixels in them. Have a look at [this entry](https://p5js.org/reference/#/p5/pixelDensity) in the docs. You can look for or ask further questions at the [forum](https://forum.processing.org/two/).

It's a bit frustrating working with p5.Graphics with pixelDensity at the moment and many issues were opened regarding this. @lmccart Do you think maybe a docs or code rework may be required?

**Comment by unbenjami** [comment]
thanks for your answer!

yes, i'm on a retina display, right now
And yes, it's a bit frustating, because i have the idea the picture (graphic) it's been cut

So, do you think is there any way to create a graphic bigger than the canvas (so i can save it in its entirely size) and to show it on canvas? I guess changing the pixel densitiy is not an option, isn't it?

Thanks again!

**Comment by limzykenneth** [comment]
You can do `pg.pixelDensity(1)` but it may seemed blurry on a retina screen, otherwise, you just have to mentally remember that your graphic is actually `(1000 x density) x (1000 x density)` in size instead of `1000 x 1000`. Which means that to draw it on a retina screen, you need to do something like the following:

```
if(pg.pixelDensity() > 1){
  var d = pg.pixelDensity();
  pg.ellipse(pg.width*d/2-25, pg.height*d/2-25, 50, 50);
}else{
  pg.ellipse(pg.width/2-25, pg.height/2-25, 50, 50);
}
```

**Comment by unbenjami** [comment]
Hello, again

I see what you say, but maybe I can't absolutely understand. 

I mean. Imagine that I want to create a Graphic (1000x1000, for example). And I want to draw a line in it, for example, at position y=900.

When shall I convert the position adding the density?

var pg;

function setup() {
  createCanvas(400, 400);
  pg = createGraphics(1000, 1000); // a graphic bigger than the canvas
}

function draw() {
  background(100,0,0);
  pg.pixelDensity(1);
  pg.background(0);
  pg.stroke(255);
  pg.strokeWeight(1);
  pg.line(10,900,100,900);
  image(pg, 0, 0, 100, 100); // i'd like to show a smaller version of the graphic pg, for example 100x100
}

Sorry, but I can't see where should I convert it?

Thanks again.

**Comment by limzykenneth** [comment]
In that case you will need to scale your line and its coordinates by the pixel density as well, so:

```
var d = pg.pixelDensity();
pg.line(10/d, 900/d, 100/d, 900/d);
```

Note I've made a mistake previously by multiplying the pixel density whereas you should divide by the pixel density, do take note of that.

**Comment by unbenjami** [comment]
Sorry, but there's something that it does not work or maybe I do not understand.

var pg;

function setup() {
  createCanvas(400, 400);
  pg = createGraphics(1000, 1000); // I create a graphic bigger that canvas
}

function draw() {
  background(100,0,0);
  pg.pixelDensity(1);
  pg.background(0);
  pg.stroke(255);
  pg.strokeWeight(1);
  var d = pg.pixelDensity();
  pg.line(10/d, 900/d, 100/d, 900/d); // I want to draw a line 10,900 - 100,900 on the original graphic which is 1000x1000
  image(pg, 0, 0, 100, 100); // I want to show the graphic 1000x1000 scaled at 100x100, and it's been cut
}

Is there something that I don't do well or it's just not possible what I'm thinking?
Thanks a lot

**Comment by limzykenneth** [comment]
@unbenjami Sorry I'm a bit tied up for the past week and wasn't able to look at this issue. On second thought, I think this issue may be better for the [forum](https://forum.processing.org/two/), you can start by searching for posts related to p5.Graphics on the forum as this is quite a common issue and perhaps you will find  a good explanation for your problem. Otherwise asking on the forum may also help you get a faster and perhaps more helpful response. Cheers

**Comment by unbenjami** [comment]
Hello,
Yes, i'll look for it again in the forum or i'll ask  there if anyone has asked it before.
Thank you very much!
Cheers

**Comment by julian-weinert** [comment]
I stumbled across the same issue today. But I think I have a bit of a cleaner solution, than saving the density and applying it over and over again:

`pg.scale(1 / pixelDensity());`
