### ISSUE TITLE
angleBetween can return NaN when 0 was expected

### ISSUE THREAD

**Issue by quinox** [processing/p5.js#2135]
#### Nature of issue?

- [X] Found a bug

#### Most appropriate sub-area of p5.js?

- [X] Math

#### Which platform were you using when you encountered this?

- [X] Desktop/Laptop

#### Details about the bug: 

- p5.js version: 0.5.12
- Web browser and it's version: Chrome 60.0.3112.101 (64-bit)
- Operating System: OSX Sierra
- Steps to reproduce this:
```js
 function setup() {
     var velocity = createVector(-11, -20);
     var outcome = createVector(-5.5, -10);
     var angleBetween = velocity.angleBetween(outcome);
     var dotmagmag = velocity.dot(outcome) / (velocity.mag() * outcome.mag());

     console.log('<velocity, x=' + velocity.x + ', y=' + velocity.y + '>');
     console.log('<outcome, x=' + outcome.x + ', y=' + outcome.y + '>'); 
     console.log('<velocity>.angleBetween(<outcome>) = ' + velocity.angleBetween(outcome)); 
     console.log('<velocity>.dot(<outcome>) / (<velocity>.mag() * <outcome>.mag()) = ' + velocity.dot(outcome) / (velocity.mag() * outcome.mag()));
 
     console.log('Math.acos(' + dotmagmag + ') = ' + Math.acos(dotmagmag));
 }
```
* Demo URL: https://ghost.qtea.nl/tmp/p5js/angleBetween.html (same as above, open JS console)

Expected outcome: `angleBetween.html:16 <velocity>.angleBetween(<outcome>) = 0`

Actual outcome: `angleBetween.html:16 <velocity>.angleBetween(<outcome>) = NaN`

Details:
It seems to be a rounding issue. `<velocity>.dot(<outcome>) / (<velocity>.mag() * <outcome>.mag()) ` returns 1.0000000000000002; `Math.acos(1)` returns 0, `Math.acos(1.0000000000000002)` returns NaN.

An easy solution I see would be to use `Math.acos(Math.min(1, ...))`.

**Comment by limzykenneth** [comment]
I had a look into this but did not dig down into the math but if simply constraining the value passed to `Math.acos` will not result in any false positive or false negative cases then it should be fine.

**Comment by quinox** [comment]
I'll spend some time this weekend on making a PR with testcases.

**Comment by Danie12345** [comment]
This issue is still happening.
