### ISSUE TITLE
Examples on website are not working

### ISSUE THREAD

**Issue by pjnovas** [processing/p5.js#2136]
Hey examples on the website are not working ie https://p5js.org/examples/form-points-and-lines.html
```
Uncaught ReferenceError: p5 is not defined
    at <anonymous>:32:1
    at Object.loadExample (examples.js:165)
    at HTMLIFrameElement.<anonymous> (examples.js:37)
    at HTMLIFrameElement.dispatch (jquery-1.12.4.min.js:3)
    at HTMLIFrameElement.r.handle (jquery-1.12.4.min.js:3)
```

And I think the problem comes from https://p5js.org/assets/js/p5.min.js which returns nothing with a 200 response

**Comment by lmccart** [comment]
dreamhost (our website hosting provider) is currently under ddos attack, so the webpage is not loading all or parts of the contents that should be online. there's not much we can do on our end, but hopefully things will be back up soon https://www.dreamhoststatus.com/

**Comment by pjnovas** [comment]
uh oh, sorry to hear that  
I'm closing this one then and lets :crossed_fingers:   
Thanks!
