### ISSUE TITLE
getUserMedia() on iOS 11 Safari

### ISSUE THREAD

**Issue by kylemcdonald** [processing/p5.js#2146]
Good news! getUserMedia() is a new feature on iOS 11 Safari, which means that some time next month you can start using the webcam and microphone input on iOS.

But it looks like right now there is a bug with the way p5.js wraps getUserMedia().

A friend of mine who is running iOS 11 Safari tried three examples. First, this page:

https://webrtc.github.io/samples/src/content/getusermedia/gum/

Which works:

![](https://pbs.twimg.com/media/DIajcvLUEAAIsKb.jpg)

Then this one:

https://kylemcdonald.github.io/cv-examples/FaceTracking/

Which gives an error:

![](https://pbs.twimg.com/media/DIam6V-VYAE4Uin.jpg:large)

And this one:

https://p5js.org/examples/dom-video-capture.html

Which gives a similar (maybe the same?) error:

![](http://i.imgur.com/pQpmKo0.png)

I'm not going to be installing iOS 11 on my phone until it's out of beta, so I can't help with testing yet, but at least I wanted to start a tracking issue for this :)

**Comment by lmccart** [comment]
@kylemcdonald oh now you're logging issues you don't even have yet huh

**Comment by bwhitman** [comment]
^ Try the patch above, works for me!

**Comment by lmccart** [comment]
fixed with https://github.com/processing/p5.js/pull/2147

**Comment by usachatnow** [comment]
I have the latest version of ios 11 on my iphone which was release tuesday. I believe its the final version. Getusermedia is not working. I get a message that asked to request access to my cam but the video never comes up. Does anyone know if iOS 11 is going to support getusermedia? because as of now its not working.

**Comment by bwhitman** [comment]
@usachatnow can you give more details on how you are testing, with a test url?

**Comment by lmccart** [comment]
the patch from #2147 is not in the latest release yet (new one should be out in the next few days), are you testing with the most recent release or with the src from this repo?

**Comment by usachatnow** [comment]
i am testing it using the getusermedia demo, also i have getusermedia technology in my website that doesnt work with iphones. I have been testing since beta 1 and getusermedia asks for cam and audio permission but fails to work. I also used the links on this page and they fail with the iOS 11 release that was released this past tuesday

**Comment by usachatnow** [comment]
all the releases started with beta 1 through 10 the release that came out tuesday was not called beta, It was called iOS 11 making be believe the final version was released to beta testers first

**Comment by lmccart** [comment]
sorry, I'm talking about the version of the p5.js library. the current release or version is 0.5.14. it does not include support for getusermedia on ios yet. the next one will.

**Comment by usachatnow** [comment]
The getusermedia for iOS 11 still is not working. Today an update for iOS 11 came out and still it fails to work. Can anyone shed some light on whether Apple is indeed going to fix the problem for iPhone?

**Comment by lmccart** [comment]
this is the repository for p5.js (https://p5js.org/), it's not an apple affiliated project and can't do anything to fix ios native issues

**Comment by usachatnow** [comment]
I was told iphone was supporting WebRTC, can anyone tell me why getusermedia is still not working on iPhone?
