### ISSUE TITLE
Problems with color function

### ISSUE THREAD

**Issue by GeneralBender** [processing/p5.js#2148]
#### Nature of issue?

- [ x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ x] Color
- [ ] Core
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [ x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: dont qutie know. Downloaded it yesterday though :D
- Web browser and it's version: chromonium dont know the version (if anyone needs this, he can tell me where to look it up)
- Operating System: ubuntu (I think 16.04)
- Steps to reproduce this:????

How can I do this?

#### New feature details:

Hello everyone!

I am completly knew here and to programming, so I dont even know how to report my issue properly :(
I have the problem that the color funcion (where I can write something like:)

var col = color (255,100,100); 

doesn't work. I guess I dont have the right library "loaded"(???) in this weird html file. 
I get the error: 

Did you just try to use p5.js's color() function? If so, you may want to move it into your sketch's setup() function.

Uncaught ReferenceError: color is not defined

If someone can give me a quick tutorial how to give you the code here I would really be happy. I hate it to not have a clue about what I am doing. I really dont have!

I try to learn how to programm with the tutorials of " The Coding Train" on youtube. When he uses the color function it is higlighted, but in my skript it is not :(

**Comment by limzykenneth** [comment]
Hi @GeneralBender! I would advice you start [here](https://p5js.org/get-started/), follow the steps outlined on that page and you should have a properly set up project and hopefully some basic understanding of how to move forward. Then you should be able to follow Coding Train with no problem.

In future, if you have any programming related questions, feel free to ask them on the [forum](https://forum.processing.org/two/). Github issues are usually used to file bug reports or feature requests.

Good luck with learning programming! 😃
