### ISSUE TITLE
createGraphics sizing problem

### ISSUE THREAD

**Issue by thinsoldier** [processing/p5.js#2149]
#### Nature of issue?
- [x] Found a bug

#### Most appropriate sub-area of p5.js?
- [x] Image

#### Which platform were you using when you encountered this?
- [x] Desktop/Laptop

#### Details about the bug: 
https://codepen.io/thinsoldier/pen/oemPqZ?editors=0010
In an image created by using a 100 wide createGraphics object, drawing a 50 wide rectangle within that creates a 100 wide rectangle instead of a 50 wide rectangle.

p5.js version https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.5.14/p5.min.js

**Comment by limzykenneth** [comment]
Probably related to #2133. I would suggest visiting the [forum](https://forum.processing.org) for help at this point. 

I'm thinking of trying to modify p5.Graphics so it can be a bit more intuitive even on high density display, what do you think @lmccart? Just this kind of problem keeps popping up.

**Comment by thinsoldier** [comment]
It would be a giant help if the documentation was simply updated to mention this quirk. If you're not already 100% certain that this behaviour needs to be changed then just accept that its the way things are and will always be and *mention it in the documentation*.

**Comment by aferriss** [comment]
I just encountered this as well and agree with @thinsoldier  it would be really nice to have a note in the reference about this. It's easy enough to scale the createGraphics with window.devicePixelRatio, but baffling to newcomers who might not know about pixel density.

**Comment by shusain** [comment]
Ran into this as well I have a simple fix as others said just check the devicePixelRatio in the call for rendering images with the image function otherwise having previously created a graphics object with create graphics it is using the scaled size.

**Comment by lmccart** [comment]
following up on this one over here https://github.com/processing/p5.js/issues/2077
