### ISSUE TITLE
Enhancing Image Library 

### ISSUE THREAD

**Issue by Thzn** [processing/p5.js#2157]
#### Nature of issue?

- [ ] Found a bug
- [x] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [x] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Feature enhancement details:

P5.Image has the basic functionality of image arithmetics. So it will be better if it contains simple image processing functionalities as well. I'm proposing some basic functions and like to implement those using p5.

1. RGB to GrayScale conversion
2. Thresholding function 
3. Log transform and Power transform
4. Filtering in spatial domain (median, gaussian, averaging)
5. More simple functions ...

I hope these functionalities will help when using the p5 image. Also, we have to think about performance as well so I assume these simple functions will have lesser execution time.   

Thank You.

**Comment by Thzn** [comment]
Hi,
Can you give me some feedback about my feature request. Is it useful or not. Also is there any features in the development checklist. The link is not working. Can you please give me some guide.
Thank you.

**Comment by limzykenneth** [comment]
While I'm not sure whether specialized functionality like these fit in with p5.js core library, I do believe they do make for a great idea for an addon library focused around image processing, filters and image manipulations.

**Comment by lmccart** [comment]
+1
I think this is beyond the scope currently, but could make a great addon. more info on how to that [here](https://github.com/processing/p5.js/wiki/Libraries#creating-a-new-library)

**Comment by Thzn** [comment]
@lmccart 
Ok, I will implement it as an addon.
Thank you.
