### ISSUE TITLE
I wonder if would be possible to have Processing interacting with Text Data to build Forms.

### ISSUE THREAD

**Issue by dinooz** [processing/p5.js#2158]
I wonder if would be possible to have Processing interacting with Text Data to build Forms.

Also, based on that concept, wonder if the construction of a cool framework like rails or yeoman to build Forms on the Fly, taking the approach of K2 Form will be really awesome.

A SQL/noSQL Data source with some schema.
A constructor for each table /method [ CRUD Methods ]
A contructor for relationships between tables [ CRUD Methods ]
Automatic Build of Functional Forms
Layout Fields and Form Defintion in an XML File
Ability to add Effects like Fade In/ Fade Out. Popup Etc.
Portability to any platform.

I think that will be really awesome !!!.

**Comment by lmccart** [comment]
if this is a suggestion for processing, please report it here: https://github.com/processing/processing thanks!
