### ISSUE TITLE
Passing a variable to textSize() gives an uncaught TypeError

### ISSUE THREAD

**Issue by ErikDuemig** [processing/p5.js#2159]
#### Nature of issue?

- [x ] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ x] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x ] Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: p5.js v0.4.23 March 04, 2016
- Web browser and version: Google Chrome | 60.0.3112.113 (Official Build) (64-bit)
- Operating System: MacOS El Capitan v10.11.6
- Steps to reproduce this:

textSize(30); << returns fine
-----
var textSize = 30;
textSize(textSize); << returns ERROR - Uncaught TypeError: textSize is not a function

**Comment by lmccart** [comment]
in javascript, variables and functions all share one namespace... meaning assigning a value to textSize will overwrite the existing textSize() function. try changing the name of your variable to something else and it should work.

**Comment by ErikDuemig** [comment]
Oh duh. Boy I'm dumb.

Thanks!

-E
