### ISSUE TITLE
Bad lerp behaviour with string numbers

### ISSUE THREAD

**Issue by meiamsome** [processing/p5.js#2167]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [x] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug: 

- p5.js version: 0.5.14
- Steps to reproduce this:

Lerp behaves very badly when passed numbers in strings:
```javascript
lerp("0", 2, 0.5) // Results in "10"
```
My proposed fix would be to replace the current
`return amt*(stop-start)+start;`
with:
`return amt * (stop - start) + +start;`
Which appears to fix all test cases I've tried...
Otherwise, an overly precautions take would be to do:
`return (+amt)*(+stop - +start) + +start;`

**Comment by lmccart** [comment]
lerp is designed to take numbers rather than strings. perhaps this is a case for the friendly error system to help check this, but I worry about going down the rabbit hole of trying to make every function support any type of parameter.

**Comment by meiamsome** [comment]
That does sound sensible. 

I wonder if there is a way to make the FES automatically apply itself to every publicly documented method. That seems like it would be simpler than relying on it being added to some by choice.
