### ISSUE TITLE
TravisCI has not been running for ~4 Months

### ISSUE THREAD

**Issue by meiamsome** [processing/p5.js#2169]
Is this intentional?

There are 7 failing tests at the current commit (fd750bf), that were introduced in fcd82ab - a fix for #2156  by my estimates.

I will pull request fixes for these in a bit, but the TravisCI not running

**Comment by lmccart** [comment]
no definitely not intentional, will look into it..

**Comment by sakshamsaxena** [comment]
is #1881 related?

**Comment by sakshamsaxena** [comment]
I logged in to Travis, only to find out that the building options were disabled. I did switch em on, let's see ..

**Comment by lmccart** [comment]
wow I have no idea how they got switched off. 
it looks like it's running now as far as I can tell. 
<img width="1044" alt="screen shot 2017-09-28 at 5 27 25 pm" src="https://user-images.githubusercontent.com/191056/30995973-509cc4a8-a472-11e7-8ea5-6cc0dfb31df3.png">
