### ISSUE TITLE
PhantomJS is now no longer maintained

### ISSUE THREAD

**Issue by meiamsome** [processing/p5.js#2174]
For information, see https://github.com/ariya/phantomjs/issues/15105

This is just an issue to note that testing should probably be moved over to headless chrome (Probably puppeteer: https://github.com/GoogleChrome/puppeteer ) when the ecosystem is a bit better (I can't see a way to integrate it in the grunt file easily yet)

**Comment by meiamsome** [comment]
I was working on a potential implementation of headless chrome testing with chrome-mocha here:

https://github.com/meiamsome/p5.js/tree/testing/headless-chrome

However I currently have an issue where on Travis it will always crash at the same place:

https://api.travis-ci.org/jobs/283092554/log.txt?deansi=true

Any ideas?

**Comment by lmccart** [comment]
is webgl supported in headless-chrome?
https://bugs.chromium.org/p/chromium/issues/detail?id=617551

**Comment by lmccart** [comment]
oh I just saw your comments on https://github.com/processing/p5.js/issues/2200 so I guess that isn't the problem

**Comment by meiamsome** [comment]
So, I managed to get it to not crash by using the beta version of chrome, instead it just reports `Error: Error: Error creating webgl context`. Interestingly, I can only get that behaviour locally (Even when running inside one of Travis' docker containers) by using the `--disable-webgl` flag on chrome. Maybe it's disabled automatically on Travis. I might raise an issue over there at some point.

**Comment by meiamsome** [comment]
@lmccart This is not fixed by 74019da, as @Spongman commented on there, we need to remove grunt-mocha and switch to another test runner (grunt-karma, perhaps?). Please re-open this.
