### ISSUE TITLE
Missing delta time for constant velocity

### ISSUE THREAD

**Issue by bugan** [processing/p5.js#2180]
#### Nature of issue?

- [ ] Found a bug
- [x] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [x] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### I was looking the **_draw** method on the core code and I noticed that you have an **frameCount** property. This let me thinking that it would be good to add an **deltaTime** property on the p5 library.

This would be good for anyone that need a constant velocity, acceletarion or time relative app. 

As I was looking the code I found this:

```
var now = window.performance.now();
var time_since_last = now - this._lastFrameTime;
var target_time_between_frames = 1000 / this._targetFrameRate;
```

So, we already calculated the delta time we just need to expose it.

**Comment by Siphonophora** [comment]
Hi, did you take a look at getting this from frameRate()? Looks like that is what you need.   https://p5js.org/reference/#/p5/frameRate

**Comment by rmib200** [comment]
Yes, it isn't implemented yet? This is extremely useful.
