### ISSUE TITLE
Implement image() for webgl mode

### ISSUE THREAD

**Issue by kjhollen** [processing/p5.js#2182]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [x] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Feature enhancement details:

image() only works in 2D mode currently, but it would be great for WEBGL mode, too. I think it could be implemented in a pretty straightforward way using other parts of the API: begin/endShape with vertex, and the p5.Texture cache in the renderer. 

this is a nice self-contained issue and would be great for a new contributor who wants to write some webgl code. see: [WebGL Module Architecture](https://github.com/processing/p5.js/blob/master/developer_docs/webgl_mode_architecture.md) for relevant documentation.

**Comment by bomoko** [comment]
***raises hand***
I'd love to take a swing at this, if nobody else is working on it yet?

**Comment by lmccart** [comment]
go for it!

**Comment by bomoko** [comment]
@kjhollen I've managed to get a sense of what's involved here, and have even managed to bang up a working version (totally throwaway, pasted below) - I was hoping you could point me in the right direction with the texture though.

```
p5.RendererGL.prototype.image = function(image, sx, sy, sw, sh, dx, dy, w, h) {
  texture(image); //  <-- presumably I should be doing this some other way ...
  var iWidth = image.width;
  var iHeight = image.height;

  var sxPerc = sx / iWidth; //TODO: rework var names
  var syPerc = sy / iHeight;
  var sx1Perc = (sx + sw) / iWidth;
  var sy1Perc = (sy + sh) / iHeight;

  this.beginShape();
  this.vertex(dx, dy, 0, sxPerc, syPerc);
  this.vertex(dx + w, dy, 0, sx1Perc, syPerc);
  this.vertex(dx + w, dy + h,0, sx1Perc, sy1Perc);
  this.vertex(dx, dy + h,0, sxPerc, sy1Perc);
  this.endShape(CLOSE);
  return this;
}
```
You'll see that I'm calling `texture()` in the first line of my function to load up the image that gets passed through from the `image()` function in  `src/image/loading_displaying.js`.

I'm pretty sure this isn't the right way of doing this - I was hoping you could give me an idea of what you had in mind in terms of actually loading up the texture here?
I'm not sure where the appropriate place to do it is, I'm sure it's not where I'm currently doing it.

To my mind, it would be good for the image function to behave the same in P2D and WEBGL (as it does with my hack above) - but then, where to load the texture (and how)?

I'm going to carry on digging through the p5.js source to try work it out - but any guidance you could give would be awesome.
Thanks!

**Comment by Siiiimon** [comment]
the `WebGL Module Architecture` link might be borked...

**Comment by lmccart** [comment]
@Siiiimon thanks! updated

**Comment by mohhasbias** [comment]
Is this issue solved?
The status is still open.

**Comment by unjust** [comment]
yea what's the status of this?

**Comment by vedhant** [comment]
If no one is working on this currently, I am willing to contribute to this issue!

**Comment by bomoko** [comment]
Yeah, I'm not sure about the status of this - I submitted a PR (#2211) back in 2017, but nothing came of it. I'm going to close that since things have changed significantly since there form an architecture perspective and open it up for whomever is interested in addressing it.

**Comment by wanbinkimoon** [comment]
this feature is *needed*

**Comment by stalgiag** [comment]
Hi @vedhant work is very welcome on this issue. Do you still want to contribute to it?

**Comment by vedhant** [comment]
@stalgiag Yup certainly!

**Comment by vedhant** [comment]
I'm having a issue using beginShape() with texture().
I have opened up an issue for this. #3606

**Comment by stalgiag** [comment]
@vedhant responded in that issue!

**Comment by vedhant** [comment]
```javascript
var img;
function preload() {
//any image not given in base64 format like data:image/png;base64,iVBORw0KGgoAA....
 img = loadImage('some_image.png');
}

function setup() {
  createCanvas(500, 500, WEBGL);
}

function draw() {
  background(153);
  rotateZ(frameCount * 0.01);
  rotateX(frameCount * 0.01);
  rotateY(frameCount * 0.01);

  texture(img);
  box(200, 200, 200);
}
```
@stalgiag I get an error when i try to render an non base64 image (data:image/png;base64,iVBORw...) using ```texture()```

**Error message**
Uncaught DOMException: Failed to execute 'texImage2D' on 'WebGLRenderingContext': Tainted canvases may not be loaded

**Comment by stalgiag** [comment]
@vedhant I am a bit confused by what you mean. None of the working examples (manual test, reference, unit tests) for `texture()` use base64 images, but you are saying that only base64 images work for you? That error you are getting seems to be a cross-origin request error. Are you [running your sketch on a local server](https://github.com/processing/p5.js/wiki/Local-server)?

**Comment by vedhant** [comment]
@stalgiag thanks! It was a cross-origin request error and I fixed it.
