### ISSUE TITLE
Implement point() for webgl mode

### ISSUE THREAD

**Issue by kjhollen** [processing/p5.js#2184]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [x] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Feature enhancement details:

point() only works in 2D mode currently, but it would be great for WEBGL mode, too.

this is a somewhat self-contained issue and would be great for a new contributor who wants to write some webgl code, but maybe a little more work than some of the other issues I've labeled with level:beginner. see: [WebGL Module Architecture](https://github.com/processing/p5.js/wiki/WebGL-Module-Architecture) for relevant documentation.

**Comment by bomoko** [comment]
Hi, I'd really like to volunteer do this one.
I actually attempted this a little while ago (when working through some or other example processing sketch in Matt Pearson's book and found point wasn't implemented) but stopped when I heard the WebGL layer was being reworked.

**Comment by kjhollen** [comment]
yay! go for it!

**Comment by fractalfrenzy** [comment]
Any update on this?

**Comment by bomoko** [comment]
Hi @fractalfrenzy (and @kjhollen, I suppose :) )
I've fallen a bit behind on this - wasn't as quick a patch as I'd imagined (required quite a bit more reading through the source, and reading about WebGL, than I'd anticipated - but that probably speaks to the lacunae in my own knowledge than the difficulty of the task itself).

I'm still planning on getting to this - but if anyone else wants to have a go, please feel free.

**Comment by kjhollen** [comment]
added in webgl-gsoc-2018!
