### ISSUE TITLE
textureMode() or similar for pixel-based texture coordinates

### ISSUE THREAD

**Issue by kjhollen** [processing/p5.js#2188]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [x] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Feature enhancement details:

Processing has a [textureMode](https://processing.org/reference/textureMode_.html) feature for using image pixel coordinates for u,v texture coordinates instead of the normal 0-1 convention. adding this feature to p5 would make some texturing operations easier for beginners.

this is a small to medium size project for someone with a little experience working with open gl. see the [WebGL Module Architecture](https://github.com/processing/p5.js/wiki/WebGL-Module-Architecture) page on p5 conventions for webgl.

**Comment by Siphonophora** [comment]
A note from looking into this a bit, the documentation for vertex is missing u and v parameters which are supported in the code.

**Comment by aferriss** [comment]
I'm interested in taking a look at this one if nobody else has started with it. Is this a webGL only feature? I know that texture only works in webGL, but the 2d renderer has uv options for vertex(). What purpose do the uv parameters of vertex() serve in non webGL mode?

**Comment by Spongman** [comment]
is the support for vertex texture coordinates that i implemented in my rendering pipeline changes going to be merged?
