### ISSUE TITLE
createSelect allows creation of a select with multiple selection, but they aren't returned from value()

### ISSUE THREAD

**Issue by meiamsome** [processing/p5.js#2193]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other (specify if possible) (DOM)

**Comment by lmccart** [comment]
value is a thin wrapper that returns this.elt.value. for the array of selected options, there's the .selected() method which will return an array for a multiple select element
