### ISSUE TITLE
name appears to be written into the global scope somewhere

### ISSUE THREAD

**Issue by meiamsome** [processing/p5.js#2194]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

I was having issues when using a variable called name in global scope.. Not sure what would cause that? If I have a variable called name in the global scope it is set to "[object Object]"

**Comment by meiamsome** [comment]
Hmm, this appears to be fine actually. I was having issues when using a variable called `name` in global scope.. Not sure what would cause that? If I have a variable called name in the global scope `createInput` returns `"[object Object]"`

**Comment by limzykenneth** [comment]
For me `name` is an empty string. No idea how to hunt it down though... 😞

**Comment by meiamsome** [comment]
I feel rather dumb, this is of course the `window.name` property, existent on all pages: https://developer.mozilla.org/en-US/docs/Web/API/Window/name

**Comment by limzykenneth** [comment]
welp...I never knew that, dumb +1 for me
