### ISSUE TITLE
Incorrect return type in docs for keyIsDown()

### ISSUE THREAD

**Issue by dhowe** [processing/p5.js#2195]
Should be boolean

![image](https://user-images.githubusercontent.com/737638/30731736-c20ff4c8-9fa1-11e7-8e11-00f3744de690.png)

**Comment by jmalk** [comment]
Looking at the [doc comment in the source](https://github.com/processing/p5.js/blob/master/src/events/keyboard.js#L327), the return type is Boolean. Perhaps the website is out of date with the source?

**Comment by meiamsome** [comment]
@jmalk I see the same thing on locally built docs on the new source - interestingly the docs/reference/data.json file shows the correct return details - so an issue with the templating? Possibly related to #2171 ?
