### ISSUE TITLE
Tests take a very long time in Chrome

### ISSUE THREAD

**Issue by meiamsome** [processing/p5.js#2201]
For some reason, the tests in p5.js currently take about 200s to run in Chrome on my PC, whereas the same tests take 6s on Firefox.

**Comment by kaininc** [comment]
That's weird

**Comment by sakshamsaxena** [comment]
A little more info here would be great. Specifically, OS, and the number of total tests passed and failed in both browsers. You think some were skipped due to some incompatibility/uncertainty in FF ?

**Comment by meiamsome** [comment]
This seems to be fine for me now - Chrome is  61.0.3163.100.
This was at the same time I posted another issue stating Chrome as 59.0.3071.86
So therefore, I can only assume it was solved in Chrome 61?
