### ISSUE TITLE
We should consider adding a lerpAngle

### ISSUE THREAD

**Issue by meiamsome** [processing/p5.js#2202]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [x] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [x] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

To lerp around to an angle in the most efficient way (i.e. using the wrapping when appropriately)

**Comment by limzykenneth** [comment]
I don't fully understand this, do you mean lerping but with built in modulo?

**Comment by meiamsome** [comment]
Yeah, something along the lines of (In DEGREES mode)
`lerpAngle(300, 60, 0.75) // 30 instead of 120`

Perhaps also include a modulo argument for advanced users, but by default use the angle mode.

**Comment by lmccart** [comment]
this makes sense to me, but I feel might be beyond the scope of the api right now. I'd really like to focus efforts on getting what we have in working order and fully documented.

**Comment by grilly86** [comment]
this worked for me: 
```
function lerpAngle(a,b,i) {
  var va = p5.Vector.fromAngle(a)
  var vb = p5.Vector.fromAngle(b)
  return p5.Vector.lerp(va,vb,i).heading();
}
```
