### ISSUE TITLE
reference doc for arc() doesn't explain modes OPEN, PIE, CHORD

### ISSUE THREAD

**Issue by makeyourownalgorithmicart** [processing/p5.js#2203]
The reference documentation for arc() at [https://p5js.org/reference/#/p5/arc](https://p5js.org/reference/#/p5/arc) doesn't explain the modes, OPEN, PIE, CHORD.

The examples show OPEN but the parameter list only lists PIE and CHORD. 

None are explained. The examples look the same, so not illustrating the modes

**Comment by meiamsome** [comment]
The reference image colours are currently broken as a consequence of #2156, and should be fixed whenever the documentation site is updated. I do agree a description update here would be useful.

**Comment by Siphonophora** [comment]
I can flesh out the documentation while working on #2181

**Comment by eJohnstonePhd1991** [comment]
Hi all.
I'm looking to make my first contribution to the project. Perhaps I could update the documentation and then @Siphonophora can update it when the WEBGL extension of it is live?

**Comment by lmccart** [comment]
fixed with https://github.com/processing/p5.js/pull/2346
