### ISSUE TITLE
please try to make references more informative. i wasn't really able to understand the blue function under color section. (in p5.jsj).

### ISSUE THREAD

**Issue by GagandeepSingh1357** [processing/p5.js#2205]
#### Nature of issue?

- [ ] Found a bug
- [x] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 
- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

**Comment by outofambit** [comment]
hey @GagandeepSingh1357 did you mean the function for setting the blue value of an existing color? or to get the current blue value out of a color? (`_getBlue()` or `setBlue()`). thank you for filing this!

**Comment by GagandeepSingh1357** [comment]
i actually didn't understood the whole concept behind the blue function. i feel the data or info provided in the reference is a little limited 
![blue](https://user-images.githubusercontent.com/32274872/31048686-56cabb30-a5d7-11e7-945f-c8a62910c682.PNG)

**Comment by lmccart** [comment]
@GagandeepSingh1357 each color is defined as a [combination of a red, green, and blue value](https://www.w3schools.com/colors/colors_rgb.asp). the blue() function returns the blue number in that combo of three, while red() and green() respond the red and green values.

**Comment by lmccart** [comment]
this tutorial also might be helpful for you: https://p5js.org/learn/color.html
