### ISSUE TITLE
WebGL - Ellipse should not take detailY as an arg

### ISSUE THREAD

**Issue by Siphonophora** [processing/p5.js#2210]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: Current master branch
- Steps to reproduce this:
The ellipse primitive takes a detailX and detailY args. detailX determines the number of verticies in the ellipse. If detailY == 1 then the primitive is correctly rendered. For each value of detailY above 1, an entire set of redundant verticies/faces is added. 

I can fix that by fixing detailY = 1, but wanted to check that I am not missing some reason why the redundant geometry would be desired. 

Also, should the vertex locations be rounded at all (or is webgl going to automatically weld these together)? I noticed that the the vertices at the beginning and end of the ellipse didn't exactly match, similar to below
```
vector(200, 0, 0)  
vector(200,-4.2e-10, 0);

```

**Comment by mlarghydracept** [comment]
Hi! Thanks for looking into this. I don't think any of the code that constructs the ellipse primitive has been looked at in a long time. I agree that the detailY sounds unnecessary and rounding would be nice even if only just for a cleaner understanding of the ellipse construction.

**Comment by Spongman** [comment]
this was fixed by #2473
