### ISSUE TITLE
Potential logic error in Line() function's parameter tests

### ISSUE THREAD

**Issue by bomoko** [processing/p5.js#2212]
#### Nature of issue?

- [X] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [X] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: v0.5.14

I think I've come across a small logic error in the WebGL line code. 

Currently, the function has a check of its parameters (just pasting the entire function here, it's teensy):

```
p5.RendererGL.prototype.line = function(x0,y0,z0,x1,y1,z1) {
  if (typeof x0 !== 'undefined' ||
      typeof y0 !== 'undefined' ||
      typeof z0 !== 'undefined' ||
      typeof x1 !== 'undefined' ||
      typeof y1 !== 'undefined' ||
      typeof z1 !== 'undefined')
  {
    this.beginShape();
    this.vertex(x0, y0, z0);
    this.vertex(x1, y1, z1);
    this.endShape();
  }
  return this;
};
```
The check will pass if _any_ of the parameters are _not_ undefined. I _think_ that what we actually want is for the line to be drawn only if we have all parameters -- that is, I think that what makes more sense here are ANDs and not ORs.

The problem with not checking that _every_ parameter is defined is that if someone calls this like one might call the 2D version, i.e. `line(x, y, x1, y1)` then the first vertex is going to be loaded with x1 as its z value.
Step debugging a call to `line()` in this manner confirms that this is what happens.

**Comment by bomoko** [comment]
Closing - have a better solution ...

**Comment by bomoko** [comment]
Apologies for closing then reopening the issue - I had an idea for an enhancement, then I thought it was probably better to deal with this directly, first.

**Comment by lmccart** [comment]
fixed with https://github.com/processing/p5.js/pull/2213
