### ISSUE TITLE
Support hex color strings in color functions

### ISSUE THREAD

**Issue by kadamwhite** [processing/p5.js#222]
Given the primacy of hex color values on the web, I'd like to propose enhancing `fill`, `background` and the other color-related methods to be able to take a hex value string in addition to the RGB color values or color array. This will make it easier to integrate other JS color libs into p5, because almost all of them are able to spit out hex values one way or another.

Example:
```js
// same:
fill( '#45ab31' );
fill( 69, 171, 49 );
```

**Comment by lmccart** [comment]
:))
