### ISSUE TITLE
Support static mode

### ISSUE THREAD

**Issue by sofian** [processing/p5.js#2220]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [x] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [x] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [x] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### New feature details:

P5.js does not currently support "static" mode which allows sketches that do not contain functions setup() and draw() to work.

There was a discussion about this on the old repository:
https://github.com/processing/p5.js-editor/issues/104

Static mode is an interesting feature when introducing students to Processing. I wonder if it would even be possible to make it work but I'd be happy to give it a try if this is something you believe would be a benefit. I personally feel it makes many students feel like it is an empowering feature tof Processing especially for beginners, as it allows to build confidence early on. I usually begin my classes with an empty sketch and show them that this still produces a gray-background canvas, and we build from there.

**Comment by lmccart** [comment]
yes, a good point. we also discussed it at length [here](https://github.com/processing/p5.js/issues/113) and [here](https://github.com/processing/p5.js/issues/158). as of now we would like to stick by the decision not to support non-setup/draw mode, but an issue could be opened on the forthcoming web editor if this is of interest.

**Comment by sofian** [comment]
I have opened an issue on P5.js editor: https://github.com/processing/p5.js-web-editor/issues/448
