### ISSUE TITLE
mouse pressed function didn't execute

### ISSUE THREAD

**Issue by GagandeepSingh1357** [processing/p5.js#2223]
#### Nature of issue?

- [x] Found a bug
- [x] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [x] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 
- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

**Comment by GagandeepSingh1357** [comment]
plz check the last mouse pressed function and let me know the error in the program!!
the function wasn't executing in my PC.
***
var a=3;
var b=3;
var x=3;
var y=3;
function setup() {
  createCanvas(1080,720)
  
}

function draw() {
	background(0,0,50);
         stroke(0,0,0);
	fill(255,170,0);
         ellipse(445,350,a,b);
         a=a+50,b=b+50;
        noStroke();
         fill(0,0,30);
          rect(390,330,95,40);
         rect(350,230,40,250);
         rect(390,230,150,40);
         rect(390,440,150,40);
         fill(233,0,0);
        }
 function mousePressed(){
	fill("lightgreen");
         ellipse(445,350,x,y);
          x=x+30,y=y+30;}

**Comment by meiamsome** [comment]
Your draw code will immediately overwrite the rendering done in `mousePressed`.

Instead you can include the code in your draw based on the `mouseIsPressed` variable:
```
var a=3;
var b=3;
var x=3;
var y=3;
function setup() {
  createCanvas(1080,720)
}

function draw() {
  background(0,0,50);
  stroke(0,0,0);
  fill(255,170,0);
  ellipse(445,350,a,b);
  a=a+50,b=b+50;
  noStroke();
  fill(0,0,30);
  rect(390,330,95,40);
  rect(350,230,40,250);
  rect(390,230,150,40);
  rect(390,440,150,40);
  fill(233,0,0);
  if(mouseIsPressed) {
    fill("lightgreen");
    ellipse(445,350,x,y);
    x=x+30,y=y+30;
  }
}
```

**Comment by lmccart** [comment]
thanks @meiamsome!
