### ISSUE TITLE
Documentation round function vs. round constant.

### ISSUE THREAD

**Issue by sjorsvanheuveln** [processing/p5.js#2233]
There's seems to be no documentation about the round function, but only on the round constant. If I click in round() in the reference, I get the documentation for the constant.

**Comment by meiamsome** [comment]
Note that the `round` method appears to have documentation but the url for `ROUND` and `round` are the same, and so one of them is effectively hidden.

This is possibly a bug for the website - https://github.com/processing/p5.js-website but I am unsure

**Comment by sjorsvanheuveln** [comment]
Ok, I'll post it there. Consider this closed here!
