### ISSUE TITLE
sketch.js is empty

### ISSUE THREAD

**Issue by chrisspurgeon** [processing/p5.js#2239]
#### Nature of issue?

p5.js/lib/empty-example/sketch.js is empty. I believe it should contain this...

```
function setup() {
  // put setup code here
}

function draw() {
  // put drawing code here
}
```

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other  -- Code Download

**Comment by lmccart** [comment]
hehe ;) 
<img width="785" alt="screen shot 2017-10-03 at 10 53 49 pm" src="https://user-images.githubusercontent.com/191056/31161709-cae5b26e-a88d-11e7-8013-d571e1003d5e.png">
