### ISSUE TITLE
WEBGL renderer is never added to _elements - canvas not removed

### ISSUE THREAD

**Issue by meiamsome** [processing/p5.js#2241]
#### Nature of issue?

- [X] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Other (specify if possible)

I believe this renderer should be pushed onto `this._elements` when it is created so that it can be removed correctly when `p5.remove` is called later. Also, should the P2D default renderer be removed?

**Comment by lmccart** [comment]
fixed with https://github.com/processing/p5.js/commit/2bb7aa500776dfdf768da1409b256235846577a1
