### ISSUE TITLE
mozImageSmoothingEnabled is deprecated - console warning on Firefox.

### ISSUE THREAD

**Issue by RoseCrime** [processing/p5.js#2242]
#### Nature of issue?

- [#] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [#] Other (Shape,smooth() and noSmooth() functions).

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [#] Desktop/Laptop
- [ ] Others (specify if possible)

- p5.js version: p5.js v0.5.14 August 28, 2017 ;
- Web browser and version: 56.0 Firefox (64-bit),Firefox Developer Edition 57.0b5 (64-bit).
- Operating System: 
- Steps to reproduce this:

I'll include my code if it's necessary, but problem is simple enough.

FireFox console shows warning "Use of mozImageSmoothingEnabled is deprecated. Please use the unprefixed imageSmoothingEnabled property instead." in P5.js.

**Comment by meiamsome** [comment]
This was just fixed in #2228 but hasn't been released yet :)

**Comment by RoseCrime** [comment]
Good news :)

**Comment by michael-v-bloom** [comment]
Hi there, I know this topic is old, but I'm having the exact same issue on Firefox v108.0.2 (64-bit) with the latest p5.js version ( v1.5.0 ) ... Should I open a new issue/ticket for this, or we can continue here?

Thanks in advance!
