### ISSUE TITLE
p5.prototype.directionalLight takes unused parameter

### ISSUE THREAD

**Issue by Spongman** [processing/p5.js#2246]
p5.prototype.directionalLight = function(v1, v2, v3, a, x, y, z);

but the parameter `a` is never used.

also, the docs for this method should be split into separate overrides to indicate the valid permutations of its parameters. for example, parameter `x` is required, but `v2` and `v3` are optional... there's no indication (without looking at the code) how it resolves this.

**Comment by lmccart** [comment]
same with pointLight

**Comment by lmccart** [comment]
fixed with https://github.com/processing/p5.js/pull/2300/files
