### ISSUE TITLE
validateParameters() is too slow

### ISSUE THREAD

**Issue by Spongman** [processing/p5.js#2247]
if you run a `color(0,0,0)` under chrome's profiler, you'll see that `validateParameters()` takes ~95% of the time.

![image](https://user-images.githubusercontent.com/1088194/31303405-d115b432-aac1-11e7-93a4-cad9e3900dbb.png)

**Comment by lmccart** [comment]
for improved performance, it is recommended to use p5.min.js, or to set `p5.disableFriendlyErrors = true;`

https://github.com/processing/p5.js/wiki/Friendly-Error-System

**Comment by modermo** [comment]
I noticed this myself. Will using .min automatically set `disableFriendlyErrors` to `true`?

**Comment by lmccart** [comment]
@modermo yes

**Comment by modermo** [comment]
Awesome, thanks. I've noticed an enormous performance improvement from that alone.

**Comment by Spongman** [comment]
try this, also:
````
var docCache = {};
...
  var arrDoc = docCache.hasOwnProperty(func) ? docCache[func] : (docCache[func] = lookupParamDoc(func));
````
