### ISSUE TITLE
createImage and translate not working correclty on mac and windows 

### ISSUE THREAD

**Issue by GiorgioMartini** [processing/p5.js#2249]
#### Nature of issue?

- [ x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [x ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x ] Other (Translate and createImage)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x ] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 
- Web browser and version: on my mac laptop:  Google Chrome | 60.0.3112.113 (Official Build) (64-bit)
On my pc: Google Chrome	61.0.3163.100 (Offizieller Build) (64-Bit) (cohort: Stable)

- Operating System: on mac el capitan 10.11.6, on windows windows 10
- Steps to reproduce this:   create an image with createImage() and use some transformations and render the created image 0n the main canvas... the result looks good on windows.. but on mac its not, it looks blurry and not centered as it should but at the bottom...

here is the codepen.. which looks good on windows but wrong in mac... https://codepen.io/giorgiomartini/pen/LzQeGQ?editors=0010

```javascript
let vignette,
    textShadow,
    wordsUppercase
   
const canvasX = 300,
      canvasY = 500
     
function setup(){
  colorMode(HSB, 360) 
  createCanvas(canvasX,canvasY)
  textShadow = createGraphics(canvasX, canvasY)
}

function returnRandomFromArray(array) {
  return array[Math.floor(Math.random() * array.length)]
}

function mouseClicked(){
    blendMode(BLEND)
    const colsArray = randomColor({luminosity: 'light', format: 'hsl',count: 5}) 
    background(colsArray[0])
    translate(width/2, height/2)
    drawTextShadow()
    image(textShadow, -width/2,-height/2);
}

function returnArrFromHslColor(stringInHsl){
  const tono = color(stringInHsl),
        h =  hue(tono),
        firstPartOfSat = stringInHsl.substring(stringInHsl.indexOf(",") + 1),
        satArray = firstPartOfSat.split(","),
        s = parseInt(satArray[0]),
        l =  lightness(tono)  
  return [Math.round(h),Math.round(s),Math.round(l)]
}

function drawTextShadow(someWord) {
  textShadow.clear()
  textShadow.translate(width/2,height/2)   
  textShadow.textSize(60)
  textShadow.fill(0)
  textShadow.textAlign(CENTER)
  textShadow.rectMode(CENTER)
  textShadow.textFont('Passion One')
  textShadow.strokeWeight(10)
  textShadow.text(   Math.random().toString() , 0,canvasY/2.3,canvasX/1.5,canvasY)
  textShadow.translate(-width/2,-height/2) 
}
```

**Comment by lmccart** [comment]
this is related to https://github.com/processing/p5.js/issues/2077 so we will continue work on it over there.
the difference between mac and pc is probably the pixel density of the screen. if you add this line as the first in setup, the image looks correct: ` pixelDensity(1);`

**Comment by GiorgioMartini** [comment]
Awesomw thanks!
