### ISSUE TITLE
Blur not working on createImage() err: Cannot read property 'getContext' of undefined

### ISSUE THREAD

**Issue by GiorgioMartini** [processing/p5.js#2253]
#### Nature of issue?

- [x ] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [x ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [x ] Mobile/Tablet (touch devices)
- [ ] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.5.2/p5.min.js
- Web browser and version: 61.0.3163.100 (Official Build) (64-bit)
- Operating System: Mac os sierra 10.12.6
- Steps to reproduce this:

When trying to use the filter function in an image created with createImage() i get the following error: Cannot read property 'getContext' of undefined

Here is a codpen, if you uncomment line 36.. and click on the canvas the error comes..
https://codepen.io/giorgiomartini/pen/LzQeGQ?editors=0010

Code:

let textShadow
   
const canvasX = 300,
      canvasY = 500
     
function setup(){
  pixelDensity(1)
  colorMode(HSB, 360) 
  createCanvas(canvasX,canvasY)
  textShadow = createGraphics(canvasX, canvasY)
}

function returnRandomFromArray(array) {
  return array[Math.floor(Math.random() * array.length)]
}

function mouseClicked(){
    background(255)
    blendMode(BLEND)
    translate(width/2, height/2)
    drawTextShadow()
    image(textShadow, -width/2,-height/2);
}

function drawTextShadow(someWord) {
  textShadow.clear()
  textShadow.translate(width/2,height/2)   
  textShadow.textSize(60)
  textShadow.fill(0)
  textShadow.textAlign(CENTER)
  textShadow.rectMode(CENTER)
  textShadow.textFont('Passion One')
  textShadow.strokeWeight(10)
  textShadow.text(   Math.random().toString() , 0,canvasY/2.3,canvasX/1.5,canvasY)
  textShadow.translate(-width/2,-height/2) 
  textShadow.filter(BLUR,3);
}

**Comment by limzykenneth** [comment]
Hi @GiorgioMartini, the p5.js version you used is rather old, can you try switching it out to the latest 0.5.15 and if the problem persist, let us know? Thanks!

**Comment by GiorgioMartini** [comment]
duh!  somehow i had an old versiom.. yup that worked!  :) 👍
