### ISSUE TITLE
Implement Path Interpolation for animation and custom shapes.

### ISSUE THREAD

**Issue by mathacka** [processing/p5.js#2254]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [x] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [x] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### New feature details:

Implement 2D functions for a linear, quadratic, and cubic interpolation by percentage to calculate animation paths or have precise control for defining a custom shape.

The code I'm thinking of is based on code from this site:

[https://stackoverflow.com/questions/17083580/i-want-to-do-animation-of-an-object-along-a-particular-path](https://stackoverflow.com/questions/17083580/i-want-to-do-animation-of-an-object-along-a-particular-path)

given starting, ending, and control points (if necessary), each function would return a 2D object {x:X,y:Y} representing a point interpolated by a percentage going from 0 to 1 (incremented by developer/user).

and would have the form "( return point {x:x, y:y} ) getQuadraticBezierPathPoint2D(startX, startY, controlX, controlY, endX, endY, percent)"

also:

getLinearPathPoint2D
getCubicBezierPathPoint2D

together these three could make just about any necessary 2D path from one point to another, even in combination.

**Comment by limzykenneth** [comment]
I think this can be useful for creating sophisticated animations. However, it may not be best to include it in the core library as we want to avoid bloating the library too much. What can be done instead is to make this into an addon library, some info on how to create that can be found [here](https://github.com/processing/p5.js/wiki/Libraries).

**Comment by mathacka** [comment]
thanks!
