### ISSUE TITLE
p5 sketch renders in editor preview window but not in full screen viewer

### ISSUE THREAD

**Issue by jenagosta** [processing/p5.js#2256]
Hello,
My p5 sketch renders in the alpha editor viewer but not in the Full Screen viewer. It is probably a simple fix, I just can't figure it out.

Sketch: 
http://alpha.editor.p5js.org/jenagosta/sketches/ByVARkj3W

Full Screen:
http://alpha.editor.p5js.org/full/ByVARkj3W

Any ideas? Thanks for your thoughts.

#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [x] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 
- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

**Comment by limzykenneth** [comment]
Hi @jenagosta, this is a known bug for the editor, see this issue https://github.com/processing/p5.js-web-editor/issues/449. You can follow the progress there.

**Comment by jenagosta** [comment]
Thank you! Will do.
