### ISSUE TITLE
grunt release-p5 task not creating draft release

### ISSUE THREAD

**Issue by lmccart** [processing/p5.js#2258]
all other tasks seem to work, and a [new tag version gets posted](https://github.com/processing/p5.js/releases), but the release draft does not get made. I've tried two versions 0.5.15 and 0.5.16 that both failed this step. I'm not sure what changed since 0.5.14, I haven't looked into it yet..

@sakshamsaxena any ideas?

**Comment by sakshamsaxena** [comment]
Were the console messages any helpful? Or any changes in env variables ? The draft process is essentially a simple HTTP request to github api, so the probable causes would lie around it, mainly failed auth or something broke while uploading

**Comment by himanshuc3** [comment]
I want to start contributing to p5js. Can anyone list languages/technology used so I can go up and running quickly.
