### ISSUE TITLE
p5.prototype._registeredMethods is a memory leak

### ISSUE THREAD

**Issue by Spongman** [processing/p5.js#2259]
if, like `test/test-minified.html`, you create multiple `p5` instances on a single page, the p5.prototype._registeredMethods.remove array quickly grows very large resulting in a memory leak (it's holding onto those p5 instances via those closures), and the subsequent remove() calls take progressively longer and longer, having to iterate through all those registered functions.

**Comment by meiamsome** [comment]
Aha, excellent!

I was running into something that looked like a resource leak while I was working on trying to get headless chrome to work on Travis, and this is that leak!

I have a fix I'll PR in a second

**Comment by lmccart** [comment]
hey @meiamsome this looks right, does it fix the leak? do you want to PR against this branch if so?
