### ISSUE TITLE
[feature request] i18n for website

### ISSUE THREAD

**Issue by swirly** [processing/p5.js#2260]
#### New feature details
First of all, congrats for all the work already done
two years ago, I asked if a internationalization was in project. I was told it was on the todo list, with high expectations.
in summer 2016, mayaman posted some things on i18n version of site. But his work, expected to come in fall, was never integrated to p5js website
Is there any new or progress on internationalization ? 
I would gladly translate documentation in french, but you need a framework to include that.
TIA for your answer

**Comment by meiamsome** [comment]
Hello!

There is already a Spanish translation here: https://p5js.org/es/

Translation of the website is done on the p5.js website repository here: https://github.com/processing/p5.js-website

Hopefully that helps?

**Comment by lmccart** [comment]
yes, we're getting close to releasing the spanish version. our plan is to focus on one language and learn what we need to in terms of making sure we have the structure to maintain and support it. then we will begin adding other languages. until then, you are most welcome to translate materials and share ad hoc, we will help amplify through social media.
