### ISSUE TITLE
[very minor] [documentation] Missing link in development checklist 

### ISSUE THREAD

**Issue by inderpreetsingh** [processing/p5.js#2271]
I hope this is right place to report it. I wanted to start exploring development of p5 a bit and found a wrong link on home page for tutorials (which i fixed, yay!!!) but then on development page (https://github.com/processing/p5.js/wiki/Development) the link to development checklist is broken and I couldn't find the right link. Can anyone help?

#### Nature of issue?

- [x] Found a bug

#### Most appropriate sub-area of p5.js?

- [x] Other (Documentation)

**Comment by limzykenneth** [comment]
I think it may have been removed but the wiki was not updated. There isn't really a checklist right now as far as I know, just lots of issues 😉

**Comment by lmccart** [comment]
@limzykenneth is correct. I've just updated the wiki. thanks!
