### ISSUE TITLE
PWA (progressive web app) with p5s

### ISSUE THREAD

**Issue by scls19fr** [processing/p5.js#2273]
Hello,

I'm new to p5js (I'm not very experienced with web development)
My goal is to create an application that will be able to run offline on iOS and Android devices and look like a native app (or at least quite similar to a native app).
I was looking for [progressive web app](https://en.wikipedia.org/wiki/Progressive_web_app) example with p5s but I haven't been able to found one.
Maybe you can send me some tips, pointers...

I also wonder if/how p5s can deal with [Responsive web design (RWD)](https://en.m.wikipedia.org/wiki/Responsive_web_design).

Kind regards

**Comment by lmccart** [comment]
the github issues here are a good place for bugs and issues with the p5.js library itself. for questions about writing your own code, tests, or following tutorials, the [forum](https://forum.processing.org/two/) is the best place to post. thanks!

**Comment by scls19fr** [comment]
https://forum.processing.org/two/discussion/24657/progressive-web-app-pwa-and-p5js
