### ISSUE TITLE
can't get the property "event.scale" from android device when use method "touchMoved(event).

### ISSUE THREAD

**Issue by igouz** [processing/p5.js#2275]
can't get the property "event.scale" from android devices when use method "touchMoved(event).
but ios devices webview can get .
somebody can tell me the same property on android devices.
I'am so sorry ,My english is poor.

**Comment by Zalastax** [comment]
p5 is forwarding the [toucmove event](https://developer.mozilla.org/en-US/docs/Web/Events/touchmove) from Chrome which doesn't seem to have a scale property. Maybe you can simulate something using https://p5js.org/reference/#/p5/touches or combine p5 with http://hammerjs.github.io/?
Good luck!

**Comment by igouz** [comment]
tks a lot
