### ISSUE TITLE
doubleClicked() function not being called

### ISSUE THREAD

**Issue by limzykenneth** [processing/p5.js#2276]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [x] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 
There seem to be a problem with the implementation of the `doubleClicked` function which causes it to not call the user defined function at all and looking into the source, it seems to have some mistakes when calling the user defined function and also not being registered in `core.js` as part of the events list as well.

I'll look into this today.

- p5.js version: 0.5.16
- Web browser and version: All latest Safari, Chrome and Firefox as of (20 October 2017)
- Operating System: Mac OS X 10.13
- Steps to reproduce this: Present on reference page of [doubleClicked](https://p5js.org/reference/#/p5/doubleClicked)

**Comment by lmccart** [comment]
fixed with #2277
