### ISSUE TITLE
Regular polygon function needs implementing

### ISSUE THREAD

**Issue by cursorial** [processing/p5.js#2280]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [x] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [X] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [X] Desktop/Laptop
- [ ] Others (specify if possible)

#### Feature enhancement details:
We have basic functions to draw shapes (ellipse, triangle, rect), although to draw regular polygons we have to find the example in the docs and then implement that function in our own code.

It would be nice to have a function that did this for us provided by p5.js.

I've implemented this functionality and made a pull request: https://github.com/processing/p5.js/pull/2281

**Comment by lmccart** [comment]
hi @cursorial, thanks for this. I think this is a bit beyond the scope of the api right now.. we are discussing some changes if you want to join in over here: https://github.com/processing/p5.js/issues/2305. but we probably won't add polygon anytime soon.
