### ISSUE TITLE
strokeWeight too thick in ortho camera

### ISSUE THREAD

**Issue by shaunlebron** [processing/p5.js#2283]
The [`ortho()`](https://p5js.org/reference/#/p5/ortho) example page shows the following:

![ortho](https://user-images.githubusercontent.com/116838/31859644-2a202d00-b6d4-11e7-9d0b-8f149cb8ef87.gif)

**Comment by mlarghydracept** [comment]
I think changing the stroke weight in the example is a good short-term solution but I think in the long run we should shoot to change the orthographic rendering so that expected behavior for stroke-weighting is the same across both camera styles. I will start looking into it.
