### ISSUE TITLE
color in array

### ISSUE THREAD

**Issue by ronraisch** [processing/p5.js#2285]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [x] New feature request

#### Most appropriate sub-area of p5.js?

- [x] Color

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: < web editor >
- Web browser and version: < chrome >
- Operating System: <windows 7>
- Steps to reproduce this:
function randomColors(){
return [randon(255),randon(255),randon(255)];
}
fill(randomColors(),100);
>

#### Feature enhancement details:
every time you use the rgb color system you can use an array, but if you want to add some alpha to the color, it won't work with an array, only with three numbers like useal. it's just ignoring the alpha and color it normally. (it took me around two hours to relieze that in my code, it got me crazy lol).

**Comment by lmccart** [comment]
this is the correct behavior. in the documentation, there is an entry for
`fill(values)` where values is defined as "Number[]: an array containing the red,green,blue & and alpha components of the color"
while there is no entry for `fill(values, alpha)`
