### ISSUE TITLE
loadJSON in draw()?

### ISSUE THREAD

**Issue by wjmoner** [processing/p5.js#2289]
#### Nature of issue?

- [ x ] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ x ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [ x ] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

Would love some help on this! 

I can't seem to allow for p5js to poll a data source in real time. I've been able to connect to the OpenWeatherMap API and get a weather data object the first time, but I can't get it to update the JSON data using the same method using JSON callbacks. None of the p5 example code shows samples using draw(), only setup() or without the loop. 

OpenWeatherMap API limits to 60 calls per minute, and I can hammer it and receive data manually. 

Thanks, friends.

- p5.js version: p5.js v0.5.11 June 01, 2017
- Web browser and version: Google Chrome	61.0.3163.100 (Official Build) (64-bit)
Revision	57c9d07b416b5a2ea23d28247300e4af36329bdc-refs/branch-heads/3163@{#1250}
OS	Mac OS X
JavaScript	V8 6.1.534.41
- Operating System: Mac OSX
- Steps to reproduce this:

Gist here:
<https://gist.github.com/wjmoner/779122898d7b14741c44d0caf49bf9e2>

#### Error Messages:

_I know this means that the object is undefined, meaning that the variable has been rewritten but is not retrieving the data on the second call. I'm wondering whether (or how) to add a delay to this. I paused the loop until the callback was able to execute, but that didn't seem to work._

sketch.js:49 Uncaught (in promise) TypeError: Cannot read property 'name' of undefined
    at weatherUpdate (sketch.js:49)
    at p5.min.js:7
    at p5.min.js:7
    at <anonymous>

**Comment by lmccart** [comment]
I think you're trying to poll the weather data too frequently. If you put it in draw, that means you are asking the url for data 60times / second which is 60x the rate limit of the OWM API.

I'd suggest using setTimeout() to make the call every few seconds:
```javascript
setTimeout( function() {
  loadJSON(url, weatherUpdate);
}, 5000);
```

The data in OWM is only updated every 2 hours for the free plan anyway. http://openweathermap.org/price

**Comment by meiamsome** [comment]
So, there are a few things which have accumulated to the result that you're getting. Here's a small explanation of some of them:

1) `loadJson` returns immediately - I think you're assuming that it will pause execution until the request is done but it does not.
2) `noLoop` and `loop` do not pause execution of the current draw loop, they simply prevent/allow the next loop to run. By calling `noLoop` and then `loop` you are not pausing drawing.

Your method of limiting calls to every 5 seconds should be working fine & I do not see your undefined issue in the callback.

In addition to @lmccart's suggestion perhaps `setInterval` may be more applicable?

**Comment by lmccart** [comment]
ah yes setInterval is correct! thank you @meiamsime

**Comment by wjmoner** [comment]
Thanks for your help. 

@meiamsome yes, the `setInterval` method will work for re-polling the data. The undefined issue wasn't coming from the callback, but I think @lmccart makes a great point that my requests were 60*60 in the draw() loop. Thanks for the clarification on noLoop() and loop().

@lmccart thanks, too, for the note about OWM's update for data. We're using them as an example, but in a scenario where we would have an API partner that allows for realtime updating -- or someone who is using polling intervals -- I want to be able to have that code working, and your help is valuable for that.
