### ISSUE TITLE
loadJSON() with array

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js#2290]
Working with students I noticed that when loading a JSON array with `loadJSON()`, the result is actually an "object" with numeric keys and no `.length` property. For example:

```json
[
    "apple", "pear", "mango"
]
```

```javascript
let data;
function preload() {
  data = loadJSON('test.json');
}
function setup() {
  console.log(data);
}
```

`data.length` returns `undefined` and the result is an object, not an array. 

<img width="581" alt="screen shot 2017-10-23 at 11 06 02 am" src="https://user-images.githubusercontent.com/191758/31896604-337e4a62-b7e2-11e7-883e-3d2718dbe81a.png">

These can be fixed by reformatting the JSON but some APIs return only an array. Is this a p5.js bug or something deeper in JS?

**Comment by meiamsome** [comment]
See #2207

**Comment by shiffman** [comment]
Oh, thanks! I only searched "open" issues to see if this had been posted already! Lesson learned!

**Comment by Tablelayout-unwrapped** [comment]
take a look at this note https://javascripter.space/questions/reorganizing-json-arrays-with-javascript
