### ISSUE TITLE
value returned by soundFile.currentTime() differs on windows and osx

### ISSUE THREAD

**Issue by aferriss** [processing/p5.js#2298]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other  - Sound

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- Web browser and version: Chrome
- Operating System: Windows and OSX
- p5.js version: 0.5.11
- Steps to reproduce this:
https://alpha.editor.p5js.org/aferriss/sketches/HybUuLnaW

I noticed on a student's computer that they were getting different values for soundFile.currentTime() when on windows and mac. I'm not sure how to test for this other than to have two machines in front of you. Essentially they were writing code like

```
if(sound.currentTime() > 10){
 // do something
}
```
And noticed that the timing was off when they switched to a different computer / OS. Wondering if someone else can replicate this issue.

**Comment by lmccart** [comment]
This issue was moved to processing/p5.js-sound#226
