### ISSUE TITLE
Use existing dom elements with p5 

### ISSUE THREAD

**Issue by oth-aw** [processing/p5.js#2299]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [x] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] DOM

#### New feature details:

It would be fine to use existing dom elements together with p5. 
Even though `select("#elem")` is working fine for div-Elements, it does not return a p5.Element.
When an existing element is selected, it does not provide any p5 features like listeners ( e.g. `mousePressed()` or `changed()`...)

Maybe it is possible to define a method like `registerElement(elem)`  or `new p5.Element(select(elem))` to equip existing elements with p5 features.

Here is my workaround for elements like radio-buttons:
```
function registerElement(id) {
  var elem = {};
  var tmp = createRadio();
  elem.elt = document.querySelector(id);
  elem.value = tmp.value;
  elem._events = tmp._events
  elem.changed = tmp.changed;
  tmp.remove();
  return elem;
}

function setup() {
  var radio = registerElement("#existing-radio-button");
  radio.changed(my_function);
}
```

**Comment by limzykenneth** [comment]
`select()` should return a p5.Element and should be able to take the events functions by default. Can you check you are using the latest version of p5.js? If the problem persist then there may be some bug in the library so do let us know.

**Comment by oth-aw** [comment]
I have the latest version v0.5.16. The problem is that `.value()` is not working with radio buttons.
I guess it is a bug.
Here is an example code where `radio.value()`is undefined:
```
<!DOCTYPE html>
<html>
<head>
<script src="../p5.min.js"></script>
<script src="../addons/p5.dom.min.js"></script>
<script>
function setup() {
  /** working
  radio = createRadio();
  radio.option("black");
  radio.option("white");
  */
  // not working
  radio = select("#radios");
  radio.changed(myCheckedEvent);
}
function myCheckedEvent() {
    console.log("Checking! value: "+radio.value());
}
</script>
</head>
<body>
<div id="radios">
  <input value="black" name="defaultradio1" id="defaultradio1-0" type="radio"><label for="defaultradio1-0">black</label>
  <input value="white" name="defaultradio1" id="defaultradio1-1" type="radio"><label for="defaultradio1-1">white</label>
</div>
</body>
</html>
```

**Comment by lmccart** [comment]
@mlarghydracept do you want to look into this one?

**Comment by outofambit** [comment]
I took a look into this. It seems [`createRadio()` creates those methods]() but [`select()` passes the element to `new p5.Element()`](https://github.com/processing/p5.js/blob/fc22ba8733d3feaaed9e9e5b9572dd08504d187f/lib/addons/p5.dom.js#L195) which won't call `createRadio()` because its wrapped in a div.

Will explore a fix for this. (I think we need extra logic in `select()` as well as a small refactor of `createRadio()` to accept existing html elements.)
