### ISSUE TITLE
select is not defined

### ISSUE THREAD

**Issue by deepika1212** [processing/p5.js#2303]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 
- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

**Comment by meiamsome** [comment]
Hey there!

Could you describe your issue some more? It sounds like your p5 isn't included correctly!

**Comment by lmccart** [comment]
please reopen when you have more details. or check out the forum for more help:
forum.processing.org
