### ISSUE TITLE
Having a problem downloading p5.js Please Help

### ISSUE THREAD

**Issue by Raddog59** [processing/p5.js#2328]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 
- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

**Comment by lmccart** [comment]
hello, you can download the library by clicking the "p5.js complete" button on this page:
https://p5js.org/download/

**Comment by Raddog59** [comment]
Thanks Imcart for  quick response. still an issue with download, error message
C:\\User\AppData\Local\Temp\Temp1_p5(2).zip\p5\p5.js
 line 46519
Char 1
Error :Expected Identifier, string or number
Code 800A0404
Source: Microsoft J Script compilation error

**Comment by lmccart** [comment]
are you hitting this error when you try to unzip the file or when you try to load a page that has p5.js linked in?

**Comment by Raddog59** [comment]
error occurs after download and when unzipping file.

**Comment by Raddog59** [comment]
error occurs when unzipping file.

**Comment by Jared-Sprague** [comment]
@Raddog59 You could try using CDN:  https://cdnjs.com/libraries/p5.js

You can just include these urls directly in script tags like this:

`<script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.5.16/p5.js"></script>`

CDN even gives you a handy short-cut to copy the script tag.   Or you could download directly from CDN,  if you want to work offline.

**Comment by Raddog59** [comment]
Jared thanks for your help. new to computers not sure what to do next with this info

**Comment by Raddog59** [comment]
Jared let me restate last comment sent by me, new to web design, not sure what exactly to do with the information stated in your last comment. thanks

**Comment by Jared-Sprague** [comment]
@Raddog59 In that case, Welcome!   I recommend you check out this [Getting Started](https://p5js.org/get-started/) guide.  Just skip the part that talks about downloading the complete zip file,  the next paragraph talks about how to include the files directly from CDN, and gives a complete example.  

Even easier, it gives a link to a codepen pen that you can use just in your browser without having to download anything.   You could also try the alpha version of the [p5.js web editor](https://alpha.editor.p5js.org/). I think either of these options would be the easiest to get you started.

**Comment by Raddog59** [comment]
Jared using p5js web editor to explore. Thank-you for your time and help.

**Comment by Raddog59** [comment]
Will try this Thanks.
