### ISSUE TITLE
get()  image function trouble with w,h parameters

### ISSUE THREAD

**Issue by osupk8** [processing/p5.js#2330]
When I use get(), get(5,5) I got an array of R,G,B,A value
But when I try get(0,0,10,10) I got an undefined value but no array
Can you help me please.
Here my basic test program 
function setup() { 
  createCanvas(400, 400);
} 
function draw() { 
  background(220);
  loadPixels();
  var zone=get(0,0,10,10);
  print(zone.length); // --> return undefined in debugger
}

#### Nature of issue?
- [ x] Found a bug
#### Most appropriate sub-area of p5.js?
- [x ] Image
#### Which platform were you using when you encountered this?
- [ x] Desktop/Laptop

#### Details about the bug: 

- p5.js version: 0.5.8 and 0.5.11
- Web browser and version: Chrome
- Operating System:  Windows
- Steps to reproduce this:

**Comment by lmccart** [comment]
calling get() with four parameters returns a p5.Image rather than an array. if you console.log(zone) you can see the parameters included. if you are looking for the pixels, you can do console.log(zone.pixels)

**Comment by osupk8** [comment]
Great, thank you
