### ISSUE TITLE
loadPixels parameters

### ISSUE THREAD

**Issue by osupk8** [processing/p5.js#2332]
I'd like to have a sketch like this one : [https://www.openprocessing.org/sketch/469492](https://www.openprocessing.org/sketch/469492)
But with a version like this one (not running yet ;)) [https://www.openprocessing.org/sketch/469658](https://www.openprocessing.org/sketch/469658) 
I want to use pixels array so my student can create their own image processing.
At the moment with loadPixels() you get all the image canvas, so if you want 
Like I'd like to o it in this second sketch  ( img.loadPixels(0,0,img.width,img.height);) , Can it be possible to add x,y,w,h parameters to loadPixels so we can take just a portion of the canvas image ?

Best regards
Christophe

[x] Existing feature enhancement
Most appropriate sub-area of p5.js?

[x ] Image
Which platform were you using when you encountered this?

[ x] Desktop/Laptop
Details about the bug:

p5.js version: 0.5.8 and 0.5.11
Web browser and version: Chrome
Operating System: Windows

**Comment by mlarghydracept** [comment]
Maybe [get](https://p5js.org/reference/#/p5/get) will accomplish what you want? You can pass (x,y,w,h) to `get()`.

**Comment by sixhat** [comment]
@osupk8 I think that you want the function get https://p5js.org/reference/#/p5.Image/get and https://p5js.org/reference/#/p5/get

**Comment by lmccart** [comment]
@sixhat is correct, thanks!

**Comment by osupk8** [comment]
Great, Thank you
