### ISSUE TITLE
p5js editor

### ISSUE THREAD

**Issue by osupk8** [processing/p5.js#2333]
Hi,
Can it be possible to have a full screen code editor  in alpha p5js editor
- [x ] New feature request

Best regars
Christophe

**Comment by lmccart** [comment]
you can drag the right side of the code editing box to be full screen width

**Comment by lmccart** [comment]
for further discussion, you can report over here: https://github.com/processing/p5.js-web-editor/issues

**Comment by osupk8** [comment]
Great, Thank you
