### ISSUE TITLE
get and updatePixels

### ISSUE THREAD

**Issue by osupk8** [processing/p5.js#2334]
I try this sketch where I want to generate a copy of the image but just with the red componant.
I'd like to know how to copy zone on the right of my canvas 
[https://www.openprocessing.org/sketch/469658](https://www.openprocessing.org/sketch/469658)

if I don't use zone.updatepixels(); zone is not updated and I got the same picture twice.
If I use it I got the error :
Uncaught TypeError: Failed to execute 'putImageData' on 'CanvasRenderingContext2D': parameter 1 is not of type 'ImageData'.
    at d.Image.d.Renderer2D.updatePixels (VM156 p5.min.js:5)
    at d.Image.updatePixels (VM156 p5.min.js:6)
    at setup (<anonymous>:29:8)
    at e.<anonymous> (VM156 p5.min.js:4)
    at _runIfPreloadsAreDone (VM156 p5.min.js:4)
    at e._decrementPreload (VM156 p5.min.js:4)
    at Image.d.onload (VM156 p5.min.js:6)

So how can I transfert the zone pixels modified on my canvas ?
Thanks for your help
Christophe

**Comment by osupk8** [comment]
Does anyone have an idea ?

**Comment by limzykenneth** [comment]
@osupk8 You are missing a call to `zone.loadPixels()` after you call `get`. `loadPixels` must be called before modifying the `pixels` array and calling `updatePixels`. In future, this kind of question mainly about debugging your own code is better suited to the [forum](https://forum.processing.org) as github issues are more for feature requests or bug reports concerning the library itself. You should also get a faster respond there. Thanks!

**Comment by osupk8** [comment]
Oh Great, Thank you. 
For further questions I'll use forum
Promise ;)
