### ISSUE TITLE
travis builds failing

### ISSUE THREAD

**Issue by Spongman** [processing/p5.js#2338]
i just noticed all that the travis-ci builds are failing, something to do with npm and phantomjs...

**Comment by Spongman** [comment]
just verified, the following fails on linux during phantomjs-prebuilt install:
````
rm -fr ./node_modules
nvm install 4.2
npm install
````

**Comment by limzykenneth** [comment]
I'm not able to replicate the build failing locally on my machine, @Spongman can you try with newer versions of node and see if that works?

**Comment by Spongman** [comment]
it works fine with newer node. but the travis-ci machine explicitly sets the node version to '4.2'

**Comment by limzykenneth** [comment]
Yeah, just wanted to pin down where the problem is. I don't think phantomjs is releasing any new versions now that they have stopped development so maybe one of the dependencies stopped working for 4.2?

**Comment by lmccart** [comment]
yes I believe that's correct. is there a way to remove the testing against 4.2 requirement from travis? I couldn't find one.
