### ISSUE TITLE
Wiki check for benchmarking

### ISSUE THREAD

**Issue by Jared-Sprague** [processing/p5.js#2339]
I added a [benchmarking p5.js](https://github.com/processing/p5.js/wiki/Benchmarking-p5.js) page to the wiki. 

I would love it if someone could test my guide and it by adding a new benchmark.   A good easy one would be `Math.sin()` vs `sin()`.     It's hard to know if I made it the guide easy enough for anyone to follow.

Thanks!

**Comment by ChrisJohnRyan** [comment]
@Jared-Sprague I took a swing at this with https://github.com/processing/p5.js/pull/2374 , I wasn't sure from the guide whether or not I need to have friendly errors disabled or not in the pull request.  I saw that the random.bench.js in the repo didn't have it.That might be something to clarify, and please let me know if I missed anything!

Thanks

**Comment by Jared-Sprague** [comment]
@ChrisJohnRyan This looks great!  Yeah I put the friendly error system example in there to show how to disable it if you want to, but it's not required.  However if it is on or off has a BIG difference on the results.  So it's probably good to keep it off, because if you're optimizing for performance you're going to want it off in prod anyway.

Thanks for giving it a try and for the feedback!

**Comment by ChrisJohnRyan** [comment]
No problem @Jared-Sprague . I had a quick question, can you explain/point me to the docs for where you are getting the scope to instantiate this class : `p5Inst = new p5();` ? Thank's in advance

**Comment by Jared-Sprague** [comment]
@ChrisJohnRyan Yep,  that is in scope when the benchmark runs in the browser because karma-benchmark will include anything in the 'files' section as <script> tags on the page:

```
  'random-dev': {
    options: {
      files: [
        'lib/p5.js',
        'bench/random.bench.js',
      ],
    },
  },
```
So before the benchmark runs in the browser there will be these script tags included in the document:
```
<script src="lib/p5.js"></script>
<script src="bench/random.bench.js"></script>
```

**Comment by ChrisJohnRyan** [comment]
That makes sense to me @Jared-Sprague , thanks for clarifying. When you define base path to be 
` // base path that will be used to resolve all patterns (eg. files, exclude)`
`basePath: '',`

and then we reference:
`files: [`
 `  'lib/p5.js', ` 
will that be loading files location at https://github.com/processing/p5.js/tree/master/lib? 

I did some more research on http://karma-runner.github.io/1.0/config/files.html after your last answer, but I'm not sure what part of the toolchain is putting a file there (if that is the right location for the base lib).

Mainly trying to find this so I can see where these actual methods (Random, Sin) are that we are stubbing out to benchmark.

**Comment by Jared-Sprague** [comment]
@ChrisJohnRyan Oh!  You have to run a build first and the build puts builds the p5.js file and puts it in lib.  I think I put that as the first step in the wiki article.  Is that what you're asking?

**Comment by ChrisJohnRyan** [comment]
Thanks @Jared-Sprague , yea that was actually what I was missing! @lmccart This is the initial thread for Jared's wiki edits
