### ISSUE TITLE
want a cool enhancement "clear(alpha)"

### ISSUE THREAD

**Issue by godhand4826** [processing/p5.js#2341]
#### Nature of issue?

- [ ] Found a bug
- [X] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [x] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [ ] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 
- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

#### Feature enhancement details:
I want to do something like 
```clear(alpha)```
, so the view in the canvas will fade out slowly as time goes on.

**Comment by mlarghydracept** [comment]
You can clear the canvas gradually by drawing a semi-transparent background over the top of image. If you want to do something like a traditional fade out, you can try clearing with semi-transparent black. You can see an example of [this in action here](https://www.openprocessing.org/sketch/470761). When you click an ellipse is drawn onto a canvas which has a semi-transparent black being drawn on every frame. With this effect, you can create many different types of fade effects.

**Comment by godhand4826** [comment]
thank for help ~ background with alpha works perfectly. ^^
