### ISSUE TITLE
Is there any way to make a canvas responsive?

### ISSUE THREAD

**Issue by jeffminsungkim** [processing/p5.js#2353]
According to the reference from the website, creates a canvas element in the document, and sets the dimensions of it in **pixels**. I think it would be nice to make a canvas mobile friendly by using with bootstrap or CSS. Perhaps there might be some solutions for this idea?

**Comment by Spongman** [comment]
''''
function windowResized() {
	createCanvas(windowWidth, windowHeight);
}
''''

**Comment by jeffminsungkim** [comment]
@Spongman Thanks for the response. As you said, it does affect the canvas size itself. However, a drawn object on the canvas such as text stays the same. Are there any options for this issue?
