### ISSUE TITLE
Shader uniform int array

### ISSUE THREAD

**Issue by tbremner** [processing/p5.js#2354]
#### Nature of issue?

- [ ] Found a bug
- [x] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Feature enhancement details:
Is there any reason why setting int array uniforms on shaders isn't supported at the moment? Seems like a simple addition using `gl.uniform1iv(location, data)`. Thanks guys.

_from p5.Shader.prototype.setUniform_
<img width="308" alt="screen shot 2017-11-10 at 12 47 18 pm" src="https://user-images.githubusercontent.com/29671817/32638955-ac30653a-c615-11e7-97aa-2c2568845920.png">

**Comment by kjhollen** [comment]
It probably just wasn't need for the initial default shaders that we had, but would be a great addition if you'd like to add it. :) Otherwise, I'll get to this when I can.
