### ISSUE TITLE
Mouse event get executed before setup()

### ISSUE THREAD

**Issue by DrSensor** [processing/p5.js#2355]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [x] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug:
`mouseMoved()` executed when mouse moved before `setup()`
```
Did you just try to use p5.js's clear() function? If so, you may want to move it into your sketch's setup() function.

For more details, see: https://github.com/processing/p5.js/wiki/Frequently-Asked-Questions#why-cant-i-assign-variables-using-p5-functions-and-variables-before-setup
/home/wildan/Projects/Sensorfied/f.i.d.e/node_modules/p5/lib/p5.js:42674 Uncaught TypeError: Cannot read property 'clear' of undefined
```

- p5.js version: p5@0.5.16
- Web browser and version: Google Chrome Version 62.0.3202.75 (Official Build) (64-bit)
- Operating System: Ubuntu 16.04.2
- Steps to reproduce this:
in instance mode
```javascript
let s = function (sketch) {
skecth.setup = function { 
  sketch.createCanvas(400, 400);
  sketch.noLoop()
} 

skecth.mouseMoved = function () {
  sketch.clear()
  sketch.fill(100)
  sketch.ellipse(mouseX, mouseY, 100, 100)
}
}

let canvas = new P5(s, document.getElement(#canvas))
```

**Comment by limzykenneth** [comment]
@DrSensor There are some mistakes in the code you posted, I've corrected them as below and I couldn't replicate the problem.

```
let s = function(sketch) {
	sketch.setup = function() {
		sketch.createCanvas(400, 400);
		sketch.noLoop();
	}

	sketch.mouseMoved = function() {
		sketch.clear();
		sketch.fill(100);
		sketch.ellipse(sketch.mouseX, sketch.mouseY, 100, 100);
	}
}

let canvas = new p5(s);
```
