### ISSUE TITLE
School project P5.js PWA 

### ISSUE THREAD

**Issue by Ry10p** [processing/p5.js#2358]
Hi there! 

I have a question about using p5.js in web components.

1. How to add it to a web compoent setup like Stenciljs 

https://stenciljs.com/docs/getting-started/

or EVEN BETTER 

Polymer framework
https://www.polymer-project.org/2.0/start/

These things seem to no want to render the p5.js sketch to the canvas or at times not even create the canvas for the sketch.

I want to use the this for a school project.

#### Any Ideas?

Thanks in advance!

**Comment by limzykenneth** [comment]
@Ry10p I've never used those frameworks before but p5.js is just a javascript library that you can include with a `<script>` tag or you can include it via npm if you prefer. If you need further help for this, please direct them to the [forum](https://forum.processing.org) as github issues are used more for feature requests and bug reports. Thanks!
