### ISSUE TITLE
Bug: Print() creates Dialogt to PRint File to Printer and Alpha.editor issue

### ISSUE THREAD

**Issue by Xrispy7** [processing/p5.js#2360]
I found a bug with Print(); on both Google Chrome Local and Google Chrome > p5.js Alpha Editor
When I try to use Print() in the Alpha Editor i get the following error:

//begin example
var x = 10;
print(x);
//end example
Ignored call to 'print()'. The document is sandboxed, and the 'allow-modals' keyword is not set.

when  I use Print(); Locally Google Chrome opens a Print Dialog window, as if I want to Print my File to a Printer.

Macbook Pro 2011 MACOSX 10.8.5 Laptop, Google Chrome version 49.0.2623.112 (64-bit) 
/*! p5.js v0.5.16 October 11, 2017 */

**Comment by limzykenneth** [comment]
Hi @Xrispy7, we have a dedicated repo for the web editor, can you post this issue [over there](https://github.com/processing/p5.js-web-editor/issues) so the web editor team can have a look at it? Thanks.

**Comment by lmccart** [comment]
This issue was moved to processing/p5.js-web-editor#474
