### ISSUE TITLE
New linter having issues with some parts of current code base

### ISSUE THREAD

**Issue by limzykenneth** [processing/p5.js#2361]
#### Nature of issue?

- [ ] Found a bug
- [x] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

Getting the latests pull at https://github.com/processing/p5.js/commit/b181c0311b174e7cc634604eb4587f7a7aa4fc9d and trying to build locally simply running `grunt`, I'm getting the following linter errors:

```
Running "eslint:build" (eslint) task

/Users/kennethlim/Dropbox/Sites/p5.js/tasks/build/combineModules.js
  28:21  error  Unnecessary escape character: \'  no-useless-escape
  28:25  error  Unnecessary escape character: \'  no-useless-escape

✖ 2 problems (2 errors, 0 warnings)

Warning: Task "eslint:build" failed. Use --force to continue.

Aborted due to warnings.
```

Fixing those result in the following:
```
Running "eslint:build" (eslint) task

Running "eslint:source" (eslint) task

/Users/kennethlim/Dropbox/Sites/p5.js/src/io/files.js
   381:18  error  Unnecessary escape character: \"  no-useless-escape
   412:12  error  Unexpected constant condition     no-constant-condition
  1420:35  error  Unnecessary escape character: \"  no-useless-escape
  1420:49  error  Unnecessary escape character: \"  no-useless-escape
  1421:14  error  Unnecessary escape character: \"  no-useless-escape
  1421:39  error  Unnecessary escape character: \"  no-useless-escape
  1471:26  error  Unnecessary escape character: \/  no-useless-escape
  1473:17  error  Unnecessary escape character: \/  no-useless-escape
  1516:48  error  Unnecessary escape character: \"  no-useless-escape
  1516:61  error  Unnecessary escape character: \"  no-useless-escape

/Users/kennethlim/Dropbox/Sites/p5.js/src/io/p5.Table.js
  678:25  error  Unnecessary escape character: \/  no-useless-escape

/Users/kennethlim/Dropbox/Sites/p5.js/src/typography/p5.Font.js
  815:19  error  'ii' is already defined  no-redeclare

✖ 12 problems (12 errors, 0 warnings)

Warning: Task "eslint:source" failed. Use --force to continue.

Aborted due to warnings.
```

Which led me to believe there may be more areas the linter is not happy about. I can go ahead and fix them but the only question I want to make sure of first is whether we want to fix all of them in the codebase or do we want to selectively turn them off (`Unnecessary escape character` for example can be turned off without too much problem I think).

One thing I don't understand is why didn't the tests fail at the linting stage on Travis?

**Comment by Zalastax** [comment]
That's strange but fortunately I've already fixed all those errors in https://github.com/processing/p5.js/pull/2336. It's possible that Travis has cached the node_modules and as we don't use any version lockfiles you can get a newer version than Travis when installing on your machine. I will propose adopting either npm5 or yarn lock files in a separate issue later this week.

**Comment by limzykenneth** [comment]
As part of #2362, I have committed a package-lock.json generated by npm5 but maybe we should overwrite that since I'm getting these errors? I did a clean install of all the dependencies by the way so not sure how to generate one that would work properly...

**Comment by Zalastax** [comment]
The issue can't come from different versions since we added eslint so recently. I downloaded your `package-lock.json` and I get no errors. Do you perhaps have [this change](https://github.com/Zalastax/p5.js/blob/0515b97e887592772677aa549a7bdc9384b9e1a9/.eslintrc) in your local repo? The errors should come from the preset `eslint:recommended` which could also be present in your global .eslintrc.

**Comment by limzykenneth** [comment]
@Zalastax That may be it, I'll check it in a bit.

**Comment by limzykenneth** [comment]
Can confirm is a result from my global .eslintrc extending eslint:recommended
