### ISSUE TITLE
adding whitespace causes reference sample to fail

### ISSUE THREAD

**Issue by Spongman** [processing/p5.js#2364]
Sometimes, if you edit one of the examples in the reference docs and add a space between the 'draw' function name and the '()' parentheses, if fails to run.

to repro:
- go to https://p5js.org/reference/#/p5/cursor
- click 'edit'
- add a space after the 'draw' function name
- click 'run'

**Comment by Zalastax** [comment]
This was already solved in https://github.com/processing/p5.js-website/commit/43b37f0bea1cb472f6251eed264f95a096ded7e5 but I guess the change has not been deployed yet.

**Comment by lmccart** [comment]
deployed!
