### ISSUE TITLE
angleBetween()

### ISSUE THREAD

**Issue by jamesgrubb** [processing/p5.js#2368]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [x] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.5.7
- Web browser and version: 62.0.3202.94 
- Operating System: Mac
- Steps to reproduce this:
Copy and paste the example code from https://p5js.org/reference/#/p5.Vector/angleBetween Running the code throws a console error - angleBetween is not a function

**Comment by meiamsome** [comment]
`angleBetween` was changed in v0.5.11, so the current docs aren't relevant to your version - I'd suggest updating p5

**Comment by jamesgrubb** [comment]
Will do, many thanks.
