### ISSUE TITLE
Manipulating p5.Geometry Vertices (WebGL)

### ISSUE THREAD

**Issue by BillDNA** [processing/p5.js#2369]
#### Nature of issue?

- [ ] Found a bug
- [x] Existing feature enhancement
- [x] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

- p5.js version:  v0.5.16
- Web browser and version: Chrome
- Operating System: MacOSX

#### New feature details:

When using a p5 Geometry object to draw 3D models, it would be nice since you have access to the vertices if you change the value of one.  If you can recompute the shape and it will deform the model appropriately.  Looking at the object it seems to have functions like computeNormals and computeFaces but these don't seem to be what I'm looking for.   Maybe the feature exists but there doesn't seem to be and documentation on it.

**Comment by Siphonophora** [comment]
Hi, could you give an example of the type of geometry you are trying to update? 

For most geometry, the compute faces and compute normal functions are only called once at the time the geometry is first drawn. That computed geometry is then put into the webgl buffer. We then use a reference to that geometry to redraw the geometry in subsequent frames. 

I believe once the geometry is defined we don't ever modify it. Possibly we can't, but I am not sure.

**Comment by BillDNA** [comment]
So the idea is by moving the specific vertices of a geometry the shape will
deform in ways that scale, translate or rotate can't.

After digging into it I found the buffer based on the Geometries based on
the 'gid' property.  So in a supper messy way I'm just changing the gid so
the 'morphed' shape get added into buffer.  but it would be nice if the
geometry object had a method that would re add it to the buffer.

**Comment by Siphonophora** [comment]
What type of geometry are you trying to deform (2d, 3d) and how often? 

My understanding of what happens once we hand geometry off to the buffer is pretty limited, but I think if you generate new geometry you would want a new gid and not to overwrite the buffer. I am not sure what will happen if you try to make changes.

**Comment by BillDNA** [comment]
3d and the only way i've found is to change the gid after adjusting the vertices so it is forced to recalculate and insert into buffer.

**Comment by Spongman** [comment]
try this for a hack:

````
var renderer;
var geometry;
var gid = 'custom';
function setup () {
  renderer = createCanvas(500, 500, WEBGL);
  geometry = new p5.Geometry(...);
}
function draw() {
  // modify geometry
  geometry.computeNormals();

  renderer.createBuffers(gid, geometry);
  renderer.drawBuffers(gid);
}
````

**Comment by stalgiag** [comment]
It feels slightly distracting from the intent for p5 to expose this more than it is already. I think the example that @Spongman gives above and the [customGeometry manual example](https://github.com/processing/p5.js/blob/master/test/manual-test-examples/webgl/customGeometry/sketch.js) will have to suffice for this kind of task.

Closing now for organization purposes but if there is a good argument for putting more emphasis on custom geometry (ie making a publicly exposed helper function to do so) then feel free to post here and we can reopen for a discussion.
