### ISSUE TITLE
style push/pop for webgl mode

### ISSUE THREAD

**Issue by kjhollen** [processing/p5.js#2370]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [x] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Details about the bug: 

- p5.js version: 0.5.16
- Web browser and version: any :)
- Operating System: any
- Steps to reproduce this:
call push(), change the stroke and/or fill, call pop()

expected results: stroke and fill revert to color last used before push()
actual results: color does not revert

in 2D mode, the styles are cached wholesale as part of the canvas API—but we need to do a little bit more work to reset the shaders in 3D mode.

for reasons outlined in pull request #2211, it would be good to also cache which texture is in use. so that we can use push/pop internally to change textures in gl mode for image() and future calls to text() when implemented—and maybe other uses we haven't anticipated yet.

I have a first pass at this semi-working that is not quite ready for review. needs unit tests!

**Comment by kjhollen** [comment]
work in progress here: https://github.com/kjhollen/p5.js/commit/bd40111984c78bdae0349075ac6a6c845dc67e61

@mlarghydracept this needs a lot more testing, though it seems to be working in simple cases. I'm worried that the code is a little messy or too complicated—if you've got time, can you have a look and let me know if you have any ideas for resolving that? I used the main push/pop as a model for saving styles.

**Comment by Spongman** [comment]
i think it might simplify things a _little_ if, instead of handling multiple stacks in the renderer, you just allow the renderer to add its state into the objects pushed onto the `_styles` array. well, in the future if there are more renderers it would reduce the amount of duplicated stack-handling code.

for example, if the top-level `push` function looked something like:

    p5.prototype.push = function () {
      var rendererState = this._renderer.push();
      this._styles.push({
        rendererState: rendererState,
        properties: {
          _doStroke: this._renderer._doStroke,
          _strokeSet: this._renderer._strokeSet,
          ...
        }

and `pop` looked like:

    p5.prototype.pop = function () {
      var lastS = this._styles.pop();
      for(var prop in lastS.properties) {
        this._renderer[prop] = lastS.properties[prop];
      }
      this._renderer.pop(lastS.rendererState);
    };


then the renderer's `push` function could just return an object containing all the state it wished to preserve:

    p5.RendererGL.prototype.push = function() {
      return {
        properties: {
          uMVMatrix: this.uMVMatrix.copy(),
          cameraMatrix: this.cameraMatrix.copy(),
          curCamera: this.curCamera,
          ...
        },
        fillShaderSamplers: cachedTextures,
        ...
      };

and the rendere's `pop` is just passed back that state:

    p5.RendererGL.prototype.pop = function(state) {
      for (var prop in state.properties) {
      ...

**Comment by mlarghydracept** [comment]
@kjhollen sorry for the delay! I somehow missed this and have been swamped. I like  your suggestion @spongman but I am bit confused about the reasoning for the separate rendererState and properties objects in your styles array. In terms of messiness, I feel like it mostly looks good to me. It might feel a bit cleaner if you did the uniform resets in its own private function. This function could potentially be used elsewhere in the code anyways. 

I really only got a chance to do a quick read of the code and tests. I'll try to make some more complicated and stress-heavy tests to run in the next few days.

**Comment by Spongman** [comment]
i separated out the `properties` object as a collection of properties that can be directly re-applied to the renderer (using Object.apply, or similar) so the special-case handling in the loop is no longer required.

**Comment by kjhollen** [comment]
awesome, great suggestion, thanks @Spongman! stand by for updates, hopefully next week.

**Comment by Spongman** [comment]
I think this can probably be closed now.

**Comment by yousifucv** [comment]
Hi all, this is still an issue in 0.6.1
