### ISSUE TITLE
How to get more than 60 fps frameRate

### ISSUE THREAD

**Issue by gkaragoz** [processing/p5.js#2372]
#### Nature of issue?

- [ ] Found a bug
- [ x ] Existing feature enhancement
- [ ] New feature request

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [ x ] Desktop/Laptop
- [ ] Others (specify if possible)

#### Feature enhancement details:
I want to increase default FPS rate which is 60 for now. I need to make it more than 60. How can I do that? The setFrameRate(val); function does not work more than 60 value.

**Comment by Spongman** [comment]
i don't believe this is a p5.js issue -- there's no code in p5 that limits the frameRate to 60fps. I believe that the browser will not refresh the script animation faster than the monitor's refresh rate. i have no 120Hz monitors to test this, so all I see is 60Hz.

You _could_ call your rendering code more than once per frame, but really there's no point in rendering frames that aren't going to be sent to the monitor. Maybe if you're looking for faster animation speed, it might be worth looking at tying your animation to the time (`millis()`) instead of frameCount?

**Comment by gkaragoz** [comment]
Actually you're right. My monitor also has the same frequency like 60Hz for maximum. So this is why I can't get more than 60 fps in my p5 project.

But I just want to fix that problem. You can see image that below, there is an mouseDragged() function in my project that makes draw ellipse into canvas. When I dragged my mouse with so much speed, that result will not be very well. 

[https://pasteboard.co/GUylHDJ.png](url)

This is my code where I put my Paint function;

```
function mousePressed() {
    paint();
}

function mouseDragged() {
    paint();
}

function paint() {
    this.mouseX = mouseX;
    this.mouseY = mouseY;
    
    noStroke();
    fill(pencilColor);
    ellipse(this.mouseX, this.mouseY, pencilSize, pencilSize);
    
    sketchData.x = this.mouseX;
    sketchData.y = this.mouseY;
    
    console.log(sketchData);
}
```

**Comment by Spongman** [comment]
i'm afraid that is the best you can do. the mouse is only sampled once per frame and at 60fps you're going to see those gaps. if you want more steps you could simply draw a line (in this case), or lerp your coordinates over a (possibly distance-based) number of steps.

**Comment by Spongman** [comment]
try this:

	var px, py;
	var H;
	function setup() {
		createCanvas(windowWidth, windowHeight);
		background(0);
		px = mouseX;
		py = mouseY;
		H = 0;
		colorMode(HSB);
	}

	function draw() {
		noStroke();

		var d = dist(px, py, mouseX, mouseY);

		for (var i = 0; i <= d; i += 10) {

			var nx = lerp(px, mouseX, i/d);
			var ny = lerp(py, mouseY, i/d);
			fill(H, 255, 255);
			H = (H+10) % 255;
			ellipse(nx, ny, 10, 10);
		}

		fill(255);
		ellipse(mouseX, mouseY, 20, 20);

		px = mouseX;
		py = mouseY;
	}
