### ISSUE TITLE
loadSound is not a function when I using it with Angular

### ISSUE THREAD

**Issue by OrionStark** [processing/p5.js#2375]
I got problem when using p5js with Angular4. it said that the loadSound is not a function.
This is my code looks like : 
import { Component, OnInit, AfterViewInit } from '@angular/core';
import * as p5 from 'p5';

@Component({
  selector: 'app-music',
  templateUrl: './music.component.html',
  styleUrls: ['./music.component.css']
})
export class MusicComponent implements OnInit {

  constructor() { }

  ngOnInit() {
    var myMusic = function (props) {
      var music;
      var fft;
      var canvas;
      props.preload = function () {
        music = props.loadSound("../../music/01-royal_blood-how_did_we_get_so_dark.mp3");
      };
      props.setup = function () {
        canvas = props.createCanvas(props.windowWidth-13, 500);
        music.play();
        fft = new p5.FFT();
        music.amp(1);
      };

**Comment by lmccart** [comment]
are you including the p5.sound library? that is a separate module than the p5 main

**Comment by OrionStark** [comment]
I'm so sorry, yeah it's working now by putting the 3 libraries of p5js in the global index and declare a var p5 with an any type

**Comment by chrisjaimes** [comment]
hey @OrionStark can you show how to you imported the p5.sound library and then add it to the p5 constructor? thanks!

**Comment by OrionStark** [comment]
@chrisjaimesdev , hey, I just put these library in index.html
`<script src="./assets/p5js/p5.js"></script>
  <script src="./assets/p5js/p5.dom.js"></script>
<script src="./assets/p5js/p5.sound.js"></script>`

Then in the ts file, I put some codes like
`declare var p5:any;`
and then make a function to for the music module like

`var spectrum = function(myspectrum) {
      var music = null;
      var fft;
      var myPeak;
      var canvas;
      var widthParent = document.getElementById("spectrum").clientWidth;
      var heightParent = document.getElementById("spectrum").clientHeight;
      var play_button;
      var stop_button;

      function toggle() {
        if ( document.readyState ) {
          play_button = document.getElementById("play");
          stop_button = document.getElementById("stop");

          play_button.addEventListener('click', () => {
            if ( music.isPlaying() ) {
              music.pause();
              play_button.innerText = "Play";
            } else {
              music.play();
              play_button.innerText = "Pause";
            }
          });

          stop_button.addEventListener('click', () => {
            if ( music.isPlaying() || music.isPaused() ) {
              music.stop();
              play_button.innerText = "Play";
            } else {
              // Gak tau mau diapai
            }
          });
        }
      }

      myspectrum.preload = function() {
        music = myspectrum.loadSound("../../assets/music/Selena Gomez - My Dilemma 2.0.mp3");
      }
      myspectrum.setup = function() {
        canvas = myspectrum.createCanvas(widthParent - 30, heightParent);
        fft = new p5.FFT();
        music.amp(1);
        toggle();
      }
      myspectrum.draw = function() {
        myspectrum.background(0);
        fft.analyze();
        var wave = fft.waveform();
        myspectrum.translate(widthParent * 0.02, heightParent * 0.25);
        myspectrum.noFill();
          myspectrum.stroke(255, 255, 255);
          myspectrum.strokeWeight(2);
          for ( var i = 0; i < wave.length; i+=5 ) {
            var x = i;
            var y = 80 + wave[x] * 50;
            var x2 = i + 1;
            var y2 = 80 + wave[x2] * 50;
            myspectrum.line(x,y, x2, y2);
          }

          myspectrum.beginShape();
          myspectrum.stroke(255, 202, 40);
          myspectrum.strokeWeight(1);
            for ( var i = 0; i < wave.length; i += 10 ) {
              var x = i + 1;
              var y = 80 + wave[x] * 50;
              myspectrum.vertex(x, y);
            }
          myspectrum.endShape();
      }
};`

`
/* And this is the part that you could add it to p5 constructor */
var result = new p5(spectrum, "spectrum");`

**Comment by NOPROD** [comment]
import { Component, OnInit } from '@angular/core';
import * as p5 from 'p5';
import    'p5/lib/addons/p5.sound';
import { Observable, observable, of } from 'rxjs';
import {map,filter, bufferWhen} from 'rxjs/operators'
@Component({
  selector: 'theme-first',
  templateUrl: './first.component.html',
  styleUrls: ['./first.component.scss']
})
export class FirstComponent implements OnInit {
  constructor() { }
  private p5sketch: p5;
  private p5Sound: p5.p5InstanceExtensions;


  ngOnInit() {
     this.createCanvas();
  }

  private createCanvas() {
    this.p5sketch = new p5(this.sketch);
  }

  private sketch(p: p5) {

    /** Preload all assets/pre-config */
    p.preload = () => {

    var song = new p5.SoundFile('./../../../../assets/music/theme/first/InClosing-DaysPast.mp3', playSong);

    function playSong(){
    song.play();
    }
    
    }

    /** Setup load all  */
    p.setup = () => {
      p.createCanvas(500, 500);
      p.background(0);
    }
}

    ngOnDestroy() {
    this.p5sketch.remove();
    }
}


Just do like this with payload, i think is a clean method

**Comment by curiouscod3** [comment]
loadSound Doesn't work!

**Comment by OrionStark** [comment]
> loadSound Doesn't work! in Angular...

Hey, could you tell us more about what happened?. Maybe you could show us the error message

**Comment by ronenwo** [comment]
I needed something similar - i wanted in angular to add p5.play.

angular.json:

"scripts": [
              {
              "input": "node_modules/p5/lib/p5.min.js",
              "inject": true,
              "bundleName": "p5"
              },
              {   
              "input": "node_modules/p5/lib/addons/p5.sound.js",
              "inject": true,
              "bundleName": "p5.sound" },
              {
              "input": "src/assets/js/p5.play.js",
              "inject": true,
              "bundleName": "p5.play"
              }
            ]

in angular component using p5:

declare var p5: any;

**Comment by OrionStark** [comment]
@ronenwo Is it working?
