### ISSUE TITLE
loadXML failing in instance mode (parseXML not defined)

### ISSUE THREAD

**Issue by limzykenneth** [processing/p5.js#2388]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [x] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug: 
When running `loadXML()` in instance mode, the error `ReferenceError: parseXML is not defined` will be thrown and the loading fails. This does not affect immediate mode. 

After some digging, I find that it is probably to do with scoping issue where `loadXML` is calling `parseXML` directly, expecting it to be in scope, which it is in window scope in immediate mode, in instance mode however it cannot find reference to parseXML directly. Also happens when parseXML attempts to call itself recursively.

I have two ways of fixing this: 
1. Call `this.parseXML` in `parseXML` and make reference to `this` and call `self.parseXML` in `loadXML`.
2. `parseXML` is an undocumented feature and is only used by `loadXML` internally in the module, so instead of attaching `parseXML` to the p5.prototype, we can just make it a private function in that scope, ie `function parseXML()` instead of `p5.prototype.parseXML = function()`.

Let me know what is the preferred way to fix this and I can make the PR. I personally prefer the second option to keep the prototype clean of undocumented features, unless there is a desire to document this function officially.

Thanks to @jonaseltes for finding this issue.

- p5.js version: 0.5.16
- Web browser and version: Safari 11.0.1 and Chrome 62.0.3202.94 but expected on all browsers
- Steps to reproduce this:

```javascript
var sketch = function(p){
	var xml;
	p.preload = function(){
		xml = p.loadXML("/example.xml");
	};

	p.setup = function(){
		console.log(xml);
	};
};

new p5(sketch);
```

**Comment by danstanhope** [comment]
I could take a look at this if it's still available!

Was going to follow the approach outlined in option 2. In files.js there appears to be a section where one or two private functions have been defined already. I was thinking I'd implement parseXML() there -- unless I'm mistaken parseXML just needs to convert the xml doc to a JSON object.

Thanks!

**Comment by danstanhope** [comment]
Sorry, that should have read "unless I'm mistaken parseXML just needs to convert the xml doc to p5.XML objects". 👍

**Comment by danstanhope** [comment]
So here's my parseXML function. It's a recursive function that builds out a list of p5.XML object.

```
function parseXML(xml){  
  var resp = new p5.XML();  

  resp.setName(xml.nodeName);
  resp._setAttributes(xml);

  for (var i = 0; i < xml.children.length; i++) {    
    var item = xml.children[i],
        name = item.nodeName;

    if(item.children && item.children.length > 0){ 
      resp.addChild(parseXML(item));        
    }else{      
      if(item.firstChild){ 
        var child = new p5.XML();

        child.setName(item.nodeName); 
        child._setCont(item.firstChild.nodeValue.trim());  
        child._setAttributes(item);

        resp.addChild(child);
      }                    
    }       
  }

  return resp;
}
```

I snagged some code from the documentation page to test my implementation and everything seems to be working:

`
var sketch = function(p){
	var xml;

	p.preload = function(){
		xml = p.loadXML("../../test/unit/assets/books.xml");
	};

	p.setup = function(){
		var children = xml.getChildren('book');

		for (var i = 0; i < children.length; i++) {
			console.log(children[i].getName(), children[i].getNum('id'))
		}
	};
};

new p5(sketch);
`
I have a unit test to write and a bit of clean-up to do, but if you guys like the look of this I'd be happy to submit a pull request.

Thanks & best,
Dan

**Comment by limzykenneth** [comment]
Ah, this issue complete slipped my mind. I actually already have a the fix ready but was just waiting for concensus on whether to go for option 1 or 2. There already is a `parseXML` function in the library, it's just not working correctly in instance mode hence some fix is required. You've got the right idea about `parseXML` though.

Sorry about this, I should have followed up with this issue earlier. I'll make the PR for my changes today, if you like you can help me test it. Otherwise we should have some other issues that can use some help. 😃

**Comment by danstanhope** [comment]
No problemo! Yeah, I'd happy to help test. In the meantime, if there are any available bugs you could assign to me, I'd be happy to have a look.

Thanks!
