### ISSUE TITLE
The p5.js reference page contains no info about degrees method, or description

### ISSUE THREAD

**Issue by chris-relaxing** [processing/p5.js#2390]
The p5.js reference page contains no info about degrees method, when using search. The DEGREES constant page has no description. https://p5js.org/reference/#/p5/degrees

**Comment by hackertron** [comment]
Can i take on this task ? . Currently i am reading the documentation and learning p5.js , soon i will reach this section and will create an example for myself . it would be better if i will be able to lay down the steps , it can serve as an example

**Comment by limzykenneth** [comment]
@hackertron PR #2395 is addressing similar issue but with `BLEND` rather than degree. Most (if not all) constants are missing definitions in the documentation so if you want to help create them please do, it will be a great help!

**Comment by hackertron** [comment]
Sure , i will start writing them soon !!

**Comment by hackertron** [comment]
Hey , i saw that there is already good descriptions about constants ( HALF_PI , PI, QUARTER_PI, TAU , TWO_PI ) .

**Comment by Spongman** [comment]
the degrees/DEGREES bug was fixed in a1cc055975f89d14a7c364173bf12bdd62cc42a2. we're just waiting for that fix to be pushed to the web site. once that happens, the docs for the `degrees()` method will appear correctly.
