### ISSUE TITLE
Emojis with text size >= 127 are not rendered

### ISSUE THREAD

**Issue by i3games** [processing/p5.js#2393]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [x] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: v0.5.16
- Web browser and version: Firefox 57, Chrome 62
- Operating System: MacOSX 10.12.6
- Steps to reproduce this:

```
function draw() {
  background(255);
  textSize(127); // <= 126 works
  text("😀", width/2, height/2);
}
```

**Comment by limzykenneth** [comment]
I can only replicate this behaviour with Firefox, Chrome and Safari both worked fine for me.

**Comment by norbit8** [comment]
I use Firefox Quantum and it did work for me.
```
function setup() {
  createCanvas(500,500);
}

function draw() {
  background(255);
  textSize(127); // <= 126 works
  text("😀", width/2, height/2);
}
```

**Comment by limzykenneth** [comment]
@norbit8 Can I know which OS are you using? Also which device as well. I'm using Firefox Quantum 57.0.1 but it did not work.

**Comment by norbit8** [comment]
@limzykenneth I run Windows on my PC.

**Comment by iErcann** [comment]
I have tried Chrome and Firefox and It's not showing the emoji for me, even when i take a value less than 126.
Im on linux, Ubuntu XFCE : 4.10.0-38-generic #42~16.04.1-Ubuntu

**Comment by limzykenneth** [comment]
@iErcann Does your build of Ubuntu have support for Emoji in the browser?

It may be an OS specific issue, can someone else with Windows PC test this and confirm is it working as intended?

**Comment by Spongman** [comment]
embedding unicode characters in source code like this is really problematic. you really need to be careful to make sure that the text file itself is save in the correct format (potentially with a BOM), you also need to make sure either the web server serving it is able to inform the browser of the correct encoding, or alternatively include the encoding in the header of the html document.

it's usually much safer to use ASCII-only encoded html files, and encode character entities like this using the existing html/javascript mechanisms.

for example, the code below should work on any browser:

````
  text("\uD83D\uDE00", width/2, height/2);
````

**Comment by i3games** [comment]
@Spongman good point but this not the issue in this case. The encoded version you provided has the same bug.

**Comment by lmccart** [comment]
looks like some browsers just have a maximum size at which they render emoji. it's a reported bug for chrome at least: https://stackoverflow.com/questions/29142118/why-do-emoji-not-render-above-a-certain-size-in-chrome, [more](https://nicolas-hoizey.com/2017/10/chrome-fails-showing-big-emojis.html). i don't think there's anything we can do on the p5.js end for this.
