### ISSUE TITLE
default alpha for background() in reference. Is it 0-255 or 0-100?

### ISSUE THREAD

**Issue by amilo** [processing/p5.js#2394]
Hello,
I am aware of the [discussion](https://github.com/processing/p5.js/pull/857) related to colorMode() which seems to be solved. I've also just found this [recent discussion that confused me a bit more](https://github.com/processing/p5.js/pull/2385).
In the [background()](https://p5js.org/reference/#/p5/background) reference it seems that the information stating that default alpha is 0-100 might be misleading. I verified that background takes 0-255 for the alpha value without changing colorMode(). Is there a reason to amend the reference or something misinterpreted by me?

Along the same line I would suggest to detail more the syntax specification for [fill() ](https://p5js.org/reference/#/p5/fill)and [stroke()](https://p5js.org/reference/#/p5/stroke) since the definition for the alpha value seems a bit vague. Maybe it's work in progress.

#### Nature of issue?

- [ ] Found a bug
- [x] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [x] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Feature enhancement details:

https://p5js.org/reference/#/p5/background

**Comment by lmccart** [comment]
yes, you're correct the reference should state that the alpha is 0-255 (not 0-100). feel free to submit a PR if you like, or i will update next chance i get. thanks!
