### ISSUE TITLE
how to save image file as javascript to display image on canvas.

### ISSUE THREAD

**Issue by pooja0692** [processing/p5.js#2396]
#### Nature of issue?

how to save image file in p5.js
resize of the image

#### Most appropriate sub-area of p5.js?

- [ ] Image
- 

#### Which platform were you using when you encountered this?

- [ ] Desktop/Laptop

#### Details about the bug: 
there are no errors. But I cannot see the image on the screen.
Is there anything to be written in HTML?

- p5.js version: 

- Web browser and version: <!-- On Chrome

- Operating System: <!-- Ex: Windows

**Comment by lmccart** [comment]
hi @pooja0692 can you please post this question in the forum?
https://forum.processing.org/two/

the github issues are just for issues with the library development.

here are some video tutorials that may be helpful in what you're doing:
https://www.youtube.com/watch?v=RUSvMxxm_Jo
https://www.youtube.com/watch?v=nMUMZ5YRxHI
