### ISSUE TITLE
Failed calling a function with an arguments inside

### ISSUE THREAD

**Issue by norbit8** [processing/p5.js#2398]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [x] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version:  v0.5.8
- Web browser and version: FireFox Quantum 
- Operating System: Windows 
- Steps to reproduce this: 

The error I get is: 
> TypeError: fxn is undefined p5.js:14207:7

As you can see in the code below, I tried to select all the paragraphs in my HTML file (Which I didn't include because it's pretty basic one), and then execute a function which will change the paragraph's color.
***Please note that I know I could use "this." instead but I wanted to try the "Vanilla" way of doing such thing, and then I encountered this problem.**
Thank you.

```
var paragraphs = [];
var i;

function setup() {
  noCanvas();
  paragraphs = selectAll('p');
  for (i=0;i<paragraphs.length;i++){
    paragraphs[i].mousePressed(changeColor(i));
  }
}

function changeColor(i){
  paragraphs[i].style("background-color", '#ffe7ba');
}
```

**Comment by limzykenneth** [comment]
When defining callbacks, you usually cannot pass arguments to the callback function being called, ie
```
paragraphs[i].mousePressed(changeColor(i));
```
should be
```
paragraphs[i].mousePressed(changeColor);
```
and you cannot pass the argument `i` like this to the callback function. Note that you do not have any parenthesis behind the callback function's name because putting the parenthesis there indicate calling the function, which will attach whatever is returned from the called function as callback instead.

The easiest way to get around this problem will be to use `this`, that's exactly why it's there in the first place. However if you still want to avoid using `this`, perhaps you need `i` for example, you can do something like the following:
```
paragraphs[i].mousePressed(function(){
  changeColor(i);
});

**Comment by limzykenneth** [comment]
Something like this should run, although it is getting a bit unnecessarily complicated now:
```javascript
var paragraphs = [];
var i;

function setup() {
  noCanvas();
  paragraphs = selectAll('p');
  for (var i = 0; i < paragraphs.length; i++) {
    bindMouse(i);
  }
}

function changeColor(i) {
  paragraphs[i].style("background-color", '#ffe7ba');
}

function bindMouse(i){
  paragraphs[i].mousePressed(function() {
    changeColor(i);
  });
}
```

**Comment by norbit8** [comment]
Thank you, the code on the second comment works just fine, though when I tried the first one I get an error, do you know why is that?

```
var paragraphs = [];
var i;

function setup() {
  noCanvas();
  paragraphs = selectAll('p');
  for (var i = 0; i < paragraphs.length; i++) {
    paragraphs[i].mousePressed(function() {
      changeColor(i);
    });
  }
}

function changeColor(i) {
  paragraphs[i].style("background-color", '#ffe7ba');
}
```
> paragraphs[i] is undefined

**Comment by limzykenneth** [comment]
When you bind the event handler with `paragraphs[i].mousePressed(callback)` whatever is in the callback is not executed and not evaluated. When the event fires, the callback is then executed which means at this time, it will then evaluate what the value of `i` in the callback function and in turn for `changeColor(i)` is. However, the `for` loop has already executed and finished so the value of `i` is at the final state of the `for` loop which is `paragraphs.length` which is 1 more than what you have for index, so you will get undefined.

Have a read on JS variable referencing and scoping on the web, John Resig wrote some good resources to help with that.
