### ISSUE TITLE
WEBGL mode performs much worse after version 0.5.14

### ISSUE THREAD

**Issue by DexterShepherd** [processing/p5.js#2399]
#### Nature of issue?

- [ x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x ] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

_MacOS - Chrome_

Hey all,

I noticed some of my WEBGL mode sketches are performing much worse in p5 version `0.5.15` and later. After digging around in the chrome performance tab a bit I found a call to `getParameter` in `p5.Shader.prototype._setViewportUniform` taking > 90% of each frames time that isn't present in version `0.5.14`.

Issue can be reproduced by changing the p5 version in the `script` `src` from `0.5.15` to `0.5.14` and comparing performance stats.
  
```
<!DOCTYPE html>
<html lang="en">
<head>
  <script src='https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.5.15/p5.js'></script>
</head>
<body>
  <script type="text/javascript">
    function setup() {
      createCanvas(500, 500, WEBGL)
    }
    
function draw() {
  background(0)
  for(var i = 0; i < 100; i += 1) {
    push()
    rotateX(i * frameCount * 0.1)
    rotateZ(i * frameCount * 0.2)
    box(250)
    pop()
  }
}
  </script>
</body>
</html>

```
_0.5.14_
<img width="734" alt="screen shot 2017-12-05 at 5 01 04 pm" src="https://user-images.githubusercontent.com/7800175/33639592-f37c08de-d9e0-11e7-9427-3d1e5fa72199.png">

_0.5.15_
<img width="670" alt="screen shot 2017-12-05 at 4 59 37 pm" src="https://user-images.githubusercontent.com/7800175/33639615-0bb4e330-d9e1-11e7-9833-320a7db22802.png">

I don't know enough about the webgl internals of p5 to fix this issue by myself, but hopefully this ticket helps someone out. 

Thanks,

Dex

**Comment by Spongman** [comment]
yup, you're spot on. the `getParameter` call is quite expensive and luckily in this case it can be cached.

**Comment by lmccart** [comment]
you can also try linking to the p5.min.js version which is much faster because it doesn't do parameter validation and friendly errors, though I'm not sure it helps specifically with the webgl getParameter() call.
