### ISSUE TITLE
Load and Display Image Limits

### ISSUE THREAD

**Issue by darkworks** [processing/p5.js#2403]
i came cross this project looks interesting to me ,  i explore it and landed on this example 

> https://p5js.org/examples/image-load-and-display-image.html

so my Question is what are the limits of loading image to canvas through p5 , am working with big images recently  have problem with loading 20k ( 20 megapixel ) image to canvas with standard img.onload function of mage() class   , i am getting NS_ERROR_FAILURE error , so can anybody tell me this library limits  or can suggest any other library as  i do pixel analysis mostly so am currently stuck cant load above 10 Megapixel image to canvas  

thanks

**Comment by limzykenneth** [comment]
@darkworks The library doesn't set a limit on the size of images. The limit on how big of an image you can load in depends on the browser and the system the browser is running on (OS, amount of RAM, etc). If you are interested in doing image analysis and need all the pixels, you will be better off looking into other more native solutions such as Processing or openframeworks or something else depending on what you actually need to do, browser based solution may not be able to handle it at the moment.
