### ISSUE TITLE
iOS input element not functional

### ISSUE THREAD

**Issue by BillDNA** [processing/p5.js#2405]
#### Nature of issue?

- [X] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [X] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [X] Mobile/Tablet (touch devices)
- [ ] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

I have an input field ```<input type="email" name="email">``` and when I load the page on the phone it is not bringing up the keyboard.

if i remove p5 from the page then the keyboard will work.

**Comment by lmccart** [comment]
I'm not able to reproduce this, could you post a snippet of the sketch and html code you're working with? This is what I'm testing with currently:
```html
<!DOCTYPE html>
<html>
  <head>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.5.16/p5.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.5.16/addons/p5.dom.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.5.16/addons/p5.sound.min.js"></script>
    <link rel="stylesheet" type="text/css" href="style.css">
    <meta charset="utf-8" />
  </head>
  <body>
    <script src="sketch.js"></script>
    <input type="email" name="email">
  </body>
</html>
```

```javascript
function setup() { 
  createCanvas(400, 400);
} 

function draw() { 
  background(220);
}
```
