### ISSUE TITLE
setAttributes() Not working !

### ISSUE THREAD

**Issue by realcygnus** [processing/p5.js#2412]
P5 js sketch
WEBGL mode
Chrome on Windows
p5 Libs both old & latest

//init
function setup() {
  createCanvas(800, 600, WEBGL);
  setAttributes('antialias', true);
  cg = createGraphics(100, 100);
}//su

Uncaught ReferenceError: setAttributes is not defined
    at setup (sketch.js:26)
    at p5.<anonymous> (p5.js:9107)
    at p5.<anonymous> (p5.js:9047)
    at new p5 (p5.js:9320)
    at _globalInit (p5.js:5602)

**Comment by Spongman** [comment]
@realcygnus did you discover what was wrong? was it a versioning issue?

**Comment by realcygnus** [comment]
yes just a version issue .....the very latest libs do work.......thought I closed it.....sorry & thanks !


________________________________
