### ISSUE TITLE
only the final light source (pointLight, directionalLight) is rendered

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js#2414]
- Found a bug
- WebGL
- Desktop
- p5.js version: 0.5.16
- Web browser and version: chrome Version 63.0.3239.84 (Official Build) (64-bit)
- Operating System: Mac OSX 10.11.6

In the following simple example which positions two point lights (one on the left, one on the right) the second call to `pointLight()` overrides the first, rather than adding a new light.

```javascript
function setup() {
  createCanvas(400, 300, WEBGL);
}

function draw() {
  background(175);
  pointLight(0, 0, 255, -200, 0, 0);
  pointLight(255, 0, 0, 200, 0, 0);
  ambientMaterial(255);
  noStroke();
  sphere(50);
}
```

With the red light second, i.e.

```javascript
  pointLight(0, 0, 255, -200, 0, 0);
  pointLight(255, 0, 0, 200, 0, 0);
```

![screen shot 2017-12-14 at 5 58 30 pm](https://user-images.githubusercontent.com/191758/34018596-83130b00-e0f8-11e7-9798-5cf80b1ac79f.png)

With the blue light second:
```javascript
  pointLight(255, 0, 0, 200, 0, 0);
  pointLight(0, 0, 255, -200, 0, 0);
```
![screen shot 2017-12-14 at 5 58 40 pm](https://user-images.githubusercontent.com/191758/34018605-88dc9d76-e0f8-11e7-9736-abb881c8ad85.png)

This bug appeared somewhere between 0.5.14 and 0.5.16. Using 0.5.14, both lights are active:

![screen shot 2017-12-14 at 6 00 23 pm](https://user-images.githubusercontent.com/191758/34018631-bcf86af4-e0f8-11e7-9d52-d81777edbb5d.png)

The same bug exists for `directionalLight()`.

This may be related to: #2251 and #1622 

(this issue was filed by the viewers of The Coding Train live!)

**Comment by sharethewisdom** [comment]
https://github.com/processing/p5.js/pull/2257/commits/ddf9188a9916f3d4d161af7092d0c6c714416081 ?

**Comment by superdump** [comment]
I just finished bisecting this:

```
commit 9fc042c2d1b949aef7456b782c504f3a5fe8a104
Author: DoubleJump <gareth.battensby@gmail.com>
Date:   Tue Jul 18 14:47:53 2017 +0100

    Added type checking for array uniforms

```

**Comment by Henningstone** [comment]
@sharethewisdom that commit didn't really do anything though, besides changing the function signature, did it?

**Comment by superdump** [comment]
To my reading, it looks quite clear that this code: https://github.com/processing/p5.js/blob/master/src/webgl/light.js#L269-L315 - will overwrite the uniforms when calling `pointLight()` multiple times as only a single uniform location is used despite the shader uniforms for `uPointLightColor` and `uPointLightLocation` being arrays of vecs. I'm not sure whether one needs to keep track of, say, the vec3s of coordinates for each point light in one big array and then upload that whenever the array changes, or if one can provide an offset into the uniform to be able to upload the coordinates for the ith index in the array, if you see what I mean. I suspect the former.

**Comment by superdump** [comment]
Yeah, it looks like the WebGL uniform location objects can't handle offsets, so you'd have to either make them into many separate uniforms, or maintain an array with the colour values and coordinates for each pointLight and just reupload the complete array on every call to pointLight.
