### ISSUE TITLE
Problem with keyIsPressed documentation

### ISSUE THREAD

**Issue by F4Tornado** [processing/p5.js#2419]
#### Nature of issue?

- [ x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x ] Other - Reference

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x ] Desktop/Laptop
- [ ] Others (specify if possible)

 
#### Details about the bug: keyIsPressed always returns false in the example in the reference

- p5.js version: whatever the reference uses
- Web browser and version: Chrome
- Operating System: Windows 10 version 1709
- Steps to reproduce this:

**Comment by lmccart** [comment]
hi @F4Tornado, can you describe what the problem is?

**Comment by F4Tornado** [comment]
When I pressed a key, it stayed white, but it seems fixed now.
