### ISSUE TITLE
p5.random(arr).index suggestion

### ISSUE THREAD

**Issue by VoxLight** [processing/p5.js#2425]
#### Nature of issue?

- [ ] Found a bug
- [x] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?
...

- [ ] IO
- [x] Math
- [ ] Typography
- [ ] Utilities

...

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Feature enhancement details:

So, I recently learned of P5's Random() function capability to now take "choices"(arr[]) as an argument instead of just a range. This feature has been amazing and saves time, and makes writing code much more fluent. However, I have found a slight issue (for me at least), that forces me to write it in the old way;

```
arr1 = [1, 2, 3];
var index = random(arr1.length);
num = arr1[index];
```

If I ever need that "index" (to compare one or more array index's), I can't get it with: random(arr1).

It would be HUGE if I could do something like;

```
arr1 = [1, 2, 3];
num = random(arr1)
num.index; //and then this returns the index at which random() made it's choice

```

**Comment by limzykenneth** [comment]
If the usage is 
```
num = random(arr1)
num.index; //and then this returns the index at which random() made it's choice
```
That means `num` cannot be `1` or `2` or `3` because it needs to be an object in order to store the `index` value.

**Comment by Spongman** [comment]
...and it cannot be any object that has an 'index' property.

**Comment by sixhat** [comment]
Wouldn't it be possible to use some destructuring assignments like in eg?

```javascript
var [x,y] = (()=>{return [3,4]})();
// x is 3
// y is 4
```

in the worse case it might be possible to wrap your code in one auxiliary function.

**Comment by Spongman** [comment]
you should be careful, too. the code you quoted above:

````
var index = random(arr1.length);
````

... is invalid. index will generally be a non-integral value. and indexing an array like that will probably not be what you want.

you'll need to do something like this:

````
var index = floor(random(arr1.length));
````

**Comment by lmccart** [comment]
I think the donut function is beyond the scope of the p5.js api (we try to keep as minimal as possible) but it could be a great starting point for an addon library. see the docs here for how to create an addon: https://github.com/processing/p5.js/wiki/Libraries#creating-a-new-library
