### ISSUE TITLE
LoadString Error

### ISSUE THREAD

**Issue by matthewwicker** [processing/p5.js#2429]
Not totally sure if this is a bug or if I am just misunderstanding your API... But the exact code for load string: 
`function setup() {
    createCanvas(600, 400);
    fill(0);
    
    loadStrings("lines.txt", doText);
}

function doText(data) {
    for (var i=0; i<data.length; i++) {
        text(data[i], 5, 20*i+20);
    }
}`

with "lines.txt" in the same directory as sketch.js and index.html throws the following error: 

`Fetch API cannot load file:///Users/.../lines.txt. URL scheme must be "http" or "https" for CORS request.`

where ... is just an abbreviation I have used for the rest of the path. Any help would be appreciated! Thanks!

#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [x] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

**Comment by limzykenneth** [comment]
To be able to use the loading functions you need to run your sketch from a server environment. See [local server](https://github.com/processing/p5.js/wiki/Local-server) for instructions on how to set one up on your computer.
