### ISSUE TITLE
p5.js sketch breaks when I save it

### ISSUE THREAD

**Issue by chris-relaxing** [processing/p5.js#2430]
#### Nature of issue?
- [X] Found a bug

#### Which platform were you using when you encountered this?
- [X] Desktop/Laptop (Windows 10) Firefox. Processing 3.3.6
p5.js v0.5.16 October 11, 2017

#### Details about the bug: 
If I start up a new sketch in p5.js mode and paste in this code, it works fine. I click run and it shows the output in my browser window with no errors:

--------------------------------------
let angle = 0;

function setup() {
  createCanvas(400, 300, WEBGL);
}

function draw() {
  background(175);
  rectMode(CENTER);
  //noStroke();
  //fill(0, 0, 255);
  //rotateZ(angle);
  rotateY(angle);
  rect(0, 0, 150, 150);
  angle += 0.03;
  
}
--------------------------------------

However, if I then save this file, it no longer works. I get an error message:
SyntaxError: Expected ; but found angle
And this generally highlights the first line in the code.

**Comment by limzykenneth** [comment]
Hi @chris-relaxing, is this issue related to the web editor? If so can you move this issue over [there](https://github.com/processing/p5.js-web-editor/issues)? It may be helpful to see what the file saved out looks like.

**Comment by chris-relaxing** [comment]
@limzykenneth : Web editor? I am not sure I know what that is. I was coding in Processing 3.3.6 (the exe), in p5.js mode.

**Comment by limzykenneth** [comment]
Huh, I'm not sure if that is officially supported. If you can try finding the repo for that. As for the web editor you can find it [here](http://alpha.editor.p5js.org/).

**Comment by chris-relaxing** [comment]
I want to make sure we are talking about the same thing:

Processing environment.
![image](https://user-images.githubusercontent.com/30215910/34267890-445f6ae2-e644-11e7-9905-66f8ec937cc3.png)

p5.js mode:
![image](https://user-images.githubusercontent.com/30215910/34267903-57093344-e644-11e7-9637-8fc5134d1d6d.png)

error message:
![image](https://user-images.githubusercontent.com/30215910/34267908-5dc3d63a-e644-11e7-859d-c2883dbf7e05.png)

index.html:
![image](https://user-images.githubusercontent.com/30215910/34267924-6f1b91a2-e644-11e7-83a3-1c0f1219bf0e.png)

**Comment by chris-relaxing** [comment]
@limzykenneth Why so quick to close this? Can you confirm that what I pasted above is not supported? 
Are you even going to see this comment now that you closed the issue? Ugh! Frustrating. 

BTW: Using p5.js in the Processing environment is the only way I knew how to do this, based on Daniel Shiffman's coding train videos. If this is not supported, I am very surprised.

**Comment by limzykenneth** [comment]
Yes I’m still able to see this. Closing an issue is mainly for organizational purposes for issues that we cannot directly help with. 

The mode you are using is probably this [p5.js mode](https://github.com/fathominfo/processing-p5js-mode) for processing. Let me know if it isn’t. You can seek help with the developer of that. The video you watched of Daniel is probably a bit dated where the project is still in its early stages. His latest videos are all using text editors when p5.js is used. You can follow his tutorial with the new web editor as well and everything should still work similarly.

**Comment by chris-relaxing** [comment]
Yes, that must be it. Thank you! I didn't know of the web editor or that I could use a text editor, which is much preferable anyway. Thanks!
