### ISSUE TITLE
Block-scoped declaration error on Gruntfile.js

### ISSUE THREAD

**Issue by mlarghydracept** [processing/p5.js#2434]
- Operating System: Mac OS X 10.10.5

Apologies if this has already been addressed in the ES5-ES6 conversation and I missed it. I searched all the closed issues and saw no mention. The [let line](https://github.com/processing/p5.js/blob/master/Gruntfile.js#L99) in Gruntfile.js is causing my build to fail. The error message is:

```
Loading "Gruntfile.js" tasks...ERROR
>> SyntaxError: Block-scoped declarations (let, const, function, class) not 
yet supported outside strict mode
```
Using the `--force` flag has no impact. To ensure it was nothing on my end I downloaded a zip of the repo and followed all steps in the Development wiki with the fresh folder. It seems that it might be an npm dependency version mismatch or something.

**Comment by Spongman** [comment]
can you do an `npm install` and post the results of:

````
npm --version
node --version
````

**Comment by mlarghydracept** [comment]
so after a fresh `npm install` run-through, I am getting `2.15.9` for the npm version and `4.5.0` for the node version. If I am not mistaken it looks as though we are using a newer version of npm now.

**Comment by mlarghydracept** [comment]
It seems that my node version weren't managing properly! Sorry for the confusion.

**Comment by Spongman** [comment]
yeah, i'm running much more recent versions of node & npm.  i'll try to find the minimum required versions and put them into the `package.json`
