### ISSUE TITLE
p5.js WebGl in Codepen?

### ISSUE THREAD

**Issue by FrodoSwaggins** [processing/p5.js#2438]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.5.16
- Web browser and version: 63.0.3239.84
- Operating System: Windows
- Steps to reproduce this:
For some reason, using p5.js WebGl in Codepen does not work. A 3D object or whatever doesn't appear...

**Comment by mlarghydracept** [comment]
Can you provide a code example? Codepen WebGL links appear to be working as expected.

**Comment by Spongman** [comment]
here's one i made earlier: https://codepen.io/Spongman/pen/xpEpqd?editors=0010

**Comment by FrodoSwaggins** [comment]
Huh... I must have done something wrong...(oops)
