### ISSUE TITLE
Feature request: ellipse() with innerRadius parameter (donut shape)

### ISSUE THREAD

**Issue by kristianpedersen** [processing/p5.js#2442]
I wanna have a bunch of donuts flying around the screen, made from simple shapes.

I really wish the ellipse() function had an innerRadius parameter.

1. beginShape() + endShape() looks too aliased, even with high resolution.
2. Having a smaller ellipse inside a bigger one looks nice and smooth, but doesn't show what's behind the donut.

If anyone can help me, it would be greatly appreciated.

View sketch+code (left: custom shape / right: two ellipses): 
http://alpha.editor.p5js.org/Kristian_Pedersen/sketches/r1KtBpjzz

```javascript
const bg = [270, 100, 25];

const Donut = (x, y, r) => {
	const resolution = 1000;
	const angleStep = 180 / (resolution / 2);
	let angle = 0;

	const outsideRadius = r;
	const insideRadius = outsideRadius / 2;
	return {
		display: () => {
			stroke(255);
			fill(255);
			beginShape(TRIANGLE_STRIP);

			for (let i of Array(resolution).keys()) {
				let px = x + cos(radians(angle)) * outsideRadius;
				let py = y + sin(radians(angle)) * outsideRadius;
				
				angle += angleStep;
				vertex(px, py);
				
				px = x + cos(radians(angle)) * insideRadius;
				py = y + sin(radians(angle)) * insideRadius;
				
				vertex(px, py);
				angle += angleStep;
			}
			endShape();
		}
	}
}

let donut1;
function setup() {
	createCanvas(300, 200);
	colorMode(HSL);

	donut1 = Donut(90, 100, 50);
}

function draw() {
	background([...bg]);
  let y = map(mouseY, 0, height, 75, 125);
  line(0, y, width, y);

	donut1.display();

	fill(255);
	ellipse(210, 100, 100);
	fill(...bg);
	ellipse(210, 100, 50)
}
```

**Comment by Spongman** [comment]
https://p5js.org/reference/#/p5/beginContour

**Comment by kristianpedersen** [comment]
Thanks! I managed to make a good one.

Here it is, in the middle, with the other two for comparison:

http://alpha.editor.p5js.org/Kristian_Pedersen/sketches/Hy3J1Enfz

**Comment by lmccart** [comment]
thanks @Spongman. @kristianpedersen I think the donut function is beyond the scope of the p5.js api (we try to keep as minimal as possible) but it could be a great starting point for an addon library. see the docs here for how to create an addon: https://github.com/processing/p5.js/wiki/Libraries#creating-a-new-library
