### ISSUE TITLE
some constant reference entries displaying erroneous "and" in "Used by" entry

### ISSUE THREAD

**Issue by lmccart** [processing/p5.js#2450]
#### Nature of issue?
- [ x] Found a bug

#### Most appropriate sub-area of p5.js?
- [ x] Reference

#### Details about the bug: 

some constant reference entries are displaying "Used by" incorrectly, showing "and " preceding single function usage (example: https://p5js.org/reference/#/p5/DEGREES)

<img width="352" alt="screen shot 2017-12-23 at 6 44 04 pm" src="https://user-images.githubusercontent.com/191056/34323901-66010fd8-e811-11e7-8d2a-31b5ab9f8f52.png">

**Comment by Spongman** [comment]
doh! my bad... #2452

**Comment by lmccart** [comment]
thanks for the quick fix!
