### ISSUE TITLE
Apply current transformation to a point

### ISSUE THREAD

**Issue by aman-tiwari** [processing/p5.js#2456]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [x] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [x] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### New feature details:

It would be useful to be able to apply the current transformation matrix to a point to see what its coordinates in "world space" are, for instance to test if a shape will lie outside the screen and so don't draw it, or check what the colour of that point on the screen is in ```pixels```.

**Comment by lmccart** [comment]
same challenges as mentioned here, https://github.com/processing/p5.js/issues/2457. we won't be able to add this in the near future
