### ISSUE TITLE
Misleading comment in beginShape example

### ISSUE THREAD

**Issue by bomoko** [processing/p5.js#2461]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [ ] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

I suppose that calling this a "bug" is overkill - but I was browsing the documentation for vertex and I noticed an old comment in the beginShape() documentation that suggested that "POINT" mode doesn't work.
It does (just not yet in 3D, which I'm working on atm).

Since the example is actually working (correctly showing 4 points plotted), I think it makes sense to remove the comment.

**Comment by lmccart** [comment]
fixed with https://github.com/processing/p5.js/pull/2462
