### ISSUE TITLE
this.curFillShader.attributes.aNormal is undefined

### ISSUE THREAD

**Issue by OussamaBouchareb** [processing/p5.js#2466]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version:0.5.16 
- Web browser and version:firefox 57.0.1(64bit) 
- Operating System: Ubuntu16.04 
- Steps to reproduce this:
function setup() {
  createCanvas(windowWidth, windowHeight, WEBGL);
}

function draw(){
  background(255);
  box();
}
![screenshot from 2017-12-28 16-55-59](https://user-images.githubusercontent.com/24980901/34415798-db6fc510-ebf0-11e7-8eca-4e0dae4fb928.png)

**Comment by mlarghydracept** [comment]
Hi! Thanks for submitting an issue! I wasn't able to recreate your bug with the included code on Windows 10 with Firefox or Chrome. Unfortunately I don't have a computer with Ubuntu 16 readily available. Maybe somebody else does (though it would be strange if that were a creating a problem there) The code that you included is the only code in the sketch?

**Comment by OussamaBouchareb** [comment]
yes, and I tried it with other codes too it's still the same problem I even tried without the live web server and tried chromium, p5.js works fine but webgl isn't, I tested at get.webgl.org and both browsers support webgl.

**Comment by Spongman** [comment]
I believe this is related to attribute optimization issues, and should be fixed in #2349

**Comment by mlarghydracept** [comment]
fixed with #2349
