### ISSUE TITLE
createGraphics(), Uncaught TypeError: a.setModified

### ISSUE THREAD

**Issue by diwi** [processing/p5.js#2472]
#### Nature of issue?
- [x] Found a bug

#### Most appropriate sub-area of p5.js?
- [x] WebGL

#### Which platform were you using when you encountered this?
- [x] Desktop/Laptop

#### Details about the bug: 

- p5.js version: 0.5.16
- Web browser and version: Chrome/FireFox

#### Snippet

```javascript
var pg;
function setup() {
  createCanvas(100, 100, WEBGL);
  // pg = createGraphics(80, 80); // works
  pg = createGraphics(80,  40); // fails when w != h
}


function draw() {
  var w = pg.width;
  var h = pg.height;

  // create texture
  pg.background(255);
  pg.stroke(0,0,255);
  pg.line(0,0,w,h);

  // use texture
  background(0);
  texture(pg);
  rectMode(CENTER);
  rect(0,0,w,h);
}
```
throws: Uncaught TypeError: a.setModified is not a function

**Comment by Spongman** [comment]
I cannot reproduce this on master. I _believe_ it was fixed...

**Comment by diwi** [comment]
Indeed, the error seems to be gone there.
