### ISSUE TITLE
4D Perlin Noise

### ISSUE THREAD

**Issue by Dozed12** [processing/p5.js#2477]
#### Nature of issue?

- [x] New feature request

#### Most appropriate sub-area of p5.js?

- [x] Math

#### New feature details:

Any thoughts on implementing 4D Perlin Noise? Although it's not typically useful by itself, 4D Noise is a good way to generate Tileable 2D Noise without the distortion that other methods create.

**Comment by Siggi005** [comment]
Very good idea!
By myself I wanted to do this for 3-dimensional wind, but then I read in the reference that it can just be 3D...

**Comment by lmccart** [comment]
thanks @Siggi005! 
I think the donut function is beyond the scope of the p5.js api (we try to keep as minimal as possible) but it could be a great starting point for an addon library. see the docs here for how to create an addon: https://github.com/processing/p5.js/wiki/Libraries#creating-a-new-library
