### ISSUE TITLE
p5.Texture.js - ctor - width/height mixed up

### ISSUE THREAD

**Issue by diwi** [processing/p5.js#2480]
- [x] Found a bug
- [x] WebGL
- [x] 0.5.16

https://github.com/processing/p5.js/blob/master/src/webgl/p5.Texture.js#L50

```
this.height = textureData.width;
this.width = textureData.height;
```

this seems mixed up, ... unless it's a trick :)

**Comment by mlarghydracept** [comment]
Certainly looks mixed up :upside_down_face:
