### ISSUE TITLE
FFT Sample Size

### ISSUE THREAD

**Issue by ccorcos** [processing/p5.js#2485]
#### Nature of issue?

- [ ] Found a bug
- [x] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other (specify if possible)
  - [x] Sound

#### Which platform were you using when you encountered this?

- [x] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Feature enhancement details:

Currently the maximum FFT sample size is 2048. It would be really cool if we could support higher sample sizes. 

Looking around [the code](https://github.com/processing/p5.js/blob/master/lib/addons/p5.sound.js#L2513), I'm not able to understand where the 2048 buffer size limitation is. It sounds like we should be able to set the [analyzer fft size](https://developer.mozilla.org/en-US/docs/Web/API/AnalyserNode/fftSize) much higher. If you can point me in the right direction, I'd be happy to jump in and make a PR. 

Anyways, I'm trying to make music visuals and higher accuracy would make them way better :)

https://ccorcos.github.io/circle/

Thanks guys!

**Comment by lmccart** [comment]
This issue was moved to processing/p5.js-sound#237
