### ISSUE TITLE
The bug of left-click when some keys are down

### ISSUE THREAD

**Issue by mayoneko** [processing/p5.js#2487]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [x] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.5.16
- Web browser and version: Chrome 63.0.3239.84
- Operating System: Windows10 64bit
- Steps to reproduce this: 

When some keys are down, left-click don't return no reactions.
Some keys are for example '1' , '2' , 'a' , 'SPACE' or anything except 'Alt' , 'Ctrl' or 'Shift'.
My code is here.
```javascript
function setup() {
	createCanvas(windowWidth, windowHeight);
	background(100);
}

function draw() {
	ellipse(mouseX, mouseY, 20, 20);
}

function mousePressed(){
	if(mouseButton===LEFT){
		print("hoge");      //When some keys(1, x, a or etc...) are down, this line won't work.
	}
}
```
If it is not only on my computer, please fix this problem.

**Comment by Spongman** [comment]
strange. i'm not seeing it, though:

https://codepen.io/Spongman/pen/JMJeZL?editors=0011

**Comment by mayoneko** [comment]
This page makes the same probrem too. What is wrong with that?

**Comment by Spongman** [comment]
do you have any chrome extensions enabled? maybe try with firefox or edge?

**Comment by mayoneko** [comment]
firefox and edge were same.
when '1' or 'd' key was down, left-click didn't print.

**Comment by mayoneko** [comment]
sorry... this is on windows touchpads error, and it solved with change settings.
https://support.microsoft.com/en-us/help/2907018/button-clicks-for-internal-touchpads-and-pointing-sticks-are-not-respo
sorry for bothering you. thank you.

**Comment by Spongman** [comment]
Ah! That's good to know. Thanks for the info!
