### ISSUE TITLE
webgl: directionalLight is inverted

### ISSUE THREAD

**Issue by Spongman** [processing/p5.js#2490]
compared to Processing, at least, `directionalLight` seems to result in light coming from the opposite direction than specified.

````
directionalLight(255, 255, 255, 1, 1, 1);
````

p5.js vs processing:
![image](https://user-images.githubusercontent.com/1088194/34544814-6f3db5ee-f09d-11e7-8fa0-1340f3068b6e.png)

https://codepen.io/Spongman/pen/YYxvdQ?editors=0010

**Comment by kjhollen** [comment]
processing multiplies the direction by -1 in the shader but we don't! should be an easy update.

**Comment by Spongman** [comment]
ok, i have fixed this in the per-pixel-lighting PR (#2490) since it also affects the phong shader.

**Comment by mlarghydracept** [comment]
fixed by #2449
