### ISSUE TITLE
webgl: line() seems not to be working in 3D

### ISSUE THREAD

**Issue by villares** [processing/p5.js#2495]
#### Nature of issue?
- [X] Found a bug

#### Most appropriate sub-area of p5.js?
- [X] WebGL

#### Which platform were you using when you encountered this?
- [X] Desktop/Laptop

#### Details about the bug: 

- p5.js version: p5.js v0.5.7  
- Web browser and version: Safari 11.0.2 and Firefox 57.0.3
- Operating System: Mac OS
- Steps to reproduce this:

```
function setup() {
  createCanvas(110, 110, WEBGL);
}

function draw() {
  background(200);
  stroke(255, 0, 0); // not required to the bug, but used on the screenshot provided
  strokeWeight(10); // same
  line(-100, 0,-100, 100, 0, 100);
}
```
#### result on my system
![screen shot 2018-01-05 at 2 03 44 am](https://user-images.githubusercontent.com/3694604/34595347-5bfc9992-f1be-11e7-9402-40be446e8479.png)

#### expected (works on the reference site! I believe it uses p5.js v0.5.16)
![screen shot 2018-01-05 at 2 02 49 am](https://user-images.githubusercontent.com/3694604/34595361-718d9b1c-f1be-11e7-9077-049c120327bb.png)

####  might be related
I'm unable to make `stroke()` and `strokeWeight()` work on other primitives;
`BeginShape(TRIANGLE_STRIP);` makes a sketch freeze/go very slow; and`triangle()` seems not to be working right in 3D/WEBGL.

**Comment by mlarghydracept** [comment]
Hi! The version of p5 that you are using is too old for those features. [Try the latest](https://p5js.org/download/) (0.5.16).
