### ISSUE TITLE
How to Update p5?

### ISSUE THREAD

**Issue by IamDiversity** [processing/p5.js#2506]
I'm here because I watched a video and seen someone talking about the new "foreach loop" that's been added and I want to use it but i have to update p5 i think for that, so i checked on internet but i've found nothing :/

Can anyone tell me how to update it to have the new features please ?

**Comment by Zalastax** [comment]
Could you link to the video? I think they might have been talking about the [for ... of](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of) loop which you can use without updating p5, you just need a modern browser.

**Comment by IamDiversity** [comment]
https://www.youtube.com/watch?v=Y8sMnRQYr3c&lc=z22xi3t4pzvjwf5qx04t1aokgzrxu3ydc440bkfksecnrk0h00410.1513483600310329

Here it is , but i just realized that it's not called a "foreach loop" in javascript but a "for loop"

**Comment by Zalastax** [comment]
Great!
You can use the [for ... of loop](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of) in any modern browser. The browsers that support for ... of are detailed in the "Browser compatibility" of the [for ... of loop](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of) page. If you want to support older browsers it becomes a [fair bit more advanced](https://babeljs.io/). You won't need to update the p5 library in any case 😃

**Comment by IamDiversity** [comment]
Thank you for your help ^^


________________________________
De : Pierre Krafft <notifications@github.com>
Envoyé : lundi 8 janvier 2018 01:02
À : processing/p5.js
Cc : IamDiversity; Author
Objet : Re: [processing/p5.js] How to Update p5? (#2506)


Great!
You can use the for ... of loop<https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of> in any modern browser. The browsers that support for ... of are detailed in the "Browser compatibility" of the for ... of loop<https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of> page. If you want to support older browsers it becomes a fair bit more advanced<https://babeljs.io/>. You won't need to update the p5 library in any case 😃
