### ISSUE TITLE
webgl: artifact caused by edge z adjustment

### ISSUE THREAD

**Issue by Spongman** [processing/p5.js#2510]
here, the red face is behind the green face, but its edge appears in front (neither faces are transparent):

![image](https://user-images.githubusercontent.com/1088194/34647613-5971d952-f33b-11e7-8f8b-a05e8eb6950f.png)

````
function setup() {
  createCanvas(windowWidth, windowHeight-4, WEBGL);
  stroke(255, 255, 255);
}

function draw() {
  background(0);
  
  fill(255, 0, 0);
  rect(-100, -100, 200, 200, 1, 1);

  translate(0, 0, 0.5);
  fill(0, 255, 0);
  rect(0, 0, 200, 200, 1, 1);
}
````
https://codepen.io/Spongman/pen/YYEJjy?editors=0010

**Comment by mlarghydracept** [comment]
Hm this is probably happening because of how the shader is avoiding z-fighting between the stroke and face. Could you try this with your branch that is using the latest Processing shader?

**Comment by Spongman** [comment]
good call. it looks like the processing shader doesn't have this issue.
