### ISSUE TITLE
processing-compatible 3d setup?

### ISSUE THREAD

**Issue by Spongman** [processing/p5.js#2514]
i was playing around with increasing Processing compatibility somewhat.

i was wondering if there's any interest in a PR that makes the following 'just work' ?

````
function setup() {
  size(500, 500, P3D);
}
function draw() {
  translate(width/2, height/2);
  sphere(150);
}
````

ie. the `size()` function works, the `P3D` constant works, and it configures the 3d renderer to use a processing-compatible camera so the sphere appears in the appropriate location. the existing `WEBGL` constant would continue unaffected.

**Comment by limzykenneth** [comment]
I'm not very in tune with webgl mode's development so let me know if I misunderstood or missed something. Why not make the existing webgl mode's have a processing compaticle camera? ie. why not directly implement what you are thinking about for a `P3D` renderer directly in the webgl renderer?

**Comment by Spongman** [comment]
See #2347 for the reason for the WEBGL mode. I think it makes sense to keep the WEBGL for those reasons and to maintain compatibility with existing p5.js code. This is mainly an attempt to provide assistance for people porting from processing, not really for new code.

**Comment by Spongman** [comment]
It would definitely use he same renderer. It would just remember the mode that was used to create it and initialize the default camera accordingly. Maybe I'll just submit a PR, the code will be clearer than my nonsense English ;)

**Comment by lmccart** [comment]
my preference would be to leave things as is. the goal with p5.js is not to offer a port, but a reinterpretation. it's important to keep the freedom to deviate from processing, so this library can be looking to the future rather than locked to the past.

**Comment by lmccart** [comment]
it would be nice to list the change in this wiki page though https://github.com/processing/p5.js/wiki/Processing-transition
