### ISSUE TITLE
Q: continuously deployed master?

### ISSUE THREAD

**Issue by Spongman** [processing/p5.js#2521]
I wonder if it would be helpful to have Travis automatically build/deploy the master branch somewhere (either just the libs, or the docs, too) in order to help issue creators verify fixes?

Maybe it could be instrumented with a watermark somehow to discourage people using it in 'production' ?

**Comment by lmccart** [comment]
I like the idea a lot but want to balance it against complexity of processes going on. I already feel that the grunt and release items are a lot and difficult for me to keep a handle on and maintain. While this would be helpful, for simplicity sake, I'd prefer to stick with just asking developer to pull the latest changes and build locally for testing.

**Comment by Spongman** [comment]
Ok
