### ISSUE TITLE
Variable fonts support

### ISSUE THREAD

**Issue by thomgb** [processing/p5.js#2522]
#### Nature of issue?

- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Typography

Hey all, 

The `text('sometext', x, y);` only uses the default parameters of the fonts. Since we have now variable fonts there is no way to access these in the current version. Please correct me if I am wrong.

**Variable what?**
Variable font are font files with additional data. Short explanation: one font file with a whole font family inside.
Variable font have so called _axes_ and these have a _default value_, _minimum value_ and _maximum value_. 

**Axes**
An axis has a tag, name and the values
example: weight, wght, 0 1000 200

A reasonable way to handle these variation is just like colours. There is a current state and all the thing you do will have this state. Until you change them...
This way the `text()` function will not change at all.
We only need a way to set the state of a font:
`fontVariations()`
As arguments something like: `wght=394, wdth=4` 

I have little experience with javascript, I come from python-land. But these variable fonts are ideal for browser environments. 

Please join this discussion and hopefully get this thing working :)

All the best,
enjoy! 

Thom

look at this!: https://www.axis-praxis.org

**Comment by limzykenneth** [comment]
I think it is a very exciting feature and worth investigating. Unfortunately, due to being relatively new, browser support are rather spotty (with [Chrome having more reliable support than others](https://caniuse.com/#search=variable%20fonts)). I don't think at this moment we will be considering implementing this in p5.js itself due to the lack of browser support but I would think making a addon library is a feasible middleground and we can merge in the addon later once browser support improves.

**Comment by thomgb** [comment]
Indeed not all browsers are supporting it yet. But... The nice thing about Variable fonts is how it works: if the environment is not supporting the variable data in the font it fallback to the default (is normal font) of the variations. Nothing breaks, no errors, just no variations...

**Comment by limzykenneth** [comment]
@thomgb Yes, there should be no problem using the fonts themselves, it's just that something like `fontVariations()` would probably have no effect on the browsers not supporting it. That being said, I'm not sure if the HTML canvas font rendering API have the same support as CSS/HTML generally but I assume so.

**Comment by thomgb** [comment]
O yes what renders the fonts... That is a thing indeed. Various tests showed that Safari uses CoreText while Chrome uses something of its own (Chrome is better) But these tests is all just plain HTML and CSS (like axis-praxis.org), I know nothing about canvas behaviour.

**Comment by lmccart** [comment]
very interesting. given that it's relatively new in browsers and a bit beyond the p5 scope, this sounds like great territory for an addon library.  see the docs here for how to create an addon: https://github.com/processing/p5.js/wiki/Libraries#creating-a-new-library

**Comment by HiImDaniel-type** [comment]
Any news in this topic? Is there any javascript library that can work with variable fonts already ?

**Comment by Mark2Mark** [comment]
The referencing in all discussing issues is an endless loop. If you follow any links that claim "it has been discussed here" you’ll always see the same answer and eventually come back to where you started, without finding an actual issue that’s left open.

Just want to make you aware that the implementation of Variable Fonts might get lost. It should not, Variable Fonts are no marginal fun technology anymore and implemented in all major browsers for a while. Processing is predestined for variable fonts. While I could help with implementing in Objective-C, I have no clue for how to contribute for Java, though

**Comment by dhowe** [comment]
I _think_ the result of several discussions on this topic is that it should first be implemented as a library... 

Has anyone tried this (perhaps there is a prototype underway)? If not, is there some reason why it cannot be implemented, at least initially, this way?

**Comment by limzykenneth** [comment]
#5607 is the current open issue tracking this and there are plans to look into this as part of GSoC. Please continue discussion there instead. Thanks.
