### ISSUE TITLE
Typo on Reference for Filter ("Guassian" instead of "Gaussian")

### ISSUE THREAD

**Issue by abangfarhan** [processing/p5.js#2526]
The title says it all. Found the typo on https://p5js.org/reference/#/p5/filter
The correct word is Gaussian, not Guassian.

From the page:
> BLUR Executes a **Guassian** blur with the level parameter specifying the extent of the blurring. If no parameter is used, the blur is equivalent to **Guassian** blur of radius 1. Larger values increase the blur.

**Comment by Benjamin-Davies** [comment]
I have fixed it
#2535

**Comment by lmccart** [comment]
thanks!
