### ISSUE TITLE
Lost default fill/stroke in WebGL

### ISSUE THREAD

**Issue by mlarghydracept** [processing/p5.js#2527]
We lost the default fill/stroke in WebGL. It used to default to white fill with black stroke. Now it seems to be defaulting to black fill with no stroke. I don't have a chance to look into this right now but it seems possible that this happened with  #2511. Any insights @Spongman ?

**Comment by Spongman** [comment]
do you have a repro? i have this:

````  
function setup(){
  createCanvas(400, 400, WEBGL);
}

function draw(){
  background(0);
  sphere(150);
}
````

gives this:
![image](https://user-images.githubusercontent.com/1088194/34798701-fe70e5a0-f611-11e7-9f6e-87e8a598391d.png)

**Comment by mlarghydracept** [comment]
Oh! My apologies. I was editing some tests in the chrome developer tools not realizing that the live update feature was causing this to happen.

**Comment by Spongman** [comment]
phew! ;-)
