### ISSUE TITLE
smooth/noSmooth not defined in WebGL

### ISSUE THREAD

**Issue by micuat** [processing/p5.js#2528]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [x] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.5.16
- Web browser and version: Chrome 63.0.3239.132 (Official Build) (64-bit)
- Operating System: Windows 10
- Steps to reproduce this:

```
function setup() { 
  createCanvas(400, 400, WEBGL);
} 

function draw() { 
  background(220)
  smooth();
  rectMode(CENTER);
  rect(100, 100, 100, 100);
}
```

https://alpha.editor.p5js.org/micuat/sketches/rk_KIxV4f

WebGL Primitives are discussed [here](https://github.com/processing/p5.js/issues/2226#issuecomment-356707969). As described `smooth` is not defined and terminates the script - but it should instead give a friendly error. There's a workaround for smoothing in Webgl but never implemented as `smooth` function https://github.com/processing/p5.js/issues/2250

**Comment by kjhollen** [comment]
I want to propose that smooth/noSmooth in the WebGL renderer can be functions that just defer to `this.setAttributes('antialias', true);` or `this.setAttributes('antialias', true);`. a call to push/pop before & after may also be required. this can probably go right into src/webgl/p5.RendererGL.js
