### ISSUE TITLE
weblg: rotate[XYZ] doesn't take angleMode into account

### ISSUE THREAD

**Issue by Spongman** [processing/p5.js#2533]
as noted in #2524, currently the 3D rotate functions don't take `angleMode` into account when calculating the angle.

````
angleMode(DEGREES);
rotateZ(45);
rect(-100, -100, 200, 200);
````

this leads to an inconsistency with the way the 2d `rotate` function works.

**Comment by Spongman** [comment]
this was fixed with #2552

**Comment by Spongman** [comment]
turns out this problem still exists.

**Comment by lmccart** [comment]
should be fixed now with https://github.com/processing/p5.js/pull/3077
