### ISSUE TITLE
change arc() documentation to match other 2D primitives

### ISSUE THREAD

**Issue by bmoren** [processing/p5.js#2546]
#### Nature of issue?

- [ ] Found a bug
- [x] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?
- [ ] Color
- [x] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Feature enhancement details:

I'm not totally sure if this should be in the website repo or here

currently the documentation for arc specifies `arc(a,b,c,d,start,stop,[mode])`
I propose we change this to `arc(x,y,w,h,start,stop,[mode])` to reflect the standards in the other 2D primitives.

**Comment by Spongman** [comment]
ironic that the function prototype itself actually matches what you proposed:

````
p5.prototype.arc = function(x, y, w, h, start, stop, mode) {
````
