### ISSUE TITLE
Perfomance slow down in v0.5.14 or v0.5.16

### ISSUE THREAD

**Issue by joeyklee** [processing/p5.js#2549]
#### Nature of issue?

- [ ] Found a bug
- [X] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [X] Other (specify if possible) ==> Performance issues in v0.5.14 & v0.5.16

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [X] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: v0.5.14 & v0.5.16
- Web browser and version:  Tested with chrome 64.0.3282.85 (64-bit) and firefox 57.0.4 (64-bit) 
- Operating System: macbook pro with os x 10.12.
- Steps to reproduce this:
+ Please see discussion here: https://github.com/generative-design/Code-Package-p5.js/issues/161#issuecomment-358035000
+ You can run the `test` in [pre-release](https://github.com/generative-design/Code-Package-p5.js/tree/pre-release) branch to see the differences in performance between v0.5.12 and v0.5.14+
+ v0.5.12 seems to perform faster by 2x compared to v0.5.14+

#### Feature enhancement details:
It would be great to check the performance slow down in the latest versions compared to v0.5.12

Many many thanks! ❤️💜💚

**Comment by limzykenneth** [comment]
@joeyklee The performace slow down may be due to the extra parameter validations that we do as part of the [Friendly Error System](https://github.com/processing/p5.js/wiki/Friendly-Error-System). If for the sketch you have in mind performance is an issue, you can try switching out to use the p5.min.js package or in the beginning of your own code include this line:
```
p5.disableFriendlyErrors = true;
```

**Comment by joeyklee** [comment]
@limzykenneth wow! Thanks for your speedy response. I will give this a try and see if there's any improvements in the latest versions. Thanks so much!

**Comment by limzykenneth** [comment]
Happy to help! I'm going to close this issue now, feel free to reopen if problem persist.

**Comment by joeyklee** [comment]
Thanks a bunch! as a closing note, I should mention it does indeed feel snappier. 🌈🎉
