### ISSUE TITLE
Inaccurate description in Friendly Error System page

### ISSUE THREAD

**Issue by limzykenneth** [processing/p5.js#2550]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Wiki

In the [Known Limitations](https://github.com/processing/p5.js/blob/master/developer_docs/friendly_error_system.md) section of the Friendly Error System doc, at the bottom of the section mentioned:

> Only detects an error in loadXML and loadTable when the file is requested as a url and not as a file path. I think this has to do with the reqwest library as documented here: https://github.com/ded/reqwest/issues/177

which is no longer accurate (we don't use reqwest anymore and I believe the limitations are not limited to `loadXML` and `loadTable` only). I'm not familiar enough with the behaviour of FES so if someone more familiar with it can edit this section it would be great!

**Comment by Spongman** [comment]
I believe this limitation still exists and is due to the fact that the correct signatures of these functions (and httpDo also) cannot be statically determined without looking at the values of the passed parameters. The value of one parameter can change the types/number of other parameters.

**Comment by limzykenneth** [comment]
@Spongman yes that's what I understand, do you think you can make the relevant edits regarding the functions not covered by FES yet?

**Comment by Spongman** [comment]
I'm not sure about he complete set of non-FES-checked functions, some that set is somewhat ad-hoc at the moment.

I have a pending PR #2471 that automatically applies FES to _every_ public documented method, except for a short list of these troublesome methods.

Is like to avoid manually checking every method to build this list of that PR has any chance of being merged, sine it would make that work unnecessary.

**Comment by kjhollen** [comment]
just a note here that this documentation has been moved to developer_docs/friendly_error_system.md but still needs updating :)
