### ISSUE TITLE
soundFile starts playing without beeing started

### ISSUE THREAD

**Issue by decurus** [processing/p5.js#2551]
EDIT: sorry I only now realized I posted this to the wrong forum. this belongs to the p5.sound. can anyone move it properly?

Hey guys,

```
var song;

function preload(){
  song = loadSound('media/sample.wav');
}

function setup() {
  //erstellt ein leeres Fenster in welches man zeichnen kann
    createCanvas(640,480);
    song.loop();
    song.pause();
}

function draw() {
  background(127);

  fill(200,123,0);
  rect(0, 0, width, 100);
  if(mouseIsInCanvas()){
    song.rate(map(mouseX, 0, 640, 0, 1));
    song.setVolume(map(mouseY, 0, 480,1,0));
  }
}

function mousePressed() {
  if(!song.isPlaying()&&mouseIsInCanvas())song.play();
}
function mouseReleased(){
  if(song.isPlaying())song.pause();
}

function mouseIsInCanvas(){
  return (mouseX >= 0 && mouseX <= 640 && mouseY <= 480 && mouseY >= 100);
} 
```

This code works very well: the sound plays back when pressing the mouse button, it stops, wenn I release it, volume and rate are set properly.
BUT
when you change the line 
`song.rate(map(mouseX, 0, 640, 0, 1));`
to
`song.rate(map(mouseX, 0, 640, -1, 1));`
to make everything play backwards and you move the mouse to the left area (which of course lets the sound play backwards) the song might start without pressing the mouse button. Even more funny: if you then press the mouse and therefore start the file, it starts a NEW loop. now you can release, the already looping sound does not stop and when you move the mouse to the left again, another new loop might start. And so on. I mean with some delay it sounds pretty awesome, but it is not what you might expect. Any Ideas?
Cheers
Benny

**Comment by lmccart** [comment]
This issue was moved to processing/p5.js-sound#247
