### ISSUE TITLE
WEB GL 3D camera crash this code : "plane(x, y);" in v. 0.5.16 (in v. 0.5.14 all fine)

### ISSUE THREAD

**Issue by Worseize** [processing/p5.js#2554]
#### Nature of issue?
- [x] Found a bug
#### Most appropriate sub-area of p5.js?
- [x] WebGL
#### Which platform were you using when you encountered this?
- [x] Desktop/Laptop
#### Details about the bug: 

- p5.js version:  https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.5.16/p5.js
It working  in version --> https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.5.14/p5.js

- Web browser and version: On Chrome
- Operating System:  Windows 10
- Steps to reproduce this:
new p5();
let graphics, myText;

function setup(){
  myCanvas = createCanvas(innerWidth - 30, innerHeight - 30, WEBGL);
  myText = createGraphics(200, 200);
  graphics = createGraphics(1, 1);
}

function draw(){
  background(155,255,255);
  myText.background(155,155,155);
  myText.textSize(20);
  myText.fill(255);
  myText.textAlign(CENTER);
  myText.text("controls", myText.width / 2, myText.height / 2);
  texture(myText);
  plane(200,200);
  camera(0,0,10, 0,0,0, 0,0,1);
}

**Comment by Spongman** [comment]
i believe this is fixed in the current master branch.

your `camera()` parameters will need fixing though: you can't have a camera looking in that direction that has that 'up' vector.
