### ISSUE TITLE
How to use shader() and loadShader()

### ISSUE THREAD

**Issue by hackertron** [processing/p5.js#2556]
Hello , i am trying to create example for shader() and loadShader() . 
** shaders that i am using are the one provided in webgl/shaders folder
Code : 
```javascript
var s;
function setup() {
  // put setup code here

  createCanvas(windowWidth, windowHeight, WEBGL);
    s = loadShader("line.vert","line.frag");
}

function draw() {
  // put drawing code here

  background(255);
  shader(s);
   //  draw some figure here ex : box() ;
}
```
Errors i am getting  

> p5.min.js:37 Yikes! An error occurred compiling the vertex shader:ERROR: 0:1: 'undefined' : syntax error

> Uncaught TypeError: Failed to execute 'useProgram' on 'WebGLRenderingContext': parameter 1 is not of type 'WebGLProgram'.

I am not sure if i am even doing this correctly since there is no example for these functions . 

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

**Comment by Spongman** [comment]
my guess is that it's failing to load the `line.vert` file. there may need to be some additional error checking before attempting to compile the shader in order to give a more useful message.

maybe try putting the `loadShader` call in a `preload()` function?

**Comment by hackertron** [comment]
hey i put  `loadshader()` in `preload()` . there was no error this time .  
but if i call any function like box() or line() i get this error 

> Uncaught (in promise) TypeError: Cannot read property 'location' of undefined

My guess  : either box() , line() or any other similar function like this should not be used here . 

But with `preload()` there was no error . now how to actually demonstrate the use of `shader()` and `loadShader()`

```javascript
var s;

function preload() {

   s = loadShader("line.vert","line.frag");
}
function setup() {
  // put setup code here

  createCanvas(windowWidth, windowHeight, WEBGL);
}

function draw() {
  // put drawing code here

  background(255);
  shader(s);
  //box();
   //  draw some figure here ex : box() ;
}
```

**Comment by Spongman** [comment]
I believe you're now seeing the same issue as #2262. There's an interim build you can download in that issue's comments. Or you can clone&built p5.js yourself.

**Comment by hackertron** [comment]
Okay , but is my example right ? i was trying to create this example for docs .

**Comment by lmccart** [comment]
this will be included in the next release, working on it now
