### ISSUE TITLE
Remove instance fails with "Cannot read property 'elt' of undefined" when using setAttributes

### ISSUE THREAD

**Issue by amicoleo** [processing/p5.js#2557]
On instance mode and WEBGL, if I use the `setAttributes` function, I have a problem when I dismiss the sketch with 'remove'. The consoles prints this 

```
Uncaught TypeError: Cannot read property 'elt' of undefined
    at e.<anonymous> (p5.min.js:32)
    at HTMLDivElement.<anonymous> ((index):40)
    at HTMLDivElement.dispatch (jquery.min.js:3)
    at HTMLDivElement.q.handle (jquery.min.js:3)
``` 

and the sketch doesn't get removed at all. 

Also, when creating the instance, the js console outputs 'p5.RendererGL: enabled webgl context' twice. Maybe something gets created twice?  

#### Nature of issue?

- [X] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [X] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.5.16
- Web browser and version: Chrome 63.0.3239.132
- Operating System: MacOS Sierra 10.12.6
- Steps to reproduce this:

Mouse click on the page once to launch the sketch. Click again for dismissing it. 
It works just if the `p.setAttributes('antialias', true)` line is commented. 

```html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Test</title>

	<style>
	.generative-element{
	  width: 100vw;
	  height: 100vh;
	}
	</style>
</head>

<body id="home">

  <div class="generative-element" id="div0"></div>

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.5.16/p5.min.js"></script>

  <script>

	var p5Test = null
	var p5SketchTest = function( p ) {
		p.setup = function() {
			p.createCanvas(window.innerWidth, window.innerHeight, p.WEBGL)
			p.setAttributes('antialias', true) //NO ISSUE IF THIS LINE COMMENTED
		}

		p.draw = function() {
			p.background(0)
			p.box()
		}
	}

	$("#div0").click(function(){
		if (p5Test == null){
			p5Test = new p5(p5SketchTest, "div0")
		}else{
			p5Test.remove()
			p5Test = null
		}
	})

	</script>
</body>
</html>

```

**Comment by Spongman** [comment]
the duplicate 'enabled webgl context' message is expected. the context is re-created when you call `setAttributes`.

using master, i cannot reproduce the error you were seeing, so i believe this was fixed a while back.

**Comment by amicoleo** [comment]
Thanks for checking that. Indeed, I switched to v. 0.6 and it's now working fine. Issue was in the version v. 0.5.16 I was previously using.
