### ISSUE TITLE
404 on http://p5js.org/reference/assets/mammals.csv

### ISSUE THREAD

**Issue by keebOo** [processing/p5.js#2559]
#### Nature of issue?
404 on CSV file for https://p5js.org/reference/#/p5/loadTable

table = loadTable("http://p5js.org/reference/assets/mammals.csv","csv", "header");

#### Most appropriate sub-area of p5.js?
- [x] IO

**Comment by lmccart** [comment]
fixed https://github.com/processing/p5.js-website/commit/e1b6aedcf5102d08be1e51d31f740ce99aa8e601
