### ISSUE TITLE
Flashing 3d box in WEBGL mode when using alpha values for colors.

### ISSUE THREAD

**Issue by pishleback** [processing/p5.js#2560]
#### Nature of issue?

- [X] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [X] Color
- [X] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [X] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug:

- p5.js version: 0.5.16
- Web browser and version: FireFox 57.0.4
- Operating System: Windows 10

- Steps to reproduce this:

running this code:

function setup() {
  createCanvas(200, 200,WEBGL);
}
function draw() {
  background(0);
  stroke(255, 255, 255);
  strokeWeight(6);
  colorMode(RGB)
  fill(255, 0, 0, 128);
  rotateX(frameCount * 0.01);
  rotateY(frameCount * 0.01);
  box(75, 75, 75);
}

The online editor draws a rotating box with 50% transparency however it flashes very quickly flipping between the box and a black background very fast. In contrast when I remove the alpha value in the fill statement or set it to 255 as in this code:

function setup() {
  createCanvas(200, 200,WEBGL);
}
function draw() {
  background(0);
  stroke(255, 255, 255);
  strokeWeight(6);
  fill(255, 0, 0);
  rotateX(frameCount * 0.01);
  rotateY(frameCount * 0.01);
  box(75, 75, 75);
}

The box is drawn as I would expect.
Additionally the stroke that makes up edges of the box appears to be drawn "behind" the face when the alpha value is not 255, but in front of it when it is 255.

Also if I remove the statement which draws the background the box no longer flashes, however there is of course no longer a black background.

**Comment by Spongman** [comment]
looks like this was fixed with #2511
