### ISSUE TITLE
registerPreloadMethod mechanism is broken

### ISSUE THREAD

**Issue by Spongman** [processing/p5.js#2568]
0.6.0: https://p5js.org/reference/#/p5/loadModel

the sketch never starts because `_incrementPreload()` is called twice, once for the wrapped `loadModel` call, and once more for `loadStrings`. and `_decrementPreload()` is only called once.

it has something to do with the reference docs site, because if you copy that sketch to its own .html file it works fine - the `loadStrings` doesn't result in `_incrementPreload()` getting called.

**Comment by Spongman** [comment]
ok, so on further investigation it turns out that the difference is caused by the fact that the p5 instance is not global.

when the p5 instance is global it's the `window`'s methods that are wrapped with the preload refcounting stuff. so when `loadModel` calls `loadStrings` it's calling the _real_ `loadStrings`, and everything loads a completes as intended.

however, when the p5 is _not_ global, it's the p5 instances _own_ methods that are wrapped, so when so when `loadModel` calls `loadStrings`, it's calling the _wrapped_ method. this causes a double `_preloadCount` increase which never then reaches zero.

**Comment by Spongman** [comment]
i changed the title because there's a larger issue here: the registerPreloadMethod mechanism breaks when p5 is used in non-global (instance) mode.

the problem is as above: if any preload method (including those registered using `registerPreloadMethod `) calls another wrapped method then this will result in multiple calls to `_incrementPreload`, but only one of these is resolved with a matching `_decrementPreload` call.

the fix I suggested above would work for those methods that are statically delcared in `p5.prototype._preloadMethods`, but any that are dynamically added via `registerPreloadMethod` could still trigger this bug.

**Comment by meiamsome** [comment]
This sounds bad.
If no one else minds, I would be interested in taking this on and converting the preloads to all use promises under the hood. I suggest this would involve adding `loadXPromise(..)` versions of each of the current loading functions and having the older `loadX(...)` functions be mapped onto them, perhaps along the lines of the following snippet, that should be able to keep backwards compatibility viable. 
```javascript
p5.prototype.loadX = function() {
  var ret = {};
  ret.promise = p5.loadXPromise.apply(this, arguments);
  ret.promise.then(function() {
    // Set properties on ret like before
  });
}
```

In the future, we could then deprecate the use of the return directly and prefer to use `loadX().promise.then(ret => variable = ret)` and after a long deprecation time we could convert to something like the following:

```javascript
p5.prototype.loadX = function() {
  var ret =  p5.loadXPromise.apply(this, arguments);
  ret.promise = ret;
}
```

And then deprecate the use of `.promise`. I think this makes sense from a future standpoint where we get rid of the current `loadX` behaviour but that is a somewhat desirable feature. Perhaps it may even be a good idea to let `preload` return a promise. This would let users do

```javascript
let file1, file2;
async function preload() {
  file1 = await loadJSON(...);
  file2 = await loadString(...);
}
```

Which would be relatively new user friendly I think. [Browser support](https://caniuse.com/#search=await) is getting there for async/await so I think this is actually viable in the near future. 

It is notable, however that using `await` like this would actually cause the loads to be called one-by-one, so perhaps this is not the best solution.

**Comment by Spongman** [comment]
i don't think using promises is going to fix the issue here, and i don't think it's worth compromising compatibility yet just to include them here.

the problem is not the async mechanism being used. the issue is the preload method refcounting mechanism.

**Comment by meiamsome** [comment]
I know, I am just saying that both outcomes are desirable and mess with the same part of the same codebase. I would like to see this fixed, but also see promises, but I'd rather re-implement the management mechanism with promises for the simplicity it will add as well as fixing bugs on the way

There is no direct loss with compatibility with my implementation suggestion - it will behave the same to the end user and we are already polyfilling Promise so I don't see why you suggest there would be.

**Comment by Spongman** [comment]
i guess i don't see how using promises would fix the bug.

**Comment by meiamsome** [comment]
You're probably right, really. I'll move that discussion to another issue.. 

I actually started looking at this issue, and actually `loadModels` never calls `this._decrementPreload`, so that's where the issue's from (BTW, If you had promises, individual load function wouldn't need to handle calling that after them). I'll do a PR for this minor fix and move discussion to a new issue.

**Comment by Spongman** [comment]
i'm not it's as simple as making `loadModels` call `_decrementPreload`. the behavior is different between instance and global mode...

**Comment by meiamsome** [comment]
Ah, I didn't realise you already have code to work on this - I was working while discussing. You're right, of course, my preferred fix would be to path both of those issues (#2697)

**Comment by Spongman** [comment]
yeah, i think your fix is better.

**Comment by lmccart** [comment]
fixed with https://github.com/processing/p5.js/pull/2697
