### ISSUE TITLE
Move the TypeScript definitions files for global mode to a more convenient place

### ISSUE THREAD

**Issue by Zalastax** [processing/p5.js#2572]
A convenient way to get typesafety when using p5 is to reference the definition files in your JavaScript file.
```JavaScript
/// <reference types="p5/lib/p5.global-mode" />
const col = color(255); // is type checked and knows that col is p5.Color
```
@pflannery [suggests](https://github.com/processing/p5.js/commit/09eed169d54aefdea8ca41f34860a815eefd8f03#r27004820) making the global mode definitions more easily available, and I quoute:
> It could probably be improved if "p5.global-mode.d.ts" was renamed to "global.d.ts" so the statement becomes
types="p5/lib/global", or even better if we moved the file and could state something simple like types="p5/browser" as the reference.

We can for sure rename the file to just global, but is it also possible to move it oustide the lib folder? I don't want to make the build script/folder layout too complicated. To me, a rename and some good documentation seems best.

**Comment by kjhollen** [comment]
I'm closing this because #2571 is the plan for typescript support. thank you for offering to take care of the migration, and I hope the master's thesis wraps up smoothly @Zalastax!
