### ISSUE TITLE
TypeScript stroke definition missing

### ISSUE THREAD

**Issue by rdelpeso** [processing/p5.js#2575]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other (specify if possible)

TypeScript Typings Generation.

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: NPM p5.js v0.6.0 January 19, 2018
- Web browser and version: Not Applicable
- Operating System: (Not really applicable) Linux Centos7 + xfce4 + Visual Studio Code 1.20.0-insider
- Steps to reproduce this:

While using p5.js in a typescript project, attempting to call the method stroke with a single parameter (Grayscale integer value) typescript complaints that there is no definition for the shape of method calling.

    stroke(0)
    // [ts] Argument of type '0' is not assignable to parameter of type 'Color'.

After tracing through the p5.d.ts I noticed that the following definition is missing:

    declare class p5 {
    ...
      /**
      *   Sets the color used to draw lines and borders 
      *   around shapes. This color is either specified in 
      *   terms of the RGB or HSB color depending on the 
      *   current colorMode() (the default color space is 
      *   RGB, with each value in the range from 0 to 255). 
      *   The alpha range by default is also 0 to 255.  If a 
      *   single string argument is provided, RGB, RGBA and 
      *   Hex CSS color strings and all named color strings 
      *   are supported. In this case, an alpha number value 
      *   as a second argument is not supported, the RGBA 
      *   form should be used. 
      * 
      *  
      *   A p5 Color object can also be provided to set the 
      *   stroke color.
      *
      *   @param gray specifies a value between white and
      *   black
      *   @param [a] opacity of the background relative to
      *   current color range (default is 0-255)
      *   @chainable
      */
      stroke(gray: number, a?: number): p5;
    ...
    }

I cobbled together the above by merging the existing background(gray: number, a?: number): p5; definition together with the documentation from stroke.

The same issue occurs in p5.global-mode.d.ts, the function definition for stroke(number, number?) is also missing.

The problem here is that if you have typescript in strict mode and want to compile with no errors, there is no way to write stroke(0) or stroke(0, 125), since the typings are missing for it. Instead you must result to writing stroke(0,0,0) and stroke(0,0,0,125) respectively to bypass the error.

I am not sure how the typing files are being generated currently, so i wanted to bring up the issue to confirm if it is just me that missed something or if others have encountered the same issue. When i have a bit more time I will dive through the code and hopefully provide a pull request to address this issue.

Thanks

**Comment by kjhollen** [comment]
Thank you for reporting this. Typescript support will soon be moved to an independent repository. Future issues can be addressed there. Please see #2571 for a detailed discussion.
