### ISSUE TITLE
PrintWriter.flush has confusing name

### ISSUE THREAD

**Issue by Spongman** [processing/p5.js#2581]
I believe that `PrintWriter.flush()` should be renamed to `clear()` or `reset()` or something similar. the name `flush` implies functionality similar to:

- https://docs.oracle.com/javase/8/docs/api/java/io/OutputStream.html#flush--
- http://python-reference.readthedocs.io/en/latest/docs/file/flush.html
- http://man7.org/linux/man-pages/man3/fflush.3.html
- https://msdn.microsoft.com/en-us/library/system.io.stream.flush(v=vs.110).aspx
- toilets

essentially "_ensure any internally buffered data is written to the output_".

however, `PrintWriter.flush()` just clears the internal buffer without writing. and this might be misleading to people familiar switching to/from other APIs. it might be impossible to implement `flush` properly in the browser (without doing some [ServiceWorker magic](https://www.npmjs.com/package/streamsaver)).

obviously backward compatibility issues in play - although i can't imagine any real application of `flush()` as it currently stands. food for thought.

**Comment by carolinehermans** [comment]
Agreed, I left `flush()` out of the PrintWriter examples I was creating because I couldn't figure out what it did. It behaves differently than `flush()` in other languages or even the Java Processing. +1 for `clear()` or `reset()`

**Comment by hackertron** [comment]
Well when i was looking at the  `flush()` method on p5 site , there was no description about it . I assumed it to be something similar to `C++ flush ` but it was not .  So  later  i just tried it in `sketch.js` file and to me it looked like it just clears the content of the object .

**Comment by limzykenneth** [comment]
> * toilets

I laughed pretty hard at this...

In all seriousness, I agree that `flush` isn't really descriptive enough as a function name and can be misleading. However for backwards compatibility, we can just make a `clear` function as an alias of `flush`. Maybe we can start thinking about how we deprecate functionalities.

**Comment by lmccart** [comment]
I agree it's confusing! we are still under 1.0 so in my opinion it'd be fine to make minor changes like this without aliasing deprecated functions. i think this helps us keep the code a little simpler and more maintainable. I think clear() makes sense with the rest of the API.
