### ISSUE TITLE
WEBGL - when used in createGraphics() - light position does not get updated

### ISSUE THREAD

**Issue by ogoossens** [processing/p5.js#2586]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 
When working with WEBGL in a createGraphics environment and population that to a standard P5.js canvas with image() function - some functions may not work as in a normal P5.js WEBGL sketch.

For example I have noticed that the position of pointLight() gets not updated in the sketch, even when I clearly has changed. Is populates light from the original location and that does no change. What I figured "refreshes" the light position, is when I call the function createGraphics() again (but that slows down the performance by a lot).

I made two examples that I ran in the P5 editor sketch. They are and should work identical, but actually don't:

```
function setup() {
  createCanvas(100, 100, WEBGL);
}

function draw() {
  background(0);
  directionalLight(250, 250, 250, mouseX-50, 0, 10);
  sphere(25);
}
```

versus

```
var a;

function setup() {
	createCanvas(200, 200);
	a = createGraphics(100, 100, WEBGL);  
}

function draw() {
	// Calling createGraphics on each draw() "helps", kinda
	// Uncomment the next line and see for yourself
	// a = createGraphics(100, 100, WEBGL);  
	
        background(60);
	a.resetMatrix();
	a.background(0);
	a.directionalLight(250, 250, 250, mouseX-50, 0, 10);
        a.sphere(150);
	image(a,0,0);
}
```

- p5.js version: 
https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.6.0/p5.min.js

- Web browser and version: 
Firefox 57.0.4 64-bit

- Operating System: 
Win 10 - 64bit

- Steps to reproduce this:
Just test the first code and than the second code here : https://alpha.editor.p5js.org/

**Comment by Spongman** [comment]
yup, that's a bug! it looks like the `_update()` method isn't getting called for off-screen webgl canvases (although i'm not sure if it should, anyone?), and the directional light array for that renderer is just overflowing.

try the following:

    //a.resetMatrix();
    a._renderer._update();

**Comment by ogoossens** [comment]
That 
`a._renderer._update();`
seems to be working :-) 

Thank you

**Comment by stalgiag** [comment]
going to work on this re discussion in #3079
