### ISSUE TITLE
reduce webgl missing examples noise in build

### ISSUE THREAD

**Issue by kjhollen** [processing/p5.js#2593]
#### Nature of issue?

- [x] Existing feature enhancement

#### Most appropriate sub-area of p5.js?

- [x ] WebGL

The new missing example output when building / running grunt is great. It reveals that a bunch of gl methods that are library-internal & not requiring examples are not listed as such:

these are the ones that could be quieted, but the four others should stay:

`
src/webgl/p5.Geometry.js:54: method p5.Geometry.computeFaces missing example
src/webgl/p5.Geometry.js:87: method p5.Geometry.computeNormals missing example
src/webgl/p5.Geometry.js:116: method p5.Geometry.averageNormals missing example
src/webgl/p5.Geometry.js:137: method p5.Geometry.averagePoleNormals missing example
src/webgl/p5.Geometry.js:226: method p5.Geometry.normalize missing example
src/webgl/p5.RendererGL.Immediate.js:19: method p5.RendererGL.beginShape missing example
src/webgl/p5.RendererGL.Immediate.js:61: method p5.RendererGL.vertex missing example
src/webgl/p5.RendererGL.js:573: method p5.RendererGL.get missing example
src/webgl/p5.RendererGL.js:601: method p5.RendererGL.loadPixels missing example
src/webgl/p5.Texture.js:123: method p5.Texture.update missing example
src/webgl/p5.Texture.js:232: method p5.Texture.bindTexture missing example
src/webgl/p5.Texture.js:245: method p5.Texture.unbindTexture missing example
`

I'll take care of this shortly!

**Comment by Spongman** [comment]
i think a generous sprinkling of `@private` attributes should do the trick!
