### ISSUE TITLE
gl unit test failure: check activate and deactivating fill and stroke

### ISSUE THREAD

**Issue by kjhollen** [processing/p5.js#2597]
#### Nature of issue?

- [x] Found a bug

#### Most appropriate sub-area of p5.js?

- [x] WebGL

One of the WebGL unit tests doesn't pass. Here's what it says:

```
AssertionError: fill shader still active after noFill(): expected false to be true
    at Function.assert.isTrue (http://localhost:8000/node_modules/chai/chai.js:2483:31)
    at Context.<anonymous> (unit/webgl/stroke.js:50:14)
```

**Comment by Spongman** [comment]
it looks to me like the test is wrong. shouldn't it be

      myp5.noFill();
      ...
      assert(
        !myp5._renderer._doFill,     // <----- this is negated
        'fill shader still active after noFill()'
      );
