### ISSUE TITLE
reference docs contain syntax for constructors that should probably be hidden

### ISSUE THREAD

**Issue by Spongman** [processing/p5.js#2601]
in the reference docs there are pages for the constructors of classes in the library whose class page needs to exist (because it contains a description of the class and lists its members), but whose constructor probably shouldn't be advertised since there are other correct methods of instantiating objects of those classes, and the constructor definition exposes hidden implementation details of the library innards.

for example, the `p5.Font` page describes a constructor that takes a `pInst` parameter, however it's probably _never_ correct for a user of the library to call this constructor, they should instead be pointed to the `p5.prototype.loadFont()` function which hooks everything up correctly.

the following docs pages have the similar issues:
- https://p5js.org/reference/#/p5.Color (should use `color()` to ensure correct `colorMode` handling)
- https://p5js.org/reference/#/p5.Graphics (should use `createGraphics()`)
- https://p5js.org/reference/#/p5.TypedDict (shouldn't be directly constructed)
- https://p5js.org/reference/#/p5.NumberDict (should use `createNumberDict()`)
- https://p5js.org/reference/#/p5.Image (should use `createImage()`)
- https://p5js.org/reference/#/p5.PrintWriter (should use `createWriter()`)
- https://p5js.org/reference/#/p5.Vector (should use `createVector()` for correct `angleMode` handling)
- https://p5js.org/reference/#/p5.Font (should use `loadFont()`)
- https://p5js.org/reference/#/p5.Texture (maybe should be hidden entirely)
- https://p5js.org/reference/#/p5.Element (should use `createElement()` or other tag-specific methods)

------

my proposed solution involves removing the `@constructor` attribute from the constructor's doc comments, and adjusting the docs preprocessor and routing code to handle showing pages for public, constructorless classes correctly.

**Comment by lmccart** [comment]
this sounds right on to me
