### ISSUE TITLE
requesting sound files saved to mp3

### ISSUE THREAD

**Issue by sagitarious12** [processing/p5.js#2603]
#### Nature of issue?

- [ ] Found a bug
- [X] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [X] Other (specify if possible)

p5.sound module.

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [ ] Desktop/Laptop
- [X] Others (specify if possible)
Not relevant

#### Details about the bug: 

- p5.js version: v0.3.5
- Web browser and version: Chrome
- Operating System: Mac
- Steps to reproduce this: no steps

**Comment by lmccart** [comment]
you might check out this library, which seems like it might do what you want:
https://github.com/Audior/Recordmp3js
