### ISSUE TITLE
IE11/Edge Support

### ISSUE THREAD

**Issue by aarangop** [processing/p5.js#2604]
#### Nature of issue?

- [x] Found a bug

#### Most appropriate sub-area of p5.js?

- [x] Core

#### Which platform were you using when you encountered this?

- [x] Desktop/Laptop

#### Details about the bug: 

When loading p5.js scripts on IE Edge or IE11 I am getting an 'unable to get property' error that comes form p5.js. Unfortunately, there is no call stack to see if there is something upstream that could have caused the error.

- p5.js version: 0.5.4 & 0.6.0 
Tried both versions and both showed the same behavior.
- Web browser and version: IE11 / Edge
No problems on chrome and firefox
- Operating System: Windows 10
It seems the same error doesn't occur on Windows 7, which has been tested by other colleagues.

- Steps to reproduce this:

The error is reported on line 15863 when trying to access the x property of acceleration.

15861   p5.prototype._ondevicemotion = function (e) {
15862       this._updatePAccelerations();
15863       this._setProperty('accelerationX', e.acceleration.x * 2);
15864       this._setProperty('accelerationY', e.acceleration.y * 2);
15865       this._setProperty('accelerationZ', e.acceleration.z * 2);
15866       this._handleMotion();
15867   };

I appreciate your support :)

**Comment by Spongman** [comment]
can you provide a little more information about how you're loading p5?

i'm not seeing any errors on IE11 (v 11.192.16299.0) or Edge ( 41.16299.15.0) on my win10 (10.0.16299.192) box.

here's the sketch i tried: https://codepen.io/Spongman/pen/JMLVdo
