### ISSUE TITLE
missing not implemented renderer messages.

### ISSUE THREAD

**Issue by Spongman** [processing/p5.js#2607]
several `p5.prototype` methods that call into the underlying renderer do not correctly handle the case when that renderer does not implement the required functionality, leading to exceptions.

for example, this leads to a `Cannot read property 'apply' of undefined` exception:

      createCanvas(500, 500, WEBGL);
      text("", 0, 0);

and this leads to a `this._renderer._useLightShaders is not a function` exception:

      createCanvas(500, 500);
      pointLight(0, 0, 0, 0, 0, 0);

**Comment by kjhollen** [comment]
Can you clarify the scope of this issue, @Spongman? Methods that are missing (but need implementation) in Web GL mode are mostly have individual issues open already to make it easier for people to find and self-assign tasks. Should this focus on issues that won't (ever) be implemented in the 2D or 3D modes?

**Comment by Spongman** [comment]
yes, mostly for methods that don't make sense in both renderers, but also i think it's worth providing better error messages for those methods whose implementations are not coming any time soon.

**Comment by lmccart** [comment]
I think this has been addressed. Functions now print messages like `pointLight() is only supported in WEBGL mode`. Let's open individual issues for any methods that are not correctly routed or messaged.
