### ISSUE TITLE
WEBGL: Cylinder broken in 0.6.0?

### ISSUE THREAD

**Issue by ogoossens** [processing/p5.js#2612]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 
Please see:
https://p5js.org/reference/#/p5/cylinder 

I don't think this is how a Cylinder should behave, or is this some new design?

**Comment by Spongman** [comment]
you're right, that's a bug! it was fixed in #2579

**Comment by ogoossens** [comment]
Thank you! :-)

One more question : Where do I get the latest build of P5 with this fix? Is there any resource please?

**Comment by Spongman** [comment]
there aren't any interim release published, but you can build it yourself pretty easily:

````
git clone --depth 0 https://github.com/processing/p5.js.git
cd p5.js
npm install
npm build
ls -l ./lib
````

**Comment by ogoossens** [comment]
Thank you very much for your support.

Closing this issue :-)
