### ISSUE TITLE
p5.js integration with Angular / not using global functions

### ISSUE THREAD

**Issue by dragonflypl** [processing/p5.js#2614]
In tutorials & youtube channel all examples use sketch.js & global functions & canvas / video tags are automatically created by library. Is there a way to manually create "p5.js context", pass it video & canvas tag and use API on some global object? I would like to write my p5.js code inside my components.

**Comment by limzykenneth** [comment]
@dragonflypl Perhaps, [instance mode](https://github.com/processing/p5.js/wiki/Global-and-instance-mode) is what you are looking for? If not maybe include an example code of what are you thinking of for your use case? Thanks!
