### ISSUE TITLE
visual glitch due to z-buffering and transparent textures

### ISSUE THREAD

**Issue by Spongman** [processing/p5.js#2616]
this is just a quick issue to track the fact that z-buffering and semi-transparent textures don't mix. the z-buffer kills subsequently-drawn more-distant pixels, even if the buffered pixel is semi-transparent. the only effective solution is depth-sorting which is probably out of scope.

this is illustrated in the transparentTexture manual test (duplicated here: https://codepen.io/Spongman/pen/eVNOoj?editors=0010)

this repros in 0.5.16 and master since #2610. it's not visible in 0.6.0 because it's masked by #2608.

**Comment by stalgiag** [comment]
This occurs in Processing as well. Adding the "will not fix" label for the above mentioned reasons (depth sorting is out of scope). This label and the "known issue" label will be used to close (for organization purposes) known issues that will not be fixed.
