### ISSUE TITLE
rebuilding the library has no influence on lib/empty-example

### ISSUE THREAD

**Issue by shinytang6** [processing/p5.js#2617]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: v0.6.0
- Web browser and version:  Chrome
- Operating System:  Windows 8
- Steps to reproduce this:

when using ```npm run grunt watch:quick``` to automatically rebuild the library, l think it only rebuilds the p5.xx.js, not the p5.xx.min.js.
l belive p5.js/lib/empty-example/index.html should be:
```
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0>
    <style> body {padding: 0; margin: 0;} </style>
    <script src="../p5.js"></script>
    <script src="../addons/p5.dom.js"></script>
    <script src="../addons/p5.sound.js"></script>
    <script src="sketch.js"></script>
  </head>
  <body>
  </body>
</html>
```

**Comment by shinytang6** [comment]
lf it's necessary, l would be glad to take this as my first contribution:)

**Comment by shinytang6** [comment]
lf it's necessary, l am glad to quickly fix it:)

**Comment by limzykenneth** [comment]
That is the intended behaviour, `grunt watch:quick` as the name implies is just for a quicker build process while watching the source files and are not meant to be used to generate the final files that goes into the `lib` folder. If you run `grunt watch:main` it will create the minified versions as well. 

For distributing the project as `p5.js-complete.zip` we simply zip up the `lib` folder, which is what it is meant for more or less, and before that the full build step is run to which will generate both versions of the library from source.

**Comment by shinytang6** [comment]
Thank you for your explanation and sorry for my haste：）

Just a small advice：l think lib/empty-example is a convenient place for new same as me to test the code,  actually it confused me a few minutes when my changes didnt apply to the browser, so maybe adding some annotations or improving the documents of the installation part is much better？

**Comment by limzykenneth** [comment]
No worries. We have a [development wiki](https://github.com/processing/p5.js/wiki/Development#setup) that hopefully covers most of the points needed to  get a build and test it but if you think it is lacking, feel free to suggest edits!

Personally, how I usually test p5.js is having a dedicated test sketch folder at the same level as the p5.js repo folder and every time I build I chain a command to copy over the contents of the `lib` folder to my test folder where I want them to be. It is a bit more of a hassle to setup but it gives me more flexibility: I can test against the latest fix or the latest release on the fly, include assets in the test folder that can be loaded in etc. But I imagine there's a different preferred setup for everyone here... 😉

**Comment by Spongman** [comment]
i usually edit test/manual-test-examples/sketch.js (which uses the un-minified p5.js), then after running `grunt connect watch:quick`, i can navigate to http://localhost:9001/test/manual-test-examples/empty-example/
