### ISSUE TITLE
save() for text results in 1 char per line

### ISSUE THREAD

**Issue by SeltonMurakami** [processing/p5.js#2629]
I have a string which I want to save, let's call it 
```
str = "this is a string"
```
When I try the following:
```
save(str, "text.txt");
```

And the resulting text.txt file is like:
```
t
h
i
s

i
s

a

s
t
r
i
n
g
```

**Comment by Spongman** [comment]
try this:

    save([str], "text.txt");

**Comment by SeltonMurakami** [comment]
It's works great! Thanks man
