### ISSUE TITLE
Flow Types

### ISSUE THREAD

**Issue by j6k4m8** [processing/p5.js#2633]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [x] New feature request

#### Most appropriate sub-area of p5.js?

- [x] Other: **Code organization** (npm module)

#### New feature details:
I am using p5 for a large(ish)-scale project with multiple developers, and we've adopted [Flow](https://flow.org) to help us keep track of types and validate our code. In the process, **we're drafting out type declarations for the p5 core codebase and we'd love to contribute these back to the p5 community if they're useful to others.**

Do you have preferences for how we contribute these? We're happy to host a public GitHub repo, pull-request into this repo, etc.

----

I'm tagging https://github.com/processing/p5.js/issues/2571 because this is related to the Typescript implementation but we can't quite use identical code.

**Comment by limzykenneth** [comment]
I don't think we are likely to merge Flow definitions into this repo itself as even now there are planning to move Typescript definitions out into its own repo. What I would suggest is that if you are interested, you can host the definitions on a separate repo on your own and open an issue letting us know where we can find these definitions, then we can include the links to that repo along with the Typescript ones.

**Comment by j6k4m8** [comment]
Excellent — I'll post again here once these are online. Would you prefer I close this issue in the meantime?

**Comment by limzykenneth** [comment]
Great, thanks!

**Comment by dellaert** [comment]
Jordan, I'm very interested in flow types as well. Was a separate repo ever created? If so, where can I find it?

**Comment by j6k4m8** [comment]
This is in progress! We'll hopefully publish something shortly; I'll reach
out once something public exists.
ᐧ
