### ISSUE TITLE
missing semicolon in object example

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [processing/p5.js#2635]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other (docs)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 
https://p5js.org/examples/objects-objects.html missing semicolon in Jitter object

**Comment by montoyamoraga** [comment]
hi @Abdur-rahmaanJ 
you mean on the last line here, after the curly bracket?

this.display = function() {
    ellipse(this.x, this.y, this.diameter, this.diameter);
}

or somewhere else?

**Comment by Abdur-rahmaanJ** [comment]
yes after this.display(){...}

**Comment by limzykenneth** [comment]
There shouldn't be a semicolon after the final curly bracket as well

**Comment by Abdur-rahmaanJ** [comment]
yes

**Comment by TanviKumar** [comment]
I'd be glad to be assigned this issue so I can fix it and send in a PR asap!

**Comment by TanviKumar** [comment]
This is fixed in [p5.js website repository PR #171](https://github.com/processing/p5.js-website/pull/171)
