### ISSUE TITLE
HELP !!

### ISSUE THREAD

**Issue by nomiliveson** [processing/p5.js#2636]
VERY BASIC

**trying to play multiple audio files simultaneously, but they play back at different times

also it has a pharrell-like 4 count start before playing..**
code:

var playerRate = 1;

function preload() {

song1 = loadSound('assets/melody1.mp3');
song2 = loadSound('assets/melody2.mp3');
song3 = loadSound('assets/melody3mp3');
song4 = loadSound('assets/melody4.mp3');
song5 = loadSound('assets/melody5.mp3');

}

function setup() {
createCanvas(windowWidth, windowHeight, WEBGL);

song1.playMode('restart');
song2.playMode('restart');
song3.playMode('restart');
song4.playMode('restart');
song5.playMode('restart');

}

function draw() {

if (key == '1') {

song1.loop();
song2.loop();
song3.loop();
song4.loop();
song5.loop();
}

}

Please Help

Thank U <3 X O

**Comment by lmccart** [comment]
hi @nomiliveson I would try moving your key check and song.loop() calls to a mousePressed() function. it's likely that they are restarting with every frame of draw as long as your finger is down, causing weird delays.

for the future, the github issues here are a good place for bugs and issues with the p5.js library itself. for questions about writing your own code, tests, or following tutorials, the [forum](https://forum.processing.org/two/) is the best place to post. thanks!
