### ISSUE TITLE
incorrect documentation for processPeaks()? (p5.sound)

### ISSUE THREAD

**Issue by DigitalData** [processing/p5.js#2637]
#### Nature of issue?

- [ ] Found a bug
- [x] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 
- Web browser and version: 
- Operating System: Windows 10 Pro
- Steps to reproduce this:
 I just have no idea how to actually get a value out of processPeaks(); It returns undefined with code like this:
Audio is my soundfile...

tempo = audio.processPeaks(function(){
      audio.play();
      print(tempo);
      playing = true;
    });

**Comment by Spongman** [comment]
I think there's a bug in the docs for this method. They indicate that it returns an array of timestamps, where in fact the array of timestamps is passed as a parameter to the callback function.

**Comment by lmccart** [comment]
This issue was moved to processing/p5.js-sound#254

**Comment by Spongman** [comment]
btw: to get your code to work, you need to do this:

````
audio.processPeaks(function(tempos){
  print(tempos);
});
````
