### ISSUE TITLE
saveCanvas('myfile', 'png') downloads files as "myfile.myfile"

### ISSUE THREAD

**Issue by Ucodia** [processing/p5.js#2638]
`saveCanvas('myfile', 'png')` is supposed to download the canvas as a PNG file named `myfile.png` but instead downloads as `myfile.myfile`.

p5.js version: 0.6.0

#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [x] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

**Comment by lmccart** [comment]
fixed with #2651
