### ISSUE TITLE
Feature request: lights() function from Processing

### ISSUE THREAD

**Issue by EndBug** [processing/p5.js#2645]
**Nature of issue?**
- [x] New feature request.

**Most appropriate sub-area of p5.js?**
- [x] Lights, Camera

**New feature details:**

In Processing there's a function (`lights()`) that quickly creates a good light effect. You can reproduce it in p5, but it's not as easy and quick as `lights()`.
It would be good to have this function in p5 too.

**Comment by Spongman** [comment]
this is part of #2547

**Comment by EndBug** [comment]
Oh, sorry, I didn't see that.
I'm glad that someone is trying to add this function, are you going to split it and try to pull request again?

**Comment by kjhollen** [comment]
Someone can take this on by creating the new method in src/webgl/p5.RendererGL.js and just having it call `this.ambientLight(128, 128, 128)` and `this.directionalLight(128, 128, 128, 0, 0, -1)` to match the Processing behavior, more or less. some adjustments to the direction might be necessary.

**Comment by Spongman** [comment]
you can just take the code from #2547. it's already tested and working.

**Comment by IceDune** [comment]
@EndBug @Spongman @kjhollen , can i work on this pls?

**Comment by stalgiag** [comment]
Help is still needed with this. The todo is add a function called `lights` that calls the other light functions as @kjhollen explains above. #3112 can be looked at for some clues on how to do example docs and manual tests, but the method only needs to do what is outline in @kjhollen 's comment above.

**Comment by EndBug** [comment]
Hi guys! Seeing the last comment and the interest that this issue gained I decided to try it myself with PR #3553 
At the moment works in Node 10 but has failed the test for Node 8: can someone help me figure out why?

**Comment by stalgiag** [comment]
Hi @EndBug this was unrelated to your code. I restarted the build. This time it was successful. I will open an issue. If this happens again restart the Travis CI build.
