### ISSUE TITLE
translate() does not work inside beginShape/endShape of an createGraphics object.

### ISSUE THREAD

**Issue by eccker** [processing/p5.js#2647]
#### Nature of issue?
- [X ] Found a bug
#### Most appropriate sub-area of p5.js?
- [X] Core
#### Which platform were you using when you encountered this?
- [X] Desktop/Laptop
#### Details about the bug: 
- p5.js version: 0.6.0
- Web browser and version: Google Chrome | 64.0.3282.140 (Build oficial) (64 bits) (cohort: 64_140_win)
- Operating System: Windows 10 / 64 bits
- Steps to reproduce this:
In the following code, when translate() is applied to myCanvas object (createGraphics object) inside the beginShape/endShape, it only draws the first vertex. Without translate() it draws all the vertex almost as expected (well, with a shift).

let r1;
let r2;
let m1;
let m2;
let a1;
let a2;
let myCanvas;

function setup() {
	createCanvas(windowWidth, windowHeight);

	// dynamically calculate the size of the pendulum
	r1 = height/4;
	r2 = height/4;
	m1 = width/32;
	m2 = width/32;
	a1 = PI/8;
	a2 = PI/4;
	pixelDensity(1);
	myCanvas = createGraphics(width, height);
	myCanvas.beginShape();
	    myCanvas.background(128);
	myCanvas.endShape();
}

function draw() {
	image(myCanvas, 0, 0);
	stroke(10);
	strokeWeight(2);
	translate(width/2,height/8);
	let x1 = r1 * sin(a1);
	let y1 = r1 * cos(a1);
	let x2 = x1 + r2 * sin(a2);
	let y2 = y1 + r2 * cos(a2);
	fill(0);
	line(0, 0, x1, y1);
	ellipse(x1, y1, m1, m1);
	line(x1, y1, x2, y2);
	ellipse(x2, y2, m2, m2);
	a1 += 0.05;
	a2 -= 0.07;

	myCanvas.beginShape(POINTS);
		myCanvas.translate(width/2, height/8);
		myCanvas.stroke(255, 204, 0);
		myCanvas.strokeWeight(4)
		myCanvas.vertex(x2,y2)
	myCanvas.endShape();
}
![image](https://user-images.githubusercontent.com/5886200/36187634-a82af582-1114-11e8-968f-95fc82340f65.png)

If I use push/pop instead of begin/endShape and ellipse instead of vertex, translate just works fine.
![image](https://user-images.githubusercontent.com/5886200/36187657-cd3d79f8-1114-11e8-9f32-0522e367f117.png)

**Comment by Rud156** [comment]
Add a `push` and `pop`.
```js
myCanvas.beginShape(POINTS);
    myCanvas.push();
    myCanvas.translate(width/2, height/8);
    myCanvas.stroke(255, 204, 0);
    myCanvas.strokeWeight(4);
    myCanvas.vertex(x2,y2);
    myCanvas.pop();
  myCanvas.endShape();
```

You may need to fix the translate positions BTW

**Comment by kjhollen** [comment]
It looks like this was a specific code question that has been solved, so I'm going to close this issue. Please re-open if this isn't the case. :)

**Comment by sflanker** [comment]
Just in case somebody winds up here for the same reason I did...

For the record, neither p5js, nor Java version of processing, support calls to translate() (or other transformation functions) in between calls to vertex while drawing a shape with beginShape/endShape. The title of this GitHub isn't really appropriate for the problem the OP was having (it sounds like they just weren't using translate correctly). However, push/pop or no, it is still the case that code like the following will not work:

```javascript
  // I expected this code to draw a green square
  push();
  // This translation would be respected by the shape if we specified vertices normally
  translate(mouseX, mouseY);
  fill('limegreen')
  beginShape();
  vertex(0, 0);
  // However because we're trying to use translate and then place vertices at the new origin, it doesn't work
  translate(100, 0);
  vertex(0, 0);
  translate(0, 100);
  vertex(0, 0);
  translate(-100, 0);
  vertex(0, 0);
  endShape(CLOSE);
  pop();
```

However, if you do want to use transformation functions with calls to vertex() you can always roll your own transformation matrix code: https://editor.p5js.org/Kumu-Paul/sketches/pBTvceh_d
