### ISSUE TITLE
Why running a ".pde" file on a browser throws an error like: Uncaught Type Error: cannot read property 'function_name' at Processing.Processing.Draw

### ISSUE THREAD

**Issue by Shubham-19** [processing/p5.js#2649]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [ ] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 
- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

**Comment by limzykenneth** [comment]
.pde files are Processing only and will not work in p5.js. Have a look at [Processing transition](https://github.com/processing/p5.js/wiki/Processing-transition) for some transition guide.
