### ISSUE TITLE
p5 Problem CreateGraphics and beginDraw

### ISSUE THREAD

**Issue by KeremTurkyilmaz** [processing/p5.js#2650]
Hi, I'm a beginner in the coding world and I have a problem to convert a Processing Skecht in p5.

The problem is when I call the beginDraw function that not exist in p5, I think.
  
c.beginDraw();
c.ellipseMode(CENTER);
c.noFill();
c.stroke(255, 255, 255, 30);
c.strokeWeight(0.1);
c.ellipse(0,0, 40, 40);
c.endDraw();

**Comment by Rud156** [comment]
`begin draw` function does not exists as it is not required. P5JS instead relies directly on the graphics object to draw.

Just remove `begin draw` and you'll be fine.
Refer to this example: https://p5js.org/examples/structure-create-graphics.html

**Comment by KeremTurkyilmaz** [comment]
@Rud156 Thank you, I solved the problem with push() and pop(), I don't know why but it works
