### ISSUE TITLE
Array Splice as described on the P5 reference vs. Splice as used in Shiftmann's video

### ISSUE THREAD

**Issue by Funkybo0dah** [processing/p5.js#2652]
#### Nature of issue?

- [ ] Found a bug
- [X ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ X] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [X ] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 
- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

#### Feature enhancement details:

In the P5.JS reference for array functions, the splice function is written as function that inserts values into an existing array, whereas Dan Shiftmann uses the splice function to remove objects in his videos. https://www.youtube.com/watch?v=HXOD_XDA-KU

He also uses it differently: array.splice(position of array element to be removed, number of array elements to be removed)

Versus currently on the reference, the invocation is splice(list,value,position).

Grateful if these sort of confusing directions on how to use splice can be unified!

Thank you!
Jason

**Comment by lmccart** [comment]
these are actually two different functions. dan is using the [Array.splice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/splice) function which is not part of the p5.js library, but is just plain JS. the p5.js array() function has somewhat different functionality and use. we are planning to remove all array functions from p5.js and rely on native JS ones soon though, so the confusion should be further alleviated at that point. thanks for reporting!

**Comment by lmccart** [comment]
these are actually two different functions. dan is using the [Array.splice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/splice) function which is not part of the p5.js library, but is just plain JS. the p5.js array() function has somewhat different functionality and use. we are planning to remove all array functions from p5.js and rely on native JS ones soon though, so the confusion should be further alleviated at that point. thanks for reporting!
