### ISSUE TITLE
Create Dash/Zeal documentation

### ISSUE THREAD

**Issue by nietaki** [processing/p5.js#2653]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [x] New feature request

#### New feature details:

p5.js is a great starting point for people discovering processing and programming in general. What could make it even more beginner-friendly would be a well-structured and searchable documentation. I know about https://p5js.org/reference/ but it's not as convenient as it could be. However, generating a [Dash](https://kapeli.com/dash)-format documentation shouldn't be overly complicated.

This issue is basically re-opening https://github.com/processing/p5.js/issues/1757: 

> I'm using Dash for offline documentation and have all my documentation quickly accessible with the different shortcuts that the application provides.
I'm suggesting you make a contribution to it: https://kapeli.com/docsets#contributetodash
>
> That would be awesome!
>
> I know wikis are accessible on Dash, but your wiki is less structured than your documentation / reference and would love to find you there!

**Comment by limzykenneth** [comment]
I'm not too sure about Dash being beginner friendly as it looks like another tool they need to download and learn to use but I don't deny the value it will provide. However, I think our response will be the same as #1757 which is we are unable to support it at this time. If you are keen, you are welcomed to create unofficial Dash documentation if that is a possibility.

**Comment by lmccart** [comment]
thanks @limzykenneth, I agree with this perspective.
