### ISSUE TITLE
frameRate() on Firefox/Linux maxes out at 10

### ISSUE THREAD

**Issue by DavidRegev** [processing/p5.js#2656]
#### frameRate() doesn’t go beyond 10 on Firefox on Linux

- [x] Found a bug

#### Most appropriate sub-area of p5.js?

- [x] Environment

#### Which platform were you using when you encountered this?

- [x] Desktop: _Ubuntu 17.10_

#### Details about the bug: 

- p5.js version: _0.6.0_
- Web browser and version: _Firefox 56 and Firefox Nightly 2018-02-17_
- Operating System: _Ubuntu 17.10, x64_
- Steps to reproduce this:
```
function setup() {
	frameRate(60);
}
function draw() {
	print(frameRate());
}
```
Running the above code, the console repeatedly shows `10`. There does not seem to be any way of making p5.js run any faster. This does not occur on Windows, nor does it occur on Android. It’s only on Linux, and it occurs both on Firefox and Firefox Nightly.

**Comment by lmccart** [comment]
are you using p5.js or p5.min.js? the p5.min.js is optimized to run faster because it doesn't include the friendly error helper functionality.
the print commands will also slowdown the framerate.

**Comment by DavidRegev** [comment]
The result is the same with both p5.js and p5.min.js. The purpose of the `print()` command was to assess how fast p5.js was running, since I noticed that it was running noticeably slower than in Chrome for some scripts.

I don’t think it’s a matter of slowness: the framerate is _exactly_ 10, and no amount of adjusting can make it any higher than that. It’s the same if I remove the `frameRate(60);` line, but I wanted to show that setting it manually higher than 10 doesn’t help. I can make it lower than 10, but anything higher than 10 seems impossible.

I also don’t think it’s my machine, since I get much higher framerates on Windows on the same machine and even on my Android phone (in Firefox).

**Comment by meiamsome** [comment]
I experience no issue on FF 58/Ubuntu 17.10 (Which is between FF 56 and FF Nightly.) It would impy to me that the browser thinks your screen's refresh rate is 10Hz... 
Could you post the output of `xrandr` when typed into the terminal?
Could you follow this guide on any webpage and see what FPS Firefox is running at normally: https://developer.mozilla.org/en-US/docs/Tools/Performance/Frame_rate
If it is above 10, could you do this on a page with your code and see if it is different?
Finally, what happens if you just print the framerate without setting it first?

**Comment by DavidRegev** [comment]
1. `xrander` output:
```
Screen 0: minimum 320 x 200, current 1920 x 1080, maximum 8192 x 8192
XWAYLAND0 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 310mm x 170mm
   1920x1080     59.96*+
```

2. I used the Performance tab with the record button on a page that runs only `print(frameRate())`. Assuming I did that right, I got a `max` fps of 60, `min` of 25.97, and and `avg` of 45.13. Meanwhile, the console still shows almost only `10`, but it did show some lower numbers a few times.

3. With only `print(frameRate())` it still just shows `10` over and over.

I hope this information is helpful. Thanks!

**Comment by Spongman** [comment]
My e it's just the console that is rate-limited?

Try writing the 'frameRate' to the canvas using a 'text()' call.

**Comment by DavidRegev** [comment]
`text()` gives me only `10` too.

**Comment by DavidRegev** [comment]
Good news! After much testing, I tracked it down to one experimental setting that I had left enabled both in regular Firefox and Nightly: `privacy.resistFingerprinting`.

Thank you for all your help. I’m going to close this bug, as it seems it is this hidden feature that was causing the slowdown.
