### ISSUE TITLE
beginShape(POINTS) not working in WebGL

### ISSUE THREAD

**Issue by honkachun** [processing/p5.js#2662]
It will display line instead of points in under WebGL renderer. Tested in both Safari and Chrome.

**Comment by kjhollen** [comment]
thanks for reporting this! it is a known issue (points not yet implemented) but we didn't have an issue logged to track it.

**Comment by tau-** [comment]
Looks like there is a lot to do on this. The shaders need to updated to support the stroke parameters and some choices need to be made on how stroke and fill options will work together. GLSL has some built-ins for vertex size (`gl_PointSize`) but definitely give subpar results when used alone. I have a WIP commit that can hopefully jump start some discussion on this.

**Comment by Spongman** [comment]
You might want to take a look at the changes I made in https://github.com/Spongman/p5.js/tree/render-pipeline. It fixes all the shape modes except point & quads.

**Comment by honkachun** [comment]
Thanks very much, I am trying to work in different way.

**Comment by kjhollen** [comment]
fixed in webgl-gsoc-2018!
