### ISSUE TITLE
clear() function no longer available in createWriter()

### ISSUE THREAD

**Issue by shubham0109** [processing/p5.js#2663]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [x] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x ] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

While going through the `createWriter()` documentation, I got an error on the example given there.
The error was `writer.clear()` is not a function.
I guess it has been replaced by `flush()` and probably only need to be corrected in the documentation.
`writer.flush()` did work.

**Comment by shubham0109** [comment]
`clear()` function is also mentioned in `p5.PrintWriter` documentation.

**Comment by Spongman** [comment]
Weird. Did the docs get pushed?

**Comment by lmccart** [comment]
@limzykenneth I believe that's correct. it's in the source but not in the built library. I'll work on getting another release out this week.

**Comment by lmccart** [comment]
this should be fixed in 0.6.1
