### ISSUE TITLE
Cylinder parameters

### ISSUE THREAD

**Issue by Waabuffet** [processing/p5.js#2664]
#### Nature of issue?

- [x] Found a bug
- [x] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

OK the problem with the cylinder is that its parameters should be the radius and height (first and second only)
however what it actually is, that first and second are both for the radius that make it more like an ellipses_cylinder.
shouldn't the height determine the actual height of the cylinder?

thank you

**Comment by Spongman** [comment]
Indeed. This has been fixed, but not pushed yet.
