### ISSUE TITLE
Community page contains broken link in Contributing subheading in document paragraph

### ISSUE THREAD

**Issue by iarobinson** [processing/p5.js#2667]
#### Nature of issue?

- [x] Found a bug

#### Most appropriate sub-area of p5.js?

- [x] Other (specify if possible)

A broken link is present on the community page at https://p5js.org/community/

#### Which platform were you using when you encountered this?

- [x] Desktop/Laptop

#### Details about the bug: 

- Web browser and version: Version 64.0.3282.167 (Official Build) (64-bit)
- Operating System: MacOS Sierra 10.12.6 (16G29)
- Steps to reproduce this:

Below I've included two screenshots. In the community test the link with the anchor text 'porting examples' sends the user to a separate GitHub repository for creating a new page. 

<img width="375" alt="screen shot 2018-02-24 at 2 49 04 pm" src="https://user-images.githubusercontent.com/7991933/36634437-a2448f14-1972-11e8-812a-e1a8e9e6d293.png">
<img width="375" alt="screen shot 2018-02-24 at 2 48 45 pm" src="https://user-images.githubusercontent.com/7991933/36634436-a1cb8f88-1972-11e8-94cf-0fa3511793e0.png">

If I were to be so bold as to suggest a solution... I would say this link either be removed or linked to the following page:

https://github.com/processing/p5.js/wiki/Inline-documentation

The inline documentation page has information related to 'porting examples' as well so both links in that paragraph could go to the same place.

#### I'm new to this

I'm just trying to get into OpenSource. If I'm acting silly or anything in this issue submission, please let me know. There is little doubt that I'm poking around in the dark with this submission issue.

**Comment by iarobinson** [comment]
I would appreciate the opportunity to fix this issue and submit a pull request if that works. :)

**Comment by lmccart** [comment]
@iarobinson go for it :)
https://github.com/processing/p5.js-website

**Comment by lmccart** [comment]
as for the link, I think it's easiest to remove it for now.. what we were referring to was porting examples from processing.org examples page to p5js.org examples page, but there's no good link for that right now.

**Comment by emclaren** [comment]
Hi @iarobinson, I submitted a pull request with a fix for this broken link last week ([processing/p5.js-website/#167](https://github.com/processing/p5.js-website/pull/167).

@lmccart, my pull request redirects to [https://github.com/processing/p5.js-website/wiki/Adding-examples](https://github.com/processing/p5.js-website/wiki/Adding-examples). Is this page outdated?

Thanks!

**Comment by iarobinson** [comment]
Nice work @emclaren. 

I looked at your commit and was able to trace it to understand where I could submit a pull request in the future. 

Thanks for the help and I'm happy you found it and fixed it. 👍

**Comment by lmccart** [comment]
oh! yes I think that page is the correct one, and not outdated. thank you!

**Comment by lmccart** [comment]
fixed with https://github.com/processing/p5.js-website/pull/167
