### ISSUE TITLE
`tint` function nullifies effect of `scale` on an Image

### ISSUE THREAD

**Issue by a-y-u-s-h** [processing/p5.js#2668]
- [x] Found a bug
- [x] Image
- [x] Desktop/Laptop

#### Details about the bug: 

If I use `tint` after `scale` on an image, it nullifies the effect of `scale`. 

- p5.js version: 0.6.0
- Web browser and version: 64.0.3282.140 (Official Build) (64-bit)
- Operating System: x86_64 Linux 4.15.4-1-ARCH
- Steps to reproduce this:

This code  : 

```js
let data = {
  sketch: {
    background: "#FFFFFF"
  }
}

let capture;

function setup() {
  createCanvas(windowWidth, windowHeight);
  capture = createCapture(VIDEO);
  capture.width  = capture.width * 0.3;
  capture.height  = capture.height * 0.3;
  capture.hide();
}

function draw() {
  background(0);
  translate(width, 0);
  scale(-1, 1); // horizontally inverting the capture
  // tint(255, 127); // uncomment for transparency
  image(capture, 0, 0, width, width * capture.height / capture.width);
  filter(INVERT);
}
```
produces : 

![2018-02-23_22-26-46_screenshot](https://user-images.githubusercontent.com/19586719/36644178-84f7731c-1a7c-11e8-9b8e-daf258a9a727.png)

but when I put `tint` back in : 

```js
let data = {
  sketch: {
    background: "#FFFFFF"
  }
}

let capture;

function setup() {
  createCanvas(windowWidth, windowHeight);
  capture = createCapture(VIDEO);
  capture.width  = capture.width * 0.3;
  capture.height  = capture.height * 0.3;
  capture.hide();
}

function draw() {
  background(0);
  translate(width, 0);
  scale(-1, 1); // horizontally inverting the capture
  tint(255, 127); //  transparency
  image(capture, 0, 0, width, width * capture.height / capture.width);
  filter(INVERT);
}
```

it produces transparent output except, it's not inverted anymore : 

![2018-02-23_22-27-04_screenshot](https://user-images.githubusercontent.com/19586719/36644201-cfda4f30-1a7c-11e8-892d-6258fd39806b.png)

**Comment by a-y-u-s-h** [comment]
It nullifies because I get the same output even if I use something like `scale(1, 2)` before `tint(...)`

**Comment by tau-** [comment]
Does this still occur on version 0.6.0?

**Comment by a-y-u-s-h** [comment]
Just checked : yes, it does. Upating version in original issue as well.

**Comment by tau-** [comment]
Hmm. I cannot reproduce this on my personal machine (Win10, Chrome 65.0.3325.88, p5.js p5.dom.js @ 0.6.0). Does this happen if you `tint` before `scale` as well? There could be a difference in the native canvas scaling function (which p5 `scale` uses under the hood). I'll try a few more variations to attempt to reproduce.

**Comment by a-y-u-s-h** [comment]
Yup. It happens if I put `tint` before `scale` as well. Somehow my Chrome version is older and it isn't showing any updates either. I'll report back again after re-installing Chrome as well.

On firefox, I don't get this error.

**Comment by tau-** [comment]
Making a note to check the Chromium issues list for this.

**Comment by lmccart** [comment]
I think this may have been chrome specific and seems ok now. Please comment if anyone is still having the issue.
