### ISSUE TITLE
Friendly Error: undefined text

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js#2678]
- Existing feature enhancement
- Friendly Errors

Picking up on thread from https://github.com/processing/p5.js-web-editor/pull/579, the following code:

```javascript
let txt;
function setup() {
  text(txt, 10, 10);
}
```

Produces the following error:

![screen shot 2018-03-02 at 7 52 02 am](https://user-images.githubusercontent.com/191758/36899793-a302fd48-1dee-11e8-87d8-496cecb3037f.png)

It would be nice to have a friendly error something along the lines of:

```
p5 cannot render undefined text. sketch: line 5
```

**Comment by kjhollen** [comment]
there's a subtle difference with #2607 here, I think: this error occurs in 2D mode, where the method is implemented, but throws an error because the first/txt argument of the function is undefined.

**Comment by Spongman** [comment]
oh, indeed. i thought it was a 3d thing.

**Comment by Spongman** [comment]
shouldn't `text()` be calling `validateParameters()` ?

PR #2471 adds validation for every public p5 method. demo here: https://codepen.io/Spongman/pen/qxwBJr?editors=0011 (click the 'console' button bottom-left)
