### ISSUE TITLE
createCanvas() issue in p5.js :

### ISSUE THREAD

**Issue by gogoIsComing** [processing/p5.js#2679]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version:  p5.js v0.6.0 January 19, 2018 
- Web browser and version:  chrome Version 64.0.3282.186 (Official Build) (64-bit)
- Operating System:  windows 10 Pro 64-bit 
- Steps to reproduce this:

#### New feature details:
Hi there : 
when i create a new Canvas in p5.js and run my code in google chrome it creates two canvas and i do not know why this is happen

**my code :**

`function setup() {

  createCanvas(400, 400);

}

function draw() {
  
  background(0)
  ellipse(200,200 ,20, 20);
}
`
screenshots :

image 1:
![1](https://user-images.githubusercontent.com/33967218/36905599-6edd092a-1e3c-11e8-88cd-7493f0d85600.png)

image 2:

![2](https://user-images.githubusercontent.com/33967218/36905603-721be390-1e3c-11e8-9b9b-72e575c433f0.png)

image 3:

![3](https://user-images.githubusercontent.com/33967218/36905854-10998b62-1e3d-11e8-9e4a-afd5f4ed890c.png)
  
Any Help :)

**Comment by Spongman** [comment]
Are you loading 05.js twice by any chance? Otherwise, can you post your .html file?

**Comment by gogoIsComing** [comment]
@Spongman this issue occur just google chrome and other browsers but it is not occur in live preview extension inside the editor it self.
by the way i use vscode as editor.

**Comment by PhilipRL** [comment]
@gogoIsComing: You _are_ loading p5 twice. First you're loading `p5.min.js` on line 6 and then you're loading `p5.js` on line 9. You should only load one of these :)

**Comment by gogoIsComing** [comment]
@PhilipRL  thank you , i got it 👍

**Comment by Spongman** [comment]
i will add an issue. maybe the p5 library can detect this and generate a useful error.
