### ISSUE TITLE
Radian conversion in 3D rotation does not work

### ISSUE THREAD

**Issue by mislavmilicevic** [processing/p5.js#2680]
After setting the angleMode() to degrees in setup(), calling the rotateX/Y/Z function with an angle expressed in the degrees as a parameter does not execute properly.

I've created a perspective camera and box in the scene. After trying to rotate 1 degree, it would actually rotate around 30-45 degrees.

I've temporarily patched this by adding an angle mode check inside the generated library.

**Comment by Spongman** [comment]
i think this maybe a dupe of #2533 which has been fixed (#2552) but not yet released.

**Comment by mislavmilicevic** [comment]
You're correct, closing the issue
