### ISSUE TITLE
Strange Inexplicable Behavior in Chrome on Android

### ISSUE THREAD

**Issue by JackWitherell** [processing/p5.js#2684]
#### Nature of issue?
- [X] Found a bug
I'm getting strange unexplicable behavior in the way that my program is outputting in Chrome on Android vs Chrome on Windows

#### Most appropriate sub-area of p5.js?

- [X] Core (?)
- [ ] IO
- [ ] Utilities
- [X] Other (specify if possible)
Some kind of grid issue in the way images are being drawn to the screen.

#### Which platform were you using when you encountered this?

- [X] Mobile/Tablet (touch devices)
- [ ] Desktop/Laptop... ?
- [ ] Others (specify if possible)
 --It's very possible this issue is more widespread but so far it only seems to manifest itself in chrome on android

#### Details about the bug: 
In P5JS on chrome windows I get the expected behavior for my program; to print out images that are generated from graphics that are randomly generated per row:
![Good cute working code](https://i.imgur.com/lG6wsJ4.png)

In P5JS on chrome android however I get unexpected behavior, where either the images are displayed to the screen too big, overlapping, cut off, uneven or otherwise not following standard processing behavior:
![Disgusting evil smelly smelly code](https://i.imgur.com/0KsT6Zb.png)

- p5.js version: 0.60
- Web browser and version: chrome 64.0.3282.137
- Operating System: Android 8.1.0 Oreo
- Steps to reproduce this:
go ahead and take a look at my project at http://cummies.cf:81/p5js/
or you can look at the screenshots below

```javascript
var bg_canvas;
var tab;
var randomBool;
var boxres=4;
var boxsize=64;

function setup() {
  bg_canvas=createCanvas(windowWidth, windowHeight); //make canvas the size of browser window
  bg_canvas.position(0, 0); //place canvas to top left
  bg_canvas.style('z-index', '-1'); //css shove canvas behind html frames
  tab = createGraphics(boxsize, boxsize); //make tab graphic the size of boxsize
  tab.strokeWeight(0); //no stroke
  tab.stroke(214); //color for safety
  tab.fill(214); //fill color for rectangles
  work(); //draw stuff
}

function windowResized() {
  resizeCanvas(windowWidth, windowHeight);
  work();
}

function work(){ //draws designed tiles to screen
  for(var i=0; i<windowWidth;i+=boxsize){
    designTile(); //every time a column is done generate a new tile
    for(var j=0; j<windowHeight;j+=boxsize){
      image(tab, i, j); //push to screen
    }
  }
}

function designTile(){
  tab.background(255);
  for(var x=0; x<boxsize; x+=boxres){ //until tab object is filled
    for(var y=0; y<boxsize; y+=boxres){ //decide whether or not to put a square in a boxres'd area
      randomBool = Math.floor(Math.random() * 2);
      if(randomBool==1){ //randomly 50% of the time draw a rectangle
        tab.rect(x,y,boxres,boxres); //the size of the box resolution
      }
    }
  }
}
```

I'm doing a lot of weird stuff with my code so I'm expecting it to not be up to spec, but my main goal is to be able to dynamically generate a background for my site. Let me know if there's a better way to be doing this if this is beyond the intended scope for processing or if there's a better way. I'm very experienced with processing but only just started with p5.js so while I understand the way processing code works I don't fully understand the quirks of p5.js

**Comment by Spongman** [comment]
try adding `pixelDensity(1)` at the start of your `setup` funciton

**Comment by JackWitherell** [comment]
Hooh... Wow, that nailed it.

**Comment by Spongman** [comment]
piling on #2077
