### ISSUE TITLE
Uncaught TypeError: Cannot read property 'speak' of undefined     at mousePressed (sketch.js:22)     at p5._onmousedown (p5.js:55408)

### ISSUE THREAD

**Issue by FaraazAttariSaqibi** [processing/p5.js#2687]
Sir I am Working in a project where i get this error (in chrome console and in firefox also; with or without xampp)
Uncaught TypeError: Cannot read property 'speak' of undefined
    at mousePressed (sketch.js:22)
    at p5._onmousedown (p5.js:55408)

------------------------------------------------------------------------
let speech;
function setup() {
  noCanvas();

  let voice = new p5.Speech();
  voice.onLoad = voiceReady;

  function voiceReady() {
    console.log(voice.voices);
  }

}

function mousePressed() {
  speech.speak('Hello Sir');
}
-------------------------------------------------------------------------

please help me.........

- [*] Found a bug

 Which platform were you using when you encountered this?

- [*] Desktop/Laptop

**Comment by lmccart** [comment]
Hi @FaraazAttariSaqibi you are defining the variable `let` inside of setup. this means that it is limited to the scope of the curly brackets of setup. if you try to use it in draw, it won't know what that variable is. https://scotch.io/tutorials/understanding-scope-in-javascript

to fix this, you will need to define the variable outside of setup, and then assign it inside. for future programming help, please post in the [forum]https://forum.processing.org/two/].
