### ISSUE TITLE
Feature request: Load file dialog

### ISSUE THREAD

**Issue by JuanIrache** [processing/p5.js#2688]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [ x] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [x ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x ] Desktop/Laptop
- [ ] Others (specify if possible)

#### New feature details:

As far as I know currently there is no straighforward way of opening a "load file" dialog for the user to choose a file they want to load. Am I wrong? I can get the desired behaviour using the DOM library with a workaround like this:
```
let input = p.createFileInput(confirm);
input.hide();
input.id("file-input");
let clickInput = document.getElementById("file-input").click();
```

Maybe this should somehow be made compatible with functions like loadStrings() or loadJSON(), by using them as an optional callback for interpreting the returned data.

**Comment by Spongman** [comment]
there's a few issues with this:
- you can't call `click()` on a `<input type='file'/>` from script unless that script is run directly as a result of a user action (like a click event on another button)
- without some really complicated ServiceWorker stuff, you're not going to be able to read the contents of a file chosen by the user without first posting the file to a server and then retrieving it with an API - reading local files from a web page is generally considered a security issue.

**Comment by JuanIrache** [comment]
I see, thanks for the explanation.

The workaround works on Chrome and Edge and it's concise. So I can live with that. It probably does nothing on Firefox, will have to try it before publishing.
