### ISSUE TITLE
Content Responsiveness to Display

### ISSUE THREAD

**Issue by Al-bukair** [processing/p5.js#2690]
Hi!

P5.js is now widely usable for different real-life applications especially that it is in JS, but the fact that the content is not responsive makes using it limited to applications where responsiveness is not necessary or those who know how to make the content responsive, especially with the increase use of smart phones over desktops/laptops it means responsiveness is a key area to extended the use of the language for other areas/applications.

An example of a p5.js content that is unresponsive is the test() function. The text is displayed in the given coordinates but the coordinates don't change when the display size changes, I have overcome such problems by creating my own responsiveness functions e.g.

function textBox(theText, yAxis, ts) {
    textSize(ts);
    text(theText, 0, yAxis, windowWidth, ceil(textWidth(theText) / windowWidth) * (ts+5));
}

As you can see the function above can display text in different displays by calculating the space in the text box needed for each display in order to ensure that the text is fully displayed. Many functions like this can be put together to make all kinds of features responsive e.g. images, buttons, input boxes etc. And I believe this functions will be helpful for anyone who wants their content to look great & presentable in all devices, especially phones.

If you share this view then what are you waiting for!?

Let's make P5.js better & easy for everyone! :)

**Comment by lmccart** [comment]
you could use the [windowResized](https://p5js.org/reference/#/p5/windowResized) method to detect a change in window size, and call draw to update the positions.
