### ISSUE TITLE
bezierDetail() not working in p5.js 0.6.0

### ISSUE THREAD

**Issue by grege2** [processing/p5.js#2691]
#### Nature of issue?

- [x ] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x ] Other ( Curves )

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x ] Desktop/Laptop 
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.6.0  also 0.5.16
- Web browser and version: Chrome 64.0.3282.186 (Official Build) (64-bit)
- Operating System: MacOS 10.13.3
- Steps to reproduce this:

Can't get bezierDetail working. Seems to not work in 0.6.0 or 0.5.16. 

Also the example at https://p5js.org/reference/#/p5/bezierDetail is not working for me. It always shows a smooth curve, even if you edit the bezierDetail() param down to low numbers (2,3,4).

Here's my test code .. (the "code" wrapper is not working for me, sorry).

`
function setup() {
  createCanvas(800, 600);
}

function draw() {

  background(100);

  noFill();
  bezierDetail(4);

  bezier(20, 20,   width * 0.2, height * 0.8,  width * 0.8, height * 0.2,  width - 20, height - 20);
}
`

I looked in p5.js at the actual code, it seems clear that the basis functions are evaluated at "detail" steps along the parameter space 0.0 to 1.0, I can't see why that's not working, but I haven't traced it further.

bezierDetail() also fails for me on OpenProcessing.org ...

https://www.openprocessing.org/sketch/520295

Also curveDetail() seems to be not working. The example at ...

https://p5js.org/reference/#/p5/curveDetail

does not obey the "detail" setting, similarly to bezierDetail().

Hope that's clear ! Not a priority by any means, I want to experiment with levels of detail on the Bezier curves but it's not show-stopper. 

Ciao, Greg.

**Comment by vojtapol** [comment]
I can confirm that I am having the same issue in 0.6.0

**Comment by Spongman** [comment]
it turns out that `curveDetail` and `bezierDetail` are only used in `WEBGL` rendering mode. the docs and example should be updated to reflect this.

**Comment by lmccart** [comment]
@faithwyu here's another documentation one you might look at. I think this involves adding a sentence to each reference entry very similar to the [processing documentation](https://processing.org/reference/curveDetail_.html). note that we use the terms "webgl" and "canvas" instead of "P3D" and "P2D" .

**Comment by faithwyu** [comment]
got it thanks! will be working on it asap.

**Comment by Spongman** [comment]
i have two pending PRs (#2757, #2758) that address this issue. maybe they're not showing up for other people?

**Comment by lmccart** [comment]
ah sorry i missed those, thanks!
closed with #2757

**Comment by grege2** [comment]
Hi, glad to see this looked at. I didn't get any notifications that anything was happening, have I got notifications turned off or something ?
Cheers, Greg E

**Comment by grege2** [comment]
Hmm .. I have email with subject "processing/p5.js" filtered into a "p5js" folder on my Gmail, just to see the traffic and how much is happening in p5.js (lots .. good!), maybe my personal Author update was merged with the general update, in that folder. Waffly logic but anyway .. ignore my previous question. Ciao tutti.
