### ISSUE TITLE
Saving a text file with an extension other than .txt

### ISSUE THREAD

**Issue by ThrashJazzAssassin** [processing/p5.js#2694]
I'm trying to `save(an_array_of_strings, "filename.xyz")` but p5 keeps wanting to save it as: filename.xyz.txt

Can I save it without the added .txt?

Thanks

**Comment by Spongman** [comment]
try `save(an_array_of_strings, "filename", "xyz")`

**Comment by ThrashJazzAssassin** [comment]
Worked. Thanks :)
