### ISSUE TITLE
mouse X

### ISSUE THREAD

**Issue by LenNeni** [processing/p5.js#2703]
#### Nature of issue?

- [ mouse X is not being recognized as code] Found a bug

#### Which platform were you using when you encountered this?

- [ i was using web editor on my desktop] Desktop/Laptop

#### Details about the bug: 

- p5.js version: 
- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

**Comment by Spongman** [comment]
can you post your code so we can see what's going wrong?
