### ISSUE TITLE
Color - function to add a scalar to r,g,b values of a color.

### ISSUE THREAD

**Issue by TanviKumar** [processing/p5.js#2705]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [x] New feature request

#### Most appropriate sub-area of p5.js?

- [x] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### New feature details:

A function to add scalar to r,g,b values of a color. Can be used to manipulate colors.
The function could have 3 parameters having the number to be added to r, g, and b of the color. Parameters have a default of 0. 

I'd like to take this up if this addition would be beneficial to p5.js!

EDIT : 
Example working of this function : 
```javascript
colorMode(RGB);
var c = color(0, 173, 73); // Shade of green.
fill(c);
rect(0, 0, 50, 50);
c.addScalar(20, 20, 0); // Brighter shade of green - now has red - 20 and green - 193
fill(c);
rect(50, 0, 50, 50); // Rectangle with a different shade of green.
```

**Comment by limzykenneth** [comment]
Hi, can you include a simple example use of the proposed function? Just so we don't misunderstand your proposal.

**Comment by TanviKumar** [comment]
Sure, will edit issue and add an example of the expectation of such a function.

**Comment by IcyTv** [comment]
You could achieve this in your code by doing:
`c.setRed(c._getRed() + scalarValue);`
and then repeat for all the other desired colors, right?
I agree though, that addScalar would be a nice function to have. It could be implemented like this (although I don't know if this is the best way):
`p5.Color.prototype.addScalar = function(scalarR, scalarG, scalarB, scalarA) {
    this.setRed(this._getRed() + scalarR);
    this.setGreen(this._getGreen() + scalarG);
    this.setBlue(this._getBlue() + scalarB);
    this.setAlpha(this._getAlpha() + scalarA);
}`

**Comment by TanviKumar** [comment]
Yes, the implementation of this function would look like your code
according to me. Hope this is something that can be integrated into p5.js.

On 1 Apr 2018 09:35, "IcyTv" <notifications@github.com> wrote:

You could achieve this in your code by doing:
c.setRed(c._getRed() + scalarValue);
and then repeat for all the other desired colors, right?
I agree though, that addScalar would be a nice function to have. It could
be implemented like this (although I don't know if this is the best way):
p5.Color.prototype.addScalar = function(scalarR, scalarG, scalarB, scalarA)
{ this.setRed(this._getRed() + scalarR); this.setGreen(this._getGreen() +
scalarG); this.setBlue(this._getBlue() + scalarB);
this.setAlpha(this._getAlpha() + scalarA); }

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/processing/p5.js/issues/2705#issuecomment-377742208>,
or mute the thread

**Comment by lmccart** [comment]
thanks @TanviKumar. my sense is that this is a bit beyond the scope of the p5.js library at the moment, but could be a good starting point for a p5.js color addon library if you wanted to start one. I'm going to close this for now, and we can revisit in the future if it starts to feel more necessary for the core library.

**Comment by JPlayz409** [comment]
Question, I am brand new to this, but should there be any color to the shape? Without needing to use a color command?
