### ISSUE TITLE
Directional lighting issue when using 3d primitive without material

### ISSUE THREAD

**Issue by Bjvanminnen** [processing/p5.js#2707]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other (specify if possible)
Lighting

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 
I'm creating a fairly simple scene and the `directionalLight` was behaving strangely for me, appearing to give me different behaviors for a box vs. sphere. Eventually determined that this only repros when I add a box before setting a material.

- p5.js version: 0.6.0
- Web browser and version: Chrome 64, FF 58
- Operating System: Linux
- Steps to reproduce this:
```js
function setup() {
	createCanvas(640, 640, WEBGL);
	const wide = 200;
	const high = 200;
	ortho(-wide, wide, high, -high, 0, 2000);
}

function draw() {
	background(50);

	camera(
		300, 300, 300,
		0, 0, 0,
		0, 1, 0
	);

	// If I uncomment the below, light shows up on a different face
	// of my size 50 box
	// box(10);
	stroke('black');
	ambientMaterial('#ffffff');

	box(50);

	translate(100, 0, -100);
	sphere(50);

	ambientLight(128);
	directionalLight(
		256, 0, 0,
		0, -1, 0
	);
}
```
Screenshot from https://alpha.editor.p5js.org/ with box commented out
![image](https://user-images.githubusercontent.com/1767466/37542021-f15aecb8-2919-11e8-9776-45491c1f706f.png)

Without box commented out
![image](https://user-images.githubusercontent.com/1767466/37542034-fa7c91ac-2919-11e8-85f5-76ed648a7e21.png)

**Comment by Bjvanminnen** [comment]
Tried this now on my OSX machine, where I do not repro. It is entirely believable that my Linux setup has something strange happening, so if others don't repro, it seems reasonable to close this issue.

**Comment by stalgiag** [comment]
Hi @Bjvanminnen I can't reproduce this so I am going to close for now. Feel free to ping here if you see this pop up again.
