### ISSUE TITLE
p5.js  can not display the texture() on my box() in WEBGL

### ISSUE THREAD

**Issue by dannnlily** [processing/p5.js#2711]
#### Nature of issue?

- [x] Found a bug

#### Most appropriate sub-area of p5.js?

- [x] Image
- [x] WebGL

#### Which platform were you using when you encountered this?

- [x] Desktop/Laptop

#### Details about the bug: 

Hello guys from Github:
     I am trying to apply an image as texture on the box() in WEBGL mode using Processing3(I turned the mode into p5.js). Unfortunately the canvas completely turned blank whenever i used texture() and loadImage(). Below are the codes which I copied from p5.js references. However, my canvas still had nothing on the screen just blank. I think maybe i did something wrong when I used the image path? I stored the photo in the “images” folder in “processing” folder.

var img;
function preload() {
  img = loadImage('images/ers.jpeg');
}

function setup() {
  createCanvas(1000, 1000, WEBGL);
}

function draw() {
  translate(0,0,0);
  background(0);
  rotateZ(frameCount * 0.01);
  rotateX(frameCount * 0.01);
  rotateY(frameCount * 0.01);
  texture(img);
  box(200, 200, 200);
}

Would be very appreciated if anybody could help me with this issue!

**Comment by dannnlily** [comment]
Thank you so much! I will try it later.
Have a nice weekend!

Best

Spongman <notifications@github.com>于2018年3月21日 周三上午4:40写道：

**Comment by kjhollen** [comment]
hi @dannnlily, when I drag an image into a sketch with the editor, it makes a data folder and puts the image there. then I need to do loadImage('data/img.png'); to load the image, which is a little different from Processing (where you wouldn't need the data/ part).

I'm not sure what you mean by processing folder, but if your sketch has a folder structure like /processing/images you'll need to do loadImage('processing/images/ers.jpeg');

I'm going to close this issue as it doesn't appear to be a problem with the library, but if you have more questions, the processing forum is a great place to get help debugging!
