### ISSUE TITLE
text align in instance mode

### ISSUE THREAD

**Issue by Zaptronic** [processing/p5.js#2712]
#### Nature of issue?

- [x ] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ x] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [ x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 
I'm using p5js in instance mode and I get an error: Uncaught ReferenceError: CENTER is not defined
when I try to do this:
sudoku.textAlign(CENTER);
sudoku.fill(255);
sudoku.textSize(50);

TextAlign CENTER doesn't seem to work.
Is this a know bug?

- p5.js version: 
- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

**Comment by meiamsome** [comment]
You'll need to also use `CENTER` from your p5 instance: `sudoku.CENTER`

**Comment by Zaptronic** [comment]
Ah Thanks. Makes sense.
