### ISSUE TITLE
color not showing

### ISSUE THREAD

**Issue by charbelsako** [processing/p5.js#2713]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [ ] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 
- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

**Comment by meiamsome** [comment]
Hello! it looks like you haven't filled in the issue template at all - can you please update your post to describe the issue you are having? Thanks!

**Comment by charbelsako** [comment]
yeah i was going to delete it but apparently it's still here. And it was a bug in my code.
