### ISSUE TITLE
Figured out the real problem

### ISSUE THREAD

**Issue by sadsadAdasdasdasd** [processing/p5.js#2716]
Renaming files and trying to run them causes your toolbar to make a new copy of the p5 folder and refuse to open anything except for the file originally created whilst the new file floats off to neverland. I now have like 5 p5 folders because of this, and my code won't run because the toolbar still thinks it's named "sketch.js" and keeps making new files called "sketch.js" to fill the void in its empty life now that the file once known as sketch.js has given itself a new, more appropriate name. Like a parent mourning their child's coming of age. It's really tragic.

**Comment by meiamsome** [comment]
Hello,

You don't need to create another issue - you can post a comment on your previous issue (#2714) for such things. I do not know what toolbar you mean, there isn't one packaged with p5. 

If you are referring to https://atom.io/packages/p5js-toolbar then you need to post this report in their issues as this is not an issue with p5 itself: https://github.com/bmoren/p5js-toolbar/issues
