### ISSUE TITLE
how should rotate be used - getting some strange behaviour on continuous values 

### ISSUE THREAD

**Issue by sononix** [processing/p5.js#2721]
Created 2 codepens of the behaviour Im seeing on continuous angles not being correct also checked the console to the actual values being generated

https://codepen.io/anon/pen/dmWQjm
https://codepen.io/anon/pen/jzmQXP

the rotations arent equally spaced at all either in degree of rad format 
any ideas 
tks

**Comment by limzykenneth** [comment]
Methods like `rotate` accumulate over time which means if you call `rotate(5)` and in the next iteration of the loop call `rotate(10)` it would effectively be the same as `rotate(15)`. To make the rotation local to the current iteration of the loop, just put `push()` and `pop()` around the transformation and the drawing functions. See [here](https://p5js.org/reference/#/p5/push) for more info.
