### ISSUE TITLE
Adding alternate types of noise generators

### ISSUE THREAD

**Issue by PaintedBlck** [processing/p5.js#2725]
Hi,

I'm a newbie here, so please bare with me, or give me a hint on how to improve my communications. I'm looking forward to your thoughts on the below proposition.

**_#### Nature of issue_**

- [ ] Found a bug
- [ ] Existing feature enhancement
- [x] New feature request

**_#### Most appropriate sub-area of p5.js_**

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [x] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

**_#### New feature details:_**

I'm not quite sure if I have to classify this post under "enhancing the Math section" or "new features".

The idea is the following: The Perlin noise generator is a great feature, but there are also other noise generators that provide alternative 2D, 3D or even 4D space fillings. If it hasn't been proposed before (I don't find any issues on the topic), I'd like to extend p5.js with supplementary noise generation functions.

Inspiration for code can be found on [Auburns FastNoise github page](https://github.com/Auburns/FastNoise) (where I also found most of the below images).

I'm more specific thinking about e.g the following kinds of noise generation:

- [ ] flat : blue, brown, pink, red, violet, white

- [ ] cellular

![cellular1](https://user-images.githubusercontent.com/4866268/37818839-d64da160-2e7b-11e8-8643-e23ed75e86c7.png) ![cellular2](https://user-images.githubusercontent.com/4866268/37818840-d66730da-2e7b-11e8-8c7f-b2c3be9cb2c2.png) ![cellular3](https://user-images.githubusercontent.com/4866268/37818841-d6825824-2e7b-11e8-9fb8-eee1508ace6e.png)

- [ ] cubic

- [ ] fractal

![fractal1](https://user-images.githubusercontent.com/4866268/37818874-ea78acd4-2e7b-11e8-9596-4ba27709100d.png)

- [ ] gradient : gradient perturb, Worley

![gradientperturb1](https://user-images.githubusercontent.com/4866268/37818941-1be87f06-2e7c-11e8-95fd-546baca37269.png) ![gradientperturb2](https://user-images.githubusercontent.com/4866268/37818942-1c08fdb2-2e7c-11e8-988b-46025e983e5b.png) ![gradientperturb3](https://user-images.githubusercontent.com/4866268/37818943-1c27e006-2e7c-11e8-9c39-71ae5d92e52f.png) ![worley1](https://user-images.githubusercontent.com/4866268/37818944-1c47e3e2-2e7c-11e8-8c92-e08cefb226f6.png)

- [ ] value

![value1](https://user-images.githubusercontent.com/4866268/37818928-104674f0-2e7c-11e8-9ac1-62bd06d47467.png)

- [ ] . . .

**Comment by kjhollen** [comment]
Hi @PaintedBlck, welcome! :) I think this proposal is a great idea for a library or addon—we try to keep the core library pretty trim, but these are great features and I'm sure members of the community would love to use them. Would you be interested in working on or contributing such a library?

**Comment by PaintedBlck** [comment]
Hi,

I most certainly would be interested to work on/contribute to such a library. Since I’m the new kid on the block, can you point me to an example library (I’d like to take a look on how to organise code, layout my code, make module tests, organise that part of the git, ...), in order not to do conflicting things.

Thx !

**Comment by kjhollen** [comment]
Wonderful! If you want to have the library listed on the p5 site, there's some more info here: https://github.com/processing/p5.js/wiki/Libraries

I'll close this issue for now since you've created your own repository.
