### ISSUE TITLE
How to save sound file without prompt ?

### ISSUE THREAD

**Issue by DudleySmith** [processing/p5.js#2726]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [x] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [x] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Feature enhancement details:
I would like to save sound file without having prompt (set the file path first, then save without asking...

**Comment by meiamsome** [comment]
In a Web Browser environment this is not possible due to Browser security concerns.
