### ISSUE TITLE
webgl: fill() disables lights

### ISSUE THREAD

**Issue by Spongman** [processing/p5.js#2728]
p5.js 0.6.0

demo: https://codepen.io/Spongman/pen/LdjGaX?editors=0010

(i think this was actually covered in a previous issue but i'm unable to find it)

it's currently impossible to render multiple geometries of different diffuse colors in a lit scene. this is because the `fill()` call, which sets the diffuse color also disables the use of lights - reverting to flat-shaded rendering.

this is illustrated in the demo above, which in p5.js looks like this:
![image](https://user-images.githubusercontent.com/1088194/37850379-1fd8bd08-2e98-11e8-8f83-c511d870e743.png)

in processing (3.3.6), with essentially the same code, the pointLight is preserved across `fill()` calls, and it looks like this:
![image](https://user-images.githubusercontent.com/1088194/37850440-57e7c7fc-2e98-11e8-9820-03b965aa979a.png)

there's really no workaround for this either, since re-adding the lights results in lighting being enalbed, but also results in duplicate lights being added to the shader uniforms.

**Comment by kjhollen** [comment]
This will be fixed as a side effect of #2961.

**Comment by stalgiag** [comment]
perhaps this will be fixed by #3076 or something similar?

**Comment by sanketsingh24** [comment]
@stalgiag I think this should be closed as it is fixed by #3535 and I can not reproduce it anymore on master.

**Comment by stalgiag** [comment]
thanks for the reminder @sanketsingh24 !
