### ISSUE TITLE
Using animated SVG in loading screen for preload function

### ISSUE THREAD

**Issue by Kintu-Parantu** [processing/p5.js#2729]
Hello, I am extremely new to all this so pardon me for all the mistakes that I might commit. 

I have been trying to use SVG animations inside the HTML div with id p5_loading as mentioned [here](https://github.com/processing/p5.js/wiki/p5.js-overview#loading-screen) but it is not working. It just displays a static instance of the animation. I am using preload to load a OBJ model to render in WEBGL. When I remove the preload function it works. Any idea why this happens?

**Comment by bmoren** [comment]
Hi Kintu,

I can see why there might be a bit of confusion. Inside of the `<div id="p5_loading" class="loadingclass">this could be some sweet graphics loading lots of bits.</div>` part is just normal standard HTML, so to get an animation happening there, you would have to use something that can happen using normal HTML/CSS outside of p5js. 

This could be a nice library or future feature for p5 to include a `loading(){ //p5 things to display while loading the preload}` loop, but it'd likely be a large undertaking. 

for example to get an animated gif to be your loading imagery.  you might include something like this in your `index.html`:
```html
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0>
    <style> body {padding: 0; margin: 0;} </style>
    <script src="p5.min.js"></script>
    <script src="addons/p5.dom.min.js"></script>
    <script src="addons/p5.sound.min.js"></script>
    <script src="sketch.js"></script>
  </head>
  <body>
<div id="p5_loading" class="loadingclass">
<img src="https://media.giphy.com/media/131tNuGktpXGhy/giphy.gif">
</div>
  </body>
</html>
```
this should replace the typical `Loading...` with an animated gif! you can use CSS and HTML to add more and style accordingly.

In the future this is the type of question best suited for the forums, as these issues here on github relate to issues in the _development_ of p5js itself and it's not intended as a place to seek out questions related to _using_ the library. check out the forum here: https://forum.processing.org/two/categories/p5-js
