### ISSUE TITLE
Using weights when selecting elements from array in random()

### ISSUE THREAD

**Issue by BenjaminHabert** [processing/p5.js#2732]
The `random()` function can be used to select an element from an array. It could be useful to provide weights so that some elements from the array are returned more often than others.

I would be interested in implementing this feature.

#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [x] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [x] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### New feature details:

```javascript
// Existing behaviour
var animal = random(["cat", "dog", "platypus"]);

// Proposed behaviour
var weights = [2, 1, 0.1];  // platypus is less liekely than other animals
var animal = random(["cat", "dog", "platypus"], weights);
```

The second array parameter `weights` would be optional and have the following constraints:

- same length as the first array parameter
- contains numbers
- (not required but might speed up the computation: sum of elements is equal to 1. In this case the array would be called `probabilities`.)

#### Current Status

I went ahead and implemented it in a fork. Following the instructions from the Development guide, here is the current status:

- [x] Implementing feature
- [x] Inline doc for website
- [x] unit tests
- [ ] benchmark. Not really sure how to proceed here.

Also: I am not sure if some checks should be made inside the function itself to help the user (eg: check that arrays are the same length, check that weights are non-negative, check that the sum is greater than 0).

I created a pull request, sorry if it was too soon.

**Comment by lmccart** [comment]
I think this function is beyond the scope of the p5.js api (we try to keep as minimal as possible) but it could be a great starting point for an addon library. see the docs here for how to create an addon: https://github.com/processing/p5.js/wiki/Libraries#creating-a-new-library

**Comment by BenjaminHabert** [comment]
I understand the necessity to keep the API simple. However I believe that the proposed feature is a common use case (I tend to use this a lot). 

- pick a particle direction / speed out of a given probability distribution
- pick a random pixel in an image where darker pixels are more likely
- pick a random word in a dictionary where words with many 'a's are more likely
- pick random colors out of a finite palette while making sure that some colors are used more than others (useful to have a base color + a highlight color)

But obviously I am a bit biased on this topic :)

I don't see how to integrate this feature in one of the existing addons. I probably won't create an addon just for this feature. Is there a list of future addons that are already identified (without them being implemented)?

I will let you decide and close the issue / merge request if you conclude this is indeed out of scope

**Comment by lmccart** [comment]
I'm not seeing any others weighing in on this, so I'm going to close for now. we can revisit if there's a strong need for this among others. thanks!

**Comment by deviparikh** [comment]
+1 that this feature would be great to have!
