### ISSUE TITLE
Save( ) function save on server

### ISSUE THREAD

**Issue by rafaelfaustini** [processing/p5.js#2733]
#### Nature of issue?

- [ ] Found a bug
- [x] Existing feature enhancement
- [x] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [x] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### New feature details:
 Save() function prompts download to the client's computer, it would be interesting a new function or even a new argument on that function to save locally (on script folder) image, text, json, csv, wav, or html, generated with p5.js. One example would be saving data from my sketch and generate a JSON on the server or even the canvas image.

**Comment by limzykenneth** [comment]
This may be a bit long, skip the next paragraph if you just want an alternative solution.

This won't be possible for a number of reasons: first of all and most important of all is security, the whole web ecosystem is designed to prevent this, ie a client should not be able to write any files on the server and if a client is able to it is a security risk as it means the client can potentially upload malware and backdoor onto the server. Secondly, p5.js is a client side library meaning that it runs on the browser and thus will have no knowledge of the structure/architecture of the server, it doesn't know it is served from the script folder for example so it won't know how to "save" any file.

An alternative solution is to prepare an endpoint on your server (which means you need to write some backend code) which receive this data from the client. Then the client just need to send the data, in p5.js using something like `httpPost`, then the server can save the file in the right place. Do ask on the [forum](https://forum.processing.org/two/) if you need help with this. :wink
