### ISSUE TITLE
loadModel changed to accept STL files

### ISSUE THREAD

**Issue by jeremydouglass** [processing/p5.js#2734]
#### Nature of issue?

- [x] New feature request

#### Which platform were you using when you encountered this?

- [x] Desktop/Laptop

#### New feature details:

The [STL file format](https://en.wikipedia.org/wiki/STL_(file_format)) (stereolithography files) are an old lowest-common-denominator ASCII-based format used in 3D modeling and 3D printing. It would be nice to support loading them through `loadModel()`.

This would be analogous to the previously added feature of "Loading 3d Objects from OBJ" (#904) only for the simple STL file format instead.

In Processing(Java), STL support is implemented in the third-party toxiclibs library, the STLReader class, under the [loadBinary](https://github.com/postspectacular/toxiclibs/blob/6896bc17e85320e886bdf0819c66491ce484728e/src.core/toxi/geom/mesh/STLReader.java#L90) method.

See a previous discussion of p5.js STL support on the forum here: https://forum.processing.org/two/discussion/18812/import-stl

**Comment by stalgiag** [comment]
Just putting a note here that the [ThreeJS implementation of this loader](https://github.com/mrdoob/three.js/blob/master/examples/js/loaders/STLLoader.js) is already fairly close to something that would work for us.

**Comment by sanketsingh24** [comment]
@stalgiag Shall I work on this issue? I want to take this up.

**Comment by stalgiag** [comment]
Sounds good @sanketsingh24 !

**Comment by sanketsingh24** [comment]
I have one doubt, what does `uvs` do [here](https://github.com/processing/p5.js/blob/master/src/webgl/p5.Geometry.js#L38)?

**Comment by Spongman** [comment]
`uv` usually refers to texture coordinates: https://en.wikipedia.org/wiki/Texel_(graphics)
