### ISSUE TITLE
New/Updated Reference examples for curveVertex() and bezierVertex().

### ISSUE THREAD

**Issue by AdilRabbani** [processing/p5.js#2735]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other (Documentation)

Hello! Looking for my first contribution for p5.js. I was thinking that the examples in the reference section for curveVertex() and bezierVertex() doesn't actually show the control points which makes it difficult for a new user to understand how these work (maybe show these points using point()). And I was also interested in introducing a new example using mouseX,mouseY so the user can interact with control points and understand how bezier and curve vertex work, just like how Sir @shiffman explained in his videos. :)

**Comment by limzykenneth** [comment]
Yes, I think it would be great to show the control points to show roughly how each point affect the curve, try to keep the reference example clear and simple though, think about how it will be used on a day to day basis. 

The new example idea sounds good to me as well, could serve as a good introduction point for new user who are familiar with vector drawings using something like Illustrator. Do go for it!

**Comment by AdilRabbani** [comment]
Updated the reference examples #2737

**Comment by AdilRabbani** [comment]
And about the interactive example. As I tested mouseX,mouseY in the references section https://p5js.org/reference/#/p5/bezierVertex, it wasn't responding to mouse movement...

**Comment by lmccart** [comment]
fixed with #2737
