### ISSUE TITLE
How to put multiple js files in html at the same time

### ISSUE THREAD

**Issue by Thorney13** [processing/p5.js#2736]
I am currently trying to create my own portfolio page with all of my javascript files in.

I am able to get one javascript file working at once but when I insert another file in only the lowest one on the page will work. 

Is there a way that you can use both simultaneously. I have tried canvas.position to move them so there is space but only one will ever show up.

Thanks

**Comment by lmccart** [comment]
the github issues here are a good place for bugs and issues with the p5.js library itself.
for questions about writing your own code or following tutorials, the [forum](https://forum.processing.org/two/) is the best place to post. thanks!

**Comment by PraneetBoggarapu** [comment]
> I am currently trying to create my own portfolio page with all of my javascript files in.
> 
> I am able to get one javascript file working at once but when I insert another file in only the lowest one on the page will work.
> 
> Is there a way that you can use both simultaneously. I have tried canvas.position to move them so there is space but only one will ever show up.
> 
> Thanks

Did you figure this out?
I'm having the same situtation right now.
Can you help me

**Comment by Hendiadyoin1** [comment]
Maybe use an iframe if you want multiple Instances of p5  to work

**Comment by haideralipunjabi** [comment]
Maybe this might help
https://codingtrain.github.io/12oclocks

https://github.com/CodingTrain/12oclocks
