### ISSUE TITLE
Did you just try to use p5.js's random() function? If so, you may want to move it into your sketch's setup() function.

### ISSUE THREAD

**Issue by Chupakabra111** [processing/p5.js#2738]
Hi, I'm a beginner and I don't know how to move the p5.js's random() function into my sletch's setup() function. If you know how to do that, please help!

**Comment by lmccart** [comment]
the github issues here are a good place for bugs and issues with the p5.js library itself.
for questions about writing and debugging your own code or following tutorials, the [forum](https://forum.processing.org/two/) is the best place to post and get help. thanks!
