### ISSUE TITLE
Feature request: adding EDGE option to filter() for edge detection

### ISSUE THREAD

**Issue by BenjaminHabert** [processing/p5.js#2747]
Edge detection could be interesting to create interactive experiments with the webcam. This would provide an easy way to locate stuff in the webcam feet.

This could be added to the list of options of the [`filter()`](https://p5js.org/reference/#/p5/filter) function. 

I am not sure about implementation details though. I can start investigate.

#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [x] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [x] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### New feature details:

TODO

#### Resources

Some infos and implementations of edge detection

- [wiki](https://en.wikipedia.org/wiki/Edge_detection). Page on [Canny edge detection](https://en.wikipedia.org/wiki/Canny_edge_detector)
- [marvinJS](https://github.com/gabrielarchanjo/marvinj/blob/master/marvinj/src/plugins/convolution/Convolution.js) : [demo](http://www.marvinj.org/en/index.html)
- [jsfeat](https://inspirit.github.io/jsfeat/#imgproc) has a ton of stuff on image processing [sobel filter demo](https://inspirit.github.io/jsfeat/sample_sobel_edge.html), [canny edge demo](https://inspirit.github.io/jsfeat/sample_canny_edge.html)
- [CannyJS](https://github.com/yuta1984/CannyJS)

**Comment by aatishb** [comment]
In case it's helpful, [this](https://kylemcdonald.github.io/cv-examples/) is a nice set of p5 computer vision demos as well (mostly using other computer vision libraries).

**Comment by BenjaminHabert** [comment]
Thanks! In this case I think it is better to keep a simple implementation to stay consistent with the rest of the filters.

Here is the [standard method](https://en.wikipedia.org/wiki/Canny_edge_detector) of edge detection:
1. Apply a gaussian smoothing (already implemented by `img.filter(BLUR)`)
2. Compute the intensity gradient using a convolution with a 3x3 kernel (Sobel / Prewitt)
3. Perform edge thinning. I am not sure but I think this is similar to what `img.filter(ERODE)` does
4. Apply threshold to have only white edges on black background (`img.filter(THRESHOLD)`)

Consequently most of the process is already implemented as filters. I propose to do the following:
- implement an `img.filter(SOBEL)` filter (step 2)
- (maybe: implement an `img.filter(EDGES)` filter that would only be a combination of other existing filters.

This way a user would have the option to use `EDGES` for a quick result but could also customize the different steps of edge detection using the combination of `BLUR`, `SOBEL`, `ERODE` and `THRESHOLD` mentioned above.

What do you think ? Also: what are the requirements in term of performance? I fear that applying 4 filters in succession will be quite demanding cpu-wise.

**Comment by BenjaminHabert** [comment]
I created a [toy example](http://www.rand-on.com/projects/2018_edge_detection/edge_detection.html) implementing the proposed method of chaining filters. Please try it out and let me know what you think.

I could also try to use the `POSTERIZE` filter..

<img width="729" alt="edge_detection" src="https://user-images.githubusercontent.com/9921832/38167516-655a7818-3536-11e8-9ffa-7266b659d4bf.png">

Also I found interesting that `filter(BLUR, 0)` still does some heavy computation although radius=0 should mean that no blurring is done. I disabled this computation in the example for r=0.

**Comment by lmccart** [comment]
I'd prefer to leave this one for an addon library, or offload to some of the great cv libraries already out there that you've linked to.
