### ISSUE TITLE
Line() and Array indecies

### ISSUE THREAD

**Issue by Hendiadyoin1** [processing/p5.js#2752]
I've tried to program a noise based 2D plane and I'm getting an exception, that i am giving the line function  an empty argument.....

Code:
`
let fdiv;
let p;

function setup() {
	fdiv = createDiv('');
	createCanvas(400, 400, WEBGL);
	setAttributes('antialias', true);

	p = new Plane(0.1, 100);
	p.generate;
}

function draw() {
	background(200);
	translate(0, 200);

	p.show();
	fdiv.html(floor(frameRate()));
}
`

Plane:
`
class Plane {
	constructor(scl, hscl) {

		this.scl = scl || 0.1;
		this.hscl = hscl || 100;
		this.pl = [];
	}
}

Plane.prototype.generate = function() {
	for (let i = 0; i <= width; i++) {
		this.pl.push(noise(i * scl) * hscl);
	}
}

Plane.prototype.show = function() {
	//console.log('show');
	for (let i = 1; i <= width; i++) {
		stroke(0);
		strokeWeight(2);

		line(i - 1, this.pl[i - 1], i, this.pl[i]);
		//console.log(i);
	}
}
`
Error:
<
p5.js says: line() was expecting Number for parameter #3 (zero-based index), received an empty variable instead. If not intentional, this is often a problem with scope: [https://p5js.org/examples/data-variable-scope.html] at file:///C:/Users/Leon/Desktop/Informatik/p5/2d_noise/Plane.js:21:3. [http://p5js.org/reference/#p5/line]
>

**Comment by aatishb** [comment]
Hi there! This type of question might be better suited for the p5.js [programming forum](https://forum.processing.org/two/categories/p5-js-programming-questions) where you can ask programming questions. I took a look at your code and there are a few small issues. The version below makes a plot.

```
let fdiv;
let p;

function setup() {
  fdiv = createDiv('');
  createCanvas(400, 400, WEBGL);
  setAttributes('antialias', true);
  translate(0, 200); // translate() should be in setup
                    // or if in draw loop use push() and pop()
                   // to avoid accumulating translations

  p = new Plane(0.1, 100);
  p.generate(); // was missing ()
}

function draw() {
  background(200);

  p.show();
  fdiv.html(floor(frameRate()));
}

class Plane {
  constructor(scl, hscl) {

    this.scl = scl || 0.1;
    this.hscl = hscl || 100;
    this.pl = [];
  }
}

Plane.prototype.generate = function() {
  stroke(0);        // moved these out of the for loop
  strokeWeight(2);  // so they aren't being reapplied
  for (let i = 0; i <= width; i++) {
    // use this.var to refer to variables associated with the class
    this.pl.push(noise(i * this.scl) * this.hscl);
  }
}

Plane.prototype.show = function() {
  //console.log('show');
  for (let i = 1; i <= width; i++) {
    line(i - 1, this.pl[i - 1], i, this.pl[i]);
  }
}

```

**Comment by Hendiadyoin1** [comment]
Thank you
that has fixed this problem, but it is shiftet to the right by half width and idk why in the translate its only shiftet to the bottom do you have an Idea to fix that...

**Comment by kjhollen** [comment]
@Hendiadyoin1 glad this was fixed! github is for bugs and issues with p5.js itself. please post further questions to https://forum.processing.org/two/categories/p5-js-programming-questions where other users can help debug your code. thanks!
