### ISSUE TITLE
Can not setMag to p5.Vector if vector mag is 0.

### ISSUE THREAD

**Issue by KlaussMC** [processing/p5.js#2754]
I have vector `a`. It is brand new, it's magnitude is 0. I need to set it to 25. `a.setMag(25)` does not change it's magnitude. after checking in the console, it is still set to 0.

please fix

**Comment by aatishb** [comment]
Hi @KlaussMC. This seems more a vector math thing than a bug to me. Once a vector has zero length it has no magnitude *and* no direction. So when you try to increase its magnitude, there is no way to know which direction you would like this vector to point.

A way around this would be to multiply a unit vector in the desired direction by your desired magnitude. Alternatively, just start your vector off with a very small but non zero magnitude.

```
  let unitVec = createVector(1,1).normalize();

  let zeroVec = unitVec.copy().mult(0);
  console.log(zeroVec.mag());

  let shortVec = unitVec.copy().mult(52);
  console.log(shortVec.mag());

```

That being said, maybe applying setMag() and other vector functions that are undefined on a zero length vector should give an appropriate warning/error?
