### ISSUE TITLE
update preload() docs to mention use of loadX() methods in setup for non-blocking functionality

### ISSUE THREAD

**Issue by clankill3r** [processing/p5.js#2764]
Hi,

I often have students that use p5.js.
I notice it is really common that p5.js get's stuck on "Loading ...".
This can be when they type a filename wrong or a path or when a server is down where they try to load content from.

It would be nice if p5.js was bit less blocking.

my 2 cent

**Comment by limzykenneth** [comment]
JS is non-blocking by default, we made loading in `preload` blocking just so it is a bit more straightforward for those who came from other languages and to defer explaination of asynchronicity from beginners to programming. If you wish to use the loading functions in a non-blocking way, simply call them in `setup` instead and use the callbacks to handle data returned from the server.

**Comment by lmccart** [comment]
thanks @clankill3r! @limzykenneth is correct... I think it would be good to add a note about this in the reference entry for preload() so people can discover this on their own. I will update the issue title now.

**Comment by lmccart** [comment]
@faithwyu maybe this is one you might want to tackle?

**Comment by Spongman** [comment]
it might be worth looking into providing more verbose error messages for some of these methods, especially when no error callback function is provided.

**Comment by faithwyu** [comment]
@lmccart yes i will look into it. thanks for letting me know.

**Comment by lmccart** [comment]
fixed with https://github.com/processing/p5.js/pull/2772
