### ISSUE TITLE
Issue template: "Most appropriate sub-area of p5.js?"

### ISSUE THREAD

**Issue by Qoutroy** [processing/p5.js#2768]
#### Most appropriate sub-area of p5.js?

- [ ] Core
- [x] Other (specify if possible): Github...

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [ ] Desktop/Laptop
- [x] Others (specify if possible): Github...

#### Feature enhancement details:
The Issue template want you to enter what the "Most appropriate sub-area of p5.js" this issue has to do with, and most people might not know what "core" means. Shouldn't it instead say "Environment/Rendering" or at least "Core/Environment/Rendering"? Also, you might want to add one for "Documentation"?

##### "Recreation" of "bug": #2765

**Comment by limzykenneth** [comment]
I believe the categories are based on the directory structure here https://github.com/processing/p5.js/tree/master/src, while I do think maybe it can be refined a bit.
