### ISSUE TITLE
Chrome performance issue

### ISSUE THREAD

**Issue by ceg-exp** [processing/p5.js#2769]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other (Rendering in Chrome)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.6.0
- Web browser and version: Chrome 65.0.3325.181
- Operating System: MacOSX 10.11
- Steps to reproduce this:
Really any type of animation using the draw() function doesn't run at 60 fps, instead getting around 10-15 depending on canvas size. CPU usage goes trough the roof. Any other browser which do no use a similar engine as Chrome can effectively render the animation at a steady 60 fps (on the same machine). No explanation could be found using the dev tools. Weirdly enough everything worked fine a couple weeks ago, but now it's all broken, even after a clean install of the browser. Wondering if this has anything to do with the P5 program. Otherwise sorry for bothering you. Thanks.

**Comment by lmccart** [comment]
are you using p5.js or p5.min.js?
p5.min.js runs much faster because it doesn't utilize the built-in friendly error checking

**Comment by ceg-exp** [comment]
I'm currently using p5.min.js, and I've actually tested with both libraries and the issue remains the same.

**Comment by aatishb** [comment]
I've been seeing the same error over the past few weeks specifically in Chrome (Firefox and Safari are fine). It occurs both in p5.js and p5.min.js. Ran the following code to investigate it:

```
function setup() {
    createCanvas(windowWidth, windowHeight);
}

function draw() {
    background(255);
    text('frame rate: '+round(frameRate()), 10,30);
    text('width: '+width+' height: '+height, 10,60);
}

function windowResized(){
	resizeCanvas(windowWidth, windowHeight);
}

```
It looks like the frame rate falls really fast once the canvas size gets closer to full screen. 
![chart 18](https://user-images.githubusercontent.com/1878638/38524490-bddecbdc-3c1c-11e8-81d1-683be3e2fdd0.png)

I was able to get back to 60 fps by [disabling hardware acceleration](https://www.technize.net/google-chrome-disable-hardware-acceleration/) in chrome. It looks like this is related to [this chrome bug](https://bugs.chromium.org/p/chromium/issues/detail?id=823335&q=canvas&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified).

**Comment by ceg-exp** [comment]
That seems to be it! I disable hardware acceleration and lo and behold, performance is back to normal. Thank you very much!

I wonder why this issue happened in the first place, as I remember seeing the hardware acceleration feature before, and it never seemed to cause any problem until now.

**Comment by Spongman** [comment]
you might also try adding `pixelDensity(1);` after the `createCanvas()` call. might help...

**Comment by aevin-io** [comment]
> pixelDensity(1)

you saved the day!
