### ISSUE TITLE
p5.js save() and saveCanvas not working on unsupported browser and fix

### ISSUE THREAD

**Issue by Huc91** [processing/p5.js#2777]
I wanted to save my canvas as an image with browsers that don't support force download.
I run into this "issue" but it's not a p5.js problem, it'a a browser compatibility problem.
So I'm gonna leave here the solution to save hours to someone else that will have the same problem.

Add this two beatiful library 
[FileSaver.js](https://github.com/koffsyrup/FileSaver.js)
[canvas-toBlob](https://github.com/eligrey/canvas-toBlob.js)

And now down to the code:
reference the canvas element by getting the id in a variable
mine is `'defaultCanvas0'`
`var canvas = document.getElementById('defaultCanvas0');`

and then add this snippet
```
      canvas.toBlob(function(blob) {
        saveAs(blob, "your-image.jpg");
      });
```
That's it
And with this you will also support browser that don't support the blob function

**Comment by Huc91** [comment]
It's just a tip for someone else that will have this problem, not a proper issue so i'm closing it

**Comment by Spongman** [comment]
just curious, which browser are you using?

this should have been addressed in #2270, #2389.

**Comment by Huc91** [comment]
Didn't saw these threads it would have saved me multiple headaches. I was using Safari 9

**Comment by Spongman** [comment]
oh yeah, that's pretty old. i don't think there's an official list of precisely what browsers are supported, but since we decided not to add `cavas-toBlob` as a dependency, i'm assuming Safari 9 wouldn't be on it ;-)

**Comment by Huc91** [comment]
Yep and I wasn't expecting it :-D
