### ISSUE TITLE
no education page for p5 

### ISSUE THREAD

**Issue by vamshi9666** [processing/p5.js#2778]
in community documentation, its mentioned a link about education page . but there is no actual educaton page neither in p5 docs nor in github wiki.

if any one clicked link in docs to education page , it automatically redirects to create a page in wiki .
so it will be helpful , if there is official education page . in further it can be modified 

[link to docs](https://p5js.org/community/#contribute)

**Comment by lmccart** [comment]
This issue was moved to processing/p5.js-website#184
