### ISSUE TITLE
factorial and combinatorics in p5

### ISSUE THREAD

**Issue by Hendiadyoin1** [processing/p5.js#2783]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
-  Math
- [ ] Typography
- Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### New feature details:

in the following folder is the factotrial function and an isInt() function and a try to reverse the factorial, also nCr and nPr codingwork would be nice if someone could implement this in p5.js
[Math_expansion_factorial.zip](https://github.com/processing/p5.js/files/1910689/Math_expansion_factorial.zip)

**Comment by lmccart** [comment]
I think this function is beyond the scope of the p5.js api but it could be a great starting point for an addon library. see the docs here for how to create an addon: https://github.com/processing/p5.js/wiki/Libraries#creating-a-new-library

**Comment by chrsmlls333** [comment]
Link wrong:
https://github.com/processing/p5.js/wiki/Creating-Libraries

😄
