### ISSUE TITLE
autosizing createCanvas()

### ISSUE THREAD

**Issue by Spongman** [processing/p5.js#2787]
in order to create a full-page canvas without scrollbars, there's a whole bunch of work users have to go through, minimally:

```javascript
function setup() {
  var renderer = createCanvas(windowWidth, windowHeight);
  renderer.canvas.style.display = 'block';
}
function windowResized() {
  resizeCanvas(windowWidth, windowHeight);
}
```

PR #2741 reduces all of that down to, simply:
```javascript
createCanvas();
```

no existing behavior is altered.

**Comment by lmccart** [comment]
i'm not seeing much energy around this one, so i'd like to leave as is for now.
