### ISSUE TITLE
.changed() not working correctly with textarea elements

### ISSUE THREAD

**Issue by F4Tornado** [processing/p5.js#2794]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other DOM

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: If `.changed(fxn)` is being used for textarea, the function isn't called until you click out of the textarea.

- p5.js version:  p5.js v0.6.0 January 19, 2018
- Web browser and version:  Chrome, Opera, Edge, IE, Firefox developer edition (All the web browsers I have)
- Operating System: Windows 10
- Steps to reproduce this:

```html
<textarea id="editor"></textarea>
```
```javascript
let editor;

function setup() {
  noCanvas();
  editor = select("#editor");
}

function draw() {
  editor.changed(edited);
}

function edited() {
  console.log("edited!");
}
```

**Comment by F4Tornado** [comment]
I'm having to use this hack:

```javascript
if (editor.value() != pval) {
  edited();
}
```
where pval is the value of the textarea

But I still think it's a problem

**Comment by Spongman** [comment]
The HTML `onchanged` event for `textarea`s is only fired when focus is lost after a value change. In order to trigger events on input change (key press, clipboard action, etc...) it's necessary to listen to the `oninput` event also.
