### ISSUE TITLE
P5.js Website homepage - IE/Microsoft Edge detection link javascript bug

### ISSUE THREAD

**Issue by caswallon** [processing/p5.js#2795]
My apologies for putting the bug here, however the forums are not currently accepting new user registration while they are switching platforms, and I was unable to find this issue reported elsewhere.

On the P5.js website itself, there is a bug in the script that is intended to fix a CSS issue with the links on Microsoft IE/EDGE.

`  var EDGE_IE_REGEX = /(?:\b(MS)?IE\s+|\bTrident\/7\.0;.*\s+rv:|\bEdge\/)(\d+)/;
  if (EDGE_IE_REGEX.test(navigator.userAgent)) {
    var links = document.getElementsByTagName('a');
    for (var i=0, l=btns.length; i < l; i++) {
      links[i].style.display = 'inline-block';
    }
  }`

In the code snippet above, there is a reference to a variable **btns** that does not exist and should probably be referencing **links** based on context.

This appears to only apply to the homepage.

**Comment by kjhollen** [comment]
moved this over to the website repo. thanks!
