### ISSUE TITLE
saveCanvas only working properly with no arguments

### ISSUE THREAD

**Issue by enauman** [processing/p5.js#2796]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [x] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: web editor
- Web browser and version: Chrome 65.0.3325.181
- Operating System: Mac OS 10.12.6
- Steps to reproduce this:
Call function saveCanvas() with no arguments, it will download an "untitled.png" image, add any arguments as described in documentation and different bugs happen:
saveCanvas(c, 'myCanvas', 'jpg'); //nothing happens, no file downlaoded
saveCanvas(c, 'myCanvas'); //nothing happens, no file downloaded
saveCanvas(c); //nothing happens, no file downloaded
saveCanvas('myCanvas', 'png');  //file downloaded is named myCanvas.myCanvas
saveCanvas('myCanvas'); //file downloaded is named myCanvas.myCanvas
saveCanvas(); //this works! downloads untitled.png

**Comment by limzykenneth** [comment]
This has been fixed in #2651 and will be available in the next release.

**Comment by enauman** [comment]
Sorry! Didn't realize how the release cycle works. Thanks!
