### ISSUE TITLE
Adding an arrow function?

### ISSUE THREAD

**Issue by aatishb** [processing/p5.js#2799]
#### Nature of issue?
- [x] New feature request

#### Most appropriate sub-area of p5.js?
- [x] Math

#### New feature details:

I wanted to add some visual inline examples for the p5 Vector methods. Since the direction of a vector is important, they are often represented by arrows. I was wondering if it might be worth adding a 2D arrow drawing function to p5, something like [this](https://alpha.editor.p5js.org/aatish/sketches/rykTnTunz). I'm not sure if this is a frequent enough use case to add a new function (maybe it could be a p5 vector function?). Alternatively I could add the drawArrow function to any examples that use it, but that might start getting cluttered.

**Comment by aatishb** [comment]
Hm, perhaps this is fairly specific purpose. Closing this for now, I'll just include an arrow function with the examples.

**Comment by GodWoold** [comment]
Solved ✓ https://editor.p5js.org/ThatsTrue/sketches/bMPCzWQFl
