### ISSUE TITLE
Unexpected behaviour of specularMaterial()  with ambientLight() and directionalLight()

### ISSUE THREAD

**Issue by lorenzo-lipparini** [processing/p5.js#2800]
#### Nature of issue?

- [x] Found a bug *(?)*

#### Most appropriate sub-area of p5.js?

- [x] WebGL

#### Details about the bug: 

While playing around with materials in *WebGL* mode, I noticed that shapes drawn using `specularMaterial()` respond in a strange way to light sources created with the `ambientLight()` and `directionalLight()` functions:
in fact, the result seems to be exactly the same as what you would get using `ambientMaterial()`.

I'm not sure whether this behavior is intended or not, but this seems strange to me because, when using `pointLight()` instead, the two materials look completely different (`specularMaterial()` being much shinier as you would expect).

This effect can be easily seen just by editing the example sketches in the p5 reference pages about `ambientLight()` and `directionalLight()`.

**Comment by Spongman** [comment]
yes indeed. currently specular materials are not affected by directional lights.

this has been fixed in #2670.

**Comment by lorenzo-lipparini** [comment]
Thank you;
so in your example the spheres are drawn first with `ambientMaterial()` and then with `specularMaterial()`, right?

**Comment by sanketsingh24** [comment]
@Spongman @stalgiag I think this has been fixed now. There is also a manual test (/webgl/material/specular_ambient) which also shows the expected behaviour.

**Comment by aferriss** [comment]
Going to close as it seems this has been fixed.
