### ISSUE TITLE
add optional parameter to round() for number of decimal places?

### ISSUE THREAD

**Issue by aatishb** [processing/p5.js#2802]
#### Nature of issue?
- [x] New feature request

#### Most appropriate sub-area of p5.js?
- [x] Math

#### New feature details:

I often need to round numbers to a few decimal places (mainly for printing to screen or console logging). It would be nice if there was a function for this. I looked at nf() but that doesn't round the number, and also requires you to specify digits to the left of the decimal point.

I suggest an optional second argument to round so that round(PI, 2) will return 3.14. A simple implementation might be `round(num * pow(10, i)) / pow(10, i)` although there might be a better way to handle this. If this seems useful to others, I'm happy to add it in.

**Comment by lmccart** [comment]
if you are ok with truncating, the [nfc](https://p5js.org/reference/#/p5/nfc) function should do what you need. if it's important to round, I think you could just multiply by 100, round, and then divide. I'm not sure we need a separate method for this as it might be a bit beyond the scope of this library but I guess we can see if others are strongly in favor of adding this.

**Comment by Spongman** [comment]
i think you may be looking for `Number.prototype.toFixed()`: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toFixed

**Comment by aatishb** [comment]
Ah, toFixed() is exactly what I'm looking for, thanks. I can just use that.
