### ISSUE TITLE
Image resize() doesn't work in p5.js

### ISSUE THREAD

**Issue by abi62210** [processing/p5.js#2803]
I was trying to resize the image to make it smaller/bigger but well-proportioned as described in reference: http://alpha.editor.p5js.org/shiffman/sketches/B1SmhBLJx while the error message showed up saying: "Uncaught TypeError: img.resize is not a function (sketch: line 13)."

I'm not sure is there anything wrong in my code?

var img;

function setup() {
  createCanvas(400, 400);
  img = createImg('http://www.petwebsite.com/hamsters/hamsters_images/syrian-hamster_000008437184.jpg');
  img.hide(); 
}

function draw() {
  background(100);
  image(img, 0,0,width,height); 
  img.resize(200,0);
}

**Comment by aatishb** [comment]
Hi, [createImg](https://p5js.org/reference/#/p5/createImg) creates an image [element](https://p5js.org/reference/#/p5.Element), whereas [loadImage](https://p5js.org/reference/#/p5/loadImage) loads a [p5.Image](https://p5js.org/reference/#/p5.Image) object. I think you want to use loadImage here instead. Also many browsers will block images if they aren't coming from a https url, so watch out for that.

So for example the following code works for me:

```
var img;

function preload() {
  img = loadImage('https://aatishb.com/entropy/media/sadsheep.jpg');
}

function setup() {
  createCanvas(400,400);
  background(255);
  img.resize(200, 200);
  image(img, 0, 0);
}
```

**Comment by lmccart** [comment]
thanks @aatishb, this is correct loadImage() makes a little more sense. though it's important to note the .resize() method is meant to be used only with createImg(). a way to do this is like this, using the optional width and height parameters in the image call:


```
var img;

function preload() {
  img = loadImage('https://aatishb.com/entropy/media/sadsheep.jpg');
}

function setup() {
  createCanvas(400,400);
  background(255);
  image(img, 0, 0, 200, 200);
}
```

@abi62210 the github issues are just for library bugs, for programming help, the [forum](http://forum.processing.org) is the best place to post. thanks!
