### ISSUE TITLE
beginShape/endShape convert LINES shape to triangle fan in WEBGL.

### ISSUE THREAD

**Issue by LBdN** [processing/p5.js#2804]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.6.0
- Web browser and version: chrome 65
- Operating System: win10
- Steps to reproduce this:

create a LINES shape : 

```
        sketch.beginShape(sketch.LINES);
        for (var e of this.edgePool.values()) {
            sketch.vertex(e.x1, e.y1, 0);
            sketch.vertex(e.x2, e.y2, 0);            
        }
        sketch.endShape(sketch.CLOSE);     
```

see the triangle fan displayed instead.

Probably because those lines in p5.js code : 
https://github.com/processing/p5.js/blob/834b6eccf4b0ddf9aff129aad864309f9c81569b/src/webgl/p5.RendererGL.Immediate.js#L234

the code converts the LINES shapes into a triangle fan.

**Comment by Spongman** [comment]
This should be fixed in #2670

**Comment by lmccart** [comment]
@Spongman it may be a while before we're able to merge that PR because it's so large. i would welcome pulling out some of these smaller fixes and submitting as individual PRs if you'd like to get them merged faster.

**Comment by Spongman** [comment]
@kjhollen has already reviewed it and requested changes thati have made. It really an be broken up any further.

**Comment by hamoid** [comment]
Is this the same bug? https://discourse.processing.org/t/custom-shape-not-filled-correctly-with-webgl/4631

**Comment by AdilRabbani** [comment]
Hey @stalgiag I decided to look into this issue and noticed that the current WebGL implementation of LINES with beginShape, fills the shape with a specified color whenever fill() is used. While it can be seen that fill() does not have any effect when drawing shapes with LINES, in 2D mode. Shouldn't this be the desired behavior for WebGL mode as well? i.e for shapes with LINES, it should be ignoring `p5.RendererGL.prototype._drawFillImmediateMode` function altogether, drawing only the line strokes with `p5.RendererGL.prototype._drawStrokeImmediateMode`.

**Comment by stalgiag** [comment]
Hi @AdilRabbani I agree that it probably makes sense to make this consistent between 2D and 3D. I haven't been tracking this issue since getting back into the swing of the project but what you are saying seems like a sensible place to start.

**Comment by Spongman** [comment]
i think one of the issues is that 'fill' doesn't really mean anything in 3d.

except, maybe a delaunay triangulation of the convex hull of the points given. but i think that's way beyond the scope of p5.

**Comment by AdilRabbani** [comment]
Tested on Processing v3.4. No fill for shapes drawn with LINES.

![1](https://user-images.githubusercontent.com/15272015/54453382-027ef380-4779-11e9-91f8-97f1a3b03b96.PNG)

So should I submit a PR passing the correct edges for LINES so as to close this issue? Would also limit LINES to only draw line strokes rather than having a weird effect from fill().
