### ISSUE TITLE
A Video's 'ready to play' function doesn't work in different browsers.

### ISSUE THREAD

**Issue by Al-bukair** [processing/p5.js#2808]
Hi!

video = createVideo([video.format], readytoplay);

looking at the code above, the browser is meant to trigger the 'readytoplay' function whenever the video is ready to play, this works perfectly in explorer however it doesn't work in chrome or safari.

In chrome the function is trigger very quickly & the audio plays while the video doesn't. In safari the whole sketch doesn't work.

Any solutions? or maybe a work-around that I should know about.

Thanks :)

**Comment by acasmith** [comment]
Heya! Just been playing with this I can't seem to replicate this issue in either chrome or safari using the example code found [here](https://p5js.org/reference/#/p5/createVideo), could you post all of your code? Also, is anything being output in the console when you run your sketch?

**Comment by Al-bukair** [comment]
Thanks for the reply!

In my code I use the function to trigger loading 6 other short videos & playing the main video. but only two short once load and the main video isn't, even if it's playing there is no frames displayed. This is only in Chrome.

**Comment by Al-bukair** [comment]
This is a solution I found in google's developers page (https://developers.google.com/web/updates/2017/06/play-request-was-interrupted):
// Show loading animation.
  var playPromise = video.play();
 
  if (playPromise !== undefined) {
    playPromise.then(_ => {
      // Automatic playback started!
      // Show playing UI.
      // We can now safely pause video...
      video.pause();
    })
    .catch(error => {
      // Auto-play was prevented
      // Show paused UI.
    });
  }

but it returns: TypeError: playPromise.then is not a function

**Comment by acasmith** [comment]
Hey,
If you've got lots of code, you can use [CodePen](https://codepen.io/#) to link it so it doesn't eat your post. I think it would be useful if you could link it. Were the errors shown in that google link (```Uncaught (in promise) DOMException:...```) occuring in your original code?

**Comment by Al-bukair** [comment]
Yes the error is in the original code, before I tried to use the code in google's developers page.

Here you could see it working in real time: http://touchtick.com/

**Comment by Al-bukair** [comment]
Thanks for your replies, I will start over and see if it works, otherwise I will post the issue again but more clearly.
