### ISSUE TITLE
Bezier artifacts

### ISSUE THREAD

**Issue by Nemecsek** [processing/p5.js#2810]
I am writing a Sankey library using P5.js 0.6.0 and I need to paint thick bezier curves to represent the links.

The problem is a bezier artifact that appears when two nodes (linked by a bezier curve) are too close: P5.js tries to maintain the thickness of the curve, but the algorithm to trace the outline is wrong.

Control points are always 50% of the space between the nodes.

This is the normal bezier:
![sankey1](https://user-images.githubusercontent.com/25978536/39191006-2bde43fa-47d6-11e8-936d-b0e4d949a32a.png)

Moving NODE2 to the left, this is the last moment when the curve is correct, even if slightly deformed (the sigma shape is gone):
![sankey2](https://user-images.githubusercontent.com/25978536/39191085-5f8fae8c-47d6-11e8-9eb8-8a083f3b4156.png)

Continuing the movement of NODE2 to the left, here we can see that a part of the bezier is already overlapping NODE1's rectangle:
![sankey3](https://user-images.githubusercontent.com/25978536/39191367-1955d9c2-47d7-11e8-947f-8f052f573c9f.png)

And here it is completely wrong:
![sankey4](https://user-images.githubusercontent.com/25978536/39191382-235462a4-47d7-11e8-9d6f-f87647f665df.png)

I thought that it would be nice to recognize this faulty behavior, so the bezier could be easily avoided using a romboid instead.

Which algorithm has been used for tracing the outline? 
Or is it possible to understand when this is happening? 

There is a workaround, but I would prefer a more "mathematical" solution:

1. print an exact copy of the bezier off canvas, black on white;
2. working off canvas, paint white the whole space between the two nodes, so the part of bezier that is correct  disappears;
3. check for the presence of black pixels: these would mean the bezier is being traced wrong and must be avoided;
4. on the real canvas then use a bezier (if there where no black pixels) or a romboid  (there were black pixels: it is not possible to trace a proper bezier).

![sankey_test](https://user-images.githubusercontent.com/25978536/39193524-0ec2f94a-47dc-11e8-85a1-439fc7234e11.png)

**Comment by Spongman** [comment]
Interesting... However, P5.js just uses the browser's `<canvas>` tag to draw beziers and their outlines. I would suggest trying a different browser and seeing if you get the same artifacts.

**Comment by Spongman** [comment]
weird. here's inkscape doing the same thing:
![image](https://user-images.githubusercontent.com/1088194/39231637-92f7165e-481f-11e8-943e-ac0d5c6f081f.png)

i guess everyone uses the same code for drawing beziers ;-)

**Comment by Nemecsek** [comment]
@Spongman, I solved it as I described in my workaround and it works better than I thought. 

This is the result:
![screenshot from 2018-04-27 08-40-52](https://user-images.githubusercontent.com/25978536/39349051-d022a3d2-49f9-11e8-879a-690ce53f50f7.png)

Here the algorithm: the yellow rectangle is normally hidden and represents the red-node background + 1 pixel border. Smaller is faster so I kept it as small as possible. 
Before tracing the bezier I trace it on this off canvas graphics and check two pixels of it: for a correct bezier you should see black only on the rightmost column. Any other black pixel (you can see a little bottom "horn" here) means there is an artefact and my shape should be used instead.
![screenshot from 2018-04-27 08-40-52 1](https://user-images.githubusercontent.com/25978536/39349155-342dfc8c-49fa-11e8-970e-d7808bd94ca6.png)

**Comment by limzykenneth** [comment]
If I understand correctly this is a result of the algorithm implementation of the individual browser renderers and not with p5 itself? If that's the case I would suggest opening bug reports over at the relevant browsers channel and close this issue since we can't fix it in the library itself without anything short of rolling our own bezier drawing algorithm (which I think is a gross overkill)

**Comment by Nemecsek** [comment]
@limzykenneth, it is not only a problem in the browser renderers: as @Spongman noted, there is the same problem in Inkscape too. It looks like more people is using the same (defective) algorithm to calculate the bezier outline. 
It would be nice to understand were they took it from.

**Comment by limzykenneth** [comment]
I did some digging and I believe in terms of bezier curves, what you see is actually the "correct" (intended) behaviour. See this [stackoverflow question](https://stackoverflow.com/questions/34266565/thick-bezier-curves-in-svg-without-artifacts) asking the same question and also this [jsfiddle](https://jsfiddle.net/83jr5fub/2/) for what is actually happenning, in a way the curve is folding upon itself at that thickness.

I don't know much about the math and raterization steps for bezier curve but I suspect that this is how bezier curves are meant to behave.

**Comment by Nemecsek** [comment]
Thank you for the time you gave me and the links.
I will close the issue as there is nothing more to be said about it at least for p5.js.  I will follow any news at stackoverflow.
