### ISSUE TITLE
p5.js WebGL Updates - gSoc 2018

### ISSUE THREAD

**Issue by AdilRabbani** [processing/p5.js#2811]
Hello p5.js contributors! I am creating this issue so I can get to know all the major contributors to the p5.js WebGL code.
My project is to implement most of the missing WebGL primitives in p5 (point, arc, text, bezierVertex, curveVertex, quadraticVertex). It would help a lot, if you people can guide me where to start if I'm to familiarize myself with the codebase, most importantly the WebGL section.
I also want to know how much progress has been done on implementing these primitives and what needs to be done. I have already gone through the WebGL Module Architecture page.
Mentor : @mlarghydracept 
Tagging : @kjhollen , @Spongman 
P.S. I would be asking a lot of questions here, so please bear with me... 😀

**Comment by mlarghydracept** [comment]
Glad to have you @AdilRabbani! Everything that @kjhollen said is right on point. I would also suggest doing a quick line-by-line step through in a web console on a few of the [manual test examples](https://github.com/processing/p5.js/tree/master/test/manual-test-examples/webgl) for WebGL. This will help you get a quick overview of how the different parts of the code base are interacting currently.

**Comment by AdilRabbani** [comment]
Hello everyone, I'm almost done with implementing arc() for WebGL mode. Can someone make a new branch for GSOC-2018 in the main repo? so the code can also be reviewed, while discussing other issues. @lmccart @kjhollen @mlarghydracept

**Comment by kjhollen** [comment]
Hi @AdilRabbani, I've made a new branch here: https://github.com/processing/p5.js/tree/webgl-gsoc-2018

When you make your pull requests, you can have it compare to this branch and I'll merge it there.

**Comment by AdilRabbani** [comment]
#2913 @kjhollen @mlarghydracept

**Comment by kjhollen** [comment]
hey folks, I'm going to close this issue because things are tracked well elsewhere. anyone interested in following along can have a peek at the webgl-gsoc-2018 branch. thanks! 😃
