### ISSUE TITLE
createCanvas() doesn't return an HTMLCanvasElement

### ISSUE THREAD

**Issue by lorenzo-lipparini** [processing/p5.js#2817]
#### Nature of issue?

- [x] Found a bug
#### Most appropriate sub-area of p5.js?

- [x] Core/Environment/Rendering

#### Details about the bug: 

The documentation states that the `createCanvas()` function should return an `HTMLCanvasElement` corresponding to the created canvas, but this is clearly not the case since a `p5.Renderer` is returned istead.

The thing happens in [this](https://github.com/processing/p5.js/blob/master/src/core/rendering.js#L116) line of code of the p5 source.

However, I'm not really sure about which one is wrong between the documentation and the implementation.

**Comment by limzykenneth** [comment]
`createCanvas` is indeed supposed to return a `p5.Renderer` instance and not a `HTMLCanvasElement`. The documentation probably should be corrected in this case, if anyone wants to make a PR for this change please feel free. 😃

**Comment by lad475** [comment]
I can take care of this; I'll make the PR in a bit :)

**Comment by lmccart** [comment]
fixed with https://github.com/processing/p5.js/pull/2823

**Comment by Spongman** [comment]
What's even weirder is that createCanvas doesn't really create a new canvas at all. It just replaces the existing canvas with a canvas of the right size (and renderer).

**Comment by PixsaOJ** [comment]
What is weirder is, if I use `canvas = createCanvas(...)` In typescript I should be getting `HTMLCanvasElement` so I can set width height and other properties to it, but when I get `Renderer` I have to give my variable type of p5.Renderer | HTMLCanvasElement
