### ISSUE TITLE
loadShader is broken in preload

### ISSUE THREAD

**Issue by Spongman** [processing/p5.js#2821]
re: #2697, # #2717

@meiamsome fixed an issue with the preload stuff in #2697. the result of this fix is that the preload count actually works as expected now wrt. nested calls & instance-mode. however, loadShader() needs to be updated to use the fixed preload semantics. as it is, when loadShader is called in preload, the preload never completes.

**Comment by lmccart** [comment]
closed with https://github.com/processing/p5.js/pull/2815
