### ISSUE TITLE
`color()` is unnecessarily slow

### ISSUE THREAD

**Issue by Spongman** [processing/p5.js#2830]
0.6.1

the implementation of `color()` uses `map()` (inside `_parseInputs` and `_calculateLevels`) to loop through the color components for scaling/clamping operations.

in a simple test case:
```javascript
p5.disableFriendlyErrors = true;
function setup() {
  createCanvas(100, 100);
}
function draw() {
  for (var i = 0; i < 100000; i++)
    color([255,0,100,255]);
}
```

these `map` call result in >90% of total CPU usage:
![image](https://user-images.githubusercontent.com/1088194/39409698-9f9edb4c-4ba0-11e8-8683-5321287c37ed.png)

**Comment by JohnnyDeeee** [comment]
Anything on this?
Because of this, i cant use this library because i keep getting a 0.5~ framerate on chrome.
Once i remove all my color() references, the framerate becomes acceptable...

**Comment by limzykenneth** [comment]
@JohnnyDeeee The associated PR should be ready to merge but it may not be until the next release do this fix gets incorporated into the library. If you need it urgently you can try building from the PR source.
