### ISSUE TITLE
get() is slow

### ISSUE THREAD

**Issue by Spongman** [processing/p5.js#2832]
0.6.1

re: #2822, #2065, #1485, #1235

currently there are two ways of getting pixel values from p5.js canvas/image/video elements:
1) call the `get(x,y)` method.
2) call `loadPixels()` and access the `pixels[]` array directly.

the problem with 1) is that it's _really_ slow (calling `getImageData()` for every value) and the problem with 2) is that it's really complicated for the user to get right (you need to handle non-integer inputs, check for out-of-bounds conditions, scale correctly for pixelDensity, etc...).

**Comment by VelizarHristov** [comment]
I agree - it would be great if there was a get() method which for its arguments takes x, y, and a pixels array.
(And possibly the pixel density, if it takes a non-trivial amount of compute to calculate every time)
