### ISSUE TITLE
pixelDensity value different according to the browser

### ISSUE THREAD

**Issue by Nemecsek** [processing/p5.js#2834]
There is something strange about `pixelDensity`.

Firefox 59.0.2 is returning `pixelDensity=1` and` displayDensity=1`. 
Chromium  64.0.3282.167 returns `pixelDensity=2` and `displayDensity=1.5`
Opera 51.0.2830.40, like Firefox, 1 and 1.

Is this normal?
#### Most appropriate sub-area of p5.js?
- [X] Core/Environment/Rendering

#### Which platform were you using when you encountered this?

- [X] Desktop/Laptop

#### Details about the bug: 

- p5.js version: local copy of ver 0.5.16. 
- Web browser and version: Chromium 64.0.3282.167, Firefox 59.0.2, Opera 51.0.2830.40
- Operating System: Ubuntu 16.10
- Steps to reproduce this:

```
<html>
<head>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.6.1/p5.min.js"></script>
</head>
<body style="background-color: lavender">

<script>

    let sketch = function(p) {

        p.setup = function() {
            console.log("pixelDensity:" + p.pixelDensity());
            console.log("displayDensity:" + p.displayDensity());
        };
    };

    let myp5 = new p5(sketch, "sankey_1");

</script>

<div id="sankey_1"></div>

</body>
</html>
```

**Comment by Nemecsek** [comment]
I found out what it is happening: Firefox 59.0.2 is returning `pixelDensity=1` and` displayDensity=1`. 
Chromium  64.0.3282.167 returns `pixelDensity=2` and `displayDensity=1.5`
Opera 51.0.2830.40, like Firefox, 1 and 1.

I didn't see that different browsers return different values (and different scaling because of this).

**Comment by kjhollen** [comment]
Hi @Nemecsek, the values of pixelDensity and displayDensity can vary depending on browser scaling, but with default scaling (100%), I think they should be the same. I don't have an Ubuntu box for testing, but on my Mac these values match on Firefox and Chrome consistently unless I zoom in/out (say with ctrl+plus or ctrl+minus), then they begin to vary. Is Chromium scaled up for some reason? Are you using a retina or high density display device?
