### ISSUE TITLE
problems installing p5js with NPM/Bower

### ISSUE THREAD

**Issue by mikima** [processing/p5.js#2837]
Hello,

i tried to use both bower and npm to add p5js to my project.

In NPM the package is [registered as "P5"](https://www.npmjs.com/package/p5). However, when you try to add it, it will install a lot of dependencies, since you left "grunt-mocha" as [dependency for p5v0.6.1](https://www.npmjs.com/package/p5?activeTab=dependencies).

In Bower the package is named "p5js" and [redirects to this repo](https://github.com/lmccart/p5.js-release.git), but the [latest available version is 0.5.13](https://github.com/lmccart/p5.js-release/releases).

Do you plan to fix these issues? thanks

**Comment by joshlory** [comment]
@lmccart is there a patch release scheduled soon?  I'm still seeing `grunt-mocha` as a dependency on the [0.6.1 release](https://www.npmjs.com/package/p5/v/0.6.1?activeTab=dependencies).

Thank you for the awesome library!
