### ISSUE TITLE
saveTable() wrong csv output

### ISSUE THREAD

**Issue by thomasvanhemert** [processing/p5.js#2842]
Hey all, 
I hope this is the right place to post this but I figured you might be of help here. I'm working on a p5 javascript project where I load a csv file with loadTable() in the preload() function. And I am saving it again later in my setup() with the saveTable() function when a button is pressed. Now comes my problem, the output csv is not in the right format. The function saveTable() exports the following: 

> sessionId,timeStamp,selectedItems100000,3-5-2018_10:24,EPC123412341234123412340001 

But i need it to output it as seperate rows instead of all the rows placed besides each other. Like this:

> sessionId,timeStamp,selectedItems
> 100000,3-5-2018_10:24,EPC123412341234123412340001 

This is the part of the code that prepares and exports the csv file: 

> var newRow = sessionLog.addRow(); 
> newRow.setNum('sessionId', sessionId); 
> newRow.setString('timeStamp', timeStamp); 
> newRow.setString('selectedItems', selectedItems); 
> saveTable(sessionLog, 'sessionLog.csv', 'csv');

Coud any of you help me with this?

#### Nature of issue?

- [x] Found a bug (i have a question)
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [x] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version:  p5.js v0.5.4 October 01, 2016
- Web browser and version:  Chrome version 66.0.3359.139
- Operating System:  Windows 10 Version	10.0.15063 Build 15063
- Steps to reproduce this: See the top of the post.

**Comment by Spongman** [comment]
you might need to open the file in an editor that is sensitive to different types of line endings (notepad.exe isn't).

**Comment by TanviKumar** [comment]
Hey @thomasvanhemert , could you post a copy of the intial file you load? It works fine when I create a csv file that has ``sessionId,timeStamp,selectedItems`` as the header and try your code with some values.

**Comment by lmccart** [comment]
@thomasvanhemert we haven't been able to reproduce this one without the file, so I'm going to close this for organizational purposes. please feel free to reopen if you can update with more info. thanks!
