### ISSUE TITLE
arc() parameter request

### ISSUE THREAD

**Issue by PeacefulOtter** [processing/p5.js#2843]
#### Nature of issue?
- [ ] Found a bug
- [ ] Existing feature enhancement
- [x] New feature request

Hey everyone, I'm a new Javascript developer (and also french so sorry for my bad english) but I already use p5.js since it is very easy to use. However, I found strange that the `arc()` function doesn't have a parameter to modify the width of the arc. So, that's it, can you add width parameter to the `arc()` function ?

**Comment by mislavmilicevic** [comment]
I'm not sure whether you're mixing width another term or something else but the current arc constructor is as follows:
``arc(x,y,w,h,start,stop,[mode])``
where 'w' is the width of the arc

**Comment by Spongman** [comment]
maybe you're looking for `strokeWeight()` ?

**Comment by PeacefulOtter** [comment]
Yes, i was talking about width but I wasn't talking about the width of the whole circle, I just wanted to change the border's width of it. `strokeWeight()` is the solution I searched so I can also use `stroke()` to change the color of the border.
Thank you very much :)
