### ISSUE TITLE
httpGet documentation test fails to fail

### ISSUE THREAD

**Issue by Spongman** [processing/p5.js#2844]
v0.6.1

if you run the test-reference.html file in the browser and set 'pause on caught exceptions', you'll break during the `httpGet` test in `p5.prototype.httpDo`: `res.text is not a function`.

there's two issues here:
- the httpGet function doesn't handle `jsonp` correctly
- the test runner doesn't notice this error

**Comment by kjhollen** [comment]
fixed in #2855
