### ISSUE TITLE
Clarify text() documentation for default position and alignment

### ISSUE THREAD

**Issue by nippotam** [processing/p5.js#2854]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request
- [X] Documentation

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [X] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Proposed imporvement
Is it possible to add a little example in https://p5js.org/reference/#/p5/text in order to understand where text() write the string. In other words where is the x,y starting points for text().

**Comment by lad475** [comment]
I tried to look into the documentation to see what you mean, but the docs seem to pretty clearly outline how the x and y params work to decide where on screen the text goes.  Could you please clarify a bit?  Thanks!

**Comment by nippotam** [comment]
Yes 
The text() writes in the upper zone of the y axis whereas the rect() draw in the bottom direction in y axis. 

That is not clear in the doc.

**Comment by nippotam** [comment]
You are perfectly right. It has to be clarify in the default mode. May be we should add a point () in red at the x, y in each example (especially for textAlign).

**Comment by kjhollen** [comment]
Great. Let's update the documentation to include that the baseline alignment is the default. For anyone looking for a good first issue, [here's how to update the documentation](https://github.com/processing/p5.js/blob/master/developer_docs/inline_documentation.md)

**Comment by lmccart** [comment]
closed with #3024
