### ISSUE TITLE
p5.sound import issue

### ISSUE THREAD

**Issue by qdhoward** [processing/p5.js#2856]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ x] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x ] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 
- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

Hi. I include import "p5/lib/addons/p5.sound" in sketch.js (in React) and I get a compile error Line 21: 'loadSound' is not defined no-undef.
Line 21 is: let song = loadSound("/src/test.ogg");
Is there anything I did wrong?
Thank you

**Comment by lmccart** [comment]
perhaps this wrapper could help?
https://github.com/NeroCor/react-p5-wrapper

**Comment by qdhoward** [comment]
This wrapper only includes the p5.js. it doesn't support p5.sound. BTW, p5 is great. It will be greater if it's compatible with some front-end framework like react,

**Comment by lmccart** [comment]
the second article mentions something about being able to integrate p5.sound. for further p5.sound issues you can post directly to that repo: https://github.com/processing/p5.js-sound. thanks!

**Comment by NOPROD** [comment]
import { Component, OnInit } from '@angular/core';
import * as p5 from 'p5';
import 'p5/lib/addons/p5.sound';
import { Observable, observable, of } from 'rxjs';
import {map,filter, bufferWhen} from 'rxjs/operators'
@component({
selector: 'theme-first',
templateUrl: './first.component.html',
styleUrls: ['./first.component.scss']
})
export class FirstComponent implements OnInit {
constructor() { }
private p5sketch: p5;
private p5Sound: p5.p5InstanceExtensions;

ngOnInit() {
this.createCanvas();
}

private createCanvas() {
this.p5sketch = new p5(this.sketch);
}

private sketch(p: p5) {

/** Preload all assets/pre-config */
p.preload = () => {

/** >>>>>>>Payload here : playSong<<<<<<<<< */
var song = new p5.SoundFile('./../../../../assets/music/theme/first/InClosing-DaysPast.mp3', playSong);

function playSong(){
song.play();
}

}

/** Setup load all  */
p.setup = () => {
  p.createCanvas(500, 500);
  p.background(0);
}

}

ngOnDestroy() {
this.p5sketch.remove();
}

}
`

Just do like this with payload, i think is a clean method and work like a charm

https://github.com/NOPROD/p5.js-Angular-7 if you want a repo with a ready clean p5js project under angular 7
