### ISSUE TITLE
Removing opentype.js comments

### ISSUE THREAD

**Issue by limzykenneth** [processing/p5.js#2857]
I'm currently working on refining the documentation rendering on the website and I want to parse YUIDoc documentation from the packaged p5.js file directly on the website repo. However I believe comments of opentype.js is preventing me from doing so, as they also have comment block that starts with `/**` but it doesn't follow YUIDoc completely. In any case I don't want YUIDoc to parse opentype.js comments anyway.

Is there a way to require opentype.js in the source without including all of its comments as well when we build the whole p5.js package? That way we can remove a lot of extra comments that isn't related to p5.js also. Note I still do want the comments in p5.js itself.

**Comment by lmccart** [comment]
opentype.js does offer a minified version but I don't think there's any way to get this from npm on command. I guess we would need to minify this file or all of the node_modules dependencies maybe, using the uglify task, prior to building the library.

**Comment by Spongman** [comment]
Doesn't the p5.min.js version already exclude all these comments?

**Comment by Spongman** [comment]
how about this? https://github.com/Spongman/p5.js/commit/7e602b95e8a90a6cf7a6ee8ea0787c27e39cdbba

**Comment by limzykenneth** [comment]
Pretty much exactly what I'm looking for haha. If you think said package is reliable enough for us to use we can try it out to make sure it builds without introducing any bug.

**Comment by Spongman** [comment]
yeah, i think it's fine. it does need that fix to work around the options bug, though.

**Comment by lmccart** [comment]
@limzykenneth has this been resolved with #209?

**Comment by limzykenneth** [comment]
@lmccart It's been awhile, I assume it is solved or not relevant anymore. Closing.
