### ISSUE TITLE
<video> .play().time(nn) not working in Chrome 66.0.3359.139 on Macos 10.13.4

### ISSUE THREAD

**Issue by Pumpapa** [processing/p5.js#2859]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other (specify if possible)
Video in Chrome
#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: v0.6.0
- Web browser and version: Chrome 66.0.3359.139 on Macos 10.13.4 
- Operating System: Macos 10.13.4
- Steps to reproduce this:
In Chrome pressing +60 doesn't work, whereas in FF it does. In Chrome this restarts at 0.
Am I missing something?

I've been debugging for hours, and I have the impression Chrome's P5-video behaviour is erratic but by now I'm unsure.
```
function setup() {
	var x=windowWidth, y=windowHeight

	createCanvas(x,y);
	
	var th = createVideo('TH.mp4');
	th.size(300,AUTO).position(400, 50);

	createButton('play').position(100, 25).mousePressed(() => th.play());
	createButton('pause').position(200, 25).mousePressed(() => th.pause());
	createButton('+60').position(300, 25).mousePressed(() => th.play().time(200));
}

function draw() {
}
```

**Comment by spiray** [comment]
@Pumpapa First of all you should add a title. Secondly, Please include what issue is? What errors are you getting?

**Comment by limzykenneth** [comment]
I'm not able to replicate, in both Firefox and Chrome the behaviours are both the same, with a sufficiently long enough video it jumps to that point then continues playing, if the video is shorter than specified time, it just skips to the end and stops which is intended. 

Can you describe in more details what are the behaviour you are experiencing and what is the expected behaviour? Thanks!

**Comment by lmccart** [comment]
we're not able to reproduce this but please feel free to reopen if you can provide a code sample that demonstrates the issue. thanks!
