### ISSUE TITLE
documentation help wanted!

### ISSUE THREAD

**Issue by lmccart** [processing/p5.js#2865]
Hi  👋👋👋

We are using this issue to focus on documentation! Documentation is essential for new learners and experienced programmers alike. It helps make our community inclusive by extending a friendly hand to those that are less familiar with p5.js. It also helps us find the bugs and issues with the code itself, because we test and try things out as we document.

[There are several ways to contribute, you can read more about them on this page.](https://github.com/processing/p5.js/blob/main/contributor_docs/contributing_documentation.md)

If you are adding some documentation, please comment below. And don't forget to add yourself to the [contributors list](https://github.com/processing/p5.js#contributors)!

Welcome! We're so glad you're here!
❤️ the p5.js community

**Comment by m90** [comment]
For anyone who wants to work on adding missing examples and doesn't know where to start, this seems to be where there are still examples missing right now:

```
src/io/files.js:1329: method p5.save missing example
src/webgl/material.js:14: method p5.loadShader missing example
src/webgl/material.js:125: method p5.shader missing example
src/webgl/p5.Geometry.js:52: method p5.Geometry.computeFaces missing example
src/webgl/p5.Geometry.js:94: method p5.Geometry.computeNormals missing example
src/webgl/p5.Geometry.js:133: method p5.Geometry.averageNormals missing example
src/webgl/p5.Geometry.js:154: method p5.Geometry.averagePoleNormals missing example
src/webgl/p5.Geometry.js:247: method p5.Geometry.normalize missing example
src/webgl/p5.Shader.js:270: method p5.Shader.setUniform missing example
```

**Comment by faithwyu** [comment]
I would love to help out porting the tutorials from processing (https://processing.org/tutorials/) to p5!

**Comment by lmccart** [comment]
@faithwyu that would be great!

**Comment by raulgrell** [comment]
I'm going through the processing.org examples - some of the stuff that is missing seems to address the language itself as opposed to the library. For example, processing.org talks about "Integers and Floats" and "Datatype Conversions". Should I make Javascript equivalent entries?

**Comment by lmccart** [comment]
@raulgrell good question. not yet. we're not set up with the right website/reference infrastructure yet to be able to display those correctly.

**Comment by cecilebertin** [comment]
Hi, I'd like to work on porting the examples from the processing example page to the p5.js example page.

**Comment by lmccart** [comment]
👋@cecilebertin welcome! all the instructions for porting examples should be in the issue notes above. but let us know if you have any questions or encounter problems and we'll do our best to get back to you as soon as we can

**Comment by cecilebertin** [comment]
@lmccart I will start with porting the Data: Integers and Floats example.

**Comment by cecilebertin** [comment]
@lmccart Should I call this example Data: Numbers instead? Since there is only the Number datatype for numbers in JavaScript.

**Comment by cecilebertin** [comment]
Hi @lmccart, I made a pull request for the Numbers example.

**Comment by raulgrell** [comment]
@lmccart - I was trying to ask the same question as @cecilebertin, but I seem to have had a momentary lapse of eloquence =P

Unfortunately, that also means I'm not sure I understood your reply. Did you mean you don't yet have a way to show something like console output?

**Comment by cecilebertin** [comment]
So sorry @raulgrell !! I didn't see you wanted to work on this. I only checked the issues in the processing/p5.js-website repository to check if someone was working on this example.

**Comment by raulgrell** [comment]
@lmccart @cecilebertin No worries, I could have been clearer! There are still more examples to do =)

I'll send a PR for Strings, and possibly something for Data Types as well that deals with type coercion and whatnot

**Comment by lmccart** [comment]
thanks everyone! 🙏 🙌 🎉

**Comment by raulgrell** [comment]
Oh dear, I completely forgot about this! That weekend I participated in a Game Jam where we actually used p5 to make a little neuroscience experiment disguised as a game and I never got round to finishing the examples... check it out: https://github.com/raulgrell/NeuroJam

Unfortunately, I've got a big presentation for uni on Monday and I won't be able to dedicate any time to this right now...

**Comment by lmccart** [comment]
thanks @raulgrell no worries. we'd welcome the additions anytime, no rush. thanks for sharing the game jab examples, they're great!

**Comment by justinsunho** [comment]
Hi @lmccart, is https://github.com/processing/p5.js/issues/1954 an up to date list of examples we could take on? Or is there an active list of tutorials that could be worked on? Don't want to be re-doing anyone else's work/ work that's already been done.

**Comment by Spongman** [comment]
```
src\io\files.js:1402: method p5.save missing example
src\webgl\material.js:151: method p5.shader missing example
src\webgl\p5.Camera.js:187: method p5.createCamera missing example
src\webgl\p5.Camera.js:298: method p5.Camera.perspective missing example
src\webgl\p5.Camera.js:380: method p5.Camera.ortho missing example
src\webgl\p5.Camera.js:671: method p5.Camera.camera missing example
src\webgl\p5.Geometry.js:50: method p5.Geometry.computeFaces missing example
src\webgl\p5.Geometry.js:92: method p5.Geometry.computeNormals missing example
src\webgl\p5.Geometry.js:131: method p5.Geometry.averageNormals missing example
src\webgl\p5.Geometry.js:152: method p5.Geometry.averagePoleNormals missing example
src\webgl\p5.Geometry.js:245: method p5.Geometry.normalize missing example
src\webgl\p5.Shader.js:274: method p5.Shader.setUniform missing example
```

**Comment by lmccart** [comment]
closing this, all key info has been moved over here: https://github.com/processing/p5.js/blob/master/developer_docs/contributing_documentation.md
we can continue to open specific issues for documentation that needs work, and maybe reopen this issue for the next mozsprint

**Comment by lmccart** [comment]
actually, reopening this because I think it's a nice issue to have around for people looking for ways to help out

**Comment by GaurangTandon** [comment]
@lmccart Could you please update this link: https://github.com/processing/p5.js-website/wiki/Adding-examples ? It is mentioned on the [Contributing docs](https://github.com/processing/p5.js/blob/master/developer_docs/contributing_documentation.md) under section "Make examples".

Also, is there a running list of missing ports as was mentioned in this [comment](https://github.com/processing/p5.js/issues/2865#issuecomment-431519678)?

**Comment by lmccart** [comment]
@GaurangTandon I've updated the text and linked to the page where we have all this info in more complete and correct form. Thanks!

**Comment by GaurangTandon** [comment]
@lmccart Hey thanks! Could you please also link to the list of examples that are yet to be ported?

**Comment by lmccart** [comment]
@GaurangTandon The list of examples needed and info about how to generate them is in the first paragraph on the adding inline documentation page

**Comment by grege2** [comment]
@lmccart  Hi, I'd like to regain access to edit the "JavaScript basics" Wiki. I'm helping someone else learn JavaScript and I re-read it in the last few days, and there are some small improvements and corrections I'd like to make. Thanks.

**Comment by lmccart** [comment]
hi @grege2 sorry for the delay, you should have received an invitation that will give you edit access to the repos and the wiki. thanks!

**Comment by grege2** [comment]
Hi @lmccart thanks, no problem re delay.  Really enjoying my involvement with p5.js, I'm coding it with it several hours a day the last few months, on a large project of 4000 lines I'm collaborating with someone else on, not actively looking for bugs or doco/examples errors/typos although if only there were 48 hours in the day I could. Congrats on the 0.9.0 release, nothing broke for me in the upgrade from 0.8.0, not that that's critical in beta, but starting to look really tight product. Thanks for the edit access. Ciao GE

**Comment by mbtamuli** [comment]
Hey people, is there any specific section of the documentation that needs some work? I'd like to take a dig if there's any.

**Comment by stalgiag** [comment]
Hi @mbtamuli thanks for the interest! You should definitely start off by checking out the [contributing documentation readme](https://github.com/processing/p5.js/blob/master/developer_docs/contributing_documentation.md). Also any [issue tagged 'documentation'](https://github.com/processing/p5.js/issues?q=is%3Aissue+is%3Aopen+label%3Aarea%3Adocumentation). [This might be a good issue](https://github.com/processing/p5.js/issues/4011) to start with. Good luck!

**Comment by zoyron** [comment]
Hello people, I would like to work on the documentation. If there is any specific task for a beginner then please guide me, I am more than happy to contribute.
Thank you.

**Comment by fenilgandhi** [comment]
Hey guys, i am working on updating description and adding examples for [p5.Geometry.js](https://github.com/processing/p5.js/blob/master/src/webgl/p5.Geometry.js).

**Comment by fenilgandhi** [comment]
Hey guys, while updating documentation, i am facing 2 issues, if somebody can check and verify if these are legitimate bugs or it just might be a newbie mistake.
 
1. The alternative text for the examples in the reference documentation is not getting read by a screen reader even where it is available. You can check for the following methods [arc](https://p5js.org/reference/#/p5/arc), [quad](https://p5js.org/reference/#/p5/quad).
2. In the local development environment, The reference docs generated by `npm run grunt yui:dev` are not properly aligned. The description text overflows, the example is displayed above the example code. For example, here's a screenshot of `plane` method.
![Screenshot from 2020-03-05 20-58-34](https://user-images.githubusercontent.com/9128903/75996740-52c00a00-5f24-11ea-9241-2f8efc595461.png)

**Comment by limzykenneth** [comment]
@fenilgandhi Is this the development preview of the documentation that is hosted in this repo (as opposed to the one on the website repo)? If so it could very possibly be that some of the code that is stored in this repo for the documentation preview has gone out of date and wasn't able to render the reference correctly.

**Comment by fenilgandhi** [comment]
Yes @limzykenneth, it is the development preview of documentation in this repo. If that may be the issue, I would like to fix it, can you give me some pointers on where to start looking from ?

**Comment by limzykenneth** [comment]
The code for rendering documentation in this repo is [here](https://github.com/processing/p5.js/tree/master/docs), while that is generated (awhile ago) from the original templates and scripts, now moved over to the website repo, [here](https://github.com/processing/p5.js-website/tree/master/src/yuidoc-p5-theme-src/scripts). 

Honestly the codebase is quite convoluted so there's no pressure for you to fix it now, I do plan on doing some clean up next time I have some free time on my hand, but if you can that'll be a great help!

**Comment by fenilgandhi** [comment]
Thank you soo much @limzykenneth. I think i would learn a lot fixing it so i would really like to have a go at it. Will get back to on it soon.

**Comment by ykabusalah** [comment]
Has anyone completed this? Could I try tackling this issue?

**Comment by lmccart** [comment]
@ykabusalah you are welcome to contribute documentation, just open a pull request and we can review.

**Comment by fenilgandhi** [comment]
Oh hey, @ykabusalah, Yes i have solved the issue with CSS overflow for canvas over here. [https://github.com/processing/p5.js-website/pull/580](https://github.com/processing/p5.js-website/pull/580). But the docs in development mode can definitely benefit from some CSS updates. So feel free to work on it and open a PR.

**Comment by ykabusalah** [comment]
Alright awesome. I'll do that. Can you assign me? @fenilgandhi

**Comment by lmccart** [comment]
@ykabusalah we're not assigning people via the interface for this one because more than one person can work on it at once, and we don't want to discourage them. but you consider yourself "assigned" :)

**Comment by ykabusalah** [comment]
I have some thoughts and would like your feedback if possible:

The asterisk-design-element on the https://p5js.org/get-started/ page causes an accessibility issue; the language controls are inaccessible to color blind users due to the colors of the asterix and the color of the languages. Either move the asterix below the language or change colors of the language bar on that page
* The asterisk-design-element on the home page collides with the text and makes it hard to read, so move it to the bottom right corner
* On the download-page the asterisk-design-element, on small screen sizes, the asterix collides with the nav, making it unusable; scale down the asterisk on that page to make this happen
* On the reference page, same as above

**Comment by Rizz0S** [comment]
Could someone provide some guidance of what needs help with documentation rn? I really want to start contributing to the community, but most of the open issues right now are either already being worked on or out of my experience range. Thanks!

**Comment by montoyamoraga** [comment]
thank you @Rizz0S, i think the most straightforward help to contribute,
instead of adding more documentation, would be to help us mantain the one we already have,
so i suggest going through the reference and examples, making sure that they don't have bugs,
and that they are written in a clear way :)

**Comment by samporapeli** [comment]
Hello :wave: 

I noticed a tiny incoherence in [this reference page](https://p5js.org/reference/#/p5/dist) and decided to fix it (in a way that makes sense to me). I created [a pull request draft #4817](https://github.com/processing/p5.js/pull/4817) and would appreciate if I could get some feedback on it :)

Best,
Sampo

**Comment by fal-works** [comment]
Just linking docs-related issues which i recently opened:
#4988
#4991

**Comment by shreyan-invalid** [comment]
Hey if this issue is open I would like to contribute.

**Comment by lmccart** [comment]
hi @shreyan-invalid yes, you are welcome to work on this!

**Comment by Nolski** [comment]
Hi!
I'm working with [W. Michelle Harris](https://www.rit.edu/directory/wmhics-w-michelle-harris) to help improve the experience of contributing learning materials for p5.js as a part of our [Open Programs Office](https://www.rit.edu/research/open). We have a team of designers, technical writers, and developers to help us do this as well. Some things we were hoping to potentially help out with and contribute are:

 - Developing an initial education plan and identifying gaps in what is provided by the p5.js website. It looks like there's work towards this already in this thread, we would hope to perhaps split it out into its own series of tickets or document depending on how the maintainers felt.
 - Having out UX designers take a look at the learning section of the website and discuss/propose some changes
 - Michelle has developed lots of course work around p5.js and we would like to contribute this to the existing library of learning resources.

@mcturner1995 What do you think of this? Happy to have a chat to see how we can best use our resources to make p5.js better without hindering anyone else's work.

**Comment by lmccart** [comment]
Hi @Nolski, this is wonderful! It would be very helpful to the project. I'd be happy to chat with you about this. I'm in an extreme zoom overload state these days, could we possibly discuss via email? You can write to hello@p5js.org and it will come through to me.

**Comment by AndrewAung11** [comment]
I saw a space in the [reference page](https://p5js.org/reference/) under the [foundation](https://p5js.org/reference/#group-Foundation). But under other header I didn't see any space. Is it a bug or something else? Just letting you know.
![image](https://user-images.githubusercontent.com/64914752/108517900-5e077380-72f6-11eb-8dd8-01c6979dc610.png)

**Comment by lmccart** [comment]
@AndrewAung11 yes this could be considered a bug. If you are interested in working on it, you are welcome to!

**Comment by LouisJustinTALLOT** [comment]
hi, I was considering starting a documentation in French. would anyone be interested ?

**Comment by limzykenneth** [comment]
Hi @LouisJustinTALLOT, I don't think there is a plan to add additional translations at this point, maybe it can be pitched as a GSoC or Fellowship project but that's not a decision I'm involved with. That's for official translations though, for unofficial translations we definitely welcome anyone to do it and publish on their own URL, you can then share that URL with us so we can list it as an unofficial translation.

On a not totally unrelated note, I'm working on some research into this area, if you are able to would you be interested in trying out some experiments I'll be working on? Basically I'm looking into the documentation translation process and possibly creating a software or workflow for translations that fits into the overall documentation process.

**Comment by two-ticks** [comment]
Hi, I'm new here. I want to contribute. Can I work on examples to write mathematical expressions using KaTeX in p5.js sketches? 
![katex_example](https://user-images.githubusercontent.com/68433541/110251620-5529c980-7fa7-11eb-9bd7-20925e74a788.jpg)

**Comment by lmccart** [comment]
hi @two-ticks thanks for your interest! I would suggest looking at https://processing.org/examples/ and seeing if you can port any over to http://p5js.org/examples. I think there are several missing from the math categories right now.

**Comment by two-ticks** [comment]
I would like to work on porting 'Graphing 2D Equations' example from https://processing.org/examples/ to http://p5js.org/examples

**Comment by two-ticks** [comment]
Are these meant to be `links` ? 

![image](https://user-images.githubusercontent.com/68433541/110879059-5558fa80-8302-11eb-9984-6cdf50f562d2.png)

**Comment by myloooon** [comment]
Hi all! I'd love to contribute whatever would be most helpful right now. :)

**Comment by ghgsnaidu** [comment]
Hello !! I would like to contribute.
 I have seen  an example of bubble sort under maths section
 ,I would like to add other sorting algorithms as examples can I do that??

**Comment by thinklikeadesigner** [comment]
I would like to help!

**Comment by cystark** [comment]
Hello would love to contribute~

**Comment by prakhar3062** [comment]
I would love to contribute but need little more explanation where you wanted update

**Comment by Manan17** [comment]
I would love to contribute but need little more explanation where you wanted update

**Comment by Qianqianye** [comment]
Thanks @thinklikeadesigner @prakhar3062 @Manan17. You can take a look issues with label '[help wanted](https://github.com/processing/p5.js/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22)', or read the [contributing documentation](https://github.com/processing/p5.js/blob/main/contributor_docs/contributing_documentation.md) for different ways of contributing.

**Comment by Qianqianye** [comment]
Thank you all for all your input on this issue. We are currently working on a project to reorganize and update the p5.js documentations. So I will close this issue for now to avoid confusion. We will revisit the issues labeled '[Documentation](https://github.com/processing/p5.js/labels/Documentation)' or open a new issue about documentation helps we need later.
