### ISSUE TITLE
`loadShader` fails to compile seemingly ok shader files

### ISSUE THREAD

**Issue by m90** [processing/p5.js#2878]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.6.1
- Web browser and version: Firefox & Chrome
- Operating System: Ubuntu 16.04

So I wanted to add an example for `loadShader` which currently does not have one, but could not get it to work as it's not entirely clear how to use it.

What I tried to run was the following sketch:

```js
function setup() {
  createCanvas(100, 100, WEBGL);
  // create and initialize the shader
  var demo = loadShader('assets/shader.vert', 'assets/shader.frag');
  shader(demo);
  noStroke();
}

function draw() {
  quad(-1, -1, 1, -1, 1, 1, -1, 1);
}
```

The shader files are in the correct directory and I can see the XHR succeeding. Their contents look like this (actually taken [from this tutorial](https://www.html5rocks.com/en/tutorials/webgl/shaders/)):

```
// shader.frag
void main() {
    gl_FragColor = vec4(1.0, 0.0, 1.0, 1.0);
}
```
```
// shader.vert
void main() {
    gl_Position = projectionMatrix *
                  modelViewMatrix *
                  vec4(position,1.0);
}
```
This will fail with the following error message(s):

```
p5.min.js:12 Yikes! An error occurred compiling the vertex shader:ERROR: 0:1: 'undefined' : syntax error

```

Interestingly, this error will be logged twice.

I also tried using the shader definitions from the `createShader` example but ran into the same issue.

Am I doing something wrong or is there an issue in p5.js?

**Comment by Spongman** [comment]
Try putting the loadShader call in `preload`.

**Comment by m90** [comment]
The `setup`/ `preload` distinction never fails to be smarter than I am :jack_o_lantern: 

It's working fine now, see #2881 

Thanks.
