### ISSUE TITLE
`rect()` documentation description inaccurate

### ISSUE THREAD

**Issue by limzykenneth** [processing/p5.js#2879]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [x] Documentation

In the [`rect()` documentation](https://p5js.org/reference/#/p5/rect) the order of corner radius parameters are described in the wrong order (top-right, top-left, lower-right and lower-left corners instead of top-left, top-right, lower-right and lower-left corners)

**Comment by cecilebertin** [comment]
Can I work on this?

**Comment by lmccart** [comment]
@cecilebertin yes please :)
