### ISSUE TITLE
Return of a few curve functions in docs

### ISSUE THREAD

**Issue by limzykenneth** [processing/p5.js#2892]
[`curveDetail`](https://p5js.org/reference/#/p5/curveDetail) and [`curveTightness`](https://p5js.org/reference/#/p5/curveTightness) in the docs have seemingly truncated return description (the beginning part probably missing something)

**Comment by lmccart** [comment]
@L05 want to take a look at this?
I believe @limzykenneth is referring to the text under "Parameters"
you can use the processing reference as a guide for what text would make more sense for these https://processing.org/reference/curveTightness_.html
