### ISSUE TITLE
In keyPressed() some ascii values of key are incorrect.

### ISSUE THREAD

**Issue by devonsoft** [processing/p5.js#2893]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [x] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.6.1
- Web browser and version: Google Chrome (64-bit) | 67.0.3396.40 Firefox (64-bit) 59.0.2

- Operating System: Windows 8 (Macbook Pro 2013)
- Steps to reproduce this:

In keyPressed() some ascii values of key are incorrect. These values are correct in processing.js in the same environment.

function keyPressed()
{
print(key);
}

',' comes in as '¼'
'.' comes in as '¾'
'/' comes in as '¿'
' comes in as 'Þ'
'[' comes in as 'Û'
']' comes in as 'Ý'
'\' comes in as 'Ü'
'~' comes in as 'À'
'-' and SHIFT+'=' are also wrong

The other ascii characters seem ok but I may have missed some.

**Comment by m90** [comment]
Do you specifically need to use `keyPressed` or could you also use `keyTyped`? Due to browsers doing very strange things when handling keyboard events, the output is very hard to handle.

If it's an option for you, using [`keyTyped`](https://p5js.org/reference/#/p5/keyTyped) will probably give you what you expect for most use cases.

**Comment by kjhollen** [comment]
Fixed in #2898. thanks @m90!
