### ISSUE TITLE
I'm a little teapot -- loadModel() example .obj appears as mere speck or not at all

### ISSUE THREAD

**Issue by PAEDevelopment** [processing/p5.js#2896]
#### Nature of issue?

- [ ] Found a bug
- [x ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ x] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [ x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: p5.js v0.6.1 
- Web browser and version: Version 66.0.3359.139 (Official Build) (64-bit)

- Operating System:MacOSX 10.13.3
- Steps to reproduce this:
var teapot;
function preload(){
  rock = loadModel("teapot.obj") 
}
function setup() {
  createCanvas(720, 480, WEBGL);
  }
function draw() {
  background(200);
  //rotateX(frameCount * 0.01);
  //rotateY(frameCount * 0.01);
  translate(0,0,300);
  model(teapot);
  }

**Comment by Spongman** [comment]
> `translate(0,0,300);

I think the reason it appears so small is because you're moving it so far away.

**Comment by PAEDevelopment** [comment]
No, I should have explained -- that translation just makes it visible (like 20px across).  Otherwise it is as small as it appears in the documentation. 
![screen shot 2018-05-13 at 2 50 27 pm](https://user-images.githubusercontent.com/4973341/39971256-9377abaa-56bd-11e8-9a55-44261c27ba39.png)

**Comment by PAEDevelopment** [comment]
Neglected to try 'normalize'. D'oh.

**Comment by kjhollen** [comment]
Good catch. I think the default example should maybe include normalize, then? or at least, use a model that will show something more legible in the example. :) feel free to open another issue to track this.

**Comment by Spongman** [comment]
`loadModel` takes an optional `normalize` boolean parameter. maybe the default for this should be `true` ?

**Comment by PAEDevelopment** [comment]
I opened a new issue addressing only the documentation: https://github.com/processing/p5.js/issues/2904
But I agree the default for normalize should be true
