### ISSUE TITLE
`quad()` documentation missing description

### ISSUE THREAD

**Issue by yutinglu413** [processing/p5.js#2899]
#### Nature of issue?

- [ ] Found a bug
- [x] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Documentation

#### Details about the bug: 

in [quad() documentation](https://p5js.org/reference/#/p5/quad), z1,z2,z3,z4 do not has the specific explaination. 

#### Feature enhancement details:

Add z1, z2, z3, z4 explainations: the z-coordinate of the point.

**Comment by lad475** [comment]
I can take care of this by tomorrow! :)

**Comment by lmccart** [comment]
closed with #2924
