### ISSUE TITLE
cursor() description clarification

### ISSUE THREAD

**Issue by limzykenneth** [processing/p5.js#2900]
In the description for the [cursor()](https://p5js.org/reference/#/p5/cursor) function I find that the description, in particular "It is not possible to load an image as the cursor if you are exporting your program for the Web" not very clear, basically what does it mean by exporting for the web? I have never used an image as the cursor so I may be missing something here but I suggest a clarification on this.

**Comment by lad475** [comment]
I agree; the documentation doesn't seem to be very clear as per what the cursor function does if it doesn't work on the web (local only perhaps?) and it would be nice for the documentation to give a better idea of at least why it wouldn't work when put on the web, and if there are alternatives.

**Comment by lmccart** [comment]
the cursor function does work on web, this is leftover documentation from the processing(java) reference that got accidentally transferred. i will remove. thanks!
