### ISSUE TITLE
Default framerate in frameRate() reference

### ISSUE THREAD

**Issue by limzykenneth** [processing/p5.js#2901]
In the [`frameRate()`](https://p5js.org/reference/#/p5/frameRate) reference page, it is mentioned that "The default rate is 60 frames per second" which although for most displays are true, it is actually tied to the refresh rate of the display. The reference should be edited to explain that.

**Comment by lmccart** [comment]
@L05?

**Comment by doxanthropos** [comment]
Would you mind if I take that? @L05 seems to not be interested?

**Comment by lmccart** [comment]
@doxanthropos please go ahead, thanks!
