### ISSUE TITLE
Suggested improvements to loadModel() reference example

### ISSUE THREAD

**Issue by PAEDevelopment** [processing/p5.js#2904]
#### Nature of issue?

- [ ] Found a bug
- [x ] Existing feature enhancement
- [x ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [ x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

-p5.js version: p5.js v0.6.1

-Web browser and version: Version 66.0.3359.139 (Official Build) (64-bit)

-Operating System:MacOSX 10.13.3
- Steps to reproduce this:
On the reference page https://p5js.org/reference/#/p5/loadModel the .obj file loaded in appears as a disappointing speck in the canvas.  (see attachment1)

#### Feature enhancement details:  
Setting the normalize parameter to true fixes this (see attachment2), but still requires some scaling (translate the object back on the Z-axis. Best would be to reformat page to increase size of canvas, then the translate() isn't necessary (attachment3).
![attachment1](https://user-images.githubusercontent.com/4973341/40030555-d75195f4-57b0-11e8-8e21-ce137d1e713b.png)
![attachment2](https://user-images.githubusercontent.com/4973341/40030556-d763a06e-57b0-11e8-8386-6e96674dbc93.png)
![attachment3](https://user-images.githubusercontent.com/4973341/40030557-d77c596a-57b0-11e8-9484-4a945c0661ea.png)

**Comment by TanviKumar** [comment]
This solution works well, but perhaps it is a lot of tweaking required for an example. I've found a very simple .obj file that takes a lot lesser time to load and doesn't require any tweaking for the examples sake. Would this be a better solution to the current issue or would it be wiser to show the user different steps they might have to take to make their models on an appropriate scale.

**Comment by Spongman** [comment]
I think it's useful to show the use of the `normalize` flag, and the model scaling (perhaps this can be better achieved here in example 2 by the use of the `scale` function). Not everyone's model will be exactly the right size to fit in their canvas, and I think it's useful to teach them how to normalize & scale in this example.

**Comment by kjhollen** [comment]
Hey! My proposal is to have two examples for this, one that @TanviKumar added in #2968 as the first (and simplest) example, then a second example describing the cleanup that @Spongman suggests. I'll merge Tanvi's PR shortly (assuming tests look ok) and then we can another PR to add the slightly more complex teapot example.

**Comment by TanviKumar** [comment]
This issue can now be closed since the example has been changed!
