### ISSUE TITLE
Problem with running functions

### ISSUE THREAD

**Issue by hockpond** [processing/p5.js#2905]
I  just started to learn p5js and when I write functions like "keyPressed()" or "mousePressed()", my code doesn't execute these functions for no reason and the console shows me the following message: 

http://prntscr.com/jhy5ic
http://prntscr.com/jhy5mq
http://prntscr.com/jhy5pe

Can someone help me, please?

**Comment by Spongman** [comment]
not sure about the `require` error, but your ellipse is getting erased immediately by the `background` call.

**Comment by lmccart** [comment]
@Spongman is correct. the desktop editor has not been supported for a while, so it's possible the require error is coming from somewhere in there.
