### ISSUE TITLE
Can't execute a for loop

### ISSUE THREAD

**Issue by hockpond** [processing/p5.js#2909]
Hey everyone. Could someone tell me why my program isn't running, please? (ignore the ".")

function setup() {
....createCanvas(600, 400);
}

function draw() {
....for (var x = 0; x <= width; x += 50) {
........ellipse(x, 200, 10, 10);
....}
}

Errors: 
   Uncaught ReferenceError: loopProtect is not defined (sketch: line 6)

**Comment by Spongman** [comment]
your sketch is fine. `loopProtect` sounds like something to do with a web ide.

maybe try the p5 web editor, or codepen. like this: https://codepen.io/Spongman/pen/zjJPqw?editors=0010

**Comment by kjhollen** [comment]
hi @hockpond, thanks for this report. this is an open issue with the p5 web editor that just came up recently: https://github.com/processing/p5.js-web-editor/issues/633

I'm going to close this issue as it is already tracked in the editor repository.

**Comment by kjhollen** [comment]
yes! thanks @catarak :)
