### ISSUE TITLE
"Local server" page and Sublime Text Browsersync Utility

### ISSUE THREAD

**Issue by rich-gg** [processing/p5.js#2912]
#### Nature of issue?

- [ ] Found a bug
- [X ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ Manual] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [ X] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

 Hi there

Yesterday I had to setup a whole new environment for my p5.js development so I had to use the [Local Server](https://github.com/processing/p5.js/wiki/Local-server) page.

It is kind of nice but not being on Mac OS I found it a bit tricky.
Since the [Get Started](https://p5js.org/get-started/) page recommends that I use Sublime Text I looked for the simplest way to get a Editor/Local Server/Browser set working.
I found [Sublime Text Browsersync Utility](https://packagecontrol.io/packages/Browser%20Sync) and the way to install it thanks to a very simple [YouTube video](https://www.youtube.com/watch?v=3Pptm3EMaP4)

trying it for a day now, it seems to work really fine.

What do you thing of it ?
Would it be cool to have that method added to the "Local Server" manual page ?

cheers

**Comment by lmccart** [comment]
Sure, please feel free to add it to the page.
