### ISSUE TITLE
loadJSON ( . . ., . . ., 'jsonp') error

### ISSUE THREAD

**Issue by WolcWocker** [processing/p5.js#2921]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [ ] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: /*! p5.js v0.6.1 April 27, 2018 */
- Web browser and version: Google Chrome Version 66.0.3359.181 (Official Build) (64-bit)
- Operating System: Windows 10

- Steps to reproduce this:

//Code
let input;
let searchUrl = 'https://en.wikipedia.org/w/api.php?action=opensearch&format=json&search=';

function setup() {
  input = document.getElementById("input");
  goWiki(input);
}

function goWiki(input){
  let Url = searchUrl + input.value;
  loadJSON(Url, gotData, 'jsonp');
}

function gotData(data){
  console.log(data);
}

//Console errors 

TypeError: b.text is not a function
at p5.min.js:10

It works if I use loadJSON (url, gotData) , it's just that wikipedia API doesn't have the 'Access-Control-Allow-Origin' header

**Comment by limzykenneth** [comment]
You need to add `&origin=*` to your URL query as per wikimedia's API [manual](https://www.mediawiki.org/wiki/Manual:CORS#Description), that will allow anonymous request from any origin. `jsonp` will often require the server/API endpoint to support it (because it sends data back in a different way) so it's not a direct substitute solution for API endpoint without CORS header.

**Comment by Spongman** [comment]
i believe this was fixed in #2855 but that hasn't been released yet.
