### ISSUE TITLE
'orbitControl()' documentation missing description

### ISSUE THREAD

**Issue by yutinglu413** [processing/p5.js#2923]
#### Nature of issue?

- [ ] Found a bug
- [x] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Documentation

#### Details about the bug: 
there is no explanation on [orbitControl() documentation](https://p5js.org/reference/#/p5/orbitControl) page

**Comment by AidanNelson** [comment]
I can take a look at this.  I'll submit a PR in a bit.
