### ISSUE TITLE
book reference and porting tutorial from processing

### ISSUE THREAD

**Issue by faithwyu** [processing/p5.js#2925]
#### Nature of issue?

- [ ] Found a bug
- [x] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [x] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Feature enhancement details:
porting tutorials from processing to the p5.learn page

#### New feature details:
What are some good ideas to port the tutorials `typography` and `strings and drawing text` when it comes to references in the book _Processing_? Should I just use the same content and then label it as the chapter from _Processing_ but substitute it with examples in p5.js syntax?

**Comment by lmccart** [comment]
For simplicity, I think those book references can be removed entirely. For example:
"The keyPressed() event function introduced on page 97 can be used to record each letter as it is typed.'"

can become

"The keyPressed() event function can be used to record each letter as it is typed."

It's also fine to remove any section of the tutorials which refers to functionality not supported in p5.js, or not relevant.
