### ISSUE TITLE
texture() slow when no id

### ISSUE THREAD

**Issue by micuat** [processing/p5.js#2926]
I found that `texture(...)` is slow when the img/canvas tag to be bound does not have an id (example code at the bottom)

#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.6.0
- Web browser and version: Google Chrome 66.0.3359.181
- Operating System: windows 10
- Steps to reproduce this:

Compare the framerate with / without line 12:
https://alpha.editor.p5js.org/micuat/sketches/ry-6oxxkQ

**Comment by micuat** [comment]
And the issue becomes significant with larger texture size

**Comment by micuat** [comment]
I noticed that it has nothing to do with id; but the width/height parameter slows down the texture function:
https://github.com/processing/p5.js/blob/5f6b4ab7e1c1a680186e52a9a1ac3f63450e8406/src/core/p5.Element.js#L148

**Comment by stalgiag** [comment]
Closing as I wasn't able to detect framerate changes in 0.7.2 with the included example. If you can still repro then feel free to post something here and I will repoen
