### ISSUE TITLE
Odd behavior when perspective() near plane set to 0

### ISSUE THREAD

**Issue by AidanNelson** [processing/p5.js#2936]
#### Nature of issue?

- [ ] Found a bug
- [X] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [X] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version:  0.6.1
- Web browser and version:  Chrome 66.0.3359.181
- Operating System:  MacOSX
- Steps to reproduce this:

```
function setup() {
  createCanvas(400, 400, WEBGL);
  let fov = 60 / 180 * PI;
  perspective(fov, width / height, 0, 500);
}
function draw() {
  background(200, 100, 200);
  orbitControl();

  normalMaterial();
  rotateX(0.3);
  rotateY(frameCount * 0.01);
  box(100);
}
```

#### Feature enhancement details:

In perspective(), when the near clipping plane is set to 0, certain faces become transparent as their angle to the camera changes.  Any value above zero (even 0.001) stops this behavior.  Also, if the near clipping plane is set below 0, nothing is shown.

I am unclear whether this is desired behavior or not.  I would expect that when the near clipping plane is at or behind the camera (0 or below), everything within the frustum in front of the camera would be visible.  

Would it be possible to add a friendly warning OR a check for zero/below-zero values on the input?  I am happy to take a look at this if either solution sounds ok.

**Comment by mlarghydracept** [comment]
The near clipping plane should never be set to [0 in a perspective matrix as per the mozilla reference.](https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/WebGL_model_view_projection) It would be great to get a friendly error then automatic reset to 0.001 in my opinion.

**Comment by Spongman** [comment]
also see this khronos article on depth buffer precision and a more thorough treatment of the implications that i alluded to above: https://www.khronos.org/opengl/wiki/Depth_Buffer_Precision

**Comment by kjhollen** [comment]
closing because this is taken care of in webg-gsoc-2018!
