### ISSUE TITLE
webgl rect() draws diagonal and internal vertices when stroke is on

### ISSUE THREAD

**Issue by kjhollen** [processing/p5.js#2943]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Details about the bug: 

- p5.js version: master, works ok in 0.6.1
- Web browser and version: Chrome but probably all
- Operating System: Mac OS but probably all
- Steps to reproduce this:

 
rect() is including too many vertices in its stroke vertices in webgl mode. see picture below: we should really only see the outline of the rect. this was working okay in 0.6.1 but seems to be new in master.

<img width="477" alt="screen shot 2018-05-23 at 3 22 15 pm" src="https://user-images.githubusercontent.com/78966/40454301-1b0959ce-5e9d-11e8-817e-c5b1d917a8f6.png">

```
function setup() {
  createCanvas(windowWidth, windowHeight, WEBGL);
}

function draw() {
  background(220);
  push();
  rectMode(CENTER)
  fill(255);
  rect(0, 0, 100, 100);
  fill(255, 0, 0);
  rect(20, 20, 100, 100);
  pop();
}
```

**Comment by kjhollen** [comment]
hey @AidanNelson, this one might make a good first issue to fix, if you're looking for one? the code is relatively contained and you can look at some of the other primitive shape function as examples.

**Comment by Spongman** [comment]
actually, i'm pretty sure this is _not_ a bug. the behavior you see above was present in v0.6.0, v0.5.16 and long before that (see #2510 for an old example).

the behavior you're seeing in v0.6.1 is actually the bug here. introduced in #2515 and fixed in #2657.

**Comment by kjhollen** [comment]
rect() should produce a rectangle with a stroke around its perimeter only in the default state. the current behavior, while expected for someone familiar with the inner-workings of the web gl code, won't meet an end user's expectations.

**Comment by Spongman** [comment]
ok, i just wanted to make to point out that this wasn't an issue that has turned up _since_ v0.6.1, and that v0.6.1 is the outlier in the history of the behavior of this function. the reason that `rect` has historically drawn the diagonal line is that it uses the same face triangulation mechanism as the other 3d primitives.

**Comment by AidanNelson** [comment]
Hmmm... I'm not seeing that behavior in either 0.6.1 or the current master branch build.  This is what I see with the code snippet above on the master branch build: 

![screen shot 2018-05-23 at 7 42 57 pm](https://user-images.githubusercontent.com/6486359/40456874-8531556c-5ec1-11e8-8ee8-e48a86196fa1.png)

**Comment by Spongman** [comment]
ah, you're right! sorry, i was getting my versions mixed up. looks like #2515 made it in before to 0.6.0 release - i should have paid closer attention to the logs ;-)

i _do_ see the diagonals in current master (75a949b), though. maybe you're old/cached version?

**Comment by AidanNelson** [comment]
Yup, that was it.  Now I'm seeing this.
