### ISSUE TITLE
renderer can't use its own push/pop methods

### ISSUE THREAD

**Issue by kjhollen** [processing/p5.js#2946]
currently, the p5 instance stacks the styles for renderer and passes an object to p5.Renderer.prototype.pop when p5.prototype.pop is called. this means that the renderer cannot internally use push/pop to maintain its own state; it must have the p5 instance call pop for it.

there are some cases in webgl mode where it would be helpful to let the renderer push/pop it's own state to restore a user texture or shader (for example in image() in #2211). the suggestion here is to let the renderer keep its own style stack instead, and to remove the argument to p5.Renderer.prototype.pop.

I'm planning to implement this soon, let me know if you have any questions. thanks!

**Comment by lmccart** [comment]
@kjhollen are you still planning to work on this one? if not, will you remove your assignment so others can claim it? or if you are, feel free to keep your name assigned to this, just wanted to check in.

**Comment by stalgiag** [comment]
Hi @kjhollen I don't wanna bug you with another ping on this one but I am happy to take this up if you are still busy.

**Comment by kjhollen** [comment]
Oh yes, please take this one! I'm sorry I've been out of touch. I can
review this when it's ready!

**Comment by stalgiag** [comment]
closing as per discussion in #3621. will reopen if it makes sense.
