### ISSUE TITLE
Error in definition files in TypeScript

### ISSUE THREAD

**Issue by andry-tino** [processing/p5.js#2951]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other (Typescript definitions)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x ] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: latest
- Web browser and version: Chrome latest
- Operating System: Windows 10
- Steps to reproduce this:

Just try to reference the global definition file: `/// <reference path="../node_modules/p5/lib/p5.global-mode.d.ts" />`

And compile:

```
node .\node_modules\typescript\lib\tsc.js --project .\tsconfig.json
node_modules/p5/lib/p5.d.ts(10312,5): error TS2416: Property 'amp' in type 'Noise' is not assignable to the same property in base type 'Oscillator'.
  Type '(volume: number | object, rampTime?: number, timeFromNow?: number) => void' is not assignable to type '(vol: number | object, rampTime?: number, timeFromNow?: number) => AudioParam'.
    Type 'void' is not assignable to type 'AudioParam'.
```

I have to say that working with this library is particularly painful given the lack of isolation.Having infinite issues using webpack and troubles using Typescript :(

**Comment by lmccart** [comment]
we have made the decision not to support typescript any longer due to the realities of maintenance. there's currently an open issue to move this out of the repository, though we haven't gotten there yet. so typescript files you find may be out of date / buggy. apologies!

**Comment by Spongman** [comment]
This is fixed in the p5 sound repo. We're just waiting for that to be merged and released.

**Comment by Trimad** [comment]
If p5.js has dropped typescript, does that mean it's not possible to use p5.js with Angular?

**Comment by kjhollen** [comment]
typescript will be moved to a new repository (see #2571 for progress / updates), which will be managed independent of the core library. some additional steps will probably be required to work with angular or other external libraries.
