### ISSUE TITLE
Frequently referenced wiki page has been archived

### ISSUE THREAD

**Issue by Kinrany** [processing/p5.js#2952]
#### Nature of issue?

Found a problem with documentation.

#### Most appropriate sub-area of p5.js?

Instantiation cases, documentation.

#### Details about the bug: 

Open this p5 wiki page: https://github.com/processing/p5.js/wiki/Instantiation-Cases

It's empty, presumably because [it was archived](https://github.com/processing/p5.js/wiki/Archived-Content#instantiation-cases), but there are still links around the internet referencing it.

Examples:
* ["I guess we don't actually have a page just about instance mode, do we need one? Right now we have instantiation cases and a section in p5.js overview."](https://github.com/processing/p5.js/issues/1327#issuecomment-202093644)
* ["In Instance Mode, how do I write events function? [...] I found the answer here: link"]( https://forum.processing.org/two/discussion/comment/39278/#Comment_39278)
* ["You may create a p5wrapper component and launch p5 in instance mode (link)"](https://discuss.reactjs.org/t/using-react-with-p5-js/5565/2)

More: https://www.google.com/search?q=p5+%22Instantiation+cases%22

#### Feature enhancement details:

It would be nice if the removed page had the reason it was removed and links to relevant non-archived docs that should be used instead.

**Comment by extrajordanary** [comment]
Also found a dead link to an archived FAQ page, inside of the error you get when trying to call color at the top of the sketch:

```
ReferenceError: color is not defined
    at https://replbox.repl.it/data/web_project/a0ffc276bd3e84fd0a01d30b5603d426/sketch.js:10:21
Script error.
Did you just try to use p5.js's color() function? If so, you may want to move it into your sketch's setup() function.

For more details, see: https://github.com/processing/p5.js/wiki/Frequently-Asked-Questions#why-cant-i-assign-variables-using-p5-functions-and-variables-before-setup
> p5.js says: color() was expecting Number for parameter #0 (zero-based index), received an empty variable instead. If not intentional, this is often a problem with scope: [https://p5js.org/examples/data-variable-scope.html] at https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.6.0/p5.js:49849:33. [http://p5js.org/reference/#p5/color]
```

Seems like the link is in the p5 error code itself, so just wanted to be sure that's also on the todo list to update and/or remove those links as well.

Cheers!

**Comment by lmccart** [comment]
thanks @extrajordanary this has been fixed and should be updated in the next release :)

**Comment by lmccart** [comment]
I think this page now covers all the questions linked from the first post:
https://github.com/processing/p5.js/wiki/Global-and-instance-mode/

for the rest, I think this remaining open issue should address what's still needed
https://github.com/processing/p5.js/issues/1327
