### ISSUE TITLE
Add additional parameter to orbitControl to enable/disable inverted vertical rotation

### ISSUE THREAD

**Issue by dekmm** [processing/p5.js#2962]
#### Nature of issue?

- [ ] Found a bug
- [x] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Feature enhancement details:
As mentioned in PR #2956 I was thinking of adding an additional parameter to orbitControl to enable/disable inverted vertical rotation. The linked PR currently changes the inverted rotation in orbitControl, that was supposedly incorrect, to normal rotation. Knowing some users actually prefer inverted vertical rotation, adding a flag to control this would be helpful.

**Comment by Spongman** [comment]
how about adding two parameters `scaleX` and `scaleY` with default value `1`? making either of these negative would change the sense of the rotation, and adjusting the magnitude would change the sensitivity.

**Comment by dekmm** [comment]
I like the approach. Would 1 be considered the maximum allowed sensitivity so it ranges from -1 to 1 or is it just an agreed upon starting point?

**Comment by kjhollen** [comment]
Thanks @dekmm! @AidanNelson is one of our Google Summer of Code students for p5.js and part of his project is improving the camera API and interactions for Web GL mode. Is it ok with you if I assign this issue to him?

**Comment by Spongman** [comment]
I don't see the need for a setting a maximum. If someone wants to make it more sensitive than normal, it should probably allow that.

**Comment by dekmm** [comment]
@kjhollen go ahead!

**Comment by Spongman** [comment]
1. you can use `_fromRadians` to convert from radians to angleMode, if necessary.
2. i'd recommend coming up with some sensible default scale factor that you think makes sense, and then just multiply that by any scale factors that are passed in.

**Comment by kjhollen** [comment]
closing because the fix for this has been merged into webgl-gsoc-2018!
