### ISSUE TITLE
Suggestion: pixelPerfect()

### ISSUE THREAD

**Issue by SaintPepsi** [processing/p5.js#2964]
#### Nature of issue?

- [x] Existing feature enhancement
- [x] New feature request

#### Most appropriate sub-area of p5.js?

- [x] Image
- [x] Typography

#### Which platform were you using when you encountered this?

- [x] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop

#### Details about the bug: 

- p5.js version: v0.6.0 January 19, 2018
- Web browser and version: Google Chrome | 66.0.3359.181
- Operating System: MacOSX 10.13.4
- Steps to reproduce this: 
```
imageMode(CENTER);
image(someImage, x, y);
```
under 66k +/- pixels: (how it should look)

<img width="34" alt="github-issue2-b" src="https://user-images.githubusercontent.com/16056759/40820746-a391c790-65a5-11e8-866d-31a1de81e79a.png">

above 66k +/- pixels: (how it should NOT look)
<img width="40" alt="github-issue2" src="https://user-images.githubusercontent.com/16056759/40820751-aa9f9f6c-65a5-11e8-8655-9178171fcd14.png">
I'm not sure why the total pixels is around 66k when this happens

#### New feature details:
some kind of `pixelPerfect()` mode which tells the image and text renderer to `floor()` the `imageMode(CENTER)` and `textAlign(CENTER)`
how I fixed it. (probably not the best way)
imageMode Center:
`45348 return { x: a - floor(c * 0.5), y: b - floor(d * 0.5), w: c, h: d };`

textAlign Center:
`50989 x += floor(maxWidth / 2);`
`51002 y += floor((maxHeight - totalHeight) / 2);`
`66632 x -= round(textWidth / 2);`
`66640 y += floor(textAscent / 2);`

Reason I use floor is for consistency when dealing with different image sizes.

Hopefully that was everything. If I need to clarify more or did something wrong please feel free to correct me as i'm still learning about github and libraries.

**Comment by Spongman** [comment]
Did you try `pixelDensity(1);` after your `createCanvas()` call?

**Comment by SaintPepsi** [comment]
@Spongman Yes!

**Comment by lmccart** [comment]
I think this function is beyond the scope of the p5.js api for now as we try to focus on webgl and mobile updates. I apologize that this is confusing, we are in the process of implementing a public roadmap and milestones to make this more clear. We will soon be calling for input for new features for the 1.0 release. We can revisit this idea then. For now, it could be a great starting point for an addon library. see the docs here for how to create an addon: https://github.com/processing/p5.js/wiki/Libraries#creating-a-new-library
