### ISSUE TITLE
Less rotation than expected with angleMode(DEGREES) in WEBGL mode

### ISSUE THREAD

**Issue by AidanNelson** [processing/p5.js#2965]
#### Nature of issue?

- [X] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [X] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version:  0.6.1
- Web browser and version:  Chrome 66.0.3359.181
- Operating System: Mac OSX 10.12.6
- Steps to reproduce this:

It seems that rotateX,Y,Z produce less rotation than expected when angleMode is set to DEGREES in WEBGL mode.  See the below sketch with 2D and 3D rotations.  2D mode exhibits expected behavior (degree and radian modes produce same rotation when scaled appropriately) whereas in WEBGL mode, the boxes rotate less in ```angleMode(DEGREES)```.  I briefly looked into this using the Chrome debugger, but didn't see anything super obvious.  I will keep looking!

```
function setup() {
  // createCanvas(400, 400);
	createCanvas(400, 400,WEBGL);
}

function draw() {
  background(200);
	
	let currentTime = millis();
	
// 	push();
// 	translate(width/2,height/4);
// 	angleMode(DEGREES);
// 	rotate((currentTime / 1000) * 360);
// 	fill(0,0,255);
// 	rectMode(CENTER);
// 	rect(0,0,100,50);
// 	pop();
	
// 	push();
// 	translate(width/2,height/4*3);
// 	angleMode(RADIANS);
// 	rotate((currentTime / 1000) * TWO_PI);
// 	fill(255,0,0);
// 	rectMode(CENTER);
// 	rect(0,0,50,100);
// 	pop();
	
	push();
	translate(0,-100,0);
	angleMode(DEGREES);
	rotateZ((currentTime / 1000) * 360);
	fill(0,0,255);
	box(100,50);
	pop();
	
	push();
	translate(0,50,0);
	angleMode(RADIANS);
	rotateZ((currentTime / 1000) * TWO_PI);
	fill(255,0,0);
	box(50,100);
	pop();
}
```

**Comment by AidanNelson** [comment]
Update: [this line](https://github.com/processing/p5.js/blob/master/src/webgl/p5.Matrix.js#L514) is converting an angle from degrees to radians which has already seen that conversion. So, seeing this conversion twice means the final rotation is less than expected:

``` var _a = this.p5 ? this.p5._toRadians(a) : a;```


I don't quite understand what that line is meant to do, however.  I assume it has something to do with checking whether the rotation is being performed on a p5.Matrix object directly, or whether it is being performed internally by the renderer on a model view matrix, but am having a little trouble understanding why that conversion is needed there in the first place.  Could anyone help me parse it out?

**Comment by Spongman** [comment]
yeah, you're right. that line shouldn't be there. as it says in the doc comment just above:
```javascript
@param  {Number} a The angle of rotation in radians
```
this function is always called with it's argument as radians, it shouldn't need to convert it again.

**Comment by dekmm** [comment]
```_toRadians``` only converts to radians if the angle mode is DEGREES. It has an internal check. Otherwise it just returns the argument.

**Comment by AidanNelson** [comment]
@dekmm -- yes, but in this case it seems the degree conversion is happening twice.  Once correctly, and the second time in error.  O_o

I could submit a PR to remove that line, but I can't quite parse out what purpose it served in the first place.  When would `this.p5` not evaluate as `true`?

**Comment by meiamsome** [comment]
@dekmm 
The conversion is already occurring inside [p5's rotate()](https://github.com/processing/p5.js/blob/master/src/core/transform.js#L195-L199) that calls the [render's rotate()](https://github.com/processing/p5.js/blob/master/src/webgl/p5.RendererGL.js#L734-L740), which then performs the Matrix operation.

@AidanNelson it would be null when the matrix is constructed on its own - `new p5.Matrix()`, so there's a check for it. This is standard across the subclasses (Example [here](https://github.com/processing/p5.js/blob/master/src/math/p5.Vector.js#L1063-L1067) for Vector), so the check should be kept.

If a user gets a `Matrix` from the [proposed](https://github.com/processing/p5.js/blob/master/src/webgl/p5.Matrix.js#L39-L41) (but as of yet unimplemented) `createMatrix` or through some webGL functions, I believe the user would expect the `Matrix` to respect the `angleMode` from the p5 instance. Therefore, I suggest actually changing the renderer's method, perhaps to the following, to account for the extra `_toRadians` in the pipeline:

```javascript
p5.RendererGL.prototype.rotate = function(rad, axis) {
  if (typeof axis === 'undefined') {
    return this.rotateZ(rad);
  }
  arguments[0] = this._pInst._fromRadians(rad);
  p5.Matrix.prototype.rotate.apply(this.uMVMatrix, arguments);
  return this;
};
```

I also note that [the initial declarations of the matrices](https://github.com/processing/p5.js/blob/master/src/webgl/p5.RendererGL.js#L81-L83) do not get passed the p5 instance, so behaviour with these things are possibly inconsistent - we should probably more consistently pass the p5 instance in to the matrices.

**Comment by AidanNelson** [comment]
@meiamsome ahh, ok.  That is what I was wondering.  So `createMatrix()` would store a reference to  the current p5 instance in `this.p5` and be able to convert angles according to that instance's angle mode.  

In that case, is there a strong reason not to drop the angleMode conversion from the [publicly accessible](https://github.com/processing/p5.js/blob/master/src/core/transform.js#L224-L229) `p5.prototype.rotate/X/Y/Z` functions and just allow that conversion to happen later (in the P2D renderer [rotate](https://github.com/processing/p5.js/blob/master/src/core/p5.Renderer2D.js#L1113-L1115) and the p5.Matrix [rotate](https://github.com/processing/p5.js/blob/master/src/webgl/p5.Matrix.js#L513)?  This would avoid making that conversion three times (degrees to radians in `p5.prototype.rotate/X/Y/Z`, radians to degrees in `p5.RendererGL.prototype.rotate`, and again back to radians in `p5.Matrix.prototype.rotate`) when angleMode is set to degrees in WebGL mode.

Maybe something along the lines of [this](https://github.com/AidanNelson/p5.js/commit/01ee66977b4fb7bf1c215b4411dc8beadcaa7a1e)?

**Comment by AidanNelson** [comment]
That makes sense.  I will submit a PR with your suggested change, and see if anyone else has suggestions on this!

**Comment by kjhollen** [comment]
fixed in webgl-gsoc-2018!
