### ISSUE TITLE
What should the sync option do?

### ISSUE THREAD

**Issue by meiamsome** [processing/p5.js#2970]
The `sync` parameter (Added in #493, initial proposal #490 by @kevinbarabash - tagged to get their input, hopefully) is not well documented (I cannot find any reference to it anywhere).

The sync tests assert that when the constructor is ran with the sync option then it expects to run the `setup` function synchronously. This behaviour is not compatible with the preload mechanism, as the existence of any preload calls will mean that `setup` is delayed to a point further down the line.

The current tests are basically this:
```javascript
var p5inst = new p5(function() {}, true);
p5.drawingContext // Check this is defined - works
```

Adding a preload function like this causes them to fail:

```javascript
var p5inst = new p5(function(s) {
  s.preload = function() {
    loadJSON('a');
  };
}, true);
p5.drawingContext // Check this is defined - doesn't work
```

So my question is what should the sync option do:
 - Is it intended to block the thread until setup completes? (I.e. not possible in JS)
 - Is it intended to only start p5 early? (Tests should be changed to only assert this behaviour - I have a working idea for this)
 - Is it intended to do something else?
 - Should it be removed entirely for implying behaviour that doesn't make sense (1) and exhibiting unpredictable behaviour (sometimes `setup` has run, sometimes it hasn't)

**Comment by lmccart** [comment]
This seems unclear and since we haven't heard from the initial author, I'd prefer to simplify and clarify by removing completely for now.
