### ISSUE TITLE
Typescript type file mistake for p5.Vector

### ISSUE THREAD

**Issue by mictadlo** [processing/p5.js#2977]
Hi
`bubble1 = new Bubble(p, new p5.Vector(200, 200, 40));` caused `[ts] Expected 0 arguments, but got 3.`

#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [x] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.6.1
- Web browser and version: chrome
- Operating System: Linux (Debian testing)
- Steps to reproduce this:

```
import 'p5';
import { Bubble } from "./Bubble";

let sketch = (p: p5) => {
  let bubble1;
  let bubble2;

  p.setup = function() {
    p.createCanvas(600, 400);
    bubble1 = new Bubble(p, new p5.Vector(200, 200, 40));
    bubble2 = new Bubble(p, new p5.Vector(400, 200, 20));
  }

  p.draw = function() {
    p.background(0);
    bubble1.move();
    bubble1.show();
    bubble2.move();
    bubble2.show();
  }

}

var sketchP = new p5(sketch);
```
Did I miss anything?

Thank you in advance.

Michal

**Comment by Spongman** [comment]
Try using the `createVector(x,y,[z])` function instead of the constructor.

**Comment by kjhollen** [comment]
thank you for reporting this @mictadlo. At this time, we are planning to move Typescript definitions into a new, separate repository because we can't continue to support them. This is being tracked in #2571—I'm tagging your post in the issue so that the new maintainer can track this in the new repo, but will close it here.

**Comment by dcsan** [comment]
I had this issue, solved it for me ty!
