### ISSUE TITLE
Add global modes to p5.d.ts

### ISSUE THREAD

**Issue by DatoIsko** [processing/p5.js#2980]
///<reference path="p5.global-mode.d.ts" />

I think you should add `///<reference path="p5.global-mode.d.ts" />` to top the p5.d.ts, because it's getting error.

**Comment by Zalastax** [comment]
We are migrating the TypeScript definitions to a [new repo](https://github.com/p5-types/p5.ts/), see #2571.
Soon you will be able to import the definitions via a `@types/p5.js` package.
This problem should already be fixed in the new repo 😃

**Comment by jtpio** [comment]
Really looking forward to `@types/p5.js` being available on npm :smiley: !
