### ISSUE TITLE
Please write documentation for node.js integration for p5.js sound

### ISSUE THREAD

**Issue by wktdev** [processing/p5.js#2982]
I would like to request that you update the documentation for how to incorporate p5.js sound into node.js. A few basic examples of how to play an oscillator and load/play sound file from different node packages would be helpful (create-react-app etc).

**Comment by wktdev** [comment]
Just a simple code example this this would be helpful:
## Using P5.js with Node.js
`
import 'p5/lib/addons/p5.dom';
import "p5/lib/addons/p5.sound";
import p5 from "p5";

let p5audioContext;

var p5temp = function(sketch) {

    sketch.preload = function() { // @preload is required by P5.js
        p5audioContext = sketch.getAudioContext();

 
    }
};


let osc =  new p5.Oscillator();
osc.start()
`

**Comment by KevinWorkman** [comment]
The nice thing about P5.js being open source is that you can add this documentation!

**Comment by lmccart** [comment]
you can post issues for p5.js-sound over here: https://github.com/processing/p5.js-sound
