### ISSUE TITLE
angleMode in multiple canvases

### ISSUE THREAD

**Issue by hhalkin** [processing/p5.js#2990]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 
- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

**Comment by hhalkin** [comment]
I have an associative array of canvases: canv["bigshow"], canv["it"] etc
I can say canv["it"].ellipse(50,50,20,20); or canv["it"].ellipseMode(CORNER); etc and it works as expected. When I write canv["it"].angleMode(DEGREES); nothing happens (and I am still in RADIANS).

**Comment by samdelong** [comment]
Can you please give more information about the bug?

**Comment by hhalkin** [comment]
Thank you for responding. I thought that I removed my posting! My bad!
Actually there is no bug: just a brain lapse on my part.
