### ISSUE TITLE
Uncaught Package not found p5.dom 

### ISSUE THREAD

**Issue by mictadlo** [processing/p5.js#3002]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.6.1
- Web browser and version: Chrome 62.0.3202.89
- Operating System:  Linux debian testing
- Steps to reproduce this:

`src/sketch.ts` 
```
import 'p5';
/// <reference path="../node_modules/p5/lib/addons" />
import 'p5.dom'
```
The `package.json` looks like this:
```
    {
    	"dependencies": {
    		"p5": "^0.6.1"
    	},
    	"devDependencies": {
    		"@types/node": "^10.3.1",
    		"fuse-box": "^3.2.2",
    		"tslib": "^1.9.2",
    		"typescript": "^2.9.1",
    	}
    }
```
What did I miss?

Thank you in advance.

**Comment by Zalastax** [comment]
I will have to investigate some more on how p5 should be used with TypeScript in regards to imports and such.
What I can tell you now is that We only have `p5/lib/p5.global-mode.d.ts` and `p5/lib/p5.d.ts`.
We will be able to better outline a good workflow once #2571 is completed.

@Spongman @toolness have you experimented with using p5 from TypeScript? Do you know someone who has? Especielly with regards to using the addons...

**Comment by mictadlo** [comment]
https://github.com/fuse-box/fuse-box/issues/1290#issuecomment-396134278

**Comment by Zalastax** [comment]
Please create a new issue in [https://github.com/p5-types/p5.ts](p5.ts) and we can probably figure this out.
The SNAPSHOT branch contains definitions for the latest p5.js.
I think you would want something like this: `import "p5/lib/p5.dom.min";`.

**Comment by mictadlo** [comment]
Done https://github.com/p5-types/p5.ts/issues/2
