### ISSUE TITLE
displayWidth / displayHeight report incorrect values on Android  

### ISSUE THREAD

**Issue by i3games** [processing/p5.js#3003]
#### Nature of issue?

- [X] Found a bug

#### Most appropriate sub-area of p5.js?

- [X] Core/Environment/Rendering

#### Which platform were you using when you encountered this?

- [X] Mobile/Tablet (touch devices)

#### Details about the bug: 

/*! p5.js v0.6.1 April 27, 2018 */
Chrome 67.0.3396.81 
Moto G, Android 7.0 

- Steps to reproduce this:

`index.html:`

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0>
    <style> body {padding: 0; margin: 0;} </style>
    <script src="lib/p5.min.js"></script>
    <script src="sketch.js"></script>
  </head>
  <body>
  </body>
</html>
```

`sketch.js`

```
function setup() {
  console.log(displayWidth, displayHeight);
  console.log(windowWidth, windowHeight);
}

function draw() {
}

```

first line: **360, 640**
second line: 980, 1525

The physical screen of the device is 1080 x 1920 pixels

**Comment by i3games** [comment]
The values reported on desktop (Mac) are correct.

**Comment by LadySith** [comment]
Hi @i3games 

When you test your device resolution using http://whatismyscreenresolution.net/ does it match your actual device resolution or does it give the same result as the p5.js sketch?

**Comment by i3games** [comment]
It is 360, 640 as in the sketch. I don't believe it is a bug in p5, as this is what comes from `window.screen.width` and `window.screen.height`. I think  the documentation could mention that you have to multiply with `displayDensity()` to get the actual device dimensions.

**Comment by LadySith** [comment]
Hi @i3games ,

Yes. According to the documentation displayWidth/displayHeight (p5) returns screen.width/screen.height (javascript) and windowWidth/windowHeight (p5) returns window.innerWidth/window.innerHeight (javascript). I don't think it would be necessary to modify the functions. As you mentioned, if you would like to return your actual device screen size you can multiply displayWidth by displayDensity() which returns window.devicePixelRatio() in javascript.

If this is alright for you, I will be closing the issue.

**Comment by i3games** [comment]
I'm ok closing the issue. I would still suggest to mention on [https://p5js.org/reference/#/p5/displayWidth](https://p5js.org/reference/#/p5/displayWidth) / [https://p5js.org/reference/#/p5/displayHeight](https://p5js.org/reference/#/p5/displayHeight) that these do not return the actual display resolutions.
