### ISSUE TITLE
viewport is not set in included index.html due to wrong syntax in meta tag

### ISSUE THREAD

**Issue by i3games** [processing/p5.js#3004]
#### Nature of issue?

- [X] Found a bug
#### Most appropriate sub-area of p5.js?

- [X] Other (specify if possible)
p5.js complete distribution `empty-example/index.html`

#### Which platform were you using when you encountered this?

- [X] Mobile/Tablet (touch devices)

#### Details about the bug: 

/*! p5.js v0.6.1 April 27, 2018 */
Chrome 67.0.3396.81
Moto G, Android 7.0

- Steps to reproduce this:

Current meta tag is:
    `<meta name="viewport" width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0>`

This does not set the viewport.

Correct meta tag syntax:
    `<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1 user-scalable=0">`

**Comment by lmccart** [comment]
@L05 care to investigate? the file to update is here https://github.com/processing/p5.js/blob/master/lib/empty-example/index.html
