### ISSUE TITLE
Obsolete & confusing error message when I use p5.js functions outside setup

### ISSUE THREAD

**Issue by DavidAPowers** [processing/p5.js#3006]
#### Nature of issue?

Improve documentation / confusing error message. 

When attempting to use p5.js functions and constants outside of the setup() function, *THE ERROR MESSAGE IS CONFUSING BECAUSE THE LINK FOR MORE INFO DOES NOT EXIST!*. I was hoping to use p5.js functions, especially the noise function, with a different javascript library, because some things P5.js offers are not readily available from other libraries.

#### Details about the bug: 

- p5.js version: 0.6.1
- Web browser and version: Chrome
- Operating System: Windows 10
- Steps to reproduce this:
1. Include p5.js
2. Try to call noise() or reference a constant like HALF_PI, an error message is received like this:

> Did you just try to use p5.js's QUARTER_PI constant? If so, you may want to move it into your sketch's setup() function.
> For more details, see: https://github.com/processing/p5.js/wiki/Frequently-Asked-Questions#why-cant-i-assign-variables-using-p5-functions-and-variables-before-setup

> Did you just try to use p5.js's noise() function? If so, you may want to move it into your sketch's setup() function.
> For more details, see: https://github.com/processing/p5.js/wiki/Frequently-Asked-Questions#why-cant-i-assign-variables-using-p5-functions-and-variables-before-setup

#### Feature enhancement details:
Point the error message to a valid link.
Update documentation somewhere to either explain how to use p5.js with other libraries, or why that's not possible and things can only be called within *setup()*.  Your introduction is great for beginners but it is missing information that a developer with a more technical background might want or need.

**Comment by lmccart** [comment]
thanks. this has been updated and will be in the next release of the library:
https://github.com/processing/p5.js/commit/2a724b950555bbe866f705e8b941af948ddfbc75#diff-52d252b9f74ec945f5b64c3f53be90f1

you can find the content from that link here:
https://github.com/processing/p5.js/wiki/p5.js-overview#why-cant-i-assign-variables-using-p5-functions-and-variables-before-setup
