### ISSUE TITLE
Some ttf font files fail to load

### ISSUE THREAD

**Issue by aferriss** [processing/p5.js#3012]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [x] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

When trying to load certain ttf font files I get the error "No valid cmap sub-tables found". It looks like this is originating in [opentype](https://github.com/nodebox/opentype.js/blob/0e16508f2aaebb5db15589b3d723bcde2466d618/src/tables/cmap.js#L104)  and may be possible related to https://github.com/processing/p5.js/issues/1901 . 

- p5.js version: 0.6.1
- Web browser and version: Chrome 65 and Firefox 59
- Operating System: Mac OS 10.13.3
- Steps to reproduce this:
http://alpha.editor.p5js.org/aferriss/sketches/rkfrMH2lm
There's a ttf file in there. I saw some people on the [opentype issues page](https://github.com/nodebox/opentype.js/issues/139) mentioning that it might have to do with how the font is extracted from a ttc font collection, but the font I'm using wasn't pulled from a ttc afaik.

**Comment by dhowe** [comment]
opentype.js does not support all cmap formats (though new ones have been added in more recent versions), so we might want to:

- verify p5.js is using the most recent version of opentype
- check and update tickets [here](https://github.com/nodebox/opentype.js/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+cmap) - sometimes a request is needed before a new format is added

**Comment by aferriss** [comment]
@dhowe I did just check to see if 0.8.0 of opentype would work and sadly it threw the same error. I don't know anything about how font files are stored. Do you know of a tool to check the cmap format of a specific font? I'd be happy to put in a request if I knew a little bit more about what I was asking for :D

**Comment by dhowe** [comment]
Its not a simple topic (and I am not an expert) but you can read the font file with a demo version of [SynalyzeIt](https://www.synalysis.net/downloads/), as described below. There is good list of resources on font formats [here](https://github.com/Jolg42/awesome-typography) and (specifically an intro to cmap) [here](https://pomax.github.io/1449777175633/opentype-let-s-learn-how-modern-fonts-actually-work). This [link](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6cmap.html) gives the specific info you need to grab the cmap table data from a file.

This [online tool](https://opentype.js.org/font-inspector.html) parses TTF fonts, but, b/c it is based on opentype, will fail in the case above as well. 

In the demo version of SynalyzeIT, open the file then specify the 'OpenType' grammar as in the image below:

![image](https://user-images.githubusercontent.com/737638/41274808-59b92d7a-6e51-11e8-87fa-e4e62b57a806.png)

**Comment by dhowe** [comment]
So there was a response from opentype [here]
(https://github.com/nodebox/opentype.js/issues/348).  

Seems like the best way to validate fonts that we are trying in p5.js might be via the [Microsoft Font Validator](https://github.com/HinTak/Font-Validator/).

There is also the Font-Bakery online tool [here](http://35.225.170.228), but (according to HinTak) this isn't as good as the above tool. Here is the [output for the problematic font](http://35.225.170.228/report/079442f2-5c9e-4a49-b94d-fdcbb4b8c165) above

**Comment by aferriss** [comment]
@dhowe Amazing, thanks for filing that over there and sharing all this! I believe that Big Caslon file was [supplied with High Sierra](https://support.apple.com/en-us/HT207962), which is why I was so surprised to find it not working but also might explain why it didn't have the MS platform id. 

One thing that seems odd to me is that the font works fine after converting it to an otf file, but again I don't know enough about these things to really make a guess as to why that would happen.

Do you have any ideas about what would be the best path forward? It seems like until there's a PR on opentype to support fonts without the MS id's this will be an issue. Is it worth trying to throw an error that suggests converting the font to another format?

**Comment by dhowe** [comment]
Can you clarify what you mean by 'works fine after converting it to an .otf file' ?
Also, I don't think it is the case that all OS X fonts fail, but maybe you can test a few to verify this?

**Comment by aferriss** [comment]
@dhowe I converted the font to .otf using the link I posted above and then the font loaded without error and could be drawn to screen. [Here's another test](http://alpha.editor.p5js.org/aferriss/sketches/S1XTXJAe7) with that otf font in it so you can see that it loads without issue. There's also a few more fonts in that sketch that I found that don't work. I didn't test all system fonts, only about the first 20 or so. Seems like it's about 25% that don't work.

**Comment by dhowe** [comment]
@aferriss  can you repost the link to the otf converter you used?

**Comment by aferriss** [comment]
@limzykenneth Are you sure you're getting Big Caslon and not the default serif font for you browser? I think textFont("BigCaslon") will only work if your system can find the font locally, which will be different for every user. On my machine textFont("BigCaslon") defaults to the Times typeface. [See here](http://alpha.editor.p5js.org/aferriss/sketches/S10NMV0x7)
![screen shot 2018-06-12 at 11 03 35 pm](https://user-images.githubusercontent.com/3698659/41333000-dea19e8a-6e94-11e8-9fe7-dd55264e55e2.png)

I do think catching the error and giving a helpful error would be good though! loadFont does already have a friendly error, but it seems like it was more targeted at errors where the font can't be found or the file path was typed incorrectly. It'd be nice if we could suggest converting the font to otf or at least some indication that the font file itself might be bad.

**Comment by aferriss** [comment]
@dhowe ah yea sorry I thought I had linked it before. I used this one: https://convertio.co/ttf-otf/

**Comment by limzykenneth** [comment]
Yes, I'm getting Big Caslon and yes I do have the font installed locally which was what I meant, locally installed fonts works fine just those that are loaded in via opentype.js may cause problem. 

P.S. You need a space between "Big" and "Caslon" (at least on Mac) to actually use the system Big Caslon, the names should be the same as in the Font Book.

**Comment by limzykenneth** [comment]
@dhowe Yeah, I'm not suggesting recommending using system font as a replacement for loading via opentype.js just that since there is no support right now, we can't do much on our end to fix this other than throw a helpful message.

**Comment by dhowe** [comment]
right, though I'm curious what transformation is happening in convertio (https://github.com/Convertio/convertio-cli)...

**Comment by dhowe** [comment]
Ok, so it looks like this issue has been resolved in [v0.9.0](https://github.com/nodebox/opentype.js/releases/tag/0.9.0) of opentype -- can someone integrate this into current p5.js and give it a test?

**Comment by limzykenneth** [comment]
I've just tried out the latest version with p5 and it works with all the ttf fonts @aferriss's example uses (well Farisi gave me tofu but that's expected), no errors thrown and whatever are displayed are the right fonts. I'll make a PR for the update in a bit.

**Comment by aferriss** [comment]
@limzykenneth amazing, thanks for investigating :D

**Comment by limzykenneth** [comment]
@aferriss Do try it out, make sure I didn't break anything. 😄

**Comment by aferriss** [comment]
@limzykenneth As far as I can tell it works perfectly. I just updated the package.json, are there any other changes that need to be made?

[Here's a test with a build I uploaded to the alpha editor](http://alpha.editor.p5js.org/aferriss/sketches/Bk_EU6A-Q)
