### ISSUE TITLE
day() no longer seems to work

### ISSUE THREAD

**Issue by imaginationfactory** [processing/p5.js#3015]
#### Nature of issue?

- [ x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ x] Mobile/Tablet (touch devices)
- [ x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

I'm using open processing.org to create a sketch using p5.js
In the sketch I am calling the day, month and year functions but day does not work.
It keeps saying day() is not a function.

**Comment by AidanNelson** [comment]
It seems to work on the web editor using the following code: 

```javascript 
function setup() {
  createCanvas(400, 400);
  console.log("Today is the ", day(), " of ", month());
}
```

Could you copy/paste your code here?

**Comment by lmccart** [comment]
we're not able to reproduce this but please feel free to reopen if you can provide a code sample that demonstrates the issue. thanks!
