### ISSUE TITLE
Mobile examples do not load on larger tablet screens

### ISSUE THREAD

**Issue by LadySith** [processing/p5.js#3019]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [x] Mobile/Tablet (touch devices)
- [ ] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 
Mobile examples not detected on larger tablets. Tested on a 7" Lenovo tablet

- p5.js version:  
- Web browser and version: Chrome 67
- Operating System: Android  
- Steps to reproduce this: Loading any of the examples listed under mobile on https://p5js.org/examples/ on a large tablet will not load the mobile version of the example

**Comment by lmccart** [comment]
This issue was moved to processing/p5.js-website#285
