### ISSUE TITLE
Default canvas size for various examples too large for screens

### ISSUE THREAD

**Issue by LadySith** [processing/p5.js#3020]
#### Nature of issue?

- [x] Found a bug
- [x] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [x] Mobile/Tablet (touch devices)
- [ ] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 
- Web browser and version: Chrome v66 
- Operating System: Android 5.0.1 
- Steps to reproduce this: When loading various examples, the width of the canvas is too large for mobile devices. In some cases such as the Simple Shapes example (https://p5js.org/examples/hello-p5-simple-shapes.html) information is left out. On other examples it can be an annoyance and on some it does not significantly change the experience of the user

**Comment by lmccart** [comment]
related https://github.com/processing/p5.js-website/issues/72

**Comment by lmccart** [comment]
This issue was moved to processing/p5.js-website#284
