### ISSUE TITLE
Adding MouseWheelDelta Property

### ISSUE THREAD

**Issue by AidanNelson** [processing/p5.js#3021]
#### Nature of issue?

- [ ] Found a bug
- [X] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [X] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### New feature details:

It has been helpful to save the current and previous mouse wheel state to control zoom level in the expanded orbitControl() function (#2497) and I wanted to open a separate issue for this added feature.  

Is there a reason not to add `mouseWheelDeltaY` and `pmouseWheelDeltaY` to the list of other saved mouse properties (and update it within [this function](https://github.com/processing/p5.js/blob/master/src/events/mouse.js#L823-L832))?

Does anyone have a suggestion for a shorter name?

**Comment by lmccart** [comment]
it's relatively easy to get the mouse delta from the event handler we have.. is there a reason a dedicated property is needed? i'm worried this could add more overhead than the payoff it would provide, but maybe there's a use case I'm missing? https://p5js.org/reference/#/p5/mouseWheel

**Comment by AidanNelson** [comment]
I'm trying to find a way to use mouseWheel delta within `orbitControl()` without blocking any user-defined `mouseWheel()` functions.  Is there a way to do this?

**Comment by kjhollen** [comment]
I think we could track the state for this internally only, rather than making it a user-facing feature. I think the idea is to be able to able to call `orbitControl()` in `draw` and to have access to the delta there, though the user doesn't need to know about it directly.

There are some more questions about the scope for orbitControl in p5 itself vs. in a library. Email coming shortly...

**Comment by lmccart** [comment]
was there a resolution here?

**Comment by AidanNelson** [comment]
Yes, the webgl-gsoc-2018 version of orbitControl() now tracks this state internally per Kate's suggestion above!
