### ISSUE TITLE
addCue() does not return a number/Id. It returns NaN

### ISSUE THREAD

**Issue by wktdev** [processing/p5.js#3030]
I don't know if I am misreading the documentation or if this is an error. addCue does not return a number or "ID".  It returns NaN. 

https://p5js.org/reference/#/p5.SoundFile/addCue

Documentation quote:

> Returns
> Number: id ID of this cue, useful for removeCue(id)

**Example**

```
  mySound.play();
  let id = mySound.addCue(3, console.log,"we are the world");
  console.log(id)  //  NaN
```
  
### How does removeCue(id) work?
Ultimatley I am trying to understand how to use the removeCue(id) function and the documentation does not give a clear cut example. 

Can someone please show me and clear this up ? The documentation is very poor.

**Comment by EsdrasXavier** [comment]
Hello, I tried do the same thing and I also get the same error, so I looked at the source code 'p5.sound.js' and searched where this method is called... On line 2098:
`  p5.SoundFile.prototype.addCue = function (time, callback, val) {
    var id = this._cueIDCounter++;
    var cue = new Cue(callback, time, id, val);
    this._cues.push(cue);
    // if (!this.elt.ontimeupdate) {
    //   this.elt.ontimeupdate = this._onTimeUpdate.bind(this);
    // }
    return id;
  };`

But this._cueIDCounter has not been set, maybe just in version: 2018-01-19 v0.3.7 ... So I added this code in line 815:
`this._cueIDCounter = 0;`

Look works fine now, maybe a bug or just forgot to declare.

**Comment by limzykenneth** [comment]
Hi, can this issue be moved to the [p5.sound repo](https://github.com/processing/p5.js-sound)? As the source code for sound are hosted separately there. Thanks!

**Comment by lmccart** [comment]
This issue was moved to processing/p5.js-sound#306
