### ISSUE TITLE
large strokeWeight on text renders spikes

### ISSUE THREAD

**Issue by aferriss** [processing/p5.js#3035]
When using stroked text with a strokeWeight greater than 2 or 3, you start to see odd peaks jutting out of the characters. This is especially prevalent on spiky capitals (A, M, V, W), but also happens on lowercase letters too. 
![screen shot 2018-06-20 at 4 02 31 pm](https://user-images.githubusercontent.com/3698659/41689566-0b339bd0-74a6-11e8-8d71-89ce3bf78a89.png)

![screen shot 2018-06-20 at 4 02 37 pm](https://user-images.githubusercontent.com/3698659/41689522-d60b0434-74a5-11e8-883a-165399df7fa8.png)

![screen shot 2018-06-20 at 4 02 10 pm](https://user-images.githubusercontent.com/3698659/41689574-140a33f4-74a6-11e8-869e-6f4d9a9fb743.png)

This issue only effects stroke with a strokeJoin of MITER— the other modes render fine. I think this is not really a p5 issue, but really just a canvas rendering bug. Additionally as you increase the strokeWeight at some point the peaks will pop to some even larger size. It seems to be different for every character. 

It can be fixed by setting the miterLimit of the drawingContext to some low number like 2 (the browser defaults it to 10). Here's [an example showing the gitches](http://alpha.editor.p5js.org/aferriss/sketches/HkQQtUdZQ), as well as the fix.

I'm happy to make a PR with this fix but wanted to see if anyone anticipated this breaking anything else. I briefly tried drawing a few other shapes but saw no difference in the rendered output regardless of what I set for the miter limit. I also did some searching and as far as I can tell miter limit never gets assigned anywhere in p5.
 
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [x] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.6.1
- Web browser and version: Chrome 65, Firefox 60, Safari 11.03
- Operating System: OSX 10.13.3
- Steps to reproduce this: Set large strokeweight: http://alpha.editor.p5js.org/aferriss/sketches/HkQQtUdZQ

**Comment by aferriss** [comment]
@MichaelPaulukonis Yes I think it is functioning as designed, I just don't think this is what you might expect from stroked text. If it doesn't break anything else or change the appearance of the way any other functions render, is there a downside to just defaulting miterLimit to 2?

The miterLimit property seems a bit arcane to me. Even if you're well versed in the canvas context's properties, it seems like this one might be easily overlooked. I'm just curious if there is an argument for leaving it at the default vs. changing it so that text stroke renders in a more expected way.

**Comment by limzykenneth** [comment]
I would say if this is a consistent behaviour across implementations in other drawing applications then it should probably be left as is, partly to manage expectation for people who were used to using those applications. Also limiting it to such a low number wouldn't that mean if someone wanted the sharp miters couldn't have them in p5 (star shapes for example)?

How about a new function in p5.js to set miter limit to cater to both case?

**Comment by aferriss** [comment]
@limzykenneth I think a function to set miter limit sounds like a good compromise. I'll see if I can whip something up. 

I finally was able to see a difference when changing the miter limit settings when drawing a star as you suggested.

**Comment by lmccart** [comment]
this function might be a bit specific for such a general purpose library -- one thing we want to avoid is newcomers looking at the reference page and seeing many functions whose use are confusing for them. maybe it would be better to have an examples on the examples page that demonstrates how to call some native canvas JS within a sketch to address this issue? (presuming that is possible with the way the text and stroke functions work in p5?)
