### ISSUE TITLE
Suggested improvement to keyIsDown documentation

### ISSUE THREAD

**Issue by chrisorban** [processing/p5.js#3036]
I had a suggestion for improving this page:

https://p5js.org/reference/#/p5/keyIsDown

The only examples are things like keyIsDown(UP_ARROW) and there aren't any examples of just putting a keyCode in the keyIsDown function. In the description it is clear that this should work, but I totally missed it the first 20 times I read it and I assumed that UP_ARROW, DOWN_ARROW, RIGHT_ARROW and LEFT_ARROW were the only things that keyIsDown worked with.

An improvement would be to add another if statement to the example program like this:
```js
if ( keyIsDown(65) ) {   // 65 is the keyCode for the "a" key
     x -= 5;
}
```
I think this would clear this up.

**Comment by bomoko** [comment]
Just for anyone browsing, I've grabbed this issue. Working on the example in the PR above.
