### ISSUE TITLE
PmouseX/Y Update with Touch Events

### ISSUE THREAD

**Issue by AidanNelson** [processing/p5.js#3037]
#### Nature of issue?

- [ ] Found a bug
- [X] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [X] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [X] Mobile/Tablet (touch devices)
- [ ] Desktop/Laptop
- [ ] Others (specify if possible)

#### Feature enhancement details:

This isn't an issue per se, but I wanted to bring up what was - for me - an unexpected behavior when using pmouseX/Y with touch events.  Basically, pmouseX/Y won't be updated between touch events because nothing is touching the screen.  So, at the beginning of every touch event, pmouseX/Y will represent the last mouse position from the previous touch event, rather than the previous frame's mouse position (which doesn't exist).  I am wondering whether it makes sense to either reset pmouseX/Y at the beginning of every touch event (to the current mouseX/Y) or add a note in the documentation explaining this behavior.  Resetting the pmouseX/Y at the beginning of each touch event seems most in-line with what I expect from that value (i.e. a mouse position very near the current one).  

Do either of these solutions make sense?

**Comment by lmccart** [comment]
Thanks @AidanNelson. I think the reseting behavior you've proposed makes sense to me.
