### ISSUE TITLE
Add runkit example for npm ?

### ISSUE THREAD

**Issue by dhowe** [processing/p5.js#3039]
The p5.js lib on npm has a 'Test with Runkit')  button (as all npm packages do) -- might be nice to add an example there?

Can do this either by adding a line to package.json as described [here](https://discuss.runkit.com/t/customizing-your-npm-packages-page-on-tonic/23)

![image](https://user-images.githubusercontent.com/737638/41830022-dc04426e-7870-11e8-9286-2094097ff803.png)

**Comment by kjhollen** [comment]
Ah cool—this would be great. Since we're already distributing with npm, might as well. Any takers for this issue?

**Comment by Zalastax** [comment]
Yes, RunKit is server-side so I don't think there's any  example we could add that would be useful in that context. I would like us to provide usage examples with build tools like webpack - which we for now only have in https://github.com/p5-types/p5.ts as far as I know.

Reopen the issue if you have an idea of an example that could be useful when run in RunKit.

**Comment by jasonsbarr** [comment]
You can create views in Runkit though, including HTML views. For example, they have views you can customize called Value Viewers that could probably be used to create an example application.

[Value Viewer documentation](https://runkit.com/docs/value-viewers)
