### ISSUE TITLE
the mouseClicked() function template

### ISSUE THREAD

**Issue by AngelDaMage** [processing/p5.js#3049]
so, when I was using openprocessing.org which uses p5.js, I used the mouseClicked reference, and when I filled in everything, and launched the code, it said "'Value' isn't defined"

**Comment by lmccart** [comment]
thanks @AngelDaMage can you post the code you were trying to run?

**Comment by kjhollen** [comment]
hi @AngelDaMage, I wasn't able to reproduce this—I copied in the first example from here https://p5js.org/reference/#/p5/mouseClicked and everything seemed okay. I'm noticing that in your error message, Value has a capital v but the code you're using as a reference has a lowercase v for value. Maybe there's a mismatch somewhere?

I'm going to close this issue, but if this doesn't work feel free to re-open to share your question on the processing forums at https://discourse.processing.org/ — thanks!
