### ISSUE TITLE
Hello P5 Video Volunteer Interest Form

### ISSUE THREAD

**Issue by emclaren** [processing/p5.js#3052]
Hello P5 Community!

We are looking for a handful of volunteers for our new hello p5 trailer.

Taking part is easy - you just have to video record yourself saying a few lines from a script using your phone camera/webcam. Videos will be edited together to let new users know what p5 is for!

If you use p5.js and would like to take part, please let us know by completing this form: [https://www.surveymonkey.com/r/YXFKYKN](https://www.surveymonkey.com/r/YXFKYKN). We will reach out shortly with more specific instructions.

Please note, depending on the volume of responses we receive we may not be able to include everyone who applies.

**Comment by lmccart** [comment]
thanks all! stay tuned for the new video..
