### ISSUE TITLE
Only 'default' cameras resize with window

### ISSUE THREAD

**Issue by AidanNelson** [processing/p5.js#3053]
#### Nature of issue?

- [ ] Found a bug
- [X] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [X] Mobile/Tablet (touch devices)
- [X] Desktop/Laptop
- [ ] Others (specify if possible)

#### Feature enhancement details:

Only a default camera will update its projection matrix in a webGL renderer's `resize` method.  This update happens according to a 'default' or 'custom' camera flag placed on the renderer.  I think default behavior should have every camera update its projection matrix (so that its aspect ratio isn't incorrect), and this could be accomplished by ...

* adding a projMatrixType flag with 'perspective' and 'ortho' as possible options
* resetting the camera's projection matrix according to that type ('perspective' or 'ortho') using current projection values (FOV, near/far) whether or not they are default and an updated aspect radio.

My only worry is whether this update would make it more difficult to intentionally use an 'incorrect' aspect ratio for ... some funhouse mirror type scenario? This would still be possible by manually setting the aspect ratio when calling 'perspective'

Thoughts?

correct aspect ratio with custom camera:
![correct aspect ratio](https://user-images.githubusercontent.com/6486359/42182842-a1af19b6-7e0d-11e8-929d-d0cce139f302.png)

incorrect aspect ratio after resize:
![incorrect aspect radio](https://user-images.githubusercontent.com/6486359/42182844-a3ade7c4-7e0d-11e8-9a0b-ce36cc5fb5e0.png)

**Comment by Spongman** [comment]
is this an issue that can occur in user code? i didn't think `Renderer` methods were exposed through the API.

does this happen if you call `resizeCanvas()`?

**Comment by AidanNelson** [comment]
This happens because `resizeCanvas()` calls the renderer's `_resize()` method.  

Also this is closed by #3080.
