### ISSUE TITLE
how to use global variable and functions on p5 instance mode  in  angular 4

### ISSUE THREAD

**Issue by Christian-health** [processing/p5.js#3059]
code like this.

![qq 20180705221317](https://user-images.githubusercontent.com/29979200/42328134-2177c910-80a0-11e8-84f0-a9267e1d392e.jpg)

thank you very much  !!

**Comment by lmccart** [comment]
hi @Christian-health the github issues here are a good place for bugs and issues with the p5.js library itself. for questions about writing your own code, tests, or following tutorials, the [forum](https://forum.processing.org/two/) is the best place to post. thanks!

**Comment by GeraGarza** [comment]
How was this problem solved? I can't find the forum discussion over this. Thank you!

**Comment by GeraGarza** [comment]
Solution for me:
// where you create the canvas, pass the value to a function you create to receive the value
  private createCanvas() {
    this.p5 = new p5(this.sketch);
    this.p5.passValue(this.value);
  }

// in sketch{
  p.passValue = (x) => {
      value = x;
 }
..
