### ISSUE TITLE
Bug: Missing typings for TypeScript

### ISSUE THREAD

**Issue by TeemuKoivisto** [processing/p5.js#3078]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.6.1
- Web browser and version: N/A
- Operating System: N/A
- Steps to reproduce this: Create a project with TypeScript and p5.js

As the title suggests using p5.js with TypeScript results in compiler throwing errors about missing typings for various constants: `Cannot find name 'COLOR_MODE'.`. From what I've gathered those constants are defined in `p5.global-mode.d.ts` yet as I recall I couldn't make it work even by importing global-typings instead of regular `p5.d.ts`.

I've avoided the issue by mocking p5 with an any-value which is a sorry hack but I didn't want to invest too much time in this. Similar issue was referenced in #2605

**Comment by TeemuKoivisto** [comment]
Well as a temporary solution I managed to fix the `p5.d.ts` definitions file locally by first inserting all the constants from the `p5.global-mode.d.ts` file to it: https://pastebin.com/DsxsS0uF

Then apparently p5.sound is out-of-date with its definitions so as described here https://github.com/processing/p5.js-sound/pull/248 I fixed the method in the line 10312 from:
```
    amp(volume: number|object, rampTime?: number, timeFromNow?: number): void
```
to:
```
    amp(volume: number|object, rampTime?: number, timeFromNow?: number): AudioParam
```

Yet it also seems that SoundFile's constructor is broken as I can't initialize a new SoundFile without first giving a path as a parameter to its constructor. So I turned the parameter into nullable:
`constructor(path?: string|any[], ...`

**Comment by kjhollen** [comment]
Hi @TeemuKoivisto, thanks for reporting this—the Typescript definitions have been moved to their own repository: https://github.com/p5-types/p5.ts and are now being maintained independently. I think the new repo has a few fixes that are more up to date than the last version distributed with p5, if you want to give that a try. I've copied the issue there so that the maintainers are aware. Thanks!
