### ISSUE TITLE
Unexpected behavior using transforms with createGraphics

### ISSUE THREAD

**Issue by aferriss** [processing/p5.js#3079]
In the normal draw loop, if you use a translate rotate or scale the transforms get reset at the end of the draw loop. For example if you do

````
translate(width/2, height/2);
ellipse(0,0,100);
````

The ellipse will always be drawn in the center of the screen.

If you do this in a createGraphics layer, the transforms will compound so your shape will end up flying off screen.

````
graphics.translate(width/2, height/2);
graphics.ellipse(0,0,100);
````

Is this intentional? I assumed that createGraphics would behave like drawing normally does where transforms are reset at the end of the loop. The behavior occurs in both WEBGL and the 2D renderer. A push and pop will make things normal in the createGraphics layer, but I found it confusing that it didn't reset on it's own. If it is intended, is this documented anywhere? 

I've included an example at the bottom to demonstrate.

#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.6.1
- Web browser and version: 67
- Operating System: OSX 10.13.4
- Steps to reproduce this:

https://alpha.editor.p5js.org/aferriss/sketches/S1g0H_GmX

**Comment by kjhollen** [comment]
Related to #2586 — the same work around should help!

I guess createGraphics could update a running list of known p5.Graphics objects created that need a reset at the end of every draw loop for a specific p5 instance (and then perform the reset). Is there any reason not to do this?

**Comment by Spongman** [comment]
> Is there any reason not to do this?

i think this should be optional (probably opt-in per-Graphics) since you may not be drawing into the Graphics at the same cadence as the main draw loop. alternative, just adding a method to the Graphics object to manually reset the state would probably suffice.

**Comment by aferriss** [comment]
I think that users would expect Graphics to work the same way as the default renderer (at least I do) and if you didn't want the matrices to reset maybe there should be some flag to prevent that from happening. 

Not that the p5 is always tracking with desktop processing, but the Graphics layers there do reset at the end of the draw loop (or at least at the graphics.beginDraw() or graphics.endDraw() calls).

**Comment by Spongman** [comment]
> but the Graphics layers there do reset at the end of the draw loop (or at least at the graphics.beginDraw() or graphics.endDraw() calls).


are you saying it's automatic in processing, or that it's reset by an API call made by the user? sorry, i didn't understand what you wrote there.

**Comment by aferriss** [comment]
@Spongman yes, it's automatic in processing. However processing also requires you to use beginDraw and endDraw, which don't exist in p5.

**Comment by Spongman** [comment]
ok, so i ran a test and it's **not** automatic in processing. the PGraphics matrix is _only_ reset when the `beginDraw()` method is called. it's _not_ reset at the beginning of the frame.

the following program rotates the graphics' matrix every frame, but only completes the beginDraw/endDraw pair when the mouse is clicked. you'll see that the rotation of the clock hand depends on the time number of frames between mouse clicks. if the matrix were reset every frame then the clock hand would always appear in the same location. this is precisely the behavior that p5.js exhibits today, and that i was referring to here: "you may not be drawing into the Graphics at the same cadence as the main draw loop"

````
PGraphics gr;
void setup () {
  size(500, 500, P2D);
  gr = createGraphics(100, 100, P3D);
  gr.beginDraw();
  gr.translate(50, 50);
}

void draw() {
  gr.rotateZ(.01);
  gr.clear();
  gr.rect(0, -5, 100, 10);
}

void mouseClicked() {
  gr.endDraw();
  
  image(gr, width/2, height/2);
  
  gr.beginDraw();
  gr.translate(50, 50);
}
````

**Comment by aferriss** [comment]
Right, so in p5 the equivalent to begin/endDraw would be push and pop or resetMatrix. 

If it's working as intended then it would be good to document this behavior somewhere— I think it's useful information and the default behavior might not be intuitive for beginners. In the processing docs, they recommend that all drawing be done between beginDraw and endDraw. I think we can similarly mention that matrices of Graphics don't get reset unless you explicitly do so.

**Comment by Spongman** [comment]
actually, there's currently no p5.js equivalent for processing's begin/endDraw. the p5.js push/pop are somewhat equivalent to processing's push/popMatrix, push/popStyle. i believe these were combined in p5.js because html5's canvas also has a combined matrix/style stack and separating them out is a bit of a pain.

we're on the same page: in #2586 i suggested "maybe we should add a `beginFrame()` method for both 2d & 3d graphics".

**Comment by stalgiag** [comment]
I am going to go ahead and work on this. I don't see any reason to depart from Processing on naming here so I am going to implement `p5.Graphics.prototype.beginDraw()` and `p5.Graphics.prototype.endDraw()`. I think those names clearly reference a "draw" loop for the Graphics object.
