### ISSUE TITLE
grunt build fails test (building from source)

### ISSUE THREAD

**Issue by Siiiimon** [processing/p5.js#3090]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other (specify if possible) (dev build)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: p5.js v0.6.1 July 20, 2018
- Web browser and version: Google Chrome | 67.0.3396.99 (Official Build) (64-bit)
- Operating System: macOS 10.13.5 17F77 x86_64
- Steps to reproduce this:

This is actually just an error that grunt throws when i try to build the project (i hope posting my issue here is okay for that sort of thing...). I should probably mention that I'm new to using automated tests/benchmarks/etc. on rather large scale projects.

Following the developer_docs and also using [the latest Travis CI job](https://travis-ci.org/processing/p5.js/jobs/403744923) as kind of a reference, `npm install` works fine but Grunt throws an error when it gets to a p5.Reverb docs test: `lib/addons/p5.sound.js p5.Reverb documentation`.

##### node/npm/nvm versions
```
projects/p5.js [master●] » node --version
v8.9.4
projects/p5.js [master●] » npm --version
5.6.0
projects/p5.js [master●] » nvm --version
0.33.11
```
##### the Error
```
682 passing (18s)
  1 failing

  1) lib/addons/p5.sound.js p5.Reverb documentation example #1 works:
     Error: Failed to set the 'buffer' property on 'ConvolverNode': Cannot set buffer to non-null after it has been already been set to a non-null buffer
      at p5.Reverb._buildImpulse (http://localhost:9001/lib/addons/p5.sound.js:9574:31)
      at p5.Reverb.process (http://localhost:9001/lib/addons/p5.sound.js:9501:12)
      at p5.setup (eval at <anonymous> (test-reference.html:36:11), <anonymous>:12:10)
      at p5.p.(anonymous function) [as setup] (test-reference.html:158:27)
      at p5.<anonymous> (http://localhost:9001/lib/p5.js:47814:15)
      at p5._runIfPreloadsAreDone (http://localhost:9001/lib/p5.js:47762:15)
      at p5._decrementPreload (http://localhost:9001/lib/p5.js:47772:15)
      at http://localhost:9001/lib/addons/p5.sound.js:968:14
      at AudioContext.<anonymous> (http://localhost:9001/lib/addons/p5.sound.js:1000:15)
```

[Here](https://pastebin.com/jr6be5mA) is a link to a paste bin containing the log file (since i did not want to spam this post any further).

It also says `Aborted due to warnings.` at the end, but even running grunt with the `-f` or `--force` option does not help.

This is probably just an issue on my end, since the CI job ran fine. I just don't know what the problem is or how i could fix it. Looking forward to any kind of help ^^

**Comment by lmccart** [comment]
@Siiiimon could you try updating to node10 and see if it resolves things?

**Comment by pioug** [comment]
_I just came across this issue by googling the error._ 

It seems like Chrome recently disallowed assigning `ConvolverNode.buffer` more that once.

**Comment by lmccart** [comment]
I'm going to close this issue as it's tracked more specifically in https://github.com/processing/p5.js-sound/issues/328
