### ISSUE TITLE
console.log multiple arguments 

### ISSUE THREAD

**Issue by RinayShah** [processing/p5.js#3094]
http://alpha.editor.p5js.org/lisajamhoury/sketches/BJBbQ7uMf

I am trying to use I want to display both Kinect joint's data on JSON Object file 
I can display data for either of the Kinect but I cannot display it for both. I want to know where I can insert t
console.log(joint,joint2) so I can acquire both joint data?

**Comment by lmccart** [comment]
this simplified example of printing two arguments seems to work ok:
```javascript
var x = 10;
var y = 20;
function setup() {
  console.log(x, y);
}
```

if you'd like more formatting, you can also write things like:
```
function setup() {
  console.log("x = " + x + " y = + y);
}
```

if you are having trouble getting values out of kinect data, I would suggest posting this in the forum for more specific programming assistance. https://discourse.processing.org/
