### ISSUE TITLE
What JS standard does p5js use?

### ISSUE THREAD

**Issue by patlecat** [processing/p5.js#3096]
So what JS standard does the p5js basic libraries use? I hope at least ES5? Or even newer? How does it play with compilers like TS and Babel?

**Comment by lmccart** [comment]
p5.js currently uses ES5. we will shortly be undertaking efforts to update to ES6.

here are some templates for using p5.js with Babel and TS:
https://github.com/apitaru/P5JS-ES6-Babel-Webpack-Starter
https://github.com/mkontogiannis/p5.js-es6-babel-sass-webpack-boilerplate
https://github.com/p5-types/p5.ts
https://github.com/Gaweph/p5-typescript-starter
