### ISSUE TITLE
Unwanted Dependency on grunt-mocha in npm package

### ISSUE THREAD

**Issue by gdad-s-river** [processing/p5.js#3100]
#### Nature of issue?

- [x] Found a _possible_ bug

#### Most appropriate sub-area of p5.js?

- [x] Other — NPM package

#### Details about the bug: 

`grunt-mocha` is a dependency shown on p5 npm package (which, if needed should be devDependency, I guess?)

<img width="1280" alt="screen shot 2018-07-30 at 2 09 50 pm" src="https://user-images.githubusercontent.com/4655633/43387044-0249d12a-9403-11e8-98f2-fedcd82387c9.png">

while p5 repository doesn't have any dependency on it at all seen from [package.json](https://github.com/processing/p5.js/blob/master/package.json)

- p5.js version: 0.6.1

**Comment by limzykenneth** [comment]
Should have been solved but #2837 also reports this issue unsolved but it may need to wait for the next release, I'm not sure. @lmccart

**Comment by lmccart** [comment]
yes that's correct @limzykenneth. I'm working on getting a new release out this week.
