### ISSUE TITLE
Gamepad Support

### ISSUE THREAD

**Issue by moritz157** [processing/p5.js#3106]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [x] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [x] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### New feature details:
It would be nice to have gamepad support using the Gamepad API in the Browser. A Documentation of the API can be found here: https://developer.mozilla.org/en-US/docs/Games/Techniques/Controls_Gamepad_API

**Comment by limzykenneth** [comment]
I was briefly looking into the Gamepad API last month and found that the implementation across browsers differs quite significantly, especially in key bindings, controller detection, and controller namings.

Until the implementations across browsers significantly stabilized, it may be very difficult to properly implement this.

**Comment by lmccart** [comment]
I'm not seeing a lot of energy currently around this one, and based on @limzykenneth's point, I think this function is beyond the scope of the p5.js api in the gamepad API's current state. but it could be a great starting point for an addon library. see the docs here for how to create an addon: https://github.com/processing/p5.js/blob/master/developer_docs/creating_libraries.md
