### ISSUE TITLE
Unsupported kern table version.

### ISSUE THREAD

**Issue by phywand** [processing/p5.js#3107]
Morning..

#### Nature of issue?

- [x] Found a bug

#### Most appropriate sub-area of p5.js?

- [x] Typography

#### Which platform were you using when you encountered this?

- [x ] Desktop/Laptop

#### Details about the bug: 

- p5.js version: p5.js v0.5.11 June 01, 2017
- Web browser and version: Safari 11.1.2
- Operating System: OSX 10:13:6

-I switched a  font from OpenSans(google font) to Renner (http://indestructible-type.github.io) in a working sketch, so

romanFont= loadFont("../__PDLenvironment/Renner-300-Light.otf");

 and got

[Error] Error: Unsupported kern table version.
	argument (p5.min.js:1:8432)
	d (p5.min.js:3:597)
	g (p5.min.js:1:30426)
	(anonymous function) (p5.min.js:1:30582)

Sorry don't know enough to know if it is the font or p5js, but the font works well elsewhere...hope this is helpful

**Comment by dhowe** [comment]
See [this ticket](https://github.com/nodebox/opentype.js/issues/244). Can we verify the p5js and opentype versions that fail here?

**Comment by phywand** [comment]
So I upgraded to p5.js v0.6.1 April 27, 2018 and the error went away. I hope 0.6.1 is a superset of 0.5.11, so nothing else breaks. Sorry not to be up to date with p5js. And thanks for getting back. Next time, if there is one, I'll check the versions first: and the tickets if I remember how to find them.

**Comment by limzykenneth** [comment]
We updated opentype.js in between these versions so that may have fixed the problem. If you found anything broken, just open a new issue, thanks.
