### ISSUE TITLE
Reference documentation for the curvePoints may be wrong

### ISSUE THREAD

**Issue by OsakaStarbux** [processing/p5.js#3108]
#### Nature of issue?

- [x ] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x ] Other (specify if possible) curvePoints() documentation

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x ] Desktop/Laptop
- [ x] Others: P5 reference editor, codepen

#### Details about the bug: 

- p5.js version: 0.6.1
- Web browser and version: Safari 11.1.2
- Operating System: MacOS 10.13.6
- Steps to reproduce this:
I think the docs for the function curvePoint() show the wrong order of parameters. I think the parameters are the same order as the curve() function but the docs say they are different. Here's my codepen explaining and showing what I mean: [https://codepen.io/KevinBradley/pen/GBybKg](https://codepen.io/KevinBradley/pen/GBybKg)

I think the example in the online reference works because it follows the real order of parameters rather than the one described.

Apologies in advance if I'm just confused, wrong, etc. I'm newish to programming and self-taught.

**Comment by lmccart** [comment]
I believe you are correct, thank you for the clear and thorough write-up.
