### ISSUE TITLE
How can save SoundRecorder as ogg or mp3 file ??

### ISSUE THREAD

**Issue by hany0526** [processing/p5.js#3109]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [ ] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 
- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

**Comment by K1ngjulien** [comment]
Here is the Refence page for the sound recorder. it clearly shows how to save sound files
https://p5js.org/examples/sound-record-save-audio.html

**Comment by limzykenneth** [comment]
@hany0526 p5.Sound currently don't directly support saving to ogg or mp3 files, only to wav files. You will need to convert them yourself once saved. You can open an issue at https://github.com/processing/p5.js-sound if you wish to request for this feature (though I'm not sure how possible it is to implement).

In future, this kind of question is better for the [forum](https://discourse.processing.org/) as github issues are more for bug reports and feature requests. Thanks!
