### ISSUE TITLE
Typescript definitons in NPM package not up to date

### ISSUE THREAD

**Issue by K1ngjulien** [processing/p5.js#3111]
#### Nature of issue?

- [x] Found a bug
- [x] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] WebGL
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] Other (Typescript)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: v0.6.1
- Web browser and version: 68.0.3440.84 
- Operating System: Windows 10 64bit
- Steps to reproduce this:

Using VSCode as the editor:

1. `npm install p5`
2. open `p5.d.ts` in `node_modules/p5/lib`
3. let VSCode analyze the type definitions

This is the result:

![image](https://user-images.githubusercontent.com/16562333/43642718-fcf8c57c-9728-11e8-9cb1-34f4ce343d54.png)

These missing definitions have already been added to the release branch of the types repository: 
https://github.com/p5-types/p5.ts/blob/a1d043ef29fa33ed99f203d7ebc1a5d1560295c9/index.d.ts#L12150 

If you use `ctrl+f ` you will find them at the bottom of the file.

**Comment by K1ngjulien** [comment]
UPDATE: It seems to me that the "global.d.ts" and "index.d.ts" from the *p5-types* repository actually get swapped in the build process.

p5-types/index.d.ts => npm-package/p5.global-mode.d.ts
p5-types/global.d.ts => npm-package/p5.d.ts

**Comment by lmccart** [comment]
typescript support has been moved to the library you linked, future npm packages will not contain typescript.
