### ISSUE TITLE
video speed() needs to be called after play()

### ISSUE THREAD

**Issue by micuat** [processing/p5.js#3113]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [x] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.6.1
- Web browser and version: chrome 68.0.3440.84
- Operating System: windows 10 
- Steps to reproduce this:

video `speed()` is ignored when called before `play()`

http://alpha.editor.p5js.org/micuat/sketches/rJzuVH7r7

for me I thought calling `speed()` before `play()` is more intuitive but it makes sense to change speed after video has started too. Looking at this PR https://github.com/processing/p5.js/pull/1245 I guess setting `video.elt.playbackRate` is not enough.

**Comment by micuat** [comment]
ok I found that this problem is because video is not loaded yet when `speed()` is called.

However, even though I add `createVideo()` in `preload()`, `speed()` does not take into effect
http://alpha.editor.p5js.org/micuat/sketches/BJO5vJErQ

I need to explicitly load `setup()` after video loading is finished
http://alpha.editor.p5js.org/micuat/sketches/H17mu1VBm

I supposed that, like loading images or fonts, `preload()` works as promise for loading videos, but it seems not.

**Comment by lmccart** [comment]
that's correct, as the reference says "Nothing besides load calls (loadImage, loadJSON, loadFont, loadStrings, etc.) should be inside preload function."

there is, however, a currently undocumented `loadedmetadata` property. see the example here for how to use it. https://github.com/processing/p5.js/issues/3123

I'm going to close this issue since resolution of the other one should address this problem as well.

**Comment by micuat** [comment]
@lmccart sounds good. I guess it's also useful to document that initialize operations (e.g., `speed()`) should be in the callback of `createVideo()` instead of `setup()`.

**Comment by lmccart** [comment]
oh I see, there is actually an additional issue here. thanks

**Comment by lmccart** [comment]
this has been fixed so you shouldn't need to check the loadedmetadata property. however note that to get the correct console.log readout, you will need to update your log line to:
```js
  console.log(vid.speed());
```
