### ISSUE TITLE
error open loadJSON p5js 0.6.1

### ISSUE THREAD

**Issue by unoudos** [processing/p5.js#3118]
When you try to open it, it gives you the message TypeError: b.text is not a function
    at p5.min.js:10
﻿

but if you do it with version 0.6.0 it works correctly

code
let url = 'http://api.open-notify.org/iss-now.json'

function setup(){
	createCanvas(600,400);
 askISS();
}

function askISS(){
 loadJSON(url, gotData, 'jsonp');
}

function gotData(data){
	console.log(data);
 }
function draw(){

}

**Comment by limzykenneth** [comment]
This is fixed in #2855 which will be included in the next release 0.6.2
