### ISSUE TITLE
TRIANGLE_STRIP in WEBGL has wrong vertex connection

### ISSUE THREAD

**Issue by binkpitch** [processing/p5.js#3119]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.6.1
- Web browser and version: Chrome  68.0.3440.84 
- Operating System: OSX
- Steps to reproduce this:

The TRIANGLE_STRIP is suppose look like the one in the document (https://p5js.org/reference/#/p5/beginShape 2).
<img width="539" alt="screen shot 2561-08-05 at 22 10 44" src="https://user-images.githubusercontent.com/20456165/43687307-082edfa0-98fd-11e8-8b57-f0d82c8371f0.png">

But, when I tried it in WEBGL it looks different, some points are not connected to each other. (https://alpha.editor.p5js.org/binkpitch/sketches/HJkNCBEBQ).
<img width="1305" alt="ed25bd68d33177bd38f7b4fdfe1fd4f9eac70394" src="https://user-images.githubusercontent.com/20456165/43687300-e7328216-98fc-11e8-9e09-f50ebf1e28b0.png">

**Comment by AdilRabbani** [comment]
Hey @mlarghydracept correct me if I'm wrong but shouldn't this be fixed by adding : 
```
if (this.immediateMode.shapeMode === constants.TRIANGLE_STRIP) {
     var i
     for (i = 0; i < this.immediateMode.vertices.length - 2; i++) {
         this.immediateMode.edges.push([i, i + 1]);
         this.immediateMode.edges.push([i, i + 2]);
     }
     this.immediateMode.edges.push([
       i,
       i + 1
     ]);
 }
```
when the edges are being pushed in [p5.RendererGL.prototype.endShape](https://github.com/processing/p5.js/blob/master/src/webgl/p5.RendererGL.Immediate.js#L120).

**Comment by MarellaB** [comment]
Still seeing this issue in version 0.7.2 any news on a fix? Works just fine with 2d, but switching to WEBGL renders a line loop instead it seems.

![image](https://user-images.githubusercontent.com/10491114/45012145-d32a4580-afe3-11e8-8bea-a12458d5b014.png)
Renders this with 2d
![image](https://user-images.githubusercontent.com/10491114/45012159-dae9ea00-afe3-11e8-90e0-73ba59db060d.png)
but as soon as I add WEBGL to createCanvas. It becomes this:
![image](https://user-images.githubusercontent.com/10491114/45012186-f0f7aa80-afe3-11e8-94b6-56e56bc85827.png)

**Comment by bashbers** [comment]
Doesnt seem to be fixed in 0.7.2. Below is an image using WEBGL and using P2D side-to-side:
![image](https://user-images.githubusercontent.com/23037527/50769288-ccf2f100-1283-11e9-9882-afd974060de4.png)

![image](https://user-images.githubusercontent.com/23037527/50769311-d5e3c280-1283-11e9-913a-413e47af703f.png)

**Comment by arapl3y** [comment]
I'm still getting this issue in the p5 web editor
```
  beginShape(TRIANGLE_STRIP);
  vertex(30, 75);
  vertex(40, 20);
  vertex(50, 75);
  vertex(60, 20);
  vertex(70, 75);
  vertex(80, 20);
  vertex(90, 75);
  endShape();
```

outputs:
![screen shot 2019-02-04 at 10 39 34 am](https://user-images.githubusercontent.com/14939268/52184580-5ab50280-2869-11e9-9ff6-8a0261f756ae.png)

**Comment by AdilRabbani** [comment]
I believe the p5 web editor is not updated with the latest version. I am getting correct results for the above example when building from the master branch.
```
function setup()
{
  createCanvas(200, 200, WEBGL);
  stroke(0);
  fill(255);
  background(200);
  strokeWeight(2);
}

function draw()
{
  beginShape(TRIANGLE_STRIP);
  vertex(30, 75);
  vertex(40, 20);
  vertex(50, 75);
  vertex(60, 20);
  vertex(70, 75);
  vertex(80, 20);
  vertex(90, 75);
  endShape();
}
```
Outputs:

![result](https://user-images.githubusercontent.com/15272015/52201943-decdb100-288e-11e9-80af-19b1582a6e37.PNG)

**Comment by AdilRabbani** [comment]
Also getting correct results for Version 0.7.3 from the [official website](https://p5js.org/download/).

**Comment by stalgiag** [comment]
Thanks for checking @AdilRabbani!
