### ISSUE TITLE
document loadedmetadata property for video element

### ISSUE THREAD

**Issue by paulcanning** [processing/p5.js#3123]
When dealing with images, I can load an image in setup, then use `get()` to fetch a section of the image.

Is there a way to do this with video capture?

I tried by having `createCapture(VIDEO)` in `setup()` and then in `draw()` I tried using `var foo = 
capture.get(x, y, w, h)` and then `image(foo, x, y, w, h)` but I got an error about drawImage.

The error:

`Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0`

My code:

```
var capture;

function setup() {
	createCanvas(640, 480);
	capture = createCapture(VIDEO);
}
function draw() {
	background(0);
	var c = capture.get(0, 0, 100, 100);
	image(c, 0, 0);
}
```

EDIT - I can get it to work via the Chrome console after the video is fully loaded, so I tried adding a boolean flag in the createCapture callback, and check it in the draw method, but I'm still getting the same error.

**Comment by lmccart** [comment]
this should work
```js
var capture;

function setup() {
	createCanvas(640, 480);
	capture = createCapture(VIDEO);
}
function draw() {
	background(0);
  if (capture.loadedmetadata) {
    var c = capture.get(0, 0, 100, 100);
		image(c, 0, 0);
  }
}
```

**Comment by lmccart** [comment]
updating the title to reflect todo

**Comment by paulcanning** [comment]
That helps a lot, thanks! I was using `if (c.widtrh > 0)` 😄

**Comment by lmccart** [comment]
reopening this to remind us to document this property
