### ISSUE TITLE
Custom function incompatible with image() in the draw loop when both take mouseX,mouseY as coordinates?

### ISSUE THREAD

**Issue by rsummr** [processing/p5.js#3126]
#### Most appropriate sub-area of p5.js?
- [x] Events
#### Which platform were you using when you encountered this?
- [x] Desktop/Laptop

#### Details about the bug: p5.js on Chrome (MacOSX) via Open Processing

Scroll to function draw() for description of the problem. Complete code minus image URLs below: 

`var bgImg; 
var whitewall;
var wallSections =[]

function preload(){
 bgImg = loadImage(...)
 whitewall = loadImage(...)
}

class FreshPaint{
	constructor (x,y){
		this.xCoord=x;
		this.yCoord=y;
	}
	checkPos(x,y){
		if (dist(x,y,this.xCoord,this.yCoord) < 10){
			return true;
			}
			else{return false;
					}
		}	
}

function setup() {
	createCanvas(windowWidth, windowHeight);
	rectMode(CENTER)
	paintRoller();
	for (var ix = 0; ix<width; ix+=10){
		for (var iy = 0;iy<height; iy+=10){
			wallSections.push(new FreshPaint(ix,iy))
		}
	}
}

**//Without 'image(wallSections), the paintRoller graphic follows mouseX,mouseY coordinates as designed;**

 **//But with the addition of 'image(wallSections)'— which makes visible "white paint" [image(whitewall...)] when mouseDragged() occurs—the paintRoller() graphic snaps to 0,0 from the outset when the code is run and doesn't budge**

function draw(){
	imageMode(CORNER);
	background(bgImg);
	paintRoller() :

	image(wallSections);

**//Why does this one line of code, 'image(wallSections)', undermine the paintRoller() function, and how do I get around the problem?**

function mouseDragged(){
	imageMode(CENTER);
	for(var ipaint = 0; ipaint<wallSections.length; ipaint++){
		if (wallSections[ipaint].checkPos(mouseX,mouseY)){
			tint(255,85);
			image(whitewall,wallSections[ipaint].xCoord,wallSections[ipaint].yCoord,85,30);
		}
	}
}

//custom paintRoller () function
function paintRoller(){
		fill(255,226,145);
		stroke(150);
		strokeWeight(.5);
		rect(mouseX,mouseY,100,30,50);
		fill(172,191,185);
		stroke(114,127,123);
		strokeWeight(0.75);
		beginShape();
		vertex(mouseX+50,mouseY-1.25);
		vertex(mouseX+60,mouseY-1.25);
		vertex(mouseX+60,mouseY+25);
		vertex(mouseX+10,mouseY+50);
		vertex(mouseX+10,mouseY+62.5);
		vertex(mouseX+7.5,mouseY+62.5);
		vertex(mouseX+7.5,mouseY+47.5);
		vertex(mouseX+57.5,mouseY+22.5);
		vertex(mouseX+57.5,mouseY+1.25);
		vertex(mouseX+50,mouseY+1.25);
		endShape(CLOSE);
		fill(64,54,0);
		stroke(0);
		strokeWeight(.5);
		rect(mouseX+8.75,mouseY+87.5,10,50,5);
	}`

**Comment by lmccart** [comment]
the github issues here are a good place for bugs and issues with the p5.js library itself. for questions about writing your own code, tests, or following tutorials, the [forum](https://discourse.processing.org/) is the best place to post. thanks!
