### ISSUE TITLE
grunt-mocha should be a devDependency

### ISSUE THREAD

**Issue by QuentinRoy** [processing/p5.js#3130]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other (specify if possible) npm publishing

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.6.1
- Web browser and version: any
- Operating System: any
- Steps to reproduce this:
```sh
npm install p5
```

Because `grunt-mocha` is registered as a `dependency` (instead of `devDependency`), it is installed when installing the library with `npm`. This is useless, but also raises an misleading warning because `grunt-mocha` as `grunt` as a `peerDependency` and hence will warn consumers if `grunt` isn't found (most of the time).

**Comment by Spongman** [comment]
i believe this is already fixed in master and should be fixed in the next release.

**Comment by QuentinRoy** [comment]
Apologies this is true.

**Comment by Spongman** [comment]
no apologies necessary. there's no such thing as a bad bug report!
