### ISSUE TITLE
Zooming in browser breaks the clear() function (version 0.6.1)

### ISSUE THREAD

**Issue by lobertrand** [processing/p5.js#3131]
#### Nature of issue?

- [x] Found a bug

#### Most appropriate sub-area of p5.js?

- [x] Core/Environment/Rendering

#### Which platform were you using when you encountered this?

- [x] Desktop/Laptop

#### Details about the bug: 

- p5.js version: 0.6.1
- Web browser and version: Google Chrome 68.0.3440.84 and Microsoft Edge 42.17134.1.0
- Operating System: Windows 10
- Steps to reproduce this:

```html
<!DOCTYPE html>
<html>
<head lang="fr">
  <meta charset="utf-8">
</head>
<body>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.6.1/p5.min.js"></script>
  <script src="sketch.js"></script>
</body>
</html>
```
```javascript
function setup() {
  createCanvas(100, 100);
}

function draw() {
  clear();
  ellipse(random(width), random(height), 20, 20);
}
```
![clear-function-bug](https://user-images.githubusercontent.com/37326143/43864456-08adebb4-9b60-11e8-816a-ca8ebef3c905.png)

When the browser has a zoom level greater than 100% at the moment of the code execution, the `clear()` function doesn't work properly. Only the top left corner of the canvas is cleared.

This code works fine with version 0.6.0 of p5 but breaks with version 0.6.1.

**Comment by Spongman** [comment]
i believe this is a dupe of #2846 which should be fixed in the next release of p5.

**Comment by lobertrand** [comment]
@Spongman You're certainly right, sorry for that, I'm new to GitHub ^^

**Comment by Spongman** [comment]
no worries. thanks for the bug report!
