### ISSUE TITLE
"postinstall": "patch-package" causing npm download error

### ISSUE THREAD

**Issue by lmccart** [processing/p5.js#3135]
this line in package.json is causing an error when downloading p5 via npm, because it requires package "patch-package"
```
  "postinstall": "patch-package",
```

is there a version of postinstall that only runs for development downloads? would this be "prepare"?

cc @Spongman

**Comment by Spongman** [comment]
I believe so. I'm not sure exactly why it was changed to post-install (I never had any issues with it before), but I think changing it back would be fine to fix the npm error.

**Comment by Spongman** [comment]
ok, it looks like the only issue with using `prepare` is that `npm ci` doesn't work. :man_shrugging:
