### ISSUE TITLE
button.mousePressed() broken?

### ISSUE THREAD

**Issue by Creechie** [processing/p5.js#3141]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [x] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: p5.js v0.7.1 August 10, 2018
- Web browser and version: Chrome 68.0.3440.106 (Official Build) (64-bit)
- Operating System: Windows 10
- Steps to reproduce this:
Getting the error "`Uncaught TypeError: Cannot read property '_setProperty' of undefined at g.Element.<anonymous> (p5.min.js:7)`" when using the `button.mousePressed();` function.
This also seems to be happening in the p5 example linked below:
https://p5js.org/examples/dom-input-and-button.html

**Comment by limzykenneth** [comment]
It seems `this._pInst` at https://github.com/processing/p5.js/blob/master/src/core/p5.Element.js#L239 appears to be undefined.

**Comment by ashleyjamesbrown** [comment]
Can I ask if this is fixed ?

**Comment by Zalastax** [comment]
@ashleyjamesbrown it will be fixed once #3150 is merged.

**Comment by Spongman** [comment]
could we possibly cherry-pick this fix into a special branch off 0.7.1 and release that? it seems like this is a somewhat critical issue that deserves to be fixed outside the regular release schedule.

**Comment by mm909** [comment]
Still having this issue. Has it been resolved?

**Comment by mm909** [comment]
Have the p5.js libs been updated on the p5.js website? I manually updated my dom lib based on issue  #3150 and it is working. Thank you for all the help.

**Comment by Spongman** [comment]
yup, 0.7.2 includes a fix for this ;-)

**Comment by Bubblebyb** [comment]
On 0.7.3, still getting this error.
