### ISSUE TITLE
saveTable() wrong csv output 

### ISSUE THREAD

**Issue by PassLn** [processing/p5.js#3143]
Hi,
I have a problem when I saved table in csv.
CSV tables are saved with a new line after any element.

For example, the following code:

```
var table;

 function setup() {
 table = new p5.Table();

 table.addColumn('id');
 table.addColumn('species');
 table.addColumn('name');

 var newRow = table.addRow();
 newRow.setNum('id', table.getRowCount() - 1);
 newRow.setString('species', 'Panthera leo');
 newRow.setString('name', 'Lion');

 saveTable(table, 'new.csv');
 }
```

Gives the following result ( I try to open in OpenOffice Calc, Excel and Notepad++, it's always the same)
id,
species,
name
0,
Panthera leo,
Lion

But the result should be this:

id,species,name
0,Panthera leo,Lion

Could you help me?

#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [x] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 1.0.4
-processing version : 3.4
- Operating System: Windows/

**Comment by Spongman** [comment]
> p5.js version: 1.0.4

this doesn't look like a valid p5.js version, the latest version is 0.7.1. can you take a look at your p5.js script file? the version should be near the beginning of the first line.

**Comment by PassLn** [comment]
Sorry, I mixed "p5.js Mode 1.0.4" (which is for the IDE) and "p5.js v0.5.7"

I downloaded the latest version of Processing 3 yesterday and I thought that it was made with the latest version of P5js but it was not the case. In fact, it contains version 0.5.7. In order to use 0.7.1, I had to download the minified version from the P5js website, and replace the p5.min.js file in the /java/reference/javascript directory. 

There is an automatic update system in the processing IDE, but I didn't find the way to update the P5js version in there. Do you know if it's possible and how ? It will be easier for next time.

Thank you for your help,

**Comment by lmccart** [comment]
hi @PassLn p5.js mode in processing is a separate project and we don't have control over the versioning from here. you could try posting over on that repo: https://github.com/fathominfo/processing-p5js-mode
