### ISSUE TITLE
mousePressed won't work for buttons with v0.7.0 or later

### ISSUE THREAD

**Issue by kotobuki** [processing/p5.js#3148]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [x] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.7.0 or later
- Web browser and version: Chrome 68.0.3440.106 and Safari 11.1.2
- Operating System: 10.13.6
- Steps to reproduce this:
1. Open the example at CopePen (https://codepen.io/kotobuki/pen/qyGVxY?editors=0011)
2. Press the 'Press Me!' button
3. See the console

What I expect is that the string "pressed" is output when the button is pressed. However, in fact, nothing happens.

The same code works fine with v0.6.1 (same version as http://alpha.editor.p5js.org/)
https://codepen.io/kotobuki/pen/GBajWo?editors=0011

**Comment by lmccart** [comment]
thanks this is tracked here https://github.com/processing/p5.js/issues/3141
