### ISSUE TITLE
video.get() seems to freeze live stream of the video

### ISSUE THREAD

**Issue by CreativeCode** [processing/p5.js#3153]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [X] Other (DOM?)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [X] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.6.1
- Web browser and version: Version 68.0.3440.106 (Official Build) (64-bit)
- Operating System: Mac
- Steps to reproduce this:

Run the following code and you will see that the video no longer is updated after video.get() is called.:
```
function takesnap() {
   currentImg = video.get(); 
}

function setup() {
    createCanvas(600, 240);
    video = createCapture(VIDEO);
    video.size(320, 240);
    video.hide();
    background(0);
    captureBtn = createButton('snap');
    captureBtn.mousePressed(takesnap);
}

function draw() {
    image(video,0,0);
}
```

Workaround by @meiamsome 👍 
```
function draw() {
  var frame = video.get();
  image(frame, 0, 0);
}
```

**Comment by Spongman** [comment]
can you try this with 0.7.1?

**Comment by garciadelcastillo** [comment]
I believe this issue is still happening...

**Comment by ffd8** [comment]
@garciadelcastillo Indeed – just ran into this, searched and stumbled across this old issue with your brand new comment. [Here's a mini-example](https://editor.p5js.org/ffd8/sketches/ZKFzcHIxB) showing the issue.. using `capture.get()` all the time is ok, but the minute it's within an if statement, the capture stops when that if statement is false... weird.

**Comment by garciadelcastillo** [comment]
Yup, I assume `get()` does pixel loading within the function. 

The issue [can be bypassed](https://editor.p5js.org/garciadelcastillo/sketches/fuSAIioJQ) if you `loadPixels()` every frame, but adds the overhead...
