### ISSUE TITLE
Stroke cap style doesn't apply to point() as in Processing

### ISSUE THREAD

**Issue by noisefactor** [processing/p5.js#3159]
The behavior relating strokeCap() and point() is not the same in p5js as in Processing. For example,
the following will produce squares when clicking in Processing, but it generates circles in p5js.
```java
//processing
void setup() {
  size(500,500);
  stroke(0);
  strokeWeight(50);
  strokeCap(PROJECT);
}
void mousePressed() {   point(mouseX, mouseY); }
void draw(){}
```
```js
// p5js
function setup() {
	createCanvas(windowWidth, windowHeight);
	stroke(0);
	strokeWeight(50);
	strokeCap(PROJECT);
}
function mousePressed() {	point(mouseX, mouseY); }
```

**Comment by lmccart** [comment]
Hm it makes sense to me that a point is a circle. There's no rule that p5.js has parity with Processing, so maybe it is ok to deviate here?

**Comment by noisefactor** [comment]
I feel as though it's removing a feature to leave it this way. point() is two parameters instead of four, so it permits square points with fewer parameters. It's only ever activated if people fiddle with strokeCap(), which I think is fairly uncommon. The Processing treatment of a point as related to stroke, as opposed to being a primitive shape, makes more sense to me.

**Comment by lmccart** [comment]
Yes I agree it's one less feature, but as you mention, it may be an uncommonly used one. If this doesn't break any intuitions for how a point should work in general, perhaps we can let this one go and focus our energy on other more critical unimplemented features and bug fixing?
