### ISSUE TITLE
p5.js:48602 Uncaught TypeError: Cannot read property '_setProperty' of undefined (eventPrependedFxn @ p5.js:48602)

### ISSUE THREAD

**Issue by stuleelight** [processing/p5.js#3163]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [x] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: p5.js/0.7.1
- Web browser and version: Chrome
- Operating System: MacOs
- Steps to reproduce this: I'm following CodingTrain's tutorial and went through a few fine until the L system one. Everything works up until the mousePressed? I'm not sure; I'm nub, but any help is appreciated. 
The following code is viewed through an index.html file.

```
// variables: A B
// axiom: A
// rules: (A -> AB), (B -> A)

var axiom = "A";
var sentence = axiom;

var rule1 = {
	a: "A",
	b: "AB"
}

var rule2 = {
	a: "B",
	b: "A"
}

function generate() {
	var nextSentence = "";
	for (var i = 0; i < sentence.length; i++) {
		var current = sentence.charAt(i);
		if (current === rule1.a) {
			nextSentence += rule1.b;
		}	else if (current == rule2.a) {
			nextSentence += rule2.b;
		}	else {
			nextSentence += current;
		}

	}

	sentence = nextSentence;
	createP(sentence);

}

function setup() {
	noCanvas();
	createP(axiom);
	var button = createButton("generate");
	button.mousePressed(generate);
}
```

**Comment by Spongman** [comment]
yup, this is a bug (actually a dupe of #3141). i'd recommend using p5.js version 0.6.1 for now until a fix for this is released.

**Comment by stuleelight** [comment]
Thank you so much! Makes sense since the tutorial is using that version as well.
