### ISSUE TITLE
Online Reference Source Link Error

### ISSUE THREAD

**Issue by jaspertravers** [processing/p5.js#3164]
At the bottom of https://p5js.org/reference/#/p5/vertex the link to the github documentation is broken. This issue persists in most of the subsections of **Shape** in the online reference.

search `src/core/vertex.js`

The links for all files under `/src/core/shape` (namely `2d_primitives.js`, `attributes.js`, `curves.js` and `vertex.js`) are broken from the reference manual to the github source.

They should point to `/src/core/shape/<ITEM>.js` //note the added `/shape/` from refactoring.

These broken links are from every file of every header under **Shape** on the reference page (https://p5js.org/reference/).

Note **3D Models** links are not broken, but **3D Primitives** are. They should also probably be updated to `/src/webgl/3d_primitives.js` where it looks like the source filename was renamed from `src/webgl/primitives.js`.

I couldn't tell if this issue should be posted here or (https://github.com/processing/p5.js-website/issues) because I read in multiple places specifically that the reference page lives in this repo. Feel free to move or tell me to move it if I got that wrong.

**Comment by lmccart** [comment]
thanks! fixed with https://github.com/processing/p5.js-website/commit/5306ea719564714cdb1aae20e45dac183e841e14
