### ISSUE TITLE
Shadows for p5

### ISSUE THREAD

**Issue by TanviKumar** [processing/p5.js#3167]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [x] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### New feature details:
Currently p5.js does not have any support for shadows. It's one of the very few things missing and should be relatively easy to implement too! This links to the [documentation about shadows](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D#Shadows). 

It would be great if a method could be added to allow the user to create shadows with ease. Perhaps multiple methods could be created to change specific properties of the shadows, though I'm unsure as to how useful that might truly be. Hoping this issue can be a space for discussion about this.

In case the community believes that this would be a useful addition, I've written some [code](https://github.com/processing/p5.js/pull/3154) for a method for creating shadows, hopefully that can be a good start!

**Comment by lmccart** [comment]
I'm not seeing a lot of response around this one right now and I think it may be beyond the scope of the library for now. It is possible to call these methods natively on the canvas object, so I'm not sure a wrapper of these is necessary. Let's revisit in the future if others express the same need. Thanks @TanviKumar

**Comment by lekmao** [comment]
@TanviKumar 
Do you have an example of using "drop shadows" in 2D art?
New to p5.js and working on an assignment. I would like to add depth to it. Any help?
Thanks!

**Comment by flomerboy** [comment]
An example in the documentation would be very helpful - I don't know how to "call these methods natively on the canvas object" and I would expect the average p5js user to not be familiar with it either.

**Comment by lmccart** [comment]
@jatin33 maybe you'd like to look at this one?

**Comment by Pedroxam** [comment]
Adding shadow to objects is easy :

var context = drawingContext; // or p5.drawingContext
context .shadowOffsetX = 5;
context .shadowOffsetY = -5;
context .shadowBlur = 10;
context .shadowColor = '#FFF';
`

**Comment by 8o8inCodes** [comment]
> Adding shadow to objects is easy :
> 
> var context = drawingContext; // or p5.drawingContext
> context .shadowOffsetX = 5;
> context .shadowOffsetY = -5;
> context .shadowBlur = 10;
> context .shadowColor = '#FFF';

Here is a documentation
https://p5js.org/reference/#/p5/drawingContext

**Comment by nnmrts** [comment]
Yeah drawing a line without p5 on a canvas is "easy" too:

```js
const canvas = document.getElementById('canvas');
const ctx = canvas.getContext('2d');

ctx.beginPath();       // Start a new path
ctx.moveTo(30, 50);    // Move the pen to (30, 50)
ctx.lineTo(150, 100);  // Draw a line to (150, 100)
ctx.stroke();
```

That's not the point of the issue though. Saying "I'm not sure a wrapper of these is necessary" would imply that 90% of p5.js is not necessary, most of it is just a wrapper around canvas stuff.

But I guess it's not in the scope of a creative coding library to add more accessible support for shadows.

**Comment by ThatIsAPseudo** [comment]
I wanted to use shadows as well, after I found this issue I simply added this snippet to my `sketch.js`
```js
function shadow(color, blurRadius = 0, offsetX = 0, offsetY = 0) {
    drawingContext.shadowColor = color;
    drawingContext.shadowBlur = blurRadius;
    drawingContext.shadowOffsetX = offsetX;
    drawingContext.shadowOffsetY = offsetY;
}

function noShadow() {
    drawingContext.shadowColor = '#0000';
}
```

You then can use it like this:
```js
shadow('#fff0', 10);
fill('#fff');
noStroke();
circle(0, 0, 50);
noShadow();
```
