### ISSUE TITLE
dom-drop example code from p5.js doesn't work

### ISSUE THREAD

**Issue by kazimsanlav** [processing/p5.js#3168]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [x] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: p5.js v0.6.0 January 19, 2018
- Web browser and version: Chrome and FireFox
- Operating System: Windows
- Steps to reproduce this:
Example code given in [https://p5js.org/examples/dom-drop.html] doesn't seem to work both from the site itself and in my local code. image() function doesn't show any image on the canvas when I drag on it.

**Comment by limzykenneth** [comment]
Possibly related to #3117, can you try the method described there and if you still encounter a problem, let us know. Thanks. @kazimsanlav

**Comment by kazimsanlav** [comment]
Yes, it was the same issue and that method worked. Thanks. @limzykenneth
