### ISSUE TITLE
Click/Hover detection for 3d shapes?

### ISSUE THREAD

**Issue by jbrundage** [processing/p5.js#3169]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [x] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [ ] Desktop/Laptop
- [ ] Others (specify if possible)

#### New feature details:
Could support be added for 3d shape click/hover detection? (ex: Hover over a `box` and it changes color.)

**Comment by lmccart** [comment]
an example would be great. i'll let the webgl team speak to whether this makes sense for the core library right now.

**Comment by John-Jelatis** [comment]
Any updates on the situation as of this point?

**Comment by tillmanjex** [comment]
Would also really love this 🙏

**Comment by mihkuno** [comment]
I'm actually confused on how to manually implement this with obj models..

**Comment by davepagurek** [comment]
@mihkuno one method would be: in mouse down, pick a random color for each object in your scene, and then draw your scene where each object is drawn without shading using its assigned color to a `p5.Graphics` so it's not visible on the main canvas. Then you can read the pixel under the mouse and see what color is there, and the object with the corresponding color is the one the user clicked on.

I can add making an example for this to my to do list if there's renewed interest!
