### ISSUE TITLE
createVector() converts float to int!

### ISSUE THREAD

**Issue by JuanGaray93** [processing/p5.js#3173]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [x] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.6.0
- Web browser and version: Google Chrome 68.0.3440.106 (Build oficial) (64 bits) (cohort: Stable)
- Operating System: Windows 10
- Steps to reproduce this:

Hello! I was following Dan Schiffman's The Nature of Code playlist and wanted to try doing what he did but using p5 instead of Processing. I tried creating vectors for an object's position, velocity and acceleration like so:

```
class Vehicle{
    constructor(x,y,dx,dy,ddx,ddy){
        this.location = createVector(x, y);
        this.velocity = createVector(dx, dy);
        this.acceleration = createVector(ddx, ddy);
    }
   .  .  .
}
```
and I noticed that whenever the values passed as arguments were floating point numbers below 1, the values would be 0 (my vehicle didn't move).

I managed to get around this issue by creating the vectors at (0,0) and then using the set() method to give them the float values, but this might make someone else's code buggy if they don't notice this.

Thanks in advance!

**Comment by lmccart** [comment]
@JuanGaray93 can you give more of a snippet that demonstrates the issue? when I try this simple example, the vector seems to get created and set correctly, outputting a magnitude > 0:
```js
function setup() {
  var v = createVector(0.5, 0.5);
  console.log(v.mag()); // 0.7071
}
```
if you need help debugging a larger sketch or project, please post in the forum for more help: https://discourse.processing.org/

**Comment by JuanGaray93** [comment]
@lmccart I wasn't able to reproduce the issue, I spent a lot of time debugging when I had this problem but I didn't commit the code while I was doing it so sadly I can't verify if I was the buggy one (which is probably the case). Sorry to have bothered you and thank you for your time. I'll post in the forum next time with some archive of my code.

**Comment by lmccart** [comment]
ok thanks for the update @JuanGaray93
