### ISSUE TITLE
KeyIsDown event failing on Chrome windows 10

### ISSUE THREAD

**Issue by ankeris** [processing/p5.js#3174]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [x] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: v0.7.1
- Web browser and version: Chrome Version 68.0.3440.106 (64-bit)
- Operating System: Mac / Windows 10
- Steps to reproduce this:
In this app, I am inserting p5js into create-react-app. I am creating a canvas where object "Player" moves with help of p5 key events. 
Overall, the Object movements WORKS fine in Microsoft Edge, Mozilla Firefox, Safari. However, it fails on Chrome on Windows 10 OS, no errors occur in the console. The object moves continuously even when a key is not pressed down. Weirdly it works normally on Chrome in Mac OS environment (with same code).
I have very simple conditional statements for movement:

        class Player {
        constructor(xPos, yPos) {
            this.x = xPos;
            this.y = yPos;
        }

        display() {
        p5.rect(this.x, this.y, this.diameter, this.diameter);
        }

        move() {
        if (p5.keyIsDown(p5.RIGHT_ARROW) || p5.keyIsDown(68)) {
            this.x = this.x + 5;
        }
        if (p5.keyIsDown(p5.LEFT_ARROW) || p5.keyIsDown(65)) {
            this.x = this.x - 5;
        }
        if (p5.keyIsDown(p5.DOWN_ARROW) || p5.keyIsDown(83)) {
                this.y = this.y + 5;
        }
        if (p5.keyIsDown(p5.UP_ARROW) || p5.keyIsDown(87)) {
                this.y = this.y - 5;
        }
        }

        p5.draw = function () {
            p5.background(col);
            player.move();
            player.display();
        };

#### Github repo:
https://github.com/ankeris/challengefriend/blob/master/src/sketches/map.js

**Comment by stalgiag** [comment]
I am unable to reproduce using Windows 10 Chrome 75.0.3770 and 0.8.0. I didn't use your example code as it has some problems but the [reference examples work well](https://p5js.org/reference/#/p5/keyIsDown) with the aforementioned setup. Let us know if you are still able to reproduce and try to narrow down the bug example code a little and we will look into it.

**Comment by stalgiag** [comment]
I am closing for organization purposes. I can't reproduce and this issue is rather stale.

Let me know if you can reproduce and I'll reopen the issue. Thank you!
