### ISSUE TITLE
calling pixelDensity() with no args messes with graphic context (calls thereafter behave incorrect)

### ISSUE THREAD

**Issue by vogtadi** [processing/p5.js#3175]
#### Nature of issue?

- [X] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [X] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [X] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.7.1
- Web browser and version: Chrome Version 68.0.3440.106 (Official Build) (64-bit)
- Operating System: MacOSX 10.13.6
- Steps to reproduce this:
As an example, use code in https://p5js.org/reference/#/p5/createGraphics 
add a "var d = pd.pixelDensity();" before the last line
-> circle in example gets scaled
-> expected result:
  - calling pixelDensity without any arguments only READS the parameter

#### Workaround

use the property _pixelDensity instead the function pixelDensity() for reading until this issue has been fixed.

**Comment by lmccart** [comment]
fixed with #3176
