### ISSUE TITLE
p5.js not working on AOSP browser

### ISSUE THREAD

**Issue by iProgramMC** [processing/p5.js#3177]
#### Nature of issue

- Found a bug

#### Most appropriate sub-area of p5.js

- Core/Environment/Rendering

#### Which platform were you using when you encountered this

- Android phone

#### Details about the bug: 

- p5.js version: 0.7.1
- Web browser and version: AOSP Browser (Android 4.2.2)
- Operating System: Android 4.2.2
- Steps to reproduce this:
enter growalonegame.000webhostapp.com/demo/ with AOSP browser for Android 4.2.2

**Comment by Spongman** [comment]
not sure if it's related, but Chrome on Windows gives me a malware warning for that page:

![image](https://user-images.githubusercontent.com/1088194/44742039-b35ec300-aab3-11e8-9e21-e51b432a99a2.png)

**Comment by limzykenneth** [comment]
I don't think there are any plans to support AOSP browser (at least not fully) as it is usually very outdated. The support table on the developer docs are a couple years outdated as well, which we probably should rewrite to keep it up to date.

However, given it is Blink and V8 it should still work most of the time. You will have to provide us with more specifics on how p5.js is not working on AOSP browser. The link you provided as @Spongman mentioned gives the error page above, 000webhost as it is a free web host are often distrusted by browsers, instead you can just paste in a minimal code example here and we can test out the code ourselves.

**Comment by lmccart** [comment]
thanks for reporting @iProgramMC. as @limzykenneth mentions, AOSP is not supported. you can see the full list of supported browsers [here](https://github.com/processing/p5.js/edit/master/developer_docs/supported_browsers.md) without seeing your example page, it's difficult to tell what's wrong, so I'm going to close this one. sorry we can't help!

**Comment by iProgramMC** [comment]
That's why I moved my page to GitHub Pages (for non-WebClient C# stuff, as that won't work with GH Pages).

**Comment by iProgramMC** [comment]
Also, Spongman, it's 000webhost's fault.
