### ISSUE TITLE
WEBGL, smooth() and parent() do not seem to work correctly.

### ISSUE THREAD

**Issue by richardkmichael** [processing/p5.js#3180]
Update: The new online editor is nice! So I used it (and a bit of CSS) to help [demo this issue](https://editor.p5js.org/rmichael/sketches/BkOWCDvwQ). :-)

#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.7.1
- Web browser and version: 61.0.2
- Operating System: MacOSX 10.12.6
- Steps to reproduce this:

Apologies if I've misunderstood usage of instance mode, `smooth()`, and `parent()`.

In instance mode, `smooth()`, `parent()`, and the `WEBGL` renderer do not correctly interact.  I have not yet tested this in global mode.  Perhaps there is a problem coordinating the reference returned by createCanvas and that used in the instance?

This does not seem to happen with the `P2D` renderer, presumably because the smooth implementation is different.

Finally, there is a problem with `noSmooth()` and the 2D renderer, it is mentioned at the end of this issue.

Given this code:

```javascript
var sketch = function (s) {

  s.setup = function () {

    // s.smooth(); // No effect; if called here, the shapes will not actually be smoothed.

    var canvas;
    canvas = s.createCanvas(400, 400, s.WEBGL);

    // Case 1
    // s.smooth();  // If called here, the canvas is duplicated -- one will be at the end of the document,
                    // and it will be the one used in draw(), with the grey background and ellipse.
                    // Use the web inspector to see the duplicate canvas, and the console logs the
                    // "p5.RendererGL: enabled webgl context" a second time.

    canvas.parent('test');  // This correctly moves the blank canvas, returned by createCanvas.
                            // If case 1, draw() uses the original canvas, which has remained
                            // at the end of the document.

    // Case 2
    // s.smooth();  // If called here, the canvas is not duplicated and is correctly used by draw,
                    // but it remains at the end of the document and is not moved by .parent()

  }

  s.draw = function () {
    s.background(150, 150, 150);
    s.ellipse(0, 0, 100, 100);
  }
}

new p5(sketch);
```

As a minor matter, it appears `smooth()` has no effect if called before the canvas has been created.  This seems strange and is not mentioned in the documentation.

There are several cases, which depend upon when `smooth()` is called, they are discussed in the code above.  If `smooth()` is not called at all, `parent()` does move (not duplicate) the canvas and it is used by draw() correctly.

In addition, `noSmooth()` and the `P2D` does not appear to work.  2D shapes default to smoothed, but trying to un-smooth them does not work, code below.

```javascript
var sketch = function (s) {

  s.setup = function () {

    var canvas;
    canvas = s.createCanvas(400, 400);
    canvas.parent('logo');
    s.noSmooth();
  }

  s.draw = function () {
    s.background(150, 150, 150);
    s.ellipse(s.width / 2, s.height / 2, 100, 100);
  }
}

new p5(sketch);
```

**Comment by lmccart** [comment]
could be related to this https://github.com/processing/p5.js/issues/3061?

**Comment by richardkmichael** [comment]
@lmccart Ah, thank you. I hadn't seen that, but I noticed #3027 (smooth is implemented as antialiasing using `setAttribute`).

**Comment by voidgraphics** [comment]
Any updates on this matter? I'm still encountering this bug on 0.7.2. Or any workarounds so I can have smoothing and still manage to move my canvas to my other div?

If help is needed to squash this bug, I can help, I just need someone to point me in the right direction

Thanks :)
