### ISSUE TITLE
p5.XML implementation details

### ISSUE THREAD

**Issue by limzykenneth** [processing/p5.js#3189]
#### Nature of issue?

- [ ] Found a bug
- [x] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [x] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Feature enhancement details:
I'm currently working on a new implementation of p5.XML as part of the discussions at #3170 and there are a few questions I need consensus on in order to carry on:

1. `listChildren()`
This one is pretty straightforward, the current implementation seems to be incorrect as each children node is separated by some kind of type node resulting in the function returning an array that looks like this: `["#text", "book", "#text", "book", "#text", "book", "#text"]` instead of `["book", "book", "book"]` which is what the documentation describes. If this is indeed a bug, the new implementation will fix it.

2. `getContent()`
I think the original intent for this is for it to be called on child nodes which only has text content and not nodes with nested child nodes of its own. However, it still does return all content of the specified node separated by a comma (incidentally, white space at the beginning and end of the tags are parsed as well). I might be getting the wrong idea but I don't feel this behavior is very useful, instead if we simply return `innerHTML` it should still take care of text only nodes or nested nodes, formatted nicely as XML string and in my opinion are more useful and clearer (although we probably need to trim the whitespace off the beginning and end here). 

3. `setAttribute()`
I don't quite understand the use for this check at https://github.com/processing/p5.js/blob/master/src/io/p5.XML.js#L716. Why is the existence of the attribute checked before setting it? The documentation doesn't really specify this is the behavior as well. It also means the user cannot set new attributes on the element.

4. Object properties
Current implementation has object property under p5.XML such as `children`, `name`, `attributes`, `parent` and `content`, these are not documented publicly. As such, my new implementation only has one property, intended to be private/undocumented as well, `DOM`. All the functions of p5.XML directly query or modify the DOM and so the DOM being the one source of truth. I'm assuming that since the other properties are undocumented they can be removed entirely. Is that fine? If not, some sort of getters or setters might be needed although support of that may not extend to IE or even Edge.

Everything else should more or less work the same without any breaking changes. Only major breaking changes will be the behavior of `getContent()` if we switch to return `innerHTML`. If anyone needs to see a test page, I can clean up mine and publish it somewhere, just let me know.

**Comment by Spongman** [comment]
The existing behavior you described in 1 & 2 wrt handling of text nodes sounds consistent with the way other XML Dom APIs behave - and indeed is in line with the semantics of xml itself.

I would recommend retaining compatibility with the existing code if possible.

**Comment by Spongman** [comment]
The existing behavior you described in 1 & 2 wrt handling of text nodes sounds consistent with the way other XML Dom APIs behave - and indeed is in line with the semantics of xml itself.

I would recommend retaining compatibility with the existing code if possible.

**Comment by limzykenneth** [comment]
For 1, from [here](https://developer.mozilla.org/en-US/docs/Web/API/Node/childNodes) and [here](https://stackoverflow.com/questions/6766721/why-are-there-text-nodes-in-my-xml-file) I understand that the `#text` node is a result of parsing new lines which if it is desired they are retained for compatibility with the XML specification then it should be fine. However, the documentation mentions 

> This is the same as looping through and calling getName() on each child element individually.

Which doesn't make sense as it isn't possible to call getName() and get the `#text` node. `getChildren()` also does not returns those `#text` node as they are not parsed into p5.XML object, meaning on a formatted twelve children p5.XML object, `listChildren()` returns a 25 element array while `getChildren()` returns a 12 elements array.

For 2, I'm not familiar with other implementation of XML DOM API, what I can think of that gets contents of a DOM element is just `innerHTML`. If the string returned from the existing implementation is some kind of convention, then it can be ok to retain it.

**Comment by limzykenneth** [comment]
Looking at it closer it seems I have overlooked that it is possible to mix text nodes and elements under the same parent. I'm not sure what is the best way to handle these without making the whole API too complex and just a clone of native API. 

If it is desired, we can retain existing behavior (but uses native API while returning the same things), and make the DOM property under p5.XML public so more advanced user can manipulate the DOM directly if we did not provide enough functionality for their use case.

**Comment by Spongman** [comment]
I think its a reasonable assumption that text nodes would only be leaf nodes, but XML closely follows the HTML semantics. Indeed an XHTML document is just that - a `body` element will often have text and element nodes intermingled, for example.

**Comment by Spongman** [comment]
I think its a reasonable assumption that text nodes would only be leaf nodes, but XML closely follows the HTML semantics. Indeed an XHTML document is just that - a `body` element will often have text and element nodes intermingled, for example.

**Comment by limzykenneth** [comment]
I'm going to keep existing public behaviour as to not introduce breaking changes and I don't know enough about how people are using this to suggest breaking changes. For now if necessary, the user can directly manipulate or query the DOM if they wish. We can come back to this topic some other time maybe.
