### ISSUE TITLE
dragOver() and drop() not working together?

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js#3208]
This is a bug I think I have found with p5.dom.js. Here is an example:

https://editor.p5js.org/icm/sketches/HJuRys8_X

If you drag a file over the canvas, it will turn red (according to how `dragOver()` should work. However, if I comment back in the `drop()` method for receiving the file, the `dragOver()` event ceases to function.)

```javascript
function setup() {
  var c = createCanvas(100, 100);
  background(200);
  textAlign(CENTER);
  text('drop image', width / 2, height / 2);
  c.dragOver(test);  // does not work if line below is added back in
  // c.drop(gotFile);
}

function test() {
  background(255,0,0);
}

function gotFile(file) {
  var img = createImg(file.data);
}
```

I went back and found that the code above works with `0.5.14`, but stops working with `0.5.15` (for both p5.js and p5.dom.js.)

(Addendum! The order seems to matter here. If I call `drop()` before `dragOver()`, `test()` is called but receiving the file breaks.)

**Comment by Spongman** [comment]
i think the calls to `stopPropagation()` in `p5.prototype.Element.drop()` are what's causing this issue. I also don't think they're necessary i think calling `preventDefault()` is sufficient to override the browser's default behavior - although browser differences may be a factor here. there's also an issue where the use of `attachListener` is causing the user-specified event handlers to be removed.

**Comment by Leiyufazhuangjia** [comment]
omg! same isuue!
i have juse post the it there https://discourse.processing.org/t/dragover-and-dragleave-do-not-work/4208

**Comment by CranShawdy** [comment]
Isn't this issue still present? For me it is but also this one seems closed, I'm not sure if it's meant to be, because in #3209 there isn't a solution to this, yet. Am I wrong?
