### ISSUE TITLE
Parser Throws Errors When it Finds Keywords in Regex

### ISSUE THREAD

**Issue by Lukalotr** [processing/p5.js#3214]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [x] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

(Wasn't sure exactly how to classify this)

#### Platform:

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 
Parser hangs or gets confused when it finds some language keywords inside a literal regular expression.
- p5.js version: 0.7.1
- Web browser and version: Google Chrome | 68.0.3440.106 (Official Build) (64-bit)
- Operating System: MacOSX 10.12.6
- Steps to reproduce this:
var x = /while/;
--> Uncaught SyntaxError: Unexpected token { (sketch: line 1)
var x = /for/;
--> Uncaught SyntaxError: Unexpected token { (sketch: line 1)

- Here is a temporary solution until the bug is fixed
var x = /whil\e/;

**Comment by meiamsome** [comment]
Hello, is this on the p5 web editor? I can reproduce it there and not elsewhere, so I'd suggest raising an issue on the web editor's repo instead: https://github.com/processing/p5.js-web-editor/issues

**Comment by Lukalotr** [comment]
You’re right, my mistake. Thanks for your advice!
