### ISSUE TITLE
Feature Request: Letter-spacing (tracking)

### ISSUE THREAD

**Issue by slowizzm** [processing/p5.js#3223]
Sorry if there is already an issue open/closed, but I was unable to find anything regarding letter-spacing (tracking). I would like to be able to adjust the letter-spacing, is there a way to do this already, if not, is this a possible feature that can be added to p5?

thanks

**Comment by lmccart** [comment]
I think this function is beyond the scope of the p5.js api (we try to keep as minimal as possible) but it could be a great starting point for an addon library. see the docs here for how to create an addon: https://github.com/processing/p5.js/blob/master/developer_docs/creating_libraries.md
