### ISSUE TITLE
DOMException error using p5.sound on Chrome 69

### ISSUE THREAD

**Issue by petlil** [processing/p5.js#3224]
The most recent version of Chrome (69) seems to have compatibility issues with some p5.sound objects. Chrome 68 does not exhibit the error.

The error reads:
"DOMException: Failed to set the 'buffer' property on 'ConvolverNode': Cannot set buffer to non-null after it has been already been set to a non-null buffer"

#### Nature of issue?

- [x] Found a bug

#### Most appropriate sub-area of p5.js?

- [x] Sound (p5.sound)

#### Which platform were you using when you encountered this?

- [x] Desktop/Laptop

#### Details about the bug: 

- p5.js version: 0.7.2
- Web browser and version: Chrome 69.0.3497.100 (Official Build)
- Operating System: Mac 10.13.1 (high sierra)
- Steps to reproduce this:
P5.sound example code for reverb encounters the error (several others also fail) on Chrome 69.
https://p5js.org/reference/#/p5.Reverb

Image of the error as it appears in the javascript developer console:
<img width="323" alt="screen shot 2018-09-20 at 5 00 14 pm" src="https://user-images.githubusercontent.com/43123543/45796833-acb01e00-bcf6-11e8-91d7-bb5a8bf409a1.png">

**Comment by dirkk0** [comment]
Possibly related to this:
https://github.com/processing/p5.js/issues/3090

**Comment by lmccart** [comment]
This issue was moved to processing/p5.js-sound#328
