### ISSUE TITLE
Feature request: Add Enable() and Disable() to p5.DOM

### ISSUE THREAD

**Issue by config2000** [processing/p5.js#3233]
[*] New feature request

#### Most appropriate sub-area of p5.js?

- [* ] - p5.DOM

#### Feature enhancement details:

P5.DOM has **Show()** and **Hide()** for the elements but lacking complimentary **Enable()** and **Disable()**
I am writing a front-end GUI that relies on certain elements being disabled according to user data entered. So the additional two functions would be welcome.

**Comment by SphaeriCactus** [comment]
Sounds good!

**Comment by lmccart** [comment]
you can do this like:
```js
var b = createButton("button");
b.elt.disabled = 'false';
```
