### ISSUE TITLE
confirm blendmodes are working as expected

### ISSUE THREAD

**Issue by yonghuming** [processing/p5.js#3234]
```
def setup():
    size(400, 400)
    global ballsx, ballsc, ballsy
    ballsx = []
    ballsy = []
    ballsc = []
    noStroke()
    blendMode(ADD)
def draw():
    global ballsx, ballsy, ballsc
    background(0)
    for i in range(len(ballsx)):
        fill(ballsc[i])
        ellipse(ballsx[i], ballsy[i], 100,100)
def mouseClicked():
    ballsx.append(mouseX)
    ballsy.append(mouseY)
    ballsc.append(color(random(255),random(255),random(255)))
```
![image](https://user-images.githubusercontent.com/435079/45927533-20f0f880-bf67-11e8-8a6f-e052eb740d16.png)
in processing.py, bend do not affect backgound, but in p5.js i got
![image](https://user-images.githubusercontent.com/435079/45927537-47169880-bf67-11e8-8408-ca7a764f2174.png)
or this if i make ellipse move
![image](https://user-images.githubusercontent.com/435079/45927541-5b5a9580-bf67-11e8-8a81-36275ef179e1.png)
i wrote equle code with python mode in p5.js
```
var ballsx;
var ballsy;
var ballsc;

function setup(){
    createCanvas(windowWidth, windowHeight);
    ballsx = [];
    ballsy = [];
    ballsc = [];
    blendMode(ADD);

}
function draw(){
    background(0);
    // console.log(ballsx.length);

    for(var i=0;i<ballsx.length;i++){
        // fill(255);
        // ballsx[i] += 1;
        ballsy[i] += 1;
        fill(ballsc[i]);
        ellipse(ballsx[i], ballsy[i], 100, 100);
    }
}
function mouseClicked(fxn){
    ballsx.push(mouseX);
    ballsy.push(mouseY);
    ballsc.push(color(random(255),random(255),random(255)));
    
}
```

**Comment by yonghuming** [comment]
seems in p5 
![image](https://user-images.githubusercontent.com/435079/45927576-d6bc4700-bf67-11e8-810f-4b4e6cb5cae5.png)

**Comment by yonghuming** [comment]
https://editor.p5js.org/yonghuming/sketches/HyGfjlBtQ js code is here

**Comment by lmccart** [comment]
Our goal is not to have parity with processing.py, but it would be good to confirm that blendmode words align with processing, or built-in browser support. if these sets don't align (I think I recall that they don't), we should be clear about this.

**Comment by lmccart** [comment]
here's the blendmode page for reference: https://p5js.org/reference/#/p5/blendMode

**Comment by vipulrawat** [comment]
Ok. It looks like there is an implementation difference in *ADD* `blendMode()`  between processing/processing.py and p5.js.

In p5.js *ADD* just adds two pixels that's why results to white everytime while in processing its 
`C = min(A*factor + B, 255)`
What should be better changing the documentation or changing the implementation to sync. with processing?

**Comment by lmccart** [comment]
I think the documentation "ADD - sum of A and B" is correct then, right? In this case, no need to make any further changes, this can be closed. Thanks for looking into it.

**Comment by vipulrawat** [comment]
Ok. I am closing this issue now.
