### ISSUE TITLE
"Uncaught Error: Error creating webgl context"

### ISSUE THREAD

**Issue by lmccart** [processing/p5.js#3235]
#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: all (tested with 0.6.1 and 0.7.2)
- Web browser and version: chrome 69.0.3497.100
- Operating System: osx 10.13.6
- Steps to reproduce this:
All webgl examples seem to have stopped working since chrome browser was updated. I've tried running an example [on the website](https://p5js.org/examples/3d-geometries.html) as well as [in the editor](https://editor.p5js.org/p5/sketches/By-X4gy7um) and locally. Seems to run fine in safari.
I get the error "Uncaught Error: Error creating webgl context"

```javascript
function setup() {
  createCanvas(200, 200, WEBGL);
}
```

**Comment by meiamsome** [comment]
Sounds like your chrome might have disabled hardware acceleration. Does this page work for you: https://get.webgl.org/ ? If not, check hardware acceleration option under settings -> advanced -> system settings

**Comment by lmccart** [comment]
oh! you're right, thank you! sorry about that, all is well :)

**Comment by kjhollen** [comment]
whew 😅
