### ISSUE TITLE
Contributing Docs - Issue Assignment

### ISSUE THREAD

**Issue by justinsunho** [processing/p5.js#3239]
#### Nature of issue?

- [ ] Found a bug
- [x] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [x] Developer Docs

#### Feature enhancement details:
The contribution docs mention to 'assign an issue to yourself'. That is not currently possible. New instructions should be written so that new, future collaborators know whether to ask @lmccart for issue assignment, for access to collaborate, or if there is a 'process' to do so.

Not sure if I missed instructions on this in the `dev-docs` or in past issues (tried my darndest to find anyone mention issue assignment), but either way, I believe it wouldn't hurt to have even clearer instructions especially for those who are newer to open source/ collaborating on `p5.js`

**Comment by lmccart** [comment]
thanks @justinsunho I agree this could be much clearer. while the docs could use a general rewrite to make things as clear as possible, a small step in the meantime would be to replace the line that says "assign an issue to yourself" with "comment on the issue that you plan to work on it"

**Comment by justinsunho** [comment]
I'll assign this issue to myself then!

**Comment by lmccart** [comment]
fixed with https://github.com/processing/p5.js/pull/3323

**Comment by lmccart** [comment]
thanks @justinsunho! add yourself as a [contributor on the readme page](https://github.com/processing/p5.js/blob/master/README.md#contributors) if you haven't already. instructions [here](https://github.com/processing/p5.js/issues/2309)
