### ISSUE TITLE
Feature Request: Return heading between two vectors with v1.heading(v2)

### ISSUE THREAD

**Issue by PhilipRL** [processing/p5.js#3240]
#### Nature of issue?

- [ ] Found a bug
- [x] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [x] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug: 

- p5.js version: 0.7.2

#### Feature enhancement details:
I would find it useful to be able to use heading() to calculate the heading between two vectors by passing another vector as an argument - just like dist() is used to find a distance between two vectors.

If v1 and v2 are vectors, an example would be:
`let a1 = v1.heading(v2);`

Today I solve this by using:
`let a1 = v1.copy().sub(v2).heading();`

Please observe that this is NOT equal to `v1.angleBetween(v2);`!

**Comment by pakosaldanaort** [comment]
@lmccart @PhilipRL  I will work on this  Existing feature enhancement

**Comment by lmccart** [comment]
I'm not seeing a lot of interest in this feature, and we don't have a clear explanation of how it [expands access](https://github.com/processing/p5.js/blob/main/contributor_docs/access.md), so I will close this for now. If an access statement can be added to the issue request, please feel welcome to reopen.
