### ISSUE TITLE
webgl: strange angleMode/resize/scaling issue

### ISSUE THREAD

**Issue by Spongman** [processing/p5.js#3246]
0.7.2 webgl: https://codepen.io/Spongman/pen/pxggxg?editors=0010

```javascript
function setup() {
  createCanvas(windowWidth, windowHeight, WEBGL);
  stroke(255);
  angleMode(DEGREES);
}

function windowResized() {
  resizeCanvas(windowWidth, windowHeight);
}

function draw() {
  background(0);
  line(0, 0, 100, 50);
}
```

initially looks like this:
![image](https://user-images.githubusercontent.com/1088194/46380661-064e0c00-c658-11e8-8495-1f7111466fa9.png)

but resizing the window, it redraws like this:
![image](https://user-images.githubusercontent.com/1088194/46380682-16fe8200-c658-11e8-93c1-1aec3e7b0cd1.png)

it doesn't repro if you take out the `angleMode(DEGREES);` line, or change it to `RADIANS` instead. 😕

**Comment by sanketsingh24** [comment]
I think this is due to the fact that `_curCamera` uses radians to compute FOV properties and there is no condition when `this._angleMode` is degrees. Shall I send a PR to fix this?

**Comment by sanketsingh24** [comment]
@Spongman Yes you are right. I also think that.
