### ISSUE TITLE
Suggestion: midiToString

### ISSUE THREAD

**Issue by EthanHermsey** [processing/p5.js#3252]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [x] New feature suggestion

#### Most appropriate sub-area of p5.js?

- [x] Sound

#### New feature details:

Accepts midi, returns note + octave as string. 

```
p5.prototype.midiToString = function(m){
	let stringNotes = ["C", "C#", "D", "D#", "E", "F", "F#", "G", "G#","A", "A#", "B"];
	return stringNotes[m%12] + Math.floor((m- 12) / 12);
}
```

**Comment by lmccart** [comment]
I think this function is beyond the scope of the p5.js api (we try to keep as minimal as possible) but it could be a great starting point for an addon library. see the docs here for how to create an addon: https://github.com/processing/p5.js/blob/master/developer_docs/creating_libraries.md
