### ISSUE TITLE
The feature email address listed on the website is down

### ISSUE THREAD

**Issue by dfsp-spirit** [processing/p5.js#3253]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other: Website

#### Details about the bug: 

- The website lists the email address (feature@p5js.org) where people should can send their work to be featured. but the address is rejected by the mail server at p5js.org. 

See https://p5js.org/community/, section 'Create' or search the page content for 'feature@p5js.org' using the search function of your browser (usually CTRL+f) to find the address on the page. Send a test email to the address to see that it's broken.

NOTE: I know the bug template text here asks you to post stuff like this on the forums, but they are closed for registration, so there is no way to do that.

**Comment by lmccart** [comment]
thanks @dfsp-spirit I will update this.
btw the [forum](https://discourse.processing.org/) should be open for registration.. can you tell me the error you're seeing? or is there a leftover link to the old archived forum somewhere?

**Comment by dfsp-spirit** [comment]
Hi @lmccart,

yes, the link to the old forum is displayed when you click on the _New Issue_ link here at github. It says:

> PLEASE NOTE: The github issues are for bugs and feature requests for the p5.js library itself. If you have a general question or bug programming with p5.js please post it in the p5.js forum: https://forum.processing.org/two/.

And there it says:

> We are about to switch to a new forum software. Until then we have removed the registration on this forum.

**Comment by lmccart** [comment]
aha thank you. I will update this

**Comment by lmccart** [comment]
This issue was moved to processing/p5.js-website#267
