### ISSUE TITLE
webgl: iOS12 per-pixel lighting is broken

### ISSUE THREAD

**Issue by Spongman** [processing/p5.js#3258]
0.6.1->0.7.2

https://codepen.io/Spongman/pen/MPjGbq?editors=0010

i have only tried this on a single iOS12 device (an iPhone 6S), but on that device the per-pixel lighting is broken. it works fine on everything else i have tried it on, mac, windows, linux, android.

this may be a regresseion in iOS12 itself. i don't have access to other devices with different iOS versions.

![image](https://user-images.githubusercontent.com/1088194/46574532-a60de180-c959-11e8-9f38-5880eef78757.png)

**Comment by Spongman** [comment]
This still happens in 0.8.0. I think it may be a z resolution thing.

**Comment by stalgiag** [comment]
Closing in favor of same issue with consolidated reporting in #4023
