### ISSUE TITLE
https://p5js.org/reference/ is not okay?

### ISSUE THREAD

**Issue by nazhenhuiyi** [processing/p5.js#3262]
![image](https://user-images.githubusercontent.com/11942909/46608863-b29c6080-cb38-11e8-86ee-4a745399ed6c.png)

somebody can help me?

**Comment by LanceFun** [comment]
For me, the reference page works.  Are you still having this problem?  My first guess is the error was caused by loading the page when a new version of the reference was being built.

**Comment by nazhenhuiyi** [comment]
oh, I can open this with chrome stealth mode or firefox. it's weird, but thank you @LanceFun .

**Comment by Spongman** [comment]
Sounds like a bad chrome extension.
