### ISSUE TITLE
Print function opens print dialog even with a defined var if there is no setup/draw

### ISSUE THREAD

**Issue by lee2sman** [processing/p5.js#3264]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [x] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

Hello, I am posting about an old bug reported [here](https://github.com/processing/p5.js/issues/2765) where the print command triggers the system to print. Past issues state that this should occur when you are attempting to print an undefined var, but it is happening to me even when I am passing a set variable. Tested on Firefox, Chrome and Safari. I believe this is because setup/draw has not run. Is this a bug or should this be documented somewhere?
 
Minimal version showing this [here](https://editor.p5js.org/2sman/sketches/r1hYEh557).

- p5.js version: 
- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

**Comment by limzykenneth** [comment]
This is expected functionality, `print()` does not have its functionality overwritten before p5 is initialized, ie when `setup()` is defined and being called. It is the same as all the constants and functions in p5 being undefined if `setup()` isn't present or before it is called.

**Comment by lee2sman** [comment]
I see. Thanks. 
I wonder if there's a way to give some warning on the console that can help identify this.

**Comment by limzykenneth** [comment]
The FES can potentially handle this but I wonder if it would be desired because if you are using instance mode and have a `print()` outside of your sketch meant to bring up the print dialog, it would still warn about it. Also the message thrown by FES on similar cases are usually meant to handle silent or hard to decipher error messages whereas in this case the print dialog serves as a pretty obvious indicator of what's going on.

**Comment by lee2sman** [comment]
What do you think @almchung

**Comment by lmccart** [comment]
I think this one is as clear as we can make it for now. We can revisit next time we work on the FES.
