### ISSUE TITLE
change anchor point of a 3D primitive.

### ISSUE THREAD

**Issue by pbouigue** [processing/p5.js#3266]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

Hey.

I was wondering if there was any way to change the anchor point of the plane in a 3D mode. By default, it's set to center.
like the rectMode(CENTER)
the planeMode(CENTER)
could be an idea !

Have a nice day!

**Comment by hackertron** [comment]
is it still open ?

**Comment by stalgiag** [comment]
Hi sorry for the delay! I think this is definitely an interesting idea but it begins to challenge some fundamental ambiguities in WEBGL mode. First,[ here is an example](https://editor.p5js.org/stalgiag/sketches/ZW4aFnP9e) that more or less accomplishes what you are asking for. It switches between center anchor and corner anchor on click.

To return to the ambiguities of WEBGL, the addition of a third dimensions makes it less clear what a 'CORNER' is. With some of the basic shapes this may be simple but it can become very unclear with certain conditions. For these reasons, I think it is better to rely on the `translate()` approach to shifting the pivot which is shown in the above example. This is the approach taken in all examples and it is more inline with use of webgl in other libraries and contexts. That way the user can begin to make their own interpretations for what constitutes a CENTER or CORNER. While this may be a bit more difficult than the `rectMode(CENTER)` present in 2D mode, we are typically working from the assumption that users have a bit more experience by the time that they start experimenting with 3D mode.

I am closing for now, but if there is more interest feel free to post here and I'll happily reopen. Thank you!
