### ISSUE TITLE
typescript types issue - Should be HTMLMediaElement

### ISSUE THREAD

**Issue by jeremychone** [processing/p5.js#3269]
#### Nature of issue?

- [X] Found a bug

#### Most appropriate sub-area of p5.js?

- [X] TYPES

#### Details about the bug: 

- p5.js version: 0.7.2 (@types/p5 0.7.0)

#### Issue
Not sure this is the right place for p5 typescript bugs, but this is a probably bug with @types/p5

It seems it should `MediaElement` does not exist (but specified in the type) and `HTMLMediaElement` is the one to use. 

```
node_modules/@types/p5/src/webgl/material.d.ts:62:11 - error TS2304: Cannot find name 'MediaElement'.

material.d.ts
![image](https://user-images.githubusercontent.com/74671/46920356-fe6c6100-cfa1-11e8-94fa-2da7134f5e31.png)


62         | MediaElement
             ~~~~~~~~~~~~
```
![image](https://user-images.githubusercontent.com/74671/46920460-696a6780-cfa3-11e8-82c9-5bd847a6ced0.png)

Changing to HTMLMediaElement make the compile work (now, I am not sure if this is the wrong thing to do, and a MediaElement should exist in the default dom types)

![image](https://user-images.githubusercontent.com/74671/46920363-117f3100-cfa2-11e8-867c-7cf69729517c.png)

**Comment by lmccart** [comment]
This is referring to the object type "p5.MediaElement", which is different than HTMLMediaElement. 
However, the typescript definitions are independently maintained, so I would suggest posting this over [here](https://github.com/p5-types/p5.ts).
