### ISSUE TITLE
Using AUTO with p5.element.size() sets width or height to 0, rather than "auto"

### ISSUE THREAD

**Issue by catarak** [processing/p5.js#3270]
#### Nature of issue?

- [X] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [X] Other (specify if possible) DOM

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [X] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version:  0.7.2
- Web browser and version:  Chrome 69.0.3497.100
- Operating System:  MacOSX 10.13.4
- Steps to reproduce this:

The image is rendering with no height, with the height set to `AUTO` in the following code:
```JS
function setup() {
  noCanvas();
  const url = 'https://dog.ceo/api/breeds/image/random';
  loadJSON(url, processData);
}

function processData(data) {
  print(data.message);
  let img = createImg(data.message);
  img.size(500, AUTO);
}
```
If I look at the DOM, the `<img>` was appended with a` height` of `"0"`:
<img width="540" alt="screen shot 2018-10-16 at 3 20 46 pm" src="https://user-images.githubusercontent.com/6063380/47041564-23ee9b80-d157-11e8-8774-eddbd767b52b.png">
If I manually change the `height` to `"auto"` by editing the DOM, it works as expected.

I also tried changing `AUTO` to the String `"auto"`, and I see the same behavior.

**Comment by Ajayneethikannan** [comment]
I would like to work on this issue !

**Comment by Ajayneethikannan** [comment]
I tried to fix the issue and this is what I came up with:
Whenever we use the createImg function to create the image with the given data, the corresponding height and width of the image are initially set to 0, before the image has finished loading by the browser. 
So when we attempt to calculate the automatic height or width, the calculation results in NaN.

**Comment by Ajayneethikannan** [comment]
As I was going through the docs, I noticed that createImg function had a callback parameter,called after the image has loaded , and I believe that the correct way to call the  methods  on the image object would be to call it inside the callback function.
so changing this code : 

``let img = createImg(data.message);
 img.size(500, AUTO);``

to:

`let img = createImg(data.message,  () => img.size(500, AUTO));`

would resolve the size issue.

@catarak , please verify if this is a sufficient solution , 
thank you !

**Comment by lmccart** [comment]
@Ajayneethikannan this is the correct solution. so the code is working properly. however, it would be helpful to have some documentation to make this clear. I would suggest we update the [documentation for the `AUTO` constant](https://p5js.org/reference/#/p5/auto), right now it is very empty. we could include your code above as an example on that page of how to use it.

**Comment by Ajayneethikannan** [comment]
Sounds great to me !

**Comment by lmccart** [comment]
fixed with https://github.com/processing/p5.js/pull/3481
