### ISSUE TITLE
Set textStyle() both to Italic and Bold

### ISSUE THREAD

**Issue by mikima** [processing/p5.js#3271]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [x] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [x] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.7.2
- Web browser and version: Chrome 69.0.3497.100
- Operating System: MacOSX

Maybe is something i just missed, but I don't find a way to set the font style to bold italic in P5.

In the documentation (https://p5js.org/reference/#/p5/textStyle) says it is possible to set the style to NORMAL, ITALIC, or BOLD.

If not available, would it be possible to add a BOLDITALIC parameter to P5.js?

**Comment by TanviKumar** [comment]
Willing to take this up if this feature is to be added!

**Comment by L05** [comment]
> Willing to take this up if this feature is to be added!

Hey sorry @TanviKumar! I didn't see your reply before I had self-assigned. Did you still want to take this on? Let me know when you get a chance.

**Comment by TanviKumar** [comment]
@L05 I'll take this up, thanks!

**Comment by lmccart** [comment]
fixed with #3301 thanks @TanviKumar
