### ISSUE TITLE
table.getObject() edit proposal

### ISSUE THREAD

**Issue by mikima** [processing/p5.js#3277]
In `p5.table` we have a `getObject()` function. When called, it creates an object with a property for each line having as property name the row index:
```
{
  "0": {"Title1":"value1", "Title2":"value2"},
  "1": {"Title1":"value1", "Title2":"value2"},
  ...
}
```

However, in most of the other libraries (like as d3.js) CSV are parsed as array containing objects:
```
{
 values: [
    {"Title1":"value1", "Title2":"value2"},
    {"Title1":"value1", "Title2":"value2"},
  ...
}
```
This would be more meaningful in my opinion, since in this way we can use all the vanilla array operators provided by JS.

It would be also more consistent and would provide less errors. Finally, it allows to add other properties to the table object as metadata.

I know it would change a behaviour present in previous versions of P5 but i think it worths it.

**Comment by lmccart** [comment]
Thanks @mikima. I'm not seeing a lot of energy around this proposal, so I'd like to close it for now. We can revisit in the future if there is greater need for it.
