### ISSUE TITLE
loadPixels() does not work for video elements

### ISSUE THREAD

**Issue by catarak** [processing/p5.js#3278]
#### Nature of issue?

- [X] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [X] Other (specify if possible) DOM: Video

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [X] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version:  0.7.2
- Web browser and version:  Chrome 69.0.3497.100
- Operating System:  Mac OSX 10.13.4
- Steps to reproduce this:

I noticed that [this code](https://github.com/CodingTrain/website/tree/master/Tutorials/P5JS/p5.js_video/11.4_p5.js_brightness_mirror) (it's Coding Train example) doesn't work in 0.7.2, but does work in 0.6.1.

When running loadPixels(), video.pixels is still empty. I tried this for both a video capture and loading in a video from a .mov file.

loadPixels() and pixels does work for images, however.

using video.get(x, y) returns a garbage value.

**Comment by Spongman** [comment]
i believe this is fixed in #3221

**Comment by catarak** [comment]
@Spongman yeah, seems like it's the same bug!

**Comment by togergo** [comment]
If I'm right, the video loadPixels push the data into a global (window.)pixels array, if you don't do anything, the just the loadPixels calls, the video with appear on canvas. So, if you work with canvas pixels, you can modify them pixels[index] = doSomething(pixels[index]) .. etc

I'm totally new, is it a workaround?

**Comment by kylemcdonald** [comment]
I can confirm this bug, and I can narrow it down a little: I have examples that use `loadPixels()` that work in 0.7.1 but not 0.7.2.

**Comment by jameshujun** [comment]
Just to confirm kylemcdonald's comment, same bug on my project: Video capture loadPixels() works on 0.7.1 on Firefox but not on 0.7.2. But on Chrome both 0.7.1 and 0.7.2 works.

**Comment by Leiyufazhuangjia** [comment]
I confirm this , I met the same problem when using video.loadPixels(),it gave me empty thing,and i can not get the red green blue alpha value of video,pixels

**Comment by Yaniki** [comment]
Confirmed: loadPixels(); doesn't work with video capture under p5js 0.7.2 (FireFox 63.0.3 64bit, Mojave).

**Comment by bengrosser** [comment]
I'm also seeing this. Is there an ETA on this bug? Was hoping to switch to p5.js and the p5js editor for teaching this spring (have used Processing in past), but not being able to access the video pixels array is probably a showstopper for me. Or is there a workaround to get the data? Looks to me like the video.pixels array is just empty.
