### ISSUE TITLE
Line 20 Comment has a typo

### ISSUE THREAD

**Issue by kendalled** [processing/p5.js#3279]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other (Although in a comment, confused me when reading the p5 dom code)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

Not much to say, libary is library. Love p5 :+1:

**Comment by kendalled** [comment]
p5.dom.js - Line 20

**Comment by montoyamoraga** [comment]
fixed by pull request #3276
