### ISSUE TITLE
p5.sound loadSound() doesn't work on Mobile safari

### ISSUE THREAD

**Issue by jeffro-** [processing/p5.js#328]
I have code with loadSound() that works when I load it up on Safari from my MacBook but for some reason it doesn't work when I load it from my iPhone. Any ideas what's going on? Here's what I've built http://jeffro.nfshost.com you can view the code by right clicking on the page and hitting view source.

**Comment by hems** [comment]
@therewasaguy i'm having issues with loading and playing sound on mobile safari //=

my sketch [is super simple](http://pastebin.com/raw.php?i=5DgzZatF), just uses sketch.loadSound, sound.rate / sound.play and p5.FFT.

It worked perfectly on chrome android, but on iOS no chance, using iOS 8.

Any ideas? i'm using the latest version from the website ( /*! v0.4.17 October 13, 2015 */ )

**Comment by therewasaguy** [comment]
@hems thanks, looking into it. p5.sound has a separate repo so let's move the discussion over here: https://github.com/processing/p5.js-sound/issues/74

**Comment by hems** [comment]
@therewasaguy okay, thanks

**Comment by DArshit94** [comment]
@therewasaguy  does this api support for recording sound using Safari browser ?
