### ISSUE TITLE
Mail address in community page doesn't work 

### ISSUE THREAD

**Issue by reona396** [processing/p5.js#3280]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other (p5.js web page)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

I sent mail to "feature@p5js.org", I received error mail immediately.
This address is written in [p5\.js \| community](https://p5js.org/community/) > "Create."

**Comment by lmccart** [comment]
thanks for reporting. the correct address should be hello@p5js.org

**Comment by lmccart** [comment]
This issue was moved to processing/p5.js-website#273
