### ISSUE TITLE
Placeholder in createInput

### ISSUE THREAD

**Issue by Emil0hman** [processing/p5.js#3281]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [x] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [x] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.7.2
- Web browser and version: Chrome 69.0.3497.100, 64-bit
- Operating System: MacOSX
- Steps to reproduce this:

#### New feature details:
I am working on a project where i need to create an input with a placeholder, i.e.
`<input type="text" placeholder="X"></input>`
However, as far as the internet has told me, there is no way to do this. It would be nice if an argument could be added to the `createInput()`. Then the syntax could look like:
`createInput([value], [placeholder], [type])`.

**Comment by Spongman** [comment]
one way to do this is:
```javascript
createInput('value').attribute('placeholder', 'X');
```

**Comment by digitalfrost** [comment]
Is placeholder a custom attribute or are you trying to do this:

`<input type="text" value="placeholder">`

**Comment by limzykenneth** [comment]
@digitalfrost `placeholder` is an existing attribute for input type of `text` (it shows a greyed out placeholder text when the field is empty)

@TanviKumar I think the method suggested by @Spongman is sufficient in this case, for me at least.

**Comment by digitalfrost** [comment]
@limzykenneth  - oh yes html5 - duh !

**Comment by Pratyush21706** [comment]
shittttttttttttttttttt!!!!!!!!!!!!!
