### ISSUE TITLE
random() passed an array of vectors returns a string

### ISSUE THREAD

**Issue by drusepth** [processing/p5.js#3282]
#### Nature of issue?

- [x] Found a bug

#### Most appropriate sub-area of p5.js?

- [x] Utilities

#### Which platform were you using when you encountered this?

- [x] Desktop/Laptop

#### Details about the bug: 

- p5.js version: 0.6.1
- Web browser and version: Chrome 70
- Operating System: Windows 10

Steps to reproduce this:

* Open a console on a page with p5.js
* Execute `result = random(createVector(1, 2), createVector(3, 4))`.
* Observe the output of `result` is a string, rather than one of the vectors.

```
 > result = random(createVector(1, 2), createVector(3, 4))
=> "NaNp5.Vector Object : [1, 2, 0]"
```

Based on https://github.com/processing/p5.js/pull/1456, I would expect the result to be a random choice from the options passed into `random`. 

I am also unsure why it is prefixed with a `NaN`, but that seems like a byproduct of something wrong as well.

**Comment by Spongman** [comment]
Try `random([ ... ])`

**Comment by drusepth** [comment]
Whoopsies. Thanks!

```
 > random([createVector(1, 2, 3), createVector(4, 5, 6)])
=> d.Vector {p5: e, x: 4, y: 5, z: 6}
```

**Comment by Spongman** [comment]
Actually, can you reopen this?  I think the string you’re seeing is still an issue.

**Comment by drusepth** [comment]
I can reopen it, but I haven't used p5 in several months so I'm not sure if it's still reproducible. You should be able to reproduce with the above snippet, though.

**Comment by sixhat** [comment]
I've read the random function code and this is still an issue. The issue is when you pass an array as the first element and then a second argument to the random function. The code doesn't have a proper use case for this and returns garbage.  Also the random function doesn't test for the validity of the arguments, just assumes everything was passed correctly. Maybe some refactoring would make it behave more consistently. 

You can see a minimal example of this problem in https://codepen.io/sixhat/pen/axjBvE with P5js v0.8.0. 

**Possible solutions:** 

* we could return an element of the array if the first argument is an array independently of the existence of more arguments to the function... 
* or we could take advantage of _random([...], N)_ to implement a random picker like "from this array choose N values at random and return them in a new array (allowing repetition of elements". 


Both solutions are easy to implement but I think a decision as to be made to what is best.

**Comment by lmccart** [comment]
I think this is a case for the friendly error system to help us. According to the [reference entry](https://p5js.org/reference/#/p5/random) (array, array) or (array, number) are not valid inputs of this function. There are many different ways to interpret a range of unexpected inputs, but this function already has a few different signatures / ways to use it, so I would err on the side of keeping things simple, and alerting the user if they don't match any of the supported parameter inputs.

**Comment by Spongman** [comment]
Indeed, I think `random` could just call `validateParameters` and this case _should_ be automatically handled.

**Comment by drusepth** [comment]
I think showing an error letting a coder know `(array, array)` isn't a valid input to the function technically works (and would probably lead someone like OP down the right path of using the function different/correctly). 

However, is it correct to for p5-using coders to mentally internalize vectors as arrays? While using them I always treated them like coordinate objects (x|y or x|y|z) -- so I'd expect passing them into functions to treat them as objects (e.g. `{x: 5, y: 7, z: 1}` since `vector.x`, `vector.y`, etc work). 

Treating `random([createVector(1, 2, 3), createVector(4, 5, 6)])` as `random([array, array])` rather than `random([object, object])` gives me pause, but if vectors _are_ actually just arrays I suppose that makes sense.

As an example, I just find it odd that the following snippet works, whereas swapping the literal objects for vectors doesn't. I understand this is probably just because vectors are probably internally treated as arrays, I just find it odd as a consumer of p5 because it doesn't jive with my mental model of what a vector is. Obviously, I also concede I'm likely to just be _wrong_ in how I understand vectors are meant to be used -- just wanted to provide my feedback since I opened this issue originally. :)

```
 > random([{x: 5, y: 4}, {x: 6, y: 9}])
=> {x: 6, y: 9}
```

**Comment by bomoko** [comment]
I've added FES to the random() in the PR above, which addresses the immediate need to notify the dev.

My own thinking on this is that random's functionality is already quite broad - I'd vote/prefer more specific random functions (a whole family of 'em) for any proposed extensions.

**Comment by lmccart** [comment]
thanks @bomoko, I think #3915 sufficiently addresses this specific issue
