### ISSUE TITLE
Addition to reference page for loadFont()

### ISSUE THREAD

**Issue by fergfluff** [processing/p5.js#3283]
#### Nature of issue?

- [ ] Found a bug
- [ x] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [x ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 
- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

#### Feature enhancement details:

Hello! 

I'm suggesting an addition to the loadFont() reference page's explanation text. 

The opening paragraph should say that if you are using your own font file, to upload that font file to the p5 online editor. Otherwise the example code below will not run, since it can't reference the actual file. 

Right now it doesn't mention this. An undergrad student (in Dan Shiffman's online Code! class that I'm TAing) wasn't able to get her font to work because she used the example code but didn't know to upload her own font.

Dan suggested putting an issue here in the p5 library because that's where the reference content is found.

I will attempt to make this content change to the p5 source code. Thanks to Dan who showed me how to do this!

Best,
Elizabeth

**Comment by Spongman** [comment]
is the p5.js library documentation going to assume that everyone is using the p5 web editor going forward?

the docs already include the sentence "The path to the font should be relative to the HTML file that links in your sketch." which covers the general case here.

**Comment by lmccart** [comment]
I think it's reasonable to add this in order to make the tools place nice together, but we should perhaps add to the beginning of that paragraph, "If you are using the [p5.js web editor](https://editor.p5js.org), "

**Comment by dhowe** [comment]
> is the p5.js library documentation going to assume that everyone is using the p5 web editor going forward?
suggestion above sounds reasonable, but I think that we should avoid this general assumption

**Comment by lmccart** [comment]
@dhowe I agree. I guess I'm thinking there could be some middle ground where we don't assume anyone is using it but do provide some scaffolding for those that are

**Comment by digitalfrost** [comment]
The  [reference page](https://p5js.org/reference/#/p5/loadFont) for **loadFont()**

**Comment by digitalfrost** [comment]
If included this should not be in the opening paragraph but in the description.

Personally I agree with @Spongman and do not think that the p5.js reference should be “littered” with references to the p5 web editor.

There should either be a specific section in the documentation about using p5.js with online code editors such as the p5 web editor, CodePen, JSFiddle, et al.

Or this should be part of the p5 web editor documentation in an FAQ section.

**Comment by lmccart** [comment]
I agree it makes sense to separate the editor from the library, and I think the common gotcha FAQ in [this issue](https://github.com/processing/p5.js-web-editor/issues/748) is a good start. I'll close this one.
