### ISSUE TITLE
the problem that cant add event

### ISSUE THREAD

**Issue by tneotc** [processing/p5.js#3284]
[issue.txt](https://github.com/processing/p5.js/files/2517610/issue.txt)
[issue.txt](https://github.com/processing/p5.js/files/2517612/issue.txt)

#### Nature of issue?

- [√ ] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ √] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [√ ] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: the latest one
- Web browser and version: edge and firefox
- Operating System: windows10
- Steps to reproduce this:

```js
function setup()
{
	var canvas = createCanvas(1200,600);
	canvas.position(300,200);
}
function draw()
{
	background(150);
	var age1 = arc(600, 300, 500, 500, 0, PI + QUARTER_PI, PIE)
	fill(255, 204, 100);
	age1.mouseover(ps);
}
ps()
{
	fill(255,0,0);
}
```
the shape object can  not use event and the shape lost color.
[issue.txt](https://github.com/processing/p5.js/files/2517607/issue.txt)

#### Feature enhancement details:
no

#### New feature details:
no

**Comment by digitalfrost** [comment]
@tneotc 
There is no **mouseover()** function in the core p5.js library
The available functions are listed [here](https://p5js.org/reference) . Please refer to the **events** section
This [example](https://p5js.org/examples/hello-p5-interactivity-1.html) should give you an idea as to how to solve your problem.

The p5.dom library has a **mouseOver()**  function : https://p5js.org/reference/#/p5.Element/mouseOver
Refer to this [page](https://p5js.org/libraries/#using-a-library) for how to use a library that extends the p5.js core functionality

**Comment by tneotc** [comment]
> @tneotc
> There is no **mouseover()** function in the core p5.js library
> The available functions are listed [here](https://p5js.org/reference) . Please refer to the **events** section
> This [example](https://p5js.org/examples/hello-p5-interactivity-1.html) should give you an idea as to how to solve your problem.
> 
> The p5.dom library has a **mouseOver()** function : https://p5js.org/reference/#/p5.Element/mouseOver
> Refer to this [page](https://p5js.org/libraries/#using-a-library) for how to use a library that extends the p5.js core functionality

so if my shape have different part,how can the mouseOver() do different behavior in different part?Looks like the shape is not an object? Only I create different canvas?

**Comment by lmccart** [comment]
thanks @tneotc please post this question on the [forum](https://discourse.processing.org) for more help.
