### ISSUE TITLE
Typo in loadFont() reference

### ISSUE THREAD

**Issue by digitalfrost** [processing/p5.js#3290]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [X] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details 

There is a typo in the description section of the loadFont() [reference](https://p5js.org/reference/#/p5/loadFont)  :

> Loading **_an_** from a URL or other remote location may be blocked due to your browser's built-in security.

**Comment by lmccart** [comment]
fixed with https://github.com/processing/p5.js/pull/3291
