### ISSUE TITLE
Some Materials not working on iPhone in 3D

### ISSUE THREAD

**Issue by sjscotti** [processing/p5.js#3293]
#### Nature of issue?

- [XX ] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ XX] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ XX] Mobile/Tablet (touch devices)
- [ ] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version:  checked 0.5.11 and 0.7.2
- Web browser and version: Safari on iPhone 
- Operating System: IOS 12.0.1 
- Steps to reproduce this:
On newer iPhones (8 and greater), the materials and shading in examples:
https://p5js.org/examples/3d-multiple-lights.html 2
https://p5js.org/examples/3d-materials.html 1
https://p5js.org/examples/3d-textures.html 1
are not showing up. It appears that when texture, ambientMaterial, or specularMaterial are used, the shaded objects do not show up. It appears to be the hardware, not the IOS version. The latest versions iOS 12.0.1 and iOS 12.1 on an iPhone 8+ definitely has this problem, and I have heard from colleagues that iPhone X also has the same issue
It does not occur with iPhone 7+ with iOS 12.0 or 12.0.1

**Comment by danielemichieletto** [comment]
I confirm the bug, also with firefox chrome in iOS 12.1.2

**Comment by odvnpx** [comment]
Confirm same issue on iOS 12.1.4.

**Comment by stalgiag** [comment]
Hi @danielemichieletto & @odvnpx, do you have the same hardware as sjscotti (Iphone 8+ or Iphone X)? Trying to narrow this down and want to determine if it is hardware as @sjscotti suggested. If it is hardware, then maybe it's connected to the [A11 Chip](https://en.wikipedia.org/wiki/Apple_A11)?

**Comment by odvnpx** [comment]
@stalgiag hey, my device is an iPhone XR.

**Comment by danielemichieletto** [comment]
@stalgiag <https://github.com/stalgiag> hey, my device is an iPhone 8 and iphone 6s

**Comment by danielemichieletto** [comment]
a workaround of the problem is to use **vertex** instead of plane and set first  textureMode(NORMAL);

beginShape();
  vertex(-larg, -alt, 0, 0);
  vertex(larg, -alt, 1, 0);
  vertex(larg, alt, 1, 1);
  vertex(-larg, alt, 0, 1);
  endShape();

**Comment by rich-gg** [comment]
apparently the workaround doesn't work
in https://rich.gg I I replace all the rect() with the Shapes as described above and... it didn't fix the probleme

:(

**Comment by danielemichieletto** [comment]
this work for me: http://dotcode.it/p5_iphone8/

**Comment by rich-gg** [comment]
Cool @danielemichieletto but what is the trick ?

Is it in p5-v80 ?
Is it using no Material ?

I use
```
  ambientMaterial(255, 0);
  texture(logo);
```

I don't use any textureMode()
...

**Comment by rich-gg** [comment]
> this work for me: http://dotcode.it/p5_iphone8/

@danielemichieletto 

Would you try this variation of your code
https://rich.gg/iPhone8r/

Only difference is, at line 84/85 I added
    fill(255);
    box(100);

**Comment by rich-gg** [comment]
@stalgiag 
Would it help knowing that 
this works :

**Comment by stalgiag** [comment]
@rich-gg so odd.

Sorry I haven't made any progress on this yet. I am working on something else currently. This is still a priority. I just need to get my hands on one of these devices. 

Obviously if anyone owns an Iphone 8+ and is interested in working on WebGL stuff then help is very welcome. Otherwise, I'll investigate as soon as I am able.

**Comment by rich-gg** [comment]
I wish that detail I just posted, about
the render being affected by
the presence of a model() or a 3D primitive
prior to the render of a textured object
can help the bug investigation

thanks for the good work :)

**Comment by sjscotti** [comment]
I just verified that the fix mentioned at https://github.com/processing/p5.js/issues/3518 that is in the new version located at https://raw.githack.com/stalgiag/stalgiag.github.io/master/p5.min-master-5-21-19.js has fixed the problem I originally identified.  Does anyone know when this fix will be in the production version of p5.js?

And thanks for making the fix!
