### ISSUE TITLE
Issue: 'size' fails as variable name

### ISSUE THREAD

**Issue by dhowe** [processing/p5.js#3297]
Each week in class a student attempts to use 'size' as a variable name. And their sketch silently fails (at least in the editor), which is confusing. As size() is, I believe, only a function on numberDict, I wonder if there is a way to allow its use unqualified use? 

On a separate but related note, why are we not using the friendly error mechanism by default in the online editor (including p5.js rather than p5.min.js)? This seems the place where it would be most useful (perhaps with an option to disable for the few advanced users still using the editor who happen to need higher performance)? 

```
var size = 300;
function setup() {
  createCanvas(400, 400);
  ellipse(200,200,size);
}
```

p.s. I've also now added a ticket in the editor repo [here](https://github.com/processing/p5.js-web-editor/issues/417)

**Comment by digitalfrost** [comment]
I can reproduce this problem in CodePen: https://codepen.io/anon/pen/KrPxXY?editors=1111

Interestingly changing 

`var size = 300;`

to 

`let size = 300;`

works

**Comment by Spongman** [comment]
It should be quite simple to have the editor hook the FES functionality and report those errors to the user.

**Comment by lmccart** [comment]
we were previously reporting an error when users entered size() to assist with transitioning from processing. I think we're far enough into p5.js as it's own project now that we no longer need this warning. I will remove this and it should enable use of size as a variable name without problem.
