### ISSUE TITLE
p5 round() method

### ISSUE THREAD

**Issue by leohasanose** [processing/p5.js#3298]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [x ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [x ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [ x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version:  current p5.js Web Editor
- Web browser and version:  69.0.3497.120
- Operating System:  DELL chromebook on chrome web browser
- Steps to reproduce this: Open the p5.js Web Editor in google Chrome Web Browser.

#### Feature enhancement details:
I would like to suggest a new parameter for the round() method. This would be useful to round to a specific decimal place, round to the nearest fifth, tenth, etc.... If this is already a feature, please disregard this feature request, but add the information to the round() method's reference page.

**Comment by leohasanose** [comment]
is it possible to round a number such as 43 to 45 or 67 to 70?

**Comment by lmccart** [comment]
in this case, since JS support is already pretty good and straight forward, I think we can leave the more minimal p5 round() support as is. thanks @renabil

**Comment by lmccart** [comment]
@leohasanose you could do this like `6.7.toFixed(0) * 10`
