### ISSUE TITLE
Error in image displaying

### ISSUE THREAD

**Issue by ejgutierrez74** [processing/p5.js#3299]
#### Nature of issue?

- [X ] Found a bug

#### Most appropriate sub-area of p5.js?

- [ ] Image

#### Which platform were you using when you encountered this?

- [X ] Desktop/Laptop

#### Details about the bug: 

- p5.js version: Complete version 0.7.2
- Web browser and version: Atom live server using Firefox 63.0 64 bits
- Operating System:Ubuntu 18.04.1
- Steps to reproduce this:
Following this tutorial to create a pacman game in p5.js using windows,
https://www.youtube.com/watch?v=YLjFBwnUz30&index=3&list=PLLdsG7VOUdG8IpuNR1RyOBNR_aPj8DtB5

 i tried in Ubuntu. Everything was fine till i has to show a image part. It has a pacman.png sprite with different positions in movement. 
![imagen](https://user-images.githubusercontent.com/11474846/47951092-2e34d600-df5c-11e8-93c4-110136f8c549.png)

That thing that worked ok in windows didnt work in linux.
Seem image parameters differs.
In video uses the documentation parameters of image as:
`  image(pacManImage, 32*this.frame++, 32*this.direction, 32, 32, this.x, this.y, 32,32);`

What it really worked:
    `image(pacManImage, this.x,this.y, 32, 32, 32*this.frame, 32*this.direction, 32,32);`

So parameters 2 and 3 are changed by 6 and 7.

Should work as in documentation ( first instruction).

**Comment by lmccart** [comment]
Is this an issue with the tutorial's directions? In this case, please report it to the video tutorial author.

**Comment by ejgutierrez74** [comment]
Not an issue with tutorial as you can watch in the video, it works ok for him in Windows. I think that error is related to image displaying is different in Windows and Linux, and or is a bug in P5js or it has to be documented( displaying images in different way in Windows and Linux, dont know in MacOS).
If you can confirm this issue....

**Comment by limzykenneth** [comment]
@ejgutierrez74 The tutorial video is from January 2017, while I don't remember the sprite sheet image drawing function changing between then and now, I may be wrong. In any case, there are several releases between then and now so unless you can run the same code on Windows now with version 0.7.2 and confirm the order of parameters differs, we can't be sure the bug indeed exist. Thanks.

**Comment by ejgutierrez74** [comment]
I can confirm that at least in Windows 10 64bits it also only works the second option not the first one, so from july 2017 this instruction has changed. It should be reflected in the documentation. I think that parameters has changed. Thanks for your help.

Taken  yesterday from your web:
https://p5js.org/reference/#/p5/image

image(img, dx, dy, dWidth, dHeight, sx, sy, [sWidth], [sHeight])
img | p5.Image\|p5.Element: the image to display
-- | --
```
x | Number: the x-coordinate of the top-left corner of the image
y | Number: the y-coordinate of the top-left corner of the image
width | Number: the width to draw the image
height | Number: the height to draw the image
dx | Number: the x-coordinate of the destination                           rectangle in which to draw the source image
dy | Number: the y-coordinate of the destination                           rectangle in which to draw the source image
dWidth | Number: the width of the destination rectangle
dHeight | Number: the height of the destination rectangle
sx | Number: the x-coordinate of the subsection of the source image to draw into the destination rectangle
sy | Number: the y-coordinate of the subsection of the source image to draw into the destination rectangle
sWidth | Number: the width of the subsection of the                           source image to draw into the destination                           rectangle
sHeight | Number: the height of the subsection of the                            source image to draw into the destination rectangle

```

Think should be changed. Perhaps im confused, but the code is clearly different from july ( the video proof it) till today.

**Comment by limzykenneth** [comment]
The change probably was to bring it more inline with the default HTML canvas's signature. As long as the documentation reflects current behaviour of the library, there's nothing for us to change. You can ask the video tutorial's creator to update the tutorial if necessary.

**Comment by ejgutierrez74** [comment]
Perhaps im wrong but : https://p5js.org/reference/#/p5/image 
It says that you have to use image this way:
image(img, dx, dy, dWidth, dHeight, sx, sy, [sWidth], [sHeight])

And this is the way shown in the video that it doesnt work... first coordinates is the destination image ( dx and dy).And the function corrected that it works it has the source x and source y instead ( the "begin" of the image"). So parameters 2,3 and 6.7 should be changed.

The image code line that works should be:
image(img, sx, sy, dWidth, dHeight, dx, dy, [sWidth], [sHeight])

Thanks for answering and sorry for my bad english....

**Comment by limzykenneth** [comment]
For me the signature works as stated, ie `image(img, dx, dy, dWidth, dHeight, sx, sy, [sWidth], [sHeight])`. `dx`, `dy` is the location where the image will be on canvas; `dWidth`, `dHeight` is how big the image will be on canvas; `sx`, `sy` is the starting coordinates of the subsection rectangle within the image; `sWidth`, `sHeight` is how big the subsection rectangle will be.

I don't have time to go through the video to verify what they used but if you have a look at the reference page there is an image that should explain what individual parameters are in a clearer way. If you have further problem, you can post them on the [forum](https://discourse.processing.org). Thanks!
