### ISSUE TITLE
quadraticVertex() in contour anchors to the wrong X coordinate

### ISSUE THREAD

**Issue by aparrish** [processing/p5.js#3309]
You can see the problem in this sketch: https://editor.p5js.org/allison.parrish/sketches/H1OqsJBa7

The quadratic vertex always gets anchored to the coordinate in the previous call to `vertex()`, but with the X coordinate set to zero.

I think the problem is a typo(?) in this line: https://github.com/processing/p5.js/blob/aeaf6865b0af2b8e302f305e6a573eb733ab1117/src/core/p5.Renderer2D.js#L810 `[0]` there should maybe read `vertices[i][0]`?

**Comment by rikkertkoppes** [comment]
Can confirm. This also seems to be a problem when even a single quadraticVertex: https://editor.p5js.org/rikkertkoppes/sketches/u19G4z09K

The suggested fix by @aparrish does solve this.

**Comment by stalgiag** [comment]
fixed via #3585. Thanks @aparrish & @rikkertkoppes !
