### ISSUE TITLE
Teapot in p5.js reference example loadModel() nearly unvisible

### ISSUE THREAD

**Issue by toniholzer** [processing/p5.js#3310]
Hallo
Example loadModel() displays the teapot with a size of only some pixels.
The example works fine, if you scale up the teapot with the statement scale(12);

#### example of:
https://p5js.org/reference/#/p5/loadModel
https://p5js.org/reference/#/p5/model

#### corrected example:
//draw a spinning teapot
var teapot;
function preload() {  teapot = loadModel('assets/teapot.obj'); }
function setup() {  createCanvas(100, 100, WEBGL); }
function draw() {  background(200);
  rotateX(frameCount * 0.01);
  rotateY(frameCount * 0.01);
  scale (12);
  model(teapot);
}

#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [x] Reference
- [x] Example
- [x] WebGL

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop

#### Details about the bug: 

- Web browser and version: Firefox 63.0.1
- Operating System: Windows 7

**Comment by vipulrawat** [comment]
@lmccart It's looking like the reference page in p5.js website is taking all the examples (i.e. inline documentation) from version 0.6.1. 
The above issue is already resolved in [this](https://github.com/processing/p5.js/pull/2968) PR. The version of p5.js is 0.7.2. But the reference page is not updated, seems like a manual process to update the reference page.


What is the process of 'reference page' updation?

**Comment by lmccart** [comment]
@vipulrawat it's supposed to happen via [this task](https://github.com/processing/p5.js/blob/master/tasks/release/release-docs.js) when grunt release is run. more info on the [release process here](https://github.com/processing/p5.js/blob/master/developer_docs/release_process.md). it seems like some part of this is not working correctly though.
