### ISSUE TITLE
Axidraw p5 clean webusb interface

### ISSUE THREAD

**Issue by TiborUdvari** [processing/p5.js#3315]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [x] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [x] Utilities
- [ ] WebGL
- [x] Other (specify if possible)

#### New feature details:

I'm looking to create an API to control my [axidraw](https://axidraw.com/) through [WebUSB](https://developers.google.com/web/updates/2016/03/access-usb-devices-on-the-web) (currently only working on Chrome) with p5. The communication works by sending simple serial messages. My idea is to have the usual functions like `line`, `ellipse` etc. behave normally, but in a certain state draw with the drawing machine instead of to the canvas. 

I know this might be out of the scope of the general codebase, but I was wondering what would be a good entry point into the API as I would like to publish it as an optional addon/extensions to p5. I have thought of creating function decorators to the existing library with a global switch to toggle using the Axidraw. 

I think ideally it would function something like a custom renderer class, that doesn't actually render anything on the screen. But again, I don't know how that would work, since I don't know if that would work with the paradigm since drawing with the physical machine would mean taking a significant time for each action. 

Do you have any ideas on the subject?

**Comment by lmccart** [comment]
I think this plan sounds good as an addon. I don't know about the specifics of axidraw so it's hard to give advice here. I would suggest posting to the forum for more discussion. https://discourse.processing.org
