### ISSUE TITLE
P5 Web Editor won't preview any sketches

### ISSUE THREAD

**Issue by msgarnier** [processing/p5.js#3316]
#### Nature of issue?

- [ x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [x ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x ] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 
- Web browser and version: Chrome 70.0.3538.102
- Operating System: MacOS Sierra 10.12.5 (16F73)
- Steps to reproduce this:
It seems to be account specific. It was happening to my students, and then it happened to me. Here is a screen shot
![screen shot 2018-11-13 at 3 43 27 pm](https://user-images.githubusercontent.com/25465795/48444456-fe5aaf00-e761-11e8-8db6-567d3eccf4a9.png)
I have tried a different browser, I have tried using another account, I have tried clearing my browsing history completely, and restarting my computer. The sketches can be previewed by another account.

**Comment by lmccart** [comment]
This issue was moved to processing/p5.js-web-editor#764
