### ISSUE TITLE
mouseReleased() not triggered by right-click but mousePressed() is

### ISSUE THREAD

**Issue by sarisarah** [processing/p5.js#3317]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [x] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: v0.5.7 
- Web browser and version: 70.0.3538.102
- Operating System: macOS Sierra
- Steps to reproduce this:
```
function setup() {
  createCanvas(400, 400);
  background(255);
}

function mousePressed() {
  console.log('mouse pressed');
  if (mouseButton == RIGHT) console.log('right-click');
}

function mouseReleased() {
  console.log('mouse released');
  if (mouseButton == RIGHT) console.log('right-click');
}
```
When right-clicking `mousePressed()` registers it, but `mouseReleased()` doesn't. This can create problem especially if using a variable that it set `true` by `mousePressed()` and `false` by `mouseReleased()`. 

Not sure if this is just on macOS Sierra or affects everyone.

**Comment by vipulrawat** [comment]
@sarisarah By the default behavior of browser, the right mouse up event triggers the context-menu unless prevented. If you are looking for looking to grab the right mouse release event you should disable the default behavior of the browser using the following code in `function preload()`.
```javascript
document.oncontextmenu = function ()
{
 return false;     // remove context menu
}
```

This function removes the context menu on right mouse click. Notice that after this you cannot get context-menu in the whole document. But you can target this to only `canvas` element also using DOM selectors.

**Comment by sarisarah** [comment]
Thanks - that's what I was looking for!
