### ISSUE TITLE
Issue With TextSize() and StrokeWeight

### ISSUE THREAD

**Issue by Blingboy740** [processing/p5.js#3319]
I don't know ifthis is happening due to the dis proportionality of strokeWeight() and textSize() but there is a problem with "A" in particular where it has a weird extra triangle at the top of the "A". You can check the enclosed file for a picture and p5.js sketch which shows the issue.

[ISSUE EXAMPLE RUNABLE.zip](https://github.com/processing/p5.js/files/2590751/ISSUE.EXAMPLE.RUNABLE.zip)

**Comment by TanviKumar** [comment]
The error can be replicated in the p5.js Web Editor with just the sketch code. 
`var x;

function setup() {
  createCanvas(windowWidth, windowHeight);
}

function draw() {
  background(0);
  textSize(100);
  strokeWeight(30);
  stroke(255);
  text("AAAAAA TEST AAAAAA", 100, windowHeight / 2);
}

function windowResized() {
  resizeCanvas(windowWidth, windowHeight);
}`

Increasing the ratio of testSize to strokeWeight helps reduce the size of the weird triangle, so it does seem to be an issue with proportionality.

**Comment by vipulrawat** [comment]
It's not a problem with p5.js.This thing happens with native canvas elements.
Also, the extra triangle's size and visibility highly depend on the typeface you are using.

_Example: Using sans typefaces removes those extra triangle as sans doent have serifs (feet)_

You may want to check [this](https://jsfiddle.net/vipulrawat/kq4syu15/4/) for reference.
__In p5.js, you can use some good sans typefaces like `textFont('Georgia');` this will remove the issue of extra triangle.__

**Comment by limzykenneth** [comment]
This is a known issue (#3035), it is related to the default miter limit set by the Canvas API. For now you can access the underlying canvas and set the miter limit on there. 

PS. @vipulrawat Georgia is a serif typeface

**Comment by vipulrawat** [comment]
Oh yes. Sorry, I think I missed this thing then. Also in Canavs API using only Georgia is solving the issue but in p5 both Georgia and Helvetica solved the issue. Then the miter limit is real solution by setting something like this 
```javascript 
var context = canvas.getContext('2d');
context.miterLimit = 2 ; // default is 10
```
