### ISSUE TITLE
optimization: remove unnecessary object creation throughout codebase

### ISSUE THREAD

**Issue by lmccart** [processing/p5.js#332]
Splitting this out from https://github.com/lmccart/p5.js/issues/331:

There is a lot of unnecessary object creations throughout the whole code base e.g.
https://github.com/lmccart/p5.js/blob/master/src/shape/2d_primitives.js#L71
Creating a new object to return 4 numbers is a quite some of overload. Also considering this case:

for(var i = 0; i < 1000; ++i){
    ellipse(newPosX,newPosY,newScaleY,newScaleY);
}
At 60fps thats 60000 objects created every seconds just to calculate 4 numbers.

Constantly recreating an array can easily be replaced
by a single one time initiated array and altering its length via array.length = n

See: http://jsperf.com/array-recreation-vs-array-length-adjust

**Comment by kjhollen** [comment]
Hey folks. I'm working on this one and wondering if you have a favorite method for performance testing with js. Right now I'm just looking at the frame rate for a sketch that renders 1000 ellipses both on the master branch and a branch with some (possible) optimizations. Is there a more accurate or better way?

**Comment by jedahan** [comment]
I have no experience with performance testing, but http://www.html5rocks.com/en/tutorials/canvas/performance/#toc-perf and http://benchmarkjs.com looked potentially useful. Would be really cool to see speedups :)

**Comment by kadamwhite** [comment]
Most of the tools I know are for establishing how long it takes a page to load; not familiar with options for specific performance benchmarking though. Pinging @Wilto and @tbranyen to see if they have any knowledge that would be useful.

**Comment by brysonian** [comment]
There are some pretty impressive new performance tools in the latest [firefox developer edition](https://hacks.mozilla.org/2015/06/new-performance-tools-in-firefox-developer-edition-40/) which could be handy.

**Comment by kjhollen** [comment]
Great suggestions. Thanks all. Hope to have some actual results to report later this week!

**Comment by workergnome** [comment]
Something else that I was thinking about, which you can :+1: :-1: as you like:  It would be really helpful to be able to run a bunch of the examples as tests, to see if code changes break the examples.  That might also be useful for performance, or at least identifying where we are doing things?

**Comment by dhowe** [comment]
[jsperf](https://github.com/mathiasbynens/jsperf.com) if also useful, at least for testing smaller code chunks

**Comment by lmccart** [comment]
Before I forget, I noticed that the `get()` method creates a new `p5.Image()` with every call, it would be good to remove this. https://github.com/processing/p5.js/blob/master/src/core/p5.Renderer2D.js#L251

**Comment by kadamwhite** [comment]
I came across this issue when I noticed that any call to `fill` or `stroke` slows my sketch down by a significant percentage -- Is this issue the right place to talk through p5.Color performance, or should I make a new one?

As an aside, it doesn't look like Github updates line numbers in links so here's a direct link to the `p5.Image()` call mentioned above in the latest commit on master: https://github.com/processing/p5.js/blob/e51fa1cbafe654c9c8c5d54aa67d12892c484be7/src/core/p5.Renderer2D.js#L244

**Comment by lmccart** [comment]
hi @kadamwhite can you please open a new issue for the color discussion?

**Comment by lmccart** [comment]
closing this issue as it's been generally addressed. to continue to work on this, let's open individual issues for specific areas in the code that need improvement.
