### ISSUE TITLE
Bring back textHeight()

### ISSUE THREAD

**Issue by devinhalladay** [processing/p5.js#3320]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [x] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [x] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### New feature details:
Working with typography in some basic ways is currently very difficult in P5; currently, I'm really struggling with multiple multi-line text boxes that need to be positioned in relation to each other. I see that P5 used to have a `textHeight()` function that got the height of a text block (though I'm not sure this handled multi-line text) and it was removed in [PR #368](https://github.com/processing/p5.js/pull/368) because Processing doesn't have an equivalent.

Is there the possibility of bringing this back into P5 so that the library can handle typographic basics on its own without the use of P5.dom elements?

(To clarify, I would like to use this to get the height of a multi-line text block.)

**Comment by dhowe** [comment]
This is not totally straightforward. There are two ways to make multiline text in p5.js: a) to include line breaks (\\n) in your text-string, or b) to pass x,y,w,h to the text() command, which automatically breaks lines according to the implied rectangle. 

For case a) one could easily enough split the string (on line breaks) into some number of substrings, then compute the sub-bounds for each using p5.Font.textBounds(), then return the smallest bounding box that contains each of those bounding boxes (the sum of the sub-bounds).

For case b) if the user supplies a bounding box, then this is, by definition, a bounding box for the supplied text, however, it is not a _tight_ bounding box (In most cases there will be additional space  edges). To get the tight bounds, one must again compute the bounds for each line separately, then return the aggregate bounds for the set.  If one had implemented case a), then it could be called with the text from case b) with line breaks specified as \\n. 

The 2nd issue with case b) is that the signature of p5.Font.textBounds() would have to change to accommodate these additional parameters, and its not fully clear (to me at least) how this would best work. 


![image](https://user-images.githubusercontent.com/737638/49342829-ee682800-f69a-11e8-8913-bf032595dd60.png)

**Comment by Spongman** [comment]
i wonder, does it make sense for the user to supply the height of a bounding box? isn't the height a calculated result?

**Comment by GodWoold** [comment]
Hi! I tried a little something but it's quite goofy

check it --> [https://editor.p5js.org/ThatsTrue/sketches/3Y2hmBc7v](url)

**Comment by GodWoold** [comment]
Hi! I tried a little something but it's quite goofy
check it --> https://editor.p5js.org/ThatsTrue/sketches/3Y2hmBc7v

**Comment by GodWoold** [comment]
Solved ✓ https://editor.p5js.org/ThatsTrue/sketches/QmHcXTd_o (works for p5.js up to u to convert it to processing)

**Comment by munusshih** [comment]
https://editor.p5js.org/munusshih/sketches/4BwL7q2Fe

`javascript=
p5.prototype.textHeight = function (...args) {
  const tL = this._renderer.textLeading();
  const tS = this._renderer.textSize();

  let lineNum = 0;
  if (typeof args[0] !== undefined) {
    lineNum = args[0].split(/\r?\n|\r|\n/g).length;
  }
  const textH = tL * (lineNum - 1) + tS;

  return textH;
};
`
I made this sketch here to propose an idea of using textLeading and textSize to calculate textHeight()
But I'm not sure if this math is general enough to cover all cases.

**Comment by limzykenneth** [comment]
@munusshih That I think will give the maximum height possible but not necessarily the exact height, ie. it includes the ascenders of the first line (if any) and descenders space of the last line (if any) even if the line itself don't have anything that goes to the top or bottom of the bounding box, it will still be calculated.

For example
```js
textHeight("xxxxxxxxx");
textHeight("AAAAAAAAAA");
```
would have the same height.

It is simpler this way but it would differ from value returned from `textBounds()`, so whether this is ok or not depending on the possible use case of `textHeight()`.
