### ISSUE TITLE
curvePoint() Documentation incorrect

### ISSUE THREAD

**Issue by mzed** [processing/p5.js#3321]
#### Nature of issue?
- [x] Found a bug

#### Most appropriate sub-area of p5.js?
- [x] Core/Environment/Rendering

#### Which platform were you using when you encountered this?
- [x] Desktop/Laptop

#### Details about the bug: 
- p5.js version: Documentation

I’m pretty sure that the documentation for the `curvePoint()` function in p5.js is wrong. It is here:
https://p5js.org/reference/#/p5/curvePoint

I think the parameters should be:

Parameters
`a` Number: coordinate of first _control_ point
`b` Number: coordinate of first point on the curve
`c` Number: coordinate of second point on the curve
`d` Number: coordinate of second _control_ point
`t` Number: value between 0 and 1

So, the points on the curve are values 2 and 3, not 1 and 4. That would be more similar to the `curve()` function.

Here's an example: https://editor.p5js.org/kll/sketches/BJYFW_hTQ

The original processing documentation is inconsistent, too:
https://processing.org/reference/curvePoint_.html

**Comment by lmccart** [comment]
fixed with https://github.com/processing/p5.js-website/commit/8e0c66b5a336b09d18042b1c494bb5cef5370f6a
