### ISSUE TITLE
reference is not building correctly

### ISSUE THREAD

**Issue by lmccart** [processing/p5.js#3322]
Running `grunt yui` currently builds a version of the [reference](https://p5js.org/reference/) lacking heading and translation buttons. Looks like there were some changes [here](https://github.com/processing/p5.js/commit/da936b4740b60b354f606863ad54a82359440d7e#diff-8929bd6276966eccdcc6f70e33ae64d6) but I'm not sure where the removed code went. Perhaps I'm just running the wrong command in which case the gruntfile needs updating?

**Comment by vipulrawat** [comment]
Were these file changes in the recent commit in p5-website repo directly generated from `grunt yui`?

**Comment by lmccart** [comment]
yes. this was incorrect I realize now. the docs were out of date for reference building. working on a revert..

**Comment by lmccart** [comment]
@vipulrawat more over here: https://github.com/processing/p5.js/commit/da936b4740b60b354f606863ad54a82359440d7e#r31337713
