### ISSUE TITLE
3D renderer only has a 2D implementation of `quad`

### ISSUE THREAD

**Issue by unjust** [processing/p5.js#3328]
Trying to pass z coordinates to `quad` for 3d rendering doesn't work, there is no implementation for 12 args (which would contain `z`)

 https://github.com/processing/p5.js/blob/9851414f747384d708a556285876bc585a2c9e4f/src/webgl/3d_primitives.js#L1027-L1064

_Originally posted by @meiamsome in https://github.com/_render_node/MDExOlB1bGxSZXF1ZXN0MjMyMDgxNzM4/pull_requests/unread_timeline#issuecomment-440012991_

**Comment by unjust** [comment]
It would be my first issue, but I can attempt to fix.

**Comment by meiamsome** [comment]
@unjust great! You can find an example of how to parse the arguments in both forms at once in the `bezier` function just below: https://github.com/processing/p5.js/blob/9851414f747384d708a556285876bc585a2c9e4f/src/webgl/3d_primitives.js#L1069-L1108

**Comment by unjust** [comment]
https://github.com/processing/p5.js/pull/3329

**Comment by unjust** [comment]
Apologies if my closing and opening another pull request to fix this got lost somehow. Or maybe it doesn't fit with the es6 roadmap ?

This is the fix https://github.com/processing/p5.js/pull/3358
