### ISSUE TITLE
Grunt build error

### ISSUE THREAD

**Issue by rnkn** [processing/p5.js#3330]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Build

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: v0.7.2
- Web browser and version: Safari Version 12.0.1 (14606.2.104.1.1)
- Operating System: macOS 10.14.1 (18B75)
- Steps to reproduce this:
~~~
$ git clone https://github.com/processing/p5.js.git
...
$ npm install
...
$ grunt
...
Running "mochaChrome:yui" (mochaChrome) task
EventBus initialized
Promise Rejection:  Error: No Chrome Installations Found
    at Launcher.<anonymous> (/Users/Paul/Developer/p5.js/node_modules/chrome-launcher/dist/chrome-launcher.js:141:27)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/Paul/Developer/p5.js/node_modules/chrome-launcher/dist/chrome-launcher.js:9:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)

~~~

I think this might be because I don't have Google Chrome installed, but this is not something I plan on doing anytime soon...

**Comment by limzykenneth** [comment]
The tests run in Chrome so without Chrome you will not be able to run the tests. You can still run the build with `grunt build`.

**Comment by rnkn** [comment]
Cool, thanks Kenneth.
