### ISSUE TITLE
Improve reference page for lerp() - t can go outside [0,1]

### ISSUE THREAD

**Issue by grege2** [processing/p5.js#3332]
#### Nature of issue?

- [x] Existing feature enhancement

#### Most appropriate sub-area of p5.js?

- [x] Math

#### Which platform were you using when you encountered this?

- [x] Desktop/Laptop

#### Details about the bug: 

- p5.js version: 0.7.2 Sep 02 2018

#### Feature enhancement details:

I suggest that the doco for lerp() add that it works fine for control parameter outside the [0,1] range.

The reference page for lerp() states that the lerp parameter should be between 0.0 and 1.0, but it works fine outside this range as well. Ie. the lerp() does the mathematically consistent thing and continues to interpolate, in fact extrapolate, beyond the end of the min/max range. This is to be expected really, since the same internal p5.js code will just continue to work. Unless the range was clamped to [0,1] which it doesn't seem to be. 

Therefore it would be helpful to some users to note that the control param can go outside [0,1] and all will work as expected.

**Comment by sanketsingh24** [comment]
I can work on this issue

**Comment by lmccart** [comment]
fixed with https://github.com/processing/p5.js/pull/3361
