### ISSUE TITLE
improve triangle doc page.

### ISSUE THREAD

**Issue by davidhbigelow** [processing/p5.js#3333]
It would be helpful to know what the "vertex" of the triangle is.  This is often used for translating the triangle.. and it is hard to know what the true vertex of the final triangle is.

**Comment by vipulrawat** [comment]
You means a method to get the vertices (x,y) of the triangle?

**Comment by davidhbigelow** [comment]
well... that would be helpful.... but I was thinking more along the lines of the centerpoint...
Or the start point for translation of the triangle.

I am assuming the first set of coordinates is the start point (vertex) that the rest of the triangle is built from.   But without clarification - it is easy to assume the middle point as the "vertex" -- but depends on how one thinks about triangles.

**Comment by lmccart** [comment]
Yes, I think the triangle function and documentation are currently in line with the most [common mathematical definition of a triangle](https://www.mathopenref.com/triangle.html) so I think we can close this. If you have suggestion for further text to be added please let us know.
