### ISSUE TITLE
Optimize dist() with distsq() for comparison, without computing square root

### ISSUE THREAD

**Issue by ThatIsAPseudo** [processing/p5.js#3337]
#### Nature of issue?

- [ ] Found a bug
- [x] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [x] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Feature enhancement details:
The `dist()`function should have an optionnal parameter (or a similar function) in the case we want to get the sqare of the distance between two points, that would avoid computing a square root when we just want to use it in a comparison, i.e. when we don't really want ton know the exact value.

For instance, a simple `distsq()` would complete this task :
```javascript
function distsq(x1, y1, x2, y2) {
   return sq(x1 - x2) + sq(y1 - y2);
}
```
`distsq()` should work in 3D as well.

**Comment by Remcodejong** [comment]
> `distsq()` should work in 3D as well.


This would require the z value of the point as well. Based off the original dist function in p5:
```javascript
e.prototype.distSq = function() {
return e._validateParameters("distSq", arguments),
4 === arguments.length ? return Math.sqrt (d(arguments[2] - arguments[0], arguments[3] - arguments[1])) : 6 === arguments.length ? return Math.sqrt(d(arguments[3] - arguments[0], arguments[4] - arguments[1], arguments[5] - arguments[2])) : void 0
}
````
Something like this?

**Comment by Remcodejong** [comment]
I think that would be exactly the same as the normal distance function, but I could try to rework the suggestion, and ill get back to you

**Comment by ThatIsAPseudo** [comment]
It should be the sum of the square of the differences, shouldn't it? Just like in the `dist` function but without applying `sqrt`

**Comment by Remcodejong** [comment]
Like the variable r2 here? 
https://editor.p5js.org/Remcodejong/sketches/HktaQoYC7

**Comment by Spongman** [comment]
Doesn’t `p5.Vector.dot()` already cover this?

**Comment by ThatIsAPseudo** [comment]
Yeah, exactly like this :
```javascript
let dx = x2-x1;
let dy = y1-y2;
d = (pow(dx,2)+pow(dy,2));
text("dist squared is " + floor(d),10,220);
```

**Comment by Remcodejong** [comment]
> Doesn’t `p5.Vector.dot()` already cover this?

I think that would still require a square root wouldn't it? 
https://math.stackexchange.com/questions/1236465/euclidean-distance-and-dot-product

**Comment by lmccart** [comment]
I think this function is beyond the scope of the p5.js api (we try to keep as minimal as possible) but it could be a great starting point for an addon library. see the docs here for how to create an addon: https://github.com/processing/p5.js/blob/master/developer_docs/creating_libraries.md

**Comment by Remcodejong** [comment]
I could make it into a library if you would like? @ThatIsAPseudo

**Comment by ThatIsAPseudo** [comment]
> I could make it into a library if you would like? @ThatIsAPseudo

Yes, in fact that would be cool to have a "more functions" library with such functions that aren't absolutely necessary but useful btw

**Comment by Remcodejong** [comment]
Ill open a thread on the forums to ask for suggestions! Think this issue can be closed then.
