### ISSUE TITLE
ARC() ERROR on Electron?

### ISSUE THREAD

**Issue by ZhangBo1191** [processing/p5.js#3338]
![](https://user-images.githubusercontent.com/36790218/48966287-8f0a7800-f009-11e8-9241-16211512482e.png)
This is a [Material-Clock](https://github.com/zlyfer/Material-Clock) that I try to use it by electron.
But this is the error.
I also asked a Issue on the project itself [Issue](https://github.com/zlyfer/Material-Clock/issues/1)
But the author tell me to ask it on p5js Issue.

**Comment by lmccart** [comment]
Hm it seems to run correctly in the p5.js editor, so maybe it is something specifically with electron. https://editor.p5js.org/lmccart/sketches/BkbTflDRX

It's difficult to tell what the error and what's going on with electron from such a complex example. This kind of problem is best discussed in the forum which is better suited for programming help: https://discourse.processing.org
