### ISSUE TITLE
KeyIsDown() returns true every frame with Chrome extension Evernote Web Clipper

### ISSUE THREAD

**Issue by pgrenon1** [processing/p5.js#3339]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [x] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.6.0
- Web browser and version: Google Chrome | 70.0.3538.102 (Official Build) (64-bit)
- Operating System: Windows 10 pro
- Steps to reproduce this:
   1. Install and enable the Chrome extention "Evernote Web Clipper" https://chrome.google.com/webstore/detail/evernote-web-clipper/pioclpoplcdbaefihamjohnefbikjilc2
   2. Use KeyIsDown() in Draw()

Behavior: When the Chrome extension "Evernote Web Clipper" is enabled, and I check KeyIsDown() in Draw(), and then as soon as I press the key once, it starts returning true every frame, as though I would keep the key pressed the whole time.

I tried this on two different computers. The bug also happens even when that extension is the only one enabled and all other extensions are disabled. At this point I imagine it's a problem that comes from the extension itself, but I thought this would be an issue worth reporting.

**Comment by pgrenon1** [comment]
Here is the right link to that extension: https://evernote.com/features/webclipper

I am trying instance mode, but I'm not sure I am doing it right. I have classes that are defined in other files than my main sketch.js. Should this work anyway? Do I just have to wrap my sketch.js in a `var myp5 = new p5( function( sketch ) {
  // empty
});`? or do I need to link up my classes in the sketch instance?

**Comment by lmccart** [comment]
hi @pgrenon1 can you follow up on this by posting your question in the [discourse forum](https://discourse.processing.org)? that is the ideal place to get programming help and help debugging issues with outside tools. thanks!
