### ISSUE TITLE
My page just crashed and blank page opens. Lost my code. Please help! https://editor.p5js.org/carlaplotnicoff/sketches/SycQtp_pm

### ISSUE THREAD

**Issue by carlaplotnicoff** [processing/p5.js#3342]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 
- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

**Comment by carlaplotnicoff** [comment]
https://editor.p5js.org/carlaplotnicoff/sketches/SycQtp_pm

**Comment by lmccart** [comment]
i'm sorry to hear it. can you please post over here: http://github.com/processing/p5.js-web-editor
that is the dedicated repository for the web editor. thanks
