### ISSUE TITLE
keyCode does not work properly for arrow keys in Firefox

### ISSUE THREAD

**Issue by ikselven** [processing/p5.js#3346]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.7.2
- Web browser and version: Firefox 63.0.3, Chromium 70.0.3538.110
- Operating System: Linux
- Steps to reproduce this:
Run the code from example 5-19 of the "Getting Started with p5.js" book in both of the above-mentioned browsers:
```javascript
var x = 215;

function setup() {
  createCanvas(480, 120);
}

function draw() {
  if (keyIsPressed) {
    if (keyCode == LEFT_ARROW) {
      x--;
    } else if (keyCode == RIGHT_ARROW) {
      x++;
    }
  }
  rect(x, 45, 50, 50);
}
```

In Chromium, the rectangle is moving, when the left or right arrow keys are pressed. In Firefox, the rectangle does not move, when pressing the arrow keys.

To check, what's in `keyCode`, I added `console.log(keyCode);` right below the first if-statement. As expected, in Chromium, the key codes 37 and 39 are logged. But in Firefox it's always key code 0.

**Comment by ThatIsAPseudo** [comment]
I found a way to actually make the rectangle move, by pressing really quickly right-left-right-left arrows (dunno why)

**Comment by lmccart** [comment]
@vipulrawat thanks for looking into this. I think it would be great to do a review and update of keyboard event handling as I don't think it's been touched in a little while, and as you mention, some things are out of date and not working. would you be interested in taking this on?

**Comment by Spongman** [comment]
i just tested this on Firefox 63.0.3 and it works just fine. i'm not sure i understand the explanation above.

https://codepen.io/Spongman/pen/NELOLz?editors=0010

**Comment by ThatIsAPseudo** [comment]
> i just tested this on Firefox 63.0.3 and it works just fine. i'm not sure i understand the explanation above.
> 
> https://codepen.io/Spongman/pen/NELOLz?editors=0010
> 
> EDIT: i tried both on win10 and ubuntu.

Indeed, using `keyCode ==` works well on Codepen website but not on p5 web editor

**Comment by vedhant** [comment]
I tried this in firefox and it doesn't work for me too.
@lmccart I would love to take up on this issue.

**Comment by ikselven** [comment]
I'm reading the P5.js book at the moment and for learning purposes, I'm implementing the examples in their own HTML files. This is the full code used for the example I mentionend in the opening post:
```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Move with Arrow Keys</title>
    <link rel="stylesheet" href="css/style.css" />
</head>
<body>
    <script src="js/p5.min.js"></script>
    <script type="text/javascript">
        let x = 215;

        function setup() {
            createCanvas(480, 120);
        }

        function draw() {
            if (keyIsPressed) {
                console.log(keyCode);
                if (keyCode == LEFT_ARROW) {
                    x-=10;
                } else if (keyCode == RIGHT_ARROW) {
                    x+=10;
                }
            }
            rect(x, 45, 50, 50);
        }
    </script>
</body>
</html>
```

Note: The included stylesheet is irrelevant here, it only sets the background colour of the body.

**Comment by vedhant** [comment]
> Has anyone reproduced this outside of the web editor?
> 
> I doubt it’s a p5 library issue.

I got it outside the web editor.
```javascript
var x = 215;

function setup() {
  createCanvas(480, 120);
}

function draw() {
  if (keyIsPressed) {
    if (keyCode == LEFT_ARROW) {
      x--;
    } else if (keyCode == RIGHT_ARROW) {
      x++;
    }
  }
  rect(x, 45, 50, 50);
}
```

**Comment by vedhant** [comment]
@Spongman @lmccart  I would like to work on this issue.

**Comment by vipulrawat** [comment]
Ok. Here is a small insight into the issue. I have tested the code in these environments:
__Issue:__ The unexpected behavior of some code that involves keyboard event in chrome and firefox. The box is not able to move(smoothly) in firefox when using arrow (left, right) keys but works perfectly in chrome.
__p5.js__ v0.7.2
__Browsers:__ Chrome (v70.0.35), Firefox (v60.0.1)
__OS:__ Linux kernel 4.15.0-29 64-bit, macOS mojave
__Editor:__ Codepen, p5 web editor
__Links:__ Problem [Codepen](https://codepen.io/vipulrawat-imi/pen/LXgObx?editors=0010) | [p5 web editor](https://editor.p5js.org/vipulrawat/sketches/r1TclVjRm)

Table of working breakdown: 

|  using `keyCode` | Firefox  | Chrome  |
|---|---|---|
| Codepen  | __NO__ | YES  |
| Editor  | __NO__  | YES |

According to me, use of [`keyIsDown()`](https://p5js.org/reference/#/p5/keyIsDown) is more appropriate while trying handle movement of element using arrow keys (one can try to change the code in above links with `keyIsDown(LEFT_ARROW/RIGHT_ARROW)`).

|  using `keyIsDown()` | Firefox  | Chrome  |
|---|---|---|
| Codepen  | YES | YES  |
| Editor  | YES  | YES |

---
@lmccart I would love to do this once the unusual behavior in different browser get confirmend by other users too. 
@Spongman I may be wrong but if you overwrite `_onkeypress` in p5 library to do nothing (that is not registering the keypress event) i.e. just `return;` the code using `keyCode` works fine in both the browsers. The thing about not registering onkeypress by chrome [here](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onkeypress#Browser_Incompatibilities)
@ThatIsAPseudo Are you still getting correct results using `keyCode` in code but not in p5 web editor?
@vedhant Do you want to this issue on or shall I do this.

**Comment by Spongman** [comment]
@vipulrawat can you try this with the latest version of firefox?

**Comment by vedhant** [comment]
i further investigated the issue and have concluded as following : 

As mentioned above by @vipulrawat : 
When Arrow key is pressed, the events fired up in chrome are:

- onkeydown
- onkeyup

and in firefox the events are:

- onkeydown
- onkeypress
- onkeyup

The documentation for onkeypress event as described in MDN web docs : 

> The keypress event is fired when a key that produces a character value is pressed down. Examples of keys that produce a character value are alphabetic, numeric, and punctuation keys. Examples of keys that don't produce a character value are modifier keys such as Alt, Shift, Ctrl, or Meta.

Clearly, when Arrow key is pressed the onkeypress event should not fire up. However, in firefox the keypress event fires up irrelevant of the key actually pressed. The catch here is even though firefox fires onkeypress event for every key, the 'e.which' value is set to 0 if it is not a character value. If it is a character value then it is set to its ASCII value as expected but for keys like LEFT_ARROW, RIGHT_ARROW etc, it sets e.which to 0.

Therefore, when Arrow key is pressed in firefox, the keyCode value is been set to 0.

Possible Fix : 
```javascript
p5.prototype._onkeypress = function(e) {
  if(e.which === 0){
    return;
  }
  if (e.which === this._lastKeyCodeTyped) {
    // prevent multiple firings
    return;
  }
  this._setProperty('keyCode', e.which);
  this._setProperty('_lastKeyCodeTyped', e.which); // track last keyCode
  this._setProperty('key', String.fromCharCode(e.which));
  var keyTyped = this.keyTyped || window.keyTyped;
  if (typeof keyTyped === 'function') {
    var executeDefault = keyTyped(e);
    if (executeDefault === false) {
      e.preventDefault();
    }
  }
};
```
@vipulrawat @lmccart if guys permit me, I would like to fix this issue.

**Comment by vipulrawat** [comment]
@vedhant Instead of using `e.which`, I think it's better to use `e.key` and update the keyboard events in p5. Reason being:
1. `e.which` is deprecated and may lose its effect in coming years with recent web engines.
2. `e.key` doesn't results out into Unicode. Also it has better fallback techniques like "dead key" or "unidentified key"

**Comment by vedhant** [comment]
@vipulrawat Yes you are right. We should use e.key instead of e.which for all of the keyboard events.
I also checked e.key value for onkeypress in firefox and it gives correct results for non character values.

Can you allow me to do the changes?

**Comment by vedhant** [comment]
```javascript
// Click any key to display it!
// (Not Guaranteed to be Case Sensitive)
function setup() {
  fill(245, 123, 158);
  textSize(50);
}

function draw() {
  background(200);
  text(key, 33, 65); // Display last key pressed.
}
```
In the second comment, why is it mentioned that it is not guaranteed to be case sensitive?

**Comment by vipulrawat** [comment]
@vedhant Using key will be good until unless it is not breaking anything else in p5. One thing that I recommend is that other people in the p5js community will review when you make the PR.

**Comment by ikselven** [comment]
@savvysiddharth Do you have a link to a bug report on Mozilla's Bugzilla for this?

**Comment by savvysiddharth** [comment]
here's the bug report on bugzilla,
https://bugzilla.mozilla.org/show_bug.cgi?id=968056
which got fixed by this bug which is tracked as firefox65+,
https://bugzilla.mozilla.org/show_bug.cgi?id=1496288
@ikselven

**Comment by ikselven** [comment]
Firefox 65 has been released today. I cannot reproduce the issue anymore and the example works fine now.
