### ISSUE TITLE
Auto-update libraries ? (used to be a p5-editor's feature)

### ISSUE THREAD

**Issue by ThatIsAPseudo** [processing/p5.js#3349]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [x] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other (update libraries)

#### New feature details:

I saw that the deprecated p5 desktop editor used to auto-update, and I guess it could as well be used offline with local libraries files.
Is there currently a way to do that within the `index.html` itself or through a JS script for our own projects ? Or are we doomed to manually update the lib files in our old projects ?

(I don't have the skills required to determine whether the `p5-mode.js` of the p5 editor repo is usable as it is just by adding a line to the `index.html` or not, but that would be the perfect solution)

**Comment by ThatIsAPseudo** [comment]
> Isnt there a cloud-based p5 file? If there is, you'll always have the latest file if you use that in index.html

Indeed but this means you use the online file, you don't save it in order to use it offline later. It would be better if the cloud-based file was downloaded when it's available so that it would still be available  without any connexion. For the moment it just gives an error when I'm in airplane mode : `Failed to load resource: net::ERR_INTERNET_DISCONNECTED`

**Comment by lmccart** [comment]
because things change from version to version, it is not recommended that the p5.js file is automatically updated. it's best if you make this update when you feel it is necessary, and modify your project and test to make sure everything works once you've switched versions. you can manually update the file, and you could use the [cdn link](https://cdnjs.com/libraries/p5.js/) for easier updating (you just need to change the version number, rather than download a whole new file).

I couldn't tell if you are talking about the [web editor](http://editor.p5js.org). in this case, each new project is created with the latest version of p5.js, but it is not automatically updated when new releases come out. you can manually update this by going into the index.html file and changing the version number for the p5.js link.

**Comment by ThatIsAPseudo** [comment]
Ok that makes sense
I suggested that because I just replaced old libs by new ones in all my projects (no compatibility issue so far), that took a lot of time

> I couldn't tell if you are talking about the web editor. in this case, each new project is created with the latest version of p5.js, but it is not automatically updated when new releases come out. you can manually update this by going into the index.html file and changing the version number for the p5.js link.

No I was talking about the [desktop editor](https://github.com/processing/p5.js-editor) and more precisely about [this file](https://github.com/processing/p5.js-editor/blob/master/app/modes/p5/p5-mode.js) that I found by googling "auto update p5js".
It contains the following piece of code that seems to auto-update the libraries by downloading them from Github :
```javascript
update: function(callback) {
    var url = 'https://api.github.com/repos/processing/p5.js/releases/latest';
    var libraryPath = Path.join('mode_assets', 'p5', 'empty_project', 'libraries');
    var fileNames = ['p5.js', 'p5.dom.js', 'p5.sound.js'];

    request({url: url, headers: {'User-Agent': 'request'}}, function(error, response, data){
      if (error) return;

      // filter assets to only include the filenames we want
      var assets = JSON.parse(data).assets.filter(function(asset){
        return fileNames.indexOf(asset.name) > -1;
      });

      // if remoteVersion != localVersion, download new version of each asset
      var remoteVersion = JSON.parse(data).tag_name;
      var localPathToP5 = Path.join(libraryPath, 'p5.js');

      var localVersionTag = getVersion(localPathToP5, function(localVersion) {
        if (remoteVersion != localVersion || !localVersion) {
          assets.forEach(function(asset) {
            var localPathToAsset = Path.join(libraryPath, asset.name);
            downloadAsset(asset.browser_download_url, localPathToAsset);
          });
        }
      });

    });

    function downloadAsset(remote, local) {
      request({url: remote, headers: {'User-Agent': 'request'}}, function(error, response, body){
        if (error) return;

        if (body.split('\n')[0].indexOf('/*! p5.') > -1) {
          fs.writeFile(local, body);
        }
      });
    }
},
```

What about to feature an `update` function that updates libraries from the Github repo, or even better that downloads the version passed as a parameter from the cloud-based files (all p5 versions are available there) ?
So that if you want to update automatically your libraries for each new project (or at the opposite keep a particular version), you can just put `update()` in the `setup` or write it in the console
