### ISSUE TITLE
`npm run dev` fails. open:dev not defined.

### ISSUE THREAD

**Issue by unjust** [processing/p5.js#3357]
Can't run `npm run dev`.

Fails with
```
Warning: Task "open:dev" not found. Use --force to continue.

Aborted due to warnings.
npm ERR! code ELIFECYCLE
npm ERR! errno 3
npm ERR! p5@0.7.2 dev: `grunt browserify connect open:dev watch:quick`
```

Looks like we are missing a script that was once there? 
Is there a new dev workflow and the documentation is out of date?

#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [ ] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 
- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

**Comment by lmccart** [comment]
I'm not able to reproduce this. Can you please respond to the bullet points under "Details about the bug", especially
- p5.js version:
- Web browser and version:

Thanks!
