### ISSUE TITLE
I just wanted to know how to use loadimage in asp.net mvc core

### ISSUE THREAD

**Issue by trobertsson** [processing/p5.js#3360]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [ ] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 
- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

**Comment by limzykenneth** [comment]
Hi @trobertsson, question about your code and usage are best for the [forum](https://discourse.processing.org/) as github issues are used for bug reports and feature requests. Thanks.
