### ISSUE TITLE
Load and update pixels from p5.Graphics problem

### ISSUE THREAD

**Issue by pashatechnic** [processing/p5.js#3363]
#### Nature of issue?

- [x] Found a bug

#### Most appropriate sub-area of p5.js?

- [X] Core/Environment/Rendering
- [X] Image

#### Which platform were you using when you encountered this?

- [X] Desktop/Laptop

#### Details about the bug: 

- Web browser and version: Chrome Version 70.0.3538.110 (Official Build) (64-bit)
- Operating System: MacOSX
- Steps to reproduce this:

I can only once successful load and update pixels from p5.Graphics element. Then, when I try draw some shapes and manipulate pixels again – all added shapes disappear and I returning to point when I updated pixels for the first time.

Basic code idea:

```
if (mouseIsPressed) {
    if (mouseButton == LEFT) {
      drawing.fill(51, 51);
      drawing.noStroke();
      drawing.rect(mouseX, mouseY, 20, 20);
    } else {
      drawing.loadPixels();
      burn(); // some manipulations with pixels
      drawing.updatePixels();
    }
  }
```

[See working example](https://editor.p5js.org/pashatechnic/sketches/rJ6Pamtk4)

**Comment by grege2** [comment]
Hi @pashatechnic 

I spent some time on this but couldn't solve it. Annoying. It must be a simple oversight about loading and restoring pixels, and jumping between the onscreen canvas and the offscreen graphics context. This happens a lot. Check your use of that very carefully, and check that some alpha gotcha is not happening. Anytime you blend with alpha there's room for error - accidentally supplying zero alpha can erase your rendering, all sorts.

Anyway my main point here is that this is probably the wrong forum for this question. For general coding problems that are not proven bugs in p5.js, you'd be better to post in the new Processing forum ..

https://discourse.processing.org/

Ciao e Buona Fortuna.
