### ISSUE TITLE
Ref page for p5.dom child() function omits to create child in one example

### ISSUE THREAD

**Issue by grege2** [processing/p5.js#3366]
#### Nature of issue?

- [x] Reference page error

The reference page for the p5dom child() function at ...
  http://p5js.org/reference/#/p5.Element/child

seems to have an omission in the third example:

  var div0 = createDiv('this is the parent');
  var elt = document.getElementById('myChildDiv');
  div0.child(elt); // use element from page

The element "myChildDiv' is not shown as created, and the getElementById() call will return null, and the child() call will fail.

I think there should be an extra line showing the creation of a DOM element with id "myChildDev".

A capable reader will realize that 'myChildDiv' can be any already-existing DOM element, but it would be better for the example to be complete IMO.

Cheers.

**Comment by lmccart** [comment]
thanks, I've added a clarifying comment that this example is demonstrating how things would work if there were already a div on the page with this id

**Comment by grege2** [comment]
Great. Sorry to be reporting such trivia when you are in a storm of ES6 updates and all the rest. Ciao.

**Comment by lmccart** [comment]
it's all helpful!
