### ISSUE TITLE
update developer docs to ES6

### ISSUE THREAD

**Issue by lmccart** [processing/p5.js#3367]
As part of the migration to ES6, the [developer_docs](https://github.com/processing/p5.js/tree/master/developer_docs) need to have code snippets and language updated from ES5 to ES6. 

All docs currently in the folder have been listed here, but not all of them have code snippets that need updating. These can be checked off once it's confirmed no update is needed.

* [x] [benchmarking_p5.md](https://github.com/processing/p5.js/blob/master/developer_docs/benchmarking_p5.md)
* [x] [creating_libraries.md](https://github.com/processing/p5.js/blob/master/developer_docs/creating_libraries.md)
* [x] [custom_p5_build.md](https://github.com/processing/p5.js/blob/master/developer_docs/custom_p5_build.md)
* [x] [design_principles.md](https://github.com/processing/p5.js/blob/master/developer_docs/design_principles.md)
* [x] [friendly_error_system.md](https://github.com/processing/p5.js/blob/master/developer_docs/friendly_error_system.md)
* [x] [inline_documentation.md](https://github.com/processing/p5.js/blob/master/developer_docs/inline_documentation.md)
* [x] [issue_labels.md](https://github.com/processing/p5.js/blob/master/developer_docs/issue_labels.md)
* [x] [preparing_a_pull_request.md](https://github.com/processing/p5.js/blob/master/developer_docs/preparing_a_pull_request.md)
* [x] [release_process.md](https://github.com/processing/p5.js/blob/master/developer_docs/release_process.md)
* [x] [supported_browsers.md](https://github.com/processing/p5.js/blob/master/developer_docs/supported_browsers.md)
* [x] [webgl_mode_architecture.md](https://github.com/processing/p5.js/blob/master/developer_docs/webgl_mode_architecture.md)

**Comment by dinesh196** [comment]
@Ajayneethikannan  since there are a number of pages, I would also like to help in updating the snippets and thus, this issue.

**Comment by lmccart** [comment]
closed with #3454
