### ISSUE TITLE
Add overview to /src/core/error_helpers.js (FES)

### ISSUE THREAD

**Issue by kjhollen** [processing/p5.js#3371]
Individual functions for the Friendly Error System are well documented in /src/core/error_helpers.js, but an overview of how these functions fit together would make this code easier to understand for contributors looking to get familiar with this part of the library. The idea here is to add a paragraph or list of bullet points of the order of operations for which FES functions are called when.

**Comment by EOstling** [comment]
If nobody has started working on this, I would like to take it.

**Comment by lmccart** [comment]
@EOstling we would welcome your work on this if you are still interested!
