### ISSUE TITLE
update p5.js build and release tasks to ES6

### ISSUE THREAD

**Issue by lmccart** [processing/p5.js#3372]
As part of the migration to ES6, the p5.js build and release tasks in the [tasks folder](https://github.com/processing/p5.js/tree/master/tasks) need to be checked and updated as needed from ES5 to ES6.

**Comment by Spongman** [comment]
maybe #3204 will be of some help?

**Comment by limzykenneth** [comment]
Is there a timeline/guide/steps for the transition to ES6 in general? I just saw a bunch of ES6 transition issues and PR but have no idea the criteria (in terms of target compatibility) or the priorities other than the milestones tags. Is it possible to draft a document/wiki on github to at least outline compatibility targets and even better a rough timeline?

**Comment by lmccart** [comment]
@limzykenneth I just added a document that represents a first draft of a [roadmap to 1.0](https://github.com/processing/p5.js/blob/master/developer_docs/roadmap.md) including ES6 transition, comments welcome on [this issue](https://github.com/processing/p5.js/issues/3418).

In terms of compatibility targets, does [this supported browsers doc](https://github.com/processing/p5.js/blob/master/developer_docs/supported_browsers.md) (needs some updating) address it? Or are you thinking of something else?

**Comment by limzykenneth** [comment]
The document is great, I'll have a closer look when I get a chance.

**Comment by LakshSingla** [comment]
@lmccart I would like to take up this issue, but since there were issues regarding the change of build systems and task runners ( #3409 #3425 ), is this issue still relevant ??

**Comment by LakshSingla** [comment]
@limzykenneth #3451 tackles this issue.

**Comment by lmccart** [comment]
closed with #3451

**Comment by limzykenneth** [comment]
I just noticed that although the tasks in the `tasks` folder are all updated, the `Gruntfile.js` file isn't fully updated yet.

**Comment by JaiKotia** [comment]
Hey I'd like to take up this issue @lmccart @limzykenneth

**Comment by limzykenneth** [comment]
@JaiKotia Go ahead, only `Gruntfile.js` needs to be updated.

**Comment by lmccart** [comment]
closed with https://github.com/processing/p5.js/pull/3628
