### ISSUE TITLE
Update Structure Reference Examples on p5js.org to ES6

### ISSUE THREAD

**Issue by mlarghydracept** [processing/p5.js#3373]
Update the **Structure** section of the [p5js reference](https://p5js.org/reference/) to ES6. This will entail updating all of the references in source files that have `@module Structure` at the top.

As a step forward in the transition to ES6 all of the reference examples on p5js.org should be updated to use ES6 standard. This will often mean simply switching 'var' to 'let' or in some cases [using es6 classes](https://github.com/processing/p5.js/issues/2215) where applicable. 

There are tons of resources online for learning about ES6. [Here is an interactive guide](http://stack.formidable.com/es6-interactive-guide/#/) that covers the biggest features.

**Comment by sanketsingh24** [comment]
Would like to work on this issue today :)
