### ISSUE TITLE
Add circle() function

### ISSUE THREAD

**Issue by L05** [processing/p5.js#3375]
Add circle() function for K-12 education/accessibility, as suggested in [this thread](https://github.com/processing/p5.js/issues/2305).

#### Nature of issue?

- [X] New feature request

#### Most appropriate sub-area of p5.js?

- [X] Core/Environment/Rendering

**Comment by vedhant** [comment]
Is this to be added to 2D Rendering?

**Comment by lmccart** [comment]
this method could just be an alias that calls `p5.prototype.ellipse(x, y, 2*r, 2*r)`

**Comment by vedhant** [comment]
Yup.
I would like to do it!

**Comment by AnimeshSinha1309** [comment]
Okay, seems like no one is working on this, hope it's okay for me to do this.

**Comment by nimishagarwal76** [comment]
#3419  resolves this issue

**Comment by lmccart** [comment]
addressed with https://github.com/processing/p5.js/pull/3419
