### ISSUE TITLE
Add square() function

### ISSUE THREAD

**Issue by L05** [processing/p5.js#3376]
Add square() function for K-12 education/accessibility, as suggested in [this thread](https://github.com/processing/p5.js/issues/2305).

#### Nature of issue?

- [X] New feature request

#### Most appropriate sub-area of p5.js?

- [X] Core/Environment/Rendering

**Comment by lmccart** [comment]
this method could just be an alias that calls `p5.prototype.rect(x, y, s, s)`

**Comment by montoyamoraga** [comment]
would that be adding to the file the src/core/shape/2d_primitives.js the following?
I am trying to figure it out.

p5.prototype.square = function(x, y, s) {
  p5.prototype.rect(x, y, s, s);
}

**Comment by lmccart** [comment]
@montoyamoraga I think this would do it, though I think you want to use `this.rect()` rather than `p5.prototype.rect()` so rectMode() is taken into consideration. and then adding documentation too. documentation could be based on the rect() docs and modified.

**Comment by lmccart** [comment]
resolved with https://github.com/processing/p5.js/pull/3393
