### ISSUE TITLE
More complete unit tests

### ISSUE THREAD

**Issue by outofambit** [processing/p5.js#3377]
We'd like to expand our unit tests to be more complete and cover more of the codebase.

This is a list of the areas we'd like to focus on. (It will be populated over time and then broken out into separate issues.)

* 

(This list will be informed by the findings of #3385)

**Comment by lmccart** [comment]
@outofambit I'm going to close this issue because I believe this is covered in https://github.com/processing/p5.js/issues/3567. if there are additional issues beyond what's outlined there, we can open additional tickets for them.
