### ISSUE TITLE
confirm/implement use of Promises across codebase

### ISSUE THREAD

**Issue by lmccart** [processing/p5.js#3378]
This one may already be done, but I'm opening an issue so that we can go through the codebase and confirm that Promises are used for all loadX() methods and anywhere else that a callback is used internally. Additional issues can be opened for areas discovered that require Promise implementation.

**Comment by limzykenneth** [comment]
Promises are currently polyfilled so considerations can be made about removing the polyfill as well

**Comment by ankur54** [comment]
I would like to work on this issue.

**Comment by dhuang612** [comment]
Hi, is this still available to work on?

**Comment by lmccart** [comment]
@dhuang612 it is!

**Comment by limzykenneth** [comment]
@aditya-shrivastavv This is actually quite a bit older than that and concerns converting old callback style async handling with `.then()` style promises and not async await which the codebase for the most part don't currently use. I'll close this for now as it's not terribly relevant anymore.
