### ISSUE TITLE
Update DOM Reference Examples on p5js.org to ES6

### ISSUE THREAD

**Issue by stalgiag** [processing/p5.js#3379]
Update the **DOM** section of the [p5js reference](https://p5js.org/reference/) to ES6. This will entail updating all of the references in source files that have `@module DOM` at the top. In this probably just the [p5.Element class](https://github.com/processing/p5.js/blob/master/src/core/p5.Element.js)

As a step forward in the transition to ES6 all of the reference examples on p5js.org should be updated to use ES6 standard. This will often mean simply switching 'var' to 'let' or in some cases [using es6 classes](https://github.com/processing/p5.js/issues/2215) where applicable. 

There are tons of resources online for learning about ES6. [Here is an interactive guide](http://stack.formidable.com/es6-interactive-guide/#/) that covers the biggest features.

**Comment by figraham** [comment]
I'll work on this.

**Comment by ihsavru** [comment]
@figraham are you still working on this?

**Comment by figraham** [comment]
Sorry I forgot about this. I'll finish it up soon.

**Comment by ankur54** [comment]
Is anyone working on this? I am willing to work on this asap. Would that be okay?
Or is this issue resolved?

**Comment by figraham** [comment]
I finished this a while ago but I've been having some problems with git. If someone else wants to work on it that's fine with me. Sorry for keeping this open so long. @ihsavru @ankur54

**Comment by ankur54** [comment]
Actually, yesterday I went on to update the syntaxes, but limzykenneth said that they are currently not migrating the library code base to ES6 yet. So he closed the pull request as of now.

**Comment by stalgiag** [comment]
@ankur54 just for clarity, the reason that pull request was closed is because it updated the library code to ES6. This issue is specifically asking for the reference examples to be update.

If anyone wants to update the reference examples to ES6, this issue is currently in need of help. Thanks!

**Comment by ihsavru** [comment]
i'd like to work on this

**Comment by ankur54** [comment]
@ihsavru I think its 1st come 1st serve basis. I am currently working on it.
@stalgiag can you please put the link for the "reference example" here? I am a bit confused. Sorry for the inconvenience.

**Comment by ankur54** [comment]
@stalgiag I can see that a few times inside the <code> </code>, cng, d and g are defined. Should I keep them as it is just changing var to let/const, or should I define it just once?

**Comment by ankur54** [comment]
@stalgiag I have made the necessary changes. I am closing the pull request.

**Comment by ihsavru** [comment]
> @ihsavru I think its 1st come 1st serve basis. I am currently working on it.
@ankur54 I think I came first but I saw @figraham  was already working, it's just so that nobody's effort is wasted, next time onwards please explicitly say that you are working on it because i started working as well and maybe mention the issue in your PRs so that others know there's an existing PR for the issue.

**Comment by stalgiag** [comment]
Yes @ihsavru you are right. Quoting from my statement above:

> Just make sure to get confirmation here so that multiple people don't work on it at once.

@ihsavru You have politely checked in on figraham's progress and you said that you would like to work on it directly after I said that someone is able to work on it.

@ankur54 I am going to close your pull request because at every turn you have ignored that someone else came before you and submitted pull requests without getting confirmation to work on it. There have to be community standards for how we interact with each other as one big team.

@ihsavru if you still wish to work on this that would be great. Hopefully your work-in-progress branch still exists. Thanks!

**Comment by ihsavru** [comment]
Working on it!

**Comment by ankur54** [comment]
@stalgiag @ihsavru I am terribly sorry for my ignorance and rudeness. To be honest, I didn't notice any pull request and thus commented to work on it. I am terribly sorry.

**Comment by stalgiag** [comment]
No sweat @ankur54 thanks for understanding!

**Comment by ankur54** [comment]
I am new to open source community, so I didn't know the ways to go about it. Hope you would forgive my ignorance.
