### ISSUE TITLE
Update Rendering Reference Examples on p5js.org to ES6

### ISSUE THREAD

**Issue by mlarghydracept** [processing/p5.js#3381]
Update the **Rendering** section of the [p5js reference](https://p5js.org/reference/) to ES6. This will entail updating all of the examples that fall under`@module Rendering`.

As a step forward in the transition to ES6 all of the reference examples on p5js.org should be updated to use ES6 standard. This will often mean simply switching 'var' to 'let' or in some cases [using es6 classes](https://github.com/processing/p5.js/issues/2215) where applicable. 

There are tons of resources online for learning about ES6. [Here is an interactive guide](http://stack.formidable.com/es6-interactive-guide/#/) that covers the biggest features.

**Comment by Remcodejong** [comment]
I'd like to work on this issue!
I guess I would first have to change var to let, and see if classes could be used instead of functions?

**Comment by mlarghydracept** [comment]
I think changing `var` to `let` should be enough in this case but if you think other changes are necessary then feel free to ask about specific suggestions on here. Just remember that the goal is to make sure that these examples are written for absolute beginners, so ES6 features only need to be used when they are foundational to how modern javascript is written.

**Comment by Remcodejong** [comment]
Just to confirm, I need to change the examples in the src file, wherevere where is a ```@module Rendering``` at the top, right?

**Comment by mlarghydracept** [comment]
@Remcodejong  yes that is correct. [There are some cases in which the module is set somewhere other than at the top of the file](https://github.com/processing/p5.js/blob/master/src/webgl/p5.RendererGL.js#L212). I will update all of the relevant issues to be more accurate when I get a chance. But yes, I think the best approach is to do a folder wide search for occurrences of `@module Rendering`.

**Comment by lmccart** [comment]
this is fixed with https://github.com/processing/p5.js/pull/3395
