### ISSUE TITLE
Update Data Reference Examples on p5js.org to ES6

### ISSUE THREAD

**Issue by stalgiag** [processing/p5.js#3382]
Update the **Data** section of the [p5js reference](https://p5js.org/reference/) to ES6. This will entail updating all of the examples that fall under `@module Data`.

As a step forward in the transition to ES6 all of the reference examples on p5js.org should be updated to use ES6 standard. This will often mean simply switching 'var' to 'let' or in some cases [using es6 classes](https://github.com/processing/p5.js/issues/2215) where applicable. 

There are tons of resources online for learning about ES6. [Here is an interactive guide](http://stack.formidable.com/es6-interactive-guide/#/) that covers the biggest features.

**Comment by clinckzone** [comment]
I would love to help out by working on this issue!

**Comment by hellonearthis** [comment]
Does that mean removing the ; as it's not needed in ES6  but prettier still wants it.

**Comment by michelefenu** [comment]
@hellonearthis I can not figure out if you're already working on this :) Otherwise I can work on it
