### ISSUE TITLE
update webgl lighting examples

### ISSUE THREAD

**Issue by lmccart** [processing/p5.js#3383]
Some of the webgl examples are based on an old version of the codebase, and values used no longer make sense. Do a pass over all lighting examples in the reference and confirm each displays correctly and makes sense with the current codebase value ranges.

**Comment by stalgiag** [comment]
I am not sure that I see any major problems with any of the examples in the [ Lighting section of reference.](https://p5js.org/reference/#group-Lights,%20Camera). Maybe I am missing something?

@vibss2397 I think you might be able to make an improvement to the [directional light example](https://p5js.org/reference/#/p5/directionalLight) by bringing the light to the camera side of the sphere on the z-axis. A small negative value in the z-argument for `directionalLight()` in the example might make the movement of the light more legible.
