### ISSUE TITLE
Measure Unit Test Coverage

### ISSUE THREAD

**Issue by outofambit** [processing/p5.js#3385]
Instrument the unit test suite so we can see which parts of the codebase are well tested and which need more coverage.

Some relevant libraries and services that might work for this:
* [Istanbul + nyc](https://istanbul.js.org/docs/tutorials/mocha/)
* [CodeCov](https://codecov.io)

**Comment by vipulrawat** [comment]
One thing but might not be preferable as p5.js is already built up on mocha.
If p5.js is targeting whole new set of paradigm with all es6 features, then one can think on migrating to [jest](https://jestjs.io/). 
Reason being:
- I think many unit tests are missing, so anyways lots of new unit tests are going to be written.
- [Istanbul is inbuilt in jest](https://istanbul.js.org/docs/tutorials/jest/).

**Comment by rakeshcheekatimala** [comment]
I want to join as a contributor, I have a basic understanding of Jest and writing Unit Test Cases. Please let me know your thoughts.

**Comment by outofambit** [comment]
I started working on this and am hitting a number of unexpected bumps to completing it. (Currently, I am fighting with instrumenting the code and uglifyjs's syntax parsing limitations.) Will update as things progress! 🚀

**Comment by ihsavru** [comment]
Hi @outofambit, I was hoping this can be completed before writing more unit tests. I would like to help with this.

**Comment by outofambit** [comment]
been researching this and why the standard https://github.com/tandrewnichols/grunt-simple-nyc doesn't seem to work for us. i will have to do something similar to the approach described in this tutorial: https://www.engineyard.com/blog/measuring-clientside-javascript-test-coverage-with-istanbul
