### ISSUE TITLE
Update Events Reference Examples on p5js.org to ES6

### ISSUE THREAD

**Issue by mlarghydracept** [processing/p5.js#3386]
Update the **Events** section of the [p5js reference](https://p5js.org/reference/) to ES6. This will entail updating all of the references in source files that fall under `@module Events`.

As a step forward in the transition to ES6 all of the reference examples on p5js.org should be updated to use ES6 standard. This will often mean simply switching 'var' to 'let' or in some cases [using es6 classes](https://github.com/processing/p5.js/issues/2215) where applicable. 

There are tons of resources online for learning about ES6. [Here is an interactive guide](http://stack.formidable.com/es6-interactive-guide/#/) that covers the biggest features.

**Comment by hellonearthis** [comment]
But prettier doesn't like you not having ; on the end of lines and in ES6 they are not needed.

**Comment by limzykenneth** [comment]
@hellonearthis Default setting of prettier [recommends semicolons](https://prettier.io/docs/en/options.html#semicolons), they were optional since a long time ago but this discussion is already covered in another issue.
