### ISSUE TITLE
Update Lights, Camera Reference Examples on p5js.org to ES6

### ISSUE THREAD

**Issue by mlarghydracept** [processing/p5.js#3392]
Update the **Lights, Camera** section of the [p5js reference](https://p5js.org/reference/) to ES6. This will entail updating all of the examples that fall under `@module Lights, Camera`.

As a step forward in the transition to ES6 all of the reference examples on p5js.org should be updated to use ES6 standard. This will often mean simply switching 'var' to 'let' or in some cases [using es6 classes](https://github.com/processing/p5.js/issues/2215) where applicable. 

There are tons of resources online for learning about ES6. [Here is an interactive guide](http://stack.formidable.com/es6-interactive-guide/#/) that covers the biggest features.

**Comment by burkus** [comment]
Most of these seem pretty simple, would just changing instances of `var` to `let` be good? Do you want values that are never changed to be to constant? Also, do you want to replace all `function` instances with constant arrow function declarations?

I think some regex search and replace could update all of that, although the change is somewhat arbitrary unless it's purely for consistency.
