### ISSUE TITLE
createHTML for html5 video not working

### ISSUE THREAD

**Issue by liasomething** [processing/p5.js#340]
https://github.com/lmccart/itp-creative-js/wiki/Week-5#global-and-instance-mode

if i try this example in the p5 editor, then i get the error:
9: Uncaught ReferenceError: createHTML is not defined

// Video
var video;

// Drawing context
// Temporary as eventually p5 may support drawing video into canvas directly?
var context;

function setup() {
  video = createHTML('<video id=\'vid\'><source src=\'fingers.mov\'></video>');
  video = document.getElementById('vid');
  video.play();

  var canvas = createCanvas(640, 360);
  // need to keep track of the context to draw the video
  context = canvas.elt.getContext('2d');
}

function draw() {
  background(51);
  // Draw video into canvas
  context.drawImage(video,0,0,width,height);
};

**Comment by ferrelucas** [comment]
I have run into the same issue with the documentation :T 

I am just starting to learn about p5.
I would like to know if, after some readings and tests to understand how to use it properly, I could update some parts of the documentation.

I think the WIki's samples are a great way to receive new users (:

**Comment by lmccart** [comment]
@ferrelucas yes updates would be most welcome!
