### ISSUE TITLE
On my project in git don't finish to load canvas 

### ISSUE THREAD

**Issue by dbistuer** [processing/p5.js#3412]
Hi there! 

#### Nature of issue?

- [ X] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ X] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [] Mobile/Tablet (touch devices)
- [X ] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.7.2
- Web browser and version: Firefox 62.0.3
- Operating System: Ubuntu 18.04 64bits
- Steps to reproduce this:
Ive develop a local project using p5.js library. In local using git with atom local server, works ok, but when i create a gh-pages and upload to github, the project gets stuck on loading the canvas.
No error or warning message is displayed in the Console or Developer Web tools.
I attatch the link to the project: https://github.com/dbistuer/comecocos
( if you download the repo for example downloading the zip file, and unzip in your desktop you can test that works ok, but the same code in github doesnt.)

**Comment by limzykenneth** [comment]
From just looking at your page, there are errors about missing variable reference, `myPacman` specifically. If `preload` throws an error such as this, it will not finish and thus the sketch will not run. Problrms with debugging your own code are best posted on the [forum](https://discourse.processing.org/), github is used mostly for bug reports or feature request. If you can determine it is indeed a bug with the library you can post a new issue here. Thanks.
