### ISSUE TITLE
invalid warning during 3d `bezier` call

### ISSUE THREAD

**Issue by Spongman** [processing/p5.js#3414]
~~current master (not 0.7.2)~~ fef6c41

when running the `bezierDetail` example, the following invalid error is given:

> You must first call texture() before using vertex() with image based u and v coordinates

**Comment by Spongman** [comment]
looks like this was introduced here: fef6c41e2c1c896790ad87a447f6af8c8735f08e

@aferriss can you take a look?

**Comment by aferriss** [comment]
@spongman happy to look but I'm sans computer for the next couple weeks so it might be a little while.

**Comment by aferriss** [comment]
I finally had a chance to look this over and filed https://github.com/processing/p5.js/pull/3483 which should hopefully fix in these instances.

**Comment by jdeboi** [comment]
this appears to be a problem in v1.5.0 in WEBGL mode? 

[example here](https://editor.p5js.org/jdeboi/sketches/nw2SMkGzn)
