### ISSUE TITLE
createColorPicker() from p5.dom is Missing from Reference

### ISSUE THREAD

**Issue by figraham** [processing/p5.js#3422]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other (specify if possible)
part of p5.dom

#### Details about the bug: 

`createColorPicker()` is missing from reference. I saw that @TanviKumar worked on this feature during GSOC and I saw a screen shot of their reference [here](https://cdn-images-1.medium.com/max/1200/0*5AoWN3onIwiOCie4). When I navigated to that url seen in the screenshot there's nothing there. I looked in the p5.dom reference but it wasn't in there. I then did a [search of the site for 'createColorPicker'](https://www.google.com/search?q=createColorPicker+site:p5js.org&nfpr=1&sa=X&ved=0ahUKEwiQ_Iy5_rffAhUnl1QKHRx-ASgQvgUILCgB&biw=1366&bih=632) which only showed a web editor sketch. I was able to [recreate the example using p5 and p5.dom 0.7.2 in the web editor](https://editor.p5js.org/figraham/sketches/SJ9vUWAeV). So `createColorPicker()` should be in the current reference unless I'm mistaken.

- p5.js version:  0.7.2

Related Links:
[Original color picker issue.](https://github.com/processing/p5.js/issues/2504)
[Pull Request for createColorPicker().](https://github.com/processing/p5.js/pull/3089)
[Forum discussion about a color picker which sparked this issue.](https://discourse.processing.org/t/looking-for-a-p5-js-color-chooser-widget/6868/4)

**Comment by Ajayneethikannan** [comment]
@limzykenneth Could this issue be also caused due to the same problem as in #3444 ?
The last time **data.json** file was updated,  was in this commit,
https://github.com/processing/p5.js-website/commit/4425d5d2815c261a9748808efbfe8805dc65258d (May 2018)
and the **createColorPicker** was added afterwards through this commit
ef00da5d0481d36c5a096b1b910ae126e1d69642 (July 2018)

**Comment by limzykenneth** [comment]
Probably yes, the reference is stuck on 0.6.1 version of p5.js

**Comment by Ajayneethikannan** [comment]
After the updation of the reference , the createColorPicker examples can be seen in the website , but the p5 and p5-dom versions are presently in v0.5.4 (October 20, 2016), so the example is throwing reference error currently. Should I make a pull request by updating the two files (p5.min.js and p5-dom.min.js) or should this be handled in a different way ? Help please @limzykenneth !

**Comment by limzykenneth** [comment]
I'm not sure I understand what you mean. The version of p5.js and p5.dom.js on the website are both 0.7.3 at the moment. `createColorPicker`'s example is also working, just the layout needs to be tweaked.

**Comment by Ajayneethikannan** [comment]
Oh , I am really sorry ! I must have made a mistake while checking. Sorry for disturbing you!
