### ISSUE TITLE
Current solution encoding saveStrings() to UTF-8 is not adequate for all situations

### ISSUE THREAD

**Issue by faxinadu** [processing/p5.js#3423]
#### Nature of issue?

- [ x] Found a bug
- [ x] Existing feature enhancement

#### Most appropriate sub-area of p5.js?
- [x ] IO

#### Which platform were you using when you encountered this?

- [x] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop

#### Details about the bug: 

- p5.js version: p5.js v0.7.2 September 02, 2018
- Web browser and version: Chrome 1.0.3578.98 (Official Build) (64-bit) 
- Operating System: Windows 7

- Steps to reproduce this:

```
`var words = 'apple bear cat dog';

// .split() outputs an Array
var list = split(words, ' ');

createButton('save')
.position(10, 10)
.mousePressed(function() {
  saveStrings(list, 'nouns.txt');
});`
```

saveStrings enforced encoding to UTF-8 is probably great and I understand the logic behind doing it, but there are situations where you may want to save strings, for example as a Windows notepad txt file, that is to be used by the user later and not as source for arrays or variables in the code. Currently I have such a situation and as I understand it there is no parameter in saveStrings that allows overriding default encoding.

Another small issue is p5js reference makes no mention of this, had to dig google and find this on the Processing reference, maybe this should be copied to the p5js reference as well:
> Starting with Processing 1.0, all files loaded and saved by the Processing API use UTF-8 encoding. In earlier releases, the default encoding for your platform was used, which causes problems when files are moved to other platforms.

#### Feature enhancement details:
Optional argument (maybe a boolean?) for the saveStrings() method allowing switching between Windows and Unix line breaks.

**Comment by jatin33** [comment]
Hey, @faxinadu 
Could you please specify if the problem is specifically line-break related?

**Comment by limzykenneth** [comment]
UTF-8 encoding should not affect behaviour of the saved file. p5.js does not explicitly set the saved file encoding to UTF-8, the browser decides this based on the type.

It seems the problem you have is line break character (`\n` vs `\r\n`), the default here is indeed Unix style `\n` and another optional parameter can probably be added to toggle between the two. UTF-8 encoding have nothing to do with line break though (`\r\n` can be encoded in UTF-8 with no problem)

**Comment by yashpandit** [comment]
@lmccart - I can take this up.

**Comment by lmccart** [comment]
@yashpandit wonderful!
