### ISSUE TITLE
ES6 Class Extension

### ISSUE THREAD

**Issue by bigmstone** [processing/p5.js#3424]
I see mention of ES6 support around several issues. Most notibly [this comment](https://github.com/processing/p5.js/issues/2215#issuecomment-334813299) is closest to what I'm after. I'm brand new to P5. So I know little of its internals. I hacked together [this](https://github.com/bigmstone/p5.js/pull/1) tonight to get somewhat what I'm after. ~Though I don't love the `super` API.~ Is there any plans on making something like this work? My hack is trying to keep backwards compatibility. ~Can anyone think of a cleaner API to communicate P5 is extending another class?~

Edit: In a "duh" moment after some sleep I got rid of the need to pass any arguments to `super`.

#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [x] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other (specify if possible) (syntax?)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

**Comment by bigmstone** [comment]
Playing around further with that branch. Creating a second class and the experience broke down a bit. Worked up a solution [here](https://gist.github.com/bigmstone/5b80af4a2f4635aa19c7044792bc598e). `Builder` could be worked into P5, and only copy over public methods instead of the kitchen sink. I'm recreating @shiffman's latest snowflake to see if there's anything obvious I'm missing.

**Comment by ankur54** [comment]
@bigmstone are you still working on this, is it still open, can I help in this issue? I would really love working on this issue, to add additional features of ES6. If possible please do guide. Thank you.

**Comment by bigmstone** [comment]
@ankur54 I started this issue to see what the feedback would be from the maintainers on this approach or commentary about alternate approaches (Per [guidelines](https://github.com/processing/p5.js/tree/master/developer_docs#how-to-contribute)). I don't have any intention of continuing the work at this point. A such I will close the issue. Feel free to re-open if appropriate.
