### ISSUE TITLE
endShape(CLOSE) won't treat the beginning point like a join

### ISSUE THREAD

**Issue by zzhhbyt1** [processing/p5.js#3430]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [X] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [X] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: v0.7.2 (September 02, 2018)
- Web browser and version:  Firefox 64.0 (20181206201918)
- Operating System: Windows 10 Pro 1809 (OS Build 17763.195)

#### Steps to reproduce this:

I first found this strange behavior during completing my course assignment and now confirmed when playing around with `p5.gui`'s example - [`quicksettings-1`](https://bitcraftlab.github.io/p5.gui/examples/quicksettings-1/).
![image](https://user-images.githubusercontent.com/11014745/50507094-eee7b900-0ab6-11e9-9314-ad8b3a255f75.png)
Notice how the top/beginning point is rendered like a `strokeCap(ROUND)` rather than a `strokeJoin(MITER)`.

##### Code:

```javascript
beginShape();
for(var i = 0; i < 2 * n; i++) {
	var d = (i % 2 === 1) ? d1 : d2;
	var angle = PI / n * i;
	var px = x + sin(angle) * d / 2;
	var py = y - cos(angle) * d / 2;
	vertex(px, py);
}
endShape(CLOSE);
```
Is this by design?
Reference to [original issue](https://github.com/bitcraftlab/p5.gui/issues/14) which didn't get replied from `p5.gui`'s developer.

#### Feature enhancement details:
Maybe make the begin and end point rendered just like a join point, or simply demonstrate that this is by design in the documents?

**Comment by lmccart** [comment]
is this the same issue being described here: https://github.com/processing/p5.js/issues/3352?

**Comment by zzhhbyt1** [comment]
> 
> 
> is this the same issue being described here: #3352?

I've seen that issue. I think mine is different.
In this issue I'm talking about the line's "Cap" shape is not intended but my line did close.
In his issue he's talking about the line won't even close.

**Comment by lmccart** [comment]
I see, thank you for the clarification.
