### ISSUE TITLE
Input file selecting and callback

### ISSUE THREAD

**Issue by dlefur** [processing/p5.js#3442]
#### New feature details:

Hello,
After selecting an **input file** from the html file, how to launch the callback ?
Would it be possible to have something like : 
`let inputFile=select("#inputFile");`
`inputFile.change(myCallback);`

Cordially.

**Comment by lmccart** [comment]
Something like this?

```js
var input;

function setup() {
  input = createFileInput(handleFile);
}

function handleFile(file) {
  print(file);
}
```

**Comment by dlefur** [comment]
Hello,
yes, I know that solution. 
But is it possible to use an input file created in the html file (with select()) and then select it and use it in the p5.js file ?
I do it for an input text but I don't know if it is possible for an input file...

**Comment by lmccart** [comment]
Can you clarify what you mean by "input file"?

**Comment by dlefur** [comment]
I mean `<input type="file" id="inputFile">`.

**Comment by Spongman** [comment]
Try `inputFile.changed(myCallback)`

**Comment by dlefur** [comment]
Let see my sketch : [https://editor.p5js.org/dlefur@gmail.com/sketches/rygPFZrME](https://editor.p5js.org/dlefur@gmail.com/sketches/rygPFZrME)

The callback is really called. But I don't know how to access the file. It returns an event.

**Comment by lmccart** [comment]
something like this should work
```js
let inputFile;

function setup() {
  noCanvas();
	inputFile= select("#inputFile");
	inputFile.changed(filePicked);
}


function filePicked(data) {
  var files = data.target.files;
  console.log(files[0].name)
}

```
more here: https://www.html5rocks.com/en/tutorials/file/dndfiles/

**Comment by dlefur** [comment]
Thank you.
I did manage to access the content : https://editor.p5js.org/dlefur@gmail.com/sketches/rygPFZrME

But it is not as simple as I thought. I will use createInputFile() ...

Cordially.
