### ISSUE TITLE
createFile Input reference example not rendering

### ISSUE THREAD

**Issue by lmccart** [processing/p5.js#3444]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [x ] Documentation

#### Details about the bug: 

The reference example for [createFileInput](https://p5js.org/reference/#/p5/createFileInput) is not rendering correctly.

**Comment by Ajayneethikannan** [comment]
I would like to work on this issue!

**Comment by limzykenneth** [comment]
@Ajayneethikannan Do go ahead! It is missing HTML tags so it isn't rendering correctly.

**Comment by Ajayneethikannan** [comment]
@limzykenneth I checked the example present in the inline documentation of the createFileInput method, 
and it contains the proper HTML tags.<br/>
I checked the commit history of p5.dom.js and the tags were fixed a long time ago (https://github.com/processing/p5.js/commit/3f99a89ad714cb9483f7354179e167d5392c5761#diff-84dfcaf5d56a24f4ee13a32c644817b0)

But I found that the data.json and data.min.json file in p5.js-website/src/templates/pages/reference 
do not contain the 'code' and 'div' tags, and changing them, properly renders the examples in the p5.js-website

Should I just change those two files and make a pull request (in p5.js-website repository) ? 
Please, can you  explain how the inline examples(stored in this repository) are converted into documentation(in p5.js-website)  for the reference ?

**Comment by limzykenneth** [comment]
@Ajayneethikannan Actually on further investigation this is a different problem linked to the website itself. You can checkout the [developer docs](https://github.com/processing/p5.js/tree/master/developer_docs) for more information about how things are built.

@lmccart The `data.min.json` version has reverted back to 0.6.1, I thought we managed to fixed that already? Will look into this further especially with the new travis build stuff.

**Comment by lmccart** [comment]
@limzykenneth I tried running this and got this error:
```
(node:99289) UnhandledPromiseRejectionWarning: Error: Error: Command failed: rm -rf p5-website/ && git clone -q https://github.com/undefined/p5.js-website.git p5-website
remote: Repository not found.
fatal: repository 'https://github.com/undefined/p5.js-website.git/' not found

    at /Users/lmccart/Documents/p5/p5.js/tasks/release/release-docs.js:82:17
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
(node:99289) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:99289) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
I'm guessing I'm missing a login or token setting. Is this `grunt release-docs` command in the docs somewhere where I can see if there are further instructions?

**Comment by Spongman** [comment]
it looks like `release-docs` can't be run directly. you would need to run `release-p5` in order to initialize the configuration correctly, however that's going to push a whole new release out. maybe try commenting out all but step 4 in `release-p5.js` ?

**Comment by lmccart** [comment]
ok, looks like we're good now. I ran the command as you instructed and docs updated to 0.7.2, which is the latest. agree this doesn't need to be documented publicly.
