### ISSUE TITLE
Can we use image instead of video in createCapture() to add Images in dataset

### ISSUE THREAD

**Issue by a4ankit** [processing/p5.js#3445]
Hi,

We are using FeatureExtraction to get classification and regression since it using   `video = createCapture(VIDEO);` so can we use images in place of video to add our images in the dataset and also want to train that image.

I'm using https://ml5js.org/docs/custom-classifier and https://ml5js.org/docs/custom-regression for reference.

Thanks

**Comment by lmccart** [comment]
this should be possible using `VIDEO`, and then writing code to save out individual frames as images.
the github issues here are a good place for bugs and issues with the p5.js library itself. for questions about writing your own code, tests, or following tutorials, the [forum](https://discourse.processing.org/) is the best place to post.
