### ISSUE TITLE
beginShape(TRIANGLE_STRIP) is not working properly

### ISSUE THREAD

**Issue by closebang** [processing/p5.js#3452]
#### Nature of issue?

- [x] Found a bug

#### Most appropriate sub-area of p5.js?
- [x] WebGL

#### Which platform were you using when you encountered this?

- [x] Desktop/Laptop

#### Details about the bug: 

- p5.js version: 0.7.2
- Web browser and version: Chrome 71.0.3578.98, Firefox 63.0.3
- Operating System: MacOS 10.14
- Steps to reproduce this:
In the WEBGL its look like the "beginShape(TRIANGLE_STRIP);" is not working properly

Live:
https://gusty-ambulance.glitch.me/

```
let cols, rows;
let scl = 20;

let w = 600;
let h = 600;

function setup() {
  createCanvas(600, 600, WEBGL);

  cols = width / scl;
  rows = height / scl;
}

function draw() {
  background(0);
  stroke(255);
  noFill();
  
  rotateX(PI/3);

  translate(-width/2, -height/2);
  
  for(let x = 0; x < rows; x++) {
    beginShape(TRIANGLE_STRIP);
    for(let y = 0; y < cols; y++) {
      vertex(x*scl, y*scl);
      vertex(x*scl, (y+1)*scl);
    }
    endShape();
  }
  
}

```

What would you expect to happen?
![bildschirmfoto 2019-01-14 um 10 28 51](https://user-images.githubusercontent.com/7612464/51104801-750a3c00-17e7-11e9-82a7-6cc925d2bb33.png)

What actually happens?
![bildschirmfoto 2019-01-14 um 10 27 58](https://user-images.githubusercontent.com/7612464/51104759-4d1ad880-17e7-11e9-87e7-8ee48fc2022e.png)

**Comment by AdilRabbani** [comment]
Are you sure your loop is correct? This one gives me correct results for both 2D and 3D.

```
for(let x = 0; x < rows; x++) {
    beginShape(TRIANGLE_STRIP);
    for(let y = 0; y < cols; y++) {
      vertex(x*scl, y*scl);
      vertex((x+1)*scl, (y+1)*scl);
    }
    endShape();
}
```

2D            |  3D
:-------------------------:|:-------------------------:
![2d](https://user-images.githubusercontent.com/15272015/51131186-ca2e6800-1850-11e9-8a37-874a7d72ef4e.PNG)|![3d](https://user-images.githubusercontent.com/15272015/51131192-cef31c00-1850-11e9-9ba9-6b051dedf533.PNG)

**Comment by closebang** [comment]
Hey @AdilRabbani,

I tried your loop and its look diffrent for me.

Which OS / Browser are you using?

<img width="303" alt="bildschirmfoto 2019-01-14 um 20 02 40" src="https://user-images.githubusercontent.com/7612464/51134277-63e91b80-1837-11e9-89eb-e97d4e93aa87.png">

**Comment by closebang** [comment]
Hey,

yes thanks, with building from Master is helping 👍 

I also found a mistake made by me. In the first loop Its have to be y ( for the rows) and x (for the cols )🙈 

Here compare the two builds:

Website CDN 0.7.2:
<img width="299" alt="bildschirmfoto 2019-01-14 um 21 51 21" src="https://user-images.githubusercontent.com/7612464/51140555-15437d80-1847-11e9-97fc-61def895c37e.png">

Build from Master from 14.01.2019 with version 0.7.2:
<img width="302" alt="bildschirmfoto 2019-01-14 um 21 50 53" src="https://user-images.githubusercontent.com/7612464/51140526-107ec980-1847-11e9-89c0-2d085a59825d.png">

Live:
https://glitch.com/edit/#!/ruby-tax
