### ISSUE TITLE
saveCanvas() works fine but it cant save the p5s dom 

### ISSUE THREAD

**Issue by nour023** [processing/p5.js#3453]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [ ] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 
- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

**Comment by lmccart** [comment]
This is the correct behavior, saveCanvas() saves only the canvas element, created by createCanvas(). I think there's not any good way to save out the whole screen from within the JS code, easiest would be to take a screenshot or to use a program to automate this task.

**Comment by nour023** [comment]
that's a pity .. cause i have some elements like icons  created by  "createDiv" and saveCanvas() saves  the whole page and my page's width and hieght are quite bigger than innerWidth and innerHeight .. screenshot will take only (innerWidth*innerHeight) .. thank you :)

**Comment by nour023** [comment]
hello

Le lun. 14 janv. 2019 à 16:55, Lauren McCarthy <notifications@github.com> a
écrit :

**Comment by hellonearthis** [comment]
I did a little googling on this,  was hoping I could find a way to access chrome's command panel to use it's screenshot features via javascript. nope.

Next I saw that people were converting the dom to svg then  rendering that to a canvas.
Here's a few links.
http://html2canvas.hertzen.com/documentation
https://github.com/miohtama/Krusovice/blob/master/src/tools/html2svg2canvas.js
http://docs.w3cub.com/dom/canvas_api/drawing_dom_objects_into_a_canvas/

Maybe this could be turned into a p5 command?
