### ISSUE TITLE
Save Images and Train them and get results

### ISSUE THREAD

**Issue by a4ankit** [processing/p5.js#3459]
We are using 'imageClassifier' and 'featureExtractor' methods to recognize images using ml5-library and p5.js. We have successfully recognized the images with your Pre-trained model.
We are successfully implemented featureExtractor.classification(video, VideoReady) function to add a poses using a video element. But now we want to add an image using featureExtractor's addImage() function as it shows that now featureExtractor works with images.

We require something which takes images from local and trains them, and after training of those images if we provide anyone image from local to recognize. That will give us a good result.

We tried with 'video = captureCreate(VIDEO)' but it taking video frame as input, we wanted to provide image as input and wanted to save for further recognization.

Thanks

**Comment by lmccart** [comment]
the github issues here are a good place for bugs and issues with the p5.js library itself. for questions about writing your own code, tests, or following tutorials, the [forum](https://discourse.processing.org/) is the best place to post. thanks!
