### ISSUE TITLE
improvements for reference materials

### ISSUE THREAD

**Issue by lmccart** [processing/p5.js#346]
- [x] createCanvas says "Appends to the container node if one is specified, otherwise appends to body..." could use a little more clarification and links to relevant sections in [overview tutorial](https://github.com/lmccart/p5.js/wiki/p5.js-overview). and example of this in the ref.

- [x] p5.dom page: include some info about appended items following flow of the page, how to use position() to absolutely position them. more generally, need to finish up the overdue "p5.dom: beyond the canvas" tutorial

- [x] p5.Element.style(): a little more info, should it be a string or something else (ex: `fingers.style('opacity', 0.5);` vs `mylink.style('color', '#00ff00');`)

- [ ] reference may need to include p5.dom and p5.sound API, it's hard to find them otherwise. or else clear link to these pages.

- [x] createVideo, createSound: explanation for using an array for input src as option instead of single string src

- [ ] p5.Color

- [x] add info/documentation for static functions in p5.Vector

**Comment by marti1125** [comment]
Hi @lmccart could you tell me more about the first task, please

**Comment by lmccart** [comment]
hi @marti1125. this one has already been addressed actually, thanks!
