### ISSUE TITLE
beginShape close end is not working 

### ISSUE THREAD

**Issue by closebang** [processing/p5.js#3460]
#### Nature of issue?

- [x] Found a bug

#### Most appropriate sub-area of p5.js?

- [x] Core/Environment/Rendering

#### Which platform were you using when you encountered this?
- [x] Desktop/Laptop

#### Details about the bug: 

- p5.js version: master from 17.01.2019
- Web browser and version: Chrome, Firefox
- Operating System: MacOS Mojave
- Steps to reproduce this:

I did some learning and saw that when I using the latest master, some unexpected behavior accourse.
When I use the version from the p5.js Website, this error don't happen.

Version with CDN from the p5.js Website V 0.7.2
Live:
https://wheat-swordfish.glitch.me/
Source:
https://glitch.com/edit/#!/wheat-swordfish

![bildschirmfoto 2019-01-17 um 12 08 13](https://user-images.githubusercontent.com/7612464/51314667-9de13a00-1a50-11e9-8f55-1e7828c94f58.png)

Version with lastest master from 17.01.2019
Live:
https://helpful-cello.glitch.me/
Source:
https://glitch.com/edit/#!/helpful-cello

![bildschirmfoto 2019-01-17 um 12 08 23](https://user-images.githubusercontent.com/7612464/51314668-9faafd80-1a50-11e9-9a6b-57858133da6a.png)

Where I think the error is related:
```
push()
  noFill();
  beginShape();
  for(let i = 0; i < wave.length; i++) {
  	vertex(i, wave[i]);
  }
  endShape();
pop();

```

What should happen:

![bildschirmfoto 2019-01-17 um 12 11 22](https://user-images.githubusercontent.com/7612464/51314850-17792800-1a51-11e9-9417-8fc18a61793d.png)

What happen:

![bildschirmfoto 2019-01-17 um 12 11 29](https://user-images.githubusercontent.com/7612464/51314853-1b0caf00-1a51-11e9-89ad-0ab1d9aadf41.png)

**Comment by sanketsingh24** [comment]
This was recently implemented in #3433 by @AdilRabbani. Though this behaviour is certainly incorrect.

**Comment by AdilRabbani** [comment]
Before #3433 closePath() was being called after stroke() in the function `p5.Renderer2D.prototype._doFillStrokeClose()`. Looking at a [simple example](https://www.w3schools.com/tags/canvas_closepath.asp), it is clear that closePath() doesn't really 'close path' if it is called after stroke(). So it seems that the method wasn't really doing anything in the function before #3433.

I apologize that I didn't test this on other examples before submitting the pull request. I can submit another pull request to revert the changes. But it seems we have some issue here. After carefully testing on different shapes, I have observed that without closePath() we won't be able to properly close shapes with large stroke weight. For example, making a hexagon using beginShape() would still result in a round stroke at the last vertex. This can't be fixed even after changing the strokeCap to 'SQUARE' or 'PROJECT'.

```
function setup()
{
  createCanvas(600, 600);
  noLoop();
  stroke(100, 100, 100);
  strokeWeight(50);
  background(240);
}

function draw()
{
  translate(-50, 0);
  ngon(6, 150, 300, 150);
  translate(200, 0);
  strokeCap(SQUARE);
  ngon(6, 150, 300, 150);
  translate(200, 0);
  strokeCap(PROJECT);
  ngon(6, 150, 300, 150);
}

function ngon(n, x, y, d) {
  beginShape();
  for(var i = 0; i < n; i++) {
    var angle = TWO_PI / n * i;
    var px = x + sin(angle) * d / 2;
    var py = y - cos(angle) * d / 2;
    vertex(px, py);
  }
  endShape(CLOSE);
}
```
<p align="center">
<img src="https://user-images.githubusercontent.com/15272015/51346046-6e691680-1abe-11e9-8d5e-c2961cfe7dd4.PNG"></p>

Maybe use closePath() only when `closeShape` is true? :confused: Can submit this pull request as well but would need approval from other contributors.

**Comment by AdilRabbani** [comment]
@closebang @sanketsingh24 would you care to test #3462?
