### ISSUE TITLE
Feature request: resetShader()

### ISSUE THREAD

**Issue by sanketsingh24** [processing/p5.js#3461]
#### Nature of issue?
- [x] New feature request

#### Most appropriate sub-area of p5.js?

- [x] WebGL (Shader)

#### New feature details:
In Processing, resetShader() is a function which restores the default shader. Wouldn't it be nice if it 
is also present here? There are always some workarounds, but this will surely be easier to use, for both the beginners (Like me) and for the experienced one's too. 

If agreed upon, I have an approach in my mind to implement this and will work towards this. :)

**Comment by vedhant** [comment]
This feature sounds nice. Although I'm a beginner in webgl I would like to work on this feature. I would like to listen to your approach to implement this.
