### ISSUE TITLE
ReferenceError: square is not defined

### ISSUE THREAD

**Issue by klevstul** [processing/p5.js#3464]
#### Nature of issue?

- [x] Found a bug

#### Most appropriate sub-area of p5.js?

- [x] Core/Environment/Rendering

#### Which platform were you using when you encountered this?

- [x] Desktop/Laptop

#### Details about the bug: 

- p5.js version: p5.js v0.7.2 September 02, 2018
- Web browser and version: firefox 64.0.2
- Operating System: manjaro linux

#### Steps to reproduce this:

- visit https://p5js.org/reference/#/p5/square
- check the console output
- it shows **ReferenceError: square is not defined**

**Comment by sanketsingh24** [comment]
I think this error arises because this was implemented in PR #3393 some days ago, and this error doesn't shows up when docs are built locally. Probably because online reference docs were built two days ago (in #3444) by @lmccart  but the p5 version used by reference is still v0.7.2 (commit in #3393 is not included in v0.7.2). @limzykenneth  @Spongman can you help me here please?

**Comment by limzykenneth** [comment]
The only immediate solution I can think of is to either revert back to the 0.7.2 tag then run the `release-docs` task or push out a new version. I didn't anticipate this problem back in #3444...

**Comment by lmccart** [comment]
I posted a new release so `square()` should be in there now. However, I wasn't able to get the docs to release the latest version on the website. the `grunt release-p5` command threw an error. I tried to rerun with `grunt release-docs` and got this printout:
```
lmccart:p5.js lmccart$ grunt release-docs
Running "release-docs" task
Cloning the website ...
Copying new docs ...
Pushing to GitHub ...
(node:81041) UnhandledPromiseRejectionWarning: Error: Error: Command failed: git add --all && git commit -am "Updated Reference for version 0.7.3" && git push

    at /Users/lmccart/Documents/p5/p5.js/tasks/release/release-docs.js:82:17
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
(node:81041) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:81041) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by lmccart** [comment]
yeah you're right ref is up to date. so it's not a critical error but one we might want to remove to alleviate confusion

**Comment by limzykenneth** [comment]
Yeah, looking into it now and something seems weird, I'll report back when I find something out.
