### ISSUE TITLE
oblong arc() draws angles inconsistently

### ISSUE THREAD

**Issue by datramt** [processing/p5.js#3466]
#### Nature of issue?

- [ x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ x] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [ x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: v0.7.3
- Web browser and version: brave 0.58.21, chrome 71.0.3578.98, safari 12.0.2 
- Operating System: MacOS Mojave 10.14.2  
- Steps to reproduce this: https://editor.p5js.org/datramt2/sketches/3nZSO_HMn

#### Details

Please take a look at this example:
https://editor.p5js.org/datramt2/sketches/3nZSO_HMn

While increasing the slider from the minimum to maximum value, a green arc() will trace a vertical ellipse from 0 to TWO_PI. Next to it, a blue arc() will trace the same vertical ellipse from PI to 3 PI. I’ve rotated the blue arc() by -PI to cancel out the phase difference between the two arcs, so as to demonstrate the angle differential between them.

In theory—I think(?)—the green arc and the blue arc ought to trace ellipses at the same rate as the user manipulates the slider. As my example shows, there are some inconsistencies in the rate at which the two arcs form when using the slider.

Further investigation revealed that angles fed into arc() that are less than 3/2 PI are drawn according to the subtended angle (i.e., the angle at the center-point that would form were we to connect the edges of the arc to the center). Meanwhile, angles fed into arc() that are greater than 3/2 PI are drawn according to the parametric equation (i.e., x(t) = a cos(t), y(t) = b sin(t)). 

In my example, if we focus on everything that's green and ignore anything that is blue, I have drawn a small circle in the center with a small rotating hand that represents the subtended angle. I’ve also drawn a relatively larger hand that reaches the perimeter of the ellipse. This is the parametric representation. If we drag the slider, we see that the arc follows the subtended angle (little hand) until we’ve reached 3/2 PI, at which point, the arc follows the big hand (parametric angle). 

Unless I am confused about something, to me, this seems unintended. It is worth noting that in processing, arc() uses the parametric equation only. Here is a java snippet to demonstrate that:
```java
void setup() {
  size(600, 600);
  noFill();
}

void draw() {
  background(80);
  stroke(150, 255, 150);
  strokeWeight(1);
  pushMatrix();
  translate(width / 2, height / 2);
  //text((mouseX / PI).toFixed(3) + " PI", -22, 268)
  ellipse(0, 0, 80, 500);
  strokeWeight(10);
  arc(0, 0, 80, 500, 0, 0 + mouseX/float(90)); //0 to 2 PI
  popMatrix();
  
  strokeWeight(4);
  pushMatrix();
  translate(width/2, height/2);
  line(0, 0, cos(mouseX/float(90))*40, sin(mouseX/float(90))*250);
  popMatrix();
}
```

I believe that this p5.js arc() issue is the culprit behind this "closed" bug: #3273. They fixed it by ensuring that the arc was not oblong, but did not fix the underlying issue that I am highlighting here

Thanks, and cheers! <3

**Comment by vedhant** [comment]
You are right. There is inconsistency in the way angle is used in arc().
Can I work on this issue @datramt  @Spongman @lmccart ?

**Comment by lmccart** [comment]
@vedhant certainly!
