### ISSUE TITLE
Vertex is now seemingly totally broken

### ISSUE THREAD

**Issue by Trimad** [processing/p5.js#3473]
#### Nature of issue?

- [X] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [X] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.7.3
- Web browser and version: Google Chrome 71.0.3578.98 and Firefox Developer 66.0b1
- Operating System: Windows 10
- Steps to reproduce this:

```
function setup() {
  createCanvas(800, 800, WEBGL);
}

function draw() {
  background(51);
  beginShape(LINES);
  vertex(30, 20, 0);
  vertex(85, 20, 0);
  vertex(85, 75, 0);
  vertex(30, 75, 0);
  endShape();
}
```

When I run this snippet of code in the p5.js web editor, it works as intended. When I run it locally in Chrome or in Firefox, my console is flooded with errors. In fact I can't get vertex to work at all in either Chrome or Firefox now. See screenshots.

Firefox
![vertex-firefox](https://user-images.githubusercontent.com/13515006/51581340-bcd63680-1e6b-11e9-8aa3-a0e4adfa3584.png)
p5.js web editor
![vertex-editor](https://user-images.githubusercontent.com/13515006/51581342-bcd63680-1e6b-11e9-889a-725386939671.png)
Google Chrome
![vertex-chrome](https://user-images.githubusercontent.com/13515006/51581343-be076380-1e6b-11e9-9964-28eabb914ea5.png)

**Comment by Trimad** [comment]
Another development:

So I've discovered that if I texture my shape with an image, the program works as intended. Problem is, I don't want to texture my shape. Working code:

```
var img;

function preload() {
  img = loadImage('water.jpg');
}

function setup() {
  createCanvas(1024, 1024, WEBGL);
}

function draw() {
  rotateX(frameCount*0.01);
  rotateY(frameCount*0.01);
  background(51);
  texture(img);
  textureMode(IMAGE);
  beginShape(LINES);
  vertex(0, 512, 0, 0, 512);
  vertex(512, 512, 0, 512, 512);
  vertex(512, 0, 0, 512, 0);
  vertex(0, 0, 0, 0, 0);
  endShape();
}
```

![textured](https://user-images.githubusercontent.com/13515006/51582713-61a74280-1e71-11e9-80d6-4e5742115c70.png)

**Comment by limzykenneth** [comment]
@Trimad Have you tried the sketches outside of the Processing p5.js mode? The mode is not maintained officially and will likely be out of date. If you wish to run you code locally you will need to follow steps lay out [here](https://p5js.org/get-started/)

**Comment by lmccart** [comment]
If you want to report issues with processing p5.js mode, you can do that here: https://github.com/fathominfo/processing-p5js-mode
