### ISSUE TITLE
Problem importing p5.dom in webpack project

### ISSUE THREAD

**Issue by mattt-b** [processing/p5.js#3474]
#### Nature of issue?

- [x] Found a bug

#### Most appropriate sub-area of p5.js?

- [X] Other (specify if possible)
p5.dom

#### Which platform were you using when you encountered this?

- [x] Desktop/Laptop

#### Details about the bug: 

- p5.js version: 0.7.3
- Steps to reproduce this:

I am using p5js 0.7.3 with webpack. I do not get this error with 0.7..2. When using the global script tags in the Getting Started guides there is no issue.

When importing p5.dom I get an error: `Uncaught ReferenceError: p5 is not defined`, relating to this section: [p5.dom.js#L3225](https://github.com/processing/p5.js/blob/master/lib/addons/p5.dom.js#L3225).

I'm wondering if those two functions are supposed to be moved up inside of the block above where p5 is defined? Moving it manually erases my issues locally, but I don't know enough about p5js or js modules to know if that affects something else.

**Comment by limzykenneth** [comment]
`p5` needs to be defined first in `p5.js` before loading in `p5.dom.js`. Without knowing how you are using webpack to package the two scripts it's hard to tell what the problem is. If moving the loading order of the scripts solve your problem then there likely isn't going to be a further problem.

**Comment by mattt-b** [comment]
In short:
* [these two functions](https://github.com/processing/p5.js/blob/master/lib/addons/p5.dom.js#L3225) cause the scripts to not load in webpack. Moving them into the block above where their parent class is defined fixes it for webpack, and continues to work for normal script tag version of p5js.
* `drop()` is listed as a core p5js function, but will not work unless p5.dom is included (this has been the case since at least 0.6.1).


> `p5` needs to be defined first in `p5.js` before loading in `p5.dom.js`. Without knowing how you are using webpack to package the two scripts it's hard to tell what the problem is. If moving the loading order of the scripts solve your problem then there likely isn't going to be a further problem.

I am importing p5.js before p5.dom.js. I believe it is loading them in the correct order because there are no problems with 0.7.2.

There is only a problem with 0.7.3 when it hits the last to last two functions that I linked to which aren't part of the block that everything else in the file is part of. Note that p5.File itself is also declared inside that block, so I am fairly confident [these two functions](https://github.com/processing/p5.js/blob/e9c45058ca05191bc06c0b5429a32b2d461b0070/lib/addons/p5.dom.js#L3225) are supposed to be in there with it.

Further, searching the repo for `p5.File._load` returns two results. One inside the p5.dom block, and one in [p5.Element.js#L931](https://github.com/processing/p5.js/blob/a6e47d6ea6d2bfd01ff1c1b7e5884486c1bb6eb5/src/core/p5.Element.js#L931).

After moving the last two functions of p5.dom.js into the block above them, `drop()` from [p5.Element.js#L931](https://github.com/processing/p5.js/blob/a6e47d6ea6d2bfd01ff1c1b7e5884486c1bb6eb5/src/core/p5.Element.js#L931) still works.

Note that `drop()` does NOT work unless p5.dom.js is included **even in the plain html file + script tag getting started version**. I don't believe this is correct behavior since https://p5js.org/reference/#/libraries/p5.dom states:

> Methods and properties shown in black are part of the p5.js core

**Comment by limzykenneth** [comment]
The two functions were added a few months ago which is why the problem isn't present in 0.7.2, we can make the change so that it is included in the block as currently it is looking for a global p5 object which doesn't exist in the case of packaged builds like webpack.

As for the issue with `drop()` is it related to this issue (ie. importing into webpack)? If not can a separate issue be filed for it?

**Comment by mattt-b** [comment]
> As for the issue with `drop()` is it related to this issue (ie. importing into webpack)? If not can a separate issue be filed for it?

Only in the sense that I believe the same change will fix both issues. I'll make another issue and a PR for both.

**Comment by kousun12** [comment]
@lmccart is there a new release planned any time soon? Also came across the issue that was fixed here trying to use webpack with the latest p5
