### ISSUE TITLE
:question How works the _validateParameters function in 2d_primitives.js

### ISSUE THREAD

**Issue by Narrathek** [processing/p5.js#3479]
### Or to be more precise, how does the parameter validation generally work in p5?

**Comment by Spongman** [comment]
the method arguments are defined in the YUIdoc comments above each method's implementation. those comments are compiled into a file `data.json` during the build, which is included in the debug version of the library. the `_validateParameters` function checks that the passed parameters agree with the declared arguments:
https://github.com/processing/p5.js/blob/23a917e57e90988fe1262a8e537786478c9db067/src/core/error_helpers.js#L601

**Comment by Narrathek** [comment]
Thank u
