### ISSUE TITLE
0.7.3 not obeying angleMode(DEGREES) in WEBGL mode

### ISSUE THREAD

**Issue by grege2** [processing/p5.js#3490]
#### Nature of issue?

- [x] Found a bug

#### Most appropriate sub-area of p5.js?

- [x] WebGL

#### Which platform were you using when you encountered this?

- [x] Desktop/Laptop

#### Details about the bug: 

- p5.js version: 0.7.3
- Web browser and version: Chrome 71.0.3578.98
- Operating System: Mac 10.14.2

- Steps to reproduce this:

It seems like p5.js 0.7.3 is not obeying angleMode(DEGREES) in WEBGL mode. Rotations stay in Radians. This worked fine in 0.7.2

An easy way to see this is just on the Reference Page examples for "rotate()" and "rotateZ()". If you insert angleMode(DEGREES) anywhere before the rotation, it is obeyed in the rotate() example, but not in the rotateZ() example.

I tried to reproduce this at https://editor.p5js.org/grege2/sketches/TDIyVt9tT but it works ok there. Possibly the Web Editor is still on 0.7.2 or earlier (it would be good to be able to query the version of p5.js that you're running on). 

I've checked it thoroughly in my own app code and it seems a hard error. My WEBGL app rotates fine in numerous DEGREES modes at 0.7.2, but goes crazy at 0.7.3 (because all rotations are 180/PI too large, easily spotted !) I can see from other discussions about angleMode() in the last few months that there has been some looseness in all the _fromRadians / _toDegrees etc calls that has received quite a few fixes recently, possibly there's still a gremlin in there.

I'd be happy to pursue this myself, but if anyone feels they can nail it quickly, feel free. I'll pursue it anyway, it's a good learning exercise.

Regards, GE

**Comment by sanketsingh24** [comment]
I changed the code in #3458, will take up this issue and try to solve it.

**Comment by grege2** [comment]
@Spongman @sanketsingh24  Thanks for fixing this.

**Comment by grege2** [comment]
@Spongman @sanketsingh24
Just fyi, I've modified my code to always use Radians mode, ie. the default, and everything works fine at 0.7.2 and 0.7.3. So I'm a happy camper. No need to rush out a 0.7.4 for me :=)
