### ISSUE TITLE
loop() issues

### ISSUE THREAD

**Issue by Spongman** [processing/p5.js#3496]
re: #3242, #3495

i see a couple of issues with loop() currently:

1) calling loop() inside draw() when looping is currently enabled, causes a recursive call to draw which can go infinite.
2) calling loop() inside setup() also calls draw() which can cause weird side-effects.

here's a sketch that illustrates this:

https://codepen.io/Spongman/pen/WPEbeB?editors=0011

**Comment by meiamsome** [comment]
I think these tests would describe the problems well, and should be added to the repo:
```js

    testSketchWithPromise('loop in setup does not call draw', function(
      sketch,
      resolve,
      reject
    ) {
      sketch.setup = function() {
        sketch.loop();
        resolve();
      };

      sketch.draw = function() {
        reject(new Error('Entered draw during loop()'));
      };
    });

    testSketchWithPromise('loop in draw does not call draw', function(
      sketch,
      resolve,
      reject
    ) {
      sketch.draw = function() {
        if (sketch.frameCount > 1) {
          reject(new Error('re-entered draw during loop() call'));
        }
        sketch.loop();
        resolve();
      };
    });
```

Both fail on the current master, as expected.
