### ISSUE TITLE
You must first call texture() before using vertex() with image based u and v coordinates

### ISSUE THREAD

**Issue by infusion** [processing/p5.js#3498]
Hello,

I just updated my dev branch from 0.7.2 to 0.7.3 and get tons of warnings for each attempt to draw lines, vertices and so on in WEBGL. The library still works perfectly well but it is not possible to work with this version due to the massive amount of warnings. Here is a simple example to reproduce:

```
<script src ="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.7.3/p5.min.js"></script>
<script>
function setup() {
  createCanvas(720, 400, WEBGL);
  stroke(255);
}
function draw() {
  background(0);
  line(0, 100, 0, 400, 100, 0);
}
</script>
```

Thanks Robert

**Comment by sanketsingh24** [comment]
I think this is fixed in #3483, but it is not present in v0.7.3, and will be present in the next version release, so I guess you can use the build from the master branch, which does not have this problem.

**Comment by infusion** [comment]
Yep, the patch looks good. For when is v0.7.4 planned?

**Comment by sanketsingh24** [comment]
I don't have idea about the next minor version, but the next major version v0.8.0 is scheduled on 31st March

**Comment by grege2** [comment]
Hi @sanketsingh24 @lmccart 
I didn't know there were release schedules. That could be useful, eg. I'm sending some colleagues new code, but if a release might happen in a few days or a week I would wait and test against it. Is a schedule (and planned content?) viewable anywhere ? Thanks. (Also, and this isn't said enough, thanks to everyone here for a great product. The ease and flexibility of designing with p5.js, and being able to develop locally, or host on numerous places incl. p5.js web editor, CodePen, OpenProcessing, your own AWS S3 bucket etc. is quite exceptional).

**Comment by lmccart** [comment]
@grege2 we have a [0.8.0 release](https://github.com/processing/p5.js/milestones) targeting march 31, but don't have a schedule for minor releases in the interim, it's really as we can do them. we'd like to get to a point where we have more scheduled releases, but we're not there yet.

**Comment by lmccart** [comment]
I'm closing this since the issue has been addressed in the codebase.

**Comment by valmormn** [comment]
Same issue here.

This warning floods on my console when I try to draw a simple line.

line(0, 0, 0, 100);

**Comment by infusion** [comment]
Downgrade to 0.7.2 until the fix gets pushed

**Comment by Vamoss** [comment]
Hi, I am experiencing the same error on this code:
https://www.openprocessing.org/sketch/672835

@msawired, maybe it's good to downgrade OpenProcessing.

**Comment by outofambit** [comment]
hi @Vamoss, i looked at your link and its using p5.js version `0.7.3`. i copied and pasted your code into the p5js web editor (which is using the latest `0.8.0`) and didn't see the issue (https://editor.p5js.org/outofambit/sketches/V0Mp-GFOA).

please upgrade your sketch on OpenProcessing to use the latest p5.js release and you should be good!
