### ISSUE TITLE
some webgl texture manual tests are broken

### ISSUE THREAD

**Issue by stalgiag** [processing/p5.js#3503]
Several WebGL manual test examples are broken since #3056. These can be fixed by setting `textureMode(NORMAL)` in setup or by changing the coordinates to use the image dimensions instead of 1.

Broken tests include:
[immediateMode/texture](https://github.com/processing/p5.js/tree/master/test/manual-test-examples/webgl/immediateMode/texture)
[immediateMode/minTextureAndFill](https://github.com/processing/p5.js/tree/master/test/manual-test-examples/webgl/immediateMode/mixTextureAndFill)
[immediateMode/vertexArgs](https://github.com/processing/p5.js/tree/master/test/manual-test-examples/webgl/immediateMode/mixTextureAndFill)
[texture/multipleTextures](https://github.com/processing/p5.js/tree/master/test/manual-test-examples/webgl/texture/multipleTextures)
[texture/videoTexture](https://github.com/processing/p5.js/tree/master/test/manual-test-examples/webgl/texture/videoTexture)

**Comment by shakeabi** [comment]
I'd love to take a swing at this, if nobody else is working on it yet.

**Comment by stalgiag** [comment]
That would be great @shakeabi
