### ISSUE TITLE
How to open the Java Script console in Chrome?

### ISSUE THREAD

**Issue by nsrinivasan80** [processing/p5.js#3511]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [x] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 
- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

**Comment by nsrinivasan80** [comment]
I am unable to open the Java Script Console as described in the Make book.
Please help.

**Comment by montoyamoraga** [comment]
Hi @nsrinivasan80 
I will take a look at the Make book to check how it is said,
can you try using the methods pointed out here?
https://stackoverflow.com/questions/66420/how-do-you-launch-the-javascript-debugger-in-google-chrome?

**Comment by nsrinivasan80** [comment]
I am unable to open the Java Script console in Chrome.
I followed the instructions given in the book, "Make"

--N. Srinivasan

**Comment by sanketsingh24** [comment]
If you are on windows or Linux, CTRL + SHIFT + J works on most browsers (including firefox, chrome, chromium, i don't know about MS Edge though). On Mac, Use ⌥ + ⌘ + J to open Developer Tools and bring focus to the Console.

**Comment by nsrinivasan80** [comment]
I get this error message:
Failed to load resource: the server responded with a status of 500 (Request
Blocked)
--N. Srinivasan

**Comment by stalgiag** [comment]
Hi @nsrinivasan80 the Github issues section is available for discussions about features and bugs that are relevant for contributors as they work together to develop this library. Unless you believe that something is broken or not working as expected then I recommend asking questions in [the p5 category of the processing discourse page](https://discourse.processing.org/c/p5js). That forum is a great resource for learning how to use the library. I am closing this issue for now for organization reasons but good luck!
