### ISSUE TITLE
circle() is not definded on web editor

### ISSUE THREAD

**Issue by icq4ever** [processing/p5.js#3512]
on webeditor, circle() function is not working. I can see this error.

```
ReferenceError: circle is not defined (sketch: line 8)
```

#### Nature of issue?

- [v] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [v] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [v] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 
- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

**Comment by Ajayneethikannan** [comment]
Hi @icq4ever ! Can you provide link to your sketch. It would be helpful for people to solve your issue.

**Comment by sanketsingh24** [comment]
Probably this is because the p5 version on editor is not up to date(not so sure)? You should report the error [here](https://github.com/processing/p5.js-web-editor/issues), that repository is specific for the p5 web editor.

**Comment by k-malek** [comment]
Same with square()

I use rect() and ellipse() instead. Ex. ellipse(100,100,20,20). I feel like I already got used to it ;p

**Comment by sanketsingh24** [comment]
Ok, now I think it is because the p5 version editor uses is still v0.7.2, but the current p5 version is v0.7.3, and square() and circle() were first introduced in v0.7.3. So I think it is better to close the issue here and open a new one [here](https://github.com/processing/p5.js-web-editor/issues).

**Comment by icq4ever** [comment]
@sanketsingh24 thanks! I'll close this issue and open there :)
