### ISSUE TITLE
Is there a way to find the drop of a song using p5.js audio module?

### ISSUE THREAD

**Issue by MakoMakox** [processing/p5.js#3516]
Is there a way to find the drop of a song using p5.js audio module?
How should I proceed ? Thank you for your time

**Comment by hellonearthis** [comment]
Might be better to ask here.
https://discourse.processing.org/c/p5js/p5js-questions

**Comment by stalgiag** [comment]
Yes, @hellonearthis is correct. The github issues section is reserved for bugs and feature discussions. The discourse page should help though. Good luck @MakoMakox !
