### ISSUE TITLE
P5js Dom, ReferenceError: createDiv is not defined

### ISSUE THREAD

**Issue by pbouigue** [processing/p5.js#3523]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [x] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.7.2
- Web browser and version: Firefox 65.0.1
- Operating System: Windows 10
- Steps to reproduce this:

Hello, I'm trying to work with p5.dom to  play with html divs and cliquable links.
Everything seems to work fine when i'm trying this code in my processing program and even if I copy it to a tumblr.
Here is my code so far :

```html
<!DOCTYPE` html>
<html>
  <head>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.7.2/p5.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.7.2/addons/p5.dom.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.7.2/addons/p5.sound.min.js"></script>
    <meta charset="utf-8" />

<style>
html, body {
  margin: 0;
  padding: 0;
}
</style>
  </head>
<body>
  <script>

function setup() {
  canvas = createCanvas(600, 400);
  let txt = createDiv('This is an HTML string!');
  txt.position(50, 50);
}

function draw() {
  background(220, 180, 200);
  ellipse(width/2, height/2, 100, 100);
  ellipse(width/4, height/2, 50, 50);
}

</script>
  </body>
    </html>
```

I am now trying to import it to my wordpress by using the html editor on my project page.
The code is working fine until I add : 

``` javascript
let txt = createDiv('This is an HTML string!');
txt.position(50, 50);
```

in my firefox console, the error seems to be the following:

**ReferenceError: createDiv is not defined**

Do you know any way to get over it?

Thanks a lot for your future help.

**Comment by Ajayneethikannan** [comment]
Hi @pbouigue ! From what you have mentioned , it appears that the code you have written is has no error and there seems to be no error in the library itself , as it is working fine in other platforms you have tested. 

If you believe the issue to be specific to the library itself, please do share screenshots, links and steps to reproduce the bug, as it will help the maintainers to correct the issue.

I would recommend you to check out the [processing forum](https://discourse.processing.org/c/p5js), to solve your issues and any help you need regarding the usage of the library .

**Comment by lmccart** [comment]
I don't think you can just insert p5 code straight into wordpress, but here is a plugin that helps you do it: https://wordpress.org/plugins/wp-p5js-block/
