### ISSUE TITLE
3D Text in WebGL

### ISSUE THREAD

**Issue by FreddieRa** [processing/p5.js#3524]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [x] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [x] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [X] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: v0.6.1
- Web browser and version: 
- Operating System: Windows

#### New feature details:

3D Text (i.e creating 3D letters and words) in WebGL does not currently exist. I have implemented a simple version that uses the 2D Graphic and Pixels array to create an array of cubes. This has the advantage it can render anything drawn with the "text()" command, but currently doesn't seem very efficient. 

Does someone more well-versed in P5 and WebGL than me want to see if they can optimise it, or at least think about adding a better version into the actual codebase?

Sketch:
https://www.openprocessing.org/sketch/669863

Code:
https://github.com/FreddieRa/P5JS/tree/master/3DText

**Comment by dhowe** [comment]
This has been discussed previously (see https://github.com/processing/p5.js/issues/2183, https://github.com/processing/p5.js/issues/1177, ). One approach would be a simple cube font, like you have above... a more general, though more complex, option would be to use opentype paths extruded along the z-axis, which should allow for use of a wide range of fonts

**Comment by FreddieRa** [comment]
Using an algorithm to find rectangles in the array and drawing those instead, it now renders text in 3D roughly 10x faster than a cube font (~50 fps).

Sketch:
https://www.openprocessing.org/sketch/669863

Code:
https://github.com/FreddieRa/P5JS/tree/master/3DText2.0

**Comment by FreddieRa** [comment]
With about 2 seconds load time it can draw letters with a resolution of 100*100 at that same frameRate, since the number of rectangles doesn't scale linearly with resolution. This is also not limited to letters. Any black and white bitmap of any resolution can use this with a little adaptation.

**Comment by stalgiag** [comment]
@FreddieRa it would be cool to make [this into a library](https://github.com/processing/p5.js/blob/master/developer_docs/creating_libraries.md) that works more generally with any graphics object to turn it into a voxels object. This demo has a really charming visual effect and I can imagine something that expands on it that makes for fun options for transition from 2D to 3D.

I think that for core 3D text implementation we would need to extrude the opentype paths as @dhowe suggests, just to keep behavior from diverging too unexpectedly from Processing.

**Comment by FreddieRa** [comment]
@stalgiag I've already started work on creating a library out of this now I've got it working for images and canvases. I'll update the thread when I'm finsihed. Thanks for the advice.

**Comment by stalgiag** [comment]
Hi @FreddieRa  I am going to close this issue for organization purposes as it seems like you are going to work on your library separately. Feel free to post here when you are done with it. It is also a good idea to post [in the forum.](https://discourse.processing.org/)

**Comment by FreddieRa** [comment]
Hi @stalgiag the library is finished, should I make a new issue?

**Comment by stalgiag** [comment]
Hi @FreddieRa - I checked it out and it seems cool. You have the right idea posting on discourse.processing.org as a start. Github issues probably aren't the best places to talk about and announce new libraries but there are other options. Feel free to shoot an email to hello@p5js.org to introduce your library to the maintainers.

**Comment by FreddieRa** [comment]
@stalgiag Thank you for the help and comments, I appreciate it. I have sent an email, and will see if they can add it to the list of accepted libraries. Do let me know if you think there is anything else that will either improve the library or help get the word out.
