### ISSUE TITLE
TypeError: 'undefined' is not an object (evaluating 'window.performance.now')

### ISSUE THREAD

**Issue by joepdooper** [processing/p5.js#3528]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [x] Mobile/Tablet (touch devices)
- [ ] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.7.3
- Web browser and version: Mobile Safari 7.0
- Operating System: iOS 7.1.2
- Steps to reproduce this:
`TypeError: 'undefined' is not an object (evaluating 'window.performance.now')`
On line 9587 of p5.min.js
`return window.innerHeight || document.documentElement && document.documentElement.clientHeight || document.body && document.body.clientHeight || 0`

**Comment by limzykenneth** [comment]
Hi @joepdooper, do you have a simple code example that demonstrate this behaviour?

**Comment by joepdooper** [comment]
The code in action is here: 
[https://dooper.io/montauk-v4/](https://dooper.io/montauk-v4/). 
[https://dooper.io/montauk-v4/js/sketch.js](https://dooper.io/montauk-v4/js/sketch.js)

And the problem only occurs on Mobile Safari.

**Comment by meiamsome** [comment]
The polyfill for this was removed from P5 a few months ago - (see #2797 )

That browser appears to be very old, but you should be able to get it to work by adding a suitable polyfill to your page manually. 

It looks like you might be able to get away with just adding this to your html before p5:
`<script src="https://polyfill.io/v3/polyfill.min.js?features=performance.now"></script>`

**Comment by joepdooper** [comment]
> It looks like you might be able to get away with just adding this to your html before p5:
> `<script src="https://polyfill.io/v3/polyfill.min.js?features=performance.now"></script>`

@meiamsome thanks a lot! The errors are gone.

The only thing now it doesn't start playing… but that's for me to figure out.

Thanks again!
