### ISSUE TITLE
Adding hasClass and toggleClass to p5.dom.js (and fix addClass)

### ISSUE THREAD

**Issue by OleksiiBulba** [processing/p5.js#3533]
#### Nature of issue?

- [x] Bug with addClass method in p5.Element
- [x] Existing feature enhancement

#### Most appropriate sub-area of p5.js?

- [x] p5 DOM

#### Which platform were you using when you encountered this?

- [x] All devices

#### Details about the bug:
* p5.js version: 0.7.3
* Web browser and version: Google Chrome 64 bit 72.0.3626.109
* Operating System: Windows 10 Enterprise; version 1809; build 17763.194
* Steps to reproduce this:

```
let div;
function setup() {
  div = createElement();

  // add class
  div.addClass('test-class');
  console.log(div.elt.getAttribute('class'));
  // Output: "test-class"

  // add the same class
  div.addClass('test-class');
  console.log(div.elt.getAttribute('class'));
  // Output: "test-class test-class" // (!) Should: "test-class"

  // removing class when two same classes applied (I think it should delete all same classes)
  div.removeClass('test-class');
  console.log(div.elt.getAttribute('class'));
  // Output: "test-class" // (!) Should: ""

  // removing the last class (because previous did not remove doubled class)
  div.removeClass('test-class');
  console.log(div.elt.getAttribute('class'));
  // Output: ""
}
```

#### Feature enhancement details:
There are methods like p5.Element.prototype.**addClass(class)** and p5.Element.prototype.**removeClass(class)**. 
Why not to add p5.Element.prototype.**hasClass(class)** and p5.Element.prototype.**toggleClass(class)**?
(And fix addClass: add check if class is added previously)

I think we can implement new functions like this:
```
  /**
   *
   * Checks if specified class already set to element
   *
   * @method hasClass
   * @returns {boolean} a boolean value if element has specified class
   * @param c {String} class name of class to check
   * @example
   * <div class='norender'><code>
   *
   * var div;
   *
   * function setup() {
   *   div = createDiv('div');
   *   div.addClass('show');
   * }
   *
   * function mousePressed() {
   *   if (div.hasClass('show')) {
   *       div.addClass('show');
   *   } else {
   *       div.removeClass('show');
   *   }
   * }
   * </code></div>
   */
  p5.Element.prototype.hasClass = function(c) {
    var regex = new RegExp('(?:[a-zA-Z-_d:]s)*' + c + '(?:s[a-zA-Z-_d:])*');//<--tested in Chrome
                                                                            //console
    return this.elt.className.search(regex) !== -1;
  };

  /**
   *
   * Toggles element class
   *
   * @method toggleClass
   * @param c {String} class name to toggle
   * @chainable
   * @example
   * <div class='norender'><code>
   *
   * var div;
   *
   * function setup() {
   *   div = createDiv('div');
   *   div.addClass('show');
   * }
   *
   * function mousePressed() {
   *   div.toggleClass('show');
   * }
   * </code></div>
   */
  p5.Element.prototype.toggleClass = function(c) {
    if (this.hasClass(c)) {
      this.removeClass(c);
    } else {
      this.addClass(c);
    }
    return this;
  };
```

And fix addClass like this:
```
/**
   *
   * Adds specified class to the element.
   *
   * @for p5.Element
   * @method addClass
   * @param c {String} class name of class to add
   * @chainable
   * @example
   * <div class='norender'><code>
   * var div = createDiv('div');
   * div.addClass('myClass');
   * </code></div>
   */
  p5.Element.prototype.addClass = function(c) {
    if (this.elt.className) {
      // PEND don't add class more than once
      //var regex = new RegExp('[^a-zA-Z\d:]?'+c+'[^a-zA-Z\d:]?');
      //if (this.elt.className.search(/[^a-zA-Z\d:]?hi[^a-zA-Z\d:]?/) === -1) {
      if (!this.hasClass(c)) { // <--- Added this check instead of the two top lines above
        this.elt.className = this.elt.className + ' ' + c;
      }
    } else {
      this.elt.className = c;
    }
    return this;
  };
```

**Comment by outofambit** [comment]
hi @OleksiiBulba ! thanks for this great write up! this seems like a really sensible addition. would you like to open a pull request for these fixes? i'm happy to work with you on getting this tested and merged!

**Comment by ankur54** [comment]
Hello everyone. I'm sorry, but is this issue still open? Since I couldn't find any pull request for this, I would like to work on it if possible. Thank you

**Comment by OleksiiBulba** [comment]
Hi @ankur54 ! We can work with this issue together. I have not started yet because of circumstances, but right now I am ready to go. @ankur54 , do you know how to setup p5 project and run build and tests?
I think all my code I provided in issue description is enough to resolve it. All I need is to write and run tests.

**Comment by OleksiiBulba** [comment]
I created pull request #3609 for this issue. Any comments and suggestion is appreciated

**Comment by ankur54** [comment]
> Hi @ankur54 ! We can work with this issue together. I have not started yet because of circumstances, but right now I am ready to go. @ankur54 , do you know how to setup p5 project and run build and tests?
> I think all my code I provided in issue description is enough to resolve it. All I need is to write and run tests.

Oh. you have already written the code. Is there anything I can do?

**Comment by lmccart** [comment]
closed with https://github.com/processing/p5.js/pull/3609
