### ISSUE TITLE
updating node modules

### ISSUE THREAD

**Issue by shaharyar-shamshi** [processing/p5.js#3538]
#### Nature of issue?

- [ ] Found a bug
- [x] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- Many of the node modules are not updated example
all-contributors-cli
brfs   
chai
es6-promise
eslint
eslint-config-prettier
eslint-plugin-prettier
esprima-extract-comments
file-saver
grunt-cli
grunt-contrib-clean
grunt-eslint
grunt-karma
grunt-saucelabs
html2plaintext
husky
karma
karma-benchmark
karma-detect-browsers
lint-staged
marked
mocha
opentype.js
prettier
puppeteer
whatwg-fetch

**Comment by shaharyar-shamshi** [comment]
I would like to solve this issue

**Comment by limzykenneth** [comment]
If there is a minor or patch version available for those packages, you can go ahead and update them, run the whole build as well to make sure nothing breaks before commiting the changes.

If the newer version is a major version or if the version is still 0.x.x then you will need to find out what the changes are and open a new separate issue for them if necessary.

**Comment by shaharyar-shamshi** [comment]
@limzykenneth thanks for reply actually when I moved forward with this issue I analysed there are many issue with code formatting prettier issue (npm run grunt failed due to this) I am sending pr of it first
