### ISSUE TITLE
WEBGL with OTF fonts, sending constant warning

### ISSUE THREAD

**Issue by ffd8** [processing/p5.js#3539]
#### Nature of issue?

- [X] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [x] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [X] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.7.3
- Web browser and version: Chrome 72.0.3626.119 + Safari 11.1.2
- Operating System: MacOS 10.13.16
- Steps to reproduce this:
```
var f;
function setup() {
	createCanvas(windowWidth, windowHeight, WEBGL);
	fill(255);
	f = loadFont("data/roboto-mono_regular.otf", function(){
		textFont(f, 200);
		text("hello", 0, 0); // no issue, renders
	});
	//text("world", 0, 0); // sends WEBGL console error
}

function draw(){
	//text("world", 0, 0); // sends WEBGL console error
}
```

First it's awesome that `text` is now working in WEBGL mode! Nevertheless, when most definitely using OTF fonts (tried a few different ones), the console is being flooded by the following WEBGL warning:
`WEBGL: only opentype fonts are supported`

Loading the font as a `preload()` also didn't help/work.

Tried double checking with the web-editor, however that's using p5.js 0.6.1, where `text` didn't work in WEBGL mode.

**Comment by Spongman** [comment]
that's weird. can you share the `.otf` file you're having trouble with?

here's a version of your sketch that uses an .`otf` font: https://codepen.io/Spongman/pen/aMzaze?editors=0011 does it work for you?

**Comment by ffd8** [comment]
Ahaaa! Was backtracking the `_isOpenType()` function and trying to figure out how/why it wasn't ready when called. 

Great find – although a bit strange the callback function doesn't handle it.. closing since your technique works, but interested if it could be integrated into callback to avoid need of preload? 

Thanks for the quick reply and codepen[s]!

**Comment by Spongman** [comment]
The callback does work, that why you don’t see the error in that case.

The issue is that the rest of `setup()` and subsequent calls to `draw()` complete before the callback is invoked.

Once the callback calls `fontFace()` the errors in `draw()` cease.
