### ISSUE TITLE
solve Prettier issue for code quality

### ISSUE THREAD

**Issue by shaharyar-shamshi** [processing/p5.js#3546]
when running the **npm run grunt** it is giving lot of prettier issue I want to open PR of it

![screenshot from 2019-02-27 23-07-48](https://user-images.githubusercontent.com/17377195/53510730-ae231500-3ae4-11e9-9b20-2f765b439907.png)

**Comment by shaharyar-shamshi** [comment]
@limzykenneth  should I open the PR

**Comment by Spongman** [comment]
i think this is because you updated the eslint package too far. i'd recommend resetting and just running an `npm audit --fix` instead of updating everything all the way.
