### ISSUE TITLE
Calling size() on a p5.graphic object automatically draws it

### ISSUE THREAD

**Issue by FreddieRa** [processing/p5.js#3548]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.7.3
- Web browser and version: 
- Operating System: Windows
- Steps to reproduce this:

```javascript
function setup() {
    createCanvas(windowWidth, windowHeight, WEBGL)
    graphic = createGraphics(200, 50);
    graphic.size(200, 50)
    graphic.textAlign(CENTER, CENTER);
    graphic.position(width/2, height/2);
}

function draw() {
    background(255);
    graphic.text("HELLO",graphic.width/2,graphic.height/2)
}
```

This is technically a bug, but may be useful for people currently dealing with #2183 . When you create a p5.graphics object and use the `size()` function on it, be it in `setup()` or `draw()`, it will then render over the top of whatever other graphics you are using. It does not need to be called as a texture, it just appears.

This means we now have a one line method to draw 2D text in 3D, but can be very annoying if you actually want to resize a graphics object without its contents appearing onscreen.

Can someone figure out what it is that is causing this, and separate it out into its own function so we can maintain this useful functionality without it being mandatory?

**Comment by Spongman** [comment]
maybe `size()` is causing the `Graphics`'s canvas to be made visible?

**Comment by Ajayneethikannan** [comment]
I agree to @Spongman 's suggestion.
I think the function graphic.resizeCanvas() should be used here, as it is very similar to normal resizeCanvas, as we are basically manipulating another canvas behind the scenes, by my understanding. 
Would love to hear what you think of this,
thanks !

**Comment by FreddieRa** [comment]
The `resizeCanvas()` function appears to globally affect the main canvas for some reason. I do not know why this is the case, but even if called as `graphic.resizeCanvas()` it will affect the graphic created with `createCanvas()`.

And yes, as I mentioned in the initial post I confirmed it is `size()` that causes it to become visible, I am just trying to figure why.

**Comment by FreddieRa** [comment]
Hmm, it seems it's not as simple as calling it on the main canvas because if `graphic.` is removed, the behaviour changes, but in neither case is as expected.

Some example code:
```javascript
function setup() {
    createCanvas(windowWidth, windowHeight, WEBGL)
    graphic = createGraphics(200, 100);
    graphic.resizeCanvas(400, 100)
}

function draw() {
    background(0);
    graphic.background(255)
    box(200)
}
```

**Comment by Ajayneethikannan** [comment]
Can you please say what is the expected behavior, and what is the current behavior, I am not able to reproduce your results.

**Comment by Ajayneethikannan** [comment]
> And yes, as I mentioned in the initial post I confirmed it is `size()` that causes it to become visible, I am just trying to figure why.

This is happening because of size function [setting the style attribute](https://github.com/processing/p5.js/blob/master/lib/addons/p5.dom.js#L2008) as ,
```
  this.elt.setAttribute(
            'style',
            'width:' + aW + 'px; height:' + aH + 'px'
          );
```
which seems to remove some of the older style properties applied, including 
`display: 'none'`
for reference : https://www.w3schools.com/jsref/met_element_setattribute.asp

By changing it to ,
```
this.elt.style.height = ah + 'px'
this.elt.style.width = aW + 'px' 
```

we can avert this.

**Comment by FreddieRa** [comment]
Ahh great, is this fix going to be implemented in the code base?

**Comment by Ajayneethikannan** [comment]
I have made a pull request regarding this , hopefully it solves your issue !
