### ISSUE TITLE
Travis build for Node 8 fail sometimes

### ISSUE THREAD

**Issue by stalgiag** [processing/p5.js#3555]
The Travis builds for Node 8 are failing occasionally. The problem seems to be [that this unit test](https://github.com/processing/p5.js/blob/master/test/unit/webgl/p5.Texture.js#L111) occasionally fails because the texture being passed is sometimes [not passing this conditional ](https://github.com/processing/p5.js/blob/master/src/webgl/p5.Texture.js#L311). 

~~Note that this test never fails with Node 8 running on my local machine or Node 10 on Travis.~~

**Comment by stalgiag** [comment]
Correction: this is failing locally.

Probably some discrepancy between the way that textures are stored and retrieved introduced with the merging of #3535 and #3537. (see [RendererGL._tex](https://github.com/processing/p5.js/blob/master/src/webgl/p5.RendererGL.js#L134) vs [RendererGL.textures](https://github.com/processing/p5.js/blob/master/src/webgl/p5.RendererGL.js#L128). I will revert the latter PR merge today if the problem isn't tracked down.

**Comment by stalgiag** [comment]
Update: Apparently this only fails locally sometimes

**Comment by sanketsingh24** [comment]
Ok so problem is [here](https://github.com/processing/p5.js/blob/master/test/unit/assets/nyan_cat.gif), called [here](https://github.com/processing/p5.js/blob/master/test/unit/webgl/p5.Texture.js#L15). This GIF has a size of `50*50 pixels`, so width is `50 pixels` and vice versa, which is not a power of `2`. Sometimes (like, the most of times), for some reason, `texImg1` is `1*1 pixels`, so at those times the test passes without any fuss, but sometimes, GIF loads up and those cases, the test fails. For more info, go [here](https://www.diffchecker.com/KhFb5lvz).

**Comment by sanketsingh24** [comment]
Changing [`setup()`](https://github.com/processing/p5.js/blob/master/test/unit/webgl/p5.Texture.js#L11) to this would make sure `texImg1` is loaded and ready to go, and would make the tests consistent, now just need to replace GIF with one which has dimensions in power of 2s.
```js
  setup(function() {
    myp5 = new p5(function(p) {
      p.setup = function() {
        p.createCanvas(100, 100, p.WEBGL);
        texImg1 = p.loadImage('unit/assets/nyan_cat.gif', function(img) {
          p.texture(img);
        });
        texImg2 = p.loadImage('unit/assets/target.gif');
        // texture object isn't created until it's used for something:
        //p.box(70, 70, 70);
      };
    });
  });
```

**Comment by stalgiag** [comment]
Thanks for the detective work @sanketsingh24! That all makes sense. So when the tests were passing is when the tests were actually failing. You can add another asset if you would like something that is 2x2 should be fine. I would say resize nyan_cat but it is used in many places.

**Comment by stalgiag** [comment]
Or actually, you could just use `createGraphics` there. The image loading to texture is proven by `texImg2`. Your choice!

**Comment by stalgiag** [comment]
Assuming you are going to handle fixing the test @sanketsingh24? Let me know if not and I can make the changes.

**Comment by Spongman** [comment]
shouldn't these `loadImage()` calls be done in a `preload()` method?

**Comment by stalgiag** [comment]
Yes or `createGraphics` could be used. `preload` + `loadImage` covers more I suppose.

**Comment by meiamsome** [comment]
@Spongman yes, and currently `setup` is not set to be asynchronous to wait for p5 to set itself up:
```javascript
  setup(function(done) {
    myp5 = new p5(function(p) {
      p.preload = function() {
        texImg1 = p.loadImage('unit/assets/nyan_cat.gif');
        texImg2 = p.loadImage('unit/assets/target.gif');
        
        // texture object isn't created until it's used for something:
        //p.box(70, 70, 70);
      };
      p.setup =  function() {
        p.createCanvas(100, 100, p.WEBGL);
        p.texture(texImg1);
      };
    });
  });
```

That said, I would advocate these tests be translated to use the `promisedSketch`/`testSketchWithPromise` methods so that each test can have an isolated environment and have correct preload/setup behaviours

**Comment by sanketsingh24** [comment]
I also think using something like promisedSketch is better here.

@stalgiag I will be in my class for next few hours, If the changes are urgent, as it seems , please go ahead
