### ISSUE TITLE
Noise never gets close to 0.0 nor 1.0

### ISSUE THREAD

**Issue by Mamboleoo** [processing/p5.js#3558]
#### Nature of issue?

- [x] Found a bug

#### Most appropriate sub-area of p5.js?

- [x] Math

#### Which platform were you using when you encountered this?

- [x] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [x] Others (specify if possible)

#### Details about the bug: 

- p5.js version: **v0.7.3 January 20, 2019**
- Web browser and version: **All of them**

Hey there,
I'm currently playing with the noise function to make some demos and I noticed that whenever I call the `noise()` function it never returns a number close to 0.0 or 1.0.
I'm making dots moving around the screen by multiplying the noise value by the width & height of the canvas.
```
this.x = noise(millis() * 0.0003) * width;
this.y = noise(10 + millis() * 0.0003) * height;
```
But as you can see on this screenshot, my dots are always gathering in the center of my screen.
![image](https://user-images.githubusercontent.com/6048794/53681414-b0a28c00-3ce9-11e9-817e-fb80b2650187.png)

You can access this live demo on CodePen. If you press on the window I'm switching from P5's native noise function to another one I found online and it's quite clear that the external algorithm is returning more extended values.
https://codepen.io/Mamboleoo/pen/WmwOKe

I'm not 100% sure this is a proper 'bug' or the way P5's noise algorithm is supposed to work but in my case it doesn't really export nice results.

Thanks for your help!
Louis

**Comment by Ajayneethikannan** [comment]
I think it's the intended behavior due to the  bell curve distribution of the function,
mentioned by Dan in this video,
https://www.youtube.com/watch?v=YcdldZ1E9gU

**Comment by Mamboleoo** [comment]
Oh I see, so I guess I only have two solutions then.
- Trying to fix the results by mapping the results from ~[0.3, 0.6] to [0, 1]
- Using an external noise algorithm

**Comment by b2renger** [comment]
@Mamboleoo if you want you could use noise as a speed instead of as a position ie use the noise to add something to both coordinates

**Comment by hellonearthis** [comment]
there is a nice Open simplex noise library here. [https://github.com/blindman67/SimplexNoiseJS](https://github.com/blindman67/SimplexNoiseJS)  Not as fast at the perlin noise,  so map() might be a better choice.  @shiffman did a great [live show last week on simplex noise](https://www.youtube.com/watch?v=O6dsGXhD0sc) in Java but was good to see the difference between the two noise types.
