### ISSUE TITLE
[WIP]GSOC 2019:Ideas needed for Improving p5.js WebGL functionality 

### ISSUE THREAD

**Issue by sanketsingh24** [processing/p5.js#3561]
#### Nature of issue?

- [x] Existing feature enhancement
- [x] New feature request

#### Most appropriate sub-area of p5.js?

- [x] WebGL (Mostly)

Hey! My name is Sanket Singh, and I intend to work on improving and enhancing the WebGL mode in this year's Google Summer Of Code. I have been contributing to p5.js since last December, so I know basic things about p5 and its workflow. At the moment, these are some of the functionalities, along with a little briefing, which can be implemented (clicking in my mind atm) and might benefit the community. I will be adding more about them in the comments-

- [`spotLight()`](https://github.com/processing/p5.js/issues/3561#issuecomment-469818481) - A spotlight is a type of directional light that is not coming from infinitely far away. That is, it has a source position. The closest real-world example would be of a torch's light, in the dark.

- [`emissiveMaterial()`](https://github.com/processing/p5.js/issues/3561#issuecomment-469840655) - What if, the material itself glows? Well, it is effectively an `ambientMaterial()` which does not rely on lighting upto a certain extent.

- `specularMaterial()` && `specularLight()` - If your sketch contains a red rubber ball, and a white light shines on it, diffuse red light is reflected in all directions. If that ball were to land in a puddle, the water on the surface of the ball would shine, or reflect a specular light. Specular refers to light which bounces off a surface in a preferred direction (rather than bouncing in all directions like a diffuse light).

- `fallOff()` for lights - What if you are standing with a lamp in your hands? Things which are further away from you would appear darker, or the light would 'fall off'. 

- `removeLights()` - Want to reset all the lights defined earlier, or just want no lighting effect in some part of your sketch? 

- a function, by which the users can crop or resize the image in the sketch itself, would prove helpful, along with a sister function, which would return the original image.

- `stopCamera()` - Want the camera to stop rendering after some time? Can be used with `createCamera()`.

I need reviews and suggestions on the above, along with maybe new ideas which can be implemented? Thanks for your time!

**Comment by sanketsingh24** [comment]
`spotLight(v1, v2, v3, x, y, z, nx, ny, nz, angle, concentration)`- 
We can understand this by taking the example of the torch. It is essentially an extension of `pointlight()` while also considering the opening of the torch, the direction of the torch, and torch's strength.

Arguments - 
1. The torch's light has a color, depicted by the three RGB values `v1,v2,v3` or we can pass `p5.color` object.
2. The position of the torch, whereas `x,y,z` being the coordinates of the position, a `p5.vector` can also be used. 
3. The direction of the light emitted by the torch, with `nx, ny, nz` being the coefficient for a normalized vector describing the direction of the light, and `p5.vector` can also be used here.
4. The width of the opening of the torch, which basically resembles a cone, here is measured by the solid angle `angle`. It will be a number.
5. The strength of the torch, used here as `concentration`. The higher value of `concentration` will let you concentrate the light in the middle more.

**Comment by sanketsingh24** [comment]
`emissiveMaterial(v1, v2, v3)`-
Here, the material doesn't emit the light, it just glows. So the neighboring objects don't react to its light, but if there is no light, you can still see the `emissivematerial()`. It can be a lot like ambient material. You can also check this demonstration to understand more-

![image](https://user-images.githubusercontent.com/24548786/53833726-3c007380-3faf-11e9-8b69-fb56376b1998.png)

The code for this will be - 
```js
void draw(){
 
  background(0);
 
  ambientLight(128, 128, 128);
 
  push();
    translate(width * 0.25, height * 0.5, 0);
 
    ambientMaterial(0,0,0);
    emissiveMaterial(255,0,0);
    sphere(width * 0.2);
 
  pop();
 
  push();
    translate(width * 0.75, height * 0.5, 0);
 
    ambientMaterial(255,0,0);
    emissiveMaterial(0,0,0);
    sphere(width * 0.2);
 
  pop();
}
```

So, here we can see if the strength of light is lesser than its emissive strength, emissive behaviour will be shown, whereas if strength of light is more, both strengths add up (This is doubtful to me, as they should add up or light's strength just shadow over the emissive strength @stalgiag) .

Here, `v1, v2, v3` will be the color, can be also passed on as p5.color object.

**Comment by Spongman** [comment]
*sigh*  #2547

**Comment by lmccart** [comment]
hi @sanketsingh24 thanks for your interest! we're discussing GSOC ideas over on the [processing forum](https://discourse.processing.org) so it's all in one place for everyone to see and contribute ideas to. feel free to open a thread over there.

**Comment by sanketsingh24** [comment]
Hello @lmccart, I posted this on the [forum](https://discourse.processing.org/t/ideas-and-suggestions-needed-for-improving-p5-js-webgl-mode-in-gsoc-2019/8865) too at the same time. I was just unsure where to post it so I am updating both :(
