### ISSUE TITLE
Community Live Chat at 10:00 PDT MARCH 12

### ISSUE THREAD

**Issue by stalgiag** [processing/p5.js#3566]
**Update:** The link for the chat is at https://gitter.im/processing/p5.js. If you don't have a Gitter account it is very easy to sign up with your Github account. See you at 10 PST!

Hi Everyone!

We wanted to experiment with new types of community engagement and one thought is to host a live chat meetup for current, past, or future contributors. The hope is that this format will facillitate a different type of conversation than is possible [on the forum](https://discourse.processing.org/) or on this repository page. The live format might allow for a more fluid casual conversational environment where people can talk about the structure of the codebase, the vision for the project, how to get involved, etc. 

The current plan is that the chat room will be live for 2 hours starting at **10:00 MARCH 12 PDT**. I know that this time doesn't work well with all timezones but if this iteration goes well there is a high likelihood that this will be recurring event sometimes happening at times that are favorable to other timezones. [Lookup your timezone here.](https://www.thetimezoneconverter.com/?t=10%3A00am&tz=PDT%20(Pacific%20Daylight%20Time)&)

I will hang out in there for the full two hours and other community members will drop in-and-out. Everything is going to be loose for the most part, but there will be rooms that are topical that will open up at regular intervals throughout the two hours. This is a more casual way of managing an agenda. If you are interested in a topic you can bounce into that room at a time, and the day of the meeting there will be a schedule posted here and in the chat. We will be using [Gitter](https://gitter.im/) for the chat. You can sign up easily with your Github account. Note that for the most part, this won't be an appropriate venue for troubleshooting problems with project as there will be limited time and human resources for those kinds of tasks. The [forum](https://discourse.processing.org/) is still the ideal venue for those questions.

Feel free to suggest agenda items below. I am starting a list here and I will edit this message and add to it as we go. Also, if anyone has ideas for how to mix up the format, I am very open to hearing those suggestions. 

**Agenda**
- Current contributor experience and thoughts on how to improve it
- Localization
- p5's Mission and Role as a Library

**Comment by limzykenneth** [comment]
I will probably drop in and out if I can, got a class on that time slot exactly but really look forward to this!

**Comment by stalgiag** [comment]
Hi all - 

The agenda is still pretty loose so instead of posting a complete schedule. I am just going to say that:

- 10 PST the main room discussion will be about 'Current contributor experience and thoughts on how to improve it'
- 10:30 PST The main room discussion will be about 'Internationalization'
- 11:00 PST the main room discussion will be about 'p5's Mission and Role as a Library'

If those topics have continued conversational momentum after their window a room will be opened up for them. If other topics that are relevant to contributors come up during the chat, rooms will be opened up for them so as not to distract from the main room topic. 

This is a casual experiment in different communication models for the community, so this format is subject to change at any point 👅

**Comment by stalgiag** [comment]
Thanks for coming out everyone! We will work to collect all the ideas tossed around during the chat and re-present them again in a different format over here.
