### ISSUE TITLE
GSoC 2019: Improve p5.js unit tests

### ISSUE THREAD

**Issue by ihsavru** [processing/p5.js#3567]
I am interested in working on improving the unit tests for p5.js. (I am not quite sure if I should post this on the issue tracker or the forum?) There aren't any existing issues on GitHub which would help me get started with testing. As mentioned in the Project List, this project would start with a survey to understand which areas are in need of unit tests and which are sufficiently covered. I went through the codebase, following are the areas which are *missing* unit tests:

* core 
  * shape/attributes.js
  * shape/vertex.js
  * helpers.js
  * init.js
  * legacy.js
  * p5.Graphics.js
  * p5.Renderer.js
  * p5.Renderer2D.js
  * shim.js
  * transform.js
* events
* image
  * filters.js
  * image.js
  * p5.image.js
* typography
  * attributes.js
  * p5.font.js
* utilities
 * conversion.js
* WebGL
  * 3d_primitives.js
  * interaction.js
  * light.js
  * loading.js
  * material.js
  * p5.Geometry.js
  * text.js

I would like others feedback on this! Am I missing something? Please let me know if I can pick up one of these files for creating unit tests, I would love to work on this!

**Comment by outofambit** [comment]
Hi again @ihsavru! Thanks for this list. If you're interested in working on some of these outside of Google Summer of Code, I can help get you started now! If you have questions about an idea or need guidance on forming your proposal for Google Summer of Code, please post to the [Processing Forum](https://discourse.processing.org). Thanks!

**Comment by ihsavru** [comment]
@outofambit Sure, I would like to work on this. How can I get started?

**Comment by outofambit** [comment]
@ihsavru awesome! 😄 Looking at the list above, I think a good place to start is [`modeAdjust()`](https://github.com/outofambit/p5.js/blob/a6f762c570925f78bd4980745552b43156ac8049/src/core/helpers.js#L10-L20). Lets work towards having a PR with tests for that function.

Some background on our unit testing framework:
* you can run the unit tests with `npm test`
* we use [mocha](https://mochajs.org) for structuring and running the unit tests
* we use [chai's `assert`](https://www.chaijs.com/api/assert/) to write individual statements about how code should behave
* the [color conversion unit tests](https://github.com/outofambit/p5.js/blob/a6f762c570925f78bd4980745552b43156ac8049/test/unit/color/color_conversion.js) are a good example to reference

Take a look at that, and let me what questions you have :)

**Comment by ihsavru** [comment]
@outofambit how do i run an individual test?

**Comment by sanketsingh24** [comment]
you can easily do it by appending `.only` on suite or test.

**Comment by outofambit** [comment]
> you can easily do it by appending .only on suite or test.

yeah i think that's the easiest approach! we just have to be careful not to commit the `.only`.

for example:

```js
suite.only('color/p5.ColorConversion', function() {
```

**Comment by ihsavru** [comment]
@outofambit What do I work on next? :)

**Comment by ihsavru** [comment]
Hi @outofambit, I created my first draft proposal for this project, I looking forward to some feedback from you. It would be great if you could review it 😅

**Comment by outofambit** [comment]
@ihsavru how about [conversion.js](https://github.com/processing/p5.js/blob/master/src/utilities/conversion.js) or add some more tests for the keyboard events? (@Ajayneethikannan just added [the first one](https://github.com/processing/p5.js/blob/master/test/unit/events/keyboard.js) last week!)

**Comment by chrisorban** [comment]
Hey @ihsavru and @outofambit  can we get this pull request for the iPad external keyboard sorted out before we add a keyboard unit test?

https://github.com/processing/p5.js/pull/3286

This is the second oldest pull request on p5 now.
