### ISSUE TITLE
Edit access of wiki

### ISSUE THREAD

**Issue by limzykenneth** [processing/p5.js#3568]
Given that we have moved the developer docs from the wiki to the repository itself, the wiki have fewer pages left and I'm questioning whether we should move the rest of the content or limit the editing of the wiki to contributors only. 

The reason I'm asking this is that over the past week or more I have been repeatedly undoing, I won't say malicious but I have no idea how it came about, changes to just one [specific page](https://github.com/processing/p5.js/wiki/Processing-transition/_history) which may be because it was renamed recently and so the link changed. (I left the latest change on for now to illustrate the issue)

**Comment by outofambit** [comment]
@limzykenneth sorry you've been dealing with that. 😕 i'm in favor of at least limiting editing the wiki to contributors. perhaps we can put a note on the landing page of the wiki that if someone would like access to contribute to the pages there?

i'm not familiar enough with the content there to have an opinion on moving it, so i'll defer to others on that point.

**Comment by Spongman** [comment]
weird. i noticed that one of the commits is basically a bunch of text from openprocessing.org. maybe they have a bug that's doing this?

**Comment by limzykenneth** [comment]
@Spongman Potentially somewhere has a hard link to the page and when it doesn't exist github just automatically goes to create new wiki page for it. Why the specific content is inputed? No idea.

**Comment by lmccart** [comment]
I think the reason for keeping the tutorials in the wiki was (1) they didn't seem to make sense in the developer_docs folder, or in the code part of the repo in general. But mostly (2) we wanted to make editing them faster and more accessible than going through the whole process of a PR. I think limiting to contributors only makes sense, and making the process for getting edit access very clear. (ex: open an issue or comment on an existing one noting the wiki page you'd like to edit, and you're be added as a contributor with edit access)

**Comment by limzykenneth** [comment]
@lmccart Sounds good to me

**Comment by lmccart** [comment]
updated edit access settings and added note here: https://github.com/processing/p5.js/wiki
