### ISSUE TITLE
 should setUnform work on a shader before shader() is called?

### ISSUE THREAD

**Issue by sanketsingh24** [processing/p5.js#3574]
EDIT:The main issue has been resolved and discussion for new idea started from [here](https://github.com/processing/p5.js/issues/3574#issuecomment-470211811).

#### Nature of issue?

- [x] Found a bug

#### Most appropriate sub-area of p5.js?

- [x] WebGL

#### Which platform were you using when you encountered this?

- [x] Desktop/Laptop

#### Details about the bug: 

- p5.js version: 0.7.3
- Web browser and version: Chromium 72.0.3626.119
- Operating System: Arch Linux Kernel: 4.20.11
- Steps to reproduce this:

While debugging for #3467, I found out that `shader()` if used in `draw()` along with `ambientMaterial()`, irrespective of the relative placement, `ambientMaterial()` seems to overwrite `shader()` effects. But when `shader()` is used in setup, `shader()` effects have a preference over `ambientMaterial()`. This certainly is an inconsistency, but I don't know for sure which behavior is correct.

#### Demonstration- 
![deepinscreenshot_select-area_20190301182837](https://user-images.githubusercontent.com/24548786/53639730-0de9ff00-3c50-11e9-9d78-09638945656e.png)

```js
var toonShader;

 function preload() {
  toonShader = loadShader('vert.glsl', 'frag.glsl');
}

 function setup() {
  createCanvas(windowWidth, windowHeight, WEBGL);
  noStroke();
  toonShader.setUniform('fraction', 1.0);
}

function draw() 
{
  background(0);
  var dirY = (mouseY / height - 0.5) * 2;
  var dirX = (mouseX / width - 0.5) * 2;
  directionalLight(204, 204, 204, -dirX, -dirY, -1);

  shader(toonShader);
  ambientMaterial(0, 255, 255);
  translate(-150, 0, 0);
  sphere(120);
  
  translate(300, 0, 0);
  ambientMaterial(0, 255, 255);
  sphere(120); 
}
```

![](https://user-images.githubusercontent.com/24548786/53639868-7b962b00-3c50-11e9-86f7-9c757b9fc8f9.png)

```js
var toonShader;

 function preload() {
  toonShader = loadShader('vert.glsl', 'frag.glsl');
}

 function setup() {
  createCanvas(windowWidth, windowHeight, WEBGL);
  noStroke();
  shader(toonShader);
  toonShader.setUniform('fraction', 1.0);
}

function draw() 
{
  background(0);
  var dirY = (mouseY / height - 0.5) * 2;
  var dirX = (mouseX / width - 0.5) * 2;
  directionalLight(204, 204, 204, -dirX, -dirY, -1);

  ambientMaterial(0, 255, 255);
  translate(-150, 0, 0);
  sphere(120);
  
  translate(300, 0, 0);
  ambientMaterial(0, 255, 255);
  sphere(120); 
}
```

**Comment by Spongman** [comment]
Can you try also moving the `setUniform` call into `draw()` after the `shader()` call?

**Comment by sanketsingh24** [comment]
@Spongman Oh yea it does, I understand now, kind of missed that line :sweat:

**Comment by Spongman** [comment]
it doesn't right now because the shader isn't initialized until the sketch calls the `p5.shader()` method.

i guess that poses a good question: should `setUnform` work on a shader before `shader()` is called?

**Comment by sanketsingh24** [comment]
> it doesn't right now because the shader isn't initialized until the sketch calls the p5.shader() method.

Yea I thought the same.

> i guess that poses a good question: should setUnform work on a shader before shader() is called?

I think this can be done by storing all the `setuniform` calls, and applying them after `shader()` is done? 

BTW I think there needs to be an error reporting failure of `setUniform` [here](https://github.com/processing/p5.js/blob/master/src/webgl/p5.Shader.js#L287).

**Comment by stalgiag** [comment]
> i guess that poses a good question: should `setUnform` work on a shader before `shader()` is called?

My instinct is to say no. Making this work would require keeping track of applied uniforms before the uniforms outside of the shader object or at least before initialization, and the gains aren't that significant imo. I can't think of a use case when it would be really advantageous to modify uniforms before applying the shader.

**Comment by sanketsingh24** [comment]
I don't think it would affect anything other than a user's experience, it just adds up another unnecessary element in core. I would close this out now.
