### ISSUE TITLE
createVector returns undefined when executed in draw()

### ISSUE THREAD

**Issue by Pancolar** [processing/p5.js#3577]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [x] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.7.3
- Web browser and version: Opera 58.0.3135.79
- Operating System: Windows 10
- Steps to reproduce this:
This does not happen in an environment that is otherwise free of code, so I will have to explain:
In draw, I set a variable to = createVector(3,0).
Then, I send this variable to another function. In that function I try rotating the vector, but I get the error "Uncaught TypeError: Cannot read property 'rotate' of undefined"
This message also comes up when I console.log the vector directly after creating it.

Stuff I tried:
- Changing the name of the variable
- Calling "new p5()" at beginning of script

**Comment by sanketsingh24** [comment]
I was not able to reproduce the error, can you please give us a snippet?

**Comment by Pancolar** [comment]
I take the issue back. I have another problem in my code, and made some stupid mistakes while trying to fix it. (I moved the call to the function in which the vector is rotated to outside draw(). That does not seem to be allowed)
