### ISSUE TITLE
Processing transition info missing?

### ISSUE THREAD

**Issue by stevedurie** [processing/p5.js#3599]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [ ] Desktop/Laptop
- [x] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 
- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

**Comment by stevedurie** [comment]
Hey All,

Just went to the Processing Transition Page on this repo and could not find the documentation that
was on this page. It should contain info on the various commands and syntax difference between the 2 frameworks. Has it moved?

**Comment by lmccart** [comment]
@stevedurie thanks for reporting. the content was erased but I've restored it [here](https://github.com/processing/p5.js/wiki/Processing-transition). we've recently restricted edit access to p5.js repo contributors so hopefully we get less lost content. if you'd like to edit any page, just open an issue or comment on an existing one and you'll be added to the editor list and have access.

**Comment by stevedurie** [comment]
Thanks Lauren for the timely response, I’m glad its back up.
I also just want to also special word of thanks for creating P5.js. Its awesome! :)
In the future, If I do see something that I can contribute to,  I will certainly make a request.

Thanks again,

Steve Durie
