### ISSUE TITLE
Changing 'require' statement to 'Import' statement (ES6)

### ISSUE THREAD

**Issue by plxity** [processing/p5.js#3603]
#### Nature of issue?

- [ ] Found a bug
- [x] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 
- Web browser and version: 
- Operating System: Windows
- Steps to reproduce this:

#### Feature enhancement details:
Changing require statement to import statement in app.js and other files.

**Comment by stalgiag** [comment]
Hi @plxity thanks for making a suggestion! We aren't moving the codebase to ES6 just yet. That will happen later in the year. We can definitely consider whether to go with `require` or `import` at that time.

**Comment by plxity** [comment]
@stalgiag Okay sure, no issues.
