### ISSUE TITLE
beginShape() not working with texture()

### ISSUE THREAD

**Issue by vedhant** [processing/p5.js#3606]
#### Nature of issue?

- [ x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ x] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [ x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 
- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

```
let img;
function preload() {
 img = loadImage('image.jpg');
}

function setup() {
  createCanvas(500, 500, WEBGL);
}

function draw() {
  background(0);
  //pass image as texture
  texture(img);

  beginShape();
  vertex(0, 0, 0, 0, 0);
  vertex(100, 0, 0, 1, 0);
  vertex(100, 100, 0, 1, 1);
  vertex(0, 100, 0, 0, 1);
  endShape(CLOSE);
}
```

```beginShape()``` and ```endShape()``` is not working with ```texture()``` in the latest commit on the master branch.

**Comment by stalgiag** [comment]
I think this is maybe not as clearly explained in the reference as is necessary but try putting `textureMode(NORMAL);` in setup **or** use `img.width` and `img.height` in places of the `1` in the 4th and 5th parameters, respectively.

**Comment by vedhant** [comment]
@stalgiag thanks! it works now.
