### ISSUE TITLE
updatePixels scaling issue for x, y parameters.

### ISSUE THREAD

**Issue by Ajayneethikannan** [processing/p5.js#3614]
#### Nature of issue?

- [x] Found a bug

#### Most appropriate sub-area of p5.js?

- [x] Core/Environment/Rendering

#### Which platform were you using when you encountered this?

- [x] Desktop/Laptop

#### Details about the bug: 

- p5.js version:  0.7.3
- Web browser and version:  Google Chrome 72.0.3626.121
- Operating System:  Ubuntu 16.04
- Steps to reproduce this:

This sketch can be used for reference https://editor.p5js.org/TheSkepticSniper/sketches/EWv9y7SPd
(For me the pixelDensity was 2, but you can check for different pixelDensity by changing it in setup).

In the reference for updatePixels , it says thay x, y, w, h are the x , y coordinates and the width , height to update respectively. The height and width parameters work irrespective of the pixelDensity , but the x and y parameters seem to depend on it.

From what I discovered , I think the bug is  due to how x, y, w, h are handled by the function.
w and h (width and height) are scaled by pixelDensity, while x and y are not scaled.
```
p5.Renderer2D.prototype.updatePixels = function (x, y, w, h) {
.
.
  w *= pd;
  h *= pd;

  this.drawingContext.putImageData(pixelsState.imageData, x, y, 0, 0, w, h);
.
.
}
```
This can be removed by changing the p5.Renderer2D.prototype.updatePixels function as : 
scaling x , y as 
```
x *= d;
y *= d;
```
Hoping for suggestions , 
Thank you !

**Comment by lmccart** [comment]
@Ajayneethikannan your fix looks correct to me, thank you!
