### ISSUE TITLE
webgl wiki indentation

### ISSUE THREAD

**Issue by micuat** [processing/p5.js#3623]
since I don't know how to make PR for wiki (or maybe it's not possible if one is not a collaborator) I'm making this issue for a small fix.

In https://github.com/processing/p5.js/wiki/Getting-started-with-WebGL-in-p5#offscreen-renderer the code example seems to have unnecessary indentation. This

```javascript
  let pg;
  function setup(){
    createCanvas(100, 100, WEBGL);
    pg = createGraphics(256,256);
  }
  function draw(){
    background(0);
    pg.background(255);
    pg.text('hello world!', 50, 50);
    //pass graphics as texture
    texture(pg);
    plane(100);
 }
```

should be

```javascript
let pg;
function setup(){
  createCanvas(100, 100, WEBGL);
  pg = createGraphics(256,256);
}
function draw(){
  background(0);
  pg.background(255);
  pg.text('hello world!', 50, 50);
  //pass graphics as texture
  texture(pg);
  plane(100);
}
```

**Comment by lmccart** [comment]
thanks @micuat. I've just added you as a contributor for this repo so you should be able to edit the wiki once you accept the invite.

**Comment by micuat** [comment]
thanks, I just edited it!

**Comment by lmccart** [comment]
thanks @micuat!
