### ISSUE TITLE
beginShape/endShape vertex coloring

### ISSUE THREAD

**Issue by ekeneijeoma** [processing/p5.js#364]
It'd be great if would display a gradient line like in Processing
 
beginShape()
stroke(0)
vertex(x1, y1)
stroke(255)
vertex(x2, y2)
endShape();

**Comment by lmccart** [comment]
I'm going to close this one for now since there hasn't been any further action on this since last fall and it is more of a ++ feature. If anyone is interested in adding it we can reopen.
