### ISSUE TITLE
createCapture() throws DOM error on Chrome

### ISSUE THREAD

**Issue by bengrosser** [processing/p5.js#3645]
#### Nature of issue?
- [x] Found a bug

#### Most appropriate sub-area of p5.js?
- [x] Other --> DOM

#### Which platform were you using when you encountered this?
- [x] Desktop/Laptop

#### Details about the bug: 

- p5.js version: 0.7.3 and earlier
- Web browser and version: Chrome 73.0.3683.86
- Operating System: MacOS 10.14.3
- Steps to reproduce this:
1. Create a sketch
2. Include this line in `setup()`: `capture = createCapture(VIDEO);`
3. Run on Chrome. This will produce `Error {}` in the console, and in devtools says `DOMException`

Another quick way to see this error is to try out the [p5js reference example for createCapture()](https://p5js.org/examples/dom-video-capture.html) while using Chrome.

This still seems to work in Firefox.

**Comment by limzykenneth** [comment]
I'm not able to replicate this issue with the exact same setup as yours. Does the capture work at all or does it halt upon throwing the error? Do you have any extensions running on Chrome? If so can you try disabling them.

**Comment by lmccart** [comment]
Maybe also check: is the camera allowed for this site?

**Comment by bengrosser** [comment]
The camera does not work at all. I'm testing this via https://editor.p5js.org, and that site is explicitly allowed in my Chrome content settings for camera access. I just tried this on a different computer (same browser and OS version) and am getting the same result. [Here's the sketch I'm using](https://editor.p5js.org/bengrosser/sketches/3lDgO0Q4j). Does this work for you? Or am I doing something incorrectly?

**Comment by limzykenneth** [comment]
@bengrosser The sketch you provided works for me perfectly with no issues on Firefox, Safari and Chrome. 

Can you see if you can get more info about the DOMException you got? The name and message would be helpful.

**Comment by bengrosser** [comment]
Well, I'm at a loss. Today it works as expected. Same OS version, same Chrome version (even with all my extensions installed). On both machines I tested on. I'll report back if I see the problem behavior again.

**Comment by tiansheng97** [comment]
Hi! 1st time trying this and i also encounter the same problem on my pc but not on my smartphone. Weird. I also tried asking some of my friends to test it and some can run it and some cant. Those who cant all throw the same error: DOMException. i tried both on [p5js reference for createCapture()](https://p5js.org/examples/dom-video-capture.html) and also on [my code](https://editor.p5js.org/tiansheng97/present/xrKtqjXzi). Hope you can help me solve my problem. Thanks

**Comment by lmccart** [comment]
@tiansheng97 could you try out this link and see if the example works? it would help us isolate the issue a little more. thanks!
https://webrtc.github.io/samples/src/content/getusermedia/gum/

**Comment by tiansheng97** [comment]
@lmccart  i tried on my pc and on my smartphone as well. Nothing wrong with my smartphone as it is able to run it while on my pc it gives a getUserMedia error: NotFoundError. Is it some security error or something? Because i found at that those who cant use createCapture() all have a same behavior which is it never pops a notification asking the user whether to grant it the permission to use the camera.

**Comment by lmccart** [comment]
@tiansheng97 if this example works, that indicates that it's an issue with your pc and camera functionality, and not with the p5.js library itself. it sounds like your pc or browser might be blocking the camera by default. I would take a look through your settings on both your pc and browser and see if you can find any related to allowing camera or "getusermedia" which is the name of the functionality behind the camera.

**Comment by bengrosser** [comment]
This example doesn't work for me on Chrome 73.0.3683.103 (MacOS), I get a
DOMException. It does work on my Firefox Dev Edition 67.0b15.

Happy to help isolate more if helpful.

**Comment by lmccart** [comment]
@bengrosser by "this example" do you mean the webrtc one?

**Comment by bengrosser** [comment]
yes, the webrtc one is what i was referring to.

**Comment by chachramohit** [comment]
this error was coming in my chrome browser.
but it is working properly in Firefox browser.
