### ISSUE TITLE
Inconsistent behaviour of utilities/conversion.js

### ISSUE THREAD

**Issue by ihsavru** [processing/p5.js#3658]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [x] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug: 
While designing unit tests for `utilities/conversion.js`, I came across the following behaviour:

- `float()`, `int()` and `hex()` behave differently on `Infinity` as input. `float(Infinity)` returns `Infinity`, however `int(Infinity)` returns 0 and `hex(Infinity)` returns "INFINITY". These should behave uniformly. Similarly, for `NaN` as input.

- `hex()` should return `NaN` for all invalid hex strings. `hex("cat")` returns `202` while  `hex("mat")` returns `NaN`.

**Comment by lmccart** [comment]
There's actually an interesting discrepancy between how parseInt() and parseFloat() handle Infinity in native JS: https://stackoverflow.com/questions/38357220/why-parseintinfinity-returns-nan-and-parsefloatinfinity-returns-infinity.

I would vote that we make `float(Infinity)` and `float(Infinity)` return Infinity. It's less clear what `hex()` should do, but I suppose it could return the same?

**Comment by limzykenneth** [comment]
> `int(Infinity)` and `float(Infinity)` return Infinity

That sounds good to me as well, also `int(-Infinity)` and `float(-Infinity)` should return `-Infinity`

For `hex()` the value would overflow after `4294967295` (with `4294967296` being `00000000`), should we set a maximum value based on the number of hex digits and either
1. return the max value passed through `hex()`, ie. `FFFFFFFF`, or
2. throw a [range error](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError) if that's the correct use for it.

**Comment by lmccart** [comment]
I like `FFFFFF` for `hex(Infinity)`, and I assume `000000` for `hex(-Infinity)`.
