### ISSUE TITLE
Variable name conflict in per-pixel-lighting manual test

### ISSUE THREAD

**Issue by stalgiag** [processing/p5.js#3659]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

There is a variable named `lights` in the [per-pixel-lighting manual test example](https://github.com/processing/p5.js/blob/master/test/manual-test-examples/webgl/material/perPixelLighting/sketch.js#L12). This is a problem now because p5 was recently updated [with a `lights()` function.](https://github.com/processing/p5.js/pull/3553) and there is a naming conflict causing errors in the manual test.

The to-do here is to change the name of the variable `lights` in the manual test example linked above.

**Comment by WenheLI** [comment]
Is anyone working on this? I can help with it!

**Comment by stalgiag** [comment]
Sounds good @WenheLI thanks!

**Comment by stalgiag** [comment]
close via #3661
