### ISSUE TITLE
improved documentation for p5.CreateGraphics() and renderer objects

### ISSUE THREAD

**Issue by AndrewWPhillips** [processing/p5.js#3663]
#### Nature of issue?

- [ ] Found a bug
- [x] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Feature enhancement details:
I got here by clicking the "please let us know" link at the bottom of the p5.createGraphics() reference page.  The error I want to report is that at the top of the page it says that a p5.Renderer is returned but at the bottom it says that a P5.Graphics is returned.

However, there is the more general issue that it is a bit hard to work out the relationship between p5.Graphics, p5.Renderer, p5.Image, p5.Element, etc, and how to create and use them.

BTW Its a great library, thanks. It's just a bit hard to work out how to do more complicated things.

**Comment by limzykenneth** [comment]
It returns a p5.Graphics object. 

p5.Graphics extends p5.Element which itself it the wrapper that is used to represent all DOM objects. p5.Graphics is just a HTML canvas that is hidden in the DOM (you can open up the browser's inspector and you should see it in the DOM).

p5.Renderer extends p5.Element as well and it the base class that make up the drawing canvases. It is controlled by the `draw()` loop directly.

In 2D context, the canvas is an instance of p5.Renderer2D which extends p5.Renderer. p5.Image extends p5.Renderer2D.

This is all very complicated and I may be completely wrong here but that's what I understand from the source. I agree very much that it all can be much better explained and documented, especially it can be a bit ambiguous what methods are available for p5.Graphic and p5.Image.

**Comment by Spongman** [comment]
would it help to include inherited methods in a class' description (maybe with some indication that they're inherited from a base class) ?

or maybe just expand the auto-generated text that says "Extends p5.Element" to something more descriptive, like 'p5.Graphics also includes all the properties and methods of the p5.Element class, and you can use a p5.Graphics object wherever a p5.Element is required.'

**Comment by outofambit** [comment]
thanks for filing this @AndrewWPhillips! i totally agree. i think this needs more explanation than including the inheritance tree for each class in the docs. (@lmccart i'd be happy to look at this as well.)

**Comment by lmccart** [comment]
we've made some progress on this, working on a very basic flowchart that shows the inheritance of the main graphics objects. the next step would be adding this into the markdown docs somewhere and then adding entries below that elaborate on some of the specifics of each class. feedback on this diagram is welcome, I'm working on finding a way to make it modifiable by other users and stored in the repo
<img width="1239" alt="Screen Shot 2019-10-14 at 9 16 17 AM" src="https://user-images.githubusercontent.com/191056/66766596-4c40d100-ee63-11e9-80ce-bb33365aff9a.png">
