### ISSUE TITLE
P5.Table size limit?

### ISSUE THREAD

**Issue by pixclautotech** [processing/p5.js#3665]
#### Nature of issue?
- [x ] Found a bug ... maybe
- [ ] Existing feature enhancement
- [ x] New feature request

#### Most appropriate sub-area of p5.js?
- [x ] IO

#### Which platform were you using when you encountered this?
- [x ] Desktop, Windows 10-32bit

#### Details about the possible bug: 
Great library, easy to learn and fun to use.  I'm reading electrical power data from a local networked sensor, using loadJSON, every 5 seconds, running in the latest Chromium browser. Data is placed into a P5.Table, and saved to a CSV every 5 minutes i.e. 60 data lines in the CSV. This all works well, just generates a LOT of data files. Setting the count to 8640 (i.e. 12 hours of data lines) is an extreme test, and would result in a CSV of around 1MB.

This crashed Chromium some time during the overnite test.   I'm currently running a new test  with a smaller count (4320, which I expect to crash as well).   I suspect, and it's very reasonable to assume, that P5.Table has a size limit.  Are you able to state what that size limit might be?  My aim it to identify the issue as P5, Chromium, or both.

#### Related to above, new feature details:
It would be really helpful if a     appendTable(...)    method could be added to P5. A new CSV would be created with saveTable(...), in my 5 seconds case then subsequent data sets would call appendTable(...).    This has the benefit of allowing the CSV to be copied elsewhere  and processed with Excel, while the original file keeps getting appended. A new CSV would be created by my app after, say, 12 hours.

I know that new methods (if approved) take time, so meanwhile, I'm looking at the P5 source and will see about writing something myself.

regards from Ottawa, CANADA

**Comment by limzykenneth** [comment]
It may have caused the browser to run out of memory as that is a pretty large data structure. We can't say for sure what is the size limit as it depends on browser, OS and the hardware itself and could even vary by the current usage of the computer.

Something like `appendTable()` would pose certain challenge as a sketch running in the browser will have no way to access a user's file system (for security purposes, you don't want a malicious website accessing your files) and so it cannot append to an existing file. If you don't mind the extra work though, you can save to a new file every time then at the end when the 12 hours have passed, merge the generated csv on your computer locally into one.

**Comment by pixclautotech** [comment]
Hi Kenneth,
thanks for the fast reply.
It does seem to be an "out-of-memory" issue.

>...save to a new file every time then at the end when the 12 hours have 
>passed, merge the generated csv

This is what we currently do. With 4000 data lines in the CSV, the app still 
fails, and with 2000 lines, it works on the client's PC. On a similar PC in 
our lab, we can run a simple test app based on P5.Table sample code, and it 
quite happily creates the 8640 CSV entries with content similar to our app. 
The difference is the test app is in a tight 'for' loop, while our app does 
the Table.addRow  and eventually save in the loadJSON callback.

The next step is looking closely at the client's PC for hardware issues 
(Power  Options like sleep and hibernate settings) and in the browser dev 
console.

regards
Stewart DIBBS
PiXCL Automation Technologies Inc.
Gatineau, Quebec, Canada

**Comment by limzykenneth** [comment]
I'm going to close this issue as it is not something we can easily fix in the library. If you have further questions, feel free to post them on the [forum](https://discourse.processing.org) for help. Thanks.
