### ISSUE TITLE
Circles sometimes not drawn at center coordinates

### ISSUE THREAD

**Issue by bgenchel** [processing/p5.js#3668]
#### Nature of issue?
Seems to either be a bug or bad information in the docs. I want to draw a circle, and then have a little radiate out animation by drawing progressively larger and increasingly less opaque circles on it over time. Every time I draw one of these circles, I use the position of the original circle as the new circles center. And yet, it doesn't seem like that argument it taking. The radiation circle is always off down and to the right. By a quite noticeable amount
- [ ] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [x ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x ] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 
- Web browser and version:  Chrome 73.0.3683.86 
- Operating System: 
Max OSX High Sierra 
- Steps to reproduce this:

just create an instance of this class and see what happens

```
function Collision(x, y) {
    this.position = createVector(x, y);
    this.r = 4.0;

    this.color = color(255, 255, 255);
    
    this.time = 0;
    this.lifespan = 800;

    this.animating = true;
    this.animateClock = 0;
    this.animateTime = 50;
    this.animateStartRadius = this.r;
    this.animateMaxRadius = this.r * 2;
    this.animateColor = color(255, 255, 255);
}

Collision.prototype.animate = function() {
    this.animateClock++;
    let age = (this.animateClock / this.animateTime);
    if (age > 1) {
        this.endAnimation();
        return;
    }
    let radius = this.animateStartRadius + age * (this.animateMaxRadius - this.animateStartRadius);
    this.animateColor.setAlpha(255 - 255 * age);
    stroke(this.animateColor);
    fill(this.animateColor);
    push();
    console.log('animate:: this.position.x = ' + this.position.x)
    console.log('animate:: this.position.y = ' + this.position.y)
    translate(this.position.x, this.position.y);
    beginShape();
    circle(radius, radius, radius);
    endShape(CLOSE);
    pop();
}

Collision.prototype.endAnimation = function() {
    this.animating = false;
    this.animateClock = 0;
    this.animateCircle = null;
}

Collision.prototype.run = function(){
    this.update();
    if (this.animating) {
        this.animate();
    }
    this.time += 1;
}

// Method to update fading basically
Collision.prototype.update = function() {
    // render
    let alpha = 255 - 255 * (this.time / this.lifespan);
    this.color.setAlpha(alpha);
    fill(this.color);
    stroke(this.color);
    // strokeWeight(1);
    push(); // start a new drawing state
    // console.log('update:: this.position.x = ' + this.position.x)
    // console.log('update:: this.position.y = ' + this.position.y)
    translate(this.position.x, this.position.y);
    beginShape();
    circle(this.r, this.r, this.r);
    endShape(CLOSE);
    pop();
}

Collision.prototype.setAge = function(pct) {
    // input is percentage of life over
    this.time = int(this.lifespan * pct);
}
```

**Comment by lmccart** [comment]
Thanks @bgenchel! Can you please post a simpler version of your code? The most minimal snippet that will illustrate the issue. It's hard to debug when the code sample is so complex. 

One thing to keep in mind is that calls to translate() will accumulate until the next time draw() runs. So perhaps the issue you're seeing is from the translate() calls adding on to each other?

**Comment by bgenchel** [comment]
Hi, sorry about that. I actually figured it out! It was my dumb mistake. Once translated, I should have been setting the x and y coordinates of the circles to (0, 0), but here I'm setting them to the radius values. All fixed! Sorry for the trouble!
