### ISSUE TITLE
video.get() not working 

### ISSUE THREAD

**Issue by wezzahd** [processing/p5.js#3670]
#### Nature of issue?

- [x ] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ x] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [ x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: <0.7.3>
- Web browser and version: < Chrome 73.0.3683.86 (Official Build) (64-bit)>
- Operating System: <MacOSX 10.10.05>
- Steps to reproduce this:
<function setup() {
  createCanvas(320, 240);
  video = createCapture(VIDEO);
  video.size(320, 240);
}

function draw() {
  background(51);
  var snapshot = video.get();
  image(snapshot, 0, 0);
}

Error : Uncaught InvalidStateError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0. (sketch: line 10)
>

**Comment by limzykenneth** [comment]
This has recently been fixed (see #3549). The next release coming April 8 will contain the fix.
