### ISSUE TITLE
Capture pixel array is empty, even after calling loadPixels()

### ISSUE THREAD

**Issue by sam-peach** [processing/p5.js#3673]
#### Nature of issue?

- [x ] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

I'm trying to manipulate the pixel array from a video feed. The video will stream without issue but I can't access the 'pixels' array, even after loading it.

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ x] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [ x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: p5.js v0.7.3 
- Web browser and version: Google Chrome | 73.0.3683.86
- Operating System: Windows 10.0.17763 Build 17763
- Steps to reproduce this:
**HTML file:**
<!DOCTYPE html>
<html>
  <head>
    <script src="p5/p5.min.js"></script>
    <script src="p5/addons/p5.dom.min.js"></script>
    <script src="p5/addons/p5.sound.min.js"></script>
    <script src="sketch.js"></script>
  </head>
  <body>
  </body>
</html>

**JS file:**
var video;

function setup() {
  createCanvas(320, 240);
  video = createCapture(VIDEO);
  video.size(320, 240);
  video.hide();
}

function draw(){
  background(51);
  video.loadPixels();
  console.log(video.pixels) << This is displaying an empty array.
}

**Comment by lmccart** [comment]
thanks, this is being tracked here: https://github.com/processing/p5.js/issues/3549
it has been fixed and will be in the next release (april 8)
