### ISSUE TITLE
keyIsDown() should return false onBlur

### ISSUE THREAD

**Issue by ihsavru** [processing/p5.js#3674]
`onBlur()`, we assume that all keys have been released, therefore `keyIsDown(x)` should return false for every key `x`. However, it currently returns undefined because onBlur resets `downKeys` to empty object

```
p5.prototype._onblur = function(e) {
  this._downKeys = {};
};

p5.prototype.keyIsDown = function(code) {
  p5._validateParameters('keyIsDown', arguments);
  return this._downKeys[code];
};
```

**Comment by WenheLI** [comment]
That's true! I can fix it if you haven't dealt the code yet!

**Comment by ihsavru** [comment]
@WenheLI  please go ahead!

**Comment by lmccart** [comment]
fixed with https://github.com/processing/p5.js/pull/3696
