### ISSUE TITLE
loadJSON erroring in 0.7.2 & 0.7.3 when using jsonp

### ISSUE THREAD

**Issue by piecesofuk** [processing/p5.js#3684]
#### Nature of issue?

- [X] Found a bug

#### Most appropriate sub-area of p5.js?

- [X] Data
- [X] Events
- [X] IO

#### Which platform were you using when you encountered this?

- [X] Chromebook

#### Details about the bug: 

- p5.js version: 0.7.2 & 0.7.3
- Web browser and version: Google Chrome	74.0.3729.58 (Official Build) beta (64-bit)
- Operating System: ChromeOS
- Steps to reproduce this:
Using the following code
```
let url = "https://en.wikipedia.org/w/api.php" +
           "?action=parse&format=json&prop=langlinks" +
           "&section=0&redirects&page=dog";

function setup() {    
    loadJSON(url, gotData, "jsonp");
  }

function gotData(data) {
  console.log(data);
}
```

In versions prior to 0.7.2 the data loads and is logged to the console. In versions 0.7.2 & 0.7.3 the data is not logged and I get two identical errors in the Chrome error console of 
```
p5.min.js:3 Uncaught (in promise) TypeError: Cannot read property 'get' of undefined
    at VM363 p5.min.js:3
```

However, when I view the Network tab it appears that the json has been loaded from the network.

Example sketches:
[Using 0.7.3](https://editor.p5js.org/piecesofuk/sketches/HjFnwOPve)
[Using 0.7.1 ](https://editor.p5js.org/piecesofuk/sketches/gHNAM5CPO)

**Comment by limzykenneth** [comment]
It's failing on the file size checking stage, JSONP doesn't return headers so the file size cannot be checked by looking at the headers. I'll see what fix I can come up with.
