### ISSUE TITLE
How to rotate my video captured through webcam?

### ISSUE THREAD

**Issue by pip33eed** [processing/p5.js#3688]
I don't see any feature that does this, rotating the image drawn every frame just makes it lag like hell. 
I am trying to just flip the capture of the video, horizontally.

**Comment by stalgiag** [comment]
Hi @pip33eed ! This github is for feature requests, bug tracking, and library structure discussion. It is best to ask these kinds of questions at [discourse.processing.org](https://discourse.processing.org/). Good luck!
