### ISSUE TITLE
save() not working

### ISSUE THREAD

**Issue by liasomething** [processing/p5.js#369]
when i try save from the reference: http://p5js.org/reference/#/p5/save

for just testing the save() function i put in into the setup:

function setup() {
 var canvas = createCanvas(800, 600);
 save(canvas, 'myCanvas.jpg');      // Saves canvas as an image
 }

function draw() {
  background(255,0,0);
}

---> i am getting the error:
Uncaught TypeError: Expecting a function in instanceof check, but got undefined 

(maybe i am missing something here ? i did include the p5.dom.js)

when i just use save('myCanvas.jpg'); 
then it works though...

**Comment by swhit194** [comment]
I was making use of saveCanvas having started working in P5JS - I was thinking that a circle on its own when saved as a PNG would give me the object on its own (with a transparent background)- it didn't.  

That's OK as I get that it saves the entire canvas of pixels, but despite showing this canvas in the web browser, and successfully saving it out to a file, on opening this in Preview (on Mac) or loading it into MS Word, it shows up as nothing.  Not sure whether this is an error, or just me.

**Comment by lmccart** [comment]
could you please post a minimal code snippet that illustrates the problem happening?

**Comment by swhit194** [comment]
@lmccart thanks for your reply.  I have it working now in a different sketch.

I think it was caused by a rookie mistake of setting up a background and running the code with saveCanvas that hadn't been started with a createCanvas command.  That would explain why it was just black in mac Preview, and all white and blank in MS Word.  Must get better at this. :)

**Comment by lmccart** [comment]
great, glad you got it working :)

**Comment by nkg447** [comment]
How to save the current state of the canvas so that the another time, draw() function is called the drawing should start from the previous state not from the start
