### ISSUE TITLE
npm run grunt fails at eslint-samples:source with "prefixLength of undefined".

### ISSUE THREAD

**Issue by JoshuaGrams** [processing/p5.js#3692]
* p5.js commit e838315a
* Windows 10 version 1803 (OS Build 17134.706)
* Nodej.s 10.15.3
* npm 6.4.1

I cloned the repository from github, did `npm install`, then `npm run grunt`. It fails at `eslint-samples:source` (`npm run grunt eslint-samples:source` gets the same error faster) with "Warning: Cannot read property 'prefixLength' of undefined Use --force to continue."

Then it says "Aborted due to warnings." and the stacktrace is from `node_modules/npm-lifecycle/index.js` which doesn't look helpful.

I did find this comment https://github.com/processing/p5.js/issues/3387#issuecomment-447070729 and the following one, which suggests that it's a line-endings thing. But I checked and there are no CRLFs in the `src/` or `lib/` directories, and adding them produced many errors wanting the CRs removed.

Any suggestions?

**Comment by stalgiag** [comment]
Hi @JoshuaGrams how did you clone the repository? This definitely seems like a line-endings problem. I develop on Windows as well. I'd also check to see what value you have for `core.autocrlf` with `git config --list`

**Comment by JoshuaGrams** [comment]
I have `core.autocrlf` set to `false`, and there are no DOS line endings in the project. I tried switching to DOS line endings and it just gave errors about wanting to remove the '\r' characters...

**Comment by JoshuaGrams** [comment]
Oh, huh. I switched it to DOS line endings again and now the build works. I wonder what I did wrong the other two times I tried it?

Well, thanks for your time.

**Comment by fal-works** [comment]
For anyone who reached here:
I just had the same issue, and after doing the below `eslint-samples:source` succeeded.

1. Set autocrlf so that the line endings will be automatically converted: `git config --local core.autocrlf true`
2. Remove all files except `.git` and restore them again by `git restore .`

Had then another error in the succeeding test task, but anyway :)
