### ISSUE TITLE
implement PShape

### ISSUE THREAD

**Issue by lmccart** [processing/p5.js#37]
http://processing.org/reference/PShape.html
#### Shape
- PShape
- createShape()
- loadShape()
#### Loading & Displaying
- shape()
- shapeMode()

Later version!

**Comment by asfarley** [comment]
May I ask what happened here? That link gives a 404. I'm interested in the PShape functionality for rendering large point-clouds.

**Comment by Spongman** [comment]
i believe that issue was moved here: https://github.com/processing/p5.js/issues/458

**Comment by asfarley** [comment]
From my reading, that discussion is more about re-implementing p5.js to render SVG, rather than replacing PShape. 

Really, what I want to do is optimize the display of a point-cloud with many thousands of points. Somewhere I read that PShape is the way to do this in Processing, hence my question.

Is there any recommended facility for making something like a vertex buffer to contain an object that I'm rendering repeatedly at different locations? Is p5.js looking for something like this as a contribution?

**Comment by Spongman** [comment]
do you mean something like this: https://p5js.org/reference/#/p5/vertex ?

**Comment by b2renger** [comment]
I think what @asfarley is referring to is creating a PShape object in which you could store points an geometric forms ready to be rendered in one call and I guess on the gpu 

probably something like that : https://processing.org/tutorials/pshape/
Dan talks about it and refers to this as "retained" mode to draw VBO

**Comment by asfarley** [comment]
@b2renger yes, that's exactly what I meant.

**Comment by rsodre** [comment]
I don't understand why this has been closed.
This is a fair request, to implement a great Processing feature, and was not addressed by #458 as mentioned.
Please reopen it, even if it's not on the roadmap, it should be.

**Comment by darthgrayter** [comment]
I agree, I feel like this should be a default feature.

**Comment by designbyadrian** [comment]
I really hate to +1 an issue, but this is an unsolved issue from 2013 that still remains unresolved with no opinion from the devs why it shouldn't be included. I'm experiencing huge slowdowns while drawing many vertices in each draw() call. Being able to cache the shape somehow would be a solution.

**Comment by davepagurek** [comment]
> I'm experiencing huge slowdowns while drawing many vertices in each draw() call. Being able to cache the shape somehow would be a solution.

Is this something that would be solved by drawing to a p5.Graphics and reusing that? Or for 3D, creating a p5.Geometry and then drawing it with `model()`?
