### ISSUE TITLE
Processing 3 trails and anti-image auto scaling

### ISSUE THREAD

**Issue by EricLindesay** [processing/p5.js#3701]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [x] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 
- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

**Comment by EricLindesay** [comment]
So I have a problem where I am trying to have a character move but they leave their remnants behind and the only way I know how to fix this is just draw it again over the original image with the new position. Is there any better way then this?

Also I would like to know how you can make it so when you import an image file, the image doesn't automatically fit to screen and goes 'off' the screen where the camera can be moved to later. 
Thanks

**Comment by limzykenneth** [comment]
Hi @EricLindesay, this is the p5.js repo and not the Processsing repo, also for coding help it is best to post them on the [forum](https://discourse.processing.org/). Github issues are mainly used for bug reports and feature requests. Thanks!
