### ISSUE TITLE
while editing for loops increment with auto refresh on crashes browser

### ISSUE THREAD

**Issue by ddddtttt6666** [processing/p5.js#3702]
#### Nature of issue?

- [x ] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ x] Other (web editor)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x ] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.7.3
- Web browser and version: Chrome 73.0.3683.103
- Operating System: Windows
- Steps to reproduce this:

just editing for loops increment to 0 while auto refresh on causes browser to crash

**Comment by stalgiag** [comment]
Hi @ddddtttt6666 thanks for filing an issue. This isn't a bug with p5. What I assume is happening is that your for loop isn't incrementing and so it never exits which means it runs infinitely causing the browser to crash. It looks like like [the editor is already tracking this on their repository](https://github.com/processing/p5.js-web-editor/issues/698). Closing this for now.
