### ISSUE TITLE
angleMode(DEGREES) still being used in p5.Vector.fromAngle example

### ISSUE THREAD

**Issue by limzykenneth** [processing/p5.js#3704]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Documentation

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [ ] Desktop/Laptop
- [x] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.8.0

This is related to the issue looked at in #2541 and is fixed by #2563. Although the documentation in the parameter field of `p5.Vector.fromAngle` states that it receives the angle in radians, the [example code](https://p5js.org/reference/#/p5.Vector/fromAngle) still includes `angleMode(DEGREES)` despite it's not doing anything in that particular example. I was initially confused by it and thought `p5.Vector.fromAngle` does use `angleMode()`.

The description itself should probably also explicitly mention that this function is not affected by `angleMode()`

**Comment by jpegsarebad** [comment]
I'm on it!
