### ISSUE TITLE
lights() method not recognized by recent p5js version

### ISSUE THREAD

**Issue by estevancarlos** [processing/p5.js#3705]
#### Nature of issue?

- [X] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [X] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.7.3
- Web browser and version: 72.0.3626.119
- Operating System: Windows 10
- Steps to reproduce this:
Copy and paste the code example provided here: https://p5js.org/reference/#/p5/lights
Paste that code example into editor.p5js.org. It produces the error: Uncaught ReferenceError: lights is not defined (sketch: line 6)

**Comment by stalgiag** [comment]
Hi @estevancarlos, `lights()` is [only available in 0.8.0.](https://p5js.org/download/). Closing for organization purposes.
