### ISSUE TITLE
add unit tests for dist()

### ISSUE THREAD

**Issue by outofambit** [processing/p5.js#3713]
(incomplete) list of test cases:
* handles overflows/rounding correctly
* handles infinities
* handles string parameters
* handles arbitrary-length argument lists 

_Originally posted by @outofambit in https://github.com/processing/p5.js/pull/3457#issuecomment-460075241_

**Comment by JithinKS97** [comment]
I'm ready to take up this issue. But I see that hypot is not attached to p5 prototype.

**Comment by outofambit** [comment]
my mistake @JithinKS97! this should be `dist()` not `hypot()`. updating the original issue description now!

**Comment by JithinKS97** [comment]
Oh! So let me see if I can take up the remaining test cases.

**Comment by JithinKS97** [comment]
I've written some test  cases. Here are they.

` test('should return infinity if coordinate of a point is at infinity', function() {
      result = myp5.dist(0, 0, Infinity, 0);
      assert.equal(result, Infinity);
    });
    test('should return infinity if coordinate of a point is at -infinity', function() {
      result = myp5.dist(0, 0, -Infinity, 0);
      assert.equal(result, Infinity);
    });
    test('should handle overflow correctly', function() {
      result = myp5.dist(0, 1e200, 0, 1e199);
      assert.equal(result, 9e199);
    });
    test('should handle string parameters correctly', function() {
      result = myp5.dist(0, 0, '4', '3');
      assert.equal(result, 5);
});`

By handling arbitrary length arguments, do you mean that we should check that dist returns undefined when unsuitable no. of arguments provided?

**Comment by JithinKS97** [comment]
I've written some test cases. Here are they.

`function() {
 test('should return infinity if coordinate of a point is at infinity', function() {
      result = myp5.dist(0, 0, Infinity, 0);
      assert.equal(result, Infinity);
    });
    test('should return infinity if coordinate of a point is at -infinity', function() {
      result = myp5.dist(0, 0, -Infinity, 0);
      assert.equal(result, Infinity);
    });
    test('should handle overflow correctly', function() {
      result = myp5.dist(0, 1e200, 0, 1e199);
      assert.equal(result, 9e199);
    });
    test('should handle string parameters correctly', function() {
      result = myp5.dist(0, 0, '4', '3');
      assert.equal(result, 5);
    });
}`

By handling arbitrary length arguments, do you mean that we should check that dist returns undefined when unsuitable no. of arguments provided?

**Comment by JithinKS97** [comment]
I've written some test cases. Could you please check them?

 test('should return infinity if coordinate of a point is at infinity', function() {
      result = myp5.dist(0, 0, Infinity, 0);
      assert.equal(result, Infinity);
    });
    test('should return infinity if coordinate of a point is at -infinity', function() {
      result = myp5.dist(0, 0, -Infinity, 0);
      assert.equal(result, Infinity);
    });
    test('should handle overflow correctly', function() {
      result = myp5.dist(0, 1e200, 0, 1e199);
      assert.equal(result, 9e199);
    });
    test('should handle string parameters correctly', function() {
      result = myp5.dist(0, 0, '4', '3');
      assert.equal(result, 5);
    });

By saying arbitrary length paratmeters, do you mean that dist should return undefined when unsuitable no. of arguments provided?

**Comment by outofambit** [comment]
@JithinKS97 these are looking good, thank you! i went back and looked at the arbitrary length of parameters thing and i think we can ignore that case as it applies to the underlying code and not `dist()` itself.

It would be great to add 3D versions of all of these test cases too if you don't mind! (x, y, and z)

Let me know if you need any help getting this into pull request form, I'm happy to help!
