### ISSUE TITLE
vectors as coordinate

### ISSUE THREAD

**Issue by Matt-the-Marxist** [processing/p5.js#3719]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [x] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Feature enhancement details:
 I think it would be useful to be able to pass a vector anywhere you need to pass a point. First it checks what arguments it has been given; if it's vectors of coordinates, then uses the x, y, and possibly z, components of the vector as it would the coordinates.

So if I were to write this:

```
let a = createVector(10, 5)

point(a)
```
it would be the same as this
```
point(10, 5)
```
So as to avoid this:
```
let a = createVector(10, 5)

point(a.x, a.y)
```
Which, in my opinion, is a little tedious.
Thank you for your time.

**Comment by Spongman** [comment]
I was just think in the same thing earlier today. Probably for the same reason...

It should be reasonably simple to add overloads for most of these. One question: how to pass width/height parameters (eg for `rect()`) ?

**Comment by limzykenneth** [comment]
I'm actually surprised this hasn't been done yet. Would be really nice to have!

> how to pass width/height parameters (eg for rect())
@Spongman Is it reasonable to let the width and height be defined by another vector as well? There's also different `rectMode()` to consider.

**Comment by nobobo1234** [comment]
I could try to look into this! I really want to contribute to an open source project, this seems pretty doable.

**Comment by nobobo1234** [comment]
Btw letting width and height be definable by a vector seems really counter intuitive to me :thinking:

**Comment by nobobo1234** [comment]
I've looked into this but this'd require a lot of changes in the p5.Renderer2D file. Since most arguments aren't handled 'dynamically' you'd have to rewrite a lot of code to use the `arguments` object, or if p5 starts using es6, the rest parameters. Now this isn't as much of a problem for me coding-wise but I just wanted a head-ups if this should be implemented...

**Comment by Spongman** [comment]
i would recommend leaving the vector argument handling out of the renderer code.

**Comment by nobobo1234** [comment]
Yeah I see, but looking at the renderer code every parameter for every function is hardcoded so you cannot really avoid it.

**Comment by Spongman** [comment]
> you cannot really avoid it

not sure how you arrive at this. it should be possible to extract the scalars from the vectors in the p5.prototype methods and then pass them to the renderer methods as usual.

it's probably best to only add a single overload to each vector-taking method: an over load that replaces _all_ appropriate scalars with vectors. i don't think it makes sense to have a whole power set of overloads for each scalar-pair / vector replacement.

**Comment by limzykenneth** [comment]
@nobobo1234 You can destructure objects without ES6, ES6 destructuring is really just syntactic sugar. So you can just assign each individual `x`, `y`, `z` component of a vector into their own variables before passing them to the renderer, or even make them an array if you want to keep the existing way the renderer method is called.

**Comment by nobobo1234** [comment]
@Spongman Sorry, but I haven't had much experience with the source of the library. But I can't seem to find the place where the individual renderer methods are called from? E.g. `point()`, `line()`. I've found the constructor of the methods (`p5.Renderer2D.js`) but not the place where they are called from, only where the renderer itself is initialized (`rendering.js`). I can't seem to find a call to these functions in the `p5.Element.js` file which seemed like the most logical place to me.

**Comment by limzykenneth** [comment]
@nobobo1234 At the bottom of the [reference page](https://p5js.org/reference/#/p5/point) for the individual functions is a link to where the function is defined in the [source code](https://github.com/processing/p5.js/blob/0.8.0/src/core/shape/2d_primitives.js#L356). These are the function you should be making the changes to, they will call the renderer's method themselves.

**Comment by nobobo1234** [comment]
Sorry for the long wait but I'm kinda busy with school right now so I think I won't be able to finish this is the for the next few months 😞. I hope someone else will pick this up!

**Comment by dhruvs009** [comment]
@Spongman @nobobo1234 Hey, since this issue still needs some working upon, could I pick it up?

**Comment by dhruvs009** [comment]
@Spongman @nobobo1234  @limzykenneth  Hey, I have been working on the issue, and I have been able to overload the point() method with something what the issue demands. I'll soon issue a PR for the same and it would be really great if someone could verify if it's upto the mark. (Keeping in mind it'd be my first meaningful work in open source). Thanks :)

**Comment by limzykenneth** [comment]
Hi @dhruvs009, you can go ahead and file a PR for this whenever you are ready, we can review the changes over there since this issue has pretty much already settled on a solution now.

**Comment by dhruvs009** [comment]
Hey @limzykenneth I've filed #4058 for the same. Please take a look?

**Comment by dhruvs009** [comment]
Hey, I was just wondering if we can open another issue (or reopen this one) to let other similar functions have the capability of having vectors as point coordinates? We could maybe have a list of such functions and work on them as well?
