### ISSUE TITLE
split is not defined

### ISSUE THREAD

**Issue by alexander-wick** [processing/p5.js#3730]
this my code but i'm wandering why the console says split is not defined

var txt;
function preload() {
  txt = loadStrings("sample.txt");
}

function setup() {
  noCanvas();
  console.log(txt);
}

var names = 'Pat,Xio,Alex';
var splitString = split(names, ',');
text(splitString[0], 5, 30);
text(splitString[1], 5, 50);
text(splitString[2], 5, 70);
//var splitStrings = split(txt, "!");
//console.log(splitStrings[1]);

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>testing</title>
  </head>
  <body>
    <h1>testing</h1>
    <pre id="pre"></pre>
  </body>
</html>
<script src="sketch.js"></script>
<script src="p5/p5/p5.js"></script>
<script src="p5/p5/addons/p5.dom.js"></script>

**Comment by piecesofuk** [comment]
Because split is a p5 function it can't be used before setup() is run. If you run your code in the p5 web editor you get the following warning message: 

> Did you just try to use p5.js's split() function? If so, you may want to move it into your sketch's setup() function.
> 
> For more details, see: https://github.com/processing/p5.js/wiki/p5.js-overview#why-cant-i-assign-variables-using-p5-functions-and-variables-before-setup

**Comment by stalgiag** [comment]
Thanks for the accurate response @piecesofuk! In the future @alexander-wick if you are unsure of whether something is a bug with the p5 library or your code it is best to [post on the forum first.](https://discourse.processing.org/c/p5js). 

Closing this now for organization purposes.

**Comment by phemyojo** [comment]
great work guys

**Comment by alexander-wick** [comment]
thanks for help :D
