### ISSUE TITLE
Mouse Brightness circle to rectangular shape

### ISSUE THREAD

**Issue by thewebdevelopment** [processing/p5.js#3734]
Is there any way we can make mouse brightness circle to rectangular?
I have seen the docs but unable to find the right method.

https://p5js.org/zh-Hans/examples/color-brightness.html

**Comment by stalgiag** [comment]
It looks like you already [asked this question in the forum](https://discourse.processing.org/t/change-shape-of-color-brightness/11030/2) and it was answered, which is great! But the github page is for bugs, issues, and feature requests. Please don't dual post on the forum and here as it makes it hard to keep the issues section of the github organized.

If you need help figuring out how to code something, the forum is the appropriate place to get help (which you did! yay!)
