### ISSUE TITLE
Delta time feature

### ISSUE THREAD

**Issue by limzykenneth** [processing/p5.js#3737]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [x] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### New feature details:
This has been brought up before in #2180 and although while it is true that we can get the delta time of the last frame with `1000/frameRate()` it requires a bit of extra explanation about why that would give the delta time. Also most game engines also provides a delta time variable in their animation loop so implementing it here would help with moving from one to the other.

It also isn't that hard to implement because p5.js already has the property as [`now - this._lastFrameTime`](https://github.com/processing/p5.js/blob/25ba3ec4e76788fc58c4de9b5166d9300dd516a2/src/core/main.js#L375) (which is how `frameRate()` is derived anyway) we can just expose that as a public variable (named `deltaTime` or `lastFrameTime` maybe) and we're done.

**Comment by stalgiag** [comment]
I am very in favor of this. As you said,`deltaTime` is fundamental for most game and animation engines, and it can be a bit unexpected to find it isn't explicitly available in p5.

**Comment by lmccart** [comment]
I agree this sounds like a very good idea

**Comment by limzykenneth** [comment]
I'll implement this, will file a PR in a couple days the latest.
