### ISSUE TITLE
First character of text() is glitchy/'swapped' across other text() calls with different font faces. 

### ISSUE THREAD

**Issue by DarkWyvren** [processing/p5.js#3745]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [x] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 
WEBGL ONLY:
First character of text() is 'swapped' across other text() calls. 
Fonts are fetched from a server and are .otf fonts.
Otherwise the first character flickers.

- p5.js version: OpenProcessing's p5 version & p5.js v0.8.0 
- Web browser and version: 74.0.3729.131 (Official Build) (64-bit) (cohort: Stable)
- Operating System: Windows
- Steps to reproduce this:

Console errors:
none.

```
function setup() {
	createCanvas(windowWidth, windowHeight,WEBGL);
	background(100);
	getFont("phantom"); //get them fonts from server
	getFont("frozito");
  getFont("unseen");
}

function draw() {
	var w = windowWidth;
        var h = windowHeight;
		translate(-w/2,-h/2);
		background(0);
		push();
		fill(255);
		textAlign(CENTER);
		applyFont("phantom");
		textSize(64);
		text("DC",w/2,h/2);
		applyFont("frozito");
		textSize(24);
		text("quest",w/2,h/2+30);
                pop();
		stroke(255);
		noFill();
		//console.log(checkLoading());
		let loadBarAni=1;
		arc(w/2,h/2-15,200,200,0,PI*2.0*loadBarAni);
		noStroke();
		let loadTextFade=1;
		fill(255*loadTextFade);
		textAlign(CENTER);
		applyFont("unseen");
		textSize(18);
		text("Welcome player",w/2,h/2+110);
	
}
httpGetMap = new Map();
getFont = async function (fontName){
        httpGetMap.set(fontName,loadFont('https://draw-circle-quest.herokuapp.com/font/'+fontName));    //get them fonts from server and put it in hashmap
    }
    

applyFont = function(key){
		if(httpGetMap.has(key)){
				textFont(httpGetMap.get(key));  
		}else{
				textFont("Helvetica");
		}

}
```

Output for me:
![image](https://user-images.githubusercontent.com/13158938/57760378-c5b28700-773e-11e9-9433-721a2a7bbc1d.png)

**Comment by DarkWyvren** [comment]
workaround hack:
this only triggers on the first text calls 
so you can call a useless text and draw it off screen to 'get rid' of the first call

`text("Awe",-999,-999);`

**Comment by Spongman** [comment]
I think this may have been fixed already. Can you try with this interim build? https://github.com/Spongman/p5.js/releases/download/untagged-cd68b53ab47e77c09904/p5.js

**Comment by DarkWyvren** [comment]
yep thank you c:
