### ISSUE TITLE
3D object having a texture renders abnormally

### ISSUE THREAD

**Issue by diem389** [processing/p5.js#3748]
#### Nature of issue?

- [X] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [X] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version:  after 0.5.15
- Web browser and version: Chrome latest 
- Operating System: Windows 10
- Steps to reproduce this:

I run a following example code with p5.js. 
```
let kitten;
let cam;
let theta = 0;

function preload() {
  kitten = loadImage('/kittens/cat.jpg');
}

function setup() {
  createCanvas(400, 300, WEBGL);
}


function draw() {

  rotateX(theta * 0.1);
  rotateY(theta * 0.1);
  rotateZ(theta * 0.1);

  noStroke();
  texture(kitten);
  box(128, 128, 128);

  theta += 0.05;
}
```
![image](https://user-images.githubusercontent.com/305927/57829603-7b86df80-77ea-11e9-917e-a54df18cf6ca.png)

Whole versions after 0.5.15 has the same problem. 
Previous version (before 0.5.14) works well. 
![image](https://user-images.githubusercontent.com/305927/57829624-88a3ce80-77ea-11e9-9d3e-f23a624721c7.png)

The texture image file I use:
![cat](https://user-images.githubusercontent.com/305927/57829717-d3bde180-77ea-11e9-9dfc-8f2a2237d9f6.jpg)

**Comment by Spongman** [comment]
Looks like you need to call `background()` at the start of your `draw` function.

**Comment by diem389** [comment]
I see. Thanks.
