### ISSUE TITLE
lights() not working in p5.js web editor

### ISSUE THREAD

**Issue by SaltyBuckets** [processing/p5.js#3750]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [x] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other : lights

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 
- Web browser and version:
chrome 74.0.3729.131 (Official Build) (32-bit) (cohort: Stable)

- Operating System:windows 7 
- Steps to reproduce this:

lights() not working
![ghkjgt](https://user-images.githubusercontent.com/49991711/57918732-fb797c00-78b4-11e9-9206-c299fda28657.JPG)
![gjg](https://user-images.githubusercontent.com/49991711/57918743-fddbd600-78b4-11e9-9ab4-652366019f84.JPG)

#### New feature details:
when adding a new file in the editor, it should be automatically included in index.html
also make a physics library

**Comment by SaltyBuckets** [comment]
i know light should have been below backgound

**Comment by sanketsingh24** [comment]
Probably this is because the p5 version on editor is not up to date. You should report the error [here](https://github.com/processing/p5.js-web-editor/issues), that repository is specific for the p5 web editor.

Also, it has been [an old problem](https://github.com/processing/p5.js-web-editor/issues/826#issuecomment-465752585)

**Comment by lmccart** [comment]
@saltybuckets in the meantime, you can update the version of p5.js by changing the number "0.7.3" to "0.8.0" in your html file
