### ISSUE TITLE
Enhance fill support p5.Image

### ISSUE THREAD

**Issue by informathemusic** [processing/p5.js#3754]
I need to do an user profile image and i need to crop round an image,so i need to fill a circle with an image.Would this be possible? 

#### Nature of issue?

- [ ] Found a bug
- [x ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [x ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x ] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.7.3
- Web browser and version: Avast Secure Browser | 73.0.1270.87 (Build officiel) (32 bits)
- Operating System: Windows 10 1803
- Steps to reproduce this:I need to crop round an image without any mask

#### Feature enhancement details:
fill(p5.Image);
Fills a form/a vertex with an image

**Comment by limzykenneth** [comment]
@informathemusic You can use [`mask()`](https://p5js.org/reference/#/p5.Image/mask) to achieve what you need. If you have further questions you can ask them on the [forum](https://discourse.processing.org/) first.
