### ISSUE TITLE
Unable to display images from URL

### ISSUE THREAD

**Issue by CullenSharp2** [processing/p5.js#3757]
Hey all, 
Been working with xml, I'm now able to get URL paths to images--Great! Unfortunately, the images never display. I can access image properties(.width & .height) but not display the actual image; whenever I try the console logs "Cannot read property '_imageMode' of undefined." Pasting my code below, hope you can help.

Thanks!

/*
NOTES:
fails to display image
errorMessage = "cannot read property '_imageMode' of undefined"
*/

let img;

function preload() {
  img = loadImage('https://static01.nyt.com/images/2018/12/12/world/00oz-china-1/00oz-china-1-moth.jpg',success,fail);
}

function setup() {
  createCanvas(windowWidth,windowHeight);
}

function draw() {

}

let success = function() {
  console.log("nice, success");
  console.log(img.width);
  image(img, 0,0);
};

let fail = function() {
console.log("oopsy, no image");
};

**Comment by Spongman** [comment]
I think this is because your success function is getting called before setup (and thus before the canvas is created). Try just putting your `image()` code at the end of your setup function.

**Comment by CullenSharp2** [comment]
@Spongman You're a blessing!
