### ISSUE TITLE
Draw transparent shapes

### ISSUE THREAD

**Issue by lucifer1004** [processing/p5.js#3759]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [x] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### New feature details:

My use case:

I put the canvas created by `p5` over an image so that I can draw on it. It worked fluently but when I wanted to implement a rubber, I found no way to make a certain region transparent, e.g., drawing a transparent rectangle/circle.

I ended up with using `p.drawingContext.clearRect()`. Is it possible that `p5` would expose this method, or provide a direct way to draw transparent shapes?

**Comment by Spongman** [comment]
you _might_ be able to use `blendMode()` to achieve what you want to do here.

**Comment by lucifer1004** [comment]
> you _might_ be able to use `blendMode()` to achieve what you want to do here.

I have tried but found no suitable blend mode.

**Comment by stalgiag** [comment]
This seems simple to add and useful.

**Comment by zerosimms** [comment]
This would be super useful, I've spent 2 days trying to get around this but to no avail :(

**Comment by stalgiag** [comment]
What do we think the interface should be for this? A few very different approaches are:

1. Only expose `drawingContext.clearRect` as `clearRect(x, y, w, h)`
2. some kind of state in the vein of `erase`/`noErase` that sets the blend mode to `destination-out`, which would allow any shape to be used for clearing. [Here is an example.](https://editor.p5js.org/stalgiag/sketches/eCsygQ7-5)
3. Add a constant for `blendMode()` that evaluates to 'destination-out' which can be used for erasing

Any thoughts @limzykenneth @lmccart @outofambit ?

**Comment by zerosimms** [comment]
> What do we think the interface should be for this? A few very different approaches are:
> 
> 1. Only expose `drawingContext.clearRect` as `clearRect(x, y, w, h)`
> 2. some kind of state in the vein of `erase`/`noErase` that sets the blend mode to `destination-out`, which would allow any shape to be used for clearing. [Here is an example.](https://editor.p5js.org/stalgiag/sketches/eCsygQ7-5)
> 3. Add a constant for `blendMode()` that evaluates to 'destination-out' which can be used for erasing
> 
> Any thoughts @limzykenneth @lmccart @outofambit ?

Personally, I really like option one, it's what I was searching for when I was looking for the answer

**Comment by limzykenneth** [comment]
Option 1 seems to be most simple but I really like option 2 and the possibilities it provides. Option 3 could also potentially be an option as well, I'm just not sure between option 2 and 3 which will cause the least confusion.

**Comment by outofambit** [comment]
I would vote either option 2 or 3 since presumably we'd also want to be able to draw clear shapes that aren't rects. I think I have a preference for option 3, since that feels more in line with the current API. (I'm not remembering/finding other methods that affect how something is drawn outside of color/stroke/fill.)

Another option might be to add an optional argument for `stroke()` and `fill()`, where you could pass a constant that denotes the transparency option? I guess that wouldn't cover the Image case though. 🤔

**Comment by stalgiag** [comment]
Hm I guess that my personal preference leans slightly towards option 2. I like being able to erase with many shapes and the use of `blendMode()` somehow feels more advanced than I'd like this feature to be. I can imagine very new users being interested in this feature and `blendMode()` usage feels a bit counter-intuitive for first learning. The idea with the `xxxx`/`noXxxx` format is that it resembles other things that people use when first learning ie `fill`/`noFill` and `stroke`/`noStroke`.

**Comment by lmccart** [comment]
I think option two sounds conceptually easier to understand, and really fun!

**Comment by lucifer1004** [comment]
I am also in favor of option 2.

**Comment by stalgiag** [comment]
Okay thanks for the input everyone! I'll pursue option 2 and we can see how it feels in a feature branch. If the end result isn't ideal we can always switch to one of the other approaches.
