### ISSUE TITLE
createCapture(VIDEO) does not work on iOS if imported from p5.dom.min

### ISSUE THREAD

**Issue by blackwolf08** [processing/p5.js#3763]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [x] Image
- [x] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [x] Mobile/Tablet (touch devices)
- [ ] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.8.0
- Web browser and version: safari latest 
- Operating System: iOS
- Steps to reproduce this:
Webcam gives a black screen on safari in minified version of p5.js or p5.dom.js.

#### Feature enhancement details:
On importing p5.js and p5.dom.js ( not the minified versions ) It worked! maybe something to do with the minification on minified versions?

**Comment by lmccart** [comment]
@blackwolf08 can you please post a snippet of code you are using that demonstrates the issue?

**Comment by lmccart** [comment]
please reopen if you can provide more info, thanks!
