### ISSUE TITLE
p5.SoundFile.saveBlob url not open

### ISSUE THREAD

**Issue by Wess21** [processing/p5.js#3765]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [ ] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 
- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

**Comment by Wess21** [comment]
p5.SoundFile.saveBlob url not open

**Comment by stalgiag** [comment]
Hi thanks for the issue! We need a little more information to understand what you are referring to.

Are you talking about a website link? I don't think [p5.SoundFile.saveBlob is a method currently.](https://p5js.org/reference/#/p5.SoundFile)

**Comment by lmccart** [comment]
please reopen if you can provide more info, thanks!
