### ISSUE TITLE
Unexpected fill with curveVertex, bezierVertex and quadraticVertex

### ISSUE THREAD

**Issue by anthonygalea** [processing/p5.js#3766]
<img width="990" alt="Screenshot 2019-05-24 at 09 39 59" src="https://user-images.githubusercontent.com/1301852/58312393-7a1d6e80-7e0b-11e9-8031-e3da898501f2.png">

#### Nature of issue?

- [X] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [X] Shape

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [X] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.8.0
- Web browser and version: Chrome 74.0.3729.169 (Official Build) (64-bit)
- Operating System: MacOSC
- Steps to reproduce this: https://editor.p5js.org/anthonygalea/sketches/OqM3tWGbB

Actual: Using vertex functions without calling either `fill` or `noFill` results in a weird fill. See screenshots below.
Expected: In p5 0.7.3 there was no fill.

Seen this behaviour in `curveVertex`, `bezierVertex` and `quadraticVertex`.

<img width="777" alt="Screenshot 2019-05-24 at 10 02 00" src="https://user-images.githubusercontent.com/1301852/58312391-7a1d6e80-7e0b-11e9-8e69-14c917f17a15.png">

**Comment by AdilRabbani** [comment]
A quick debugging in 0.8 and 0.7.3 reveals that `this.drawMode` here,
https://github.com/processing/p5.js/blob/6640d149348dea0a1b3df61f0cf8442222403a9f/src/webgl/p5.RendererGL.Immediate.js#L306-L327
is equal to `'fill'` in 0.7.3 while it is `undefined` in 0.8 which causes the 0.8 version to go into the else condition, generating a LINE_LOOP.
