### ISSUE TITLE
Screen record a version of a sketch

### ISSUE THREAD

**Issue by maddyfisher** [processing/p5.js#3771]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [x] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### New feature details: 
Providing a "camera feature" that allows the user to screen record their interaction with their sketch. This would allow users to document their work to illustrate to others about a problem that occurred with the program or even to have a video of their work. I have noticed that there is a save canvas feature, but no save video feature.

**Comment by limzykenneth** [comment]
I usually just use a software made specifically for this purpose, Quicktime on macOS, Xbox on Windows, Screen Recording on iOS and probably something for Android as well, are all built in by default. They also have the added ability to capture cursors and cursor actions (hightlighting clicks).

**Comment by lmccart** [comment]
I agree, I think the idea of this issue is great, but I'm doubtful that we could build anything better than existing tools. @maddyfisher if you want to try qucktime on mac [here are some instructions](https://support.apple.com/guide/quicktime-player/record-your-screen-qtp97b08e666/mac). let us know if you think this meets your needs.

**Comment by maddyfisher** [comment]
Yes, quicktime works great with cursor action! Thanks for the feedback @lmccart @limzykenneth
