### ISSUE TITLE
Add "Web Server for Chrome" to "Local server" wiki page

### ISSUE THREAD

**Issue by AltoRetrato** [processing/p5.js#3773]
Hello, p5.js World! 😄 

Millions of people around the world (mostly students) are **Chromebook** users, and they also want to use p5.js! (Well, who doesn't?)

In order to **load local files**, a local web server is required. Unfortunately, the **[Local server](https://github.com/processing/p5.js/wiki/Local-server) wiki page** doesn't provide any solution for Chromebook users (specially those that can't/won't enable developer mode).

But there is a **[Web Server for Chrome](https://chrome.google.com/webstore/detail/web-server-for-chrome/ofhbbkphhbklhfoeikjpcbhemlocgigb/)**! I tested this app on Windows 10 and on a Chromebook, and it worked fine on both. Since it is easier to install and configure than the other options (and, unlike them, it works on Chromebooks), I'd suggest it to be included in that wiki page, and if possible, for it to become the "1st option".

I'm sure that would help more people to start and keep using p5.js.

**Comment by outofambit** [comment]
Hi @AltoRetrato and thanks for filing this issue! I think it would be great to include this option in the wiki.

Would you like to edit the wiki page to add this section? or if you share the steps you used to set it up with p5.js, I'm happy to incorporate them too! Thanks again!

**Comment by AltoRetrato** [comment]
I'm OK with both options (having edit access or for you to add this info). If you want to review / change these steps, feel free to do so:

The simplest and fastest solution for anyone using a Chrome web browser is to install the [Web Server for Chrome](https://chrome.google.com/webstore/detail/web-server-for-chrome/ofhbbkphhbklhfoeikjpcbhemlocgigb/) extension. Visit its chrome web store page and install it.

By default, the Web Server won't run in the background, so keep it open for it to work. To launch it on [most devices](https://support.google.com/chrome_webstore/answer/3060053), type `chrome://apps` in the Chrome address bar and press [Enter] to see all your Chrome apps, then click the Web Server icon. On a [Chromebook](https://support.google.com/chromebook/answer/6206362), press the Search key (🔍) or click the Launcher icon (usually at the bottom left corner of the screen) to find and launch the Web Server.

After launching the Web Server a new window will open. There you can click [CHOOSE FOLDER] and select the folder with the HTML page for your sketch. Now you can just click on the Web Server URL (`http://127.0.0.1:8887` by default) to see and open your sketch. If you name your sketch HTML page `index.html` and enable `Automatically show index.html`, your sketch will load as soon as you open the URL!

**Comment by lmccart** [comment]
Thanks @AltoRetrato! I've added the info to the [Local Server](https://github.com/processing/p5.js/wiki/Local-server) page.
