### ISSUE TITLE
webgl: mobile glyph rendering issues

### ISSUE THREAD

**Issue by Spongman** [processing/p5.js#3776]
0.8.0
re: #3769 

@stalgiag reported webgl font rendering issues on android mobile devices:

> The text/chinese manual test is still rendering oddly on my mobile device (Android 8, Galaxy s7). I don't know if that has to be addressed in this PR as it is "more broken" in master currently. Just thought it worth noting. Here is a screenshot:

![](https://user-images.githubusercontent.com/10382506/58438015-7e52c180-8081-11e9-9317-27f717e04eab.png)

it looks like it might be due to integer precision issues on that device:
> If I change the fragment shader to use high precision floats and also do the integer substitution with floats (ie #if 1 in line 4) then it displays correctly.

**Comment by Spongman** [comment]
@stalgiag 
can you try this in `font.frag`?

```
precision mediump float;

#if 0
  ...
#else
  // use native integer math
  precision highp int;
  ...
```

**Comment by stalgiag** [comment]
@Spongman that also works!

**Comment by Spongman** [comment]
ok, so until we have some framework for parameterizing shader compilation, i'm just going to force `highp int` on all devices. i wish there was some way to say 'int16' or determinine precision at compile time (eg `sizeof()`), oh well...
