### ISSUE TITLE
httpdo post is still notworking

### ISSUE THREAD

**Issue by ursulawolz** [processing/p5.js#3777]
#### Nature of issue?

- [X ] Found a bug

#### Most appropriate sub-area of p5.js?
- [X ] Data

- [ X] Other (specify if possible)  http server communication

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [X ] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version:  most recent download 
- Web browser and version: CHrome Version 74.0.3729.169 (Official Build) (64-bit)
- Operating System: MacOSX 10.11.6
- Steps to reproduce this:

[FullStackTraining.zip](https://github.com/processing/p5.js/files/3239267/FullStackTraining.zip)

**Comment by Spongman** [comment]
if you open your browser's debugger, you'll see that it's complaining about malformed JSON coming back from the server. `httpDo`, when called like this is expecting json. try changing your post method to something like this:

```javascript
app.post('/api/data', (request, response) => {
  response.send({ foo: "bar" });
});
```

**Comment by ursulawolz** [comment]
I don't think that's the problem.  I sent back a json object, but the json object going out is empty.
I do not know how to set up the parameters for httpDO or httpPost because I cannot see what your server is expecting.

sending through the form at the top of the client works fine. The server sees:
[Object: null prototype] { data: 'hello' }

Sending through the httpDo, or an httpPost sends an empty object.:
{}
How do I form the 'data' parameter of htttpDo or HttpPost? It seems to be not recognizing the input as a JSON object?

**Comment by ursulawolz** [comment]
I am convinced that httpDo (and httpPost) are not sending out the request. Please see the zip file PostFromP5. When the 'z' key is pressed as per the P5 sketch, the request payload is loaded, but on the server side the 'body' of the request is coming back empty.  I've gone the extra mile on this -- jsonlint, formed the data request in a variety of ways.  The payload is not making it across the web. In the server console the body object is {}. Search for  body: {}.  

Then see the project PostFromForm.  This works, sending back the payload, except the payload is labeled as the Form Data: data: LauraFeire, rather than as a json 'request payload'. On the server side the 'body' is [Object: null prototype] { data: 'LaruaFeire' }.

My next step is a fetch or ajax workaround.... to convince myself I understand what should be happening on the server side since you don't have a doc for that and I can't find one in Dan Shiffman's resources (It could be there.... haven't found it. )

I am probably doing something wrong in either setting up the parameters for the p5 httpPost or in how I'm extracting the payload on the other side.  If so, please show me a full loop?  A sketch and server that successfully ack the data being moved.  I'll rebuild your documentation on this and other less frustrating typos in the P5. docs :-)
-Ursula
[PostFromP5.zip](https://github.com/processing/p5.js/files/3243056/PostFromP5.zip)
[PostFromForm.zip](https://github.com/processing/p5.js/files/3243057/PostFromForm.zip)

**Comment by limzykenneth** [comment]
I had a look at the code you posted. The problem is not with the sketch code nor p5 itself but rather with the server code.

For an Express server anything that isn't parsed by `bodyParser` prior to passing to route handler will result in an empty `req.body` object. In your server code you only have `app.use(bodyParser.urlencoded( ... ));` which will only parse form data, while your p5 sketch is sending JSON data. You will need to add `app.use(bodyParser.json());` to your server code before the route handling code to be able to read JSON data sent by `httpDo`.

Here's what the modified code of the server look like:
```javascript
// app.js
const express = require('express');
const bodyParser = require('body-parser');
const app = express();

app.use(bodyParser.urlencoded({
    extended: false
}));
app.use(bodyParser.json());

app.use(express.static('p5'));

app.post('/postTest', (request, response) => {
    console.log(request.body);
    response.send({
        foo: request.body
    });
});

app.listen(3000, () => console.info('Application running on port 3000'));
```

If you have further questions you can ask on the [forum](https://discourse.processing.org/). Thanks.
