### ISSUE TITLE
Video.get() isn't working

### ISSUE THREAD

**Issue by MaanasNegi** [processing/p5.js#3779]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [x] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 
- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

**Comment by MaanasNegi** [comment]
let video;
let button;
var snapshots = [];

function setup() {
  createCanvas(800, 240);
  background(100);
  video = createCapture(VIDEO);
  video.size(150,240);
  button = createButton('Snap');
  button.mousePressed(takesnap);
}

function takesnap() {
  // image(video, 0, 0);
  snapshots.push(video.get());
  
}

function draw() {
var w = 80;
var h = 60;
var x = 0;
var y = 0;
for (var i =0;i<snapshots.length;i++){
  tint(255,50)
  image(snapshots[i],x,y,w,h);
  x=x+w;
  if (x>=width){
  x=0;
  y+=h;
  }
}
}

**Comment by MaanasNegi** [comment]
I used the same code from **11.2: Video Photobooth / Muybridge Style Animation - p5.js Tutorial**
Link:[https://www.youtube.com/watch?v=oLiaUEKsRws&list=PLRqwX-V7Uu6aKKsDHZdDvN6oCJ2hRY_Ig&index=2].
And I think this is a problem with a later version as I saw some comments saying the same thing.

**Comment by limzykenneth** [comment]
@MaanasNegi I am not able to identify any problem with the code you provided, it works as how I would expect it to. Can you fill out the issue template so that we have more info about what's wrong? Specifically, are you using the latest version of p5.js and what browser/OS versions you are using. 

Also can you describe what is the expected behaviour and what is the current behaviour you are seeing? Otherwise we can't really tell for sure what's wrong. Thanks.

**Comment by Spongman** [comment]
i think i see what the issue is. while `video.get()` _is_ returning an image, it's not updating over time, so it always returns the first captured image.

**Comment by MaanasNegi** [comment]
The src in my html file are : src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.8.0/p5.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.8.0/addons/p5.dom.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.8.0/addons/p5.sound.min.js"></script>
and there is no error but I want it to take the image of the latest snapshot. I think using a for loop like for (var i = 0; i < snapshot.length; i ++){
snapshots[i].push(video.get)
}

**Comment by MaanasNegi** [comment]
The expected behaviour is to see the latest image come up in the canvas and the current behaviour is only getting the first image.

**Comment by MaanasNegi** [comment]
I think it is what @Spongman  is saying. The video.get is only taking the first image and isn't updating.

**Comment by MaanasNegi** [comment]
Also thanks for commenting since this is my first github issue and I never expected for my problem to get comments so quickly.
