### ISSUE TITLE
textureMode manual test and reference example broken in master

### ISSUE THREAD

**Issue by stalgiag** [processing/p5.js#3784]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [x] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: master branch
- Web browser and version: 
- Operating System: 
- Steps to reproduce this:
Build master and look at reference example at
test/manual-test-examples/webgl/material/textureMode/ or run `npm run docs:dev` and look at the reference example for textureMode

![Screenshot (643)](https://user-images.githubusercontent.com/10382506/58765136-438ad680-8524-11e9-83a7-b7e506a36981.png)

No messages in console. Oddly the very similar test at manual-test-examples/webgl/immediateMode/texture/ works as expected.

**Comment by Spongman** [comment]
Did I break this with the BufferDef stuff, I wonder?

**Comment by Spongman** [comment]
i did a git bisect and it appears to be this commit: 8827a914d663f29fd12c2de949cb897db0ce07c2

**Comment by stalgiag** [comment]
Thanks @Spongman I'll figure out what the problem is tomorrow

**Comment by stalgiag** [comment]
Okay I should've caught this but essentially [this line is breaking it](https://github.com/processing/p5.js/blob/master/src/webgl/p5.RendererGL.Immediate.js#L311), but when the line is removed the custom shapes manual test stops working. 

We need to allow someone to build a quad without passing any arguments in `beginShape()`. We also need to know when to tesselate. Maybe the idea of a mode should be revisited @AdilRabbani what do you think?

Meanwhile I am going to open an issue to untangle Immediate Mode.

**Comment by stalgiag** [comment]
Okay barring updates from @AdilRabbani, next week I will revert some of the changes from #3680.

I will try to figure out a design that retains some of the hollow fill tesselation features that were introduced by that PR, but the priority will be fixing 4-vertex quad immediate mode geometry without an argument in `beginShape()` (ie fixing this bug)
