### ISSUE TITLE
Remove "console.log" when creating WebGL drawingContext

### ISSUE THREAD

**Issue by FreddieRa** [processing/p5.js#3787]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.8.0
- Web browser and version: Firefox
- Operating System: Windows 10
- Steps to reproduce this:

When creating a new sketch with WebGL I get "p5.RendererGL: enabled webgl context" in the console. This is frustrating since I assume there is an error, or something I am actually trying to log. 

This appears at https://github.com/processing/p5.js/blob/3ec269b89dab5892104b2c0acadb0e82f988b2c3/src/webgl/p5.RendererGL.js#L175

I understand returning an error if it fails to initialize, but it doesn't need to return a message everytime it is successful. Enabling `p5.disableFriendlyErrors = true;` does also not remove this.

**Comment by stalgiag** [comment]
Haha thanks for being the one that said it @FreddieRa. I think this is an example of something that has just been around for so long that people have accepted it as necessary for whatever reason. Any interest in making this change?

**Comment by FreddieRa** [comment]
Aha, glad I'm not the only one. Happy to make the change, assuming that change is just removing the line, or do you want it to be affected by the "disableFriendlyErrors?"

**Comment by FreddieRa** [comment]
PR here: https://github.com/processing/p5.js/pull/3792

**Comment by lmccart** [comment]
thanks! closed with https://github.com/processing/p5.js/pull/3792
