### ISSUE TITLE
Update Instance Mode wiki page to ES6

### ISSUE THREAD

**Issue by figraham** [processing/p5.js#3788]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request
- [X] Documentation request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [X] Other, Wiki - Instance Mode

#### Which platform were you using when you encountered this?

Not Applicable

#### Details about the bug: 

Not Applicable 

#### Feature enhancement details:

I noticed that the [instance mode wiki page](https://github.com/processing/p5.js/wiki/Global-and-instance-mode) is still using var. Would be great if we could update it to ES6 with const, let, and arrow functions.

I'd be happy to work on it but I don't have permission.

**Comment by lmccart** [comment]
that would be great! I'm adding you as a repo contributor now so you should have access.

**Comment by figraham** [comment]
Done! Feel free to [check it out](https://github.com/processing/p5.js/wiki/Global-and-instance-mode) and make sure everything looks good. I updated the examples, added a note about es6, and corrected a couple small things that my markdown lint found.

**Comment by figraham** [comment]
@lmccart If I don't hear back in the next day or two, I'll assume everything is good and close this issue.

**Comment by lmccart** [comment]
looks great, thank you @figraham!
