### ISSUE TITLE
"focused" in iOS Safari

### ISSUE THREAD

**Issue by rich-gg** [processing/p5.js#3789]
Might be a follow up on [#1706](https://github.com/processing/p5.js/issues/1706)

[focused](https://p5js.org/reference/#/p5/focused) parameter doesn't seem to work ok on Safari for iOS

[My website](https://rich.gg) works fine on FireFox / Chrome / Edge on Mac / Windows / Linux / Android / iOS but on Safari/iOS it doesn't get that "focused" is true

Haven't tryed on Safari for Mac

**Comment by lmccart** [comment]
@rich-gg I'm not able to reproduce this issue in safari mac or safari IOS, I'm just testing with the focused parameter page example. Is it just a problem you're seeing with your website, or do you also see the focused parameter page example not working either?
