### ISSUE TITLE
p5.RendererGL.Immediate needs to be refactored

### ISSUE THREAD

**Issue by stalgiag** [processing/p5.js#3793]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

[p5.RendererGL.Immediate](https://github.com/processing/p5.js/blob/master/src/webgl/p5.RendererGL.Immediate.js) needs to be refactored. It is very difficult to untangle what is happening with the structure of the code, especially the density of conditionals. This seems to lead to a number of bugs. I know that you were working on a unification @Spongman and I am not sure where you are with that, but if that is a ways off then I would be happy to take a readability pass over this file.

**Comment by FreddieRa** [comment]
I'm happy to try take a look at it?

**Comment by stalgiag** [comment]
@FreddieRa  sure if you would like to! This might be contingent on a few other things, namely #3620 and #3784

**Comment by FreddieRa** [comment]
@stalgiag Ahh, not sure I'm familiar enough with the WebGL library to do more than some basic refactoring I'm afraid. I'll stay subscribed to the issues to see if I can learn from the fixes though.

**Comment by Spongman** [comment]
@stalgiag yeah, having the immediate renderer re-use the retained geometry/buffers stuff was the next thing i was going to tackle. like you said, i think #3784 should probably be fixed first, though.

**Comment by stalgiag** [comment]
@Spongman Great thanks for the info. That should make this issue irrelevant since a refactor is a given with those changes. I am going to close this issue then.

As for #3784, the changes necessary to fix that should be minimal. Worst case scenario, a shapeMode argument can be added for tessellation or the changes for custom shapes can be reset altogether. But yes, I agree that this should be resolved soon, I'll make sure that a fix comes through asap.
