### ISSUE TITLE
TTF font works in WEBGL on PC, doesn't work in Chromebook

### ISSUE THREAD

**Issue by AltoRetrato** [processing/p5.js#3801]
#### Nature of issue?

- [x] Found a bug

#### Most appropriate sub-area of p5.js?

- [x] Typography

#### Which platform were you using when you encountered this?

- [x] Others: Chromebook

#### Details about the bug: 

- p5.js version: p5.js v0.8.0 April 08, 2019
- Web browser and version: Chrome 74.0.3729.159 (Official Build) (64-bit)
- Operating System: Chrome OS 74.0.3729.159
- Steps to reproduce this:

```
let font;
function preload() {
    font = loadFont("Roboto/Roboto-Medium.ttf"); 
    // https://fonts.google.com/specimen/Roboto
}
function setup() {
    createCanvas(100, 100, WEBGL);
    fill(255);
    textFont(font);
    textSize(width / 3);
    textAlign(CENTER, CENTER);
    frameRate(1);
}
function draw() {
    background(0);
    text("12345", 10, 10);
}
```

The sketch above works fine on my Windows 10 machine (browser 74.0.3729.169 (Official Build) (64-bit) (cohort: Stable), same p5.js version and TTF files), using either WEBGL or P2D renderers. But on my Chromebook, it only works on P2D. When using WEBGL the following error appears in the Javascript console:

> WebGL: INVALID_OPERATION: drawElements: no buffer is bound to enabled attribute

The error appears once for each character printed.

Using the non-minified version of p5.js, the error happens on line 83487 (function p5.RendererGL.prototype._renderText):

```
gl.drawElements(gl.TRIANGLES, 6, this.GL.UNSIGNED_SHORT, 0);
```

**Comment by Spongman** [comment]
i think this might be fixed in master. can you try this sketch which uses the most recent buid?

https://codepen.io/Spongman/full/yWdoVb

**Comment by AltoRetrato** [comment]
It works! 😀 
Thank you!
