### ISSUE TITLE
Pointer Lock API

### ISSUE THREAD

**Issue by jonnytest1** [processing/p5.js#3803]
#### Nature of issue?

- [x] New feature request

#### Most appropriate sub-area of p5.js?

- [ x] Core/Environment/Rendering
- [x ] Utilities

#### Which platform were you using when you encountered this?

- [ x] Desktop/Laptop

#### New feature details:
I found this API which removes the cursor from the website and thought this would be a fitting 
addon to p5
demo: https://mdn.github.io/dom-examples/pointer-lock/
demo src: https://github.com/mdn/dom-examples/tree/master/pointer-lock
api doc:     https://developer.mozilla.org/en-US/docs/Web/API/Pointer_Lock_API

**Comment by jonnytest1** [comment]
so I created a fork for this functionality but I cant commit it since I dont know how to get eslint to recognize new variables oO ? https://github.com/jonnytest1/p5.js/blob/master/src/events/mouse.js (couldnt double check the docs yet since the data.json file dissapears all the time)

**Comment by jonnytest1** [comment]
ok fixed the docs but the linter still complains about deltaX and deltaY to be undefined oO

**Comment by lmccart** [comment]
closed with #3804 thanks @jonnytest1
