### ISSUE TITLE
saveCanvas() should have a target

### ISSUE THREAD

**Issue by tsunamira** [processing/p5.js#3808]
The saveCanvas() should have these arguments:
saveCanvas(file name, file extension, x of picture, y of picture, width of picture, height of picture);

**Comment by limzykenneth** [comment]
@tsunamira You can use [`get()`](https://p5js.org/reference/#/p5/get) to get the subset of the canvas you want then [`save()`](https://p5js.org/reference/#/p5.Image/save) to save that subset of the canvas.
