### ISSUE TITLE
Webgl: log warning if user tries to render text before setting a font

### ISSUE THREAD

**Issue by outofambit** [processing/p5.js#3811]
how about we add this at the top of `p5.RendererGL.prototype._renderText()` ?

````javascript
  if (!this._textFont || typeof this._textFont === 'string') {
    console.log('WEBGL: you must load and set a font before drawing text. See `loadFont` and `textFont` for more details.');
    return;
  }
````

_Originally posted by @Spongman in https://github.com/processing/p5.js/issues/3179#issuecomment-501389847_

**Comment by dhowe** [comment]
don't we include a default font for just this purpose?
