### ISSUE TITLE
Including other p5-xyz.js libraries in instance mode in node?

### ISSUE THREAD

**Issue by thely** [processing/p5.js#3813]
Most existing libraries in the Contributed category on the p5js website are intended to be included through ye olde `<script src="p5.xyz.js"></script>` method, and they add themselves to the p5 global like this:

```js
p5.prototype.XYZ = function() {
    // ...
}
```

But this doesn't seem to work super well when working in node, and specifically in instance mode. As an example, I'm trying to extend [p5.canvascam.js](https://github.com/bitcraftlab/p5.canvascam/blob/master/p5.canvascam.js) to work as an import. canvascam extends the p5 global as above, but also calls on some of the p5 global methods (translate, scale). To try and make this exportable, I figured I needed to import p5 and prepend it to all the global methods, like I'm already doing in my sketch. But if I attempt to use imports and instance-mode this library like this:

```js
// p5.canvascam.js
import p5 from 'p5';

p5.prototype.CanvasCam = function(zoom, tx, ty) {
  // .. some code ..
  p5.prototype.resetMatrix = function() {
    this._renderer.resetMatrix();
    p5.translate(p5.width/2, p5.height/2); // line 58
    p5.scale(zoom);
    p5.translate(-tx, -ty);
    return this;
  };
  // .. more code ..
}

export default p5.prototype.CanvasCam; // is this necessary?

// main.js of project
cam = new p5.CanvasCam();
```

Then the error I get is `TypeError: _p.default.translate is not a function` on line 58 of canvascam (marked). My guess is that I need to do something else to include the p5 global in this file. Or pass in the p5 global externally? I've looked at p5-dom and p5-sound to see if I can figure out what they do to easily include themselves in the global without issue, but I haven't figured it out. Any ideas?

**Comment by Spongman** [comment]
inside of a `p5.prototype` method, you can just use `this` to refer to the `p5` instance.

````javascript
p5.prototype.CanvasCam = function(zoom, tx, ty) {
  // .. some code ..
  p5.prototype.resetMatrix = function() {
    this._renderer.resetMatrix();
    this.translate(this.width/2, this.height/2);
    this.scale(zoom);
    this.translate(-tx, -ty);
    return this;
  };
  // .. more code ..
}
````

the fact that canvascam's code assumes that the p5 methods are injected into the global scope is probably a bug in canvascam itself.

**Comment by thely** [comment]
This helped a lot! I was able to adapt the library to Node with minimal hackishness. :)
