### ISSUE TITLE
.ttf fonts not valid in webGL mode

### ISSUE THREAD

**Issue by CubeOfCheese** [processing/p5.js#3818]
#### Nature of issue?

- [ ] Found a bug
- [x] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [x] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: v0.8.0 April 08, 2019
- Web browser and version: 74.0.3729.169 
- Operating System: MacOSX Mojave
- Steps to reproduce this:

p.preload = function() {
    font = p.loadFont("https://fonts.googleapis.com/css?family=Roboto&display=swap" );
  }

Error Message:
> p5.js says: It looks like there was a problem loading your font. Try checking if the file path [https://fonts.googleapis.com/css?family=Roboto&display=swap] is correct, hosting the font online, or running a local server.[https://github.com/processing/p5.js/wiki/Local-server]
index.js:1375 Error: Unsupported OpenType signature /* c
    at parseBuffer (p5.js:42241)
    at p5.js:42439
    at XMLHttpRequest.request.onload (p5.js:42079) "https://fonts.googleapis.com/css?family=Roboto&display=swap"

#### Feature enhancement details:

In WEBGL mode, p5 is not supporting .ttf text files when stored locally or when accessed via url (as is the case in the above example). Meanwhile, the reference page for text() says 
"WEBGL: Only opentype/truetype fonts are supported."
which would imply .ttf fonts shoud be usable.

**Comment by Spongman** [comment]
The url you provided is not a font file, it’s a css file.

**Comment by CubeOfCheese** [comment]
You are correct, my mistake, however after downloading the ttf file for Roboto from Google fonts and linking to it, I received this error:
![Screen Shot 2019-06-13 at 3 42 35 PM](https://user-images.githubusercontent.com/16740469/59472068-12e35080-8df2-11e9-824e-fe5c9774330e.png)
From the file Sketch.js:
![Screen Shot 2019-06-13 at 3 44 54 PM](https://user-images.githubusercontent.com/16740469/59472151-6190ea80-8df2-11e9-95ea-a89dfdf562a4.png)
![Screen Shot 2019-06-13 at 3 45 40 PM](https://user-images.githubusercontent.com/16740469/59472157-681f6200-8df2-11e9-9464-053b80f94f5c.png)

**Comment by Spongman** [comment]
try looking in the network tab in the chrome debugger. did the request for that url succeed?

**Comment by CubeOfCheese** [comment]
The response succeeds, but it is returning React's index.html file in the public folder.

**Comment by lmccart** [comment]
Here is an example loading a ttf font in webgl mode. It appears to work correctly..

It sounds like there may be some error with your file setup. I'd suggest posting on the [forum](https://discourse.processing.org) to get some more help with this.
