### ISSUE TITLE
Suggestion for origin

### ISSUE THREAD

**Issue by NadaThiru** [processing/p5.js#3821]
Hi,
Could this be counted as suggestion?
For drawings - Is there any way to set the origin at the left bottom corner and have the x axis pointing to the right and y axis pointing upwards via a function (or routine). So that we can call this function right at the start and work using the standard coordinate system?
Thank you

#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [x] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 
- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

**Comment by lmccart** [comment]
@NadaThiru you could shift the origin to the bottom left in webgl mode with a single command by doing something like this:

```js
function setup() {
  createCanvas(100, 100, WEBGL);
}

function draw() {
  translate(-width/2, height/2, 0); // moves origin from center to bottom left
}
```

and adding a scale command will invert the direction of the y-axis:
```js
function setup() {
  createCanvas(100, 100, WEBGL);
}
function draw() {
  translate(-width/2, height/2, 0); // moves origin from center to bottom left
  scale(1, -1, 1); // inverts the y axis direction
}
```

**Comment by NadaThiru** [comment]
Thank you lmccart for the suggestion. Can it be even made simpler. Just calling one function originshift (or something) with one argument bottomleft. I started my programming with Fortran many years ago. Now after my many years of retirement I started on this project. https://discourse.processing.org/t/time-line-without-flash/12037. Thanks again

**Comment by lmccart** [comment]
I think that two lines is not significantly more complex than one line, and also removes the need to add an additional concept or origin shift. Since I'm not hearing others chiming in on this, I will close this issue for now.
