### ISSUE TITLE
p5.dom.js in download/complete library is weird version

### ISSUE THREAD

**Issue by vincentsijben** [processing/p5.js#3822]
**Actual Behaviour**
When downloading the complete library from https://p5js.org/download/, the versioning of p5.dom.js and p5.dom.min.js is not accurate.

p5.dom.js states "p5.dom.js v0.4.0 August 9, 2018"
p5.dom.min.js states "p5.js v0.8.0 April 08, 2019" 

The single file download over at https://p5js.org/reference/#/libraries/p5.dom even states "p5.dom.js v0.3.4 Jan 19, 2017"

https://github.com/processing/p5.js/blob/master/lib/addons/p5.dom.js states "p5.dom.js v0.4.0 August 9, 2018". Shouldn't there be a minified version in [here](https://github.com/processing/p5.js/tree/master/lib/addons) for p5.dom.js as well? 
Because there is one for sound...

 **Expected Behaviour**
Versioning should be consistent with it's non-minified version.

 **Would you like to work on the issue?**
I'm happy to send PR, but I don't know which adjustments are preferred.

**Comment by lmccart** [comment]
this one should be resolved once https://github.com/processing/p5.js/issues/645 happens

**Comment by outofambit** [comment]
fixed by #3922 🎉
