### ISSUE TITLE
translate function not working as expected.

### ISSUE THREAD

**Issue by Vrx8** [processing/p5.js#3833]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: "https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.8.0/p5.js"
- Web browser and version: 67.0.4
- Operating System: Windows 10 
- Steps to reproduce this:

```
function setup() {
  createCanvas(640, 360);
  x = 0;
}

function update(){
	x++
}

function draw() {
	update();
	translate(x, 0);
	rect(0,0,50,50);
}
```
https://snag.gy/OmFZoI.jpg

not working as expected, rectangle leaving trails behind, if the speed is increased multiple rectangle is created on the last location of the rectangle.

if the line
```
x++ 
```
is changed to
```
x += 5
```
will result in, https://snag.gy/L8NbF5.jpg

**Comment by limzykenneth** [comment]
You will need to redraw the background at the beginning of each draw loop otherwise all drawings from the last frame will remain on the canvas.
