### ISSUE TITLE
Consecutive MAC keys cmd-xx not triggered

### ISSUE THREAD

**Issue by Crapulax** [processing/p5.js#3837]
#### Nature of issue?
On Chrome Mac El Captain, keyPressed event is not sent for consecutive cmd-xx key pressed.
cmd-v for instance is sent in keyPressed (cmd followed by keycode 86 (for 'v'). But the next cmd-v is not triggered.
Looking to p5.js source code, it appears that p5.prototype._onkeyup is not called for the 'v' key if you keep cmd key pressed. This prevents internal structure `this._downKeys[e.which]` reset and make events on that key ('v') ignored here:
`p5.prototype._onkeydown = function (e) {
                if (this._downKeys[e.which]) {
                    // prevent multiple firings
                    return;
                }`
By pressing 'v' key alone, you can again use cmd-v because keyup get called.

**Workaround** implemented, when first cmd-v is received, delete v entry from this._downKeys i.e:
`delete sketch._downKeys[67]`

Same code on Windows Chrome works just fine (using ctrl instead of cmd obviously)

- [x ] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ x] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [ ] Desktop/Laptop
- [ x] Others (specify if possible) Mac Chrome

#### Details about the bug: 

- p5.js version: 0.8.0
- Web browser and version: 74.0.3729.169
- Operating System: Mac El Captain 
- Steps to reproduce this:

```js
function keyPressed(sketch){
            console.log('sketch.keyCode:'+sketch.keyCode);
            switch (sketch.keyCode){
            
               case 67:// for 'c'
                    if (sketch.keyIsDown(sketch.CONTROL)|| sketch.keyIsDown(91)){// if ctrl is pushed
                        
                        delete sketch._downKeys[67];// correct issue on safari chrome with keyup not sent when using cmd
                        return false;
                    }
                    break;
```

**Comment by lmccart** [comment]
Reading around online, it looks like keyup events are not detected when a modifier key (like command) is held down, this is part of the browser architecture for many browsers. So I don't think there's anything we can do to solve this from the p5.js end unfortunately.
