### ISSUE TITLE
WEBGL in Safari: transforms affect canvas context

### ISSUE THREAD

**Issue by setphen** [processing/p5.js#3850]
In Safari with WEBGL rendering, the rendering context itself appears to be affected by transformations.

#### Nature of issue?

- [X] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [X] Mobile/Tablet (touch devices)
- [X] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.8.0
- Web browser and version: Safari 12.0.2
- Operating System: macOS Mojave 10.14.2
- Steps to reproduce this:

1. Open the p5js editor in Safari: https://editor.p5js.org/

2. paste the following code and press run

3. Notice how the screen seems to flicker? I don't know why the transformation seems to affect the sketch like that.

```
function setup() {
  createCanvas(400, 400, WEBGL);
}

function draw() {
  rotateZ(PI * 2 * 0.618034 * frameCount);
  translate(2 * frameCount, 0);
  box(10);
}
```

**Comment by stalgiag** [comment]
Hi @setphen thanks for filing the issue. I don't have a Mac environment so I am unable to test this consistently, but I did briefly try this on a friend's computer which reproduced the bug with the above sketch.

Are you sure that the `translate()` line is what causes the problem? Is the above sketch the simplest sketch that produces the problem in your experience?

**Comment by setphen** [comment]
@stalgiag I think this has something to do with the preservation of the drawing buffer. I am trying to draw to the cavas without clearing it. This leads to different behaviors in different browsers:

<details>
<summary> Flashing image warning, click to view screenshots </summary>

Safari:

![Kapture 2019-07-22 at 14 54 59](https://user-images.githubusercontent.com/3891632/61657486-070c6900-ac91-11e9-8a62-79b9b60eb294.gif)


Firefox:


![Kapture 2019-07-22 at 14 57 23](https://user-images.githubusercontent.com/3891632/61657490-0bd11d00-ac91-11e9-91e9-eb2030aa6611.gif)


</details>

this is the code for the sketch:

```js
function setup() {
  createCanvas(400, 400, WEBGL);
}

function draw() {
  translate(2 * frameCount, 0);
  box(10);
}
```

What I expect to see is a consistent background color, and consecutive boxes being drawn moving to the right. It seems that neither browser behaves as I would expect. Am I missing something?

**Comment by stalgiag** [comment]
Hi @setphen I can't test in Safari but I am getting the expected output from Firefox. No animated GIF but several frames in the above code looks like this:

![Screenshot (103)](https://user-images.githubusercontent.com/10382506/62587128-4af89400-b875-11e9-9f81-5b2fb30c5ccd.png)

**Comment by stalgiag** [comment]
Okay finally got a mac and came back around to this. This one is odd. Safari doesn't seem to like when the color buffer is preserved without antialiasing on.  If you put `setAttributes('antialias', true);` or `smooth()` at the top of the example sketch it works fine. But even a sketch as simple as:
```js
function setup() {
  createCanvas(400, 400, WEBGL);
  background(0);
}
function draw() {
}
```
will strobe dangerously in Safari. The color buffer must be cleared every frame or antialiasing must be enabled in the rendering context. This behavior isn't present on any other browser. Still though we should default 'antialias' to true when Safari is detected just in case because this is a pretty terrible strobe effect.
