### ISSUE TITLE
createImg() doesn't return what expected

### ISSUE THREAD

**Issue by FiftyTwoWays** [processing/p5.js#3854]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [x] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: p5.js v0.8.0 April 08, 2019
- Web browser and version: 74.0.3729.169
- Operating System: Windows 10
- Steps to reproduce this:

index.html :
```
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <title>p5.js example</title>
    <script src="p5.min.js"></script>
    <script src="p5.dom.min.js"></script>
    <script type="text/javascript" src="sketch.js"></script>
</head>
<body>
</body>
</html>
```
sketch.js :
```
let img;
let input;

function setup() {
    input = createFileInput(handleFile);
}

function handleFile(file) {
    if (file.type === 'image') {
        img = createImg(file.data);
        console.log(img);
        console.log(img.width);
    }
}
```

Hello !
I don't really know why it's happening but when I open an image with the input, console.log(img) show me this :
n.Element {..., ..., ..., ..., width: 0, ...}
But when I click on it, width got the right width (the image one).
My second console.log show me 0.

Funny fact, when I reload my page and I choose the same image, width is not longer at 0, but if I choose an other image, width stay at 0.

Someone got an idea why ?

**Comment by Mayank-Mishra0110011** [comment]
It's not exactly a bug.
If you go through p5.dom.js file the method createImg returns an object whose properties width and height are set when image elt onload callback is completed. So it takes a few seconds to load the actual image, hence the delay in setting the properties of the object.

**Comment by stalgiag** [comment]
Hi @FiftyTwoWays thanks for the issue! As @Mayank-Mishra0110011 pointed out, the width and height will not be correct until loading is complete. If you need to be sure that these values are correct before working with them you can use the optional `[successCallback]` argument. Closing now since this isn't a bug.

**Comment by FiftyTwoWays** [comment]
My bad didn't think that way. Thank you !

**Comment by limzykenneth** [comment]
When calling `console.log`, what is logged into the console is the value of the variable at the time of logging. When you click on the expansion button, the expression logged will be re-evaluated at that point in time based on the current state of the web page so its value may be different.

When you call `createImg` an `<img>` tag is created and the `src` attribute will be populated based on the argument provided, but that does not load the data provided by the `src` attribute as that is done asynchronously (hence why `createImg` has a success callback argument). If the data is not yet loaded, it cannot know what the size of the image is and so it will return 0 for the width and height.

This isn't a bug per se, at least not in p5, as that is something most browser (Chrome, Safari, probably Firefox too) does and it will occur regardless of the library you are using. Whenever you are loading data, it is best to assume they are asynchronous and use callbacks or promise, etc to handle them.
