### ISSUE TITLE
posenet google dependencies are gone!

### ISSUE THREAD

**Issue by DaleSparrow** [processing/p5.js#3855]
Hey guys! Just wanted to thank you for setting up p5js, it is an enormous help with rapid prototyping stuff! 

So I've been using posenet on p5js extensively for a university project in time and motion studies, works like a charm every time. 
However, this morning no p5js posenet stuff wants to work, even on the p5 web editor. The reason is that it can't find the mobile_net weights dependency on the google servers! Please tell me they still exist and this isn't permanent!

This is the link to the resource it can't find:

https://storage.googleapis.com/tfjs-models/weights/posenet/mobilenet_v1_075/manifest.json

Any help could save me from trouble

Kind Regards,

Dale Sparrow

**Comment by limzykenneth** [comment]
Hi @DaleSparrow, this is the repository for the source code for p5.js and we don't handle any other external dependencies. Your question is best answered on the [forum](https://discourse.processing.org/). Thanks.
