### ISSUE TITLE
Mistake in the p5 createChebox documentation

### ISSUE THREAD

**Issue by tiltproofRain** [processing/p5.js#3856]
on this page : https://p5js.org/reference/#/p5/createCheckbox

The syntax for seeing whether or not a checkbox is checked is stated as 'this.checked()' whereas it should be 'this.checked'.
(checked is not a function)

![Screenshot_9](https://user-images.githubusercontent.com/50487716/60598655-b2c94400-9dca-11e9-822a-730d7b033fcd.png)

**Comment by lmccart** [comment]
I think it's correct as is. Here's the part in the code where checked is set up as a function: https://github.com/processing/p5.js/blob/master/lib/addons/p5.dom.js#L617

And here's a working example in the editor:
https://editor.p5js.org/lmccart/sketches/5ezfWSge4
