### ISSUE TITLE
Manually dispatched key events don't trigger keyTyped

### ISSUE THREAD

**Issue by seldomU** [processing/p5.js#3858]
In the following sketch, keyPressed is called while keyTyped is not. I tested today in the online editor.

```JavaScript
var sketch = new p5( p => {     
  p.keyTyped = () => { console.log("key typed") } 
  p.keyPressed = () => { console.log("key pressed ") }  
})

window.dispatchEvent( new KeyboardEvent('keydown', {key:'a'}))
```

I would expect both key handlers to be called, like P5 does for physically pressed keys.

**Comment by lmccart** [comment]
@seldomU the `keyTyped` function is triggered by a `keypress` event. The `keyPressed` function is triggered by a `keydown` event. So this is correct behavior that only `keyPressed()` is fired by this event dispatch.

**Comment by outofambit** [comment]
@seldomU you can see more information about the `keypress` event at https://developer.mozilla.org/en-US/docs/Web/API/Document/keypress_event
