### ISSUE TITLE
Introduce p5.Vector#rem to calculate the remainder/modulo of a vector. 

### ISSUE THREAD

**Issue by frewsxcv** [processing/p5.js#3861]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [x] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [x] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### New feature details:

(PR with this change: https://github.com/processing/p5.js/pull/3860)

Introduce p5.Vector#rem to calculate the [remainder/modulo](https://en.wikipedia.org/wiki/Modulo_operation) of a vector. . This would be helpful for drawing particles that need to wrap when they go offscreen.

For example, instead of:

```js
particle.position.add(this.velocity);
particle.position.set(
  particle.position.x % width,
  particle.position.y % height,
);
```

Now one can write:

```js
particle.position.add(particle.velocity).rem(width);
```

The signature looks like this:

```js
p5.Vector.prototype.rem = function rem(n) {
  ...
};
```

The one-demension (one parameter) behavior matches what we do for `p5.Vector#mult` and `p5.Vector#div`, in contrast to `p5.Vector#add` and `p5.Vector#sub`. One drawback with this design is you can't calculate the remainder of more than one dimension. In the example above, if my canvas was not a square, I would not be able to use `p5.Vector#rem` to wrap particles since the width and height would be different numbers.

**Comment by outofambit** [comment]
@frewsxcv this looks like a handy addition! i think i would err on the side of a multi-dimensional approach since squares are not the most common window shape. plus, you can use a multi-dimensional API for a square case, but i think it would be pretty hard to use the single-dimension API for different scenarios. what do you think?

**Comment by shubymao** [comment]
I am new to here but I would like to try and add this. Is it ok? Thanks In advance.

**Comment by shubymao** [comment]
Something like this?
```
p5.Vector.prototype.rem = function rem(w, h) {
  if (h === undefined) {
    this.x = this.x % w;
    this.y = this.y % h;
  } else {
    this.x = this.x % w;
    this.y = this.y % h;
  }
};
```
I am new here please point out my wrongdoing to help me learn. Also, any tips would be greatly appreciated. Thanks in advance

**Comment by outofambit** [comment]
hi @shubmayo thanks for offering to help with this! we haven’t fully decided on how we want this to work so i’m afraid we’re not ready to jump into implementation yet. (also @frewsxcv already has a draft going that they linked to above, so i’m guessing they’re wanting to take care of that too)

**Comment by shubymao** [comment]
Ok, how about I work on one for reflecting off of the wall. Do we have something like this? As you can probably tell I really would like to help out.
```javascript
p5.Vector.prototype.reflect = function reflect(w, h) {
 if (h === undefined) {
    this.x = this.x < 0 ? this.x : this.x > w ? 2 * w - this.x : this.x;
    this.y = this.y < 0 ? this.y : this.y > w ? 2 * w - this.y : this.y;
  } else {
    this.x = this.x < 0 ? 0 - this.x : this.x > w ? 2 * w - this.x : this.x;
    this.y = this.y < 0 ? 0 - this.y : this.y > h ? 2 * h - this.y : this.y;
  }
};
```
can i do something like this?

**Comment by limzykenneth** [comment]
@shubymao You can open a separate issue if you wish to propose a reflect feature for p5.Vector, let's keep this one focused on modulo. Thanks.

@frewsxcv @outofambit Being able to modulo a vector feels a bit unintuitive to me as I'm questioning whether I'm taking the modulo of the magnitude of the vector or as demonstrated here the seperate modulo of the different dimensions. Maybe it's just me not being familiar enough with the mathematic conventions. 

I agree that in the multidimensional case, it should take into account that it can be applied differently to different dimensions.

PS. Is `rem` preferred over `mod`? I personally prefer `mod` as that what I call `%` most often but I'm fine with it being either way.

**Comment by Spongman** [comment]
this seems a little contrived to me. I can't think of any time when using a vector library of any kind where i have thought that it could use a modulo operator. usually when something's wrapping around rectangular bounds i like to know when that's happening and perform some other, related operation.
another question: would it be remainder, or remainder? what happens when the input is negative? in javascript `(-1) % 10 === (-1)`

**Comment by frewsxcv** [comment]
> PS. Is `rem` preferred over `mod`? I personally prefer `mod` as that what I call `%` most often but I'm fine with it being either way.

> another question: would it be remainder, or remainder? what happens when the input is negative? in javascript `(-1) % 10 === (-1)`

The programming language community is inconsistent– see the table in https://en.wikipedia.org/wiki/Modulo_operation. There does seem to be a trend with using `rem` if the sign stems from the dividend, as opposed to the divisor, which is the case for JavaScript. I'm not opposed to switching to `mod` if people feel strongly. We should make sure to document the dividend/divisor behavior if this feature gets implemented.

**Comment by frewsxcv** [comment]
> @frewsxcv @outofambit Being able to modulo a vector feels a bit unintuitive to me as I'm questioning whether I'm taking the modulo of the magnitude of the vector or...

Is there any reason you think it would be taking the modulo of the _magnitude_ of the vector?

**Comment by limzykenneth** [comment]
@frewsxcv Mainly because I understand modulo as just a one dimensional operation, applying it to a two dimentional vector to me feels like it should be operating on a one dimensional value of the vector ie the magnitude. It's also the same as @Spongman mentioned that with other vector implementations in other libraries there isn't a modulo that I know of, so I don't have any intuition for what it should be.

**Comment by aferriss** [comment]
It's pretty common in many shader languages that you can mod a vector and the result returned is a vector containing the remainder of each element in the vector. Nvidia has this sample implementation and some more info here https://developer.download.nvidia.com/cg/fmod.html

**Comment by limzykenneth** [comment]
@aferriss I had a quick look at some shader languages' implementation and their signatures are all `mod(vectorN, vectorN)` is this a signature we would like to go for as well? Keep in mind that shader languages tend to be strongly typed while JS isn't (ie. function overloading has always been rather tricky for us).

**Comment by Spongman** [comment]
Be careful with the negative inputs, glsl and hlsl treat them differently and at least one of them is different that the implementation suggested above.

**Comment by aferriss** [comment]
@limzykenneth If it were up to me the signature would be `mod(vectorN, vectorN)`. Additionally, I think it would be good to add one with a signature of `mod(vectorN, scalar)` where scalar would be used to mod all values in the vector. Not that the goal is to match GLSL, but it also displays this behavior. See [here](https://www.shadertoy.com/view/wlXXWH)

**Comment by singhvisha** [comment]
Hi,Can I work on this issue?

**Comment by aferriss** [comment]
@singhvisha I think that we never reached a consensus on how this should be implemented and what the signature would look like. I think if we can agree what this should look like you're good to go work on this one!  

Personally, I'm in favor of the approach I mentioned above where we have 

```
// returns component wise remainder
mod(vectorN, vectorN);
```

for example 
```
let v1 = createVector(1.5, 2.2);
let v2 = createVector(1, 2);
let remainder = mod(v1, v2); // returns (0.5, 0.2)
```

Additionally I think it would be nice to have a signature that lets you use a single scalar for the second parameter:

```
let v1 = createVector(1.5, 1.8);
let remainder = mod(v1, 1.0); // returns (0.5, 1.8)
```

One more thing to consider is the handling of negative numbers. In Javascript, the `%` operator gives you the remainder, which can be negative, [but a true modulus is always positive](https://stackoverflow.com/questions/13683563/whats-the-difference-between-mod-and-remainder). I feel like the expected result here is probably the same as the `%` operator in Javascript.

The last gotcha is probably the handling of mod by zero as in: `mod(vector, 0)`. In JS the result of mod 0 is always `NaN`.

@limzykenneth @outofambit Any opinions or thoughts about the above?

**Comment by singhvisha** [comment]
@aferriss, I think both of them is great to start work with.
