### ISSUE TITLE
SVG-Images can't be loaded with the loadImage() function!

### ISSUE THREAD

**Issue by lukakravos** [processing/p5.js#3863]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [x] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [x] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 
- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

**Comment by lukakravos** [comment]
I just can't load a .svg-Image in p5.js

**Comment by outofambit** [comment]
Hi @lukakravos, sorry you're having issues with this! can you please include your versions in the issue description and some kind of code snippet? that would be helpful, thanks!

#2150 and #1648 might also have some tips that could help.

**Comment by lmccart** [comment]
we're not able to reproduce this but please feel free to reopen if you can provide a code sample that demonstrates the issue. thanks!
