### ISSUE TITLE
Ignore the coverage folder, p5-test.js, and .nyc_output?

### ISSUE THREAD

**Issue by stalgiag** [processing/p5.js#3866]
I don't fully understand the intent for the coverage files that are produced so this question may be off base. But it seems like we might want to add these to the .gitignore
coverage/
lib/p5-test*
.nyc_output/

Is this correct?

**Comment by stalgiag** [comment]
Related to #3834. @outofambit thoughts?

**Comment by outofambit** [comment]
@stalgiag i agree but i believe those files are already in the .gitignore (https://github.com/processing/p5.js/blob/master/.gitignore). are they not ignored for you?

**Comment by stalgiag** [comment]
Oh thanks for the quick reply! That is odd. My branch shows as being up-to-date with upstream master but my gitignore isn't ignoring correctly. I will worry about it on my end as it is definitely local. Sorry for the confusion.

**Comment by meiamsome** [comment]
@stalgiag you may want to `git fetch upstream` and then compare against the upstream remote master - you are potentially comparing against an outdated cache of the upstream state
