### ISSUE TITLE
Add better disposal code handling in GIF support

### ISSUE THREAD

**Issue by stalgiag** [processing/p5.js#3870]
#### Nature of issue?

- [ ] Found a bug
- [x] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [x] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Summary
Currently when decoding a GIF, p5 does not handle all disposal methods. The [current implementation](https://github.com/processing/p5.js/blob/master/src/image/loading_displaying.js#L187) for loading GIFs handles most cases but by no means all. 

This code should be made more clear (perhaps broken out into separate private function) and it should handle more (if not all) disposal codes (methods).

#### Background info on Disposal Methods
From the [GIF89A Specification](https://www.w3.org/Graphics/GIF/spec-gif89a.txt)
            iv) Disposal Method - Indicates the way in which the graphic is to
            be treated after being displayed.

            Values :    0 -   No disposal specified. The decoder is
                              not required to take any action.
                        1 -   Do not dispose. The graphic is to be left
                              in place.
                        2 -   Restore to background color. The area used by the
                              graphic must be restored to the background color.
                        3 -   Restore to previous. The decoder is required to
                              restore the area overwritten by the graphic with
                              what was there prior to rendering the graphic.
                     4-7 -    To be defined.
[Visual Explainer of Disposal Methods](http://www.theimage.com/animation/pages/disposal.html)

**Comment by singhvisha** [comment]
@stalgiag ,
I have gone through the documentation you provided.Only few disposal codes are defined in current implemantation.So only all the disposal Codes are to be implemented in current gif COde.Am I correct?
Can I start working on it?

**Comment by stalgiag** [comment]
Hi @singhvisha yes. I'd be happy to review these changes. Good luck!

**Comment by singhvisha** [comment]
@stalgiag , Could you please redirect me to `GifReader(buffer)` implementation?

**Comment by stalgiag** [comment]
Hi @singhvisha [that is in this package here.](https://github.com/deanm/omggif/blob/master/omggif.js#L366) But the [`frameInfo(j).disposal`](https://github.com/processing/p5.js/blob/master/src/image/loading_displaying.js#L184) should already have the relevant codes.

**Comment by devashish1099** [comment]
@stalgiag  can i work on this issue ,

**Comment by stalgiag** [comment]
Hi @devashish1099 when there is already an assignee it is better to ask them directly if they wish to keep working on the issue. I would also only recommend doing this only if an assigned has been assigned without activity for more than 1 month.

**Comment by devashish1099** [comment]
@singhvisha do you wish to keep working in this issue

**Comment by davepagurek** [comment]
Hi! I filed another gif-related bug recently (https://github.com/processing/p5.js/issues/5167) and have been looking into the relevant code. I believe the change for that bug and also for this would need to be to these lines:

https://github.com/processing/p5.js/blob/8c9e9a13e4571e1c49af5b1faf2e104b89863f93/src/image/loading_displaying.js#L196-L204

I've also found <a href="https://legacy.imagemagick.org/Usage/anim_basics/#background">an old ImageMagick doc</a> that has example gifs using each disposal method would make great test cases for this.

I would be interested in taking on this task if that's alright with you all!

**Comment by stalgiag** [comment]
Hi @davepagurek it has been a long time since someone has looked into this. thank you for the well-written issue and offer to help. There is no one currently assigned so I am happy to assign you.
