### ISSUE TITLE
GIF delays are averaged across frames

### ISSUE THREAD

**Issue by stalgiag** [processing/p5.js#3872]
#### Nature of issue?

- [ ] Found a bug
- [x] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [x] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [ ] Desktop/Laptop
- [ ] Others (specify if possible)

#### Summary
Currently when decoding GIF files, p5 [averages the frame delay across all frames. ](https://github.com/processing/p5.js/blob/master/src/image/loading_displaying.js#L216). This is so that the `delay` value in `gifProperties` can be a single number, and there doesn't need to be a unique delay for every frame. This works for most GIFs, since most GIFs have a consistent delay across frames. 

This issue can serve as a discussion point. If people find that this behavior causes problems, they can post here, and if necessary changes can be made.

#### Potential Fixes
delay can be `integer[]` with a length of `numFrames`
or
A frame can become an object `frame = {imageData, delay}`

**Comment by hamoid** [comment]
Here an example of a GIF that would not work with the current approach:
https://hamoid.tumblr.com/post/79459820142/twenty-four-point-fifty-five-seconds-attempt-to
