### ISSUE TITLE
Updating reference examples in utilities/ to ES6 syntax

### ISSUE THREAD

**Issue by stalgiag** [processing/p5.js#3878]
I think this was missed when resolving #3382 

The reference examples in the files in [src/utilities](https://github.com/processing/p5.js/tree/0.9.0/src/utilities) still need to be updated to ES6 syntax.

The todo here is mostly to change `var` to `let` or `const` in the reference examples inside the folder linked above. There are tons of resources online for learning about ES6. [Here is an interactive guide](http://stack.formidable.com/es6-interactive-guide/#/) that covers the biggest features.

**Comment by hsab** [comment]
Is this referring to 0.9 in particular? Because I remember updating those for the #3874

**Comment by shubymao** [comment]
@stalgiag I would like to try and help later today. Does all the examples in utilities need to be updated?

**Comment by stalgiag** [comment]
Apologies! I was just looking at my local copy and the website when I posted this. I didn't realize that you were fixing the examples as well but that makes sense. Closing now!
