### ISSUE TITLE
p5.dom createSelect() options cannot be set to disabled or selected 

### ISSUE THREAD

**Issue by i3games** [processing/p5.js#3880]
#### Nature of issue?

- [ ] Found a bug
- [x] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [X] Other (specify if possible)

p5.dom

#### p5.js version 

0.9.0

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [X] Desktop/Laptop
- [ ] Others (specify if possible)

#### Feature enhancement details:

I'm not sure how to set an attribute like `disabled` or `selected` (default option) on the options of a Select element as `createSelect().option()` returns `undefined`. 

https://p5js.org/reference/#/p5/createSelect

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option

the following workaround works for `disabled` but not for `selected`
  
```
  const selectPlayer1 = createSelect().id('s1');
  selectPlayer1.position(10, 10);
  selectPlayer1.option('a');
  selectPlayer1.option('b');
  selectPlayer1.option('c');
  // selectPlayer1.changed(onSelectPlayer1);
  const options = selectAll('option', 's1');
  options[1].attribute('disabled', 'disabled');  
```

**Comment by limzykenneth** [comment]
Does this resolution of #3830 solve this issue?

**Comment by i3games** [comment]
I tried with the example included in master, `option()` still doesn't return anything.

```javascript
const selectPlayer1 = createSelect();
selectPlayer1.position(10, 10);
const option = selectPlayer1.option('a');
console.log(option);
```

_undefined_

**Comment by Mayank-Mishra0110011** [comment]
Use `selected(value)` to set a value as selected. So something like `selectPlayer1.selected('b')` would set option 'b' as default.

Use `attribute(attr, value)` to set an attribute. In DOM the 'disabled' attribute takes a boolean value which you can set using the attribute function as `selectPlayer1.attribute('disabled', 'true')`.

`option(name, value)` is used to modify(add/remove) an option. It does not return anything therefore you get an undefined value.

**Comment by i3games** [comment]
Thanks for the info. Selected works as you described, disabled still does not work. 

The problem with disabled is how to disable/enable an option. Setting it as you suggest disables the whole select element ('disabled' and 'true' as attribute values make no difference, both evaluate to true).

`selected` confuses me a bit, because in HTML one would set it as attribute on the <option> element, not on the <select> element (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select). The same goes for disabled.

That would suggest two options (pun intended): 

A. either document `selected` on https://p5js.org/reference/#/p5/createSelect and implement a similar API for `disabled` `selectPlayer1.disabled('b')`.

B. Or, which I think would be an even better solution: make option return its element. Then we can set attributes like selected or disabled on it like we do in HTML. We can also assign it an id which might be useful as well.

**Comment by jatin33** [comment]
Hi @i3games ,
 Please try below snippet to disable individual option by changing array index.
let sel;
function setup() {
  textAlign(CENTER);
  background(200);
  sel = createSelect();
  sel.position(10, 10);
  sel.option('pear');
  sel.option('kiwi');
  sel.option('grape');
  sel.option('banana');
  sel.selected('kiwi');// selected method working
  const options = selectAll('option');
  options[2].elt.disabled = true; // way to disable individual option
}

Here is the working example of above snippet:
https://editor.p5js.org/jatin33/present/Hg3O70N-k

**Comment by jatin33** [comment]
However I do agree that there should be a method to handle the disabling of individual options separately.

Method signature:
-------------------------
function disable(select_id, optionName){

}

Method implementation and its usage
------------------------------------------------------
let sel;

function setup() {
  textAlign(CENTER);
  background(200);
  sel = createSelect().id('fruits');
  sel.position(10, 10);
  sel.option('pear');
  sel.option('kiwi');
  sel.option('grape');
  sel.option('banana');
  sel.selected('kiwi');// selected method working
  const options = selectAll('option'); 
  disable('fruits','grape');
}

function disable(selectId,option){
  let options = select(`#${selectId}`);
  for(let i=0;i<options.elt.length;i++){
    if(options.elt[i].value === option){
      options.elt[i].disabled = true;
    }
  }
}

**Comment by jatin33** [comment]
What do you think about this @lmccart  , @i3games , @limzykenneth ?

**Comment by lmccart** [comment]
@jatin33 I think this makes sense, but I think it should be attached to the element itself. something like:
```js
  sel = createSelect().id('fruits');
  sel.disable(); // disable whole combobox
```

```js
  sel = createSelect().id('fruits');
  sel.option('pear');
  sel.option('kiwi');
  sel.disable('pear'); // disable single option
```

**Comment by jatin33** [comment]
Yes that makes a lot of sense!
Will get to implementing that and make a PR soon!

**Comment by agrshch** [comment]
I have a stupid question, sorry. How to enable the option back? :) Disabling seems to be a one-way ticket right now

**Comment by limzykenneth** [comment]
@agrshch Good question actually, do open a new issue so that we can implement a ".enable" method possibly.

**Comment by jimenez537** [comment]
@limzykenneth  may I please ask you a question re enable/disable of createSelect?

if yes, please see: https://editor.p5js.org/freedom55/sketches/AMLBS_Q7t  

when I select any element it becomes disabled in the row amd column it is in, which is good.  If I select another number on an already slected list, I try to enable the previously slelected value and it says : "enable is not a function" on similar code that worked for disable

Thank you,

Andrew

**Comment by limzykenneth** [comment]
@jimenez537 Your sketch on the editor is still using an older version of p5.js `1.4.1` and updating it to the latest `1.7.0` should get rid of the error mentioned.

**Comment by jimenez537** [comment]
@limzykenneth Thank you for your help in this matter.
