### ISSUE TITLE
How can i get each face of a loaded object (.obj file)

### ISSUE THREAD

**Issue by mraposka** [processing/p5.js#3882]
For example i want to change color of each faces of a cube that i loaded as a .obj file. How can i do that?

**Comment by lmccart** [comment]
@mraposka if you want to color or texture individual faces of an object, you can write a shader to do that and use the [loadShader()](https://p5js.org/reference/#/p5/loadShader) and [shader()](https://p5js.org/reference/#/p5/shader) methods to apply it. For more help with this, you can post on the [forum](https://discourse.processing.org).
