### ISSUE TITLE
loadfont : CORS request does not use http

### ISSUE THREAD

**Issue by derrgis** [processing/p5.js#3885]
#### Nature of issue?
- [x] Found a bug

#### Most appropriate sub-area of p5.js?
- [x] Typography

#### Which platform were you using when you encountered this?
- [x] Desktop/Laptop

#### Details about the bug: 
- p5.js version: 0.8.0 April 08, 2019 
- Web browser and version: FIREFOX 68.0 (64 bits)
- Operating System: OSX.11.6

- Steps to reproduce this:
function preload() {
   font = loadFont('ColabThi.otf');
}
> FIREFOX WEB CONSOLE ERROR:
Cross-Origin Request Blocking: The "Same Origin" policy does not allow access to the remote resource located on file: ///Users/......./ColabThi.otf. 
Reason: The CORS query does not use http.

#### New feature details:
PLEASE MAKE loadfont working  with local fonts:)

**Comment by lmccart** [comment]
@derrgis this should work, but you need to be running a local server to see it in action. here are [instructions for running a local server](https://github.com/processing/p5.js/wiki/Local-server). alternatively, you could use the [p5.js web editor](https://editor.p5js.org) and there's no need to run a server of your own.

**Comment by derrgis** [comment]
@lmccart  Great ! thx for your help. I going to have a look to that :)

**Comment by derrgis** [comment]
Hi, in Firefox it seems that option can be set to False to get the font working 👍 
`about:config -> security.fileuri.strict_origin_policy -> false`
source : [https://stackoverflow.com/questions/17088609/disable-firefox-same-origin-policy]
