### ISSUE TITLE
 getUserMedia is not implemented in this browser at createCapture() on Chrome

### ISSUE THREAD

**Issue by bpaltezo** [processing/p5.js#3886]
When i open the program as a local file there is no error. I only get the error when i run my program on a local server.

**Comment by limzykenneth** [comment]
Hi @bpaltezo, can you share a simple sample code that demonstrate this problem?

**Comment by lmccart** [comment]
we're not able to reproduce this, please reopen if you can provide some sample code. thanks!

**Comment by MetaPeak** [comment]
@bpaltezo I met the same problem, I find the reason on [p5.js offical website](https://p5js.org/reference/#/p5/createCapture) of the api of createCapture, they said: 
```
Security note: A new browser security specification requires that getUserMedia, which is behind createCapture(), only works when you're running the code locally, or on HTTPS. Learn more here and here.
```

**Comment by u99d88** [comment]
It blocked by chrome in not secured websites.
![image](https://user-images.githubusercontent.com/35187794/71324694-c6887400-24ea-11ea-885d-c7cacb2bf694.png)

You can bypass it: https://medium.com/@Carmichaelize/enabling-the-microphone-camera-in-chrome-for-local-unsecure-origins-9c90c3149339

**Comment by IncreikeSoul** [comment]
> It blocked by chrome in not secured websites.
> ![image](https://user-images.githubusercontent.com/35187794/71324694-c6887400-24ea-11ea-885d-c7cacb2bf694.png)
> 
> You can bypass it: https://medium.com/@Carmichaelize/enabling-the-microphone-camera-in-chrome-for-local-unsecure-origins-9c90c3149339

It works for me when i was testing my ibm watson demo since my host from remote gcp, the only question that i've planted will be if my demo only working in http ssl domain and without enable "Insecure origins treated as secure".

**Comment by u99d88** [comment]
> > It blocked by chrome in not secured websites.
> > ![image](https://user-images.githubusercontent.com/35187794/71324694-c6887400-24ea-11ea-885d-c7cacb2bf694.png)
> > You can bypass it: https://medium.com/@Carmichaelize/enabling-the-microphone-camera-in-chrome-for-local-unsecure-origins-9c90c3149339
> 
> It works for me when i was testing my ibm watson demo since my host from remote gcp, the only question that i've planted will be if my demo only working in http ssl domain and without enable "Insecure origins treated as secure".

Using https will probably solve the issue. Please see insecure sites definition here: https://www.chromium.org/Home/chromium-security/marking-http-as-non-secure
