### ISSUE TITLE
webgl/loadSTL manual test is broken in Chrome on Window

### ISSUE THREAD

**Issue by stalgiag** [processing/p5.js#3892]
Currently in 'master' the manual test is broken in Chrome 75.0.3770.100 with Windows 10. It works fine in Firefox. The bug seems to occur with both the binary and ascii models. I have tried testing them separately both have the same error.

The error message is:
`GL ERROR :GL_INVALID_OPERATION : glDrawElements: attempt to access out of range vertices in attribute 2`

Which usually means that the buffer for the faces (fill) is not being constructed correctly during loading. [This seems similar to a bug](https://github.com/processing/p5.js/pull/3675#issuecomment-497970726) that appeared to be fixed before merging this feature.

any ideas @sanketsingh24?

**Comment by aferriss** [comment]
@stalgiag @sanketsingh24 I'm 99% certain that the problem comes from the uv buffer not being filled. We just need to fill it up with dummy data as in that comment linked above.
