### ISSUE TITLE
New Feature: spotLight()

### ISSUE THREAD

**Issue by sanketsingh24** [processing/p5.js#3894]
#### Nature of issue?

- [x] New feature request

#### Most appropriate sub-area of p5.js?

- [x] WebGL

#### New feature details:

As a part of the Summer of Code, I will be implementing `spotLight()` along with @aferriss in  `src/webgl/light.js`. The function will be-
`spotLight(color, position, direction, angle, concentration)`. 

##### Problems-

1. The arguments `angle` and `concentration` doesn't seem to reflect what they are used for. 
    - `angle` is the maximum dispersion of light from its direction, ie angle of the cone.
    - `concentration` is the attenuation of the `spotLight()`.
Some alternatives which we could think of-
    - `angle` - `projection angle, opening angle, spread`
    - `concentration` - `falloff, intensity, attenuation` 

2. We had thought of setting `angle` and `concentration` as default to `PI/3` and `1` respectively.
But now, we have no means to distinguish between the two of them if the user sets only one of them. So we have thought that If the user wants to set the concentration, he also has to set the angle. So the usage of function would be like this-
    - `spotLight(color, position, direction)`
    - `spotLight(color, position, direction, angle)`
    - `spotLight(color, position, direction, angle, concentration)`

**Comment by aferriss** [comment]
Closing because this is merged in https://github.com/processing/p5.js/pull/3913
