### ISSUE TITLE
Bug in applyMatrix

### ISSUE THREAD

**Issue by johncbowers** [processing/p5.js#3898]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.9.0
- Web browser and version: Safari 12.1.1
- Operating System: macOS 10.14.5
- Steps to reproduce this:

The applyMatrix method does not work correctly. Below is a small example showing the problem. The first call to apply matrix should result in a matrix that aligns the y axis with the x axis (in other words, after applying the matrix [0 0 1]^T should be the same position as what was previously [0 1 0]^T). The code should draw two ellipses, one red and one blue, each with a box of the same color 50 units in the normal direction. Instead the blue box is drawn on the circle instead of in the normal direction which is incorrect. I have also converted the code to normal Processing 3 java code, which works correctly. 

__erroneous p5js code__

```javascript
function setup() {
  createCanvas(710, 400, WEBGL);
}

function draw() {
  
  background(200);
  lights();
  stroke(0);
  fill(80, 80, 200);
  rotateX(20);
  rotateY(20);
  push();
  // Applying this matrix _should_ align the z-direction with the original y direction
  // since the 3rd column of the matrix applied is [0 1 0 0]^T but it does not. 
  applyMatrix(
    0, -1, 0, 0,
    0,  0, 1, 0,
    1,  0, 0, 0,
    0,  0, 0, 1);
  ellipse(0, 0, 100, 100); // Z-direction should be in [0 1 0]
  // Drop a teal box in the normal direction to the ellipse.
  fill(0, 255, 255);
  translate(0, 0, 50);
  box(10);
  pop();
  
  // Dropping a box at 0 50 0 which _should_ be at the same position as the teal box
  // to show that the ellipse and teal box are not in correct position. 
  push();
  translate(0, 50, 0);
  box(5); // Box should not show because it should be inside the teal box previously drawn
  pop();
  
  // Example of correct behavior: 
  fill(255, 0, 0);
  push();
  ellipse(0, 0, 100, 100);
  translate(0, 0, 50);
  box(5);
  pop();
  
}
```

__The same code ported to Processing 3 for comparison__

This code works as expected. 

```java
void setup() {
  size(800, 600, P3D);
  background(255);
}

void draw() {
  background(200);
  lights();
  stroke(0);
  fill(80, 80, 200);
  translate(width / 2, height / 2, 0);
  rotateX(20);
  rotateY(20);
  pushMatrix();
  applyMatrix(
    0, -1, 0, 0,
    0,  0, 1, 0,
    1,  0, 0, 0,
    0,  0, 0, 1);
  ellipse(0, 0, 100, 100); // Z-direction should be in [0 1 0]
  // Uncomment to view teal box in appropriate location:
  //fill(0, 255, 255);
  //translate(0, 0, 50);
  //box(10);
  popMatrix();
  
  pushMatrix();
  translate(0, 50, 0);
  box(5); // Box should be normal to the circle not on it. 
  popMatrix();
  
  // Example of correct behavior: 
  fill(255, 0, 0);
  pushMatrix();
  ellipse(0, 0, 100, 100);
  translate(0, 0, 50);
  box(5);
  popMatrix();
  
}
```

**Comment by johncbowers** [comment]
It appears that sending the transpose of the desired matrix has the same behavior as in Processing 3 at least for this example it seems to fix it. I'll play around with it more when I can and add additional details here.

**Comment by johncbowers** [comment]
I have confirmed that in the larger code base I am migrating from processing transposing each call to applyMatrix _appears_ to produce correct looking output.

**Comment by johncbowers** [comment]
Another quick update, I've been playing around with it and from my testing to get the same output as Processing 3, I need to not only transpose but multiply my applied matrix by -1. So 

```
applyMatrix(a, b, c,
                     d, e, f, 
                     g, h, i)
```

in Processing 3 has the same effect as 

```
applyMatrix(-a, -d, -g, 
                     -b, -e, -h, 
                     -c, -f, -i)
```

in p5.js.

**Comment by stalgiag** [comment]
I am having a bit of trouble following what is going on here, especially the two follow up comments. Could you post a very simple working sketch (even if it needs to use Processing 3) and a very simple broken sketch? Thank you!

**Comment by johncbowers** [comment]
@stalgiag 

Here you go. 

Working Processing 3 Code. In it, two boxes are drawn, one blue, one teal, but the blue box is inside the teal box so you do not see it. This is correct behavior, since mathematically the matrix I applied should align the teal box's coordinate frame's z-direction with the blue box's y-direction. You can tell this is the case because the third column of the matrix I apply before drawing the teal box tells where to send the z-direciton and we are sending it to (0, 1, 0, 0)^T. 

```
void setup() {
  size(800, 600, P3D);
}

void draw() {
  background(200);
  
  // Necessary to center origin on screen, otherwise origin is at top
  // left corner: 
  translate(width / 2, height / 2, 0);
  
  pushMatrix();
  applyMatrix(
    0, -1, 0, 0,
    0,  0, 1, 0,
    1,  0, 0, 0,
    0,  0, 0, 1);
  fill(0, 255, 255);
  translate(0, 0, 50);
  box(10); // Teal box should incase the blue box. 
  popMatrix();
  
  pushMatrix();
  fill(80, 80, 200);
  translate(0, 50, 0);
  box(5); // Should be inside the teal box and not visible. 
  popMatrix();
}
```

Here is the not working p5js code, which I tested here: https://editor.p5js.org

When I run this code, you see both the teal box and the blue box which means the applyMatrix is not applying the matrix in the expected fashion. 

```
function setup() {
  createCanvas(800, 600, WEBGL);
}

function draw() {
  background(200);
  
  push();
  applyMatrix(
    0, -1, 0, 0,
    0,  0, 1, 0,
    1,  0, 0, 0,
    0,  0, 0, 1);
  fill(0, 255, 255);
  translate(0, 0, 50);
  box(10); // Teal box should incase the blue box. 
  pop();
  
  push();
  fill(80, 80, 200);
  translate(0, 50, 0);
  box(5); // Should be inside the teal box and not visible. 
  pop();
}
```

**Comment by meiamsome** [comment]
It looks to me actually like this code: https://github.com/processing/p5.js/blob/ca92fc457ff836e293916df06964e85f83182368/src/webgl/p5.RendererGL.js#L807 is doing `BA` where B is the input matrix in to `applyMatrix` and A is the current transform matrix. It should, however, be doing `AB` which would be given by: 
```
p5.Matrix.prototype.mult.apply(this.uMVMatrix, arguments); 
```

Indeed the other clause has been written with the matrix components transposed from normal to accommodate the misuse of apply: https://github.com/processing/p5.js/blob/ca92fc457ff836e293916df06964e85f83182368/src/webgl/p5.RendererGL.js#L810-L815
vs. as it is specified to work (It has been adapted from a 2d to 3d transformation matrix (dimension 3 to 4)): 
![Transformation matrix](https://p5js.org/reference/assets/transformation-matrix.png)

**Comment by stalgiag** [comment]
Sorry for the delay! @meiamsome thank you so much for doing the research. Would you be willing to fix it? If not let me know and I can work on it next week.

**Comment by stalgiag** [comment]
Okay!

Matrix math isn't my strong suit. But I think what is happening here is that there is some confusion as p5's WEBGL renderer is using column-major matrices for its model view matrix. Like this:

```
1, 0, 0, 0
0, 1, 0, 0
0, 0, 1, 0
x, y, z, 1
```

So if you apply the transposed matrix instead then you get what you are looking for:
```
applyMatrix(
    0, 0, 1, 0,
    -1, 0, 0, 0,
    0, 1, 0, 0,
    0, 0, 0, 1);
```

I am not sure why this decision was made (on either side) but I do know that column-major is more common for WEBGL.

Let me know if this fixes your problem because as I said this isn't my wheelhouse. I am able to get the expected results in your example when applying the transposed matrix.

**Comment by stalgiag** [comment]
Just a gentle ping @johncbowers to see if my last reply helped with your issue.

**Comment by stalgiag** [comment]
I added an indication of this difference in the [Processing transition wiki](https://github.com/processing/p5.js/wiki/Processing-transition). I am going to close this for organization purposes. If I missed something, feel free to ping me and I'll reopen. Thank you!
