### ISSUE TITLE
Masks on p5.Graphics

### ISSUE THREAD

**Issue by figraham** [processing/p5.js#3900]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [X] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [X] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### New feature details:

I was working on a sketch and I realized that you can't mask a p5.Graphics with another one. This is different from what I'm used to in Processing because PGraphics inherits from PImage. It would be a great feature to add so I created a function based on the code in p5.Image. [Here's an example sketch running in web editor](https://editor.p5js.org/figraham/sketches/vOUjYwE3Z).

```
p5.Graphics.prototype.mask = function(inputMask) {
  
  if (inputMask === undefined) {
    inputMask = this;
  }
  const currBlend = this.drawingContext.globalCompositeOperation;

  let scaleFactor = 1;
  if (inputMask instanceof p5.Renderer) {
    scaleFactor = inputMask._pInst._pixelDensity;
  }

  const copyArgs = [
    inputMask,
    0,
    0,
    scaleFactor * inputMask.width,
    scaleFactor * inputMask.height,
    0,
    0,
    this.width,
    this.height
  ];

  this.drawingContext.globalCompositeOperation = 'destination-in';
  p5.Renderer2D.prototype.copy.apply(this, copyArgs);
  this.drawingContext.globalCompositeOperation = currBlend;

}
```

**Is there a reason this hasn't been added yet?** Should I work on writing documentation and then make a pull request with it?

Related to #2841

**Comment by outofambit** [comment]
This looks pretty interesting to me @figraham. Thanks for writing this up (and having a demo!). I'm not aware of any reasons this hasn't been done already but I'll let others (esp. @lmccart and @stalgiag) chime in if there is extra context around this.

**Comment by figraham** [comment]
Sweet! The two things I haven't checked out is a webgl p5.Graphics and at other pixel densities. So I'll try out those two scenarios sometime this week to see if more work would be necessary to make this solution work for everything.

**Comment by figraham** [comment]
Unfortunately I've encountered some problems when testing this with WEBGL graphics. The `drawingContext` location changes in different modes and while I've almost got it working it appears that the copy method for p5.Graphics doesn't work in WEBGL and now I'm working on that.

I'll dedicate a bit more time to it but I think it's likely that even if I do come up with a solution it might not be very maintainable code.

As a side note, I've found that p5.Graphics has a number undocumented method attached to it which may not work in all circumstances. I wonder if worth investigating more of them to improve functionality.

**Comment by stalgiag** [comment]
Hi @figraham if you want to you can break part of that problem out into its own issue and I can work on it next week. The WebGL+p5.Graphics stuff sounds troubling and I can happily take a crack at it. It is usually better to avoid fixing or adding more than one thing in a pull request anyways. Just let me know!

**Comment by figraham** [comment]
Closing this issue with the intention of putting this feature in a separate library that's designed for working with multiple p5.Graphics objects in a streamlined way.

**Comment by jh97uk** [comment]
Hi @violetcraze are you aware of what library this belongs to? Masking on Graphics is crucial for my new project.

**Comment by violetcraze** [comment]
@jh97uk never got around to making a library. If you're project is just using 2d you can probably just use the function from my initial sketch. And I think there was another sketch somewhere in this thread with a 3d function that I think might have been merged and is part of p5 core now. 

Sorry I can't be more helpful. You could look into pixi.js, three.js, or openframeworks compiled to web assembly to see it would be easier to do with one of them.
