### ISSUE TITLE
rectMode(CORNERS) and scale function create circle instead of a rectangle

### ISSUE THREAD

**Issue by ghsuvr123** [processing/p5.js#3901]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.9.0
- Web browser and version: Chrome 75.0.3770.142
- Operating System: Windows
- Steps to reproduce this: 
```javascript
function setup(){
  createCanvas(400, 400);
  scale(50);
  rectMode(CORNERS);
  fill(0);
  rect(3, 3, 3, 3);
}
```
:
I tried to generate rectangle with scale and rectMode CORNERS on the same point, and it generated circle instead of a rectangle...
![circle](https://user-images.githubusercontent.com/18012930/61522808-c657ea00-aa1b-11e9-9fb7-386e97a4991a.PNG)
I played with the numbers and it always generate circle. I found that the diameter of the circle is always the scale size.

**Comment by lmccart** [comment]
`rectMode(CORNERS)` interprets the first two parameters of rect() as the location of one corner, and the third and fourth parameters as the location of the opposite corner. 
So what you're seeing is the browser trying to interpret the request to draw a rectangle that has all four corners at (3,3). This results in a point, that gets scaled up into a circle with `scale(50)`. If you are trying to specify only the location of the first corner, you can use `rectMode(CORNER)` instead.

**Comment by ghsuvr123** [comment]
I think this is not a point. This is an ellipse. I tried to use ellipseMode and the shape changed.
I know this is an edge case but I expected to see a rectangle with sharp corners. Not a circle.
Anyway, when I take down the `scale(50)` or the `rectMode(CORNERS)` it works properly, so I think there is an issue here.

**Comment by lmccart** [comment]
@ghsuvr123 I'm not sure what output is expected for a square whose corners are all at the exact same place. Should it be nothing at all? It's just not possible to draw a square with no pixels inside, which is how we end up with a point.
