### ISSUE TITLE
frameRate() returns value greater than 0 if frame rate is set to 0

### ISSUE THREAD

**Issue by Niels-NTG** [processing/p5.js#3903]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [x] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.9.0 & 0.8.0
- Web browser and version: Chrome 75.0.3770.142
- Operating System: macOS 10.14.5
- Steps to reproduce this:
1. Set the frame rate to 0 _after_ setup has been completed (`frameRate(0)`)
2. Visually the frame rate is indeed 0, but when getting the frameRate it reports the frame rate from the moment before frame rate was set to zero.

As a result of this bug, building logic to halt and resume a sketch is seemingly impossible. 
```is
function keyPressed() {
    if (key === ' ') {
        if (frameRate() > 0) {
            frameRate(0)
        } else {
            frameRate(25)
        }
    }
}
```

#### New feature details:
Additionally (this might be outside the scope of this issue) it would be nice if there was a method `isLooping()`. This would return `false` after `noLoop()` or `frameRate(0)` and set to true initially and when `loop()` is called.

**Comment by outofambit** [comment]
Hi @Niels-NTG thanks for filing this! I think the minimal fix here is to make sure `frameRate()` returns `0` once it's been set to `0`, so i'm going to mark this a bug.

_____

In the meantime, you should be able to keep track of this state outside of p5. Something like:

```js

let isLooping = true;

function stopLoop() {
    frameRate(0);
    isLooping = false;
}

function startLoop() {
    frameRate(25);
    isLooping = true;
}

function keyPressed() {
    if (key === ' ') {
        if (isLooping) {
            stopLoop();
        } else {
            startLoop();
        }
    }
}
```

**Comment by meiamsome** [comment]
Ideally you would prefer `noLoop()` to `frameRate(0)` - but you would hit the problem discussed in #3242 in that case

**Comment by Niels-NTG** [comment]
> Hi @Niels-NTG thanks for filing this! I think the minimal fix here is to make sure `frameRate()` returns `0` once it's been set to `0`, so i'm going to mark this a bug.
> 
> In the meantime, you should be able to keep track of this state outside of p5. Something like:
> 
> ```js
> let isLooping = true;
> 
> function stopLoop() {
>     frameRate(0);
>     isLooping = false;
> }
> 
> function startLoop() {
>     frameRate(25);
>     isLooping = true;
> }
> 
> function keyPressed() {
>     if (key === ' ') {
>         if (isLooping) {
>             stopLoop();
>         } else {
>             startLoop();
>         }
>     }
> }
> ```

That's exactly what I did. Thanks anyway.
