### ISSUE TITLE
p5js for Mobile not working after iOS update

### ISSUE THREAD

**Issue by Eoey1** [processing/p5.js#3906]
Hey,

I had made a p5.js sketch that worked with mobile devices and in particular used the deviceShaken() function.  Recently I noticed it had stopped working on my iPhone and various other iPhone's that I asked people to test it on.  Many of the mobile examples on the p5.js website no longer work either.

Has anyone experienced any similar issues?

**Comment by lmccart** [comment]
@Eoey1 apple has recently limited access to accelerometer in safari by default. You can turn it on by going to:  Settings > Safari > Privacy & Security > Motion & Orientation Access (toggle on)
[more info here](https://www.fastcompany.com/90302260/in-another-privacy-move-apple-will-limit-websites-access-to-your-iphones-motion-data)

**Comment by Eoey1** [comment]
Hey!

Thanks for this.  Turning Motion & Orientation Access on helps getting some of the examples working on the p5 website, however my app which uses deviceShaken() is still not working.

**Comment by taka1156** [comment]
https://youtu.be/AbB9ayaffTc

It seems that we can deal with this. (ios13 and iPadOS?)

![A7816866-6031-42E6-97EF-0BD228849577](https://user-images.githubusercontent.com/47517002/75942897-f1257e80-5ed6-11ea-9fdf-68dc1ca92de6.png)
Sorry for the unsightly English.
