### ISSUE TITLE
Other 2D shape possibilities

### ISSUE THREAD

**Issue by shubymao** [processing/p5.js#3908]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [x] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### New feature details:
Seeing some of the primitive 2D shapes. I feel that there can be other shapes that can be implemented such as star, polygon, etc. I don't think I would include the full implementation in here for now but I will start working on it if someone believes this is a good idea.  Thanks in advance.
```
// a sample function could look like this
star(x,y,size) 
```

**Comment by stalgiag** [comment]
Hi @shubymao sorry for the lack of response. Thank you for your interest in contributing! My personal feeling is that with shapes such as star and polygon we begin to get into uncertain territory. The amount of customization that could be given to a star alone is astronomical (i am sorry). I think that is probably why the current API lets users make more complex, custom shapes with `beginShape` and `vertex`. There is even a star-like [example in the reference for vertex](https://p5js.org/reference/#/p5/vertex). 

That said, if you want to add a ton of new custom shapes for people to play around with, without necessarily needing to know how to write the custom vertices, then that could be a good starting point for an external library.
