### ISSUE TITLE
Camera zoom with orbitControl() in WebGL

### ISSUE THREAD

**Issue by NeilTheSeal** [processing/p5.js#3914]
#### Nature of issue?

- [ ] Found a bug
- [X] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [X] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.9.0
- Web browser and version: 75.0.3770.142 (Official Build) (64-bit) (cohort: Stable)
- Operating System: Windows Version 10.0.17134 Build 17134
- Steps to reproduce this:

From the following perspective in WebGL mode:
camera(200, -300, ~100, 0, 0, 0, 0, 1, 0);
orbitControl();
Moving the scroll wheel does not always cause the renderer to zoom in or zoom out. It seems sporadic, deciding to zoom in/out some times but not others. 

#### Feature enhancement details:
I would suggest modifying orbitControl() to either smooth-out the zoom handler (it is sticky at the moment), or to allow one to adjust sensitivity (currently orbitControl(e,i) takes two arguments, one for y-sensitivity and one for x-sensitivity when dragging the camera. Perhaps a third argument for zoom would be appropriate.

A previous issue was opened about this https://github.com/processing/p5.js/issues/2497 but the issue still seems to be present

**Comment by stalgiag** [comment]
Thanks for opening an issue. This seems like a reasonable and simple request. I'll open a PR shortly.

**Comment by NeilTheSeal** [comment]
If this helps, I ended up solving the issue with this bit of code:

`cnv = createCanvas(pageWidth, pageHeight, WEBGL);
cnv.mouseWheel(zoom);

function zoom(event) {
    // zoom according to direction of mouseWheelDeltaY rather than value
    let sensitivityZoom = 0.05;
    let scaleFactor = cnv.height;
    if (event.deltaY > 0) {
        cnv._curCamera._orbit(0, 0, sensitivityZoom * scaleFactor);
    } else {
        cnv._curCamera._orbit(0, 0, -sensitivityZoom * scaleFactor);
    }
}`

It is almost identical to the code in orbitControl(), so I am not sure why this works but the default camera zoom did not.
