### ISSUE TITLE
You must first call texture() before using vertex() with image based u and v coordinates.

### ISSUE THREAD

**Issue by bishopZ** [processing/p5.js#3917]
This sketch is still getting the error. It prevents me from doing anything with 3D.

https://editor.p5js.org/bishopz/sketches/8LJDNbAQt

```
function setup() {
  createCanvas(710, 400, WEBGL);
}

function draw() {
  background(250);

  strokeWeight(3);
  beginShape(POINTS);
  vertex(30, 20);
  vertex(85, 20);
  vertex(85, 75);
  vertex(30, 75);
  endShape();
}
```

**Comment by lmccart** [comment]
@bishopZ this sketch is linking to an old version of the library (0.7.3). if you update to the latest (0.9.0) the error goes away.
<img width="1111" alt="Screen Shot 2019-07-26 at 1 59 44 PM" src="https://user-images.githubusercontent.com/191056/61981148-aa20f380-afad-11e9-9723-951f679439fc.png">
