### ISSUE TITLE
Slider outside canvas.

### ISSUE THREAD

**Issue by arunprasaad2711** [processing/p5.js#3924]
#### Nature of issue?
- [x] Found a bug

#### Most appropriate sub-area of p5.js?
- [x] Utilities

#### Which platform were you using when you encountered this?
- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

The silder element is outside the canvas.

- p5.js version: p5.js 0.9.0
- Web browser and version: Google Chrome 75.0.3770.142 (Official Build) (64-bit)
- Operating System: Ubuntu Mate 18.04 
- Steps to reproduce this:
```html
<!DOCTYPE html>
<html lang="">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>p5.js example</title>
    <style> body {padding: 0; margin: 0;} </style>
    <script src="../p5.min.js"></script>
    <script src="../addons/p5.dom.min.js"></script>
    <script src="../addons/p5.sound.min.js"></script>
    <script src="sketch.js"></script>
  </head>
  <body>
	  <div>
		  <p><object width="150" height="150" vspace="100"></object> 
			This is some text. This is some text. This is some text.</p>
	  </div>
  </body>
</html>
```

```js
// sketch.js
var slider;
function setup() {
  slider = createSlider(0, 255, 100);
  slider.position(10, 10);
  slider.style('width', '80px');
}

function draw() {
  var val = slider.value();
  background(val);
}
```

**Comment by lmccart** [comment]
In p5, the entire window area is considered the sketch. So the `position(10, 10)` line will position the slider at (10, 10) relative to the upper left of the window, regardless of canvas position. If you'd like it to overlap with the canvas, you could position the canvas as well. Something like this:
```js
var slider;
function setup() {
  var can = createCanvas(100, 100);
  can.position(10, 10);
  slider = createSlider(0, 255, 100);
  slider.position(10, 10);
  slider.style('width', '80px');
}
```

**Comment by arunprasaad2711** [comment]
I see. Didn't know that! Thank you. I'll keep that in mind!
