### ISSUE TITLE
GatsbyJS build failed: "window is not defined"

### ISSUE THREAD

**Issue by areljannC** [processing/p5.js#3926]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [x] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [x] Others (specify if possible)

#### Details about the bug: 

- p5.js version: master
- Web browser and version: Chrome 75.0.3770.142 (Official Build) (64-bit)
- Operating System: Win10/Mac 10.14/any Linux distros
- Steps to reproduce this:

My setup is [GatsbyJS](https://github.com/gatsbyjs/gatsby), [p5-react-](https://github.com/and-who/react-p5-wrapper) and [p5](https://github.com/processing/p5.js) (all are at their latest versions).

Local development using `gatsby develop` will render p5 sketches on the browser fine. However, when doing a `gatsby build`, this is the error result:

> ERROR #95312
> "window" is not available during server side rendering.
> 61279 |             return _typeof(obj);
> 61280 |           }
> 61281 |           window.requestAnimationFrame = (function() {
>       | ^
> 61282 |             return (
> 61283 |               window.requestAnimationFrame ||
> 61284 |               window.webkitRequestAnimationFrame ||
> WebpackError: ReferenceError: window is not defined
>
> - p5.js:61281 Object.34
>   node_modules/p5/lib/p5.js:61281:1
> - p5.js:34 o
>   node_modules/p5/lib/p5.js:34:1
> - p5.js:38
>   node_modules/p5/lib/p5.js:38:1
> - p5.js:54903 Object.24../constants
>   node_modules/p5/lib/p5.js:54903:1
> - p5.js:34 o
>   node_modules/p5/lib/p5.js:34:1
> - p5.js:38
>   node_modules/p5/lib/p5.js:38:1
> - p5.js:49772 Object.13../color/color_conversion
>   node_modules/p5/lib/p5.js:49772:1
> - p5.js:34 o
>   node_modules/p5/lib/p5.js:34:1
> - p5.js:51 r
>   node_modules/p5/lib/p5.js:51:1
> - p5.js:55
>   node_modules/p5/lib/p5.js:55:4
> - p5.js:4 ./node_modules/p5/lib/p5.js
>   node_modules/p5/lib/p5.js:4:1
> - p5.js:20 Object../node_modules/p5/lib/p5.js
>   
> node_modules/p5/lib/p5.js:20:2`

I am aware about [Gatsby's build issues with `window` not being defined](https://www.gatsbyjs.org/docs/debugging-html-builds/) due to its build processes.

#### Current working solution workaround:
Since p5 is accessing the `window` object in `line 61281`, what I did to prevent other `window` issues is to wrap the entire package function which was [a suggestion from Gatsby's docs](https://www.gatsbyjs.org/docs/debugging-html-builds/#how-to-check-if-window-is-defined):

```javascript
if (typeof window !== 'undefined') {
  /* place entire p5 here */
}
```

#### New feature details:
Check if `window` object exists when referring to `window`.

**Comment by outofambit** [comment]
hi @areljannC thanks for reaching out about this issue! i think [this solution](https://www.gatsbyjs.org/docs/debugging-html-builds/#fixing-third-party-modules) might be more appropriate for your setup. maybe give that a try?

would you be willing to share your project for this? this might also be able to be solved with a gatsby plugin for p5, but i've never used the two together to know how people might go about it. thanks!

**Comment by coreygo** [comment]
Greetings @areljannC,
I can confirm that the solution @outofambit mentioned does work as expected with Gatsby (2.15.1).

You might be able to get away with not using the `react-p5-wrapper` if you create a sketch wrapper component similar to this:

<details><summary>Example Sketch.js component</summary><p>

```js
import React, { Component } from 'react'
import p5 from 'p5'

class Sketch extends Component {
  constructor (props) {
    super(props)
    this.sketchRef = React.createRef()
    this.canvas = null
  }

  componentDidMount () {
    this.canvas = new p5(this.props.sketch, this.sketchRef.current)
  }

  componentDidUpdate () {
    this.canvas.remove()
    this.canvas = new p5(this.props.sketch, this.sketchRef.current)
  }

  componentWillUnmount () {
    this.canvas.remove()
  }

  render () {
    return <SketchWrapper ref={this.sketchRef} />
  }
}

export default Sketch
```

</p></details>


<details><summary>Importing the Sketch component and sketch for use on a page</summary><p>

```js
import React, { Component } from 'react'

import Layout from '../components/layout'
import Sketch from '../components/sketch'
import theSketch from '../utils/theSketch'

export default class IndexPage extends Component {
  render () {
    return (
      <Layout>
        <Sketch sketch={theSketch}></Sketch>
      </Layout>
    )
  }
}
```
</p></details>

<details><summary>Contents of `gatsby-node.js`</summary><p>

```js
exports.onCreateWebpackConfig = ({ stage, loaders, actions }) => {
  if (stage === 'build-html') {
    actions.setWebpackConfig({
      module: {
        rules: [
          {
            test: /p5/,
            use: loaders.null()
          }
        ]
      }
    })
  }
}
```

</p></details>

The following was used in my particular sketch which serves as a page background (to support page resizing):
```js
  p.windowResized = function () {
    p.resizeCanvas(p.windowWidth, p.windowHeight)
  }
```
…so the `window` error was correctly bypassed with p5.js and Gatsby (React).

Hope the above helps. Regards.

**Comment by coreygo** [comment]
Hello @janmaltel,
I've pushed a [test repository to GitHub](https://www.github.com/coreygo/coreygo) for you to clone and use—I'll keep it live for a week or two.

The relevant files are:
- [gatsby-node.js](https://github.com/coreygo/coreygo/blob/master/gatsby-node.js)
- [components/sketch.jsx](https://github.com/coreygo/coreygo/blob/master/src/components/sketch.jsx)
- [pages/index.jsx](https://github.com/coreygo/coreygo/blob/master/src/pages/index.jsx)
- [scripts/phi.js](https://github.com/coreygo/coreygo/blob/master/src/scripts/phi.js)

`<SketchWrapper ref={this.sketchRef} />` is a [styled component created with](https://github.com/coreygo/coreygo/blob/master/src/components/sketch.jsx#L5-L15) Emotion. [Emotion](https://emotion.sh/docs/styled) and [Styled-Components](https://www.styled-components.com/) are probably the most popular way to do CSS-in-JS with Gatsby and React. Emotion has a leg up because it supports multiple methods including styled.

Sorry for the confusion, I snipped that bit of code from my previous response in case you used another option for styling.

Here are a few React links which may be useful:
- [Higher-Order Components (HOCs)](https://reactjs.org/docs/higher-order-components.html)
- [Styling and CSS](https://reactjs.org/docs/faq-styling.html)
- [CSS in JS techniques comparison](https://github.com/MicheleBertoli/css-in-js)

**Comment by janmaltel** [comment]
Absolutely perfect, thank you @coreygo !

**Comment by coreygo** [comment]
@janmaltel My pleasure.

I see you've cloned the repository 😄. Note that I removed the `format` script from `package.json` as it was a copy and paste from another project, definitely do the same as the settings mismatch; you probably also don't need all the extra stuff in `config.js` but it some of it works with the various `gatsby-plugin-`'s. The eslint and prettier set up with AirBnB's config is good to go otherwise and should work fine with VSCode.

I'm removing my copy of the repository now, hope that it helps provide a base for you to build something awesome. Definitely recommend checking out [Netlify](https://netlify.com) if you're looking for a place to deploy a static [JAMstack](https://jamstack.org) site to.

Regards 🖖

**Comment by lachlanjc** [comment]
Running into a similar issue – @coreygo, could you upload that code again, maybe just as a zip here? Since the GitHub link is a 404 now.

**Comment by coreygo** [comment]
@lachlanjc sure thing, please give me a moment. It looks like @janmaltel's fork is still live if you'd like to review it while I sort things: https://github.com/janmaltel/coreygo

**Comment by coreygo** [comment]
@lachlanjc @janmaltel

- Example repository: https://github.com/coreygo/coreygo
- Live build: https://coreygo-gatsby-p5js.netlify.com

**Comment by lachlanjc** [comment]
Thanks a bunch!!

**Comment by beve** [comment]
First of all, thank for this, it really helping !

Just one little thing, in phi.js it worth replacing:

`export default function sketch(p) {`
by
`export default function sketch(...p) {`

Now we can use directly the p5 functions without need of prefixing the call by p. For example using setup() instead of p.setup()

**Comment by janmaltel** [comment]
Thanks again, @coreygo !! 

It worked like a charm until I tried to build an [automated blog summary of .mdx posts](https://www.gatsbyjs.org/docs/mdx/programmatically-creating-pages/). This requires sourcing the directory that contains the blog posts using the ```gatsby-source-filesystem``` plugin as follows:
```
...
{
            resolve: 'gatsby-source-filesystem',
            options: {
                path: `${__dirname}/src/pages/posts`,
                name: 'posts'
            }
},
....
```
in the ```gatsby-config.js``` file. The posts directory contains .mdx files, which in turn access the p5 script(s) using your p5 component. It does work fine if I run ```gatsby build``` and then ```gatsby serve```. However, it does **not** work in ```npm run develop``` mode, where it throws the classic 
```
WebpackError: ReferenceError: window is not defined
```
My assumption is that `gatsby-source-filesystem` somehow bypasses the webpack config rule 
<details>
<summary>
webpack config rule
</summary>
```
exports.onCreateWebpackConfig = ({ stage, loaders, actions }) => {
  if (stage === 'build-html') {
    actions.setWebpackConfig({
      module: {
        rules: [
          {
            test: /p5/,
            use: loaders.null()
          }
        ]
      }
    })
  }
}
``` 
</details>

in the ```gatsby-node.js``` file during some stage of the development build. Does anyone happen to have an idea of how to solve this? 

Also, @coreygo in your new github repo you say:

> ./src/components/sketch.jsx uses ./src/scripts/p5Custom.min.js, a custom minified build of p5.js.

I've seen that you import the minified build in sketch.jsx. Does this "override" the p5 from the node_module? Does one still need p5 in the package.json then?  Thank you!

**Comment by janmaltel** [comment]
Found it myself... in case someone is having the same issue: 
the solution employed by @coreygo  used [this suggestion from the gatbsy site](https://www.gatsbyjs.org/docs/debugging-html-builds/#fixing-third-party-modules) which contained the if statement ```if (stage === "build-html") {...```.
I changed that so that it includes the ```develop-html``` stage as well, as follows:
```
exports.onCreateWebpackConfig = ({ stage, loaders, actions }) => {
    if (stage === 'build-html' || stage === 'develop-html') {
        actions.setWebpackConfig({
            module: {
                rules: [
                    {
                        test: /p5/,
                        use: 'null-loader'
                        // use: loaders.null()
                    }
                ]
            }
        });
    }
};
```
Seems to work for the moment! :)

**Comment by coreygo** [comment]
Greetings @janmaltel,

Yep, as you've found, `if (stage === 'develop-html' || stage === 'build-html')` resolves things; probably the easiest workaround and one I'd go with unless some other condition pops up.

Here's some additional information regarding the [four Gatsby webpack build stages](https://www.gatsbyjs.org/docs/add-custom-webpack-config/).

From [`webpack.config.js`](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/utils/webpack.config.js#L19-L23):

```js
// Four stages or modes:
//   1) develop: for `gatsby develop` command, hot reload and CSS injection into page
//   2) develop-html: same as develop without react-hmre in the babel config for html renderer
//   3) build-javascript: Build JS and CSS chunks for production
//   4) build-html: build all HTML files
```

Also, if you aren't implementing the `gatsby-source-filesystem` plugin for MDX posts you likely wouldn't have hit this issue. This can be confirmed by adding `gatsby-plugin-mdx` but commenting out that particular `gatsby-source-filesystem` section of the `gatsby-config.js` and testing a p5.js sketch in a MDX page. It works, but obviously isn't ideal, you'll probably want the frontmatter and other data inside the MDX posts as mentioned on the [programmatically creating](https://www.gatsbyjs.org/docs/mdx/programmatically-creating-pages/) page.

This is related to [this gatsby-mdx issue](https://github.com/ChristopherBiscardi/gatsby-mdx/issues/248), another potential workaround is offered in [this comment](https://github.com/ChristopherBiscardi/gatsby-mdx/issues/248#issuecomment-529135033) using [loadable-components](https://github.com/smooth-code/loadable-components). The Gatsby [third-party modules page](https://www.gatsbyjs.org/docs/debugging-html-builds/#fixing-third-party-modules) you linked also suggests [react-loadable](https://github.com/jamiebuilds/react-loadable) which appears to offer similar functionality.

---

To answer your other question… `p5Custom.min.js` is used.

`p5` can be removed from `package.json` if you **are** [creating and using a custom p5 build](https://github.com/processing/p5.js/blob/master/developer_docs/custom_p5_build.md). Using a custom minified build shaves off 336K or more, nice if you're not going to use every feature of p5.js.

`p5` in `node_modules` only contains the distributables for p5.js, not the full source to create a custom build. I've included it for testing purposes to easily switch to the distributed build (also to help with discovery and p5's GitHub "used by" stats :wink:).

To use the distributed build `import p5 from 'p5';` or `import p5 from 'p5/lib/p5.min';` for the distributed minified build.

Regards :v:
