### ISSUE TITLE
Negative rect radius error

### ISSUE THREAD

**Issue by mihoci10** [processing/p5.js#3929]
#### Nature of issue?

- [ ] Found a bug
- [X] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [X] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [X] Desktop/Laptop
- [ ] Others (specify if possible)

#### Feature enhancement details:
When using the rounded corner attribute for rect rendering I have encountered a certain issue. I am not always orienting the rect in the positive direction. (I am developing a chart) That is why I sometimes get the error stating that corner radius input has to be positive. If it needs to be always positive to work without an issue why dont just change the attributes for radius to be absolute all the time?

**Comment by outofambit** [comment]
hi @mihoci10 thanks for filing this. can you provide a code snippet and screenshot to illustrate this? i'm not able to follow the scenario.

**Comment by mihoci10** [comment]
Yeah sure, here is a snippet of the code where I am displaying a tooltip that follows the mouse around. Obviously I don't want it to go over the canvas sides, so I check for that and react accordingly with flipping the tooltip.

![Snippet](https://user-images.githubusercontent.com/30954380/62463460-6044c400-b78a-11e9-8319-ddba8cf073da.PNG)

After I use this code with the radius modifier I get the following error:

![Error](https://user-images.githubusercontent.com/30954380/62463540-984c0700-b78a-11e9-8087-a8d72d6c4e2f.PNG)

From what I researched, this happens when the radius is negative OR the rect has been drawn fliped. My suggestion and/or questions is why don't you just modify the function to only use absolute radius value if that's the only way we can use it?

**Comment by stalgiag** [comment]
@mihoci10 I guess this comes down to whether this is a good moment for someone to learn to use [abs()](https://p5js.org/reference/#/p5/abs) on their own. I'm not sure on that point, but I do think that if we don't want to accept negative numbers for the corner rounding, it should be specified in the documentation.

**Comment by mihoci10** [comment]
@stalgiag The issue is that hte radius is ALWAYS the number I screenshoted - being 5. the issue arises when the rect has been drawn in the reverse and that is what I am asking.

By saying rect drawn in reverse I think of a situation like this: rect(posX,posY, -10,-10,5) where the radius is clearly specified as 5 and I get the following error screenshoted above. On some old thread I have seen a mention that this is what happens if the rect is drawn with negative width and/or height I have also tested this instance and can confirm this is the cause.

**Comment by stalgiag** [comment]
@mihoci10 thank you for the clarification. So I understand now that the problem is that both of these work:
`rect(0, 0, -10, -10)`
`rect(0, 0, 10, 10, 5)`
but this does not:
`rect(0, 0, -10, -10, 5)`

**Comment by stalgiag** [comment]
This is likely happening because of how the [logic for radii clipping](https://github.com/processing/p5.js/blob/master/src/core/p5.Renderer2D.js#L675) is evaluating the negative width/height.

**Comment by mihoci10** [comment]
Yes, this is precisely what I mean. Is this something that can be fixed on your end or will I need to adjust my code to always draw 'positive' rects?
