### ISSUE TITLE
Need a filter(NORMAL); option

### ISSUE THREAD

**Issue by ricardocanada** [processing/p5.js#3931]
#### Nature of issue?

- [ ] Found a bug
- [x] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [x] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [x] Mobile/Tablet (touch devices)
- [ ] Desktop/Laptop
- [ ] Others (specify if possible)

#### Feature enhancement details:

Once a filter is set on an image, there is no way I know of to remove it for other images displayed afterward. A variation named " filter(NORMAL); " could serve this purpose.

**Comment by outofambit** [comment]
hi @ricardocanada thanks for writing this up. to make sure i understand, 

> remove it for other images displayed afterward

does this mean you are reusing a `p5.Image` and giving it a new source image? and you'd like to have a way to unset the filter? i think that might be achieved by using an `if` statement to not call `.filter` on that image afterwards?

if you have a code snippet to share that would be very helpful. thanks!

**Comment by ricardocanada** [comment]
You could look at the actual sketch on OpenProcessing and make a fork to test it. 
https://www.openprocessing.org/sketch/742391

I was playing with it for a while tonight, and my request may be pointless, because even one filter on a webcam capture requires so much processing that if I try to put different filters on four different video windows, the program becomes quite choppy and erratic. But let me know if you have any suggestions. 

Thanks,

Richard

**Comment by lmccart** [comment]
this makes sense to me. once you've set a filter, you can change it, but you can't turn it off completely. it's basically a `noFilter()` option we're looking for. though I think `filter(NORMAL);` syntax feels most natural.

**Comment by aatauil** [comment]
I have the same problem `filter(BLUR, 0)` does not seem to be working either strangely enough. Trying to make a cookie clicker game and `filter(BLUR, 4)` blurs everything instead of only the specific object I want it to blur..

**Comment by lmccart** [comment]
Thanks for posting @ricardocanada. We've looked into this and it turns out it's actually quite hard to implement. We are not going to be able to implement this at this time, due to other priorities we have leading up to the [1.0 release](https://github.com/processing/p5.js/milestone/6), perhaps we can revisit in the future.

**Comment by RalenArc** [comment]
I got this workaround if anyone is still facing this issue.
function setup() {
  createCanvas(400, 400);
  background(0);
  rectMode(CENTER);
  fill(255,0,0);
  rect(width/2,height/2,50,50);
  pg = createGraphics(width,height);
  
  push()
    pg.stroke("#00ffff");
    pg.strokeWeight(5);
    blendMode(SCREEN);
    pg.line(0,height/2, width, height/2);
    pg.filter(BLUR, 4);
    image(pg, 0,0);
  pop()
}

Here's what was happening before:
![before](https://user-images.githubusercontent.com/91494500/134964806-dab5ee42-cf9c-4804-ab08-42eb7347e277.png)

And after:
![after](https://user-images.githubusercontent.com/91494500/134964890-ffb70213-cd7c-4a2a-80a3-f5e7aec5d2fe.png)
