### ISSUE TITLE
copy() broken on p5.Graphics for WebGL

### ISSUE THREAD

**Issue by figraham** [processing/p5.js#3932]
#### Nature of issue?

- [X] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [X] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [X] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.9.0
- Web browser and version: Firefox 68.0.1 (64-bit) and Chromium 76.0.3809.87
- Operating System: Linux - Zorin OS 15
- Steps to reproduce this: Run the following code. Or view it in the [web editor](https://editor.p5js.org/figraham/sketches/RH_DbTZij). Will be reproduced when `copy()` function is called through a WebGL p5.Graphics object. Example: `webglGraphics.copy(any valid args will reproduce)`

Following up on @stalgiag suggestion to branch this part of #3900 out in to it's own issue.

`copy()` is undocumented method on p5.Graphics that gets added through [this block of code](https://github.com/processing/p5.js/blob/9748945aa55342944fce9b7244949c59f56eddf3/src/core/p5.Graphics.js#L34).

The original function comes from [here](https://github.com/processing/p5.js/blob/ca92fc457ff836e293916df06964e85f83182368/src/image/pixels.js#L229) and eventually calls a hidden method in Render2D found [here](https://github.com/processing/p5.js/blob/ca92fc457ff836e293916df06964e85f83182368/src/core/p5.Renderer2D.js#L239).

The error that gets thrown is `TypeError: dstImage.drawingContext.drawImage is not a function (sketch: line 26)`. While `dstImage.drawingContext` is defined as a `WebGLRenderingContext` it doesn't have the `drawImage()` function defined. This is where I get lost I can't quite figure out where the `WebGLRenderingContext` is coming from.

This issue might be too far from the current structure of p5.js to get it fixed in a way that makes sense.

```js
let bgGraphics;
let frontGraphics;

function setup() {
  createCanvas(400, 400);
  bgGraphics = createGraphics(width, height, WEBGL);
  frontGraphics = createGraphics(width, height, WEBGL);
}

function draw() {
  
  background(0);
  
  bgGraphics.clear();
  frontGraphics.clear();
  
  bgGraphics.normalMaterial();
  bgGraphics.push();
  bgGraphics.rotateZ(frameCount * 0.01);
  bgGraphics.rotateX(frameCount * 0.01);
  bgGraphics.rotateY(frameCount * 0.01);
  bgGraphics.torus(70, 20);
  bgGraphics.pop();
  //image(bgGraphics, 0, 0);
  
  frontGraphics.copy(bgGraphics, 0, 0, width/2, height/2, 0, 0, width/2, height/2);
  
  frontGraphics.normalMaterial();
  frontGraphics.push();
  frontGraphics.rotateZ(frameCount * 0.01);
  frontGraphics.rotateX(frameCount * 0.01);
  frontGraphics.rotateY(frameCount * 0.01);
  frontGraphics.cone(70, 70);
  frontGraphics.pop();
  image(frontGraphics, 0, 0);
  
}
```
Expected output of above sketch is a cone overlayed on a torus.

**Comment by stalgiag** [comment]
Thank you for the very well written issue @figraham! Until recently I think that most of the WebGL graphics object functionality was pretty broken. The problem here (which likely exists in other places) is that the [drawing context for 2D rendering](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D) has a bunch of functions that [WebGLRenderingContext](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext) does not have. So a different pathway needs to be made that uses a different approach for copy the image data.

I can take a crack at fixing this one if you'd like.

**Comment by figraham** [comment]
Sounds good let me know if there's anything you need from me.
