### ISSUE TITLE
changing fontStyle func to set all font attr and adding fontWeight func to set just font weight attr

### ISSUE THREAD

**Issue by ekeneijeoma** [processing/p5.js#394]
I think fontStyle should set all the font attributes in 1 line like css's font property and while a new function named fontWeight should set the font's weight.

**Comment by lmccart** [comment]
I'm not sure what this means exactly. I don't believe there is a `fontStyle()` function currently?

**Comment by dhowe** [comment]
textStyle() ?

**Comment by lmccart** [comment]
ah that must be it. there are no other comments on this so it seems not crucial enough to warrant deviating from the processing API. @dhowe what do you think?

**Comment by ekeneijeoma** [comment]
I really cant remember what problems I was running into when I thought of it this. I think I meant it'd be good to be able to set the font, size, weight, and style in one call/func like in css with font property

**Comment by dhowe** [comment]
If we can clearly document this, it seems like a useful (additional) option at least for browser/system fonts. @ekeneijeoma maybe you can add a quick sketch to the examples/p5.Font dir to show a few cases of how it might work?

**Comment by brysonian** [comment]
i'm not sure supporting all the variations of the css font property is necessary, perhaps for one-line-ness, chaining would be a more javascripty way to do it? `textFont(foo).textStyle(BOLD).textSize(40)`

Also being able to set the weight with numbers rather than just  BOLD and NORMAL might be useful.

**Comment by dhowe** [comment]
I guess the intent here is something like below?
````
textStyle('italic bold 12px/30px Georgia, serif;');
textStyle('italic 2em "Open Sans", sans-serif;');
textStyle('italic small-caps bolder 16px/3 cursive;');

**Comment by ekeneijeoma** [comment]
I just found myself having to change the font and weight for a project with heavy text layout a lot and thought it'd be great if I could do it in 1 line. @dhowe I was thinking something more like textStyle(FONT,WEIGHT,SIZE) where the weights are numbers with constants (LIGHT, BOLD, and  etc). I think it should only use params that are already in the api.

**Comment by ekeneijeoma** [comment]
Also as far as I know a lot of those params/styles are only used in HTML ex: em, px/px, small-caps, and cursive.

**Comment by lmccart** [comment]
I think this is easy enough to do manually using the underlying canvas api, I suggest we don't further bloat the API as there are already a lot of settings to keep track of. for example:

```javascript
function setup() {
  createCanvas(200, 200);
  drawingContext.font = 'italic small-caps bold 12px arial';
}
```

**Comment by ekeneijeoma** [comment]
That works great for canvas but then what about WebGL? The problem is still
the same.

On Monday, October 12, 2015, Lauren McCarthy <notifications@github.com>
wrote:

> I think this is easy enough to do manually using the underlying canvas
> api, I suggest we don't further bloat the API as there are already a lot of
> settings to keep track of. for example:
>
> function setup() {
>   createCanvas(200, 200);
>   drawingContext.font = 'italic small-caps bold 12px arial';
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/processing/p5.js/issues/394#issuecomment-147490614>.
>


-- 
Ekene Ijeoma
Designer-in-residence @ Orbital <http://orbitalnyc.com/>
@ekeneijeoma <https://twitter.com/ekeneijeoma/>
www.ekeneijeoma.com

Wage Islands recently featured in Vice's Creators Project
<http://bit.ly/wageislands-creatorsproject> and Domus
<http://bit.ly/wageislands-domusweb>.

The Refugee Project currently being exhibited in Designs of the Year 2015
at Design Museum <http://therefugeeproject-designmusuem/> until March 31,
2016 and recently published in MoMA's Design and Violence
<http://bit.ly/therefugeeproject-moma>

**Comment by lmccart** [comment]
in webgl, wouldn't you just use a canvas to create a texture that has text in it?

**Comment by lmccart** [comment]
ah, I didn't realize processing does support 3d text! I don't think p5.js does currently (except for the 2d canvas solution) but I suppose eventually it will. in any case, I'd really prefer to flesh out the existing API and fix type related bugs before adding more possible cases. so unless someone is volunteering to implement this right now, I'd suggest we close it for now and revisit at some future point.

**Comment by dhowe** [comment]
sounds good to me
note: 3d text is another case where path-points for fonts comes in handy...

**Comment by ekeneijeoma** [comment]
@dhowe right! also you can also use divs too which is usually better for labeling.
