### ISSUE TITLE
Set perPixelLighting to true by default

### ISSUE THREAD

**Issue by stalgiag** [processing/p5.js#3940]
#### Nature of issue?

- [ ] Found a bug
- [x] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Feature enhancement details:

Should we set `perPixelLighting` to true by default? Copying a discussion from #3913 here:

> @stalgiag 
> Part of me feels like we should set 'perPixelLighting' to true by default. These lines can feel unnecessarily complicating for the lighting references.
> 
>   @aferriss
> I agree, and I think the per-vertex lighting looks pretty ugly. I also feel like the setAttributes function is a little arcane.
> 
> @stalgiag
> Yeah I am not sure if there are performance hits with per pixel. The setAttributes function is definitely intended to only be used by people that want a non-traditional webgl setup for whatever reason. The most commonly used attribute modification would theoretically be 'antialias' which would likely be changed by smooth() for most users.

Doing this would be straightforward, and I agree that the per-vertex lighting doesn't look great with the default primitives which have relatively few faces.

I guess my only concern would be performance.

**Comment by aferriss** [comment]
There likely is a performance hit, but imo is worth the trade off for better rendering. I think unless you're drawing tons and tons of highly tessellated pieces of geometry you won't notice the performance hit.

**Comment by LisaMabley** [comment]
Would this be a good issue for someone who is new to open source contributing (but an experienced software developer) to tackle? I haven't used p5.js yet and am not yet familiar with the codebase, but I only see perPixelLighting mentioned in a handful of places. Are you hoping that all the places the code calls `setAttributes('perPixelLighting', true);` would be unnecessary because it would just do this by default?

**Comment by aferriss** [comment]
Hi @LisaMabley ! Yes I believe your assumption is correct. We can remove the setAttributes calls in the examples once per pixel lighting is the default.

**Comment by stalgiag** [comment]
Hello @LisaMabley thanks for the interest! This would be a great place to start contributing. As @aferriss already confirmed, the examples can have the `setAttributes('perPixelLighting', true)` calls removed. Doing that along with changing the [default in this function](https://github.com/processing/p5.js/blob/master/src/webgl/p5.RendererGL.js#L176) and [changing the documentation](https://github.com/processing/p5.js/blob/master/src/webgl/p5.RendererGL.js#L308) for `setAttributes()` to reflect the new default value, should do the job quite nicely!

**Comment by stalgiag** [comment]
I just realized that before doing this we should check to see [if this bug still exists](https://github.com/processing/p5.js/issues/3258). Does anyone have access to an iOS12 device that they can check this on? The [bottom example here ](https://p5js.org/reference/#/p5/setAttributes) should suffice for testing. I now realize that this test should also probably be removed if we make 'perPixelLighting' the default? Haha 🤦‍♂

**Comment by aferriss** [comment]
So unfortunately it seems like per-pixel lighting is pretty damaged on both iOS (6s plus iOS 12.2)  and Android (Pixel 2 Android 9). Per-vertex lighting also seemed pretty broken on iOS. The rendering looked the same in all browsers that I tested (Chrome, FF, and Safari on iOS, and Chrome + FF on Android). 

Here's what it looked like on Android with per pixel lighting = true
(sorry I don't have a screen recorder on android)
![Screenshot_20190913-145313](https://user-images.githubusercontent.com/3698659/64992485-d9a2fc80-d888-11e9-8e0f-da0174f16033.png)

Rendering looked correct when android had per pixel lighting = false

And on iOS with per pixel lighting = true
![ppl](https://user-images.githubusercontent.com/3698659/64993088-18858200-d88a-11e9-81b3-2323beafa1c0.gif)

On iOS without per pixel lighting = false
![nppl](https://user-images.githubusercontent.com/3698659/64993102-220eea00-d88a-11e9-9fe8-607ee1a6ec3a.gif)

**Comment by stalgiag** [comment]
Oof just as I feared. Thank you for the thorough testing @aferris. I opened the appropriate issues. I am going to close this for now as it doesn't make sense to default to per-pixel until it is functioning properly on all devices.

**Comment by aferris** [comment]
Hi @stalgiag-

You have the wrong person. It looks like you meant to contact @aferriss.

Thanks!

**Comment by stalgiag** [comment]
Oops sorry about that @aferris 🤦‍♂
