### ISSUE TITLE
Documentation for `setAlpha()`

### ISSUE THREAD

**Issue by mbforbes** [processing/p5.js#3941]
#### Nature of issue?

- [ ] Found a bug
- [x] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [x] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Feature enhancement details:

I was reading the documentation for [`setAlpha()`](https://p5js.org/reference/#/p5.Color/setAlpha) on `p5.Color`. It would be nice if the value range was specified on this page in the documentation. I needed to read through the example to find out.

Thank you for your consideration!

**Comment by AndrasGardos** [comment]
I want to do this! It's between 0 and 255 right?

**Comment by AndrasGardos** [comment]
@mbforbes, it depends on the color mode. For example, if you set `colorMode(HSB,100);` in the setup,  then 100 will be totally opaque.

**Comment by AndrasGardos** [comment]
https://github.com/processing/p5.js/pull/3942

**Comment by mbforbes** [comment]
Thank you for jumping on this!! So sorry for my slow reply. Adding to the other setter methods as well is a great idea. Awesome you already have a PR in review. Thank you @AndrasGardos !

**Comment by lmccart** [comment]
fixed with https://github.com/processing/p5.js/pull/3942
