### ISSUE TITLE
Unexpected behavior when circle() is passed a string for size

### ISSUE THREAD

**Issue by aatishb** [processing/p5.js#3943]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.9.0
- Web browser and version: Firefox 68.0.1 
- Operating System: Max OS X 10.11.6 
- Steps to reproduce this:
I'm not sure if this is a bug or just unexpected behavior. If I pass circle or ellipse a string instead of an integer for radius, I get an unexpected shape. I would expect it to either produce an error, or convert the string to a float and draw a circle.

```
function setup() {
  createCanvas(400, 400);
  circle(200, 200, '50');
}
```

![Screen Shot 2019-08-14 at 10 53 08 PM](https://user-images.githubusercontent.com/1878638/63070049-90593900-bee7-11e9-9958-0f2abbb3fa22.png)

The shape seems to depend on the string, so e.g. this is strange:

```
let x = 0;

function setup() {
  createCanvas(400, 400);
}

function draw() {
  background(220);
  circle(200,200,str(x));
  x += 0.5;
}
```

**Comment by limzykenneth** [comment]
I'll have a look at this today.

**Comment by limzykenneth** [comment]
So as suspected, it is something to do with passing string to the function. When using `+` with a string it will always concatenante the string with what comes after, regardless of type, which often gives super weird result and in this case the offending line is [here](https://github.com/processing/p5.js/blob/master/src/core/p5.Renderer2D.js#L546).

Before describing a fix, do we see this as a bug in the library and the above code should work as expected (ie. draw ellipses still) or is this an error in the user's code (I'm not sure if the argument validation should have been triggered?)

If this is a bug in the library, adding `parseFloat` to the renderer function should fix this. If this is an error on the user side, perhaps the argument validation should have provided a message?

**Comment by stalgiag** [comment]
In my opinion this is an error in the library. I don't think these basic shapes are the best teaching moments for type specific issues.

**Comment by aatishb** [comment]
I think I agree we should consider this a library error, for example if you do `circle('200', '200', 50)` it works fine. (The best case might be issuing a friendly warning that a function is getting a type it isn't expecting, but for now accepting the string input seems to me a good step.)

**Comment by singhvisha** [comment]
Hi, Can I work on this issue?

**Comment by limzykenneth** [comment]
@singhvisha I already have a fix ready, for now I'm just collecting concensus before filing a PR.
