### ISSUE TITLE
New Feature: noLights()

### ISSUE THREAD

**Issue by sanketsingh24** [processing/p5.js#3945]
#### Nature of issue?

- [x] New feature request

#### Most appropriate sub-area of p5.js?

- [x] WebGL

#### New feature details:
As a part of the Summer of Code, I will be implementing `noLights`() along with @aferriss in `src/webgl/light.js`. The function will be-
`noLights()`.

This function will remove all the lights from the sketch for the subsequent buffers. It will affect all the methods called after this method is called.

##### Suggestions-

1. I and @aferriss had decided upon `noLights()` as the name for the function. Other suggestions were `removeLights()`, `resetLights()`. But we are open for better names and suggestions.

**Comment by stalgiag** [comment]
I like `noLights()`. It fits the `fill` and `noFill`, etc style.

Thank you for the work!
