### ISSUE TITLE
Create build/ folder in Github

### ISSUE THREAD

**Issue by HenrySkup** [processing/p5.js#3948]
#### Nature of issue?

- [ ] Found a bug
- [x] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other (specify if possible) : Release Options

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: n/a
- Web browser and version: n/a
- Operating System: n/a
- Steps to reproduce this: n/a

#### Feature enhancement details:

Hi, 

I was hoping that there could be a `build/` folder in the repository which could have the latest build(s).  This would be helpful for times when the CDN link is not available (offline) or not ideal, and would be more "git integrated" than the current download option.  (I see `lib/empty-example/` but the organisation seems to be shifting/changing.)

My use case:

I use the static site generator [Hugo](https://github.com/gohugoio/hugo) -- it is supper fast and has a great core team for development and support.  Recently, I was doing some refactoring to allow for some local development (offline).  Since I have a cloned version of P5 on my machine, I thought that I could pull `p5.min.js` et al. and use those.  And, if i used a symbolic link the website would stay updated with every `git pull` of P5.   

I think that this might be useful for others who need local access to the latest P5 releases and have  basic access to git but are not able/comfortable building from source everytime.

thanks, and, of course, amazing work!

**Comment by lmccart** [comment]
thanks for the suggestion @HenrySkup. we made a decision not to include these files in the repository a while back, you can see the [conversation here](https://github.com/processing/p5.js/issues/774). one of the main reasons was, given the number of beginners using this library, we wanted to reduce confusion by having different unreleased versions of the library floating around. so if someone wants a more up to date build, they can build from source.

**Comment by HenrySkup** [comment]
@lmccart yup, sounds good.  I was hoping that the latest release (rather than any sort of nightly build) would be in a `'dist` folder (or something similar).  I think that this might actually help address some of the concerns that were in the thread (it would offer another, complimentary, way for people to access the latest release; it would parallel many other repos that people would be using; etc.). I think that a good file name might help to smooth out confusion : `/distro` or `/latest-release` or `/stable-release` ?

just a few thoughts, maybe this is better folded into the website? 

(thank you for your mazing work, btw 👍 )
