### ISSUE TITLE
image() in WEBGL affected by the material/lighting conditions

### ISSUE THREAD

**Issue by stalgiag** [processing/p5.js#3966]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

This is more of a question about what is expected. Should calls to `image()` in WEBGL mode use the current lighting and material conditions? Currently if you call `image(img)` it behaves similarly to `texture(img); rect()` which is to say that it takes on the current material and lighting state. [Here is an example that shows this.](https://editor.p5js.org/stalgiag/sketches/weaB1OeDZ)

My instinct is that people will usually expect `image()` to appear as unlit, similar to 2D mode.

**Comment by singhvisha** [comment]
hi @stalgiag , Can I work on this issue?

**Comment by stalgiag** [comment]
Hi @singhvisha yes definitely. But first we should decide what the expected behavior is. What do you think?

**Comment by stalgiag** [comment]
Okay I think that this has been open long enough to draw any likely responses. I definitely agree that `image()` should be unlit.

This could be a good opportunity for contribution from new contributors interested in WebGL.

**Comment by singhvisha** [comment]
@stalgiag @aferriss 
hi , Can I work on this issue?

**Comment by stalgiag** [comment]
@singhvisha sounds good!

**Comment by stalgiag** [comment]
Closed via #4128
