### ISSUE TITLE
Running loadModel once in preload and again later doubles the user interface

### ISSUE THREAD

**Issue by drawliphant** [processing/p5.js#3981]
#### Nature of issue?

- [X] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [X] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 3.5.3
- Web browser and version: Chrome Version 76.0.3809.132 (Official Build) (64-bit)
- Operating System: Windows 10
- Steps to reproduce this:

//I believe this issue has to do with some over optimization of load shape, its as if it reruns the
//whole program using the new shape, The only way around this is to have all shapes loaded in 
//preload
//Please include DOM library

var Shape;

function preload() {
  Shape=loadModel("A.obj");
}

function setup() {
  let canvas=createCanvas(100,100,WEBGL);
  a=createP("I will be doubled when you press the button or by waiting 300 frames");
  b=createButton("Change Model");
  b.mousePressed(ChangeModel);
}

function draw() {
  if(frameCount==300){ Shape=loadModel("B.obj");}
  scale(10);
  model(Shape);
}

function ChangeModel(){
  Shape=loadModel("B.obj");
  
}

**Comment by stalgiag** [comment]
Hi thanks for the issue! I am not sure about this specific behavior (ie the doubling of the button) but I know that we strongly recommend that all `loadX()` methods always be run inside of `preload()`. I am seeing now that this isn't entirely clear in [the reference example](https://p5js.org/reference/#/p5/loadModel) for `loadModel()`. All of the examples show the method called from within `preload()` but there isn't explanation text emphasizing it. That might become the todo for this issue.

In the meantime, what you are looking to do can be accomplished with only a few minor tweaks to your example:
```
var Shape1, Shape2;
var currentShape = 1;

function preload() {
  Shape1=loadModel("A.obj");
  Shape2 = loadModel("B.obj");
}

function setup() {
  let canvas=createCanvas(100,100,WEBGL);
  a=createP("I will be doubled when you press the button or by waiting 300 frames");
  b=createButton("Change Model");
  b.mousePressed(ChangeModel);
}

function draw() {
  if(frameCount==300){ Shape=loadModel("B.obj");}
  scale(10);
  if(currentShape === 1) {
    model(Shape1);
  } else {
    model(Shape2);
  }
}

function ChangeModel(){
  if(currentShape === 1) {
    currentShape = 2;
  } else {
    currentShape = 1;
  }
}
```
