### ISSUE TITLE
reference: table column names 

### ISSUE THREAD

**Issue by kllsamui** [processing/p5.js#3989]
it is possible to load ( like from CSV file ) and show a table content
AND also show the column names, but that is not obvious from the reference.

`  for (var r = 0; r < data.getRowCount(); r++)
    for (var c = 0; c < data.getColumnCount(); c++)
      print("row " + r + " col " + c + " column "+data.columns[c]+" : " + data.getString(r, c));
`
example: https://editor.p5js.org/kll/sketches/Nk3OjSYa2

**Comment by stalgiag** [comment]
Thanks for the issue! In t[he documentation for `loadTable`](https://p5js.org/reference/#/p5/loadTable) it says that a [`p5.Table` is returned](https://p5js.org/reference/#/p5.Table). Is there a specific improvement to the documentation that you had in mind?

**Comment by kllsamui** [comment]
yes, like on page
https://p5js.org/reference/#/p5.Table
are methods ( what you can do with the table )
and also the 
Fields columns: 
line,
but it is not clear that it is a 
table.columns() 
method where you can get the column names...
( funny also JAVA Processing reference data.getColumnTitle(c) not mentioned )
so just add this as a methods line.
`
 columns()        Retrieves a String from the Table's column Names the column may be specified by its ID
`
