### ISSUE TITLE
problem loading dropped csv file into Table

### ISSUE THREAD

**Issue by AndreaGemmani** [processing/p5.js#3991]
#### Nature of issue?

- [ ] Found a bug
- [x] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [x] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Feature enhancement details:

I tried loading a CSV file in preload() using it's path and everything goes as it should, returning a well-done Table.

I'd like to implement a dropzone in which any CSV file could be dropped and transformed in a similar Table to easily modify it, but I'm having troubles: 
1) first of all the dropped file doesn't show a path that I can use, and most important
2) I tried using p5.Table and p5.TableRow with the data loaded but those are returning "bad" datas: every element in column and row arrays are in the form of strings with backslashes:

e.g.: an element that should be   "id"  is now  "\\"id\" 

I'd like to have a simple to use function like loadTable() that takes data in it instead of a path and returns a good Table, because I spent few hours trying to understand how to deal with all Table and TableRows functions but still not getting it.

**Comment by stalgiag** [comment]
Hello!

This doesn't seem to be a problem with the library. Here is an example that [loads a CSV file with drag and drop.](https://editor.p5js.org/stalgiag/sketches/29PKp0sES)

 In the future, it is best to checkout [discourse.processing.org ](https://discourse.processing.org/c/p5js/p5js-questions) for help with coding challenges. In fact, I just searched 'drag csv' over there and [found this page](https://discourse.processing.org/t/drop-csv-file-to-loadtable/11324) which seems to address a similar challenge. The github page is only for feature requests or library bugs.

I am gonna close this issue now for organizational purposes.
