### ISSUE TITLE
directionalLight() broken on iOS

### ISSUE THREAD

**Issue by vanajmoorthy** [processing/p5.js#3996]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [x] Mobile/Tablet (touch devices)
- [ ] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 
- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

**Comment by stalgiag** [comment]
Hi @vanajmoorthy thanks for the issue!

Could you give some more info about when this is broken ie:
- version of iOS
- iOS hardware
- browser
- version of p5

Thanks!

**Comment by vanajmoorthy** [comment]
So I've encountered the issue specifically on iOS 12.4, on an iPhone 7+,
the browser is Safari and I'm using the latest version of p5 through a CDN.
The issue still exists on iOS 11.1.2 on an iPhone 6+, so it seems pretty
pervasive.

**Comment by stalgiag** [comment]
Great thanks for the speedy reply and info!

When you get a chance would you be able to test on either of those phones with a different browser (ie Chrome or Firefox)? I want to narrow down whether it is the browser or the device/OS.

**Comment by vanajmoorthy** [comment]
Oh yeah fair point, I'll test and get back to you asap.

**Comment by vanajmoorthy** [comment]
Yeah so it's broken on Chrome and Firefox as well

**Comment by vanajmoorthy** [comment]
It might be a general iOS issue since chrome and Firefox both leverage
safari on iOS

**Comment by vanajmoorthy** [comment]
They all use WebKit, that is

**Comment by stalgiag** [comment]
Thanks for checking!

And one last question, are you testing this with the [directionalLight() reference example](https://p5js.org/reference/#/p5/directionalLight) or with other code? If the answer is the latter can you confirm that this happen in that reference example. I want to know what the simplest way to reproduce is.

**Comment by vanajmoorthy** [comment]
It's the example code with this resize function added.

function setup() {
createCanvas(windowWidth, windowHeight, WEBGL);
}
function draw() {
background(0);
let dirX = (mouseX / width - 0.5) * 2;
let dirY = (mouseY / height - 0.5) * 2;
directionalLight(255, 255, 255, -dirX, -dirY, -1);
noStroke();
sphere(160, 50, 50);
}
function windowResized() {
resizeCanvas(windowWidth, windowHeight);
}

**Comment by vanajmoorthy** [comment]
This doesn't seem to be happening in the reference though.

**Comment by stalgiag** [comment]
Ah so this is likely related to `resizeCanvas()` then. Thank you!

**Comment by vanajmoorthy** [comment]
Possibly, thank you for checking it out!

**Comment by vanajmoorthy** [comment]
I tried removing the resize canvas but it still isn't rendering on iPhones.

You can see my code here.
https://github.com/vanajmoorthy/vanajmoorthy.github.io/blob/master/JS/moon.js

You can check out the glitchy website here.
vanajmoorthy.com

**Comment by vanajmoorthy** [comment]
So I tested it after removing the resizeCanvas(), and it still doesn't work. I don't think it's a resizeCanvas() issue.

**Comment by stalgiag** [comment]
Thanks @vanajmoorthy . You said that [the reference ](https://p5js.org/reference/#/p5/directionalLight)wasn't having this issue. Is this still the case, everything displays fine in the sketch on that page?

**Comment by vanajmoorthy** [comment]
Yes, the reference sketch displays fine.

**Comment by stalgiag** [comment]
So then the only meaningful differences between your sketch and the reference example are:

- the size of the sphere
- the detailX of the sphere
- the detailY of the sphere
- the width and height of the canvas

Let me know if you are able to figure out which one of those 4 changes up there is what breaks the rendering. It is possible it is another factor.

Thanks for the help by the way. I really need to get an iPhone :-P

**Comment by vanajmoorthy** [comment]
Pretty much yeah, there don't seem to be any other differences, I tried
reducing the detail but that still didn't work.

Ahaha I don't have an iPhone either, I'm testing on a friend's.

**Comment by stalgiag** [comment]
I am going to close this as a subset of issue #4023 follow there for fixes. I should have consistent access to an iPhone at some point this month.
