### ISSUE TITLE
finish file I/O implementation

### ISSUE THREAD

**Issue by lmccart** [processing/p5.js#40]
Updated after work by @therewasaguy:

XML is the one thing that could really benefit from some more work. Currently, we can load it, but it's hard to do anything with it because there is not yet an XML object like there is in Processing. An XML object could be really useful in tandem with p5.dom. An XML to JSON converter could also be useful even though that wouldn't always translate. I'd like to work on XML in theory, but in reality I'm not sure when I will get a chance, so if anybody is inspired they should go for it (and maybe open up a new ticket?).

More stuff that isn't supported and might be worth adding:
- [ ] loadBytes() / saveBytes() --> actually spent a decent amount of time trying to figure this one out. Maybe [this](http://stackoverflow.com/questions/327685/is-there-a-way-to-read-binary-data-in-javascript/4815486#4815486) will help.
- [ ] beginRecord() / endRecord() --> save a PDF of the sketch
- [ ] beginRaw() / endRaw() --> could create a vector?

**Comment by DarkPrince304** [comment]
@lmccart : Could you tell me what's left for the full file I/O implementation to be complete for p5.js?

**Comment by lmccart** [comment]
I think @therewasaguy has outlined what's left here: https://github.com/processing/p5.js/issues/40#issuecomment-54927028.
One key missing item is a p5.XML object that could be used with loadXML() based on the [processing spec](https://processing.org/reference/XML.html).

**Comment by DarkPrince304** [comment]
Cool! @lmccart Also can you give me a little picture of where and when to use loadXML() ? As in, which conditions would require the use of loadXML() ? 

I am asking this so that I could get a better picture and then start work on this accordingly! :)

**Comment by lmccart** [comment]
loadXML() could be used just like loadJSON() or loadStrings(), either in preload() or setup() or on some event (like a mouse press). here is a test file that you can load with p5.js, but the resulting data object is a little complicated to parse with native JS calls.
https://github.com/processing/p5.js/wiki/Loading-external-files:-AJAX,-XML,-JSON#xml

there are also some external APIs that return XML rather than JSON, for example the NYC MTA subway API:
http://web.mta.info/status/serviceStatus.txt
http://web.mta.info/developers/

does that answer your question, or am I misunderstanding?

**Comment by DarkPrince304** [comment]
Yeah, thanks a lot! I'd like to start looking into it!

**Comment by lmccart** [comment]
wonderful!

**Comment by DarkPrince304** [comment]
Sure! Has any progress been made on this? I checked out `file.js` and there was some stuff inside the `loadXML()` function. Should I carry that forward or start from the scratch on my own?

**Comment by lmccart** [comment]
I think it makes sense to carry on with this, the todo here is probably to add another object called p5.XML that gets returned from loadXML(), similar to how loadTable() returns a p5.Table object.

**Comment by DarkPrince304** [comment]
How would you like the structure of the XML to be parsed? If I am not wrong is this a place where we would have to use Data Structures like B-Tree or Hash Map to reconstruct a perfect DOM behaviour for the resulting parsed XML?

**Comment by DarkPrince304** [comment]
@lmccart will the p5.XML object be having all the methods associated with it as in the case of its processing counterpart? Also for methods requiring searching what do you think of the solution that would be apt for searching an XML node inside another ones?

**Comment by DarkPrince304** [comment]
Hello @lmccart,

If the XML is like this 
`
 <?xml version="1.0"?>
 <mammals>
   <animal id="0" species="Capra hircus">Goat</animal>
   <animal id="1" species="Panthera pardus">Leopard</animal>
   <animal id="2" species="Equus zebra">Zebra</animal>
 </mammals>
`
and the `getContent('mammals')` method is called should null be returned in such a case or a complete String like `" <animal id="0" species="Capra hircus">Goat</animal><animal id="1" species="Panthera pardus">Leopard</animal><animal id="2" species="Equus zebra">Zebra</animal>"` ?

**Comment by lmccart** [comment]
1. it should match the behavior of processing wherever it makes sense. so if you run this in processing, you get something like:
```javascript
 println(xml.getContent("mammals"));
// Goat
// Leopard
// Zebra
```

so maybe it should return an array of these three items? 

2. I think it should return null, matching the behavior of processing.
3. The output from processing is:
```javascript
<animal id="0" species="Capra hircus">Goat</animal> <animal id="1" species="Panthera pardus">Leopard</animal> <animal id="2" species="Equus zebra">Zebra</animal>
```
so perhaps it should return the raw elements or maybe an array of p5.XMLNode objects?

**Comment by DarkPrince304** [comment]
Woops! Sorry, about the 3rd question I meant what if xml = the animal node and then we call `xml.getChildern()`. What will be the children of animal?

**Comment by lmccart** [comment]
hm, what is the output for processing for this? i would try to match that conceptually as best as possible, unless it makes sense to deviate for some reason. maybe it would be useful to write out a spec of this object and methods first, and we could review to make sure it all fits together as expected, before you implement?

**Comment by DarkPrince304** [comment]
I will try it out on processing soon and let you know. But I think it should be null value if xml  = animal node[0].

By the way I have done this in my PR #1255 using the class p5.XML and defined its methods and attributes too. So the loadXML() works fine except for just one thing on which I would like some help, which I have mentioned in the PR. You can check it out whenever you want :)

**Comment by lmccart** [comment]
oops sorry missed that! will take a look next chance i get.

**Comment by DarkPrince304** [comment]
@lmccart Is this finished? Or is there anythiing left with file I/O ?

**Comment by lmccart** [comment]
@DarkPrince304 the three checkboxes in the first post still need looking into.

**Comment by DarkPrince304** [comment]
@lmccart What do you think should be a good approach to saving the sketch as a PDF? If memory serves me I guess someone did a similar GSoC project to save data as PDF?

**Comment by lmccart** [comment]
since we haven't heard much demand for the three remaining unimplemented pieces, I suggest we close this issue and focus on issues that are higher priority.

**Comment by bmoren** [comment]
I agree with the bytes and pdf being pushed to the back, I've had a lot of student desire for svg/vector output to be native so they can more easily traverse p5js & css tasks & get vector information out for going to print & laser/plotter/cnc fabrication. I do think likely the svg should be an external library. But from our previous conversation, It seems a question of how possible it is given the current render setup. I also do believe that in order to get svg/vector implemented it would be super helpful to have someone with experience in this area.

**Comment by lmccart** [comment]
yes, definitely. the svg issue is still open: https://github.com/processing/p5.js/issues/458.
though realistically, I just don't have the bandwidth to take it on anytime soon, but would welcome anyone interested in tackling it.
