### ISSUE TITLE
Grunt occasionally inserts endless newlines during error

### ISSUE THREAD

**Issue by stalgiag** [processing/p5.js#4000]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Development/Testing

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

When running `npm run grunt` if a test fails during the documentation testing section (I think only during this and not the unit tests) that causes grunt to spam the terminal with infinite newlines. On my computer this leads to crashing if I don't `CRTL+C` in time, but even if I do this it is then very hard to track down the message for the error since it is often 10k+ lines away by time I catch it.

I have been experiencing this for a couple of weeks, I didn't report it because I thought it was specific to my environment, but now I see that it is happening on Travis as well. [Here is an **unstable** link to an example](https://travis-ci.org/processing/p5.js/jobs/582763763).

- Operating System: Windows 10, Ubuntu 16.0.4(Travis)
- Steps to reproduce this:

Run `npm run grunt` with code that will cause an error during the documentation testing section.

**Comment by outofambit** [comment]
@stalgiag i noticed this last week. :( will do a little diagnostics to see if i can get an idea of why its doing that.
