### ISSUE TITLE
canvas gets flipped vertically after changing browser tabs

### ISSUE THREAD

**Issue by semvis123** [processing/p5.js#4001]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

bug only works if the p5 renderer is not  WebGL.

- p5.js version: bug starting from 0.2.1 but is still present in newest release.
- Web browser and version: Edge Dev beta chromium 78.0.262.0 (Official build) dev (64-bit) (bug not found on Google Chrome 76.0.3809.132 (Official Build) (64-bit) (cohort: Stable))
- Operating System: Windows 10
- Steps to reproduce this:
  open every p5.js example sketch without WebGL rendering, move to other tab, go back to original tab, notice the whole canvas flipped vertically.
  https://p5js.org/examples/hello-p5-simple-shapes.html this page is a great example to demonstrate the bug.

**Comment by stalgiag** [comment]
Hello @semvis123 thanks for the issue! This is an odd one, but is definitely unrelated to p5. I think they just have a major bug with canvas rendering in that beta version of Edge. I downloaded the Dev Chromium 78 version out of curiosity and the same bug occurs with any thing that uses the underlying Canvas API. Here is an [example on MDN that also flips with tab switching](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Drawing_text).

[Here is a bug report on the Microsoft Edge issue tracker](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/23398232/). I am going to close as this is unrelated to p5 development.
