### ISSUE TITLE
point();

### ISSUE THREAD

**Issue by jleelove** [processing/p5.js#4012]
point doesn't seem to be working. even in your example on the reference page

**Comment by limzykenneth** [comment]
Hi @jleelove, `point()` is working for me, it is quite subtle as it is only drawing 4 tiny pixels on the canvas. If it still isn't working for you, can you fill out the initial issue template? Basically we would like to know what version of p5 are you using, what is your OS and version, what is your browser and version to start with.

**Comment by aferriss** [comment]
@jleelove  Also a call to `strokeWeight(10);` might make the point be a more visible. Otherwise as @limzykenneth notes, they're really teensy.

**Comment by stalgiag** [comment]
Good point @aferris. Maybe worth adding a second example that uses `strokeWeight(10)` before drawing point(s) to show that they are affected by the current stroke weight. This isn't clear in the documentation currently.

**Comment by stalgiag** [comment]
Closed with the above PR which is an update to documentation that adds a second example to `point()` that is easier to see. I am assuming that the difficulty was with seeing the points as there was no follow-up with a different kind of error. If this was an incorrect assumption and there is a different kind of error here, feel free to post an example with your browser version and I will reopen the issue.

Thanks for pointing out how difficult it is to see the `point()` example!
