### ISSUE TITLE
Problem loading files 

### ISSUE THREAD

**Issue by AndreaGemmani** [processing/p5.js#4014]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [x] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: last one (v0.9.0 tried both statically and dynamically with cloudflare)and I think even others 
- Web browser and version: both Safari 11.1.1 and Chrome 77.0.3865.75
- Operating System: macOS High Sierra 10.13.5
- Steps to reproduce this:
Both loadTable() and loadJSON() are giving me problems in last few days (I issued a problem that I thought was connected only with loading .csv files but now I think it's something bigger):
I made a simple Object and then converted it to a JSON and saved file like this

`let tempJSON = JSON.stringify(self.arrLists[self.actInd]);`
`saveJSON(tempJSON, 'list1');`

and it returns and saves a good JSON file like: 

`"{\"nome\":\"Spesa1\",\"arrProdotti\":[]}"`

Now I try reloading it in calling 

`loadJSON('list1.json')`

but it will get transformed into

`"{\"0\":\"{\",\"1\":\"\\\"\",\"2\":\"n\",\"3\":\"o\",\"4\":\"m\",\"5\":\"e\",\"6\":\"\\\"\",\"7\":\":\",\"8\":\"\\\"\",\"9\":\"S\",\"10\":\"p\",\"11\":\"e\",\"12\":\"s\",\"13\":\"a\",\"14\":\"1\",\"15\":\"\\\"\",\"16\":\",\",\"17\":\"\\\"\",\"18\":\"a\",\"19\":\"r\",\"20\":\"r\",\"21\":\"P\",\"22\":\"r\",\"23\":\"o\",\"24\":\"d\",\"25\":\"o\",\"26\":\"t\",\"27\":\"t\",\"28\":\"i\",\"29\":\"\\\"\",\"30\":\":\",\"31\":\"[\",\"32\":\"]\",\"33\":\"}\"}"`

so that every character of the JSON file is now an attribute (?) of the object loaded 

For my little knowledge of the argument I think that the problem could have something to do with the interpreting loading function that misleads some \ or "

(Almost same problem when trying to load .csv files in loadTable(): data get messed up in a similar way where every item like `"id"` becomes `"\"id"` )

Oh and I am getting no errors in browsers' debuggers

**Comment by limzykenneth** [comment]
Is the json file that is saved out look exactly like this?
```
"{\"nome\":\"Spesa1\",\"arrProdotti\":[]}"
```

If so then it isn't really properly formatted JSON. The JSON interpreter would have interpreted that as a string which explains the result you got from loadJSON. The JSON you are probably looking for should look more this so:

```
{
  "nome":"Spesa1",
  "arrProdotti":[]
}
```

**Comment by AndreaGemmani** [comment]
Ok, then I should just **not `JSON.stringify()`my object before saving it with `saveJSON()`** and everything goes right, I am again sorry for the time loss, I thought that the problem I had with loadTable() and .csv files was connected but now I'm not totally sure, I'll investigate a bit more, thanks

**Comment by limzykenneth** [comment]
No worries, happy to help. `saveJSON` already does `JSON.stringify` for you so that's why there is no need to stringify it first. I'm going to close this for now, if you have an issue with `loadTable` still, feel free to reopen.
