### ISSUE TITLE
Uncaught TypeError: Cannot read property 'prototype' of undefined     at p5.dom.js:77     at p5.dom.js:34     at p5.dom.js:35

### ISSUE THREAD

**Issue by kevinkarlos** [processing/p5.js#4019]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [x] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 
- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

**Comment by lmccart** [comment]
can you please provide a code snippet you are working with that results in this error?
