### ISSUE TITLE
Per-pixel lighting broken in Android 8+

### ISSUE THREAD

**Issue by stalgiag** [processing/p5.js#4024]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [x] Mobile/Tablet (touch devices)
- [ ] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version:  0.9.0
- Web browser and version:  latest Firefox and Chrome
- Operating System:  Android 9.0 Pixel 2
- Steps to reproduce this:

quoting from @aferriss 's [comment](https://github.com/processing/p5.js/issues/3940#issuecomment-531956361) in #3940 

> I was using the reference example but pasted into the editor (0.9.0), but probably worth testing with master as well:
> https://editor.p5js.org/aferriss/sketches/0h-Eh_sPF
> 
> Here's what it looked like on Android with per pixel lighting = true
> (sorry I don't have a screen recorder on android)
> ![Screenshot_20190913-145313](https://user-images.githubusercontent.com/3698659/64992485-d9a2fc80-d888-11e9-8e0f-da0174f16033.png)

Rendering with per-vertex has expected behavior.

**Comment by stalgiag** [comment]
Able to reproduce with Chrome 77.0.3865 and Android 8.0.0

**Comment by stalgiag** [comment]
`precision highp float;` at the top of [shaders/phong.frag](https://github.com/processing/p5.js/blob/master/src/webgl/shaders/phong.frag) gives the expected results with Android 8.0.0 but I don't understand why.

**Comment by aferriss** [comment]
I was wondering if this was a precision issue. I think we could safely use `highp` without losing much performance.
