### ISSUE TITLE
Uncaught ReferenceError: getItem is not defined

### ISSUE THREAD

**Issue by Ufkufk** [processing/p5.js#4025]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [x] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

I'm using processing 3.5.3 ide for p5 js, and the getItem and storeItem functions don't work. However, when I run the same code in the p5 js editor, no error occurs. I checked the libraries and there was no problem.

- p5.js version: 
- Web browser and version: 
- Operating System: Windows 
- Steps to reproduce this: 
```
let myColor;
function setup() {
   createCanvas(100, 100);
   myColor = getItem('myColor');
 }
function draw() {
   if (myColor !== null) {
     background(myColor);
   }
 }
function mousePressed() {
   myColor = color(random(255), random(255), random(255));
   storeItem('myColor', myColor);
 }
```

Even this sample  code gives the same error. https://p5js.org/reference/#/p5/getItem

**Comment by stalgiag** [comment]
Hi @Ufkufk thanks for filing the issue!

Which browser are you viewing your sketch and the error message in? 

Also, which version of p5 are you using? Those functions were added fairly recently so you would need to be running 0.9.0.

**Comment by Ufkufk** [comment]
@stalgiag Oh i'm so sorry. I've checked it out and found that i was using 0.7.2.
