### ISSUE TITLE
addCue handler does not fire

### ISSUE THREAD

**Issue by jackwlee01** [processing/p5.js#4026]
#3438 ## Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [x] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other (Sound)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.9.0
- Web browser and version: 77.0.3865.65 (Official Build) beta (64-bit)
- Operating System: OSX 10.14.6
- Steps to reproduce this:

The example on the website is also not changing background color or text;:
https://p5js.org/reference/#/p5.SoundFile/addCue

Here is a code snippet. Note that onCue does not fire.
```
var s;

function preload() {
    s = loadSound("./my-wav.wav");
}

function onCue(){
    console.log("On Cue");
}

function setup(){
    console.log("Setup");    
}

function onTouch(e){
    console.log("On touch")
    s.play();
    s.addCue(1.5, onCue);
}

document.body.addEventListener("mousedown", onTouch)

function draw(){
}
```

**Comment by stalgiag** [comment]
Hi @jackwlee01 thanks for the issue! Development for the sound library is tracked in [this repo.](https://github.com/processing/p5.js-sound/) I think [this issue may already](https://github.com/processing/p5.js-sound/issues/371) be tracking this problem. I am going to close this here. I would subscribe to that issue to track progress on fixing the bug. In the meantime, you might be able to accomplish a (less then optimal) workaround by checking `soundFile.currentTime()`.
