### ISSUE TITLE
Instruct new contributors to use npm ci instead of npm install?

### ISSUE THREAD

**Issue by stalgiag** [processing/p5.js#4028]
What do people think? Should we change `npm install` to `npm ci` in the [developer docs](https://github.com/processing/p5.js/tree/master/developer_docs)? 

Pros:
This would help new contributors avoid editing the `package-lock.json`.

Cons:
The command is a little more cryptic. `install` has a more clear meaning.
Too soon? The command was introduced to npm in March 2018.

**Comment by lmccart** [comment]
makes sense to me. by the time you're typing `npm` i think it's already pretty cryptic. so if this one is a little easier to use i'd be up for the switch.

**Comment by limzykenneth** [comment]
I think so too, `npm ci` would be more consistent and we can more easily split up changes to the source code and changes to the dependencies without needing to ask someone to modify their PR.

**Comment by stalgiag** [comment]
Thank you for the input!
