### ISSUE TITLE
Use all-contributors-bot 

### ISSUE THREAD

**Issue by stalgiag** [processing/p5.js#4029]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [x] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Documentation/Development

### New feature details:

What do people think about using the [all-contributors-bot](https://allcontributors.org/docs/en/bot/overview). I think it would make it easier to add people. [Here is an example of me testing it out](https://github.com/stalgiag/p5.xr/pull/55#issuecomment-532619479) on a repository of my own.

**Comment by lmccart** [comment]
love it

**Comment by stalgiag** [comment]
Put in a request to install on the repo :-)

**Comment by lmccart** [comment]
installed!
