### ISSUE TITLE
the round function

### ISSUE THREAD

**Issue by mujehoxe** [processing/p5.js#4038]
#### Nature of issue?

- [ ] Found a bug
- [ x] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [x ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 
- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

#### Feature enhancement details:
the round function can take only one pramater n and then round it .eg : round(2.156) => 2.
i would suggest adding an optional paramater that represents the number of decimal places.eg : round(2.156, 2)  =>  2.2 
i know that there is a simple work around by multiplying the number by 10^2 and round it then dividing the result by 10^2   but just for making the function more general.

**Comment by CrypticGuy** [comment]
@outofambit 
Hi, Can I work on this. 
It would be a nice enhancement to the function. We can add a new parameter to the existing function and just have a default argument, which rounds off to the integer value.

**Comment by lmccart** [comment]
@CrypticGuy sounds good, we would welcome your work on this one

**Comment by lmccart** [comment]
resolved with https://github.com/processing/p5.js/pull/4043
