### ISSUE TITLE
movedX and movedY are not defined

### ISSUE THREAD

**Issue by Ahmed-Hasan** [processing/p5.js#4041]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [x] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: using the p5.js web editor / p5.js v0.9.0 July 01, 2019 
- Web browser and version: Chrome  Version 77.0.3865.90
- Operating System: Windows 10 
- Steps to reproduce this: the code in the reference produces this error "Uncaught ReferenceError: movedY is not defined"

let x = 50;
 function setup() {
   rectMode(CENTER);
 }
function draw() {
   if (x > 48) {
     x -= 2;
   } else if (x < 48) {
     x += 2;
   }
   x += floor(movedX / 5);
   background(237, 34, 93);
   fill(0);
   rect(x, 50, 50, 50);
 }

**Comment by lmccart** [comment]
@Ahmed-Hasan `movedX/Y` are not properties of p5.js, so you will need to create them as variable yourself if you would like to make use of them. for more help with this, you can post your question on our [forum](https://discourse.processing.org)

**Comment by hellonearthis** [comment]
Sounds like you might need to use the p5 library https://github.com/bohnacker/p5js-screenPosition  to help with the screen positioning.

**Comment by Ahmed-Hasan** [comment]
> @Ahmed-Hasan `movedX/Y` are not properties of p5.js, so you will need to create them as variable yourself if you would like to make use of them. for more help with this, you can post your question on our [forum](https://discourse.processing.org)

I am sorry, I am still learning. But why is it listed in the reference page under Events/Mouse if it is not a property ? isn't that page the documentation for the library ?

**Comment by lmccart** [comment]
@Ahmed-Hasan ah, I'm sorry, you're correct! There's a problem right now where the reference is slightly ahead of the coming release of the library. The `movedX/Y` variables will be included and fixed in the next release, which should be out in the next week or two. Thanks for your patience.
