### ISSUE TITLE
filter() should log warning in WEBGL

### ISSUE THREAD

**Issue by stalgiag** [processing/p5.js#4046]
`filter()` does not work in WEBGL mode. It currently throws a cryptic error:
`Uncaught TypeError: Cannot read property 'getImageData' of null`

 I could modify `filter()` to use `gl.readPixels` and then create a plane geometry that covers the view that has the filter-modified pixels, but this goes against WEBGL logic. These filters can be achieved relatively easily with custom shaders.

I recommend adding a `RendererGL.prototype.filter()` that logs a warning that `filter()` is not supported in WEBGL mode and suggests using custom shaders. Additionally a link to @aferriss 's [shader examples](https://github.com/aferriss/p5jsShaderExamples) could be logged or added to documentation.

**Comment by singhvisha** [comment]
Hi, @stalgiag,Can I work on this?

**Comment by stalgiag** [comment]
Definitely @singhvisha! Let me know if you have any questions or need any help.

**Comment by stalgiag** [comment]
Closed by #4084
