### ISSUE TITLE
strokeJoin() should log warning in WEBGL mode

### ISSUE THREAD

**Issue by stalgiag** [processing/p5.js#4047]
Currently when using `strokeJoin()` in WEBGL mode an error occurs and a cryptic message is logged:
`Uncaught TypeError: this._renderer.strokeJoin is not a function`

`RendererGL.prototype.strokeJoin()` should be added and it should log a message that says something like 'Sorry, strokeJoin() is not currently implemented in WEBGL mode.'

Note: Eventually both `strokeJoin()` and `strokeCap()` could be added for WEBGL mode, but this is not a priority.

**Comment by hydrosquall** [comment]
Hi, I'd like to take a pass at this :).

**Comment by stalgiag** [comment]
closed via #4059 🎊
