### ISSUE TITLE
hypot and dist improvements and weird performance results

### ISSUE THREAD

**Issue by J-888** [processing/p5.js#4050]
#### Nature of issue?

- [ ] Found a bug
- [X] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [X] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [X] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- Web browser and version: Google Chrome 77.0.3865.90
- JavaScript version: V8 7.7.299.11
- Operating System: Windows 10 OS Version 1903 (Build 18362.356)

#### Feature enhancement details:
I was working on making the dist function faster in 2 ways. First, many graphic engines have a square dist function to make z sorting (or any distance sorting) way faster, so Im currently working on it to p5.js. The second one would be improving the current hypot function. It checks if the native implementation is available, and if so, uses it (https://github.com/processing/p5.js/blob/master/src/math/calculation.js#L794), and if not, uses the V8 implementation (https://github.com/v8/v8/blob/8cd3cf297287e581a49e487067f5cbd991b27123/src/js/math.js#L217), which I'm currently working on improving by implementing fast paths for 2 and 3 args (the most common in p5.js).

When testing the performance of a few functions (on https://jsperf.com/distance-comparison), I realized that for some reason Math.hypot works way faster than p5.js hypot, when (in this case) it''s just calling Math.hypot. Any idea why?

```js
if (typeof Math.hypot === 'function') {
  return Math.hypot.apply(null, arguments);
}
```

I'm also wondering how could (according to my tests) p5.js hypot run faster when Math.hypot is not available. This doesn't make much sense, especially with the previous weird result.

![jsperf results](https://i.imgur.com/VzjX7p3.png)

Any idea what I could be wrong? jsperf isn't flawless, but this doesn't make any sense to me. I plan on using the repo built in performance tester to double check, but I have never used it do it might take a while.

Thanks in advance!

**Comment by J-888** [comment]
Results after timing all functions on Chrome console, it makes way more sense now:

| Method | Function | Time |
| ------------- | ------------- | -------------:|
| p5.js hypot | hypotP5js  | 1343  |
| p5.js hypot manual | hypotP5jsManual | 1126 |
| squared p5.js hypot manual | squaredhypotP5jsManual | 1193 |
| 2D hypot (**) | hypot2Exp | 704 |
| squared 2D hypot (**) | squaredhypot2Exp | 694  |
| 2D hypot (pow) | hypot2Pow | 393  |
| squared 2D hypot (pow) | squaredhypot2Pow | 503 |
| 2D hypot (mult) | hypot2Mult  | 522  |
| squared 2D hypot (mult) | squaredhypot2Mult  | 330 |
| Math.hypot | Math.hypot | 1303 |

!(Execution time chart)[https://i.imgur.com/H5tvHJP.png]

**Comment by limzykenneth** [comment]
As mentioned on the PR, do have a look at #3337
