### ISSUE TITLE
push()/pop() documentation - missing functions

### ISSUE THREAD

**Issue by catarak** [processing/p5.js#4052]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

N/A

#### Details about the bug: 

- p5.js version: 0.9.0
- Web browser and version:  N/A
- Operating System:  N/A
- Steps to reproduce this:

Hi! I noticed on the documentation for [push()](https://p5js.org/reference/#/p5/push) that it lists a few functions that change the style/transformation of a p5 application:

> push() stores information related to the current transformation state and style settings controlled by the following functions: fill(), stroke(), tint(), strokeWeight(), strokeCap(), strokeJoin(), imageMode(), rectMode(), ellipseMode(), colorMode(), textAlign(), textFont(), textSize(), textLeading().

However, it seems like this is missing a bunch of functions. Ones that come to mind are `translate()`, `rotate()`, and `scale()`, and there are probably other ones that aren't coming to mind at the moment. Maybe these functions should be added to that list?

**Comment by catarak** [comment]
Looking through the p5.js reference, other functions that are missing:
- `noFill()`
- `noStroke()`
- `smooth()`/`noSmooth()`
- `bezierDetail()` and `curveDetail()`
- everything under "Transform": `applyMatrix()`, `resetMatrix()`, `rotate()`, `rotateX()`, `rotateY()`, `rotateZ()`, `scale()`, `shearX()`, `shearY()`,`translate()`
- `noTint()`
- `noiseDetail()` and `noiseSeed()` (...are these affected by push()/pop()?)
- `randomSeed()` (...again, is this affected? i don't even know)
- `angleMode()`

I don't feel confident that this is everything (this doesn't include any webgl mode stuff), but I figured it would be useful to at least try to compile a complete list.

**Comment by lmccart** [comment]
thanks @catarak this is super helpful, will add!

**Comment by aferriss** [comment]
I think most of the work @sanketsingh24 and I did this summer for GSOC is also missing from the `push()` docs. Off the top of my head that would be:

- `emissiveMaterial()`
- `specularColor()`
- `frustum()`
- `spotLight()`
- `falloff()`

**Comment by imrishabh18** [comment]
Hi guys, I am a beginner can i work on this issue ?

**Comment by outofambit** [comment]
@imrishabh18 yes feel free! i'd recommend just doing docs for one or two functions in your first PR. thank you!

**Comment by imrishabh18** [comment]
@outofambit I have updated the documentation of couple of functions from the structure.js file but when running in the local development setup.The updated text is not showing up,

**Comment by limzykenneth** [comment]
@imrishabh18 Do you mean the local preview of the documentation in p5.js repo? If so can you file the PR anyway and I'll check if that is working as inteded. Thanks.

**Comment by imrishabh18** [comment]
@limzykenneth Yes, okay i am filing the PR.

**Comment by imrishabh18** [comment]
@limzykenneth I figured out why the local preview of documentation was not happening.But the issue now is that as i was filing a PR.On comparison i am not getting any difference in changes with the master branch of processing/p5.js.

**Comment by J-888** [comment]
Currently working on it (WIP)

- [x] `noFill()`
- [x] `noStroke()`
- [x] `translate()`
- [x] `rotate()`
- [x] `scale()`
- [ ] `smooth()'/'noSmooth()`: can't manage to preview the difference properly
- [ ] `bezierDetail()`: can't manage to get it working with push() and pop()
- [ ] `curveDetail()`: can't manage to get it working with push() and pop()

- [ ] `applyMatrix()`
- [ ] `resetMatrix()`
- [ ] `rotateX()`
- [ ] `rotateY()`
- [ ] `rotateZ()`
- [ ] `shearX()`
- [ ] `shearY()`
- [ ] `noTint()`
- [ ] `noiseDetail()`
- [ ] `noiseSeed()`
- [ ] `randomSeed()`
- [ ] `emissiveMaterial()`
- [ ] `specularColor()`
- [ ] `frustum()`
- [ ] `spotLight()`
- [ ] `falloff()`

**Comment by Prasad-Chaudhari** [comment]
This issue has been merged. you can close it right ?

**Comment by stalgiag** [comment]
@Prasad-Chaudhari yes thank you!

**Comment by fguillen** [comment]
I was a bit headache to see that it was not working for `angleMode()`, coming here just to say it.

P5 version: v1.3.1 March 28, 2021
