### ISSUE TITLE
[documentation] Add a Pull Request Guidelines Template

### ISSUE THREAD

**Issue by hydrosquall** [processing/p5.js#4060]
Hi there! 

I was wondering if there was any interest in having a `PULL_REQUEST_TEMPLATE.md` file for p5.js, a template that auto populates the "pull request" body for every new pull request. I did notice we already have some [welcome messages]( https://github.com/processing/p5.js/blob/master/.github/config.yml) for first time contributors as well, so I wasn't sure if we still wanted this for subsequent activity too.

Here are some prior issues which made me think this could be useful.

- https://github.com/processing/p5.js/issues/107
- https://github.com/processing/p5.js/issues/1011

This could be a good issue for a first-time hacktoberfest participant to pick up: here's a reference PR for how something similar was done 2 years ago for a Python project: https://github.com/sendgrid/open-source-library-data-collector/pull/65 . 

It imagine it would probably be based on a combination of what's in `CONTRIBUTING.md`, and maybe a subset of checklist items from the main `developer_docs` folder.

**Comment by limzykenneth** [comment]
Yes, that would be a good idea for something to have. I know the p5.js web editor repo already has a PR template and it would be nice to have one here as well.

**Comment by outofambit** [comment]
@hydrosquall i agree with @limzykenneth that would be great!

**Comment by lmccart** [comment]
love it!

**Comment by hydrosquall** [comment]
Excellent! Perhaps we could tag this issue with `hacktoberfest`, `area:documentation`, and `level:beginner` to help people find the project?

**Comment by thumbsupep** [comment]
I can address this issue!

**Comment by lmccart** [comment]
thank you @thumbsupep and welcome! 
@all-contributors please add @thumbsupep for documentation

**Comment by lmccart** [comment]
thank you @thumbsupep and welcome!
@all-contributors please add @thumbsupep for documentation
