### ISSUE TITLE
tan() documentation

### ISSUE THREAD

**Issue by nickmcintyre** [processing/p5.js#4061]
Hello! I was doing a little work this afternoon and noticed the reference for `tan()` states the following.

> Values are returned in the range -1 to 1.

Turns out this is not the case.

#### Nature of issue?

- [x ] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [x ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [ x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.9.0
- Web browser and version: Firefox 69.0.1
- Operating System: macOS
- Steps to reproduce this:

Tried this out in the online documentation:
```
for (let i = 0; i < 100; i = i + 2) {
  print(tan(i));
}
```

Outputs were well outside of the stated range, which is consistent with the behavior of the tangent function.

**Comment by lmccart** [comment]
fixed with https://github.com/processing/p5.js/pull/4062
