### ISSUE TITLE
Question: Contributing to p5.js from a Windows machine

### ISSUE THREAD

**Issue by haschdl** [processing/p5.js#4077]
I deliberately placed this question as an issue in Github and not in the forums because it's very closely related to development and contributing to p5.js. 

Are there known limitations or dependencies in the development tooling which might prevent Windows users from following the guidelines? I received quite many warnings and errors in my first attempt and decided to ask before spending too long on trial and error.

**Comment by stalgiag** [comment]
Not that I know of. I develop on Windows 10.0.18362.

Occasionally I'll run into problems with line endings depending on how I clone but nothing that gives me problems in my day-to-day. Here is an [example issue](https://github.com/processing/p5.js/issues/3692) for line endings in case that is relevant to your warnings and errors.

**Comment by haschdl** [comment]
Thank you for your reply! If you’re contributing from a Windows machine I should be able to do the same :)
