### ISSUE TITLE
Some examples in p5js.org learn is not working since 0.10.2 is released

### ISSUE THREAD

**Issue by scott-ho** [processing/p5.js#4083]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?
Doc site

p5.js v0.10.2 is not found from cloudflare cdn

**Comment by stalgiag** [comment]
Hi @scott-ho thank you for the issue!

Can you post the URL for the specific page that is giving you trouble? I briefly looked through the 'Learn' pages and couldn't find the problem. Thanks!

**Comment by scott-ho** [comment]
@stalgiag see https://p5js.org/learn/curves.html . 

if you click the play button, nothing happens.

![image](https://user-images.githubusercontent.com/35443789/67181135-483a2380-f40e-11e9-865c-25fa80b00302.png)

**Comment by stalgiag** [comment]
Okay thank you @scott-ho!

Looks like this is the same as #4091 . The links in this section updated but the release didn't actually make it onto cdnjs.

**Comment by lmccart** [comment]
closing this since it is covered in #4091
