### ISSUE TITLE
 different textures for differents sides of box

### ISSUE THREAD

**Issue by antonilol** [processing/p5.js#4090]
#### Nature of issue?

- [ ] Found a bug
- [x] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 
- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

#### Feature enhancement details:
I want different textures for differents sides of box

**Comment by stalgiag** [comment]
Hi @antonilol you might be able to [get more help at the forum](https://discourse.processing.org/c/p5js). The github repo is typically for reporting problems with the library or requesting new features.

I'll just add a note that [the UVs](https://en.wikipedia.org/wiki/UV_mapping) of the box won't support this by default. You can make your own custom model with different UV sections for different faces. But it would be much easier to position 6 [planes ](https://p5js.org/reference/#/p5/plane)in a cube-like formation.

Good luck! Closing for organization purposes.
