### ISSUE TITLE
Latest versions not published to cdnjs

### ISSUE THREAD

**Issue by limzykenneth** [processing/p5.js#4091]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other (specify if possible)

#### Details about the bug: 

- p5.js version: 0.10.0, 0.10.2

- Steps to reproduce this:
Links to the latest versions (0.10.0 and 0.10.2) is not available on cdnjs (https://cdnjs.com/libraries/p5.js). Is the release step supposed to automatically push the new versions there or are they supposed to pull the new versions?

**Comment by limzykenneth** [comment]
@lmccart @outofambit Do you know anything about this process? I thought the pull should be automatic when publishing to npm or is there something else that should be done? Or is this an issue over at cdnjs that we should raise with them?

**Comment by ffd8** [comment]
@limzykenneth – just saw [an issue was opened](https://github.com/cdnjs/cdnjs/issues/13523) by @lmccart on CDNJS repo and it seem to be part of [a bigger autoupdate problem...](https://github.com/cdnjs/cdnjs/issues/13524)
