### ISSUE TITLE
save() and saveJSON() not working latest version

### ISSUE THREAD

**Issue by NelsonZA** [processing/p5.js#4093]
TypeError: Argument 1 is not valid for any of the 1-argument overloads of URL.createObjectURL.

Sample:

let infoTxt = [ 1 ];
save(infoTxt, 'info.txt');
noLoop();

Won't save.

**Comment by limzykenneth** [comment]
Hi @NelsonZA, can you show a complete example of a sketch that is demonstrating the problem? Also if you can fill out the issue template it would be very helpful for us as well.
