### ISSUE TITLE
Line and Point Documentation does not match Behavior

### ISSUE THREAD

**Issue by nukecoder** [processing/p5.js#4094]
#### Nature of issue?

- [x ] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ x] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x ] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.9.0 (version on the web editor)
- Web browser and version: Firefox  	69.0.3
- Operating System: Windows 10
- Steps to reproduce this:
 /* documentation for line:
    Syntax
    line(x1, y1, x2, y2)
    line(x1, y1, z1, x2, y2, z2)
*/
  point(200, 100, 10);
  point(140, 150, 10);
  
  line(200, 100, 10, 140, 150, 10); // does not connect points
  line(200, 100, 140, 150, 300, 300); // connects points

/* The current function definition on line 532 of p5.Renderer.js shows the function only accepting 4 parameters. The same goes for the Point function. Solution is to update the documentation, or implement the functions as documented. */

**Comment by limzykenneth** [comment]
Are you using WebGL mode with the above code? The number of parameters that the functions accept depends on the drawing mode of the canvas. If you try to draw `point` with 3 parameters on a 2D canvas, only the first two parameters will be looked at, same goes for `line`.

**Comment by nukecoder** [comment]
So, we can close this issue. I didn't realize there was an optional parameter to the CreateCanvas method to put it in WebGL Mode.
