### ISSUE TITLE
Developer Docs as Website

### ISSUE THREAD

**Issue by stalgiag** [processing/p5.js#4096]
#### Nature of issue?

- [ ] Found a bug
- [x] Existing feature enhancement
- [ ] New feature request

#### Feature enhancement details:

I think that the [developer_docs](https://github.com/processing/p5.js/tree/master/developer_docs) could be republished as a Developer Docs website. This would accomplish a few things:

- Someone wouldn't necessarily need to be comfortable with the Github interface to encounter and navigate the docs
- Having these documents available in a more visually organized fashion might encourage us to make them read in a more streamlined and easily-understood way
- This encourages the internationalization of these docs by displaying the developer docs alongside a familiar language-switching interface

I have made a draft of these changes that requires little to no change in our edit process for these documents which I will open as a PR.

**Comment by lmccart** [comment]
resolved with https://github.com/processing/p5.js-website/pull/509
