### ISSUE TITLE
How do I make all objects on a canvas automatically adapt their size when the window size is changed?

### ISSUE THREAD

**Issue by BaileighD** [processing/p5.js#4098]
HI! I have to make a simple game for my creative coding class, and one of the requirements it that everything on the screen has to automatically adapt when you change your window size, not just the background. I cannot figure it out for the life of me! All help is welcomed!!

**Comment by stalgiag** [comment]
Hi @BaileighD the github repo is for reporting bugs with the library and requesting new features. [This forum](https://discourse.processing.org/c/p5js) is much better for asking for help with coding challenges. I am going to close this for organization purposes. Good luck!
