### ISSUE TITLE
Issue with resizing a createCapture object since v 0.10.2

### ISSUE THREAD

**Issue by ffd8** [processing/p5.js#4116]
#### Nature of issue?

- [x] Found a bug

#### Most appropriate sub-area of p5.js?

- [x] DOM

#### Which platform were you using when you encountered this?

- [x] Desktop/Laptop

#### Details about the bug: 

- p5.js version: 0.10.2
- Web browser and version: 77.0.3865.120
- Operating System: MacOS 10.13.6
- Steps to reproduce this:
I think this is a bug since the recent merge of p5.dom into the main p5.js. 
Using the [example on createCapture](https://p5js.org/examples/dom-video-capture.html) I don't see any console errors. When testing out that code on my own (loading only p5.min.js + p5.sound.min.js) I get the following console.error:

> Uncaught TypeError: Cannot assign to read only property 'videoWidth' of object '#<HTMLVideoElement>'
    at HTMLVideoElement.<anonymous> (VM35 p5.min.js:3)
(anonymous) @ p5.min.js:3

This is based on the following code:

```
let capture;

function setup() {
  createCanvas(320, 240);
  capture = createCapture(VIDEO);
  capture.size(320, 240);
  capture.hide();
}

function draw() {
  image(capture, 0, 0, 320, 240);
}
```

Wondered why I didn't get the error on the examples website and realized that the p5.dom.min.js file is still being loaded after the latest version of p5.js. Tested out doing the same and voila, the error message goes away.

[Here's a web editor example](https://editor.p5js.org/ffd8/sketches/XcHRL10dr) – Run the sketch and you'll see the error message on the browser console (not the web editor console) – then goto index.html and uncomment/activate the p5.dom.min.js script and the error message goes away.

**Comment by lmccart** [comment]
fixed with https://github.com/processing/p5.js/pull/4146
