### ISSUE TITLE
Feature request: a reflect method for the p5.Vector class

### ISSUE THREAD

**Issue by erichlof** [processing/p5.js#4121]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [x] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [x] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [ ] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 
- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

#### New feature details:
I would like to add a new reflect method to the p5.Vector class.  When I am programming simple demos and games involving a bouncing ball for instance, I often find that I need the ball to bounce off of a wall that might not be axis-aligned with the cardinal axes.  The method I propose is a simple reflect method that acts directly on the vector.  Syntax would look like:
`incomingVector.reflect(surfaceNormal);`

Here incomingVector is a p5.Vector and surfaceNormal is also a p5.Vector.  This method will work either in 2d or 3d as the surfaceNormal either defines a normal to a surface line in 2d, or a normal to a surface plane in 3d.  Since most implementations require that the supplied normal be normalized (length of 1), this method would first normalize the given surfaceNormal, then perform the well known vector reflection formula on the incomingVector.  This is produced by:
`reflectedVector = incomingVector.sub(surfaceNormal.mult(2 * incomingVector.dot(surfaceNormal)));
`
This new method could also be helpful in visualizations of lasers or light beams that need to be reflected off of arbitrarily rotated surfaces like mirrors or walls.

Here is a documentation example that is in line with the existing p5 vector reference documentation:
[documentation_Example](https://editor.p5js.org/erichlof/sketches/LxnUNYmXW)
And here is a usage demo sketch:
[reflection_demo_Sketch](https://editor.p5js.org/erichlof/sketches/LphlZIrV7)
In this demo, a ball bounces (is reflected) off of an arbitrarily rotated surface that is controlled by the mouse.  In this case, it is a surface line in 2d, but the method automatically extends to a surface plane in WebGL 3d mode if the supplied incomingVector and surfaceNormal are 3d vector instances. 
 
Since the reflect function itself is pretty simple, it would not add but 2 or 3 lines to the p5 codebase.  But it would be useful to be able to call on it when needed.

Thanks for the wonderful p5 library - it is a joy to use!
-Erich

**Comment by haschdl** [comment]
Sounds useful!

**Comment by singhvisha** [comment]
@limzykenneth,
Can I work on this issue?

**Comment by mishazawa** [comment]
Already done but closed https://github.com/processing/p5.js/pull/4118

**Comment by rdslade** [comment]
@erichlof Are you planning to reopen a PR similar to #4118 or is there work to be done for this issue? I would love to either work on the implementation (which seems to already be done) or contribute to the inline documentation / create unit tests for this reflect method! Any updates on your overall thoughts for this feature request?

**Comment by erichlof** [comment]
Hello @rdslade 
I had initially opened #4118 as it was my first contribution to the p5.js library.  @limzykenneth suggested I close that and open this issue so it could be discussed first.  I guess I should re-open #4118 if everything seems ok?

There are no updates to this request, but if you would like to add to the PR, the unit tests and inline documentation would be a welcome addition!

Thanks!
-Erich

**Comment by limzykenneth** [comment]
@erichlof I think you can go ahead and reopen the PR, adding any unit tests or documentation that are still missing. Thanks.

@singhvisha There is already a PR prepared but this issue is opened for discussion and gauging interest before any further work is done on the PR. You can checkout #4118 to see if you can help there. Thanks.

**Comment by erichlof** [comment]
@limzykenneth 
I don't see a re-open button for PR #4118 - could you please re-open it for me?  I don't think I have authorization to re-open a closed PR.  Thank you!

**Comment by erichlof** [comment]
@limzykenneth Thanks for re-opening the PR!

@singhvisha and @rdslade 
Feel free to add to/work on #4118 now that it is re-opened! Thank you!
