### ISSUE TITLE
The addCue feature and example don't work

### ISSUE THREAD

**Issue by everythingability** [processing/p5.js#4122]
On this page: https://p5js.org/reference/#/p5.SoundFile/addCue

I click the button, the sound plays, but there are no text changes.

**Comment by stalgiag** [comment]
Hi @everythingability thanks for the issue! The sound library development is tracked in another repo and [there is an issue open for this problem over there.](https://github.com/processing/p5.js-sound/issues/371)

I am going to close this issue for organization purposes. Follow the linked issue to track progress on this. Thanks again!
