### ISSUE TITLE
Vector.cross() should allow result to be a target (avoid creating new Vec on each call) 

### ISSUE THREAD

**Issue by erichlof** [processing/p5.js#4123]
#### Nature of issue?

- [ ] Found a bug
- [x] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [x] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [ ] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 
- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

#### Feature enhancement details:
As it stands now, p5.Vector.cross() forces the user to create a new p5.Vector containing the result.  This is fine if the cross function is used in the setup() function, but if it is used in the draw() function (where I often need it), it ends up creating 60 new p5.Vectors a second for each call.
I propose that the cross function be updated to follow the add, sub, mult, div functions and allow the user to specify an optional target that holds the result of the cross product.  Syntax would look like:

inside setup():
`let v1 = createVector(1,0,0);
let v2 = createVector(0,1,0);
let target = createVector();`
and then inside draw():
`target = v1.cross(v2, target);`

The syntax for the updated p5.Vector.cross() method would look like:
`p5.Vector.prototype.cross = function cross(v, target) {
  const x = this.y * v.z - this.z * v.y;
  const y = this.z * v.x - this.x * v.z;
  const z = this.x * v.y - this.y * v.x;
  if (target) {
    return target.set(x, y, z);
  }
  if (this.p5) {
    return new p5.Vector(this.p5, [x, y, z]);
  } else {
    return new p5.Vector(x, y, z);
  }
};`

This way, no older code that used the cross() method would be broken, and the function quickly returns the result in a reusable target to the performance-minded programmers, avoiding the continual creation of new vectors to be fed to the garbage collector.

**Comment by limzykenneth** [comment]
I'm not terribly well versed with how memory works in JS but woudn't the block of memory still be allocated regardless of whether the value is returned from the function or assigned in the function?

From what I understand in JS as long as there is an assignment, a new block of memory address will be allocated for the variable regardless of whether that variable is a pre-existing one or not. But I may be wrong.

**Comment by erichlof** [comment]
@limzykenneth 

Hi Kenneth, thank you for the quick reply.  Yes I'm not too clear on how browsers allocate memory, especially with JS and just-in-time compiling.  You may be right on the mark.  I will close this issue and research the topic further.  If I find that the new keyword is worse for the garbage collector as opposed to using and reusing a 'temp' variable/object, I will re-open the issue and site any sources that back up the argument.

Thanks again!
-Erich
