### ISSUE TITLE
Using tint() can be stalling

### ISSUE THREAD

**Issue by yzxnwj** [processing/p5.js#4125]
When I use tint in my animations,  three will be   cato, how do isolve it

**Comment by stalgiag** [comment]
Hello @yzxnwj can you provide a code example?

In the future, it is best to fill out the issue template (that text that is in the issue field when you first open an issue). This give us all of the information we need to be helpful.

**Comment by lmccart** [comment]
I'm closing this for organizational purposes, please feel free to reopen if you can share a code snippet that illustrates the problem. Thanks!
I'm closing this for organizational purposes. Please reopen if you can provide a code snippet that illustrates the issue. Thanks!
