### ISSUE TITLE
Translation of contributor_docs

### ISSUE THREAD

**Issue by stalgiag** [processing/p5.js#4137]
#### Nature of issue?

- [ ] Found a bug
- [x] Existing feature enhancement
- [ ] New feature request

#### Feature enhancement details:
As we start working towards a Contributor Docs website #4096 it would be awesome to start adding some translations. In the initial setup of the navbar there is going to be a stubbed Spanish version. Further translation would be super helpful if anyone has any interest. Translations can cover all of the files in `contributor_docs/` or just `contributor_docs/README.md` both are helpful!

**Comment by junagao** [comment]
Hi, I'd like to help with Portuguese (Brazilian) translation. Let me know if it's ok to start.

**Comment by stalgiag** [comment]
Yes @junagao definitely!

**Comment by Pierre-Baptiste** [comment]
Hey, 
I'd like to work on the French translation!

**Comment by stalgiag** [comment]
Amazing thank you @Pierre-Baptiste !

**Comment by nthe** [comment]
Hello, I can help with Slovak translation :slovakia:.

**Comment by stalgiag** [comment]
Great! Thank you @nthe

**Comment by iamrajiv** [comment]
Hi, I'd like to help with Hindi translation.

**Comment by iamrajiv** [comment]
@stalgiag Hi, I'd like to help with Hindi translation.

**Comment by stalgiag** [comment]
Great thanks @iamrajiv !

**Comment by jploskonka** [comment]
I’m currently doing workshops with p5.js in Polish so I’m translating on the fly necessary website parts – I can try to get to this in structure way and put up some pull requests. I’m doing once a week workshops till end of June, so I’d put up some PRs touching parts I’m using for workshops (at least for beginning).

**Comment by DivyamAhuja** [comment]
@stalgiag I would like to translate rest of Contributor Docs in Hindi as only README.md is translated by @iamrajiv .

**Comment by stalgiag** [comment]
Sounds good @DivyamAhuja !

**Comment by fenilgandhi** [comment]
@DivyamAhuja Hey, are you working on it ? if not, i would like to pick it up from there.

**Comment by DivyamAhuja** [comment]
@fenilgandhi I have translated contributing_ddocumentation.md till now, and now I think it's not that necessary to translate all of contributor_docs.
If you are interested you can translate all other docs

**Comment by sk1122** [comment]
> @fenilgandhi I have translated contributing_ddocumentation.md till now, and now I think it's not that necessary to translate all of contributor_docs.
> If you are interested you can translate all other docs

I want to translate some docs to hindi..
Can I help you guys..

**Comment by fenilgandhi** [comment]
@sk1122, Sure go ahead with it.

**Comment by mjaything** [comment]
Hello, I would like to translate README.md file into Korean, if no one has done it yet. Please let me know if anyone is in progress -- it would help me to avoid the overlap! ;-)

**Comment by limzykenneth** [comment]
@mjaything You can go ahead with it. You can open an issue specifically for Korean translation of the contributor's docs if you want then I can assign the issue to you just as a record that you are working on this, you don't have to though.

**Comment by mjaything** [comment]
@limzykenneth Hi Kenneth, thanks for the comment. I am almost done with the translation of the readme.md file alone. At the moment, I am unsure if I should make a GSoC proposal for a p5.js web editor internationalization or the whole contributor_docs, or both. But anyways, yes if you could assign the issue, I would be able to contribute with the Korean readme.md at least, in few days! :)

**Comment by SketchySketch** [comment]
Hello and I’d like to translate README into Chinese. Please let me know if anyone is in progress :)

**Comment by Qianqianye** [comment]
Hi @limzykenneth, since we updated the [contributor doc](https://github.com/processing/p5.js/tree/main/contributor_docs) recently. Are there any needs to update the translations?

**Comment by limzykenneth** [comment]
We will likely need some new translations, particularly around the two main document for contributor guidelines and steward guidelines. Also the exact build descriptions has changed to use less `grunt` command directly and using npm aliases, so that would need updating as well.

**Comment by MostafaEwis** [comment]
Hi, I would like to translate the readme into Arabic.

**Comment by limzykenneth** [comment]
@MostafaEwis Do ahead with the translation. Thanks!

**Comment by anmode** [comment]
Hey! I would like to translate the readme into Spanish.  if @MostafaEwis agrees I am willing to convert to Arabic too!

**Comment by anmode** [comment]
> 

I can do that!

**Comment by MostafaEwis** [comment]
@anmode 
Thanks for your help, I think I want to keep working on the Arabic version of the readme currently. It's my native language by the way.

**Comment by bmsptra24** [comment]
Hi, I'd like to help with Indonesian (Bahasa Indonesia) translation!

**Comment by Qianqianye** [comment]
Thank you all for your input on this issue. We are currently working on a project to reorganize and update the p5.js documentations, so we will temporarily pause the translation effort for the contributor_docs until the documentation update is complete. To avoid any confusion, I will close this issue for now. We will revisit the issues labeled '[Documentation](https://github.com/processing/p5.js/labels/Documentation)' or open a new issue about translation helps we need later. 

Please feel free to browse other [open issues](https://github.com/processing/p5.js/issues) and see if there is anything you'd like to help with. If you need help with any issues that you'd like to work on, please let us know in a comment within the respective issue. Thanks!

CC @limzykenneth @davepagurek @nickmcintyre
