### ISSUE TITLE
no audio of safari

### ISSUE THREAD

**Issue by yzxnwj** [processing/p5.js#4139]
my sketch is super simple, just uses loadSound,   sound.play and p5.FFT.

It worked perfectly on chrome android, but on iOS no chance, using iOS 11.

music_ShowdasPoderosas = loadSound($('#music option:selected').val(), loaded)
function loaded() {
	musicStart= true
}
$('.run').on('click', ()=>{
music_ShowdasPoderosas.play()
})

**Comment by lmccart** [comment]
the github issues here are a good place for bugs and issues with the p5.js library itself. for questions about writing your own code, tests, or following tutorials, the [forum](https://discourse.processing.org/) is the best place to post. thanks!

**Comment by lmccart** [comment]
hi @yzxnwj can you confirm that the volume is turned on with your iOS device? please post a simplified example that doesn't include jquery, so we can better isolate the issue.
