### ISSUE TITLE
deviceOrientation is undefined in setup() on mobile devices

### ISSUE THREAD

**Issue by oshoham** [processing/p5.js#4142]
#### Nature of issue?

- [x] Found a bug

#### Most appropriate sub-area of p5.js?

- [x] Events

#### Which platform were you using when you encountered this?

- [x] Mobile/Tablet (touch devices)

#### Details about the bug: 

- p5.js version: 0.10.2
- Web browser and version: iOS Safari
- Operating System: iOS 12.4.1 on an iPhone 8
- Steps to reproduce this:

If you run the following sketch on a mobile device, a blank canvas will be displayed on screen.
Link for opening on a mobile device: https://editor.p5js.org/oshoham/present/uSK1mzkhI

```javascript
function setup() {
  createCanvas(displayWidth, displayHeight);
  
  textAlign(CENTER, CENTER);
  text(deviceOrientation, width / 2, height / 2);
}

function draw() {
}
```

However, if you add a call to the private p5.js function [_handleMotion()](https://github.com/processing/p5.js/blob/093d3019e463f00b71739e724eccfc90f582a1ce/src/events/acceleration.js#L641) in `setup()` before attempting to access `deviceOrientation`, the sketch will correctly display `portrait` or `landscape`, depending on the device's orientation.
Link for opening on a mobile device: https://editor.p5js.org/oshoham/present/Mlw8-kgns

```javascript
function setup() {
  createCanvas(displayWidth, displayHeight);

  _handleMotion();
  
  textAlign(CENTER, CENTER);
  text(deviceOrientation, width / 2, height / 2);
}

function draw() {
}
``` 

It seems like p5.js should populate `deviceOrientation` before a sketch's `setup()` hook runs. This would be useful for doing things like setting the initial canvas dimensions based on the orientation.

**Comment by stalgiag** [comment]
Thanks for the well-written issue.

Do you think there are other use cases for getting device orientation before `setup()` ? `displayWidth/displayHeight` can be used to set canvas dimensions based on orientation.

Overall, It makes sense to me to make `deviceOrientation` available as soon as possible. This would probably mean breaking the `deviceOrientation` calculation out of `_handleMotion()` since most of the other calculations in there are multiframe.

**Comment by oshoham** [comment]
@stalgiag Sorry for taking a few days to get back to you.

One other use case for accessing `deviceOrientation` in `setup()` that comes to mind is determining whether a sketch is running on a mobile device vs. a laptop/desktop computer. If `deviceOrientation` is `undefined`, that’s usually a good indicator that a sketch isn’t running on mobile. However, that check could also probably be done just as easily in `draw()`.

I agree that breaking `deviceOrientation` out of `_handleMotion` is probably the way to go.

If it doesn’t make sense to do that right now, I think it could also be acceptable to amend the `deviceOrientation` documentation to indicate that it’s not available in `setup()`.

**Comment by stalgiag** [comment]
It makes sense to me for it to be available during setup. It should be safe to set this in the p5 constructor in `core/main.js`. Do you want to open a PR?
