### ISSUE TITLE
Incorrect output when using print with an array 

### ISSUE THREAD

**Issue by nonsequitoria** [processing/p5.js#4143]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.9.0
- Web browser and version: Google Chrome | 78.0.3904.97 (Official Build) (64-bit)
- Operating System: MacOSX

- Steps to reproduce this:
``` javascript
function setup() {
  let a = [1, 2];
  print(a); // should print [1, 2] but actually prints [3, 2] 
  print(a[0]); // correctly prints 1
  a[0] = 3;
  print(a); // correctly prints [3, 2]
  print(a[0]); // correctly prints 3  
}
```

**Comment by anuragakella** [comment]
Not sure why that's happening for you? Seems to be working fine for me...

Check this out:
[used the exact same code that you used]
https://codepen.io/anuragakella/pen/NWWOxKj?editors=1111

**Comment by nonsequitoria** [comment]
Thanks for the test @anuragakella. Note your example is using p5.js version: 0.7.1, but I checked it on CodePen with version 0.9.0, and it also works as expected.  

So, I think this might be related to the p5 web editor. It must handle console output or how the code is run in some non-standard way. Try running my test code there: https://editor.p5js.org/nonsequitoria/sketches/6MS3iYNJG

**Comment by lmccart** [comment]
closing this because it's covered in #1203
