### ISSUE TITLE
createCapture() throws DOM error on Chrome 

### ISSUE THREAD

**Issue by DeepakKannan1992** [processing/p5.js#4145]
**Nature of issue?**
 Found a bug

**Most appropriate sub-area of p5.js?**
 Other --> DOM

**Which platform were you using when you encountered this?**
 Desktop/Laptop

**Details about the bug:**
p5.js version: Latest version as of date (14/11/2019)
Web browser and version: Chrome 78.0.3904.97

**Operating System:** Windows 10

**Steps to reproduce this:**
Create a sketch
Include this line in setup(): capture = createCapture(VIDEO);
Run on Chrome. This will produce Error {} in the console, and in devtools says DOMException
Another quick way to see this error is to try out the p5js reference example for createCapture() while using Chrome.

**This error is same as the one mentioned in error #3645 which was closed.**

**Comment by stalgiag** [comment]
I am unable to recreate testing [with this link](https://p5js.org/examples/dom-video-capture.html) on Windows 10 with Chrome 78.0.3904.97. 

I additionally tested with p5 v0.9.0 on the online editor and the p5 v0.10.2 on a local https server. All are working as expected.

Did you follow the thread in the issue you linked and try the suggestions posted there? It seems that the author of that issue experienced an unexpected and sudden disappearance of the buggy behavior so it is hard to trace the problem.

**Comment by mishazawa** [comment]
Hello @DeepakKannan1992. Are you sure that you have allowed permissions to capture device in Chrome? I can reproduce your problem when I click "Deny" when browser asking permissions.

**Comment by NandhaGopiFrost** [comment]
Hi @DeepakKannan1992 ,

I tried the same and got below two scenarios
1. Access Denied for camera - console logged as : DOM exception: access denied (No error thrown)
2. Allowed Camera but no camera connected - No error from console
3. Allowed camera and camera connected - no error and worked as expected
