### ISSUE TITLE
GitHub Actions Caching Support

### ISSUE THREAD

**Issue by gruselhaus** [processing/p5.js#4150]
#### Nature of issue?

- [ ] Found a bug
- [x] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [ ] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 
- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

**Comment by limzykenneth** [comment]
Hi @gruselhaus, can you explain a bit what this issue is about? I wasn't following the move to Github Actions so just looking at this issue and the related PR isn't making complete sense to me.

**Comment by gruselhaus** [comment]
Hi @limzykenneth,

sure. The p5.js repo uses GitHub Actions for CI now. See #4131. I added the dependency caching function to those CI Workflows in #4151.

**Comment by outofambit** [comment]
closing this since i don't think there's anything we can cache currently :/
