### ISSUE TITLE
Documentation for npm package

### ISSUE THREAD

**Issue by chriskuech** [processing/p5.js#4152]
I can't find any mention of how to use the npm package in the documentation.  The only hooks I see demonstrated in the docs are the `setup()` and `draw()` functions, which don't make sense in most scenarios where someone would be importing an npm package.  Please document this scenario.

**Comment by lmccart** [comment]
hi @chriskuech thanks for your post. we have not explicitly designed this library to be used with npm so there is no documentation for this on the website. for more help with this, I encourage you to post on our [forum](https://discourse.processing.org/). thanks!
