### ISSUE TITLE
Device rotation should respect angleMode

### ISSUE THREAD

**Issue by haschdl** [processing/p5.js#4154]
I noticed that device rotation variables, namely [rotationX](https://p5js.org/reference/#/p5/rotationX), [rotationY](https://p5js.org/reference/#/p5/rotationY) and [rotationZ](https://p5js.org/reference/#/p5/rotationZ) are always in degrees, and not follow `angleMode`. 
This creates some confusion, which is noticed for example in the example for rotationX:
```
rotateZ(radians(rotationZ));
```

#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [x] Mobile/Tablet (touch devices)
- [ ] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.9.0
- Web browser and version: Chrome for ios
- Operating System: iPhone
- Steps to reproduce this: see example for rotationX in p5.js reference

**Comment by limzykenneth** [comment]
Should be a fairly trivial fix [here](https://github.com/processing/p5.js/blob/ca92fc457ff836e293916df06964e85f83182368/src/events/acceleration.js#L627) and [here](https://github.com/processing/p5.js/blob/ca92fc457ff836e293916df06964e85f83182368/src/events/acceleration.js#L372). 

@haschdl I can assign the issue to you if you want to work on it?

**Comment by niravasher** [comment]
rotateX, rotateY, rotateZ follow radians and not degrees according to me. Since default angle mode is radians, I typed the following
`function draw() {
  background(100);
  rotateY(3.14/2);
  box();
}`
This rotates the box by 90 degrees.
But if I change angle mode to degrees then the following code doesn't work
`function draw() {
  background(100);
  angleMode(DEGREES);
  rotateY(90);
  box();
}`
Can I work to fix this issue?

**Comment by haschdl** [comment]
Hello @niravasher , “rotationX” and not “rotateX” :) Do you think you refer to the same issue?

**Comment by AnuragGupta93** [comment]
@haschdl I have tested this myself and found out that `rotationX`, `rotationY` and `rotationZ` are working perfectly fine as expected.
The default value of `rotationX`, `rotationY` and `rotationZ` is "Radian".
For ex:

```
function setup() {
  createCanvas(400, 400, WEBGL);
}

function draw() { 
  background(100);  
  rotateZ(3.14/4);   // Rotate by (PI/4) radian i.e 45 degrees
  box(); 
}
```
Output: 
![Screenshot from 2020-01-07 22-49-12](https://user-images.githubusercontent.com/35900375/71914732-3d3a9800-31a0-11ea-8c1b-83be423c3e31.png)

[Source Code] (https://editor.p5js.org/AnuragGupta93/sketches/Fg5H8XQNO)

### After using angleMode, we have:

```
function setup() {
  createCanvas(400, 400, WEBGL);
}

function draw() { 
  background(100);  
  angleMode(DEGREES);
  rotateZ(45);   // Rotate by 45 degrees
  box(); 
}
```

Output:

![Screenshot from 2020-01-07 22-53-11](https://user-images.githubusercontent.com/35900375/71914841-7ffc7000-31a0-11ea-8ef7-c249d2844b9c.png)

[Source Code] (https://editor.p5js.org/AnuragGupta93/sketches/aZi4gTMwz)

**Comment by haschdl** [comment]
hello @AnuragGupta93 and @niravasher   Your code and examples refers to **rotateX() function** while the issue is about the **rotationX** variable.
Those are different things. 
* [rotateX](https://p5js.org/reference/#/p5/rotateX), [rotateY](https://p5js.org/reference/#/p5/rotateY), [rotateZ ](https://p5js.org/reference/#/p5/rotateZ) are functions. They work as you explained, there are no issue there.

* [rotationX](https://p5js.org/reference/#/p5/rotationX) refers to device rotation.  "The system variable rotationX always contains the rotation of the device along the x axis. Value is represented as 0 to +/-180 degrees." 

The issue is that such variables always return angles in degrees, causing confusion to learners.

If you are interested in working in the issue you can see the reply from @limzykenneth  https://github.com/processing/p5.js/issues/4154#issuecomment-564017431

**Comment by sourabhdharpure** [comment]
@limzykenneth I would like to work on this issue
We need to convert the value of e.beta, e.gamma, e.alpha values according to the angleMode.

I am getting the problem correctly?

**Comment by limzykenneth** [comment]
@sourabhdharpure Yes, that is correct. I'll assign the issue to you.
