### ISSUE TITLE
bug in npm bundle

### ISSUE THREAD

**Issue by awb99** [processing/p5.js#4158]
I ran the npm bundle "p5" : "^0.10.2" through the google clojure compiler and got
an error in line 69565: "Invalid delete operand. Only properties can be deleted.".
The culprit seems to be "delete this".

I assume this function has a bug.

**Comment by stalgiag** [comment]
Hi! Thanks for the issue.

I think that [this line ](https://github.com/processing/p5.js/blob/master/src/dom/dom.js#L2077)must be the culprit. I think the intent of this line can be achieved by deleting the reference in `this._pInst._elements`. Any interest in opening a pull request and contributing a quick fix?

**Comment by awb99** [comment]
Sorry I don't know enough about p5 to fix the issue. I think with a good linter this
error also should have popped up.

**Comment by stalgiag** [comment]
New contributors are always welcome, regardless of prior experience or knowledge!

For now I will add a help wanted label but the to-do is to:
1. Follow [these instructions](https://github.com/processing/p5.js/tree/master/developer_docs#development-process) on setting up a development environment
2. During step 6, when asked to make changes to the code go to [this line in src/dom/dom.js](https://github.com/processing/p5.js/blob/master/src/dom/dom.js#L2077) and replace it with something like:
```js
// feel free to modify this code to preference as long as the result is the same
const index = this._pInst._elements.indexOf(this);
if(index !== -1) {
  this._pInst._elements.splice(index, 1);
}
```
3. Follow the rest of the instruction from step 1. and open a pull request.

**Comment by thheller** [comment]
I'm confused. The Closure Compiler is explictely complaining about `delete this;`. So this line which is still there?

https://github.com/processing/p5.js/blob/74e8d1ebdc3cf3c64b0faacaff5fabf1a50f9e1a/src/dom/dom.js#L2092

Not sure what the other code actually does but the Closure Compiler was complaining about `delete this`  when reporting `"Invalid delete operand. Only properties can be deleted."`.

**Comment by stalgiag** [comment]
My apologies @thheller early morning code review and I missed that the `delete this` line wasn't removed. The other code replaces `delete this` now we just need to remove the actual line `delete this`. 😅 

@mojosoeun would you [like to remove the line `delete this`?](https://github.com/processing/p5.js/blob/74e8d1ebdc3cf3c64b0faacaff5fabf1a50f9e1a/src/dom/dom.js#L2092) and open a pull request?

**Comment by stalgiag** [comment]
Actually[ I just quickly removed it](https://github.com/processing/p5.js/commit/4fa45678d5aaefd23163a2cf842a0b83ff04979e). Thanks for the help everyone!
