### ISSUE TITLE
Enhancement: Using Web Workers for Image Filters

### ISSUE THREAD

**Issue by anuraghazra** [processing/p5.js#4160]
#### Nature of issue?

- [ ] Found a bug
- [x] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [x] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Feature enhancement details:

Hi, i was just thinking if we could utilize web workers to fix the UI Freezing issue when applying performance heavy filter like `BLUR`. This way we can ensure that UI stays responsive while applying any filters to images.

Since the Image Filtering logic is just some math and UintArray stuff i think we could use WebWorkers.

Or maybe we could use [OffscreenCanvas](https://developers.google.com/web/updates/2018/08/offscreen-canvas)? well the [support for OffScreenCanvas is really bad.](https://caniuse.com/#search=OffscreenCanvas)

Further Resources:
- https://www.sitepoint.com/using-web-workers-to-improve-image-manipulation-performance/
- https://gist.github.com/tieleman/6028023
- https://www.kevinhoyt.com/2018/10/23/image-processing-in-a-web-worker/
- https://blog.logrocket.com/using-webworkers-for-safe-concurrent-javascript-3f33da4eb0b2/
- https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers

**Comment by limzykenneth** [comment]
As part of explorations into 2.0, I have tried out OffScreenCanvas and still found that it differs too much between browsers and for many things still work inefficiently with Web Workers. There is currently no other options for filtering within Web Workers and the relatively recently implemented WebGL filters should help things be faster too, so I will close this for now.
