### ISSUE TITLE
allow rect() use just 3 parameters, like ellipse() - so both words can be hotswapped

### ISSUE THREAD

**Issue by ffd8** [processing/p5.js#4163]
#### Nature of issue?

- [x] Existing feature enhancement

#### Most appropriate sub-area of p5.js?

- [x] Core/Environment/Rendering

#### Feature enhancement details:

`ellipse()` allows one to provide just 3 parameters ie. `ellipse(x, y, w)` and it auto-magically uses the `w` for the `h` to make a perfect circle. This functionality is really efficient (`circle` and `square` were helpful learning additions too!) – and the pending PR will just add the same feature to `rect()`, since it's confusing when the shape dissapears if swapping the word `ellipse` to `rect` with just three params (since the 4th was required with `rect`). Tested with `rectMode()` and all seems to work fine.

```
// now both will work
ellipse(mouseX, mouseY, 50);
rect(mouseX, mouseY, 50);
```

**Comment by mishazawa** [comment]
According to [docs](https://p5js.org/reference/#/p5/rect), `rect` signature accept optional parameters for corners radius. How to handle this parameters when `height` parameter was omitted?

**Comment by ffd8** [comment]
@mishazawa Ahaa - interesting issue. This is intended to address when only 3 params are given, similar to an `ellipse()`. If one wants to have rounded corners with `rect()`, they should add the additional values or swap to a `square()` if really wanting to avoid adding an `h`.
