### ISSUE TITLE
[Issue] Inconsistent default fill colors for shape and text, and `fill()` affects both; `noFill()` also causes texts disappear. Inconsistent behavior with Processing (Java) implementation.

### ISSUE THREAD

**Issue by szinubuntu** [processing/p5.js#4167]
#### Nature of issue?

- [X] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [X] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [X] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [X] Desktop/Laptop
- [ ] Others (specify if possible)

Specifically, I am using P5 web editor: https://editor.p5js.org

#### Description

Clearly by default the shape fill color is **white** while text color is **black**. The call to `fill()` will however change both colors to the same value. This can cause confusion and inconvenience.

Also notice this is NOT the same as Java version of processing, which indeed have both shape fill and text color **white** by default, and in Java version of processing `noFill()` will NOT cause the texts to disappear.

#### Details about the bug: 

- p5.js version: I am use **p5 online editor** 
- Web browser and version: Vivaldi | 2.6.1566.44 (Stable channel) (64-bit) 
- Operating System: Windows 10 
- Steps to reproduce this:

```javascript
function setup() {
  createCanvas(400, 400);
}

function draw() {
  background(220);
  noFill();
  rect(10, 10, 10, 10);
  text("Hello", 20, 20);
}
```

Above snippet will show just a box frame, **without text** (Figure 1).

On desktop version of Java processing, if we use: 

```java
void draw(){
  noFill();
  rect(10, 10, 10, 10);
  text("Hello", 20, 20);
}
```

We will see both rectangle and text (Figure 2).

#### Expected Behavior

`fill()` should change only shape color; Text color should be changed by `stroke()` or maybe `textColor()`. Or in other cases if `fill()` by design changes color of both, then make the default color for text and shape both white to avoid confusion.

#### Current Behavior

Let's say I am drawing 3 rects and 3 texts in between, however I wish to draw the rects in different colors, and draw texts over them separately. In that case I will have to reset my draw color to default black in order for the texts to display properly, which is inconvenient - a lot of redundant function calls are issued and that makes code messy.

**Expected**:

```processing
textColor(); // Set color for text throughout the program
fill(); // Set color for rect, without affect text()
rect();
text();
fill(); // Set color for rect, without affect text()
rect();
text();
fill(); // Set color for rect, without affect text()
rect();
text();
noFill(); // Draw empty shape
rect();
text(); // The text should still display
```

## Figures

![Figure 1](https://user-images.githubusercontent.com/7077098/69827589-f8f1ca80-11e5-11ea-8814-14b231f3725a.png)

Figure. 1

![Figure 2](https://user-images.githubusercontent.com/7077098/69827592-fbecbb00-11e5-11ea-84a6-009b60fd29be.png)

Figure. 2

**Comment by lmccart** [comment]
thanks @szinubuntu. our goal is not to have parity with processing, but to make decisions for this project that feel consistent and understandable as possible. our approach has been that `fill()` and `stroke()` apply to both text and shapes. this allows us to do things like text outlines. in this case, it made sense that `noFill()` and `noStroke()` would also apply.
