### ISSUE TITLE
P5.js goes VR

### ISSUE THREAD

**Issue by kappaxbeta** [processing/p5.js#4172]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [x] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [x] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [ ] Desktop/Laptop
- [x] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 
- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

#### New feature details:

While I was busy learning A-Frame and other stuff, I thought it would be lovely if P5.js would support WEBVR native. :) 

All thoughts and Ideas welcome

**Comment by limzykenneth** [comment]
There used to be a [p5.vr](https://github.com/bmoren/p5.vr) addon library but it is no longer being maintained. I think VR support would be a great idea for an addon library!

**Comment by aferriss** [comment]
You might want to look into @stalgiag 's [p5.xr](https://github.com/stalgiag/p5.xr) library. Documentation is here https://stalgiag.github.io/p5.xr/#/

**Comment by stalgiag** [comment]
Thanks @aferriss !

Yeah, p5.xr is in alpha stage currently. It has broad support for mobile VR with any p5 sketch. Better hardware support (including desktop), more stable AR functionality, and an npm package will come at the end of the year.

I am going to close for organization purposes but if you have questions or requests feel free to open issues over on [the p5.xr repo.](https://github.com/stalgiag/p5.xr) Also, contributions are always welcome 😄
