### ISSUE TITLE
Need Support of P5 on Blazor Web-Assembly

### ISSUE THREAD

**Issue by sps014** [processing/p5.js#4184]
Blazor lets you build interactive web UIs using C# instead of JavaScript. Blazor apps are composed of reusable web UI components implemented using C#, HTML, and CSS. Both client and server code is written in C#, allowing you to share code and libraries.

P5 for Blazor will be game-changer, Blazor provide JS Interop capability out of the box and hence Blazor can use P5 with interop, something like native P5 will surely reduce performance overheads of interop. Kindly think about Blazor as it is growing very rapidly.
Thank you.

**Comment by limzykenneth** [comment]
From what I understand Blazor is used to run C# in the browser through WebAssembly? I don't think there are any current plans to port p5 to C# or even WebAssembly, unless I've misunderstood what you mean by "p5 for Blazor"?

**Comment by sps014** [comment]
Thanks, hope one day we can get the port on Blazor WebAssembly, for now, I
have ported a few Drawing API for Blazor my self.

![Capture](https://user-images.githubusercontent.com/45932883/70606607-d8346680-1c22-11ea-8be4-2031328b25bf.PNG)

with JS Interop you guys can port it easily.
