### ISSUE TITLE
Possible memory leak with video texture in WebGL renderer

### ISSUE THREAD

**Issue by sweiss01** [processing/p5.js#4185]
This is a duplicate of an issue I posted to discourse.processing.org a few days ago.  I'm new to p5.js, so I wanted to check with the community to make sure I was using the software properly before reporting a potential bug.

#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

I'm experiencing a possible memory leak while displaying a video texture with a WebGL renderer.

I’m on a Mac running macOS 10.15.1 and I’ve tried Safari 13.0.3 and Chrome 78.0.3904.108 with p5.js 0.10.2 from the jsdelivr.net cdn. I am using Activity Monitor to watch memory usage. In each browser, memory usage seems to increase for as long as the sketch runs. If I use a P2D renderer and display the video with the image function, memory is stable. I experience the same problem with any mp4 video that I try. I have not tried other video formats yet.

I've also experienced the same issue on both Chrome and Firefox on Windows.

```
<!DOCTYPE html>
<html>
    <head>
        <script src="https://cdn.jsdelivr.net/npm/p5@0.10.2/lib/p5.min.js"></script>
    </head>

    <body>
        <script type="text/javascript" charset="utf-8">

let vid

const VIDEO_FILE_NAME = 'https://CommonDataStorage.GoogleApis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4'

function preload( ) {
    vid = createVideo( [ VIDEO_FILE_NAME ], ( ) => {
        vid.size( 480, 360 )
    } )
}

function setup( ) {
    createCanvas( 800, 600, WEBGL )   
}


function draw( ) {
    background( 40, 100, 100 )

//                image( vid, 10, 10 )
    texture( vid )
    box( 480, 360, 20 )
}


function mousePressed( ) {
    vid.loop( )
    vid.hide( )
}

        </script>

    </body>
</html>

```

**Comment by stalgiag** [comment]
Hi! Thanks for the well-written issue.

I tried with your example and with the videoTexture manual test example on Windows 10.0.18362 and Chrome 78.0.3904.108 with master or the 0.10.2 jsdeliver release..

With your example and 0.10.2, performance recordings look like this:
![Screenshot (202)](https://user-images.githubusercontent.com/10382506/70554771-a04df600-1b32-11ea-8c4c-d487097a910d.png)

I also recorded for longer sessions and got similar results. There is some jaggedness with memory usage building before garbage collection clears it, but this looks like an acceptable pattern. The total JS heap size never left the 16-19MB range even after I left it playing for 30 minutes.

If I use my OS activity monitor, after leaving the video playing for a long time (>20 min) I am able to see higher memory usage (+15%) from Chrome. It is tough to say as Chrome's analysis of the memory usage of the page more or less stays the same.

**Comment by sweiss01** [comment]
Hi stalgiag!  Thank you for your help with this issue.

I've been focusing on memory usage only for the rendering thread of each browser and I'm seeing more-or-less the same growth rate on Chrome that you're seeing.  Over a period of hours, it just keeps increasing. 

When I first started this project, I was rendering in Safari on my Mac and the browser would warn about high memory usage and keep restarting my sketch.  For some reason, Safari is way worse than Chrome or Firefox for this problem.

I've since started running my sketch in Electron on the latest Chromium and I'm seeing the same issue.

My project is commercial and would run indefinitely so even a small leak is cause for concern.  I'm not sure what to try next.  Any suggestions are greatly appreciated.

**Comment by stalgiag** [comment]
@sweiss01 I can look into it more, but the more possibilities that we can rule out the easier it will be to fix.

Does this happen in 2D mode?
Does this happen with a still image?
Does this happen when drawing with immediate-mode?

I tried testing this last one, but since DevTools isn't picking up on this, I don't have a very accurate or efficient way to detect issues. 

The code I used for the last one, is that I replaced your call to box with:
```js
  textureMode(NORMAL)
  let halfW = 240, halfH = 180;
  beginShape(TRIANGLES);
  vertex(-halfW, -halfH, 0, 0, 0);
  vertex(halfW, -halfH, 0, 1, 0);
  vertex(halfW, halfH, 0, 1, 1);
  vertex(halfW, halfH, 0, 1, 1);
  vertex(-halfW, halfH, 0, 0, 1);
  vertex(-halfW, -halfH, 0, 0, 0);
  endShape();
```
I don't see an increase in memory use from Chrome after 1 loop through the video, but again this is pretty unpredictable testing.

**Comment by sweiss01** [comment]
I misspoke earlier.  Under Electron/Chromium, the "Electron Helper (GPU)" thread keeps increasing while the "Electron Helper (Renderer)" thread eventually levels off.

It does not happen when I use a P2D renderer and display the video with the image() function.

It does not seem to happen with a still image using texture() on a box with WebGL.  Memory goes up and down, but the average seems to be steady.  The "Electron Helper (GPU)" process doesn't change.

It seems to happen with the immediate-mode code, but at a significantly slower rate.

**Comment by stalgiag** [comment]
Hm this is tough. I am unable to tell if I can recreate this. I leave this sketch running for long periods of time and sometimes I can see a difference in memory usage and sometimes I cannot. Since we can't monitor directly in an effective way through the browser, there aren;t many options to figure out what is wrong here.

For now I'd say try running [this simple webgl only sketch ](https://mdn.github.io/webgl-examples/tutorial/sample8/) with your setup and see if there are similar problems.

**Comment by sweiss01** [comment]
That sketch is very stable, even in Safari.  The others fluctuate a lot more and it is hard to tell what's happening without looking at the averages trend higher over a longer period of time.

**Comment by stalgiag** [comment]
Tough. Still not really able to recreate.

I got a Mac 10.15.1 to test and in Safari Version 13.0.3 I am unable to detect a significant change.

Here is my memory activity monitor upon starting your sketch:
<img width="958" alt="screenshot" src="https://user-images.githubusercontent.com/10382506/70670873-37987380-1c2f-11ea-9659-64b3c534aa55.png">

and 1 hour later:
<img width="944" alt="screenshot(1)" src="https://user-images.githubusercontent.com/10382506/70670887-43843580-1c2f-11ea-8de9-99042c849007.png">

I saw occasional mild fluctuation but only +-0.2mb.

**Comment by sweiss01** [comment]
I don't have much experience profiling memory on a Mac.  I've been looking at the content process, not the browser process.  If I run in Safari, I've been watching the "Safari Web Content" process.  When I launch from Atom, that process is named localhost:8001.  If I double-click an index.html file, it is Safari Web Content.  I've been doing all my tests by launching from an editor, though, instead of directly running the html.  When I run the html directly, like I did with the simple webgl sketch, my sketch is also stable like what you experienced.

That makes me feel a bit silly since the issue is not p5.js, but also happy and relieved because I'm really enjoying p5.js.

stalgiag, I'm grateful to you for your help and for sticking with me.  Thank you.  I think we can call this issue closed.
