### ISSUE TITLE
Getting nothing when trying to show image with the help of HTML tag

### ISSUE THREAD

**Issue by RadheTians** [processing/p5.js#4189]
I noticed that when I was trying to show an image on canvas with the help of HTML tags(i.e input tag and type is file) the codebase wasn't showing an image and when I was trying to show with the help of p5.js function `createFileInput(readImageURL);` then it is going to show.

#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [x] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.10.2
- Web browser and version: Chrome 78.0.3904.108
- Operating System: Linux 18.04
- Steps to reproduce this:

This is the sample code snippet that demonstrates the problem...  

```
<!DOCTYPE html>
<html>
  <head>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.10.2/p5.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.10.2/addons/p5.sound.min.js"></script>
    <meta charset="utf-8" />

  </head>
  <body>
    Upload image: <input type="file" name="image" onchange="readImageURL(this);" >
    <script type="text/javascript" charset="utf-8">
          let img;
          function setup() {
               var canvas = createCanvas(400, 400);
          }

          function draw() {
               background(255);
               if (img) {
                    image(img, 0, 0);
               }
   
          }

          function readImageURL(file) {
               print(file);
               if (file.type === 'image') {
                     img = createImg(file.data, ' ');
                     img.hide();
              } else {
                     img = null;
              }

    </script>
  </body>
</html>
```

The output of the above code is the following...

```<input type="file" name="image" onchange="readImageURL(this);" >```

**Comment by sweiss01** [comment]
Hi RadheTians, I think you've got a few issues going on here.  First, you're missing a closing '}' in the readImageURL() function.  Next, in readImageURL, I think the file name will be in file.value.  In Chrome, that may be something like 'C:\fakepath\...'.  If so, you can clean that up with something like 'let f = file.value.replace(/.*[\/\\]/, '')' and then do your createImg().

Give this a shot:

```
<!DOCTYPE html>
<html>
	<head>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.10.2/p5.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.10.2/addons/p5.sound.min.js"></script>
		<meta charset="utf-8" />

	</head>
	<body>
		Upload image: <input type="file" id="file1" name="image" onchange="readImageURL(this);" >
		<script type="text/javascript" charset="utf-8">
		let img;
		function setup() {
			var canvas = createCanvas(400, 400);
		}

		function draw() {
			background(255);
			if (img) {
				image(img, 0, 0);
			}
		 
		}

		function readImageURL(file) {
			console.log( file.value, file.type )
			if (file.type === 'image' || file.type == 'file') {
				let f = file.value.replace(/.*[\/\\]/, '')
				img = createImg(f, ' ');
				img.hide();
			} else {
				img = null;
			}
		}
		</script>
	</body>
</html>
```

**Comment by RadheTians** [comment]
Hello sweiss01, Thanks for your response I tried with your solution but, I got an error something like following ...

```
C:\fakepath\100.jpg file
100.jpg:1 GET http://127.0.0.1:8000/100.jpg 404 (Not Found)
Image (async)
_main.default.createImg @ p5.js:67917
readImageURL @ sketch.js:39
onchange @ (index):22
p5.js:61024 Uncaught DOMException: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The HTMLImageElement provided is in the 'broken' state.
    at _main.default.Renderer2D.image (https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.10.2/p5.js:61007:35)
    at p5._main.default.image (https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.10.2/p5.js:74875:28)
    at draw (http://127.0.0.1:8000/static/javascript/sketch.js:19:9)
    at p5._main.default.redraw (https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.10.2/p5.js:65953:19)
    at _draw (https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.10.2/p5.js:58869:25)
```

**Comment by sweiss01** [comment]
Yeah, I was afraid that might be the case.  I'm pretty sure you're bumping up against a browser security issue.  I tested on desktop instead of browser and used a local file and the file.value.replace code worked.  

I don't think this is a p5.js bug, though, so if you post the issue on https://discourse.processing.org/c/p5js, the folks there can help you get past this.  Sorry I couldn't help further.

**Comment by RadheTians** [comment]
Hello sweiss01, Thanks for another response and sorry for the inconvenience I tried with your solution in Chrome 78.0.3904.97, Firefox 71.0 & Microsoft edge 44.18362.449.0 but I got errors in all three browsers and I don't think your solution is going to work in any situation(i.e any browsers) because of you are just replacing something by something this can be lost pieces of information of image and as you said it's working on desktop there may be a chance it can work on desktop but your solution won't probably work on any browser.

**Comment by RadheTians** [comment]
After searching a lot I came up with this idea...

```
<!DOCTYPE html>
<html>
  <head>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.10.2/p5.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.10.2/addons/p5.sound.min.js"></script>
    <meta charset="utf-8" />

  </head>
  <body>
    
    <script type="text/javascript" charset="utf-8">
          let img;
          let input;
          function setup() {
               var canvas = createCanvas(400, 400);
               input = createFileInput(readImageURL);
               input.position(0,0);
          }

          function draw() {
               background(255);
               if (img) {
                    image(img, 0, 0);
               }
   
          }

          function readImageURL(file) {
               print(file);
               if (file.type === 'image') {
                     img = createImg(file.data, ' ');
                     img.hide();
              } else {
                     img = null;
              }

    </script>
  </body>
</html>
```

But my problem is still there and I'm not violating any browser security

**Comment by sweiss01** [comment]
It's hard for me to understand what's going on here because it works when I try.  Am I just misunderstanding your issue?  Is it that you want to display the uploaded image in a p5.js sketch, or that you want to dynamically create an html image?

**Comment by RadheTians** [comment]
I am just trying to display the uploaded image on` p5.js` canvas

**Comment by sweiss01** [comment]
Okay.  I don't think this is a p5.js bug yet.  I still suggest taking the discussion to the forum where a discussion like this is more appropriate.  When you run this now, what error are you seeing?  What information is in file.data?  Is the createImg() function being called?  Let's talk to the community about this stuff on the discourse forum, https://discourse.processing.org/c/p5js

**Comment by RadheTians** [comment]
Sure @sweiss01, let's discuss.
