### ISSUE TITLE
P5 syntax leads to scoping issues in Angular 8

### ISSUE THREAD

**Issue by Optiq01** [processing/p5.js#4190]
#### Nature of issue?

- [*] Found a bug
- [ ] Existing feature enhancement
- [*] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [*] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [*] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.10.2
- Web browser and version: Chrome 74.0.3729.169
- Operating System: Windows 7 64bit
- Steps to reproduce this:

Some of the P5 methods call for values that create confusion in my components.  The first issue I ran into was creating a canvas for 3D which I originally did as follows.

```
createGraphic(): void{
    const frame: FrameSize = this.meausreFrame();

    this.Scene = new p5(p=>{

          p.setup = ()=>{ p.createCanvas(frame.width, frame.height, WEBGL); };
          
    },
    this.GraphicContainer.nativeElement
    );
}
```

This wound up causing problems because `WEBGL` was being regarded as if it were a variable within the scope of my component which of course threw an error telling me it didn't exist on my component.  After getting help on stackoverflow I found out I needed to change the syntax to this.

`
p.setup = function(){ p.createCanvas(frame.width, frame.height, this.WEBGL); };
`

Due to however the library is setup that syntax somehow uses the `this` to make it point within the scope of the p5 module.  Just adding the `this.` with the arrow function syntax still made Angular search for it on he component.

Now I came to another problem with using the `angleMode();` method to set the mode to degrees.  The syntax for that is

```
p.draw = function(){

    p.angleMode(DEGREES);

}
```

Again Angular is looking at `DEGREES` as if it's something defined within the component.  I tried seeing if adding `this.` would work but I still got the same error reminding me it doesn't exist on the component.  I'm not sure of what to do at this point and was thinking of creating a pull request but thought I'd post this here first to see if maybe there's already some type of solution for handling this aspect of the syntax in platforms like Angular.

**Comment by lmccart** [comment]
in Instance mode, all p5 variables and functions should be preferred with your pointer `p.` in this case. So for example, you could write
```js
p.draw = function(){

    p.angleMode(p.DEGREES);

}
```

This should resolve the scoping issues. For more help, you can post on our forum: https://discourse.processing.org/
