### ISSUE TITLE
Autolabeler is overdoing it

### ISSUE THREAD

**Issue by stalgiag** [processing/p5.js#4202]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [ ] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 
The autolabeler is cool in theory but I am realizing that it won't work as desired with our template. It picks up too many irrelevant keywords.

**Comment by limzykenneth** [comment]
Quite agressive, and triage bot is also still acting weird, adding then removing the "triage" label for every new issue. Can't say I can help much but good luck.

**Comment by lmccart** [comment]
we could also change up the template if needed. if the bot is already picking up keywords, it may not be as necessary to have people specify specifically. I feel in general that the template, though helpful, can sometimes be a little intimidating with the amount of info it contains and asks for.

**Comment by stalgiag** [comment]
The template can seem overwhelming. It is difficult to parse and make sense of, but I do think it has quite a bit of success in encouraging people to remember to add certain details like code examples and operating systems.

I can try to ensure that the template doesn't include any label keywords. Perhaps also able to remove the amount of information in it as well. Like the 'Most appropriate sub-area of p5.js' section might not need to be a checkbox list. Maybe it could just be an open response instead since I think the main goal is to convert that information into labels.

Another option is having different templates for different kinds of issues. The issue templates feature on Github allow us to add multiple templates, so that when someone clicks 'New Issue' they go to a screen where they can click 'I have a bug', 'I have a feature request', or 'I have an idea for improving an existing feature'. If we do this, then we can reduce the complexity of any one template fairly easily.

And yes, the autotriage seems to act before the autolabeler and they sort of cancel each other out. Uninstallation definitely seems on the table for either or both of these right now. I am leaning a bit more towards trying to get the autolabeler working nicely and removing the autotriage. But open to opinions!

**Comment by stalgiag** [comment]
Closing as the autolabeler was uninstalled. Will look into reducing complexity of issue template. If a way forward for that is unclear, I will open another issue to track that.
