### ISSUE TITLE
The DOM docs aren't there

### ISSUE THREAD

**Issue by everythingability** [processing/p5.js#4208]
https://p5js.org/reference/#/libraries/p5.dom 

is empty.

**Comment by lmccart** [comment]
p5.dom has been merged into the core library, all docs for this can be found at p5js.org/reference. please let us know if you find any stray links to the above url and we will replace! thanks

**Comment by mag911** [comment]
Found a stray link whilst trying to read about p5.dom

https://p5js.org/examples/dom-modifying-the-dom.html

Modifying the DOM

Create DOM elements and modify their properties every time draw() is called. You will need to include the "**[p5.dom library](http://p5js.org/reference/#/libraries/p5.dom)**" for this example to work in your own project.
