### ISSUE TITLE
Are Streamed images supported with loadImage?

### ISSUE THREAD

**Issue by J-Cake** [processing/p5.js#4226]
#### Nature of issue?

- [ ] Found a bug
- [x] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [x] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: p5.js v0.10.2 October 14, 2019
- Web browser and version: Edge Chromium 80.0.361.9 (Official build) dev (64-bit) 
- Operating System: Windows 10 
- Steps to reproduce this: 
1) Web Server which serves images dynamically from URL and returns images in stream form
2) attempt to load image in `preload` function with `loadImage`
3) fail.

Message is : 

```
p5.js says: It looks like there was a problem loading your image. Try checking if the file path [http://localhost:1920/image?url=https%3A%2F%2Fimage.flaticon.com%2Ficons%2Fpng%2F512%2F270%2F270794.png] is correct, hosting the image online, or running a local server.[https://github.com/processing/p5.js/wiki/Local-server]
```

#### Feature enhancement details:
Add support for images that may be incomplete on the first received chunk. Buffer images and complete the function once the image has been fully loaded.

**Comment by limzykenneth** [comment]
How exactly is the image sent by the server? Does the client need to make multiple http requests?

**Comment by J-Cake** [comment]
The server is a nodejs + express server. Images are sent more or less
exactly like this:


```
app.get('/images', function (req, res) {
    const url = decodeUriComponent(req.query.url);

    request(url).pipe(res);
});
```

Note that the image is requested dynamically. It is not a static file.
Simplified, the user makes a request to the `imags` endpoint passing a
`url` query parameter with an encoded URI to the server. The server
requests the image and pipes it back to the client. This piping process
takes the full request and forwards it as-is to the client. Meaning, if the
original server returns it in 12 chunks, that's how the client will receive
it. The only difference is the `image` endpoint does not support Byte-Range
requests.

**Comment by limzykenneth** [comment]
It doesn't matter how many chunks are sent, to the browser they are all a single response. Unless the server is sending back multiple response, which without WebSockets or multiple requests the server cannot do, it still counts as one response.

You actually have a typo in your server code, it is `decodeURIComponent` instead of `decodeUriComponent`, the `URI` is all caps. In addition, if you are using express, you don't need to decode your query string, you can just do

```javascript
app.get('/images', function (req, res) {
    request(req.query.url).pipe(res);
});
```

With the above server code and `loadImage` in `preload` it loads just fine on my end.

**Comment by J-Cake** [comment]
Okay, that's good to know, as mentioned earlier, this is not the whole
code, in reality, I do some checks, but I guess it was a faulty image file
on the remote's behalf.

**Comment by J-Cake** [comment]
I've just made the connection actually, that makes perfect sense. I do
feels bit silly now.
