### ISSUE TITLE
Unecessary stroke notice when drawing a plane

### ISSUE THREAD

**Issue by Vamoss** [processing/p5.js#4235]
Hi, it seems like I found a bug.

This message that should not exist because I declared `noStroke()`.
> Cannot draw stroke on plane objects with more than 1 detailX or 1 detailY

Reproducible code:
https://editor.p5js.org/Vamoss/sketches/Ov0T1tQsP
```js
function setup() {
  createCanvas(400, 400, WEBGL);
  noStroke();
}

function draw() {
  background(0);
  plane(100, 100, 100, 100);
}
```

**Comment by stalgiag** [comment]
Yes, it is unnecessary.

A quick fix would [be to change this](https://github.com/processing/p5.js/blob/master/src/webgl/3d_primitives.js#L84) `else` to `else if(this._renderer._doStroke)`. 

All of the 'Cannot draw stroke ...' messages in the `src/webgl/3d_primitives.js` file should do this check.

**Comment by lmccart** [comment]
@jatin33 would you be interested in working on this?
