### ISSUE TITLE
More examples to add for const keyword

### ISSUE THREAD

**Issue by jatin33** [processing/p5.js#4242]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other (Foundation) 

#### Feature enhancement details:
We can add more examples for **const** keyword in foundational area.
i.e 
```
const arr = [1,2,3,4];
arr.push(5); // valid and works
arr = [3,4,5]; //gives error 
```
We can cover this for strings,objects and other compound data types.

**Comment by lmccart** [comment]
this would be great!
