### ISSUE TITLE
Add textLineHeight method to Typography

### ISSUE THREAD

**Issue by yashpandit** [processing/p5.js#4243]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [x] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### New feature details:
We can add functionality that can add spaces around a line(space on top and bottom of the line) which can be done in CSS by using line-height property.

Below is the behavior of line-height:
![lineHeightDemo](https://user-images.githubusercontent.com/26370910/72075312-7cd8bf80-3319-11ea-99a2-89f906857211.gif)

Can we add a method textLineHeight() to **Typography** module?

The signature of the function would be something like this:

```
/**
* N is the number of pixels
* @param {number} N
*/
function textLineHeight(N) {}
```

**Comment by yashpandit** [comment]
@lmccart - What do you think about this?

**Comment by limzykenneth** [comment]
This should be already covered by [`textLeading`](https://p5js.org/reference/#/p5/textLeading) unless you mean something else?

**Comment by yashpandit** [comment]
Correct me if I am wrong but textLeading only adds space below the text and keeps the baseline of the text the same(the content only goes down).

With textLineHeight, it actually increases the height of the line while keeping the text in the center and adds even spaces on the top and bottom of the text keeping it in the center so that the formatting looks even for all the lines.

**Comment by limzykenneth** [comment]
Ok I see what you mean. I feel that it's a bit niche and possibly some overlap with `textLeading` but I'll let other people chip in their thoughts on this as well. 😄

**Comment by ArjunwadkarAjay** [comment]
Can I claim this issue?

**Comment by limzykenneth** [comment]
@ArjunwadkarAjay I would like to get some opinions on this issue and workout the implementation outline before assinging anyone. Notably now that I've looked at this again, I a bit more hesitant to add this especially into the Typography module because the `line-height` property is added in CSS and not in the JS canvas API itself, which could cause problem with user defined CSS.

Any thoughts on this?

**Comment by ArjunwadkarAjay** [comment]
Can we just pass a parameter in the function mentioned and manipulate the css's line height property a particular mentionedtext.Thereby allowing flexibility to programmer

**Comment by ArjunwadkarAjay** [comment]
And sorry for replying to you late, as I was stuck in exams.

**Comment by limzykenneth** [comment]
> Can we just pass a parameter in the function mentioned and manipulate the css's line height property a particular mentionedtext.Thereby allowing flexibility to programmer

I don't quite get what you mean here. The problem I have here is the `textLineHeight()` function would necessarily modify the CSS property of the canvas which could cause conflict with user defined styling defined with `p5.Element` or in user created stylesheet.

**Comment by ArjunwadkarAjay** [comment]
@limzykenneth I thought about CSS property you mentioned, but mostly it would change the text property of the font rendered on the web page and not on canvas.
@yashpandit and @limzykenneth can we do it by adding empty text element to achieve this.
 A function can be created which can add a empty text before and after the actual text.
Pls do take a look at the example and tell if this idea is correct
[https://editor.p5js.org/Arjunwadkar/sketches/kB-un0EM](url)

**Comment by ArjunwadkarAjay** [comment]
@limzykenneth I thought about CSS property you mentioned, but mostly it would change the text property of the font rendered on the web page and not on canvas.
@yashpandit and @limzykenneth can we do it by adding empty text element to achieve this.
A function can be created which can add a empty text before and after the actual text.
Pls do take a look at the example and tell if this idea is correct
`function setup() {
  createCanvas(400, 400);
}

function draw() {
  background(220);
  textSize(32);
  text('', 10, 60-32);//line of empty text for getting the space
  fill(0, 102, 153);
  text('word', 10, 60);
  text('', 10, 60+32);//line of empty text for getting the space
  fill(0, 102, 153);
  text('word1', 10, 60+32+32);
  text('',10,60+32+32+32);//line of empty text for getting the space
  text('word2', 10, 60+32+32+32+32);
}`

**Comment by ArjunwadkarAjay** [comment]
So @yashpandit can try to work on this in the mentioned manner?
And @yashpandit and @limzykenneth plz tell if it is possible as well.

**Comment by limzykenneth** [comment]
@ArjunwadkarAjay Yeah, you're right about CSS, not sure what I was on about. CSS should not come into this.

There isn't a need to draw an empty string to get some space as if you draw nothing there, nothing is there. You can just skip to drawing the first line `text('word', 10, 60);` then the next `text('word1', 10, 60+32+32);`. But this is also not quite what `textLineHeight()` is meant for.

Assuming `textLineHeight()` is a variation similar to `textLeading()`, it is meant to be used for something like this:
```javascript
// Text to display. The "\n" is a "new line" character
let lines = 'L1\nL2\nL3';
textSize(12);

textLineHeight(10); // Set line height to 10
text(lines, 10, 25);

textLineHeight(20); // Set line height to 20
text(lines, 40, 25);

textLineHeight(30); // Set line height to 30
text(lines, 70, 25);
```

The way `textLeading()` achieve this is through manipulating the final font size on the element. The code is a bit complicated so I haven't gone through it in detail yet but it's [here](https://github.com/processing/p5.js/blob/0.10.2/src/core/p5.Renderer.js#L341). I'm not sure how possible it is to work `textLineHeight()` in, especially to consider compatibility with `textLeading()` as well. This will require more investigating.

**Comment by dhowe** [comment]
Perhaps defining textLeading and textLineHeight (line-height) would help to determine if we need both. My (cursory) understanding is that they are similar except that with leading, space is added above the text (this would start on the 2nd line of a paragraph, see 1st img below), while with line-height it is split above and below.  

The problem with textLineHeight for our API is that we specify the position of the text with x,y pixel coordinates (as we do all drawing), so these values would no longer be correct if textLineHeight was set (the text would not appear at the specified x,y coordinates).

It seems to me that one can simulate the behavior of textLineHeight by setting vertical textAlign to CENTER and using textLeading  (as in img2), but perhaps I am missing some subtlety here.

![Screenshot 2020-05-28 at 2 18 39 PM](https://user-images.githubusercontent.com/737638/83106523-34b31180-a0ef-11ea-94d8-e791c60792c1.png)

![Screenshot 2020-05-28 at 2 22 50 PM](https://user-images.githubusercontent.com/737638/83106535-37ae0200-a0ef-11ea-99cf-1c585f89c528.png)

**Comment by munusshih** [comment]
Suggestion to close this issue.
