### ISSUE TITLE
Adding method for applying tracking for fonts in typography

### ISSUE THREAD

**Issue by jatin33** [processing/p5.js#4244]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [x] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### New feature details:
We can add a method to apply tracking for given text to the **Typography** module.
You can look for more details about tracking [here](https://en.wikipedia.org/wiki/Letter-spacing)
Basically, tracking means letter-spacing throughout given text.

> Tracking involves adjusting the spacing throughout the entire word. Once you've determined the right spacing between each letter, tracking can be used, with great restraint, to change the spacing equally between every letter at once.

Visual example:
![image](https://user-images.githubusercontent.com/13780467/72080689-35573100-3323-11ea-8602-3d50d1d792ef.png)

So I think it will be useful if we provide a method for adding letter-spacing in Typography module.

```
/**
* @params {number} pixels
*
*/
function letterSpacing(pixels) {}
```

**Comment by jatin33** [comment]
@lmccart , @limzykenneth  What are your thoughts about this?

**Comment by limzykenneth** [comment]
It has been looked at before at #3800 and #3223 and basically there isn't support for it in HTML canvas, at least at that time. Rolling our own text drawing renderer just to enable tracking is a bit overkill so unless there's a way to implement this simply I'm not sure we can add it in.

**Comment by lmccart** [comment]
I agree with @limzykenneth, I think this is beyond our scope for right now.

**Comment by Vamoss** [comment]
Sorry to answer in a closed issue, but this hack may help others in future.

https://editor.p5js.org/Vamoss/sketches/x4Z8KBms
```js
let ctx;
function setup() {
  let renderer = createCanvas(600, 200);
  ctx = renderer.drawingContext;

  textAlign(CENTER, CENTER);

  //This dont work
  //textFont("monospace")
}

function draw() {
  background(0);
  fill(255);

  //letter spacing from CSS
  select('canvas').elt.style.letterSpacing = "80px";

  //This works
  ctx.font = '100px monospace';

  text('TEXT', width / 2, height / 2);
}
```

Results:
<img width="598" alt="Captura de Tela 2020-02-02 às 13 00 45" src="https://user-images.githubusercontent.com/245841/73610995-14010200-45bc-11ea-975a-75ae72d01391.png">
