### ISSUE TITLE
deltaTime is undefined

### ISSUE THREAD

**Issue by skycodr** [processing/p5.js#4248]
Chrome throws an error saying deltaTime is not defined. But the documentation mentions to use it the way I have written below. However, p5.deltaTime doesn't seem to work either.

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [X] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug: 

- p5.js version: v0.7.3
- Web browser and version: Chrome 79.0.3945.88 (Official Build) (64-bit)
- Operating System: Windows 10
- Steps to reproduce this:
```
function draw() {
  background(0);
  noStroke();

  if(canUpdate(delatTime)){
    snake.update(direction);
  }
  
  board.show();
  snake.show();
}
```

**Comment by stalgiag** [comment]
You are using an older version of p5. In order to use `deltaTime` you will need to use version 0.9.0 or later.

Closing for organization purposes. Good luck!
