### ISSUE TITLE
docs missing for JSON.parse 

### ISSUE THREAD

**Issue by jatin33** [processing/p5.js#4253]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other (Foundation)

#### Feature enhancement details:
We should add JSON.parse() method in Foundation module under JSON. This method helps in converting JSON string to JS Object.

**Comment by lmccart** [comment]
This one is a little less clear for me, because our `loadJSON()` method actually returns an object, not JSON. So I'm wondering how this function would fit in with the rest of the p5 library.

**Comment by jatin33** [comment]
I thought that if we have  JSON object then we should have mentioned both methods supported by it. However, in our library we are using loadJSON() for parsing JSON strings, then there is no point in adding documentation for JSON.parse(). Shouldn't loadJSON() be documented under JSON? As it covers functionality related to JSON.

**Comment by lmccart** [comment]
I think the current placement with the Input methods makes sense. If it were in the Foundation section, this would imply it was a JS method rather than a p5 one.

**Comment by jatin33** [comment]
So I think this issue is resolved.
