### ISSUE TITLE
P5js not downloading (Followup!)

### ISSUE THREAD

**Issue by Samisaprogrammer** [processing/p5.js#4254]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other (specify if possible)
P5 not downloading (Followup)
#### Details about the bug: 

- p5.js version: p5.js v0.10.2 October 14, 2019
- Web browser and version: Google Chrome | 79.0.3945.117 (Official Build) (64-bit) (cohort: Stable)

- Operating System:  Windows 10
- Steps to reproduce this: Try downloading the file.

When you try do download anything then it doesn't download. How this can be fixed is simple.
Just host the file on p5js.org! I am making a follow up to my last bug thingy.

**Comment by lmccart** [comment]
Can you describe what happens when you click the download button? And which button are you clicking?

**Comment by Samisaprogrammer** [comment]
Well, it takes me to this. https://p5js.org/download/support.html
I clicked the download complete thingy button at https://p5js.org/download and I tried editing the html, the link works but the button doesn't.

**Comment by lmccart** [comment]
Hm the download should start automatically, in addition to you being redirected. Can you please provide a screenshot of your chrome settings confirming that your downloads are not blocked by chrome?

<img width="1314" alt="Screen Shot 2020-01-15 at 4 52 54 PM" src="https://user-images.githubusercontent.com/191056/72483937-8b125a00-37b7-11ea-988e-476e98ebc5b5.png">
<img width="714" alt="Screen Shot 2020-01-15 at 4 53 09 PM" src="https://user-images.githubusercontent.com/191056/72483938-8b125a00-37b7-11ea-8349-e6ba2b99900a.png">

**Comment by stalgiag** [comment]
I am able to reproduce but only on Windows. Works as expected on Mac with Safari and latest Chrome.

Redirects to Support page without download on Windows with Chrome 79.0.3945.117 and Firefox 72.0.2.

It has worked on my Windows computer with both of these browsers until very recently. Let me know if I can be helpful.

![Screenshot (212)](https://user-images.githubusercontent.com/10382506/72753923-1f473d00-3b7b-11ea-9a52-16d735f8b83d.png)

**Comment by stalgiag** [comment]
Edit: this does not happen for me every time, but roughly 7 out of 10 times.

**Comment by lmccart** [comment]
thanks @stalgiag. i just pushed a small update. can you try testing again with a cleared cache?

**Comment by stalgiag** [comment]
Works great in both browsers now! Thanks @lmccart .
