### ISSUE TITLE
Creating a color with a string and an alpha value

### ISSUE THREAD

**Issue by Haksell** [processing/p5.js#4257]
#### Most appropriate sub-area of p5.js?
- [x] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### New feature details:
I would like to be able to create a color with a string and an alpha value, like so: `color("red", 127);`, and to use `fill` and `stroke` the same way.
It would be especially useful for beginners.

**Comment by lmccart** [comment]
we've discussed this a bit here: https://github.com/processing/p5.js/pull/2043
