### ISSUE TITLE
Elements created with createDiv contain text 'undefined' if no inner html is specified

### ISSUE THREAD

**Issue by lizstarin** [processing/p5.js#426]
For instance, this js: 
`var sidebar = createDiv();  
sidebar.id("sidebar");`
produces this html:
`<div id="sidebar">undefined</div>`

**Comment by austince** [comment]
Heyo, I think this is still a problem in 0.6.0. [Here's a Codepen example.](https://codepen.io/austince/pen/OQPqov/)

I'll put in a PR shortly
