### ISSUE TITLE
printMatrix() error points to url which no longer exists

### ISSUE THREAD

**Issue by DtheC** [processing/p5.js#4261]
Calling `printMatrix()` throws an error:
`Uncaught Error: printMatrix() is not implemented in p5.js, refer to [https://simonsarris.com/a-transformation-class-for-canvas-to-keep-track-of-the-transformation-matrix/] to add your own implementation.`
But the url: https://simonsarris.com/a-transformation-class-for-canvas-to-keep-track-of-the-transformation-matrix/ is a 404 and I can't seem to find an archive of this page either. Might be best to remove this in a future release.

**Comment by ashu8912** [comment]
YEAH this needs to be removed i can work on it.

**Comment by lmccart** [comment]
great thanks @ashu8912
