### ISSUE TITLE
Set the fill transparency of a vertex-based polyhedron in WEBGL with .setAlpha() is not working with faces which have to stroke too

### ISSUE THREAD

**Issue by woollyBird666** [processing/p5.js#4262]
#### Most appropriate sub-area of p5.js?

- [x] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Details about the bug: 

- p5.js version: 0.10.2, October 14, 2019
- Web browser and version: Google Chrome | 79.0.3945.130 (Build officiel) (64 bits)
- Operating System: MacOSX
- Steps to reproduce this:

``` Javascript
var i, j;       // Vertex parameters
var r = 60;    // Scale factor
var speed = 8; // Speed factor

var cubocWeight = r/30;

var vertices, faces;
var fillColor, strokeColor;
var ambientLightColor, pointLightColor;

function setup(){
  createCanvas(windowWidth, windowHeight, WEBGL);
  frameRate(30);
  setAttributes('antialias', true);

  // Set colors
  // Light colors ...
  ambientLightColor=color('#AAAAAA');
  pointLightColor=color('#FFFFFF');

  // Polygon colors ...
  fillColor=color('#348EE8');
  strokeColor=color('#AAC9E8');

  i=1;j=1; // Regular cuboctahedron

  vertices = [
    {x:0, y:0, z:1.154701},
    {x:1, y:0, z:0.5773503},
    {x:0.3333333, y:0.942809, z:0.5773503},
    {x:-1, y:0, z:0.5773503},
    {x:-0.3333333, y:-0.942809, z:0.5773503},
    {x:1, y:0, z:-0.5773503},
    {x:0.6666667, y:-0.942809, z:0},
    {x:-0.6666667, y:0.942809, z:0},
    {x:0.3333333, y:0.942809, z:-0.5773503},
    {x:-1, y:0, z:-0.5773503},
    {x:-0.3333333, y:-0.942809, z:-0.5773503},
    {x:0, y:0, z:-1.154701}
  ];

  faces = [
    // Triangles
    {s1:0, s2:1, s3:2},
    {s1:0, s2:3, s3:4},
    {s1:1, s2:6, s3:5},
    {s1:2, s2:8, s3:7},
    {s1:3, s2:7, s3:9},
    {s1:4, s2:10, s3:6},
    {s1:5, s2:11, s3:8},
    {s1:9, s2:11, s3:10},

    // Rectangles
    {s1:0, s2:2, s3:7, s4:3},
    {s1:0, s2:4, s3:6, s4:1},
    {s1:1, s2:5, s3:8, s4:2},
    {s1:3, s2:9, s3:10, s4:4},
    {s1:5, s2:6, s3:10, s4:11},
    {s1:7, s2:8, s3:11, s4:9},
  ];
}

function draw(){
  background(30);

  // Lights
  ambientLight(ambientLightColor);
  pointLight(pointLightColor, 0,0,-1000);

  push();

  translate(0,-200,0);

  // Rotation
  var angle = (frameCount*speed/100)%360;

  rotateX(angle);
  rotateY(angle);
  rotateZ(angle);

  drawCuboctahedron();

  pop();
}

function drawCuboctahedron (){
  var fillAlpha=200;

  for(let f of faces){
    if (f.s4){
      // Filling the polyhedron
      fillColor.setAlpha(fillAlpha);
      fill(fillColor);

      noStroke();

      beginShape()

      vertex(vertices[f.s1].x*r,vertices[f.s1].y*r, vertices[f.s1].z*r);
      vertex(vertices[f.s2].x*r,vertices[f.s2].y*r, vertices[f.s2].z*r);
      vertex(vertices[f.s3].x*r,vertices[f.s3].y*r, vertices[f.s3].z*r);
      vertex(vertices[f.s4].x*r,vertices[f.s4].y*r, vertices[f.s4].z*r);
      vertex(vertices[f.s1].x*r,vertices[f.s1].y*r, vertices[f.s1].z*r);

      endShape(CLOSE)

    } else {
      fillColor.setAlpha(fillAlpha);
      fill(fillColor);

      strokeWeight(cubocWeight);
      stroke(strokeColor);

      beginShape()

      vertex(vertices[f.s1].x*r,vertices[f.s1].y*r, vertices[f.s1].z*r);
      vertex(vertices[f.s2].x*r,vertices[f.s2].y*r, vertices[f.s2].z*r);
      vertex(vertices[f.s3].x*r,vertices[f.s3].y*r, vertices[f.s3].z*r);

      endShape(CLOSE)
    }
  }
}
```

You can see the bug's result right below, all the square-based faces are filled, but not the triangle-based. This is weird. The only difference is that the square-based faces are noStroke() and the triangle-based are stroked.

<img width="415" alt="cuboctahedron_issue" src="https://user-images.githubusercontent.com/45451250/72747566-4b7faf80-3bb5-11ea-9fd1-4dd143a0f5dc.png">

The weird thing is happening when I pass 255 as the value of the **fillAlpha** variable : all the faces are filled correctly. When I downgrade the value of 1, from 255, to 254, the filled-bug is right back :(

Hope that you can help me on this weird issue, thanks in advance :-)

Have a good day 🌸

**Comment by stalgiag** [comment]
Hi @woollyBird666 

Thanks for the well-written issue! Would you be able to simplify the example a bit? The simplest possible example that reproduces the bug would be really great. This makes it easier for us to sort out the problem. Perhaps you can try to draw just one rectangle without the working fill?

Thank you!

**Comment by woollyBird666** [comment]
Hi @stalgiag,

Thanks for your prompt response 👍

 This is the shortest code I can do, I suppose, to illustrate the issue :

``` Javascript
function setup(){
  createCanvas(windowWidth, windowHeight, WEBGL);
}

function draw(){
  background(128);

  rotateY(frameCount * 0.02);

  // Set colors
  fill(255, 254);
  //fill(255, 128);

  strokeWeight(5);
  stroke(255, 0, 0);
  //noStroke();

  // Scale factor
  var Scale = 150;

  // Shape #1
  beginShape();

  vertex(-1 * Scale, -1 * Scale, -1 * Scale);
  vertex(1 * Scale, -1 * Scale, -1 * Scale);
  vertex(1 * Scale, 1 * Scale, -1 * Scale);
  vertex(-1 * Scale, 1 * Scale, -1 * Scale);

  endShape(CLOSE);

  // Shape #2
  beginShape();

  vertex(-1 * Scale, -1 * Scale, 1 * Scale);
  vertex(1 * Scale, -1 * Scale, 1 * Scale);
  vertex(1 * Scale, 1 * Scale, 1 * Scale);
  vertex(-1 * Scale, 1 * Scale, 1 * Scale);

  endShape(CLOSE);
}
```

This simple code is just rotating two vertex-based squares with a fill alpha of 254 arround the Y axis. You can see that the **front square** is not transparent, which is consistent related to the alpha value, but the **other square** is totally transparent. This is crazy because they both have the same fill and alpha value !

When I uncomment the lines **fill(255, 128)** and **noStroke()**, the issue disappear. So I think this is caused by the correlation between the fill() and stroke() function in this context.

*The Front square:*

<img width="1097" alt="Capture d’écran 2020-01-21 à 12 42 07" src="https://user-images.githubusercontent.com/45451250/72802251-a237c880-3c4b-11ea-9236-a56651fa0d93.png">

*The other square:*

<img width="1097" alt="Capture d’écran 2020-01-21 à 12 42 16" src="https://user-images.githubusercontent.com/45451250/72802254-a6fc7c80-3c4b-11ea-8aac-5cfcff1d1f59.png">

Thanks for helping again !!!

Have a good day 🌸

**Comment by woollyBird666** [comment]
I just tried with quad() instead of buiding the squares with vertexes to minimize my syntax ; The issue is still there. See the code right below :

``` Javascript
function setup(){
  createCanvas(windowWidth, windowHeight, WEBGL);
}

function draw(){
  background(128);

  rotateY(frameCount * 0.02);

  // Set colors
  fill(255, 254);
  // fill(255, 128);

  strokeWeight(5);
  stroke(255, 0, 0);
  // noStroke();

  // Scale factor
  var Scale = 150;

  // Shape #1
  quad(-Scale, -Scale, -Scale, Scale, -Scale, -Scale, Scale, Scale, -Scale, -Scale, Scale, -Scale);

  // Shape #2
  quad(-Scale, -Scale, Scale, Scale, -Scale, Scale, Scale, Scale, Scale, -Scale, Scale, Scale);
}
```

As the front square is correctly filled before rotating, may be the issue is caused by the correlation between these two functions ?

🌸

**Comment by stalgiag** [comment]
Thank you for the examples! I'll check it out.
