### ISSUE TITLE
WebGL : blendMode() + fill( opaque-colour ) = no-blending

### ISSUE THREAD

**Issue by Daandelange** [processing/p5.js#4266]
#### Most appropriate sub-area of p5.js?

- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Color
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Details about the bug: 

- p5.js version: 0.10.2 (`editor.p5js.org` version)
- Web browser and version: `Vivaldi 2.10.1745.23 (64-bit) (Chrome 79.0.3945.94)` & `Firefox 72.0.2 (64-bit)`
- Operating System: MacOSX 10.12.0
- Steps to reproduce this:

Hello,
I think that I found a misbehaviour with the new WEBGL blendModes implementation #3650.
In a WEBGL context, `blendMode()` doesn't apply when the fill() colour's alpha value equals 100%.
````
blendMode(MULTIPLY);
fill(255,255); // <-- change alpha to 244 and it works as expected.
rect(0,0,width,height); // MULTIPLY not applied
````
See this working example: https://editor.p5js.org/daan/sketches/DR9EkRCe

I'm not used to p5.js's internal mechanisms... is this indeed a processing misbehaviour ?

Switching to another blendingMode doesn't resolve the issue.
I figured out that there's no call made to `p5.RendererGL.prototype._applyBlendMode()` when using fill() with any colour being 100% opaque. As soon there's some transparency in the fill colour, `_applyBlendMode()` is called and p5.js applies the blending mode as expected.

**Comment by AnuragGupta93** [comment]
@Daandelange This is the expected behavior of blend method. If you have alpha = 1, why would it blend with others? However, if the alpha value is less than 1, we need to enable blending on the gl context.

**Comment by Daandelange** [comment]
I don't understand why this is expected. Normally in openGL, blending happens regardless of alpha values.
> Let's say: we have a black background, we draw white on it with MULTIPLY: 
> `rgb(0,0,0)*rgb(1,1,1)` = `rgb(0*1,0*1,0*1)` = `rgb(0,0,0)`
> Adding an alpha channel:
> `rgba(0,0,0,1)*rgba(1,1,1,1)` = `rgba(0*1,0*1,0*1, 1*1)` = `rgba(0,0,0,1)`
> Processing's result: `rgba(1,1,1,1)`

Does that make more sense ?
Anyways, coming from a C++ background, this behaviour is very confusing for me.  
This [JS example](https://www.andersriggelsen.dk/glblendfunc.php) also blends colours without alpha while showing underlying math.

**Comment by stalgiag** [comment]
Thanks for the well-written issue and the thorough example!

Both sides of the posted example should be basically identical. @AnuragGupta93 your logic is true for whether we do depth testing, but it shouldn't determine whether blending is enabled. The logic is a bit tangled in `_applyColorBlend` as @Daandelange points out. Though it is different in `master` due to some optimization changes, this incorrect behavior was still carried over by those changes.

Perhaps somewhat related to #4262

**Comment by Daandelange** [comment]
That was quick, thanks for fixing this! 🙂
