### ISSUE TITLE
master

### ISSUE THREAD

**Issue by Long16837** [processing/p5.js#4279]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

**Comment by stalgiag** [comment]
Hello I am closing this issue as there is no descriptive information in it. If this isn't on purpose feel free to open another issue with a descriptive title and a completed issue template. Thanks!
