### ISSUE TITLE
p5.Vector equality function

### ISSUE THREAD

**Issue by zaerl** [processing/p5.js#428]
What about an equality function which tests if two vectors are equal? The implementation is trivial:

```javascript
p5.Vector.prototype.eq = function(x, y, z) {
  if (x instanceof p5.Vector) {
    x = x.x || 0;
    y = x.y || 0;
    z = x.z || 0;
  } else if(x instanceof Array) {
    x = x[0] || 0;
    y = x[1] || 0;
    z = x[2] || 0;
  } else {
    x = x || 0;
    y = y || 0;
    z = z || 0;
  }
  
  return this.x == x && this.y == y && this.z == z;
};
```

**Comment by lmccart** [comment]
@shiffman thoughts on this one?

**Comment by shiffman** [comment]
Sure, sounds great!  Is there a naming convention anywhere else in the API where equality is tested?  I would be in favor of the full `equals()`.  Happy to implement, will self-assign, but you are welcome to submit a pull request @zaerl.

**Comment by lmccart** [comment]
cool, yeah I couldn't find any convention but I think sticking to full words when possible is the style we aim for.

**Comment by zaerl** [comment]
Should I send a pull request?

**Comment by shiffman** [comment]
Go for it!  It's on my list to get to but I just haven't blocked out the time yet.  Happy for someone to take it first!

**Comment by zaerl** [comment]
OMG sorry for the spurious commits but I had github+sourcetree opened at the same time.
