### ISSUE TITLE
Allow mult and div vector math functions to take 2 vectors as arguments

### ISSUE THREAD

**Issue by aferriss** [processing/p5.js#4283]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [X] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Feature enhancement details:

Currently the vector math functions let you add or subtract two vectors together as `p5.Vector.add(v0, v1);` or `p5.Vector.sub(v0, v1)` but for multiplication and division you can only do operations between scalars and vectors `p5.Vector.mult(2, v0)`. 

I think it'd be great if we could add in function signatures for mult and div so that you can do math between two vectors. For example: `p5.Vector.mult(v0, v1)` or `p5.Vector.div(v0, v1)` 

The original mult / div by scalar functionality of these methods would remain the same (non-breaking change).

This would do component wise multiplication or division. Here's another example of how I'm imagining this would work below

```
const v0 = createVector(1, 2);
const v1 = createVector(3, 4);
const v2 = createVector(5, 6);
const multResult = p5.Vector.mult(v0, v1); // (3, 8)
const divResult = p5.Vector.div(v1, v0); // (3, 2)

// Another example 
const anotherMultResult = v2.mult(v1); // (15, 24)
const anotherDivResult = v2.div(v0); // (5, 3)
```

**Comment by aferriss** [comment]
Also, I would add that I'd be happy to work on this if it gets the greenlight!

**Comment by aferriss** [comment]
I went ahead and wrote this up here https://github.com/aferriss/p5.js/tree/vector-mult-div

I think it'd be a handy addition but it'd be great to get some feedback!

**Comment by dskeithbuck** [comment]
I'd love to see this added, it was something I was missing on a recent project.

**Comment by limzykenneth** [comment]
I think this is fine to add. Any thoughts @stalgiag @lmccart?

**Comment by lmccart** [comment]
@limzykenneth seems reasonable to me!

**Comment by stalgiag** [comment]
Yeah I definitely agree with this addition. Thanks @aferriss !
