### ISSUE TITLE
Errors from fork emailed to users that merge pull requests

### ISSUE THREAD

**Issue by stalgiag** [processing/p5.js#4294]
The Twitter Together Github action is failing on @Mattlk13 's fork of p5.js and alerting anyone that makes a merge in the upstream (this repo) via email. The error is:
```
##[error]HttpError: Resource not accessible by integration
```
Because the fork is trying to run our twitter github actions but of course it cannot and should not. @gr2m has pointed out that it might be [due to some automatio](https://github.com/Mattlk13/p5.js/pull/92)n on that user's fork.

**Comment by gr2m** [comment]
Oh I think I know what's going on. I check if the pull request head is a fork in which case I do not try to create a check run. In this particular pull request, the pull request head is not the fork, the base is the fork 🤔 I might just add a check for that, too, to resolve the problem. I made an issue here: https://github.com/gr2m/twitter-together/issues/104

**Comment by stalgiag** [comment]
This seems to be fixed over here. Closing for now.

**Comment by gr2m** [comment]
yay :)
