### ISSUE TITLE
createVector() reference example clarity

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js#4301]
#### Most appropriate sub-area of p5.js?
* Math

#### Feature enhancement details:

Hi! I'm teaching about `p5.Vector` in my course this semester and students were confused by [the example provided with the reference](https://p5js.org/reference/#/p5/createVector) for `createVector()`. 

```javascript
  pointLight(color(255), createVector(sin(millis() / 1000) * 20, -40, -10));
```

Since it involves `WEBGL`, `sin()`, and `millis()` it's difficult to parse out what the vector is actually doing. I would like to propose something simpler with a more direct visual. For example:

![example (1)](https://user-images.githubusercontent.com/191758/74765622-f4233c80-5251-11ea-8e2d-1784dddd27a6.png)

```javascript
function setup() {
  createCanvas(100, 100);
  let v = createVector(75, 50);
  background(255);
  fill(127);
  ellipse(v.x, v.y, 16);
  line(0, 0, v.x, v.y);
}
```

Or I'm open to other ideas! If this makes sense I'll make a pull request.

**Comment by aferriss** [comment]
@shiffman you are not alone! I believe someone is working on this https://github.com/processing/p5.js/issues/4285

**Comment by shiffman** [comment]
Oh, hah, indeed! The issue I'm guessing was filed by @hellonearthis after I showed the page during a live stream. . I noted to myself to file an issue and the internet is just much faster than me! I'll close this and follow-up can be in #4285. Feel free to use my example code above @aajaggi if you like!
