### ISSUE TITLE
WebGL blendMode MULTIPLY gives unexpected results.

### ISSUE THREAD

**Issue by yousifalyousifi** [processing/p5.js#4320]
#### Most appropriate sub-area of p5.js?

- [x] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Details about the bug: 

- p5.js version: current p5js editor
- Web browser and version: Firefox 72, Chrome 80
- Operating System: Windows 7
- Steps to reproduce this: 

Uncomment Line 47 in
https://editor.p5js.org/yousifalyousifi/sketches/I31c18He

The sketch does three things.
1. Draws rectangles
2. Draws a "stencil" on top to cutout a shape in the centre
3. Draws a textured (with transparency) plane to give a vertical grain effect.

![firefox_n96LCJXJcZ](https://user-images.githubusercontent.com/5132105/75116998-bcded200-563b-11ea-88a7-d92457fa86bb.png)

I want the grain effect to be blended with MULTIPLY. But when doing so it messes up the stencil.

After enabling MULTIPLY blending:
![firefox_w2UTaBocs9](https://user-images.githubusercontent.com/5132105/75116999-c10aef80-563b-11ea-8a45-d181af7acb88.png)

This doesn't seem like expected behavior, correct me if I'm wrong.

Thanks

**Comment by stalgiag** [comment]
Perhaps related to #4267 . I will check it out tomorrow. Thanks for the well-written issue!
