### ISSUE TITLE
model() does not respond to lighting as expected

### ISSUE THREAD

**Issue by flomerboy** [processing/p5.js#4329]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Details about the bug: 

- p5.js version: 
0.10.2
- Web browser and version: 
chrome  80.0.3987.122 (Official Build) (64-bit)
- Operating System: 
mac Mojave 10.14.6
- Steps to reproduce this:

1) run this code: 

  function preload(){
    roundedCube = loadModel('https://cdn.glitch.com/4562e6c1-bf45-495d-ab67-0d9bbcfbb7e0%2FCube.stl');
  }

function setup() {
  createCanvas(100, 100, WEBGL);
}
function draw() {
lights();
noStroke();
  scale(.2,.2,.2);
  background(255);
  rotateY(millis() / 1000);
  model(roundedCube);
  translate(0,200,0);
  box();
}

2) observe that the "box" reacts to lights "normally" but the roundedCube's faces seem to not respect a consistent source of light.

**Comment by stalgiag** [comment]
Hi @flomerboy thanks for the issue. The normals in your file seem good. I converted your file to obj to see if that changed the behavior, and the lighting is correct after the conversion. Perhaps something related to how `vertexNormals` are being decoded from Binary STL files. @sanketsingh24 do you have any ideas?

**Comment by AnuragGupta93** [comment]
@stalgiag I would like to work on this issue. It seems to me this problem arises due to incorrect parsing of STL files (either in vertex or vertexNormals). Sending a PR in a while.

**Comment by flomerboy** [comment]
Thanks for helping on this! The OBJ workaround should work for me but
consistent behavior is ideal.

**Comment by AnuragGupta93** [comment]
@flomerboy This issue is fixed. You can use STL files after the merging of this PR.

**Comment by flomerboy** [comment]
What version of the library will this work in? Still observing the bug in my project
