### ISSUE TITLE
README.md forum link outdated

### ISSUE THREAD

**Issue by stu01509** [processing/p5.js#4338]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other (specify if possible)

README.md forum link seems outdated, 
Maybe change the link https://forum.processing.org/two/categories/p5-js to https://discourse.processing.org/c/p5js

If yes, I will create a new PR.

**Comment by limzykenneth** [comment]
@stu01509 Go ahead with the change, I'll assign the issue to you. Thanks.
