### ISSUE TITLE
Image.pixels new (buggy) behaviour for non int indices

### ISSUE THREAD

**Issue by makeyourownneuralnetwork** [processing/p5.js#4345]
The Image.pixels(indie) gets the R,G,B or A values from a pixel array.

Previously, it worked fine when the index was not-integer. 

Now it fails in an unusual way that is not obvious. It still returns results with out stoppig the code or reporting an error/warning, but the pixel it actually returns is the wrong one.

My previous code, used as a teaching tutorial, worked fine .. then suddenly stopped working recently... after long investigation, adding int() around the x and y variables fixed it. (the index is calculated from the x and y)

[https://www.openprocessing.org/sketch/689867](https://www.openprocessing.org/sketch/689867)

I realise the index should be an integer, so I think that previously it was correctly handled in the pixel() method ... and now it isn't but worse it is not caught as an error. Silent but wrong functioning is the worse option I feel.

Sorry I am not an expert in the p5 source code to find the root change that caused this.

**Comment by stalgiag** [comment]
Hi @makeyourownneuralnetwork thanks for the issue and example code!

I am having a bit of trouble following. There is not a `pixels` method in p5. After calling `img.loadPixels()`, a p5.Image will have a `pixels` property which is [an array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Indexed_collections). Our library has no influence over how non-integer numbers are interpreted when accessing an array.

Let me know if I am missing something.

**Comment by makeyourownneuralnetwork** [comment]
you are correct, after img.loadPixels() we have a pixels property. I didn't know this was a standard javascript array.

does this mean javasript's own behaviour had changed?

the code I use has not changed but over the last 2 years the behaviour did change.

if this is outside p5js then I'll close the issue.
