### ISSUE TITLE
beginShape()/endShape() ignores noFill() with WEBGL in 1.0

### ISSUE THREAD

**Issue by ffd8** [processing/p5.js#4350]
#### Most appropriate sub-area of p5.js?

- [x] WebGL

#### Details about the bug: 

- p5.js version: 1.0
- Web browser and version: Safari + Brave
- Operating System: MacOS 10.13.6
- Steps to reproduce this:

Code for a complex shape, with `noFill()`, using WEBGL:
```
function setup() {
	createCanvas(400, 400, WEBGL);
}

function draw() {
	background(150);
	stroke(0);
	noFill();
	randomSeed(11);
	beginShape();
	for(let i=0; i < 5; i++){
		let off = width * .4;
		vertex(random(-off, off), random(-off, off));
	}
	endShape();
}
```

In v0.10.2 it renders as:
<img width="398" alt="Screen Shot 2020-03-06 at 14 33 09" src="https://user-images.githubusercontent.com/570957/76088054-a891c200-5fb7-11ea-8413-16cf499edb24.PNG">

In v1.0.0 is renders as:
<img width="398" alt="Screen Shot 2020-03-06 at 14 33 29" src="https://user-images.githubusercontent.com/570957/76088077-b1829380-5fb7-11ea-9f32-5af30e27527b.PNG">

**Comment by DivyamAhuja** [comment]
@stalgiag Should this issue be addressed? as fill(0,0,0,0) temporarily solves this
and other way I tried is by checking for this._doFill before drawImmediateFill is called 
and it's working fine

![Screenshot from 2020-03-12 13-53-35](https://user-images.githubusercontent.com/39771050/76501913-20a13180-6469-11ea-9798-761822b54813.png)

So should I solve the issue this way ?

**Comment by stalgiag** [comment]
Thank you for reporting this @ffd8 !

Hi @DivyamAhuja yes that solution should work well. I think checking for `_doFill` works there. I would also check for `_doStroke` in the same way before `_drawImmediateStroke()`. It is implicit because the lineVertices will be empty when `_doStroke` is false but best to keep clear symmetry between those two.

Thank you!
