### ISSUE TITLE
Can't initialise p5 in instance mode using constructor

### ISSUE THREAD

**Issue by DivyamAhuja** [processing/p5.js#4351]
![Screenshot from 2020-03-06 18-59-31](https://user-images.githubusercontent.com/39771050/76087733-c45b8f00-5fdc-11ea-9ac6-952d349c3369.png)

Can Someone explain how this is supposed to work.
Going through code I was trying to go through code trying to initialise p5 in instance mode

This code with class is working but i can't get it working with sketch clousre in p5 constructor parameter

![Screenshot from 2020-03-06 19-03-43](https://user-images.githubusercontent.com/39771050/76088038-58c5f180-5fdd-11ea-85db-aa4c58078e5d.png)
@stalgiag

**Comment by DivyamAhuja** [comment]
@stellartux

**Comment by limzykenneth** [comment]
To use instance mode, you can start by following examples layed out [here](https://github.com/processing/p5.js/wiki/Global-and-instance-mode). If you have further questions about using p5.js, you can ask them on the [forum](https://discourse.processing.org). Thanks.
