### ISSUE TITLE
exporting WebGL 3d Model from p5

### ISSUE THREAD

**Issue by sps014** [processing/p5.js#4352]
Is there any way of exporting or downloading 3d model from p5 WEBGL renderer.
I want to create a 3d model in the browser and want to save that user model on the user machine if the user wants to download it.
I want the model to be in .obj or .stl file format.
Unfortunately, I was not able to find any exporting API for 3d model in P5 documentation.
Thank you.

**Comment by sps014** [comment]
Any hint or suggestion to use an external 3d library capable of exporting 3d model to the client browser is also welcome.

**Comment by hellonearthis** [comment]
Have you tried asking on https://discourse.processing.org/
coding trains discord channel https://discord.gg/bF5nTx

**Comment by sps014** [comment]
Will try asking there.

**Comment by bencooper96** [comment]
did you happen to get an answer from either of those resources? - I haven't been able to find anything in them.

**Comment by sps014** [comment]
@bencooper96 no, i didn't get any acceptable answer , what i did was to track each webgl vertex and wrote a simple OBJ exporter..
You can check it out here ..
https://draw2mesh.netlify.com/

**Comment by bencooper96** [comment]
@sps014 wonderful! thank you very much!

**Comment by matttt** [comment]
wow well done this is beautiful!!
