### ISSUE TITLE
Build process fails due to < loadJSON documentation>

### ISSUE THREAD

**Issue by endurance21** [processing/p5.js#4356]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [X] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug: 

- p5.js version:0.10.2

- Operating System: 
 ubuntu 18.04
- Steps to reproduce this:
clone the repo and after installing dependencies  , just type grunt to build and run the project 
it throws some error 
`
![issuegruntbuildfailed](https://user-images.githubusercontent.com/43696525/76253725-35b37000-6271-11ea-8fe1-f04efa25553f.png)

**Comment by akshay-99** [comment]
Hey @endurance21 I have come across this too. I don't exactly know what's causing it, just that the test is taking more than 4 seconds to finish and that's causing a timeout. I close a few browser tabs here and there to speed up my system a bit, and it starts working :sweat_smile: 

I definitely shouldn't be happening though.

**Comment by DivyamAhuja** [comment]
I didn't encounter such error
![Screenshot from 2020-03-10 15-20-33](https://user-images.githubusercontent.com/39771050/76300480-c7a79100-62e2-11ea-96b4-55b6cc9c08e8.png)
maybe this depends upon machine to machine or network connection as that example loads data from internet.

am using p5 v1.0.0 tho but it was working just as fine earlier too.

**Comment by endurance21** [comment]
@DivyamAhuja 
 i mentioned the version 0.10.2

**Comment by DivyamAhuja** [comment]
> @DivyamAhuja
> i mentioned the version 0.10.2

it was working fine for me for v0.10.2

**Comment by limzykenneth** [comment]
As far as I can see the tests for `loadJSON()` does not fetch file over the internet and doesn't require an internet connection to run. The only thing that should slow it down significantly is the system file IO latency but again I'm not expecting it to be that slow. If it really is a latency problem you can try increasing the mocha time out value layed out [here](https://stackoverflow.com/questions/23492043/change-default-timeout-for-mocha), and if increasing the timeout value is still not working then the problem should be elsewhere.

@endurance21 How are you running the tests for 0.10.2? Did you restore back to the git tag for 0.10.2 and run the tests there? Is the current master branch passing tests for you?

**Comment by DivyamAhuja** [comment]
@limzykenneth that example from loadJSON() does seem to be fetching file from internet..

I tried building it with my internet off and these were the results

![Screenshot from 2020-03-10 19-50-36](https://user-images.githubusercontent.com/39771050/76322575-94c4c380-6309-11ea-94a9-e99f6451d783.png)
![Screenshot from 2020-03-10 19-52-02](https://user-images.githubusercontent.com/39771050/76322580-95f5f080-6309-11ea-8b2b-44ae05f7ebfc.png)

and this one with internet on
![Screenshot from 2020-03-10 19-58-22](https://user-images.githubusercontent.com/39771050/76322584-97271d80-6309-11ea-9808-85c023b2a3b2.png)

**Comment by DivyamAhuja** [comment]
or maybe it can really be related to IO latency and can be solved by increasing mocha time out value

**Comment by limzykenneth** [comment]
@DivyamAhuja Yeah I see, that's the test for the reference examples. I though it was the unit tests failing. In that case, it could be due to internet speed. Do try to increase the mocha timeout value and see if that helps.

**Comment by endurance21** [comment]
@limzykenneth okay

**Comment by Qianqianye** [comment]
Thank you all for the discussion. I will close this issue for organizational purpose. Please feel free to reopen it another round of conversation is needed. Thanks!
