### ISSUE TITLE
Stop forming/executing of waveform

### ISSUE THREAD

**Issue by abhishektanwar** [processing/p5.js#4382]
I am plotting the waveform by capturing the input using microphone . When a button is clicked waveform starts . But when I click the button again(if else logic implemented) I want the waveform to stop plotting and stop its further execution and capturing through mic.
Please help 

document.getElementById("graph").addEventListener("click",function(event){
  if(document.getElementById("graph").value == 0){
    var t = function(p){
      p.mic2;
      p.yslider;
      p.xslider;
      p.setup = function(){
        p.createCanvas(800,500);
        p.mic2 = new p5.AudioIn();
        p.mic2.start();
        p.fft = new p5.FFT();
        p.fft.setInput(p.mic2);
        let d = p.createDiv();
        d.style('margin-left:6%;');
        d.style('padding-left: 50px;');
        d.style('transform-origin: 0 50% 0');
        d.style('transform: rotate(' + ((360 / 4)) + 'deg);');
        d.position(820, 200);
        p.yslider=p.createSlider(0.2,2,0.5,0.05);
        d.child(p.yslider);
        p.xslider= p.createSlider(1,2,0.5,0.05);
        d.child(p.xslider)
        // console.log(p.yslider.value());
        // sound.amp(0.2);
      };
      p.draw = function(){
        p.background(220);
    
        let spectrum = p.fft.analyze();
        p.noStroke();
        p.fill(255, 0, 255);
        for (let i = 0; i< spectrum.length; i++){
          let x = p.map(i*p.xslider.value(), 0, spectrum.length, 0, p.width);
          let h = -p.height + p.map(spectrum[i]*p.yslider.value(), 0, 255, p.height, 0);
          p.rect(x, p.height, p.width / spectrum.length, h )
        }
      };
    };
    document.getElementById("two").style.display="block";
    var myp5 = new p5(t,'two');
    console.log("hello");
    document.getElementById("one").style.display="none";
    document.getElementById("graph").value =1;
    document.getElementById("graph").innerHTML="STOP";
  }
  else{
    console.log("s");
    
  }
});

**Comment by limzykenneth** [comment]
Hi @abhishektanwar, we use github issues mostly for bug tracking or feature requests relating to p5.js itself, if you need help with your own code you can post it on the [forum](https://discourse.processing.org). Thanks!
