### ISSUE TITLE
The location of point light is not changing with mouse in p5.js version 1.0.0

### ISSUE THREAD

**Issue by DivyamAhuja** [processing/p5.js#4391]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Details about the bug: 
The location of point light is not changing with mouse in p5.js version 1.0.0
`pointLight(255, 0, 0, mouseX - width/2, mouseY - height/2, 200); `

- p5.js version:  1.0.0
- Web browser and version: Google Chrome Version 80.0.3987.132 (Official Build) (64-bit)
- Operating System:  Ubuntu 18.04 LTS
- Steps to reproduce this:

```
let angle;

function setup() {
  createCanvas(800, 800,WEBGL);
  angle = 0;
}

function draw(){
  background(0,0,0,0);
  noStroke();
  pointLight(255, 0, 0, mouseX - width/2, mouseY - height/2, 200);
  specularMaterial(255,0,0);
  rotateX(angle);
  rotateY(angle);

  sphere(100);
  angle += 0.01;
}
```
This code works fine in p5.js version 0.10.2
https://editor.p5js.org/DivyamAhuja/sketches/ndOqBlh2

but the location of light doesn't change in version 1.0.0
https://editor.p5js.org/DivyamAhuja/sketches/IjnCX8L6

**Comment by DivyamAhuja** [comment]
@stalgiag @akshay-99 can you help me check this out

**Comment by akshay-99** [comment]
Sure. Let me have a look. I'll get back to you soon

**Comment by DivyamAhuja** [comment]
Thanks @akshay-99

**Comment by akshay-99** [comment]
Hi @DivyamAhuja  sorry for the delay. I found that the issue is introduced in #4136, more specifically, [this particular commit](https://github.com/processing/p5.js/pull/4136/commits/8686a4ece74bf4c1bf0613481a268e33ecd35cfa)

If I comment out the `if else` block starting from line 359 in `src/webgl/p5.Shader.js`, it starts working again. I am still trying to figure out why this happens.

**Comment by akshay-99** [comment]
Okay @DivyamAhuja I found the problem. So uniform `uPointLightPosition` is of the type `gl.FLOAT_VEC3`
However  `uniform.isArray` is currently defined as 
```
uniform.isArray =
      uniform.type === gl.FLOAT_MAT3 ||
      uniform.type === gl.FLOAT_MAT4 ||
      uniform.type === gl.INT_VEC2 ||
      uniform.type === gl.INT_VEC3 ||
      uniform.type === gl.INT_VEC4;
```

Just including `FLOAT_VEC3` like below fixes the issue
```
uniform.isArray =
      uniform.type === gl.FLOAT_MAT3 ||
      uniform.type === gl.FLOAT_MAT4 ||
      uniform.type === gl.FLOAT_VEC3 ||
      uniform.type === gl.INT_VEC2 ||
      uniform.type === gl.INT_VEC3 ||
      uniform.type === gl.INT_VEC4;
```

What happens right now with the code on master is that the `uniform.isArray` check gives false at line 359. This means we are assigning arrays with the = operator, and comparing with ===, both of which should be done for scalars, not arrays.

@stalgiag  Is the above approach to solve this issue correct?

**Comment by stalgiag** [comment]
@akshay-99 that is right! It was an unintentional omission. Thanks for finding it!

**Comment by akshay-99** [comment]
@stalgiag There are also `gl.FLOAT_VEC2` and `gl.FLOAT_VEC4`. I am assuming they should be included too?

**Comment by DivyamAhuja** [comment]
Thanks @akshay-99 for finding this bug!

**Comment by stalgiag** [comment]
@akshay-99 yes please add `FLOAT_VEC2`, `FLOAT_VEC3`, and `FLOAT_VEC4`. Thank you!

**Comment by akshay-99** [comment]
@DivyamAhuja were you working on something, encountered this issue and then incorporated these changes yourself? Or should I go ahead and open up a PR?

**Comment by DivyamAhuja** [comment]
@akshay-99 You should go ahead and open a PR for this issue, I was just experimenting current material system of p5.js while I encountered this issue, so I haven't incorporated these changes yet.
