### ISSUE TITLE
Enhancing quality of existing tests and adding missing unit tests.

### ISSUE THREAD

**Issue by fenilgandhi** [processing/p5.js#4392]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other (Tests)

#### Feature enhancement details:
The test coverage for modules like `dom`, `image` and `io` is pretty low. Also some of the existing test can be improved. 
For more reference, check out #4385, #3567

**Comment by limzykenneth** [comment]
I'm not too sure but wouldn't this issue be covered by #4385 already? Or is this about something else unrelated?

**Comment by fenilgandhi** [comment]
#4385 is a more generalised issue for discussing about the condition of testing as a whole. Whilst i would only be cover 2 or 3 modules and try to improve the quality of existing test and add missing ones. Also since #4385 is used by @akshay-99 to discuss about his GSOC proposal, i thought it would be better to have a seperate issue.

**Comment by fenilgandhi** [comment]
Just for ease of review and merging, i am going to break this work in bundled PRs each with changes of 7-8 methods.

### DOM TESTING

##### NEW PR : create Methods
  - createImg
  - createRadio
  - createColorPicker
  - createInput
  - createFileInput
  - createMedia
  - createVideo
  - createAudio
  - navigator.mediaDevices
  - navigator.mediaDevices.getUserMedia
  - createCapture
  - createElement

##### NEW PR : p5.Element methods I
  - addClass
  - removeClass
  - hasClass
  - toggleClass
  - child
  - center
  - html
  - position
  - _translate

##### NEW PR : p5.Element methods II
  - style
  - attribute
  - removeAttribute
  - value
  - show
  - hide
  - size
  - remove
  - drop

##### NEW PR: p5.MediaElements I
  - constructor
  - play
  - stop
  - pause
  - loop
  - noLoop
  - autoplay
  - volume
  - speed

##### NEW PR: p5.MediaElements II
  - time
  - duration
  - loadPixels
  - updatePixels
  - get
  - set
  - copy
  - mask

##### NEW PR: p5.MediaElements III
  - isModified
  - setModified
  - onended
  - connect
  - disconnect
  - showControls
  - hideControls

##### NEW PR: Cue and File
  Cue
  - addCue
  - removeCue
  - clearCues

  p5.File
