### ISSUE TITLE
Error w/ functions in classes

### ISSUE THREAD

**Issue by Bookworm320** [processing/p5.js#4393]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ x] Other (specify if possible) Issue with class arguments

#### Details about the bug: When trying to use classes in the web editor it claims the ellipse in the class was expecting at least 3 arguments but only received 1. I have only had this problem with classes; using objects or just the ellipse function works fine. I tried exactly coping the jitter object example on p5 and that for some reason doesn't have the console error however copying the syntax does. The error is not exclusive to ellipse; it has also happened with circle and every other shape I've tried (It looks like someone reported the same issue with line() as well). Sorry if this is my mistake with the syntax not p5.

- p5.js version: 
- Web browser and version:  Google Chrome
- Operating System:  Windows
- Steps to reproduce this: Simply run code

Console error:
> p5.js says: ellipse() was expecting at least 3 arguments, but received only 1 at about:srcdoc:81:5. [http://p5js.org/reference/#p5/ellipse] 

Code causing error:
let ball0;

function setup() {
  createCanvas(400, 400);
  ball0 = new Ball();
}

function draw() {
  background(220);
  ball0.move();
  ball0.show();
}

class Ball {
  constructer() {
    this.x = random(width);
    this.y = random(height);
    this.dia = random(20, 40);
    this.speed = 4;
  }

  move() {
    this.x = this.x + random(-this.speed, this.speed);
  }
  show() {
    ellipse(this.x, this.y, this.dia, this.dia);
  }
}

**Comment by DivyamAhuja** [comment]
Hi @Bookworm320, well the problem in your code is basically a typo. You have typed `cronstructor()` as `constructer()`, that's why your code is not working.
Here is a link right code : -
https://editor.p5js.org/DivyamAhuja/sketches/yvYgwusJg

**Comment by Bookworm320** [comment]
Thank you for setting me straight :)
