### ISSUE TITLE
p5._friendlyError() can't provide reference link for methods like p5.Vector.add

### ISSUE THREAD

**Issue by DivyamAhuja** [processing/p5.js#4398]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other (Friendly Error System)

#### Feature enhancement details:
The current `p5._friendlyError(message, method)` call appends `method` string in front of https://p5js.org/reference/#p5/ URL to link to reference site for that method, but this way it can't link to URLs like https://p5js.org/reference/#/p5.Vector/add . So I suggest checking before appending if it has `'p5.'` string in start or not and append it accordingly.

![Screenshot from 2020-03-21 01-04-43](https://user-images.githubusercontent.com/39771050/77200166-0bcf3880-6b10-11ea-8dca-28af4785fd97.png)

**Comment by ykabusalah** [comment]
Could I try tackling this issue?

**Comment by aferriss** [comment]
@ykabusalah That would be great, thank you!
