### ISSUE TITLE
Stray link to p5.dom (also #4208)

### ISSUE THREAD

**Issue by mag911** [processing/p5.js#4400]
Found a stray link whilst trying to read about p5.dom

On this page:

https://p5js.org/examples/dom-modifying-the-dom.html

### Modifying the DOM

Create DOM elements and modify their properties every time draw() is called. You will need to include the "[p5.dom library](http://p5js.org/reference/#/libraries/p5.dom)" for this example to work in your own project. 

similar to this issue #4208

**Comment by ykabusalah** [comment]
Can I try doing this?

**Comment by ykabusalah** [comment]
I have a question. Is the actual website being deployed from somewhere other than Github? If so, it's possible that the Github repo might be missing some files. The website's Github repository doesn't include a file for the "Examples" page, which is where the issue is said to be found.

**Comment by mag911** [comment]
Hi Yousef,
I don't believe any pages are missing. If you look at issue #4208 , you'll see Lauren made the comment:

"_p5.dom has been merged into the core library_" 

This is why there is no p5.dom link anymore. It all makes sense, just that a bit of housekeeping (page editing / wordsmithing) needs doing on:
https://p5js.org/examples/dom-modifying-the-dom.html

**Comment by limzykenneth** [comment]
@ykabusalah The website is built on github using travis into the [gh-pages](https://github.com/processing/p5.js-website/tree/gh-pages) branch. What you see on that branch should reflect what appears on the production server.

**Comment by ykabusalah** [comment]
I have attempted to fix this issue here: https://github.com/processing/p5.js-website/pull/633.
