### ISSUE TITLE
Translation of contributor_docs into Korean

### ISSUE THREAD

**Issue by mjaything** [processing/p5.js#4408]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [X] Other (specify if possible): Internationalization

#### New feature details:
I have finished the Korean translation of the README.md of contributor_docs(#4137). Please assign me to the issue.

**Comment by mjaything** [comment]
@limzykenneth If you could assign me, I will make a PR. Thanks!

**Comment by mjaything** [comment]
@limzykenneth thanks! By the way, I've mislabled the issue. Sorry!

**Comment by mojosoeun** [comment]
Hi, @mjaything, How about translating the other documents in the contributor's docs folder together, for example, contributing_documentation.md, creating_libraries.md, etc. I think it might be good to translate other documents into Korean. I'm translating the contributing_documentation.md now, let's split up the different documents to translate.

**Comment by limzykenneth** [comment]
@mjaything @mojosoeun To just chip in a bit here, can one of you perhaps create a checklist here of what still needs to be translated and what is being translated so that the two of you can keep track of each other's work? 

@mjaything seeing as you have already started, would you like to create such a list here?

**Comment by mjaything** [comment]
Hi @mojosoeun thanks for the suggestion, and it's great to hear that you've started working on contributing_documentation.md! I have been translating p5.js web editor developer docs. During this month, due to other commitments, I won't be able to do more translation, but I can join you later on!

@limzykenneth that's a great idea! I'm unsure if this is the list that you've thought of. Please let me know if there's a better way to maintain the list!

- [X] README.md
- [ ] benchmarking_p5.md
- [ ] contributing_documentation.md / @mojosoeun 
- [ ] creating_libraries.md
- [ ] custom_p5_build.md
- [ ] design_principles.md
- [ ] discussions.md
- [ ] es6-adoption.md
- [ ] friendly_error_system.md
- [ ] inline_documentation.md
- [ ] internationalization.md
- [ ] issue_labels.md
- [ ] method.example.js
- [ ] navbar.md
- [ ] organization.md
- [ ] preparing_a_pull_request.md
- [ ] release_process.md
- [ ] roadmap.md
- [ ] sidebar.md
- [ ] supported_browsers.md
- [ ] unit_testing.md
- [ ] webgl_mode_architecture.md

**Comment by limzykenneth** [comment]
Probably should keep this open until all the sections are translated, but let me know if otherwise.

**Comment by mjaything** [comment]
You're right @limzykenneth thanks for reopening it! If anyone starts working on any of the documents, please leave the comment here and i'll update the list!

**Comment by mojosoeun** [comment]
@mjaything Hi. I'm translating creating_libraries.md, custom_p5_build.md. and design_principles.md now

**Comment by mjaything** [comment]
@mojosoeun great! I'll start internationalization.md soon!

**Comment by montoyamoraga** [comment]
we merged @mojosoeun's contribution, and i updated the checklist above :)

**Comment by mojosoeun** [comment]
@mjaything Hi. I'm translating preparing_a_pull_request.md, es6-adoption.md, and supported_browsers.md and unit_testing.md 🙂

**Comment by mjaything** [comment]
@mojosoeun List updated! Thanks! :-D

**Comment by montoyamoraga** [comment]
i updated the list to reflect that "preparing_a_pull_request.md " is done, yay :)
thank you @mojoseun for your PR #4528 !

**Comment by jeong** [comment]
@mojosoeun 번역 속도 높이는 데 지원하러 왔습니다. :)

**Comment by mojosoeun** [comment]
@limzykenneth @montoyamoraga,  To finish Korean translation and close this issue, I would like to get help from @jeong and split up documentation. Can I do that?

**Comment by limzykenneth** [comment]
Yes of course.
