### ISSUE TITLE
"p5 had problems creating the global function "Animation", possibly because your code is already using that name as a variable. You may want to rename your variable to something else." error

### ISSUE THREAD

**Issue by ViraajRandhawa** [processing/p5.js#4412]
"p5 had problems creating the global function "Animation", possibly because your code is already using that name as a variable. You may want to rename your variable to something else."

 this error is not letting my image load in p5 editor.

**Comment by ViraajRandhawa** [comment]
and my preview is also not loading

**Comment by fenilgandhi** [comment]
Can you post your code over here ? or better yet, save it as a sketch and post the link to the sketch.

**Comment by limzykenneth** [comment]
Possibly related to #4405. 

@ViraajRandhawa Can you fill in the default issue template otherwise we don't have enough information to help you. Basically we need the p5.js version used, the browser version, the OS version, and a simple example code to replicate the problem. Thanks.
