### ISSUE TITLE
Canvas created in shadow dom is hidden indefinitely

### ISSUE THREAD

**Issue by jrobinson01** [processing/p5.js#4415]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug: 

- p5.js version: 1.0.0
- Web browser and version: Chrome 80
- Operating System: OSX Mojave
- Steps to reproduce this:
Here's a [codepen](https://codepen.io/johnrobinson/pen/YzXJoBv?editors=1000) showing the problem 

Because the canvas's parent is inside shadow dom, the code [here](https://github.com/processing/p5.js/blob/c1e30d688748543e52aa5ebc241bfc7dfb2f508d/src/core/main.js#L345) is unable to find it to make it visible after setup has run. The current solution is to manually unhide the canvas in setup as shown in the codepen above.

**Comment by lmccart** [comment]
I'm a little confused about this issue, the shadow dom is not intended to be shown. I'm not seeing a lot of interest in this feature, and we don't have a clear explanation of how it [expands access](https://github.com/processing/p5.js/blob/main/contributor_docs/access.md), so I will close this for now. If an access statement can be added to the issue request, please feel welcome to reopen!
