### ISSUE TITLE
Link to tutorial page in contributing docs is invalid

### ISSUE THREAD

**Issue by mattfan00** [processing/p5.js#4417]
In the [contributor docs](https://github.com/processing/p5.js/tree/master/contributor_docs), the link to the [p5 learning page](https://p5js.org/learn/) is incorrect. Right now the link leads to an invalid page. Additionally, the second link in the bullet point is not linked correctly either. It is supposed to route to [this](https://p5js.org/learn/tutorial-guide.html) link. Attached is a screenshot of the issue: 

![image](https://user-images.githubusercontent.com/30060256/77592147-ec495e80-6ec7-11ea-8dd1-4d06c03a9078.png)

I was wondering if this issue does get approved, if I could work on it? This would be my first contribution to p5.js and I am excited to dive deeper into contributing to this open source project! 

Thank you! 

(Additionally, apologies if this is the incorrect issue template, I could not find one that relates to issue with documentation)

**Comment by stalgiag** [comment]
Hi @mattfan00 welcome and thanks for the issue! We would love to have you contribute and fix this! I am going to assign the issue to you.
