### ISSUE TITLE
Link to i18next is broken in internationalization.md in contributor_docs directory

### ISSUE THREAD

**Issue by mjaything** [processing/p5.js#4428]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Dom
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [X] Other (specify if possible) Documentation

#### Details about the bug:
The link to i18next is broken in internationalization.md in contributor_docs directory.
Simply replace the link to https://www.i18next.com/

- p5.js version:  Documentation
- Web browser and version: Chrome Version 80.0.3987.132
- Operating System: MacOS Catalina Version 10.15.3
- Steps to reproduce this:
See the 'Tooling' section of the internationalization.md in the contributor_docs directory. Link: https://bit.ly/2WIxDvj

**Comment by limzykenneth** [comment]
Good catch. I can assign this to you if you want.

**Comment by mjaything** [comment]
Yes, please do so!
