### ISSUE TITLE
createCanvas issue need help

### ISSUE THREAD

**Issue by Codlngman** [processing/p5.js#4429]
![coding issue](https://user-images.githubusercontent.com/62736745/77724475-116dc800-6fc1-11ea-9fa1-3c52da04ffb7.JPG)

it just dose not like line 21 even thought that is what the tutorial says so idk what I am doing wrong. I am new to coding so this could be my fault so sorry if its some really simple solution.

**Comment by montoyamoraga** [comment]
hi @Codlngman, thank you for your question, the right place for questions is our forum at https://discourse.processing.org/, so i am going to close this issue.

this repository is for development of p5.js, not for coding questions, but i will give you this pointers:

1. you can only have one setup() function, you have 3 on your code.
2. your line 21 is CSS, a different language. In the template of p5.js, we include CSS in the corresponding index.html file, inside of the tag <style>, here is more info about that: https://www.w3schools.com/TAGs/tag_style.asp
3. i suggest browsing through the p5.js examples https://p5js.org/examples/ while starting, and asking questions on the forum :)

best of luck!
