### ISSUE TITLE
The square function fails when drawing rounded corners

### ISSUE THREAD

**Issue by lenincompres** [processing/p5.js#4436]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [x ] Core/Environment/Rendering
- [ ] Data
- [ ] Dom
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version: latest relased 
- Web browser and version: Chromium and Firefox 
- Operating System: Windows 
- Steps to reproduce this: Just look at the Examples in the Reference page, https://p5js.org/reference/#/p5/square

**Comment by DivyamAhuja** [comment]
This bug has already been solved in current code (1.0.1). This bug exists in version 1.0.0 but not in current code.
