### ISSUE TITLE
loadImage() documentation - mention base64 string as a parameter

### ISSUE THREAD

**Issue by stuart321** [processing/p5.js#4443]
Documentation could state that `loadImage()` accepts a base64 encoded image as a parameter (example: https://stackoverflow.com/a/51162033), as an alternative to the file path. I found this useful to avoid the CORS block when testing locally (if one doesn't wish to setup a webserver).

https://github.com/processing/p5.js/blob/f503b0b81aa86671e8ea900133985b3d26556dac/src/image/loading_displaying.js#L30

**Comment by sm7515** [comment]
I created a pr to add this in the doc ;)
