### ISSUE TITLE
textBounds for multilined text

### ISSUE THREAD

**Issue by ProgrammingLife** [processing/p5.js#4449]
How to calculate bounds for multilined text? Also I don't have any chance to find bounds for a text inside of a rect, such as:
`text(veryLongText, 50, 50, 200, 400)`

As for manually multilined text, that's what I'm talking about:
```
let textString = 'Lorem ipsum\ndolor\nsit\namet.';
let bbox = font.textBounds(textString, 10, 30, 12);
fill(255);
stroke(0);
rect(bbox.x, bbox.y, bbox.w, bbox.h);
fill(0);
noStroke();

textFont(font);
textSize(12);
text(textString, 10, 30);
```

![](https://i.imgur.com/M5DUmFq.png)

**Comment by fisherdiede** [comment]
I have a change which introduces this new feature but am having trouble creating a PR for my branch. Here is a screenshot of the described example with a few other simple verification tests.

<img width="513" alt="Screen Shot 2020-04-10 at 17 01 40" src="https://user-images.githubusercontent.com/11671032/79031062-5e799e80-7b6a-11ea-9f91-e58c3908510d.png">

could someone help me out? I don't know how to get permissions to even see my branch in the new PR page.

**Comment by akshay-99** [comment]
Hi @fisherdiede. I don't think you would have the access to directly push changes to a branch on this repository. `Fork` this repository and push the changes on a branch to your own fork. Then you should be able to create a PR. 
It should look something like processing:master <-- fisherdiede:branchname

You can check the [contributor docs](https://github.com/processing/p5.js/tree/master/contributor_docs#development-process) for more details
