### ISSUE TITLE
Present link is 404'd

### ISSUE THREAD

**Issue by everythingability** [processing/p5.js#4453]
Hi,

is it me or do you get a 404 when using the **fullscreen** link for this project?

https://editor.p5js.org/remarkability/sketches/mSkuADqwe

**Comment by limzykenneth** [comment]
The fullscreen link (https://editor.p5js.org/remarkability/full/mSkuADqwe) is working fine for me. If you think there is an issue with the web editor you can open an issue on the web editor [repository](https://github.com/processing/p5.js-web-editor). Thanks.

**Comment by everythingability** [comment]
Thank you... It IS for me now... but was 404ing for months...
