### ISSUE TITLE
drawingContext always returns 2d

### ISSUE THREAD

**Issue by micuat** [processing/p5.js#4455]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] Dom
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version: 0.10.2
- Web browser and version: chrome
- Operating System: win
- Steps to reproduce this:
https://editor.p5js.org/micuat/sketches/sU-iyw0CO
the first one (drawingContext) returns 2d while `getContext('webgl')` returns webgl

is this expected behavior? if so the reference sounds a bit misleading
> This is the equivalent of calling canvas.getContext('2d'); or canvas.getContext('webgl');.
https://p5js.org/reference/#/p5/drawingContext

**Comment by limzykenneth** [comment]
I think this is a bug and not expected behaviour. It probably is due to the webgl renderer not setting the `drawingContext` property on the instance object when creating the webgl canvas.

**Comment by DivyamAhuja** [comment]
@limzykenneth so can we solve this by adding `pInst.drawingContext = this.drawingContext;` [here](https://github.com/processing/p5.js/blob/master/src/webgl/p5.RendererGL.js#L70)?

**Comment by limzykenneth** [comment]
@DivyamAhuja Maybe, I'm not sure. @stalgiag may be more familiar with the rendering pipeline instancing.
