### ISSUE TITLE
trasparent surfaces created with begin/endShape() in 3D (WEBGL) have a one-sided normal

### ISSUE THREAD

**Issue by megadix** [processing/p5.js#4458]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] Dom
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version: 1.0.0
- Web browser and version:
  - Chrome 80.0.3987.149
  - Firefox: 74.0
- Operating System: Windows 10 Pro
- Steps to reproduce this:  
  https://editor.p5js.org/megadix/sketches/un-1SOXmm

## Expected Behavior

When I'm creating surfaces in WEBGL with
```js
fill(0, 0);
stroke([anywhere from 0 to 255])
```

I expect them to be transparent from both sides, i.e. I want to see **only the edges** of the shape, like rings.

## Actual Behavior

Shapes created this way are transparent only from one side.

## Steps to Reproduce the Problem

  1. create a sketch with version 1.0.0 of P5.js
  2. copy and run code from [example sketch](https://editor.p5js.org/megadix/sketches/un-1SOXmm)
  3. rotate mouse to see how shapes are opaque on one side, but transparent on the other
  4. repeat, but with online web editor
  5. notice the difference: **on online editor both sides are transparent**

The only difference I see looking at P5.js Editor code is that it uses a slightly older version of P5.js: `0.9.0`.

Could this be considered a regression, or `1.0.0` is more correct?

**Comment by stalgiag** [comment]
Hi @megadix thank you for the well-written issue. This is definitely a regression. I'll look into it!

**Comment by davepagurek** [comment]
Hi! I believe this has to do with depth testing -- for transparency to work, the transparent layers must be drawn from back to front. In your case, you can either disable the fill with `noFill()`, disable depth testing with `drawingContext.disable(drawingContext.DEPTH_TEST)`, or draw each layer back-to-front given the rotation of the object. I'm going to close this in favor of this issue to better document how transparency behaves: https://github.com/processing/p5.js/issues/3736
