### ISSUE TITLE
No help text on p5.Geometry.computeFaces()

### ISSUE THREAD

**Issue by Kango** [processing/p5.js#4463]
Hi there!

No help text on 

https://p5js.org/reference/#/p5.Geometry/computeFaces

Thank you!!!!!!!!!!!!!!!!!

**Comment by DivyamAhuja** [comment]
@stalgiag  can you tell me what appropriate description should be?  like ` It computes faces of primitive 3d geometry based on details.`?

**Comment by stalgiag** [comment]
@DivyamAhuja something like that or 'computes faces for geometry objects based on the vertices.'

**Comment by DivyamAhuja** [comment]
Oh, then I will try updating documentation
