### ISSUE TITLE
p5js performance on mobile device is very slow and laggy

### ISSUE THREAD

**Issue by srinivasmangipudi** [processing/p5.js#4469]
Hi,

I am using p5js for a drawing and have included the latest version from the cdn: <script src="https://cdn.jsdelivr.net/npm/p5@1.0.0/lib/p5.js"></script>

The problem is that the sketch runs gret in a browser, but the performance and speed on mobile devices is very slow. I have tried to change the frameRate() function, but no effect.

Is this a know problem? Please suggest! thanks

**Comment by mishazawa** [comment]
Please post your sketch code.

**Comment by lmccart** [comment]
try including the minified file, it is optimized for faster performance. to debug further, we will need more information like your sketch code.
`<script src="https://cdn.jsdelivr.net/npm/p5@1.0.0/lib/p5.min.js"></script>`

**Comment by amzon-ex** [comment]
I'm having the same issue and I'm using the minified version from the cdn. 55-60 fps on pc and 5-6 fps on a mobile device (Android, Chrome 88). What should I do?

**Comment by mishazawa** [comment]
> I'm having the same issue and I'm using the minified version from the cdn. 55-60 fps on pc and 5-6 fps on a mobile device (Android, Chrome 88). What should I do?

@amzon-ex

Post example of code which reproduce this behaviour.

**Comment by amzon-ex** [comment]
@mishazawa Thanks for responding. Here's the code: https://github.com/amzon-ex/amzon-ex.github.io/tree/master/dp-sketch-stripped

If you need it, you can view the animation here: https://amzon-ex.github.io/dp-sketch-stripped/dp-sketch.html
