### ISSUE TITLE
round() does not respect second argument

### ISSUE THREAD

**Issue by awarua** [processing/p5.js#4470]
#### Most appropriate sub-area of p5.js?

- [X] Math

#### Details about the bug:

- p5.js version: 0.10.2
- Web browser and version: Google Chrome | 80.0.3987.163
- Operating System: MacOSX 10.15.4
- Steps to reproduce this:

Example code snippet ([live version](https://editor.p5js.org/creativecoding/sketches/xGSg7VH3j0))

    let a = 1.234
    
    function setup(){
      print(a);
      print(round(a));  
      print(round(a, 2));
    }

Expected console output to be:

    1.234
    1
    1.23

Actual output:

    1.2.3.4
    1
    1

It doesn't seem like the `round()` function is using the optional second argument, `decimals`, which according to the documentation should be the number of decimal places to round to. 

I searched existing open issues for `round()` but couldn't find any. The following feature request is similar, but sounds like it was closed without being implemented: #2802

If this is not the intended behavior of `round()`, then we should probably update the documentation.

Apologies if this has already been submitted.

https://p5js.org/reference/#/p5/round

**Comment by akshay-99** [comment]
Hi @awarua, it seems that the support for an optional second argument specifying the number of decimal places was added in version 1.0.0

If I change the version of p5 imported in the HTML to1.0.0, this should work
https://editor.p5js.org/akshay.padte/sketches/1U09T-2yQ

**Comment by awarua** [comment]
Thanks so much @akshay-99. That totally fixed it. I'm using the default settings on the P5js web editor. Do you think it's worth adding an issue on that project to update the p5js version to 1.0.0 in new sketches?
