### ISSUE TITLE
audioIn function does nt work 

### ISSUE THREAD

**Issue by ilyasselhadi** [processing/p5.js#4472]
PLEASE NOTE: 

The github issues are only for bugs and feature requests for the p5.js library itself. 

Please post general questions or requests for help with bugs in your sketch in the p5.js forum: https://discourse.processing.org

**Comment by limzykenneth** [comment]
Hi @ilyasselhadi, can you fill out the original issue template and describe the issue in more detail? Otherwise we just don't have enough information to help you.

**Comment by ilyasselhadi** [comment]
oke i m going to fill out the original issue template thaks a lot
