### ISSUE TITLE
elaborate documentation on p5.sound / MediaElement

### ISSUE THREAD

**Issue by micuat** [processing/p5.js#4473]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [x] Dom
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other (specify if possible)
p5.Sound / documentation

#### Feature enhancement details:

I wasn't sure where to write this issue, but first I was trying to use the sound from the video as the input of FFT, and made it possible with the following code

```
  var source = getAudioContext().createMediaElementSource(vid.elt);
  var gainNode = getAudioContext().createGain();
  source.connect(gainNode);
  gainNode.connect(getAudioContext().destination);
  
  fft.setInput(gainNode);
```

but then I learned that

```
  fft.setInput(vid);
```

actually does the same thing. I think MediaElement is missing some documentation (or I couldn't find it) - which I think there's room for improvement. Is anyone already working on this? I'm happy to provide feedback.

**Comment by limzykenneth** [comment]
Is this more of a p5.sound.js issue or a p5.MediaElement issue? If any fix should be done on the sound library I can move it to that repo so maintainers there can work on it. I'm not familiar with the sound library enough to know whether this issue belongs there or not.

**Comment by micuat** [comment]
sorry that I wasn't sure where to post this issue. I will post it on https://github.com/processing/p5.js-sound

Another confusion is that https://p5js.org/reference/#/p5/createVideo is linked to Element, not [MediaElement](https://p5js.org/reference/#/p5.MediaElement) (I guess this is simply a typo). I will post this on https://github.com/processing/p5.js-website

**Comment by micuat** [comment]
@limzykenneth now I moved this issue to the proper repositories, should I close this issue?
