### ISSUE TITLE
i have a probleme in my p5 js code . the AudioIn function do not work 

### ISSUE THREAD

**Issue by ilyasselhadi** [processing/p5.js#4474]
PLEASE NOTE: 

this is my javascript code 
![js](https://user-images.githubusercontent.com/59366946/79123341-de358200-7d91-11ea-99b1-4a278be12581.JPG)
and this is my html code 
![index](https://user-images.githubusercontent.com/59366946/79123346-e097dc00-7d91-11ea-951e-1fcf2319f8b9.JPG)
but when i open my sketch in the browser the mic not working

**Comment by ilyasselhadi** [comment]
![chrom](https://user-images.githubusercontent.com/59366946/79125779-a1b85500-7d96-11ea-921b-d42ddd118cd3.JPG)
this is my browser page

**Comment by limzykenneth** [comment]
Hi @ilyasselhadi, we usually use github only for bug reports and feature requests, if you need with help your own code you can ask on the [forum](https://discourse.processing.org). Thanks!
