### ISSUE TITLE
ReferenceError: _renderer is not defined and sometimes canvas is not defined.

### ISSUE THREAD

**Issue by bassamanator** [processing/p5.js#4477]
I've had other people check this code but the problem just appears to come and go. The following is the error I get and it brings the loading of the page to a halt, or nearly a halt. Happens when I'm loading the page.
```
sketch.js:454 Uncaught ReferenceError: _renderer is not defined
    at positionCanvasAndElements (sketch.js:454)
    at windowResized (sketch.js:465)
    at p5._main.default._onresize (p5.js:60988)
```
I started to use _renderer because my canvas variable (global; cnv) would say "cnv.position not defined." 
```
let cnv;
function setup() {
	pixelDensity(1);
	setVariables();
	cnv = createCanvas(cW + borderSpacer * 2, cH + borderSpacer * 2);
	windowResized();

	readyCanvas();
	doTask();
}
function positionCanvasAndElements() {
	xCnvPos = (windowWidth - width) / 2;
	yCnvPos = (windowHeight - height) / 2;
	_renderer.position(xCnvPos, yCnvPos);
	if (button1 != undefined) {
		button1.position(xCnvPos + xbutton1Pos, yCnvPos + ybuttonPos);
		button2.position(xCnvPos + xbutton2Pos, yCnvPos + ybuttonPos);
	}
	if (button3 != undefined) {
		button3.position(xCnvPos + xbutton1Pos * 2 - 20, yCnvPos + ybuttonPos + 38);
	}
}

function windowResized() {
	positionCanvasAndElements();
```
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [x] Dom
- [x] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version: 
- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

```
Uncaught ReferenceError: _renderer is not defined
    at positionCanvasAndElements (sketch.js:454)
    at windowResized (sketch.js:465)
    at p5._main.default._onresize (p5.js:60988)
positionCanvasAndElements @ sketch.js:454
windowResized @ sketch.js:465
_main.default._onresize @ p5.js:60988
```

**Comment by limzykenneth** [comment]
`_renderer` is not a variable that is exposed to the global scope so it won't be accessible. Directly using the `_renderer` object is not supported and you should be using `cnv.position` as you mentioned to position the canvas. If it is throwing an error about `cnv.position` is not defined you should check that the function is not called before the canvas is created.

If you need further help with you code, do ask them on the [forum](https://discourse.processing.org). Thanks.
