### ISSUE TITLE
"ReferenceError: p5 is not defined" when importing p5.dom in a typescript environment

### ISSUE THREAD

**Issue by Nazeh** [processing/p5.js#4479]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [x] Dom
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version: 0.7.3
- Web browser and version: 1.7.92 Chromium: 80.0.3987.163 (Official Build) (64-bit)
- Operating System: Win 10, WSL2
- Steps to reproduce this:
In a typescript project, after installing [P5.js](https://www.npmjs.com/package/p5) and [@types/p5](https://www.npmjs.com/package/@types/p5), import p5 and p5.dom :
``` ts
//index.ts
import * as p5 from "p5";
import "p5/lib/addons/p5.dom";
```

-How to solve the problem manually:
In node_modules/p5/lib/addons/p5.dom.js :
Cut lines 3325 to 3247 and paste at line 3324

Before:
``` js
// node_modules/p5/lib/addons/p5.dom.js
(function(root, factory) {
  if (typeof define === 'function' && define.amd)
    define('p5.dom', ['p5'], function(p5) {
      factory(p5);
    });
  else if (typeof exports === 'object') factory(require('../p5'));
  else factory(root['p5']);
})(this, function(p5) {
....
});

p5.File._createLoader = function(theFile, callback) {
  var reader = new FileReader();
  reader.onload = function(e) {
    var p5file = new p5.File(theFile);
    p5file.data = e.target.result;
    callback(p5file);
  };
  return reader;
};

p5.File._load = function(f, callback) {
  // Text or data?
  // This should likely be improved
  if (/^text\//.test(f.type)) {
    p5.File._createLoader(f, callback).readAsText(f);
  } else if (!/^(video|audio)\//.test(f.type)) {
    p5.File._createLoader(f, callback).readAsDataURL(f);
  } else {
    var file = new p5.File(f);
    file.data = URL.createObjectURL(f);
    callback(file);
  }
};
```

After:
``` js
// node_modules/p5/lib/addons/p5.dom.js
(function(root, factory) {
  if (typeof define === 'function' && define.amd)
    define('p5.dom', ['p5'], function(p5) {
      factory(p5);
    });
  else if (typeof exports === 'object') factory(require('../p5'));
  else factory(root['p5']);
})(this, function(p5) {
....
  
  p5.File._createLoader = function(theFile, callback) {
    var reader = new FileReader();
    reader.onload = function(e) {
      var p5file = new p5.File(theFile);
      p5file.data = e.target.result;
      callback(p5file);
    };
    return reader;
  };
  
  p5.File._load = function(f, callback) {
    // Text or data?
    // This should likely be improved
    if (/^text\//.test(f.type)) {
      p5.File._createLoader(f, callback).readAsText(f);
    } else if (!/^(video|audio)\//.test(f.type)) {
      p5.File._createLoader(f, callback).readAsDataURL(f);
    } else {
      var file = new p5.File(f);
      file.data = URL.createObjectURL(f);
      callback(file);
    }
  };
});
```

**Comment by Nazeh** [comment]
I realized that I was using an older version of p5.js :/ sorry folks for the false alarm!

**Comment by vanyamil** [comment]
Actually, I have this exact problem. My file starts with the lines:
import p5 from "p5";
import 'p5/lib/addons/p5.sound';

I use Laravel Mix for minifying + compiling ES6 down to vanilla JS.

Since I've moved from 0.7.2 to 1.0.0 (NPM version), the compiled script that uses those lines gives me a "ReferenceError: p5 is not defined" for line 3112 of p5.sound - "p5.prototype.isSupported = ...". Any hints?

**Comment by SIRHAMY** [comment]
Running into the same issue as @vanyamil  with Typescript and Webpack

import p5 from "p5"
import "p5/lib/addons/p5.sound"

**Comment by vennsoh** [comment]
Same, webpack + p5 seems tricky.

**Comment by rjbultitude** [comment]
Hi @Nazeh 
Not sure why this issue was closed when the problem persists. 

I can confirm it is not a problem with Webpack - the problem exists in all modern module loaders/compilers including RollUp, TypeScript and Parcel. 

Having tested more thoroughly, I can confirm P5 add-ons won't load in the following configurations:

- CommonJS
- ES6 > ES5 using Babel or esm
- ES Modules

Given the enournous populariity of npm and yarn, this issue means that anyone using those package managers will not be able to use p5 with add-ons. 

The suggestions to manually overwrite files saved to node_modules are totally unsustainable - as soon as you install again (locally, or in CI) it will be overwritten.

I see the same issue exists with p5 sound, as is expressed here: https://github.com/processing/p5.js-sound/issues/453

What was it that changed between v0.9 and v1 that broke it?

**Comment by GraxMonzo** [comment]
This can be solved easily by using webpack's [ProvidePlugin](https://webpack.js.org/plugins/provide-plugin/):
```js
  plugins: [
    new webpack.ProvidePlugin({
      p5: 'p5',
    })
  ]
```

**Comment by GraxMonzo** [comment]
If you're using Laravel Mix:
```js
mix.autoload({
    p5: ['p5']
});
```

**Comment by GraxMonzo** [comment]
ProvidePlugin alternative for Vite (vite.config.js):
```js
import { defineConfig } from 'vite';
import inject from '@rollup/plugin-inject';

export default defineConfig({
  plugins: [
    inject({
      p5: 'p5',
    }),
  ],
});

```

**Comment by crankysparrow** [comment]
@GraxMonzo thank you so much for the vite solution! works perfectly for me

**Comment by RobinBoers** [comment]
Any progress on this? I can't import p5.sound (the linked issue disappeared?), and modifying random files in `node_modules` is not an option for me. 

I already tried this (I assumed p5 needed to be added to global scope explicly):

```javascript
import p5 from "p5";
window.p5 = p5;
import "p5/lib/addons/p5.sound";
```

```javascript
import p5 from "p5";
globalThis.p5 = p5;
import "p5/lib/addons/p5.sound";
```

But neither worked :(

**Comment by slack2450** [comment]
I gave up trying to get P5 to work with Vite I wrestled with it for a couple hours and it didn't end up working.

[p5.js-sound](https://github.com/processing/p5.js-sound) seems to be deprecated anyway:
`During December 2023 we are sunsetting, archiving and deprecating this repository`

And p5.js actually includes 1.0.1 as opposed to the latest 1.0.2 which is over a year old now...

Here's a helper function class I wrote which just loads a sound and plays it. No pausing etc. But it might be useful to someone who stumbles across this.

```ts
export class SoundPlayer {
    audioContext: AudioContext;
    soundBuffer: AudioBuffer | null;
    gainNode: GainNode;

    constructor(soundFile: string, volume = 0.) {
        this.audioContext = new window.AudioContext();
        this.soundBuffer = null;

        // Create a GainNode and set the default volume to 50% (0.5)
        this.gainNode = this.audioContext.createGain();
        this.gainNode.gain.value = volume; // 50% volume

        // Connect the GainNode to the audio context destination
        this.gainNode.connect(this.audioContext.destination);

        this.loadSound(soundFile);
    }

    // Load and decode the sound file
    async loadSound(soundFile: string) {
        const response = await fetch(soundFile);
        const arrayBuffer = await response.arrayBuffer();
        this.soundBuffer = await this.audioContext.decodeAudioData(arrayBuffer);
    }

    // Create and play a new AudioBufferSourceNode
    play() {
        if (this.soundBuffer) {
            const source = this.audioContext.createBufferSource();
            source.buffer = this.soundBuffer;
            source.connect(this.gainNode); // Connect to the GainNode instead of destination
            source.start(0); // Play the sound immediately
        }
    }

    setVolume(volume: number) {
        this.gainNode.gain.value = volume; // volume should be between 0.0 (mute) and 1.0 (full)
    }
}
```

**Comment by ejgutierrez74** [comment]
The same here with Vite, and deploying to Vercel...

```
Uncaught ReferenceError: p5 is not defined
    Nn https://pacman2024windows.vercel.app/assets/index-Df26wdtU.js:1776
    An https://pacman2024windows.vercel.app/assets/index-Df26wdtU.js:1
    <anonymous> https://pacman2024windows.vercel.app/assets/index-Df26wdtU.js:1776
```

In vite works ok, but not in Vercel...

 ```
<script type="module" src="js/libraries/p5.min.js"></script>
    <!--Carreguem moduls-->

    <!--Carreguem sketch-->
    <script type="module" src="/js/sketch.mjs"></script>
    <script type="module" src="/js/secondsketch.mjs"></script>
```
My files structure:

![imagen](https://github.com/user-attachments/assets/8f3c2651-b505-4337-ab05-b7301a40865e)

**Comment by RobinBoers** [comment]
For our project we ended up using Howler, which worked perfectly for our usecase.
