### ISSUE TITLE
v.1.0.0 doesnt work with ccapture

### ISSUE THREAD

**Issue by rakkoemoji** [processing/p5.js#4481]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Dom
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other (specify if possible)

#### Details about the bug:

- p5.js version: v.1.0.0

ccapture wont render with v.1.0.0. older v.0.9.0 works.

**Comment by limzykenneth** [comment]
@rakkoemoji Do you have a simple example code demonstrating the problem?

**Comment by rakkoemoji** [comment]
let Ini=function(){
this.w=1920
this.h=1080
this.fr=30
this.tmp=60/110
this.bkg=0
this.siz=0
this.num=1285
this.nam=0

}//fun

Ini.prototype.set=function(){

this.cnv=createCanvas(this.w,this.h)
this.cnv.parent("cnv")
this.ini=millis()/1000
}
`
Ini.prototype.dis=function(sec){
this.sec=sec
this.fc=frameCount
this.lap=millis()/1000
this.dur=this.lap-this.ini
this.rem=this.sec-this.dur
this.dur>this.sec?noLoop():0
}

let Cap= function(nam){
this.nam=nam
this.fmt="png"
this.cap = new CCapture({ format: this.fmt, framerate: 30,name:this.nam})
}

Cap.prototype.set=function(){
this.cap.start()
}//fun

Cap.prototype.dis=function(){
this.cap.capture(document.getElementById('defaultCanvas0'))

if (ni.dur > ni.sec) {
noLoop()
this.cap.stop()
    this.cap.save( u=>        print(u)} )
print("fin")
}//if

}//dis

let ni=new Ini(),doc="doc"
,tx=new Tx(doc)
ni.nam="ani"+0
cap=new Cap(ni.nam)

setup=()=>{
    cap.set()
    ni.set()
    print(ni.nam)
    print(ni)
    print(0)
    background(100,100,50)
    tx.set()
}//set

draw=()=>{
ni.sec=.5
    ni.dis(ni.sec)
    tx.dis()
    print(ni.dur)
    cap.dis()
}//dr
`

**Comment by rakkoemoji** [comment]
> @rakkoemoji Do you have a simple example code demonstrating the problem?
dear kenneth,

thanks for getting back. above code works for 0.9.0 but not for 0.10.0 and up.

**Comment by limzykenneth** [comment]
Have a look at https://github.com/spite/ccapture.js/issues/108

**Comment by limzykenneth** [comment]
I've done some digging and found the source of the problem. Basically after adding this [line](https://github.com/processing/p5.js/blob/master/src/core/main.js#L354) in https://github.com/processing/p5.js/commit/abe5c95ff1a20821bb9743a5ef18e002787c9bfb the first frame of the sketch is not guaranteed to be called when the internal `this._draw` is called and without it being called, CCapture doesn't have a way to hook into the animation frame as well as it relies on `capturer.capture` to run the animation frames.

@stalgiag Do you remember why that line is added? Can there be some way to guarantee the first frame is rendered on the first call to `this._draw`?

**Comment by stalgiag** [comment]
Hm strange. If I remember correctly, I was detecting a large jump in delta time between setup and draw. This fixed it. Is setup not technically the first frame of the sketch?

I am looking at removing it now but if I recall that was my original logic.

**Comment by limzykenneth** [comment]
@stalgiag `deltaTime` wasn't implemented back then, it came after that I think. The first call to `draw()` is the first frame which will always be called (should be at least) even if `noLoop()` is called in `setup()`. 

I'm thinking there could be more problem with CCapture's approach to animation frames and recording canvas content but I'm less inclined to fix those on our side if they ever came up.

**Comment by stalgiag** [comment]
@limzykenneth sorry I used confusing language. I meant delta time in a more general sense. The GIF functionality was using the underlying logic behind `deltaTime` before it existed. Problems were being encountered because delta time was usually very high on the first draw call, as it didn't include `setup()` as a starting frame. So the initial draw call had a delta time measured since `preload`.

I tried removing the line and several things break including some unit tests in [`core/environment`](https://github.com/processing/p5.js/blob/master/test/unit/core/environment.js) which appear correct in their logic. If we are thinking of the initial draw as the first frame of animation then perhaps this requires some rethinking.

**Comment by limzykenneth** [comment]
I guess it depends on whether we want to fix this on our side. There is a workaround for CCapture to start the animation loop and recording that involves only starting CCapture after p5.js' draw loop has started. It is a bit of extra code for the user but not excessively so.

**Comment by rakkoemoji** [comment]
@limzykenneth 
thanks for the input. sorry for such a noob question, and i realized it now that i should have called it a bug, but something else. i will checkout the work around in https://github.com/spite/ccapture.js/issues/108.

**Comment by rakkoemoji** [comment]
`if (ni.dur > ni.sec) {
this.cap.start()
noLoop()
this.cap.stop()
this.cap.save( u=>{
let op={method:"put",url:"/save",data:{bl:u}}
//axios(op)
print(u)} )
print("fin")
}//if
`

**Comment by rakkoemoji** [comment]
the above code work!!! thank you!

**Comment by sleep9** [comment]
no longer works with 1.11.7. stated workaround does not work.

**Comment by ksen0** [comment]
Thanks for noticing @sleep9 , is it working with 1.11.6 or is 1.11.7 the point where code breaks?

**Comment by sleep9** [comment]
Tested 1.11.6 still broken. I believe the last working version was 0.9.0 which cant work for me as it has no video support or clipping masks.
