### ISSUE TITLE
Broken link in docs

### ISSUE THREAD

**Issue by jseakle** [processing/p5.js#4484]
#### Most appropriate sub-area of p5.js?

- [x] Documentation

#### Details about the bug:

On https://p5js.org/reference/#/p5.Vector, in the sentence "The magnitude and direction can be accessed via the methods mag() and heading().", mag() and heading() are both links with the same structure. However, https://p5js.org/reference/#/p5/mag correctly resolves to the same content as https://p5js.org/reference/#/p5.Vector/mag, but https://p5js.org/reference/#/p5/heading does not, instead simply loading the main reference page. https://p5js.org/reference/#/p5.Vector/heading does exist, but perhaps an alias of some kind is missing such that the link to  https://p5js.org/reference/#/p5/heading doesn't find it.

Additionally, it would probably be good if the page for heading() mentioned somewhere that it returns the heading in radians :)

**Comment by banditelol** [comment]
Hello, I'm new here, and I'm thinking of tackling this issue as a starter, is it still open?

After looking at the source, I think both mag() and heading() method in [p5.Vector reference](https://p5js.org/reference/#/p5.Vector) should each refer to https://p5js.org/reference/#/p5.Vector/mag and https://p5js.org/reference/#/p5.Vector/heading
as the context in the reference makes more sense if the link to refer to the method inside p5.Vector as opposed to the current link which refers to the function in the [math module](https://github.com/processing/p5.js/blob/45bb7e3c204d1893ff78950187be00e5d78900ca/src/math/calculation.js).

**Comment by lmccart** [comment]
hi @banditelol! yes, it's open. this sounds right to me, please go ahead and make the change and let us know if you have questions.
