### ISSUE TITLE
The p5 library is missing

### ISSUE THREAD

**Issue by hellonearthis** [processing/p5.js#4485]
Hi there!

I was looking at download p5 to use locally and I can't seem to find it.

I started with looking to download 1.0.0 from cloudflare but it's serving the wrong version.
![image](https://user-images.githubusercontent.com/121805/80335054-3d71b700-88a7-11ea-8edd-ac67aaf21f25.png)

So I looked in the https://github.com/processing/p5.js/tree/master/lib expecting it to be there.
![image](https://user-images.githubusercontent.com/121805/80335171-9c373080-88a7-11ea-97c7-070036fe4112.png)

But no. So I downloaded the p5 repo and searched for p5*js and p5.js and it's not there too

I did manage to download it from  https://github.com/processing/p5.js/releases/
![image](https://user-images.githubusercontent.com/121805/80336248-d6ee9800-88aa-11ea-957d-cb859be450d4.png)

Which seemed kind of hidden to me and I don't if it's a bug/broken 
or something else (user problem: me :) )

**Comment by jeremydouglass** [comment]
I think "the library is missing" is just not right. It is right there in releases.

https://github.com/processing/p5.js/releases/tag/1.0.0

You can see that file drop commit here -- maybe it was a mistake, but maybe not, and the readme should just be updated.

https://github.com/processing/p5.js/commit/bf0e9aa5e5532a5efc802ac74e6086abdebf2e4e#diff-eccec67c712f3fdf3dfe1c0a5397edde

After all, most software is built and released, *not* checked in to its own repo.

**That said, the cloudflare bug seems like a big deal. I'd either retitle your issue about that or open a separate issue about "Cloudflare 1.0 loads 0.10.2" -- because that is a clear problem.**

**Comment by jeremydouglass** [comment]
It looks to me like this is the offending commit to cloudflare -- although I'm not familiar with their infrastructure.

https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/p5.js/1.0.0

So a couple months ago a bot checked in the p5.js 0.10.2 files to their CDN repo on the /1.0.0 path. Where do they get the files? Not releases, I guess. Someplace that this project configures / controls?

**Comment by lmccart** [comment]
I think this happened due to an error in the build process when we posted 1.0.0. The best way to resolve it would be to make a patch release.

**Comment by jeremydouglass** [comment]
Quick follow-up If the minor release is to 1.0.1 and it gets picked up, won't that mean that the CDN caches a bad version of 1.0.0 forever?

**Comment by lmccart** [comment]
yes, I don't know if there's a way to fix the CDN, it reads from npmjs which can't be edited. maybe submitting a manual pull request?

**Comment by jeremydouglass** [comment]
> maybe submitting a manual pull request?

Sure -- are the canonical artifacts that I should put in that PR currently in this repo's 1.0.0 release download?

**Comment by lmccart** [comment]
I'm sorry I'm not quite sure what "canonical artifacts" are, but the correct library files are posted here: https://github.com/processing/p5.js/releases/tag/1.0.0

**Comment by jeremydouglass** [comment]
I meant, if I post the stuff from the release, is it the right stuff, or is it also bad stuff.

**Comment by jeremydouglass** [comment]
Great -- I'll try to make a PR as soon as I can, later today at earliest. If anyone else wants to first, go ahead. Looks like the cdnjs repo is over 10GB, but most PRs seem to go through fast.

**Comment by lmccart** [comment]
ah got it, the right stuff :)
thank you!

**Comment by jeremydouglass** [comment]
What a headache. Finally got a commit made against cdnjs, and in the diff it looks like the version number strings are the only difference. Anyhow, I'll ping you on the PR -- they really want authors/core developers signing off on requests.

**Comment by jeremydouglass** [comment]
Great -- sign off on issue / PR here:

https://github.com/cdnjs/cdnjs/issues/13912
https://github.com/cdnjs/cdnjs/issues/13913

**Comment by lmccart** [comment]
wow, I didn't realize it was only the version number that got screwed up. well, thank you for looking into it and submitting the fix!

**Comment by limzykenneth** [comment]
Mentioned back in #4336 it is the same case as the version on jsDelivr (the code is 1.0.0 just the version string still says 0.10.2) but I imagined it would be even more impossible for jsDelivr to be able to update it to say the right version string since they reflect NPM more directly than cdnjs.

**Comment by jeremydouglass** [comment]
@limzykenneth Thanks so much, sorry I didn't find that earlier issue. While the code may be the same, I'd appreciate a 1.0.x latest release if possible to minimize confused support questions.

**Comment by lmccart** [comment]
@jeremydouglass sorry for the runaround, thanks for trying to make the change on cdnjs! we will work on getting a 1.0.1 release out soon. thanks for all your help on the forum and beyond. :)

**Comment by montoyamoraga** [comment]
since we cannot revert this,
and it will be fixed on the next release of p5.js
i am closing this issue
