### ISSUE TITLE
Accept object for creating p5.Color instance

### ISSUE THREAD

**Issue by Rizz0S** [processing/p5.js#4487]
#### Most appropriate sub-area of p5.js?

- [x] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Dom
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Feature enhancement details:

Hey folks! I'm currently doing some work related to colors in p5. The colors I'm working with are in object form, ie: `{r: 255, g: 255, b: 255}`. Currently an object such as the aforementioned is not accepted as a valid argument for creating a color via the [color() method](https://p5js.org/reference/#/p5/color).

I think this functionality could be useful as a part of the core. I've made use of it in the color library [chroma.js](https://gka.github.io/chroma.js/) and it was nice not having to manually parse it. Ideally it would work for all supported color modes (RGB, HSL, etc). Thoughts? I'm happy to start working on it myself, but I wanted to get an opinion before I submit a PR.

**Comment by akshay-99** [comment]
Hey @Rizz0S , isn't this just one extra line of code like this?
```js
let {r, g, b} = myColorObj;
color(r, g, b);
```
I don't know, but to me it feels adding library support for things which can otherwise be easily done in the sketch too may bloat the library over time.

**Comment by Rizz0S** [comment]
Thanks for responding! That is a fair point; it would add some non-trivial complexity to the library. And it's not much work on the client side.

In the past when I've worked with colors in some of my other applications it's been a feature I appreciated because some color APIs send back colors in object form. 

I am just starting out so I don't have a great idea of how much added complexity would contribute to library bloat. If anyone has any other thoughts on it, feel free to chime in! I'm still happy to work on it if others find the cost/benefit worthwhile.

**Comment by montoyamoraga** [comment]
hi @Rizz0S thank you for contributing :)
i do agree with @akshay-99, i rather not have the functionality
i guess when someone is using colors in such an object notation, they know what they are doing, and they should be able to format it to the other different ways that color() accepts inputs
it adds a lot of complexity to the library, because we don't only have rgb, but also hsb, and transparency, and i feel like that's a lot to parse, i would rather not modify color() for that use case.
any more thoughts? :)

**Comment by limzykenneth** [comment]
I agree with the general sense that this can be handled relatively easily on the client side while trying to add it in the library will also add to the complexity (seeing as it is a function overload that javascript isn't that fond of). I'm closing this issue for now. Thanks everyone!
