### ISSUE TITLE
Broken link in "Getting Started" tutorial on website

### ISSUE THREAD

**Issue by applemonkey496** [processing/p5.js#4497]
I noticed that the link for the p5.js CDN in the "Getting Started" tutorial ([here](https://p5js.org/get-started/)) is broken. The tutorial contains the following:

> Alternatively, you can link to a p5.js file hosted online. All versions of p5.js are stored in a CDN (Content Delivery Network). You can see a history of these versions here: [p5.js CDN](https://cdnjs.com/libraries/p5.js). In this case you can change the link to:
> ```html
> <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.0.0/lib/p5.js"></script>
> ```

The correct link would make the code
```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.0.0/p5.min.js"></script>
```

I would have created a pull request, but I couldn't find the source file anywhere on GitHub.

**Comment by Rizz0S** [comment]
The website is in a different repo - you might want to check out https://github.com/processing/p5.js-website
