### ISSUE TITLE
if the rect mode is corner you can put text on it but if rect mode is center the text function just doesn't work.  

### ISSUE THREAD

**Issue by ShardulAswale** [processing/p5.js#4498]
#### Most appropriate sub-area of p5.js?

- [1 ] Color
- [1 ] Core/Environment/Rendering
- [ ] Data
- [ ] Dom
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version: 
- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

**Comment by stalgiag** [comment]
Hello @ShardulAswale. The Github page is for tracking development of the library. General coding questions should be asked on [discourse.processing.org](discourse.processing.org). If you are very certain that this is a bug with the library, and not with your code, then you should post example code along with info about your p5 version, web browser, and operating system.

That said, it seems likely that you are drawing your text off-screen. Here is [an example sketch](https://editor.p5js.org/stalgiag/sketches/wuT1daOvU) showing text being drawn after a call to `rectMode(CENTER)`.

**Comment by montoyamoraga** [comment]
thank you @ShardulAswale for contributing!
i agree with the comments from @stalgiag,
so i am closing this issue for now,
if you cannot find a solution with other people on our forum,
and you are sure this is a bug, please include code on this issue,
and tag us to reopen it :)
