### ISSUE TITLE
adding recent contributors to README

### ISSUE THREAD

**Issue by montoyamoraga** [processing/p5.js#4502]

**Comment by montoyamoraga** [comment]
@all-contributors please add @sm7515 for docs

**Comment by montoyamoraga** [comment]
@all-contributors please add @banditelol for docs

**Comment by montoyamoraga** [comment]
@all-contributors please add @shaharyarshamshi for i18n

**Comment by montoyamoraga** [comment]
@all-contributors please add @shaharyarshamshi for translation

**Comment by montoyamoraga** [comment]
@all-contributors please add @shaharyar-shamshi for translation

**Comment by montoyamoraga** [comment]
@all-contributors please add @ayushjainrksh for translation

**Comment by montoyamoraga** [comment]
@all-contributors please add @ayushjainrksh for translation

**Comment by ayushjainrksh** [comment]
@montoyamoraga Thank you very much!

**Comment by montoyamoraga** [comment]
@all-contributors pleass add @Rizz0S for docs

**Comment by montoyamoraga** [comment]
@all-contributors please add @jtpio for doc

**Comment by lm-n** [comment]
@all-contributors please add @lm-n or accessibility
