### ISSUE TITLE
Get rid of warnings in empty-example/index.html

### ISSUE THREAD

**Issue by svendahlstrand** [processing/p5.js#4510]
Hello, 👋🏻

When opening the developer tools in my browser on the `empty-example/index.html` page, a "fail to load source map" warning shows up.

![Fail to load source map warning in Safari and Chrome.](https://user-images.githubusercontent.com/35639/80952243-ac946180-8df9-11ea-9a0e-793a58255f83.png)

Warnings about source maps can be scary and confusing – especially to new developers or anyone who's not learned about source maps yet. We could get rid of this warning by updating `empty example/index.html` to import `p5.sound.js` instead of `p5.sound.min.js`.

If that's a good idea, I would love to put together a pull request with the change.

**Comment by limzykenneth** [comment]
The source map should either be included along with the file that requires it or it should not be required from the file itself if it isn't distributed along with it. p5.js itself doesn't generates source maps so you may need to raise this question in the [p5.sound](https://github.com/processing/p5.js-sound) libray itself.

**Comment by svendahlstrand** [comment]
Thanks, @limzykenneth, that makes sense. As I understand it, the p5.sound add-on is updated regularly through pull requests from that project. So future pull requests from them should either include the source map or stop requiring it from `p5.sound.min.js` altogether.

Maybe we should decide which alternative we prefer first and then open an issue with the p5.sound project, asking if they be willing to change their release process accordingly?

**Comment by limzykenneth** [comment]
I'd prefer not having the source maps but the decision is up to p5.sound's maintainers and I'm ok with including the source maps if that's what they prefer.

**Comment by lmccart** [comment]
thanks @svendahlstrand I'm going to close this issue because it's being tracked over in the p5.sound repo
