### ISSUE TITLE
removeElements() works sporadically

### ISSUE THREAD

**Issue by bassamanator** [processing/p5.js#4512]
#### Details about the bug:
-using the latest p5.js (Feb 29, 2020)
-Manjaro linux
-Tested in Chrome, Mozilla, Opera
-Problem: by invoking removeElements(), buttons/input boxes are removed sometimes but not at others

**Comment by fenilgandhi** [comment]
#4414 did fix this issue, you will just need to wait for the next release.

**Comment by montoyamoraga** [comment]
thank you @bassamanator for pointing this out,
as @fenilgandhi pointed out, this issue was fixed and the fix will be included with the next release of p5.js :)

**Comment by bassamanator** [comment]
Oh I see.

Thanks!
