### ISSUE TITLE
Broken link to custom cursor on /reference/#/p5/cursor

### ISSUE THREAD

**Issue by jgordon510** [processing/p5.js#4513]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Dom
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other - Reference Docs

#### Details about the bug:

The website example at: https://p5js.org/reference/#/p5/cursor isn't working correctly.  In the bottom right-corner of the example, it should produce a custom cursor hosted at: https://s3.amazonaws.com/mupublicdata/cursor.cur but the url is dead, which breaks that portion of the example.

Here's the url in context:
`function draw() {
  line(width / 2, 0, width / 2, height);
  line(0, height / 2, width, height / 2);
  if (mouseX < 50 && mouseY < 50) {
    cursor(CROSS);
  } else if (mouseX > 50 && mouseY < 50) {
    cursor('progress');
  } else if (mouseX > 50 && mouseY > 50) {
    cursor('https://s3.amazonaws.com/mupublicdata/cursor.cur');
  } else {
    cursor('grab');`

**Comment by Rizz0S** [comment]
I'll take this if I'm allowed. Seems like a pretty easy fix. Is there a specific cursor it needs to be replaced with?

**Comment by montoyamoraga** [comment]
hi @jgordon510 thank you for pointing this out!
thank you @Rizz0S for offering to help,
it does look an easy fix, and i suggest replacing the call of the website
with one of the CSS ones mentioned on the reference 
ARROW, CROSS, HAND, MOVE, TEXT and WAIT
i am assigning you this issue, thanks!

**Comment by jgordon510** [comment]
I'm not sure replacing with one of the standard CSS icons really achieves
the purpose of that section of the code.  It's supposed to show how to load
a custom image.

**Comment by montoyamoraga** [comment]
@jgordon510 that's true, :)
instead of depending of assets hosted somewhere else, i propose we use
the avatar of github.com/processing, and we can pick either 16x16 or 32x32
https://avatars0.githubusercontent.com/u/1617169?s=16
https://avatars0.githubusercontent.com/u/1617169?s=32

**Comment by jgordon510** [comment]
That sounds like a great solution.

**Comment by Rizz0S** [comment]
Thanks y'all! Made the appropriate change - do I need to do anything in the p5.js-website repo as well, or will this change be sufficient?

**Comment by montoyamoraga** [comment]
@Rizz0S thank you! your PR is great and enough, the build of the website is automatic,
also i added you to the contributors of p5.js :)
https://github.com/processing/p5.js
