### ISSUE TITLE
Drag and Drop Files into Folder

### ISSUE THREAD

**Issue by DynamicSquid** [processing/p5.js#4518]
Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Dom
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other (specify if possible)

#### New feature details:

So I noticed how when you create a folder in p5.js, you can't drag and drop existing files into that folder. Instead you have to manually import files into that specific folder. So I'm wondering, could it be a possibility that you could drag and drop existing files into a folder? Thanks

**Comment by montoyamoraga** [comment]
hi @DynamicSquid thank you for your comments!
this issue is regarding our p5.js web editor,
https://github.com/processing/p5.js-web-editor
we will transfer this issue there :)

**Comment by montoyamoraga** [comment]
hi @catarak :) i assigned you because i don't have the permission to transfer this issue to the p5.js web editor repo :)

**Comment by DynamicSquid** [comment]
Oh yeah, np, I can do it 👍

**Comment by montoyamoraga** [comment]
u can also close this issue and copy/paste on a new issue here
https://github.com/processing/p5.js-web-editor
:)

**Comment by DynamicSquid** [comment]
did it, thanks for letting me know!
