### ISSUE TITLE
Square not using 4th parameter as rounding

### ISSUE THREAD

**Issue by AlexEltonPym** [processing/p5.js#4519]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] Dom
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version: 1.0.0
- Web browser and version: Google Chrome 81.0.4044.129 (Official Build) (64-bit)
- Operating System: Windows 10 Home 1903 18362.778

The square function is treating its 4th parameter as the width of the rectangle rather than rounding.
An example of this bug can be found on the square reference page:

![image](https://user-images.githubusercontent.com/18493526/81161755-6a247d80-8fcf-11ea-8708-baa1f1e05e3d.png)

- Steps to reproduce this:
This following snippet should look like a circle (it does in version 0.10.2) however, instead, it is creating a rect of size 100x100.

``` 
function setup() {
  createCanvas(500, 500);
}

function draw() {
square(width/2, height/2, 100, 100);
}

**Comment by limzykenneth** [comment]
This has already been fixed and will be available in the next release.
