### ISSUE TITLE
loadPixels() and retina

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js#452]
As @lmccart just discussed in person only 1/4 of the pixels are loaded into the pixels array on a retina display For example with a 10x5 canvas you get a pixel array of 50*4 which is correct, but all of the pixels are duplicated 4 times so you just have the top left corner of the image.  Forcing `_pixelDensity = 1;` is a workaround.

**Comment by kjhollen** [comment]
Alright. I've got a patch that fixes up set() & get() to work like a developer would expect (that is, with the same values set in size()).

I'm now working on updating the examples that access the pixels array directly. As implemented, some of the code/documentation is starting to look a little complex, for example:

The equivalent statement to get(x, y) using pixels[] is 
[pixels[this.pixelDensity*(y*width*this.pixelDensity+x)],
 pixels[y*this.pixelDensity*width*this.pixelDensity+x*this.pixelDensity+1], 
 pixels[y*this.pixelDensity*width*this.pixelDensity+x*this.pixelDensity+2],
 pixels[y*this.pixelDensity*width*this.pixelDensity+x*this.pixelDensity+3] ]. 
See the reference for pixels[] for more information.

The math here can be simplified a little with factorization, but the complexity here is intimidating for a beginner. So long as we're ok with that for now, I'm almost finished updating the examples and will have a pull request ready shortly.

**Comment by lmccart** [comment]
i think this is intimidating, but perhaps we can put a disclaimer sentence before this example in the documentation just acknowledging that it is complex, and suggest get() / set() for ease of use.

in the example snippet, could we pull out `var d = this.pixelDensity` for conciseness and readability? maybe this is what factorization means? :)

**Comment by kjhollen** [comment]
Yes, I think pulling out the density as a variable looks a lot less intimidating. I'll do that in the examples!

By factorization I just meant that we can get rid of one of those mentions of d/pixelDensity with clever use of parenthesis, but at the risk of making the code less direct.

<code>
pixels [d * (y * width * d + x) +1]
</code>

vs.

<code>
pixels [(y * d) * (width * d) + (x * d) +1]
</code>

What do you think?

**Comment by lmccart** [comment]
ah, yes, it's coming back to me now!
how about both?
start with the more explicit, and then say, or a shorter version...

**Comment by workergnome** [comment]
:clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap:
