### ISSUE TITLE
SaveFrame function exporting black frames

### ISSUE THREAD

**Issue by hcanndesign** [processing/p5.js#4520]
Hi there, 
When I export frames using SaveFrame("frame_####.png); I get a series of black frames rather than a recording of the sketch I've produced. Please could you advise?
Many thanks
Harriet

**Comment by akshay-99** [comment]
Hi @hcanndesign. Can you link a sketch on https://editor.p5js.org/ or a code snippet that would help to replicate this issue? Also, can you fill in the issue template, which would give us details like browser version, operating system, p5.js version etc.?

**Comment by montoyamoraga** [comment]
hi @hcanndesign thank you for contributing!
as @akshay-99 mentioned, you need more arguments on the saveFrames() function
so please refer to the reference of saveFrames() https://p5js.org/reference/#/p5/saveFrames

maybe you were looking at the Processing reference, where the function is called saveFrame()
without the "s" at the end, and where they explain how to save several images with "####" :)

in general, for doubts about code please post at  our forum https://discourse.processing.org/
for bugs you find please open an issue as you did today, yay
i am closing this issue now, tag us if you want it reopened if you think there is a problem :)
