### ISSUE TITLE
p5.js font issue

### ISSUE THREAD

**Issue by felixthefein** [processing/p5.js#4522]
Hello,

I am new to GitHub, and I just made a repository to host my p5.js sketch, which includes a .js, an .html, and an assets folder with .ttf and .otf font files and a .csv file.

However, the sketch yields an error in the console unless the fonts are removed from the sketch. (Note: the fonts don't seem to cause any problems when I view my sketch locally from the Terminal CLI.)

Here is the link to my repository: https://github.com/felixthefein/felixthefein.github.io

Any help would be much appreciated!

Thank you!

-ff

**Comment by montoyamoraga** [comment]
hi @felixthefein!
i noticed your repository is using an old version of p5.js
can you replace this line on your index.html
https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.5.16/p5.min.js
with
https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.0.0/p5.min.js
and see if that works?

**Comment by lmccart** [comment]
we're not able to reproduce, but please comment if you can provide more information in response to @montoyamoraga and we can reopen this.
