### ISSUE TITLE
Development Guide on wiki page not redirecting to correct page

### ISSUE THREAD

**Issue by shaharyar-shamshi** [processing/p5.js#4525]
Hi everyone
while exploring the wiki I clicked on Development guide link it redirect my to https://github.com/processing/p5.js/tree/master/developer_docs which does not exist instead we should be redirected to the https://github.com/processing/p5.js/tree/master/contributor_docs so I am opening the PR with correct link

**Comment by limzykenneth** [comment]
Fixed. Thanks @shaharyar-shamshi
