### ISSUE TITLE
WEBGL TRIANGLE_STRIP not rendering correctly.

### ISSUE THREAD

**Issue by Aierie** [processing/p5.js#4530]
#4439 ## Most appropriate sub-area of p5.js?

- [ ] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] Dom
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version: 1.0.0
- Web browser and version: Chrome, Firefox
- Operating System: MacOS Catalina
- Steps to reproduce this: 
With the WEBGL renderer, do
```
beginShape(TRIANGLE_STRIP);
  vertex(0, 0);
  vertex(50, 50);
  vertex(0, 50);
  endShape();
  beginShape(TRIANGLE_STRIP);
  vertex(-50, -50);
  vertex(0, -50);
  vertex(0, 0);
  vertex(50, -50);
  vertex(50, 0);
  endShape();
```
A triangle shape is produced, but stroke is only added on the first edge.

Resulting image:

![image](https://user-images.githubusercontent.com/39579264/81504249-cf9fa380-931a-11ea-9700-158ba6d48148.png)

Editor:

https://editor.p5js.org/Aierie/sketches/3xuXwEEiL

Works fine in version 0.10.2

**Comment by matvs** [comment]
I would like to start working on this issue.

**Comment by Aierie** [comment]
Hey @matvs , I've found the root cause and am submitting a PR soon!

**Comment by matvs** [comment]
Hi @Aierie 
I've just seen your comment, I should probably have waited for confirmation before starting working on this issue. My PR can be then rejected.

**Comment by Aierie** [comment]
No worries @matvs ! Just some coincidental timing. You can also close the PR yourself, would save the volunteers some work.
