### ISSUE TITLE
noFill() not working with vertices in WEBGL

### ISSUE THREAD

**Issue by MAKIO135** [processing/p5.js#4531]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [X] Core/Environment/Rendering
- [ ] Data
- [ ] Dom
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version: 1.0.0
- Web browser and version: Chrome v81.0.4044.138
- Operating System: MacOSX
- Steps to reproduce this:
```js
function setup() {
  createCanvas(400, 400, WEBGL);
}

function draw() {
  background(22);
  stroke(255);
  noFill();
  //fill(0, 0);
  
  rect(-180, -50, 100, 100);
  circle(130, 0, 100);
  
  beginShape();
  vertex(-50, -50, 0);
  vertex(50, -10, 0);
  vertex(-10, 50, 0);
  endShape(CLOSE);
}
```
![téléchargement](https://user-images.githubusercontent.com/1162231/81535884-dfdf6f00-936a-11ea-902c-0bf814d27cd9.png)
Like the rectangle and the circle, the triangle shape should not be filled.  
This was working correctly with p5js 0.10.2.   
It can be tested directly here: https://editor.p5js.org/makio135/sketches/othPcgFU2  

As a temporary workaround, using a transparent fill (`fill(0, 0)`) displays the shape correctly.

**Comment by akshay-99** [comment]
Hi @MAKIO135 . I think this issue is similar to #4350. If so, then this has been fixed now and the fix should be available in the next release.

**Comment by matvs** [comment]
Hi @MAKIO135 
Apart from @akshay-99 comment. 
This issue is already not reproducible for me and I have the same setup:
p5.js version: 1.0.0
Web browser and version: Chrome v81.0.4044.138
Operating System: MacOSX. 

Can you think of any other prerequisites, that are required in order to reproduce this bug?

**Comment by MAKIO135** [comment]
Ho, that's great ! Sorry for the repost 🙏
And thank you for this quick answers. Looking forward to the next release 😁

Le lun. 11 mai 2020 à 13:14, Akshay Padte <notifications@github.com> a
écrit :

**Comment by MAKIO135** [comment]
@matvs tried right now on my Android Phone with latest version of brave and get the same result
![Screenshot_20200511-134623_Brave](https://user-images.githubusercontent.com/1162231/81558450-fb0fa600-938d-11ea-9b1c-ad14426f12e6.jpg)
