### ISSUE TITLE
textAlign with multiline text incorrect

### ISSUE THREAD

**Issue by 03l54rd1n3** [processing/p5.js#4536]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Dom
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [x] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version: 1.0.0 
- Web browser and version: Chrome 81.0.4044.122
- Operating System: Windows 10 
- Steps to reproduce this:

```
function setup() {
  createCanvas(600, 600);	
}

function draw() {
  background(255);
  rect(100, 100, 20, 100);
  let str = [1, 2, 3, 4, 5].join("\n");
  textAlign(CENTER, BOTTOM);
  text(str, 100, 100, 20, 100);
}
```

textAlign BOTTOM doesn't work with multiline text (and looking at the result it might not even center pixel-perfectly with new lines).

![image](https://user-images.githubusercontent.com/8194856/81568388-fa7f0b80-939d-11ea-8d54-d9441099a316.png)

**Comment by matvs** [comment]
Is anyone working on this bug? If not, then I'd like to claim this issue.

**Comment by dhowe** [comment]
See also https://github.com/processing/p5.js/issues/4449

**Comment by 03l54rd1n3** [comment]
and PRs #4475, #4422. Didn't check whether they resolve this, tbh.

**Comment by lmccart** [comment]
this has been fixed with https://github.com/processing/p5.js/commit/ed7ca80b683899c9e771ece7ce0a45155502f576
