### ISSUE TITLE
Contributor Dev Process - automatically update changes to references

### ISSUE THREAD

**Issue by ffd8** [processing/p5.js#4541]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Dom
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other (Contributor Docs)

#### Feature enhancement details:

Not sure if this is a feature enhancement or a bug??

Within  the contributor docs, [Development Process](https://github.com/processing/p5.js/tree/master/contributor_docs#development-process), one can rebuild the entire library + references etc, using `npm run grunt` (takes some time) or watch for live changes and rebuild automatically with `npm run dev`. Should(n't) this also recompile the references to preview any changes made to them? 

Within CLI, the first time I run `npm run dev`, I see:
```
grunt browserify connect:yui watch:quick

Browserslist: caniuse-lite is outdated. Please run next command `npm update`
Running "browserify" task
>> Bundle lib/p5.js created.

Running "connect:yui" (connect) task
Started connect web server on http://localhost:9001

Running "watch:quick" (watch) task
Waiting...
```

after modifying/saving a file I only see:
```
>> File "src/core/main.js" changed.
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
Running "browserify" task
>> Bundle lib/p5.js created.

Done.
Completed in 9.870s at Tue May 12 2020 14:12:09 GMT+0200 (Central European Summer Time) - Waiting...
```

Seems only the p5.js lib updated and references preview at `http://localhost:9001` hasn't changed... Guessing there's an undocumented method to do a slightly slower watch that includes references (vaguely recall it being there in a previous process)?

**Comment by ffd8** [comment]
Aha, just realized from package.json that `npm run docs:dev` seems to do this (just have to refresh the reference page after any changes once compiled). Perhaps the contributor docs could have a short blurb about each of the optional CLI commands (atleast those most useful to contributing workflow)? Since there are multiple options for the docs.... `docs` and `docs:dev`

**Comment by limzykenneth** [comment]
I believe some of the commands are outdated, for example there probably shouldn't be two tasks for documentation now (`docs` and `docs:dev`) as it was previously used for local previewing but since the preview HTML templates are no longer stored and built in this repo there shouldn't be a need to seperate them into two tasks.
