### ISSUE TITLE
I hope to change the drawing of 3D WebGL into an asynchronous call. The function fuse coordinates and texture array, the most important is asynchronous call.

### ISSUE THREAD

**Issue by JiXiaoYao** [processing/p5.js#4544]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Dom
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Other (specify if possible)

#### New feature details:

Because the drawing time of P5.JS in 3DWebGL is too long, when I draw about 1600 physical blocks, the fps will drop greatly, because I can only draw in the thread of the draw function, but it will take a lot of time.

If the team cannot solve this problem, you can try to open the WebGL native method to the user.
But what I want most is to enable p5.js to support drawing 3DWebGL graphics in parallel.

This has nothing to do with the performance of WebGL. It is purely that the function of p5 is insufficient when drawing 3D entities. My CPU frequency is already up to 4Ghz, but due to the need to draw nearly thousands of entities in serial, the frame rate of draw is sharply reduced.

9X9:

![9x9](https://user-images.githubusercontent.com/26181058/81755961-59b94a80-9488-11ea-8e50-bb8d34af98dd.JPG)

20X20:
![20x20](https://user-images.githubusercontent.com/26181058/81755947-4a3a0180-9488-11ea-992c-ae8fcb44174b.JPG)

40X40:

![40X40](https://user-images.githubusercontent.com/26181058/81756008-88372580-9488-11ea-9d19-b3a84e41e41e.JPG)

**Comment by stalgiag** [comment]
Hi @JiXiaoYao check out the accepted answer for [this StackOverflow question.](https://stackoverflow.com/questions/51710067/webgl-async-operations)

Additionally, I would just say that the goal of p5's WebGL mode is to offer an easy intro to WebGL for the web for people transitioning from p5's 2D mode or Processing's 3D mode. If you want to create very complex scenes you should try writing vanilla WebGL or using [Three.JS](https://threejs.org/). Though it bears mentioning that you will still run into resource issues when drawing more than 1000+ objects without optimizations on your side.

I am closing this issue for organizational purposes. If you feel that I missed the point, comment here with more details about what you are proposing and I will reopen the issue.

Good luck!
