### ISSUE TITLE
Square expects height and width separately when adding fourth parameter for rounded corners 

### ISSUE THREAD

**Issue by LukasOpp** [processing/p5.js#4547]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] Dom
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version: v0.10.2
- Web browser and version: Firefox 76.0.1
- Operating System: Mac OSX 10.13.6
- Steps to reproduce this:
You can see this behavior in the Documentation for Square (Example 2): https://p5js.org/reference/#/p5/square
<img width="761" alt="Screen Shot 2020-05-13 at 14 35 15" src="https://user-images.githubusercontent.com/4512328/81812874-021dec00-9527-11ea-9867-209bd6365262.png">

**Comment by LukasOpp** [comment]
I just made a build of the current master and saw that square is working fine there

**Comment by limzykenneth** [comment]
Yes this has been fixed in lastest master and will be available in the next release.
