### ISSUE TITLE
Page refresh appears to disable audio context `resume()` 

### ISSUE THREAD

**Issue by doubledherin** [processing/p5.js#4549]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Dom
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other (specify if possible): Sound

#### Details about the bug:

- p5.js version: /*! p5.js v1.0.0 February 29, 2020 */ (minified)
- Web browser and version: Google Chrome | 81.0.4044.138
- Operating System: Mac OS High Sierra 10.13.6 
- Steps to reproduce this:

I am running my p5 app locally by clicking on my index.html file and choosing 
"open with Live Server" .

I am running into a problem with audio context: `main.js:21 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu`. 

So I read up on audio context and added calls to resume the audio context. 

However, apparently, the only thing that puts the audio context in a "running" state is if I make a local code change and save. Then the sounds play and console logs of the state of the audio context show "running".

But if I refresh the page without making a local code change, it shows "suspended", and even user interactions triggering a "resume" call don't work.

Also, whether or not the context resumes, I see Chrome's warnings in the console `p5.sound.min.js:2 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu` (notice that the warning here is refering to the sound libary, not my main.js file).

Here is a link to all of the source code: https://github.com/doubledherin/streakin

Here's a snippet of the relevant code:

```let framesPerSecond = 60
let gameStartDelayTimeInSeconds = 8
let copDelayTimeInSeconds = 15
let funk
let crowdCheer
let mouseMoved = false

function preload() {
  loadSounds()
}

function setup() {
  var cnv = createCanvas(900, 800)
  cnv.mouseMoved(triggerSounds)
  loadImages();
  mascot = new Mascot(100, 200)
  butt = new Butt(width - 50, height - 50)
  cop = new Cop(0, height-200)
}

function triggerSounds() {
  // This log shows "running" if I've made a code change and saved without refreshing,
  // but shows "suspended" if I refresh -- even if I move the mouse.
  console.log("AUDIO CONTEXT STATE: ", getAudioContext().state)
  if (!mouseMoved) {
    getAudioContext().resume()
    funk.play()
    crowdCheer.setVolume(0.3)
    crowdCheer.loop(gameStartDelayTimeInSeconds)      
  }
  mouseMoved = true
}

function loadSounds() {
  crowdCheer = loadSound('./assets/crowdCheersTrimmed.mp3');
  funk = loadSound('./assets/funk.mp3');
  copWhistle = loadSound('./assets/cop-whistle.mp3');
}
```

**Comment by limzykenneth** [comment]
@doubledherin I'm not sure what development server you are using so I can't tell why it is triggering the audio to start playing but the autoplay policy of chrome is such that `mouseMoved` is not a valid user gesture that can start the audio context which is why after refreshing the sound does not play on `mouseMoved`. It needs to be something like `mouseClicked()`.

**Comment by doubledherin** [comment]
Hey @limzykenneth ! I just realized that earlier today and went to close this issue but couldn't find it. I'm using a mouse click now and all is hunky dory. Thanks!
