### ISSUE TITLE
@all-contributors add @kyle1james for p5js.sound

### ISSUE THREAD

**Issue by kyle1james** [processing/p5.js#4551]
🎉 @all-contributors add @kyle1james for p5js.sound with GSoC 🎉

**Comment by montoyamoraga** [comment]
hi @kyle1james i saw your PRs at the p5.js sound repo, thanks!
the all-contributors categories are here: https://github.com/processing/p5.js/issues/2309
i am adding you as code if that's ok with you

@all-contributors please add @kyle1james for code

**Comment by montoyamoraga** [comment]
solved by #4553
