### ISSUE TITLE
Small bug with CSS in online editor

### ISSUE THREAD

**Issue by Guillaume57** [processing/p5.js#4554]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] Dom
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

Hello,

There is a small problem in the online editor, when editing a CSS and using custom variables, for example:
```css
:root
{
  --red: #ff0000;
}
```
It's working, but the editor will show a warning "Expected RBRACE" on the line "--red: #ff0000;"

**Comment by limzykenneth** [comment]
Hi @Guillaume57, this is the repository for the p5.js library. You should post this issue to the web editor [repository](https://github.com/processing/p5.js-web-editor/issues). Thanks!

**Comment by Guillaume57** [comment]
Sorry
