### ISSUE TITLE
noErase() not working in WEBGL

### ISSUE THREAD

**Issue by valentinptc** [processing/p5.js#4555]
When calling erase() in WEBGL noErase() does not jump back to the previous mode.
I believe the reason is that BLEND mode is default but has no case defined in _applyBlendMode.

```
 switch (this.curBlendMode) {
              case constants.BLEND:
              case constants.ADD:
                gl.blendEquation(gl.FUNC_ADD);
                gl.blendFunc(gl.SRC_ALPHA, gl.ONE_MINUS_SRC_ALPHA);
                break;
```

**Comment by stalgiag** [comment]
Thanks for catching this @valentinptc !

This is indeed a bug. [This sketch shows a workaround ](https://editor.p5js.org/stalgiag/sketches/HUFUmC7X1)for your immediate needs.

I submitted a PR that solves the issue quickly but in a non-ideal way. I explain the problem in more detail in that PR.
