### ISSUE TITLE
Style width/height etc throws error when passed number value as argument

### ISSUE THREAD

**Issue by limzykenneth** [processing/p5.js#4556]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [x] Dom
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version:  1.0.0
- Web browser and version:  Firefox 76.0.1 (presumably all other supported browsers as well)
- Operating System:  macOS 10.14
- Steps to reproduce this:

```
function setup() {
  createCanvas(400, 400);
  
  let div0 = createDiv('hello');
  div0.style('width', 200+'px'); //works
  div0.style('height', 300); //Uncaught TypeError: val.replace is not a function (sketch: line 6)
  div0.position(50, 50, 'absolute');
}
```

As reported by @mkmori in #3447, calling something like `p5.Element.style('width', 200)` will cause a TypeError to be thrown because the function is expecting a string. Passing a number should be a valid value since it is a valid CSS value (default to pixels).

This should affect `width`, `height`, `top` and `left`. A check should be in place [here](https://github.com/processing/p5.js/blob/master/src/dom/dom.js#L1924) to see if the value is a number of not, if it is don't do the `replace`.

**Comment by mkmori** [comment]
Thanks, @limzykenneth ! And @nebbles ! I just dug in to see, css does not seem to default to "px" if passed a unitless, numerical value (at least in Chrome...?) And it seems p5.js does not create the attribute with invalid argument...or does something else strip it out...? (So much n00b! :)

Would casting/re-casting the argument `toString()` make sense [there](https://github.com/processing/p5.js/blob/master/src/dom/dom.js#L1924) ?

`      var numVal = val.replace(/\D+/g, ''); //fails if val is a number`
`      var numVal = val.toString().replace(/\D+/g, ''); //ok to toString() even if val is already a string?`

Css "degrades gracefully," so a newbie like me could just ask around and puzzle out why an assignment had no effect, right?

Beyond that, _maybe_ it would be consistent with other p5 functions to append "px"...? Or if no css attributes take unitless, numerical arguments, catching the `style()`-specific error _might_ also be (more than) sufficiently n00b-friendly...?

**Comment by limzykenneth** [comment]
You're right, CSS does not accept unitless numerical value. In this case I would revert and say this isn't a bug as the aim here is to let `style` be a thin wrapper around CSS and not do any additional processing to the value that is passed to the underlying API. 

This would apply to `style` function only as it is designed to reflect CSS values, other functions however like `position` is not really CSS specific, which the original issue addresses so appending `px` in that case made sense.

We generally aim to make our API as easy to use as possible but without introducing too much "magic" that could make eventual transition to native API difficult, so appending `px` when just number is passed for me is a bit too far. What do you think?

**Comment by mkmori** [comment]
So tweak `style()` to just pass the css along without crashing, right? And let css do its thing? That seems reasonable to me! :)

Would inserting `toString()` before `replace()` do the trick? I read up and down the dom.js code, but I don't quite follow after the regex strips out all non-numerical characters...not sure what happens to "px" or "%" or whatever unit may be specified in the value string....

On the documentation side, if there are no "unitless, numerical arguments" in css, perhaps "Number" should be removed as a possible data type for "value" on the [`style()` reference page](https://p5js.org/reference/#/p5.Element/style) ...?

(BTW, separate website issue...`myDiv.style('font-size', mouseX + 'px');` in the third example sketch is fun...but it sure seems to make it difficult to view and navigate that page, esp. in mobile!)

**Comment by limzykenneth** [comment]
The code after the replace is meant to update the values returned by calling `width()` `height()` etc on the element, although if just a number is passed in in this case, the code probably shouldn't run to update those values as well since the change won't be reflected in CSS. This update should probably be rewritten to get pixel value directly from the Web API instead of relying on the provided arguments as you noted it would have problematic behaviour with units that are not pixels.

> On the documentation side, if there are no "unitless, numerical arguments" in css, perhaps "Number" should be removed as a possible data type for "value" on the style() reference page ...?

By removing this type in the documentation I think it will also remove Number as a valid type for that argument which the FES will warn the user when they attempt to pass in just a numeric value. So that's a good idea.

> (BTW, separate website issue...myDiv.style('font-size', mouseX + 'px'); in the third example sketch is fun...but it sure seems to make it difficult to view and navigate that page, esp. in mobile!)

I agree, it is overdoing it a bit. It can be tweaked or replaced with another example I think.
