### ISSUE TITLE
HSB needs more documentation as well as other constants

### ISSUE THREAD

**Issue by hellonearthis** [processing/p5.js#4557]
Hi there!

There is not documentation for the HSB https://p5js.org/reference/#/p5/HSB
https://github.com/processing/p5.js/blob/1.0.0/src/core/constants.js#L344

 [x] Core/Environment/Rendering

#### Feature enhancement details:
There are not docs on this,  even a link back to where there are HSB docs would help.
I also notice that the constants don't have much docs at all.

**Comment by cedarfall** [comment]
Hello! Can I work on this? There are not that many good articles or references for HSB. I was thinking of linking to this article: https://learnui.design/blog/the-hsb-color-system-practicioners-primer.html as it clearly explains the concept.

**Comment by montoyamoraga** [comment]
hi @cedarfall sounds great, thank you! i am assigning to you this issue, please tag me when you create the pull request :)
