### ISSUE TITLE
Need better blend state management in RendererGL

### ISSUE THREAD

**Issue by stalgiag** [processing/p5.js#4562]
There is problematic state management of `_cachedBlendMode` and `curBlendMode` in RendererGL. This was introduced by an optimization to `RendererGL._applyBlendMode` that tries to avoid unnecessary GL calls by caching the last applied blend mode. The problem is that `erase()` and `noErase()` also change `_cachedBlendMode`.

`_cachedBlendMode` is being used here to do two conceptually different things.

1. only do a call to `gl.blendFunc()` when the new GL blend mode is different than the applied blend mode. This makes it so that if someone calls `blendMode()` every frame, it won't do unnecessary GL calls.
2. It is used to store the blend mode before calls to `erase()` so that the previous blend mode can be applied after `noErase()`.

To further complicate things, these two uses mutate `_cachedBlendMode()` asynchronously from one another because `_applyBlendMode` is only called upon rendering.

Another property that is something like`preEraseBlend` could be added to RendererGL but then the `_cachedBlendMode` use between Renderer2D and RendererGL would diverge because Renderer2D only uses `_cachedBlendMode` to track pre/post eraser blends since it doesn't need the GL optimizations.

This is all to say that the blend state management in RendererGL is very tricky currently and probably should be restructured.

**Comment by Garima3110** [comment]
I am trying to work on this issue.
Thankyou!

**Comment by davepagurek** [comment]
I'm going to close this now that #6699 is merged in. Feel free to open more issues with further refactors!

**Comment by Garima3110** [comment]
> I'm going to close this now that #6699 is merged in. Feel free to open more issues with further refactors!

Thanks @davepagurek for you help on this . Got more insights on the codebase. All thanks to you..!  :-)
