### ISSUE TITLE
Not enough semicolons

### ISSUE THREAD

**Issue by DavidMatuszek** [processing/p5.js#4565]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Dom
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version: 
- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

In JavaScript, semicolons are supposed to be optional at the end of statements. p5.js allows statements without a semicolon terminator, but it apparently still records them as errors. When approximately 100 statements have been entered without semicolons, p5.js will not run the program, and reports "too many errors." The fix is to add semicolons to a handful of statements--it doesn't matter which ones.

I have not included a simple code snippet that demonstrates the problem. I hope the reason for this is obvious.

**Comment by limzykenneth** [comment]
Hi @DavidMatuszek, I'm not sure I understand the issue. p5.js does not pose any restriction on the user code style, meaning whether to use semicolons or not is not enforced by p5.js. 

For the source code of the library itself, we do enforce having semicolons but those are checked by automatic linters and they will stop any code with missing semicolons from passing the tests, but that check will fail regardless of whether there is one missing semicolon or 100 missing semicolons.

The web editor also does not enforce code styles on the user's code and missing any semicolons does not giving any warnings or errors there.

**Comment by DavidMatuszek** [comment]
I haven’t gotten another response from you, so I don’t know if you saw my attachment.

—Dave Matuszek

**Comment by lmccart** [comment]
@DavidMatuszek I think the attachment didn't come through. Can you try posting it directly on this github issue instead of replying to the email. Thanks!

**Comment by DavidMatuszek** [comment]
![too many errors](https://user-images.githubusercontent.com/362586/83955775-c7a52780-a824-11ea-9498-cc771fad45c7.png)

**Comment by limzykenneth** [comment]
@DavidMatuszek What you are using is the Processing editor's p5.js mode. It is not officially maintained by the p5.js project. You should raise this issue over at the Processing editor p5.js mode's [repository](https://github.com/fathominfo/processing-p5js-mode/issues). Thanks.
