### ISSUE TITLE
Can notes be added?

### ISSUE THREAD

**Issue by Ma-XX-oN** [processing/p5.js#4567]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [x] Dom
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### New feature details:
Would be nice to have some form of note/warning/important tagging.  E.g.

@note When you do this, that could result in that.
@warning Doing this could format your hard drive and cause demons from exiting your nostrils.
@important Do not look into the sun too long or you will go blind!

This would, for example, allow the markup to translate this to something like putting a vertical line to the left and add a hanging indent.  Somehow emphasize the paragraphs that follow the tag.

**Comment by limzykenneth** [comment]
@Ma-XX-oN I'm guessing you are refering to he web editor, in that case you should file this issue over at the web editor [repo](https://github.com/processing/p5.js-web-editor/issues). Thanks!

**Comment by Ma-XX-oN** [comment]
Web editor?  Not sure what you mean by that.  I mean in the documentation.  Sorry, I'm not sure what part this is supposed to be in.  Parsing the documentaion?
