### ISSUE TITLE
FES: validateParameters does not detect trailing undefined arguments

### ISSUE THREAD

**Issue by akshay-99** [processing/p5.js#4571]
#### Most appropriate sub-area of p5.js?

- [x] Other (Friendly Errors)

As mentioned in #4558

Consider the sketch
```js
let r, g, b;

r = 40;
b = 10;
function setup() {
  createCanvas(400, 400);
  color(r, g, b);
}
```
As expected we get a validation message
```
 p5.js says: color() was expecting Number for parameter #1 (zero-based index), 
received an empty variable instead. If not intentional, this is often a problem with scope: 
[https://p5js.org/examples/data-variable-scope.html] at about:srcdoc:60:3. [http://p5js.org/reference/#p5/color] 
````

But for the following, no validation message is generated
```js
let r, g, b;

r = 40;
g = 10; // now b would be undefined
function setup() {
  createCanvas(400, 400);
  color(r, g, b);
}
```

**Comment by akshay-99** [comment]
Fixing this would also involve changing the code inside `p5.proptotype.save` [here](https://github.com/processing/p5.js/blob/master/src/io/files.js#L1488) .
The problem is that when we call `save()` to save a JSON like this `save(myJSON, 'my.json')`, a call is made to `saveJSON` with the arguments `(args[0], args[1], args[2])`. However, args[2] is optional and is undefined in this case. If we fix this issue, then we would have a `ValidationError` here, resulting in a test failure.

To solve this problem, we could instead apply a check on `arguments.length` in `save()` and only pass the optional third parameter  to `saveJSON` only if `arguments.length === 3`. 

Similarly in selectAll example 2 [here](https://p5js.org/reference/#/p5/selectAll) since `d` and `f` would be `null` as no DOM elements exist that fit the selection criteria, on fixing this issue, this example also gives a `ValidationError`, resulting in a test failure.

So if we were to go ahead and fix this issue, we must either change this example so that `d` and `f` are not `null` anymore, or somehow make the FES bypass this particular example.

@stalgiag what are your thoughts on the selectAll problem?

**Comment by limzykenneth** [comment]
I may be wrong but isn't parameter validation compared against the documentation? In that it doesn't really matter what the source code itself checks for `parameterValidation` just checks the number of arguments and type of arguments against the documentation.

Parameter validation did not throw a warning in the case of `color()` is because with 2 parameters that are numbers, they are still valid (being `color(gray, [alpha])`).

**Comment by akshay-99** [comment]
@limzykenneth yes it is checked against the documentation. But the number of arguments passed by the user is a huge factor in scoring. `color(gray, [alpha])` shouldn't be a valid format to check against in this case because `arguments.length` still is 3 in this case, only the 3rd argument is `undefined`. I believe if the user has passed 3 arguments, it is more likely that the user intended to go for the formats with 3 arguments.

So what happens right now is the code [here](https://github.com/processing/p5.js/blob/master/src/core/error_helpers.js#L830) reduces the value of `arguments.length` to purposely ignore trailing undefined arguments. I believe this shouldn't happen because I said above if someone passes 3 arguments, I believe it is far more likely that they intended to go for the formats with 3 arguments.

**Comment by akshay-99** [comment]
As another example consider 
```js
let x, y, r;
function setup() {
  createCanvas(400, 400);
  x = 40;
  y = 30;
  circle(x, y, r);
}
```

Currently since we are ignoring the trailing undefined argument, the FES gives
```
🌸 p5.js says: circle() was expecting at least 3 arguments, but received only 2
```
Ideally it should be
```
🌸 p5.js says: circle() was expecting Number for parameter #2 (zero-based index), received an empty variable instead
```

**Comment by limzykenneth** [comment]
> So what happens right now is that the code here reduces the value of argCount to purposely ignore trailing undefined arguments.

So removing this is what affects `save()` and `selectAll()`'s tests?

The tail parameter culling is added in #2780 which is solving #2740. I think it is mainly to deal with  edge cases, in particular `rect(0,0,0,0,null,0,0,0); // null, non-trailing, optional parameter`. 

I'm not nearly familiar enough with FES to be able to suggest anything here and current also don't have the capacity to look into it. @akshay-99 I do appreciate if you can look into this and give us an overview of what needs to change to fix this. Thanks.

**Comment by akshay-99** [comment]
> So removing this is what affects save() and selectAll()'s tests?

Yes. That seems to be the case. 

> I think it is mainly to deal with edge cases, in particular rect(0,0,0,0,null,0,0,0); // null, non-trailing, optional parameter.  

That doesn't seem so as I have tried these edge cases after removing the line [here](https://github.com/processing/p5.js/blob/master/src/core/error_helpers.js#L830) and the FES seems to work for these cases correctly even after the change. Moreover `rect(0,0,0,0,null,0,0,0);` wouldn't be affected by the removal as there are no trailing undefined args here.
And all other FES tests ( except the ones for `save` and `selectAll` , which fail for the reason I mentioned above ) still do pass.

> I do appreciate if you can look into this and give us an overview of what needs to change to fix this. Thanks.

Yes I am on it. Thanks!

**Comment by stalgiag** [comment]
Thanks for looking into the history of this @limzykenneth . 

My quick take is that the trailing argument culling that @akshay-99 [points to was](https://github.com/processing/p5.js/blame/1e077add94d8f7c93260e732d4267299fa6edee6/src/core/error_helpers.js#L830) introduced to handle the specific edge cases listed in #2740 but it solves the problem with too broad of an impact. If the edge cases can still be handled correctly without forced trimming then that seems preferable.

It also makes sense to me that `save` wouldn't pass along arguments that it didn't receive.

I also do not have much history of interacting with FES and these are just my quick opinions. #2740 reminded me that the FES needs to be able to handle really unexpected arguments, it might be nice to think about ways that we can test for a large set of different argument configurations during FES unit testing.

**Comment by akshay-99** [comment]
So as an update on this, it seems I missed that there was one more test failure in loadModel documentation, example 1 [here](https://p5js.org/reference/#/p5/loadModel).
`ValidationError: loadStrings() was expecting Function for parameter #2 (zero-based index), received an empty variable instead. `
We are not passing any callbacks in the example and that's okay because those are optional parameters. But the code [here](https://github.com/processing/p5.js/blob/master/src/webgl/loading.js#L154) passes the `failureCallback` argument to `loadStrings` without checking if it exists. And so we see a validation error in loadStrings. This can also be fixed via a simple check. 

So far what I have seen is that none of these test failures is too surprising and most of them have an easy fix in the source. Should I go ahead and fix them?

> #2740 reminded me that the FES needs to be able to handle really unexpected arguments, it might be nice to think about ways that we can test for a large set of different argument configurations during FES unit testing.

Do you mean some way of automatically generating permutations of arguments?

**Comment by stalgiag** [comment]
Do you mean some way of automatically generating permutations of arguments?

Yes. "Permutations" is the word I was looking for :-)
