### ISSUE TITLE
how can i re-trigger draw function in case of value change from HTML

### ISSUE THREAD

**Issue by watsonbiard** [processing/p5.js#4578]
i was creating a sketch where i'll take user input by range slider and re-trigger the draw function with the changed  value. but i seem like value changes  but i could not trigger the draw function by  the value from user.

        var slider = document.getElementById("size");
        var output = document.getElementById("demo");
        output.innerHTML = slider.value;
        let size = (slider.value);
        slider.oninput = function() {
            let size = slider.value;
            console.log(size);
            output.innerHTML = this.value;
             draw();                  //draw function not working with value changes
        }
        console.log(size);
    
        let x = 0;
        let y = 0;
        var spacing_value = 30;

        function setup(){
            createCanvas(500 , 500);
            background(0);

            }
        
        function draw(){
                strokeWeight(5);
                fill(random(255),random(255),random(255));
                stroke(random(255),random(255),random(255));
                
                if (random(10) < 5 ){
                    line(x, y, x+spacing_value, y+spacing_value);                             
                }
                else{                    
                    line(x, y+spacing_value, x+spacing_value, y);                    
                }
                x = x + spacing_value;
                if (x > width){
                    x = 0;
                    y = y + spacing_value ; 
                }
            }

![image](https://user-images.githubusercontent.com/35967367/82911481-c30f8200-9f8d-11ea-8117-cfaeee203fc3.png)

**Comment by hellonearthis** [comment]
Use noLoop() and add a changed call back to the slider callback call redraw. https://p5js.org/reference/#/p5/redraw
https://p5js.org/reference/#/p5/changed
