### ISSUE TITLE
p5.Element.child throws an error when child is not found

### ISSUE THREAD

**Issue by fenilgandhi** [processing/p5.js#4581]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [x] Dom
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:
This is less of a bug and more of an unhandled case in `p5.Element.child`.
It accepts an `id` of a childElement as a parameter, finds the element in DOM and adds it as a childElement. In case, any element is not found with a matching `id`, it will throw `TypeError : Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'`. 

I think this can be handled by one of the two solutions
1. Check if the element is found, otherwise throw an error with a better message.
2. Ignore/Do nothing  and revert back to default behaviour of returning all child.

##### How should i handle it ?

- p5.js version: 1.0.0
- Web browser and version: Chrome 80.0.3987.122
- Operating System: Manjaro 19.0.2 Kyria (Linux 4.19.108-1-MANJARO)
- Steps to reproduce this:
   - Create a p5.Element ( testElement)
  -  Try to add a child element by giving an id of a child element using testElement.child("id")

**Comment by lmccart** [comment]
I think it should just return null, similar to calling `querySelector()` when a node is not found.
