### ISSUE TITLE
Using querySelector and querySelectorAll for select and selectAll

### ISSUE THREAD

**Issue by limzykenneth** [processing/p5.js#4584]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [x] Dom
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Feature enhancement details:
A couple issues pop up when I'm trying to use `select()` and `selectAll()`. Both of them are related to the CSS selection pattern of `.class1, .class2` (ie. selecting elements using multiple queries seperated by commas). 

In the case of `select()` it always returns null instead of the first element selected. For `selectAll()` it returns an empty array instead of array of elements matching the CSS selector.

```javascript
function setup() {
  console.log(document.querySelector("body, html"));
  console.log(select("body, html"));
  
  console.log(document.querySelectorAll("body, html"));
  console.log(selectAll("body, html"));
}
```

I wonder if there's any reason for us to not make `select()` and `selectAll()` a wrapper around `querySelector()` and `querySelectorAll()` respectively. If not I think switching to these API would help simplify the codebase a bit and extend support to whatever the native API support which would cover a lot of the CSS selector syntax.

**Comment by liampuk** [comment]
Hi! I'd love to contribute to p5.js and this seems like a good first issue, would it be okay for me to work on this? there seems to be a [performance hit](https://gomakethings.com/javascript-selector-performance/) when using querySelector vs getElementById but I highly doubt it's noticeable in practice.

**Comment by lmccart** [comment]
I think that makes sense. If I remember correctly, last time we discussed this `querySelector` was not yet broadly supported so we didn't use it. But now it is, so this seems appropriate.
