### ISSUE TITLE
Support for explicitly setting file type of .obj or .stl files

### ISSUE THREAD

**Issue by ismailnamdar** [processing/p5.js#4585]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Dom
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Other (specify if possible)

#### Feature enhancement details:

Currently the file type for the model is determined by the file extension of the path given to `loadModel()`. This is a limitation in the case that the model exists on a server outside of ones control but that has a different file extension. In this case, currently it is not possible to load the model even though model would be supported. It would be helpful to be able to explicitly give `loadModel()` the file type of the model being loaded. 

### Example
-  Server hosts a `.obj` file with a randomized file name with no extension. 

`https://www.example.com/aAde3AsdfaHy` 

- Another example is when you have a valid file type but the path requires a signature as query parameter.

`https://www.example.com/model.obj?AWSAccessKeyId=aSftajdS123aS`

**Comment by stalgiag** [comment]
I think this is a good idea. Any interest in working on it?

**Comment by ismailnamdar** [comment]
Yes! I opened a pull request.
