### ISSUE TITLE
How can i save a small canvas with high resolution 8k image file 

### ISSUE THREAD

**Issue by watsonbiard** [processing/p5.js#4587]
i have a canvas of 500x500 .and i want to save the canvas as a super high resolution image. but i don't know how  to do it. i don't wanna to increase the canvas size because it become bigger then my screen.

**Comment by limzykenneth** [comment]
Hi, if you need help with your own code, please direct your questions to the [forum](https://discourse.processing.org). We use GitHub issues mainly for bug reports and feature requests only. Thanks!
