### ISSUE TITLE
Can there be a version of p5.js that works for Internet Explorer 11 (IE 11)?

### ISSUE THREAD

**Issue by ghost** [processing/p5.js#4588]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] Dom
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [x] Utilities
- [x] WebGL
- [x] Other (specify if possible)

**Comment by limzykenneth** [comment]
@stevenrays p5.js should still be working on IE 11. Is there something specific that is not working on IE 11 that you found?

**Comment by akshay-99** [comment]
Hi, so while I was just checking the cross browser compatibility of things while working on the FES, I did come to know that p5.js 1.0.0 does indeed does not work on IE 11. Version 0.9.0 seems to be the last version to work on IE 11. For all p5 versions after it, the initialization itself crashes.
![image](https://user-images.githubusercontent.com/38867671/84864813-e951aa80-b07f-11ea-934a-5e81cf556c39.png)

The stacktrace of the error is 
```
ReferenceError: 'Symbol' is undefined
at p5 (https://cdn.jsdelivr.net/npm/p5@1.0.0/lib/p5.js:62900:19)
at _globalInit (https://cdn.jsdelivr.net/npm/p5@1.0.0/lib/p5.js:62466:17)
at invokeCallback (https://cdn.jsdelivr.net/npm/p5@1.0.0/lib/p5.js:33807:21)
at publish (https://cdn.jsdelivr.net/npm/p5@1.0.0/lib/p5.js:33790:21)
at flush (https://cdn.jsdelivr.net/npm/p5@1.0.0/lib/p5.js:33506:19)
```

`Symbol` is [not supported](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol#Browser_compatibility) by Internet Explorer.
It happens inside the p5() constructor. The error is caught in a try-catch block so it can't be seen on the console but can be seen using a debugger, but it prevents the constructor from calling setup().
The error happens on a line that that is not present in the source but in the final built version, probably added by Babel.

**Comment by limzykenneth** [comment]
I don't know enough about babel to know why this is happening. @outofambit Can you have a look at this?

**Comment by outofambit** [comment]
@limzykenneth yes, i can take a look at this! there's probably a small config tweak i need to make to babel. thanks for investigating this @akshay-99!

**Comment by stevenraysimon** [comment]
Yes, so here are some screenshots of what is happening for me in IE 11
![uspecified-error](https://user-images.githubusercontent.com/10055349/90690211-eb2e1a80-e236-11ea-9ddf-15909140fa7f.jpg)
