### ISSUE TITLE
How to use ‘loadImage’ load base64 Image

### ISSUE THREAD

**Issue by SlowFeather** [processing/p5.js#4591]
I got some Base64 images from the server. How to display them in p5js
I only found a way to get it directly from the server, **not** from the base64 transcoding
```
function setup() {
  // here we use a callback to display the image after loading
  loadImage('assets/laDefense.jpg', img => {
    image(img, 0, 0);
  });
}
```
Please tell me thank you

**Comment by ffd8** [comment]
@SlowFeather where you'd give it the path of an image, you can feed it a valid base64 string - just have to be sure that it's a complete string:

```
let img;

function preload(){
	img = loadImage('data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==');
}

function setup() {
	createCanvas(windowWidth, windowHeight);
	image(img, width/2, height/2);
}

```
You should see a small red dot as the image. Adjust the `data:image/png` as necessary if another filetype, ie jpeg.

**Comment by lmccart** [comment]
thanks @ffd8! @SlowFeather for more code help, you can check out our forum: https://discourse.processing.org/
