### ISSUE TITLE
Explanation of parameters for curveTangent invalid

### ISSUE THREAD

**Issue by JimBrink** [processing/p5.js#4593]
I believe the values of parameters a, b, c, and d are reversed.  a and d are for control points while b and c are for points on the curve.
https://p5js.org/reference/#/p5/curveTangent

**Comment by micuat** [comment]
thanks for this. I just moved the issue to p5.js-website. closing

**Comment by limzykenneth** [comment]
@micuat Thanks for working on this. It's a bit confusing but changes to the reference should be made in this repo in the inline documentation. The `data.json` file over on the website repo is replaced every time a new version is released with oen generated from the inline documentation here. The lines you need to change is [here](https://github.com/processing/p5.js/blob/1.0.0/src/core/shape/curves.js#L506-L509).

I'll reopen and assign the issue to you. I'll close the issue and PR over on the website repo as well. Let me know if you need any help.

**Comment by lmccart** [comment]
thanks @micuat! i'm incorporating your changes into the p5.js codebase
