### ISSUE TITLE
cursor() bug in Reference

### ISSUE THREAD

**Issue by Qyd0ro** [processing/p5.js#4597]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] Dom
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

Sorry if I'm doing this wrong, I'm not entirely sure how to signal this properly.

Just wanted to note that code **line 187** in p5.js\src\core\environment.js references this [GitHub URL](https://avatars0.githubusercontent.com/u/1617169?s=16), which seems to point to a Processing logo, but the Reference page in the browser still points to this old [amazon URL](https://s3.amazonaws.com/mupublicdata/cursor.cur), which is broken.

**Comment by akshay-99** [comment]
Hi @Qyd0ro, the change in `core/environment.js` at line 187 was done pretty recently ( 27 days ago ) as seen [here](https://github.com/processing/p5.js/blame/master/src/core/environment.js#L187). I don't exactly know how the reference on the main website is updated or how often it is, but I don't think the changes from the code here reflect there immediately.
Thanks for pointing it out though :smile:

**Comment by Qyd0ro** [comment]
No problem, the Reference's bug form redirected me here so I thought this was the place

**Comment by lmccart** [comment]
thanks! i'm going to close this since it has been resolved already. reference will be updated with the next release.
