### ISSUE TITLE
shaders (later!)

### ISSUE THREAD

**Issue by lmccart** [processing/p5.js#46]
#### _Shaders_
- _loadShader()_
- _PShader_
- _resetShader()_
- _shader()_

**Comment by AnastasiaDunbar** [comment]
Have shaders been implemented yet?

**Comment by AkashGutha** [comment]
@AnastasiaDunbar @lmccart is this being implemented or in the backlog or has been removed from plans?

**Comment by AkashGutha** [comment]
@lmccart where is the branch if we want to contribute?

**Comment by limzykenneth** [comment]
@AkashGutha I believe it's this PR: #1568
