### ISSUE TITLE
Move canvas in DOM

### ISSUE THREAD

**Issue by Siggi005** [processing/p5.js#4601]
#### Most appropriate sub-area of p5.js?

- [ ] Core/Environment/Rendering
- [x] Dom
- [ ] Utilities
- [ ] Other (specify if possible)

#### New feature details:

The idea is to provide a function which allows moving the canvas in the DOM. I know that this is an easy to write function, but I think it would be helpful anyway for those who are not able to do it.
Here is a code suggestion:

```Javascript
function moveCanvas(destination) {
  if(destination == undefined) {
    return; //error message
  }
  if(destination == null) {
    return; //error message
  }
  let canvas = document.getElementByTagName("canvas");
  if(destination instanceof p5.Element) {
    canvas.parent(destination);
  }
  else {
    canvas.remove();
    destination.appendChild(canvas);
  }
}
```

**Comment by lmccart** [comment]
I think this is a relatively specific use case, and if someone is at the point of being able to move DOM elements around, they could probably write this code themselves. In general, we've been adopting a "only add new features that increase access" mission, so I'd also question whether this meets that criteria.

**Comment by micuat** [comment]
I agree with @lmccart - but maybe it's useful to create a doc for those who want to make p5 extensions, or is there anything like that? It may be helpful to have this kind of functions as DOM utils as a separate project.

Given that - I think the suggested code is not tested yet, right? It has a few problems like `canvas` is not `p5.Element` so doesn't have functions like `parent` in the snippet. Also it needs a condition when multiple canvases exist (and of course support for instance mode).

**Comment by lmccart** [comment]
we do have this page if you think it belongs here:
https://github.com/processing/p5.js/blob/master/contributor_docs/creating_libraries.md

**Comment by Siggi005** [comment]
> Given that - I think the suggested code is not tested yet, right?

You are absolutely right, it was more like quick hacked stuff to show what I mean.

> we do have this page if you think it belongs here

Maybe this is a solution, I will think about it.
After all, thank you very much for your responses! It is nice to see such a welcoming community.

**Comment by micuat** [comment]
@Siggi005 let me know if I can help anything. would be nice to see the update from you!

**Comment by Siggi005** [comment]
I already see that you are a way better programmer than me, so thank you very much!
