### ISSUE TITLE
Editor: full screen sharing stopped working

### ISSUE THREAD

**Issue by maartenwijntjes** [processing/p5.js#4605]
It is perhaps not the right time to submit a bug, so my excuses if that is the case. 

The full screen function stopped working. For example, the p5 drawing example: 

https://editor.p5js.org/p5/sketches/ArMiCc9-Mq
https://editor.p5js.org/p5/full/ArMiCc9-Mq
https://editor.p5js.org/p5/present/ArMiCc9-Mq

The 'full' does not work.

Oops, I suddenly realize I should perhaps submit this to the p5 editor issue thread?

Thanks anyway!
Maarten

**Comment by maartenwijntjes** [comment]
I noticed it was already reported in the p5 web editor thread: https://github.com/processing/p5.js-web-editor/issues/1445

**Comment by lmccart** [comment]
im going to close this since it is tracked in the issue mentioned above on the editor repo
