### ISSUE TITLE
document: no new features except those that increase access

### ISSUE THREAD

**Issue by lmccart** [processing/p5.js#4611]
At our most recent [contributors conference](https://p5js.org/community/contributors-conference-2019.html), we made a commitment to not add any new features *except* those that increase access (meaning, inclusion and/or accessibility). This was intended not to shut down contributions, but to open up more conversations about what access means, and how we can continue to prioritize it. It would be great to get a write up / explanation of this in this repo so we can understand and apply it more easily. I think @outofambit wrote some text around this already we could start with. The doc could live in the `contributor_docs` section.

**Comment by outofambit** [comment]
@lmccart yes! ive had documenting this better in the back of my head for a while. i can take on cleaning up my notes and fleshing them out more for review/feedback from everyone!

**Comment by lmccart** [comment]
Great thank you @outofambit! Let's also link to this from our CONTRIBUTING.md file so it's easily found.

**Comment by lmccart** [comment]
@outofambit not trying to rush you, but just wanted to offer... if it's helpful for a few of us to get in a sync doc situation and hash it out i'm happy to help

**Comment by outofambit** [comment]
@lmccart that would be great, thank you! 🙏🏼 what did you have in mind?
(i started a draft [here](https://github.com/outofambit/p5.js/blob/access-focus-statement/contributor_docs/access.md) but i'm not sure if the tone is right.)

**Comment by lmccart** [comment]
@outofambit I'm up for anything. what have you drafted looks great! happy to get on a call or live chat to workshop this further. I can also just leave comments on a PR or doc if that's easier.

**Comment by outofambit** [comment]
@lmccart thanks! since it doesn't seem way off, i opened a PR #4676 and i would love your and @lm-n 's feedback, thoughts, and revisions!
