### ISSUE TITLE
README.md for p5.js Core includes invalid file reference

### ISSUE THREAD

**Issue by chen-ni** [processing/p5.js#4614]
In [/src/core/README.md](../blob/master/src/core/README.md), there is a reference at line 26 to a file called "error_helpers.js" in the same directory. However, that file doesn't exist.

**Comment by akshay-99** [comment]
Hi @chen-ni. Thanks for spotting this! `error_helpers.js` used to be a file which for broken up as it was getting too big. I seem to have missed updating the non-code files that reference it :sweat_smile:

**Comment by chen-ni** [comment]
Hi @akshay-99, thanks for the reply! In that case, would it be ok for me to create a PR that simply removes that paragraph for "error_helpers.js" to resolve this issue?
