### ISSUE TITLE
P5.Sound bug

### ISSUE THREAD

**Issue by plasmusss** [processing/p5.js#4615]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Dom
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other (specify if possible) : Sound

#### Details about the bug: I tried to use loadSound() after paste in the head of the index.html the script written on the reference (<script src="path/to/p5.sound.js"></script>) but it doesn't work, then I searched on Internet the script, and he gave me a page where there was 2 script (<script language="javascript" src="libraries/p5.dom.js"></script> and <script language="javascript" src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.5.8/addons/p5.sound.js"></script>), the 1st was completely operative, but the 2nd when I put it it says me that there was an error in the sketch line : 857, I searched the link, I went to line 857 and there wasn't any problem, so I think that is a bug,
I hope that you will read this

- p5.js version:  5.6
- Web browser and version: Microsoft Edge v. 81.0.416.58
- Operating System: Windows 10
- Steps to reproduce this:

**Comment by micuat** [comment]
Hi @plasmusss , the problem might not be a bug but the way how you included the sound library. If you're not familiar with JavaScript, I suggest you to check out the web editor. It is already equipped with p5.js and p5.Sound.
https://editor.p5js.org/

Also if you have questions that are not clear if it is a bug or you're code, you can also post them on discourse to ask for help :)
https://discourse.processing.org/
