### ISSUE TITLE
A moderate logging system

### ISSUE THREAD

**Issue by peilingjiang** [processing/p5.js#4617]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] Dom
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### New feature details:

As the `draw()` function runs unstoppably for many times a second, when we want to log out the value of a variable, it usually results in massive messages in console and weakened performance. I worked on a moderate logging system that will only log the value in console 1. when the value of the particular variable changes, or 2. periodically with the period preset. I hope this feature will be helpful for people to spot useful information in the console and help lift the performance of the code during the debugging process.

**Comment by lmccart** [comment]
I'm not seeing a lot of interest in this feature, and we don't have a clear explanation of how it [expands access](https://github.com/processing/p5.js/blob/main/contributor_docs/access.md), so I will close this for now. If an access statement can be added to the issue request, please feel welcome to reopen.
