### ISSUE TITLE
Computation bug of big integer numbers

### ISSUE THREAD

**Issue by jbroux** [processing/p5.js#4620]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Dom
- [ ] Events
- [ ] Image
- [ ] IO
- [x] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version: p5.js v0.10.2 October 14, 2019
- Web browser and version: Safari 13.1.1 & Google Chrome 83.0.4103.97
- Operating System: Mac OS Catalina 10.15.5
- Steps to reproduce this:

let p = 3*4136426146664351;
console.log(p); // -> 12409278439993052 but the right answer is: 12409278439993053

**Comment by DivyamAhuja** [comment]
Actually this has nothing to do with p5, It's just how JavaScript primitively represents Numbers
The Maximum safe Integer you can use in JavaScript `2^53 - 1`.
You can use BigInt Object in JS for computation of large integers.
eg. `BigInt(3)*BigInt(4136426146664351)`

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt

**Comment by montoyamoraga** [comment]
thank you @DivyamAhuja for your explanation,
hope this was helpful @jbroux 
i am closing this issue, best!

**Comment by jbroux** [comment]
Thank you for your answer. Sorry for disturbing you. I have made a lot of Web research for the keyword 'maxint' before writing the mail.

I will remember ‘BigInt' which would be useful for the Collatz conjecture.

JBR
