### ISSUE TITLE
I can't upload XML locally or in the web editor

### ISSUE THREAD

**Issue by InventorPanda** [processing/p5.js#4621]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Dom
- [ ] Events
- [ ] Image
- [x] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version: 0.10.2
- Web browser and version: Chromium 78.0.3904.108 (Official Build) Built on Raspbian , running on Raspbian 10 (32-bit)
- Steps to reproduce this:
It won't let me upload an XML file, saying it's not allowed, and it won't load the file locally, either. I tried downloading the library file instead of using the cloudflare link, but same thing

**Comment by DivyamAhuja** [comment]
Locally I think it's maybe due to CORS security, can you provide web editor link where it's not working?

**Comment by InventorPanda** [comment]
> e

How do I do that? I'm not very familiar with the editor, mainly the library itself

**Comment by InventorPanda** [comment]
> Locally I think it's maybe due to CORS security, can you provide web editor link where it's not working?

How do I do that? I'm not very familiar with the editor, mainly the library itself.

**Comment by InventorPanda** [comment]
https://editor.p5js.org/george.sandrowicz/sketches/LOZ0RD5Ta

**Comment by DivyamAhuja** [comment]
https://p5js.org/reference/#/p5/loadXML

You have to provide path to xml in loadXML()

which in this case will be 'xml/text.txt'

loadXML('xml/text.txt')

**Comment by lmccart** [comment]
thanks @DivyamAhuja! @InventorPanda for more help, please check out our [forum](https://discourse.processing.org/)
