### ISSUE TITLE
CREATING AN IMAGE IN P5JS

### ISSUE THREAD

**Issue by ARNAVVGUPTAA** [processing/p5.js#4632]
i want to draw something and make it an image, can I do that??? I believe its something with createImage but can't follow it properly, please help me with it

**Comment by montoyamoraga** [comment]
hi @ARNAVVGUPTAA, our issues are intended for reporting bugs and problems with p5.js,
for doubts about coding please use our forum at https://discourse.processing.org/ and the community will help you, i suggest sharing on that forum the code you have written so far, or the reference/example you are having trouble following :)

i will close this issue now, best!
