### ISSUE TITLE
Reference for rect and "optional" h parameter

### ISSUE THREAD

**Issue by JimBrink** [processing/p5.js#4633]
#### Most appropriate sub-area of p5.js?

- [ x] Core/Environment/Rendering

- [ ] Other (specify if possible)

#### Details about the bug:
The reference page for rect (https://p5js.org/reference/#/p5/rect) states  in the
line for syntax and the specification of the forth parameter, h, that it is optional.  But the description doesn't say what is supposed to happen if h is omitted. In practice, it appears that if h is omitted, nothing is drawn.   Interestingly, if h is set to 0 as in the 3rd (yellow) rectangle, the border is drawn.
- Operating System: Windows 10
- p5.min.js version: February 29, 2020
<pre>
    function setup() {
      createCanvas(100, 100);
      background(210);
      stroke("green");
      fill("blue");
      rect(10, 10, 20);
      fill("red");
      rect(50, 10, 20, 20);
      fill("yellow");
      rect(10, 50, 20, 0);
   }
</pre>
When the code is executed, the blue rectangle is not shown.
The example can be run at http://brinkje.com/p5js/rect.html

**Comment by DivyamAhuja** [comment]
Actually this is happening because you are using p5 version 0.10.2 maybe . This bug is resolved in p5 version 1.0.0 in which 3 arguments can be passed into rect()

https://p5js.org/reference/#/p5/rect

on web editor if you want to use v1.0.0 you can edit index.html file
