### ISSUE TITLE
loadImage() bug

### ISSUE THREAD

**Issue by Louis469** [processing/p5.js#4634]
I have found a bug that does not load the image.
In the console it says: "Fetch API cannot load 

file:///home/<USER>/Code/ml5/Image%20classifier/cat.png. URL scheme must be "http" or "https" for CORS request."

Please Help.
My code is in the attachments.
[Image classifier.zip](https://github.com/processing/p5.js/files/4775596/Image.classifier.zip)
:)

**Comment by Louis469** [comment]
It is p5 1.0.0

**Comment by limzykenneth** [comment]
The error message basically means that you should load the file over http or https instead of file (ie `http://....` or `https://...` instead of `file://...`). To do that you will probably need to run a local server. To do that you should start [here](https://github.com/processing/p5.js/wiki/Local-server). 

An easier way is to use the [web editor](https://editor.p5js.org) which will take care of these things for you.

**Comment by sepulm01** [comment]
Hi, I had the very same problem: I try to load image form https://storage.googleapis.com  like that:
bg = loadImage('https://storage.googleapis.com/file2net-a30e6/fotos/e647b44c54258d89.jpg?X-Goog-Algorithm=GOOG4-RSA-SHA256&amp;X-Goog-Credential=labelflow%40file2net-a....
and the answer is:
Access to fetch at 'https://storage.googleapis.com/file2net-a30e6/fotos/e647b44c54258d89.jpg?X-Goog-Algorithm=GOOG4-RSA-SHA256&amp;X-Goog-Credential=labelflow%40file2net-a30e6.iam.gserviceaccount.com%2F20211227%2Fauto%2Fstorage%2Fgoog4_request&amp;X-Goog-Date=20211227T135222Z&amp;X-Goog-Expires=86400&amp;X-Goog-SignedHeaders=host&amp;X-Goog-Signature=70150e8cb7eef01f28f0c07fac28657d0c8fae282c73409534efa090c66389221181b3844b0b5783288af1a36f255ed68d1bfd03529be990b9c4321a351a6c3bfad46354f994c21e64a1126176c20caf69b39462d0ec8186648520420b0156f4be17afe992e7a78b659f50e34f6e735604813964f594e38ccce7b3d0a226fd20fc8f80ea17a7ab3c617423ecb340ef9bcbfe9d0817b51276c52d586a99a63977149b2b10fd5c9c85e04203bbcf112140352e209fba75dc2244a5a8c395c45d993c7a85abb3e6a4ff9516e9f0dd66be8b3a6308b5c0e0fb512c52df2d27545d490c049901f4b61cf88f6984c055d6df6bde4b4d300f4f8a2d425c71506a36f309' from origin 'http://127.0.0.1:8000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled. 
Could you help us?
Best reagrs.

**Comment by montoyamoraga** [comment]
hi @sepulm01 for questions about code please review our forum :)
https://discourse.processing.org/
