### ISSUE TITLE
update GitHub issue templates

### ISSUE THREAD

**Issue by montoyamoraga** [processing/p5.js#4635]
we get a lot of issues that are labeled as bugs, and instead they are doubts with code,
and then we have to close them and point them to the forum.

also i think we are not doing new features for a while, right?

right now we have 4 templates:
* Existing Feature Enhancement
* Feature request
* Found a bug
* Need Help with Code

These are two changes i would do:

1. delete "Feature Request", or change the text with a disclaimer to say we will not be working on them for a while.

2. delete "Need Help with Code", and change the text of "Found a Bug" from
"This issue template is for reporting a bug which is broken or incorrect behaviour."
to 
"For reporting bugs (broken or incorrect behaviour). For questions about your code, please visit our forum discourse.processing.org instead of opening an issue."

**Comment by stalgiag** [comment]
Sounds good to me!

I will say that I don't think there is anything that will catch all of the doubts with code or misunderstandings of the purpose of the Github but definitely down to try out a new configuration of templates to see if it is more successful at filtering these out.

**Comment by lmccart** [comment]
thanks @montoyamoraga! 
* I think we should keep the "feature request", but as you suggest, add our intention to only add new features that increase access. we can link to the writeup @outofambit is working on.
* we could also add this link in the "existing feature enhancement" template. the difference between a feature enhancement and feature request is a little blurry to me...
* agree with delete "need help with code"

**Comment by outofambit** [comment]
what do y’all think about adding a question to the feature request template too? something like:

“How would this help increase access to p5.js?”

to prompt people to think about it if they haven’t and to give them a chance to share how/if it would in their view?

**Comment by limzykenneth** [comment]
@outofambit I was just thinking about adding that instead of removing feature requests altogether, so definitely +1 from me.

**Comment by lmccart** [comment]
@montoyamoraga do you want to make these changes or is this issue up for grabs?

**Comment by montoyamoraga** [comment]
@lmccart i will work on it this weekend :)
