### ISSUE TITLE
keyIsPressed remains stuck when Alt-Tabbing

### ISSUE THREAD

**Issue by avelican** [processing/p5.js#4636]
#### Most appropriate sub-area of p5.js?

- [x] Events

#### Details about the bug:

- p5.js version: 1.0.0
- Steps to reproduce this: Alt-Tab away from p5, then back again.

When I Alt-Tab away from the browser and back again, keyIsPressed remains stuck as true until I press and release any key (until the keyup event is triggered).

The browser can not detect a key-up while focus is lost.
However, the fact of losing focus itself triggers the onblur event.
So I use this workaround:

```
window.onblur = function() {
  keyIsPressed = false;
}
```

Hope this helps!
Andy

**Comment by limzykenneth** [comment]
That's the browser's default behaviour and I wouldn't recommend including the workaround in p5.js itself. You can definitely use the workaround in your own code to get around this problem.
