### ISSUE TITLE
not able to upload p5.js in github. all other files i am able to upload.. its says we cannot process that file

### ISSUE THREAD

**Issue by vinodhinisenthil7** [processing/p5.js#4638]
#### Nature of issue?

- Found a bug
- Existing feature enhancement
- New feature request

#### Details about the bug: 

- Web browser and version: 
- Operating System: 
- Steps to reproduce this bug:

#### New feature details:

**Comment by limzykenneth** [comment]
@vinodhinisenthil7 I'm not sure I understand the issue. Can you fill out the issue template so that we can diagnose what issue you have?

**Comment by lmccart** [comment]
I'm going to close this for organizational purposes. Please open another issue if you can add more info for us to help. You can also check out our forum for more code help: https://discourse.processing.org/
