### ISSUE TITLE
Chrome 83 makes extreme changes to some HTML widgets in p5.DOM

### ISSUE THREAD

**Issue by grege2** [processing/p5.js#4640]
#### Most appropriate sub-area of p5.js?
- [X ] Dom
p5.js 1.0.0
Chrome 81 and 83

Hi folks,

This is not a p5.js or p5.DOM bug as such, but it's quite a problem for someone extensively using the DOM toolkit in p5, so I thought I'd post it here.

I uprevved my Mac Chrome browser from 81.xxx to 83.xxx and a lot of my HTML widgets in a p5.js sketch broke. Well, substantially changed their appearance, and font sizes. And in the case of the Color Picker, just plain broke - the five options (RGB sliders, colour wheel, fixed palette etc) were replaced by just one “colour field” picker, with no eye-dropper colour sampler, and I think not even a hex colour option (I forget if that last one is exactly true).

So after much searching, I found this is deliberate ! Chrome and Edge have got together and “harmonised” their widgets, and “improved” them. I can tell you from my own experience that if Microsoft offers to help you “improve” something, be very, very, very afraid.

Details:

https://blog.chromium.org/2020/03/updates-to-form-controls-and-focus.html

https://www.youtube.com/watch?v=ZFvPLrKZywA

Anyway, there is a solution. You can force Chrome back to the old style …
Put this in your Chrome address bar …

chrome://flags/#form-controls-refresh

It brings up a bunch of internal options … set the Web Platform Controls updated UI ie. the one you land on, to Disabled. Have to then restart browser. Then you’re back to Chrome 81 behaviour.

I don’t know how long that escape route will last. I wonder whether p5.js can bring any pressure to bear to keep it available.

Ciao, GE.

PS. I've posted this on the p5.js forum too.

**Comment by limzykenneth** [comment]
Design decisions by the browser makers are not something within our control. You should raise this issue with the Chromium project instead.

**Comment by grege2** [comment]
Ok. I don't know much weight I'll have vs. Google and Microsoft ! But anyway there's the temporary solution if anyone has code that really depends on the old appearance and behaviour.
