### ISSUE TITLE
DOM examples not executed in the reference

### ISSUE THREAD

**Issue by lm-n** [processing/p5.js#4645]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [x] Dom
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Feature enhancement details:
Currently, several DOM examples are not executed in the reference. It is always helpful to have the example code executed so that novice programmers can get a clear idea of how the code works. For some examples, making them work and look good might require small changes to the code, especially when canvas size is greater than 100x100 and when DOM functions add HTML elements that take a lot of space (i.e.: go beyond 100x100 px). 

Here's a list of the examples that could be executed: 

- [ ] [removeElements()](https://p5js.org/reference/#/p5/removeElements)
- [ ] [selectAll()](https://p5js.org/reference/#/p5/selectAll)
- [ ] [ input()](https://p5js.org/reference/#/p5/input)
- [ ] [createDiv()](https://p5js.org/reference/#/p5/createDiv)
- [ ] [createP()](https://p5js.org/reference/#/p5/createP)
- [ ] [createImg()](https://p5js.org/reference/#/p5/createImg)
- [ ] [createA()](https://p5js.org/reference/#/p5/createA)
- [ ] [createButton()](https://p5js.org/reference/#/p5/createButton)
- [ ] [createCheckbox](https://p5js.org/reference/#/p5/createCheckbox)
- [ ] [createInput](https://p5js.org/reference/#/p5/createInput)
- [ ] [createInput](https://p5js.org/reference/#/p5/createInput)
- [ ] [createCapture()](https://p5js.org/reference/#/p5/createCapture)
- [ ] [createElement()](https://p5js.org/reference/#/p5/createElement)
- [ ] [createSpan()](https://p5js.org/reference/#/p5/createSpan)

**Comment by 1lias** [comment]
Hi 👋 For this issue I would need to edit the code here - [p5.js-website](https://github.com/processing/p5.js-website) - correct?

**Comment by lm-n** [comment]
Hi @1lias! I hope you and your loved ones are safe and healthy! The reference is generated in the p5.js repo you can learn more in the [inline documentation](https://github.com/processing/p5.js/blob/main/contributor_docs/inline_documentation.md) section of the contributor docs. The code for all the DOM examples in the reference mentioned above is in [p5.js/src/dom/dom.js](https://github.com/processing/p5.js/blob/main/src/dom/dom.js).
Hope this helps!

**Comment by limzykenneth** [comment]
The reference examples for `dom` (or any reference example) won't render if in the `<div>` tag that contains the example code has the class `norender`. To get them to run, just remove that class.

**Comment by lm-n** [comment]
I think it will also require re-thinking some of the examples so that they look good once rendered on the site.

**Comment by 1lias** [comment]
> Hi @1lias! I hope you and your loved ones are safe and healthy! The reference is generated in the p5.js repo you can learn more in the [inline documentation](https://github.com/processing/p5.js/blob/main/contributor_docs/inline_documentation.md) section of the contributor docs. The code for all the DOM examples in the reference mentioned above is in [p5.js/src/dom/dom.js](https://github.com/processing/p5.js/blob/main/src/dom/dom.js).
> Hope this helps!

Thankfully we are all safe and sound @lm-n 🙏 I hope you find yourself in a similar position. I understand a bit better now what needs to be done. In my understanding some parts of the documentation have examples and some do not have. I should try to create some examples for the ones without them. Is there any way I can see the results on my local machine?

**Comment by limzykenneth** [comment]
To view the reference you can run `grunt yui:dev` which will spin up a server that serves a pared down version of the final reference. It isn't very usable at the moment though. I have a PR filed yesterday that fixes it #4649, you can use that or wait for it to be merged.

**Comment by pedrotpo** [comment]
Hello! Wanted to see if I could tackle some of the examples (except for the ones @1lias might be currently working on, of course). Are there any examples up for grabs?

**Comment by limzykenneth** [comment]
@pedrotpo As far as I know, there isn't any of them that are being worked on. If you like, leave a comment here with a shortlist of examples you are working on then we can track who is working on what. Thanks!

**Comment by Aloneduckling** [comment]
Hello! I am working on this issue.
I have already worked on the code (removed norender class from the required divs). The examples are now executing. But when I preview the website locally there seems to be some problem with the CSS. I have not changed any code exept the one mentioned. 
![dispProblem](https://user-images.githubusercontent.com/54030684/93668067-d815a100-faa7-11ea-83dc-8ba213630449.png)
 
Is this Ok?

**Comment by limzykenneth** [comment]
I'm doing some work on the CSS at the moment as things are not looking right on the website. Maybe you will need to wait until that is done, I'm estimating a couple days to finish.

**Comment by Aloneduckling** [comment]
Ok! I will wait then.

**Comment by limzykenneth** [comment]
@Aloneduckling The changes are merged now so you can start with this if you like.

**Comment by Aloneduckling** [comment]
Ok thanks!

**Comment by Aloneduckling** [comment]
hello! I have created a pull request. Please check it.
Thanks, 
Aloneduckling

**Comment by Aloneduckling** [comment]
Just asking, should I add my name to the contribution list?

**Comment by ritik307** [comment]
hi there, I am kinda confused on what kind of executable examples should i make.

**Comment by limzykenneth** [comment]
@ritik307 This issue is already being addressed, if you are interested in contributing do have a look at other open issues. Thanks.

**Comment by ritik307** [comment]
Ok...will find some other issues.
