### ISSUE TITLE
erase()

### ISSUE THREAD

**Issue by Hickory-Kay** [processing/p5.js#4646]
In the reference for erase() it says that it will not erase any background() drawings, but it is erasing my background. Any help or suggestions are appreciated

**Comment by limzykenneth** [comment]
In the reference it says that

> Drawing done with image() and background() will not be affected by erase()

What this means is that using `image()` or `background()` in between `erase()` and `noErase()` will not make them an erasing mask, they will draw the image or background as usual. `background()` will be erased as `erase()` will remove any pixels, revealing the underlying HTML behind the canvas.

Perhaps the documentation needs to be clarified a bit regarding this.

**Comment by stalgiag** [comment]
Perhaps this:
> Drawing done with image() and background() will not be affected by erase()
can be changed to this:
> Drawing done with image() and background() will not erase.
?

**Comment by limzykenneth** [comment]
@stalgiag That still feels can be potentially misunderstood. Maybe expand a bit with

> Drawing done with image() and background() in between erase() and noErase() will not erase the canvas but works as usual.

**Comment by stalgiag** [comment]
Sounds good to me @limzykenneth ! @Hickory-Kay any interest in contributing an update to the documentation?
