### ISSUE TITLE
p5 sound not working in android 4.1.1

### ISSUE THREAD

**Issue by karneaud** [processing/p5.js#465]
Hello,

Im trying to preview your example at http://p5js.org/learn/examples/Sound__Amplitude_Analysis.php

In my Android 4 chrome browser and it doesn't work. What is the minimum version support for Android?

**Comment by Rousan99** [comment]
https://editor.p5js.org/K.A.Rousan/full/pjZLu-5m6
No.. it's not working..like this...this one is not working in android chrome.. the mouse click fuction is used..it is working just fine in pc but not on Android
