### ISSUE TITLE
Fract() not defined

### ISSUE THREAD

**Issue by Doynik** [processing/p5.js#4653]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Dom
- [ ] Events
- [ ] Image
- [ ] IO
- [x] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version: 0.10.2
- Web browser and version: Chrome 64-bit 83.0.4103.106
- Operating System: Windows 10
- Steps to reproduce this: Simply using the example code in the p5.js documentation for fract() produces an error that fract() is not defined.

![image](https://user-images.githubusercontent.com/67315101/85385237-f6681100-b539-11ea-8f0f-a99e389726bf.png)

**Comment by DivyamAhuja** [comment]
I guess this is happening because fract function is not defined in p5 v0.10.2 but in v1.0.0 . It works fine in version 1.0.0

**Comment by Doynik** [comment]
That... would make a lot of sense. Dunno how I missed that, derp. Thanks!
