### ISSUE TITLE
QUAD_STRIP WEBGL

### ISSUE THREAD

**Issue by thiagohersan** [processing/p5.js#4655]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Dom
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version: 1.0.0/p5.min.js
- Web browser and version: chrome 83.0.4103.116 (Official Build) (64-bit)
- Operating System: MacOSX
- Steps to reproduce this:

copy-paste QUAD_STRIP code from the vertex() reference into a WEBGL sketch:

```
function setup() {
  createCanvas(400, 400,WEBGL);
}

function draw() {
  background(220);
  beginShape(QUAD_STRIP);
  vertex(30, 20);
  vertex(30, 75);
  vertex(50, 20);
  vertex(50, 75);
  vertex(65, 20);
  vertex(65, 75);
  vertex(85, 20);
  vertex(85, 75);
  endShape();
}
```

Expected:
<img width="135" alt="Screen Shot 2020-06-23 at 5 12 25 PM" src="https://user-images.githubusercontent.com/850815/85455840-ba9e6d00-b574-11ea-835f-83930878636a.png">

Got:
<img width="298" alt="Screen Shot 2020-06-23 at 5 12 19 PM" src="https://user-images.githubusercontent.com/850815/85455863-bf632100-b574-11ea-8cb1-e99a4c17109f.png">

Not sure if bug, un-implemented feature, or my misunderstanding of how QUAD_STRIP should work in 3D.

Thanks

**Comment by aferriss** [comment]
Hi @thiagohersan I believe that QUAD_STRIP has yet to be implemented in webGL mode. If you open up the console, you should see a message about it's implementation status. 

https://editor.p5js.org/aferriss/sketches/UdHnqJ_vf

Maybe not ideal, but if you convert to `TRIANGLE_STRIP` instead that should work.

**Comment by thiagohersan** [comment]
aha !
thanks @aferriss !

I see the error on editor.p5js.org now, but didn't see anything on my console.
But... Cool.

I'll try ```TRIANGLE_STRIP```, or just straight up square-ish shapes with 4 vertices.
