### ISSUE TITLE
fract() no longer work

### ISSUE THREAD

**Issue by Sidchou** [processing/p5.js#4659]
#### Most appropriate sub-area of p5.js?

- [x ] Math

#### Details about the bug:

- p5.js version: 0.10.2
- Web browser and version: chrome 83.0.4103.106 (Official Build) (64-bit)
- Operating System: macOS Version 10.14.4
- Steps to reproduce this:   
`console.log(fract(1.2))`
error
`Uncaught ReferenceError: fract is not defined (sketch: line 3)`

also, the reference page of fract() looked messed up : [https://p5js.org/reference/#/p5/fract](https://p5js.org/reference/#/p5/fract)

**Comment by DivyamAhuja** [comment]
Same as #4653 .
You should use p5 v1.0.0 as I think feact is not defined in version 0.10.2

**Comment by DivyamAhuja** [comment]
@stalgiag I think there should be a development mode with library management on p5 web editor which can provide easy access to switching versions of p5 and also have option for latest build generated once per day or every time a pull request gets merged.

https://github.com/processing/p5.js-web-editor/issues/1396#issuecomment-644929088

**Comment by lmccart** [comment]
thanks @DivyamAhuja! yes I agree this would be a great feature. it looks like it's already being tracked in the web editor repo, so I'll close this thread for now.
