### ISSUE TITLE
Inconsistent behavior for arc

### ISSUE THREAD

**Issue by ziyaointl** [processing/p5.js#4664]
When start angle and end angle are both 2*PI, arc in PIE mode draws a small dot but all other modes do not. To keep the behavior consistent, maybe none of the modes should draw anything when the delta is 0?

<img width="419" alt="Screen Shot 2020-06-30 at 6 34 16 PM" src="https://user-images.githubusercontent.com/18119047/86198347-4c295400-bb0c-11ea-865e-2fd6f41fc81a.png">

(Scroll down for code)

#### Most appropriate sub-area of p5.js?
- [ ] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] Dom
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version: v0.10.2
- Web browser and version: Google Chrome | 83.0.4103.116 (Official Build) (64-bit)
- Operating System: MacOS 10.15.5
- Steps to reproduce this:
```javascript
function setup() {
  createCanvas(400, 400);
}

function draw() {
  var offset = 0;
  for (var x = 0; x < PI * 2; x += QUARTER_PI) {
     arc(50.0 + offset, 50.0, 50.0, 50.0, x, 2*PI);
     arc(50.0 + offset, 100, 50, 50, x, 2*PI, OPEN);
     arc(50.0 + offset, 150, 50, 50, x, 2*PI, CHORD);
     arc(50.0 + offset, 200, 50, 50, x, 2*PI, PIE);
     offset += 50;
  }
}
```

**Comment by ziyaointl** [comment]
Thanks to @dzaima, I realized that in my orginal snippet the start angle and end angle are acutally not the same. When I manually set them to a fixed value, I get a full circle instead of nothing:

```javascript
function setup() {
  createCanvas(400, 400);
}

function draw() {
  arc(50.0, 50.0, 50.0, 50.0, 2*PI, 2 * PI);
  arc(50.0, 100, 50, 50, 0, 0, OPEN);
  arc(50.0, 150, 50, 50, 1, 1, CHORD);
  arc(50.0, 200, 50, 50, 2, 2, PIE);
}
```
<img width="460" alt="Screen Shot 2020-07-01 at 7 02 52 PM" src="https://user-images.githubusercontent.com/18119047/86308334-c7067380-bbcd-11ea-9ed5-34d69192cc98.png">

**Comment by jeremydouglass** [comment]
Does that mean this issue can be closed, or is there still something to resolve?

**Comment by ziyaointl** [comment]
@jeremydouglass I think the behavior is still inconsistent since I think if the start angle and end angle are the same we should expect nothing to be drawn instead of a full circle :)

**Comment by limzykenneth** [comment]
A check probably can be added at the [beginning of the `arc` function](https://github.com/processing/p5.js/blob/main/src/core/shape/2d_primitives.js#L172) or the [normalize angle function](https://github.com/processing/p5.js/blob/main/src/core/shape/2d_primitives.js#L38) to account for this.
