### ISSUE TITLE
@all-contributors please add @pcgamer1 for code

### ISSUE THREAD

**Issue by lmccart** [processing/p5.js#4665]
@all-contributors please add @pcgamer1 for code

**Comment by lmccart** [comment]
@pcgamer1 it looks like you're already listed in the [contributors section](https://github.com/processing/p5.js#contributors), so i'm going to close this. let us know if there was a change you wanted to make to your entry?

**Comment by pcgamer1** [comment]
@lmccart It's just that I am not seeing p5 as an organization on my profile, I think that is supposed to happen when I am added to the contributors. Can you clear this out for me.

**Comment by lmccart** [comment]
ah @pcgamer1 I see. adding to the contributors list just puts your name in the readme section. but I can add you to the p5.js team in the processing foundation org and it will show up. doing that now.

**Comment by pcgamer1** [comment]
@lmccart I get it now, thanks for the invite!
