### ISSUE TITLE
Execution Control.

### ISSUE THREAD

**Issue by nakul-shahdadpuri** [processing/p5.js#4666]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [x] Dom
- [x] Events
- [ ] Image
- [x] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### New feature details:
Is there a way to control the execution of a sketch. For example, A certain DOM element could start the execution of a sketch, while the other could "pause it"/"reset it". I have tried implementing the latter by playing around with frameRate() function, but somehow it didn't seem elegant enough.

**Comment by limzykenneth** [comment]
You can use `noLoop()` and `loop()` to start and stop the `draw()` function.

If you need further help with your own code, please direct your questions to the [forum](https://discourse.processing.org). We use GitHub issues mainly for bug reports and feature requests only. Thanks!
