### ISSUE TITLE
selectAll() warning message disagrees with documentation

### ISSUE THREAD

**Issue by Trumpet63-stream** [processing/p5.js#4671]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [x] Dom
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:
I passed a p5.Element to selectAll() as its second argument, which should work according to the reference doc, but I got the following message:

"p5.js says: selectAll() was expecting String for parameter #1 (zero-based index), received object instead at about:srcdoc:58:3. [http://p5js.org/reference/#p5/selectAll]"

- p5.js version: I'm using 1.0.0, but I reproduced it with the Web Editor as well
- Web browser and version: Google Chrome: 83.0.4103.116 (Official Build) (64-bit) (cohort: Stable)
- Operating System: Windows 10 OS Version 1909 (Build 18363.900)
- Steps to reproduce this:
```
function setup() {
  createCanvas(400, 400);
  myButton= createButton("Hello World");
  selectAll("abc", myButton);
}

function draw() {
  background(220);
}
```

**Comment by akshay-99** [comment]
Hi, this has been fixed in patch #4580. The changes will be reflected in the next release. In the current release I think only the message was incorrect. The `selectAll` function itself should work as expected. You can ignore this message for now.
