### ISSUE TITLE
Falsey radio option value is ignored

### ISSUE THREAD

**Issue by Trumpet63-stream** [processing/p5.js#4672]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [x] Dom
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:
Specifying a falsey value for the second argument of a radio element's .option() (e.g. 0, "", false) causes it to behave as if no value was specified at all.

- p5.js version: I'm using 1.0.0, but I reproduced it with the Web Editor as well
- Web browser and version: Google Chrome: 83.0.4103.116 (Official Build) (64-bit) (cohort: Stable)
- Operating System: Windows 10 OS Version 1909 (Build 18363.900)
- Steps to reproduce this:
```
function setup() {
  createCanvas(400, 400);
  radio = createRadio();
  radio.option('black', 0);
  radio.option('white', 1);
  radio.option('gray', 2);
}

function draw() {
  background(220);
  console.log(radio.value());
}
```

**Comment by limzykenneth** [comment]
This has been fixed by #4395 and will be available on the next release.
