### ISSUE TITLE
add documentation of npm install p5

### ISSUE THREAD

**Issue by X-method** [processing/p5.js#4674]
As a non-expert JS developer, I would appreciate clear documentation showcasing the integration of p5.js via `npm install p5` . There are literally 0 references to npm, albeit the "instance mode" being an indirect implementation of such use case. 

I will happily make a PR for documentation update once I get my actual work done.

**Comment by lmccart** [comment]
@X-method that would be great!

**Comment by montoyamoraga** [comment]
thank you so much @X-method, i tagged you as assignee for this :)

**Comment by limzykenneth** [comment]
It seems there are increasing interest in using p5.js from NPM, @X-method while working on this if there is specific ways we could improve the codebase to make it less problematic to use p5.js from NPM do let us know as well.

**Comment by X-method** [comment]
Hey everyone, I noticed the documentation updates will only affect the `p5js-website` repo, so I'll close this issue and make a PR there.
