### ISSUE TITLE
Cannot enable wireframe on WebGL custom shapes.

### ISSUE THREAD

**Issue by Asupkay** [processing/p5.js#4677]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Dom
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version: p5.js v0.10.2
- Web browser and version:  83.0.4103.97 (Official Build) (64-bit)
- Operating System: Linux Mint 18 Cinnamon 64-bit
- Steps to reproduce this:

Cannot get a wireframe to show on vertex shapes even though it works in web editor. You can see this code here: https://editor.p5js.org/codingtrain/sketches/OPYPc4ueq produces a wireframe on the terrain, but when I run that locally it does not produce a wireframe and adding stroke as shown in the code below does not work.

Not sure if this is a bug, but I would appreciate any help, thanks :).
```
var cols, rows;
var scl = 20;
var w = 1400;
var h = 1000;

var flying = 0;

var terrain = [];

function setup() {
  createCanvas(600, 600, WEBGL);
  cols = w / scl;
  rows = h / scl;

  for (var x = 0; x < cols; x++) {
    terrain[x] = [];
    for (var y = 0; y < rows; y++) {
      terrain[x][y] = 0; //specify a default value for now
    }
  }
}

function draw() {

  flying -= 0.1;
  var yoff = flying;
  for (var y = 0; y < rows; y++) {
    var xoff = 0;
    for (var x = 0; x < cols; x++) {
      terrain[x][y] = map(noise(xoff, yoff), 0, 1, -100, 100);
      xoff += 0.2;
    }
    yoff += 0.2;
  }


  background(0);
  translate(0, 50);
  rotateX(PI / 3);
  stroke(255); /** HERE **/
  strokeWeight(5); /** HERE **/
  fill(200, 200, 200, 255);
  translate(-w / 2, -h / 2);
  for (var y = 0; y < rows - 1; y++) {
    beginShape(TRIANGLE_STRIP);
    for (var x = 0; x < cols; x++) {
      vertex(x * scl, y * scl, terrain[x][y]);
      vertex(x * scl, (y + 1) * scl, terrain[x][y + 1]);
    }
    endShape();
  }
}
```

**Comment by stalgiag** [comment]
Hi @Asupkay thanks for the issue! This is a problem with TRIANGLE_STRIP stroking that was fixed in #4533 and will be in the next release. You can build from the `main` branch of this repo or use an older version of p5 in the meantime. I am closing this for organizational purposes but feel free to ping me here if this doesn't solve your problem.
