### ISSUE TITLE
noFill not working in 1.0.0. WEBGL

### ISSUE THREAD

**Issue by buggles1** [processing/p5.js#4680]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [X ] Core/Environment/Rendering
- [ ] Data
- [ ] Dom
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:
 noFill(0) is not working in 1.0.0. It works with built-in shapes but not those created with a vertex list.

- p5.js version: 1.0.0
- Web browser and version: Safari 13.1.2
- Operating System: Mac OS 10.12.6 and 10.14.6
- Steps to reproduce this:  Type: fill('orange'); Make a polygon using vertex commands: Turn on noFill(0). Polygon remains filled. Type: box(50); box is not filled-I was told in Discourse that noFill() works in 0.10.2

**Comment by montoyamoraga** [comment]
hi @buggles1,

could you plase show us an example on our editor.p5js.org?
that would be awesome, thanks!

**Comment by buggles1** [comment]
I will send you the code directly because noFill() works in the editor but
not in HTML. Thanx.
noFill() works in v 0.10.2. I have tested it and submitted an issue report.

<html>
<head>
  <script src="p5.js"></script>
</head>
<body>

<script>
var th = .345;

function setup() {
  createCanvas(800, 600, WEBGL);
}
function draw() {
   background(204);
   rotateX(-0.5);
   scale(3);

   fill('orange');
   stroke(253);

   noFill(); // <-------- noFill();

   rotateY(th);
   noFill();
   box(50,-100, 20);
   th = th + .02;
beginShape();  // orange trapezoid
vertex( 0,0,0 );
vertex( 35,0,0 );
vertex( 35,-47,0 );
vertex( 12,-35,0 );
endShape(CLOSE);
}
</script>

</body>
</html>

 CND aka buggles1

~ Godspeed ~

**Comment by stalgiag** [comment]
Hi @buggles1 thanks for the issue! This is the same as #4677 and #4530 and is fixed in the main branch here on the Github.

We can leave this issue open until the next release.

**Comment by buggles1** [comment]
Thank you. How do I get the update from Github? Sorry, new to Github.


~ Godspeed ~

**Comment by stalgiag** [comment]
Hi @buggles1 You can do [steps 1-5 of the Development Process](https://p5js.org/contributor-docs/#/README?id=development-process) section of the contributors docs.

Alternatively you can use [the library file in this editor sketch.](https://editor.p5js.org/stalgiag/sketches/gcSyqmJsl)

**Comment by buggles1** [comment]
noFill() does work in the editor. It also works in v0.10.2. Going
through the development process seems very daunting. Can't I just get
Githubs latest version of p5.js somewhere? Thanx.


~ Godspeed ~

**Comment by buggles1** [comment]
Your version of p5.min is v1.0.0 but is dated June 8, 2020. My version is
v1.0.0 dated Fb 29, 2020. I downloaded the latest version (or so I thought)
a few days ago thinking that was my problem. Where can I go to get the
latest, latest version? Thanx, this is most helpful.


~ Godspeed ~

**Comment by stalgiag** [comment]
You do have the latest officially released version which was made on Feb. 29th. The other file (June 8th) was built locally by me with the most recent Github main branch using the steps in the above linked contributor docs.

**Comment by montoyamoraga** [comment]
thank u @stalgiag !

**Comment by buggles1** [comment]
You are obviously one of the main forces in p5js development. Thank you for
responding to my issue. Could you send me the June version of 1.0.0 or am I
asking for trouble using it. I have June p5.min from your sketch. As a
casual user am I really going to notice a difference.

This was to be my workaround just fyi:

function framePoly(v) { // v is an array of vertices - preferably in groups
of 3 :)
   // Draw polygons as wireframe aka noFill();
   // add 1st point to end of array to close polygon - "CLOSE" will not
work here
   var len = v.length;
   v[len] = v[0]; v[len+1] = v[1]; v[len+2] = v[2];
   // or... v.push(v[0]);  v.push(v[1]);  v.push(v[2]);

  beginShape();
  for (var i = 0 ; i < len; i += 3) {
         line(v[i], v[i+1], v[i+2],   v[i+3], v[i+4], v[i+5]);
  }
  endShape();
}

Best :)


~ Godspeed ~

**Comment by buggles1** [comment]
Thank you. It took someone to send me a June version of p5mini to get that
fixed.


~ Godspeed ~
