### ISSUE TITLE
version number mismatch on npm 

### ISSUE THREAD

**Issue by endurance21** [processing/p5.js#4681]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Dom
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ x] Other (versioning on npm)

#### Feature enhancement details:
The actual version at of p5 at npm  shows `1.0.0`  however as you download it and opening the p5.js file in /node_modules/lib 
we see `v0.10.2` , i am sure one of them is incorrect !
![image](https://user-images.githubusercontent.com/43696525/87078185-e3e01e00-c241-11ea-824b-585bd74ceb0f.png)

**Comment by limzykenneth** [comment]
It is a known slight build error, only the version string at the top is incorrect. The library itself is 1.0.0. We cannot republish the package but this error should be fixed by the next release.
