### ISSUE TITLE
Feature request: scaled add for vectors

### ISSUE THREAD

**Issue by medakk** [processing/p5.js#4684]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Dom
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [x] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### New feature details:

It'd be nice if I could add a vector scaled by a scalar to another vector in a single operator. This is a common pattern when doing integration. 

Currently I do:

```js
x.add(p5.Vector.mult(v, dt));
```

Instead, I'd like to do:

```js
x.scaled_add(dt, v);
```

**Comment by limzykenneth** [comment]
Can this be achieve with chaining instead? eg. `v.mult(dt).add(x)`

**Comment by medakk** [comment]
That doesn't signal the intent well ie: mutating the velocity and also "adding" the position to the velocity. I'm trying to capture `x += dt * v`. Maybe what you meant is `x = v.copy().mult(dt).add(x)`?

**Comment by limzykenneth** [comment]
Yes, something like that. My code's just an example to show chaining is possible, it will mutate `v` but `x = v.copy().mult(dt).add(x)` should work without mutating v.

**Comment by medakk** [comment]
I think the original `x.add(p5.Vector.mult(v, dt));` is a lot more succint

Anyway, this is not a big deal. I just found it to be a nice touch in rust ndarray: [scaled_add](https://docs.rs/ndarray/0.12.1/ndarray/struct.ArrayBase.html#method.scaled_add). Also since there is no way to implement `x += dt*v` in js.

**Comment by miningape** [comment]
You can add this as a function in your code

```javascript
p5.Vector.prototype.scaled_add = function scaled_add(dt, v) { 
    this.add(p5.Vector.mult(v, dt));
}
```

I havent tested it but this should work, ill try adding it to p5 soon

**Comment by lmccart** [comment]
We don't have a clear explanation of how this feature [expands access](https://github.com/processing/p5.js/blob/main/contributor_docs/access.md), so I will close this for now. If an access statement can be added to the issue request, please feel welcome to reopen.
