### ISSUE TITLE
dropdown and input in the canvas

### ISSUE THREAD

**Issue by Hugo54x** [processing/p5.js#4691]
#### Most appropriate sub-area of p5.js?
- [x] Dom
- [x] IO
- [x] Utilities
#### New feature details:
It would be nice to have an option, to create a dropdown and an input field directly tied into the p5 canvas. I am currently writing an application. When I use the createSelect() and later add some more content before my canvas the position of these elements would be destroyed. I would prefer a createDropdown() for that because of the relativily positioning.

**Comment by limzykenneth** [comment]
Does [p5.gui](https://github.com/bitcraftlab/p5.gui) have something that does what you want?

**Comment by Hugo54x** [comment]
@limzykenneth thx, this is what I am searching. I googeld for "p5 dropdown", but I did not find that.
