### ISSUE TITLE
Example for pointLight does not work.

### ISSUE THREAD

**Issue by JimBrink** [processing/p5.js#4692]
The example in  https://p5js.org/reference/#/p5/pointLight doesn't work.  It appears that the light source location is supposed to move with the mouse but that doesn't happen.  The variables locX and locY do follow the mouse so unfortunately the problem is probably with the code for pointLight.

#### Most appropriate sub-area of p5.js?
- [ x] WebGL

#### Details about the bug:

- p5.js version:  p5.js v1.0.0 February 29,
- Web browser and version: Tested in Opera and Firefox
- Operating System:  Windows 10 
- Steps to reproduce this:  Run the example on the reference page

**Comment by akshay-99** [comment]
Hi!
I think this is because of issue #4391 which was patched in #4509
