### ISSUE TITLE
FES + i18n: Loading translation files from CDN

### ISSUE THREAD

**Issue by akshay-99** [processing/p5.js#4694]
#### Most appropriate sub-area of p5.js?

- [x] Friendly Errors
- [x] Internationalization 

#### Feature enhancement details:

Internationalization was introduced to the FES in #4233. So far we only have English strings for the FES and even [that file](https://github.com/processing/p5.js/blob/b52226962eebf9f58f70eed68c4ce32661677d23/translations/en/translation.json) is starting to get pretty big, and could grow even bigger if more functionality is added or when translations are added for all of [these](https://github.com/processing/p5.js/search?q=console.log+inpath%3Asrc+--filename%3Afes_core.js+-filename%3Areference.js+-filename%3AREADME.md&unscoped_q=console.log+inpath%3Asrc+--filename%3Afes_core.js+-filename%3Areference.js+-filename%3AREADME.md) and [these](https://github.com/processing/p5.js/search?q=throw+new+Error+inpath%3Asrc&unscoped_q=throw+new+Error+inpath%3Asrc) messages.

In the future, when we have translations for more and more languages, all of this may take up a lot of space within the library. 

As @outofambit and @limzykenneth  discussed in #4233, we can host the translation files on a CDN and then fetch whichever file is needed depending on the language detected by `i18next-browser-languageDetector`. The English translation will serve as a fallback in case something goes wrong while fetching from the CDN. Another option could be to package translations into the zip, with instructions on how to load one. 

I am more inclined towards the first option as it does not require extra work and understanding on the user's part. Maybe we can implement the second option too, to have translated messages when running offline.
Translations could be updated with new releases of p5.

I can work on updating the internationalization code, the build process, the release process to implement this.
We should also have another issue to let new contributors know that we are looking for help in adding translations for all languages. :smile:

**Comment by limzykenneth** [comment]
The CDN option seems good to me. We can package the English version into the library itself so something is always available offline. In the future it would be nice if the website itself can package the appropriate langauge version into the library download depending on which language the user is viewing the website in, but that's much more advanced.
