### ISSUE TITLE
Push and Pop throw error when ran through canvas instance variable

### ISSUE THREAD

**Issue by WDSTEVE** [processing/p5.js#4695]
- [ ] Color
- [X] Core/Environment/Rendering
- [ ] Data
- [ ] Dom
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

- p5.js version: v1.0.0
- Web browser and version: Chrome 83.0.4103.116 (64-bit)
- Operating System: Windows 10 Version 1909
- Steps to reproduce this:
```
let canvas;

function setup() {
	canvas = createCanvas(250, 250);
}

function draw() {
	canvas.push();
	//push();
	canvas.scale(5);
	canvas.fill("lime");
	canvas.ellipse(25, 25, 45, 45);
	canvas.pop(); //Uncaught TypeError: Cannot read property 'properties' of undefined (line 64766)
	//pop(); //works fine with normal push and pop, just uncomment it
}
```

**Comment by chen-ni** [comment]
I've searched through the documentation and have not found that push() and pop() could be used this way. Could you add a reference to this usage?

**Comment by WDSTEVE** [comment]
My assumption was that, as push and pop have a effect on graphics, they could be run on a canvas instead of globally like other graphical functions. If this behavior was intended I will replace this thread with a feature request.

**Comment by chen-ni** [comment]
@WDSTEVE It seems to me that `push()` and `pop()` do not apply to graphics. To apply them to a graphics `pg`  I would have to use `pg.push()` or `pg.pop()` instead. See an example I've created: https://editor.p5js.org/chen-ni/sketches/H0Nz0mcyS. I guess `push()` and `pop()` apply to the canvas by default.

**Comment by WDSTEVE** [comment]
Awesome, sorry for the miss files issue
