### ISSUE TITLE
https://p5js.org/ wrong links

### ISSUE THREAD

**Issue by VSMent** [processing/p5.js#4698]
I am not sure if it is correct place, but want to notify that links from [this page (Vector)](https://p5js.org/reference/#/p5.Vector), from Description
**mag()** and **heading()**  should bring us to:
`https://p5js.org/reference/#/p5.Vector/mag` and 
`https://p5js.org/reference/#/p5.Vector/heading`.

Instead, they do:
`https://p5js.org/reference/#/p5/mag`
`https://p5js.org/reference/#/p5/heading`

If you know how to reach website devs, please notify them or send me their contacts.

**Comment by limzykenneth** [comment]
The links can be edited in the inline documentation [here](https://github.com/processing/p5.js/blob/1.0.0/src/math/p5.Vector.js#L15)

**Comment by VSMent** [comment]
Thanks. Seems it was already done by https://github.com/processing/p5.js/commit/b704784c323b9b7e7c6636a94e18ed86a7212f1d, 3 moths ago.
When will it be available online?

**Comment by limzykenneth** [comment]
I don't have a timeline for the next release at the moment. @lmccart Do you have an idea?

**Comment by lmccart** [comment]
@limzykenneth @VSMent aiming to get a release out this month before we transition to a new project leader next month. closing this issue since this has been resolved.
