### ISSUE TITLE
Shape point() does not work with scale > 1, strokeWeight < 1

### ISSUE THREAD

**Issue by ednl** [processing/p5.js#4707]
#### Most appropriate sub-area of p5.js

- [x] Core/Environment/Rendering

#### Details about the bug:

- p5.js version: 1.1.9 July 22, 2020
- Web browser and version: Safari 13.1.2 (15609.3.5.1.3)
- Operating System: MacOS 10.15.6
- Steps to reproduce this: I have a square canvas and want to use it as a coordinate system(-1..+1, -1..+1). So I translate to (width/2, width/2) and scale by (width/2,-width/2). Then I set the strokeWeight to be 1 actual pixel: 2/width. Expectation: lines, circles and points drawn will be 1 pixel wide. This is true for lines and circles, but not points. It seems that the strokeWeight is not used for points, perhaps because it can't be smaller than 1, but the scale *is* respected. This results in mega-points covering a quarter of the canvas (because in scaled coordinates the area is 4). Code that fails:

```
function setup() {
	createCanvas(400, 400);		// square canvas
	background(0);
	noFill();

	const pixperunit = width / 2;	// number of pixels per unit in the desired coordinate system
	translate(pixperunit, pixperunit); // set the origin in the middle
	scale(pixperunit, -pixperunit);	// horizontal and vertical range is now -1..+1
	strokeWeight(1 / pixperunit);	// all lines, arcs and points should be 1 pixel wide

	stroke(255, 0, 0);		// red axes
	line(-1, 0, 1, 0);
	line(0, -1, 0, 1);

	stroke(0, 255, 0);		// green circle
	circle(0, 0, 1);

	stroke(0, 0, 255);		// blue dot
	point(0, 0);
}
```

The resulting picture, which should have one blue pixel in the centre, not a large blue square:
![Schermafbeelding 2020-07-23 om 15 04 48](https://user-images.githubusercontent.com/9798500/88289951-50552580-ccf6-11ea-9ad7-4451103e7ea1.png)

**Comment by ednl** [comment]
The issue is in https://github.com/processing/p5.js/blob/main/src/core/p5.Renderer2D.js#L559 from line 559 where lineWidth is checked, presumably as a scaled value, but then fillRect is used with hardcoded width=1, height=1 without regard to scaling.

**Comment by ednl** [comment]
I could invent some amendment to that function in p5.Renderer2D.js, but I am relatively new to p5js and certainly to the actual code behind it, and I don't know whether this is by design, or what the implications are for a very local change there. Would other parts change behaviour, or break? Maybe the performance would suffer greatly?

**Comment by TakumaKira** [comment]
Hi @ednl,

I looked into the change history of the repository, and I couldn't find any reason the conditional statement on line 559 is needed. Also, the unit test for my changes passed. So I believe this library can allow your case and created the PR #4756 to allow drawing a point with strokeWeight < 1.

**Comment by ednl** [comment]
@TakumaKira Fantastic, thanks.
