### ISSUE TITLE
release 1.1.5 adds ~220kb of documentation to p5.min.js

### ISSUE THREAD

**Issue by neefrehman** [processing/p5.js#4708]
The 1.1.5 release has increased the size of p5.min.js by a substantial amount, which you can see when looking at the assets on the [release page](https://github.com/processing/p5.js/releases) (p5.js has stayed the same size). Downloading the file and looking at its contents shows that the extra ~220kb is made up of documentation like below:

`p5:{alpha:{name:"alpha",params:[{name:"color",description:'<p><a href="#/p5.Color">p5.Color</a> object, color components,\n                                        or CSS color</p>\n',type:"p5.Color|Number[]|String"}],class:"p5",module:"Color"},blue:{name:"blue",params:[{name:"color",description`

It looks like this documentation has been introduced from [parameterData.json](https://github.com/processing/p5.js/blob/main/docs/parameterData.json), by one of the two commits in that release. I'm not sure what the build error that needed to be fixed was, but it looks like `parameterData.json` still needs to be excluded from the minified build process.

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Dom
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other: Bundling

#### Details about the bug:

- p5.js version: >1.1.5
- Web browser and version: all
- Operating System: all
- Steps to reproduce this: n/a

**Comment by jay20162016** [comment]
It seems that there is still a substantial amount of documentation in the minified version.

**Comment by neefrehman** [comment]
It looks like a new release hasn't been published since #4709 was merged with the fix. I'm still using 1.1.4

**Comment by jay20162016** [comment]
1.19 doesn't have the fix either.

**Comment by neefrehman** [comment]
#4709 was merged the day after 1.1.9 was published, so the next release should contain the fix. Although I'm not sure when that will be. This seems like quite a big issue to wait so long to publish a fix for

**Comment by lmccart** [comment]
hey all, thanks for your patience. we're operating at reduced capacity in "maintenance mode" right now, so releases will be coming more slowly. i'll do my best to get something out in the next couple weeks. [see statement here](https://medium.com/processing-foundation/p5-js-leave-of-absence-70dc58e14da9)
