### ISSUE TITLE
HTML Tags actually get rendered in docs

### ISSUE THREAD

**Issue by NagariaHussain** [processing/p5.js#4710]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [x] Dom
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version: 1.1.9
- Web browser and version: 84.0.4147.89 (Official Build) (64-bit) (cohort: Experimental (No-Diff)) and Microsoft Edge 84.0.522.40 (Official build) (64-bit)
- Operating System: Windows 10
- Steps to reproduce this:
Go to the p5.js reference page and take a look at the documentation of createX() functions.

The input tags in the dom.js docs are getting rendered on the page. Here is a screenshot for the documentation of the createCheckbox() function:
<img width="620" alt="bug1" src="https://user-images.githubusercontent.com/34810212/88389045-540aaa00-cdd3-11ea-9658-2a33b4181df9.png">
The above is also happening in the docs of other DOM element creation functions like createInput, createSelect etc.
I have tried this in two browsers: **Google Chrome** and **Microsoft Edge**.

**Comment by KProgrammer** [comment]
I think this issue would be more appropriate on the p5.js-website repo, [https://github.com/processing/p5.js-website/issues](https://github.com/processing/p5.js-website/issues), but I think I will work on it
