### ISSUE TITLE
loadModel() doesn't correctly use UV map

### ISSUE THREAD

**Issue by OMGChase** [processing/p5.js#4718]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Dom
- [ ] Events
- [x] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

First off, not sure if this is a bug, or a feature that hasn't been implemented yet.
Using a UV unwrapped object with the loadModel() and texture() does not place the texture in the correct place on the object UV.
 
- p5.js version: 0.10.2
- Web browser and version: Firefox 78.0.2
- Operating System: Windows 10
- Steps to reproduce this: 

1. create WEBGL scene
2. add UV unwrapped model using loadModel()
3. add UV Texture on model using texture()
4. run

Example code below:

> 
> let obj, img;
> 
> function preload() {
> 
>   obj = loadModel('place uv unwrapped model here');
>   img = loadImage('place uv unwrapped image here'); 
> 
> }
> 
> 
> function setup() {
>   
>   createCanvas(windowWidth, windowHeight, WEBGL);
>   
>   //Setup Camera
>   perspective(45, width / height, 0.01, 10000);
>   camera(0, 0, 0.1, 0, 0, -5, 0, 1, 0);
>   
> }
> 
> function draw() {
>   
>   background(20);
> 
>   //Draw obj with UV texture
>   texture(img);
>   translate(0, 0, -65);
>   rotateY(frameCount*0.003);
>   scale(20);
>   noStroke();
>   model(obj);
> 
> }

Example file can be found here:
https://editor.p5js.org/OMGChase/sketches/TPFitpUDO
Inluded in the editor is an example uv unwrapped model with corresponding UV Texture

Thanks to all developers who are working on this powerful tool!

**Comment by aferriss** [comment]
Hi @OMGChase ,

Try doing a vertical flip on the uv map. That seemed to fix it for me here: https://editor.p5js.org/buckWorkshop/sketches/n3PZ68taL

**Comment by OMGChase** [comment]
> 
> 
> Hi @OMGChase ,
> 
> Try doing a vertical flip on the uv map. That seemed to fix it for me here: https://editor.p5js.org/buckWorkshop/sketches/n3PZ68taL

Yes! That's the trick.

Thank you!

**Comment by myselfhimself** [comment]
Thank you that some UV texturing example is now on the internet thanks to this issue.
I do believe there should be some piece of documentation on UV mapped textures in p5js.. Should I create an Issue for this?

**Comment by stalgiag** [comment]
I think this is a dupe of #4866 where we are looking for someone to make the UV flip during model loading. Should be somewhat simple if you want to give that a shot.

**Comment by myselfhimself** [comment]
OK thank you!

čt 28. 1. 2021 v 17:25 odesílatel Stalgia Grigg <notifications@github.com>
napsal:
