### ISSUE TITLE
reporting bug in createButton

### ISSUE THREAD

**Issue by bwstewart79** [processing/p5.js#4725]
#### Most appropriate sub-area of p5.js?

- [x] Dom

#### Details about the bug:

- p5.js version: "https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.10.2/p5.js"
- Web browser and version: Chrome: version 84.0.4147.105 (Official Build) (64-bit) (cohort: Stable)
Firefox: version 78.0.2 (64-bit)
- Operating System: Windows 10 OS Version 1909 (Build 18363.836)
Ubuntu 20.04
- Steps to reproduce this:
Here is a link to the full code:
https://editor.p5js.org/bwstewart79/sketches/UT3gBFtbv

When you scroll down, the button should follow, but it isn't.

I am having an issue with the positioning of a button. I would like the button to be 'sticky' but the position always says absolute.
It doesn't matter if I change the position to relative, fixed, or sticky, the position in the console always says absolute.

Here is a snippet of the code: 
![image](https://user-images.githubusercontent.com/68917789/88957278-a5e87f80-d26c-11ea-830f-8560f3041017.png)

Here is a snippet of the console:
![image](https://user-images.githubusercontent.com/68917789/88957342-bc8ed680-d26c-11ea-9bef-aca1c3439f52.png)

**Comment by limzykenneth** [comment]
This has been fixed in the latest release. You can change the URL to the library to `https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.1.9/p5.js` in order to use it.
