### ISSUE TITLE
DrawingContext shadowBlur low performance 

### ISSUE THREAD

**Issue by trantiendev** [processing/p5.js#4731]
#### Most appropriate sub-area of p5.js?

- [x] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] Dom
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

## Hi there
I have some problems when using shadowBlur, I created particles just like this https://p5js.org/examples/simulate-particles.html
But when I using this code to make a shadowBlur on circles, it's very lagg and bad performance 
```javascript
 createParticle() {
    noStroke();
    fill('rgba(200,169,169,0.5)');
    drawingContext.shadowBlur = 10; // this line
    drawingContext.shadowColor = 'white'; // this line
    circle(this.x,this.y,this.r);
  }
```

**Comment by limzykenneth** [comment]
`shadowBlur` is a native HTML canvas function and not a p5.js specific feature so we cannot provide support here. Blur in general is a very slow process and running it constantly in an animation loop will result in slow down in performance.

If you need help with your own code, please direct your questions to the [forum](https://discourse.processing.org). We use GitHub issues mainly for bug reports and feature requests only. Thanks!
