### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by jeong** [processing/p5.js#4734]
#### Most appropriate sub-area of p5.js?
- [x] Other (specify if possible)

#### Details about the bug:
There is a broken link in [contributor_docs/organization.md](https://github.com/processing/p5.js/blob/main/contributor_docs/organization.md) page.

[the online editor](https://github.com/processing/p5.js/blob/main/contributor_docs/editor.p5js.org
) link shows "Page not found" error.

![p5 js](https://user-images.githubusercontent.com/749767/89914588-2ffef380-dc30-11ea-89dd-3c9e732716d8.png)

**Comment by 13sfaith** [comment]
I would like to work on this issue as my first contribution.
