### ISSUE TITLE
An error in Chinese translation

### ISSUE THREAD

**Issue by Zixin-Ye** [processing/p5.js#4735]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Dom
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [x] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other

#### Feature enhancement details:
For function map() , parameter ‘stop1’ should be translated to ''现在值的最高值'', rather than '现在值的最低值'.

https://p5js.org/zh-Hans/reference/#/p5/map

**Comment by limzykenneth** [comment]
Thanks @Zixin-Ye, would you like to make the changes and file a PR?

**Comment by mkmori** [comment]
Hi, @limzykenneth , @Zixin-Ye : I've never done a pull request...but this _seemed_ doable for me! :)

Due to issue #4728 , the documentation points to the wrong version (1.1.8), but substituting "1.1.9"...I see only the English source...? Where/How would @Zixin-Ye or me find the Simplified Chinese?

**Comment by Zixin-Ye** [comment]
@limzykenneth @mkmori 
Hi,

I'm really willing to fix it and I tried. But I also can not find the right place to change the Chinese translation text.

**Comment by mkmori** [comment]
@Zixin-Ye : A step closer???? I found the source text...if you know how to GitHub! (Fork and pull request? @limzykenneth ?)

[https://github.com/processing/p5.js-website/blob/main/src/data/reference/zh-Hans.json](https://github.com/processing/p5.js-website/blob/main/src/data/reference/zh-Hans.json)

**Comment by limzykenneth** [comment]
@mkmori Yes, that's the source for the translation file, and you can just fork the website repo, make the changes, then file a pull request from your fork to the main branch of the website repo. You can checkout GitHub help page for detailed guides. Let me know if you need help.

**Comment by mkmori** [comment]
@limzykenneth I think I got it--first time for everything! :) Anything else to do on my part?

**Comment by limzykenneth** [comment]
All good, thanks!
