### ISSUE TITLE
Replace color in images feature

### ISSUE THREAD

**Issue by WojtekTB** [processing/p5.js#4744]
### How would this new feature help increase access to p5.js?
This, along with other image editing tools, will give designers and artists more power over image manipulation without having to build their own functions that might be inefficient or too complicated for them. For example if someone wanted to make a sketch where a specific color of the image is changed to #000000 (transparent) and then do something in the background, they might be turned off from the idea because it might seem complicated. 

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [x] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### New feature details:
```javascript
img = loadImage('assets/myImage.jpg');
let oldColor = color(0, 0, 0, 255);
let newColor = color(0, 0, 0, 0);
img.replaceColor(oldColor , newColor);
image(img); //a picture where all black is now transparent
```

**Comment by limzykenneth** [comment]
I think this is a bit too specific and out of scope of the project. It would work great as an addon library though.

**Comment by limzykenneth** [comment]
@WojtekTB Sorry for the very late reply. You can [start here](https://github.com/processing/p5.js/blob/main/contributor_docs/creating_libraries.md) for a tutorial about creating an addon library. I'm closing this issue for now but feel free to continue discussions here if you like.
