### ISSUE TITLE
A built in feature to convert uploaded images to a p5js image object

### ISSUE THREAD

**Issue by WojtekTB** [processing/p5.js#4745]
### How would this new feature help increase access to p5.js?
Right now there is a way to make an upload element through a p5js DOM library, but there is no built in way to then get the uploaded image and convert it to a p5js image object. I believe that this feature being built in would help a lot of projects to be more interactive as now people could make projects where the sketch interacts with an uploaded image, be it some sort of filter or maybe some other manipulation.

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [X] DOM
- [ ] Events
- [X] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### New feature details:
Currently, you can technically do this by getting the DOM element through document.getElementById() and then creating a URL object to it though URL.createObjectURL(); which can then be put into loadImage, but it would be great if it was already its own function.
Full code would be something like this:
```javascript
const selectedFile = document.getElementById('imageToEmulate').files[0];
let placeholderImage = new Image();
let imageSrc = URL.createObjectURL(selectedFile);
imageToGuess = loadImage(imageSrc, () => {
    //your code here
}
```

If it was a single function I'd imagine it being something like this:
```javascript
let input = createFileInput(handleFile);
let myImageObject;
input.onImageUpload((imgObject)=>{myImageObject} = imgObject);
```

**Comment by violetcraze** [comment]
Don't know if `createFileInput()` was created in response to this issue but seems like it can be closed now, since the feature already exists.

@WojtekTB If you're still interested here's a link to the reference page: https://p5js.org/reference/#/p5/createFileInput.
