### ISSUE TITLE
The index.html file does not open in the browser unless the link to 'p5.sound.min.js' is removed

### ISSUE THREAD

**Issue by Swapnil-2001** [processing/p5.js#4747]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] Dom
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version: 1.1.9
- Web browser and version: Google Chrome version 84.0.4147.125
- Operating System: Windows 10 Pro, version 1903
- Steps to reproduce this:

When the index.html file from **p5.js complete download** is opened in the browser, the message in the console reads:
**p5.sound.min.js:2 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/Lenovo/Desktop/p5/addons/p5.sound.min.js.map: System error: net::ERR_FILE_NOT_FOUND**
Removing the script tag _<script src="../addons/p5.sound.min.js"></script>_ in the index.html file solves the problem.

**Comment by limzykenneth** [comment]
The script should still run without issue as those should be blocking errors preventing p5.js from running. You can try running the sketch from a local server, checkout [this page](https://github.com/processing/p5.js/wiki/Local-server) for how to do that.

**Comment by Swapnil-2001** [comment]
Thank you, I'll certainly try that.
And, it might really be a problem at my end, but the file just would not open -- it would keep showing me a 'loading...' screen.

**Comment by miningape** [comment]
I've had this same issue, I solved it by using another source for that library, so it seems like theres something wrong with the file supplied

**Comment by surajsurajsuraj** [comment]
Same issue

**Comment by artze** [comment]
I'm able to replicate the issue highlighted by OP, by downloading `p5.js complete` from [here](https://p5js.org/download/) and opening `/empty-example/index.html` with Chromium browser.

As suggested [above](https://github.com/processing/p5.js/issues/4747#issuecomment-674577007), I could get it working with `http-server` npm. Following is what i did:
1. Run `http-server` at **project root**
2. Go to `http://localhost:8080/empty-example` and it works.

++

We might want to update the docs *Downloading a copy of the p5.js library* located [here](https://p5js.org/get-started/), to mention setting up a local server. @limzykenneth - what do you think? I can submit a PR for this

**Comment by limzykenneth** [comment]
@artze Since the existing instructions isn't sufficient anymore you can file a PR and we'll see how we can word the guide to still be as accessible as possible. Thanks.

**Comment by artze** [comment]
@limzykenneth ok I will do that

**Comment by artze** [comment]
@limzykenneth https://github.com/processing/p5.js-website/issues/885 is resolved. Suggest to close this issue as well.
