### ISSUE TITLE
how to createCanvas to the center in p5js editor

### ISSUE THREAD

**Issue by arvind088** [processing/p5.js#4748]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Dom
- [ ] Events
- [x] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version: 
- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

**Comment by Swapnil-2001** [comment]
You may use a variable to store a pointer to the canvas you created, and then call **.position()** on this variable.
[https://p5js.org/reference/#/p5.Element/position](url)
You can adjust the position as you like.
There might be a better way to do it but this is one way.

**Comment by limzykenneth** [comment]
Hi, if you need help with your own code, please direct your questions to the [forum](https://discourse.processing.org). We use GitHub issues mainly for bug reports and feature requests only. Thanks!
