### ISSUE TITLE
Uncaught TypeError: Cannot read property 'width' of undefined (Image Function)

### ISSUE THREAD

**Issue by KrishGarg** [processing/p5.js#4749]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Dom
- [ ] Events
- [x] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version: v0.8.0
- Web browser and version: Chrome | Version: 84.0.4147.125
- Operating System: Windows | Version: 10.0.19041 Build 19041
- Steps to reproduce this:
![image](https://user-images.githubusercontent.com/65218584/90394532-729d5180-e0b0-11ea-91ba-d8cff5e4ac21.png)
```

const Engine = Matter.Engine;
const World = Matter.World;
const Bodies = Matter.Bodies;
const Constraint = Matter.Constraint;

var engine,world;
var hexagon1,hexagonImg;
//area 1 boxes
var box1,box2,box3,box4,box5,box6,box7,box8,box9,box10,box11,box12,box13,box14,box15,box16;
//area 2 boxes
var box1,box2,box3,box4,box5,box6,box7,box8,box9;

function preload() {
  hexagoneImg = loadImage("hexagon.jpg");
}

function setup() {
  createCanvas(1536,792);

  engine = Engine.create();
  world = engine.world;

  hexagon1 = Bodies.circle(50,200,20);
  World.add(world,hexagon1);
}

function draw() {
  background("white");

  imageMode(CENTER);
  image(hexagonImg,hexagon1.position.x,hexagon1.position.y,40,40);

  textSize(30);
  text(mouseX+","+mouseY,1300,100);
}

```

**Comment by limzykenneth** [comment]
the p5.js version you are using (`0.8.0`) is rather old, please try updating to the latest version (`1.1.9`) and try again.

Generally if you need help with your own code, please direct your questions to the [forum](https://discourse.processing.org). We use GitHub issues mainly for bug reports and feature requests only. Thanks!

**Comment by aferrero** [comment]
I am having the same error, it seems like loadImage() is not returning value

**Comment by KrishGarg** [comment]
@aferrero My issue was of a typo in a variable name, you can check for the same, or open another issue.

**Comment by DavidHernandezUV** [comment]
Hello, i had the same error and I could solve this problem calling the preload() function before createCanvas function in setup():

CODE:

```
let img;

function preload() {
  img = loadImage("src/images/picture.png");
}

function setup() {
  preload();
  createCanvas(500, 500);
}

function draw() {
  background(220);
  image(img,0,0)
}

```

I hope that can help u :)
