### ISSUE TITLE
Addition of modulus function in p5.js reference

### ISSUE THREAD

**Issue by Swapnil-2001** [processing/p5.js#4760]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Dom
- [ ] Events
- [ ] Image
- [ ] IO
- [x] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Feature enhancement details: 
The p5.js reference does not currently have a modulus function built into it. Would it be useful if there was an implementation of the modulus function in src/math/calculation.js ? If so, I'd be glad to work on it.

**Comment by lmccart** [comment]
we generally avoid aliasing to keep the reference size smaller and avoid confusion. this request is also missing some explanation of how it [expands access](https://github.com/processing/p5.js/blob/main/contributor_docs/access.md) so I'd propose we close this for now
