### ISSUE TITLE
SaveTable not handling commas as expected

### ISSUE THREAD

**Issue by marcusround** [processing/p5.js#4766]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Dom
- [ ] Events
- [ ] Image
- [x] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version: v1.1.9
- Web browser and version: Firefox 79.0, Chrome 84.0.4147.135
- Operating System: Windows 10
- Steps to reproduce this:

```
function setup() {

  const table = new p5.Table();
  table.addColumn('name');
  table.addColumn('species');

  let row1 = table.addRow();
  row1.setString('name', 'Lion');
  row1.setString('species', 'Panthera leo');

  let row2 = table.addRow();
  row2.setString('name', 'Woodpecker, Greater Spotted')
  row2.setString('species', 'Dendrocopos major')

  saveTable(table, 'new.csv');

}
```

Saves this file:
```
name,species
Lion,Panthera leo
Woodpecker, Greater Spotted,Dendrocopos major

```

Expected output:
```
name,species
Lion,Panthera leo
"Woodpecker, Greater Spotted",Dendrocopos major

```

**Comment by marcusround** [comment]
As a further example,

With file `old.csv`:

```
name,species
Lion,Panthera leo
"Woodpecker, Greater Spotted",Dendrocopos major

```

Run this sketch:
```
function setup() {

  loadTable('old.csv', 'header', (t) => saveTable(t, 'new.csv') ) ;

}
```

Get this output:
```
name,species
Lion,Panthera leo
Woodpecker, Greater Spotted,Dendrocopos major

```

The `"` have been dropped.

**Comment by MuLx10** [comment]
Hello @marcusround , I faced a similar issue. So I created a patch for the same. I shall create a Pull Request for the same.

**Comment by MuLx10** [comment]
I thought of inserting a check [here](https://github.com/processing/p5.js/blob/c1c672272ba613ed713a1a26463a8376565e0792/src/io/files.js#L1721) and [here](https://github.com/processing/p5.js/blob/3f0b2f0fe575dc81c724474154f5b23a517b7233/src/data/p5.TypedDict.js#L349) to see if the element type is string, and then accordingly surround that with quotation marks.


```js
if (j < table.rows[i].arr.length - 1) {
    if(typeof table.rows[i].arr[j] === 'string') {
        pWriter.write('"' + table.rows[i].arr[j] + '"' + sep);
    }
    else {
        pWriter.write(table.rows[i].arr[j] + sep);
    }
}
```

I'd love thoughts or advice on this.
Thank you.

**Comment by surajsurajsuraj** [comment]
Hello @MuLx10 , I think instead of checking if it is a string, you should be checking:

- if it has comma separated values. 
- if the ['ext' is 'csv'](https://github.com/processing/p5.js/blob/c1c672272ba613ed713a1a26463a8376565e0792/src/io/files.js#L1699)  then only you need to insert double quotes since in [.tsv](https://github.com/processing/p5.js/blob/c1c672272ba613ed713a1a26463a8376565e0792/src/io/files.js#L1700) file it is not required.
- if it is the last column then also there will be a double quotes but there won't be a seperator.

`if (j < table.rows[i].arr.length - 1) {
          //double quotes should be inserted in csv only if contains comma separated single value
          if (ext === 'csv') {
            if (table.rows[i].arr[j].includes(',')) {
              pWriter.write('"' + table.rows[i].arr[j] + '"' + sep);
            }
          } else {
            pWriter.write(table.rows[i].arr[j] + sep);
          }
        } else if (i < table.rows.length - 1) {
          //double quotes should be inserted in csv only if contains comma separated single value
          if (ext === 'csv') {
            if (table.rows[i].arr[j].includes(',')) {
              pWriter.write('"' + table.rows[i].arr[j] + '"' );
            }
          } else {
            pWriter.write(table.rows[i].arr[j] );
          }
        } else {
          //double quotes should be inserted in csv only if contains comma separated single value
          if (ext === 'csv') {
            if (table.rows[i].arr[j].includes(',')) {
              pWriter.write('"' + table.rows[i].arr[j] + '"' );
            }
          } else {
            pWriter.write(table.rows[i].arr[j] );
          }
        }`

**Comment by surajsurajsuraj** [comment]
Although I think there is also a code redundancy at this [else if](https://github.com/processing/p5.js/blob/c1c672272ba613ed713a1a26463a8376565e0792/src/io/files.js#L1722)  which is not required because the ending [else](https://github.com/processing/p5.js/blob/c1c672272ba613ed713a1a26463a8376565e0792/src/io/files.js#L1724) also has the same code.

**Comment by MuLx10** [comment]
@surajsurajsuraj That would be great, but the issue is to check whether the string includes a `,` it needs to check the entire string, which may be a problem if strings are very long.
I believe we should prefer performance over redundancy.

**Comment by surajsurajsuraj** [comment]
@MuLx10  You are right it will indeed create a problem. Then we have to think and wait of an efficient solution.  
I think a commit should be made and issue should remain open with a different title and type to increases the efficiency.

**Comment by surajsurajsuraj** [comment]
@MuLx10  If you refer to src/io/p5.Table.js , they have used regex for identifying and modifying values hence I don't think a simple `include` which has lesser complexity than all of them will have any major impact on the performance.
