### ISSUE TITLE
text rendering changes location between frames

### ISSUE THREAD

**Issue by eyaler** [processing/p5.js#477]
the text has slight x location changes during the first frames causing the rendering to be spread-out and non-smooth

function setup() {
  createCanvas(640,480);
  background(0);
  noStroke();
  textSize(100);
  text("BAD",100,100);
}

function draw() {
  noStroke();
  textSize(100);
  text("BAD",100,200);
}

![image](https://cloud.githubusercontent.com/assets/4436747/5617127/e5e92bd0-9513-11e4-9ff3-4a0e251a59e2.png)

**Comment by spasmsaps** [comment]
You are not clearing the background in draw and continuously drawing 'bad on bad', this will give you jagged graphics in any rendering framework.

```
function setup() {
	createCanvas(640,480);
	background(0);
	noStroke();
	textSize(100);
	text("GOOD",100,100);
}

function draw() {
	noStroke();
	textSize(100);
	text("BAD",100,200);
	fill(0);
	rect(0, 210, width, height);
	fill(255);
	text("GOOD",100,300);
}
```
![canvas](https://cloud.githubusercontent.com/assets/4454698/6453104/0f8b4c68-c13b-11e4-8589-d0bf0b4e25f4.png)

**Comment by eyaler** [comment]
so, my point was that the p5js rendering is not stable. if you run my code in vanilla processing you would not get the the jagged noise.

**Comment by brysonian** [comment]
as @spasmsaps pointed out, it does get the jagged edges in vanilla processing because you aren't clearing the background in draw, and you are drawing the text on top of itself. Try for yourself:

```
void setup() {
  size(640,480);
  background(0);
  noStroke();
  textSize(100);
  text("BAD", 100, 100);
}

void draw() {
  noStroke();
  textSize(100);
  text("BAD", 100, 200);
}
```
