### ISSUE TITLE
add chtushar as a contributor

### ISSUE THREAD

**Issue by montoyamoraga** [processing/p5.js#4771]
@all-contributors please add @chtushar for documentation

**Comment by montoyamoraga** [comment]
@all-contributors please add @chtushar for docs

**Comment by chtushar** [comment]
@montoyamoraga Thankyou so much :). Can you add me for code as well because my commits were merged yesterday?
[Link to my commits](https://github.com/processing/p5.js-website/commits?author=chtushar)

**Comment by montoyamoraga** [comment]
@all-contributors please add @chtushar for code
