### ISSUE TITLE
Random is not defined

### ISSUE THREAD

**Issue by MDeter67** [processing/p5.js#4783]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [let r = random (0,180;)] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Dom
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

I am using macOS Catalina 10.15 with Microsoft Edge Version 85.0.564.41. When I try to run random in an argument such as:

let r = random(0,180); 

the computer prints out "random was not defined" at the end of the statement.

**Comment by anchnk** [comment]
Hello @MDeter67,

Thank you for opening this issue. 

* Do you have any minimal code example that would allow us to reproduce the problem?
* Are you trying to use the `random` function outside p5 functions (i.e before `setup()`)?

If yes, I would suggest that you have a look at [this article](https://github.com/processing/p5.js/wiki/p5.js-overview#why-cant-i-assign-variables-using-p5-functions-and-variables-before-setup) from the wiki.
[This section](https://github.com/processing/p5.js/wiki/p5.js-overview#instantiation--namespace) is also worth reading, especially if you want to use p5 with other JavaScript libraries.

By default, you need to use a function such as `random` within a p5 function. 

So the following code won't work (throwing the error you reported):

```javascript
let r = random(0, 180); // random isn't accessible outside p5's functions

function setup() {
  createCanvas(400, 400);
}

function draw() {
  background(r);
}
```

But this should work:
```javascript
let r;

function setup() {
  r = random(0, 180);
  createCanvas(400, 400);
}

function draw() {
  background(r);
}
```

Hope it helps, feel free to add any additional info if my answer isn't helping.
