### ISSUE TITLE
Incorrect behaviour with the borders in a grid

### ISSUE THREAD

**Issue by sushant52** [processing/p5.js#4794]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] Dom
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:
I have provided a link to the code. It is supposed to generate a 2D grid with borders and select a grid when clicked. However the border behaviour of the rectangle is quite weird.  When I execute the code on my laptop with NVIDIA graphics, I get this as output: https://i.stack.imgur.com/2fJhM.png

The borders are of varying length, small at first then increase in width then small again and so on. Also there is some problem with the borders around the area which were selected. I ran the same code on another laptop with AMD graphics, this time all the borders were of same width but were much thicker than strokeWeight(1), maybe 2 or 3. Also, I could see sometimes that a border was made up of a black line along with a lighter gray line( sort of like Anti-aliasing behaviour).

Edit: When I render even a single box, it has issues. https://i.stack.imgur.com/qDQXR.png. The left and upper border are fine. However the right and down borders have an extra pixel of grayish borders which seems to be the problem. How do I fix this?

 Some people have no problem with the code whatsoever. So is this a problem with my graphics settings? How do I solve this and ensure that everyone running my code can see the correct output?

- p5.js version: v1.1.9 July 22, 2020
- Web browser and version: Chrome, Microsoft Edge and Mozilla Firefox
- Operating System: Windows 10
- Steps to reproduce this: Check This out https://editor.p5js.org/janmaltel/sketches/z_eNzf6aS

**Comment by limzykenneth** [comment]
It seems like a very low level hardware or browser implementation issue, as such not much we can solve as is. 

I would suggest not using stroke in this case for drawing a grid, instead use `line()` instead to draw the grid on top of the rectangles drawn without a stroke. The result should be more consistent that way. If you need further help do post them on the [forum](https://discourse.processing.org). Thanks.
