### ISSUE TITLE
arrayCopy is depreciated

### ISSUE THREAD

**Issue by Moosdijk** [processing/p5.js#4796]
Hi all,

I've noticed that the arrayCopy() function will be removed from further versions of p5.js, but the [reference page](https://p5js.org/reference/#/p5/arrayCopy) does not list an alternative. 

Is there an alternative in the works, a better option or will we have to go back to for() loops (which the reference page states is less efficient)?

Thanks!

**Comment by limzykenneth** [comment]
You can use the native [`copyWithin`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/copyWithin) instead.

**Comment by Moosdijk** [comment]
thanks for your help!

I have also noticed that [shorten()](https://p5js.org/reference/#/p5/shorten) and [sort](https://p5js.org/reference/#/p5/sort) do have an alternative. Maybe it's worth updating the arrayCopy reference too.

**Comment by limzykenneth** [comment]
The alternative should have been listed but it's not rendered on page (it is in the inline reference). I'll reopen this issue to track that the reference should include suggestion for alternative.

**Comment by HeroicHitesh** [comment]
@limzykenneth I guess the alternative is not listed as you can see [here](https://github.com/processing/p5.js/blob/04cd6850a674335b3d5f759b039e0144a103a2fc/src/utilities/array_functions.js#L51) 
I am ready to work on this issue, let me know if I can start working on it.

**Comment by limzykenneth** [comment]
@HeroicHitesh Sorry for the late reply. Yes you can go ahead and add the alternative, you can just copy the one that is listed [here](https://github.com/processing/p5.js/blob/04cd6850a674335b3d5f759b039e0144a103a2fc/src/utilities/array_functions.js#L75). Thanks!
