### ISSUE TITLE
p5.Element.parent() should return p5.Element instance

### ISSUE THREAD

**Issue by dipamsen** [processing/p5.js#4797]
#### Most appropriate sub-area of p5.js?

- DOM

#### Feature enhancement details:

`p5.Element.prototype.child()` and `p5.Element.prototype.parent()` should return `p5.Element` instance instead of returning HTML DOM node so that `.show()`, `.hide()` and other `p5.Element` functions can be called.

Current: 
```javascript
let btn = select("button");
new p5.Element(btn.parent()).hide();
```
Suggested: 
```javascript
let btn = select("button");
btn.parent().hide();
```

We won't be losing any functionality as DOM node can be accessed through `btn.parent().elt`.

**Comment by limzykenneth** [comment]
This is technically a breaking change so I wouldn't recommend changing the implementation at this point.
