### ISSUE TITLE
PR Process

### ISSUE THREAD

**Issue by mcturner1995** [processing/p5.js#4801]
Hi Everyone,

My name is Moira and I am the new project lead for p5. As part of my role, I tend to the PRs of the p5 project and p5 website. However, I wanted to get some community input about the PR review process and empower you all to take more ownership of the process. Specifically, my questions are:
How many reviewers should take a look at a PR before it’s ready to merge?
Who should have access to merging the PR? Should the PR assignee be given access to merge?

I wanted to bring these questions up because I don’t want to create a bottleneck when it comes to the PR process. What do you all think?

**Comment by montoyamoraga** [comment]
hi @mcturner1995 :)
my guess is at least 1 person reviewing each PR,
i try to take care of the issues i know how to handle,
and sometimes ask for review of people who i know can take care of them

maybe we can formalize the process of knowing who can help with what,
we could ask the most active contributors on the repos to this section
https://github.com/processing/p5.js#stewards

**Comment by limzykenneth** [comment]
There was some discussion in #3893 and #4230 around this which led to the ideas of stewards that @montoyamoraga linked to. 

I think it is good to formalize stewards for different types of contributions to the repos (including the website) and these stewards, apart from being familiar with said area, will also be able to approve and merge the PRs for the most part. A steward will also be responsible for reviewing the changes and ask for additional changes if required.

However I also want to seperate out the PRs themselves in to maybe three categories: 
- simple fix: such as typos in documentation, these usually don't require an issue filed beforehand
- bug fix: an incorrect behaviour or behaviour that doesn't match with the documentation, these should have issues filed first
- new features: new features to the library, must have issue filed and a case for accesibility be made first before PR is filed

Of these categories, simple fix and bug fix can probably be reviewed and merged by one person (for simple fix anyone with push access, for bug fix the steward). For new features it should be agreed upon by more than one maintainer in the issues to include that feature before a PR is filed and PR approved by more than one maintainer before merging.

For assigning stewards, I think we can be relatively loose here, ie. multiple stewards for any one section and assigning the same person to a few areas.

**Comment by outofambit** [comment]
Hi @mcturner1995! Thanks for starting this conversation :)

@limzykenneth I love that breakdown of different types of PRs and the review requirements you proposed there. That sounds great to me. :)

> For assigning stewards, I think we can be relatively loose here, ie. multiple stewards for any one section and assigning the same person to a few areas.

Yeah (I think?) that was the initial intention for the stewards concept. (I've been slow to add myself there, but going to do that soon. @limzykenneth @montoyamoraga no pressure, but I think you'd be good candidates too!)

> Who should have access to merging the PR? Should the PR assignee be given access to merge?

I propose that we start with the reviewer merging the PR once it's all approved and see how that goes. I don't think it has to be a hard rule (especially if the PR author already has merge privileges), but maybe as a rule of thumb? This seems simpler than having the extra back and forth between the reviewer and the author, but also I can see the educational value of asking the author to merge the PR themselves. Perhaps we could say the reviewer is responsible for merging _or_ explicitly asking the author to do so?

**Comment by montoyamoraga** [comment]
hi @outofambit i just saw your PR request, it looks great to me, and yes i would love to be added as steward, i will do my own PR soon about it too, and i agree with the breakdown of @limzykenneth of PRs :)

in my case i try to merge PRs that i am comfortable with, and also close issues that are either stale or need no further discussion, and also i try to add people to the all-contributors list, and answer beginner doubts and direct people to the forum when it's applicable, i will think of a wording to summaerize my my steward role :)

**Comment by Qianqianye** [comment]
Hi @limzykenneth @outofambit @montoyamoraga. Shall we include the breakdown of different types of PRs and the review requirements @limzykenneth proposed to the [steward](https://github.com/processing/p5.js#stewards) description or somewhere in the Contributor Docs (https://github.com/processing/p5.js/tree/main/contributor_docs)? It'd be nice to have this info available outside of this issue.

**Comment by limzykenneth** [comment]
We can consolidate what we have here with what's already written [here](https://github.com/processing/p5.js/tree/main/contributor_docs#github-issue-flow) and [here](https://github.com/processing/p5.js/blob/main/contributor_docs/organization.md).

**Comment by montoyamoraga** [comment]
hi everyone, sounds great, i'm happy to help consolidate those so that it's more available yeah :)

**Comment by Qianqianye** [comment]
Thanks @montoyamoraga. I just assigned the issue to you. Please go ahead and start consolidating the info where you see fit. Thank you!

**Comment by montoyamoraga** [comment]
hi sorry i haven't done it and i won't be able to soon, so i unassigned

**Comment by Qianqianye** [comment]
@limzykenneth will lead the process of creating a steward guide as part of the Season of Docs 2022 project - [Organize and Develop p5.js Contributor Docs](https://github.com/processing/p5.js/wiki/Season-of-Docs-2022-Organization-Application---p5.js) 🎉. We will keep this issue open until the PR guide is up.

**Comment by limzykenneth** [comment]
A bit of an update: I've started writing the stewards guide in the contributor docs to include ideas generated here as well as any other info stewards and maintainers may need to know. The latest commit is below:

https://github.com/processing/p5.js/pull/5764/commits/7d70c3762dbc4b5b8acc694c9a0ba88ab193b5ac

Please feel free to leave comments about any part of the document while I'm still working on it.

**Comment by Qianqianye** [comment]
Thanks @limzykenneth for writing the [steward_guidelines.md](https://github.com/processing/p5.js/blob/main/contributor_docs/steward_guidelines.md), which outlines the [Pull Request](https://github.com/processing/p5.js/blob/main/contributor_docs/steward_guidelines.md#pull-requests) process for different use cases. I will close this issue for now for organizational purpose. Please feel free to reopen it if you'd like another round of discussion on this topic. Thank you!
