### ISSUE TITLE
P5 Rendering Bug in iOS Webkit (Black bars and sticky)

### ISSUE THREAD

**Issue by aspdev91** [processing/p5.js#4805]
Hi there!

I'm trying to render a video stream from iOS into P5 and ran into this issue where it seems like the video stream is rendered with a boxed, sticky styling. I attached a brief video below of how it looks. I tried to add the video into p.image(...) and nothing is displayed. You can see the video is stuck to the bottom when scrolling. 

https://youtu.be/LyqjIzqGy0Y

There's no css files or styling in my files and this is not a problem in desktop Chrome or Android. No console errors.

Also, when I feed the video stream into ML5, it throws <.01 probabilities meaning the images from the video stream may be inputted as seen in the feed with the black bars. I can provide a print of the video JS object if it helps.

I'm pulling the video using Cordova on iOS 13.7 with a plugin that enables media capture. I provided a link to it's github and also a small snippet they mentioned around HTML 5 video that I'm not sure it effects this. 

https://github.com/cordova-rtc/cordova-plugin-iosrtc

```
HTML5 video API
There is no real media source attached to the <video> element so some HTML5 video events and properties are artificially emitted/set by the plugin on behalf of the video element.

Methods such as play(), pause() are not implemented. In order to pause a video just set enabled = false on the associated MediaStreamTrack.
```

- [ ] Accessibility (Web Accessibility)
- [ ] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [x] Dom
- [ ] Events
- [x] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other (specify if possible)

#### Details about the bug:

- p5.js version: 1.1.9
- Web browser and version: WKWebView (it's a webkit browser used within a hybrid app Cordova)
- Operating System: iOS 13.7
- Steps to reproduce this:

**Comment by limzykenneth** [comment]
Hi @aspdev91 

Does this only happens in the Cordova based app or generally? It would be helpful if you can provide a minimal example that we can look at without having to setup a whole Cordova app. Thanks.

**Comment by aspdev91** [comment]
@limzykenneth  I did some further testing without P5 and it seems like this is quite specific to WKWebView. Thanks for helping. Closing this out.
