### ISSUE TITLE
Function to trigger keypress  if a certain condition is met.

### ISSUE THREAD

**Issue by yashkhasgiwala** [processing/p5.js#4806]
### How would this new feature help increase access to p5.js?
KeyPress trigger will enable automation and p5.js will have an event handler like the one in jQuery.

#### Most appropriate sub-area of p5.js?

- [x] Accessibility (Web Accessibility)
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [x] Events
- [ ] Image
- [x] IO
- [ ] Math
- [ ] Typography
- [x] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### New feature details:
 KeyCode to be passed as an argument to the function and that key press will be simulated.

**Comment by limzykenneth** [comment]
I don't think the accessibility requirement is met here as I don't see how automation and jQuery parity increase access. It is also not too hard to trigger a keypress function directly with Javascript:

```
document.dispatchEvent(new KeyboardEvent('keypress', {'key': 'h'}));
```

should trigger a `keypress` event as if the `h` key is pressed and will be picked up by p5.js and any other library.

**Comment by yashkhasgiwala** [comment]
@limzykenneth I tried this, it did not work.

**Comment by outofambit** [comment]
@yashkhasgiwala I agree with @limzykenneth, this would be a new feature and I don't see an angle for [increasing accessibility](https://github.com/processing/p5.js/blob/main/contributor_docs/access.md) here. Please post to the [p5.js forum](https://discourse.processing.org/c/p5js/) if you need help with simulating a key click manually.

Happy to revisit this if someone has an argument for how this would increase accessibility. Thanks!
