### ISSUE TITLE
Friendly error message for size 

### ISSUE THREAD

**Issue by joemckay5** [processing/p5.js#4807]
#### Nature of issue?
"Friendly" error message for mistakenly writing size() instead of createCanvas() is incomplete. 

- Found a bug (typo really). 

The error returns: 
"p5.js says: It seems that you may have accidently written size instead of line (bla bla bla)."

**Comment by akshay-99** [comment]
Hey @joemckay5 I don't seem to understand the problem here, in terms of what is incomplete or what is the typo. Can you please share the sketch that leads to the message?

**Comment by joemckay5** [comment]
Sorry for posting in the wrong forum catarak.  
The error message is missing the word "createCanvas".   So  it should read: 
It seems that you may have accidently written size instead of createCanvas on line() 
You can replicate the error by using size instead of createCanvas because you're old and your brain doesn't want to do new things. :)

**Comment by akshay-99** [comment]
@joemckay5 I now see that you were referencing the [size()](https://processing.org/reference/size_.html) function in Java Processing, which is somewhat of similar in use to `createCanvas()`. The friendly error system does not attempt to match things across the separate interpretations (Processing and p5). 
As of now, it simply looks in the p5 reference to find something similar in spelling. In this case, there is a function called "[line()](https://p5js.org/reference/#/p5/line)" which happens to be the closest match of the word "size()".

**Comment by limzykenneth** [comment]
@akshay-99 Is there a threhold in terms of similarity that we can tweak for this? Although `line()` is the closest in terms of spelling to `size()` I would say that should be over the threshold for what we should try and match to a specific function and it should just report as an undefined symbol.

**Comment by akshay-99** [comment]
@limzykenneth I agree. The threshold currently is 2 wrong characters. A threshold of 1 might be too small. It may be possible to account for the probabilities of misspelling a character (using keyboard layouts and stuff), which I am guessing is what more complex algorithms do. Or it the threshold could be variably set to 2 or 1/4 th of word length, whichever is smaller

**Comment by limzykenneth** [comment]
Keyboard layouts will probably be a bit unpractical as there are many types of keyboard layout and we can't be sure which the user is using. Basing it on word length could be something to consider.

**Comment by lmccart** [comment]
I think the functionality here is behaving correctly, and 2 wrong characters seems like a good balance for threshold. The message also makes it clear that there could be a number of other options to be used, so I think it leaves it in a good place for the user to follow up and double check that line. If it's ok with everyone, I will close this.
