### ISSUE TITLE
New p5 svg library, would like some testers

### ISSUE THREAD

**Issue by bobcgausa** [processing/p5.js#4809]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Dom
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [library ] Other (specify if possible)

#### Feature enhancement details: https://editor.p5js.org/Bobcook47/sketches/Dk3Osbx3z
Library and many test programs are available for testing before I submit a request to add to p5 library page.  Supports a number of features not found in p5.

**Comment by lmccart** [comment]
hey @bobcgausa these are issues are mostly for problems with the library or new feature requests. for more response and feedback on your library, I would suggest posting on our [forum](https://discourse.processing.org/)
