### ISSUE TITLE
video capture not working in chrome on android 4.2

### ISSUE THREAD

**Issue by eyaler** [processing/p5.js#481]
the dom video capture example is not working in latest chrome on android 4.2
i am getting only a single static image but no video.
these differentials work ok:
1. android 4.2 + firefox + http://p5js.org/learn/examples/Dom_Video_Capture.php
2. windows 7 + chrome + http://p5js.org/learn/examples/Dom_Video_Capture.php
3. android 4.2 + chrome + http://www.html5rocks.com/en/tutorials/getusermedia/intro/

so it seems my problem is only for the combination:
android 4.2 + chrome + http://p5js.org/learn/examples/Dom_Video_Capture.php

**Comment by lmccart** [comment]
according to caniuse.com, capture (getUserMedia is the underlying function) is not supported in chrome 4.2 for android: http://caniuse.com/#search=getusermedia.
