### ISSUE TITLE
I would like to add some new apis to the list in the wiki page named Loading external files: AJAX, XML, JSON. Please allow me the access to edit it.

### ISSUE THREAD

**Issue by pawki07** [processing/p5.js#4811]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Color
- [ ] Core/Environment/Rendering
- [x] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [x] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

**Comment by pawki07** [comment]
> 
> ### How would this new feature help increase access to p5.js?
> #### Most appropriate sub-area of p5.js?
> 
>     * [ ]  Accessibility (Web Accessibility)
> 
>     * [ ]  Color
> 
>     * [ ]  Core/Environment/Rendering
> 
>     * [x]  Data
> 
>     * [ ]  DOM
> 
>     * [ ]  Events
> 
>     * [ ]  Image
> 
>     * [ ]  IO
> 
>     * [ ]  Math
> 
>     * [ ]  Typography
> 
>     * [x]  Utilities
> 
>     * [ ]  WebGL
> 
>     * [ ]  Other (specify if possible)
> 
> 
> #### New feature details:

Th feature which I will add will add some more information to the above mentioned wiki page.

**Comment by limzykenneth** [comment]
Hi @pawki07, can you elaborate more on what exactly you are thinking of adding to the wiki?

**Comment by pawki07** [comment]
I would like to add some more APIs in the list.

**Comment by nakul-shahdadpuri** [comment]
@pawki07 The following [APIs](https://p5js.org/reference/#group-IO) already exist for loading JSON and XML files. Also for contributing to p5.js, you do not need explicit write access. You can try to fork the repo and make the changes there and then initiate a [pull request](https://opensource.com/article/19/7/create-pull-request-github). :)

**Comment by pawki07** [comment]
That's great. Thank you for your help.

**Comment by limzykenneth** [comment]
The wiki edit access do require permission and isn't editable via a PR. However I still need the exact intended changes you want to make before I can grant edit access.

**Comment by limzykenneth** [comment]
I'm closing this for now but feel free to respond to the above query and I can reopen the issue if still relevant.
