### ISSUE TITLE
createVector is not defined

### ISSUE THREAD

**Issue by tyrannny** [processing/p5.js#4815]
#### Most appropriate sub-area of p5.js?

- [x] Accessibility (Web Accessibility)
- [x] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [x] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [x] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### New feature details:
Hi, please add the feature to allow users to use the createVector function outside of setup(). It is very annoying to be always having to do it in setup(), it would be much easier if we could use it in another file, for example. If this feature was added/re-added, it would make my life, and probably many many others' lives much easier. Thank you.

**Comment by stalgiag** [comment]
Hi! I would [recommend reading this to learn more](https://github.com/processing/p5.js/wiki/p5.js-overview#why-cant-i-assign-variables-using-p5-functions-and-variables-before-setup) and then if your project requires access to p5 functions in the global space I would check out [on-demand global mode](https://github.com/processing/p5.js/wiki/p5.js-overview#why-cant-i-assign-variables-using-p5-functions-and-variables-before-setup).

I am closing this for organizational purposes.
