### ISSUE TITLE
Improved documentation for p5.Element style

### ISSUE THREAD

**Issue by dougjam** [processing/p5.js#4816]
-#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [x] Dom
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [x] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Feature enhancement details:

The documentation for p5.Element style is very light:
  https://p5js.org/reference/#/p5.Element/style

It would be helpful to list the options available, e.g., to set font properties, for new users, or provide better links.

**Comment by limzykenneth** [comment]
It isn't really practical to list the available options as `style` accepts any valid CSS property of which there are many and the ways to use each property are themselves varied as well, it will be like trying to document a whole programming language into this one function's reference.

**Comment by felipecustodio** [comment]
The third example is very intrusive and ends up getting in the way of reading and using the website.

![image](https://user-images.githubusercontent.com/4261743/103447502-e3619680-4c6a-11eb-949f-36b9da8628c2.png)

**Comment by limzykenneth** [comment]
Hi @felipecustodio, can you open a separate issue for that? Thanks!

**Comment by rt1301** [comment]
@limzykenneth  @felipecustodio  if the overflow of text issue on the Element example requires a fix, I would like to work on that.

**Comment by limzykenneth** [comment]
@rt1301 Please open a separate issue for that. Thanks.

Closing this issue for now as there are no further follow up to the original issue.
