### ISSUE TITLE
touchIsStarted? 

### ISSUE THREAD

**Issue by lmccart** [processing/p5.js#482]
we have `keyIsPressed` and `mouseIsPressed`, should there be something for touch?

`touchIsStarted`? `touchIsDown`?

**Comment by lmccart** [comment]
I think `touchIsDown` makes the most linguistic sense..

**Comment by karneaud** [comment]
is this variable updated automatically when touch has been started and ended? Or do i have to do this myself?

**Comment by lmccart** [comment]
it should be updated on both, touchIsDown should be true between the times of touch start and touch end, and false otherwise.

**Comment by karneaud** [comment]
I'm using the latest version of chrome for windows 7 with the mobile simulator and it doesn't seem to update

**Comment by lmccart** [comment]
closing this as it's duplicated and described in more detail here:
https://github.com/processing/p5.js/issues/587
