### ISSUE TITLE
Suggestion: provide shader for each p5js filter

### ISSUE THREAD

**Issue by dhowe** [processing/p5.js#4820]
Suggestion: make available the set of filters in p5js (currently THRESHOLD, GRAY, OPAQUE, INVERT, POSTERIZE, BLUR, ERODE, DILATE) as shaders (with the same names), so that users can more easily port sketches between default and WEBGL renderers. 

USE-CASE: Student has performance problems in sketch using filters. Instructor would like to suggest WEBGL, but the filter doesn't exist as a shader (or is not easily found).

Another option would be to have the filter call actually work in WEBGL by loading/invoking the correct shader automatically.

#### Most appropriate sub-area of p5.js?

- [x] Accessibility (Web Accessibility)
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Dom
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

**Comment by stalgiag** [comment]
Interesting idea! @aferriss has already done most (all?) of the hard work [for this in this repo.](https://github.com/aferriss/p5jsShaderExamples)

Typically, I would direct a student to this repo when I was suggesting this route. But perhaps it is worth the addition to library size (likely small) to have these as p5.Shader constants.

I think that performance is really important to consider right now and definitely falls under the umbrella of accessibility. Working with students through Zoom, I am painfully aware of the hard limits that students are hitting with performance. This is exacerbated by the fact that many students are using home computers for the first time when they have used school lab computers (which often have superior hardware) in the past.

For sketches that rely heavily on images with filters, the performance gains with WEBGL and shaders will be very significant.

**Comment by dhowe** [comment]
> Interesting idea! @aferriss has already done most (all?) of the hard work for this in this repo.

Exactly -- I think it would largely be a question of syncing up the names. And seems a good thing to do whether or not we want to have them invoked automatically when use the GL renderer.

**Comment by outofambit** [comment]
This sounds like a great idea to me! 💜

**Comment by JalokimFreelance** [comment]
Hey, I would like to help with that issue, would just the .vert and .frag files be enough? Or do I have to convert them somehow into Shader object?

**Comment by outofambit** [comment]
@JalokimFreelance i think that would be enough! i'm 90% sure we already have some build process for inlining shader files into the p5.js lib.

**Comment by JetStarBlues** [comment]
I spent some time looking at how this might work. What do you think of this approach [here][0]?

The shaders for each filter would be files that are handled the same way as other [core shaders][1].

The method `applyFilter(filterType, filterParam)` would be provided and it would behave the same as [`filter()`][2] in a 2D context.

(`applyFilter` could also just be called `filter`, and then the appropriate method called behind-the-scenes following a check of whether its a 2D or 3D sketch).

[0]: https://editor.p5js.org/acedean/sketches/g0RwIkBNX
[1]: https://github.com/processing/p5.js/tree/main/src/webgl/shaders
[2]: https://p5js.org/reference/#/p5/filter

**Comment by JetStarBlues** [comment]
@stalgiag What do you think?

**Comment by stalgiag** [comment]
Thanks for the draft @JetStarBlues !

I think using `filter` is a good idea. Your second implementation looks great to me but I am very curious whether `get()` is going to be a bottleneck. I am getting a low framerate on the example but it is unclear how much of this is caused by creating the shader in `applyFilter`. I think this is worth pursuing for now and we can see how performance shakes out once a draft PR is made.

**Comment by wong-justin** [comment]
Hey all, just a heads up that I'll be tackling this as part of my GSoC 2023 project in the coming weeks. I'll link to a PR when I make one. Looking forward to working on it!
