### ISSUE TITLE
DOM color picker not working on windows 10 chrome?

### ISSUE THREAD

**Issue by Picucu** [processing/p5.js#4830]
Hi! I was trying out the color picker DOM widget but the page just turns blank, anyone have any ideas why? I put the DOM library in the html and I tried with the pre made example code on the website too, but nothing seems to work. It does work normally in the web editor though. Any Ideas?

**Comment by limzykenneth** [comment]
Hi @Picucu, if you need help with your own code, please direct your questions to the [forum](https://discourse.processing.org). We use GitHub issues mainly for bug reports and feature requests only. Thanks!
