### ISSUE TITLE
Support for colour gradients

### ISSUE THREAD

**Issue by novachief101** [processing/p5.js#4833]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [x] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] Dom
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Feature enhancement details:
Before switching to p5js, I learnt the Canvas API (which, as far as I know, is what along with the WebGL API p5js is built on). With the Canvas API, you can create linear gradients that do not require you to draw lines/rectangles/triangles with different colours many times. Is there a p5js equivalent for this?

**Note:** I am really sorry if my English is bad, it isn't my first language.

**Comment by limzykenneth** [comment]
To me this sound like an interesting idea, however currently we have decided to only accept new features that increases access (you can read more [here](https://github.com/processing/p5.js/blob/main/contributor_docs/access.md)). Can perhaps a case for increased access be made here for this feature?

**Comment by novachief101** [comment]
I'm sorry I didn't read contributor docs, thanks for the reply.

**Comment by montoyamoraga** [comment]
thanks @novachief101 ! 
i will close this issue for now, thank you for your contribution
(and don't be sprry about your english, it's great :) )
