### ISSUE TITLE
What Is wrong with Create Sprite?

### ISSUE THREAD

**Issue by Vannman774** [processing/p5.js#4834]
If someone could let me know how I am to add a sprite to my canvas, that would be great! I am new to p5 and I could use some help.
               Thanks!

![image](https://user-images.githubusercontent.com/71670022/95109835-1e573b00-070b-11eb-8afd-462d158aafb6.png)

**Comment by surajsurajsuraj** [comment]
You can use semi-colon(;) or don't enter anything for ending the statement.
A comma after 'var tower' will give an error.

**Comment by limzykenneth** [comment]
Hi, you have a comma at the end of the first line after `var tower` which is causing the syntax error (it is expecting another variable name), remove that comma and it should run.

If you need futher help with your own code, please direct your questions to the [forum](https://discourse.processing.org). We use GitHub issues mainly for bug reports and feature requests only. Thanks!
