### ISSUE TITLE
Link to Luisa Pereira's 'Looking Inside p5.js' on Contributors Intro page results in 404

### ISSUE THREAD

**Issue by nsmarino** [processing/p5.js#4842]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Dom
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other (Contributor Docs)

#### Details about the bug:
Link to Luisa Pereira's 'Looking Inside p5.js' on the [Contributors Intro](https://p5js.org/contributor-docs/#/README) results in a 404 page. It appears the video series is no longer hosted on [luisapereira.net](https://www.luisapereira.net/teaching/looking-inside-p5/) -- perhaps this means it is out of date? The series, from 2016, seems to be available on [Vimeo](https://vimeo.com/156838703).

Page can be found in p5.js repo [here](https://github.com/processing/p5.js/blob/main/contributor_docs/README.md)

This is my first time opening an issue with p5.js so I welcome any feedback or advice.

**Comment by nsmarino** [comment]
The videos (2 in english and 2 in spanish) can be found at also be found in a different location on luisapereira.net [here](https://www.luisapereira.net/teaching/materials/processing-foundation). Perhaps we could update the readme to reflect this?

**Comment by limzykenneth** [comment]
@nsmarino Feel free to submit a PR with those links updated to where the tutorial is at now. Thanks.

**Comment by nsmarino** [comment]
Great, I will take care of this today.
