### ISSUE TITLE
Label is not clickable on Radio Buttons with createRadio()

### ISSUE THREAD

**Issue by dipamsen** [processing/p5.js#4854]
#### Most appropriate sub-area of p5.js?

- [x] Dom

#### Feature enhancement details:

In radiobutton made with `createRadio()`, when the label is clicked, the RadioButton doesn't get selected.

Current Functionality: 
```html
<input type="radio" value="value-of-option-1" name="radioOption">
<label>Label of Option 1</label>
<input type="radio" value="value-of-option-2" name="radioOption">
<label>Label of Option 2</label>
```

Enhancement: 
 Use unique ID for each `input` `type=radio`, and then use `for` attribute on `label` with that ID
```html
<input type="file" ... id="unique-id">
<label for="unique-id">Label of Option 1</label>
```

**Comment by devangmukherjee** [comment]
Hi, I would like to work on this issue.

**Comment by limzykenneth** [comment]
I would prefer for the relationship to be established with nesting like below:

```html
<label>Label of Option 1
  <input type="radio" value="value-of-option-1" name="radioOption">
</label>
```

To leave open the possibility of user assigned `id`.

**Comment by nakul-shahdadpuri** [comment]
Hi @limzykenneth @devangmukherjee , Is it okay if I try my hand at this ?

**Comment by limzykenneth** [comment]
I'm not sure whether to classify this as a breaking change or not. If it's a breaking change it will be harder to incorporate this change, if it is a bug fix(?) then adding then change won't be a problem.

**Comment by lmccart** [comment]
I would vote for a lenient interpretation here and say we could make this change, it seems to go along with the way buttons are normally handled, and I think this is best accessibility practices as well, so there's an access argument to be made.

**Comment by Prateek93a** [comment]
@lmccart @limzykenneth Shall I take it up?

**Comment by lmccart** [comment]
@Prateek93a yes if youd like to work on this please go for it
