### ISSUE TITLE
Animated mask for images OR let fill take an image as an argument

### ISSUE THREAD

**Issue by flomerboy** [processing/p5.js#4870]
### How would this new feature help increase access to p5.js?
I think it depends on the interpretation, but it seems like it would be very challenging to animate the mask of an image, so supporting this in a simple way would make that kind of creation more within reach. It's lowering the floor necessary to create this kind of behavior. I'm sure there are some very complicated ways to address this but I think most people will give up at this point.

#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [x] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### New feature details:
As far as I could tell, it's not possible to have an animated mask of an image. As a simple example, at first you can only see a little peep hole of an image, and the radius of that peep hole increases to reveal the whole image. If this was the only thing going on in a sketch, you could just draw a bunch of ellipses on top of the image, but if there's other stuff (e.g. a background) as far as I can tell it's not possible to animate a mask with the image.mask() method. Let me know if there's another way to do it.

**Comment by lmccart** [comment]
@flomerboy please take a look at our [access statement](https://github.com/processing/p5.js/blob/main/contributor_docs/access.md). right now the access explanation sounds very broad, I'm not quite sure how this feature would increase access for people who are excluded from the p5.js community. If it doesn't, I think we will table this idea in order to prioritize others that more urgently address access. Thanks for your understanding.

**Comment by flomerboy** [comment]
@lmccart thanks for linking me to that. The examples are very helpful. I don't think this applies then, it's probably not a "beginner" use case then so I don't think it counts. I eventually found a workaround with a less elegant but good enough approach to the animation and I imagine others could do the same. I think it's great that p5 is focusing on access.

**Comment by lmccart** [comment]
Thanks @nisarhassan12 for your understanding and support!
