### ISSUE TITLE
When pressing enter, the key value is set to empty string until enter is released

### ISSUE THREAD

**Issue by owenbmcc** [processing/p5.js#4871]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Dom
- [ x] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version: 1.1.9

In this [example](https://editor.p5js.org/owenroberts/sketches/g5LthBL4G), focus the canvas and then press the enter key, hold for a moment, and release.  The key value will be blank (empty string) until enter is released.

This is kind of minor but it came up with a student who couldn't figure out why their sketch wasn't working when using `if (key == 'Enter')`.

I checked and it looks like the the `_onkeydown` and `_onkeypress` functions set the `key` property differently.

[_onkeydown](https://github.com/processing/p5.js/blob/main/src/events/keyboard.js#L180):
`this._setProperty('key', e.key || String.fromCharCode(e.which) || e.which);`

[_onkeypress](https://github.com/processing/p5.js/blob/main/src/events/keyboard.js#L285)
`this._setProperty('key', String.fromCharCode(e.which));`

The problem is that `_onkeypress` fires after `_onkeydown` and the value `String.fromCharCode(e.which)` is empty string for the value 13 (the key code for Enter), so `key` is set to empty string until `_onkeyup` fires.

I could make a pull request that substitutes the line used by `_onkeydown` and `_onkeyup` for the one in `_onkeypress` but I wasn't sure if this was intentional.  I don't see anything in the documentation that suggests it is but want to check.

**Comment by limzykenneth** [comment]
Did you mean substituting the one for `_onkeypress` and `_onkeyup` for the one used in `_onkeydown`? If so I think it's an alright change and the form in `_onkeydown` seems to be the latest implemented in #2898 solving #2893.

**Comment by owenbmcc** [comment]
@limzykenneth I'm not sure but I think you may have swapped functions?

In #2898 it looks like both `_onkeydown` and `_onkeyup` were updated to use
`this._setProperty('key', event.key || String.fromCharCode(e.which) || e.which);` 
to set the `key` property.

`_onkeypress` was not changed, it uses 
`this._setProperty('key', String.fromCharCode(e.which));`.

My proposal is to update `_onkeypress` to use
`this._setProperty('key', event.key || String.fromCharCode(e.which) || e.which);` 

Hopefully that's more clear.

**Comment by limzykenneth** [comment]
Ah, I was looking at an older diff and didn't realize onkeyup has been updated as well. Yes I do mean to update them to `this._setProperty('key', event.key || String.fromCharCode(e.which) || e.which);` overall. You can go ahead with a PR.
