### ISSUE TITLE
Requesting font list

### ISSUE THREAD

**Issue by Davis9120** [processing/p5.js#4874]
### How would this new feature help [increase access](https://github.com/processing/p5.js/blob/main/contributor_docs/access.md) to p5.js?
I would be happy if it was easier to change fonts. I found it hard to find the path of .ttfs and .otfs.
Best if url to assets or list of .ttfs and .otfs were in the error popups.

#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [x ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ x] Typography
- [x ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

**Comment by limzykenneth** [comment]
I'm not 100% sure what you mean here but the file paths to file available or fonts installed on the system are both not something that can be accessed by the browser with any conventional means. In other words, there is no way for the p5.js sketch to know what the paths to any ttf or otf files you have as assets unless it is already provided as part of the sketch.

**Comment by Davis9120** [comment]
Thank you for the reply and sorry for the late response. I didn't get how to change the font of words to the Italic version of Comic Sans MS when I posted the request. At the time, I thought that font data were packaged somewhere in the p5.js, but that's not the case, am I right?

**Comment by Davis9120** [comment]
Finally got what I wanted. Thx a lot!(　＾▽＾)
