### ISSUE TITLE
noSmooth() doesn't turn off texture blurring in WEBGL mode

### ISSUE THREAD

**Issue by blechdavier** [processing/p5.js#4879]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version:  1.1.9
- Web browser and version:  was blocked by administrator but chrome
- Operating System:  macOS Mojave 10.14.6
- Steps to reproduce this:

Whenever you apply a low resolution texture to a p5.Geometry object in WEBGL mode, then the texture is blurred.  Normally, this wouldn't be an issue at all, but I'm trying to make a minecraft-like game, and noSmooth() has no effect on the textures, so the textures all look fuzzy instead of the nice, crisp edges that minecraft itself provides.  In P2D mode, however, calling noSmooth() and then image() will give you an image with those same crisp edges.  Is there a way to directly set the imageSmoothingEnabled property to false, or will I have to make a new, higher resolution texture of the same blocky texture?

**Comment by lmccart** [comment]
noSmooth() is the default rendering state in WEBGL mode, is it smooth() that you're actually looking for?

**Comment by aferriss** [comment]
Hi @blechdavier ! I believe what you're looking to accomplish is possible by disabling the bilinear texture interpolation in webGL mode. You should be able to set the texture interpolation by calling `setInterpolation(NEAREST, NEAREST)` on a webgl texture object. See below:

```javascript
let img = loadImage("someImage.jpg");
let canvas = loadCanvas(400, 400, WEBGL);
let tex = canvas.getTexture(img);
tex.setInterpolation(NEAREST, NEAREST);
```

Here is also a working example where you can click to see the difference between the two modes.
https://editor.p5js.org/aferriss/sketches/2X8aCFYqP

I don't think this function is included in the docs, so it's a bit hard to find information about it but if you dig into the source you should see some more examples of how this works.

https://github.com/processing/p5.js/blob/3f0b2f0fe575dc81c724474154f5b23a517b7233/test/manual-test-examples/webgl/texture/textureFilter/sketch.js

Here's the relevant code in p5 
https://github.com/processing/p5.js/blob/3f0b2f0fe575dc81c724474154f5b23a517b7233/src/webgl/p5.Texture.js#L256

Good luck!

**Comment by blechdavier** [comment]
THANK YOU @aferriss!!!!

**Comment by clankill3r** [comment]
This does not work for me with videos.
I have ` vid.hide();` and draw the video frames using the image function.
I can get a normal image to have the `noSmooth()` look, but the video is always using the LINEAR.
Any help would be welcome.

**Comment by vicdoval** [comment]
Hi @aferriss!
Do you know any trick to make this work with canvas created via createGraphics?
it returns that getTexture is not a function.
Also It would be great if It could be set to all textures at the same time, I have many (arrays with arrays of images) Any Idea?

**Comment by blechdavier** [comment]
Hey @vicdoval 
I’m not at a computer right now; there might be a property on the drawingContext

maybe try setting drawingContext.setInterpolation(NEAREST, NEAREST) and see where that gets you

**Comment by Zoda390** [comment]
@vicdoval
How did you go about changing LINEAR to NEAREST inside the p5.min.js?

**Comment by vicdoval** [comment]
I open p5.min.js in a text editor and searched for "LINEAR" and replace it for "NEAREST"  
Here you can see the main changes
![image](https://user-images.githubusercontent.com/10011941/216692900-b9bde02a-6aed-4957-9bbc-2ee57b4ec4df.png)

**Comment by Zoda390** [comment]
I got it. Thank you!
