### ISSUE TITLE
WEBGL Alpha Channel for Colors Produces Different Output Compared with Java Processing

### ISSUE THREAD

**Issue by stungeye** [processing/p5.js#4881]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [x] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version: v1.1.9 (Via the web editor)
- Web browser and version: Chrome 86.0.4240.111 and Firefox 82.0.2
- Operating System: Windows 10 (v2004 build 19041.572)
- Steps to reproduce this:

The following two versions of the same sketch produce different colours in p5js compared with Java Processing.

P5JS Version of Code: https://editor.p5js.org/stungeye/sketches/JHDo2t6LQ
Java Processing Version Code: https://gist.github.com/stungeye/ceaa2f243a905b0fdf8b24b613665a8b

![screen](https://user-images.githubusercontent.com/124968/97808365-1f0cbf80-1c2c-11eb-8fa4-bf1a65cc75a8.jpg)

P5js version on the left and Java Processing version on the right.

The issue is the notable color difference between versions for: `color(255, 0, 0, alpha); // alpha: 0 to 200`

p5js is rendering as WEBGL. Java p5 is rendering as P3D. Do they treat the fill color alpha channel differently? Are the lighting defaults different? Or is this a bug with p5js WEBGL?

I’ve tried forcing lighting to defaults by adding `lights()` in the draw loop of both sketches. After doing so the Java p5 output remains the same but p5js color looks even more dull.

When I use similar code within a 2D context p5js and Java p5 output looks identical. Here's a 2D sketch with the alpha channel of the `fill` for a `rect` changing with x location. p5js on the left and Java p5 on the right:

![colors2](https://user-images.githubusercontent.com/124968/97808607-8ecf7a00-1c2d-11eb-93c7-77c4eb5367aa.png)

**Comment by stalgiag** [comment]
Hi @stungeye cool sketch!

This is due to the fact that with WebGL the canvas itself is on top of another element (the document). We have experimented with different default behavior and this gets reported as a bug whenever we switch it. The problem is that some amount of blending with the background document is expected to be possible.

Long story short, you can get the same colors as Processing by adding `setAttributes('alpha', false)` to your sketch. 

The question always becomes which person should have to set this attribute, the person hoping to blend or the person that is expecting specific colors when migrating from Processing.

**Comment by stungeye** [comment]
I'm glad there's such a simple fix (which worked btw). 

Just so that I'm fully clear, is there a simple use case you could point to where you'd want document blending? I mean is it just the aesthetics of making a sketch "fit in" when embedded on a web page with something like a textured background? 

Also, is there a way to change the amount of blending with the document other than completely disabling the canvas alpha? I couldn't see any way to do this in the docs. 

I'd be happy to close this issue now, or you could close it as well if you wish.
