### ISSUE TITLE
Resizing Canvas not working when in scoped mode.

### ISSUE THREAD

**Issue by cursorweb** [processing/p5.js#4883]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version: v1.1.9
- Web browser and version: Edge (Chromium) 86.0.622.56
- Operating System: Windows 10.0.19041.572
- Steps to reproduce this:
```js
import * as P5 from './p5.js'; // imagine this works lol

function sketch(p)
{
  p.setup = () => p.createCanvas(p.windowWidth, p.windowHeight);
  p.windowResized = () => p.resizeCanvas(p.windowWidth, p.windowHeight);
}

new P5(sketch);
```

This was just taken from the examples but adapted with scoping.

**Comment by lmccart** [comment]
Hm I'm not able to reproduce this. Here's an example I used in the editor:
https://editor.p5js.org/lmccart/sketches/21W8FY-U4

Can you tell us what error or behavior you're seeing?

**Comment by cursorweb** [comment]
oh sorry, i just found out it was a mistake on my end, so sorry about this!
