### ISSUE TITLE
p5.js code fails to execute when pressing up, left and space together

### ISSUE THREAD

**Issue by JimSwift** [processing/p5.js#4884]
- p5.js version: v1.1.9
- Web browser and version: Chrome v86.0.4240.183
- Operating System: Windows 10 
- Steps to reproduce this:

Hi, I'm having a problem in which the code located in my `keyPressed()` function is failing to execute specifically when my square is travelling in a diagonal direction towards the top left of the screen. i.e while it's travelling negatively accross the X and Y axis. In all other directions it works fine, but for some reason it fails when I press space while both up and left keys are held down.

EDIT: might be an issue isolated to Windows. Seems to be working correctly on Mac

```
let squ = {
    x: 300,
    y: 300,
    size: 20
};

function keyPressed() {
    if (keyCode === 32) {
        console.log('space pressed');
    };    
};

function setup() {
    createCanvas(600,600);
    background(100);
    fill(255);
};

function draw() {
    rect(squ.x, squ.y, squ.size);


    if (keyIsDown(UP_ARROW)) {
        squ.y -= 1;
    };

    if (keyIsDown(LEFT_ARROW)) {
        squ.x -= 1;   
    };
};
```

**Comment by KKVANONYMOUS** [comment]
@JimSwift 
The code works perfectly fine on my side
Chrome: v86.0.4240.183
OS: Windows 10

Can you please elaborate your error?

**Comment by limzykenneth** [comment]
It could be a keyboard specific issue. Most keyboards have limits on how many keys can be pressed at once while still being recognized by the OS, although 3 keys is a bit too low for it to be practical so maybe it isn't that. You will have to do more tests including those outside of p5.js to determine where the problem lies.

**Comment by JimSwift** [comment]
oh right, wonder if this is isolated to my machine then which is a shame for me!

when I add all other directonal keys and test it works fine in every direction when I press space, so it can't be a limited number of key presses. It only seems to be a problem specifically with up+left+space. I've found that if I replace the space with an any other key it seems to correct the problem, so I can live with that as a workaround.

I do apologise if this has wasted any of your time.
