### ISSUE TITLE
[BUG] Instance mode - mousePressed fires when user clicks anywhere on document.

### ISSUE THREAD

**Issue by a-y-u-s-h** [processing/p5.js#4885]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [x] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

`mousePressed` fires when user clicks anywhere on the document/body in instance mode. 

- p5.js version: 1.1.9
- Web browser and version: 86.0.4240.111 (Official Build) (64-bit)
- Operating System: Arch Linux
- Steps to reproduce this:

Use P5 in instance mode, put the sketch in a div and you'll notice that the `mousePressed` function is fired when user clicks anywhere in the document/body, not just the canvas. It should be able to capture mousePressed event only on canvas in instance mode.

**Comment by limzykenneth** [comment]
I'm not sure that is the expectation. `mousePressed` from the documentation says "is called once after every time a mouse button is pressed." it does not imply where it should be pressed. If only mouse press inside the canvas should be captured, [`p5.Element.mousePressed()`](https://p5js.org/reference/#/p5.Element/mousePressed) should be used instead.

**Comment by a-y-u-s-h** [comment]
In a react application with multiple canvases and many buttons or controls, etc - this becomes extremely undesirable because mousePressed shouldn't leak outside of canvas. IMO `s.mousePressed` should be an event on the canvas and `p5.Element.mousePressed` for everything else associated with that canvas. In earlier versions this worked great.
