### ISSUE TITLE
Support for 2D shadows.

### ISSUE THREAD

**Issue by a-y-u-s-h** [processing/p5.js#4886]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### New feature details:

Canvas supports [2D shadows in all browsers](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/shadowBlur), as much as it supports fill color and stroke color. Like fill color or stroke color, it could be a part of P5 as well which could be defaulted to zero and maybe changed for different parts of the canvas with `createGraphics` or `push-pop` methods. This feature will result in a bit more power to the developer.

**Comment by blechdavier** [comment]
are there 3d shadows supported?

**Comment by limzykenneth** [comment]
Hi @a-y-u-s-h, we currently require any new feature requests to make the case for how the proposed new feature increases access of the project. You can read more [here](https://github.com/processing/p5.js/blob/main/contributor_docs/access.md). As it stands currently, I don't think this particular feature request has made the requirement. You can still make an argument for its inclusion if you can provide some info about how this feature increases access. Thanks!

**Comment by a-y-u-s-h** [comment]
Hi @limzykenneth. Honestly, I have no idea about how Web Accessibility works with canvas. I just thought that screen readers read DOM node attributes until now (half knowledge) and canvas being an image getting rendered again and again it must be something different. So all I can say is that yeah it's just a feature suggestion - because to me this feature feels not any different from already implemented `fill` or `stroke` functions. It just enables more power and maybe more interesting possible sketches. You'll have a much better idea whether this is an accessible feature or not. 

@blechdavier WebGL shadows are also a thing yes, but I'm not sure whether p5 supports it. Last time I used p5 it was 3-4 years ago and 3D support was at its infancy back then, and since then things have changed a lot so I'm experimenting things out as well.

**Comment by limzykenneth** [comment]
Accessibility in our case is not limited to the Web Accessibility API but rather a broader and self-reflective understanding of what accessibility means. It is not entirely your responsibility to come up with an accessibility argument for this feature so don't worry if you can't think of something, maybe this feature resonate with someone else in terms of giving them more access to the project and coding in general and they can chime in with their opinion.

I'll keep this issue open for the time being for additional comments but may close it further down the line for organizational purpose. 😃

**Comment by lmccart** [comment]
I'm not seeing a lot of interest in this feature, and we don't have a clear explanation of how it [expands access](https://github.com/processing/p5.js/blob/main/contributor_docs/access.md), so I will close this for now. If an access statement can be added to the issue request, please feel welcome to reopen.
