### ISSUE TITLE
"Save Image As" is actually just "Save Image"

### ISSUE THREAD

**Issue by hatcatpat** [processing/p5.js#4889]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [X] DOM
- [ ] Events
- [ ] Friendly error system
- [X] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [X] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

In most websites, right clicking an image and selecting "Save Image As" will open up a dialog that allows you to specify the name and location of the file you are about to save. Whereas selecting "Save Image" should just save the image in your downloads folder with the default file name.

However, right clicking a p5js canvas and selecting "Save Image As" will just save the image as "download.png" in your downloads folder. This is a little inconvenient for organising files.

Using the "saveCanvas" function also does not open a dialog. 

- p5.js version: p5.js v1.1.9 July 22, 2020 
- Web browser and version: Chromium | 86.0.4240.183 (Official Build) snap (64-bit) 
- Operating System: Linux, Ubuntu 20.04.1 LTS  
- Steps to reproduce this: Right click the p5js canvas, select "Save Image As"

**Comment by doxanthropos** [comment]
Just to help with testing this:
(Tested on Windows 10 with current browser versions)
Chrome behaves as described in this issue, but it does so for all canvas elements, not only p5.
Firefox "Save Image As" works as expected for images and canvas elements alike.
So it looks like this is a bug in Chrome and therefore Chromium.

**Comment by hatcatpat** [comment]
Oh yep you are right, it works perfectly in Firefox and the bug exists
Chrome for all canvas elements.

**Comment by hatcatpat** [comment]
It's a bug in Chrome with saving any canvas element. Works in Firefox

**Comment by doxanthropos** [comment]
It's already a [reported as a bug in chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=1113770&q=save%20image%20as%20canvas&can=2).
