### ISSUE TITLE
WebGL TEXT - overdraws lines or missing pixels

### ISSUE THREAD

**Issue by GeorgeSikora** [processing/p5.js#4893]
#### Most appropriate sub-area of p5.js?
- [x] WebGL
- Text
- Font

#### Details about the bug:

- p5.js version: v0.10.2 October 14, 2019
- Web browser and version: Google Chrome | 86.0.4240.183
- Operating System: Windows 10
- Steps to reproduce this: I tried lot of fonts, and with every font, there were the dead pixels and some lines when i want to display some text.

There is some code, where i was displaying some text, i tried in every size, it making same thing
>  text('connected: '+socket.connected+'\nping: ' + multiplayer.ping + 'ms\nFPS: ' + fps + '\nkills: ' + player.kills + '\nx: ' + Math.round(player.pos.x) + ' y: ' + Math.round(player.pos.y) + "\nPlayers online: " + (players.length+1) + "\nObjects: " + objects.length, 5, 5);

![image](https://user-images.githubusercontent.com/32364540/98682411-2dfa1d00-2364-11eb-8a7d-e365f5d6b473.png)

**Comment by stalgiag** [comment]
Unable to recreate [with this sketch](https://editor.p5js.org/stalgiag/sketches/SCUAEUIbc) in the latest Chrome or Firefox on Mac using either p5 v0.10.2 or 1.1.9.

Could be a problem with your font files or it could be a Windows-specific problem.

Are you able to recreate with the font file used in the linked example?

**Comment by TraXIcoN** [comment]
I am also not able to reproduce this issue!

**Comment by lmccart** [comment]
we're not able to reproduce this but please feel free to reopen if you can provide a code sample that demonstrates the issue. thanks!
