### ISSUE TITLE
Update dom to ES6 implementation 

### ISSUE THREAD

**Issue by BharathKumarRavichandran** [processing/p5.js#4895]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [x] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Feature enhancement details:
Some of the functions in the [DOM](https://github.com/processing/p5.js/blob/main/src/dom/dom.js) module is still using the ES5 syntax. I think some of the changes are made after #3874. Since the project is being updated to ES6 syntax, I think it's best we update the implementations here also. The todo here is mostly changing `var` to `let` or `const` in [src/dom/dom.js](https://github.com/processing/p5.js/blob/main/src/dom/dom.js). I would like to work on this, any heads up?

**Comment by limzykenneth** [comment]
@BharathKumarRavichandran I think you can go ahead with the changes and file a PR. Do note the convention of not using bracket syntax for object member functions. Thanks.
