### ISSUE TITLE
WEBGL transparency not working with DEPTH_FUNC, making layer system for game

### ISSUE THREAD

**Issue by GeorgeSikora** [processing/p5.js#4902]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [x] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [x] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [x] WebGL

#### Details about the bug:

- p5.js version: v0.10.2 October 14, 2019 and v1.1.9 July 22, 2020 (in example code below)
- Web browser and version: Google Chrome 86.0.4240.198 64bit
- Operating System: Windows 10 OS Version 2004 (Build 19041.630)
- Steps to reproduce this:

I made some test code for this situation, its becouse i render flag as last image, and i want to get the player and knife over this flag, but transparency of the player and knife not working and hides the flag. As in the image below. Is there any way to fix it? I want to make layers in my game by z-axis, bigger Z, the image will be more in the front, in topper layer. In classic Processing i was making layer system like hint(ENABLE_DEPTH_SORT).

#### index.html
```
<html>
<head>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.1.9/p5.min.js"></script>
    <script src="script.js"></script>
    <style>body{margin:0;padding:0;background-color: rgb(19,19,19);}</style>
</head>
<body>
</body>
</html>
```

#### script.js
```
// images variables
var img_knife, img_player, img_flag;
function setup(){
    // setup canvas
    createCanvas(600, 600, WEBGL);
    // setup gl to depth render
    var gl = document.getElementById('defaultCanvas0').getContext('webgl');
    gl.getParameter(gl.DEPTH_FUNC);
    // load images
    img_knife = loadImage('https://i.ibb.co/wpJ1HNn/knife.png');
    img_player = loadImage('https://i.ibb.co/xYmSs5t/player.png');
    img_flag = loadImage('https://i.ibb.co/t2n6n9f/flag.png');
}
function draw(){
    background(19);
    // Draw player image
    push();
    translate(30,20,10);
    tint(255,255,0)
    image(img_player, 0, 0);
    pop();
    // Draw knife image
    push();
    translate(120,95,15);
    rotate(PI)
    image(img_knife, 0, 0);
    pop();
    // Draw flag image
    push();
    translate(0,0,0);
    image(img_flag, 0, 0);
    pop();
}
```

![image](https://user-images.githubusercontent.com/32364540/99425418-17733900-2903-11eb-8f74-24a2c279afe0.png)

**Comment by aferriss** [comment]
Hi @GeorgeSikora 

I believe you're running into a classic problem with depth and transparency that doesn't really have to do with p5. In order to fix your issue, I think all you need to do is draw your elements in order from furthest to nearest. I don't think you need to use the z value in your translations either. Here's an example for you to look at.

https://editor.p5js.org/aferriss/sketches/rS8zVy7df

I'm going to close this issue for now but if you feel that there's still a bug happening feel free to reopen.

Good luck!
