### ISSUE TITLE
CreateSprite and DrawSprite is not working 

### ISSUE THREAD

**Issue by Diggingwings** [processing/p5.js#4903]
<--
Hi there!

When I'm trying to use create sprite or drawSprites, it says undefined and it says this on anything I use.
-->

#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [x ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [] Other (specify if possible)

#### Details about the bug:

- p5.js version: <-- 1.1.9 -->
- Web browser and version: 
- Operating System: <--  Windows-->
- Steps to reproduce this:
![image](https://user-images.githubusercontent.com/73551312/99545568-2269b000-297b-11eb-9f1d-b5e280a0e743.png)

**Comment by limzykenneth** [comment]
`createSprite` and `drawSprite` are functions specific to [p5.play](https://molleindustria.github.io/p5.play/) so make sure that you have included p5.play as an addon library in your html file. If you are still having problem, you should raise this issue with p5.play directly [here](https://github.com/molleindustria/p5.play/issues) as we do not maintain addon libraries such as p5.play directly. Thanks!

**Comment by Rishu1127** [comment]
In my code createSprite is not defined either. I have used p5.play.js but it is still not working.
