### ISSUE TITLE
p5.js Documentation: HTML element not escaped properly

### ISSUE THREAD

**Issue by Vbbab** [processing/p5.js#4905]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other: **Documentation rendering issue**

#### Details about the bug:

- p5.js version: *N/A* (refers to documentation)
- Web browser and version: *N/A*
- Operating System: *N/A*

In [p5.js line 1006](https://github.com/processing/p5.js/blob/b15ca7c7ac8ba95ccb0123cf74fc163040090e1b/src/dom/dom.js#L1006), documentation for `createInput()` has an `<input>` tag which is escaped; however, in the actual [documentation](https://p5js.org/reference/#/p5/createInput), it is not:

![image](https://user-images.githubusercontent.com/44555590/99476475-79cd3900-2905-11eb-9354-29b071cf2e1c.png)

Any ideas why this might happen? Or is the JSDoc not used for the actual page (in which case, is there another repo for the page)?

**Comment by limzykenneth** [comment]
This has been fixed in #4764 but the reference will not be updated until a new version is released so the fix will go live when the next version is released.

**Comment by Vbbab** [comment]
OK, thanks for letting me know! Sent from Mail for Windows 10 From: Kenneth LimSent: Wednesday, November 18, 2020 12:33 PMTo: processing/p5.jsCc: Vbbab; AuthorSubject: Re: [processing/p5.js] p5.js Documentation: HTML element not escaped properly (#4905) This has been fixed in #4764 but the reference will not be updated until a new version is released so the fix will go live when the next version is released.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Vbbab** [comment]
OK, thanks for letting me know!
