### ISSUE TITLE
"this.elt.srcObject is null" error when removing a MediaElement (video)

### ISSUE THREAD

**Issue by 01010101** [processing/p5.js#4908]
- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [X] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version: 1.1.9
- Web browser and version: Firefox 83.0 (64-bit)
- Operating System: Linux / Ubuntu

- Also reproduced on Chrome 86.0.4240.198 / Windows 10 Pro

- Steps to reproduce this:
Add a video element and later try to remove it.
The remove() method throws an error and doesn't proceed.
Error message : "this.elt.srcObject is null"

- Code snippet:

```
let vid;

function setup() {
  noCanvas();

  vid = createVideo(
    ['video.webm', 'video.mov'],
    vidLoad
  );  

  vid.size(100, 100);
}

function vidLoad() {
    vid.loop();
    setTimeout(function() {
        vid.remove();
    }, 1000)
}
```

I solved the issue with this code but I'm not sure it won't have side-effects on other types of MediaElement 
```

          * Removes the element, stops all media streams, and deregisters all listeners.
           * @method remove
           * @example
           * <div class='norender'><code>
           * let myDiv = createDiv('this is some text');
           * myDiv.remove();
           * </code></div>
           */
          _main.default.Element.prototype.remove = function() {
            // stop all audios/videos and detach all devices like microphone/camera etc
            // used as input/output for audios/videos.
            if (this instanceof _main.default.MediaElement) {
                this.stop(); // Stop the MediaElement
                var sources = this.elt.srcObject;
                if (undefined != sources) { // Only proceed if sources is not null
                    var tracks = sources.getTracks();
                    tracks.forEach(function(track) {
                        track.stop();
                    });
                }
            }
```

**Comment by limzykenneth** [comment]
I think the fixes you proposed should work without issue but better to test it. If you want to file a PR, you can go ahead, I'll be able to test a fix easier when a PR is in place. One change to your fix however is to change `if (undefined != sources)` to `if (sources !== null)` to compare directly against `null`.

**Comment by KKVANONYMOUS** [comment]
@limzykenneth If this issue is open, I would like to work on it

**Comment by limzykenneth** [comment]
@KKVANONYMOUS Sure, go ahead. I'll assign the issue to you.
