### ISSUE TITLE
Auto-refresh and loops

### ISSUE THREAD

**Issue by lwlsn** [processing/p5.js#4909]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [x] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### New feature details:

Similar to issue #3702.. When auto-refresh is on and starting to write a while loop, as the condition is not yet specified, runs into an infinite loop and crashes. Is there a way to over-ride the auto refresh until the complete loop statement is written?

**Comment by limzykenneth** [comment]
Hi @lwlsn, you should follow [this issue](https://github.com/processing/p5.js-web-editor/issues/698) over on the web editor's repo, we don't maintain the web editor here (this repo only contains the p5.js source code) and you should follow up with the maintainers of the web editor. Thanks.

I'm closing this issue for now.
