### ISSUE TITLE
In the web editor if I press the backspace key 2 the name 

### ISSUE THREAD

**Issue by iKittyCode** [processing/p5.js#4910]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other (specify if possible)

#### Details about the bug:

- p5.js version: 
- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

**Comment by iKittyCode** [comment]
When I press the backspace key in the web editor then it backspaces the whole project

**Comment by outofambit** [comment]
hi @iKittyCode could you share more about what you mean by "backspaces the whole project?" is something getting deleted? thank you!

**Comment by iKittyCode** [comment]
It starts delting every thing in the project line by line

**Comment by outofambit** [comment]
@iKittyCode gotcha, thanks. I'm going to transfer this issue to the repo for the p5.js web editor since this is specific to that project. If you can attach a GIF of this bug happening and add your browser and operating system versions to this issue that would be very helpful for them! thank you!

**Comment by outofambit** [comment]
@iKittyCode unfortunately it looks like i don't have the right permissions to transfer the issue. could you please file a new bug at https://github.com/processing/p5.js-web-editor/issues/new? sorry about that!
