### ISSUE TITLE
Where are the assets in the Examples?

### ISSUE THREAD

**Issue by lonce** [processing/p5.js#4911]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x ] Other (specify if possible)

#### Details about the bug:
This is just a documentation bug. 

The example(s) for webgl (https://p5js.org/examples/3d-shader-using-webcam.html)  include assets - but without access to those assets, we can't copy the code to our own p5.js Editor to run the code.

Thank you,

**Comment by limzykenneth** [comment]
The assets are stored [here](https://p5js.org/assets/examples/assets/) on the website. The structure is a bit weird because of how the example pages work.

**Comment by YoriKv** [comment]
Please re-open this issue. As someone learning P5 JS for the first time I had to find **this issue** to figure out where the assets were. Each example page should link to the relevant assets or at the very least link to the assets directory.

**Comment by limzykenneth** [comment]
This issue was specifically asking for the location of the example assets, if there is suggestion of how we can better handle example assets please do open a new issue. Issues are kind of like to-do list for us to we couldn't keep an issue open for just documentation purpose. Thanks!
