### ISSUE TITLE
Radio Buttons are not aligned properly in the second example of createRadio() reference

### ISSUE THREAD

**Issue by KKVANONYMOUS** [processing/p5.js#4912]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [X] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- Web browser and version: Chrome
- Operating System: Windows
- Steps to reproduce this:
 Visit [https://p5js.org/reference/#/p5/createRadio](https://p5js.org/reference/#/p5/createRadio) and see the alignment of radio buttons in the second example.

  **Here is the snap of the bug:**

![Screenshot (67)_LI](https://user-images.githubusercontent.com/58628586/99896778-c758f580-2cb9-11eb-872c-28650f0dcc10.jpg)

  **I feel that the radio buttons should be aligned horizontally, like this:**

![Screenshot (68)_LI](https://user-images.githubusercontent.com/58628586/99896785-d8096b80-2cb9-11eb-9fda-d06eb01cf290.jpg)

 **I would like to work on this issue.**

**Comment by BazTheLinuxGuy** [comment]
Unsubscribe

**Comment by KKVANONYMOUS** [comment]
Hi ,@limzykenneth Please see that if this issue is legible or not.
If yes, then please assign it to me

**Comment by limzykenneth** [comment]
I'd actually prefer the radio buttons to be vertical instead of horizontal if that is possible.

**Comment by KKVANONYMOUS** [comment]
> I'd actually prefer the radio buttons to be vertical instead of horizontal if that is possible.

Yup, that's a good idea. I will work on it
