### ISSUE TITLE
Pupeeter causing blocking issue during running grunt 

### ISSUE THREAD

**Issue by R4ph3rd** [processing/p5.js#4913]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [x] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version: 1.1.9
- Operating System: Fedora 32
- Steps to reproduce this:
Follow the instruction given here : https://p5js.org/contributor-docs/#/?id=development-process to install your project. When running ``npm run grunt`` you might see an error due to the ``puppeeter`` package. An unhandled promise chain which can cause troubles, maybe differents according to your nodejs version.
The issue for the package has been notified here : https://github.com/puppeteer/puppeteer/issues/2746. As I can see, this error has been removed since 2018, so I suppose that p5js import a old and deprecated package of puppeeter
It seems to be a blocking error for some users (https://discourse.processing.org/t/fatal-error-protocol-error-runtime-callfunctionon-object-reference-chain-is-too-long/25591) but not for me, because I do not have the latest version of nodejs.

**Comment by limzykenneth** [comment]
The pupeteer version used in this repo is pretty only indeed. Will need some time to test upgrading to the latest version doesn't break anything though.

**Comment by fal-works** [comment]
If this might help anyone else:
I had the same "Object reference chain is too long" error even though puppeteer is the latest (v5.5.0).
And after switching my Node.js to the LTS version (v15.5.1 -> v14.15.4) the test task completes successfully.

**Comment by limzykenneth** [comment]
There's a regression on this issue on node.js 16.x and npm 7.x, documented in #5367
