### ISSUE TITLE
Adding hindi translation of files in contributor docs

### ISSUE THREAD

**Issue by covalentbond** [processing/p5.js#4921]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [x] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Feature enhancement details:

I will be translating 
- contributing_documentation.md
- benchmarking.md
- discussions.md
- preparing_a_pull_request.md
- design_principles.md

**I would like to work upon this**

**Comment by covalentbond** [comment]
@KKVANONYMOUS @BharathKumarRavichandran guys I saw you contributing recently, would you like to assist me by completing the files which will be left out afterwards. I mentioned the files which I will be translating

**Comment by BharathKumarRavichandran** [comment]
> @KKVANONYMOUS @BharathKumarRavichandran guys I saw you contributing recently, would you like to assist me by completing the files which will be left out afterwards. I mentioned the files which I will be translating

Hey @covalentbond, I'm not familiar with Hindi, so I don't think I would be of much in this issue. But I would like to pitch in if there's any other work.

**Comment by KKVANONYMOUS** [comment]
> @KKVANONYMOUS @BharathKumarRavichandran guys I saw you contributing recently, would you like to assist me by completing the files which will be left out afterwards. I mentioned the files which I will be translating

@covalentbond Ya sure!! Please do let me know if you require any help.

**Comment by covalentbond** [comment]
@KKVANONYMOUS you may look into https://github.com/processing/p5.js/tree/main/contributor_docs and add those which are left out in this https://github.com/processing/p5.js/tree/main/contributor_docs/hi
