### ISSUE TITLE
docs seem wrong about textFont return type

### ISSUE THREAD

**Issue by seldomU** [processing/p5.js#4926]
The documentation page on textFont() gives the impression that the method returns the current font object. This seems to only work when a font has been loaded before. When working with the default font, `textFont()` returns a string, the font name. When called with a name as argument, e.g. `textFont("sans-serif")`, it returns the p5 object.

Is it at all possible to get a font object for the default fonts? I'd like to run textToPoints on them.

**Comment by dhowe** [comment]
The way textToPoints works (if I remember correctly) is that it uses the glyph data within a .ttf or .otf font. So if there is no font loaded (by the user) there is no glyph data to be accessed. 

To provide this functionality in the future we'd need to bundle a freely-usable .ttf or .otf font, for which there is some cost in the size of the package. But if we can find a small-enough font (or create one that includes only the basic characters for the locale) it might make sense to do.

**Comment by seldomU** [comment]
Thank you. I figured as much after looking at the source.

**Comment by lmccart** [comment]
Sorry, I accidentally closed this. Since this is a feature request, it would be helpful to have an answer to the PR template that asks: How would this new feature help [increase access](https://github.com/processing/p5.js/blob/main/contributor_docs/access.md) to p5.js?

**Comment by seldomU** [comment]
The documentation for `textFont()`'s return value doesn't mention two cases:

1. no font file has been loaded -- the current font name is returned as a string
2. the argument is a font name, like "sans-serif" -- the P5 object(!) is returned

As I user, I'd have wanted to know that.

**Comment by lmccart** [comment]
Ah ok, so this is more of a missing documentation bug. Thanks for clarifying!
