### ISSUE TITLE
Loading... issue when open p5 project

### ISSUE THREAD

**Issue by EnginKARATAS** [processing/p5.js#4927]
Hi 

For explain this issue I want to show a example.

When I download and open 

#CodingTrain/Flappy-Bird-Clone/index.html

that shows me only a text and this text is "Loading..."

I taken this issue several time, different times.
  
 
 
<img width="475" alt="Screenshot_4" src="https://user-images.githubusercontent.com/43602725/100681908-dad52200-3385-11eb-9e31-9d5775089faf.png">

- [x] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

**Comment by limzykenneth** [comment]
Are you running the sketch over a local web server? Have a look at [this page](https://github.com/processing/p5.js/wiki/Local-server) to see how to set one up. You will need the local server in order for the image assets to load in.

**Comment by EnginKARATAS** [comment]
@limzykenneth Thank you! This worked and solved my problem clearly
