### ISSUE TITLE
draw() problem

### ISSUE THREAD

**Issue by theodgr** [processing/p5.js#4928]
- [x] Events

- p5.js version: /*! p5.js v1.1.9 July 22, 2020 */
- Web browser and version:  87.0.4280.66 (Επίσημη έκδοση) (64-bit)
- Operating System: <!-- Ex: Windows10

the code
```js
function setup() {
createCanvas(300,500); 
//background(200);                  
}
function mouseDragged(){            
noStroke();                         
fill(255,0,0);
ellipse(mouseX,mouseY,20,20);       
}                                   
function draw() { 
  //background(200);                
line (0,0,mouseX,mouseY);  
}
```

**Comment by limzykenneth** [comment]
Hi @theodgr, can you explain what the problem you encountered is? Would be helpful to know what is the expected behaviour and what is the actual behaviour. Thanks.

**Comment by theodgr** [comment]
Hello @limzykenneth. During the development of a project I encountered a problem. I started removing pieces of code until I found it below and for that I sent a small piece of code. The draw is a loop. is running continuously. So very correctly when the scketch opens we see lines being created on the screen following the mouse. if we press the mouse very correctly we will see a drawing on the screen. However, after this event where the draw should be performed, we do not see lines being added to the screen. The program of course runs through the draw but the appearance on the screen of the line does not continue to appear or create it as it should.

**Comment by MysteryBlokHed** [comment]
It looks like the `noStroke()` being called in `mouseDragged()` makes the line invisible, since lines use stroke. Calling `stroke()` before the line is drawn should do the trick:
```js
function setup() {
createCanvas(300,500); 
//background(200);                  
}
function mouseDragged(){            
noStroke();                         
fill(255,0,0);
ellipse(mouseX,mouseY,20,20);       
}                                   
function draw() { 
  //background(200);                
stroke(0); // Re-enables strokes after noStroke was called
line (0,0,mouseX,mouseY);  
}
```

**Comment by theodgr** [comment]
I feel a little stupid now, :)) 
but is it possible you want to make a line with nostroke ?? 
thank you very much for your time.
