### ISSUE TITLE
Giving Errors when .play() is called

### ISSUE THREAD

**Issue by OutdatedGuy** [processing/p5.js#4933]
![Screenshot 2020-12-04 165149](https://user-images.githubusercontent.com/74326345/101157999-07708e80-3651-11eb-897c-05dfe8abbc81.png)
- p5.js version: v1.1.9 July 22, 2020
- p5.sound.js version: Version: 0.3.12 - 2020-01-06
- Web browser and version: In all web browsers(chrome, firefox and edge atleast)
- Operating System: Windows 10 Home Single Language
- Steps to reproduce this:
Use .play() in the sketch.js and access developer tools to see the error

**Comment by limzykenneth** [comment]
Hi @OutdatedGuy, can you share a minimal sketch code that demonstrates the problem? Thanks.

**Comment by OutdatedGuy** [comment]
> Hi @OutdatedGuy, can you share a minimal sketch code that demonstrates the problem? Thanks.

Hi @limzykenneth, Thanks for Replying.

The problem is that the code is running and the sound is also playing, but in the console of any browser it shows the error msg (image in the issue).

If you all the code details, it's uploaded [here](https://github.com/OutdatedGuy/Multiplayer-Snake)

For the part of code it gets error:

eat() {
		for(var f = 0; f < FoodX.length; f++) {
			if (this.x == FoodX[f] && this.y == FoodY[f]) {
				eatSound.play();
				mySnake[myLambi] = new SnakeBody(mySnake[myLambi - 1].x, mySnake[myLambi - 1].y);
				myLambi++;
				foodLocation(f);
			}
		}
	}

**Comment by limzykenneth** [comment]
Had a look into this and found that it has already been fixed in https://github.com/processing/p5.js-sound/pull/542. The fix will be available in the next release. As far as I can tell the error is not blocking so you can ignore the error for now and code as usual.

**Comment by OutdatedGuy** [comment]
Okay, Thanks for the Info and Help! 😊
