### ISSUE TITLE
erase() does not erase to background color

### ISSUE THREAD

**Issue by gvrancken** [processing/p5.js#4937]
If I paste the first example into the web editor, it looks different: the erase also erases the background.
Example: https://editor.p5js.org/vrancken.gilbert/sketches/Gw0mO070m

**Comment by limzykenneth** [comment]
For me the reference example matches the link you shared? Are you seeing or expecting a different behaviour?

`erase()` does not erase to the background but rather erases everything on the canvas, including background, effectively turning the pixels transparent.

**Comment by gvrancken** [comment]
Ah I see, I see a black circle, because I have dark mode on, so it erases to the dark browser color.
