### ISSUE TITLE
Images disappear for one frame

### ISSUE THREAD

**Issue by LsHallo** [processing/p5.js#4938]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version: `p5.js v1.1.9 July 22, 2020`
- Web browser and version: 87.0.4280.88 (Official Build) (64-Bit) (cohort: 87_88_Win)
- Operating System: Windows 10 2004
- Steps to reproduce this:
I have attached a zip of my sketch and main file. I'm rendering snow using 3 images. I've noticed that some flakes seem to flicker and have exported some frames to investigate more closely.
I've noticed that some flakes are missing in some frames which leads to the flicker. But I can't imagine why that would be the case.
Here are 3 consecutive frames:
![A_framesStacked](https://user-images.githubusercontent.com/22171518/101382822-afd45c00-38b8-11eb-9894-f709366d5ff9.png)
(Image shows 3 frames stacked each colored differently to show differences. Circled flakes are missing the blue colored frame in the middle.)

The three frames separate:
![canvasSnowFrame8405](https://user-images.githubusercontent.com/22171518/101381679-5586cb80-38b7-11eb-9013-c95d40133164.png)
![canvasSnowFrame8406](https://user-images.githubusercontent.com/22171518/101381703-5cadd980-38b7-11eb-9c3f-05a3020ef25e.png)
![canvasSnowFrame8407](https://user-images.githubusercontent.com/22171518/101381750-6c2d2280-38b7-11eb-98e7-b84c40048cdd.png)

Code:
[snow.zip](https://github.com/processing/p5.js/files/5654152/snow.zip)

**Comment by LsHallo** [comment]
Swapping the images for a simple rect() call has the same behaviour.

**Comment by LsHallo** [comment]
![A_framesStacked](https://user-images.githubusercontent.com/22171518/101384117-4c4b2e00-38ba-11eb-952b-9c02f7c221a9.gif)
GIF is maybe a better way to show the ones disappearing.

**Comment by lmccart** [comment]
@LsHallo could you post a snippet of your code here? (rather than making it a download zip, because not everyone feels comfortable downloading zips from the web when they don't know the author)

**Comment by LsHallo** [comment]
Ok here is all my code:
`main.js`:
```javascript
const FLAKES_NUM = 350;
const SAVE = false;

let snowImg;
function preload() {
    snowImg = loadImage('./img/snowflakes-447.png');
}

window.onerror = function myErrorHandler(errorMsg, url, lineNumber) {
    document.getElementById('error-log').innerText += errorMsg + '\r\n';
    console.error(errorMsg, url, lineNumber);
}
console.error("TEST");

let flakes = [];
let landedFlakes = [];
let savedFrames = 0;
function setup() {
    if(SAVE) {
        createCanvas(1920, 1080);
    } else {
        createCanvas(windowWidth, windowHeight);
    }

    for(let i = 0; i < FLAKES_NUM; i++) {
        flakes.push(new Flake(true));
    }

    if(SAVE) {
        noLoop();
        setTimeout(() => {
            saveAndDraw();
        }, 500);

        function saveAndDraw() {
            saveCanvas('canvasSnowFrame' + savedFrames, 'png');
            draw();
            savedFrames++;
            if (savedFrames < 8500) {
                setTimeout(saveAndDraw, 75);
            }
        }
    }
    frameRate(30);
    imageMode(CENTER);
    rectMode(CENTER);
    angleMode(DEGREES);
}

function draw() {
    /*if(frameCount % 120 === 0) {
        console.log(flakes.length, landedFlakes.length, frameRate());
    }*/
    if(SAVE) {
        clear();
    } else {
        //background(35);
        clear();
    }
    for(let i = 0; i < FLAKES_NUM - flakes.length; i++) {
        flakes.push(new Flake(false));
    }
    for(let i = 0; i < flakes.length; i++) {
        let f = flakes[i];
        if(f.move()) {
            let index = flakes.indexOf(f);
            let landedFlake = flakes.splice(index, 1);
            landedFlakes.push(landedFlake[0]);
        }
        f.draw();
    }

    for(let i = 0; i < landedFlakes.length; i++) {
        landedFlakes[i].draw();
    }

    if(flakeLandingOffset > height * .9) {
        flakeLandingOffset = 0;
        landedFlakes = [];
        console.log('FRAME COUNT ON RESET:', frameCount);
    }
}

function windowResized() {
    for(let f of landedFlakes) {
        let currentOffset = height - f.y;
        f.y = windowHeight - currentOffset;
    }

    resizeCanvas(windowWidth, windowHeight);
}
```

`flake.js`:
```javascript
const MAX_FLAKE_SIZE = 60;
const NUM_FLAKE_IMG = 3;

let flakeLandingOffset = 0;
class Flake {
    constructor(start) {
        this.x = random(0, width);
        this.size = random(12, MAX_FLAKE_SIZE);
        if(start) {
            this.y = random(-this.size, height + this.size * .3);
        } else {
            this.y = -this.size;
        }
        this.speedY = random(.8, 2.8) * Math.abs(this.size / MAX_FLAKE_SIZE);
        this.variation = Math.floor(random(0, NUM_FLAKE_IMG));
        this.spinRate = random(.4, .9) * random([1, -1]);
        this.spin = 0;
    }

    move() {
        this.y += this.speedY;
        this.x += random(.4, .7) * Math.abs(this.size / MAX_FLAKE_SIZE);
        if(this.y + this.size * .4 > height - flakeLandingOffset) {
            flakeLandingOffset += .12;
            return true;
        }
        if(this.x - this.size > width) {
            this.x = -this.size;
        }
        this.spin = (this.spin + this.spinRate) % 360;
        return false;
    }

    draw() {
        translate(this.x, this.y);
        rotate(this.spin);
        image(snowImg, 0, 0, this.size, this.size, 149 * this.variation, 0, 149, 149);
        //rect(0, 0, this.size);
        rotate(-this.spin);
        translate(-this.x, -this.y);
    }
}
```

**Comment by lmccart** [comment]
@LsHallo I tried running the code but couldn't get it to run without errors. We really need a concise snippet that illustrates your problem in order to solve this as a bug. I would suggest the best way to get help with this is to post it on the [forum](https://discourse.processing.org/) where you can get more code debugging help. Thanks!

**Comment by LsHallo** [comment]
The code should run without problem. It was however not a problem with p5 but my code. I was removing elements from the array and then looping over the next element not realizing the indexes just changed so i effectively skipped one.
