### ISSUE TITLE
visual studio showing drawSprites() and createSprite()is not defined

### ISSUE THREAD

**Issue by phalkeerat** [processing/p5.js#4943]
i am trying to make a 2d racer game and whenever i call the createSprite function it shows "Uncaught ReferenceError: createSprite is not defined" please help me about that

**Comment by limzykenneth** [comment]
`createSprite` is a [p5.play](https://github.com/molleindustria/p5.play/) specific function and isn't maintained by p5.js directly. You should file an issue with p5.play instead. You may also want to ask on the [forum](https:discourse.processing.org) first before opening an issue with p5.play. Thanks.

**Comment by poorvi-89** [comment]
> i am trying to make a 2d racer game and whenever i call the createSprite function it shows "Uncaught ReferenceError: createSprite is not defined" please help me about that
