### ISSUE TITLE
Image not loading

### ISSUE THREAD

**Issue by umacat** [processing/p5.js#4947]
//Hello,

//I'm using this code :

let img;
function preload() {
  img = loadImage('u.jpg');
}
function setup() {
  // Top-left corner of the img is at (0, 0)
  // Width and height are the img's original width and height
  image(img, 0, 0);
}

//i try also this one:

let img;
function preload() {
  img = loadImage('u.jpg');
}
function setup() {
  // Top-left corner of the img is at (0, 0)
  // Width and height are the img's original width and height
  image(img, 0, 0);
}

// and my image is not loading. 
//My image is on a folder called data inside the project. 
//I think i have issues with my browser but i cannot solve them.
//Any ideas ?

**Comment by daskalgg** [comment]
If the image is in a sub-folder you probably need to  change
 `img = loadImage('u.jpg');`
to
`img = loadImage('data/u.jpg');`

**Comment by umacat** [comment]
So simple...

Thank you!!!
