### ISSUE TITLE
createCapture should provide access to getUserMedia constraints

### ISSUE THREAD

**Issue by brysonian** [processing/p5.js#495]
getUserMedia allows you to pass constraints to the video resolution and fps. 
More info: https://w3c.github.io/mediacapture-main/getusermedia.html#idl-def-MediaTrackConstraints and http://www.html5rocks.com/en/tutorials/getusermedia/intro/#toc-constraints

**Comment by kevinb7** [comment]
look like a duplicate of https://github.com/lmccart/p5.js/issues/476

**Comment by lmccart** [comment]
closed https://github.com/lmccart/p5.js/issues/476, as this covers it more generally

**Comment by lmccart** [comment]
ahh this one keeps coming up with students, will get to it soon!
