### ISSUE TITLE
w, 0 and infinty

### ISSUE THREAD

**Issue by archtaurus** [processing/p5.js#4954]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [x] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

I think there is a division by zero bug in src/math/random.js

```js
    do {
      x1 = this.random(2) - 1;
      x2 = this.random(2) - 1;
      w = x1 * x1 + x2 * x2;
    } while (w >= 1);
    w = Math.sqrt(-2 * Math.log(w) / w);
    y1 = x1 * w;
    y2 = x2 * w;
```
When x1 and x2 is 0, w is zero, the `-2 * Math.log(0) / 0` is  Infinity, then `Math.sqrt(-2 * Math.log(0) / 0)` is NaN.
then y1 and y2 is NaN...

**Comment by limzykenneth** [comment]
If `x1` and `x2` are 0, `w` is 0 and the condition for the `while` loop will be true which means it will continue the `while` loop until it is no longer 0 nor >=1.

**Comment by archtaurus** [comment]
Noway, 0 &gt;= 1 == true ?


------------------&nbsp;Original&nbsp;------------------

**Comment by limzykenneth** [comment]
```jaavscript
while(w == 0 || w >=1)
```

if the condition is true (`w` is `0` or `w` is `>=1`) the `while` loop continues generating new value for `w` until `w !=0` and `w < 1`.

**Comment by archtaurus** [comment]
That's it.


------------------&nbsp;Original&nbsp;------------------

**Comment by limzykenneth** [comment]
Ah I see, my bad. I've been reading things the other way round in the PR diff.
