### ISSUE TITLE
loadImage() would display last frame of gif and cause error after playing ends

### ISSUE THREAD

**Issue by liubq7** [processing/p5.js#4955]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [x] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version: v1.1.9
- Web browser and version: chrome 87.0.4280.88
- Operating System: Windows
- Steps to reproduce this:

```
let gif;

function preload() {
  gif = loadImage("xxx.gif");
}

function setup() {
  createCanvas(2000, 1000);
}

function draw() {
  background(220);
  image(gif, 0, 0);
  gifControl();
}

function gifControl() {
  if (mouseX > 600 && mouseX < 1200) {
    gif.play();
  } else {
    gif.pause();
  }
}
```

Just as described in the [reference](https://p5js.org/zh-Hans/reference/#/p5.Image/play), I wrote this to control the play of gif (the play function is not supported if I use createImg() or other). In this way, it will display last frame of the gif at first, and after playing end, there will be an error "Cannot read property 'delay' of undefined" on p5.js:66515.
I've tried to fix this by pushing the first frame again to the frames on `_createGif` and it works, but the code is some kind silly...and the error still exists after playing ends.

**Comment by stalgiag** [comment]
Welcome!

The first issue you describe (last frame painted at first) [has been fixed with this commit](https://github.com/processing/p5.js/pull/4824/commits/b36acc2b41261e0d860f7bea4bfb986390d5ca05) and will be in the next release.

I am unable to recreate the second error and this may be specific to your GIF file. [Here is your code using a gif from GIPHY.](https://editor.p5js.org/stalgiag/sketches/WcmiIiQXy)

**Comment by liubq7** [comment]
Hello!

Using gif from GIPHY also works on my side, but the error will occur if I use local image.

**Comment by liubq7** [comment]
Sorry! As for the second error, I just tried another local gif and it works! It seems it's because the gif I used before can't loop.
