### ISSUE TITLE
 in Webgl Mode, textAscent() stays sticked to the first call result and is never updated. 

### ISSUE THREAD

**Issue by pirelaurent** [processing/p5.js#4958]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [x] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:       
 in Webgl Mode, textAscent()  stays sticked to the first call result and is never updated.    
in P2D textAScent() works correctly with same code :      
![Screen Shot 12-20-20 at 10 24 AM 001](https://user-images.githubusercontent.com/4208305/102709866-9666e300-42ae-11eb-8db2-bf8af6d245d3.PNG)
![Screen Shot 12-20-20 at 10 25 AM](https://user-images.githubusercontent.com/4208305/102709868-9ebf1e00-42ae-11eb-953b-9140a7e68256.PNG)

Same thing of course for textDescent() .

- p5.js version:   p5.js v1.1.9 July 22, 2020 
- Web browser and version: chrome 87.0.4280.88 (Build officiel) (64 bits)  same on Firefox:  	84.0
- Operating System: windows 10 64bits
- Steps to reproduce this:
( note: font is loaded in preload . Tests done with verdana.ttf & consolab.ttf )    
```javascript
function setup() {
  createCanvas(900, 900, WEBGL);
}

function draw() {
 translate(-width/2,-height/2);
  background(0);
  fill('white');
  textFont(consola);
  textSize(12);
  text('WEBGL : textAscent', 200,20);
  text('12: '+textAscent(), 20,20);
  textSize(14);
  text('14: '+textAscent(), 20,40);
  textSize(16);
  text('16: '+textAscent(), 20,60);
  textSize(32);
  text('32: '+textAscent(), 20,100);
 }
```

**Comment by vulongphan** [comment]
I will work on this issue.

**Comment by vulongphan** [comment]
@pirelaurent For some reason, when I switched to P2D mode, no text is displayed on the screen anymore. @stalgiag any thought on this?

**Comment by stalgiag** [comment]
Perhaps the `translate(-width / 2, -height /2)` line? The coordinate system is different in WebGL with (0,0) as the center of the canvas.

**Comment by pirelaurent** [comment]
i don't know what you call 'switch'. You cannot change mode while running. You must run once with a webgl canvas, then stop, change to p2d, run again. 
if you use a p2d graphics to create text while in webgl (what i do frequently for response time), think about to advance image a little bit on z to be on top of background things for camera.
Hth

**Comment by Forchapeatl** [comment]
@vulongphan may i take this off your hands ? i would like to work on it

**Comment by davepagurek** [comment]
@Forchapeatl I think it's ok if you want to start looking into this, thanks!
