### ISSUE TITLE
Variable Problem 

### ISSUE THREAD

**Issue by Saad-py** [processing/p5.js#4961]
Hi, so I was trying to make a program that is like a pattern or zigzag.

My code:
`let a = 0;
let b = 20; 
let c = 40;

function setup() {
  createCanvas(400, 400);
}

function draw() {
  stroke(255);
  background(220);
  line(a, a, b, b);
  line(b, b, c, a);
  
  line(c, a, b + c, b);
  line(b + c, b, c + c, a);

}
`

The problem here is that I want to c = 80, but when I type c += 40 or c = 80 it changes the whole program in simpler words I want the var c to be equal to 80  after making the second set of lines.

These algorithms are easy to understand but hard to make

**Comment by Saad-py** [comment]
If a use a for loop in some way, the c += 40 goes infinite.

Please help me

**Comment by limzykenneth** [comment]
Hi, if you need help with your own code, please direct your questions to the [forum](https://discourse.processing.org). We use GitHub issues mainly for bug reports and feature requests only. Thanks!
