### ISSUE TITLE
 p5.js works with HoloViz Panel. I.e. you can use it with Python and in Jupyter notebooks.

### ISSUE THREAD

**Issue by MarcSkovMadsen** [processing/p5.js#4964]
I just wanted to share the information that a Panel user showcased how to use HoloViz Panel with p5.js.

Right now it's just communication from backend (python) to front end. But it would be possible to enable bidirectional communication and use this create awesome analytics apps in Python like I do at [awesome-panel](https://awesome-panel.org) or use it in Jupyter Notebooks. Panel works in jupyter, VS Code and Colab. Panel integrates with Ipywidgets.

Check out the show case https://discourse.holoviz.org/t/p5-js-example/1551

https://user-images.githubusercontent.com/42288570/102855857-b4a31f00-4425-11eb-88cb-9cf9625c0b2a.mp4

If you want to learn more checkout [Panel](https://panel.holoviz.org), [HoloViz](https://holoviz.org) and [awesome-panel](https://awesome-panel.org).

Extending to bidirectional communication would require implementing a Bokeh extension. Check out my [Bokeh Extensions Guide](https://awesome-panel.readthedocs.io/en/latest/guides/awesome-panel-extensions-guide/bokeh-extensions.html) if that is something for you :-)

**Comment by lmccart** [comment]
Thanks @MarcSkovMadsen this is great! I would suggest posting this in the [forum](https://discourse.processing.org/c/p5js/10) so this info sticks around and others can use it. Since this isn't a bug or feature request, I'm going to close the issue here.

**Comment by MarcSkovMadsen** [comment]
Thanks i Will. Did not know about forum.
