### ISSUE TITLE
Would like to edit API examples to include Smithsonian Institution API from Data.gov.

### ISSUE THREAD

**Issue by edwardmonk** [processing/p5.js#4965]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Feature enhancement details:
Would like to edit "Useful APIs" to include Smithsonian Institution API from Data.gov:
https://github.com/processing/p5.js/wiki/Loading-external-files:-AJAX,-XML,-JSON
I work for the Smithsonian and we encourage the APIs use by the public.

**Comment by limzykenneth** [comment]
@edwardmonk That sounds good to me, do you have a link to the API for the section to link to?

**Comment by dhowe** [comment]
Looks quite cool, but would be great to have some better docs before making this live:

![image](https://user-images.githubusercontent.com/737638/102977059-70a33d80-453d-11eb-8e5d-95ca36d579af.png)

**Comment by lmccart** [comment]
@edwardmonk thanks! I've just sent you a repo invite. once you accept you should be able to edit the wiki page directly.

**Comment by lmccart** [comment]
@edwardmonk you should have edit access now, so I'll close this issue, but let us know if you need any help figuring out how to add this. thanks!

**Comment by edwardmonk** [comment]
I think I missed my opportunity to click on the invitation.  The link does not appear to be available anymore.

The Smithsonian Open Access API Documentation is here:  https://edan.si.edu/openaccess/apidocs/

I have used p5.js and ml5.js to work with the data...and could provide some examples.

**Comment by edwardmonk** [comment]
I have cloned this wiki, made a branch and made the simple change, but I do not have access to push the change.  Is there some other way you can suggest that I make the change?

**Comment by limzykenneth** [comment]
@edwardmonk You shouldn't need to clone anything, just navigating to https://github.com/processing/p5.js/wiki/Loading-external-files:-AJAX,-XML,-JSON you should see an "edit" button near the top right corner and that should let you edit the wiki directly.

**Comment by edwardmonk** [comment]
@limzykenneth , That is what I was expecting,  but unfortunately, that option is not there.  Maybe I need to clean my glasses... :)
https://guides.github.com/features/mastering-markdown/
<img width="1473" alt="Screen Shot 2021-01-14 at 1 40 47 PM" src="https://user-images.githubusercontent.com/1946394/104634415-961ff480-566e-11eb-86fa-c9bb31f9c898.png">

**Comment by lmccart** [comment]
thanks @edwardmonk. I sent you an invite to be a collaborator on this repo a little while ago. please accept this invite and then when you visit the page you’ll see the edit button

**Comment by edwardmonk** [comment]
Hello @lmccart, I think I may have missed the deadline to click on the link.  It was only good for 7 days and that was on Dec. 24th.  I was on vacation for a while...my apologies.  That must be why I don't see the options.

When I click on the invite...I get this message:
<img width="1503" alt="Screen Shot 2021-01-14 at 2 28 02 PM" src="https://user-images.githubusercontent.com/1946394/104639175-18abb280-5675-11eb-892b-74d364be72e9.png">

**Comment by lmccart** [comment]
Ah, got it! I've resent the invite.

**Comment by edwardmonk** [comment]
Thank you @lmccart ! That worked perfectly and I was able to start contributing to this...I used p5.js to query the Smithsonian API in different ways...is there some place appropriate to share that?

**Comment by lmccart** [comment]
@edwardmonk :) if you post them somewhere, we can share via social media, or retweet repost etc.

**Comment by edwardmonk** [comment]
I will just put them on github...that way I can keep track of them with all our other stuff.  Thanks again for you help everyone.
