### ISSUE TITLE
In p5.Element.prototype.parent() replace document.getElementById with document.querySelector

### ISSUE THREAD

**Issue by qqqwwweeerrrtttt12123** [processing/p5.js#4968]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [X] Core/Environment/Rendering
- [ ] Data
- [X] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Feature enhancement details:
[p5.Element.prototype.parent](https://github.com/processing/p5.js/blob/8741583b75d7b03d59e969895d232a1da2541ce4/src/core/p5.Element.js#L97) gets the parent of an element. If the type of the parameter is a string, It will get the element with that id's parent. If we instead of `document.getElementById` we use `document.querySelector` it would work more global. This might be a breaking change.

**Comment by siv2r** [comment]
Hello everyone,
Does this issue need to be worked on? If so, I can start working on it

**Comment by limzykenneth** [comment]
This would be a breaking change as with `querySelector` it will see lots of existing code that uses element ID without the `#` prefix as a tag selector. Since this will be a breaking change, we probably won't be condering it at this point in time.

**Comment by siv2r** [comment]
Sure, thanks for the info :)

**Comment by john0192** [comment]
@siv2r are you done

**Comment by limzykenneth** [comment]
Closing this as we won't be considering this change for the time being.
