### ISSUE TITLE
createGraphics size limitation

### ISSUE THREAD

**Issue by PandaBalls** [processing/p5.js#4970]
Is it possible to set larger graphics size,
```
pg =  createGraphics(30000,20000);
pg.save('test.jpg');
```
Chrome downloader will not find the pg file..
Looks like beyond the graphics size limitation??

**Comment by lmccart** [comment]
The p5.Graphics limitation is based on the underlying HTML5 Canvas limitation, which will vary depending on browser and hardware. Here's some more on [stackoverflow](https://stackoverflow.com/questions/6081483/maximum-size-of-a-canvas-element#:~:text=mobile%20devices%3A%2D-,The%20maximum%20size%20for%20a%20canvas%20element%20is%203%20megapixels,equal%20than%20256%20MB%20RAM.) and [mozilla.org](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/canvas)
