### ISSUE TITLE
loadAnimation() not working

### ISSUE THREAD

**Issue by thmjones2007** [processing/p5.js#4973]
load Animation and create Sprite are not working in my program can anyone help

Here is the link:
[https://editor.p5js.org/thmjones2007/sketches/A1hB8R5HK]

**Comment by razetime** [comment]
You haven't given proper links to your files.

**Comment by limzykenneth** [comment]
Hi @thmjones2007, `loadAnimation` and `createSprite` are not p5.js functions but rather functions related to [p5.play](https://github.com/molleindustria/p5.play/) which is not maintained here. You should direct your issue there. Thanks!
