### ISSUE TITLE
color.toString("#rrggbbaa") doesn't work for alpha value when alpha is less than 16.

### ISSUE THREAD

**Issue by EmeraldBlackbird** [processing/p5.js#4975]
#### Most appropriate sub-area of p5.js?

- [x ] Color

#### Details about the bug:

```
console.log(color(255, 0, 0, 5).toString("#rrggbbaa"));
```
prints `#ff000000`.

As you can see, the hexadecimal alpha value has become zero. This happens for all alpha values less than sixteen.

For now I am fixing this by doing
```
let clr = color(255, 0, 0, 5);
console.log(clr.toString("#rrggbb") + alpha(clr).toString(16).padStart(0, 2));
```
which prints `#ff00005`, as it should.

**Comment by limzykenneth** [comment]
Small typo [here](https://github.com/processing/p5.js/blob/main/src/color/p5.Color.js#L107) (index should be `3` instead of `2` when less than 16.
