### ISSUE TITLE
Text Anti-Aliasing

### ISSUE THREAD

**Issue by nullify0000** [processing/p5.js#4976]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [x] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version: v1.2.0
- Operating System: Windows

I've tried disabling anti-aliasing using the following function.
`setAttributes('antialias', false);`

Is setting this flag to false meant to make text non-aliased? If not, are there any other way to do it?

I'm trying to get my text to look like this: https://i.imgur.com/S312pVj.png
But instead it's smoothed, like this: https://i.imgur.com/ODbjsI0.png

**Comment by limzykenneth** [comment]
Hi @nullify0000, the `setAttributes` function is a WebGL mode function and won't have an effect on text. You can try [`noSmooth`](https://p5js.org/reference/#/p5/noSmooth) to see if it works for you.
