### ISSUE TITLE
Texture Bleeding in WEBGL even with padding

### ISSUE THREAD

**Issue by blechdavier** [processing/p5.js#4977]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version:  
- Web browser and version:  On a school computer so this is blocked (i never understand these people)
- Operating System:  MacOS Mojave Version 10.14.6 (18G103)
- Steps to reproduce this:

https://www.openprocessing.org/sketch/1044399#

• This is a (bad) minecraft clone
• I draw every chunk as a p5.Geometry using model()
• Each model has the same texture
• The texture is an image containing all block faces
• I'm pretty sure the UV coordinates are right
• There is 4 px of texture padding on every side of every block face (more than enough)
• This reduces texture bleeding but there still is a significant amount
• Texture bleeding is most visible when the normal of the face is perpendicular to the camera
• Pink stuff in the sand and red/brown stuff in the grass are the most noticeable.

**Comment by blechdavier** [comment]
Using Macbook Air (Intel HD Graphics 6000 1536 MB)

**Comment by stalgiag** [comment]
Hi @blechdavier thanks for the issue. This example is a bit complicated for tracking down a bug. I am not easily able to tell what the expected behavior is.

Can you make a sketch that is the simplest possible reproduction of the bug?

**Comment by lmccart** [comment]
we're not able to reproduce this but please feel free to reopen if you can provide a code sample that demonstrates the issue. thanks!
