### ISSUE TITLE
Travis CI builds currently disabled

### ISSUE THREAD

**Issue by catarak** [processing/p5.js#4982]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other (specify if possible) DevOps

#### Details about the bug:

Hey all,

I just found out that [Travis CI has changed their open source pricing](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing). As soon as I found out, I immediately put in a support ticket to Travis CI since they do still support open source projects, you just have to request credits. In the meantime, Travis builds are disabled which isn't great. I'll update this ticket when they get back to me!!!

**Comment by outofambit** [comment]
@catarak thanks for the heads up! 💖 this repo doesn't use travis ci anymore, we're on github actions now, so it shouldn't be directly affected.

**Comment by catarak** [comment]
Oh perfect! The p5.js website, p5.js sound, and the p5.js Web Editor all still do. For now we can try to get some credits but maybe these should all be moved to GitHub actions as well?

**Comment by lmccart** [comment]
thanks @catarak! I just discovered this yesterday and was about to email you, guess you're way ahead of me. I've logged the website issue here https://github.com/processing/p5.js-website/issues/920

**Comment by limzykenneth** [comment]
Not sure how much effort is required to get additional credits from Travis and how often we need to do this, if it gets too much we may want to consider spending some effort moving to GitHub Actions entirely.

**Comment by outofambit** [comment]
I think moving everything to GitHub Actions probably makes the most sense (at least long-term). its usually not too hard to move things over after you figure out a couple random gotchas.

from a quick glance at the travis config in p5.js-website, that one should be easy. the p5.js-web-editor config itself looks a little more involved but probably fine. I saw it uses some shell scripts that we'd need to double check too in case they rely on anything travis-specific too.

**Comment by catarak** [comment]
I messaged Travis CI support again but I still haven't heard back...

@outofambit I agree! I think in the meantime we can pay for a month or so of Travis CI so builds work while we migrate over the GitHub Actions.

**Comment by catarak** [comment]
Just added a payment for Travis so builds should be working again :smile:
