### ISSUE TITLE
p5.js seems to have been imported multiple times.

### ISSUE THREAD

**Issue by AliaNeedsHelp** [processing/p5.js#4985]
- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] [Core/Environment/Rendering]
- [ ] Data
- [ ] DOM
- [ ] Events
- [Yes? ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL

#### Details about the bug:

I'm not sure whether or not this is a bug with the Friendly error system because despite disabling the system, this warning still gets logged. Even though this does not affect my code's functionality, it's just annoying.

- p5.js version: 1.2.0
- Web browser and version: Chrome 87.0.4280.109 (Official Build) (64-bit)
- Operating System: ChromeOS
- Steps to reproduce this:
p5 script tag URL: https://cdn.jsdelivr.net/npm/p5@1.2.0/lib/p5.js
JS: 
```
p5.disableFriendlyErrors = true;
new p5();
```
Console:
`<WARNING>p5.js seems to have been imported multiple times. Please remove the duplicate import `

**Comment by limzykenneth** [comment]
Is there a specific reason you are calling `new p5()` manually? The library usually takes care of it so you don't need to when using global mode.

**Comment by AliaNeedsHelp** [comment]
I was trying to use global instance mode for three reasons: I am only using ONE sketch, a lot of function require p5 features, and my project is HUGE.
