### ISSUE TITLE
Chrome extension support - not calling setup() & draw()

### ISSUE THREAD

**Issue by SurekhaNandiyal** [processing/p5.js#4987]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [x] DOM
- [x] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version: 1.2.0
- Web browser and version: Chrome EXTENSION Version 87.0.4280.141 
- Operating System: MacOSX
- Steps to reproduce this:
Trying to create an extension using p5.js, p5.sound.js and ml5.js, `preload()` is being called however `setup()` and `draw()` is not being called.

This has been tried in both global and instance mode.

`manifest.json`:

```
"content_scripts": [
    {
      "matches": ["<all_urls>"],
      "js": ["p5.min.js", "p5.sound.min.js", "ml5.min.js", "script.js"]
    }
  ],

"permissions": ["http://*/*", "https://*/*"]

```

**Comment by limzykenneth** [comment]
I've never tried this before so can't say why for sure. Is there any error messages that you can see?
