### ISSUE TITLE
save P5.Graphics double size problem

### ISSUE THREAD

**Issue by PandaBalls** [processing/p5.js#4994]
![image](https://user-images.githubusercontent.com/22102700/104819864-8a4d5180-586b-11eb-9d89-2dafa172deb5.png)
I tried to create large p5.graphics that inside chrome's canvas limitation .
 then I use chrome console find this problem:
I created **p5.graphics (200,200)**, and console shows this **P5.graphics.width** is **200**, that is right;
But **after downloading**, the jpg file is **400x400**.
I think that is the problem I always can not download the large graphics I wanted..
![image](https://user-images.githubusercontent.com/22102700/104819929-22e3d180-586c-11eb-90e7-f55bf82ca394.png)

**Comment by limzykenneth** [comment]
Hi @PandaBalls, can you try setting [`pixelDensity`](https://p5js.org/reference/#/p5/pixelDensity) to 1 and see if it helps?

**Comment by PandaBalls** [comment]
> Hi @PandaBalls, can you try setting [`pixelDensity`](https://p5js.org/reference/#/p5/pixelDensity) to 1 and see if it helps?

wow.it works! thank you so much .mua!
