### ISSUE TITLE
The preview doesn't work it keeps on saying script error line 0

### ISSUE THREAD

**Issue by daksheshm29** [processing/p5.js#4995]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version: 
- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

**Comment by stalgiag** [comment]
Hi! What do you mean by the preview? The sketch output on the web editor? Can you include the requested information about your setup?

**Comment by lmccart** [comment]
we're not able to reproduce this but please feel free to reopen if you can provide a code sample that demonstrates the issue. thanks!
