### ISSUE TITLE
Offscreen WebGL Rendering Throws Error

### ISSUE THREAD

**Issue by choxi** [processing/p5.js#5000]
#### Most appropriate sub-area of p5.js?

- [x] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version: 1.2.0
- Web browser and version: Safari 14.0.2
- Operating System: macOS
- Steps to reproduce this: 

Here's a reproduction of the error: https://editor.p5js.org/choxi/sketches/Fu0DWOT1R

If you try to render offscreen with WEBGL, it throws an error:

```js
function setup() {
  createCanvas(400, 400, WEBGL);
  buffer = createGraphics(400, 400, WEBGL)
  buffer.fill(0, 255, 255)
  buffer.rect(-200, -200, 400, 400)
  image(buffer, -200, -200)
}
```

This throws the error: `undefined is not an object (evaluating 'this._accessibleOutputs.grid')`. It seems to work on version 1.1.9 but is broken on 1.2.0.

**Comment by stalgiag** [comment]
Thank you @choxi !

@lm-n do you have any thoughts on what might be causing this?

**Comment by lm-n** [comment]
@choxi thanks for the quick fix! @stalgiag we might find more WebGL related issues with accessibility since it was designed to support 2d shapes. let's keep an eye on those  👀  :)
