### ISSUE TITLE
wiki/p5.js, node.js, socket.io code example does not work

### ISSUE THREAD

**Issue by harplife** [processing/p5.js#5002]
#### Most appropriate sub-area of p5.js?
- [x] Other (wiki)

#### Details about the bug:

- p5.js version: v1.2.0
- Web browser and version: Chrome 87.0.4280.141
- Operating System: Windows 10
- Steps to reproduce this:

Hi, p5js first timer here, just trying to follow the wiki and code examples.

I'm having an awful time following the wiki on [setting up p5.js with socket.io](https://github.com/processing/p5.js/wiki/p5.js,-node.js,-socket.io#sockets). I've simply downloaded the code files, and installed socket.io via npm.

When I tried to run server.js with node, the server won't even start and I would get `TypeError: require(...).listen is not a function`. After looking it up on StackOverflow, I changed from `var io = require('socket.io').listen(server);` to `var io = require('socket.io')(server);` and it started working. Or at least, the server was running.

When I connected to localhost:8080, I would get an empty page. Tried to click around, and I see nothing. So, I opened up chrome developer tool, and then I saw the `ReferenceError: windowWidth is not defined`. I had a look at the index.html file, and it was reaching for p5.min.js file from a [CDN](https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.2.9/p5.min.js). Just in case, I donwloaded the latest p5.min.js to local, and made the `<script src=>` point to the local file. It worked, and I saw a black sketch board. But then..

When I thought everything was working, I saw the errors that look like `GET http://localhost:8080/socket.io/?EIO=3&transport=polling&t=NSKNJwk 400 (Bad Request)` pop up every second. Obviously, socket.io wasn't working properly and I confirmed it by connecting to the server with another client - no dice.

I haven't gotten around to troubleshooting the socket.io problem, and I'm not expecting someone to solve the problem for me here. But, I would appreciate it if someone other than me could look into it, see if it's working for them. I'll be sure to put up an update if I figure out what's going on.

**Comment by lmccart** [comment]
Ah sorry about that, this is quite an old tutorial and may be out of date with current versions. I would suggest starting with the tutorials here to get socket.io running: https://socket.io/

Then these lines should still be relevant;

```js
function mouseDragged() {
  // Make a little object with mouseX and mouseY
  let data = {
    x: mouseX,
    y: mouseY
  };
  // Send that object to the socket
  socket.emit('mouse',data);
}
```

```js
  socket.on('mouse',
    function(data) {
      // Draw a blue circle
      fill(0,0,255);
      noStroke();
      ellipse(data.x,data.y,80,80);
    }
  );
```

**Comment by harplife** [comment]
It's no problem. I know this may have been just a course material for your students but I really like the topic of the tutorial so I wanted to try it.

As per your suggestion, I did follow the tutorials at socket.io and it helped me solve the issue. Below are the changes;

server.js:

```javascript
// Socket.io version: 3.1.0
// .listen() doesn't work
var io = require('socket.io')(server);

// io.sockets.on() doesn't work
io.on('connection', function(socket) { ... });
```

sketch.js:

```javascript
// Start socket connection here
// .connect(ip_addr) is not necessary
var socket = io();

function setup() {
    createCanvas(windowWidth, windowHeight);
    background(0);

    socket.on('mouse', function(data) {
        console.log("Got: " + data.x + " " + data.y);
        fill(0,0,255);
        noStroke();
        ellipse(data.x, data.y, 80, 80);
    });
}

...
```

index.html:

```html
    <!-- This refers to the npm installed module -->
    <script language="javascript" type="text/javascript" src="/socket.io/socket.io.js"></script>
    <!-- p5.js v1.2.0 -->
    <script language="javascript" type="text/javascript" src="p5.min.js"></script>
    <script language="javascript" type="text/javascript" src="sketch.js"></script>
```

Few simple changes, and viola! It's now up-to-date.

**Comment by lmccart** [comment]
Thanks! I just made the updates. Glad it worked out!
