### ISSUE TITLE
Broken link?

### ISSUE THREAD

**Issue by metacortexplus** [processing/p5.js#5005]
https://github.com/processing/p5.js/blob/b15ca7c7ac8ba95ccb0123cf74fc163040090e1b/src/core/structure.js#L23

Should be saveFrames?

**Comment by limzykenneth** [comment]
Yes, it seems to be a typo. Would you like to file a PR to fix this? I can assign the issue to you if so.

**Comment by metacortexplus** [comment]
> Would you like to file a PR to fix this? I can assign the issue to you if so.

Yes.
