### ISSUE TITLE
saveTable issue

### ISSUE THREAD

**Issue by PandaBalls** [processing/p5.js#5006]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [x] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:
loadTable as table,
table.set() some values,
print(table) looks fine.
But saveTable(table) throw this error:
```
p5.min.js:3 Uncaught TypeError: e.rows[l].arr[u].includes is not a function
    at _.y.default.saveTable (p5.min.js:3)
    at <anonymous>:1:1
```

**Comment by PandaBalls** [comment]
only happened in p5.vscode.
It works fine in Processing Desktop IDE

**Comment by PandaBalls** [comment]
I tested with 2 version of p5.mini.js 
`/*! p5.js v0.10.2 October 14, 2019 */` this works for me .
`/*! p5.js v1.2.0 December 19, 2020 */` this will throw the error.

**Comment by limzykenneth** [comment]
@PandaBalls Can you maybe share a sample sketch? You can set one up with the p5.js web editor then we can test with the same table data as you have if you like.

**Comment by PandaBalls** [comment]
> @PandaBalls Can you maybe share a sample sketch? You can set one up with the p5.js web editor then we can test with the same table data as you have if you like.

Here is the online editor version.
[SaveTable issue](https://editor.p5js.org/PandaBalls/sketches/Dz8DUXxkY)

**Comment by limzykenneth** [comment]
The checks on [this line](https://github.com/processing/p5.js/blob/1.2.0/src/io/files.js#L1730) assumes the table element will be a string and calls a string function on it while it could be other types (numbers on your example) so it fails. 

We could add an explicit typecast before that check to make sure everything is casted as a string before continuing, or we can add an additional check if the passed in value is string or not.
