### ISSUE TITLE
Clipping issues with webGL using .png images on planes

### ISSUE THREAD

**Issue by essence-of-orange** [processing/p5.js#5007]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

Expected behaviour: https://pic8.co/sh/5MVKQs.png
Actual behaviour: https://pic8.co/sh/BAPd8B.png

Whenever there are two overlapping .png images with an alpha channel, and one is in front is drawn before the one at the back, the transparent parts of the one in front clip the one at the back as well as the visible parts. I suspect that this is because the one drawn first gathers information from the objects behind it immediately, rather than waiting until all objects have been added in order to render the scene.

In some scenes it may be trivial to work around this bug by strictly controlling the draw order and always drawing objects closest to the camera last, but in scenes with intersecting objects (as in the one where I originally encountered this problem) this may not be possible.

I have included a simple sketch to illustrate the problem.

- p5.js version: 10.2
- Web browser and version: Chrome 87.0.4280.88 (Official Build) (64-bit)
- Operating System: Linux Mint 20 Cinnamon
- Steps to reproduce this: 

Background image: https://pic8.co/sh/63guwG.png
Mario image: https://pic8.co/sh/gqXw5Z.png

```
//**********************************//
//      PRELOAD OBJECTS       //
//**********************************//
function preload() {
    mario = loadImage("mario.png");
    bgd = loadImage("background.png");
}

//******************//
//      SETUP       //
//******************//
function setup() {
    myCanvas = createCanvas(800,800,WEBGL);
    background(0);
}

//*********************************//
//      UPDATE AND DRAW     //
//*********************************//
function draw() {
    //Clear canvas
    background(0);
    
    orbitControl();
    
    //Draw background
    push();
    translate(0,0,-200);
    image(bgd,-250,-250,500,500);
    pop();
    
    //Draw mario in front
    push();
    translate(0,0,100);
    image(mario,-100,-100,200,200);
    pop();
    
    //Draw mario behind
    push();
    translate(0,0,-100);
    image(mario,-100,-100,200,200);
    pop();
}
```

**Comment by essence-of-orange** [comment]
I've just confirmed that this issue still occurs in the current version of p5: https://pic8.co/sh/l7nzNc.png

**Comment by davepagurek** [comment]
Hi, thanks for reporting this! This is an issue related to how transparent images are rendered, so for organizational purposes, I'm going to close this issue in favor of https://github.com/processing/p5.js/issues/3736, which is also about this topic. Feel free to continue the discussion there, or let me know if I've overlooked something!
