### ISSUE TITLE
Objs Rendered in Incorrect Order

### ISSUE THREAD

**Issue by S1N1C** [processing/p5.js#5009]
Hi, I am using p5 with matter.js as the render engine...I am running into an issue where as the order being rendered is not the same as the order in code. I will paste and then explain.

`function draw() {
   	
    Engine.update(engine);
  	
  	//ground.show();
    //rightBound.show();
    //topBound.show();
  	cup.showBack();
    for (let i = 0; i < bits.length; i++) {
      
      if(!bits[i].spawned && timer()){
        bits[i].spawn();
        bits[i].spawned = true;
      }
      if(bits[i].spawned){
        bits[i].show();
      }
      if(bits[i].despawn()){
        bits[i].remove();
        bits.splice(i, 1);
        i--;
      }
    } 
  	
  	cup.show();
}
`
So in this draw function there is a cup that has two images a front image that should be rendered last and a cup back image that should be rendered first...this give the impression that the rendered bits between are going into the cup...The bit objects are gifs and the cup images are pngs. not sure if that makes a difference to the render order....

when this is being rendered to screen the bits are always ontop no matter what order...advice needed thanks

**Comment by S1N1C** [comment]
this is not important for me now...as the cup was static and never needed be updated, I simply created the image above the canvas.

**Comment by limzykenneth** [comment]
Hi, if you need help with your own code, please direct your questions to the [forum](https://discourse.processing.org). We use GitHub issues mainly for bug reports and feature requests only. Thanks!
