### ISSUE TITLE
Some gifs break when rendering with image()

### ISSUE THREAD

**Issue by markof94** [processing/p5.js#5014]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [x ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version:  1.2.0
- Web browser and version: Chrome  88.0.4324.104 (Official Build) (64-bit) (cohort: 88_96_win)
- Operating System:  Windows 10
- Steps to reproduce this:

Some gifs will cause a crash when trying to render via `image()`
`game.image(img, 200, 200, 200, 200);`

![p5bug](https://user-images.githubusercontent.com/46076533/105879865-f9147280-6002-11eb-9fb2-3205dc220e79.png)

I am able to reproduce it with [this gif](https://media.giphy.com/media/kEKcOWl8RMLde/giphy.gif) consistently.

As you can see from the screenshot, it loads properly (via `loadImage()`) but if you try rendering, you get the 
`Uncaught TypeError: Cannot read property 'image' of undefined` error,
and some `gifProperties` from the image object become `NaN`

Note: Most other gifs from giphy will work fine, but some, like this one will throw that error.

**Comment by akshay-99** [comment]
Thanks for reporting. This seems to happen on GIFs that have frames with a delay value of 0ms. So `curDelay` at [line 233 here](https://github.com/processing/p5.js/blob/1.2.0/src/image/p5.Image.js#L233) becomes 0.  Because of this, the calculation for `skips` results in a division by 0 or `NaN`. 

Technically the GIF has a frame rate of infinity. From [this StackOverflow answer](https://stackoverflow.com/a/21791302), I suppose most GIF display programs have their own logic to handle this and set a reasonable value for the frame delay. Perhaps p5 should too.

**Comment by stalgiag** [comment]
@akshay-99 thank you for looking into this! 

I think that if `frameInfo.delay` is 0 [when loading](https://github.com/processing/p5.js/blob/1.2.0/src/image/loading_displaying.js#L198) it should become become 100 (or 10 * 10) to give us a fallback standard of 10fps.

Does anyone want to make this change? This could be a good issue to tackle for a first-time contributor.

**Comment by ShenpaiSharma** [comment]
Hi, @stalgiag. I want to look into this issue.

**Comment by stalgiag** [comment]
great @ShenpaiSharma assigned!

**Comment by johnmusk** [comment]
@ShenpaiSharma are you working on this if no than plz assigned it to me

**Comment by johnmusk** [comment]
@ShenpaiSharma if you are not working on this plz assigend it to me

**Comment by ShenpaiSharma** [comment]
I'm sorry, @johnmusk. I had my semester quiz in the past few days; that's why I was busy. I still want to give it a go. If I am not able to do it, then I will certainly inform you.

**Comment by johnmusk** [comment]
@ShenpaiSharma No worry take your time bro
