### ISSUE TITLE
Canvas Layers incorrect with different heights using WEBGL

### ISSUE THREAD

**Issue by da091005** [processing/p5.js#5015]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Web browser and version:  Safari
- Operating System: IPad Pro IOS 14.3
- Steps to reproduce this bug: When using WEBGL, if you set the height >425 the layers of the canvas get messed up when trying to use text.

 https://editor.p5js.org/UnOriginalPun/sketches/0yGE68Xok 

![7945A4CD-2E05-466B-846C-ADE796822039](https://user-images.githubusercontent.com/37953135/104849408-d57b6900-592c-11eb-85f5-1b8400ea4abc.png)
![C3614AD4-CFAC-438E-BD55-C1CE60B028DD](https://user-images.githubusercontent.com/37953135/104849411-d9a78680-592c-11eb-9e96-caf1c6a6167d.png)

**Comment by stalgiag** [comment]
Hi! Thanks for the issue.

I think this may be similar to #4183 . But I also notice that you are drawing everything at 0 on the z-axis. You could try separating everything out a bit on the z-axis (even tiny values like plus or minus 0.01) and that would likely fix the depth fighting on mobile.

**Comment by lmccart** [comment]
@da091005 have you tried @stalgiag's suggestion? I just tested and this should resolve the issue.
