### ISSUE TITLE
Are there any release notes for p5.js 1.2.0 ?

### ISSUE THREAD

**Issue by grege2** [processing/p5.js#5016]
Hi team, I've had a good hunt for some release notes on 1.2.0 but not found anything. Are there new features, calls, parameters in 1.2.0 ? Is it a pure bugfix release ? Thanks, and apologies if I have missed something obvious. And Happy New Year, a bit late.

**Comment by lmccart** [comment]
There are not, sorry!

**Comment by grege2** [comment]
Hi Lauren. So it's a bugfix release, nothing new to try ?

**Comment by lmccart** [comment]
There may be new things... I'm so deeply deeply underwater, no ability to write anything up, but when I do, I am normally just pulling from the commit history, so you could look there.

**Comment by grege2** [comment]
Ok, thanks. I did have a look, but not very thoughly, will look more better. Glad you're busy! Ciao.

**Comment by lmccart** [comment]
thanks for your understanding 🙏  aiming for a better record with next release!
