### ISSUE TITLE
p5.Vector object error

### ISSUE THREAD

**Issue by ricoloic** [processing/p5.js#5024]
#### Issue with p5.Vector object > p5.js

- [x] IO (Input/Output)
- [X] Utilities
- [X] Other (specify if possible)

#### Details about the bug:

- p5.js version: 1.1.9
- Web browser and version: Brave | 1.19.88 Chromium: 88.0.4324.96 (Official Build) (64-bit)
- Operating System: Microsoft Windows 10 Home - 10.0.18363 build 18363
- Steps to reproduce this: [clone the repo then run](https://github.com/ricoloic/flowField)

The lines in question can be found in the file `sketch.js line 17 to 19` and `particle.js line 1 to 8`
I'm getting some string as for the x of the vector.

here is some pic about the probleme
![](https://cdn.discordapp.com/attachments/276365426827722752/805646663355072593/9602cfe2117fccfbcbb8f42c3a869385.png)
![](https://cdn.discordapp.com/attachments/276365426827722752/805646670871527435/0cc861759a8adaa86147c3ca20194f6f.png)

**Comment by vinayaksh42** [comment]
Hey, I would like to work on this issue

**Comment by satyasaibhushan** [comment]
Hey, 
I am looking through your issue and found out that the link provided for your repository is not working.I think you've kept your repo private.
Could you please provide the new link?

**Comment by ricoloic** [comment]
sure sorry again


Le mar. 2 févr. 2021 à 07:13, Sai Bhushan <notifications@github.com> a
écrit :

**Comment by ricoloic** [comment]
There you go it's public now

**Comment by ricoloic** [comment]
https://github.com/ricoloic/flowField

**Comment by satyasaibhushan** [comment]
Hey, @ricoloic 

I don't think that this is a issue in p5.js
In your file, `flow.js` you've set the values of a vector as 
`this.vec = 0`
but in `particle.js`  you're trying to add force as a whole. try adding it as
 `this.acc.add(force.vec);`

#### I think this solves your problem. Please check and update me 😃

**Comment by ricoloic** [comment]
Thx, I'll let you know. If it's just this I'm sorry in advance for the waste of time.

**Comment by ricoloic** [comment]
Sorry again for the waste of time
