### ISSUE TITLE
Stroke opacity for HSB not working?

### ISSUE THREAD

**Issue by danawoodman** [processing/p5.js#5029]
Thanks for a great library!

Should HSB allow for transparent stroke? From what I can tell, this is not working. Here is an example:

https://editor.p5js.org/danawoodman/sketches/7cT0qwAo-

```js
function setup() {
  createCanvas(400, 400);
  
  // Comment this out to see opaque stroke:
  colorMode(HSB);
  
  stroke(0, 0, 0, 5);
  
  line(0, 0, 100, 100)
}
```

#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [x] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version: Using editor
- Web browser and version: Brave (latest)
- Operating System: macOS
- Steps to reproduce this: https://editor.p5js.org/danawoodman/sketches/7cT0qwAo-

**Comment by satyasaibhushan** [comment]
hey @danawoodman ,
from what I understand, you are asking that the stroke with the HSB colour mode should be transparent but the output stroke is dark (alpha :255) . Did I get this right?

**Comment by limzykenneth** [comment]
In HSB color mode the alpha value goes from 0-1 instead of 0-255 in RGB mode. You can change this range by providing additional arguments to `colorMode()` (eg. `colorMode(360, 100, 100, 255)`)

**Comment by peterdickx** [comment]
But why is it by default between 0-1?
Saturation and brightness are also a percentage, and they are between 0-100.
Wouldn't it be more logical to also make the alpha between 0-100?
