### ISSUE TITLE
MouseWheel firefox v35 compatibility

### ISSUE THREAD

**Issue by andrusenn** [processing/p5.js#503]
I'm using mouseWheel() method in firefox browser v35, and this method doesn't work. Here is specification: https://developer.mozilla.org/en-US/docs/Web/Events/mousewheel.
'DOMMouseScroll' instead 'mousewheel' for modern browsers.
see https://developer.mozilla.org/en-US/docs/Web/Events/wheel

**Comment by hellwoodfire** [comment]
This problem look to be very easy to fix in the p5.js

**Comment by lmccart** [comment]
would someone with a mouse mind testing the newest version to see if this fix works?

**Comment by andrusenn** [comment]
Great! working now.
Testing code:
```javascript
// to work in FF,  pass "event"
// Tested in:  FF 37 / IE 11  / Opera 28.0 / Safari 5.1.7 / Chrome 41
function mouseWheel(event) {
       var n = (event.wheelDelta || -event.detail);
      println(n);
}
```

**Comment by lmccart** [comment]
great, thanks!
