### ISSUE TITLE
Extra code block header on wiki page

### ISSUE THREAD

**Issue by waitblock** [processing/p5.js#5030]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other - Wiki

#### Feature enhancement details:
I noticed an extra HTML code block header on this [wiki page](https://github.com/processing/p5.js/wiki/Positioning-your-canvas#centering-the-sketch-on-the-page-with-js). 
![Screen Shot 2021-02-03 at 8 39 55 AM](https://user-images.githubusercontent.com/65051086/106756069-df73bc00-65fc-11eb-8c6c-21db156bae4e.png)

**Comment by limzykenneth** [comment]
Fixed. Thanks!
