### ISSUE TITLE
Using non-default camera with createVideo(CAPTURE)

### ISSUE THREAD

**Issue by bwanaaa** [processing/p5.js#5031]
I read this old thread
https://github.com/processing/p5.js/issues/1043
but it is closed.
Has the problem been solved?
I cannot access the camera on a jetson nano.

#### Most appropriate sub-area of p5.js?

- [X] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [X] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [X] Utilities
- [X] WebGL
- [ ] Other (specify if possible)

#### Feature enhancement details:
Easy access to camera on a ML edge device

**Comment by limzykenneth** [comment]
Does providing the `constrain` options object solve your use case? You can try the second example [here](https://p5js.org/reference/#/p5/createCapture).

**Comment by bwanaaa** [comment]
I tried this code in the sketch:

```
let capture;

function setup() {
  createCanvas(1280, 720);
  let constraints = {
    video: {
      mandatory: {
        minWidth: 1280,
        minHeight: 720
      },
      optional: [{ maxFrameRate: 10 }]
    },
    audio: true
  };
  createCapture(constraints, function(stream) {
    console.log(stream);
  });
}

function draw() {
  background(20);
  image(capture, 0, 0, 320, 240);
  filter(INVERT);
}
```

got a black screen but no video. Console said this:

p5.js:47875 > p5.js says: image() was expecting p5.Image|p5.Element for parameter #0 (zero-based index), received an empty variable instead. If not intentional, this is often a problem with scope: [https://p5js.org/examples/data-variable-scope.html] at http://localhost:5000/sketch.js:22:3. [http://p5js.org/reference/#p5/image]
p5.js:57054 Uncaught TypeError: Cannot read property 'width' of undefined
    at p5.image (p5.js:57054)
    at draw (sketch.js:22)
    at p5.redraw (p5.js:51956)
    at p5.<anonymous> (p5.js:46250)
    at p5.<anonymous> (p5.js:46152)
    at new p5 (p5.js:46434)
    at _globalInit (p5.js:48404)
p5.dom.js:1135 DOMException: Requested device not found

**Comment by limzykenneth** [comment]
I think in your use case you need may need to provide `{ video: { deviceId: myPreferredCameraDeviceId } }` as well. Does the webcam on your device work on other websites out of the box?

**Comment by bwanaaa** [comment]
If I plug a webcam into the usb port of the jetson, it works fine. I cannot however get p5js to use the camera plugged into the slot on the board. The only way I can get video out of that camera is to use gstreamer. -.

If I use v4l to list devices:
```
v4l2-ctl --list-devices
vi-output, imx219 6-0010 (platform:54080000.vi:0):
	/dev/video0

HD Webcam C615 (usb-70090000.xusb-2.1):
	/dev/video1


```
It is clear the camera I want to address is /dev/video0
My sketch is 
function setup() {
  createCanvas(480, 480);
  capture = createCapture({ video: { deviceId: 0 } });
  capture.hide();
}

The video stiil comes from the webcam (device id 1) and it is the same video if I use
`  capture = createCapture({ video: { deviceId: 1 } });`

**Comment by bwanaaa** [comment]
I also tried using a constraints object like this:

```
let capture;

function setup() {
  createCanvas(480, 480);
  let constraints = {
	 video:{
	  deviceId: 0  
	 },
		 
      mandatory: {
        minWidth: 1280,
        minHeight: 720
      },   
    }
 
  
  capture=createCapture(constraints, function(stream) {
    console.log(stream);
  });

}

function draw() {
  image(capture, 0, 0, width, width * capture.height / capture.width);
  filter(INVERT);
}

```
regardless of using deviceId: 0  
or
deviceId:1

I always get the same video-that from the webcam plugged into the usb port.
How can I address the camera using the slot on the board with p5js?

**Comment by limzykenneth** [comment]
Can you show the output of running the following:

```javascript
navigator.mediaDevices.enumerateDevices()
.then(function(devices) {
  devices.forEach(function(device) {
    console.log(device.kind + ": " + device.label +
                " id = " + device.deviceId);
  });
})
.catch(function(err) {
  console.log(err.name + ": " + err.message);
});
```

**Comment by bwanaaa** [comment]
```
audioinput: Default id = default
sketch.js:7 audioinput: Built-in Audio Analog Stereo id = 0068bb114c85cf3c888bf91db03836ee77229f26e4a3e662bd26f2f699f48962
sketch.js:7 audioinput: HD Webcam C615 Analog Mono id = fc89bc754ab720f208eb15003ec57a37a01914da5a15abed9bc008d6e1c80e06
sketch.js:7 videoinput: HD Webcam C615 (046d:082c) id = 293d6ffe7af3f1d03bbd157831358e5570f4eb1c279b39d4bece423a1f6c197e
sketch.js:7 audiooutput: Default id = default
sketch.js:7 audiooutput: Built-in Audio Digital Stereo (HDMI) id = 8edc1f01559c270f05b1a07d55428d00e3529eb1fb87d15874411be92068c581
sketch.js:7 audiooutput: Built-in Audio Analog Stereo id = 0607040b3dd91a27307cc71d5eb2f45d9d924c453e35e8498a6f0feb676a1952
```

**Comment by bwanaaa** [comment]
weird, p5js is not seeing the onboard camera.

**Comment by bwanaaa** [comment]
If I unplug the usb webcam I get this:
```
audioinput: Default id = default
sketch.js:7 audioinput: Built-in Audio Analog Stereo id = 0068bb114c85cf3c888bf91db03836ee77229f26e4a3e662bd26f2f699f48962
sketch.js:7 audiooutput: Default id = default
sketch.js:7 audiooutput: Built-in Audio Digital Stereo (HDMI) id = 8edc1f01559c270f05b1a07d55428d00e3529eb1fb87d15874411be92068c581
sketch.js:7 audiooutput: Built-in Audio Analog Stereo id = 0607040b3dd91a27307cc71d5eb2f45d9d924c453e35e8498a6f0feb676a1952
p5.dom.js:1135 DOMException: Requested device not found
```

**Comment by bwanaaa** [comment]
I also tried to list the sources using the code from here:

https://github.com/ITPNYU/ICM-2015/blob/master/09_video_sound/02_capture/13_get_sources/sketch.js

```

var capture;
var options;

function setup() {
  MediaStreamTrack.getSources(gotSources);
  capture = createCapture(options);

}

function gotSources(sources) {
  for (var i = 0; i !== sources.length; ++i) {
    if (sources[i].kind === 'audio') {
      console.log('audio: '+sources[i].label+' ID: '+sources[i].id);
    } else if (sources[i].kind === 'video') {
      console.log('video: '+sources[i].label+' ID: '+sources[i].id);
    } else {
      console.log('Some other kind of source: ', sources[i]);
    }
  }
}


```
and this output to console

```
Uncaught TypeError: MediaStreamTrack.getSources is not a function
    at setup (sketch.js:15)
    at p5.<anonymous> (p5.js:11613)
    at p5.<anonymous> (p5.js:11564)
    at new p5 (p5.js:11816)
    at _globalInit (p5.js:8362)
```

**Comment by bwanaaa** [comment]
I dont think there is a simple solution to this.
https://forums.developer.nvidia.com/t/using-p5-js-with-jetson-nano/167250
That forum in particular reveals a lot of people having trouble managing the CSI camera.
Since I have p5js working with a regular usb webcam, I'll stick with that for now.

**Comment by limzykenneth** [comment]
Yeah, if the browser itself have problems seeing the webcam there's not much p5.js can do either. I'm going to close this for now.

**Comment by zhangy49** [comment]
> jetson nano.

Hey, can I ask how can you use p5js work with usb cam?

**Comment by zhangy49** [comment]
> I dont think there is a simple solution to this. https://forums.developer.nvidia.com/t/using-p5-js-with-jetson-nano/167250 That forum in particular reveals a lot of people having trouble managing the CSI camera. Since I have p5js working with a regular usb webcam, I'll stick with that for now.

Hey, can I ask how can you use p5js work with usb cam?
