### ISSUE TITLE
getURLParams() reference clarification

### ISSUE THREAD

**Issue by tobyhoward** [processing/p5.js#5035]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [x ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Feature enhancement details:

getURLParams() returns undefined when called from a sketch run within the p5.js editor, because the code there is embedded in an iframe. getURLParams() works correctly when the sketch is viewed via the present or share urls. I suggest adding a sentence about this to the getURLParams() ref page at https://p5js.org/reference/#/p5/getURLParams.

cheers
Toby

**Comment by Aloneduckling** [comment]
I believe we have to changes here https://github.com/processing/p5.js/blob/c1640a7cb11c25145e9b9dd561ba27f7b49fcde4/src/core/environment.js#L707
