### ISSUE TITLE
textWidth() returns wrong value for strings with "\n" 

### ISSUE THREAD

**Issue by XikoCat** [processing/p5.js#5036]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [x] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version: p5@1.2.0
- Web browser and version: Google Chrome | 88.0.4324.146
- Operating System: Browser on Windows 10, web server on Raspbian
- Steps to reproduce this:
```
    let foo = "hello";
    let bar = "world";
    print("foo: " + pg.textWidth(foo));
    print("bar: " + pg.textWidth(bar));

    //bug is here
    let foobar = foo + "\n" + bar;
    print("foobar: " + pg.textWidth(foobar));

    foobar = foo + " " + bar;
    print("foobar: " + pg.textWidth(foobar));
```

here the textWidth() of foobar should be the same size as the widest text foo or bar, in this case, bar
Instead, the current behavior is ignoring the interpreting the "\n" as a " "(space)

Running the code above I'm getting this:
```
foo: 31.69189453125
bar: 35.8447265625
foobar: 71.7041015625
foobar: 71.7041015625
```

**Comment by Ajaya1000** [comment]
Hi, I'm new to open source contributions.
I'm interested to work on this issue.

**Comment by Aloneduckling** [comment]
This issue is similar to #3869.

If we consider the width of EOL in terms of " "(space) then we can get our desired result


Code here: 
https://editor.p5js.org/Aloneduckling/sketches/78CLYND6A

I don't know how much " "(space) characters are equivalent to EOL so I have considered '\t' in this example instead of '\n'

**Comment by limzykenneth** [comment]
I'm not familiar with this part of the codebase but as far as I know the value returned from `textWidth()` is taken from opentype.js which is what we are using as a dependency. Unless there's extra code on our end that deals with `textWidth()` in special cases already, this problem might be better raised at opentype.js.

**Comment by KarthikSundar2002** [comment]
Is this issue still open?? If it is, I would like to give it a shot.

**Comment by limzykenneth** [comment]
@KarthikSundar2002 It is still open but instead of working on a fix right away I would suggest going through the discussions above, specifically about determining whether this is something to fix in p5.js itself or a fix would better suit opentype.js.

**Comment by KarthikSundar2002** [comment]
Yea I went through the issue, as @limzykenneth told me, It is an issue with opentype.js. I guess we need to report it to them

**Comment by stelf** [comment]
well, for all I care this is a working solution, and it would not be impacted by opentype.js actually fixing (or not) their issue

```javascript
  let maxLine = "";
  const lines = split(someText, '\n');
  lines.forEach( line => maxLine = maxLine.length > line.length ? maxLine : line);
  let tW = textWidth(maxLine);
```

while this may be sub-optimal, I'm sure many people loose time debugging programs. particularly coming from the Java Processing flavor.
