### ISSUE TITLE
Problem Scaling Graphics

### ISSUE THREAD

**Issue by giovannone** [processing/p5.js#5037]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version: p5.js v1.1.9
- Web browser and version: chrome: Version 88.0.4324.150 (Official Build) (64-bit)
Firefox: 85.0.1
- Operating System: Windows 10 Home
- Steps to reproduce this:

Hello!

I am having a little bit of trouble scaling graphics on google chrome. The following code works on firefox, but not chrome:

```
function setup() {
  mycanvas=createCanvas(400, 400);
  mycanvas.elt.style = 'scale:0.7;';
}

function draw() {
  background(220);
}
```

Thank you so much for your time!!

**Comment by limzykenneth** [comment]
To scale using CSS the syntax is `mycanvas.elt.style.scale = 0.7`.

If you need further help with your own code, please direct your questions to the [forum](https://discourse.processing.org). We use GitHub issues mainly for bug reports and feature requests only. Thanks!
