### ISSUE TITLE
Using clear() every frame

### ISSUE THREAD

**Issue by nullify0000** [processing/p5.js#5038]
I'm clearing my pixel buffer every frame using clear() (every 16ms for 60fps), but it's using a lot of my cpu, is there a better and more efficient way to clear the canvas?

Other than that, p5.js has done wonders for me and I love it <3

Thanks in advance.

**Comment by limzykenneth** [comment]
`clear()` isn't a very complex operation and shouldn't be taking that much CPU. Can you share a minimal code example that shows the problem?

**Comment by lmccart** [comment]
we're not able to reproduce this but please feel free to reopen if you can provide a code sample that demonstrates the issue. thanks!
