### ISSUE TITLE
Touch screen Problem

### ISSUE THREAD

**Issue by ManavNayak** [processing/p5.js#5039]
Hi team, this is Manav. I use editor.p5js which is really good. I am working on a game to upload in Google Play Store. I uploaded this project to GitHub to test it on all devices. It worked on computer but when I tested it on my tablet and mobile the buttons don't function. I use the mousePressedOver() function. But it doesn't work on touch screen devices. So, do you have any solution to this problem ????

**Comment by ManavNayak** [comment]
What do u mean ???

**Comment by limzykenneth** [comment]
There isn't a mousePressedOver() function in p5.js. Can you fill in the issue template that is provided when creating an issue? It would be helpful for us to debug what your problem might be. Thanks.

**Comment by ManavNayak** [comment]
Ok, by the way there is one a mousePressedOver() function
