### ISSUE TITLE
blendMode() documentation

### ISSUE THREAD

**Issue by jbakse** [processing/p5.js#5042]
Hello Team.

I'm not sure which template to use for documentation issues. Let me know if I should submit it differently.

In the documentation for blendMode some of the blending equations are given like this:
```
BLEND - linear interpolation of colours: C = A\*factor + B. This is the default blending mode.
DARKEST - only the darkest colour succeeds: C = min(A\*factor, B).
LIGHTEST - only the lightest colour succeeds: C = max(A\*factor, B).
```
Before the multiplication there is a `\`. I think that character should not be there. Probably an unneeded escape?

Also, is the BLEND equation right? Maybe it should be C = A*factor + B*(1-factor)?

Drawing a transparent black shape on a white background does darken the pixels.

**Comment by limzykenneth** [comment]
I think those are indeed unneeded escape.

I'm not familiar enough about the BLEND equation though. It basically should be the `source-over` algorithm used by HTML canvas itself.
