### ISSUE TITLE
[Question] connect p5 with cordova

### ISSUE THREAD

**Issue by sarthak-g** [processing/p5.js#5043]
p5.AudioIn() does not work when build app using cordova. Therefore, I've used [cordova plugin](https://github.com/edimuj/app-audioinput-demo) to receive microphone audioContext. Now, I want to connect above context as input to p5.fft to visualize waveform.
How can I achieve this?

**Comment by limzykenneth** [comment]
Hi, if you need help with your own code, please direct your questions to the [forum](https://discourse.processing.org). We use GitHub issues mainly for bug reports and feature requests only. Thanks!
