### ISSUE TITLE
Documentation for filter method is partly missing

### ISSUE THREAD

**Issue by seldomU** [processing/p5.js#5045]
Hello,

there are two filter methods, one for the [canvas](https://p5js.org/reference/#/p5/filter) and one for [images](https://p5js.org/reference/#/p5.Image/filter). The documentation for the canvas filter method has a description of the different filter types and what the filterParam means for each type. The image filter docs are missing this description, but reference it as "see above".

**Comment by rt1301** [comment]
@limzykenneth @montoyamoraga @seldomU  Is this issue open? I would like to work on this if possible

**Comment by montoyamoraga** [comment]
hi @seldomU thanks for pointing it out,
@rt1301 thanks for offering working on it, of course, i will go ahead and assign you

**Comment by rt1301** [comment]
@montoyamoraga Would it be better to transfer this issue to the p5.js-website repository? cause it looks like an issue regarding the website documentation.

**Comment by limzykenneth** [comment]
The documentation for p5.js is written as inline comments and maintained along side the source code so this issue fits better here. You can have a read about how it works [here](https://github.com/processing/p5.js/blob/main/contributor_docs/inline_documentation.md).
