### ISSUE TITLE
loadJSON not reading URL

### ISSUE THREAD

**Issue by EunieceHarris** [processing/p5.js#5047]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other (specify if possible)

#### Details about the bug:

- p5.js version: 
- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

**Comment by montoyamoraga** [comment]
hi @EunieceHarris :)

i went to the URL and it's supposed to return some data from Giphy, but it was empty,
so there must be something wrong on the URL

also, keys are like passswords and they are supposed to be private,
i suggest continuing using your current one for testing, and then deleting it and creating a new one,
so that it continues being secure :)

could you please redirect your question to our forum?
https://discourse.processing.org/
that's the place where it's easier to find people to help with code,
and i'm almost sure that the problem is on the Giphy query, not p5.js
i hope that helps ~

**Comment by montoyamoraga** [comment]
hey @EunieceHarris i tried some of the Giphy API examples again,
and i noticed how on the docs the parameters are in a very particular order,
and then i double checked your query, and i tried with inverting, first the api key, then the query,
and it worked, now i see data as a result, so it should be easy to parse with p5.js yay :)
https://api.giphy.com/v1/gifs/search?api_key=3G13FDn952JRiNJhIGeOaJS4GSk2YscJ&q=sweden

**Comment by EunieceHarris** [comment]
Interesting. Everytime I use loadJSON with another API, I still get the same error message. Here's another one for example:

`function setup() {
  // createCanvas(400, 400);
  loadJSON("http://api.open-notify.org/astros.json", gotData, 'jsonp');
}

function gotData(data) {
  console.log(data);
}

function draw() {
  //background(220);
}`

**Comment by EunieceHarris** [comment]
Thanks for your help though. I'll post my question in the forum as instructed.

**Comment by montoyamoraga** [comment]
@EunieceHarris thanks for understanding, 
here we try to make the code and the documentation,
and the forum it's easier to navigate, and all the discussions over there
make it easier for everyone to use and share :)

i fixed several things on your code, including:
* updated from "var" to "let"
* you are doing noCanvas(), so i deleted the background() call
* you were trying to parse it as "jsonp", it needs to be "json"
* your API call has two parameters, the api key and the query: the first one goes after the "?", and the next ones are concatenated with "&", and in your code you had both starting with an ampersand and that broke it
let api = "https://api.giphy.com/v1/gifs/search?";
let apiKey = "api_key=3G13FDn952JRiNJhIGeOaJS4GSk2YscJ";
let query = "q=sweden";
let url;

function setup() {
  noCanvas();
  url = api + apiKey + "&" + query;
  loadJSON(url, gotData, 'json');
}

function gotData(giphy) {
  print(giphy.data.length);
for (let i = 0; i < giphy.data.length; i++) {
  createImg(giphy.data[i].images.original.url);
  }
}

function draw() {

}

**Comment by EunieceHarris** [comment]
Hopefully, this is my last question. Why use 'let' instead of 'var'? Thanks again!

**Comment by montoyamoraga** [comment]
i think this article explains it well
https://www.freecodecamp.org/news/var-let-and-const-whats-the-difference/
when i started with JavaScript we used var, and now i use let for variables
and const for constants, i hope that helps!
