### ISSUE TITLE
Add 'step' attribute to createInput() function

### ISSUE THREAD

**Issue by briansostek** [processing/p5.js#5050]
### How would this new feature help [increase access](https://github.com/processing/p5.js/blob/main/contributor_docs/access.md) to p5.js?
This feature will allow coders to implement number type input that supports decimal numbers or floating point numbers.

#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [x] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Feature enhancement details:

Add optional third parameter to createInput() that allows user to edit the step attribute which allows for precision in number inputs. this way, decimals can be added to inputs that allow strictly numbers.

**Comment by limzykenneth** [comment]
The step attribute can be added with the [`attribute()`](https://p5js.org/reference/#/p5.Element/attribute) method in `p5.Element`.

**Comment by lmccart** [comment]
As @limzykenneth points out in https://github.com/processing/p5.js/issues/5050#issuecomment-782607376 I think the `attribute` method covers this. Additionally, please take a look at the [access statement](https://github.com/processing/p5.js/blob/main/contributor_docs/access.md), I feel like I need more info to understand how your current response addresses the groups listed.

**Comment by DavidWeiss2** [comment]
It helps people without prior coding experience have a more consistent coding environment to find all the variables passed to a slider as functions.

I think that a consistent environment will also help people that speak other languages.
