### ISSUE TITLE
mediaElement.time(time) returns to beginning not to specified time

### ISSUE THREAD

**Issue by dgrantham01** [processing/p5.js#5051]
- [x] Other Video media Element

#### Details about the bug:

- p5.js version: 1.1.9
- Web browser and version: Chrome Version 88.0.4324.182 (Official Build) (x86_64)
- Operating System: MacOSX 11.2
- Steps to reproduce this:

The p5.MediaElement.time() command when given a time in seconds should jump the video to the specified time. Instead it jumps back to the beginning i.e. time = 0. See reference: https://p5js.org/reference/#/p5.MediaElement/time 

I checked to make sure that the video was completely loaded before trying the jump just to make sure there wasn't any error with the full duration being unavailable. I also checked different video formats.

This code will play and stop a video with a mouse press and `"PATH"` is replaced with a path to a video.

It should reproduce the issue when a key is pressed and the video is playing.

```javascript
let video;
let playing = false;
let dur = -1;

function preload()
{
	video = createVideo("PATH", () => {dur = video.duration();});
}

function setup() 
{
  createCanvas(800, 600);
  video.hide();
}

function draw() 
{
  image(video, 0, 0, width, height)
}

function mousePressed()
{
	if(playing)
	{
	video.pause();
	playing = false;
	}
	else
	{
	video.play();
	playing = true;
	}
}

function keyPressed()
{     
      let t = float(random() * 15.0);
      video.time(t);
}
```

It might it is related to how the value in `video.time(t)` is passed into `currentTime` method of the html video media element.

A couple previous issues referenced this command, but were working with scrubbing the video:
#1020, #1082

This is my first error report so, hopefully not wasting anyone's time.

**Comment by limzykenneth** [comment]
For me the reference example seems to be working correctly, do you have your example code running somewhere (the p5.js web editor for example) that we can run with the video you are using?

**Comment by dgrantham01** [comment]
Weird. I uploaded the sketch to  https://thedanielgrantham.com/p5VideoTest/index.html and it seems to be working. It must be something with the media command from the python simple http server I was running it through locally. Thank you for your help.
