### ISSUE TITLE
Sound Library not working

### ISSUE THREAD

**Issue by partyshah** [processing/p5.js#5053]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version: 1.2.0
- Web browser and version: Chrome 88.0.4324.150
- Operating System: MacOS
- Steps to reproduce this:

1) Download p5.js complete
2) open index.html

![image](https://user-images.githubusercontent.com/25253905/108777153-3a237800-7518-11eb-988e-e7cb9f45e56c.png)

I was hoping to use p5 to play around with sound visualization, but so far can't even get anything to load. Am I doing something wrong? Do I need to add something

**Comment by montoyamoraga** [comment]
hi @partyshah
please refer to our getting started guide,
in particular the section about setting a local server,
https://p5js.org/get-started/
or i recommend using our web editor instead, best!
