### ISSUE TITLE
Add documentation for p5.Camera properties

### ISSUE THREAD

**Issue by AndrewAung11** [processing/p5.js#5056]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Feature enhancement details:
Want the code to give info about the camera position. Like `camera.x`, `camera.y` and `camera.z` which will really make camera object useful.

**Comment by Aloneduckling** [comment]
@stalgiag, I think we should have a function(`getPosition`) that will return the position of the Camera and the up vector values as an object. Similar to [this].(https://github.com/processing/p5.js/blob/c1640a7cb11c25145e9b9dd561ba27f7b49fcde4/test/unit/webgl/p5.Camera.js#L7) 
Users can then access those values and use them as per their needs.
PS: I would like to work on this.

**Comment by stalgiag** [comment]
Hi @AndrewAung11 you can get these with the `centerX`, `centerY`, `centerZ` properties of the camera object. For example:

```js
let cam;

function setup() {
  createCanvas(400, 400, WEBGL);
  cam = createCamera();
  print(cam.centerX);
}
```

That might be necessary @Aloneduckling . It also might just be an issue of documentation. For example, the reference for [p5.Camera](https://p5js.org/reference/#/p5.Camera) doesn't mention the `centerX, centerY, centerZ, eyeX, eyeY, eyeZ, upX, upY, upZ` properties of camera object.

**Comment by AndrewAung11** [comment]
Thanks @stalgiag.

**Comment by Aloneduckling** [comment]
@stalgiag, So should I go ahead and code the above function?
As for the documentation problem, I guess we should open an issue. I will do so after your confirmation.

**Comment by stalgiag** [comment]
Hi @Aloneduckling I am not sure that it makes sense to add this function. It would give an object with properties that are already directly accessible on the camera object. I think we should instead just make it more clear in the documentation that these properties exist on the camera object.

**Comment by Aloneduckling** [comment]
@stalgiag, I agree that adding this function would be overdoing it. Updating the documentation makes more sense. I will update the docs and create a PR.

**Comment by Aloneduckling** [comment]
@stalgiag, I have added these lines to the p5.Camera documentation.
![image](https://user-images.githubusercontent.com/54030684/109630132-9155c800-7b6a-11eb-8876-e79ca866901a.png)

is this ok?

**Comment by stalgiag** [comment]
@Aloneduckling that is very nicely written but it might be better to list the properties with their own entries similar to how it is done with the [p5.Image reference](https://p5js.org/reference/#/p5.Image). You can see how [these are added here](https://github.com/processing/p5.js/blob/main/src/image/p5.Image.js#L90).

**Comment by Aloneduckling** [comment]
@stalgiag Thanks. Also, the description for the properties is already given in the [camera](https://p5js.org/reference/#/p5/camera) reference with detailed examples, so should I add an extra line with the link to it or should I write the entries separately.

**Comment by stalgiag** [comment]
I think it still makes sense to add the properties to the `p5.Camera` documentation separately. Those values are listed as parameters for the `camera()` function in the camera reference but this doesn't make it clear that when you create a `p5.Camera `with `createCamera()`, the resulting object will have those properties. `camera()` does not return a `p5.Camera` so there is a pretty big detachment between these two concepts for someone browsing the documentation.

**Comment by Aloneduckling** [comment]
Ok, I will add the properties separately.

**Comment by Aloneduckling** [comment]
@stalgiag, I have some properties please have a look, if this is okay then I will finish with the rest.
![image](https://user-images.githubusercontent.com/54030684/109931602-0f42dc00-7cef-11eb-960b-190a4cb5e02c.png)

![image](https://user-images.githubusercontent.com/54030684/109931621-136ef980-7cef-11eb-9c04-5b97dca24454.png)

![image](https://user-images.githubusercontent.com/54030684/109931626-14a02680-7cef-11eb-97c3-587676214953.png)

**Comment by Aloneduckling** [comment]
Update: For now I have added the following example which outputs a `div` with the contents of `centerX/Y/Z` properties and I did the same for `upX/Y/Z` properties.

![image](https://user-images.githubusercontent.com/54030684/110073961-5d66e680-7da6-11eb-9b34-d4a5e4fc0b3c.png)

**Comment by stalgiag** [comment]
Great job @Aloneduckling. The way that you are adding documentation looks good. The examples should be read-only. There are methods in place for setting these values that are safer. For example, the centerX, Y, Z docs can show the output for current camera center coordinates when the canvas is being manipulated by `orbitControls()` that way someone can see how they might read these values in a useful way in their sketch.

**Comment by Aloneduckling** [comment]
@stalgiag thanks, I will now create a PR after adding the necessary changes.
