### ISSUE TITLE
loadJSON() sometimes returns an empty object.

### ISSUE THREAD

**Issue by lemon-man125** [processing/p5.js#5066]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [x] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version: v1.1.9
- Web browser and version: 88.0.4324.190
- Operating System: Windows 10
- Steps to reproduce this:
```javascript
function loadData() {
    return new Promise((res, rej) => {
      const newData = [];
      const json = loadJSON(data);
      const keys = Object.keys(json);
      // This returns an empty object sometimes.
      print(keys);
      // Trying to turn json into an array. but keys is empty because of the object
      for (const key of keys) {
        newData.push(json[key]);
      }
      this.trainData = newData;
      res();
    })
}
```

**Comment by Prateek93a** [comment]
@lemon-man125  According to documentation [here,](https://p5js.org/reference/#/p5/loadJSON) `loadJSON` is an asyncronous method, you need to supply a callback to it.

**Comment by limzykenneth** [comment]
Hi @lemon-man125, as @Prateek93a mentioned, `loadJSON()` is an asynchronous method, meaning that there is no guarantee in the order in which the loading is done and the execution of subsequent code. If the server is fast in returning the requested data (or if the data is cached by the browser) then the return value of `loadJSON()` may be present when executing code after it, but if the data take even a faction of a second to return, code running after `loadJSON()` will only see an empty object.

You should either use `loadJSON()` in a `preload()` function to ensure any code executed in `setup()` or `draw()` is run after `loadJSON()` has completed or as @Prateek93a suggests, use a callback function to handle the returned data.

If you need further help with this, do direct your questions to the [forum](https://discourse.processing.org). Thanks!
