### ISSUE TITLE
applyMatrix() should be able to take in an array of values

### ISSUE THREAD

**Issue by msub2** [processing/p5.js#5067]
### How would this new feature help [increase access](https://github.com/processing/p5.js/blob/main/contributor_docs/access.md) to p5.js?
This feature would help simplify the process of dealing with matrix data that is already represented by an array of values, allowing the user not to have to worry about passing each value of the matrix individually or knowing how to spread the array.

#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Feature enhancement details:
`applyMatrix()` should be able to take a an array of 6 or 16 values (corresponding to a 2x3 or 4x4 matrix) in addition to the separate parameters it does currently. For a practical example, I'm currently working on a way to easily access pose data from the WebXR API for p5.xr, as can be seen here stalgiag/p5.xr#115 . Pose data is stored on XRRigidTransform.transform.matrix as a Float32Array, holding the 16 values corresponding to the 4x4 matrix. Being able to pass the array directly would allow me to simplify the necessary function calls to draw tracked controllers down to this:
```js
const right = getXRInput(RIGHT);
if (right != null) {
    push();
    fill(255, 255, 255);
    applyMatrix(right.pose);
    box(.15);
    pop();
}
```

Tagging @stalgiag by request.

**Comment by stalgiag** [comment]
Thank you for this well-written issue @msub2 !

For context, this is something that I have wanted to do for a while. This is useful when reading pose data from input sources in p5.xr but it also makes sense as a change for p5 more generally. Currently, you cannot pass in an array as an argument despite the fact that this function takes 6 or 16 parameters of the same type (number). This can quickly prove frustrating.
