### ISSUE TITLE
Project not visible

### ISSUE THREAD

**Issue by MikeMaksy** [processing/p5.js#5070]
Hi there!

#### Most appropriate sub-area of p5.js?

- [x] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version: 1.2.0
- Web browser and version: Chrome
- Operating System: MacOS

I'm having an issue with displaying content on my website that I've created in p5.js. I've had no issues before this instance, all of my work is visible except for one. The only difference between this one project and my previous works, is that its supported by version 1.2.0.  May be important to mention that I would also edit these in Adobe Dreamweaver without issue, except in the case involving this one project. It would simply not display, whether it be in Dreamweaver or in Chrome. One other thing that may be important to mention is that all of my other projects are supported by version 0.10.2 and lower.  

Links: http://mikemaksy.co.uk/gallery_generative_art_static.html

It's the latest one at the very bottom. Thank you.

**Comment by two-ticks** [comment]
It is working in firefox. For running in chrome try removing `<script src="./Abstract Quad Pattern_files/p5.sound.min.js.download"></script>` from index.html 
![code](https://user-images.githubusercontent.com/68433541/110270334-9b088100-7feb-11eb-95be-1a9410f3ecf0.jpg)
![result](https://user-images.githubusercontent.com/68433541/110270339-9cd24480-7feb-11eb-9988-f17ed9b5ec4e.jpg)

**Comment by MikeMaksy** [comment]
It works fine in Firefox, as well as Safari. It's Chrome and Dreamweaver it doesn't seem to like.

**Comment by two-ticks** [comment]
It ran in chrome after I removed `p5.sound.min.js` library.

**Comment by MikeMaksy** [comment]
Yep, working now. Thanks for your help.
