### ISSUE TITLE
saveTable() not working in 1.2.0

### ISSUE THREAD

**Issue by maartenwijntjes** [processing/p5.js#5080]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [x] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version: https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.2.0/p5.js
- Web browser and version: Safari Version 14.0
- Operating System: MacOSX/
- Steps to reproduce this:

I found that saveTable() is not working anymore in 1.2.0. The easiest way to reproduce this is to run the code from https://p5js.org/reference/#/p5/saveTable in the editor.p5js.org. When you change the p5 version into 1.1.0 in the html file it does work. 

    let table;
    
    function setup() {
    table = new p5.Table();
 
    table.addColumn('id');
    table.addColumn('species');
    table.addColumn('name');
    
    let newRow = table.addRow();
    newRow.setNum('id', table.getRowCount() - 1);
    newRow.setString('species', 'Panthera leo');
    newRow.setString('name', 'Lion');
    
    // To save, un-comment next line then click 'run'
     saveTable(table, 'new.csv');
    }

**Comment by maartenwijntjes** [comment]
Same happens in Chrome (and is also resolved when using 1.1.0), and error message is:

_p5.js says: An error with message "table.rows[i].arr[j].includes is not a function" occured inside the p5js library when saveTable was called (on line 86 in about:srcdoc [about:srcdoc:86:2])_

**Comment by KarthikSundar2002** [comment]
Can I give this bug a shot? It is my first time working in this codebase

**Comment by limzykenneth** [comment]
This seems to be fixed in 1.3.0 (just released). @maartenwijntjes Can you test with 1.3.0 can confirm if it is fixed?

**Comment by maartenwijntjes** [comment]
Yes worked! I did have to change it manually into 1.3.0 at the editor.p5js.org, do you have an idea when this will be standard? Or should I go over and ask at 'p5.js-web-editor'? Thanks anyway for the quick fix!

**Comment by limzykenneth** [comment]
I'm not as involved with the development of the web editor but you can head over to the web editor repository and see if they have a set policy around how and when they update the default p5.js version (maybe by searching existing issues first).
