### ISSUE TITLE
Include VS Code Live Server Extension on "Local server" Wiki Page

### ISSUE THREAD

**Issue by stungeye** [processing/p5.js#5082]
### How would this new feature help [increase access](https://github.com/processing/p5.js/blob/main/contributor_docs/access.md) to p5.js?

The wiki includes [local HTTP server instructions for the Brackets and Sublime Text editors](https://github.com/processing/p5.js/wiki/Local-server). Adding server instructions for VS Code will make local p5.js development easier for VS Code users. The Live Server VS Code extension is also a good alternative to the Chrome Extension for those using other browsers. Switching editors or browsers to use p5.js locally may be a barrier for new coders.

#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other: Wiki Page Update

#### Feature enhancement details:

I propose adding the following to the [Local server wiki page](https://github.com/processing/p5.js/wiki/Local-server).

#### VS Code Live Server

Using the [Live Server extension for VS Code](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer) we can easily run a development web server for any local folder. 

**Instructions:**

- Open the VS Code extension manager (`CTRL-SHIFT-X` / `CMD-SHIFT-X`) 
- Search for and install the [Live Server extension](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer).
- Add a p5.js project folder to your VS Code Workspace.
- With your project's `index.html` or `sketch.js` file open, start the Live Server using the "Go Live" button in the status bar, or by using `ALT-L` `ALT-O`.

Your sketch should now open in your default browser at location: `127.0.0.1:5500`

####  VS Code Project Generator

Another handy VS Code extension is [p5.vscode](https://marketplace.visualstudio.com/items?itemName=samplavigne.p5-vscode) which includes a project generator, an easy way to install contributor libraries, and adds p5.js autocompletion support. 

To create a new project using the p5.vscode extension:

- Create a new folder for your sketch using the terminal or file explorer.
- Open the VS Code command pallet (CTRL-SHIFT-P) and type `Create p5.js Project`.
- Select your newly created project folder. _(A p5.js project will now be automatically downloaded to this folder.)_
- [Optional] Open the command pallet again and type `Install p5.js Contributor Library` to install extra libraries.

**Comment by lmccart** [comment]
Thanks @stungeye I've made the changes. I added a note about the vs code generator, but not the full instructions as this didn't seem directly related to a local server, and the page is already a bit unwieldy.

**Comment by stungeye** [comment]
Wowzers. What a fast turn around on an issue! Thanks @lmccart for this and for everything you and the community do for this project. Much appreciated.
