### ISSUE TITLE
I'd like to do a 1.3.1 release soon?

### ISSUE THREAD

**Issue by outofambit** [processing/p5.js#5092]
after we merge https://github.com/processing/p5.js/pull/4642, does anyone mind if i do a release 1.3.1 to get that bugfix out _and_ to give myself an easy to way to make sure https://github.com/processing/p5.js-website/pull/935 works properly (once its also merged)?

if i don't hear any objections in the next week (by Mar 21), i'll assume no one minds and i'll do it :)

cc @limzykenneth @lm-n @lmccart @stalgiag as people i can think of off the top of my head who might have feelings :)

**Comment by limzykenneth** [comment]
I'd like #5081 to be resolved by the next version as it is resolving a breaking change, though can't really give a timeline for it yet so if it's not realistic we can go ahead with 1.3.1 first.

**Comment by outofambit** [comment]
@limzykenneth i'm happy to wait until that's in too! i'll make a milestone! 🙀

**Comment by lmccart** [comment]
This all makes sense to me, thanks @outofambit and @limzykenneth!

**Comment by outofambit** [comment]
just did this! (albeit slightly on accident, see https://github.com/processing/p5.js/issues/5133)
