### ISSUE TITLE
Shift key not being released

### ISSUE THREAD

**Issue by tallalnparis4ev** [processing/p5.js#5104]
#### Most appropriate sub-area of p5.js?

- [] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [x] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version: p5.js v1.2.0
- Web browser and version: Chrome 89.0.4389.82
- Operating System: MacOSX 10.15.6 (Catalina)
- Steps to reproduce this: Hold down the shift key, then proceed to take a screenshot on Mac (shift+command+4), release the shift key. Result: p5.js thinks the shift key is still held down, even though it's not.

**Comment by stalgiag** [comment]
Hi @tallalnparis4ev welcome and thanks for reporting an issue. Can you provide a simple example of code that causes this bug so we can try to reproduce it on our end?

**Comment by tallalnparis4ev** [comment]
Hello @stalgiag 👍 

```
function setup() {
  createCanvas(400, 400);
}

function draw() {
  background(220);
}


function keyPressed() {
  if(key == "Shift") console.log("Pressed");
  return false;
}

function keyReleased() {
  if(key == "Shift") console.log("Released");
  return false;
}
```

Then immediately do shift+command+4. Release the shift key, and the console output should be only "Pressed" and no "Released".

**Comment by stalgiag** [comment]
@tallalnparis4ev thanks!

I am unable to reproduce in Chrome v 89.0.4389.90 with p5 1.2.0 running on Mac 11.2.1. If my focus is on the canvas, I see both pressed and released logged even when the shift key press is used for a screenshot. Perhaps there is something specific about how the screenshot command events are captured on Catalina.

**Comment by lmccart** [comment]
@tallalnparis4ev I think if you release the shift key in the context of screen capture on OSX, the key events are then captured by the screen capture program and not accessible via p5. So you see the keypressed before the screen capture program is activated, but the keyreleased gets captured. I don't think we can fix this via p5 because it's at a lower OS level than p5 has access to.
