### ISSUE TITLE
https://p5js.org/reference/#/p5/splice is confussing

### ISSUE THREAD

**Issue by JimBrink** [processing/p5.js#5124]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other (specify if possible)   documentatation 

The documentation for splice is very confusing. How does one use array.splice?  It doesn't talk about removing elements from an array which is possible in Javascript.

**Comment by stalgiag** [comment]
p5 splice is deprecated. To remove elements from an array, pass the starting index and number of elements to remove. The [linked MDN documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/splice#remove_1_element_at_index_3) explains it well.

I am closing this for organizational purposes.
