### ISSUE TITLE
No example given for beginShape(TESS)

### ISSUE THREAD

**Issue by TsgabiXD** [processing/p5.js#5125]
This issue has already been mentioned:
https://github.com/processing/p5.js/issues/3672

#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [x] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version: p5.js v1.2.0 December 19, 2020
- Web browser and version: Microsoft Edge | 89.0.774.57
- Operating System: Windows 10
- Steps to reproduce this:

```
function setup() {
  createCanvas(800, 800, WEBGL);
}

function mouseOnCanvas() {
  return mouseX > 0 && mouseX < width && mouseY < height && mouseY > 0;
}

function makeSine(relStart = -width / 2, absEnd = height, amplitude = 200, wavelenght = 0.025, heightOffset = 0, resolution = 10) {
  for (let i = 0 + relStart; i <= absEnd; i++) {
    if (i % resolution === 0) vertex(i, Math.sin(i * wavelenght) * amplitude + heightOffset);
  }
}

function makeSineReverse(absEnd, relStart, amplitude, wavelenght, heightOffset, resolution = 10) {
  for (let i = 0 + relStart; i >= absEnd; i--) {
    if (i % resolution === 0) vertex(i, Math.sin(i * wavelenght) * amplitude + heightOffset);
  }
}

function drawShape() {
  let relStart = -200,
    absEnd = 300,
    amplitude = 50,
    wavelenght = 0.017,
    top = -150,
    bottom = 150,
    resolution = 20; // the lower the better
    
  beginShape();
  makeSine(relStart, absEnd, amplitude, wavelenght, top, resolution);
  makeSineReverse(relStart, absEnd, amplitude, wavelenght, bottom, resolution);
  endShape(CLOSE);
}

function draw() {
  background(0);
  strokeWeight(4);
  stroke(255);
  noFill();
  // noStroke();
  fill(255, 0, 0);

  drawShape();
}
```
![image](https://user-images.githubusercontent.com/66643584/112429899-a541b380-8d3d-11eb-81ab-ac339d5ff759.png)

**Comment by stalgiag** [comment]
Implicit tesselation for custom shapes was causing issues with other behavior. As of #4147, explicit tesselation by writing `TESS` as the parameter for `beginShape(TESS)` is required. Your example works as expected with this.

Perhaps a `TESS` example for [the beginShape reference](https://p5js.org/reference/#/p5/beginShape) is in order. This could be a good issue for someone interested in contributing.

**Comment by TsgabiXD** [comment]
Oh sorry.

**Comment by stalgiag** [comment]
Hi @TsgabiXD no need to be sorry! I am reopening your issue because it was helpful in indicating that we should likely document this behavior a little better in the examples for `beginShape`.

**Comment by TsgabiXD** [comment]
Thank you.

**Comment by ShenpaiSharma** [comment]
Hi @stalgiag, I would like to work on this

**Comment by ShenpaiSharma** [comment]
Hi, @stalgiag @montoyamoraga; I have added an example and also added some descriptions. Please check if it is okay:

![image](https://user-images.githubusercontent.com/47415702/112733037-98060e00-8f63-11eb-8367-1d27f783d1e7.png)

Description:

![image](https://user-images.githubusercontent.com/47415702/112733047-aa804780-8f63-11eb-8717-a31ee7795f9b.png)

**Comment by lmccart** [comment]
@ShenpaiSharma looks great! would you like to submit a pull request with this addition?
