### ISSUE TITLE
Adding node module to p5.js 

### ISSUE THREAD

**Issue by cenkakay08** [processing/p5.js#5126]
Hi everyone. I'm working on bin packing project. I want to use node module to placement of rectangles. 

Node module that I want to use:  https://www.npmjs.com/package/rectangle-bin-pack

Is there any tutorial or document to about adding node modules? If this is not the place to ask these questions, I apologize right now. Thanks already for your help. Have a nice day.

**Comment by montoyamoraga** [comment]
hi @cenkakay08!
the right place for asking code related questions is our forum
https://discourse.processing.org/
here we try to discuss issues, bugs, and enhancements,
and maybe in the forum somebody else already has your solution
:)
