### ISSUE TITLE
array shuffle 

### ISSUE THREAD

**Issue by ekeneijeoma** [processing/p5.js#513]
it'd be great to have a shuffle function for for arrays like 
```javascript
//+ Jonas Raoni Soares Silva
//@ http://jsfromhell.com/array/shuffle [v1.0]
function shuffle(o){ //v1.0
    for(var j, x, i = o.length; i; j = Math.floor(Math.random() * i), x = o[--i], o[i] = o[j], o[j] = x);
    return o;
};
```

**Comment by GoToLoop** [comment]
Nice 1-line `for ()` solution there! But here's 1 hopefully lil' more understandable:  :P
```js
// p5.js/src/data/array_functions.js

p5.prototype.shuffle = function(arr) {
  var idx = arr.length;
  while (idx > 1) {
    const rnd = Math.random()*idx | 0, tmp = arr[--idx];
    arr[idx] = arr[rnd], arr[rnd] = tmp;
  }
  return arr;
}
```

**Comment by GoToLoop** [comment]
Another 1 more similar to yours. And a better candidate I s'pose:  ^_^
```js
    // p5.js/src/data/array_functions.js
    
    p5.prototype.shuffle = function(arr) {
      for (var rnd, tmp, idx = arr.length; idx > 1;
        rnd = Math.random()*idx | 0,
        tmp = arr[--idx], arr[idx] = arr[rnd], arr[rnd] = tmp);
      return arr;
    }
```

**Comment by ekeneijeoma** [comment]
Didn't mean for it to be 1 line I just copied the highest ranked 1 on stackoverflow ;)

**Comment by ipeluffo** [comment]
Can anyone confirm me if this issue was resolved? 
I'd like to contribute to the project and I'm able to add the feature requested by @ekeneijeoma 

For support, the algorithm proposed is a very famous one called Fisher–Yates shuffle.
Please, see the following links:
* [Wikipedia](http://en.wikipedia.org/wiki/Fisher%E2%80%93Yates_shuffle)
* http://bost.ocks.org/mike/shuffle/

**Comment by GoToLoop** [comment]
What a coincidence. I was just finishing last details in order to pull request!
This is what I've got so far. I guess it's alright:
```js
// https://github.com/lmccart/p5.js/tree/master/src/data/array_functions.js
// https://github.com/lmccart/p5.js/issues/513

  /**
   * Randomizes the order of the elements of an array.
   *
   * @method shuffle
   * @param  {Array}   array  Array to shuffle
   * @param  {Boolean} [bool] Modify passed array
   * @return {Array}   Shuffled array
   */

  p5.prototype.shuffle = function(arr, bool) {
    arr = bool || ArrayBuffer.isView(arr)? arr : arr.splice();

    for (var rnd, tmp, idx = arr.length; idx > 1;
      rnd = Math.random()*idx | 0,
      tmp = arr[--idx], arr[idx] = arr[rnd], arr[rnd] = tmp);

    return arr;
  };
```

But I'm gonna take a look at this new algorithm ASAP and check whether it's faster!  :D

**Comment by GoToLoop** [comment]
It seems very like current implementation! So its real name is Fisher-Yates or Knuth Shuffle Method!

**Comment by GoToLoop** [comment]
Made a pull request of the above here: https://github.com/lmccart/p5.js/pull/528

**Comment by lmccart** [comment]
closed with https://github.com/processing/p5.js/pull/528
