### ISSUE TITLE
windowWidth and windowHeight do not work on Chrome

### ISSUE THREAD

**Issue by Michal8705** [processing/p5.js#5130]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version: v1.2.0 
- Web browser and version: 87.0.4280.141
- Operating System: iOS 13.7
- Steps to reproduce this:

Hi
I ran into a problem in the code below, which I display on iPhone 7

![image](https://user-images.githubusercontent.com/62724357/112721809-44b1a280-8f06-11eb-8b94-432d5604df61.png)

When opening a page https://editor.p5js.org/Michal8705/embed/5zKzMLXgw in chrome, the page loads correctly
![1](https://user-images.githubusercontent.com/62724357/112723053-fb188600-8f0c-11eb-9d4d-81974a84d542.jpg)

but after turning the device, the effect is as below
![2](https://user-images.githubusercontent.com/62724357/112723086-23a08000-8f0d-11eb-8e34-cd1a14922ddd.jpg)

after turning it over again
![3](https://user-images.githubusercontent.com/62724357/112723160-79752800-8f0d-11eb-8fee-f14227a9f53d.jpg)

and again
![4](https://user-images.githubusercontent.com/62724357/112723169-86921700-8f0d-11eb-9a5a-05a5d649a681.jpg)

When I open a website in safari, there is no problem, maybe apart from overlapping the toolbar as below when I touch and move the display
![5](https://user-images.githubusercontent.com/62724357/112723380-7169b800-8f0e-11eb-9808-682d0cf03bde.jpeg)

In this case i can use location.reaload(), but in real project, I will lose all variable values

Does anyone know how to solve this problem or maybe a fix in p5 is needed? 
Unless it's more of a chrome fault?

**Comment by limzykenneth** [comment]
If this is only happening in a specific browser, it is more likely an issue with the browser itself than with p5.js

**Comment by Michal8705** [comment]
It seems like you wrote limzykenneth. I checked the code on several other devices and the problem only occurs in Chrome. 

I think the only thing left is to make an exception in the code when using Chrome. Maybe i will try:
document.documentElement.clientWidth
document.documentElement.clientHeight

**Comment by DavidWeiss2** [comment]
> It seems like you wrote limzykenneth. I checked the code on several other devices and the problem only occurs in Chrome.
> 
> I think the only thing left is to make an exception in the code when using Chrome. Maybe i will try:
> document.documentElement.clientWidth
> document.documentElement.clientHeight

Or to open an issue on the browser repo.

**Comment by limzykenneth** [comment]
Closing as not directly related to p5.js
