### ISSUE TITLE
How can you get the current location coordinates when using the push/pop method?

### ISSUE THREAD

**Issue by jiameng123** [processing/p5.js#5147]
e.g:

`    
 push();  
rotate(r1); 
 line(0,0, 0, prevY- 10); 
 pop();
`

I called the lien method within the push/pop method, it works, how do I get the x1, y1, x2, y2 coordinate information in the line method correctly?

**Comment by lmccart** [comment]
@jiameng123 you would need to track and transform these coordinates yourself, there's no method for this. for more help with this please check out our forum: https://discourse.processing.org/
