### ISSUE TITLE
Impossible to set stroke shader without also setting fill shader

### ISSUE THREAD

**Issue by stalgiag** [processing/p5.js#5148]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

While investigating #5129, I realized that custom stroke shaders always become the custom fill shader. This is because [`isStrokeShader()`](https://github.com/processing/p5.js/blob/main/src/webgl/p5.Shader.js#L511) returns false on the very first frame because the uniforms have not been loaded into the Shader object yet. This causes [`RendererGL.userFillShader`](https://github.com/processing/p5.js/blob/main/src/webgl/material.js#L260) to be set to the stroke shader. Since it isn't reset every frame, the fill shader will be the custom stroke shader unless manually changed.

There are a few issues at play here. The primary one is that `p5.Shader` objects don't load uniforms during preload. They actually load them during binding. This is fine except we are checking uniforms to determine the type of shader it is.

This could potentially be fixed by initializing the shader object before decrementing the preload but that might cause more problems. Another idea is that we might want to introduce the use of `FILL`, `POINTS`, and `LINES` for the custom shaders in the same way that Processing has. We also might want to consider a different way of auto-detecting the shader type if we want that second argument to be optional.

Thoughts anyone? Maybe @kjhollen or @aferriss?

- p5.js version: latest
- Web browser and version: all
- Operating System: all
- Steps to reproduce this:
[https://editor.p5js.org/stalgia.grigg/sketches/DVQKZTPFS](https://editor.p5js.org/stalgia.grigg/sketches/DVQKZTPFS)

**Comment by aferriss** [comment]
> This could potentially be fixed by initializing the shader object before decrementing the preload but that might cause more problems.

Also, `createShader()` is often used inside of setup, so I think this would cause a problem there as well. Is there a better way to check what kind of shader it is rather than using the uniforms?

I don't know enough about what desktop Processing is doing with the FILL, POINTS, LINES optional param. Is it kind of like setting the gl primitive mode?

**Comment by stalgiag** [comment]
Hi @aferriss !

That optional parameter is for setting which geometry to apply the custom shader to. So you could theoretically have a custom line/stroke shader but still use the default fill shader. Currently, p5 tries to autodetect this but that isn't working properly.

I can't think of a better way to tell what the intended geometry is for the shader. Checking uniforms seems like the only way but also that applies unnecessary constraints as well. For ex I don't think that a custom stroke shader should absolutely need a `uStrokeWeight` uniform. This is why it might make sense to require the optional param when doing anything except FILL.

**Comment by stalgiag** [comment]
Resolved by #5286
