### ISSUE TITLE
move to github p5.js organization

### ISSUE THREAD

**Issue by lmccart** [processing/p5.js#515]
hey all, I'm preparing for an imminent move to a github organization to house this repo, as well as the one for p5js.org. https://github.com/p5xjs.

seems like everything should stay intact, you may just need to update your remotes if you're pointing to this one. but if anyone sees any potential issues with this, please holler! :)

**Comment by shiffman** [comment]
one thing that tripped us up when moving Processing to github were the issues (since they are separate from the repo).   Maybe the github issues API has more capabilities now but we ended up using the https://github.com/processing-bugs user to re-post all the issues via the API.  I can try to dig this up, I think @prisonerjohn may recall the steps?

**Comment by shiffman** [comment]
Another option is to leave this repo for existing issues and file new ones at p5.js org. Eventually these will all get closed and then this repo can get locked and exist purely for historical purposes.

**Comment by lmccart** [comment]
reading this: https://help.github.com/articles/transferring-a-repository/, it seems like issues will transfer? maybe this has been changed since the processing move.

**Comment by lmccart** [comment]
ah maybe the difference with processing was that you were coming from google code (I think?), so in this case, yes, the issues are separate. but I think if you transfer within github, they have a system for preserving these.

**Comment by shiffman** [comment]
oh awesome, great!

**Comment by prisonerjohn** [comment]
Right, if I remember correctly, it was both because we were coming from svn and Google Code.

**Comment by kadamwhite** [comment]
Why `p5xjs` and not `p5js`?

**Comment by GoToLoop** [comment]
I 2nd that. p5js seems much better! The `x` seems outta place!

**Comment by lmccart** [comment]
the organization name matches the twitter handle (twitter.com/p5js was taken): twitter.com/p5xjs

more generally, it is a bit of a branding thing. the asterisk replaces the dot in the logo to represent two things—P5 and JS—coming together, multiplying in force. each page of the website has a different play on this idea, using the word "times" to reference the asterisk in the logo. (for example http://p5js.org/get-started/)

**Comment by GoToLoop** [comment]
Does GitHub accepts `*` like p5*js?  :-?

**Comment by lmccart** [comment]
only alphanumeric and dashes :\

**Comment by lmccart** [comment]
as you can see, p5.js and p5.js-website are now under the processing organization. make sure to update your remotes if you are pointing to either of these using git.
