### ISSUE TITLE
LGPL restriction

### ISSUE THREAD

**Issue by ivorylover** [processing/p5.js#5150]
I will handle a commercial project which hope to use p5.js library，we need use P5 engine to render P5 material  in webview. but this library it is licensed under the LGPL, would I have to open source just the combined library file or the complete project, or none of it?

**Comment by lmccart** [comment]
Hi @ivorylover I don't know the details of your particular case but hopefully [this resource](https://tldrlegal.com/license/gnu-lesser-general-public-license-v2.1-(lgpl-2.1)#:~:text=This%20license%20mainly%20applies%20to,license%20them%20under%20LGPL%2D2.1.&text=The%20LGPL%20prohibits%20sublicensing%2C%20yet,modify%20and%20distribute%20the%20work.) is helpful:
