### ISSUE TITLE
Friendly error message not displayed 

### ISSUE THREAD

**Issue by Aloneduckling** [processing/p5.js#5152]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [X] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:
When a user overwrites p5.js's inbuilt function displays a non-friendly error message. 
![img](https://user-images.githubusercontent.com/54030684/113406536-4200f280-93c9-11eb-96c8-a25e7d68d92d.png)

This can be easily converted to a friendly error message by passing message to `p5._friendlyError()` method.
- p5.js version: 
- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

```
function createCanvas(){
    console.log(`hello`);
}
function setup() {
  createCanvas(400, 400);
}

function draw() {
  background(220);
}
```
We can replace createCanvas with any of the inbuilt p5.js function.
PS: I would like to wok on this

**Comment by Aloneduckling** [comment]
I have done the changes and will create a PR upon confirmation.
Here are the screenshots for the same:
![image](https://user-images.githubusercontent.com/54030684/113407302-a4a6be00-93ca-11eb-930c-292545ba3638.png)

Here the 1st message is the friendly error message, the second was the original.

**Comment by limzykenneth** [comment]
You can go ahead and file the PR. Thanks.

**Comment by Aloneduckling** [comment]
@limzykenneth
When I am committing the changes in my local repo, I am getting this message:
`Error: Cannot find module '../docs/reference/data.min.json'` 
I figured out that this file is missing from my local repo, I had cloned this repo earlier which did contain these files I copied it to the clone which I am working with currently and the pre-commit tests passed. I wanted to mention this to confirm if this is okay? and what is the solution for this error because this is the first time I am encountering this error?

PS. I have closed my PR because I wanted to discuss this.

**Comment by limzykenneth** [comment]
It depends on the final diff with the main branch here. If the diff looks clean then it's probably fine. In this case there probably shouldn't be a diff for `data.min.json` and as long as that file doesn't exist in the diff when filing a PR, there should be no problem.

**Comment by Aloneduckling** [comment]
@limzykenneth, I found the reason for the error. The reference folder was not generated because I didn't run tests after making the changes to the code which resulted in pre-commit errors. running `npm test` or `npm run grunt` will fix this and generate the reference folder.
