### ISSUE TITLE
angleMode not saved/restored by push/pop

### ISSUE THREAD

**Issue by bobcgausa** [processing/p5.js#5160]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [X ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [X ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

My library sets angleMode to degrees, which can have side effects if user has set it to radians.
You might say, ok reset to radians after use, but what if user had set to degrees?
Two fixes:
Have angleMode return previous angleMode so i can save and restore
or
Save/restore angleMode in push/pop

**Comment by stalgiag** [comment]
Hi @bobcgausa ! Thanks for the issue. I agree that `angleMode` should be captured by `push` and `pop`. [Here is an example](https://editor.p5js.org/stalgia.grigg/sketches/s_liZIXG8) that shows the problem.

**Comment by DavidWeiss2** [comment]
I would love to try to fix it.
Do I need to both change:
p5.Renderer.js
p5.Renderer2D.js
p5.RendererGL.js
?

**Comment by bobcgausa** [comment]
The rule is that library methods should not have side effects, such as changing angleMode, unless the changes are documented.

Since angleMode is a math function, the update should not be restricted to push/pop.
The reason is that a math library function should not have to call push/pop to save the environment.
Thus, in addition to push/pop change, angleMode should return the previous angleMode.


________________________________

**Comment by DavidWeiss2** [comment]
So maybe we will add an option to add functions to a push()/pop().
Like:
```js
push.add(angleMode)
```
and the life span of this function will be until a
```
push.remove(angleMode)
```
Will be called.

This will also give an option to exclude a state, like color() you don't want the push/pop to affect.

**Comment by stalgiag** [comment]
Unless I am misunderstanding something, you should be able to add `angleMode` to [the properties returned by `p5.Renderer.push`](https://github.com/processing/p5.js/blob/main/src/core/p5.Renderer.js#L67) to get the expected behavior.

**Comment by bobcgausa** [comment]
But still forces math only funcs to use mostly graphic push popPersonally, I would just change AngleMode to return previous modeOn Apr 12, 2021 9:43 AM, David Weiss ***@***.***> wrote:
So maybe we will add an option to add functions to a push()/pop().
Like:
push.add(angleMode)
and the life span of this function will be until a
push.remove(angleMode)

Will be called.
This will also give an option to exclude a state, like color() you don't want the push/pop to affect.

**Comment by DavidWeiss2** [comment]
So how do you want to address it?

**Comment by bobcgausa** [comment]
Adding return to anglemode affects noone and can be added immediately.I would get more opinions on any push changeOn Apr 12, 2021 10:17 AM, David Weiss ***@***.***> wrote:

So how do you want to address it?

**Comment by limzykenneth** [comment]
Adding a return to `angleMode()` call without argument should be a doable solution.
