### ISSUE TITLE
`globalCompositeOperation` and `shadowBlur` together not likely working on windows+firefox

### ISSUE THREAD

**Issue by smrnjeet222** [processing/p5.js#5162]
with `shadowBlur = 0` it works. So it seems windows+firefox doesn't like `globalCompositeOperation` and `shadowBlur` together. I don't know if it's related but quick search showed this:
https://stackoverflow.com/questions/34028717/canvas-shadow-with-globalcompositeoperation-destination-out

_Originally posted by @micuat in https://github.com/processing/p5.js/issues/4403#issuecomment-640077275_

**Comment by smrnjeet222** [comment]
Firefox 87.0 (64-bit)  on Windows 10 20H2

https://github.com/processing/p5.js/issues/4403#issue-585898291


| `shadowBlur = 0`  | `shadowBlur > 0` | 
| --------------- | --------------- | 
| <img src="https://user-images.githubusercontent.com/48654626/113602613-73472000-9660-11eb-8638-b4b8a740a545.png" /> | <img src="https://user-images.githubusercontent.com/48654626/113602902-e0f34c00-9660-11eb-95b9-a0ef4d57c83e.png" />|

**Comment by limzykenneth** [comment]
Is this the same issue as #4403 or is this documenting something else?

**Comment by smrnjeet222** [comment]
It's similar, but I think this issue is more specific to `shadowBlur` behavior in firefox  on windows 10

**Comment by micuat** [comment]
I don't see any difference from #4403. closing...

**Comment by limzykenneth** [comment]
@smrnjeet222 That is what the original issue is about so there's no need to open another issue. Thanks.
