### ISSUE TITLE
createCapture documentation layout is broken

### ISSUE THREAD

**Issue by seldomU** [processing/p5.js#5166]
The code examples for [createCapture](https://p5js.org/reference/#/p5/createCapture) are increasingly indented, so that only the first one is actually readable. Tested on current Firefox and Chrome.

**Comment by limzykenneth** [comment]
The second and third example sketches for `createCapture` should probably have the `norender` class on its container `div` as the canvas created is larger than 100x100.

**Comment by SanjaySinghRajpoot** [comment]
> The second and third example sketches for `createCapture` should probably have the `norender` class on its container `div` as the canvas created is larger than 100x100.

Currently, the `createCapture` div has a `notest` class I think changing it with `norender` class will work out for this issue. If yes, then I would love to fix this issue. Otherwise, please suggest changes for this bug.

**Comment by Aloneduckling** [comment]
@SanjaySinghRajpoot, no need to remove `notest` class just add `norender` class.
``` 
<div class = 'notest norender'>
```
this should work

to read more you can check the [inline documentation](https://github.com/processing/p5.js/blob/main/contributor_docs/inline_documentation.md)

**Comment by SanjaySinghRajpoot** [comment]
ok got it. I would like to work on this issue. Could you please assign this task to me. Thanks 😀

**Comment by Aloneduckling** [comment]
@SanjaySinghRajpoot, I cannot assign tasks, I am not a member. You can just work on the issue right away.
