### ISSUE TITLE
code in the fract() page in reference section is not properly shown

### ISSUE THREAD

**Issue by two-ticks** [processing/p5.js#5169]
- Steps to reproduce this: Go to [https://p5js.org/reference/#/p5/fract](https://p5js.org/reference/#/p5/fract)

The code of the sketch is not properly shown due to `createCanvas(windowWidth, windowHeight);` in the sketch (code is slightly visible on the right corner). I have also tested in firefox and edge, it is showing the same behavior in them as well.

#### Screenshots:
![image](https://user-images.githubusercontent.com/68433541/114310526-98c4a580-9b08-11eb-9a7f-2f899942c97e.png)
![image](https://user-images.githubusercontent.com/68433541/114310593-d7f2f680-9b08-11eb-8fb2-eef393cf9086.png)

#### Details about the bug:

- Web browser and version: Chrome 89.0.4389.114 
- Operating System: Windows 10

I would like to work on this.

**Comment by lmccart** [comment]
thanks @two-ticks I have assigned you
