### ISSUE TITLE
Sample needed to play multiple sound files one after the other with a specific BPM

### ISSUE THREAD

**Issue by Benoit1980** [processing/p5.js#5170]
Well done for making this very complex library.

I would like to know if you could kindly add a sample that shows how to play files within a synched BPM.

ie:
Let's say you have 5 files:
a.wav
b.wav
c.wav
d.wav
e.wav

How to play them as :
a.wav | b.wav | c.wav | d.wav | e.wav

At let's say a bpm of 120?

This would be great to have a tiny example showing how to do this please.

Thanks

**Comment by paulcanning** [comment]
Are you wanting to play then at a set BPM, e.g. a.wav is 140BPM, but you want to play it at 120BPM?

Or, are you just asking how to play a.wav, then b.wav, then c.wav... etc?

**Comment by Benoit1980** [comment]
Thank you for the reply.

To be honest, both, but having the files playing as your second example would be a good start:
_"Or, are you just asking how to play a.wav, then b.wav, then c.wav... etc?"_

**Comment by paulcanning** [comment]
Add the filenames to an array, and use this https://p5js.org/reference/#/p5.SoundFile/onended to grab the next filename in the array when the previous audi file ends.

**Comment by paulcanning** [comment]
As for the bpm, the play() method has a rate parameter, that might work to some extent? Best bet is to read up and experiment with the sound library

**Comment by Benoit1980** [comment]
thank you so much, I will give it a shot this week end as I am doing it with my kids, trying to have a bit of fun :-)

**Comment by paulcanning** [comment]
For the most part, the documentation is great and the p5js web editor makes experimentation super easy and quick.

**Comment by Benoit1980** [comment]
Sorry for the delay in replying to you but unfortunately, I cannot try the solution. I can't get P5 to work in vue.js, keep getting 👍 "ReferenceError: loadSound is not defined"

**Comment by paulcanning** [comment]
You might want to share some code if you want some help. Initial thought is that p5 soubd is not being loaded in. Its a separate library, so make sure it's included in your project
