### ISSUE TITLE
Add dist(vector1,vector2)

### ISSUE THREAD

**Issue by DavidWeiss2** [processing/p5.js#5173]
### How would this new feature help [increase access](https://github.com/processing/p5.js/blob/main/contributor_docs/access.md) to p5.js?

It would help shortness the code written and help to simplify the code for beginners.

#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [x] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Feature enhancement details:
Add static and not static versions of dist for vectors.
Non-static:
```
let v1 = createVector(1, 0, 0);
let v2 = createVector(0, 1, 0);
let distanceBetween= v1.dist(v2)
```
Static:
```
let v1 = createVector(1, 0, 0);
let v2 = createVector(0, 1, 0);
let distanceBetween= dist(v1, v2)
```

**Comment by limzykenneth** [comment]
This feature already exist (https://p5js.org/reference/#/p5.Vector/dist), unless you are thinkingg of something else?

**Comment by DavidWeiss2** [comment]
I totally missed it. I saw only this reference:
https://p5js.org/reference/#/p5/dist

Maybe an edit to the reference page of both pages will help new people (like me) to notice both options.

**Comment by lmccart** [comment]
@DavidWeiss2 if you'd like to submit a PR with a note on the reference pages please do.

**Comment by DavidWeiss2** [comment]
Thanks. I will do that.
