### ISSUE TITLE
Background image with alpha not working as expected

### ISSUE THREAD

**Issue by paulcanning** [processing/p5.js#5175]
Using the following simply code, the alpha parameter simply has no effect

```
function setup() {
    ...
    bg = loadImage('bg.jpg');
    ...
}

function draw() {
    ...
    background(bg, 10);
    ...
}
```

If you replace `bg` in `background()` with a colour value, you see trails on screen, which is correct, but with the image, there are no trails, effectively, the alpha value doesn't work. You can test this by changing the alpha value to anything and there is no difference. I tried ranges 0-1, and 0-255.

NB - this issue, https://github.com/processing/p5.js/issues/1906, was closed, with @limzykenneth stating `background()` could not accept an image, which is false, proven by the fact you can indeed load an image using `background()` and the documentation even states you can use an image and an alpha value.

**Comment by paulcanning** [comment]
So, either the documentation is incorrect, or its correct and someone forgot to write this feature properly

https://github.com/processing/p5.js/blob/374acfb44588bfd565c54d61264df197d798d121/src/core/p5.Renderer2D.js#L49-L51

The alpha argument is simply disregarded when loading an image. 🤦

**Comment by two-ticks** [comment]
I tried the same and read the [documentation](https://p5js.org/reference/#/p5/background), it mentions `background(image, [a])`. It is not working properly. I would like to work on this issue if you are not working on it.

**Comment by JalokimFreelance** [comment]
I guess the easy fix would be just using tint() before using image().
https://p5js.org/reference/#/p5/tint

**Comment by lmccart** [comment]
@two-ticks great, I will assign you

**Comment by Palaksharma23** [comment]
Can I work on this issue , if no one is working on it. I would love to work on this issue .

**Comment by paulcanning** [comment]
@Palaksharma23 this was already assigned to someone if you look at the activity log

**Comment by two-ticks** [comment]
Hi @Palaksharma23! I am working on this issue in PR #5225. I have fixed the problem partially (not optimized), it would be great if you can fix the issue. If you have any improvements or want it to be reassigned to you, you can ask maintainers on the PR (#5225).
