### ISSUE TITLE
blend mode not working properly on graphics

### ISSUE THREAD

**Issue by wxyEquation** [processing/p5.js#5179]
#### Most appropriate sub-area of p5.js?

- [x] Color
- [x] Core/Environment/Rendering

#### Details about the bug:

- p5.js version: tested on 1.3.1 and 1.2.0
- Web browser and version: chrome 90.0.4421.5
- Operating System: Windows
- Steps to reproduce this:

Setting erase strength to a low value and using it repeatedly cannot fully erase the graphics.

The issue occured when I tried to do a fast trailing effect, I used a graphic object with no background to store the trail and made it gradually fading out by repeatedly using erase(). However there is always something left.

I also tried other method including blendMode(REMOVE) and drawingContext.globalCompositeOperation, but it still doesn't work.

For composite operation set to 'destination-in' and using background() with a high alpha value to do the erase, there is a particularly interesting behaviour: if I try to use print(get()) to log out the actual value of the graphics, the bug disappeared. But for 'destination-out' combined with a low alpha valued background, it will always left something. 

here is the [code](https://editor.p5js.org/wxyEquation/sketches/IZBuRxYBJ) to reproduce this
```
function setup() {
  createCanvas(400, 400);
  gr = createGraphics(400, 400); 
  gr.fill(55, 240, 160);
  gr.noStroke();
}

function draw() {
  background(26, 60, 115);
  gr.circle(mouseX, mouseY, 20);
  gr.drawingContext.globalCompositeOperation = 'destination-in';
  gr.background(0, 250);
  gr.blendMode(BLEND);
  image(gr, 0, 0);
  
  //if you comment out this line, there will be trail
  print(gr.get(20, 20));
  
}
```

Also here is the [fomulas](https://drafts.fxtf.org/compositing-1/#porterduffcompositingoperators_dstin) I found for the blend mode:

- co: output color
- Cb: destination color
- αo: output alpha
- αb: destination alpha
- αs: source alpha

destination-in:
> co = αb x Cb x αs
> αo = αb x αs

destination-out:
> co = αb x Cb x (1 – αs)
> αo = αb x (1 – αs)

**Comment by limzykenneth** [comment]
If it is happening also when using `globalCompositeOperation`, it probably should be considered a problem with the browser itself and not something p5.js can fix.

**Comment by wxyEquation** [comment]
further testing shows that the issue also occurred on plain canvas.
It could be originated from the float point precision problems of the alpha value. Nevertheless it is out of concern for p5 library.
