### ISSUE TITLE
French localization for p5js.org

### ISSUE THREAD

**Issue by LEMIBANDDEXARI** [processing/p5.js#5180]
### How would this new feature help [increase access](https://github.com/processing/p5.js/blob/main/contributor_docs/access.md) to p5.js?

Translation of the site https://p5js.org in French, to facilitate its use by the French-speaking community.

#### Most appropriate sub-area of p5.js?

- [X] Localization

**Comment by limzykenneth** [comment]
On a personal note, I'm currently working on some research into translation on open source software and will probably need some help/perspectives of people working on translations as part of my research. If you are interested to be involved (will most probably be working on p5.js related materials), do let me know and I'll contact you with more details when available.

**Comment by LEMIBANDDEXARI** [comment]
Always a pleasure to help if the project pleases me, I await your news to present me the thing.
As for p5js, I will do an unofficial translation as you suggest.

**Comment by LEMIBANDDEXARI** [comment]
To follow the unofficial French translation of p5.js -> https://github.com/LEMIBANDDEXARI/p5js-unofficial-french-translation/blob/main/READMEus.md
While waiting for a response from the official p5.js team.

**Comment by limzykenneth** [comment]
@LEMIBANDDEXARI Sorry for the late follow up. Can I please have your email address so that I can send you some details about the research project I would like your help with? If you don't feel comfortable sharing your email address publicly you can email me at limzy.kenneth@gmail.com and we can continue there. Thanks!

**Comment by LEMIBANDDEXARI** [comment]
Hello, the unofficial French translation of p5js.org is on its way.
V1.0.0-alpha is now available on https://p5js-unofficial-french-translation.vercel.app
For the moment there is only the home page which has been translated, I will continue to do the other pages soon.
I tried to respect the UI design of the site as much as possible.
If you have any comments, I am listening. ❤️
(https://github.com/LEMIBANDDEXARI/p5js-unofficial-french-translation)

**Comment by limzykenneth** [comment]
@outofambit @Qianqianye I never really looked into it but it seems we may not have a page listing all unofficial translations (or it is too hidden). Would be great to collect those that we know of and list them as promised.

**Comment by Qianqianye** [comment]
Thanks @LEMIBANDDEXARI for translating the website and @limzykenneth for offering feedback! I have added your website to the [Externally hosted language versions](https://github.com/processing/p5.js-website#externally-hosted-language-versions) section of the p5.js-website README, along with other external hosted translated p5.js websites. Please open an issue at [p5.js-website](https://github.com/processing/p5.js-website) GitHub repo if you'd like to update the credit. We are planning to add the externally hosted language versions to the p5.js website at some point soon and will keep you posted.

For future reference, issues about p5js.org website will be a better fit at the [p5.js-website](https://github.com/processing/p5.js-website) GitHub repo.

**Comment by Qianqianye** [comment]
@all-contributors please add @LEMIBANDDEXARI for translation
