### ISSUE TITLE
Issue with setting default text-leading after textSize() and textFont()

### ISSUE THREAD

**Issue by JalokimFreelance** [processing/p5.js#5181]
### How would this new feature help [increase access](https://github.com/processing/p5.js/blob/main/contributor_docs/access.md) to p5.js?
Would make documentation about text less confusing.

#### Most appropriate sub-area of p5.js?

- [x] Accessibility (Web Accessibility)

#### Feature enhancement details:
If we use textLeading(value1), and then use textSize(value2), it will change current text leading. It isn't mentioned in documentation of these functions. In textLeading() documentation there is even something that suggest opposite behavior:
"This setting will be used in all subsequent calls to the text() function.", which is wrong in this situation since textSize() behavior is overwriting textLeading().
```js
        textLeading(25);
        console.log(textLeading()); //shows text leading 25
        textSize(100);
        console.log(textLeading()); //shows text leading 125
```

A small enhancement, I might add this to documentation myself, if needed.

**Comment by limzykenneth** [comment]
Good find. @dhowe Can you perhaps confirm the intended behaviour here and if the documentation do indeed need to be updated @JalokimFreelance you can file a PR with a fix then. Thanks.

**Comment by JalokimFreelance** [comment]
Sure, waiting for confirmation then :)

**Comment by dhowe** [comment]
So I believe this is actually a bug (nice find @JalokimFreelance)
We want to use a default leading when set a new font, or change textSize, _only_ if it has not been set before
The bug is that it is always being done now.

**Comment by dhowe** [comment]
PR #5186 should resolve this, using the user-set leading value regardless of whether a new font or size is set. This means that, in the example 1 above, the leading will stay at the user-set value of 20, even when the font size is changed to 100. And in example 2, the leading will stay at the user-set value of 20 for all 3 fonts.

**Comment by limzykenneth** [comment]
@dhowe That sounds good to me and seems intuitive as well (not much stuff happening in the background automatically). I'll have a look at the PR.
