### ISSUE TITLE
Update the Hindi contributor docs README.md  

### ISSUE THREAD

**Issue by Rahulm2310** [processing/p5.js#5182]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [x] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:
The contributor docs Hindi README.md file of is out of sync with the latest English README.md. It needs to be updated.

- p5.js version: v1.3.1
- Web browser and version: Google Chrome | 89.0.4389.128

- Operating System: Windows
- Steps to reproduce this:

Compare [Hindi Readme.md](https://github.com/processing/p5.js/blob/main/contributor_docs/hi/README.md) with [English Readme.md](https://github.com/processing/p5.js/blob/main/contributor_docs/README.md)

**Comment by Rahulm2310** [comment]
I would like to work on this 🙂

**Comment by limzykenneth** [comment]
@Rahulm2310 Go ahead, I'll assign the issue to you. Thanks.
