### ISSUE TITLE
I can't use await in instance mode

### ISSUE THREAD

**Issue by wilkerpaiva** [processing/p5.js#5189]
![Sem título](https://user-images.githubusercontent.com/81369225/115121056-119f8380-9f87-11eb-8505-8cfbb49fed60.png)

Everything in the code below is working less the async function with await in the instance mode. The Chrome console is **returning the fallowing error: Uncaught (in promise) ReferenceError: faceapi is not defined.** 

I think the error might be something in how I'm using the p5 elements in instance mode.

```javascript

// Este projeto não utiliza o método global do p5.js, mas o modo instaciado onde posso criar mais de uma sketch no mesmo projeto, me permitindo criar várias
// camadas de elementos de mídias com diferentes funções que no modo global geraria conflitos pois não pode haver dois canvas dentro de uma mesma sketch.

// Início da instância videoLoop() [a primeira instancia]. videoLoop() é sketch principal onde o video está em fullscreen e em loop. É a layer mais interna.

const videoLoop = p5 => {

// Inicio do carregamento das imagens e videos.
// As funções videoReady() e imageReady() são dois callbacks (vindos da função preload) que indicam que as imagens e os vídeos estão devidamente carregados.

  function videoReady() {
    console.log('Video is ready!!!');
  }

  function imageReady() {
    console.log('Image is ready!!!');
  }

  p5.preload = () => {
    img = p5.loadImage('imagens/load.png', imageReady);
    video = p5.createVideo('video/votosim.mp4', videoReady);
  }

// Fim do carregamento das imagens e videos.

// Preparando (setting up) os arquivos carregados na função setup() para serem exibidos posteriormente na função draw().

  p5.setup = () => {
    p5.w = window.innerWidth;
    p5.h = window.innerHeight;

    const canvas = p5.createCanvas(p5.w, p5.h);
    canvas.parent('mainVideo');
    p5.background(0);
    video.parent('mainCam');
    video.hide();
    video.volume(0);
  };

// desenhando as imagens na função draw. img = imagem de carregamento e video = video principal fullscreen e em loop.

  p5.draw = () => {
    p5.image(img, 0, 0, p5.w, p5.h);
    p5.image(video, 0, 0, p5.width, p5.height);
    
  }

// Função mousePressed é uma função p5.js. Quando algum botão do mouse é pressionado o vídeo inicia o loop.

  p5.mousePressed = () => {
    video.loop();
  }

// A função window.onresize é javascript + p5.js e utilizo para deixar o video responsivo (compativel com qualquer dispositivo).
// Essa função é um loop: sempre que a janela alterar a largura e a altura, o canvas e o vídeo se adequaram às novas medidas.

  window.onresize = function() {
    p5.w = window.innerWidth;
    p5.h = window.innerHeight;  
    p5.resizeCanvas(p5.w, p5.h);
    p5.background(0);
}  

};

// Fim da primeira instância videoLoop().

// webCam() é a segunda instância e esta sobreposta à primeira instância videoLoop().
// Essa instância é destinada para os elementos que irão aparecer em diferentes lugares da tela. Exemplo: no segundo 35 do vídeo irá aparecer uma caixinha
// com a webCam rodando a IA FaceAPI.

// Início da segunda instância webCam().

const webCam = p5 => {
  const MODEL_URL = 'libraries/face-api/weights/';
// Inicio do carregamento da câmera e video.
// As funções camReady() e videoGuideReady() são dois callbacks que indicam que o vídeo e a câmera estão devidamente carregados.

  // function videoGuideReady() {
  //   console.log('Video guide is ready!');
  // }


    videoGuide = p5.createVideo('video/votosim.mp4');
  

// Fim do carregamento.

// Preparando (setting up) os arquivos carregados na função setup() para serem exibidos posteriormente na função draw().
// Especificamente dentro do setup() dessa instância há duas variaveis diferentes (capture e camVid) para receber a mesma câmera. Fiz isso para contornar
// um problema do p5.js onde o método filter() só pode ser aplicado uma única vez (one way method) em um elemento desenhado no draw.

// O vídeo está declado como hide() pois não quero visualiza-lo, mas sim utilizar a timeline identica a da intância anterior para iniciar os eventos. 
  
  p5.setup = () => {
    videoGuide.hide();
    videoGuide.volume(0);

    const canvas = p5.createCanvas(640, 480);
    canvas.position(200, 200);

    vid = p5.createCapture(p5.VIDEO, async () => {
      await faceapi.loadSsdMobilenetv1Model(MODEL_URL)
      await faceapi.loadFaceLandmarkModel(MODEL_URL)
      await faceapi.loadFaceRecognitionModel(MODEL_URL)
      await faceapi.loadFaceExpressionModel(MODEL_URL)
      getExpression();
    });
    vid.size(640, 480);
    vid.hide();

  };

// Desenhando a câmera em dois lugares diferentes com dois diferentes filtros (invert e threshold).

  p5.draw = () => {

}

// Função mousePressed é uma função p5.js. Quando algum botão do mouse é pressionado o vídeo inicia o loop.

  p5.mousePressed = () => {
    videoGuide.loop();
  }

};

// Fim da segunda instância webCam().

const div = document.createElement("div");
div.id = 'webcam';
div.style.position = "absolute";
document.getElementById("mainVideo").appendChild(div);

const webCamDois = p5 => {
  
  // Inicio do carregamento da câmera e video.
  // As funções camReady() e videoGuideReady() são dois callbacks que indicam que o vídeo e a câmera estão devidamente carregados.
  
    function camReady() {
      console.log('Camera dois is ready!');
    }
  
    function videoGuideReady() {
      console.log('Video guide is ready!');
    }
  
    p5.preload = () => {
      videoGuide = p5.createVideo('video/votosim.mp4', videoGuideReady);
    }
  
  // Fim do carregamento.
  
  // Preparando (setting up) os arquivos carregados na função setup() para serem exibidos posteriormente na função draw().
  // Especificamente dentro do setup() dessa instância há duas variaveis diferentes (capture e camVid) para receber a mesma câmera. Fiz isso para contornar
  // um problema do p5.js onde o método filter() só pode ser aplicado uma única vez (one way method) em um elemento desenhado no draw.
  
  // O vídeo está declado como hide() pois não quero visualiza-lo, mas sim utilizar a timeline identica a da intância anterior para iniciar os eventos. 
    
    p5.setup = () => {
      videoGuide.hide();
      videoGuide.volume(0);
  
      const canvas = p5.createCanvas(1280, 720);
  
      capture = p5.createCapture(p5.VIDEO, camReady);
      capture.hide();
    };
  
  // Desenhando a câmera em dois lugares diferentes com dois diferentes filtros (invert e threshold).
  
    p5.draw = () => {
  
  // início da câmera capture.
  
  if (videoGuide.time() > 10) { 
    if (capture.loadedmetadata) {
      let c = capture.get(0, 0, 640, 480);
      p5.image(c, 200, 200);
      
    }
  }
  
  // Fim da câmera capture.
  
  }
  
  // Função mousePressed é uma função p5.js. Quando algum botão do mouse é pressionado o vídeo inicia o loop.
  
    p5.mousePressed = () => {
      videoGuide.loop();
    }
  
  };
  
  // Fim da segunda instância webCam().
  
  const divDois = document.createElement("div");
  divDois.id = 'webcamDois';
  divDois.style.position = "absolute";
  document.getElementById("webcam").appendChild(divDois);

var principal = new p5(videoLoop);
var elemento = new p5(webCam, div);
var elementoDois = new p5(webCamDois, divDois);
'''

**Comment by limzykenneth** [comment]
I don't see anywhere in your code where `faceapi` is defined and since that's the error Chrome is reporting you should check to make sure `faceapi` is defined somewhere in your code first.

**Comment by wilkerpaiva** [comment]
the code below (the code is from Joey Lee GitHub)  works nicely, but when adapted the code to instance mode of p5.js I had  that problem.

'''javascript

const MODEL_URL = '../libraries/face-api/weights/';
let vid;
let expression;
let btn;
let div;

// function preload() {
//     faceapi.loadSsdMobilenetv1Model(MODEL_URL)
//     faceapi.loadFaceLandmarkModel(MODEL_URL)
//     faceapi.loadFaceRecognitionModel(MODEL_URL)
//     faceapi.loadFaceExpressionModel(MODEL_URL)
// }

function setup() {
    textAlign(RIGHT);
    div = createDiv('<br> please wait while face-api models are loading...');
    
    createCanvas(640, 480).parent('myCanvas');
    
    // use an async callback to load in the models and run the getExpression() function
    vid = createCapture(VIDEO, async () => {
            await faceapi.loadSsdMobilenetv1Model(MODEL_URL)
            await faceapi.loadFaceLandmarkModel(MODEL_URL)
            await faceapi.loadFaceRecognitionModel(MODEL_URL)
            await faceapi.loadFaceExpressionModel(MODEL_URL)
            div.elt.innerHTML = '<br>model loaded!'
            getExpression();
    }).parent('myCanvas');
    vid.size(640, 480);
     //vid.hide();
}



async function getExpression(){
    expression = await faceapi.detectAllFaces(vid.elt).withFaceExpressions()
    getExpression()
}


function draw() {
    image(vid, 0, 0);
    background(0)
    // image(vid,0,0)
    // console.log(expression)
    if(expression){
        if(expression.length > 0){

        const {expressions} = expression[0]
        // div.elt.innerHTML = '';
        expressions.forEach( (item, idx) => {
            const {expression, probability} = item;
            fill(255)
            // text(`${expression}: ${probability}`, 20, idx*20 )
            textSize(12)
            text(`${expression}:`, 70, idx*20 + 20 )
            const val = map(probability, 0, 1, 0, width/2)
            rect(80, idx*20 +10 , val, 15)
            // div.elt.innerHTML += `${expression}: ${probability} <br>`
        })
        }
        
    }
}
'''

**Comment by wilkerpaiva** [comment]
> I don't see anywhere in your code where `faceapi` is defined and since that's the error Chrome is reporting you should check to make sure `faceapi` is defined somewhere in your code first.

the code below (the code is from Joey Lee GitHub) works nicely, but when adapted the code to instance mode of p5.js I had that problem.

'''javascript

const MODEL_URL = '../libraries/face-api/weights/';
let vid;
let expression;
let btn;
let div;

// function preload() {
// faceapi.loadSsdMobilenetv1Model(MODEL_URL)
// faceapi.loadFaceLandmarkModel(MODEL_URL)
// faceapi.loadFaceRecognitionModel(MODEL_URL)
// faceapi.loadFaceExpressionModel(MODEL_URL)
// }

function setup() {
textAlign(RIGHT);
div = createDiv('
please wait while face-api models are loading...');

createCanvas(640, 480).parent('myCanvas');

// use an async callback to load in the models and run the getExpression() function
vid = createCapture(VIDEO, async () => {
        await faceapi.loadSsdMobilenetv1Model(MODEL_URL)
        await faceapi.loadFaceLandmarkModel(MODEL_URL)
        await faceapi.loadFaceRecognitionModel(MODEL_URL)
        await faceapi.loadFaceExpressionModel(MODEL_URL)
        div.elt.innerHTML = '<br>model loaded!'
        getExpression();
}).parent('myCanvas');
vid.size(640, 480);
 //vid.hide();
}

async function getExpression(){
expression = await faceapi.detectAllFaces(vid.elt).withFaceExpressions()
getExpression()
}

function draw() {
image(vid, 0, 0);
background(0)
// image(vid,0,0)
// console.log(expression)
if(expression){
if(expression.length > 0){

    const {expressions} = expression[0]
    // div.elt.innerHTML = '';
    expressions.forEach( (item, idx) => {
        const {expression, probability} = item;
        fill(255)
        // text(`${expression}: ${probability}`, 20, idx*20 )
        textSize(12)
        text(`${expression}:`, 70, idx*20 + 20 )
        const val = map(probability, 0, 1, 0, width/2)
        rect(80, idx*20 +10 , val, 15)
        // div.elt.innerHTML += `${expression}: ${probability} <br>`
    })
    }
    
}
}
'''

**Comment by lmccart** [comment]
@wilkerpaiva we really need an isolated code snippet that demonstrates the problem in order to help here. otherwise, I would suggest posting on our forum for more general coding help: https://discourse.processing.org/

**Comment by limzykenneth** [comment]
@wilkerpaiva The latest code you provided also doesn't have `faceapi` defined anywhere so I can't really debug it. As mentioned it would be best if you can pare down the code to a minimal example that we can quickly read and run then we'll be able to isolate the issue better. Thanks.

**Comment by wilkerpaiva** [comment]
Hello, thanks for the answers and sorry for the delay in my response. I made two examples in p5.js Web Editor:

1. This one is working perfectly and uses global mode of p5.js (this code doesn't work here but the exactly same code is available on Joey Lee GitHub through this link [)](https://joeyklee.github.io/face-api-expressions-demo/webcam) -->>
link: [](https://editor.p5js.org/wilkertwitter/sketches/i_U2wGqzk)

2. And this one isn't working when I use instance mode -->>
link: [](https://editor.p5js.org/wilkertwitter/sketches/a34YbxOtB)

Both of them are pretty similar codes and they don't have `faceapi ` declared before the setup, but the first one works nice and the second one doesn't work and now, with p5.js Web Editor, appear this new warning: "'async functions' is only available in ES8 (use version: 8)" in lines 16 and 28.

Observations: The 1st code just work when I use a local server like WAMP and doesn't work when I try to run in Go Live extension from VScode and p5.js Web Editor (the same error appears for both). The 2st code doesn't work in WAMP, VScode or p5.js Web Editor. 

I'm trying to adapt the Joey Lee code to p5.js instance mode when this error happens.

thanks for the help!!

**Comment by wilkerpaiva** [comment]
> @wilkerpaiva we really need an isolated code snippet that demonstrates the problem in order to help here. otherwise, I would suggest posting on our forum for more general coding help: https://discourse.processing.org/

Oh, ok! If you guys think this topic isn't in the right place i can move to processing forum without any problems.

**Comment by outofambit** [comment]
> Oh, ok! If you guys think this topic isn't in the right place i can move to processing forum without any problems.

hey @wilkerpaiva yeah this is probably best answered in the forum, thank you for understanding! all the info you shared in https://github.com/processing/p5.js/issues/5189#issuecomment-823617021 would be great posted there. :)
