### ISSUE TITLE
WebRTC/getUserMedia video capture freezes app when pointed at very bright things?

### ISSUE THREAD

**Issue by jywarren** [processing/p5.js#5197]
OK, this is a really weird one and i'm sorry! It may also be upstream in Chrome but I couldn't reproduce it with another WebRTC/getUserMedia application (https://infragram.org/sandbox for example worked fine)

Basically very bright things such as daylight sky or bright lights freeze the app entirely, requiring a restart. But there are no errors in the console. I attached a video at the bottom...

I use WebRTC/getUserMedia a good bit and have never seen this. Any idea what's going on? 

Sorry for this mysterious one, I'm just hoping someone else has experienced this at some point!!

Thanks for all your hard work, i ❤️ ❤️ ❤️ ❤️  p5js!!!

****

#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [x] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other (specify if possible)

- Video capture

#### Details about the bug:

- p5.js version: http://editor.p5js.org/ (/*! p5.js v1.1.9 July 22, 2020 */)
- Web browser and version: Chrome 90.0.4430.82
- Operating System: Android 11 (Apr 5 security update) on a Pixel 3a
- Steps to reproduce this: Run code at https://editor.p5js.org/jywarren/present/1caq6OUtU (from https://editor.p5js.org/jywarren/sketches/1caq6OUtU) and point at a very bright light, like a cloudy sky during the day, or bike light on a white piece of paper
 

Video of this happening, and error console not showing anything!

https://user-images.githubusercontent.com/24359/115632558-007fab00-a2d6-11eb-8e68-f64ae2bec7ed.mp4

**Comment by jywarren** [comment]
If anyone can reproduce this on another devoce or browser that would maybe help narrow down what level the error happens at!

**Comment by jywarren** [comment]
Noting that this does NOT seem to happen with latest chrome desktop and a built-in iMac camera.

**Comment by jywarren** [comment]
Also tested on Chrome on a Samsung tablet and did not encounter this. I'm wondering if it is... device specific to Pixel phones?

**Comment by limzykenneth** [comment]
It seems from your descriptions to be a device specific problem, if that's the case I'm not sure how much we can fix on our end. One thing to test is whether this happens only with p5.js or video capture in browser in general.

**Comment by Qianqianye** [comment]
I'm closing this for organizational purposes. Please feel free to reopen this issue if you can provide more tests that illustrate the issue. Thanks!
