### ISSUE TITLE
Online discussion channel 

### ISSUE THREAD

**Issue by joeyouss** [processing/p5.js#5201]
### How would this new feature help [increase access](https://github.com/processing/p5.js/blob/main/contributor_docs/access.md) to p5.js?
Since there are a lot of people like me who would want to be a part of a more dynamic communication channel for p5.js, I think an online discussion channel on discord or slack would be really helpful.

#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ + ] Other (specify if possible) -> increased accessibility and better community

**Comment by lmccart** [comment]
hi @joeyouss have you checked out our [forum](https://discourse.processing.org/)?

**Comment by joeyouss** [comment]
> hi @joeyouss have you checked out our [forum](https://discourse.processing.org/)?

Yes I did, but could you provide any link for GSOD discussions and queries in particular? Couldn't find any tag related to in it the forum

**Comment by outofambit** [comment]
@joeyouss sorry for the delay here. you can use the [p5.js channel in the forum](https://discourse.processing.org/c/p5js) to ask questions about season of the docs. if you haven't seen https://github.com/processing/p5.js/wiki/Google-Season-of-Docs, make sure you take a look there too!

**Comment by joeyouss** [comment]
Thank you @outofambit !. In the process of making the proposal!
