### ISSUE TITLE
Difference between createinput() and rect() lengths

### ISSUE THREAD

**Issue by Michal8705** [processing/p5.js#5206]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [x] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version: v1.2.0 
- Web browser and version: 90.0.4430.85
- Operating System: Windows 10
- Steps to reproduce this:

Hi
I ran into a problem in the code below, which I display on my computer with windows 10 and chrome

![DOM1](https://user-images.githubusercontent.com/62724357/115999186-1f8a7f80-a5eb-11eb-85d0-009bb180d27a.PNG)

When I open the https://editor.p5js.org/Michal8705/embed/2NdEO4etP page, it shows that the DOM window of the element is longer than that of the rectangle I created.

![DOM2](https://user-images.githubusercontent.com/62724357/115998916-f1f10680-a5e9-11eb-9808-0caf2096210e.PNG)

Shouldn't these lengths be the same (100px)? Or is this situation correct?
I also checked on other browsers and the problem also occurs

**Comment by rt1301** [comment]
@Michal8705 I replicated your code and founded that the Rectangle is equal to 100px in width and height. The Web Browser adds some default margin and padding to all the elements and hence the actual dimension of the input tag is not 100x100 in size.
![image](https://user-images.githubusercontent.com/63252510/116048079-6c756100-a692-11eb-8f18-770d7f85d39a.png)

My above screenshot shows the actual computed size of the input tag on the browser.

**Comment by Aloneduckling** [comment]
@Michal8705 
@rt1301 is right. I wanted to add more info that would help you. 
```
//the below line of code will solve your problem
inp.style('box-sizing: border-box');
```
this is a CSS property default behavior of which is making the dimensions of the input element more than (100 X 100)px, so this is not a bug in p5.js but a default behavior of the input element. 
You can read about it [here](https://developer.mozilla.org/en-US/docs/Web/CSS/box-sizing).

You can ask questions like these in p5.js [forum](https://discourse.processing.org/) 

Thanks for opening this issue

**Comment by Michal8705** [comment]
@Aloneduckling 
Thanks for your help, Your code solved the problem and the link to the forum will definitely be useful for future.

@rt1301  
Thanks for the analysis and useful information
