### ISSUE TITLE
Adding Hindi translation of the README.md

### ISSUE THREAD

**Issue by Rahulm2310** [processing/p5.js#5208]
### How would this new feature help [increase access](https://github.com/processing/p5.js/blob/main/contributor_docs/access.md) to p5.js?
The README.md of the project is only available in English which makes it inaccessible to Hindi speakers. It is the first file one should read when getting started a project. By translating it in hindi, it will be accessible to hindi speakers who want to get started with the project.

#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [x] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### New feature details:
We can add translation files for README.md like `README.hi.md` and add links to these files in the english version so that visitors can go to their desired translation file. For example-
![image](https://user-images.githubusercontent.com/54268438/116214183-17098480-a764-11eb-8585-b3a9d60faef2.png)

**Comment by Rahulm2310** [comment]
@montoyamoraga @outofambit what do you say?

**Comment by montoyamoraga** [comment]
hi @Rahulm2310 thanks, it would be great to have it, but also i would prefer first to have a system so that if the english README.md changes, we have a notice for the translation that needs to be updated and where, does that make sense? :)

**Comment by Rahulm2310** [comment]
@montoyamoraga it completely makes sense. Although, I was searching a workaround for this but couldn't find a way to automate this process.

**Comment by montoyamoraga** [comment]
yeah it's tricky, let's see if other people can help ~

**Comment by Rahulm2310** [comment]
@lmccart @limzykenneth can you help us out here 🙂

**Comment by limzykenneth** [comment]
Sorry had been super busy.

We can emulate the tracking system used on the website repo that track git for changes to README.md as a git precommit step and track them in a separate file. The system is not elegant though. I have something potentially more useful but it'll take some time to realize.

**Comment by Qianqianye** [comment]
I'd like to pick up this conversation again about potentially adding translations of the main README.md file, like in issue #6158.  I agree that we should come up with a translation tracking system before we take in more translations. We tried to roll out a similar translation tracking system project idea for GSoC this year, but it wasn't ready. @limzykenneth, what could be a good next step to move this forward? Thank you!

**Comment by limzykenneth** [comment]
I find that the README.md document actually doesn't really change that much and also not very often. It may be fine to have translated versions of the README file for now without worrying about change tracking.

**Comment by Qianqianye** [comment]
Yes, I agree with you that the README file doesn't change much and we can probably go ahead without worrying about tracking the changes. Where should the translation files go? Should we start a new folder only for README translations?

The currently '[translations](https://github.com/processing/p5.js/tree/main/translations)' folder in the main menu is mostly for FES. I think we can rearrange the folder location to avoid confusion. I'm wondering if GSoC FES contributor @Ayush23Dash and mentors @almchung @nbriz have any thoughts on the location of the '[translations](https://github.com/processing/p5.js/tree/main/translations)' folder. Thank you!

**Comment by Ayush23Dash** [comment]
Yes I believe relocating the '[translations](https://github.com/processing/p5.js/tree/main/translations)' folder would make sense since, it acts as a source of confusion for someone new trying to add translations for Readme.
Also one suggestion : Now onwards whenever we create a translations folder for something specific, we could name it accordingly, for instance in this case, it could be : _**translationsForReadme**_

I could relocate the current translations folder, just need a confirmation on that!

**Comment by nbriz** [comment]
hey all, i'm still getting oriented w/the codebase, but it seems like the translations are already in a decent place (root directory of the repo) && nicely organized `translations/[lang]/translation.json`, but as @Qianqianye pointed out it seems the `translation.json` file is really only being used by FES at the moment, though it does seem that early on @outofambit (&& maybe other folks working on it) saw potential for this file to contain translations for various aspects of the library (i'm just inferring that from the structure of [the file 3 years ago](https://github.com/processing/p5.js/blob/68c8510d467882fd05d9663bd500fe39694b1b69/translations/en/translation.json) when the "fes" key/property was first introduced to the json file).

if we don't imagine the data getting too large, then placing all the translations in the `/translations/[lang]/translation.json` would be fine, but my guess (just from our FES convos) is that it can easily grow && might be best, as @Ayush23Dash suggested, to separate the data out into different files based on their concerns. my instinct is to keep these as .json files, so something like this (where "etc" is just a placeholder for other future files):

```
translations/
    en/
      fes.json
      etc.json
    es/
      fes.json
      etc.json
    etc/
      etc.json
```

**Comment by outofambit** [comment]
@nbriz hey! i'm honestly not sure why we put that `fes` key in the file. i think it may have been there since the first strings we added were taked out of the `fes.js` file, but then when i went to add more strings, it was all technically part of the friendly error system.

regardless, i agree a separate file or place of some kind for README translations would be best. i don't think we need to do a JSON for that, since its really all one text right? the main benefit of using a JSON file for translations is being able to pick out specific strings that aren't related so they can be used in code. however, i'm not doing active translation work on p5, so please feel free to disregard this if something about the translation workflow would be easier if we used JSON instead of a plain MD file or something else. :)

**Comment by nbriz** [comment]
@outofambit  i totally agree, JSON would be great for any i18n w/in the library itself (FES being the most obvious example), but README's should just remain MD files for sure

**Comment by Qianqianye** [comment]
Thank you all for your input on this issue. We are currently working on a project to reorganize and update the p5.js documentations, so we will temporarily pause the translation effort for the README.md until the documentation update is complete. To avoid any confusion, I will close this issue for now. We will revisit the issues labeled '[Documentation](https://github.com/processing/p5.js/labels/Documentation)' and '[Internationalization](https://github.com/processing/p5.js/labels/Internationalization)' later. 

CC @limzykenneth @davepagurek @nickmcintyre
