### ISSUE TITLE
angleMode() doesn't work in instance mode

### ISSUE THREAD

**Issue by topherbb** [processing/p5.js#5211]
I don't think angleMode() works in instance mode. I am very new here, so I don't know how much of a problem this is but I recently downloaded the p5.js template to my local hard drive, and I'm trying to run angleMode() but I keep getting an error message. It's not a huge deal for me (it should be a pretty easy math problem to solve) but I thought you might want to know!

sketch.js:17 Uncaught ReferenceError: DEGREES is not defined
    at p5.p.draw (sketch.js:17)
    at p5._main.default.redraw (p5.js:70718)
    at _draw (p5.js:63058)
p.draw @ sketch.js:17
_main.default.redraw @ p5.js:70718
_draw @ p5.js:63058
requestAnimationFrame (async)
_draw @ p5.js:63081
requestAnimationFrame (async)
_draw @ p5.js:63081
requestAnimationFrame (async)
_draw @ p5.js:63081
_runIfPreloadsAreDone @ p5.js:62935
_decrementPreload @ p5.js:62944
img.onload @ p5.js:80628
load (async)
(anonymous) @ p5.js:80618
Promise.then (async)
_main.default.loadImage @ p5.js:80582
(anonymous) @ p5.js:62961
p.preload @ sketch.js:6
_start @ p5.js:62917
load (async)
p5 @ p5.js:63275
(anonymous) @ sketch.js:49

**Comment by limzykenneth** [comment]
When you are using instance mode, constants like `DEGREES` need to be prefixed with the p5 object as well, eg:
```
p.angleMode(p.DEGREES)
```
