### ISSUE TITLE
A bolinha fica pendendo para direita usando o código abaixo: The ball hangs to the right using the code below:

### ISSUE THREAD

**Issue by Marcos-Vitor123** [processing/p5.js#5215]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [* ] Other (specify if possible)

#### New feature details:

let xBolinha = 300;
let yBolinha = 200;
let diametro = 15;

let velocidadeXBolinha = 6;
let velocidadeYBolinha = 6;

function setup() {
  createCanvas(600, 400);
}

function draw() {
  background(0);
  circle(xBolinha, yBolinha, diametro);
  xBolinha = xBolinha + 1;
  xBolinha += velocidadeXBolinha;
  yBolinha += velocidadeYBolinha;

  if (xBolinha > width || xBolinha < 0) {
  velocidadeXBolinha *= -1;
  }
  
  if (yBolinha > height || yBolinha < 0) {
  velocidadeYBolinha *= -1;
  }
  
}

**Comment by montoyamoraga** [comment]
hi @Marcos-Vitor123 for code questions please use our forum
at https://discourse.processing.org/
and follow the guidelines there, thanks!

**Comment by Marcos-Vitor123** [comment]
Muito obrigado! Consegui resolver meu problema. Era um erro em meu código
mesmo, por isso a bolinha pendia para a direita. Agora está tudo certo.
Thank you very much! I managed to solve my problem. It was an error in my
code, so the ball hung to the right. Now everything is fine.

Em qui., 29 de abr. de 2021 às 15:58, aarón montoya-moraga <
***@***.***> escreveu:
