### ISSUE TITLE
Typo in a p5.js reference page!

### ISSUE THREAD

**Issue by Brahvim** [processing/p5.js#5219]
https://github.com/processing/p5.js/blob/1250864d63e6353233789f0059f62ebe0188a2a5/src/core/environment.js#L664

The word 'editor' is misspelled.

I also have an improvement suggestion for the code on this page, where can I submit it? Do I create a new issue for it..? Can I mention it here? Thank you for helping! :D

**Comment by limzykenneth** [comment]
You can file a PR to fix the typo. For additional suggestions please open and new issue and fill out the issue template. Thanks.

**Comment by Brahvim** [comment]
Thank you for the help, @limzykenneth! Rhank you for helping with fixing the issue, @cryptochap and thank you, @montoyamoraga, for automatically closing the issue!~
