### ISSUE TITLE
Redesigning the p5.js website for better accessibility and documentation

### ISSUE THREAD

**Issue by cryptochap** [processing/p5.js#5222]
#### Most appropriate sub-area of p5.js?

- [x] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Feature enhancement details:
Hello contributors, I joined about p5.js project and for the past few weeks I have been navigating through and learning the internals of the project, I must it really cool but still finds its difficult getting my head around a lot of things on the page.  I think a redesign to accommodate better documentation is due to help new contributor.

**Comment by cryptochap** [comment]
Processing p5.js web page refactor and redesign

**Comment by Eric-co** [comment]
uhhh..... i dont understand a fuck about coding...Damn

**Comment by cryptochap** [comment]
> uhhh..... i dont understand a fuck about coding...Damn

 I believe you can learn in no time

**Comment by montoyamoraga** [comment]
hi, thanks! 
there is currently a big redesign in progress, 
and also i suggest starting with specific contributions in mind,
and some big projects we are currently looking for help are detailed here
https://github.com/processing/p5.js/wiki/Google-Season-of-Docs
:)

**Comment by cryptochap** [comment]
Ok @montoyamoraga its actually part of my proposal as means of contribution for GSoD. Thanks for the response
