### ISSUE TITLE
[Wiki] Google Season of Docs wiki page (broken) links

### ISSUE THREAD

**Issue by maxdevjs** [processing/p5.js#5227]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other (specify if possible)

#### Feature enhancement details:

Reading through [Google Season of Docs](https://github.com/processing/p5.js/wiki/Google-Season-of-Docs):

- broken link: [please post to the Processing Forum](https://discourse.processing.org/c/season-of-docs) -> `Oops! That page doesn’t exist or is private.`
- broken link: [adding comments inline to the code](https://github.com/processing/p5.js/blob/main/src/core/error_helpers.js) -> `page not found`

**Comment by outofambit** [comment]
hey @maxdevjs and @Rahulm2310, i've fixed both links on the wiki page. Thanks for flagging those! Let me know if anything else seems amiss.
