### ISSUE TITLE
Add image comparison tests

### ISSUE THREAD

**Issue by kevinbarabash** [processing/p5.js#523]
Maybe we can reuse processing-js' ref test suite but use selenium to control the browser.  Here's a link to the test suite I'm talking about: https://github.com/Khan/processing-js/tree/master/test/ref.  The image data is contain in a comment on the first line of each program.

**Comment by lmccart** [comment]
we've got some image comparison in there, you can see an example here:
https://github.com/lmccart/p5.js/blob/master/test/unit/shape/2d_primitives.js

here's the testRender function:
https://github.com/lmccart/p5.js/blob/master/test/js/testRender.js

the main issue was just the slowness of the tests, dealing with varieties between browser rendering, and the workflow of adding them. but happy to incorporate any improvements in this area!

**Comment by kevinb7** [comment]
Link to in-progress pull request https://github.com/lmccart/p5.js/pull/529.  The comments contain some ideas of how to address these issues.

**Comment by kevinb7** [comment]
I'm going to quote my comments here so that people don't have to click through to another page.

> @lmccart I know you were concerned about differences between browsers. One way to address that is to make sure that we always use the same browser to run the tests. I've had some experience using docker images with Firefox to do this. I set up the docker image with ubuntu, Firefox, and FreeType to match the versions on travis-ci. This way users can run the image compare tests locally regardless of what OS they're running on.

> This will allow use to do exact pixel comparisons which are more reliable. Before we can do this though we need a way to generate our own set of reference images because we have antialiasing on by default which doesn't match the current reference images which don't.

> I'd like to get the whole suite ported first before making these enhancements to the test harness because even though it's not exact it can still pick up issues.

**Comment by lmccart** [comment]
thanks for posting this @kevinb7, sorry I haven't had a chance to dig into your pr yet. will take a look as soon as I can!
