### ISSUE TITLE
images loaded in preload persist despite clearing browser cache

### ISSUE THREAD

**Issue by enauman** [processing/p5.js#5235]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [x] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version: 1.2.0
- Web browser and version: Chrome: 90.0.4430.93, Safari: 14.1
- Operating System: MacOS 10.15.7 
- Steps to reproduce this:
I am preloading images from an images folder using prefix and extension variables, in a loop:
```
var PRE1 = 'images/legs';
var PRE2 = 'images/body';
var PRE3 = 'images/head';
var EXT = '.jpg';
function preload(){
  for(var i=0;i<legs.length;i++) {
    legs[i] = loadImage(PRE1 + i + EXT);
    body[i] = loadImage(PRE2 + i + EXT);
    head[i] = loadImage(PRE3 + i + EXT);
  }
}
```
Images are numbered legs0.jpg, legs1.jpg, legs2.jpg, etc.
If I replace an image with a new one, deleting the old and uploading the new, I can't get the old cached one to stop showing up after clearing my browser cache and history. What is weirdest is the old image still shows up in Incognito, and opening the fullscreen URL in Safari when I had not even opened the app in Safari before, so it couldn't have been cached in that browser. The only way to make the new image show up is to duplicate the whole project.

**Comment by limzykenneth** [comment]
Hi @enauman, is this specific to the web editor?

**Comment by enauman** [comment]
Yes, sorry didn't mention that.

**Comment by limzykenneth** [comment]
The web editor is not maintained in this repo, can you open an issue over [here](https://github.com/processing/p5.js-web-editor/issues) instead? Thanks.

**Comment by enauman** [comment]
Thanks!
