### ISSUE TITLE
Plz put a function for setting width and height of gif like image

### ISSUE THREAD

**Issue by Gunkar16** [processing/p5.js#5241]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [x] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

**Comment by stalgiag** [comment]
Hello and welcome @Gunkar16 ! There is not enough information in your issue for us to be able to identify the problem. Judging by the title, you want to change the size of a GIF-based p5.Image. There are many ways to do this. You can modify the width and height properties directly. You can also use `resize()` as [in this example.](https://editor.p5js.org/stalgia.grigg/sketches/3YOyZSpj3) You can also pass width and height parameters to `image()` when drawing the GIF.

I am closing this issue for organizational purposes. If you have a different problem, please comment with more information and I will reopen.
