### ISSUE TITLE
Hi,i'm using various js like P5.sound.js and dom js in my html, and got errors: 1.amplitude is not defined 2.d._validateParameters is not a function

### ISSUE THREAD

**Issue by ss-cmd** [processing/p5.js#5242]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [x] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

**Comment by ss-cmd** [comment]
i have some screen shot
<img width="842" alt="截屏2021-05-13 上午1 57 53" src="https://user-images.githubusercontent.com/66662667/118022544-0b86a200-b38f-11eb-843b-9578b0a3b9d7.png">
<img width="1108" alt="截屏2021-05-13 上午1 54 39" src="https://user-images.githubusercontent.com/66662667/118022551-0de8fc00-b38f-11eb-9c27-63f3c905d9f7.png">
![Uploading 截屏2021-05-13 上午2.01.12.png…]()

**Comment by montoyamoraga** [comment]
hi @ss-cmd,
please ask your questions about your code on our forum
discourse.processing.org/
and it helps if you can upload an example on the p5.js web editor
thanks! :)
