### ISSUE TITLE
p5.js Editor + Friendly Errors

### ISSUE THREAD

**Issue by catarak** [processing/p5.js#5243]
### How would this new feature help [increase access](https://github.com/processing/p5.js/blob/main/contributor_docs/access.md) to p5.js?

This would improve the friendly errors on the web editor!

#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [x] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Feature enhancement details:

**TL;DR:** I would like to get access to the private function [`report()`](https://github.com/processing/p5.js/blob/61d2b09f8ea217d6c7d84b7a3373cb865fc134bf/src/core/friendly_errors/fes_core.js#L211) to monkey patch it in order to make friendly errors look better in the web editor.

**Why I would like to do this:** I've been updating the way the p5.js Editor renders sketches for security reasons (https://github.com/processing/p5.js-web-editor/issues/166). Recently, this issue came in (https://github.com/processing/p5.js-web-editor/issues/1853) about the web editor not being friendly with using the debugger. I did some thinking about how to fix this and came up with a solution! But. It caused me to look at how friendly errors look in the web editor.

##### Current rendering engine, friendly errors
<img width="625" alt="Screen Shot 2021-05-12 at 4 14 14 PM" src="https://user-images.githubusercontent.com/6063380/118038518-35af7400-b33d-11eb-81af-7ce4d03ab2f5.png">

##### New rendering engine, friendly errors
<img width="621" alt="Screen Shot 2021-05-12 at 4 14 46 PM" src="https://user-images.githubusercontent.com/6063380/118038600-537cd900-b33d-11eb-87b1-6d3267d5e0c4.png">

As you can see, the friendly errors don't give useful information about the error location due to the magic that the p5.js editor does in order to render everything client-side. What are these seemingly meaningless URLs? They are [Object URLs](https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL).

But! If I were able to monkey patch the [`report()`](https://github.com/processing/p5.js/blob/61d2b09f8ea217d6c7d84b7a3373cb865fc134bf/src/core/friendly_errors/fes_core.js#L211) function, I would be able to substitute the actual file names for the ObjectURLs in the messages. 

Also, my reasoning for requesting for monkey patching versus a public API for updating the friendly errors is that this issue is editor specific—I'm not sure this issue would come up in any other places.

**Comment by cryptochap** [comment]
while working with the web-editor I noticed the inconsistencies in error reporting and references this you have pointed out.

**Comment by outofambit** [comment]
@catarak i'm very willing to make report monkeypatchable for the editor! i can take this one

**Comment by catarak** [comment]
thank you @outofambit! 

I also wonder if it would ever make sense to create an API for the p5.js FES. Some reasons that come to my head:
- Allowing p5.js addons to create friendly errors
- Allowing p5.js addons to overwrite friendly errors, targeting different user demographics, perhaps for internationalization or other reasons
