### ISSUE TITLE
Incorrect links in wiki/Beyond-the-canvas file

### ISSUE THREAD

**Issue by Rahulm2310** [processing/p5.js#5245]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [X] Other (specify if possible)

#### Details about the bug:
The link https://github.com/processing/p5.js/wiki/Intro-to-HTML-and-CSS goes to file which doesn't exist in the wiki.
The link to forum needs to be updated from http://forum.processing.org/two/ to https://discourse.processing.org/c/p5js/
![error](https://user-images.githubusercontent.com/54268438/118159038-2d892e80-b43a-11eb-80fd-63ab014d72a9.JPG)

- p5.js version: 1.3.1
- Web browser and version: Google Chrome v90
- Operating System: Windows 10
- Steps to reproduce this:

1. Go to https://github.com/processing/p5.js/wiki/Beyond-the-canvas#what-next
2. See error.

**Comment by Rahulm2310** [comment]
@outofambit please have a look

**Comment by montoyamoraga** [comment]
@Rahulm2310 great catch!
i updated the link to the forum
removed the link to that intro to HTML and CSS
and also removed all the references to the p5.dom library,
which was merged into p5.js a while ago ~

**Comment by ghgsnaidu** [comment]
Hi Rahul!  I've never contributed before but I love javascript and I have been having a lot of fun with p5js and I'd like to contribute to any issue .it would be a great help if you can guide me like how this works
Hope you will reply

**Comment by Rahulm2310** [comment]
Hey @ghgsnaidu, welcome to the p5.js community 🎉. You can have a look at the [Github Issue Flow here](https://github.com/processing/p5.js/tree/main/contributor_docs#github-issue-flow) to get started. Hope it helps 🙂

**Comment by montoyamoraga** [comment]
hi @ghgsnaidu welcome!
i recommend checking also our contributor docs
https://github.com/processing/p5.js/tree/main/contributor_docs
and even recent closed issues and pull requests, to see the ways you can contribute :)
i will close this issue in the meantime because it has already been addressed ~

**Comment by ghgsnaidu** [comment]
Hey thanks guys @montoyamoraga  @montoyamoraga 
I am kinda getting know the flow .I really appreciate your help
