### ISSUE TITLE
Volunteer as a steward

### ISSUE THREAD

**Issue by Rahulm2310** [processing/p5.js#5246]
Hello everyone!
I have been contributing to the p5.js-website since one year and have a descent number of [PRs merged](https://github.com/processing/p5.js-website/pulls?q=is%3Apr+author%3A%40me+is%3Aclosed) now. I feel comfortable with the project now and thus want to volunteer as a steward for the p5.js-website project. I am not an expert but I am very much interested to actively participate. Hope the maintainers believe in me.
Thanks :)

**Comment by Rahulm2310** [comment]
tagging @lmccart @montoyamoraga @mcturner1995

**Comment by outofambit** [comment]
hey @Rahulm2310, sorry for the delay! We'd love to have you! 🎉 Could you open a PR to add yourself to https://github.com/processing/p5.js#stewards in that bulleted list and the table? Ping me on it and I'll approve + merge.

Thank you for volunteering, we're glad to have you!!

![excited dog](https://user-images.githubusercontent.com/964912/118291647-b0d37000-b48c-11eb-9a73-2d74c343eb8f.gif)

**Comment by montoyamoraga** [comment]
i agree with @outofambit, you have been amazing in contributing, thanks for becoming a steward!

**Comment by Rahulm2310** [comment]
Thanks a lot @outofambit @montoyamoraga @lmccart ❤️

**Comment by outofambit** [comment]
added to readme in #5249. thank you again @Rahulm2310!
