### ISSUE TITLE
Editor does not work in Safari 14.1 on Catalina or Big Sur

### ISSUE THREAD

**Issue by ednl** [processing/p5.js#5250]
#### Most appropriate sub-area of p5.js?

- [x] Core/Environment/Rendering ???
- [x] Other: web editor on https://editor.p5js.org

#### Details about the bug:

- p5.js version: newest, linked from https://editor.p5js.org (can't immediately find it in the page source)
- Web browser and version: Safari 14.1 (15611.1.21.161.7 on Catalina, 16611.1.21.161.6 on Big Sur)
- Operating System: MacOS 10.15.7 "Catalina" and 11.3.1 "Big Sur"
- Steps to reproduce this: go to https://editor.p5js.org, load a script or not, click the Run button, the canvas area only shows "Loading..." and does not change ever.

**Comment by stalgiag** [comment]
I was able to reproduce Safari 14.1 and macOS 11.3.1

**Comment by stalgiag** [comment]
This issue should be transferred to [the web-editor repo](https://github.com/processing/p5.js-web-editor) but for whatever reason p5.js-web-editor isn't appearing in the 'Transfer Issue' menu.

**Comment by ednl** [comment]
@stalgiag Thanks. Sorry, I didn't know there was a separate repo for the editor; I simply followed the GitHub link from the homepage.

**Comment by stalgiag** [comment]
No worries. It is an easy thing to not realize. I will transfer this issue manually as I am seeing it reported a lot by my students and I don't see it reported on that repo.
