### ISSUE TITLE
p5.Vector.mult example wrong

### ISSUE THREAD

**Issue by yanisr** [processing/p5.js#5252]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ x] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version: p5.js v1.0.0 February 29, 2020
- Web browser and version: Firefox 88.0.1
- Operating System: Windows10
- Steps to reproduce this:

When i reproduce the 4th example of p5.vector.mult (https://p5js.org/reference/#/p5.Vector/mult) the result variable is equal to v0 and the p5.Vector.mult function seem not to works
Here is the example code:
```
let v0 = createVector(1, 2, 3);
let v1 = createVector(2, 3, 4);
const result = p5.Vector.mult(v0, v1);
print(result); // result's components are set to [2, 6, 12]
```

Here is the warning i got when i paste this example in my console: 
```
p5.Vector.prototype.mult: n is undefined or not a finite number    (p5.min.js:3:442705)
```

Here is what is printed when i check 'result' value: 
```
Object { p5: {…}, x: 1, y: 2, z: 3 }
```

**Comment by limzykenneth** [comment]
@yanisr Can you try with the latest version of p5.js (1.3.1)?

**Comment by yanisr** [comment]
My bad, it's ok with this version
