### ISSUE TITLE
Typo at src/accessibility/outputs.js

### ISSUE THREAD

**Issue by mikeneth042118** [processing/p5.js#5253]
- x Typography

texOutput(FALLBACK)...should read textOutput(FALLBACK)

**Comment by two-ticks** [comment]
@mikeneth042118 are you talking about description in https://p5js.org/reference/#/p5/textOutput ? 

https://github.com/processing/p5.js/blob/1250864d63e6353233789f0059f62ebe0188a2a5/src/accessibility/outputs.js#L24

If you are not working on this issue I would like to work on this.

**Comment by mikeneth042118** [comment]
Hello TwoTicks…just in the second paragraph of the textOutput()
description…says texOutput()…missing the ‘t’.

Yes…you can take care of this if you like. I’m new so I wouldn’t know how
to fix this.

Thanks
