### ISSUE TITLE
Missing p5.Vector link on Reference Index Page

### ISSUE THREAD

**Issue by mikeneth042118** [processing/p5.js#5255]
No link to p5.Vector class description on Reference Index. Can be accessed through point() function...but should be included in the index. Some shape functions don't indicate that a vector object can be used as a param instead of manually entering coordinates...is this correct?

**Comment by JetStarBlues** [comment]
Hey,

On my computer, I can see a link to `p5.Vector` on the reference page:    

![Capture](https://user-images.githubusercontent.com/4354703/119047056-a593af00-b97a-11eb-9f19-bf9284d26417.png)

> Some shape functions don't indicate that a vector object can be used as a param instead of manually entering coordinates

I think it's safe to assume that's the case. I.e. if there's no such example in the syntax section of the method's documentation page, then most likely it does not accept one as a parameter.

There is sometimes the odd chance that the documentation for that specific parameter variant is missing - but this is rare. If you are comfortable looking through the source code, you can click through the link at the bottom of the method's documentation page, to have a look at the source and confirm whether it is capable of accepting vector parameters.

>  Notice any errors or typos? [Please let us know](#). Please feel free to edit [src/core/shape/2d_primitives.js](#) and issue a pull request!

**Comment by mikeneth042118** [comment]
That’s great…sorry I had not noticed that. Thanks

**Comment by JetStarBlues** [comment]
No worries, there are a lot of links on the page!  
The search bar at the top can help with quickly finding a page of interest.
