### ISSUE TITLE
Add p5.Camera.frustum documentation on reference page

### ISSUE THREAD

**Issue by JetStarBlues** [processing/p5.js#5256]
### How would this new feature help [increase access](https://github.com/processing/p5.js/blob/main/contributor_docs/access.md) to p5.js?

Provides missing description on how to use the method.

#### Most appropriate sub-area of p5.js?

- [x] Other (documentation)

#### Feature enhancement details:

The [`frustum()`][0] method of [`p5.Camera`][1] lacks documentation on the reference page.  

_p5.Camera reference page_  
![frustumMissingDescription](https://user-images.githubusercontent.com/4354703/119035807-36fc2480-b96d-11eb-94af-d3cc02857834.png)

_p5.Camera.frustum reference page_  
![frustumMissingDescription2](https://user-images.githubusercontent.com/4354703/119035830-3ebbc900-b96d-11eb-89d4-de58487ae660.png)

I propose adding the following description:

```js
/**
 * Sets the frustum for a p5.Camera object and sets parameters
 * for that frustum according to <a href="#/p5/frustum">frustum()</a> syntax.
 * @method frustum
 * @for p5.Camera
 */
```

This follows the documentation style of the p5.Camera [`perspective()`][2] and [`ortho()`][3] methods, which link to their "global" p5 counterparts ([`perspective()`][4] and [`ortho()`][5]) that contain more detailed explanations with examples.

For example, this is [the description][6] for `perspective()`:

```js
/**
 * Sets a perspective projection for a p5.Camera object and sets parameters
 * for that projection according to <a href="#/p5/perspective">perspective()</a>
 * syntax.
 * @method perspective
 * @for p5.Camera
 */
 ```

_p5.Camera.perspective reference page_  
![frustumMissingDescription3](https://user-images.githubusercontent.com/4354703/119036488-049ef700-b96e-11eb-9926-d9aace9e46fc.png)

[0]: https://p5js.org/reference/#/p5.Camera/frustum
[1]: https://p5js.org/reference/#/p5.Camera
[2]: https://p5js.org/reference/#/p5.Camera/perspective
[3]: https://p5js.org/reference/#/p5.Camera/ortho
[4]: https://p5js.org/reference/#/p5/perspective
[5]: https://p5js.org/reference/#/p5/ortho
[6]: https://github.com/processing/p5.js/blob/75f367c034c0c7419347ad05894da30a07ab31c2/src/webgl/p5.Camera.js#L665

**Comment by JetStarBlues** [comment]
Not sure if I should open a separate issue for this, but I think the clarity of these three (ortho, perspective, frustum) descriptions can be improved by changing them from:

>  Sets _method_ for a p5.Camera object and sets parameters for that _thing_ according to _method_() syntax.

To:

>  Sets _method_ for a p5.Camera object. Accepts the same parameters as its global equivalent, _method_(). See the global function for more information and examples.

For example, the perspective description would become:

> Sets a perspective projection for a p5.Camera object. Accepts the same parameters as its global equivalent,  <a href="#/p5/perspective">perspective()</a>. See the global function for more information and examples.

The change aims to make it clearer to a reader that:
- there are two distinct functions - the p5.Camera method, and the "global" p5 method
- the reference page for the global version is the place-to-go for information on how to use method

What do you think?

**Comment by JetStarBlues** [comment]
I can also copy over (with slight changes to use p5.Camera methods) the examples from the global equivalents. The detailed explanations can remain in the global equivalents.

This would satiate the current build complain:
```
src/webgl/p5.Camera.js:665: method p5.Camera.perspective missing example
src/webgl/p5.Camera.js:746: method p5.Camera.ortho missing example
src/webgl/p5.Camera.js:807: method p5.Camera.frustum missing example
src/webgl/p5.Camera.js:1099: method p5.Camera.camera missing example
```

**Comment by stalgiag** [comment]
Looks good thanks @JetStarBlues
