### ISSUE TITLE
Canvas.elt.toDataURL saving blank images

### ISSUE THREAD

**Issue by sameehj** [processing/p5.js#5263]
Hi

- [x] Image
- [x] IO (Input/Output)

This is my nextjs (reactjs) code, I'm using the p5 library, everything is fine until I try to view the saved base64 image, the image is saved as blank. Any idea what I might be doing wrong? or is it a bug in the p5 reactjs library? 

```
const Sketch = (W, H, saveDataURI) => (p) => {
  const BRUSH_START_SIZE = 10;
  const BRUSH_END_SIZE = 60;
  const BRUSH_DELTA = 1;
  let dataURI;
  let canvas;
  let count = BRUSH_START_SIZE;
  let bg;
  let button;
  let mouseWasPressed = false;

  function clearCanvas() {
    p.clear();
  }

  p.setup = () => {
    p.createCanvas(W, H);
    bg = p.loadImage("/foot_scan_clean_estiqama.png");

    canvas = p.select("canvas");

    //  button = p.createButton("clear");
    // button.position(W / 2 - button.width / 2, H - 50);
    //  button.mousePressed(clearCanvas);
    saveDataURI(canvas.elt.toDataURL());
  };

  p.draw = () => {
    p.background(bg);
    if (p.mouseIsPressed) {
      if (count < BRUSH_END_SIZE) count = count + BRUSH_DELTA;
      else count = BRUSH_END_SIZE;

      let squareColor = p.color(255 - count, 0, 0);
      squareColor.setAlpha(20);

      p.fill(squareColor);
      p.noStroke();
      p.ellipse(p.mouseX, p.mouseY, count, count);
      mouseWasPressed = true;
    } else {
      if (mouseWasPressed) {
        p.updatePixels();
        dataURI = canvas.elt.toDataURL("image/png");
        saveDataURI(dataURI);
        console.log(dataURI);
        mouseWasPressed = false;
      }
      count = BRUSH_START_SIZE;
    }
  };

  p.mouseDragged = () => {
    count = BRUSH_START_SIZE;
    // prevent default
    return false;
  };
};
export default Sketch;
```

**Comment by limzykenneth** [comment]
The `dataURI` variable is set in the else block of your draw function which has no drawing code in it (they are all in the if block) so it literally hasn't drawn anything in the frame that it is saving the canvas data and only the blank background has been drawn. That's why you only get a blank output.

If you need help with your own code, please direct your questions to the [forum](https://discourse.processing.org). We use GitHub issues mainly for bug reports and feature requests only. Thanks!

**Comment by sameehj** [comment]
@limzykenneth Thanks for the answer! I still believe this is a bug as the background I have drown is anything but blank! nonetheless I have taken your advice and saved the dataURI in the previous iteration, the value is still null!

**Comment by sameehj** [comment]
Also I have posted my questions on the forums here: https://discourse.processing.org/t/canvas-elt-todataurl-saving-blank-images/30371

**Comment by limzykenneth** [comment]
Try removing `p.updatePixels();`.
