### ISSUE TITLE
Stroke odd behaviour for small shapes but up-close camera

### ISSUE THREAD

**Issue by JetStarBlues** [processing/p5.js#5264]
#### Most appropriate sub-area of p5.js?

- [x] WebGL

#### Details about the bug:

- p5.js version: 1.3.1 (though I think this bug is not specific to this version)
- Web browser and version: Chrome, Firefox
- Operating System: Windows 10, Ubuntu 20.04
- Steps to reproduce this:
  - Visible on the:
    - [camera() reference page][0] (first example with a plane (white fill, black stroke))
      - ![stroke1](https://user-images.githubusercontent.com/4354703/119559045-64771280-bd5f-11eb-9b0e-fa5201115825.png)
    - [frustum() reference page][1] (example with two cubes(no fill, blue stroke))
      - ![stroke2](https://user-images.githubusercontent.com/4354703/119559079-70fb6b00-bd5f-11eb-81f9-371b338fde7c.png)

It seems by default, the stroke shader draws "small" objects with a thick background. I think this is to help with visibility. For example:

```js
function setup() {
  createCanvas(100, 100, WEBGL);
}

function draw() {
  background(204);
  plane(10, 10);
}
```
generates,  
![stroke_100x100_plane10_defaultCameraPostion](https://user-images.githubusercontent.com/4354703/119559654-33e3a880-bd60-11eb-8948-92341c77e4c8.png)

When the object is larger, the stroke gets thinner.

```js
plane(40, 40);
```
generates,  
![stroke_100x100_plane40_defaultCameraPostion](https://user-images.githubusercontent.com/4354703/119559689-3e05a700-bd60-11eb-80ae-1e0420e4683f.png)

```js
plane(80, 80);
```
generates,  
![stroke_100x100_plane80_defaultCameraPostion](https://user-images.githubusercontent.com/4354703/119559718-46f67880-bd60-11eb-8afe-1f24652f8052.png)

However, this thinning of the stroke does not happen when instead of the object getting bigger, the camera moves closer to the object.

The default camera position is calculated as `(0, 0, (height / 2) / tan(PI / 6))`. For a canvas with height `100`, this is `~(0, 0, 87)`.
```js
let cam;

function setup() {
  createCanvas(100, 100, WEBGL);
  cam = createCamera();
}

function draw() {
  background(204);
  cam.camera(
    0, 0, 87,
    0, 0, 0,
    0, 1, 0
  );
  plane(10, 10);
}
```
generates,  
![stroke_100x100_plane10_defaultCameraPostion](https://user-images.githubusercontent.com/4354703/119559853-6f7e7280-bd60-11eb-9e70-208a5109bc2b.png)

As we move the camera closer, though the object gets bigger, the stroke does not get thinner.

```js
cam.camera(
  0, 0, 25,
  ...
```
generates,  
![stroke_100x100_plane10_eyeZ25](https://user-images.githubusercontent.com/4354703/119559869-74dbbd00-bd60-11eb-9372-e020e52ee772.png)

```js
cam.camera(
  0, 0, 12,
  ...
```
generates,  
![stroke_100x100_plane10_eyeZ12](https://user-images.githubusercontent.com/4354703/119559885-7ad19e00-bd60-11eb-80f0-88a732df97c9.png)

**Expected behaviour:** stroke should get thinner as camera moves closer

[0]: https://p5js.org/reference/#/p5/camera
[1]: https://p5js.org/reference/#/p5/frustum

**Comment by stalgiag** [comment]
Hi @JetStarBlues thanks for the well-written issue. This may just be my perspective (smh) but I wouldn't expect the stroke to get smaller in the second set of examples. The reason the stroke appears to be getting smaller is that its relative size is shifting. 1px stroke is 1/10th of `plane(10, 10)` and 1/80th `plane(80, 80)`. In the second set of examples, you are moving closer to a small plane so the stroke grows. In the first set of examples, the plane is growing bigger and the camera is not moving so the stroke never grows. Let me know if this makes sense.

**Comment by JetStarBlues** [comment]
>  The reason the stroke appears to be getting smaller is that its relative size is shifting

Ah, I see! That makes a lot of sense! Thanks for taking the time to explain this.

I'm tempted to change the code used in the [`frustum()`][0] example (use bigger boxes, and a camera that's further away - or use filled boxes (normalMaterial)). Currently it is hard to tell what the example is trying to demonstrate. (I imagine the visual effect is supposed to be similar in spirit to the [`persepective()`][1] and [`ortho()`][2] examples).

[0]: https://p5js.org/reference/#/p5/frustum
[1]: https://p5js.org/reference/#/p5/perspective
[2]: https://p5js.org/reference/#/p5/ortho
