### ISSUE TITLE
GIF writer bug or mistake ?

### ISSUE THREAD

**Issue by DJLinux** [processing/p5.js#5267]
hello i'm new to JS but in section GIF writer I found 'var has_local_palette' in two scopes !
```javascript
var has_local_palette = false;
if (local_palette_flag) {
  var has_local_palette = true; /* <-- is it a new local var ? */
  palette_offset = p;  // Override with local palette.
  palette_size = num_local_colors;
  p += num_local_colors * 3;  // Seek past palette.
}
```
Is it a bug or my mistake ?
DJ

**Comment by stalgiag** [comment]
Hi @DJLinux ! Thanks for the issue. That [code is in a dependency.](https://github.com/deanm/omggif/blob/master/omggif.js#L479). I would recommend filing over there. Going to close here for organizational purposes.
