### ISSUE TITLE
add TylersGit as contributor 

### ISSUE THREAD

**Issue by montoyamoraga** [processing/p5.js#5268]

**Comment by montoyamoraga** [comment]
@all-contributors please add @TylersGit as contributor for doc

**Comment by montoyamoraga** [comment]
@outofambit since yesterday i noticed that the allcontributors bot is not working :(

**Comment by outofambit** [comment]
@all-contributors please add @TylersGit as contributor for doc

**Comment by outofambit** [comment]
@all-contributors please add @TylersGit for docs

**Comment by outofambit** [comment]
@all-contributors please add @TylersGit for doc

**Comment by outofambit** [comment]
@montoyamoraga fixed it with https://github.com/processing/p5.js/commit/7bfb8b376ddde286c4bbfad5b52baccf1b638384!
