### ISSUE TITLE
Documentation Error: Processing instead of p5

### ISSUE THREAD

**Issue by dipamsen** [processing/p5.js#5278]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [x] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other: **Documentation**

## Documentation error

[p5 `mouseButton`](https://p5js.org/reference/#/p5/mouseButton) (https://github.com/processing/p5.js/tree/main/src/events/mouse.js#L351-L359)
Actual: 
> Processing automatically tracks if the mouse button is pressed and which button is pressed. The value of the system variable mouseButton is either LEFT, RIGHT, or CENTER depending on which button was pressed last. Warning: different browsers may track mouseButton differently.

Expected:
> p5 automatically tracks if the mouse button is pressed and which button is pressed. The value of the system variable mouseButton is either LEFT, RIGHT, or CENTER depending on which button was pressed last. Warning: different browsers may track mouseButton differently.

**Comment by SanjaySinghRajpoot** [comment]
may I work on this issue?
