### ISSUE TITLE
Rename "Lights, Camera" group in Reference page

### ISSUE THREAD

**Issue by JetStarBlues** [processing/p5.js#5294]
#### Most appropriate sub-area of p5.js?
- [x] WebGL
- [x] Other (documentation)

### How would this new feature help [increase access](https://github.com/processing/p5.js/blob/main/contributor_docs/access.md) to p5.js?

The group contains information on more than just `Lights` and `Camera`. For example the `Material` subgroup is a key component of the group.

Renaming the group (module) to something that reflects this range, will help make it clear which section of the Reference page to go to for information about 3D-related topics.

#### Feature enhancement details:

I propose renaming the group to something like `3D` or `3D Environment` or `3D Scene` or `WebGL`, which better encompasses the existing subgroups (`Lights`, `Camera`, `Material`, `Interaction (3D)`) and potential future subgroups.

Here are snapshots of the current state:

_top menu_
![lightsCamera_cur2](https://user-images.githubusercontent.com/4354703/120850822-3353ca80-c535-11eb-9e2f-617b4d075388.png)

_lights, camera_
![lightsCamera_cur1](https://user-images.githubusercontent.com/4354703/120850836-377fe800-c535-11eb-893d-039a7a9885cc.png)

**Comment by aferriss** [comment]
I'd be in favor of using `3d` over `WebGL`. To me, webGL might not be a term that a beginner would have heard before. Personally, 3D feels much more approachable and easy to understand to me.

**Comment by JetStarBlues** [comment]
I see, agreed. Will update the PR accordingly.
