### ISSUE TITLE
strokeWeight() not working properly with odd numbers

### ISSUE THREAD

**Issue by byma1995** [processing/p5.js#5296]
strokeWeight() works as expected with even numbers, but when used with odd numbers, it always draws strokes that are 1 pixel wider with some transparent pixels.

#### Most appropriate sub-area of p5.js?

- [x] Core/Environment/Rendering

#### Details about the bug:

- p5.js version: 1.3.1
- Web browser and version: Chrome 91.0.4472.77
- Operating System: Windows 10 Home
- Steps to reproduce this:
```
function setup() {
  createCanvas(200, 200);
}

function draw() {
  background(255);
  noSmooth();
  stroke(0);
  strokeCap(SQUARE);
  for(let i = 0; i < 10; i++) {
    strokeWeight(i);
    line(10,10*(i+1),100,10*(i+1));
  }
}
```

**Comment by limzykenneth** [comment]
The same behaviour exist in the native HTML canvas underlying p5.js which means that this is either a browser implementation issue or a result of the HTML canvas specifications. I'm not sure why it is implemented like this but as such there isn't a way for p5.js to solve this.

**Comment by soegaard** [comment]
Check this explanation of the phenomenon in the FAQ of Cairo:

https://www.cairographics.org/FAQ/#sharp_lines

And the follow up here:

https://softwareengineering.stackexchange.com/questions/275610/getting-strokes-and-fill-to-align-to-pixel-boundaries
