### ISSUE TITLE
support processing-js' blendColor method

### ISSUE THREAD

**Issue by kevinb7** [processing/p5.js#530]
It's kind of like ```blend```, but for colors, e.g. ```blend(color1, color2, blendMode)```.  Here's a link to the docs: http://processingjs.org/reference/blendColor_/

**Comment by lmccart** [comment]
since there doesn't seem to be further energy around this one, and it's not a part of the official Processing API, I'm going to close this for now, so we can focus on getting parity with Processing before extending further in this area.
