### ISSUE TITLE
point() does not respect the stroke cap

### ISSUE THREAD

**Issue by soegaard** [processing/p5.js#5301]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [x ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version: the one online 7. june
- Web browser and version: Chrome 90.0.4430.212 
- Operating System: MacOSX
- Steps to reproduce this:

```
function setup() {
  createCanvas(200, 100);
}

function draw() {
  background(220);
  strokeWeight(10);
  strokeCap(ROUND);
  point(50,50);
  strokeCap(SQUARE);
  point(100,50);
  strokeCap(PROJECT);
  point(150,50);
}

```
The expected behaviour:  the project cap ought to give a square and the square cap ought to draw nothing.

Compare with the description of point() for the Java version.
https://processing.org/reference/point_.html

**Comment by spencerstith** [comment]
Hmm. Although Processing does support `strokeCap()` with points, it appears as though P5.js only [supports `strokeCap()` with lines](https://p5js.org/reference/#/p5/strokeCap). So, if you are trying to use this I would suggest using very sort lines, such as
```javascript
function setup() {
  createCanvas(200, 100);
}

function draw() {
  background(220);
  strokeWeight(10);
  strokeCap(ROUND);
  point(50,50);
  strokeCap(SQUARE);
  line(100,50, 110, 50);
  strokeCap(PROJECT);
  line(150,50, 160, 50);
}
```

**Comment by soegaard** [comment]
Thanks for the suggestion. I noticed the difference between Processing (Java) and P5.js 
because I am implementing something "Processing"-like in Racket. 

The drawing library I use is based on Cairo. Your short line trick is actually one of the 
recommended methods to get a point in Cairo. 
[sidenote: if scaling transformations are in effect, then one must be careful to choose the right distance of "short"]

The other method,  is: 

```
cairo_move_to (cr, x, y);
cairo_close_path (cr);
```

Since there is no direction available, the direction of the cap is unspecified. 
	
https://lists.cairographics.org/archives/cairo/2009-June/017459.html

**Comment by limzykenneth** [comment]
The drawing API in p5.js (ie. the HTML canvas API) is going to be very similar to Cairo because that's what many browser uses directly (or something based closely on Cairo). 

Parity with Processing isn't a goal for p5.js and since there's a workaround found, I'm going to close this issue for now.
