### ISSUE TITLE
1.4 Release

### ISSUE THREAD

**Issue by outofambit** [processing/p5.js#5309]
I'd like to do a release of p5 soon so we can get the [new p5 sound library (🎉)](https://github.com/processing/p5.js/pull/5266) out to everyone! Is there anything else specific we need to get merged in before then? I'm thinking we can shoot for the week of June 28.

I think the next release version should be `1.4` since I believe there are some small breaking changes in the sound library. @therewasaguy @limzykenneth does that sound right to you? (Otherwise, I believe it's all non-breaking changes on the p5 side.)

**Comment by outofambit** [comment]
I need to finish #5243 for this release to unblock some web editor work!

**Comment by limzykenneth** [comment]
Would be nice to get a fix of #5142 out but also don't want to rush it.

**Comment by therewasaguy** [comment]
week of June 28th and 1.4 sounds good to me!

Thank you for making this happen, @outofambit!

**Comment by outofambit** [comment]
released today! https://github.com/processing/p5.js/releases/tag/v1.4.0

the release notes need some work 😅 will revise them soon
