### ISSUE TITLE
Word wrapping doesn't wrap the long words.

### ISSUE THREAD

**Issue by 8o8inCodes** [processing/p5.js#5321]
#### Most appropriate sub-area of p5.js?

- [x ] Typography

#### Details about the bug:

- p5.js version: latest
- Web browser and version: Chrome
- Operating System: Windows 10
- Steps to reproduce this:
```js
let s = "It was the best of times, it was the worst of times. Only 90s kids will remember these times. Alf and Growning Pains remember that. fkdjshfkasjdhfkasdjhflkasdjfhalsdkjfhasdlkfjhasdlkfjhsadlkfjhasdklfjhasdlkfjhaklsdjfhaslkdfhalskdjfhaslkdjhfasdkljhfaskdlfhaskdlhfksadhfaskdfhaksdlhfaksdjfhsadklfjhaslkfjhasldkjfhalskdfhasdlkfhasdlkfhasdklfjhasdklfhaskdljfhaklsjdhf";
function setup() {
  createCanvas(400, 400);
}

function draw() {
  background(220);
  let size = map(mouseX, 0 , width, 10, 72)
  textSize(size);
  textLeading(size*1.1); //goes AFTER TEXT

  fill(0);
  text(s, 50, 50, 250, 250);
  noFill();
  rect(50, 50, 250, 250);
}
```

It doesn't word wrap long words and these words escape the wrapping box.
And I have no way of containing such text.

Here is an quick editor example that I've found, you can add a very long word there
https://editor.p5js.org/gfm262/sketches/TGK6Th4Xr

**Comment by limzykenneth** [comment]
This has been address by #5146 with the addition of the `textWrap()` function. It will be available in the next release of p5.js.

**Comment by 8o8inCodes** [comment]
> This has been address by #5146 with the addition of the `textWrap()` function. It will be available in the next release of p5.js.

Thank you! Will be waiting for it
