### ISSUE TITLE
Examples stuck at "Loading..." on Safari 14.1

### ISSUE THREAD

**Issue by darrinm** [processing/p5.js#5323]
#### Most appropriate sub-area of p5.js?

- [x] Other (specify if possible)
(all?) p5 examples (https://editor.p5js.org/p5/sketches)
https://editor.p5js.org/p5/sketches/Hello_P5:_song
https://editor.p5js.org/p5/sketches/Hello_P5:_drawing
https://editor.p5js.org/p5/sketches/Hello_P5:_weather
https://editor.p5js.org/p5/sketches/Hello_P5:_flocking
https://editor.p5js.org/p5/sketches/Hello_P5:_interactivity
...

#### Details about the bug:

- p5.js version: 
p5.js 1.1.9, p5.sound.min.js 0.3.12

- Web browser and version: 
Safari Version 14.1 (16611.1.21.161.3)

- Operating System: 
macOS 11.3

- Steps to reproduce this:

In Safari, go to one of the URLs above (e.g. https://editor.p5js.org/p5/sketches/Hello_P5:_interactivity) and press the Play button. You'll see "Loading..." to the right but nothing more.

The Javascript console reports a couple of errors:
`Failed to load https://editor.p5js.org/editor/session` -- this seems innocuous and also is reported on Chrome where the examples do work.
`Error while parsing the 'sandbox' attribute: 'allow-downloads' is an invalid sandbox flag'` -- also an innocuous error? I say this because I have been doing testing on my own site with Safari and have the same "Loading..." problem w/o the sandbox error.

**Most revealing: When I load p5.js and NOT p5.sound.js these examples run as expected.**

Also note, the examples do run fine in other contexts. E.g. https://p5js.org/examples/hello-p5-interactivity-1.html

**Comment by stalgiag** [comment]
Thanks for filing this well-written issue. I believe this may be [the same as this](https://github.com/processing/p5.js-web-editor/issues/1870).

**Comment by catarak** [comment]
Thank you! This is an issue with the p5.js Editor, p5.js sound, and the latest version of Safari. I have updated the examples to use an earlier version of p5.js sound so this is fixed for now.
