### ISSUE TITLE
mouseDragged is very slow.

### ISSUE THREAD

**Issue by sukhchainn** [processing/p5.js#5327]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [x] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Feature enhancement details:
I am using this code in mouseDragged event :-
`
if (event.x > canvasX1 && event.y > canvasY1
		 && event.x < canvasX2 && event.y < canvasY2) {
			let a = (p.mouseX)/size;
			let b = (p.mouseY)/size;
			a = parseInt(a);
			b = parseInt(b);
			pixels[b][a].click();
			redraw = true;
		}
`
my code is detecting drag in elements very slowly, I even optimized my code and still no significant improvement. I need to make it faster, how can I do it?

**Comment by outofambit** [comment]
hi @sukhchainn thanks for reaching out. this is a question best directed to the [p5 forum](https://discourse.processing.org/c/p5js) for help with your code! If you can include a link to your running code there, that will also help folks help you faster. :)
