### ISSUE TITLE
Removing unused jshint config (.jshintrc)

### ISSUE THREAD

**Issue by N4M3L355** [processing/p5.js#5334]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [x] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

The `.jshintrc` file in `src` directory is not used anywhere in the repository. It is probably a legacy after the repository moved from .jshint. Besides, IDE like WebStorm is confused and tries to enforce the rules from it (and giving errors as the code is not compliant with the rules specified). I propose to delete it, but I was not sure if I need to create an issue first before doing a pull request.

**Comment by limzykenneth** [comment]
Should be alright to delete it. You can file a PR if you wish.
