### ISSUE TITLE
Nullish Coalescing Operator shows syntax error in editor

### ISSUE THREAD

**Issue by The-Warlord** [processing/p5.js#5347]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [x] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version: 
- Irrelevant (error with web editor)
- Web browser and version: 
- Irrelevant (error with web editor)
- Operating System: 
- Irrelevant (error with web editor)
- Steps to reproduce this:
- 1. Use a nullish coalescing operator (`??`)
- 2. ❌ Note the editor shows an error, even though this operator was added in ECMA 11th Edition

![image](https://user-images.githubusercontent.com/63512394/124531123-d705f400-dddb-11eb-8a37-9e5bbd9087db.png)
Note that the code works, of course. It's just the editor that _thinks_ it's invalid.
Since this it seems that this operator [is not supported in all browsers](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator#browser_compatibility), perhaps it could show a warning, like the usage of BigInt instead. 
![image](https://user-images.githubusercontent.com/63512394/124531302-37953100-dddc-11eb-8148-3a8b94671e0e.png)

**Comment by limzykenneth** [comment]
Hi @The-Warlord, the editor is maintained in a separate repository so you should file this issue over [here](https://github.com/processing/p5.js-web-editor/issues) instead. Thanks!

**Comment by The-Warlord** [comment]
> Hi @The-Warlord, the editor is maintained in a separate repository so you should file this issue over [here](https://github.com/processing/p5.js-web-editor/issues) instead. Thanks!
Oh, thanks for letting me know! I'll move it.
