### ISSUE TITLE
keyPressed event: upper and lower case

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js#536]
I'm noticing that in `keyPressed()` I always get a capital letter for any key pressed.  For example with both 'a' and 'A' I get the following:

```
key code: 65
key: 'A'
```

```
function keyPressed() {
  console.log("p5 keyCode: " + keyCode);
  console.log("p5 key: " + key);
}
```

With native browser events, however

```
window.addEventListener("keypress", function(e) {
  console.log("native keycode: " + e.which);
  console.log("native key: " + String.fromCharCode(e.which));
});
```

I get:

```
key code: 97
key: 'a'
```

and

```
key code: 65
key: 'A'
```

Is this on purpose for a reason I'm missing?

**Comment by lmccart** [comment]
it has to do with differences between browsers... we are updating the keyCode and key on keyPressed, keyReleased, and keyTyped which actually returns different results. this page explains a little more:
http://www.quirksmode.org/js/keys.html

however, this may need to be revisited, I don't know if the discrepancies are still there with the most recent browser versions, or maybe there is something smarter we can do, keeping track of some internal vars and only using the results from the keyup call if the key isn't already set... or maybe key and keyCode just shouldn't be updated at all on keyup?

feel free to play around, it's all in src/input/keyboard, or I'll take a closer look next chance I get.

**Comment by ipeluffo** [comment]
Hi!
Feel free to take a look to the following example I've made:
http://jsbin.com/yotobu/6/edit?html,js,console,output

There you'll be able to see that the p5's "keyTyped" event is the same as the native event "keypress", and the p5's "keyPressed" event is actually "keydown" native event.

So, I believe that the behaviour noticed by @shiffman is the normal one :)

**Comment by iamutkarshtiwari** [comment]
I would like to work on this fix. I have already submitted the patch for a similar issue in PDE -> https://github.com/processing/processing/pull/4006

**Comment by lmccart** [comment]
as @ipeluffo mentions, the behavior noticed is correct. the keypress event in browser events is mapped to `keyTyped()` in p5, because the keydown event is mapped to `keyPressed()`. so the best level of accuracy we can get inside `keyPressed()` is capitalized letters, but if you use `keyTyped()` you will get the correct casing.
