### ISSUE TITLE
Undefined totalHeight in text function when setting vertical alignment

### ISSUE THREAD

**Issue by AlexEltonPym** [processing/p5.js#5360]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [x] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

Using textAlign(CENTER, CENTER) causes 'ReferenceError: totalHeight is not defined' when using the text function.

- p5.js version: 1.4.0
- Web browser and version: Google Chrome	91.0.4472.164 (Official Build) (x86_64)
- Operating System: macOS Version 10.15.7 (Build 19H1030)
- Steps to reproduce this:
```
function setup() {
  createCanvas(400, 400);
}

function draw() {
  textAlign(CENTER, CENTER)  
  text("example text", width/2, height/2, 300, 100)
}
```

Console error:
```
Uncaught ReferenceError: totalHeight is not defined
    at _main.default.Renderer2D._main.default.Renderer.text (p5.js:64912)
    at _main.default.Renderer2D.text (p5.js:66355)
    at p5._main.default.text (p5.js:93356)
    at draw (24871d84-9d19-45cd-b2fe-c6baebca1e56:7)
    at p5._main.default.redraw (p5.js:70809)
    at _draw (p5.js:63046)
```

**Comment by AlexEltonPym** [comment]
Bug occurs with either textAlign(, BOTTOM) or textAlign(, CENTER)

**Comment by AlexEltonPym** [comment]
Offending code:

https://github.com/processing/p5.js/blob/f21bbaf16e0659a6eb47461ed98f3ae3a2b73fcd/src/core/p5.Renderer.js#L270-L283

**Comment by HaroldLee931** [comment]
you can avoid this issue by using `textAlign(TOP, TOP)`
