### ISSUE TITLE
Thin lines look much brighter in Safari than Chrome

### ISSUE THREAD

**Issue by hjalmar-astrom** [processing/p5.js#5362]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version:1.4.0 
- Web browser and version: Chrome - 92.0.4515.107, Safari - 14.1.2  
- Operating System:MacOS Catalina 10.15.7 
- Steps to reproduce this:
- make a sketch with a lot of thin lines (I find 0.1 particularly noticeable)
Example sketch here [https://openprocessing.org/sketch/1238402](https://openprocessing.org/sketch/1238402)
View the sketch in both Safari and Chrome, for me they look like this:
Chrome
![chrome](https://user-images.githubusercontent.com/87953105/126916756-da702fb7-de53-4f9e-b1c2-e92d1cf81579.png)
Safari
![safari](https://user-images.githubusercontent.com/87953105/126916758-7bc9cdf8-6fbb-43c8-906f-3b2e3eabfa41.png)

**Comment by limzykenneth** [comment]
This is probably down to the detailed implementation differences of subpixel drawings in the browsers and nothing much p5.js can do to make them consistent. In other words, when drawing such thin lines, it is up to the browser to decide how it wants to draw them.

**Comment by hjalmar-astrom** [comment]
Ah yeah you're right, I had a look at the implementation and it mostly just calls through to the rendering context.
