### ISSUE TITLE
Testing out using Pontoon and Fluent for translation workflow 

### ISSUE THREAD

**Issue by limzykenneth** [processing/p5.js#5363]
### How would this new feature help [increase access](https://github.com/processing/p5.js/blob/main/contributor_docs/access.md) to p5.js?

Using [Pontoon](https://pontoon.mozilla.org/) and [Fluent](https://projectfluent.org/) could potentially increase the ease of contributing to translation of p5.js, removing the need for translators to have a development setup to start translating. Pontoon can also provide effective translation tracking and management without having to edit data files manually. Both projects are free and open sourced as well.

#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [x] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [x] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### New feature details:
**Full disclosure**: this ties into a research project I'm working on around software documentation translation and will serve as a testing ground for some of the ideas I have for the project. The research outcome will be shared with the community and I plan to continue developing and supporting the use of Pontoon in p5.js even after the end of the research project if relevant. As a start, the three main areas I'm looking at are: 

1. Accessibility: how easy is it to start contributing translation
2. User interface/experience: how fit for purpose is Pontoon's interface
3. Machinery: how useful are machine translations and translation memory systems provided by Pontoon are for the translators.

As part of the research project I'm working on, I'm planning to deploy an instance of Pontoon, a translation/localization system developed and used by Mozilla to translate their various products including Firefox, for p5.js. It will be a standalone deployment and at this stage only covers the reference. The goal is to have all the translation work be done in the Pontoon interface and have everything else be done seamlessly.

Since Pontoon doesn't take the JSON strings we have been using for storing translations, I have begun writing a script that converts between the JSON that we have and the Fluent `.ftl` files that Pontoon supports. There are various challenges there and while I'm not able to get all the strings ported to `.ftl` and back, I estimate about >95% do work.

**What I need from the community**
As this is pretty much an experiment, I would like the community to use the system once it's up and provide any feedback about their experience, I plan to ask for more formal feedback from the translation maintainers but will be very happy to get feedback from other translation contributors as well.

In addition, if anyone has thoughts or ideas related to this, please comment below this issue!

**Plan of action**
I plan to get the whole thing up and running by 1st August and will continue to run it as an experiment until end of August. In that time period where appropriate, I'll iterate on the system based on feedback. I'll also collect feedback and responses from the community about the setup and their experience using it, which will contribute to the research project I'm working on.

---

I don't want to pad this issue out too long but I'm happy to answer any questions anyone has!

**Comment by limzykenneth** [comment]
@outofambit @Qianqianye @montoyamoraga @yukienomiya 

Pinging a few people off the top of my head, but hopefully this will reach other people interested too.

**Comment by montoyamoraga** [comment]
hey @limzykenneth this sounds great to me,
and happy to test it out when it is implemented in August :)

**Comment by yukienomiya** [comment]
Sounds great to me too! happy to test it out 🙃🙃

**Comment by SanjaySinghRajpoot** [comment]
Looks good, I have read some documentation for Pontoon. Let's test this thing out 🙂

**Comment by limzykenneth** [comment]
A note here to say that things are almost ready for people to try out now: https://github.com/processing/p5.js-website/pull/1069

You can also start using the [Pontoon](https://p5js-pontoon-test.herokuapp.com/) instance right away!

**Comment by montoyamoraga** [comment]
hey @limzykenneth i tried the Pontoon instance and did some translations, i didn't know how to check if they were submitted / or next steps?
also, there are several Spanish options, could we just have one? :)

**Comment by limzykenneth** [comment]
Actually for most of the strings imported, although it says translated, they are actually still untranslated. I'll make you a manager for Spanish and you can go in and unapprove any untranslated strings. I'll probably make a video showing how everything works in a day or two but feel free to explore, it's pretty hard to do any damage to it :stuck_out_tongue_winking_eye: 

I'm only seeing one for Spanish, can you try this link: https://p5js-pontoon-test.herokuapp.com/projects/p5js-documentation/ and see if there's only Chinese, Korean, and Spanish listed? What you are seeing might be new locale request, let me turn that off for now.

**Comment by montoyamoraga** [comment]
oh got it, yeah, when i clicked on teams, it shows many Spanish languages, but only the "es" is activated, the other ones are not :)

**Comment by limzykenneth** [comment]
A basic video guide is available now: https://vimeo.com/582952817

**Comment by yukienomiya** [comment]
Hey @limzykenneth I tried it out a bit and it seems very cool! 🙃👏🏻 

I was wondering, will there be a way to create (and work on) new translations directly from the platform? Or will the translation files need to be added to the repository first?

**Comment by limzykenneth** [comment]
@yukienomiya I think a new language can be added directly from Pontoon and when syncing it will automatically create the new translation file.

**Comment by limzykenneth** [comment]
@catarak Here's the issue about Pontoon that was mentioned yesterday. If you want to look at what kind of things are required repo-side, you can have a look at this PR https://github.com/processing/p5.js-website/pull/1069

**Comment by limzykenneth** [comment]
I'm going to reopen this until the end of September to gather any feedback.

A quick update, at https://p5js-pontoon-test.herokuapp.com/projects/p5js-documentation/ all the strings incorrectly labelled as "translated" have been corrected to not have a translation and please go ahead and work on them if you like! I will do occasional syncing of Pontoon with the website repo and that will update the translation on the live website.

Any feedback, please do let me know either here or through other mediums.
