### ISSUE TITLE
Array.fill() didn't fill; it fill color.

### ISSUE THREAD

**Issue by MrBean3737** [processing/p5.js#5364]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [x] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version: 1.4.0
- Web browser and version: 92.0.4515.107 (Official Build) (64-bit)
- Operating System: Windows 10 Version 10.0.19042 (Build 19042)
- Steps to reproduce this:

```
var Test = Array(10).fill(Array(10))

function setup() {
  createCanvas(400, 400);
  for(var x=0;x<Test.length;x++){
    for(var y=0;y<Test[x].length;y++){
      console.log(Test[x][y])
    }
  }
}

function draw() {
}
```

Console:

`(100) undefined`

**Comment by malviys** [comment]
Try using 
```JavaScript
var Test = Array(10).fill(Array(10).fill(color('hex-value')));
```

**Comment by murilopolese** [comment]
Hey, @MrBean3737! 👋 

May I ask you what was the output you were expecting to happen?

English is not my first language so I might be projecting my own struggles but I think there might be a misunderstanding about `fill` as in "fill my shapes with this color" and `fill` as in "fill this array with a value".

**Comment by ggorlen** [comment]
> Try using
> 
> ```js
> var Test = Array(10).fill(Array(10).fill(color('hex-value')));
> ```

This is the right idea, but be careful because the `.fill()` value is a single array rather than 10 arrays as you may intend. Changing an element of one will reflect across all 10 subarrays.

I suggest avoiding `fill` in favor of spread syntax and `.map`:

```js
const test = [...Array(10)].map(() => [...Array(10)].map(() => color("red")));
```

Full p5 example:

```js
<!DOCTYPE html>
<html lang="en">
<head>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.4.2/p5.min.js"></script>
</head>
<body>
<script>

let colors;
let size;

function setup() {
  createCanvas(500, 500);
  noLoop();
  noStroke();
  const amount = 10;
  size = width / amount;

  colors = [...Array(amount)].map(() =>
    [...Array(amount)].map(() =>
      color(random(256), random(256), random(256))
    )
  );
  // won't work--gives one solid color:
  //colors = [...Array(amount)].fill(
  //  [...Array(amount)].fill(
  //    color(random(256), random(256), random(256))
  //  )
  //);
}

function draw() {
  colors.forEach((row, i) => {
    row.forEach((color, j) => {
      fill(color);
      rect(i * size, j * size, size, size);
    });
  });
}

</script>
</body>
</html>
```
