### ISSUE TITLE
After using the push() function, the previous values cannot be seen

### ISSUE THREAD

**Issue by sahintelli** [processing/p5.js#5369]
I tried the code provided on [https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/push](url). However, on [https://editor.p5js.org/](url), it returns a different and an unexpected result for the **_push()_** function. The array is updated but the previous version is also changed. I am unable to see the original array anymore.

![image](https://user-images.githubusercontent.com/36115381/128607369-a3f4a64d-56c1-4d40-aef2-30371a308463.png)

**Comment by limzykenneth** [comment]
Hi, the editor is maintained in a separate repository and you should file this issue [here](https://github.com/processing/p5.js-web-editor/issues) instead. Thanks!

**Comment by sahintelli** [comment]
Hi 👋 I see. Thank you so much 😊✌
