### ISSUE TITLE
Strange behaviour for bezier() in sub pixel stroke weight 

### ISSUE THREAD

**Issue by andreiantonescu** [processing/p5.js#5385]
### Most appropriate sub-area of p5.js?
- [x] Core/Environment/Rendering

### Environment details:

- p5.js version: 1.4
- Web browser and version: Chrome 2.0.4515.159 (Official Build) (x86_64)
- Operating System: Mac OS 11.4

### Issue details and reproduction: 
See https://openprocessing.org/sketch/1244219

I’ve encountered some strange behavior for bezier() when using subpixel (<0.49) stroke weights. This seems to happen only on some curve configurations and only on Chrome:

The curve on the top has a glitch when going from .51 to .49 stroke weight. What is strange is that if I slightly change the curve’s configuration, it doesn’t happen anymore (see curve on the bottom).

Note that on Safari this does not happen - I believe it is due to how the browsers handle subpixel stroke weights (in Safari the .51 line seems a lot thicker).

Does anyone have any direction as to how to solve this?

**Comment by limzykenneth** [comment]
I'm not quite sure what I'm supposed to be seeing here in terms of the problematic behaviour, some screenshots would be very helpful in this case. 

That being said, I doubt there's much that can be done about it as subpixel drawings are often prone to many problems that can be traced back to the browser's implementation itself, so there's not much we can do in p5.js itself.

**Comment by andreiantonescu** [comment]
I've arrived at some acceptable workarounds. For reference, if anyone encounters problems with sub-pixel lines I recommend:
- for lines that should be < 1px, draw them at 1px but change their alpha. So if you would like to draw a line at 0.45px, draw it at 1px with 45% alpha
- draw all lines at >1px and then scale down by the needed amount
