### ISSUE TITLE
Error when running "npm run dev" related to missing parameterData.json file

### ISSUE THREAD

**Issue by gregsadetsky** [processing/p5.js#5388]
#### Most appropriate sub-area of p5.js?

- [X] Build tools and processes

#### Details about the bug:

- p5.js version: commit 22c858186f0b8e3ae12152171012aa341e976d95
- Operating System: macOS 10.15.7

#### Steps to reproduce this:

- follow instructions at https://p5js.org/contributor-docs/
- check out version 22c858186f0b8e3ae12152171012aa341e976d95
- run `npm ci`
- run `npm run dev`

Error shown is:

```
$ npm run dev

> p5@1.4.0 dev
> grunt browserify:dev connect:yui watch:quick

Running "browserify:dev" (browserify) task
Fatal error: Cannot find module '../../../docs/parameterData.json' from '<...local path...>/p5.js/src/core/friendly_errors'
```

#### Solution:

Running `npm run grunt` once before running `npm run dev` fixes the issue as it generates the missing `parameterData.json` file.

I believe that the documentation should be updated to reflect this i.e. "make sure to run `npm run grunt` at least once before running `npm run dev`"

**Comment by muziker** [comment]
I had some run time errors when doing `npm run dev`, saying minimatch wasn't a function. I altered the 2 lines in run.js mentioned in the error output to minimatch.minimatch to solve get past `npm run dev`.
