### ISSUE TITLE
Download Complete doesn't recognise loadSound()

### ISSUE THREAD

**Issue by everythingability** [processing/p5.js#5396]
Hi...

I downloaded the Complete min version of p5js that says it has the Sound library added, but it is the same size as the regular p5.min.js file and doesn't recognize loadSound()... I don't think it is in there..

Tom

**Comment by limzykenneth** [comment]
I don't think we provide such a download. Where did you get it from?

**Comment by everythingability** [comment]
https://p5js.org/download/ But my mistake sorry.... I thought sound was IN the p5js file, it's in the addons folder. Dur. Sorry.
