### ISSUE TITLE
IntelliSense for external libraries

### ISSUE THREAD

**Issue by Atcold** [processing/p5.js#5400]
# Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other: using 3rd party libraries

# Details about the bug

Visual Studio Code IntelliSense does not work for external modules.

I'm loading an external module in `index.html` which puts everything inside a specific `name` (the IDE doesn't know).
I can successfully run methods by typing `name.`, but there is no autocompletion nor documentation.

The alternative would be using `import` (which is what [the documentation of the module prescribes](https://github.com/mljs/matrix)), but I understand that p5js doesn't want me to do that.
So, I'm not sure where to look in order to solve this issue.

I've written more extensively on [StackOverflow](https://stackoverflow.com/q/69020620/2247039).
Originally I started a conversation on [p5js forum](https://discourse.processing.org/t/autocomplete-and-documentation-for-imported-p5js/), but that didn't lead to a solution.
So, I'm trying here as well, in case it is an actual issue to be handled somehow.

In case this is not achievable, I think it should be specified in the documentation.
I've spent a week trying to figure this out, and it's getting rather frustrating.

**Comment by limzykenneth** [comment]
For this the forum will still be a better place for a solution. We don't explicitly support IntelliSense and the case with a third party library is out of scope for us. I'm closing this issue for now, please do continue the discussions on the forum. Thanks.

**Comment by Atcold** [comment]
Hi @limzykenneth, thank you for following up.

I would love to continue this discussion on the forum.
Looking forward to reading your reply.

Thanks.
