### ISSUE TITLE
Bezier Glitch on certain point combinations

### ISSUE THREAD

**Issue by andreiantonescu** [processing/p5.js#5403]
#### Most appropriate sub-area of p5.js?
- [X] Core/Environment/Rendering

#### Details about the bug:
**p5.js version:** 1.4.0

**Web browser and version:** Chrome 93

**Operating System:** Mac OS 11.4

**Steps to reproduce this:**
- In certain point combinations, non-filled bezier curves produce a strange glitch, appearing as if they are filled. 
- Example: bezier(108.87, 3.78, 201.1, -128.61, 34.21, 82.54, 134.14, 126.01)
- This happens only on Chrome from my testing
- If you slightly change the points, this does not reproduce. 
- Example: https://openprocessing.org/sketch/1258357 (left is glitch, right is slightly modified points 126.01 to 126.0 on last one)
<img width="477" alt="Screenshot 2021-09-09 at 23 34 45" src="https://user-images.githubusercontent.com/5208182/132844732-98a42ddc-f2c4-4d58-b8f1-a9ca2ed43711.png">
- On HTML Canvas this does not reproduce. Example using only Canvas: https://openprocessing.org/sketch/1258759

**Comment by andreiantonescu** [comment]
For reference, if I set StrokeCap(SQUARE), then the behaviour is slightly different, although the curve still has issues:
<img width="621" alt="Screenshot 2021-09-10 at 18 53 11" src="https://user-images.githubusercontent.com/5208182/132883232-43dc51c6-2164-4a57-9e38-86c54d235a4e.png">

**Comment by awelles** [comment]
On my mac (Big Sur) this bug appears in Chrome, but everything looks fine in FireFox and Safari.

Google Chrome
Version 96.0.4664.55 (Official Build) (x86_64)

Firefox Developer
95.0b12 (64-bit)

Safari
Version 15.0 (16612.1.29.41.4, 16612)

**Comment by awelles** [comment]
This appears to be purely a Chrome bug. 

jsFiddle of bug replication without p5js: https://jsfiddle.net/k0ts7en2/1

I sent a bug report to Google.

For the curious, Chrome is fine if you remove the transform on the context (at least with those curve points):

```js
// From the fiddle: https://jsfiddle.net/k0ts7en2/1

// comment out this line and chrome is fine
ctx.transform(2, 0, 0, 2, 0, 0);
```
