### ISSUE TITLE
add text height calculation for multiline text area

### ISSUE THREAD

**Issue by outofambit** [processing/p5.js#5404]
_(As previously noted in #5366)_

We support vertical alignment of text with [`textAlign()`](https://p5js.org/reference/#/p5/textAlign), but right now the vertical height for multiline text is not computed. This means that a single line text is vertically aligned properly, but not multiline text.

It might be tricky to calculate the total height of multiline text because the [text wrap style](https://p5js.org/reference/#/p5/textWrap) will change how many lines of text are laid out.

https://editor.p5js.org/outofambit/sketches/eqIUrqXH6 would demonstrate this issue, but won't render until we release a version of p5.js with the bug fix in #5366.

**Comment by dhowe** [comment]
<img width="200" alt="image" src="https://user-images.githubusercontent.com/737638/132979314-9f843867-13f8-45ef-9e46-dcac91bddfee.png">

**Comment by dhowe** [comment]
can someone help double-check these alignments?

<img width="673" alt="image" src="https://user-images.githubusercontent.com/737638/133656992-ded5eb8e-95e7-4359-87d4-0f3abea7801e.png">

**Comment by dhowe** [comment]
Note: seems baseline and top are the identical when a width is specified, which appears to be the case in the existing reference test as well.

![image](https://user-images.githubusercontent.com/737638/133657445-e7a0146c-86bb-453f-8d1b-ce3e08762406.png)

**Comment by outofambit** [comment]
hey @dhowe thanks so much for doing this! i was going to say all the examples look right but i wasn't sure about baseline vs center but it seems you've figured that out. :) For the leading question, i think we might want to fix that, but that doesn't need to happen as part of this fix. (i just checked and the behavior your're showing is the same on the `main` branch.) so i think this is good as-is!

**Comment by dhowe** [comment]
Great. And if I remember correctly the different manner of calculating leading was a group decision made at the time as it yielded better results, but certainly open to re-discussing.

**Comment by dhowe** [comment]
also @outofambit perhaps you have a preference, one way or the another, regarding https://github.com/processing/p5.js/issues/5408 ...

**Comment by outofambit** [comment]
fixed with https://github.com/processing/p5.js/pull/5432!
