### ISSUE TITLE
Typescript @types/p5 does not recognize createVector() as p5.Vector

### ISSUE THREAD

**Issue by kiwi-fruitiwi** [processing/p5.js#5410]
### How would this new feature help [increase access](https://github.com/processing/p5.js/blob/main/contributor_docs/access.md) to p5.js?
It would make working with p5.js in IDEs better! Vectors are fairly common in P5 so having warnings pop up all over the place isn't good ^^;

#### Most appropriate sub-area of p5.js?

- [x] Build tools and processes
- [x] Math

#### Feature enhancement details:
I'm new to JavaScript so my terminology is probably incorrect. Apologies ^^;

When you use `createVector()` to make a vector, the typescript file for p5 does not seem to recognize that you are creating a `p5.Vector` object. Here is an example in WebStorm:

![createVector() does not make p5.Vectors](https://puu.sh/Ib7Zh/a57c641b33.png)

When you create one with `new p5.Vector()` instead, all `p5.Vector` methods are recognized.

![using new seems to work](https://puu.sh/Ib829/a8842b49db.png)

I'm still unsure the pros and cons of using `createVector()` vs `new p5.Vector`; it looks like the latter has some problems.

Here is my WebStorm typescript config page in case it is helpful:

![webStorm typescript config page](https://puu.sh/Ib83o/654a47e8bf.jpg)

Is this something that is easily fixable? What are the best practices regarding `createVector()` vs `new p5.Vector`?

**Comment by limzykenneth** [comment]
Hi, we don't maintain the typescript typings of p5.js in this repo. You should file this in https://github.com/p5-types/p5.ts. Thanks.
