### ISSUE TITLE
Request for adding more functions like limit for p5.Vector objects.

### ISSUE THREAD

**Issue by Madwesh123** [processing/p5.js#5428]
### How would this new feature help [increase access](https://github.com/processing/p5.js/blob/main/contributor_docs/access.md) to p5.js?
It would act similar to limit but instead of max value it would be min value and constrain the value of the vector.

#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Colour
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [x] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### New feature details:
```
_main.default.Vector.prototype.limit_min = function limit_min(min) {
            var mSq = this.magSq();
            if (mSq < min * min) {
              this.div(Math.sqrt(mSq)) //normalize it
                .mult(min);
            }
            return this;
          };
```

when above function is used it doesn't allow the vectors magnitude below min,
```
_main.default.Vector.prototype.constrain = function constrain(min, max) {
            var mSq = this.magSq();
            if (mSq < min * min) {
              this.div(Math.sqrt(mSq)) //normalize it
                .mult(min);
            }
            else if (mSq > max * max) {
              this.div(Math.sqrt(mSq)) //normalize it
                .mult(max);
            }
            return this;
          };

```

when above function is used vectors magnitude is set between max and min,

**examples:**
```
var x = createVector(100, 0);
x.limit_min(20);

//will result in x having {x:100, y:0, z:0}

var x = createVector(10, 0);
x.limit_min(20);

//will result in x having {x:20, y:0, z:0}

var x = createVector(10, 0);
x.constrain (20, 50);

//will result in x having {x:20, y:0, z:0}

var x = createVector(60, 0);
x.constrain (20, 50);

//will result in x having {x:50, y:0, z:0}

var x = createVector(30, 0);
x.constrain (20, 50);

//will result in x having {x:30, y:0, z:0}

```

**Comment by Qianqianye** [comment]
We are not seeing a clear explanation of how this issue [expands access](https://github.com/processing/p5.js/blob/main/contributor_docs/access.md), so I will close this issue for now. If an access statement can be added to the issue request, please feel welcome to reopen. Thank you!
