### ISSUE TITLE
check if keyIsPressed === true

### ISSUE THREAD

**Issue by michaeleggers** [processing/p5.js#5430]
Hello :)
Could we change the docs for `keyIsPressed `to not be checked against `true ` explicitly?
It is on: https://p5js.org/reference/#/p5/keyIsPressed

### How would this new feature help
Avoiding to teach new devs bad coding-habit:

`function draw() {
  if (keyIsPressed === true) {
    fill(0);
  } else {
    fill(255);
  }
  rect(25, 25, 50, 50);
}`

#### Most appropriate sub-area of p5.js?

- [x] Documentation

#### Feature enhancement details:

`function draw() {
  if (keyIsPressed) {
    fill(0);
  } else {
    fill(255);
  }
  rect(25, 25, 50, 50);
}`

**Comment by limzykenneth** [comment]
Hi @michaeleggers, can you expand a bit more about why checking against `true` is considered bad coding habit? I would actually consider it a good practice, especially in Javascript where truthyness can be a common pit falls for beginners, but I'm interested in hearing about your perspective.

**Comment by saivan** [comment]
I actually have to agree with @limzykenneth, whilst I appreciate brevity and would almost certainly write `if(keyIsPressed)` in my own code, in a library I think the explicit check is better. Mainly because something like `Boolean("hello")` is still true.

**Comment by naveen106** [comment]
I think it is better like this - 
```
function draw() { 
  if (keyIsPressed) 
  fill(0); 
  
  else  fill(255); 
  rect(25, 25, 50, 50);
}
```

**Comment by michaeleggers** [comment]
@limzykenneth Actually, good thought! Haven't taken that into account when opening the issue. However, the reference page for `mouseIsPressed` doesn't do that (https://p5js.org/reference/#/p5/mouseIsPressed). Maybe I am a bit too pedantic here, but I guess we should at least be consistent then?

@saivan I think you're right, but this issue is about the example in the reference pages. Maybe my issue is not making it clear enough, if so, I'm sorry. (Couldn't change the label for the issued to documentation).

@naveen106 Think so too. 

Thanks for dealing with this. I work in education and the documentation is a crucial part :)

**Comment by limzykenneth** [comment]
Consistency would be a good thing to go for and I don't mind `mouseIsPressed` reference example be edited to match `keyIsPressed` if there's no other opinion on this.

**Comment by michaeleggers** [comment]
> Consistency would be a good thing to go for and I don't mind `mouseIsPressed` reference example be edited to match `keyIsPressed` if there's no other opinion on this.

@limzykenneth If it's ok for you I'd like to 'fix' this and do a pull request. I'd tag you.
