### ISSUE TITLE
how to dispatch event to p5 instance?

### ISSUE THREAD

**Issue by jiharu** [processing/p5.js#5441]
I have an offscreen canvas p5 instance that I need to dispatch events (mouse etc.) to, but it doesn't seem to be possible (or it is not documented how to). 

The p5 instance is not part of an on-screen <canvas> tag, but is used entirely offscreen. I need dispatch mouse events to it manually.

In HTML5 you can dispatch mouse events to arbitrary elements like this:

```js 
targetElement.dispatchEvent(new MouseEvent("click", {
    clientX: 20, clientY: 30, // etc.
}));
```

With the offscreen canvas, this doesn't seem to have any effect:

`instance._elements[0].canvas.dispatchEvent(...)` does not invoke the script's `mouseClicked` handler.
`instance._elements[0].elt.dispatchEvent(...)` does not invoke the script's `mouseClicked` handler either.

Looking into what `new p5()` returns, I see `_events.click`, but directly invoking the `instance._events.click()` doesn't seem to have any effect on the script's `mouseClicked` handler either.

I'm posting this here rather than the forum because a) if this is not currently supported, this would be a feature request, or b) if it is, it is a documentation request :-)  but please point me to a better place if there is one. 
 
Context:

The p5 instance is not being displayed in an on-screen canvas element, I am using the p5 instance as an off-screen canvas to produce a texture that is being displayed in a Three.js scene. I'm wanting to use Three.js interaction (raycaster) to provoke the equivalent of mouse events in the p5 instance (e.g. raising a `mouseClicked()` event in the p5 script).   The Three.js aspect here is irrelevant to the question though -- it should be general to using p5 instances with an offscreen canvas as far as I can tell. 

Thanks so much for looking into this!  And apologies if I missed some documentation that covers this already.

**Comment by Qianqianye** [comment]
Hi @jiharu! I'm closing this for organizational purposes. Please reopen it if you can provide an example like @limzykenneth suggested that illustrates the issue. Thanks!
