### ISSUE TITLE
frameRate will not run faster than 30 frames

### ISSUE THREAD

**Issue by RedBeard41** [processing/p5.js#5450]
frameRate not displaying faster than 30 frames per second.

- Found a bug

#### Details about the bug: 

- Web browser and version: 

Google Chrome | 94.0.4606.81 (Official Build) (64-bit) (cohort: Stable)
-- | --
Revision | 5a03c5f1033171d5ee1671d219a59e29cf75e054-refs/branch-heads/4606@{#1320}
OS | Windows 10 Version 1607 (Build 14393.4583)

- Operating System: Windows
- Steps to reproduce this bug:
I have ran multiple programs and they are all capping at 30 frames per second.  Even when I manually set the frameRate in setup to 60 it will still not run faster than 30fps.  I have a completely empty project that is doing nothing other than running the frameRate in a console.log and it still will not run faster than 30 fps.  I have restarted browsers, and restarted the computer to see if it was a memory issue.  The problem remains.

function setup() {
  createCanvas(400, 400);
  //frameRate(60);
}

function draw() {
  background(220);
  console.log(frameRate());
}
![error1](https://user-images.githubusercontent.com/42767289/137192864-2064183a-3d1f-4901-8d94-469eafe6ba79.PNG)
![error2](https://user-images.githubusercontent.com/42767289/137192865-0811f285-e48e-446a-becf-c0a81aafc99b.PNG)

**Comment by limzykenneth** [comment]
The framerate of p5.js is tied directly to [`requestAnimationFrame`](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame) which in turn is tied to the refresh rate of the monitor, ie if you have a  60Hz monitor the framerate will be 60fps and a 30Hz display (some projectors for example) will have 30fps.

If you need some sort of consistent timing in the animation loop, you can use `deltaTime` as part of the animation calculation instead.

**Comment by RedBeard41** [comment]
@limzykenneth thank you so much for your input.  I am running a dual monitor setup, with one of the monitors being duplicated with the Qomo board for class.  I was running only at 30hz refresh rate.   When I bumped down the resolution to something that supported 60hz refresh then the frameRate in P5js is running again at 60 fps.
