### ISSUE TITLE
Semi-transparent objects in WebGL mode make the background behind them transparent

### ISSUE THREAD

**Issue by tonyrobots** [processing/p5.js#5451]
#### Most appropriate sub-area of p5.js?

- [x] Color
- [x] Core/Environment/Rendering
- [x] WebGL

#### Details about the bug:

- p5.js version: 1.4.0
- Web browser and version:  reproduced on multiple browsers
- Operating System: Windows 10
- Steps to reproduce this:

1. Create a canvas in WEBGL mode
2. Set the background color to something (white is fine)
3. Draw an object on the canvas that is semi-transparent, e.g. RGBA color (100,100,100,150)
4. Without changing the background color of the p5.js canvas, change the background color (or image!) of the page it's sitting on -- you will see that it affects the color of the objects on the canvas

It appears the canvas background behind the cube (or other object) is not appearing (i.e. is completely transparent), and the transparency of the object is exposing the background of the webpage itself. 

Here is an example that makes it very clear (no pun intended!), since I've specified a background image pattern in the css:

[https://openprocessing.org/sketch/1309599](https://openprocessing.org/sketch/1309599)
![Screenshot 2021-10-14 181900](https://user-images.githubusercontent.com/178870/137416956-1992b77f-6554-4a56-9ff8-bbb89e5f7867.png)

In this example:
The background image of the html page is set to be a repeating red "x"
The background of the canvas is a solid (no alpha) green
The color of the spinning cube and rect is (RGBA) color(255,80,180,150) -- note the "150" alpha value.
It appears the canvas background behind the cube is not appearing (i.e. is completely transparent), and the transparency of the cube is exposing the background of the webpage itself.
Indeed, even a PNG capture (hit 's' to saveCanvas()) has the same behavior, and the background of whatever you
look at the PNG on (a web browser, an OS image viewer, whatever) shows through in the area of the cube.  (It does *not* in this example capture the "x"s, rather it preserves the transparency. Same happens with GIF capture with createloop.p5 or any capture with CCapture.js -- the issue is with the object itself as rendered in ps.j5)

Also attached two files -- the code is identical; only the background color of the underlying web page has changed (from white to black.) You can see the profound effect on the color of the object because the underlying color is showing through.
![bug_left_black](https://user-images.githubusercontent.com/178870/137416788-a18663fa-58d1-4380-94f5-e8b1b7472fb2.png)
![bug_right_white](https://user-images.githubusercontent.com/178870/137416799-e4a038a8-a9ad-44a8-9f2e-1e9adb9106e5.png)

**Comment by sflanker** [comment]
This seems relevant: https://medium.com/david-guan/alpha-blending-and-webgl-823d86de00d8

**Comment by aferriss** [comment]
I think you should also be able to call `setAttributes('alpha', false); ` somewhere in your sketch to fix this issue.
