### ISSUE TITLE
lib/p5.js is missing

### ISSUE THREAD

**Issue by clankill3r** [processing/p5.js#5456]
`lib/p5.js`  is missing from the repository.

In `lib/readme.txt` it says:

```
# Contents of the p5 folder

* p5.js file
* p5.min.js file
* addons folder
  * p5.sound.js
  * p5.sound.min.js
* empty-example folder
  * index.html
  * p5.js
  * p5.sound.js
  * sketch.js
```

But most of those files are just not there.
I just figured I have to run `grunt`. The thing is, `grunt` is a nightmare to install.

It would be so nice if those files where included in the repository so I can look at some of the examples.

**Comment by limzykenneth** [comment]
The folder is what gets eventually packaged into the zip file that is downloaded from the official website (the readme.txt thus is for that zip file, not for this repo). The built library is not usually included in repositories as the idea is that it bloats the repository while those who cloned the repo can build the library itself using the build steps.

If you are able to clone the repo and run `npm install` you do not need to install `grunt` as that is installed already, you can run either `npm test` or `npx grunt` and you will be able to build the library if you wish to.

**Comment by Qianqianye** [comment]
Thanks @limzykenneth for answering this. Would it be okay to close this issue  for now @clankill3r? Thank you!

**Comment by clankill3r** [comment]
I don't know, I still think it makes sense to include them in the repository or to add a note about `npm install`.

**Comment by limzykenneth** [comment]
The main way to get a copy of p5.js is meant to be through one of the release channel (website download, CDN, GitHub Release) and it is not common to include build artifacts which the p5.js file is in the repo itself. 

One reason is that the current HEAD version of p5.js is not guaranteed to be stable or working so it isn't recommended that it be used.

Another reason is that including the build artifacts in the repo will make reviewing PR difficult as every source change will also change the build artifacts creating unnecessary diff in PR and git history. There's a problem with source of truth as well such as if the source or build artifacts were edited separately and the build step wasn't run to keep things in sync, we will need to resolve that difference manually.

There are other reasons why those build artifacts are not included as well but do you have a use case in mind where having those build artifacts included be useful?
