### ISSUE TITLE
textToPoints not working with letter "B" from Google Font

### ISSUE THREAD

**Issue by pifragile** [processing/p5.js#5462]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [x] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version: 1.4.0
- Web browser and version:Chrome 94.0.4606.81 
- Operating System: MacOSX
- Steps to reproduce this:

I loaded the Google Font "Dancing Script" and used `textToPoints` on it. It works well for all letters, but with letter "B" no points are returned. When simply using "text" with the same font, the letter "B" prints as expected. So i suppose it is not a problem with the font.

Please refer to https://editor.p5js.org/pifragile/sketches/l0JS6TCks. It is all setup there. You can take a look at the console output and you can see that for letter "B" an empty array of points is returned.

**Comment by dhowe** [comment]
> it occurs to me that we may need to handle other types of whitespace in that function, let me do a few more tests before we merge

**Comment by dhowe** [comment]
So this is fine with single or multiple spaces, including tabs, and can be merged as is
I do notice a possible issue with line breaks, but will create a new ticket for this

**Comment by limzykenneth** [comment]
Fixed by #5466
