### ISSUE TITLE
Description for hour() has the wrong integers

### ISSUE THREAD

**Issue by eents** [processing/p5.js#5463]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other (specify if possible)

#### Details about the bug:

The reference for hour() says that it returns the current hour as a value from 0 - 23, but I think it actually returns a value from 1 - 24!

**Comment by reejuBhattacharya** [comment]
I tested the hours() function and could not replicate the error. For me, it returned between range 0-23, as it should.

**Comment by limzykenneth** [comment]
Closing as we can't replicate this. @eents If you can provide an example that replicates your problem, do let us know. Thanks.
