### ISSUE TITLE
Orthographic projection incorrectly renders stroke of a rotating cube

### ISSUE THREAD

**Issue by prichodko** [processing/p5.js#5464]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

First of all, thank you for this wonderful library. 

While playing with rotating cubes, I've noticed that using `ortho()` incorrectly renders the rear corner of the cube. You can see this happening here – look at the biggest cube: https://editor.p5js.org/prichodko/sketches/_b3OEhoLG.

Default camera is working correctly. 

Let me know, if there is anything I can help with.

**Comment by stalgiag** [comment]
Hi! Thanks for the issue.

Not sure what this is off the top of my head and I can't investigate now. I'll just add that this particular sketch is 'fixed' by adding `translate(0, 0, 200);` to the top of the `cube()` function. Hopefully this is helpful in tracking down the issue!

**Comment by Qianqianye** [comment]
Thanks @prichodko for the issue and @stalgiag for offering a fix. Are we good with closing this issue for now for organizational purpose or should we keep it open to gather more discussion?

**Comment by stalgiag** [comment]
I think we can close this as an edge case and see if the issue pops up again in a way that is more broadly reproducible.
