### ISSUE TITLE
Error in example in references for p5.Vector.setMag() 

### ISSUE THREAD

**Issue by TOrfevres** [processing/p5.js#5465]
Here's what the documentation says about p5.Vector.setMag() 
![image](https://user-images.githubusercontent.com/23334809/139310979-8010db76-ad53-4a39-b192-55c5f7675ed3.png)

But by doing it in the web editor AND by hand here is the real result:
![image](https://user-images.githubusercontent.com/23334809/139311341-ea379c83-a1b2-4ed2-bff3-010e3098bf6a.png)

Regards,
Hope it helps

**Comment by limzykenneth** [comment]
The original vector here probably should be `createVector(3, 4, 0)`
