### ISSUE TITLE
Imprecise description of strokeWeight

### ISSUE THREAD

**Issue by soegaard** [processing/p5.js#5468]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x ] Other (specify if possible) - documentation

#### Details about the bug:

The description of `strokeWeight` from [2] says:

> Sets the width of the stroke used for lines, points and the border around shapes. 
> All widths are set in units of pixels.

The problem is that the last part "All widths are set in units of pixels." is true only
if there is no transformation active.

After, say, `scale(10)` the effect of `strokeWeight(1)` is to set the line width to 10 pixels.

The MDN documentation [1] uses the phrase:

> A number specifying the line width, in coordinate space units. 

Now, "coordinate space units" may not we the most beginner friendly phrasing,
but a side note explaining that the current transformation affects the interpretation
of argument given to `strokeWeight` would be appreciated.

[1] https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/lineWidth

[2] https://github.com/processing/p5.js/blob/v1.4.0/src/core/shape/attributes.js#L331

**Comment by reejuBhattacharya** [comment]
Is this a documentation issue? If it is, I would like to work on it, if available
