### ISSUE TITLE
textToPoints() not handling line-breaks correctly

### ISSUE THREAD

**Issue by dhowe** [processing/p5.js#5474]
textToPoints() inserts a blank character instead of a line-break

For the string 'B\nA', text() (in white) handles linebreak correctly, while textToPoints() does not:

<img width="231" alt="image" src="https://user-images.githubusercontent.com/737638/141467173-98d40d7d-5211-4d57-ae6a-26219af5ff91.png">

```js

// load font first

function setup() {
  createCanvas(400, 400);
  textFont(font, 100);
  pts = font.textToPoints('B\nA', 0, 0, 100, {
    sampleFactor: 0.4 // increase for more points
  });
  background(0);
  fill(255);
  noLoop()
}

function draw() {
  text('B\nA', 200, 200)
  pts.forEach(p => circle(200 + p.x, 200 + p.y, 3));
}
```

**Comment by sixhat** [comment]
Does this happens with other non-printing characters, like '\t', spaces, etc...

**Comment by dhowe** [comment]
tab and spaces, definitely not
I suppose we will need to catch line break chars (\r, \n etc.) and insert our own linebreaks

**Comment by ffd8** [comment]
Being able to add `\n` line breaks to `textToPoints()` would be huge and oh so useful! 
I'm not so sure that opentype.js supports it?

**Comment by dhowe** [comment]
no, I think it would just require computing the layout for the entire string (as we do with text()), then handling each line (after line breaks) separately

and this is also the workaround we can suggest in the meantime: 'pass each line to textToPoints() separately`

**Comment by Ashley-Y-Lin** [comment]
Is anyone currently working on this?

**Comment by dhowe** [comment]
Not to my knowledge

**Comment by Aqmalp99** [comment]
Hey, I am part of a group from the University of Adelaide. My group and I would like to work on this issue as a part of an open-source contribution project. Are we able to tackle this issue?

**Comment by Decoy4ever** [comment]
Hey, my group and I from the University of Adelaide want to tackle this issue as part of an open-source contribution project. Is the issue still available to for us to tackle?

**Comment by davepagurek** [comment]
I believe it's still up for grabs! I'll assign it to you.

**Comment by munusshih** [comment]
Hi guys! I'm working on this issue as part of my GSoC project. I will do a pull request by adopting most of @Decoy4ever 's suggestion here (https://github.com/processing/p5.js/pull/6163) and fix this in the future version of p5 👍
