### ISSUE TITLE
Top Bar on embed window

### ISSUE THREAD

**Issue by burnedsap** [processing/p5.js#5476]
Hello,

I see that there's a top bar with the p5js logo and the button to the code added on the embeds–can we remove this? It causes the embeds to have scroll bars (especially on embeds posted on websites before this bar was introduced. Is there a way to embed sketches from the editor without this top bar? 

![Screenshot 2021-11-20 at 4 54 45 PM](https://user-images.githubusercontent.com/4111699/142742066-880e4f2a-c7ca-43de-8e98-6d9e56a94cec.png)

#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other (specify if possible) Embeds/Visual layout

**Comment by limzykenneth** [comment]
Hi, this is an issue specific to the web editor which is maintained in a separate repo. You should file this issue [here](https://github.com/processing/p5.js-web-editor/issues) instead. Thanks.
