### ISSUE TITLE
TypeError: null is not an object (evaluating 'this.drawingContext.scale')

### ISSUE THREAD

**Issue by ccccooooddddyyyy** [processing/p5.js#5477]
I'm very new to the community so  I can't really write all aspects of the problem.
I just want to open an issue I don't know what to do next. Please do ask me questions.

```TypeError: null is not an object (evaluating 'this.drawingContext.scale')```

```js
import * as p5 from "p5"
import React from "react"
import Module from "@p5/0_module"
import ModuleCanvas from "@p5/main"

import styles from "@styles/Outlooks.module.scss"

class SketchOutlooks extends React.Component {
    constructor(props) {
        super(props)

        this.myRef = React.createRef()
        this.sketchRef = React.createRef()

        this.entry = this.props.entry
    }

    Sketch = (p) => {
        let canvasDiv = this.myRef.current
        let FPS_DEFAULT = 30

        p.FRAME_COUNT = 0
        p.MODULE_RATIO_TO_CANVAS = 0.45

        p.setup = () => {
            p.canvas = new ModuleCanvas(p, canvasDiv.clientWidth, canvasDiv.clientHeight)

            p.MODULE_RADIUS = canvasDiv.clientWidth * p.MODULE_RATIO_TO_CANVAS

            p.frameRate(FPS_DEFAULT)
            p.FPS_RELATIVE_SPEED = 1

            p.rectMode(p.CENTER)
            p.ellipseMode(p.CENTER)

            p.strokeCap(p.SQUARE)

            p.getModuleByID()

            p.MAX_NOISE_SEED = 10000
            p.MODULE_VERTEX_COUNT = 6
        }

        p.getModuleByID = () => {
            p.createModule(p, p.createVector(0, 0), this.entry.visualization)
        }

        p.createModule = (p, pos, vis) => {
            p.thisModule = new Module(p, pos, vis)
            p.thisModule.id = this.entry.id
            p.thisModule.username = this.entry.instagram.username
            p.thisModule.timestamp = this.entry.instagram.taken_at
        }

        p.draw = () => {
            p.background(0)
            p.FPS_RELATIVE_SPEED = p.frameRate() >= 5 ? (FPS_DEFAULT * 1.0) / p.frameRate() : 1

            if (p.thisModule != null) {
                p.push()
                p.translate(p.width / 2, p.height / 2)
                p.rotate(p.FRAME_COUNT * p.thisModule.rotationSpeed)

                if (!p.canvas.isPaused) {
                    p.thisModule.run()
                    p.FRAME_COUNT++
                }
                p.thisModule.display()

                p.pop()
            }
        }
    }

    // React things to make p5.js work properly and not lag when leaving the current page below
    componentDidMount() {
        this.myP5 = new p5(this.Sketch, this.sketchRef.current)
    }

    componentDidUpdate() {
        this.myP5.remove()
        this.myP5 = new p5(this.Sketch, this.sketchRef.current)
    }

    componentWillUnmount() {
        this.myP5.remove()
        console.log("Unmouted.")
    }

    render() {
        return (
            <div ref={this.myRef} className={styles.canvas}>
                <div ref={this.sketchRef} />
            </div>
        )
    }
}

export default SketchOutlooks
```

The issue seems to more likely to happen when I render 100x canvas in a page:
```js
// My data had about 100 entries to pass data to the p5 canvas
{data.entries.map((entry) => {
  return (
 <SketchOutlooks entry={entry} />
 )})}
 ```

<img width="513" alt="CleanShot 2021-11-21 at 20 38 16@2x" src="https://user-images.githubusercontent.com/8092790/142764204-0b80caac-0a7e-4511-8cba-bf156ec4736e.png">

#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Web browser and version: iOS Safari 15.0
- Operating System: iOS
- Steps to reproduce this bug: Navigate back and forth in Next.js Application

**Comment by limzykenneth** [comment]
Hi @ccccooooddddyyyy, can you provide a simple example that we can run that reproduces this problem? Ideally without being a react component. Thanks.

**Comment by ccccooooddddyyyy** [comment]
Hello @limzykenneth,
I also included:
- Axios, useSWR for fetching heavy data. 
- Styling with CSS grid (what I think can be the main reason because the canvas width & height calculated by div size)

Codesandbox: https://codesandbox.io/s/mystifying-matan-2ee3x
Preview link: https://7lf8g.sse.codesandbox.io/ (Tap screen to route between pages)

Tested on iOS Safari 15.1
If you go back & forth too constantly. The error will occur.

Images from my iPhone XS Max:
![IMG_2736](https://user-images.githubusercontent.com/8092790/142773801-3f0d792b-d806-4619-afa0-d9815aacaf2f.png)

![IMG_2737](https://user-images.githubusercontent.com/8092790/142773805-c071586c-17b5-4818-95fd-74fe12beaad6.png)

My sandbox is messy but these are APIs, and P5 codes I'm using for my current project.

**Comment by limzykenneth** [comment]
I'm afraid you really have to simplify it here as I cannot debug the whole code that you have. Running the preview link you provided also doesn't give the same error that you've shown here.

**Comment by willmartian** [comment]
Hey @ccccooooddddyyyy, it looks like this might be performance-related issue of your app creating multiple canvases. 

Using your code sandbox preview link, I am able to reproduce the issue if I repeatedly click back and forth between the two pages:

<img width="773" alt="image" src="https://user-images.githubusercontent.com/17113462/143466667-279b7a4a-4d14-4cba-ae11-5b729a66e595.png">

Note that I am only able to do this when emulating a mobile device, and not in the normal browser mode. I believe the mobile device emulator has a lower memory usage limit, so this makes sense. 

Doing some investigating on that memory use warning message, it looks like others have found success by setting the width and height of the canvas to 0 when unmounting a React component: https://stackoverflow.com/questions/52532614/total-canvas-memory-use-exceeds-the-maximum-limit-safari-12#comment102082116_52586606

Perhaps give that a try in your app and report back here on if it helps or not?

**Comment by ccccooooddddyyyy** [comment]
> 

Yes, thank you.
I can confirm this is a memory-related issue. I had to lower the number of canvases rendered and were looping at a time.
