### ISSUE TITLE
Typo in Hindi translation of the contributor_docs

### ISSUE THREAD

**Issue by IamEzio** [processing/p5.js#5489]
I found two translation mistakes in the Hindi translation of the contributor_docs. The link to file can be found [here](https://github.com/processing/p5.js/blob/main/contributor_docs/hi/README.md)
 1. Hindi translation of the docs misses the logical NOT operator
![Error2](https://user-images.githubusercontent.com/89375125/144286118-b4bcd50c-25ab-484f-82e5-8fce3340cb1f.jpg)
![Error2 b](https://user-images.githubusercontent.com/89375125/144286218-47677796-8070-4fc4-93b0-2f9c4ed4551d.jpg)

 2. The word "कहा" translates to a different meaning
  ![Error1](https://user-images.githubusercontent.com/89375125/144284651-6e071ee7-0e87-4303-a4c4-edbf1bd3bf6f.jpg)

	 <img width="514" alt="error1 sol" src="https://user-images.githubusercontent.com/89375125/144285201-d2ab556e-c146-4f83-b19a-d3ba55eb6484.png">

	 Instead "कहां" should be used which translates to the word "where" :

	<img width="509" alt="error 1 sol b" src="https://user-images.githubusercontent.com/89375125/144285444-803ef662-1bee-4dbf-becf-508a81fd1c85.png">

Sorry, I accidently made a Pull request before I created an issue. I am a newbie here and liked your editor tool. I am exploring the source code and looking forward to contribute and help :)

**Comment by sambhavsaxena** [comment]
can i work on this?

**Comment by limzykenneth** [comment]
@IamEzio You can go ahead and submit the PR. Thanks.

@sambhavsaxena Thanks for your interest but since @IamEzio already have a PR ready I'll let them submit it instead. You can check out some of the other issues here that may need help with.
