### ISSUE TITLE
angleMode(DEGREES) ignored by Math.cos() Math.sin() ?

### ISSUE THREAD

**Issue by rzeta0** [processing/p5.js#5491]
It looks like angleMode(DEGREES) is ignored by Math.cos() Math.sin().

My old drawings all work fine with older versions of p5js, so this looks like a new bug.

```
function setup() {
	createCanvas(windowWidth, windowHeight);
	background(100);
	angleMode(DEGREES);
	noLoop();
}

function draw() {
	print(Math.cos(90));
	print(Math.sin(90));
}
```

results in the wrong answers

```
-0.4480736161291701
0.8939966636005579
```

**Comment by aferriss** [comment]
Hi @rzeta0 

Any function that is prefixed with `Math.` is part of native javascript, and not part of p5. Anglemode and other p5 functions will never affect those functions.

If you drop the Math. prefix however, there is a p5 version of cos and sine that will respect the angle mode.

The following should work like you expect.

```
function setup() {
	createCanvas(windowWidth, windowHeight);
	background(100);
	angleMode(DEGREES);
	noLoop();
}

function draw() {
	print(cos(90));
	print(sin(90));
}
```
Going to close the issue for now, but please feel free to reopen if my answer wasn't correct.
