### ISSUE TITLE
p5.Vector.setHeading uses radians, even when angleMode(DEGREES) is specified

### ISSUE THREAD

**Issue by oleboleskole3** [processing/p5.js#5497]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [x] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version: 1.4.0
- Web browser and version: Chrome v96.0.4664.45
- Operating System: Windows
- Steps to reproduce this:
```js
function setup() {
  angleMode(DEGREES)
  const vector = createVector(0, 1)
  vector.setHeading(1)
  console.log(`Expected: 1, Received: ${vector.heading()}`)
}
```
Logs `Expected: 1, Received: 57.29577951308232` to the console, but
```js
function setup() {
  angleMode(RADIANS)
  const vector = createVector(0, 1)
  vector.setHeading(1)
  console.log(`Expected: 1, Received: ${vector.heading()}`)
}
```
Logs `Expected: 1, Received: 1` to the console

**Comment by awelles** [comment]
`p5.Vector.fromAngle()` and `p5.Vector.fromAngles()` also ignore `angleMode(DEGREES)`

**Comment by limzykenneth** [comment]
Fixing this would probably count as a breaking change so I'm not 100% sure if we want to fix this as this stage. Alternatively on the vector and angle related functions documentation we can add a note about this and suggestion to use `radians()` to convert the values where needed.

**Comment by Willyham** [comment]
Please add this to the docs 🙏 . I just got tripped up by this for a few hours until I read the source and realised it only took radians as input.

**Comment by limzykenneth** [comment]
I'm having a reverse on opinion here and think all angle related methods under p5.Vector probably should be respecting `angleMode()` because `heading()` and `angleBetween()` are already doing so but the rest isn't, creating a pretty inconsistent experience that will more likely to be viewed as a bug.

**Comment by KevinGrajeda** [comment]
Functions in p5.Vector taking angleMode() into consideration:
- [x] [heading()](https://p5js.org/reference/#/p5.Vector/heading)
- [ ] [setHeading()](https://p5js.org/reference/#/p5.Vector/setHeading)
- [x] [rotate()](https://p5js.org/reference/#/p5.Vector/rotate)
- [x] [angleBetween()](https://p5js.org/reference/#/p5.Vector/angleBetween)
- [ ] [fromAngle()](https://p5js.org/reference/#/p5.Vector/fromAngle)
- [ ] [fromAngles()](https://p5js.org/reference/#/p5.Vector/fromAngles)

should we make `setHeading()`,`fromAngle()` and `fromAngles()` use the current `angleMode()`? 
@limzykenneth i would like to have your opinion on this so i can start making changes.

**Comment by KevinGrajeda** [comment]
@jeffawang, @AdilRabbani, I would also like to know your opinion.

**Comment by limzykenneth** [comment]
@KevinGrajeda You can file PRs to apply angle mode to those functions.

**Comment by jeffawang** [comment]
> @jeffawang, @AdilRabbani, I would also like to know your opinion.

Thanks for finding other instances that need to change. I agree witih @limzykenneth's conclusion that it's a breaking change but that it's worth fixing for consistency.

**Comment by KevinGrajeda** [comment]
hey @limzykenneth i think #5495 closed this by mistake.
