### ISSUE TITLE
sketches not loading via require.js

### ISSUE THREAD

**Issue by rjbultitude** [processing/p5.js#550]
When using the AMD loader require.js sketches do not run correctly. The modules that depend on p5 load the library and run the code but do not seem to have access to any of the p5 methods. 

I have created a demo of this issue in this repository: https://github.com/rjbultitude/p5-requirejs-demo

When loading the sketch and library via standard inline script tags the sketch runs as expected, appending the canvas element and animating my objects. 
It might be that I'm missing something obvious (do I need to pass in the p5 object to the define callback and call an init function?) so some documentation would be very helpful.

**Comment by brysonian** [comment]
when using AMD the p5 methods are not pushed into the global namespace. I had imagined that folks using AMD would want that, I'll have to play with shim configuration options to see if there is a way around it. 

here is a quick AMD example:
```
require(["p5"], function(p5) {

	var myp5 = new p5(function( sketch ) {
	  sketch.setup = function() {
	    var cnv = sketch.createCanvas(400, 400);
	  }

	  sketch.draw = function() {
	  	sketch.background(0,0,0);
	  	sketch.fill(0);
	  	sketch.ellipse(sketch.random(0, sketch.width), sketch.random(0, sketch.height));
	  }
	}, 'sketch-div');

});
```

**Comment by lmccart** [comment]
@rjbultitude does this solve your issue, or are you still having problems?

**Comment by rjbultitude** [comment]
Yes, this solved my issue. I was hoping that all my modules/sketches would have access to the global p5 object but it's not too much of problem to use the constructor and callback. Many thanks.

**Comment by lmccart** [comment]
ok great!

**Comment by hkmoon** [comment]
This tip works in Jupyter notebook too. Thanks, @brysonian !
