### ISSUE TITLE
Remove `touchX`, `touchY` from wiki

### ISSUE THREAD

**Issue by JaPatGitHub** [processing/p5.js#5501]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [x] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other -Wiki

#### Details about the bug:

- Web browser and version: Chrome 96.0.4664.93 (Official Build) (64-bit) (cohort: 96_win_93)
- Operating System: Windows 10
- Issue: 
`touchX`, `touchY` doesn't work and also doesn't exist in p5.js reference. However it is mentioned in the [Mouse & touch interaction](https://github.com/processing/p5.js/wiki/p5.js-overview#mouse-and-touch-interaction) section of this page.

At the same time I notice `mouseX`, `mouseY` works fine with touch devices too. Hence I believe they're wrongly mentioned in the wiki/
- Steps to reproduce this:

Using `touchX` in the [editor](editor.p5js.org)
```javascript
function touchStarted() {
 console.log(touchX)
  }
```
the console displays a reference error:
![image](https://user-images.githubusercontent.com/73636668/131767950-094d3a59-1824-4329-a580-7b47ae86051a.png)

**Comment by limzykenneth** [comment]
Removed those references. Thanks.
