### ISSUE TITLE
Blurred straight lines in 2D mode from 0.7.3 to 0.8.0 (up to 1.4.0)

### ISSUE THREAD

**Issue by ctrlbru** [processing/p5.js#5505]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [X] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version: 0.8.0 through 1.4.0
- Web browser and version: Chrome 96.0.4664.93 / .92
- Operating System: Windows 10 / Android 11
- Steps to reproduce this:

[Behavior with 0.7.3](https://codepen.io/ctrlbru/pen/YzrpmZM)
[Behavior with 0.8.0](https://codepen.io/ctrlbru/pen/KKXNOmW)
[Behavior with 1.4.0](https://codepen.io/ctrlbru/pen/jOGVgxw)

I have a matrix of squares drawn using P2D with rect(x, y, w, h, 0, 0, 0, 0). They appear crisp with 0.7.3 and blurry with 0.8.0-1.4.0. I checked the changes from 0.7.3 to 0.8.0 but I was unable to find the reason.

0.7.3
![image](https://user-images.githubusercontent.com/4280720/145862977-104d5523-c35d-4a0a-833a-b4c8eb14a7e2.png)

0.8.0-1.4.0
![image](https://user-images.githubusercontent.com/4280720/145863217-42c92dae-6062-48b8-9134-f98bcc2e8046.png)

**Comment by limzykenneth** [comment]
The change came in ea260a098ab7c9195b090e91f9b4a4df380a2a57 / #3619 to fix issue reported in #3576 which has to do with stroke alignment of shapes. I'm not 100% familiar with how things work in these parts but any fix to this issue will need to take into account the original issue.

**Comment by ctrlbru** [comment]
Oh well... it looks like calling translate(0.5, 0.5) before rect is enough to fix it, I guess I'll go with that.
