### ISSUE TITLE
Drawing webgl graphics on a 2d canvas not updating

### ISSUE THREAD

**Issue by jackcruden** [processing/p5.js#5509]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version: 1.4.0
- Web browser and version: Safari 15.2
- Operating System: macOS 12.1
- Steps to reproduce this:

In this example I would expect as you move the mouse around the canvas the light source updates, however the WebGL canvas is not updating.
https://editor.p5js.org/jackcruden/sketches/RJJ2MrkIr

**Comment by aferriss** [comment]
When you use a createGraphics object, many things aren't handled for you anymore. One of those things is blending and transformations. If you add img.push() and img.pop() before and after your drawing code, I think your sketch may look correct again. 

```
let img

function setup() {
    createCanvas(500, 500)
    img = createGraphics(500, 500, WEBGL)
}

function draw() {
    background(230)

    //move your mouse to change light direction
    let dirX = (mouseX / width - 0.5) * 2
    let dirY = (mouseY / height - 0.5) * 2
    img.push();
    img.background(255);
    img.directionalLight(250, 250, 250, -dirX, -dirY, -1);
    img.noStroke();
    img.sphere(40);
    img.pop();

    image(img, 0, 0, 500, 500)
}
```

**Comment by aferriss** [comment]
Actually, when testing this, I noticed that there is something else going on. It seems that depth is not being cleared when using createGraphics buffers, leading to weird artifacts. You can get around it by manually clearing the depth, but we should fix this. Going to open a separate issue to describe it in more detail.

Feel free to reopen this issue if you still have questions!

**Comment by jackcruden** [comment]
Awesome, thank you for taking the time to check it out.
