### ISSUE TITLE
Depth is not being cleared on webGL graphics objects.

### ISSUE THREAD

**Issue by aferriss** [processing/p5.js#5514]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

It seems that when using a graphics object in WEBGL mode, the depth buffer is never cleared at the end of each frame. This means that depth just keeps accumulating, preventing geometry from being able to render properly.

You can work around this by manually clearing depth yourself at the beginning of each frame, but I think we should look into doing this by default for the user. I'm not sure if there would be any unintended consequences here. If we don't want to do it by default, then I think we at least need to give the user an easy method to clear the depth buffer, or incorporate depth clearing into the`clear()` function.

```
    // setup()
    let buf = createGraphics(400, 400, WEBGL);
    let gl = buf._renderer.GL;
    
    // draw()
    gl.clearDepth(1);
    gl.clear(gl.DEPTH_BUFFER_BIT); 
```

- p5.js version: 1.4
- Web browser and version: Chrome
- Operating System:OSX
- Steps to reproduce this:
1. Create a graphics buffer in webGL mode `g = createGraphics(400, 400, WEBGL);`
2. Draw some 3d geometry to the screen
3. Add a call to background before you draw the geometry
4. Observe the z-fighting / weird artifacts.

[Small example sketch here](https://editor.p5js.org/aferriss/sketches/cWAWWupMH)

**Comment by aferriss** [comment]
Actually, I think this is happening by design, but since it keeps popping up and even I keep forgetting about it, I wonder if we should do something to make it more obvious that this is the default behavior. 

I think that the `reset()` function will clear the depth buffer, but we should make this more clear in the documentation.

**Comment by stalgiag** [comment]
I often forget about this too but yes, `reset()` is the intended way to make a graphic object behave like the main canvas. The documentation on this is pretty sparse though, one needs to know what they are looking for to arrive at the relevant info and the `reset()` documentation does not mention depth.

**Comment by davepagurek** [comment]
Bumping this issue because someone else was just asking me about something similar!

Would it be possible to make `background()` and `clear()` also call `reset()` automatically, or at least clear the depth buffer? Are there use cases you all can think of that this would break?

**Comment by harold** [comment]
Yeah, this one is gnarly - glad I found this issue.

Here's another sketch that behaves in an unexpected (to me!) way: https://editor.p5js.org/harold/sketches/bVoJZCk0U

**Comment by stalgiag** [comment]
> Bumping this issue because someone else was just asking me about something similar!
> 
> Would it be possible to make `background()` and `clear()` also call `reset()` automatically, or at least clear the depth buffer? Are there use cases you all can think of that this would break?

Hi sorry for the delay! Was really busy for a bit and turned off notifications. I think that it is a good idea to avoid having `background()` and `clear()` call `reset()` automatically because it is relatively common to expect transformations to accumulate in graphics objects (or at least I see this a lot in 2D mode).

Exclusively clearing the depth buffer is a more open question imo. I have a vague recollection of an argument being made that the depth buffer should only be cleared when the transformation is reset but I can't track down where that was. I personally feel that it would be good to reset the depth buffer with `background()` & `clear()` as the effect is a little too jarring and confusing to debug for those who expect graphics objects to behave similarly to the main canvas.

**Comment by davepagurek** [comment]
I can see maybe not wanting it to be reset if your call to `background()` leaves the previous content slightly visible. I think 2D mode does this if you clear the background with a semitransparent color, but WebGL mode doesn't, so with the current WebGL implementation we don't have to worry about that case.

Anyway I also think it would save new WebGL users some debugging! But just to make sure, I can also try finding that discussion you mentioned, and also I can ask around and see if anyone has any ideas for why we might not want to clear the depth buffer.

**Comment by davepagurek** [comment]
I haven't heard back from *too* many people, but it seems like some always call `background()` or `clear()` along with `reset()`, and the two people so far who mentioned they don't both were using fullscreen shaders on the graphic, so it wouldn't be affected either way. Super small sample size here, but so far it looks like clearing the depth buffer wouldn't interrupt any of their workflows.

**Comment by harold** [comment]
(:

fwiw, I guess I was expecting `.background`, when called with a solid color, to also clear the depth buffer in my offscreen webgl Graphics. Though I see now that `.clear` behaves more like what I was imagining. (note: my expectations and imagination are only so useful overall... :smile: )

I also agree that this reference page could mention that `.reset` clears the depth buffer: https://p5js.org/reference/#/p5.Graphics/reset
 - It seems that in many situations people doing offscreen webgl Graphics things `.reset` would help a lot, so additional encouragement to use `.reset` in various examples or docs could be good.

Just to reiterate, I am not blocked, I'm super pleased, and p5.js is rad and a huge time-saver (!) keep up the awesome work.

**Comment by davepagurek** [comment]
I can make a PR to make `background()` clear the depth buffer if we're comfortable trying it, then!

**Comment by harold** [comment]
I guess you'll see if that causes more or less strife overall. (: I hope I'm not leading you astray.
