### ISSUE TITLE
How do I download my sketch as a video or a gif through the p5js web editor 

### ISSUE THREAD

**Issue by Hima87** [processing/p5.js#5522]
<!--
Hi there!

i wrote a code and I want to download the file as a gif or a video ,i know how to download this as a SVG file but it comes as a still image 
this is the code ,i am very new to  p5js  let alone coding ,would appreciate any help or directions ,

thanks 
here is my code 

index html 

<!DOCTYPE html>
<html lang="en">
  <head>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.4.0/p5.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.4.0/addons/p5.sound.min.js"></script>
    <link rel="stylesheet" type="text/css" href="style.css">
    <meta charset="utf-8" />

  </head>
  <body>
    <script src="sketch.js"></script>
  </body>
</html>

and my code 

let yoda;
let x, y, x1, y1;
let colour;
let i;
function preload() {
  yoda = loadImage("rsz_2untitled_design_4.png");
}
function setup() {
  createCanvas(400, 400);
  x = width / 2;
  y = height / 2;
  background(0);
}

function draw() {
  
  for (i = 0; i<10;i++) {
    //image(yoda,0,0);
  x1 = x + random(-10, 10);
  y1 = y + random(-10, 10);
  colour = yoda.get(x,y);
  stroke(colour);
  strokeWeight(2);
  line(x, y, x1, y1);
  x = x1;
  y = y1;

  if (x < 0 || x > width || y < 0 || y > height) {
    x = random(0, width);
    y = random(0, height);
  }
  
  }
}

**Comment by Hima87** [comment]
> _No description provided._
Hi there!


i wrote a code and I want to download the file as a gif or a video ,i know how to download this as a SVG file but it comes as a still image 
this is the code ,i am very new to  p5js  let alone coding ,would appreciate any help or directions ,

thanks 
here is my code 


index html 

<!DOCTYPE html>
<html lang="en">
  <head>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.4.0/p5.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.4.0/addons/p5.sound.min.js"></script>
    <link rel="stylesheet" type="text/css" href="style.css">
    <meta charset="utf-8" />

  </head>
  <body>
    <script src="sketch.js"></script>
  </body>
</html>

and my code 

let yoda;
let x, y, x1, y1;
let colour;
let i;
function preload() {
  yoda = loadImage("rsz_2untitled_design_4.png");
}
function setup() {
  createCanvas(400, 400);
  x = width / 2;
  y = height / 2;
  background(0);
}

function draw() {
  
  for (i = 0; i<10;i++) {
    //image(yoda,0,0);
  x1 = x + random(-10, 10);
  y1 = y + random(-10, 10);
  colour = yoda.get(x,y);
  stroke(colour);
  strokeWeight(2);
  line(x, y, x1, y1);
  x = x1;
  y = y1;

  if (x < 0 || x > width || y < 0 || y > height) {
    x = random(0, width);
    y = random(0, height);
  }
  
  }
}

**Comment by brianpeiris** [comment]
Take a look at the saveFrames function, or ccapture.js that is linked there in the docs: https://p5js.org/reference/#/p5/saveFrames

You could also use an external program to capture your screen, like OBS or ShareX

**Comment by montoyamoraga** [comment]
hi everyone! thanks :)
for code questions please let's use the forum
https://discourse.processing.org/
see you there!
