### ISSUE TITLE
totalHeight is not defined when setting horizontal and vertical alignment

### ISSUE THREAD

**Issue by Sarang-R-119** [processing/p5.js#5526]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [x] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version: v1.4.0
- Web browser and version: Google Chrome (96.0.4664.110)
- Operating System: Windows 10 Version 21H1
- Steps to reproduce this:

I was trying to center my text both horizontally and vertically. Although the horizontal alignment works on its own, the following error is displayed when I try to CENTER the text vertically as well.

Code snippet:
```
fill(0, 255, 0);
textAlign(CENTER, CENTER);
text('hello world', 300, 100, 700, 200);
```
Console output:
```
p5.min.js:3 Uncaught ReferenceError: totalHeight is not defined
    at d.default.Renderer2D.l.default.Renderer.text (p5.min.js:3)
    at d.default.Renderer2D.text (p5.min.js:3)
    at _.f.default.text (p5.min.js:3)
    at Game.drawStartScreen (Game.js:61)
    at draw (sketch.js:82)
    at _.o.default.redraw (p5.min.js:3)
    at _draw (p5.min.js:3)
```

**Comment by limzykenneth** [comment]
This has been fixed by #5366 but not released yet.

**Comment by Sarang-R-119** [comment]
Thanks, @limzykenneth for answering and leading me to the issue with the solution. However, I am using p5.min.js and I am unable to figure out how to solve the issue of the undefined variable totalHeight. Since the solution is not released yet, is there a short fix I can do to avoid this error?

**Comment by limzykenneth** [comment]
Depending on how you are laying out your text on the canvas, you can maybe simulate that effect by ofsetting the y position manually.

**Comment by Sarang-R-119** [comment]
Oh, I see, well I have done that by taking the midpoint between the top and bottom (min and max) y values of the text box with some offset. Thanks anyway!

**Comment by dhowe** [comment]
> This has been fixed by #5366 but not released yet.

do we have a timeline for release?

**Comment by limzykenneth** [comment]
pinging @outofambit @Qianqianye

**Comment by outofambit** [comment]
new release coming in the next week! see #5568 for more :D

**Comment by nathanielstern77** [comment]
Issue seems to still occur in Safari (works in Firefox and Chrome, but gives error in Safari). Any way to define totalHeight myself? TY!

**Comment by mjmeijer** [comment]
Not yet solved!
