### ISSUE TITLE
loadImage

### ISSUE THREAD

**Issue by vsquared** [processing/p5.js#5529]
https://github.com/processing/p5.js/blob/cb3f59740bcb71ba5e2bee820bb1f784004d85ef/src/image/loading_displaying.js#L333

let img;
function preload() {
  img = loadImage('xxxxxx.jpg');
}
function setup() {
  // Top-left corner of the img is at (0, 0)
  // Width and height are the img's original width and height
	**createCanvas(img.width, img.height);  //Added this line**
  image(img, 0, 0);
}

Please add one line of code to make this a runnable example.  Otherwise beginners are perplexed why it doesn't work.

**Comment by stalgiag** [comment]
Hi thanks for the issue. By default p5 makes a canvas that is 100x100 when `createCanvas()` is absent. This is outlined in the [createCanvas reference.](https://p5js.org/reference/#/p5/createCanvas). This means that the `loadImage()` [example](https://p5js.org/reference/#/p5/loadImage) works currently.

Closing this for organizational purposes.

**Comment by vsquared** [comment]
Thanks for looking into it.  Maybe add a comment telling the user to add a
createCanvas() if they want to see a decent sized image.  A user typically
expects to see a robust sized image, not a postage stamp in the middle of
the screen.
