### ISSUE TITLE
3d

### ISSUE THREAD

**Issue by artofmus** [processing/p5.js#553]
Hello! One may ask? At what stage is now working on implementation webgl in p5? Thank you for your attention))

**Comment by lmccart** [comment]
hi @artofmus structurally, we're nearly at the point where you will be able to switch between renderers and use webgl. the implementation of the webgl drawing functions still needs to be done. you can see the progress so far here: https://github.com/processing/p5.js/tree/renderers. we are hoping this may be a google summer of code project.
