### ISSUE TITLE
add backlog of people to all-contributors

### ISSUE THREAD

**Issue by montoyamoraga** [processing/p5.js#5530]
i'm going through some issues and pull requests in the last ~4 months and adding people as contributors on this thread

**Comment by montoyamoraga** [comment]
@all-contributors please add @akshatnema for code in https://github.com/processing/p5.js-website/pull/1107

**Comment by montoyamoraga** [comment]
@all-contributors please add @IamEzio for bug in https://github.com/processing/p5.js-website/issues/1101

**Comment by montoyamoraga** [comment]
@all-contributors please add @Himanshu664 for bug in https://github.com/processing/p5.js-website/pull/1106

**Comment by montoyamoraga** [comment]
@all-contributors please add @chosamuel for bug in https://github.com/processing/p5.js/issues/5530

**Comment by montoyamoraga** [comment]
@all-contributors add @TOrfevres for bug

**Comment by montoyamoraga** [comment]
@all-contributors add @reejuBhattacharya for code in #5465

**Comment by montoyamoraga** [comment]
@all-contributors add @JaPatGitHub for docs in #5501

**Comment by montoyamoraga** [comment]
@all-contributors please add @Zearin for doc in #5500

**Comment by montoyamoraga** [comment]
@all-contributors please add @pifragile for bug in #5462

**Comment by montoyamoraga** [comment]
@all-contributors please add @KevinWorkman for doc in #5472

**Comment by montoyamoraga** [comment]
@all-contributors please add @JetStarBlues for code in #5283

**Comment by montoyamoraga** [comment]
@all-contributors please add @j-stodd for bug in #5478

**Comment by montoyamoraga** [comment]
@all-contributors please add @soegaard for doc in #5468

**Comment by montoyamoraga** [comment]
@all-contributors please add @reejuBhattacharya for code in #5480

**Comment by montoyamoraga** [comment]
@all-contributors please add @oleboleskole3 for bug in #5497

**Comment by montoyamoraga** [comment]
@all-contributors please add @awelles for bug in #5497

**Comment by montoyamoraga** [comment]
@all-contributors please add @andreiantonescu for bug in #5403

**Comment by montoyamoraga** [comment]
@all-contributors please add @awelles for bug in #5403

**Comment by montoyamoraga** [comment]
@all-contributors please add @dipamsen for bug in #5284

**Comment by montoyamoraga** [comment]
@all-contributors please add @soegaard for bug in [#1108](https://github.com/processing/p5.js-website/pull/1108)

**Comment by montoyamoraga** [comment]
@all-contributors please add @stigmollerhansen for bug in #5422

**Comment by montoyamoraga** [comment]
@all-contributors please add @willmartian for ideas in #5479

**Comment by montoyamoraga** [comment]
i'm done until mid January 2022, yay, this issue is closed now

**Comment by outofambit** [comment]
thank you so much @montoyamoraga!! 💖

**Comment by Qianqianye** [comment]
Thanks @montoyamoraga!!

**Comment by montoyamoraga** [comment]
@all-contributors please add @Divyansh013 for translation in https://github.com/processing/p5.js-website/pull/1122

**Comment by montoyamoraga** [comment]
@all-contributors please add @cas-c4ta for bug in https://github.com/processing/p5.js-website/issues/1128

**Comment by montoyamoraga** [comment]
@all-contributors please add @danieljamesross for bug in https://github.com/processing/p5.js-website/issues/1129

**Comment by soegaard** [comment]
@montoyamoraga  Consider creating a new pull request for future additions.
Reusing this PR means earlier contributors keep getting mails.
