### ISSUE TITLE
exitFullscreen() missing Microsoft-specific code

### ISSUE THREAD

**Issue by SteveTiffany** [processing/p5.js#555]
I noticed I could only get out of full screen in Internet Explorer 11 via the 'Esc' key.  When I opened up p5.js v0.4.2 and added

         else if (document.msExitFullscreen) {
     document.msExitFullscreen(); }

near the end of function exitFullscreen(), my fullscreen test started working the same in IE 11 as it does in Chrome, Opera, Safari, and the OS X version of Firefox.  The code for my full screen demo is here:

http://forum.processing.org/two/discussion/9489/p5-sketch-running-fullscreen#latest

**Comment by lmccart** [comment]
woops, sorry for leaving that one out, thanks for the fix!
