### ISSUE TITLE
add contributor...

### ISSUE THREAD

**Issue by unjust** [processing/p5.js#5561]
@all-contributors please add @unjust for code, bug

**Comment by unjust** [comment]
long overdue, hope this works 🤞  . also looking for new issues to fix.

**Comment by unjust** [comment]
@all-contributors please add @unjust for code in #3344

**Comment by unjust** [comment]
@all-contributors please add @unjust for bug in #3344

**Comment by montoyamoraga** [comment]
some conflicts, closing and trying again, one sec

**Comment by montoyamoraga** [comment]
@all-contributors please add @unjust for bug

**Comment by montoyamoraga** [comment]
closed by #5611, thanks @unjust! :)
