### ISSUE TITLE
Console Window Useability Enhancements.

### ISSUE THREAD

**Issue by RichardDL99** [processing/p5.js#5563]
I've just started using Processing 4.0b2 (On W10) and I want to tell you a few things about the console window (cw).

Vertical: Wouldn't it be nice to be able to put the cw vertically up the (right) side of the main window?  When you are working on the code you don't want vital screen height taken by the console window, so close it.  Yes, but if you could put it beside the code then you'd have a good view of both.  Screens have become wider over the years, this would make better use of the screen area.  Frequently I have diagnostic output and I want to look at it at the same time as the code.  I usually copy the output to Notepad++.  This would often avoid having to do that.  The portrait shape for the console window is better suited to a program that is frequently outputting short (40-60 chars) of text.

Auto Open:  The cw could auto open when you run the sketch.

F8: (I'm probably the only one to find this).  F8 starts a mode where you can use the arrow keys to alter the height of the cw.  Exit from that is the tab key (not return, or escape).  I can't find any documentation on it.  It's useless, make F8 toggle the cw open/closed.  That would be much faster than using the mouse.

Mouse Open/Close:  There's a new feature to open and close the cw with the mouse.  Good, but if you want to do it frequently, you'll get RSI moving the mouse to the open and close icons.  Much better to have it in one place so you can simply click to toggle. I do want to open and close it frequently, trying to see why my code didn't output what I expected.

Size Fault: If you drag the cw bigger, then click it closed, then click it open, it goes back to the original size (not the dragged bigger size).

I really like Processing and I hope you can use the above ideas.

**Comment by aferriss** [comment]
Hi, I think you meant to put this in the desktop processing repo. This repo is for p5.js, the javascript library. I believe this is the one you're looking for: https://github.com/processing/processing4

Feel free to re-open if I'm mistaken!
