### ISSUE TITLE
Unnecessary word in docs

### ISSUE THREAD

**Issue by danieljamesross** [processing/p5.js#5564]
https://p5js.org/reference/#/p5/curveVertex

`Description`, paragraph 2, 1st sentence there is an extra `a`.

> The first and last points in a series of curveVertex() lines will be used to guide the beginning and end of `a` the curve.

**Comment by khanjasir90** [comment]
@danieljamesross can i take this up

**Comment by limzykenneth** [comment]
@khanjasir90 This is already being worked on in #5566. Thanks.
