### ISSUE TITLE
resetMatrix can't work on webgl

### ISSUE THREAD

**Issue by yama-yeah** [processing/p5.js#5565]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version: 1.4.0
- Web browser and version: chrome 97.0.4692.71
- Operating System: ubuntu 21.04
- Steps to reproduce this:

All objects will not be able to be drawn
```typescript
import p5 from "p5"
const sketch = (p: p5) => {
    p.setup = () => {
        p.createCanvas(p.windowWidth, p.windowHeight, p.WEBGL);
    };
    p.draw = () => {
        p.background(100);
        p.resetMatrix();
        p.box(100);
    };
};
let p=new p5(sketch)
```

**Comment by stalgiag** [comment]
In this example, `resetMatrix()` is going to make it feel like you are inside of the box. If you want to move back to the starting position after resetting the matrix you can call `translate(0, 0, -350)`.

**Comment by stalgiag** [comment]
Glad it helped. I am going to close for organizational purposes with the hope that it is clear that resetMatrix resets the matrix to the origin, not to the default location.
