### ISSUE TITLE
getURLParams() not working in fullscreen share mode

### ISSUE THREAD

**Issue by mutterer** [processing/p5.js#5567]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [X] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

### p5.js version

1.4.0

### Web browser and version

Chrome 97.0.4692.71 (Official Build) (x86_64)

### Operating System

MacOSX

### Steps:
1. Consider the example at https://p5js.org/reference/#/p5/getURLParams
2. Paste the code below in a new editor window
2. Create the fullscreen share mode using File, Share, Fullscreen option
3. add ?year=2014&month=May&day=15 to the URL
4. From the description, it is expected not to work from the editor, but supposed to work using the 'share' URLs

### Snippet:

```js
// Example: http://p5js.org?year=2014&month=May&day=15

function setup() {
  let params = getURLParams();
  text(params.day, 10, 20);
  text(params.month, 10, 40);
  text(params.year, 10, 60);
}
```

**Comment by limzykenneth** [comment]
Is this issue specific to the web editor? If so you can move it [here](https://github.com/processing/p5.js-web-editor/issues) as we do not maintain the web editor in this repo. Thanks.
