### ISSUE TITLE
Incorrect parameter description for p5.Geometry

### ISSUE THREAD

**Issue by reejuBhattacharya** [processing/p5.js#5574]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Other (specify if possible)

### Steps to reproduce this

![image](https://user-images.githubusercontent.com/40564575/150590862-0be33b09-f758-4562-b603-ac64799ebe24.png)

detailX and detailY have the same description.

Wouldn't the highlighted word be "vertical"?

**Comment by aferriss** [comment]
Yep, good catch! Should probably be vertical. I would also say that I think this is kind of a confusing description. Maybe something better might be:

detailX — Integer: Number of vertices along the x axis
detailY — Integer: Number of vertices along the y axis

**Comment by reejuBhattacharya** [comment]
Thanks, I'll send a pull request fixing this asap!
