### ISSUE TITLE
Way to pass background object to functions other than `setup` and `draw`

### ISSUE THREAD

**Issue by fanbyprinciple** [processing/p5.js#5583]
### Increasing Access

The method currently stops me from resetting the background color from button press

### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [X] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

### Feature request details

I am sorry if the request is too naive

**Comment by limzykenneth** [comment]
Hi @fanbyprinciple, I'm not sure what you mean here. Can you perhaps provide some sample use case code so I can get a better idea of what you are trying to do? Thanks.

**Comment by fanbyprinciple** [comment]
Hello @limzykenneth, I just wanted clarification over whether I can use objects like `background` in functions other than `draw()` and `setup()`.  I was trying to use them outside here https://editor.p5js.org/fanbyprinciple/sketches/s5c0thgLn but was not able to change background color. (It might be that I am making a very obvious mistake) . Thank you for your time.

**Comment by limzykenneth** [comment]
It is possible to use functions like `background()` in places other than `draw()` or `setup()` however functions like `background()` must be run after p5 has started. The easiest way to know that p5 has started is to check if `setup()` has already run, which can be achieved by using a boolean variable that changes value in setup to keep track of this status.

If you need help with your own code, please direct your questions to the [forum](https://discourse.processing.org). We use GitHub issues mainly for bug reports and feature requests only. Thanks!
