### ISSUE TITLE
loadImage function is not returning value

### ISSUE THREAD

**Issue by aferrero** [processing/p5.js#5585]
### Topic

Hi there!
Is the loadImage() function working? I am trying to load a image  but when draw it has not value and returns an error.

I have tried every way possible and always same result.

**Comment by limzykenneth** [comment]
You may need to run a local server for loading images if you are not already doing this: https://github.com/processing/p5.js/wiki/Local-server. Alternatively you can use the [web editor](https://editor.p5js.org) directly from your browser.

If you need further help with your own code, please direct your questions to the [forum](https://discourse.processing.org) unless there are more specific cases where `loadImage` fails that you find. Thanks!
