### ISSUE TITLE
textAlign() doesn't center multiline text properly

### ISSUE THREAD

**Issue by koljam** [processing/p5.js#5587]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [x] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

### p5.js version

1.4.0

### Web browser and version

Firefox 96.0.3, tested in other browsers - same issue

### Operating System

Windows

### Steps:
1. Go into any browser and look at this [sketch](https://editor.p5js.org/koljam/sketches/dQC2iH91E)
2. Or set up your own using this code: 

### Snippet:

```js

function setup() {
  createCanvas(400, 150);
}

function draw() {
  background(220);
  textSize(50);
  textAlign(CENTER);
  text("AAAAAAAAAAAA",200,50)
  text("AAAAAAAAAAAA",0,100,400,200)
}

```
![image](https://user-images.githubusercontent.com/76401593/152238152-ae0b9c8a-8670-4fa1-8509-5fa9b47f8f02.png)

You would expect the two strings to be displayed in the same place. But as soon as you add a wrapping box to  your `text()`-function, the text is shifted slightly to the left.

Defining another `rectMode()` doesn't change anything.

Thank you in advance!

**Comment by dhowe** [comment]
This should be fixed in the recent 1.4.1 release. Please reopen if not:

<img width="1060" alt="image" src="https://user-images.githubusercontent.com/737638/152678970-b880074a-3ff4-4bb2-965d-b746b3e3ca07.png">
