### ISSUE TITLE
mouseMoved() called before preloading completes

### ISSUE THREAD

**Issue by jbakse** [processing/p5.js#5588]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [X] Core/Environment/Rendering
- [X] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [X] Other (specify if possible)

### p5.js version

v1.4.0

### Web browser and version

chrome 97.0.4692.71 (Official Build) (x86_64)

### Operating System

MacOSX

### Steps to reproduce this

Not sure if this is a bug, but it led to a problem in one of my sketches.

p5 will wait for all loading started in preload() before calling setup() (and draw()).

This is helpful because then you don't need to have a lot of logic checking if things are loaded.

p5 will NOT wait for preloading before calling events like mouseMoved() though.

So its possible to have mouseMoved() or mousePressed() called before preloading or setup is called. You can work around this by adding an early return in your event handlers.

The preload() docs only promise that p5 will wait before calling setup, so this isn't violating documented behavior.

```
// move the mouse around alot and reload the page
// can mouseMoved be called before preload? - no / expected
// can mouseMoved be called before preload is done? - yes / undesired
// can mouseMoved be called before setup? - yes / undesired
// can mouseMoved be called before the first draw? - yes / expected
let img;
function preload() {
  console.log("preload");
  img = loadImage("https://placekitten.com/g/200/300");
}
function setup() {
  console.log("setup", img.width);
  createCanvas(512, 512);
}

function draw() {
  console.log("draw", img.width);
  background("gray");
  noLoop();
}

function mouseMoved() {
  console.log("mouseMoved", img.width);
}

function mousePressed() {
  // happens on mousePressed too, but harder to click fast enough
  console.log("mousePressed", img.width);
}
```

**Comment by limzykenneth** [comment]
As noted this is working as documented, the mouse handlers are bound when the p5 instance is created, while we can change it so that they are created after setup run, it will be a breaking change and also be limiting in some ways. In your case you can have an additional boolean variable that check if the code has got to `setup()` already or not by setting its initial value as `false` then changing it to `true` in `setup()` then checking this variable's value in the mouse events functions.

I'm going to close this for now as we are unlikely to change the behaviour here.

**Comment by jbakse** [comment]
Both limzykenneth and I mentioned a workaround for this. Here it is in code, in case it might help someone.

```javascript
let img;

let setupComplete = false;

function preload() {
  console.log("preload");
  img = loadImage("https://placekitten.com/g/200/300");
}
function setup() {
  console.log("setup", img.width);
  createCanvas(512, 512);
  setupComplete = true;
}

function draw() {
  console.log("draw", img.width);
  background("gray");
  noLoop();
}

function mouseMoved() {
  if (!setupComplete) return;
  console.log("mouseMoved", img.width);
}

function mousePressed() {
  if (!setupComplete) return;
  console.log("mousePressed", img.width);
}
```

**Comment by jbakse** [comment]
Another wrinkle on this that I didn't notice before: mouseMoved() and other events can be called before setup() but it looks like mouseX and mouseY are NOT updated before setup(). I don't think this is documented, and it is likely unintended?

```javascript
let img;
function preload() {
  console.log("preload");
  img = loadImage("https://placekitten.com/g/200/300");
}
function setup() {
  console.log("setup", img.width);
  createCanvas(512, 512);
}

function draw() {
  console.log("draw", img.width);
  background("gray");
  noLoop();
}

function mouseMoved(e) {
  console.log("mouseMoved", img.width, mouseX, mouseY, e.clientX, e.clientY);
 // ^ will be something like "mouseMoved 0 0 0 55 61"
}

function mousePressed() {
  // happens on mousePressed too, but harder to click fast enough
  console.log("mousePressed", img.width);
}
```
