### ISSUE TITLE
char() ?

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js#560]
I'm porting some examples from Processing which take a number and convert it to a String via its ASCII code, i.e.  

```
char c = char(35);
```

The JS way to do this is:

```
var c = String.fromCharCode(35);
```

Much in the way we added `int()` to p5.js, should we also add a generic `char()` function or perhaps something different like `toString()` or `string()` or just expect users to use `String.fromCharCode()`?

**Comment by russomf** [comment]
I think this is a great idea. Following the lead of ```int()```, perhaps something like the following?

```javascript
  p5.prototype.char = function(n) {
    if (typeof n === 'string') {
      return String.fromCharCode( parseInt(n) );
    } else if (typeof n === 'number') {
      return String.fromCharCode( n | 0 );
    } else if (typeof n === 'boolean') {
      return String.fromCharCode( n ? 1 : 0 );
    } else if (n instanceof Array) {
      return n.map(p5.prototype.char);
    }
  };
```

**Comment by lmccart** [comment]
this makes sense to me, do you want to submit a PR?

**Comment by russomf** [comment]
I'm not happy with my proposed solution. I will put some more thought into this and submit a pull request with a better approach, which will include `char()` and some of the other conversion functions.

**Comment by zaerl** [comment]
According the the [processing docs](https://processing.org/reference/charconvert_.html) char() accepts boolean, byte, char, color, double, float, int, or long (JS: boolean, number). The only caveat here is that char() should not accept an array type. If think that it's outside the scope of this function.

**Comment by russomf** [comment]
The docs also say "When an array of values is passed in, then a char array of the same length is returned." So, I think an array is a valid parameter type.

I find it odd that boolean is included in this list. If I pass a boolean to char() in Java Processing, I get the error "The method parseChar(byte) in the type PApplet is not applicable for the arguments (boolean)." So, in spite of the docs, I don't think boolean is a valid parameter type for char().

**Comment by russomf** [comment]
Added pull request with proposed changes (#607).

**Comment by zaerl** [comment]
@russomf didn't see the array paragraph, my bad. Great addition :+1:

**Comment by lmccart** [comment]
closed with https://github.com/processing/p5.js/pull/607

**Comment by Great-Bucket** [comment]
I had this same problem (moving from PROCESSING to P5.js) with obtaining the ASCII code for a character.  A person I was working with showed me how to do it:

PROCESSING 3 (on desktop):  myvar = int (wordvar.charAt(2));   

Change on P5.js to:                   myvar = int (wordvar.charCodeAt(2)); 

That is, change '.charAt' to '.charCodeAt'
