### ISSUE TITLE
rect curvature causing renderer error

### ISSUE THREAD

**Issue by zturtledog** [processing/p5.js#5602]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [X] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

### p5.js version

1.4.0

### Web browser and version

97.0.4692.77 (Official Build) (64-bit)

### Operating System

chrome

### Steps:
1.create an array
2.put an item in the array with any two number tepresenting width and height
3.draw a rectangle with the width and height represented through the array and a curve value of anything
4.remove the curve value an see the problem go away

### Snippet:

```js

function draw() {
  background(220);
  
  let testraa = [
    {
      width: "300",
      height: "150",
    }
  ]
  fill("#000000")
  rect(200,200,testraa[0].width,testraa[0].height,10)
}

```

**Comment by zturtledog** [comment]
the same is happening with a line that uses the same width value

**Comment by reejuBhattacharya** [comment]
`tl`, `tr`, `br` and `bl` (for the corner parameters) take **Number** values as input, but in the given example, **String** values have been provided. On giving the same input as **Number**, it is rendered correctly.

![image](https://user-images.githubusercontent.com/40564575/154236923-6e6c96cb-a336-4dad-ae0f-219bdd089688.png)

Does this solve your problem?

**Comment by zturtledog** [comment]
yes, thank you
