### ISSUE TITLE
how to register a p5.RendererGL method in pre?

### ISSUE THREAD

**Issue by nakednous** [processing/p5.js#5609]
### Topic

no totally sure if here is the right place to ask this (please let me know otherwise), but I'm implementing a utility lib having some `p5.RendererGL` functions of my own, some of them that needed to be called in `pre`:

```js
p5.RendererGL.prototype._cache = function () {
  this._cVMatrix = this.uMVMatrix.copy();
  this._cPMatrix = this.uPMatrix.copy();
  this._cPVMatrix = this._cPMatrix.copy();
  this._cPVMatrix.mult(this._cVMatrix);
  this._cPVInvMatrix = null;
}
```
And then registering the method in `pre` as suggested [here](https://github.com/processing/p5.js/blob/main/contributor_docs/creating_libraries.md#use-registermethod-to-register-functions-with-p5-that-should-be-called-at-various-times):

```js
p5.prototype.registerMethod('pre', p5.RendererGL.prototype._cache);
```

And I get a `TypeError: this.uMVMatrix is undefined`. The method works fine if I don't call it in `pre`.

What am I missing? I guess the same result may be achieved by overridden the `p5.RendererGL.prototype._update` but not sure if it is even possible to do that.

Any help much appreciated.

**Comment by aferriss** [comment]
I've never worked with the registerMethod functions before, but it sounds like maybe the uMVMatrix is out of scope. Can you log p5.RendererGL in pre and inspect what properties are attached to it?

**Comment by nakednous** [comment]
yeah it seems so. I found a way without registering the method in `pre`. Thanks.
