### ISSUE TITLE
Old version of p5 runs faster?

### ISSUE THREAD

**Issue by yangren72** [processing/p5.js#5610]
### Topic

I have been running a image/pixel based code on p5 web editor and I found that the old version 0.7.2  of p5.js runs faster than the current 1.4.0?

[here](https://editor.p5js.org/yangren72/sketches/Npt0tom9x) is a link to my code.

In the code I show the frame rate on the top left corner. When I am running it with version 0.7.2, it runs more than 2 times higher frame rate than when I am running the same code with version 1.4.0.

I also took a recording with my phone and put it here for reference.
https://user-images.githubusercontent.com/97763629/155131506-552420c1-2887-4267-873d-8456b6f0cbed.mp4

I am not very experienced in coding and I just found out this by accident. I don't know why exactly this happens or maybe there is something I misunderstood? What do you think? Why does this happen?

**Comment by yangren72** [comment]
@limzykenneth Thank you for your reply! It was very helpful. I am looking into it and test things out!

**Comment by limzykenneth** [comment]
@yangren72 If you need more help with your own code, do direct your questions to the [forum](https://discourse.processing.org). I'm closing this for now. Thanks.
