### ISSUE TITLE
Formal stance on p5.js + NFTs/blockchain/cryptocurrency

### ISSUE THREAD

**Issue by willmartian** [processing/p5.js#5617]
### Topic

There has been an influx of people interested in using p5 for making NFTs. I think NFTs and similar technologies go against core values of the project: increasing access, freedom of information, and open digital expression.

- The environmental impact of blockchain technologies disproportionately harms the global south.
- The speculative nature of NFTs and cryptocurrencies supports income inequality and favors the already wealthy.
- Even the _intent_ behind NFTs, commodification of computational expression and restricting access, runs squarely against the mission of the Processing Foundation.

While it may not be possible or feasible for the project to prevent p5.js being used in these contexts (without changing the license), I would at the very least like to see a public statement condemning it. I believe this kind of statement fits well with existing messaging to the community, such as the [access statement.](https://github.com/processing/p5.js/blob/main/contributor_docs/access.md)

**Comment by irajgreenberg** [comment]
Hi willmartian. Thanks for your comment and starting this topic. Could there be a statement short of straight condemnation? For example, the clean NFT movement and open generative marketplaces are offering some alt opportunities. I know a number of sites that are now working to help fundraise for  Ukraine. Yes, there is so much wrong and predatory, but perhaps also some rays of hope poking through.

**Comment by camelCaseSensitive** [comment]
We've already decided to not allow any NFT promotion on /r/p5js since the spam posts/ self promo was getting out of control.

**Comment by dhowe** [comment]
> Could there be a statement short of straight condemnation? For example, the clean NFT movement and open generative marketplaces are offering some alt opportunities. I know a number of sites that are now working to help fundraise for Ukraine. Yes, there is so much wrong and predatory, but perhaps also some rays of hope poking through.

Perhaps useful as well to

**Comment by willmartian** [comment]
Hi @dhowe, could you offer some kind of reason as to why this issue was closed?

**Comment by dhowe** [comment]
sorry, my mistake

**Comment by Qianqianye** [comment]
Thanks for raising this issue, @willmartian. Thanks @irajgreenberg and @limzykenneth for sharing your thoughts.

p5.js is created with a focus on making coding accessible and inclusive for artists, designers, educators, beginners, and anyone else! In the past, p5.js has had few official statements on specific issues. It's been more communicating through actions and discussions. I think some of this tendency grew out of the community statement that aims to support people of many different beliefs, cultures, and opinions. When there have been more unified statements (community statement, access statement) they usually came out of contributors conferences, preceded by group discussion. I share this not to suggest that there should or shouldn't be a statement, but just to provide some history that may help in understanding current expectations. And statements can be updated, expectations and processes change, as the project evolves with new leadership :)

Meanwhile, the Processing Foundation is currently trying to navigate bringing in more community conversation around these concerns. We are fully aware of the issues that have been raised, but wanting to approach these conversations with care and intention. We can keep this issue open and circle back to this after some organized community conversations in the near future.

**Comment by AnmolBansalDEV** [comment]
I sincerely disagree with your stance. Although I'm a beginner and new to this community, I think the usage of p5.js for creating NFTs is increasing the accessibility of p5.js to artists and people from different communities. For the first time, the NFTs have opened gates for artists to become financially independent without the need of any art gallery or a middleman. And this is driving young underrepresented artists worldwide to this space and in turn to p5.js. I agree that most of these people are coming for the money to be made but I truly believe only the ones who are devoted to the art and its community will stay in the end which is the case in almost every field. I think we should promote the integration and develop features that make NFT development smooth in p5.js.

**Comment by camelCaseSensitive** [comment]
> NFTs have opened gates for artists to become financially independent without the need of any art gallery or a middleman.
Is this true?  From what I've seen NFTs are valued mainly on hype rather than artistic quality.

**Comment by AnmolBansalDEV** [comment]
yes, it has. Take the example of Daniel, founder of Hashlips, he was a full-time software developer but couldn't pursue his passion for drawing and art.  Now, thanks to NFTs he has left his job and now is all in nfts.

https://youtu.be/R_xeTle2WdE

**Comment by camelCaseSensitive** [comment]
Every MLM has a success story but that doesn't mean it's a reliable way to make money.  It also seems that he created an entire NFT community through his tutorials and youtube channel etc. which is my point, if you just mint your art without a following no one is going to buy it just because they like how it looks.

**Comment by mugungalabz** [comment]
A formal stance against NFTs is going to put the processing foundation on the wrong side of history. Its an incredibly exciting, energetic space and there are many artists and developers doing amazing things with p5.js and using it for NFTs. Also, The 3 original bullet points are incorrect, and make it sound like you don't like NFTs for personal resentment issues, not real reasons. 

- Environmental issues: There are eco friendly blockchains like Tezos that don't have heavy energy consumption and also have a thriving NFT community. Further, Ethereum will be moving to proof of stake soon, all but eliminating the environmental concerns there. Ethereum is the primary NFT chain. 

- Countless underprivileged persons from minority groups have had life changing experiences selling NFTs of their art, from quitting their jobs, putting down payments on houses, paying off college debt, etc, so it wouldn't look great trying to condemn that. 

- The intent behind NFTs is not "commodification of computational expression and restricting access", if anything blockchain technology increases access, and NFT sales increases access to collectors for artists who were making $0 to begin with.
