### ISSUE TITLE
Extra files in p5 download?

### ISSUE THREAD

**Issue by tegacodes** [processing/p5.js#5619]
### Topic

hey folks, I noticed there are couple of extra files in the zip p5 download. One called p5-test.js and one called p5-pre-min.js. Wondering if these have been left in by accident?

**Comment by limzykenneth** [comment]
Yes, those are extra intermediate files generated during the build and probably should have been cleaned up at the end of the build.

**Comment by rinkydevi** [comment]
hey @limzykenneth i would love to work on this

**Comment by limzykenneth** [comment]
@rinkydevi Sure, I'll assign the issue to you.

**Comment by Qianqianye** [comment]
Thanks @tegacodes for pointing it out. I just fixed the zip file in the p5 download for the latest release, so the extra files are no longer in the zip file.

Thanks @limzykenneth for following up with this issue. There have been extra files in the zip file during the last few releases, which we didn’t catch.

@rinkydevi  I think the work left to do here is to change the release process in the future to not include these extra files in the zip. I’d suggest looking at https://github.com/processing/p5.js/blob/main/tasks/release/release-p5.js and https://github.com/processing/p5.js/blob/a8862389633404da72d8d76db3d44d45b1fc5535/Gruntfile.js#L361-L370 to get started.

**Comment by Qianqianye** [comment]
Hi @rinkydevi, thanks for your interests in working on this issue. Just want to check in with you to see if you are still available working on this. Otherwise, we can un-assign you to avoid confusion. Thank you!
