### ISSUE TITLE
Don't blur resized images

### ISSUE THREAD

**Issue by Omay238** [processing/p5.js#5628]
### Increasing Access

It would make it easier to create programs with pixel art.

### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [x] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

### Feature enhancement details

Add an option to the resize funtion - [p5.Image/resize](https://p5js.org/reference/#/p5.Image/resize)
Perhaps resize(width, height, [mode])
Where mode is "smooth" or "pixelate".

**Comment by rinkydevi** [comment]
hey @Omay238  i would like to work on this issue

**Comment by alec-kr** [comment]
Hey @Omay238. Can I work on this issue?

**Comment by Falling10fruit** [comment]
I need this, this is a great idea

**Comment by limzykenneth** [comment]
While something like `img.noSmooth()` can possibly be considered to affect `resize()`, is there a reason why using the global `noSmooth()` and drawing the pixel art at the desired size (`image(img, x, y, width, height)`) not be a feasible solution? 

It is also a more efficient method as opposed to using `resize()` if you need to draw the same pixel art at many different sizes or using a spritesheet as `resize()` will create a temporary HTML canvas whenever it is called while drawing with a different size doesn't.

**Comment by Falling10fruit** [comment]
Oh, I didn't know it existed

**Comment by yogitheboss** [comment]
Is this issue still valid or has been resolved? If it has been sorted then I guess @limzykenneth  you can close it.
