### ISSUE TITLE
Documentation for DOM Library

### ISSUE THREAD

**Issue by HSchmale16** [processing/p5.js#5630]
### Topic

I'm currently trying to embed p5.js into my jekyll blog to show case some things and maybe build some games with it. However, the `createSlider` function puts the slider outside of the `<main>` tag where the canvas is created. Is there a way to modify or patch the dom functions so that embedding is easier?

I've tried using `slider.position(10,10)` but that's the location within the entire page, which I don't want, I want it relative from where I tell p5 to embed itself. Which I've been able to do by using a `<main>` tag.

**Comment by Ryuyxx** [comment]
Since you can't just draw HTML into a canvas, it is necessary to use absolute location. Here is one way to make it easier.
```js

    // get canvas information
    canvasRect = canvas.elt.getBoundingClientRect()
    slider = createSlider(0, 255, 100);

    // Set the position based on canvas coordinates.
    slider.position(canvasRect.x, canvasRect.y);
```

<br />

If you want to move the slider into `<main>`,

```js
select('main').elt.appendChild(slider.elt);
```

**Comment by limzykenneth** [comment]
@HSchmale16 You can nest the slider inside any container in the DOM using the [`.parent()` method](https://p5js.org/reference/#/p5.Element/parent).

if you need further help with your own code, please direct your questions to the [forum](https://discourse.processing.org). We use GitHub issues mainly for bug reports and feature requests only. Thanks!
