### ISSUE TITLE
FES not triggering in certain cases.

### ISSUE THREAD

**Issue by reejuBhattacharya** [processing/p5.js#5632]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [X] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

### p5.js version

v1.4.1

### Web browser and version

Chrome 99.0.4844.51 (Official Build) (64-bit) (cohort: Stable) 

### Operating System

Windows 10 Version 20H2

### Steps to reproduce this

I have been digging around the FES files for quite some time and noticed that the FES does not work for certain errors and we only see the default error messages even though they are included in the _browser_errors.js_ file (I assume therefore they are handled). 
browser_errors.js file: [https://github.com/processing/p5.js/blob/main/src/core/friendly_errors/browser_errors.js](url)

### Screenshots:
![image](https://user-images.githubusercontent.com/40564575/157820229-c10bf47e-ebdd-4b9c-8ae7-98c7714e0237.png)

![image](https://user-images.githubusercontent.com/40564575/157820407-5ef401a9-1268-41d3-9c0f-7c245ca4a3aa.png)

![image](https://user-images.githubusercontent.com/40564575/157820514-4b132475-e998-4409-bbcc-5a846ef1afc5.png)

![image](https://user-images.githubusercontent.com/40564575/157820820-e03cb9c7-9688-4abd-b465-5f85ff294a9e.png)

All these errors seem to have been included in the aforementioned file but does not generate the FES.

**Comment by Qianqianye** [comment]
Thanks @[reejuBhattacharya](https://github.com/reejuBhattacharya) for raising this issue.
Hi @almchung @Aloneduckling, do you have any thoughts on this? Thanks!

**Comment by almchung** [comment]
Hi @reejuBhattacharya, thank you for reporting this issue!
Would you provide us version of p5.js you are using for running these tests? 

I confirm that I get no FES messages using v1.4.0 (`https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.4.1/p5.js`) but get corresponding FES messages switching to v1.4.1 (`https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.4.1/p5.js`).

**Comment by Aloneduckling** [comment]
@reejuBhattacharya thanks for opening the issue. 
The FES messages appear when we switch to V1.4.1 as mentioned by @almchung. 
Currently, the p5.js web editor is using V1.4.0 which is the reason why there are no FES messages.

You can update the src in the script tag in the `index.html` file in the web editor and it will work fine.
![image](https://user-images.githubusercontent.com/54030684/159397889-5bdc4f76-d597-4a67-b965-21a6e613a43b.png)

**Comment by reejuBhattacharya** [comment]
Yep, that does clear my doubts. Thanks for the help, everyone! 

As a side note, is there any particular reason the p5.js web editor is still using v1.4.0 ?

**Comment by Qianqianye** [comment]
Thanks @almchung and @Aloneduckling!
@catarak, can you share some thoughts on the editor related question @reejuBhattacharya asked? Thanks!

**Comment by Qianqianye** [comment]
Since this is more of a issue for [p5.js Web Editor](https://github.com/processing/p5.js-web-editor) now, I'm closing this for organizational purposes. Thank you!
