### ISSUE TITLE
Adopt vue-p5?

### ISSUE THREAD

**Issue by Kinrany** [processing/p5.js#5633]
Hi! A few years ago I created a p5.js wrapper for Vue frontend framework: https://github.com/Kinrany/vue-p5

Unfortunately at this point I barely ever use p5, Vue or even JS, which frankly makes me a poor maintainer of the library. (Not that there's a lot to maintain: I answer about a couple of questions a year.)

So I wonder if making the library a part of the Processing org would make sense.

**Comment by Ryuyxx** [comment]
Since Github issues are not often checked, I suggest you post this on [here.](https://discourse.processing.org/)

**Comment by Qianqianye** [comment]
Hi @Kinrany! I think this feature is beyond the scope of the p5.js api (we try to keep as minimal as possible) but it could be a great starting point for an add-on library. see the docs here for how to create an add-on: https://github.com/processing/p5.js/blob/main/contributor_docs/creating_libraries.md
