### ISSUE TITLE
Should issues be automatically labelled for the appropriate area of p5.js

### ISSUE THREAD

**Issue by stampyzfanz** [processing/p5.js#5636]
### Topic
I am proposing a GitHub Action to be employed to automatically label new issues based on which checkboxes are checked in the "relevant part of p5.js" section. This section is included in all issue forms except for the discussion form. 

![image](https://user-images.githubusercontent.com/34364128/158528167-4a4eda3e-7521-440f-8bf7-f693240a3761.png)
![image](https://user-images.githubusercontent.com/34364128/158528865-7f27eff4-b5a3-4c9c-b4fc-ce844eaea9d7.png)

The only reasons against this that I can think of are 
1. The difficulty of setting the system up
2. People may choose an irrelevant part of p5.js

The benefits are that 
1. It's easier to search for issues 
2. People don't have to manually assign labels.

**Comment by stampyzfanz** [comment]
I created a functional prototype that implements this idea in [one of my repositories](https://github.com/stampyzfanz/TestingGithubActions/issues). It uses GitHub's [RegEx Issue Labeler](https://github.com/marketplace/actions/regex-issue-labeler) which is probably overkill but it works. It might not be elegant using both the bot and the GitHub Action, but they should be able to co-exist.

**Comment by Qianqianye** [comment]
Thank you @stampyzfanz @stalgiag and @limzykenneth for the conversation. I went ahead and cleaned up the labels a bit based on @limzykenneth's suggestions. Below are some other label updates:
- All the `Area` labels are now coordinated with the [src folder](https://github.com/processing/p5.js/tree/main/src) structure.
- Updated some old label's names to `Build Process`, `Unit Testing`,` Localization Tools`, `Friendly Errors` based on the steward focus areas mentioned in the #5719 issue. 
- `area:examples`, `area:tutorial`, and some random labels are removed.
- All the previous issued labeled with`area:build` and `area:devops` are under `Build Process`.

Some questions: 
- Currently, the definition of the word `Area` in the labels and the #5719 issue are overlapped but exact same. Wondering if we need to replace the word `Area` in the #5719 to something like `Section` (maybe I am just overthinking)?
- Should we keep the browser (like `Chrome`) and OS (like `Android`) related labels?
- When we update the GitHub action, shall we require to add at least 2 labels for one issue, one is `Area` related, another is action related, like `bug` or `feature request`? What do you think?

**Comment by limzykenneth** [comment]
> Currently, the definition of the word Area in the labels and the https://github.com/processing/p5.js/issues/5719 issue are overlapped but not exactly same. Wondering if we need to replace the word Area in the https://github.com/processing/p5.js/issues/5719 to something like Section (maybe I am just overthinking)?

I think this is fine to leave it as `area`.

> Should we keep the browser (like Chrome) and OS (like Android) related labels?

This info should be available as the issue template is filled in so I don't think this is as necessary, and I don't think a scenario in which one would specifically filter by browser or OS comes up often.

> When we update the GitHub action, shall we require to add at least 2 labels for one issue, one is Area related, another is action related, like bug or feature request? What do you think?

👍

**Comment by Qianqianye** [comment]
Thanks @limzykenneth! 
Hey @stampyzfanz, do you have any thoughts about the recent label updates? Will you be interested working on this issue? Thank you!

**Comment by stampyzfanz** [comment]
All the labels look good to me except maybe _gif_ and _dependencies_ which could be capitalized for consistency. Additionally friendly-errors is the only multi word issue using kebab case. I am interesting in working on this issue and have a working prototype with all the correct labels [here](https://github.com/stampyzfanz/TestingGithubActions/issues) which should be able to be added here. It uses GitHub's [RegEx Issue Labeler](https://github.com/marketplace/actions/regex-issue-labeler) like my previous prototype which is probably overkill but it works.

**Comment by Qianqianye** [comment]
> All the labels look good to me except maybe _gif_ and _dependencies_ which could be capitalized for consistency. Additionally _friendly-errors_ is the only multi word issue using kebab case. I

Thanks @stampyzfanz for catching that! I have capitalized the `Dependencies` and `GIF` label for consistency, and cleaned up the format of `Friendly Error` label. We are keeping GIF label for now because a GSoC contributor @jesi-rgb is working on a GIF related project, and we might remove the label later if it's confusing.

> I am interesting in working on this issue and have a working prototype with all the correct labels [here](https://github.com/stampyzfanz/TestingGithubActions/issues) which should be able to be added here. It uses GitHub's [RegEx Issue Labeler](https://github.com/marketplace/actions/regex-issue-labeler) like my previous prototype which is probably overkill but it works. I

In the issue template, would it be possible to add `Build Process`, `Unit Testing`, `Localization Tools`, `Friendly Errors` as sub-area after the Area Labels? So it will coordinate with the stewards [focus areas](https://github.com/processing/p5.js#stewards). Thank you!

**Comment by jesi-rgb** [comment]
This looks super cool! I love when we can automate these kind of things!!

Also, @Qianqianye if you are worried about the GIF functionality, actually it is not used either in my [PR](https://github.com/processing/p5.js/pull/5709), nor in the [issue it references](https://github.com/processing/p5.js/issues/5118), so you might as well go ahead and remove it already! All good! Thanks for being so thoughtful!

**Comment by Qianqianye** [comment]
> Also, @Qianqianye if you are worried about the GIF functionality, actually it is not used either in my [PR](https://github.com/processing/p5.js/pull/5709), nor in the [issue it references](https://github.com/processing/p5.js/issues/5118), so you might as well go ahead and remove it already! All good! Thanks for being so thoughtful!

Thank you @jesi-rgb. I removed the `GIF` label, and all the issues labeled `GIF` are now under `Area:Image`.

**Comment by stampyzfanz** [comment]
> In the issue template, would it be possible to add `Build Process`, `Unit Testing`, `Localization Tools`, `Friendly Errors` as sub-area after the existing sub-areas? So it will coordinate with the stewards [focus areas](https://github.com/processing/p5.js#stewards). Thank you!

I am just doing this right now and have noticed that _User Documentation_ isn't on the issue template either. Should I add it too?

**Comment by Qianqianye** [comment]
> The labels are much more standardised, thank you. I also assume that there is a good reason why some labels are prefixed with Area and others aren't.

The labels prefixed with `Area` are  coordinated with the [src folder](https://github.com/processing/p5.js/tree/main/src) structure. The labels without `Area` prefix are the rest ones in the stewards [focus areas](https://github.com/processing/p5.js#stewards). Hope this makes sense?

> I am just doing this right now and have noticed that User Documentation isn't on the issue template either. Should I add it too?

When you say `User Documentation`, do you mean `Contributor Docs`? If so, we can leave it for now because it's too specific.

**Comment by Qianqianye** [comment]
Thanks @stampyzfanz for working on automating the labelling process.
I just updated the [contributor_docs/issue_labels.md](https://github.com/processing/p5.js/blob/main/contributor_docs/issue_labels.md) with the new label system, please feel free to make edits. Thank you!
