### ISSUE TITLE
Welcome bot necessarily asks new users to follow the issue template on an issue form

### ISSUE THREAD

**Issue by stampyzfanz** [processing/p5.js#5637]
### Topic

The Welcome bot says "Welcome! 👋 Thanks for opening your first issue here! And to ensure the community is able to respond to your issue, be sure to follow the issue template if you haven't already" to new users creating an issue.

I don't think this is necessary because p5.js is now using issue forms, which force the issue to include the relevant sections. If it is still necessary for users to be reminded to address all the inputs, I think the message should be changed to "...be sure to fill out the issue form template inputs accurately if you haven't already". 

The relevant configuration code:
https://github.com/processing/p5.js/blob/a8862389633404da72d8d76db3d44d45b1fc5535/.github/config.yml#L7

**Comment by limzykenneth** [comment]
Didn't think of updating this message when we were moving to the new issue template. Yes, this message should probably be updated accordingly.

**Comment by montoyamoraga** [comment]
@all-contributors please add @stampyzfanz for docs
