### ISSUE TITLE
canvas offset

### ISSUE THREAD

**Issue by artofmus** [processing/p5.js#564]
can I set offset of canvas right in sketch, not in html ?

**Comment by debone** [comment]
Yes, you can use `p5.position()`:

```javascript
function setup(){
    var canvas = createCanvas(42,42); //Created a 42x42px canvas
    canvas.position(100,100); // 100px margin top and left
}
```

**Comment by lmccart** [comment]
thanks @debone! indeed, this is correct. for future, questions like these are great for the forum, so that the answers can be preserved more easily for others to learn from.
forum.processing.org/two/

**Comment by artofmus** [comment]
Ok, thanks)
