### ISSUE TITLE
httpGet does not show FES message

### ISSUE THREAD

**Issue by reejuBhattacharya** [processing/p5.js#5646]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [X] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

### p5.js version

v1.4.1

### Operating System

Windows 10 Version 20H2

### Steps to reproduce this

`httpGet()`does not show Friendly Error Message.

Below, I have made a httpGet call with a wrong URL. 

![image](https://user-images.githubusercontent.com/40564575/160285137-76b54657-b199-4820-ba0a-eb88f93ff365.png)

As we see, only the system generated error is thrown.

**Comment by xinranyu-yuki** [comment]
Hi, can I please take this issue?

**Comment by Sejal1411** [comment]
would like to work on this issue..pls assign.

**Comment by limzykenneth** [comment]
Being addressed in #7178 for 2.0
