### ISSUE TITLE
Some p5.js functions do not make a call to _validateParameters (FES)

### ISSUE THREAD

**Issue by reejuBhattacharya** [processing/p5.js#5649]
### Topic

I was not sure whether this was a bug or intentional behaviour, so I filed it under discussion...

I have noticed that a large number of functions do not make a call to `_validateParameters()`, while others do. This leads to different types of error messages being produced when incorrect parameters are passed to each of them. For example:

 `fill()` and `stroke()` both do **not** make a call to `_validateParameters()`. The error message is as follows:

![image](https://user-images.githubusercontent.com/40564575/160579975-f3481a0b-5f33-4bf7-958b-7db2fa32fa5d.png)

![image](https://user-images.githubusercontent.com/40564575/160580564-fd80b710-ba8e-43bd-be26-2262678ff949.png)

However, the functions which **do** have a call to `_validateParameters()` have a different ( _friendlier_) error message, as illustrated by the example of `constrain()`:

![image](https://user-images.githubusercontent.com/40564575/160580891-b850df5f-9a45-40f0-a09c-8c3cd9b2a6a8.png)

Is there a specific reason for this, or is this a bug?

**Comment by limzykenneth** [comment]
The `validateParameters` function is not able to handle all kinds of function signature that we use, so there will be some functions that just doesn't work with `validateParameters`. If you find some that could work but isn't using `validateParameters` you can list them here.

**Comment by stampyzfanz** [comment]
Quite a lot can be found using a quick search for "console.warn" without all files in the source code. In particular, it occurs regularly in light.js https://github.com/processing/p5.js/blob/4640a269c35d90d2b0e1bf4d712149455e5f4766/src/webgl/light.js#L598-L600
Another way to find lots are to search for "new Error" and "throw new". It occurs in the source code in many ways such as when a browser hasn't implemented an API such as https://github.com/processing/p5.js/blob/4640a269c35d90d2b0e1bf4d712149455e5f4766/src/dom/dom.js#L1344

I agree that `validParameters` shouldn't be expected to be used for every function, however, the use of hard coded English error messages isn't very inclusive and it should be delegated to the FES to internationalise with the `_report` function.

**Comment by dhowe** [comment]
along the same lines, do we have any standard mechanism for warnings ?

**Comment by aditya-shrivastavv** [comment]
If I am not wrong, we have to add a new line which uses `_friendlyError` to validate all the parametes to all the functions whose parameters are not validated, but needed to be.
is this issue still open ? if yes i would like to work upon it please assign this to me.

**Comment by limzykenneth** [comment]
Ideally validating parameters go through `validateParameters` only, otherwise it can make things difficult to maintain further down the line, so I wouldn't suggest adding `_friendlyError` to all functions that's not covered by `validateParameters` already.

If there are places where `console.error` or `console.warn` are still being used, we can switch these to use `_friendlyError` as that's what it's for anyway.

**Comment by limzykenneth** [comment]
Being addressed in #7178 for 2.0
