### ISSUE TITLE
save() with first argument type string defaults to image no matter what

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js#565]
If the first argument to `save()` is a String it always assumes you are trying to save the canvas as an image, in the p5 source:

```
    if (args.length === 0) {
      p5.prototype.saveCanvas(cnv);
      return;
    } else if (args[0] instanceof p5.Graphics) {
      p5.prototype.saveCanvas(args[0].elt, args[1], args[2]);
      return;
    } else if (typeof args[0] === 'string') {
      p5.prototype.saveCanvas(cnv, args[0]);
    } else {
```

I ran into this doing the following:

```
  var test = {x: 'test'};
  var json = JSON.stringify(test,null,2);
  save(json,'test.json');
```

This, however, works as intended:

```
  var test = {x: 'test'};
  // var json = JSON.stringify(test,null,2);
  save(test,'test.json');
```

But took me a while to figure out why the first had failed.  Should `save()` be checking the second arguments file extension?  Happy to fix this but not 100% clear of desired behavior.

This relates to @therewasaguy's work with pull request #313

**Comment by therewasaguy** [comment]
Hey @shiffman, good catch! The idea was that you can save the canvas with a filename, without having to also include a reference to the canvas.

So ``save("myCanvas")``  works the same as ``save(cnv, 'myCanvas.png')``

But it should only do this when there is one argument. So [this line](https://github.com/processing/p5.js/blob/master/src/output/files.js#L181)  should be changed to

```
 if (args.length === 1 && typeof args[0] === 'string') {
      p5.prototype.saveCanvas(cnv, args[0]);
    } 
```

This should also be added to the [docs](http://p5js.org/reference/#/p5/save).
