### ISSUE TITLE
Should add error message when Canvas.parent couldn't be found

### ISSUE THREAD

**Issue by Falling10fruit** [processing/p5.js#5650]
### Increasing Access

This will help beginners, especially if they're copying a project as a template.

### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [X] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

### Feature enhancement details

When the user attempts to attach the canvas to a non-existing element, a Friendly Error should appear instead, replacing the "appendbody" error

**Comment by limzykenneth** [comment]
Hi @Falling10fruit, I don't quite understand what you are referring to here in this issue, can you perhaps expand on it a bit more? Some sample code would be great as well. Thanks.

**Comment by Falling10fruit** [comment]
That didn't happen to me

**Comment by limzykenneth** [comment]
Are you using p5.js (instead of p5.min.js) as FES is not included in the minified version.

**Comment by Falling10fruit** [comment]
*Doesn't understand* Um, yes I'm using p5.js through the script tag in VSCode

**Comment by justlucdewit** [comment]
@Falling10fruit what @limzykenneth meant was if you were using the minified version of p5.js, because FES is not included in the minified version

check if your version is the minified one by looking if the js file that you include to include p5js ends with .min.js or just with .js
if you still cant figure that out, then please send us the src="" attribute of the script tag that includes p5

**Comment by Falling10fruit** [comment]
Oh, I'm using p5.js, not p5.min.js

**Comment by limzykenneth** [comment]
@Falling10fruit Can you share a simplified version of your project with us (HTML and JS)?

**Comment by Falling10fruit** [comment]
`<!DOCTYPE html>
<html lang="">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>p5.js example</title>
        <style>
            body {
                padding: 0;
                margin: 0;
            }
        </style>
        <script src="../p5.js"></script>
        
        <script src="sketch.js"></script>
    </head>
    <body>
        <main>
        </main>
    </body>
</html>`

`function setup() {
    // put setup code here
    var Canvas = createCanvas(0,0);
    Canvas.parent("Non-existent_Tag");
}

function draw() {
    // put drawing code here
}`

**Comment by Falling10fruit** [comment]
Do I have to make a respitory?

**Comment by Falling10fruit** [comment]
To simplify my mistake up there, all I did was add `var Canvas = createCanvas(0,0,);` & `Canvas.parent("Non-existent_Tag");` in the empty example.

**Comment by limzykenneth** [comment]
Using the following sketch and p5.js 1.4.1 I'm still not able to replicate the issue

```js
function setup(){
  var Canvas = createCanvas(0, 0);
  Canvas.parent("Non-existent_Tag");
}
```

FES message in console:
```
🌸 p5.js says: [main.js, line 3] An error with message "p is null" occurred inside the p5js library when parent was called. If not stated otherwise, it might be an issue with the arguments passed to parent. (http://p5js.org/reference/#/p5/parent)
```

Can you try replacing the p5.js src URL value to `https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.4.1/p5.js`?

**Comment by Falling10fruit** [comment]
![image](https://user-images.githubusercontent.com/85048907/162566307-7c242967-7511-4859-beb5-0ce48f3ef47b.png)

No difference

**Comment by limzykenneth** [comment]
Have you tried replacing the script tag URL as mentioned?

**Comment by Falling10fruit** [comment]
Yes I did that
![image](https://user-images.githubusercontent.com/85048907/162606273-d737384c-52dd-4dd1-a311-fdfa305f12a9.png)

**Comment by limzykenneth** [comment]
But the error in the debug console doesn't show that the error comes from the CDN version but from a local file instead.

**Comment by Falling10fruit** [comment]
So how do I do that?

**Comment by limzykenneth** [comment]
I'm not entirely sure how you are currently running the html file as I'm expecting console messages from the browser console but you are showing the debug console in VSCode (I don't use it much) so I can't advise much from the provided info. You may want to move your question to the [forum](https://discourse.processing.org) as it pertains more to your own code and I can't replicate the mentioned issue. Thanks.

**Comment by Falling10fruit** [comment]
The debug console in VS Code is pretty much the same with the browser console. But instead it also gathers data from other tabs in the same window. Note that it creates a new window so it doesn't interfere with other tabs that I'm currently using.

**Comment by Falling10fruit** [comment]
Also, I don't have an account for the forums.

**Comment by Ayush23Dash** [comment]
Hi @Falling10fruit, @limzykenneth :
I tried replicating this issue.
So the problem is something as follows:
FES messages are being displayed in some browsers like Firefox(as expected)
<img width="1787" alt="Screenshot 2023-06-18 at 11 28 48 AM" src="https://github.com/processing/p5.js/assets/40827680/89730abd-a70f-4499-8c9c-483514ed32ff">
and are not being displayed in some versions of Chrome.
I also had a discussion with @nbriz @almchung regarding a similar issue that I was facing.

**Comment by limzykenneth** [comment]
@Ayush23Dash I'm still not sure what the issue is, can you share the replication steps?

**Comment by Falling10fruit** [comment]
Seeing how there is so much difficulty in replicating this bug, I think my
laptop is broken.
