### ISSUE TITLE
issue with trim function

### ISSUE THREAD

**Issue by yadroRus** [processing/p5.js#5658]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [X] Other (specify if possible)

### p5.js version

v1.4.1

### Steps:
1. write in console 'Весна '.trim()
2. result will be 'есна '
3. should be 'Весна'

### Snippet:

```js

// Paste your code here :)

```

**Comment by limzykenneth** [comment]
@yadroRus I cannot replicate this, can you fill in the rest of the issue template, specifically the browser and OS versions? Also `.trim()` is not a p5.js function but rather native javascript string method.

**Comment by limzykenneth** [comment]
Using the following code I'm still not able to replicate this problem

```js
const loadScript = (url) => {
  if (document.querySelector(`script[src^="${url}"]`)) return Promise.resolve();
  return new Promise((resolve, reject) => {
    const script = document.createElement('script');
    script.src = url;
    script.defer = true;
    script.onload = resolve;
    script.onerror = reject;
    document.head.appendChild(script);
  });
}

console.log('Весна '.trim());
loadScript("https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.4.1/p5.min.js").then(() => {
  console.log('Весна '.trim());
  return loadScript("https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.4.1/addons/p5.sound.min.js");
});
```

**Comment by Qianqianye** [comment]
Thanks @yadroRus. I'm closing this for organizational purposes. Please reopen if you can provide more info replicates this issue. Thanks!
