### ISSUE TITLE
Browsers assign pixels inconsistently

### ISSUE THREAD

**Issue by jthomerson** [processing/p5.js#5665]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [X] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [X] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

### p5.js version

1.4.0

### Web browser and version

Multiple

### Operating System

MacOSX

### Steps to reproduce this

I'll start by saying that I don't know that this is actually an issue in p5js - I think it may be an issue in browser implementations differing. The difference seems very small and unimportant, but in a piece of generative art I was building, it was dependent on using the drawing functions, then loading the pixels, and iteratively "walking" away from the colored pixels to color all adjacent pixels until the entire canvas was filled with a pattern. The problem is that since the initial pixels don't end up in the same place (and there's not even the same number of them), that the canvas ends up drastically different in different browsers, which is undesirable for reproducible generative art. I pasted a picture demonstrating the output of my actual art at the bottom of this report, and a drastically-simplified example that shows the core problem in the code snippet below.

### Steps:
1. Draw a shape on the canvas
2. Load the pixels
3. Read the coordinates and colors of every pixel
4. Notice that each browser colored a different set of pixels, and with different alpha values

### Snippet:

See my example with annotation here: <https://editor.p5js.org/jthomerson/sketches/LYM2I1z56>

Or, it's pasted here:
```js
const CANVAS_SIZE = 400;

function setup() {
  createCanvas(CANVAS_SIZE, CANVAS_SIZE);
  pixelDensity(1);
  noFill();
  noLoop();
  noSmooth();
}

function draw() {
  stroke('red')
  circle(width / 2, height / 2, width * .75);
  loadPixels();
  
  let coloredPixels = 0;

  // FIRST PROBLEM: p5 is making pixels partially-transparent to smooth
  // out the drawing. I tried to work around that by setting the alpha of
  // every colored pixel to 100%, which gives the drawing a rougher,
  // aliased look
  for (let x = 0; x < width; x++) {
    for (let y = 0; y < height; y++) {
      const i = getPixelIndex(x, y);

      if (pixelHasColor(i)) {
        const r = pixels[i],
              g = pixels[i + 1],
              b = pixels[i + 2],
              a = pixels[i + 3];

        coloredPixels++;
        console.info(`${x}, ${y} = ${r}, ${g}, ${b}, ${a}`);
        
        // The last lines of that output on these two browsers (at least
        // my versions of them) is as follows.
        
        // NOTE PROBLEM TWO: not only are the alpha values different, the
        // ACTUAL PIXEL COORDINATES are different as well. The browsers don't
        // color the same pixels when drawing the line, or else don't read
        // those values back the same (I'm not sure which).

        // FIREFOX:
        // 350, 208 = 255, 0, 0, 59
        // 350, 209 = 255, 0, 0, 40
        // 350, 210 = 255, 0, 0, 20
        // 350, 211 = 255, 0, 0, 1

        // BUT ON CHROME:
        // 350, 209 = 255, 0, 0, 56 
        // 350, 210 = 255, 0, 0, 40 
        // 350, 211 = 255, 0, 0, 23 
        // 350, 212 = 255, 0, 0, 4 
        pixels[i + 3] = 255;
      }
    }
  }
  updatePixels();
  
  // note: don't call loadPixel again - there's no need
  // see https://github.com/processing/p5.js/issues/5064

  // Even the number of colored pixels differs, which is what makes the biggest
  // problem for my generative art.
  // FIREFOX: 1687
  // CHROME:  1864
  console.info(`Number of colored pixels: ${coloredPixels}`);
}

function getPixelIndex(x, y) {
  return (x + y * width) * 4;
}

function pixelHasColor(i) {
  return pixels[i] !== 0 || pixels[i + 1] !== 0 || pixels[i + 2] !== 0;
}
```
![problem-example](https://user-images.githubusercontent.com/171934/163740426-aa1a2ae1-d1bd-4dca-b24d-c8bdb7a5d042.jpg)

**Comment by limzykenneth** [comment]
As you have mentioned, this is probably down to individual browser's implementation. While Firefox and Safari are likely still using Cairo as a backing graphics engine, the detailed implementation of things such as anti-aliasing probably is different, and Chrome uses Skia as the graphics engine so we can expect different behaviour as well.

The main thing that caused your problem is that you are trying to get around the default anti-aliasing which the spec does not require to be uniform across implementation so each browser just does what it felt are the best. I would suggest if you really need consistency at that level you may want to define the drawing on a pixel level which can add a lot of complexity to your code. Unfortunately there is no way to turn off anti-aliasing for the line drawings in a canvas (that I know of).

As this is not a problem with p5.js itself and we are not likely to be able to address it, I'm going to close this issue for now.

**Comment by jthomerson** [comment]
@limzykenneth thanks! I figured it was something like that, but wanted to report it so an expert could check. I appreciate your time. Thanks again.
