### ISSUE TITLE
What's the difference between let and var?

### ISSUE THREAD

**Issue by Falling10fruit** [processing/p5.js#5673]
### Increasing Access

I use var instead of let and it didn't seem to change anything, removing let would clear some confusion between people who use var and let.

### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [X] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

### Feature enhancement details

If there is really no difference, I suggest removing let. But if there is, please tell me, I would really like to know

**Comment by lindapaiste** [comment]
If you're a beginner you can use `var` and it won't break anything.  It does make your code more prone to bugs because you might be unintentionally using the same variable in multiple places.  Advanced coders who understand when to use `let` vs `const` will typically never use `var` at all.

There are subtle differences between how the two behave.  [MDN has a good explanation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let).

> [`let`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let) allows you to declare variables that are limited to the scope of a [block](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/block) statement, or expression on which it is used, unlike the [`var`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/var) keyword, which declares a variable globally, or locally to an entire function regardless of block scope.

```
var a = 1;
var b = 2;

if (a === 1) {
  var a = 11; // the scope is global
  let b = 22; // the scope is inside the if-block

  console.log(a);  // 11
  console.log(b);  // 22
}

console.log(a); // 11
console.log(b); // 2
```

**Comment by limzykenneth** [comment]
Hi, if you need help with your own code, please direct your questions to the [forum](https://discourse.processing.org). We use GitHub issues mainly for bug reports and feature requests only. Thanks!

**Comment by Falling10fruit** [comment]
Thanks for clarifying
