### ISSUE TITLE
Can't render sketch if included p5.sound.min.js in Index.html header

### ISSUE THREAD

**Issue by PandaBalls** [processing/p5.js#5681]
### Most appropriate sub-area of p5.js?

- [X] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [X] Other (specify if possible)

### p5.js version

1.4.0

### Web browser and version

edge

### Operating System

windows/android

### Steps to reproduce this

If I included the p5.sound.min.js in index.html. then Mobile phone can not run sketch.. I will see nothing even just a red background..
It works ok after deleting
`    <script src="libraries/p5.sound.min.js"></script>`

**Comment by hamzhfreajat** [comment]
The `<script src="libraries/p5.sound.min.js"></script>` should be added at the bottom of the page I think before </body> tag and make sure that you have all the requirement of this file

**Comment by Qianqianye** [comment]
Hi! I'm closing this for organizational purposes. Please reopen if you can provide a longer code snippet that illustrates the issue. Thanks!
