### ISSUE TITLE
frameCount does not stop incrementing when noLoop() is called

### ISSUE THREAD

**Issue by lonesword** [processing/p5.js#569]
I'm not sure if this is a bug or an intended functionality. Right now, frameCount keeps on getting incremented even if noLoop() is called. A quick glance at core.js showed that draw() loop is controlled from this._draw() while the frameCount is independently incremented in this._runFrames. Wouldn't it make more sense if frameCount is incremented only if the draw loop is executed?

**Comment by shiffman** [comment]
I think you are in a previous version, as this was fixed with #406.  Can you check that you are using most recent p5.js and if the problem persists?

**Comment by lonesword** [comment]
Yes I was using an outdated version. My bad.
