### ISSUE TITLE
movedX and movedY undefined on touchscreen devices

### ISSUE THREAD

**Issue by jasonfyw** [processing/p5.js#5692]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [X] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

### p5.js version

v1.3.1

### Web browser and version

Safari 15.1

### Operating System

iOS 15.4

### Steps:
1. Go to the P5 editor on a touchscreen device
2. Enter the snippet below
3. Run and drag a finger across the canvas. Notice that both `movedX` and `movedY` are undefined

### Snippet:

```js

function setup() {createCanvas(400, 400);}

function draw() {background(220);}

function mouseDragged() {console.log(movedX, movedY)}

```

**Comment by limzykenneth** [comment]
`movedX` and `movedY` in p5.js is directly taking from the mouse event [`movementX` and `movementY`](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/movementX) values. It seems those values are not prevent in a touch interface. You may need to find other ways around for what you are trying to do here.

**Comment by jasonfyw** [comment]
> `movedX` and `movedY` in p5.js is directly taking from the mouse event [`movementX` and `movementY`](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/movementX) values. It seems those values are not present in a touch interface. You may need to find other ways around for what you are trying to do here.

Understood. I'll see what other options are available.
