### ISSUE TITLE
P5 website reference page fails to load

### ISSUE THREAD

**Issue by bxuserx** [processing/p5.js#5695]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [X] Other (specify if possible)

### p5.js version

na

### Web browser and version

Chrome on macOS	102.0.5005.115

### Operating System

mac

### Issue:
https://p5js.org/reference/ fails to load all search bar and all content. Fails on Chrome, but works on firefix

### Steps:
1. Go to web https://p5js.org/reference/

<img width="1164" alt="Screen Shot 2022-06-19 at 8 22 09 PM" src="https://user-images.githubusercontent.com/86570251/174506068-b2c0fce9-f117-477a-9997-36cf1a22cc89.png">

**Comment by limzykenneth** [comment]
@bxuserx I'm not able to replicate this problem. Do you have extensions installed on Chrome? If so can you try disabling them? If that doesn't solve it can you try a different machine with Chrome?

**Comment by Qianqianye** [comment]
Hi @bxuserx. Could  you please open this issue at the [p5.js Website repo](https://github.com/processing/p5.js-website)? I am closing this issue for organization purpose. Thank you!
