### ISSUE TITLE
Create a Basic Feedback Effect for the Examples Page

### ISSUE THREAD

**Issue by aceslowman** [processing/p5.js#5717]
### Increasing Access

Texture feedback is a simple and easy to use effect that can sometimes be difficult for newcomers to figure out in a straightforward way. I am proposing a simple example for the website that shows how to create texture feedback without shaders, which will be easy to learn from and extend.

I will be taking on this task myself as part of my work on WebGL examples and documentation for GSOC. Let me know if there is any issue with this!

### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [X] Other (specify if possible)

### Feature enhancement details

The example will involve creating two buffers, one with simple geometry and another that will hold the previous frame. The result will be a minimal example of feedback applied to the image.

**Comment by Qianqianye** [comment]
Sounds great @aceslowman! Just wondering if this issue will be a better fit in the [p5.js-website ](https://github.com/processing/p5.js-website)repo? You might also want to check out the [p5.js Website / Translation Stewards Open Call 🎉 #1220](https://github.com/processing/p5.js-website/issues/1220), in which we have a focus area about the example page.

**Comment by Qianqianye** [comment]
Yes, let's close this one for now. Thanks @aceslowman!
