### ISSUE TITLE
p5 logs a message every time noSmooth() is called on a graphics object

### ISSUE THREAD

**Issue by IkeB108** [processing/p5.js#5723]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [X] DOM
- [ ] Events
- [ ] Friendly error system
- [X] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

### p5.js version

1.4.1

### Web browser and version

Chrome 103.0.5060.114

### Operating System

Windows 10

### Steps:
1. Create a p5 graphics object
2. Call noSmooth() on the graphics object
3. A message is logged to the console (even though `noSmooth()` works properly):
`You are trying to use setAttributes on a p5.Graphics object that does not use a WEBGL renderer.`
There is no way to stop the logs as far as I know (even with disableFriendlyErrors). This is problematic if a sketch calls noSmooth() frequently.

### Snippet:

```js

function setup(){
  myGraphics = createGraphics(100,100)
  myGraphics.noSmooth() //message is logged once
}

function draw(){
  myGraphics.noSmooth(); //message is logged once per frame
}


```

**Comment by Qianqianye** [comment]
Thanks @IkeB108 for opening the issue and @limzykenneth for fixing it.
