### ISSUE TITLE
Improve Keyboard Events

### ISSUE THREAD

**Issue by error-four-o-four** [processing/p5.js#5725]
### Increasing Access

This feature would allow p5 users to easily read keyCodes that are held down at the same time.

### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [X] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

### Feature request details

Hey there, 

At the moment p5 only provides the properties `key` and `keyCode` to read the input of a user but they return only the last pressed key. On the other hand p5 reads and stores the user input from a keyboard in the property `_downkeys` as an object literal.

The following function would return the object as an array:
```js
p5.prototype.getDownKeyCodes = function() {
	return Object.entries(this._downKeys).reduce((downKeys, [k, v]) => (v) ? [...downKeys, k] : downKeys, []);
}
```

It could be used like this:
```js
const inputs = {
	'87': 'move up',
	'65': 'move left',
	'83': 'move down',
	'68': 'move right'
};

window.draw = () => {
	clear();

	const downKeyCodes = getDownKeyCodes();

	for (const downKeyCode of downKeyCodes) {
		if (Object.keys(inputs).includes(downKeyCode)) {
			console.log(inputs[downKeyCode]);
		}
	}
};
```

Another idea would be to create a global p5 property like `downKeys`.

But on the other hand it looks like `event.which` and `event.key` will be deprecated in the future and maybe the whole p5 keyboard event functions should be rewritten 🤷‍♂️

**Comment by error-four-o-four** [comment]
Additionally it's necessary to change the `_onblur` method to make this work.

```js
p5.prototype._onblur = function(e) {
  // old
  // this._downKeys = {};

  // new
  for (const k in this._downKeys) {
    this._downKeys[k] = false;
  }
};
```

**Comment by davepagurek** [comment]
Would the existing `keyIsDown` method handle this use casse? https://p5js.org/reference/#/p5/keyIsDown It provides a public method that accesses the `_downKeys` object internally:
https://github.com/processing/p5.js/blob/v1.4.1/src/events/keyboard.js#L381

> Additionally it's necessary to change the _onblur method to make this work.

The `keyIsDown` method might also need this if your example needs it. Is this to handle the case where you press down a key, then unfocus the window, and then release the key?

**Comment by error-four-o-four** [comment]
mmh.

i'm tempted to close this issue because the `keyIsDown` method is way more beginner friendly than my suggestion (and honestly i wasn't aware of the method as i opened the issue).

I'm wondering if there really is a benefit.

**Comment by davepagurek** [comment]
I think the existing method probably covers the use case decently enough. Did you notice a big that your updated blur handler fixes? If the same issue applies to keyIsDown then we could try to fix that.

**Comment by error-four-o-four** [comment]
haven't investigated yet. but will do it later.

**Comment by davepagurek** [comment]
> I think it's because i updated the downKeys array in a registered method before draw ('pre').

Ahh ok, makes sense! Thanks for looking into it!
