### ISSUE TITLE
Specifying loadJSON() callback in preload() makes console.log() useless

### ISSUE THREAD

**Issue by Spaxe** [processing/p5.js#574]
Minimal test case A (expected to succeed):

    function preload () {

    }

    function setup () {
      console.log('Test');
    }

    function draw () {

    } 

Console:
`Test`

Minimal test case B (expected to fail):

    function preload () {
      var x = loadJSON('bad_file');
    }

    function setup () {
      console.log('Test');
    }

    function draw () {

    }

Console:
`GET http://localhost:8000/bad_file 404 (File not found)`

Minimal test case C (expected to fail, but nothing happens):

    function preload () {
      var x = loadJSON('');
    }

    function setup () {
      console.log('Test');
    }

    function draw () {

    }

Thoughts?

**Comment by Spaxe** [comment]
Another instance where this can be rather annoying:

Say I have `data.json` which exists.

    function preload () {
      var x = loadJSON('data.json');
    }

    function setup () {
      console.log('Test');
    }

    function draw () {

    }

Console:
`Test`

But the following fails:

    function preload () {
      var x = loadJSON('data.json', function (data) { 
        // do nothing
      });
    }

    function setup () {
      console.log('Test');
    }

    function draw () {

    }

**Comment by kevinb7** [comment]
Is ```setup``` even being called?

**Comment by lmccart** [comment]
either preload or a callback should be used with the loadJSON call, but not both. these are two distinct options.
empty preload will also cause p5.js to hang.

**Comment by Spaxe** [comment]
@lmccart Noted. I see it's written in http://p5js.org/reference/#/p5/loadJSON, but it's not completely obvious. Also, it seems a bit weird to have distinct options when one is a [global] function and the other being one or more callbacks of certain functions.

I suggest some clarification in documentation for now. May send in a patch later.

**Comment by Spaxe** [comment]
@kevinb7 P5.js looks for a `setup()` and calls it by default.

**Comment by lmccart** [comment]
thanks yeah that's be great, the preload is a little hacky. clearer documentation would help I think.

**Comment by Spaxe** [comment]
@lmccart Later down the road I would recommend decoupling the inter-exclusion, such that:

 1. `preload()` is called before `setup()`
 2. callbacks for `load*()` functions are called after the async operation completes. 

This means if you want to make sure `loadJSON()` is complete before the draw, you could just include it in `preload()` and no more fiddle.

**Comment by Spaxe** [comment]
I'll make sure my head is clear before sending it. :]
