### ISSUE TITLE
Unable to read properties of undefined (reading "x")

### ISSUE THREAD

**Issue by xDarkAngelXD** [processing/p5.js#5743]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Localization Tools
- [X] Friendly Errors
- [X] Other (specify if possible)

### p5.js version

1.4.2

### Web browser and version

Brave 1.41.1

### Operating System

Windows

### Steps:
1. Created Sprite
2. created function to move sprite
3.error properties of undefined (reading "x")

### Snippet:

I created a global variable already

```js
	function setup() {
	createCanvas(400, 400);

	playerPaddle = createSprite(200,50,50,10);
	playerPaddle.shapeColor= "black";

	let compPaddle = createSprite(200,350,50,10);
	compPaddle.shapeColor = "black";

	let striker = createSprite(200,200,10,10);
	striker.shapeColor = "white";

	let playerGoal = createSprite(200,18,100,20);
	playerGoal.shapeColor = "yellow"

	let compGoal = createSprite(200,382,100,20);
	compGoal.shapeColor = "yellow";
}


```js
function playerMovements(){
	if(keyDown("a")){
		playerPaddle.x = playerPaddle.x-10;
	}
}


```

**Comment by limzykenneth** [comment]
Hi @xDarkAngelXD, it seems your problem is related to p5.play which is not maintained officially in this repo. You may want to file this issue [here](https://github.com/molleindustria/p5.play/) instead. Thanks.
