### ISSUE TITLE
Remove superfluous _setProperty method from p5.Element

### ISSUE THREAD

**Issue by SanzSeraph** [processing/p5.js#5749]
### Topic

I've been looking through the p5.js source code to get a better understanding of it and to get some ideas for a p5 library I'm working on.

I noticed that there are several places where a p5.Element _setProperty method is being called. All this method does is use string key syntax to set the value of an arbitrary property.

Is there some reason this method exists that I'm not seeing? Can it be removed to cut down on the indirection?

**Comment by limzykenneth** [comment]
`_setProperty` is used so properly handle both global mode and instance mode, ie. in instance mode we can just set the property value on the instance object but in global mode we need to set the property value on the global `window` object as well. The `_setProperty` method takes care of this check and conditional value setting to simplify the rest of the codebase.
