### ISSUE TITLE
loadTable('csv') unable to get() content from table object

### ISSUE THREAD

**Issue by efares** [processing/p5.js#575]
I am trying to loadTable('csv') and then grabbing the content from the table object. I can see the table object being created with content stored in it but I'm unable to get specific content. What am I doing wrong?
 
Sample code:
var day;

function preload() {
day = loadTable("data/20150101.csv", "csv");
}
function setup() {
console.log(day);
console.log(day.get(1,0));
}

Output:
amdclean.p5Table.c.Table {columns: Array[1], rows: Array[3735], addRow: function, removeRow: function, getRow: function…}
Uncaught TypeError: undefined is not a function

Link: http://eliasfares.com/projects/comp5209/

**Comment by lzyla** [comment]
I have the same problem with grabbing the content:

var tab;
function preload () {
  
  tab = loadTable('tabela.csv');
}

function setup() {
  createCanvas(400,600);
  rowCount = tab.getRowCount();
  print(rowCount); // here is all good
  var w = tab.getRows();
  print(w);
}

Output:
8
2: Uncaught RangeError: Maximum call stack size exceeded

**Comment by efares** [comment]
Hey I got it figured out.
Try doing this:
...[your previous code]
//add
for (var row = 0; row < *array length*; row++) {
var w = tab.getRow(row).get(2) //get() for the specific column value you want
print(w)
}
which would output each row's value

**Comment by lzyla** [comment]
thanks! :)

**Comment by lmccart** [comment]
is this one resolved or is there still an issue with this function?

**Comment by efares** [comment]
resolved.

**Comment by dano1234** [comment]
I am having a similar problem in LoadXML.  Can't print out the returning data and also can't iterate through it in P5 IDE  I can do both of these in Sublime.

function setup() {
   loadXML("http://www.ps3nyc.org/news/feed/?cat=32",getNews);
}


function getNews(data){
    //This gets uncaught RangeError: Maximum call stack size exceeded
  console.log(data);


    //the approach of iterating is foiled by Cannot read property 'getElementsByTagName' of undefined
  var rss = data.getElementsByTagName("rss")[0].getElementsByTagName("channel")[0].getElementsByTagName("item");
  if(data === undefined ) print("undeffinnned");
  var len = rss.length;
  print(len);
	for (var row = 0; row < rss.length; row++) {
    var w = rss[row] //get() for the specific column value you want
    print(w)
  }
 
}


function draw() {
  ellipse(50, 50, 80, 80);
}

**Comment by lmccart** [comment]
is this an issue just with the editor? can you log it here, if so: https://github.com/processing/p5.js-editor/issues. apologies if I'm misunderstanding.

**Comment by dano1234** [comment]
Will do.
