### ISSUE TITLE
IndexedDB

### ISSUE THREAD

**Issue by SanzSeraph** [processing/p5.js#5757]
### Topic

Has there been any discussion about providing an API to interact with indexed DB?

**Comment by limzykenneth** [comment]
There hasn't been any discussions about this and I feel indexedDB support is a bit out of scope for the core p5.js library though an add on library, possibly an interface to an existing library for indexedDB would be a good thing to have instead.

**Comment by SanzSeraph** [comment]
That's a good point. Maybe I'll work on that!

**Comment by Qianqianye** [comment]
Thanks @SanzSeraph! Yes I agree with @limzykenneth that indexedDB support is beyond the scope of the p5.js api (we try to keep as minimal as possible) but it could be a great starting point for an add-on library. Please see the [contributor doc](https://github.com/processing/p5.js/blob/main/contributor_docs/creating_libraries.md) of how to create a library. I will close this issue for now for organizational purpose, and please feel free to re-open it when you have updates on this. Thank you!
