### ISSUE TITLE
Add a function to get the target frame rate

### ISSUE THREAD

**Issue by tapioca24** [processing/p5.js#5762]
### Increasing Access

I am developing a library for recording p5.js animations and this proposal is to improve it.
Many already use this library, and improving its usability should increase the number of sketches posted to Twitter, Instagram, etc., and thus more access to p5.js.

### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [X] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### Feature request details

I am developing a library to record p5.js animations.
In a recording library, it makes sense in many use cases to match the recording frame rate to the target frame rate in p5.js.

But it looks like the only way to get the target frame rate is to reference a variable called `_targetFrameRate`. And this is probably a private variable, not intended for user use. Libraries that depend on private variables in p5.js could suddenly stop working if p5.js is updated, which should be avoided if possible.

It would be great if p5.js supported a function to get the target frame rate as a public API, such as `getTargetFrameRate()`.

**Comment by limzykenneth** [comment]
Hi @tapioca24, does the return value of `frameRate()` (without any arguments) not work in your use case?

**Comment by tapioca24** [comment]
Hi @limzykenneth, `frameRate()` does not work in my use case.
`frameRate()` returns an actual measured value, which is different from the target set by the user. This difference is especially noticeable when there is slow processing in the draw function. I need the target frame rate set by the user itself.
