### ISSUE TITLE
Cannot download projects from the browser version

### ISSUE THREAD

**Issue by DQGiac** [processing/p5.js#5766]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [X] Other (specify if possible)

### p5.js version

I have tried all versions from 1.1.9 to 1.4.1. 

### Web browser and version

Google Chrome v 104.0.5112.69

### Operating System

Windows

### Steps:
1. Create any kind of project or just a blank project, save it.
2. Go to File -> Download.
3. Open the zip and you'll see the size of every file is 0.

Am I the only one here experiencing this? I had tried to find what is wrong but found nothing. So now I am currently using vscode :) Thanks.

**Comment by davepagurek** [comment]
Hi! I think downloading a sketch is an issue with the p5 editor website as opposed to the library itself. There's an issue for it open here that you can track: https://github.com/processing/p5.js-web-editor/issues/2038

I'm going to close this issue in favour of that one to keep the issues organized, but let me know if this affects more than what's in that other issue!
