### ISSUE TITLE
Too many active WebGL contexts. Oldest context will be lost.

### ISSUE THREAD

**Issue by LinMu-z** [processing/p5.js#5767]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

1.4.2

### Web browser and version

Chrome  104.0.5112.102

### Operating System

Windows 10

### Steps:
1. Create multiple Graphics
2. Using the Graphics as texture to draw
3. Refresh page
4. WARNING: Too many active WebGL contexts. Oldest context will be lost.
5. 

### Snippet:

```js

// Paste your code here :)
createCanvas(windowWidth, windowHeight,WEBGL);
pg1 = createGraphics(500,500, WEBGL);
pg2 = createGraphics(500,500, WEBGL);
pg3 = createGraphics(500,500, WEBGL);
pg4 = createGraphics(500,500, WEBGL);
pg5 = createGraphics(500,500, WEBGL);
pg6 = createGraphics(500,500, WEBGL);
pg7 = createGraphics(500,500, WEBGL);
pg8 = createGraphics(500,500, WEBGL);
pg9 = createGraphics(500,500, WEBGL);
```

**Comment by limzykenneth** [comment]
This is not really a bug and the message itself also does not come from p5.js. As described in the message itself, this is a fundamental limit of how many WebGL canvases can exist on a web page at a time. Most browser set it at 8.

You can briefly read about this [here](https://webglfundamentals.org/webgl/lessons/webgl-multiple-views.html) and [here](https://threejs.org/manual/?q=mult#en/multiple-scenes). I'm going to close this issue for now.
