### ISSUE TITLE
arc() don't render right with big sizes

### ISSUE THREAD

**Issue by Art2B** [processing/p5.js#577]
Hey, 
just make a little program with p5js, but I found something weird. The arc() function doesn't render right when the size is quite big.

Here is my code which render the arcs: 

```
  var ellipseSize = 200;
  var strokeSize = 60;

  for(var j=0; j<filteredTrees.length; j++){
    strokeWeight(strokeSize);
    var rad = 0;
    for(var i =0; i < filteredTrees[j].trees.length; i++){
      var element = filteredTrees[j].trees[i];
      var radBegin = rad;
      rad += (element.nbr/filteredTrees[j].rangeNbr)*(2*PI);
      stroke(element.color.red, element.color.green, element.color.blue);
      arc(width/2, height/2, ellipseSize, ellipseSize, radBegin, rad);
    }
    ellipseSize += (strokeSize*2);
    strokeSize *= 0.9;
  }
```

And here is one render of it, with circle wich mark the good alignment the arc should have.

![Exemple](https://cloud.githubusercontent.com/assets/3877717/6690392/a6b0ee46-ccc0-11e4-87a0-900cd7ac349e.png)

Is it a bug or something I didn't figure right ?

**Comment by kevinb7** [comment]
I think this is an interesting side-effect of the implementation I did for arc.  It uses bezier curves under the hood.  This is fixable, but we'll have to move away from bezier curves to approximating it with a polyline.

**Comment by hamoid** [comment]
I see the canvas API provides an [arc](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/arc). Was that not good enough for some reason? Maybe slow?

**Comment by lmccart** [comment]
as I remember, the canvas arc function only lets us do circular arcs, while we wanted to support the processing arc method which allows the user to specify different width and height, @kevinb7 is that correct?

**Comment by hamoid** [comment]
I also see that the PIE mode is missing in the native solution.

**Comment by kevinb7** [comment]
@lmccart yes, that's correct.  There was an issue a while ago where arcs with different aspect ratios weren't being rendered in the correct location and the width of the arc wasn't constant.

@hamoid I had a look at the code you linked too and it's rather complicated.  Processing.js' arc implementation is much simpler so I'd probably leverage that code instead.

**Comment by ekeneijeoma** [comment]
I haven't had problems with canvas arc. I thought you implemented it using bezier curves so it'd be easier to implement in 3d/webgl which doesnt have an arc drawing as far as I know.

**Comment by kevinb7** [comment]
I choose the implementation because I thought it would be more performant and because it has improve quality vs. processingjs' implementation at certain radii.  The quality issue is pretty easy to remedy.

I don't think it makes things easier with WebGL because WebGL doesn't have a bezier curve command.  You have to either render it with triangles or use a shader to do the whole thing at once.  The problem with using a shader though is it's tough to get a uniform antialiased edge for all possible sizes and aspect ratios.

**Comment by lmccart** [comment]
could we check if w===h and use the arc function just for these cases? it wouldn't really solve the issue here, but it would fix this particular case. I wonder if that might also be better for performance, in cases where people are just drawing circular arcs?

**Comment by kevinb7** [comment]
That sounds reasonable.

**Comment by workergnome** [comment]
The only issue I could see with that is if the rendered appearance differs between the two drawing methods.  In that case, if you're interpolating the arc, you'd get a visual 'pop' when w===h.

**Comment by lmccart** [comment]
ah good point, hmm
