### ISSUE TITLE
3 unit tests associated with `tint` sometimes fail when running in GH Action

### ISSUE THREAD

**Issue by stalgiag** [processing/p5.js#5772]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [X] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

main

### Web browser and version

N/A

### Operating System

N/A

### Steps to reproduce this

Open a pull request and look at the tests. If there isn't a failure re-run them or look at the time readouts next to the 'displaying images' tests.

I noticed this after I had to restart unit tests on two PRs included #5508 where the failed tests created some confusion.

Every time the GH actions run there is a chance that the unit tests in the 'displaying images' suite in [images/loading.js](https://github.com/processing/p5.js/blob/main/test/unit/image/loading.js#L344) will fail due to timeout (max 2000ms). The inconsistent behavior is likely due to the available resources on the virtual machine used to run the GitHub action. 

These tests were added in #5471 . It is likely that these unit tests are a bit too resource-intensive for reliable testing on a VM. One possible fix would be reducing the size of[ the test image.](https://github.com/processing/p5.js/blob/main/test/unit/assets/cat-with-hole.png)

**Comment by davepagurek** [comment]
Agreed, the test image can be smaller, I didn't consider it being slower on CI when I added those tests. I can clean them up and make them more efficient
