### ISSUE TITLE
Dom.createImg() should allow passing an onload callback.

### ISSUE THREAD

**Issue by brysonian** [processing/p5.js#578]
I suppose it could be 2nd or 3rd arg. If 2nd is string it is alt attr, if it is a function, onload callback.

**Comment by shiffman** [comment]
Agreed!  Just chiming in to cross-reference this with #561 in case that's relevant to the discussion.

**Comment by lmccart** [comment]
@futuremarc this seems related to some of the callback stuff we were looking at during the meetup last month, want to take a look if you have time?

**Comment by futuremarc** [comment]
createImg() actually does take a callback now via PR #745

**Comment by lmccart** [comment]
oops, missed that, great!
