### ISSUE TITLE
Make the p5.js editor a Progressive Web App (PWA) so it can be installed on desktop operating systems

### ISSUE THREAD

**Issue by captainbrosset** [processing/p5.js#5786]
### Increasing Access

PWAs can be installed on supporting operating systems (Android via Chromium-browsers, iOS using the "add to homescreen" feature, desktop OSs using Chromium-browsers). Installing a PWA locally means you get an icon and the website that got installed looks and feels like an app.

On desktop, in particular, being able to install the p5.js editor would increase re-engagement with the app. The icon is right there in the taskbar and start menu, the app launches fast, it can even work offline (using service workers), making it easier for people with low or unstable internet connection.

### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [X] Other (specify if possible)

### Feature request details

Add the necessary PWA building blocks to https://editor.p5js.org/ so it becomes installable.
This means adding a web app manifest to describe what the app is about and how it integrates in the OS, and adding a service worker so it can work offline too.

Once the website is seen by supporting browsers as a PWA, users will be able to install it locally and use it as any other OS-native apps they have installed.

PWAs also come with special super powers like:

* File handling which could be used to save sketches on disk and register the PWA as a native handler for these files.
* Share target which could be used to received shared sketches.
* Protocol handling, which could be used to share sketches with each other.
* And more ...

**Comment by captainbrosset** [comment]
I'm planning to spend a few days in September to hack on this idea.

**Comment by limzykenneth** [comment]
Hi @captainbrosset, this is the repository for the p5.js library while the web editor is maintained in a different repository. You should file this issue in the web editor repo instead. Thanks.

**Comment by captainbrosset** [comment]
Ok, sounds good. Here is the new issue: processing/p5.js-web-editor/issues/2060
