### ISSUE TITLE
Did you just try to use p5.js's cos() function? If so, you may want to move it into your sketch's setup() function

### ISSUE THREAD

**Issue by EliRockenbeckAmericanEdu** [processing/p5.js#5809]
### Topic

I've seen there's been a similar issue in the past with the noise() and random() functions. This error is giving when running on https://editor.p5js.org/

**Comment by Qianqianye** [comment]
Hi @EliRockenbeckAmericanEdu. Can you provide a code snippet or a p5.js web editor link that illustrates the issue? Thanks!

**Comment by EliRockenbeckAmericanEdu** [comment]
Absolutely, Attached below

`function setup() {
  createCanvas(400, 400);
}


function draw() {
  background(120);
}

console.log(cos(90));`

**Comment by limzykenneth** [comment]
@EliRockenbeckAmericanEdu The FES message is working as intended based on the example code you provided, ie. `console.log(cos(90));` is used outside of `setup()` or `draw()` which means `cos()` isn't available yet. The FES is suggesting moving it into `setup()` where it would be available.

Is there some other behaviour here that you are not expecting?

**Comment by Qianqianye** [comment]
Thanks @EliRockenbeckAmericanEdu and @limzykenneth. I will close this issue for now for organizational purpose. Please feel free to reopen it if there's any unexpected behaviour you'd like to share, @EliRockenbeckAmericanEdu. Thanks.
