### ISSUE TITLE
Specify lineWidth / stroke width

### ISSUE THREAD

**Issue by scottdonaldson** [processing/p5.js#582]
It seems like it would be helpful if there were a way to specify a stroke thickness along with the stroke color. I know it can be done by getting and adjusting the context, but it would be more intuitive to have either a built-in function or parameter to do this.

Now:
```javascript
var canvas = createCanvas( w, h );
canvas.drawingContext.lineWidth = 2;
```

Maybe something like:
```javascript
strokeWidth(2);
```

Or:
```javascript
stroke({
  color: 'foo',
  width: 2
});
```

**Comment by spasmsaps** [comment]
see http://p5js.org/reference/#p5/strokeWeight

**Comment by scottdonaldson** [comment]
Gah, sorry — should have read the docs more carefully. Thanks for the response!
