### ISSUE TITLE
Shaders + Textures appear black on mobile devices

### ISSUE THREAD

**Issue by jessssssse** [processing/p5.js#5820]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [X] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [X] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

1.4.2 + 1.4.1 + 1.0.0

### Web browser and version

Chrome: 105.0.5195.147, Safari, duckduckgo, firefox

### Operating System

IOS + Android

### Steps to reproduce this

hello!
### Links:
my example: [https://editor.p5js.org/jbass754468546/sketches/7aG0rrQoy](url)
p5 example: [https://p5js.org/examples/3d-textures.html](url) 

Both links work as intended on desktop browsers. On mobile both textures appear as black or clear depending on the device.
Tested on 3 devices, 4 browsers, and 3 versions. 
The issue only didn't appear on Android - Chrome - v1.4.1 + v1.4.2
![p5.js example](https://user-images.githubusercontent.com/74994218/192547436-77875e0a-33d9-4c25-98ff-741e28a83325.jpg)
![my example](https://user-images.githubusercontent.com/74994218/192547439-ee0b1d0f-592e-4735-aa2f-aa229e0ca3d1.jpg)

Both links use shaders to texture some geometry in different ways. 
My example copies the shader to a image and then textures objects.
The p5 example uses createVideo() to set a texture. 

Both examples cause the same behavior so I include them both. 

### Snippet from web editor:

```js

let myShader;
let drawTex = true; 
let myImg;
let myImgRez = 1024;
let myImgNum = 8;
let theta = 0;

//shader sets screen to one color from a uniform
let stringVert = "attribute vec3 aPosition; attribute vec2 aTexCoord; varying vec2 vTexCoord; void main() {vTexCoord = aTexCoord; vec4 positionVec4 = vec4(aPosition, 1.0); positionVec4.xy = positionVec4.xy * 2.0 - 1.0; gl_Position = positionVec4; }";
let stringFrag ="precision mediump float; uniform vec3 col; void main() { gl_FragColor = vec4(col.r,col.g,col.b, 1.0 ); }";


function setup() {
  canvas = createCanvas(400, 400, WEBGL);
  myImg = createImage(myImgNum*myImgRez , myImgRez);
  myShader = createShader(stringVert, stringFrag);
}

function draw() {
  
  if (drawTex == true) {//only run this once.  wont work if in setup()
    drawTex = false;
    shader(myShader);
    resizeCanvas(myImgRez,myImgRez,false);
    
    for (let i = 0; i < myImgNum; i++) {
      myShader.setUniform("col", [ i/myImgNum, 0.4, 0.3] );
      noStroke();
      rect(0, 0, 40, 40);

      //for my application I save iterations of myShader to a image, then texture map with that. 
      myImg.copy(canvas, 0, 0, myImgRez , myImgRez , myImgRez*i, 0, myImgRez , myImgRez );
    }
    resetShader();
    resizeCanvas(400,400,false);
  }
  
  stroke(0);
  background(230);
  rotateZ(theta * 0.1);
  rotateX(theta * 0.1);
  texture(myImg);
  box(100, 100, 100);
  theta += 0.05;
}


function keyPressed() {
if ((key == 'u') || (key == 'U') ) {
    myImg.save('texture', 'png');
  }
}


```

**Comment by aferriss** [comment]
After looking at this a little bit I think the main issue stems from the call to myImg.copy(). I would stay away from that function for now and instead use graphics objects for rendering a scene to a texture. 

I made a small example showing the issue with img.copy(), where a call to background seems to overwrite whatever was in the image.
https://editor.p5js.org/aferriss/sketches/HK9JwerUl

**Comment by davepagurek** [comment]
I was able to reproduce something similar on both Firefox and Chrome for android using the p5 example here: [https://p5js.org/examples/3d-textures.html](https://github.com/processing/p5.js/issues/url), but not reliably. I think maybe what I'm seeing is a separate issue from the one @aferriss mentioned, maybe having to do with the loading of the video? I wonder if p5 is trying to create a texture for it before it has loaded enough metadata to know the size.

**Comment by aferriss** [comment]
AH, I also meant to mention that the example on the reference in [https://p5js.org/examples/3d-textures.html](https://github.com/processing/p5.js/issues/url) worked on my Pixel 6 in Chrome. It seems like it could be device specific.

**Comment by jessssssse** [comment]
IOS would never work for either case. 
Android works some of the time. 

Ill try it using a graphics object, but wont I need to use myImg.copy() anyway?
```js
myImg.copy(graphicsOBJ, ... );
```
or are you saying to try: 

```js
texture(graphicsOBJ);
box(100, 100, 100);
```

I noticed in the example I gave, lowering myImgRez to 512 works some of the time. 
are there maximum texture sizes for mobile browsers?

**Comment by aferriss** [comment]
You shouldn't need myImg at all, using the graphics object is like drawing into a separate textures.

```
// in setup
g = createGraphics(400, 400, WEBGL);
sh = g.createShader(vert, frag);

// in draw
g.shader(sh);
sh.setUniform('col' ,[1, 0, 0]);
g.rect(0, 0, 10, 10);

texture(g);
box();

```

**Comment by aferriss** [comment]
@jessssssse Here's an example using graphics objects similar to your sketch 
https://editor.p5js.org/aferriss/sketches/WcJDnM8Nu

**Comment by jessssssse** [comment]
Thanks Adam!
This ended up working for me. 
https://editor.p5js.org/jbass754468546/sketches/k7NCFwzMt

**Comment by davepagurek** [comment]
> I made a small example showing the issue with img.copy(), where a call to background seems to overwrite whatever was in the image. https://editor.p5js.org/aferriss/sketches/HK9JwerUl

@aferriss I think in this example, the issue is that when you don't specify a source image in `.copy()`, it assumes it's copying from itself, so your sketch is copying an empty image to itself. If you pass the canvas in, it looks like `copy` works as expected: https://editor.p5js.org/davepagurek/sketches/UvcoAcpdd

If I ever need a full copy as a P5.Image instead of a p5.Graphics (mostly for perf reasons, because p5 sends new texture data to the GPU every frame when your texture is a graphic, but can keep the cached version for an image), I like using `img = canvas.get()`: https://editor.p5js.org/davepagurek/sketches/vk3F1btA1

**Comment by davepagurek** [comment]
One more update! @jessssssse, in your [p5 editor example](https://editor.p5js.org/jbass754468546/sketches/7aG0rrQoy), I also see black textures for the cube on Chrome for Android (but not Firefox.) After connecting it to a debugger, I see this error getting logged:

```
INVALID_VALUE: texImage2D: width or height out of range
```

It seems like maybe there's just a very conservative texture size limit on some mobile devices. When I set `myImgRez = 200;` in your sketch instead of 1024, the textures show up again. Maybe that's another source of this issue?
