### ISSUE TITLE
p5.Pvector.div() tries to divide by 0, if the vector was created by createVector(x,y)

### ISSUE THREAD

**Issue by v-k-** [processing/p5.js#5821]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [X] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [X] Math
- [ ] Typography
- [X] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

1.4.1

### Web browser and version

 	104.0.2

### Operating System

macOSX - 12.4

### Steps:
1. Make 2 vector using `createVector(x,y)`
2. Call Static version of p5.Vector div using both as parameters
3. get the error

### Snippet:

```js

function setup() {
  noCanvas();

  const v11 = createVector(10, 20);
  const v12 = createVector(5, 5, 1);//notice z is set here
  const v13 = p5.Vector.div(v11, v12);
  console.log(v13)//logs the vector (x: 2, y: 4) all fine
  
  
  const v1 = createVector(10, 20);
  const v2 = createVector(5, 5);
  const v3 = p5.Vector.div(v1, v2);//p5.Vector.prototype.div: divide by 0 error

  
}
```

**Comment by limzykenneth** [comment]
Hmm...This is a bit tricky. Internally all vectors are represented as 3D vectors and there is no differentiation between 2D or 3D vectors (1D as well), which means creating 2D vector automatically populate the third dimension magnitude as 0. Since `.div()` is element wise division it will cause a divide by zero in this case.

I'm not entirely sure what a good solution will be. We can check that the two vectors being divided have their third dimension be 0 and ignore it but it will cause false negative when the user are actually working in 3D. 

We can add an internal property to the vectors signalling whether it is created as 2D or 3D but there is nothing to stop a "2D" vector from interacting with a "3D" vector (which in certain situation defeat the purpose of this fix) and if we introduce something like that, it will be a breaking change. 

We can make the default magnitude of the third dimension non-zero but that will likely cause major problems with expected output of other vector operations.

Anyone has some ideas for how we can address this?

**Comment by davepagurek** [comment]
A non-breaking way to address this could be to add a `div2` or `div2D` to do 2d vector division, but that feels not quite ideal.

I wonder if we're able to detect when we convert a 2D vector to a 3D one? We could turn the x, y, and z properties of the vectors into getters/setters so that when you set z, it gets auto-converted into a 3D vector. Would that be enough to make it backwards compatible?

**Comment by v-k-** [comment]
>We can make the default magnitude of the third dimension non-zero but that will likely cause major problems with >expected output of other vector operations.

What if just inside `.sub` if the third parameter is 0 change it for 1 and back to zero after de division? If documented, would that be ok? 

Or maybe default z to 1 only in case the vector is created with just 2 params. Again documenting this.

`createVector(1,2)` creates (1,2,1)
`createVector(1,2,5)` creates (1,2,5)

I think mostly it affects who's working in 2D, and who's working in 3D will most likely creates 3d vectors with 3 parameters.

Anyway, the `.div2D` and `div3D` solution looks ok to me.

**Comment by davepagurek** [comment]
> I think mostly it affects who's working in 2D, and who's working in 3D will most likely creates 3d vectors with 3 parameters.

I think this is likely true for *most* cases, but I wouldn't be surprised if people initialize vectors that eventually get used in a 3D setting without specifying z if they know it'll be 0. This is a thing people do in shaders often, so devs used to GLSL might do that in p5 too. This is just a guess, but if we can avoid breaking those uses, that would be the best case scenario.

> Or maybe default z to 1 only in case the vector is created with just 2 params.

Unfortunately I think it will affect `length()` calculations if we default it to anything but 0, making 2D vectors look unexpectedly long.

Another idea: If both of the vectors involved in `.div()` have `z=0` we can skip writing to `z`. If you divide a 3D vector by a 2D vector, then getting an error is expected I think, and dividing a 2D vector by a 3D vector will still leave `z=0` at the end. It would mean that some 3D vector divisions that originally would throw an error now will continue silently, but maybe that tradeoff is OK?

**Comment by limzykenneth** [comment]
> I wonder if we're able to detect when we convert a 2D vector to a 3D one? We could turn the x, y, and z properties of the vectors into getters/setters so that when you set z, it gets auto-converted into a 3D vector. Would that be enough to make it backwards compatible?

My instict here is that there is no deterministic way to do the detection of when `z` gets accessed without false positives.

> Another idea: If both of the vectors involved in .div() have z=0 we can skip writing to z. If you divide a 3D vector by a 2D vector, then getting an error is expected I think, and dividing a 2D vector by a 3D vector will still leave z=0 at the end. It would mean that some 3D vector divisions that originally would throw an error now will continue silently, but maybe that tradeoff is OK?

This solution is not perfect as noted but I think may be the only possible solution short of the larger breaking change of making 2D and 3D vectors separate. I'm not sure how in 3D an element wise division would mean geometrically but there may be a possible argument to be made that element wise division works on every Z plane except for z=0 so we'll just be making it possible for every value of Z I guess, or maybe making it possible for the plane z=0 would not make sense at all(?)

**Comment by v-k-** [comment]
As a "fix" to this, in my code, 2D, I set the z to 1 at the constructor only for vector that I'm going to divide by. Although with no practical effects, as I'm not using z anyway, I happen to notice this bad, because when I add the vector to some other z becomes 2...3...4...

**Comment by v-k-** [comment]
How do java's Processing deal with it?

**Comment by limzykenneth** [comment]
Processing only allows division by a scalar value and no element-wise vector division.

**Comment by davepagurek** [comment]
> This solution is not perfect as noted but I think may be the only possible solution short of the larger breaking change of making 2D and 3D vectors separate. I'm not sure how in 3D an element wise division would mean geometrically but there may be a possible argument to be made that element wise division works on every Z plane except for z=0 so we'll just be making it possible for every value of Z I guess, or maybe making it possible for the plane z=0 would not make sense at all(?)

One possible geometric interpretation: Multiplying two vectors elementwise is applying a linear map from one coordinate space to another (the second vector can be thought of more like a diagonal matrix that you're multiplying the first vector by.) Elementwise division would then correspond to inverting that linear map. For both the forward and inverse to be defined, the map would have to be both injective and surjective. If any of the values of the vector is 0, multiple inputs map to the same output and it would no longer be injective, so the inverse wouldn't be defined.

Anyway, I think I'm comfortable with this solution if you are! I can make a PR if we're ok with it.
