### ISSUE TITLE
_downKeys should use event.code rather than depreceted event.which

### ISSUE THREAD

**Issue by ibrahimqasim** [processing/p5.js#5823]
### Increasing Access

Currently the keyboard events are stored as numerical values in an object using the deprecated `event.which` property of keyboard events. Accessing them requires the use of built-in constants or having to look up the key code values. Using the `event.code` property is the modern way to access them, and also increases accessibility by making key codes easier to memorize and removes the need for constants.

### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [X] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### Feature request details

Currently, keyboard events are stored in the _downKeys object. When a keydown event is registered, the _downKeys object is updated using the `event.which` property. This property has been deprecated for a while now. Furthermore, use of functions like `keyIsDown` require either the numerical value of keys, e.g. 65 for key A, or the use of constants, e.g. LEFT_ARROW. This makes code less clear and requires the use of other websites to get specific keycodes.

_downKeys should be updated to use `event.code` instead. This works in a similar fashion to `event.which` in that is it not dependent on capitalization, however the values returned are more readable and easier to use, e.g. 'KeyA' instead of 65.

For example, a very common situation might be to use WASD keys for navigation:
Current version:
```
if (keyIsDown(87)) {
    ...
}
if (keyIsDown(65)) {
    ...
}
if (keyIsDown(83)) {
    ...
}
if (keyIsDown(68)) {
    ...
}
```
New version:
```
if (keyIsDown('KeyW')) {
    ...
}
if (keyIsDown('KeyA')) {
    ...
}
if (keyIsDown('KeyS')) {
    ...
}
if (keyIsDown('KeyD')) {
    ...
}
```

This would be a breaking change, but there are ways to keep backwards compatibility.

**Comment by davepagurek** [comment]
For backwards compatibility, how do you feel about making `keyIsDown` accept either a string or a number, so that existing code passing character codes won't stop working, but one can pass a string to use a more mnemonic name for each key?

**Comment by ibrahimqasim** [comment]
> For backwards compatibility, how do you feel about making `keyIsDown` accept either a string or a number, so that existing code passing character codes won't stop working, but one can pass a string to use a more mnemonic name for each key?

That's exactly what I was thinking should work. And the _downKeys map could just include the `event.code` as it wouldn't conflict with the numerical key codes from `event.which`.

Happy to make a pull request if this can be agreed. I'm unsure exactly where else the _downKeys is used.

**Comment by ibrahimqasim** [comment]
Would `_downKeys` be something that would be used on touch devices? I didn't think that key down was a thing for them, but if that is an issue then could that be handled by including the `event.which` in `_downKeys` as well as `event.code` as it keeps backwards compatibility?

My understanding of the layout issue is that if the physical layout of the keyboard is DVORAK, the key codes will match the keys. I just tested, and it seems that the only issue is that it doesn't match the emulated keyboard layout. I may be wrong though. I also imagine this could not handle keyboards where simply the keycaps have been swapped around.

Does `keyIsDown` assume keyboard layout, or is it based on the physical keys?

This may be more suitable in a separate discussion, but I would expect the key events to be handled based on physical layout rather than the character layout. This is similar to how many games handle keyboard input which is based on physical layout and is not affected by language.

**Comment by ibrahimqasim** [comment]
Further from testing on [keycode.info](https://www.toptal.com/developers/keycode):

`event.which`
- ASCII code for key, independent of layout
- Does not differentiate between left or right modifier keys
- Unaffected by capitalization
- Matches input character if using different layouts

`event.key`
- Affected by modifier keys (e.g. shift) or capslock
- Affected by keyboard layout

**Comment by limzykenneth** [comment]
> Would _downKeys be something that would be used on touch devices?

Physical keyboards can be attached to those devices (plus other android based devices that has nothing to do with smartphones and tablets) and other potential usage may also be possible so we can't infer physical capabilities from just the OS it is running.

> My understanding of the layout issue is that if the physical layout of the keyboard is DVORAK, the key codes will match the keys. I just tested, and it seems that the only issue is that it doesn't match the emulated keyboard layout. I may be wrong though. I also imagine this could not handle keyboards where simply the keycaps have been swapped around.

What it means is that the key code from `KeyboardEvent.code` is mapped as if the keyboard is always a US layout keyboard, regardless of the virtual layout, physical layout, actual number of keys, foreign script, or whatnot. It describes a physical key/button on the keyboard, which in my opinion made no sense to be named `KeyA` etc after the US keyboard and I'm privately disappointed at the W3C for naming them this way, but that's beside the point :stuck_out_tongue_closed_eyes: 

Since `keyIsDown` is using `event.which` it is not based on physical key but a number code given to each typed key.

**Comment by ibrahimqasim** [comment]
I see... It's strange then that there is no alternative for `KeyboardEvent.which` which takes the keyboard layout into account.

I still feel this feature should be considered some time in the future, but clearly there are many more challenges than I first thought! I'll close the issue for now though.

**Comment by davepagurek** [comment]
Thanks @limzykenneth for your research into the details of this!
