### ISSUE TITLE
Typescript Definition File

### ISSUE THREAD

**Issue by benhinchley** [processing/p5.js#583]
I am in the works/thinking about creating a typescript definition file for the main p5.js file along with both the addons p5.sound.js & p5.dom.js, was wondering if this will be useful to other people or am I the only one wanting to write my sketches in typescript?? and if this is useful is it something that if made should be put into the main repo??

**Comment by lmccart** [comment]
hey @benhinchley this seems like a great thing to link to from the [contributed tools page](https://github.com/processing/p5.js/wiki/Contributed-Tools,-Projects,-Demos). the page is a bit of a hodge podge right now, but we're planning to do some reorganization of it at the beginning of the summer.

**Comment by omidb** [comment]
Is there any progress on typescript? I need it to port p5js to ScalaJS

**Comment by benhinchley** [comment]
I am currently like a quarter of the way through, just been doing it in my spare time. It's a little confusing tbh as there isn't a lot of docs on making typescript definition files

**Comment by benhinchley** [comment]
@omidb I have kind of given up on this, as I have started to use babel and es6 more and more. Sorry about that, if you were waiting on me for it.

**Comment by lpil** [comment]
If it is useful to others can you post what you have so far?

**Comment by benhinchley** [comment]
I'll try and clean up what I have an post it sometime in the few weeks

**Comment by lmccart** [comment]
thanks @benhinchley!

**Comment by lmccart** [comment]
since it seems like there's no active energy around this one, I'm going to close it. if anyone would like to tackle it, we can reopen.

**Comment by benhinchley** [comment]
Sorry guys have been swamped with work recently, I will try and get what I have done previously up somewhere soon. Though best to keep this closed for the meantime

**Comment by toolness** [comment]
Hey, I've just done some work with TypeScript as part of my Processing Fellowship to improve the friendly error system, and wrote a blog post about it here:

http://processing.toolness.org/general/2016/03/16/typescript-to-the-rescue.html

I'm really liking TypeScript so far, and I'm hoping we'll be able to integrate a well-maintained TypeScript definition file into p5 going forward.

**Comment by lpil** [comment]
Hooray!

**Comment by asifm** [comment]
@toolness Is there a way to install the type definitions with `typings install`? `typings search --name -p5` doesn't return any result. 
Thanks for your work on this.

**Comment by toolness** [comment]
Oh, shoot, I'm such a noob at typescript I didn't even know about `typings`! :sweat_smile: 

I'll register it asap, thanks for mentioning it :)

**Comment by deiangi** [comment]
@toolness  Thank you so much for the effort.
Help me understand have you had a chance to test it or use it?

I just for a copy of it but it seems that there are some issues with the latest version.

**Comment by ranveeraggarwal** [comment]
Is anyone currently working on this? 

I am new to Typescript (and to p5js; I just saw the intro video) but I have some time on my hands and love for the field of visualization, so I would love to contribute 😃

**Comment by Alv1s** [comment]
Hi, so is there option to take type definition as install using npm ? My goal is to add p5js to intellisense to Visual Studio Code, maybe somebody succeeded already and could share their experience? Thanks in advance.

**Comment by shramee** [comment]
Hi @toolness, I am experienced with both typescript and p5 (done for my clients), I'm looking forward to using p5 with TypeScript 😋 
I'll have a play with your definition files, in the meantime feel free to tell me what is missing...

**Comment by TheShashank** [comment]
Any news on Typings bindings for P5js?

**Comment by olaven** [comment]
It would be great to use typescript in p5js. I have just started using TS and would love to move that over to p5-stuff! 

I am beginner in TS as well, but if I can do something, I'll gladly contribute! 🐶

**Comment by Spongman** [comment]
here's a build of the latest p5.js master branch, including the `.d.ts` files: https://github.com/Spongman/p5.js/releases

**Comment by wuyudi** [comment]
https://github.com/p5-types/p5.ts
