### ISSUE TITLE
Translators and proofreaders needed for SoD contributor survey

### ISSUE THREAD

**Issue by limzykenneth** [processing/p5.js#5831]
### Topic

Hi everyone, this is a call for translators and translation proofreaders for a survey I am planning for the GSoD project around contributor documentation. The survey is mainly about the p5.js contributor experience and the plan is to release it around end of October. The survey is about 14 questions long mostly consist of multiple choice questions.

I'm seeking contributors who are fluent in the below listed languages to either be a translator or proofreader for the translation. There are currently already a few languages translated and just require proofreading, in addition I'm seeking to add one or two more translations. The timeline I'm working with at the moment is rather tight to I'm not looking to add additional translations beyond the languages listed below.

Simplified Chinese
* [x] Translation
* [x] Proofreading

Korean
* [x] Translation
* [x] Proofreading

Hindi
* [x] Translation
* [x] Proofreading

Japanese
* [x] Translation
* [x] Proofreading

Spanish
* [x] Translation
* [x] Proofreading

Arabic
* [x] Translation
* [x] Proofreading

---

If you are interested to help with the translation or proofreading for any of the listed languages above, you can leave a comment here with the language you are interested in translating/proofreading and drop me an email on limzy.kenneth@gmail.com. Thank you!

cc @Qianqianye

**Comment by Qianqianye** [comment]
Thanks Ken for initiating the contributor survey.  If you are interested in translating/proofreading the survey to Chinese, Korean, Hindi, Japanese, Spanish or Arabic, please leave a comment here with the language you are interested in translating/proofreading and contact Ken via email. Thank you!

I am also pinning the translation stewards to this issue.
| Language | Steward(s)                |
| -------- | ------------------------- |
| Spanish  | @Guirdo, @Andreu-G, @dnd-alv         |
| Chinese  | @unicar9, @Gracia-zhang, @pentalei|
| Korean   | @yinhwa, @almchung, @jhongover9000, @sssueing, @GeryGeryGery, @sosunnyproject |
| Hindi    |  @adarrssh, @Divyansh013, @deepchauhan, @SarveshLimaye,  (Reviewers: @ranaaditya @SanjaySinghRajpoot)|

Other Language Steward(s):

- Portuguese: @raphaelavelar

**Comment by almchung** [comment]
Hi Kenneth, I'll be happy to do proofreading (Korean). Let me know if there's anything more to help.

**Comment by shaharyar-shamshi** [comment]
Hi keneth I will be happy for hindi proofreading. Do let me know how to proceed

**Comment by 3ru** [comment]
Hi Kenneth, I can help with Japanese translation and proofreading😸

**Comment by AlexxLeoHansen** [comment]
Hi Kenneth!
I can help translation and proofreading in Spanish.

**Comment by vickyyysss** [comment]
Hey Kenneth!

I can help with translation and proofreading in Spanish.

**Comment by limzykenneth** [comment]
Hi @AlexxLeoHansen and @vickyyysss, I would like to ask you two to translate and proofread the survey in Spanish (separately), can the two of you drop me an email at my email address above so we can make an arrangement over email? I can't find your email address on your GitHub profile. Thanks!

**Comment by tetunori** [comment]
Hi @limzykenneth and @3ru , I can also help with Japanese proofreading!

**Comment by CinminC** [comment]
Hi Kenneth, I can help translation and proofreading in Chinese.

**Comment by AladdinX** [comment]
Hi Kenneth, I can help with translation and proofreading in Arabic .

**Comment by jeff2957** [comment]
Hi Kenneth, I can help with translation and proofreading in Chinese (Traditional Chinese if it's needed)

**Comment by limzykenneth** [comment]
Hi @jeff2957, I would love to do a Traditional Chinese version and if I can find one additional person to do the proofreading while you do the translation I can get that going. However, I'm kinda on a tight deadline though as I want to have the survey out by early November so if we didn't manage it this time we can still look into any of the follow up stuff I have planned that may need translation. 

Thanks for offering to help in any case!

**Comment by jsyeh** [comment]
Hi @limzykenneth  I could do the Traditional Chinese translation or help the proofreading of the translation of @jeff2957 .

ps. I just finish another translation assigned by SableRaf now.

**Comment by limzykenneth** [comment]
@jeff2957 If you can drop me an email at my email address above, I can arrange for you to do the proofreading for the Traditional Chinese translation.

**Comment by comparlimage** [comment]
What about french translation ?

**Comment by LoubiTek** [comment]
Im French ! :)

**Comment by limzykenneth** [comment]
Hi @comparlimage and @LoubiTek, thanks for the interest in a French translation of the survey. Currently I'm operating at capacity and we are finalizing the surveys to be release soon so I can't prioritize adding another translation to the survey at this moment. 

Additionally for the languages we did choose previously, as listed above, to translate into are primarily communities where we know there are a good amount of p5.js users and contributors, as well as having a sizable community where knowledge of English may be more limited. It is by no means comprehensive nor complete but for now I'll have to table adding additional translations and I'm sure there will be more opportunities in the future as I certainly do plan to continue this line of research.

**Comment by takawo** [comment]
Hello @limzykenneth @3ru @tetunori. I thank you all for your contributions!
I can also help with Japanese proofreading.

**Comment by Sillenaj** [comment]
Hi i can support in proofreading Arabic

**Comment by limzykenneth** [comment]
Thanks to everyone for the very generous help with this! The survey is now released and I would like to ask all of you for one more help: the survey is now released at [bit.ly/2022p5survey](https://bit.ly/2022p5survey) so please share them widely in your network!

Closing the issue now and I'll share the survey result and its analysis after the survey has concluded.
