### ISSUE TITLE
Distinguish contours in textToPoints

### ISSUE THREAD

**Issue by davepagurek** [processing/p5.js#5838]
### Increasing Access

Currently, `textToPoints` returns a flat array of points. For some use cases, this is sufficient, but it makes it difficult to draw closed shapes without artifacts. The example in [the p5 docs](https://p5js.org/reference/#/p5.Font/textToPoints) illustrates the problem:
![image](https://user-images.githubusercontent.com/5315059/196491183-9617e93a-3d3f-4497-b927-1d14058c96a5.png)

Right now, there are some glitches in the shapes between the inner circle of the p and between the p and the 5, as the whole shape is drawn as one path.

If one wishes to avoid those artifacts, a significant amount of code is required. One approach is to try to distinguish between different shapes by looking at the distance between points, implemented in this sketch: https://openprocessing.org/sketch/1695048 Unfortunately, this approach is a tad brittle, and the threshold must be carefully chosen, or other artifacts appear:
![image](https://user-images.githubusercontent.com/5315059/196492054-f5a8320e-9e49-4ca0-8c56-0f7b845bf3c2.png)

Another approach is to not use `textToPoints` and instead use opentype.js. This sketch implements this method: https://editor.p5js.org/davepagurek/sketches/mBTDpMnhT However, it requires parsing the Bezier drawing commands manually into `vertex` and `bezierVertex` calls. If one wants points from these, one would have to sample the curves manually. It is doable, but has a large number of parts.

One more approach is to try to recreate what the p5 source code already does, but instead of appending all points to a flat array, create a new array for each contour here: https://github.com/processing/p5.js/blob/v1.4.2/src/typography/p5.Font.js#L260 This sketch implements that approach: https://openprocessing.org/sketch/1616318 However, it relies on a number of non-exported helpers, requiring copy-and-pasting of a significant amount of code.

Neither approach seems ideal, and drawing filled text shapes but allowing for you to modify the points seems like a common thing one would want to do with `textToPoints`.

### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [X] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### Feature request details

Instead of returning an array of points, it would be great to have a way of returning an array of arrays of points, where each sub-array corresponds to a separate contour. Internally, this would mean creating sub-arrays here instead of adding them all to the same array:
https://github.com/processing/p5.js/blob/v1.4.2/src/typography/p5.Font.js#L260

A few API designs for this:

```js
// As a separate method
const contours = textToContours('p5', 0, 0)

// As an option
const contours = textToPoints('p5', 0, 0, 24, { contours: true })

// As a mode
textToPointsMode(CONTOURS)
const contours = textToPoints('p5', 0, 0)
```

Other things I'd like feedback on:
- Does it make more sense to further segment the output by letter?
- Technically we can use `begin/endContour` for all contours, as it just uses the evenodd rule to determine if something is a fill or a hole. However, p5 breaks if you only use contours and don't have vertices.
  - [This sketch](https://openprocessing.org/sketch/1695048) treats the first path as vertices and the rest as contours, but this feels less clean than letting users use *only* contours
- How much do we care about the TypeScript types for p5, which would be a bit more difficult if the same method can return multiple signatures based on options/mode?

**Comment by dhowe** [comment]
see also: https://github.com/processing/p5.js/issues/4086

**Comment by davepagurek** [comment]
Aha, thanks for bringing that one up! I'll close this and move discussion over to the other.
