### ISSUE TITLE
saveGif - Delay Parameter Error in Instance Mode

### ISSUE THREAD

**Issue by pcybriwsky** [processing/p5.js#5848]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [X] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [X] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

1.5.0

### Web browser and version

Chrome: 107.0.5304.87 

### Operating System

macOS 11.6.4

### Steps:
Hi! This is my first issue report so hope this is formatted correctly.

I am using p5js in instance mode and trying to render a GIF of the onscreen Canvas. 

In-short, instance of p5 sketch rejects the 'delay' parameter, throwing an error that it is of not type number. Have tried this in both set-up, draw, and independent function calls as well as across browsers. Does this function work in instance mode?

The error and sample code below of the function call:

Error included here: 

> Unhandled Promise Rejection: TypeError: Delay parameter must be a number
> dispatchException — regeneratorRuntime.js:231
> (anonymous function) — regeneratorRuntime.js:52
> l — p5.min.js:2
> n — p5.min.js:2
> (anonymous function) — p5.min.js:2
> Promise
> r — p5.min.js:2
> (anonymous function) — Trailblazer.js:729

### Function Snippet:

```js

p.downloadGif = () => {
    var gifDuration = Math.ceil(max_coordinates/fr);
    p.saveGif(piece_title, gifDuration, Number(0));
    callGIF = false;
  }

**Comment by davepagurek** [comment]
I believe after the title and duration, you need to specify an options object with the delay number and the unit. Does this work for you?:
```js
p.saveGif(piece_title, gifDuration, { delay: 0, unit: 'seconds' })
```

**Comment by bleything** [comment]
> I believe after the title and duration, you need to specify an options object with the delay number and the unit.

I was having this same problem and adding the object fixed it for me. That said, the docs state that third param should be optional. It would be good to either fix the docs or fix the code.

**Comment by davepagurek** [comment]
I believe the third parameter *is* optional -- does the example code here work for you? https://p5js.org/reference/#/p5/saveGif It just uses two parameters, and seems to successfully save a gif for me. I believe the issue in the comment I was replying to was that they were providing a third argument, but it was just a single number, not an object, which is not something the docs say is possible.

**Comment by bleything** [comment]
You're right, the sample code works fine. I'm a little embarrassed... I was trying a bunch of different ways of calling `saveGif` and I think I just got confused about which one worked and which one didn't. And I didn't read this issue closely enough before commenting. Sorry for the noise!

**Comment by davepagurek** [comment]
No worries, glad it works!

**Comment by davepagurek** [comment]
For organizational purposes I'm going to mark this as closed, but feel free to comment/ask to reopen this if anyone finds any more issues, or file a new issue if you find any different bugs in saveGif 🙂
