### ISSUE TITLE
P5's `random()` function results in non-random outputs

### ISSUE THREAD

**Issue by ianstormtaylor** [processing/p5.js#5849]
I noticed a weird behavior with P5's built-in `random()`, when doing a test of:

```ts
  for (let x = 0; x < width; x++) {
    for (let y = 0; y < height y++) {
      let r = random()
      let i = int(map(r, 0, 1, 0, 2 ** 32))
      fill(i % 2 ? 'black' : 'white')
      rect(x, y, 1, 1)
    }
  }
```

Results in very non-random looking output:

<img width="299" alt="image" src="https://user-images.githubusercontent.com/311752/199852750-b2fb3c90-3e9a-44cc-bf90-732245dd1311.png">

And I compared it with a few other PRNG's that don't seem to exhibit the same issue…

<details>
<summary>Math.random</summary>
<img width="299" alt="image" src="https://user-images.githubusercontent.com/311752/199853088-96ae1c4b-3a9d-4325-a9eb-22ba2b95d31d.png">
</details>

<details>
<summary>crypto.getRandomValues</summary>
<img width="299" alt="image" src="https://user-images.githubusercontent.com/311752/199853130-10fc8f3a-7468-43f2-9171-4075b08c1af1.png">

[source](https://stackoverflow.com/questions/15821447/converting-random-bytes-to-an-integer-range-how)
</details>

<details>
<summary>LCG</summary>
<img width="299" alt="image" src="https://user-images.githubusercontent.com/311752/199853154-016b03f5-ea96-423c-8292-677c178cfc24.png">

[wiki](https://en.wikipedia.org/wiki/Linear_congruential_generator), [source](https://github.com/kisel/lcg-bytes/blob/master/index.js)
</details>

<details>
<summary>Mersenne Twister</summary>
<img width="299" alt="image" src="https://user-images.githubusercontent.com/311752/199853670-bf9ac64c-5a74-4dbe-b10b-0834e31e9d2b.png">

[source](https://github.com/boo1ean/mersenne-twister/blob/master/src/mersenne-twister.js)
</details>

<details>
<summary>Xorshift</summary>
<img width="299" alt="image" src="https://user-images.githubusercontent.com/311752/199853694-ac7e5411-ad6e-45ab-88e1-eb7d37c86e1d.png">

[source](https://github.com/AndreasMadsen/xorshift/blob/master/xorshift.js)
</details>

<details>
<summary>PCG</summary>
<img width="299" alt="image" src="https://user-images.githubusercontent.com/311752/199853721-2b18740d-8ead-4a30-acfc-96fb9346f6ce.png">

[source](https://github.com/thomcc/pcg-random/blob/master/pcg-random.js)
</details>

---

As the `2 ** 32` maximum end of the interpolated range is reduced, you start to get more and more random-looking results again…

<details>
<summary><code>2 ** 30</code></summary>
<img width="299" alt="image" src="https://user-images.githubusercontent.com/311752/199854211-2fc61b23-d3d3-4c90-b64c-1c03f687673e.png">
</details>

<details>
<summary><code>2 ** 28</code></summary>
<img width="299" alt="image" src="https://user-images.githubusercontent.com/311752/199854284-215cbb36-5448-48cb-a05d-d598e195cc05.png">
</details>

<details>
<summary><code>2 ** 26</code></summary>
<img width="298" alt="image" src="https://user-images.githubusercontent.com/311752/199854329-487dc107-4ef8-4bea-b695-256a8a9b7c86.png">
</details>

<details>
<summary><code>2 ** 24</code></summary>
<img width="298" alt="image" src="https://user-images.githubusercontent.com/311752/199854373-57bf9014-33d9-478a-b4fb-1265841dfabc.png">
</details>

<details>
<summary><code>2 ** 22</code></summary>
<img width="299" alt="image" src="https://user-images.githubusercontent.com/311752/199854415-801b0cee-ac5f-419d-a6d7-9d9d1d04a41e.png">
</details>

<details>
<summary><code>2 ** 20</code></summary>
<img width="299" alt="image" src="https://user-images.githubusercontent.com/311752/199854465-40264d97-9f77-479a-9cf2-6be56d3f6217.png">
</details>

<details>
<summary><code>2 ** 18</code></summary>
<img width="298" alt="image" src="https://user-images.githubusercontent.com/311752/199854483-8d3d580e-52a6-42b3-84b9-8a6bb98c0d01.png">
</details>

<details>
<summary><code>2 ** 16</code></summary>
<img width="298" alt="image" src="https://user-images.githubusercontent.com/311752/199854495-ae925b1f-12d1-413f-b81f-9f610bf8a1ff.png">
</details>

By the time it's down to `2 ** 16` it feels very random again.

Is this a hard limit on P5's implementation that should be mentioned somewhere? Or some other bug going on? (I'm sure there could be other calculations where this crops up if it does in the simple `x % 2` case.)

---

Here's a sketch file I made where you can choose between a handful of PRNG's and test the varying outputs: https://editor.p5js.org/ianstormtaylor/sketches/P6wSKmB1v

**Comment by ianstormtaylor** [comment]
This might be a reflection of this phenomenon: (but I'm no expert)

> Another problem of LCGs is the lattice structure appearing in high-dimen-
sional random points plotting. … Then we obtain Figure 1. Comparing with Figure 2 generated by MT, one sees a clear lattice structure. This is not because of bad choices of a or c. For any LCG, if it is used for the full period, then the generated points in the unit cube are arranged in a lattice. 
>
> <img width="662" alt="image" src="https://user-images.githubusercontent.com/311752/199899654-d52c9642-0c68-42b5-b5e8-a3ade0d0d90f.png">
>
> — [Pseudorandom Number Generation: Impossibility and Compromise](https://www.jucs.org/jucs_12_6/pseudorandom_number_generation_impossibility/jucs_12_06_0672_0690_matsumoto.pdf)

Oh, well actually further down in that paper, there's this bit which is much more relevant:

> Another warning applies when the modulus N is chosen to be a power of two,
to decrease the cost of calculating modulo N . In this case, the s least significant
bits of the generated pseudorandom integers have the period at most 2s. In
particular, the least significant bit has period at most 2, and the above LCG
generates odd numbers and even numbers alternately

**Comment by limzykenneth** [comment]
I think the problem is exactly as what you have found and is an inherent limitation of the LCG implementation. Depending on whether you need a fixed random seed or not you can use `random()` without setting a random seed which will use `Math.random()` by default.

**Comment by davepagurek** [comment]
@ianstormtaylor thanks for filing this issue! I didn't know about this limitation of LCG before, and your visuals are really fun to look at.

**Comment by ianstormtaylor** [comment]
@davepagurek thanks! I had no idea either. 

Apparently it's also not inherent to all LCG's (at least the `% 2` issue isn't), but it so happens that the super-fast one that P5.js uses is vulnerable to this:

```ts
function p5js(seed: number) {
  let M = 2 ** 32
  let A = 1664525
  let C = 1013904223
  seed = seed >>> 0
  return () => {
    seed = (A * seed + C) % M)
    return seed / M
  }
}
```

But if it used [Parker-Miller](https://en.wikipedia.org/wiki/Lehmer_random_number_generator#Parameters_in_common_use) I believe it wouldn't have that specific issue, roughly:

```ts
function parkerMiller(seed: number) {
  let M = 2 ** 31 - 1
  let A = 48271
  seed = seed >>> 0 // technically the seed needs more restricting than this
  return () => {
    seed = (A * seed) % M
    return seed / M
  }
}
```

Although I think it might still have the other distribution issues.

**Comment by quinton-ashley** [comment]
I made this sketch based on the 2 ** 28 tessellation that looks like a little pixel fish to me!
https://openprocessing.org/sketch/1736582
