### ISSUE TITLE
Getting Errors in Page build and deployment

### ISSUE THREAD

**Issue by swannekim** [processing/p5.js#5851]
### Topic

I was making a simple page through p5.js.
It showed up on p5.js web editor (https://editor.p5js.org/swannekim/sketches/6v-vdq7xi),
so I downloaded the files via File > Download on the editor,
then uploaded the files on a folder at my Git Repository.

I did the same process last time, and the web page built by GitHub worked out well.
However, there is just <Loading...> sign on a blank page this time.

It is the same repository, just folders where files are in are different.
I have no idea why my web page is not showing up. It would be so nice if anyone could give me some help!

**Comment by davepagurek** [comment]
It looks like this is a result of this issue with the web editor: https://github.com/processing/p5.js-web-editor/issues/2075

Does this still happen if you copy the text/images files from wherever they first came from on your own computer rather than from the zip download from the p5 editor?

**Comment by swannekim** [comment]
> It looks like this is a result of this issue with the web editor: [processing/p5.js-web-editor#2075](https://github.com/processing/p5.js-web-editor/issues/2075)
> 
> Does this still happen if you copy the text/images files from wherever they first came from on your own computer rather than from the zip download from the p5 editor?

It worked after uploading the original files! Thank you so much in helping to resolve the issue :)
