### ISSUE TITLE
line() is not a function

### ISSUE THREAD

**Issue by raulhubgit** [processing/p5.js#5865]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [X] Other (specify if possible)

### p5.js version

0.9.0

### Web browser and version

Microsoft Edge 107.0.1418.52

### Operating System

Windows 11 Version 21H2 (Build 22000.978)

### Steps:
1.start function draw
2.put an if with the condition mouseIsPressed
3.put the function line() with parameters pmouseX, ´pmouseY, mouseX, mouseY

### Snippet:

```js

// Paste your code here :)

function setup(){
    canvas = createCanvas(280, 280);
    canvas.center();
    background("white");
    canvas.mouseReleased(classifyCanvas);
    synth = window.speechSynthesis;
}
function preload(){
    classifier = ml5.imageClassifier('DoodleNet');
}
function draw(){
    strokeWeight(13);
    stroke('red');
    if(mouseIsPressed){
        line(pmouseX, pmouseY, mouseX, mouseY);
    }
}
function clearCanvas(){
    background("white");
}
function classifyCanvas(){
    classifier.classify(canvas, gotResult)
}
function gotResult(error, results){
    if(error){
        console.error(error);
    }
    console.log(results);
    document.getElementById('label').innerHTML = 'label: '+results[0].label;
    document.getElementById('confidence').innerHTML = 'confidence: '+Math.round(results[0].confidence*100)+'%';
    utterThis = new SpeechSynthesisUtterance(results[0].label);
    synth.speak(utterThis);
}

console error: Uncaught TypeError: line is not a function
    at draw (main.js:46:5)
    at i.redraw (p5.min.js:3:274898)
    at h.<anonymous> (p5.min.js:3:231436)

**Comment by davepagurek** [comment]
Hi! It seems to work for me if I take out the ML5 parts and just do the line drawing:

```js
function setup(){
  canvas = createCanvas(280, 280);
  canvas.center();
  background("white");
}

function draw(){
    strokeWeight(13);
    stroke('red');
    if(mouseIsPressed){
        line(pmouseX, pmouseY, mouseX, mouseY);
    }
}
```

Live version: https://editor.p5js.org/davepagurek/sketches/cqXZslT1N

Maybe this means there's an error happening in your `preload` or `gotResult` handlers that's causing everything to break? Are there any other errors in your console?

**Comment by raulhubgit** [comment]
> Hi! It seems to work for me if I take out the ML5 parts and just do the line drawing:
> 
> ```js
> function setup(){
>   canvas = createCanvas(280, 280);
>   canvas.center();
>   background("white");
> }
> 
> function draw(){
>     strokeWeight(13);
>     stroke('red');
>     if(mouseIsPressed){
>         line(pmouseX, pmouseY, mouseX, mouseY);
>     }
> }
> ```
> 
> Live version: https://editor.p5js.org/davepagurek/sketches/cqXZslT1N
> 
> Maybe this means there's an error happening in your `preload` or `gotResult` handlers that's causing everything to break? Are there any other errors in your console?

no, unfortunately

**Comment by Npvpr** [comment]
I am also having this issue. How did you solve it?

**Comment by Npvpr** [comment]
I found the problem. In my case, the error is not actually from p5.js. It's from VScode live server extension. When I open the HTML file manually, it works just fine.

**Comment by njberman** [comment]
> I found the problem. In my case, the error is not actually from p5.js. It's from VScode live server extension. When I open the HTML file manually, it works just fine.

I have the same issue, did u find anything else to fix it?

**Comment by davepagurek** [comment]
@njberman Maybe try using p5 in instance mode? https://github.com/processing/p5.js/wiki/Global-and-instance-mode This means no variables will be global, so nothing should clash with the extension.

**Comment by njberman** [comment]
@davepagurek thanks i will try that

**Comment by raulhubgit** [comment]
thanks
