### ISSUE TITLE
inconsistent strokeWeight between Safari and Chrome

### ISSUE THREAD

**Issue by WillMuijrers** [processing/p5.js#5867]
### Web browser and version

Safari and Chrome

### Operating System

MacOSX

### Steps to reproduce this

Please check the below sketch in Safari and Chrome:
https://editor.p5js.org/ChaniceMertens/sketches/XakHo3ES-

StrokeWeight() seems to be placed inconsistently between browsers.

**Comment by limzykenneth** [comment]
This is a relatively new Safari bug, it has already been reported here: https://bugs.webkit.org/show_bug.cgi?id=246498. We'll have to wait for the fix in Safari and not much we can fix in p5.js. I'll close this for now but feel free to follow up in this issue.
