### ISSUE TITLE
touchIsDown bug?

### ISSUE THREAD

**Issue by hardmaru** [processing/p5.js#587]
Hi!

There seems to be some bug when using touchIsDown.  Basically, when I remove my hand from the screen, touchIsDown is still set to true.  I have this issue with iPhone and iPad, but have not tested this on android.

As a comparison, mouseIsPressed works fine.

This is a simple example i created to test the issue:

http://swaption.net/gesture.html

code:
```javascript
function setup() {

  var myCanvas = createCanvas(windowWidth,windowHeight);
  myCanvas.parent('p5Container');
  frameRate(60);

  fill(0);
  stroke(0);
  textFont("Courier New");
  textSize(32);

}


function draw() {
  background(255);
  text("Gesture", 10, 32);

  if (mouseIsPressed) {
    text('dx: '+(mouseX-pmouseX), 10, 64);
    text('dy: '+(mouseY-pmouseY), 10, 96);
    text('x: '+(mouseX), width/2, 64);
    text('y: '+(mouseY), width/2, 96);
    text('mouse is pressed', 10, 128);
  } else {
    text('mouse is not pressed', 10, 128+32);
  }

  if (touchIsDown) {
    text('dx: '+(touchX-ptouchX), 10, 64);
    text('dy: '+(touchY-ptouchY), 10, 96);
    text('x: '+(touchX), width/2, 64);
    text('y: '+(touchY), width/2, 96);
    text('touch is down', 10, 128);
  } else {
    text('touch is not down', 10, 128+64);
  }

}

'''

**Comment by debone** [comment]
I've tested on Internet Explorer on Windows Phone 8 and it has the same bug
apparently

**Comment by kevinb7** [comment]
I had a quick look at the code and ```_updateTouchCoords``` is doing a couple of wrong things, namely:
- copying ```e.changedTouches``` into ```this.touches``` on ```touchend``` means that we end up with touches in ```this.touches``` when we don't want any
- overwriting ```this.touches``` each time... not all touches are included in ```changedTouches```, e.g. touches that aren't moving

**Comment by lmccart** [comment]
thanks @kevinb7 these definitely sound like problems! :) do you want to submit a PR for this or I can take a look, let me know.

**Comment by kevinb7** [comment]
@lmccart I'm pretty swamped at the moment.  If you have some time to look at this it would be much appreciated.

**Comment by lmccart** [comment]
cool, will do

**Comment by karneaud** [comment]
bump

**Comment by hardmaru** [comment]
Thanks!

I tried digging around the touches code earlier but I'm afraid I'm not able
to solve and patch this myself

**Comment by lmccart** [comment]
closed with https://github.com/processing/p5.js/pull/609
