### ISSUE TITLE
contributor_docs/README.md and p5js website mention npm run grunt

### ISSUE THREAD

**Issue by devAyushDubey** [processing/p5.js#5872]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [X] Other (specify if possible)

### p5.js version

1.5.0

### Web browser and version

1.45.131 Chromium: 107.0.5304.110 (Official Build) (64-bit) 

### Operating System

Linux

### Steps to reproduce this

While setting up p5js for the first time:
### Steps:
1. Follow first 4 steps from Development Process from [contributor_docs/README.md](https://github.com/processing/p5.js/blob/main/contributor_docs/README.md) or [p5js website](https://p5js.org/contributor-docs/#/?id=development-process).
2. `5th` step mentions `npm run grunt`, which when executed results in missing script error as there is no `grunt` stage in the `"scripts"` property of [package.json](https://github.com/processing/p5.js/blob/main/package.json).

![image](https://user-images.githubusercontent.com/33064931/203779141-14ed7bad-09bf-4d43-9925-d1dbdfa76df7.png)

### Snippet:
Bash:
```
npm run grunt
```

![image](https://user-images.githubusercontent.com/33064931/203777785-694038f7-4e6c-465a-b143-c39f09b5cfbd.png)

In package.json:
```json
"scripts": {
    "build": "grunt build",
    "dev": "grunt yui browserify:dev connect:yui watch:quick",
    "docs": "grunt yui",
    "docs:dev": "grunt yui:dev",
    "test": "grunt",
    "lint": "grunt lint",
    "lint:source": "grunt lint:source",
    "lint:samples": "grunt lint:samples",
    "lint:fix": "grunt lint-fix",
    "contributors:add": "all-contributors add",
    "contributors:generate": "all-contributors generate",
    "generate": "all-contributors generate",
    "release": "grunt release-p5",
    "prepublishOnly": "grunt prerelease"
  }
```
`grunt` named stage is missing here in scripts property.

**Comment by limzykenneth** [comment]
Sorry the info in the README is a bit outdated and redundant, I'll have to find an hour or two to finish up #5841 which will address this. [This section](https://github.com/processing/p5.js/blob/main/contributor_docs/README.md#source-code-contribution) and where it links to is the latest information regarding setup and development process.

**Comment by devAyushDubey** [comment]
Oh okay! Thanks @limzykenneth , do let me know if I could help you in any of that I would be more than happy 😄.
