### ISSUE TITLE
strokes disappear when culling is enabled

### ISSUE THREAD

**Issue by titoasty** [processing/p5.js#5877]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

1.4.0

### Web browser and version

Chrome 107.0.5304.121

### Operating System

Ubuntu 22.04

## Steps:
1. open sketch here: https://editor.p5js.org/nicoboo/sketches/0h8fiYJfm
2. strokes does not show because culling is enabled
3. now disable culling (comment line 7)
4. strokes are visible but the wrong faces are visible

I think it could probably be easily solved by disabling culling when drawing strokes, then reenabling it (or not, depending on the current state) before drawing the filled version.
Maybe a curStrokeCull/curFillCull? Similar to curStrokeColor/curFillColor?

**Comment by davepagurek** [comment]
Thanks for finding this!

> I think it could probably be easily solved by disabling culling when drawing strokes, then reenabling it (or not, depending on the current state) before drawing the filled version.

I agree, this is probably the way to go. Until/unless we have a p5 API for setting culling, I think we'll just have to record `gl.isEnabled(gl.CULL_FACE)` to a local variable before drawing strokes, then disable culling, then set it back afterwards.
