### ISSUE TITLE
add fog

### ISSUE THREAD

**Issue by titoasty** [processing/p5.js#5878]
### Increasing Access

Unsure

### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### Feature request details

Hi,

Would it be possible to add fog for WebGL rendering?

I tried adding it by hijacking some methods, here's how I did it:
[https://github.com/titoasty/p5.js-boost/blob/main/fog.js](https://github.com/titoasty/p5.js-boost/blob/main/fog.js)
(it adds the function fog(r, g, b, start, end))

And the shader, based of phong.frag:
[https://github.com/titoasty/p5.js-boost/blob/main/assets/shaders/phongFog.frag](https://github.com/titoasty/p5.js-boost/blob/main/assets/shaders/phongFog.frag)

The shader code comes from here: [https://github.com/hughsk/glsl-fog](https://github.com/hughsk/glsl-fog)

Thanks!

**Comment by Qianqianye** [comment]
The p5.js community has made a commitment to only add features to p5.js that [expand access](https://github.com/processing/p5.js/blob/main/contributor_docs/access.md). Could you please add an access statement to the feature request? Thank you!

**Comment by harveymoon** [comment]
Hey just chiming in here. 
Fog in 3D rendering can be a graceful trick to improve performance.
By clipping the camera view to a certain distance, you can render fewer polygons and improve performance and access to 3d works from less powerful computers. 
Fog is a graceful way of hiding this clipping distance and making it feel more natural.

**Comment by Qianqianye** [comment]
Thanks @harveymoon and @davepagurek. I'm inviting more webGL stewards to this discussion @stalgiag, @aferriss, @kjhollen, @ShenpaiSharma, @calebfoss. Would love to hear what you think!

**Comment by davepagurek** [comment]
For organizational purposes, I'm going to close this issue in favour of https://github.com/processing/p5.js/issues/6144: Ideally, we will try to keep our core material fairly small, and built in a way where it is feasible for more rendering features to be added by plugins.
