### ISSUE TITLE
CDN does not serve as application/javascript

### ISSUE THREAD

**Issue by ednl** [processing/p5.js#5888]
### Most appropriate sub-area of p5.js?

- [X] Core/Environment/Rendering
- [X] Other: CDN link from P5js website does not work in all circumstances

### p5.js version

1.5.0

### Web browser and version

Safari 16.1 (18614.2.9.1.12)

### Operating System

macOS Ventura 13.0.1 (22A400)

### Steps:
1. Create local index.html file.
2. Use new "cdnjs.com" CDN link from https://p5js.org/download/
3. Open local file directly in browser.
4. None of the javascript code will be executed.

I haven't checked if this is also an issue when the index.html file is served via a (local or remote) webserver. I guess that depends on the webserver, specifically on whether the "nosniff" option is set in the webserver config (see error below).

### Error:
Because the javascript file is served as "text/plain", it is not executed. Error message from Javascript Console: "Refused to execute https://cdnjs.com/libraries/p5.js as script because "X-Content-Type-Options: nosniff" was given and its Content-Type is not a script MIME type."

### Solution:
Cdnjs.com should serve ".js" files with a Content-Type of "application/javascript" instead of "text/plain".

### Workaround:
Use the old Cloudflare CDN link: https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.5.0/p5.min.js which still works and does come with the right Content-Type.

### Snippet:
```html
<script src="https://cdnjs.com/libraries/p5.js"></script>
```

**Comment by davepagurek** [comment]
Does this also happen if you run a local webserver? e.g. with `python3 -m http.server` from the directory of your file, then opening localhost:8000? It might be that the content type restrictions are stricter for file:// URLs.

Also, this might be worth reporting to cdnjs directly, it looks like they've responded quickly to things like this in the past: https://github.com/cdnjs/cdnjs/issues/1707

**Comment by ednl** [comment]
@davepagurek Oh sorry, yes, same problem. I said I hadn't tested it, and I didn't, because I thought the "X-Content-Type-Options: nosniff" header would be in the request, not the response. But it's in the response! So yeah, probably worth asking cdnjs. Thanks.
