### ISSUE TITLE
p5.js Contributors Conference at CMU

### ISSUE THREAD

**Issue by lmccart** [processing/p5.js#589]
Hi everyone,

We are holding the first ever p5.js Contributors Conference at the CMU STUDIO for Creative Inquiry May 25-31! Complete info here: http://bit.ly/p5concon.

Whether you’re a developer, designer, writer, educator, or somewhere in between, we welcome individuals with all backgrounds, skills, and styles to come together and get creative. It will be a code sprint, documentation sprint, and unique gathering dedicated to p5.js. Together we will work on all aspects of p5.js, including (but not limited to) new features, bug fixing, documentation, outreach, community, design, and internationalization. Travel (up to $400), food, and accommodations will be covered for participants.

If you're interested in joining us, please fill out the short application here: http://bit.ly/p5concon. __The deadline is Monday, April 13.__ Due to limited funds, we may not be able to bring everyone that applies. We will however have a couple video sessions for remote participants to join in.

The Frank-Ratchye STUDIO for Creative Inquiry at Carnegie Mellon University is an academic laboratory for atypical, anti-disciplinary, and inter-institutional research at the intersections of arts, science, technology, and culture. This event is supported by a grant from the National Endowment for the Arts, with additional support from the Processing Foundation and the NYU Interactive Telecommunications Program.

Please forward to others you think may be interested. We are also looking for partners that may be interested in supporting or sponsoring the event. More info about this at the link.

Excited!

**Comment by jedahan** [comment]
Feature request for this conference: some sort of irc / slack / chat channel for those who can't attend but still want to help :)

**Comment by lmccart** [comment]
definitely! we will most likely be on IRC, more details as we get closer.

**Comment by taseenb** [comment]
sounds like you'll have a lot of fun! i'd really love to participate but it's too far.
by the way, i'll be at Resonate in Belgrade next week, and i saw you'll be giving a talk @lmccart.
i'll be there to listen of course! :) 

enjoy the conconf!

**Comment by hamoid** [comment]
I wish I could join, I'm teaching the summer semester... I'm looking forward to what comes out of it :)

**Comment by JobLeonard** [comment]
I have too much on my plate around that time as well. Any other options to follow what you will be cooking up that week beside IRC, like a livestream?

**Comment by lmccart** [comment]
still figuring it out, but we'll be sure to let you know! I'm sure there will be a lot of action here on the github repo, we are thinking about video options, as well.

**Comment by benhinchley** [comment]
could setting up a gitter channel be a good option??

**Comment by daytona1** [comment]
+1 for IRC/gitter/etc some of participating from afar!

**Comment by workergnome** [comment]
For all those interested in collaborating remotely, we're on IRC: `p5js` on irc.freenode.net

**Comment by lmccart** [comment]
you can also follow the hackpad here:
https://p5jscon.hackpad.com

**Comment by workergnome** [comment]
I don't know whether to applaud closing this (Congrats, @lmccart, on an amazing event!) or :crying_cat_face:.
