### ISSUE TITLE
Adding score to snake game

### ISSUE THREAD

**Issue by tumbledrylow** [processing/p5.js#5894]
### Topic

Hello Everyone,

I have also attached a link the my p5 sketch so the code can be better visualized 

https://editor.p5js.org/wmotlow5297/sketches/y68qMMGsy

I am trying to add a score tracker to the snake game I built on p5js using a Dan Shiffman video as a guide for this project. I am able to get the score to display, but it will either display NaN (not a number) or just add a "1" each time the snake eats a box. For example if the snake eats four boxes the score displays as 1111

I have attached the code below. 
The issue is in  if (snake.eat(food)){. When I add the parseInt to the code is when the score is displayed as NaN, and when I remove it is when it lists the number one for however many times the snake eats a box

**index.html file**

<!DOCTYPE html>
<html lang="en">
  <head>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.5.0/p5.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.5.0/addons/p5.sound.min.js"></script>
    <link rel="stylesheet" type="text/css" href="style.css">
    <meta charset="utf-8" />

  </head>
  <body>
    <p>Snake Game! Please select the difficulty level before beginning </p>
    <main>
    </main>
    <script src="snake.js"></script>
    
    <script src="sketch.js"></script>
  </body>
</html>

**sketch.js file**

// Snake game with addations. Base code is from Dan Shiffman

//https://www.youtube.com/watch?v=OMoVcohRgZA

// goal was to expand on this base code without help

let snake;
let rez = 20
let food;
let w;
let h;
let checkbox;
let checkbox2;
let checkbox3;
let scoreElem;

function setup() {
  scoreElem = createDiv('Score = ');  
  scoreElem.id = 'score';
  scoreElem.style('color', 'black');
  
  createCanvas(400, 400);
  w = floor(width / rez);
  h = floor((height) / rez);
  
  
  snake = new Snake();
  foodLocation();
  checkbox = createCheckbox('Easy', false);
  checkbox.changed(myCheckedEvent);
  checkbox2 = createCheckbox('Medium', false);
  checkbox2.changed(myCheckedEvent);
  checkbox3 = createCheckbox('Hard', false);
  checkbox3.changed(myCheckedEvent);
}

function myCheckedEvent() {
  if (checkbox.checked()) {
    frameRate(5);
  }
  if (checkbox2.checked()) {
    frameRate(10);
  }
  if (checkbox3.checked()) {
    frameRate(15);
  } 
}

function foodLocation() {
  let x = floor(random(w));
  let y = floor(random(h));
  food = createVector(x, y);
}

// function is called once every time a key is pressed
// https://p5js.org/reference/#/p5/keyPressed

// this function is connected to the arrow keyboard keys

function keyPressed(){
  if (keyCode === LEFT_ARROW){
    snake.setDir(-1, 0) // moves left on x axis
  } else if (keyCode === RIGHT_ARROW){
    snake.setDir(1, 0) // moves right on x axis
    
  } else if (keyCode === DOWN_ARROW){
    snake.setDir(0, 1) // moves down on y axis. 1 instead                        // of -1 bc in p5 sketch moving                            // down the canvas vertically is                          // increasing the value of y
    
  } else if (keyCode === UP_ARROW){
    snake.setDir(0, -1)  // moves up on y axis
  }
  else if (key == ' ') {
    fill(111);
    
    snake.grow();
  }
}

function draw() {
  scale(rez)
  background(255);
  frameRate(myCheckedEvent);
  
  
  if (snake.eat(food)){
    foodLocation();
    let r1 = random(0, 255) // I added this
    let r2 = random(0, 255) // I added this
    let r3 = random(0, 255) // I added this
    background(r1, r2, r3); // I added this
    const prevScore = (scoreElem.html().substring(8));
    // const prevScore = parseInt(scoreElem.html().substring(8));
    scoreElem.html('Score = ' + (prevScore + 1));
    console.log(prevScore)
    
  }
  snake.update(); // updates the snakes location every                       // frame
  snake.show(); //displays the snake
  // must have an update and a show in the snake.sj file     // for these to work
  
  if (snake.endGame()) {
    background(255, 0, 0);
    
    noLoop();
    const scoreVal = (scoreElem.html().substring(8));
    scoreElem.html('Game ended! Your score was : ' + scoreVal);
  }
  
  noStroke();
  fill(255, 255, 0);
  rect(food.x, food.y, 1, 1);
}

**snake.js file**
// this is a template for the snake object that will be made in the sketch.js file

class Snake {
  constructor() {
    
    this.body = []; // this needs to be an array because
                    // you want to keep track of a list of                     // all of its locations 
    this.body[0] = createVector(floor(w/2), floor(h/2)); 
                    // creates a vector object at the                         // location within the parentheses 
    this.xdir = 0;  // is the snake moving left or right?
                    // if you make this an interger other 
                    // than 0 the snake will move along                       // the x axis right or left
    this.ydir = 0;  // is the snake moving up or down?
                    // if you make this an interger other 
                    // than 0 the snake will move along                       // the y axis up or down
    this.len = 0;   // the lenght of the snake starts as 
  }
  
  setDir(x,y){
    this.xdir = x;
    this.ydir = y;
  }
  
  update(){
    let head = this.body[this.body.length-1].copy();
    this.body.shift();
    head.x += this.xdir;
    head.y += this.ydir;
    this.body.push(head);
    
    // this.body[0].x += this.xdir;
    // this.body[0].y += this.ydir;
  }
  
  
  // this means I want to expand the array
  grow() {
    let head = this.body[this.body.length-1].copy();
    
    this.len++;
    this.body.push(head);
    
  }
  
  endGame(){
    let x = this.body[this.body.length-1].x;
    let y = this.body[this.body.length-1].y;
    if (x > w-1 || x < 0 || y > h-1 || y < 0) {
      return true;
    }
    for (let i = 0; i < this.body.length-1; i++) {
      let part = this.body[i];
      if (part.x == x && part.y == y) {
        return true;
      }
    }
    return false;
  }
  
  eat(pos) {
    let x = this.body[this.body.length-1].x;
    let y = this.body[this.body.length-1].y;
    if (x ==pos.x && y == pos.y){
      this.grow();
      return true;
    }
    
    return false;
  }
  
  show(){
    for (let i = 0; i < this.body.length; i++) {
    fill(0);
    noStroke();
    rect(this.body[i].x,  this.body[i].y, 1, 1);
    }
  }
}

**style.css file**

html, body {
  margin: 0;
  padding: 0;
}
canvas {
  display: block;
}

Any advice on this issue would be greatly appreciated

**Comment by Qianqianye** [comment]
Hi, the GitHub issues here are a good place for bugs and issues with the p5.js library itself. For questions about writing your own code, tests, or following tutorials, the [forum](https://discourse.processing.org/c/p5js/10) is the best place to post. Thanks!
