### ISSUE TITLE
Request: changelog

### ISSUE THREAD

**Issue by JobLeonard** [processing/p5.js#590]
I occasionally come back to the p5.js website to see if the version number has increased - it often has, which isn't surprising given the amount of work that clearly is going into this project :).

The thing is that I can't find any announcements or changelogs or anything explaining what has changed, or why the version numbers were bumped up. Something like p5.js-sound would be nice.

https://github.com/processing/p5.js-sound/blob/master/changelog.md

**Comment by lmccart** [comment]
this information is included on the releases page
https://github.com/processing/p5.js/releases

**Comment by JobLeonard** [comment]
Ah, thank you! In that case, could it be linked from the p5.js webpage? Because it's not easily found.

**Comment by lmccart** [comment]
great idea, just added under ETC on the downloads page:
http://p5js.org/download/
