### ISSUE TITLE
Support CSS HSL color strings

### ISSUE THREAD

**Issue by kadamwhite** [processing/p5.js#591]
Opening this issue to track this as an outstanding to-do: Following #573 it would make sense to support `hsl()` and `hsla()` CSS color strings, to complete our support for native CSS colors. This can follow the same regex-based parsing pattern established in #573, but will require some color conversion logic because [HSL is not the same as HSB](http://en.wikipedia.org/wiki/HSL_and_HSV).

**Comment by sarahgp** [comment]
Clarification request: 

We currently support RGB integer & string values, plus HSB integer values but not strings, if I read [`p5.Color._getFormattedColor`](https://github.com/processing/p5.js/blob/master/src/objects/p5.Color.js#L348) & [`fill()`](http://p5js.org/reference/#/p5/fill) correctly. This issue specifies HSL strings.

Should we be supporting integer & string for all values? I assume yes, but I want to be sure I am not missing previous decisions.

**Comment by kadamwhite** [comment]
@sarahgp The CSS color specification, which is what I've been going off of for all string parsing, defines the following [valid string color identifiers](http://www.w3.org/TR/css3-color/#colorunits) *for CSS*:

- named CSS / SVG color strings e.g. `red`, `white`, `lightblue`, `lemonchiffon`
- hex color codes e.g. `#ffae00`
- `rgb( r, g, b )`
- `rgba( r, g, b, a )`
- `rgb( r%, g%, b% )`
- `rgba( r%, g%, b%, a )`
- `hsl( h, s%, l% )`
- `hsla( h, s%, l%, a )`

My stance is that we should support all string values that are valid CSS color identifiers; to that end I do not think we should support HSB strings, because HSB is not a valid CSS color identifier.

The main rationale for this stance is that the first thing I did, as a web developer sitting down to use P5, was to try to write `fill( 'red' )`: at the time, it did not work, prompting my desire for us to support web-native color identifiers (which are part of the CSS spec).

**Comment by sarahgp** [comment]
:100:

**Comment by lmccart** [comment]
@sarahgp is this one all set to close now, aside from issues that have been broken out?

**Comment by sarahgp** [comment]
@lmccart Yep!
