### ISSUE TITLE
curveTightness bug (with a proposed fix)

### ISSUE THREAD

**Issue by zacharystenger** [processing/p5.js#592]
I noticed [curveTightness](http://p5js.org/reference/#/p5/curveTightness) was throwing the error message 'Uncaught not yet implemented'.  I looked into the p5 source code and found this around lines 4860-4880
```javascript
p5.prototype.curveTightness = function (t) {
    this._setProperty('_curveTightness', t);
};
.
.
.
p5.prototype.curveTightness = function () {
    throw 'not yet implemented';
};
```
I think p5 is always using the parameterless function because it comes a few lines after the curveTightness function that has a parameter.  
  
I am proposing a change where we get rid of the parameterless function and modify the other function to deal with an empty parameter like this:
```javascript
p5.prototype.curveTightness = function (t) {
    if(t === undefined) t = 0;
    this._setProperty('_curveTightness', t);
};
```
Here are examples of curveTightness with this fix: [with a parameter aka the example on p5js.org](http://goo.gl/mry7kq) and [an example with no parameter](http://goo.gl/uKk7o5). 
Please let me know if this looks right and I can create the pull request.

**Comment by lmccart** [comment]
woops, yes, looks like that second definition should be removed completely, it was just a leftover duplicate. I think we can leave the other function as is, no need to check if t is undefined. in most cases with things like this, we just assume the user is calling the method properly.

do you want to submit a pr to remove the second curveTightness definition?

**Comment by zacharystenger** [comment]
Sure.
