### ISSUE TITLE
make saveGif's third argument even more optional

### ISSUE THREAD

**Issue by bleything** [processing/p5.js#5927]
### Increasing Access

maybe a bit of a stretch, but: improving/streamlining APIs makes them more accessible to folks who may not yet have the experience to understand what the error messages are saying and how to resolve them

### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [X] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [X] Friendly Errors
- [ ] Other (specify if possible)

### Feature enhancement details

`saveGif` currently accepts an optional third argument in the form of an object with `delay` and `unit` keys. If you pass that object with only one of those keys defined (e.g. if you're trying to override delay but leave units alone, or vice versa) then you get an error message complaining about the format of the key you _didn't_ pass:

```
saveGif("loop.gif", 600, {"delay": 40})
=> TypeError: Units parameter must be either "frames" or "seconds"

saveGif("loop.gif", 600, {"unit": "seconds"})
=> TypeError: Delay parameter must be a number
```

In the first example I'm passing the `delay` key but getting an error message about units. In the second, passing `unit` but getting an error about delay.

The docs state that the default value for `unit` is seconds. The default for `delay` is not documented but the code shows it to be 0. Since both keys have defaults, I propose altering that function so that it will accept an object with only one of the keys defined.

**Comment by davepagurek** [comment]
This makes sense, and would be a well-scoped change!

In this area https://github.com/processing/p5.js/blob/1246fc26daf558522a60b693b4e0059027aae8b4/src/image/loading_displaying.js#L232-L248 we would need to change it to something like:

```js
const delay = (options && options.delay) || 0
const units = (options && options.units) || 'seconds'
```

If anyone is interested in taking this on and would like some more guidance, feel free to comment and let me know!

**Comment by Neilblaze** [comment]
@davepagurek I'd love to take a shot. I've built a few hobby sketches with p5.js, but I still consider myself a newbie, so I might trouble you a bit on discord 😄

**Comment by gaurav8y785675474** [comment]
hello
i am new here
please tell me in which file this issue exists

**Comment by davepagurek** [comment]
Hi @gaurav8y785675474, thanks for your interest! @Neilblaze has made a pull request that handles this issue. If you're interested in following along, you can look at the PR here https://github.com/processing/p5.js/pull/5931 and go to the Files Changed tab to see where the fix was made 🙂
