### ISSUE TITLE
Simplex noise implementation

### ISSUE THREAD

**Issue by SanzSeraph** [processing/p5.js#5932]
### Topic

Has there been any discussion of adding a simplex noise implementation to the core library?

**Comment by davepagurek** [comment]
Maybe something like this could first start out as a library for p5? Something like a port of https://github.com/CodingTrain/OpenSimplexNoise-for-Processing but for p5

**Comment by limzykenneth** [comment]
As @davepagurek mentioned, this will likely be more suitable for an addon library, at least to start with, possibly even built into one of the existing addon library that deals with mathematical functions. 

Additionally adding simplex noise functionality into p5.js would be considered a [feature request](https://github.com/processing/p5.js/blob/main/contributor_docs/contributor_guidelines.md#new-feature-request) and the relevant issue template should be used instead with the case for increasing access made. But again, it is more straightforward to start with an addon library first and inclusion in the core library can be brought up later.

I'm closing this for now but feel free to continue the discussion here.
