### ISSUE TITLE
korea languge web page arc()  function option Explanation

### ISSUE THREAD

**Issue by leejuha** [processing/p5.js#5934]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [X] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

web page

### Web browser and version

chrome 버전 108.0.5359.125(공식 빌드) (64비트)

### Operating System

windows 11

### Steps:
1. There is a typo in the website description.   ---korea language page
    https://p5js.org/ko/reference/#/p5/arc
2.  befor :   mode 상수: (선택 사항) 호를 그리는 방식들로, CHORD, PIEC, OPEN 중 선택 가능
3.  tobe : mode 상수: (선택 사항) 호를 그리는 방식들로, CHORD, PIE, OPEN 중 선택 가능
                                                                                   --->option PIEC ->PIE   change

### Snippet:
PIEC ->PIE   change     arc.js

// Paste your code here :)
mode 상수: (선택 사항) 호를 그리는 방식들로, CHORD, PIE, OPEN 중 선택 가능

**Comment by Qianqianye** [comment]
Thanks @leejuha. I am tagging @almchung to take a look at this.

**Comment by almchung** [comment]
Hi @leejuha, I agree there is a typo on the Korean reference page. Please go ahead and submit a pull request. Thank you!
