### ISSUE TITLE
Coexistence of lighting shader and per-vertex coloring

### ISSUE THREAD

**Issue by inaridarkfox4231** [processing/p5.js#5936]
### Increasing Access

Currently, if you call a function that uses lightingShader such as pointLight() in immediateMode, per-vertex coloring will not work and it will be coloring with a single color. for example:

[sampleCode (p5.Editor)](https://editor.p5js.org/dark_fox/sketches/NX3A-jl0-)
```javascript
function setup() {
  createCanvas(400, 400, WEBGL);
  noStroke();
  
  //pointLight(0, 255, 255, 0, 0, 30);

  beginShape();
  fill(255);
  vertex(-100,-100);
  fill(255,0,0);
  vertex(100,-100);
  fill(0,255,0);
  vertex(100,100);
  fill(0,0,255);
  vertex(-100,100);
  endShape();
}
```
![compare_perVertexColor](https://user-images.githubusercontent.com/39549290/210822964-53669825-e952-447a-9419-4a817ce4ad3d.png)
If you enable pointLight by uncommenting "pointLight()", the image will look like the one on the right and the per-vertex coloring method will not be applied. Only the blue color, registered with fill() at the end, will be used.

If applied, it should look like this:
![expected_2](https://user-images.githubusercontent.com/39549290/210824355-336e6fcc-a4c5-460b-ab58-b6548ed7f0c5.png)

Another problem is that when using p5.Geometry, you can store color information in an array called "vertexColors", but there is no defaultShader that uses it.
I would like to solve these problems.

### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [X] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### Feature enhancement details

First, add the flag "_useVertexColor" and the default shader "_defaultVertexColorShader" to rendererGL.
```javascript
this._useVertexColor = false:
this._defaultVertexColorShader = undefined;
```

_useVertexColor is determined by whether the length of the geometry's vertexColors is positive:
immediateMode:
```javascript
p5.RendererGL.prototype._drawImmediateFill = function () {
  var gl = this.GL;
  this._useVertexColor = (this.immediateMode.geometry.vertexColors.length > 0); // determine frag
  var shader = this._getImmediateFillShader();
  this._setFillUniforms(shader);
  etc..
```
retainedMode:
```javascript
if (this._doFill) {
  this._useVertexColor = (geometry.model.vertexColors.length > 0); // determine frag
  var fillShader = this._getRetainedFillShader();
  this._setFillUniforms(fillShader);
  etc...
```

Set _useVertexColor to uUseVertexColor in _setFillUniform.
```javascript
p5.RendererGL.prototype._setFillUniforms = function (fillShader) {
  fillShader.bindShader(); // TODO: optimize
  fillShader.setUniform('uUseVertexColor', this._useVertexColor); // set flag.
```

Modify where retainedMode gets _defaultColorShader so that when _useVertexColor is ON, vertex coloring shader created from "vertexColorVert" and "vertexColorFrag" will be used.
```javascript
p5.RendererGL.prototype._getColorShader = function () {
  if (!this._defaultColorShader) {
    this._defaultColorShader = new _main.default.Shader(this, defaultShaders.normalVert, defaultShaders.basicFrag);
  }
  // If _useVertexColor is ON, use the per-vertex coloring shader.
  if (!this._defaultVertexColorShader) {
    this._defaultVertexColorShader = new _main.default.Shader(this, defaultShaders.vertexColorVert, defaultShaders.vertexColorFrag);
  }
  if (this._useVertexColor) return this._defaultVertexColorShader;
  return this._defaultColorShader;
};
```

Finally, modify the lightingShader.
Change the uMaterialColor of uniform in phongFrag and lightTextureFrag to vColor of varying.
Then add vColor of varying, uMaterialColor of uniform, uUseVertexColor of uniform, and aVertexColor of attribute to phongVert and lightVert so that vColor becomes aVertexColor or uMaterialColor according to ON/OFF of uUseVertexColor.
```glsl
varying vec4 vColor;
uniform bool uUseVertexColor;
uniform vec4 uMaterialColor;
attribute vec4 aVertexColor;

vColor = (uUseVertexColor ? aVertexColor : uMaterialColor);
```
Now per-vertex coloring should work even if lightingShader is used.

**Comment by davepagurek** [comment]
Agreed, it's unexpected that turning on lighting causes vertex colors to be ignored.

I wonder if we need to add a new shader with `vertexColorVert` and `vertexColorFrag`, or if we can just edit the existing shaders to optionally support vertex colors? Does anything break if we just use the existing shaders modified in the way you describe without adding `_defaultVertexColorShader`? It's maybe a bit more efficient having shaders that do less, but the tradeoff is higher surface area for bugs when there is functionality spread across many shaders, so it might be nicer if we can keep the logic for switching shaders the same. (Only if that actually works though!)

I think that would mean testing beginShape()/endShape(), geometry without vertex colors, and geometry with vertex colors, all with and without lights turned on.

**Comment by inaridarkfox4231** [comment]
I was wondering which way to do it, but since vertexColorVert was not used, I wondered if I could use it... But if that's the case, I'll rewrite it. In that case, we should calculate vColor with normalVert and send it to basicFrag. I will try to rewrite it!
Also, I would like to add a proper unit test.
