### ISSUE TITLE
p5.Camera : setPosition and Move do not maintain camera orientation

### ISSUE THREAD

**Issue by quarks** [processing/p5.js#5943]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

v1.5.0

### Web browser and version

Firefox version  	108.0.2

### Operating System

masOSX 12.6.1

### Steps to reproduce this

In the p5.Camera class the methods `setPosition` and `move` do not maintain the camera orientation. Instead they assume that the camera orientation (up vector) is [0, 1, 0] even if previously changed by the user.

The code below demonstrates this problem

```js
function setup() {
  createCanvas(480, 320, WEBGL);
  let eyeZ = (height/2)/tan(PI/6);
  console.log(eyeZ);
  let cam = createCamera();
  console.log(camToString(cam, 'Default camera'));
  cam.camera(0, 0, eyeZ, 0, 0, 0, 0, 0, -1);
  console.log(camToString(cam, 'Change camera up direction to [0, 0, -1]'));
  cam.setPosition(0, 0, 500);
  console.log(camToString(cam, 'Change camera position'));
  cam.camera(0, 0, eyeZ, 0, 0, 0, 0, 0, -1); // restore
  cam.move(0,0,100);
  console.log(camToString(cam, 'Move camera'));
}

function camToString(c, title = '') {
  let s = `Camera: ${title} \n`;
  s+= `   Position: [${c.eyeX}, ${c.eyeY}, ${c.eyeZ}]\n`;
  s+= `   LookAt  : [${c.centerX}, ${c.centerY}, ${c.centerZ}]\n`;
  s+= `   Up      : [${c.upX}, ${c.upY}, ${c.upZ}]\n`;
  s+= '------------------------------------------------------------------';
  return s;
}

```

Although not a bug I have another related issue with the `createCamera` method which has a negative impact  when creating multiple cameras. This is discussed further in [issue 5941](https://github.com/processing/p5.js/issues/5941).

**Comment by Prateek462003** [comment]
if no one is working on this issue I would like to make a quick PR
