### ISSUE TITLE
endContour() throws error in WEBGL mode

### ISSUE THREAD

**Issue by davepagurek** [processing/p5.js#5946]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

1.5.0

### Web browser and version

Firefox 108.0

### Operating System

MacOS 12.5.1

### Steps to reproduce this

Currently, if you add a `createCanvas(100, 100, WEBGL)` to the start of the [`beginContour` example in the docs](https://p5js.org/reference/#/p5/beginContour), we get an type error in `endContour`: `d[0] is undefined`.

We're able in theory to support this in `beginShape(TESS)` mode (the default on the main branch currently) by supplying multiple contours to libtess. I have an example of using that to extrude text in 3D in https://openprocessing.org/sketch/1721124 on `extrudeText:52` and it triangulates the cutouts correctly, so implementing this would be a matter of mapping `begin/endContour` shapes to an array in the parameters of our `_triangulate` call.

**Comment by aditya-shrivastavv** [comment]
### According to documentation

createCanvas method should be called only once at the start of setup(). Calling createCanvas more than once in a sketch will result in very unpredictable behavior. If you want more than one drawing canvas you could use createGraphics() | [Link](https://p5js.org/reference/#/p5/createCanvas)

another point i could think of is that createCanvas() is a function from the p5.js library, and beginContour() is a function from the p5.js WebGL library. They are different libraries and need to be used with the corresponding mode (either 2D or WEBGL) specified in the createCanvas()

**Comment by davepagurek** [comment]
@aditya-shrivastavv for clarification, I'm suggesting _replacing_ the existing  2D `createCanvas` call with the WebGL one.

While `beginContour` is currently only functional in 2D mode, it is not documented as such. We're hoping that we can eventually get this implemented in WebGL mode to match the feature set of 2D mode to increase predictability for new users of WebGL mode.

**Comment by aditya-shrivastavv** [comment]
Please assign this issue to me, I want to work on this

**Comment by davepagurek** [comment]
Thanks @aditya-shrivastavv! I'll assign this one to you.
