### ISSUE TITLE
Semitransparent strokes disabled in WebGL mode

### ISSUE THREAD

**Issue by davepagurek** [processing/p5.js#5951]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [X] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

1.5.0

### Web browser and version

Firefox 108.0

### Operating System

MacOS 12.5.1

### Steps to reproduce this

Noticed this one after someone on the p5 discord was asking about it.

In this bit of code, we make WebGL strokes fully opaque: https://github.com/processing/p5.js/blob/00821f33ca1d8a6990364568f0374c4aaf713faa/src/webgl/p5.RendererGL.js#L670-L672

Are we able to remove this without causing any bugs? To test it, one can wrap color arguments in `color`, e.g. `stroke(color(0, 255, 0, 50))`. If not, maybe we should document this, as it currently can leave people wondering what they're doing wrong when switching from 2D to WebGL mode.

**Comment by Prateek462003** [comment]
@davepagurek i would like to work on this issue

**Comment by davepagurek** [comment]
Thanks @Prateek462003! I'll assign this to you.
