### ISSUE TITLE
Turkish Language

### ISSUE THREAD

**Issue by 900ugurgunes** [processing/p5.js#5955]
### Increasing Access

I want to add Turkish language support to the project. The JSON file is complete.

### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [X] Other (specify if possible)

### Feature request details

translation

**Comment by Qianqianye** [comment]
Hi @900ugurgunes! Regarding p5.js translation, we are rolling out new languages slowly to be absolutely sure that we can support the full translation and maintenance of each language. We want to avoid the situation where we have many languages and it's beyond our means to support. So for this reason, we are holding now with Spanish, Chinese, Korean, and Hindi and getting those fully complete before we take on others.

 If we begin with the language you’ve proposed, we will certainly be in touch. However, we very much welcome translations that are hosted elsewhere. Currently, we have two [externally hosted language versions](https://github.com/processing/p5.js-website#externally-hosted-language-versions) (Japanese and French) listed on p5.js-website GitHub repo. Please feel free to translate any of the website content and host it on an external blog or site. All of the website content is licensed under Creative Commons which makes it possible to reuse this content for non-commercial purposes if it is credited. We would be happy to share links and make connections so others can find and use this material. Hope this makes sense to you, and I will close the PR for organizational purpose. Thank you!
