### ISSUE TITLE
Using 3D, rotationX, Y and Z are all null. According to the Ref, they should be numbers between -180 and 180.

### ISSUE THREAD

**Issue by ChristerNilsson** [processing/p5.js#5957]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

v1.5.0 October 18, 2022

### Web browser and version

Chrome: 109.0.5414.74

### Operating System

W10 Home 19045.2486

### Steps:
1. setup: Create the WEBGL canvas
2. draw: Log rotationX
3. Run, turn the 3D world with your mouse
4. null printed

**Comment by ChristerNilsson** [comment]
```c
function setup() {
    createCanvas(500, 500, WEBGL)
}
 
function draw() {
    background("#000")
    orbitControl(4, 4)
    rotateX(1)
    rotateY(1)
    rotateZ(1)  
    console.log(rotationX,rotationY,rotationZ)
    box(100, 100, 100)
}
```

**Comment by davepagurek** [comment]
I tried out the example code on Firefox and Chrome for Mac and 0,0,0 is logged instead of null. Perhaps this means it's a Chrome for Windows issue?

**Comment by ChristerNilsson** [comment]
I can confirm 0,0,0 is returned in FireFox. But, I was turning to 1,1,1 in radians.
So, a small step forward, but still unusable.
(please note, you can turn the cube using mouse drag.)

**Comment by davepagurek** [comment]
> please note, you can turn the cube using mouse drag

Oh, were you expecting is to log different values based on orbit control? I believe rotationX/Y/Z uses data from your device's accelerometer, and not the camera.

While p5 doesn't currently have a way to extract the rotation, it can be accessed in a sketch via `_renderer.uMVMatrix.mat4`. Using the [gl-matrix library](https://glmatrix.net/docs/module-mat4.html), one can get a quaternion representing the current rotation with `const quat = mat4.getRotation(quat.create(), _renderer.uMVMatrix.mat4)`. From there, there is a `quat.getAxisAngle(out_axis, input_quat)` method one can use to get the angle.

**Comment by ChristerNilsson** [comment]
You a completely right! I missed "device".
