### ISSUE TITLE
3D orbitControl allowing +-90 degrees not enough.

### ISSUE THREAD

**Issue by ChristerNilsson** [processing/p5.js#5958]
### Increasing Access

It would be nice to be able to observe an object from ALL angles.

### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### Feature enhancement details

I'm rotating a Rubik's cube and I can't turn to all angles. I would like to have the position in the image available for all top colors. I can only get the blue color on top, unfortunately. Maybe this is unsolvable, considering the mouse only has two dimensions. In that case, maybe the scroll wheel could be used for the third dimension.
Turning the cube upside down is impossible. (The blue face downwards)

![Capture](https://user-images.githubusercontent.com/3437195/212659543-7fb31f53-d050-4509-8363-6d41076171eb.JPG)

```c
function setup() {
    createCanvas(500, 500, WEBGL)
}
 
function draw() {
    background("#000")
    orbitControl(4, 4)
    rotateX(1)
    rotateY(1)
    rotateZ(1)  
    console.log(rotationX,rotationY,rotationZ)
    box(100, 100, 100)
}
```

**Comment by davepagurek** [comment]
Your use case makes sense, thanks for reporting this! In the mean time, maybe try using the p5.EasyCam library as an alternative form of orbit control: https://github.com/freshfork/p5.EasyCam

**Comment by AryanKoundal** [comment]
@davepagurek Can I start working on this?

**Comment by davepagurek** [comment]
Thanks @AryanKoundal! I'll assign this to you.
