### ISSUE TITLE
eslint problem in windows

### ISSUE THREAD

**Issue by aditya-shrivastavv** [processing/p5.js#5971]
Opening this issue because i faced it and also mentioned by @limzykenneth in https://github.com/processing/p5.js/pull/5792#issuecomment-1354543512

I am a windows 11 user, when i installed the **ESLint** extention in **VS Code**. I saw that any JS file i open was highligthed in red.
example -

![image](https://user-images.githubusercontent.com/81470938/214225821-3bf60f31-ca29-42f0-8600-68686a997232.png)
---
I also have **Prettier** extention installed. I am not sure if that is causing any problem.
The most simple solution i found for myself was to change "unix" to "windows" but i also know that this will cause problems in other operating systems.
https://github.com/processing/p5.js/blob/69702de9f245b2b960fa24f127e5e3b2b3d21ecc/.eslintrc.json#L49
I think we need to modify it such that it works fine in all the operating systems. One solution mentioned on [ESLint Website](https://eslint.org/docs/latest/rules/linebreak-style#using-this-rule-with-version-control-systems) was to use `*.js text eol=lf`.
I don't know what it means so i invite experienced developers to see this.

## Possible solutions I found on the web
- https://eslint.org/docs/latest/rules/linebreak-style
- https://stackoverflow.com/questions/37826449/expected-linebreaks-to-be-lf-but-found-crlf-linebreak-style

## Some related threads 
- https://github.com/processing/p5.js/pull/2431
- https://github.com/processing/p5.js/pull/5792#issuecomment-1352489350
- https://github.com/processing/p5.js/pull/2484

**Comment by aditya-shrivastavv** [comment]
Another solution i found that in vscode we can directly select which end of line sequence we want CRLF or LF

![image](https://user-images.githubusercontent.com/81470938/214268734-6f75b1da-5641-47d1-87b8-51f41971c619.png)

if i select LF all my errors vanished.

**Comment by limzykenneth** [comment]
We exclusively use LF for p5.js' codebase and not CRLF. As you have found, the errors you are seeing is due to your text editor automatically converting LF to CRLF while eslint and git wants otherwise.

In the root of the repo there it a `.editorconfig` file which is meant to be a cross platform way of automatically setting line endings and other related settings in text editors to match project settings. I'm not sure if you need to install an additional plugin for VSCode for it to read that file though. In any case we won't be changing the line endings to CRLF for p5.js.

**Comment by aditya-shrivastavv** [comment]
Just noticed that there is a `.editorconfig` file in the project, It is meant to override user/workspace settings. For this file to work a VS Code extention must be downloaded [EditorConfig for VS Code](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig).

This should automatically solve all EOL related issues
