### ISSUE TITLE
orientation of triangle geometry is opposite

### ISSUE THREAD

**Issue by inaridarkfox4231** [processing/p5.js#5977]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

1.5.0

### Web browser and version

Chrome

### Operating System

Windows11

### Steps:
1. Draw a triangle with the triangle function in p5.js webgl.
2. When doing so, make sure the vertices are clockwise and apply lighting. The light should be in the negative z-axis direction.
3. It doesn't get brighter because it has negative normals.

### Snippet:

```js
function setup(){
  createCanvas(400, 400, WEBGL);
  directionalLight(255, 255, 255, 0, 0, -1);
  ambientLight(64);
  ambientMaterial(255);
  fill(255, 128, 0);
  triangle(0, 0, 200, 0, 200, 200);
}
```
![tri1](https://user-images.githubusercontent.com/39549290/214992397-9d148860-73ba-411e-aa4e-86dcb34de058.png)

If you specify the same in immediate mode, the normal will normally be in the positive direction
```js
function setup(){
  createCanvas(400, 400, WEBGL);
  directionalLight(255, 255, 255, 0, 0, -1);
  ambientLight(64);
  ambientMaterial(255);
  fill(255, 128, 0);
  beginShape();
  vertex(0, 0);
  vertex(200, 0);
  vertex(200, 200);
  endShape();
}
```
![tri2](https://user-images.githubusercontent.com/39549290/214992823-d8f77022-d721-453a-8f74-9b1a861f21ee.png)
This is probably because the order of specifying the vertices is reversed when creating the geometry.

**Comment by inaridarkfox4231** [comment]
I accidentally committed to my main. Excuse me.

**Comment by davepagurek** [comment]
Thanks for finding this! Agreed, this should be the reverse in order to be consistent with all the other shapes.
