### ISSUE TITLE
No need to specify 255 as the fourth argument in stroke()

### ISSUE THREAD

**Issue by inaridarkfox4231** [processing/p5.js#5988]
### Topic

Currently(p5.js/1.5.0), stroke() is being processed to specify 255 as the fourth argument.
```javascript
p5.RendererGL.prototype.stroke = function (r, g, b, a) {
  //@todo allow transparency in stroking currently doesn't have
  //any impact and causes problems with specularMaterial
  arguments[3] = 255;
  var color = _main.default.prototype.color.apply(this._pInst, arguments);
  this.curStrokeColor = color._array;
};
```
This seems to be a process that always sets the transparency of the line to 1, but it is a meaningless process. Because you can achieve line transparency like this:
```javascript
function setup() {
  createCanvas(400, 400, WEBGL);
  background(0);
  strokeWeight(32);
  stroke(color(0, 128, 255, 128));
  noFill();
  beginShape();
  vertex(-100, -100);
  vertex(100, -100);
  vertex(100, 100);
  vertex(-100, 100);
  endShape(CLOSE);
}
```
![trapLine](https://user-images.githubusercontent.com/39549290/216057636-9e7d5bdd-12dc-474f-948a-1a3513cee460.png)
(However, it seems that strokeJoin will be implemented, so it will look different in the next version.)
This is because if there are two or fewer arguments, the third and subsequent arguments are ignored.
Therefore, you can draw a transparent line even if you pass two arguments as follows.
```javascript
function setup() {
  createCanvas(400, 400, WEBGL);
  background(0);
  strokeWeight(32);
  stroke(64, 64);
  line(-100, -100, 100, -100);
  stroke(64, 64, 64);
  line(-100, 100, 100, 100);
}
```
![trpline2](https://user-images.githubusercontent.com/39549290/216060632-bc078a65-e836-4092-9183-c16295ffe258.png)
I don't know why p5.js has to set the line opacity to 1 in webgl, and it's not something to discuss here, but if p5.js wants to achieve this, the resulting color object should set the alpha value with setAlpha().
Or it can be more easily realized if the 4th component is set to 1 when setting curStrokeColor.

However, it was decided that this specification will be abolished in the previous pull request([#5985](https://github.com/processing/p5.js/pull/5985)). At that time, the code to set to 255 remained.
```javascript
p5.RendererGL.prototype.stroke = function(r, g, b, a) {

  if(arguments[3] === undefined){
    arguments[3] = 255;
  }

  const color = p5.prototype.color.apply(this._pInst, arguments);
  this.curStrokeColor = color._array;
};
```
This is unnecessary processing. because it is ignored if there are less than 2 arguments. In the case of 3, the maximum value is automatically set if nothing is specified. For four, it goes without saying.
(To be more specific, there is no guarantee that 255 is the maximum alpha value.)
If the user doesn't explicitly specify alpha, the process for color has already been implemented, so I think this should be omitted.

**Comment by davepagurek** [comment]
Makes sense, I think we can take out that if statement then.
