### ISSUE TITLE
Failed to execute 'putImageData' on 'CanvasRenderingContext2D': parameter 1 is not of type 'ImageData'

### ISSUE THREAD

**Issue by karneaud** [processing/p5.js#599]
I'm trying to manipulate the pixels of a p5.Video by creating a p5.Image from the p5.Video.pixels. However when i try...

` video.loadPixels();
 var img = new p5.Image(video.width,video.height);
 img.pixels = video.pixels;
 img.updatePixels();`

I get the subject error. I am creating the image from video frame in order to manipulate the pixels then draw the manipulated pixels to the canvas.

**Comment by lmccart** [comment]
try calling `img.loadPixels()` first

**Comment by karneaud** [comment]
Gotcha! Works however doesn't seem to be rendering so i suspect that the data from the video isn't being captured. am i doing this correctly though? Can i manipulate a video frame before drawing it to canvas?
