### ISSUE TITLE
Text displays very wrong or not at all when using rectMode(CENTER)

### ISSUE THREAD

**Issue by greenStone83** [processing/p5.js#5996]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [X] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

1.5.0

### Web browser and version

Firefox 109.0.1

### Operating System

Windows 10

### Steps to reproduce this

Step 1: use rectMode(CENTER)
Step 2: use textAlign(\*, CENTER) or textAlign(\*, TOP)
Step 3: use all 5 inputs in the text() command (or a line break)
Step 4: oh God why does it do that?

https://editor.p5js.org/greenStone83/sketches/G8aAhwZ_a

Edit: It seems this issue may be the same as #5880 but there may be minor differences.

**Comment by inaridarkfox4231** [comment]
That issue has already been resolved. Have a look at this.
[p5.js/1.6.0/beta/text](https://editor.p5js.org/dark_fox/sketches/66cWaHS9N)
This is a build version made by davepagurek. Not all features are implemented, but the text() bug has been fixed. I fixed it. The release is scheduled for this month, so please wait for a while. I recommend closing this issue.

**Comment by greenStone83** [comment]
Awesome, thanks
