### ISSUE TITLE
`saveGif` exports with black bg color if background() is called only in `setup`

### ISSUE THREAD

**Issue by yuletide** [processing/p5.js#5999]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [X] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

1.5.0

### Web browser and version

Chrome Version 109.0.5414.119 (Official Build) (arm64) 

### Operating System

Mac OSX

### Steps:
1. Set background color in `setup()`
2. Export gif
3. Gif does not reflect bg color

### Snippet:
Minimal example
```js



function setup() {
  createCanvas(windowWidth, windowHeight);
  background(220);
}

function draw() {
  // Another attempt to draw bg only at start, renders on screen fine but gif exports as black
  if (frameCount === 1)   background(200);
}

function windowResized() {
  resizeCanvas(windowWidth, windowHeight);
}

function keyPressed() {
  // this will download the first 5 seconds of the animation!
  if (key === 's') {
    saveGif('mySketch', 5);
  }
}
```

Full example where I also tried setting the background in the first frame off the `draw()` call but this doesn't fix it either (for this sketch we don't want to redraw background each frame): https://editor.p5js.org/yuletide/sketches/M0A8YYKMD

**Comment by anmode** [comment]
It looks like the problem is that the background color is not being set in the first frame of the gif, which is causing the output gif to have a black background. One possible solution is to explicitly set the background color in the first frame of the "draw" function before any other drawings are made.
```
var x = 0;

function setup() {
  createCanvas(300, 300);
}

function draw() {
  if (frameCount == 1) {
    background(255);
  }
  x = x + 1;
  rect(x, height / 2, 20, 20);
}

function keyPressed() {
  if (key == 's') {
    saveGif('rect_gif', frameRate());
  }
}
```

**Comment by davepagurek** [comment]
This is a known issue which, for now, is documented: https://github.com/processing/p5.js/blob/ed3add541680edf10783dcce1cf8aa55a21e69eb/src/image/loading_displaying.js#L183

However, it would be great to remove this limitation! I haven't spent enough time yet looking into why this happens, but when I get around to looking (or if someone else finds out!) we can talk about how best to fix it in the comments on this issue.

**Comment by davepagurek** [comment]
Oh ok it looks like the issue is that `draw()` gets called immediately after `setup()` even when `noLoop` is called, which interferes with the saveGif process. I'm going to whip up a PR to make it so that it doesn't do this if a gif is recording.

**Comment by yuletide** [comment]
Awesome! thanks yall

**Comment by yuletide** [comment]
Did this make it into the latest 1.6.0 release? I'm still seeing the old behavior here: https://editor.p5js.org/shartse/sketches/KZfvtBlPZ

**Comment by yuletide** [comment]
Here's another sketch with issues saving gifs, showing some of the strange edge cases that can pop up: https://editor.p5js.org/yuletide/sketches/EBif8-8hz

**Comment by davepagurek** [comment]
Hi @yuletide! I think this is because your draw function is not synchronously drawing to the canvas, but rather doing it in an async callback. p5 currently only supports synchronous `draw` functions (so making `draw` an `async` function and `await`ing the result of the `fetch` won't solve the issue unfortunately), so for now your best bet is probably to save up a bunch of fetch results in an array, and then when you save a gif, read each frame's data from that array rather than through a fetch callback.

**Comment by yuletide** [comment]
Just ran into this again with this sketch: https://editor.p5js.org/yuletide/sketches/zvtaN4dfJ

When loading the background as an image in setup() and then drawing over top, the gif exports with transparent bg -- anything I missed or is this related? 

Sketch: 
![image](https://github.com/processing/p5.js/assets/58695/66fc00c6-64f8-4ad4-a4e3-220edd676b03)

GIf: 
![image](https://github.com/processing/p5.js/assets/58695/3c05c70b-fd9e-46d9-9bd6-a346e5a32d0f)
