### ISSUE TITLE
Text kerning gets messed up when on Chrome on a phone

### ISSUE THREAD

**Issue by greenStone83** [processing/p5.js#6007]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [X] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

1.5.0

### Web browser and version

Chrome 109.0.5414.118

### Operating System

Android 9; SM-G95OU Build/PPR1.180610.011

### Steps to reproduce this

The gaps between letters is irregular on small text on Chrome on my phone, but not Firefox.

Code
https://editor.p5js.org/greenStone83/sketches/1-ukmh-o4

Pic
https://cdn.discordapp.com/attachments/796128626625347635/1072193667525251172/Screenshot_20230206-113433_Chrome.jpg

**Comment by davepagurek** [comment]
Thanks @MostafaEwis, I'll assign this to you. Feel free to discuss in this issue if you narrow down the problem, e.g. if this only applies to the default font or if fonts from `loadFont` are affected too.

**Comment by MostafaEwis** [comment]
## I have done some tests and here is what I found out until now:

These apply weather I'm using createP or text methds.

### The error shows:
- only for small fonts (usually under 10px for text created with createP method, and 16px when using text method)
- only for sans-serif fonts
- when you use the Google app in-app-browser
- when you use "open in Chrome" from the Google app in-app-browser, and it keeps showing even if you refreshed the Chrome tab
### The error doesn't show:
- when you open directly from the browser weather it's Chrome or Firefox 
- when you use share in full screen (it shows for the bug reporter though)
- when you open in the Google app in-app-browser it shows the error at first but when you choose share edit and open in the same in-app browser, the error oddly disappears 

I suspected that the Google in-app-browser may have problems, so I made a dummy website with small text and hosted it on Netlify and tried to open it from the in-app-browser, then I used the p5.js lib to render the text on the dummy site, the error didn't show in both cases, and the text showed correctly which means it's probably error from p5.js web editor.

hi @greenStone83 ,  I'm assuming you used the Google app to view the sketch, is this true? also, I'm wondering if the same error shows when you use Chrome directly.

**Comment by davepagurek** [comment]
The fact that it also happens for `createP` implies it's definitely a browser bug, as `createP` is just a normal HTML element without p5 involved in its rendering. I think this means we can't fix this in p5, and instead just look for temporary workarounds until it's fixed in Chrome.

Do `loadFont` fonts have this problem too?

**Comment by MostafaEwis** [comment]
No, I loaded some fonts with loadfont and the bug stopped showing 
The weird letter spacing occurs only when using sans-serif font family

**Comment by davepagurek** [comment]
Ok nice, for anyone encountering this issue, they can try loading a font (e.g. through a Google Fonts url) or using a different default font. We can check in when Chrome updates to see if this gets fixed.

I'm going to close this for organizational purposes but feel free to keep discussing workarounds here!

**Comment by greenStone83** [comment]
> hi @greenStone83 , I'm assuming you used the Google app to view the sketch, is this true? also, I'm wondering if the same error shows when you use Chrome directly.

I sent the link to myself on Discord and opened it from Discord. This led to like a Chrome browser opening it but still in the Discord App. However this issue is the same when I open it up on Chrome directly.
