### ISSUE TITLE
Feed for some problems that may exist in Chinese translation

### ISSUE THREAD

**Issue by HairlessVillager** [processing/p5.js#6008]
### Topic

NOTICE: This is a discussion of language translation, and if you are not a native speaker of the language, this may not be the place for you.

反馈一下中文翻译可能存在的一些问题。以这个文档为例：

https://github.com/processing/p5.js/blob/main/contributor_docs/zh/contributing_documentation.md

- “帮助我们找到代码本身的bug和问题”（“bug”和“问题”语义重复）
- “一个非常有帮助的方式”（不够本土化）
- “损坏的例子”（搭配不当）
- “打开一个 issue” vs. “创建一个 issue”（前后翻译不一致）
- “虽然参考文的例子通常是非常简单的代码片段”（“参考文”？）

虽然这是一个对新手非常友好的开源项目，但是这种翻译质量实在难以恭维，以至于我怀疑这是否是机器翻译（幸好不全是）。欣慰的是，已经有人整理了一份[中文词汇集链接](https://github.com/processing/p5.js-website/blob/main/contributor_docs/%E4%B8%AD%E6%96%87%E8%AF%8D%E6%B1%87%E9%9B%86%E9%93%BE%E6%8E%A5.md)。希望我们的 Translation Stewards 能考虑一下具体的翻译标准（例如：不能出现语法错误，不能直接使用未经润色的机翻文本等），这样不仅能提醒后来者规范翻译，也有利于润色已经提交的翻译。谢谢！

[@unicar9](https://github.com/unicar9), [@Gracia-zhang](https://github.com/Gracia-zhang), [@pentalei](https://github.com/pentalei)

**Comment by Qianqianye** [comment]
Thanks @HairlessVillager for catching the translation issues. Please feel free to open a pull request with your edits of the translation, if you'd like. Otherwise, please feel free to share your recommended translation edits here directly. Thank you!

**Comment by Bernice55231** [comment]
hi, I am very interested in polishing this translation issue here! Can I take over this issue?

**Comment by HairlessVillager** [comment]
@Bernice55231 Sure!
