### ISSUE TITLE
Support for drawing to/reading from framebuffers

### ISSUE THREAD

**Issue by davepagurek** [processing/p5.js#6018]
### Increasing Access

`createGraphics` is currently the recommended way to create a texture and use it elsewhere in a sketch. While this is very flexible and approachable, it unfortunately comes with inherent performance implications (https://github.com/processing/p5.js/issues/5128) that are currently are hard to work around within p5. Framebuffers are the native WebGL solution to this task with the best potential performance.

Giving users access to better performance with, ideally, a simple and familiar interface would let their sketches take better advantage of hardware capabilities and give viewers with lower-end hardware a much smoother viewing experience.

### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### Feature request details

While for technical reasons it will not be feasible to make all graphics used as textures use Framebuffers under the hood, we believe creating an interface for Framebuffers that fits well with existing p5 features will still be beneficial. 

## Inspiration
- [p5.Framebuffer](https://github.com/davepagurek/p5.Framebuffer)
- [p5Fbo](https://github.com/aferriss/p5Fbo)
- [openFrameworks ofFbo](https://openframeworks.cc/documentation/gl/ofFbo/)

## High level features

- A Framebuffer class can be created with `createFramebuffer()`
- It may only be used in WebGL environments
- [If WebGL2 is enabled](https://github.com/processing/p5.js/issues/2536), antialiasing is supported
  - We have decided, at first at least, we will not try to provide an antialiasing fallback on WebGL1
  - The most practical fallback option would be to render at 2x pixel density. However, this has a noticeable performance impact which is especially large on the sorts of older devices that don't have WebGL2 support. For that reason, we believe a more reasonable option is to degrade gracefully to a 1x density non-antialiased Framebuffer if only WebGL1 is available.
- The Framebuffer can be passed into `texture()` or `setUniform()` or `image()` like a graphic can

## Implementation details
- Things that aren't part of the main motivation but we would get as a side effect:
  - Writing in floating point format
    - This has been [asked](https://github.com/processing/p5.js/issues/5556) [for](https://stackoverflow.com/questions/66334783/is-it-possible-to-use-floating-point-texture-with-p5-js-glsl) directly, but also indirectly after people notice [artifacts in feedback sketches](https://github.com/davepagurek/p5.Framebuffer#floating-point-textures)
    - Readable depth information (not essential for v1)
    - p5.Framebuffer allows this to be read via the `.depth` property of a framebuffer
- How does one choose a framebuffer to draw to?
  - Prior art:
    - p5.Framebuffer: `fbo.draw(() => /* ... */)`
    - p5Fbo, ofFbo: `fbo.begin(); /* ... */ fbo.end();`
  - Probably the `begin`/`end` version is more similar to `push`/`pop` and is what we should go with
    - The callback function version could also potentially be added on top of this as a way to avoid accidental improper nesting of begin/end, but this is not essential
- Different size support
  - Each fbo has to come with its own camera in order to be able to properly render to a size different from the main canvas
- We probably do not want to (at least initially) support all texture formats
  - By making users ask for either `UNSIGNED_BYTE` (default) or `FLOAT`, this lets us pick the appropriate mode for the environment (WebGL1, WebGL2, etc)
  -  Antialiasing support will need lots of testing (p5.Framebuffer supports this but runs into cross-browser version issues often) so letting us pick texture modes that work will give us an avenue for resolving these sorts of issues

**Comment by aferriss** [comment]
Thanks for making this writeup Dave, very exciting! I have a couple quick thoughts:

1. Would this change also require us to add a friendlier api for creating and using p5.Texture objects? Or would you just pass around the framebuffer itself?
2. Should we also add support for the HALF_FLOAT data type? I believe it is more widely supported than FLOAT on mobile hardware
3. I think we should consider creating an api for reading a framebuffer back to pixels.
4. Can we outline some of the accessibility arguments that we talked about yesterday re: performance?
5. Can framebuffers also be created for p5.Graphics (probably yes, but does this get confusing)?
6. Is framebuffer the best name to use here? I know that's the technical term, but just want to double check if there is anything else less graphics jargon-y that could help newcomers find this feature.
7. Should a framebuffer try to emulate the previously used camera, or just always construct itself with a default?
8. Should we allow users some way to set the texture min / mag / wrap settings when constructing the framebuffer (I know I find this useful).

**Comment by aferriss** [comment]
> HALF_FLOAT makes sense. Do you think it should be a separate option people should pick or something we try to fall back to if FLOAT isn't available?

I think we should probably default to uint8 and allow users to choose another type if they want. If we want to take inspiration from openFramworks we could do something like this
```
let fbDefault = createFramebuffer(100, 100); // creates a fbo with 8888 int type at the specified size
let fbDefault2 = createFramebuffer(100, 100, RGBA); // creates fbo with the 8888 int type at the specified size
let fbNoAlpha = createFramebuffer(100, 100, RGB);// creates fbo with 888 int type at the specified size
let fbRedOnly = createFramebuffer(100, 100, R); // creates fbo with 8bit int type at the specified size
let fbHalfFloat = createFramebuffer(100, 100, HALF_FLOAT); // creates fbo with 16bit half float type at the specified size
let fbFloat = createFramebuffer(100, 100, FLOAT); // creates fbo with 32 bit float type at the specified size
```
Alternatively we could allow the function to accept an object which might make parsing settings a little easier. We can default to something sane if the field is left empty on the settings object.
```
let fboSettings = {
  width: 100,
  height: 100,
  type: FLOAT,
  channels: RGBA
}
let fb = createFramebuffer(fboSettings);
```

> I'm open to a friendlier name, do you have any suggestions? 
Nothing especially coming to mind, just wanted to flag it in case we thought of something compelling.

> Re:cameras Do you think that tradeoff would make sense? 
Makes sense to me, thanks for explaining!

**Comment by ShivangMishra** [comment]
@davepagurek  @aferriss  awesome discussion... I've been using p5.js for some of my personal projects, so I'm familiar with how things work in p5. I'd love to contribute to this feature. Any suggestions on where I should start?

**Comment by davepagurek** [comment]
Thanks for your interest @ShivangMishra! I think the plan for this one will be something along these lines:
- First get https://github.com/processing/p5.js/pull/6035 merged to add WebGL2 support
- Then I'll make a PR with initial framebuffer support, to provide some scaffolding for the rest of the features we want
- From there, I'll make some issues for follow-up tasks, including things like reading pixels, ensuring antialiasing works on all platforms with all combinations of settings, writing documentation, and writing examples

Once we get to that third step I'm hoping it'll be easy to pick up tasks and help bring this feature to completion! In the mean time, feel free to keep an eye on this issue to see how things are shaping up, and maybe take a look at [p5.Framebuffer](https://github.com/davepagurek/p5.Framebuffer), [p5Fbo](https://github.com/aferriss/p5Fbo), or [openFrameworks ofFbo](https://openframeworks.cc/documentation/gl/ofFbo/) to get a sense of the sorts of ways we'll want to use this feature.

**Comment by ShivangMishra** [comment]
@davepagurek alright thanks, I'll go through the related docs and code while you do the first two tasks.

**Comment by davepagurek** [comment]
Thanks for your patience everyone! Once #6072 is merged, here are a number of follow-up issues that we'd love some help on:
- https://github.com/processing/p5.js/issues/6083
- https://github.com/processing/p5.js/issues/6082
- https://github.com/processing/p5.js-website/issues/1340
- https://github.com/processing/p5.js-website/issues/1341
