### ISSUE TITLE
line is not a function

### ISSUE THREAD

**Issue by Johanalopez0922** [processing/p5.js#6020]
### Most appropriate sub-area of p5.js?

- [X] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [X] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [X] Other (specify if possible)

### Steps:
1.Download the package from de ps website
2.Write the code below
3.You'll fin the next error in the console: "line is not a function"

### Snippet:

```js

// Paste your code here :)
function setup() {
  createCanvas(600,600);
}
function draw() {
  background("white"); 
  line(200,100,200,300);   
}

```

**Comment by AllaithpPr** [comment]
Z

**Comment by Johanalopez0922** [comment]
Uncaught TypeError: line is not a function
    at draw (sketch.js:70:3)
    at _main.default.redraw (p5.js:68314:25)
    at _draw (p5.js:60836:23)

**Comment by wuyudi** [comment]
> Uncaught TypeError: line is not a function at draw (sketch.js:70:3) at _main.default.redraw (p5.js:68314:25) at _draw (p5.js:60836:23)

I can't reproduce this, maybe give an online editor link?
![image](https://user-images.githubusercontent.com/30024051/219435171-7303b568-8c23-4b79-a0b5-591d1ffc18fe.png)
