### ISSUE TITLE
non case sensistive reserved names checking generates incorrect warnings

### ISSUE THREAD

**Issue by Wildernesss** [processing/p5.js#6026]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [X] Friendly Errors
- [X] Other (specify if possible)

### p5.js version

 v1.5.0

### Web browser and version

Google Chrome Version 110.0.5481.104 (Official Build) (64-bit)

### Operating System

Windows 10

### Steps to reproduce this

Hi everyone,

I’ve been defining and using in one of my sketch for year a move() function as this one:

```js

function move(){
  
  print('hello');
  
}
```

I’ve just updated p5js library used by this sketch (the previous one was 3 years old…) and since I get the following warning in Chrome Dev Tools:

> p5.js says: you have used a p5.js reserved function “move” make sure you change the function name to something else.
> 
> More info: [reference | p5.js](https://p5js.org/reference/#/p5/move)
> p5js.org/reference/#/p5/move

But I cannot find any move() function in p5js, excepted a **.move()** method in camera object [https://p5js.org/reference/#/p5.Camera/move](url) and **MOVE** constant (with capital letters for the id of course) used as argument by the cursor() function ([p5js.org/reference/#/p5/move](url))

I’ve written a small IDE for my students that offers them opportunity to learn programming first steps with Blocky and Javascript in parallel. The Javascript library I’ve developped contains basic functions to program a game and one of them that is called move(). As I’ve already written all the documentation, including exercices, screen and video captures, so I want to keep this function with this name move() into my library.

I don’t see any standalone _move()_ function into p5js library. So why this warning? Is this an issue in p5js? How to get rid off this warning without changing the function name? It seems the cause of these incorrect warning are non case sensitive reserved names checking.

Thanks a lot for your lights!

Laurent

### Steps:
1. create a new sketch
2. define a new function called move() (see below)
3. run and watch console in Dev Tools

**Comment by davepagurek** [comment]
Hi! I think this is the same bug as https://github.com/processing/p5.js/issues/5753, and should be fixed by my proposed solution in there (currently we are adding all methods from all p5 classes to the reserved name list, when, as you pointed out, some are only ever used as a method on a camera object.) I'm going to close this issue for now for organizational purposes since we're tracking this issue there.

In the mean time, does this go away if you disable friendly errors? https://p5js.org/reference/#/p5/disableFriendlyErrors

**Comment by Wildernesss** [comment]
Hi Dave,
Thanks for your quick reply. Perfect for joining this issue to  #5753 issue.
Adding:
p5.disableFriendlyErrors = true;
to setup() doesn't disable the notification in console.
Thanks again and have a nice week-end!
Laurent 

    Le jeudi 23 février 2023 à 19:17:08 UTC+1, Dave Pagurek ***@***.***> a écrit :  
 
 


Hi! I think this is the same bug as #5753, and should be fixed by my proposed solution in there (currently we are adding all methods from all p5 classes to the reserved name list, when, as you pointed out, some are only ever used as a method on a camera object.) I'm going to close this issue for now for organizational purposes since we're tracking this issue there.

In the mean time, does this go away if you disable friendly errors? https://p5js.org/reference/#/p5/disableFriendlyErrors

**Comment by davepagurek** [comment]
Ah ok, I think there may not be a way to avoid the warning in the console for now unfortunately. At the very least, it can be safely ignored. There's some movement on that issue so hopefully we'll get this fixed for real soon!
