### ISSUE TITLE
link not working in "src/README.md"

### ISSUE THREAD

**Issue by aditya-shrivastavv** [processing/p5.js#6031]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [X] Other (specify if possible)

### Steps to reproduce this

the [JSDoc and module](https://github.com/processing/p5.js/blob/929b162a7b44f789c8b819104d4344e30aafcbaf/src/README.md?plain=1#L7) link is no longer working in the "src/README.md" file.
need to update those links

**Comment by konstantinstanmeyer** [comment]
Hey! Think that I found the correct URLs so going to try and fix this now.
