### ISSUE TITLE
image() to draw a Capture object after using capture.updatePixels() doesn't show updated pixels

### ISSUE THREAD

**Issue by dougrosman** [processing/p5.js#6033]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [X] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

1.6.0

### Web browser and version

Chrome 110.0.5481.177, Firefox 110.0

### Operating System

Windows 10 Version 22H2 (Build 19045.2604)

### Steps

Updated pixels on a capture object don't take effect when using image() to draw the capture.

When I `console.log(capture.pixels)` after calling `capture.updatePixels()`, I see that the values have actually changed correctly, but the `image(capture, 0, 0)` function doesn't take the updated pixels into account and draws the unchanged capture feed.

The code snippet below, a simple brightness thresholding sketch, works fine on version 1.5.0 and earlier.

1. capture = createCapture(VIDEO)
2. capture.loadPixels()
3. // loop through pixel array, change RGB channels in pixel to 0 or 255 based on brightness
4. capture.updatePixels()
5. image(capture, 0, 0); // only the original capture feed is displayed, the updated pixels don't show.

### Snippet:

```js

const cam_w = 640;
const cam_h = 360;
let capture;

function setup() {
    createCanvas(cam_w, cam_h);
    capture = createCapture(VIDEO);
    capture.size(cam_w, cam_h);
    capture.hide();
}

function draw() {
    capture.loadPixels();
    
    if (capture.pixels.length > 0) {
        for (let y = 0; y < capture.height; y++) {
            for (let x = 0; x < capture.width; x++) {
                const index = (x + y * capture.width) * 4;
                
                const r = capture.pixels[index];
                const g = capture.pixels[index + 1];
                const b = capture.pixels[index + 2];
                const brightness = (r + g + b) / 3
                
                if (brightness > 127) {
                    capture.pixels[index] = 255;
                    capture.pixels[index + 1] = 255;
                    capture.pixels[index + 2] = 255;
                } else {
                    capture.pixels[index] = 0;
                    capture.pixels[index + 1] = 0;
                    capture.pixels[index + 2] = 0;
                }
            }
        }
        
        capture.updatePixels();

        // ISSUE: image() doesn't draw the thresholded image like it should, just the untouched webcam feed.
        // This code works with version 1.5.0 and earlier.
        image(capture, 0, 0); 
    }
}

```

**Comment by limzykenneth** [comment]
I bisected down the issue to stem from https://github.com/processing/p5.js/commit/1806b8e6877497eb5089d4cd21c1d04d247ef2d0, @davepagurek would you be able to have a look at this since you implemented that part of the change?
