### ISSUE TITLE
p5.EasyCam library's HUD(Head Up Display) is not working correctly

### ISSUE THREAD

**Issue by hochanjo** [processing/p5.js#6034]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

1.6

### Web browser and version

Chrome 110.0.5481.177

### Operating System

MacOSX 13.2.1(22D68)

### Steps:
1. Use p5.EasyCam Library's HUD(Head Up Display) method - camera.beginHUD()
2. It runs gl.disable(gl.DEPTH_TEST) and display fixed 2D Panel in the 3D mode.
https://freshfork.github.io/p5.EasyCam/examples/HeadUpDisplay/
3. It works fine (fixed position) with p5 1.5. But 2D Panel moves with Camera at p5 1.6. (not fixed position)

### Snippet:

p5.EasyCam.beginHUD()

```js
    /**
     *
     * begin screen-aligned 2D-drawing.
     *
     * <pre>
     * beginHUD()
     *   disabled depth test
     *   ortho
     *   ... your code is executed here ...
     * endHUD()
     * </pre>
     *
     */
    beginHUD(renderer, w, h) {
      var cam = this.cam;
      renderer = renderer || cam.renderer;

      if (!renderer) return;
      this.pushed_rendererState = renderer.push();

      var gl = renderer.drawingContext;
      var w = w !== undefined ? w : renderer.width;
      var h = h !== undefined ? h : renderer.height;
      var d = Number.MAX_VALUE;

      gl.flush();
      // gl.finish();

      // 1) disable DEPTH_TEST
      gl.disable(gl.DEPTH_TEST);
      // 2) push modelview/projection
      //    p5 is not creating a push/pop stack
      this.pushed_uMVMatrix = renderer.uMVMatrix.copy();
      this.pushed_uPMatrix = renderer.uPMatrix.copy();

      // 3) set new modelview (identity)
      renderer.resetMatrix();
      // 4) set new projection (ortho)
      renderer._curCamera.ortho(0, w, -h, 0, -d, +d);
      // renderer.ortho();
      // renderer.translate(-w / 2, -h / 2);
    }
```

p5.EasyCam.endHUD()

```js
    /**
     *
     * end screen-aligned 2D-drawing.
     *
     */
    endHUD(renderer) {
      var cam = this.cam;
      renderer = renderer || cam.renderer;

      if (!renderer) return;

      var gl = renderer.drawingContext;

      gl.flush();
      // gl.finish();

      // 2) restore modelview/projection
      renderer.uMVMatrix.set(this.pushed_uMVMatrix);
      renderer.uPMatrix.set(this.pushed_uPMatrix);
      // 1) enable DEPTH_TEST
      gl.enable(gl.DEPTH_TEST);
      renderer.pop(this.pushed_rendererState);
    }
  }
```

**Comment by davepagurek** [comment]
This is an intended consequence of https://github.com/processing/p5.js/pull/5899, which changed `resetMatrix` to not ignore the camera position to make it more intuitive to users. It looks like the EasyCam HUD was relying on the old behaviour.

I think to fix this, the library could also reset the camera's position and orientation in `beginHUD`.

**Comment by jwdunn1** [comment]
Dave, Thanks for the info. FYI, I manage the [EasyCam library](https://github.com/freshfork/p5.EasyCam). I am investigating the [issue](https://github.com/freshfork/p5.EasyCam/issues/24) opened this morning.

**Comment by davepagurek** [comment]
Thanks @jwdunn1, sorry for the breaking change! Let me know if you need any help getting it working 🙂 Also thanks for your library, it's great!

I'm going to close this issue for organizational purposes but feel free to keep discussing here.

**Comment by inaridarkfox4231** [comment]
I am the one who proposed the specification change. I'm sorry that my suggestion caused you trouble this time.
The gist of the proposal, as mentioned in the pull request, is to make resetMatrix() behave more like 2D.
There is little benefit in replacing the uMVmatrix with the identity matrix in normal p5.js code. It's fine if it's an internal function, but it doesn't help that an externally accessible function behaves that way.
I apologize for the inconvenience, but I would like you to replace it directly with the identity matrix.
