### ISSUE TITLE
Links in navigation bar of Korean translation of contributor docs are broken

### ISSUE THREAD

**Issue by al6862** [processing/p5.js#6040]
### Most appropriate sections of the p5.js website?

Other (specify if possible)

### What is your operating system?

Mac OS

### Web browser and version

Google Chrome: 109.0.5414.119 (Official Build) (arm64)

### Actual Behavior

After clicking on the Korean translation of the navigation bar, when I try to return back to the English translation, it leads me to a 404. 

### Expected Behavior

It should lead me back to the English translation.

### Steps to reproduce

1. Go to https://p5js.org/contributor-docs/#/ko/.
2. Click on another translation on the navigation bar.

This will lead to a 404 - Not found for me.

### Would you like to work on the issue?

Yes!

**Comment by Qianqianye** [comment]
Thank you @al6862. Just added you to the p5.js [contributors](https://github.com/processing/p5.js#contributors) list 🎉
