### ISSUE TITLE
Misleading description of mousePressed() reference

### ISSUE THREAD

**Issue by yogitheboss** [processing/p5.js#6045]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [X] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

v1.5.0

### Web browser and version

108.0.5359.125 (Official Build) (64-bit) (cohort: Stable)

### Operating System

Windows

### Steps:
1. go to the webpage [link](https://p5js.org/reference/#/p5/mousePressed)
2.  the description of the mouse Pressed i.e. Click within the image to change
 the value of the rectangle, is wrong as we don't really need to click within the rectange , clicking anywhere would still change the value. 
 also I think we should call the variable color_value instead of value only.

### Snippet:
![image](https://user-images.githubusercontent.com/91418287/222914783-18f6315e-f72f-41cb-aa4a-620ba4ca90cd.png)

```

**Comment by yogitheboss** [comment]
Can I work on this issue? @davepagurek @limzykenneth

**Comment by davepagurek** [comment]
Thanks @yogitheboss, I'll assign this to you!
