### ISSUE TITLE
Image .loadPixel() generating warning 'Multiple readback operations'

### ISSUE THREAD

**Issue by Wildernesss** [processing/p5.js#6074]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [X] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

v1.5.0 October 18, 2022

### Web browser and version

Chrome Version 111.0.5563.65 (Build officiel) (64 bits)

### Operating System

Windows 10

### Steps to reproduce this

Hi everyone,

The _rotateRight_(img) function below gets a square (n x n pixels) image (img) and returns a new image of the same dimension with a 90 degrees right rotation. It still works fine but since I've updated code to a more recent version of p5js I get the following warning, concerning the use of the **.loadPixels()** method:

> p5.js:63227 Canvas2D: Multiple readback operations using getImageData are faster with the willReadFrequently attribute set to true. See: https://html.spec.whatwg.org/multipage/canvas.html#concept-canvas-will-read-frequently"

Any idea concerning the reason of this warning? Non optimal code in p5js? Other?

Thanks a lot for your lights and your precious work!

Laurent

### Steps:
1. execute the below function passing a squared bitmap image :

```js

 function rotateRight(img){

   var w = img.width;
   var h = img.height;
   var index, indexr;
   var img2 = createImage(w, h);

   img.loadPixels();
   img2.loadPixels();

   indexr = 0;

   for (let x = 0; x < w; x++) {

     for(let y = h - 1; y >= 0; y--) {

       index = (x+y*w)*4;
       img2.pixels[indexr] = img.pixels[index];
       img2.pixels[indexr + 1] = img.pixels[index+1];
       img2.pixels[indexr + 2] = img.pixels[index+2];
       img2.pixels[indexr + 3] = img.pixels[index+3];

       indexr += 4;

     }
   }

   img.updatePixels();
   img2.updatePixels();

   return img2;
 }
```

**Comment by davepagurek** [comment]
I think this can be safely ignored. Chrome gives that warning whenever you read canvas pixels into normal Javascript variables. The property it suggests setting would turn off hardware acceleration for the canvas in question, which means no data has to be transferred from the GPU to get the pixel values in an array, but that also means that any canvas functions we call will also not get hardware acceleration. This would slow down things like `tint()` a lot.

In general, `loadPixels`/`updatePixels` will be fine as long as you try to do it as little as possible (e.g. in your example, rotating your image once upfront is fine, just don't do it every frame in `draw()` 🙂) If you do need to be calling it often, maybe consider using a different approach. That will depend on the task, but sometimes it can be accomplished with blend modes or shaders (or in your case, maybe just a `rotate(PI/2)` before drawing the image.)

**Comment by Wildernesss** [comment]
Thanks for your quick and clear answer @davepagurek! :o)

**Comment by Qianqianye** [comment]
Thanks @Wildernesss and @davepagurek. Closing this issue for organizational purpose. Please feel free to reopen it if further discussion is needed.
