### ISSUE TITLE
p5.dom createSelect() options enable()

### ISSUE THREAD

**Issue by agrshch** [processing/p5.js#6077]
### Increasing Access

Unsure 

### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [X] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### Feature request details

Hello!

This is a continuation of [issue 3880](https://github.com/processing/p5.js/issues/3880)

p5.dom createSelect() options (and p5 dom objects in general) can be set to 'disabled' but there is no way to enable them back. It would be nice to be able to manipulate this attribute in both directions :)

It could be something like this

```
function enable(selectId,option){
  let options = select(`#${selectId}`);
  for(let i=0;i<options.elt.length;i++){
    if(options.elt[i].value === option){
      options.elt[i].disabled = false;
    }
  }
}
```

Thank you!

**Comment by Queen-codes** [comment]
Hi, @agrshch . are you working on this issue?

**Comment by Aqmalp99** [comment]
Hey, I am part of a group from the University of Adelaide. My group and I would like to work on this issue as a part of an open-source contribution project. Are we able to tackle this issue?

**Comment by limzykenneth** [comment]
@Aqmalp99 I think you can go ahead unless we hear anything back from @Queen-codes
