### ISSUE TITLE
Verify that p5.Framebuffer settings work in all environments

### ISSUE THREAD

**Issue by davepagurek** [processing/p5.js#6083]
### Increasing Access

Once we add support for framebuffers in https://github.com/processing/p5.js/pull/6072, although it has been heavily manually tested by the authors and also unit tested, more manual testing on more environments will help make sure it works smoothly for everyone. Small inconsistencies in WebGL drivers on different browsers and OSes have come up in the past, so it would be great to catch them early.

### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### Feature enhancement details

There are a few manual test examples in `/test/manual-test-examples/webgl/framebuffer`. These have been tested by me already in Chrome and Firefox on an M1 Macbook Pro, but it would be great if these could also be tested:
- On older Macs without Apple silicon (possibly with older Safari too)
- On Windows on various browsers

**Comment by wong-justin** [comment]
I viewed the manual test examples on Windows 10, with Firefox/Chrome/Edge versions 114.0. Everything seemed to work fine, no fps problems or unexpected behavior as far as I could tell.

**Comment by davepagurek** [comment]
Thanks @wong-justin! I have access to old Safari I can test on, so I'll double check there too, and close this issue if everything looks good.

**Comment by davepagurek** [comment]
Everything runs without crashing on Safari 12 (with no WebGL2 support, so everything falls back to WebGL1), so I'm going to call this issue done 🙂
