### ISSUE TITLE
Gifs are not playing

### ISSUE THREAD

**Issue by epleaner** [processing/p5.js#6085]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [X] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

1.6.0

### Web browser and version

Firefox 111.0

### Operating System

MacOS 13.2.1

### Steps:
Reproduction sketch here:
https://editor.p5js.org/elip/sketches/eFQ4AzZAU

Also does not work here:
https://p5js.org/reference/#/p5.Image/play

Gif does not animate.

### Snippet:

```js
let gif;

function preload() {
  gif = loadImage('poke.gif');
}

function draw() {
  background(255);
  image(gif, 0, 0, width, height);
}

function mousePressed() {
  gif.pause();
}

function mouseReleased() {
  gif.play();
}

```

**Comment by davepagurek** [comment]
Hi! I think this issue is the same as https://github.com/processing/p5.js/issues/6070 (which has a fix now, should be good to go in the next release!) I'm going to close this for organizational purposes but let me know if we've missed anything.
