### ISSUE TITLE
problem creating global function 'createElement'

### ISSUE THREAD

**Issue by awdriggs** [processing/p5.js#6097]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [X] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [X] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

1.6.0

### Web browser and version

Chrome Version 111.0.5563.146 (Official Build) (x86_64)

### Operating System

MacOSX 12.5.1

### Steps:
1. Open a new [editor](https://editor.p5js.org/)
2. Write any p5 function `ellipse(20, 20, 20, 20);`
3. Press Play

I get this error...

```
p5.js says: p5 had problems creating the global function "createElement", possibly because your code is already using that name as a variable. You may want to rename your variable to something else. (http://p5js.org/reference/#/p5/createElement) 
```

Mostly the sketch will still work, but if I use p5.play I don't even get a canvas.

Strajngely, if open any sketches or create a new sketch on the same computer, same browser, but with a different p5 account I don't get the error.

**Comment by davepagurek** [comment]
Hi! This sounds like it might be this issue: https://github.com/processing/p5.js-web-editor/issues/2188

Can you try turning off the accessibility settings in the p5 editor then reloading?
<img width="684" alt="image" src="https://user-images.githubusercontent.com/5315059/230116896-3fdfe432-5959-4992-9588-88eba14a50ca.png">

(It's not great having to turn those off of course, but if that fixes it, then at least we know this isn't a brand new issue)

**Comment by awdriggs** [comment]
That did fix it!

**Comment by davepagurek** [comment]
Awesome! I'm going to close this issue for organizational purposes, feel free to follow along with https://github.com/processing/p5.js-web-editor/issues/2188 for when a proper fix lands 🙂
