### ISSUE TITLE
Make Graphics and Framebuffer update ortho cameras

### ISSUE THREAD

**Issue by davepagurek** [processing/p5.js#6100]
### Increasing Access

Currently, p5.Graphics and p5.Framebuffer resize their cameras when they themselves resize. This means that the user doesn't have to worry about their camera getting stretched when resizing, and things just work. However, it only tries to do this for perspective cameras, and other cameras end up reverting to a default camera setup. Updating ortho cameras will make that edge case work more like the default perspective case and reduce confusion (as currently I believe this behaviour is also not documented.)

### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### Feature enhancement details

Currently, resizing a p5.Graphics calls this (and p5.Framebuffer does something similar):
https://github.com/processing/p5.js/blob/d086bae37aca14850f838ea79ae721da4e08089c/src/webgl/p5.Camera.js#L1607-L1618

We could update this to also update the size of ortho cameras without fully resetting the camera to a default perspective camera.

**Comment by Gaurav-1306** [comment]
hello everyone i have been trying to work on this code. Does the solution I provided make sense? almost the same code can be used in p5.framebuffer


```
p5.Camera.prototype._resize = function() {
  if (this.cameraType === 'default') {
    this._computeCameraDefaultSettings();
    this._setDefaultCamera();
  } else if (this.cameraType === 'perspective') {
    this.perspective(
      this.cameraFOV,
      this._renderer.width / this._renderer.height
    );
  } else if (this.cameraType === 'ortho') {
    this.ortho(
      -this.width / 2,
      this.width / 2,
      -this.height / 2,
      this.height / 2,
      this.cameraNear,
      this.cameraFar
    );
  }
  // Additional handling for other camera types can be added here
};

```

**Comment by davepagurek** [comment]
We might want to hold off a little bit on this change until this PR is done https://github.com/processing/p5.js/pull/6216#issuecomment-1740151498 since it looks like it might change the API a little bit.

**Comment by davepagurek** [comment]
ok I'm going to close this one now -- The reason is that when one calls custom `frustum()` or `ortho()`, they supply left/right/top/bottom values, which could already be stretched. So further stretching is expected when the canvas is resized, and if different behaviour is desired, one can update the camera after they resize the canvas. Feel free to comment again if there's anything we missed!
