### ISSUE TITLE
Can I use p5.js to create playable ads for Google, Facebook and Unity ads ?

### ISSUE THREAD

**Issue by salmaan25** [processing/p5.js#6110]
### Topic

I am currently working on building a 2D playable ad for a game and p5.js looks like the perfect library for my use case. However, in order to check whether it would work, I wrote a very simple inline code to test on Facebook playable ad preview tool. The file works perfectly on the browser (both the desktop and phone browser), however on the tool it fails in the case:
`Asset cannot contain any JavaScript redirects.` 
It also displays some js code on the phone emulator screen of the tool.

What does this mean and how do I fix the issue? I'm sorry but I'm new to web development and javascript so any help would be greatly appreciated.
This is my code in [jsfiddle](https://jsfiddle.net/#&togetherjs=BxJi5r9INR) and [this](https://developers.facebook.com/tools/playable-preview/) is the link to the Facebook playable ad preview tool.

**Comment by limzykenneth** [comment]
Hi, if you need help with your own code, please direct your questions to the [forum](https://discourse.processing.org). We use GitHub issues mainly for bug reports and feature requests only. Thanks!
