### ISSUE TITLE
Make orbitControl() usable on mobile

### ISSUE THREAD

**Issue by inaridarkfox4231** [processing/p5.js#6118]
### Increasing Access

Currently, orbitControl() is used to change the camera matrix based on mouse information (although in some cases the projection matrix was also tampered with).

At that time, in mobile environments such as smartphones, mouseIsPressed barely responds, and nothing can be done about scaling and movement.

However, if you record the position of the previous frame in the touch object stored in touches as shown here, you can rotate, scale, and move smoothly even in a mobile environment.

However, since I only tried it in my own environment, I do not know if it will work properly in other mobile environments, so that may be a problem.

Also, you may have to specify touch-action:none in your css to kill the default behavior of touch operations, but that's up to the user, and the method shouldn't force it, but I don't know... (In the touch reference, there is no processing that kills the default behavior in the example).

### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [X] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### Feature enhancement details

First, modify the function that updates touch object information so that the position of the touch object in the previous frame is recorded. If there is one with the same id, it means that the previous frame also exists, so we record it and flag it as having moved.
```js
p5.prototype._updateTouchCoords = function (e) {
  if (this._curElement !== null) {
    // Get an array of previous touch objects
    const pTouches = this.touches.slice();
    var newTouches = [
    ];
    for (var i = 0; i < e.touches.length; i++) {
      newTouches[i] = getTouchInfo(this._curElement.elt, this.width, this.height, e, i);
    }
    // Compare with the previous array of touch objects
    for(let i = 0; i < newTouches.length; i++){
      for(let k = 0; k < pTouches.length; k++){
        if(newTouches[i].id === pTouches[k].id){
          newTouches[i].px = pTouches[k].x;
          newTouches[i].py = pTouches[k].y;
          newTouches[i].moved = true;
          break;
        }
      }
    }
    this._setProperty('touches', newTouches);
  }
};
function getTouchInfo(canvas, w, h, e) {
  var i = arguments.length > 4 && arguments[4] !== undefined ? arguments[4] : 0;
  var rect = canvas.getBoundingClientRect();
  var sx = canvas.scrollWidth / w || 1;
  var sy = canvas.scrollHeight / h || 1;
  var touch = e.touches[i] || e.changedTouches[i];
  return {
    x: (touch.clientX - rect.left) / sx,
    y: (touch.clientY - rect.top) / sy,
    winX: touch.clientX,
    winY: touch.clientY,
    id: touch.identifier,
    px: undefined, // previous touch position X
    py: undefined, // previous touch position Y
    moved: false // flag as having moved
  };
}
```

Next, calculate the flags and variables to use for touch and mouse respectively. Prepare in advance and decide the contents if the conditions are met.

```js
  // get moved touches.
  const movedTouches = this.touches.filter(t => t.moved);
  // flags for interaction.
  let zoomFlag = false;
  let rotationFlag = false;
  let moveFlag = false;
  // variables for interaction.
  let deltaRadius, deltaPhi, deltaTheta;
  let moveDeltaX, moveDeltaY;

  // For touches, the appropriate scale is different
  // because the distance difference is multiplied.
  const mouseZoomScaleFactor = 0.02;
  const touchZoomScaleFactor = 0.0008;
  const scaleFactor = this.height < this.width ? this.height : this.width;

  // calculate and determine flags and variables.
  if (movedTouches.length > 0) {
    /* for touch */
    // if length === 1, rotation.
    // if length > 1, zoom and move.
    if(movedTouches.length === 1){
      rotationFlag = true;
      const t = movedTouches[0];
      deltaTheta = -sensitivityX * (t.x - t.px) / scaleFactor;
      deltaPhi = sensitivityY * (t.y - t.py) / scaleFactor;
    } else {
      zoomFlag = true;
      const t0 = movedTouches[0];
      const t1 = movedTouches[1];
      const distWithTouches = Math.hypot(t0.x - t1.x, t0.y - t1.y);
      const prevDistWithTouches = Math.hypot(t0.px - t1.px, t0.py - t1.py);
      const changeDist = distWithTouches - prevDistWithTouches;
      deltaRadius = -changeDist * sensitivityZ * touchZoomScaleFactor;

      moveFlag = true;
      moveDeltaX = 0.5 * (t0.x + t1.x) - 0.5 * (t0.px + t1.px);
      moveDeltaY = 0.5 * (t0.y + t1.y) - 0.5 * (t0.py + t1.py);
    }
  } else {
    /* for mouse */
    // if wheelDeltaY !== 0, zoom.
    // if mouseLeftButton is down, rotation.
    // if mouseRightButton is down, move.
    if (this._mouseWheelDeltaY !== 0) {
      zoomFlag = true;
      // zoom according to direction of mouseWheelDeltaY rather than value
      const mouseWheelSign = (this._mouseWheelDeltaY > 0 ? 1 : -1);
      deltaRadius = mouseWheelSign * sensitivityZ * mouseZoomScaleFactor;
      this._mouseWheelDeltaY = 0;
    }
    if (this.mouseIsPressed) {
      if (this.mouseButton === this.LEFT) {
        rotationFlag = true;
        deltaTheta = -sensitivityX * (this.mouseX - this.pmouseX) / scaleFactor;
        deltaPhi = sensitivityY * (this.mouseY - this.pmouseY) / scaleFactor;
      } else if (this.mouseButton === this.RIGHT) {
        moveFlag = true;
        moveDeltaX = this.mouseX - this.pmouseX;
        moveDeltaY = this.mouseY - this.pmouseY;
      }
    }
  }
```

Based on the value determined here, the interaction is executed for each flag.
```js
  if (zoomFlag) {
    this._renderer._curCamera._orbit(0, 0, deltaRadius);
    // In orthogonal projection, the scale does not change even if
    // the distance to the gaze point is changed, so the projection matrix
    // needs to be modified.
    if (this._renderer.uPMatrix.mat4[15] !== 0) {
      this._renderer.uPMatrix.mat4[0] *= Math.pow(10, -deltaRadius);
      this._renderer.uPMatrix.mat4[5] *= Math.pow(10, -deltaRadius);
    }
  }
  
  if (rotationFlag) {
    this._renderer._curCamera._orbit(deltaTheta, deltaPhi, 0);
  }
  if (moveFlag) {
    /* and move method (I will omit it because it is very long.) */
  }
```

There is demo: [orbitControl() mobile](https://openprocessing.org/sketch/1898661)
p5Editor is here: [touch orbitControl Demo](https://editor.p5js.org/dark_fox/sketches/wClVcwamH)

**Comment by inaridarkfox4231** [comment]
This is a video that confirms the oreration in my mobile environment with a screen recorder.

https://user-images.githubusercontent.com/39549290/233856893-a94b6d69-a129-430b-a356-c434eb0364cd.mp4

**Comment by davepagurek** [comment]
This would have a big positive impact on mobile accessibility! Sounds like this implementation would also address https://github.com/processing/p5.js/issues/5176, does that also sound correct to you?

> Also, you may have to specify touch-action:none in your css to kill the default behavior of touch operations, but that's up to the user, and the method shouldn't force it, but I don't know... (In the touch reference, there is no processing that kills the default behavior in the example).

I'm thinking maybe when you use orbitControl, the first time it's executed, we should add that CSS to the canvas it's called on by default so that the default mobile experience is good. There are definitely cases where we wouldn't want that CSS added, so maybe we can add options to the function to disable adding custom CSS? It's kind of awkward to add with the current function signature though, maybe we could have two function signatures like this? (Using typescript syntax below just to show the parameter types)
```typescript
function orbitControl(sensitivityX?: number, sensitivityY?: number, sensitivityZ?: number)
function orbitControl(options?: {
  sensitivityX?: number
  sensitivityY?: number
  sensitivityZ?: number
  disableTouchActions?: boolean // defaults to true
})
```

That way, to use all the defaults but disable adding the extra CSS, one could call `orbitControl({ disableTouchActions: false })`. Can you think of any problems that might introduce? Or do you have other ideas to also get a better mobile experience by default?

**Comment by inaridarkfox4231** [comment]
I thought it would be good to add the following processing in the same way as other flagging processing.
```js
p5.prototype.orbitControl = function (sensitivityX, sensitivityY, sensitivityZ) {

  /* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

  if (this.touchActionsDisabled !== true) {
    this.canvas.style["touch-action"] = "none";
    this._setProperty('touchActionsDisabled', true);
  }
```
What if we separated by a flag whether to run this or not...?

How about adding a boolean representing disableTouchActions as a fourth argument? You have to write meaningless three 1s that set Sensitivity, but compatibility with the conventional way of writing is maintained. In the case of object notation, it is efficient because only the necessary parameters can be set, but the conventional way of writing does not work, so...

Also, no matter which style of writing I change to, I don't know what kind of code I should write to change the arguments, so there is also that kind of problem...

**Comment by inaridarkfox4231** [comment]
However, after thinking about various things, I couldn't think of any disadvantages to turning off the default action of touch when calling orbitControl. Since the behavior of opening the menu etc. is turned off, I feel that there is no particular problem even if the default behavior of touch is newly turned off...

**Comment by davepagurek** [comment]
I think having it as a fourth argument instead of having a separate overload with different parameters can work. How do you feel about still having the fourth parameter be an options object though, instead of just a boolean?

The idea would be to have an interface [similar to `saveGif`](https://p5js.org/reference/#/p5/saveGif) or [`textToPoints`](https://p5js.org/reference/#/p5.Font/textToPoints) so that if, in the future, we decide to add more options, we don't end up with a really long arguments list [like we have for `image()`.](https://p5js.org/reference/#/p5/image) For now it would mean the options object only has one option in it though.

**Comment by inaridarkfox4231** [comment]
Okay, the first three are Sensitivity variables, and the fourth argument is an option object. In that case, there is certainly backward compatibility, and it is more convenient to add options in the future. I would like to.

What would it look like...
```js
p5.prototype.orbitControl = function (sensitivityX, sensitivityY, sensitivityZ, options) {
  /* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

  if (this.touchActionsDisabled !== true && options.disableTouchActions) {
    this.canvas.style["touch-action"] = "none";
    this._setProperty('touchActionsDisabled', true);
  }
```
I thought it would be better to write it like this because disabling processing is enough once...

If so, do I need to add a note to this section?
```js
  /**
 * @method orbitControl
 * @for p5
 * @param  {Number} [sensitivityX] sensitivity to mouse movement along X axis
 * @param  {Number} [sensitivityY] sensitivity to mouse movement along Y axis
 * @param  {Number} [sensitivityZ] sensitivity to scroll movement along Z axis
 * @param  {Object} [options] An optional object that can contain two more arguments,
 *  disableTouchActions, disable default touch actions.
 * @chainable
 * @example
 */
```
Should I add something like this...or is there another place to add it?

**Comment by inaridarkfox4231** [comment]
How about something like this...?
```js
  /**
 * @param  {Object} [options] An optional object that can contain two more arguments,
 * disableTouchActions - Boolean, default value is true.
 * It's supposed to be disabled by default, but if you're already doing it via css
 * or want the default touch actions, consider the non-disabled option.
 */
```

Also, regarding validation of options, there was a function like this in textToPoints(), but should I prepare the same one...?
```js
function parseOpts(options, defaults) {
  if (_typeof(options) !== 'object') {
    options = defaults;
  } else {
    for (var key in defaults) {
      if (typeof options[key] === 'undefined') {
        options[key] = defaults[key];
      }
    }
  }
  return options;
}
```
However, if there are few properties, I feel like I can write it directly.

**Comment by davepagurek** [comment]
Maybe instead of "It's supposed to be disabled by default" we can say something like "Disabling prevents accidental interactions with the page while orbiting" (assuming that's the reason for disabling)? Also, instead of "that can contain two more arguments" maybe we can say "that can contain additional settings" so that we don't need to update the number when we add options.

> Also, regarding validation of options, there was a function like this in textToPoints(), but should I prepare the same one...?

Since we use Babel, we can maybe use JS default values and destructuring:

```js
if (typeof options !== 'object') {
  options = {};
}
const { disableTouchActions = true } = options;
```

**Comment by inaridarkfox4231** [comment]
Well, I should have explained why...How about this?

```js
  /**
 * @param  {Object} [options] An optional object that can contain additional settings,
 * disableTouchActions - Boolean, default value is true.
 * Because by setting this to true, it prevents accidental interactions with the page
 * while orbiting, makes mobile interactions smoother. But if you're already doing it
 * via css or want the default touch actions, consider setting it to false.
 */
```

There is such a way of writing! I saw it for the first time...I wonder if it will be like this.
```js
  if (typeof options !== 'object') {
    options = {};
  }
  const { disableTouchActions = true } = options;

  if (this.touchActionsDisabled !== true && disableTouchActions) {
    this.canvas.style["touch-action"] = "none";
    this._setProperty('touchActionsDisabled', true);
  }
```

**Comment by davepagurek** [comment]
That all looks good to me! My only (super minor) suggestion, just to make the sentence flow a little more nicely, would be to slightly rearrange the sentence: "Setting this to true makes mobile interactions smoother by preventing accidental interactions with the page while orbiting."

**Comment by davepagurek** [comment]
All of that looks good!

**Comment by davepagurek** [comment]
Sounds good, I'll assign this to you! I think the doc comment right above the `orbitControl` function is the only thing we'll need to edit.
