### ISSUE TITLE
Actions disallowed when viewed via file: scheme should trigger an alert

### ISSUE THREAD

**Issue by brysonian** [processing/p5.js#612]
I've had a couple of students who just can't remember that they need to use a server to view their code and they just bang their heads trying to load images. Maybe there should be an alert when loadImage (and whichever other functions) are unavailable because of not using http(s).

**Comment by lmccart** [comment]
I think this is a great idea. Or at least an error in console.

**Comment by lmccart** [comment]
closed with https://github.com/processing/p5.js/pull/717
