### ISSUE TITLE
Avoid using strokeIndices and use edges directly, when creating the geometry

### ISSUE THREAD

**Issue by inaridarkfox4231** [processing/p5.js#6120]
### Topic

Currently, when trying to create an edge-only geometry with p5.Geometry, I'm having problems with edges not being drawn.

```js
let geom;

function setup() {
  createCanvas(400, 400, WEBGL);

  geom = new p5.Geometry();
  geom.gid = "mySquare";
  const v = (x, y, z) => createVector(x, y, z);
  geom.vertices.push(v(-100, -100, 0));
  geom.vertices.push(v(100, -100, 0));
  geom.vertices.push(v(100, 100, 0));
  geom.vertices.push(v(-100, 100, 0));
  geom.edges.push([0, 1], [1, 2], [2, 3], [3, 0]);

  geom.computeNormals();

  background(0);
  noFill();
  strokeWeight(3);
  stroke("lime");
  model(geom);
}
```
## current output / expected output:

![current](https://user-images.githubusercontent.com/39549290/235022619-c0124c61-3dde-4f77-8d85-e7ce31823f91.png)

This is because _makeTriangleEdges() is always executed inside the model function. This function always discards the array of edges, so even if edges are prepared in advance, the contents will be discarded. And it is calculated based on faces, but since there are no faces, the edges also disappear.

```js
  _makeTriangleEdges() {
    this.edges.length = 0;
    if (Array.isArray(this.strokeIndices)) {
      for (let i = 0, max = this.strokeIndices.length; i < max; i++) {
        this.edges.push(this.strokeIndices[i]);
      }
    } else {
      for (let j = 0; j < this.faces.length; j++) {
        this.edges.push([this.faces[j][0], this.faces[j][1]]);
        this.edges.push([this.faces[j][1], this.faces[j][2]]);
        this.edges.push([this.faces[j][2], this.faces[j][0]]);
      }
    }
    return this;
  }
```
In addition, edges are always overwritten with edges computed based on faces after the edges are prepared beforehand. Therefore, there is also the problem that the configuration of edges cannot be freely determined.

However, some functions such as rect and arc construct edges that are not based on faces. As you can see from the specification of _makeTriangleEdges() above, this is achieved using an array called strokeIndices.
This _makeTriangleEdges() function, if the geometry has an array type property called strokeIndices, reads it as edges as it is. It uses faces to compose edges when it doesn't have strokeIndices.

However, I think this is a wasteful process. It should be fine because it does nothing if edges are configured from the beginning. In addition, strokeIndices are not provided when p5.Geometry is initialized, so we purposely provide them in the form of a new array during construction. This is not a very natural process.

Of course, there is also a way to prepare strokeIndices as a property at initialization, but it is unnecessary if edges are sufficient. Or you could force p5.Geometry users to use an array of strokeIndices, but that would be inconvenient.

So, I propose to abolish the strokeIndices currently used in rect, arc, box, and triangle and replace them with edges, and also make _makeTriangleEdges do nothing if the length of edges is positive.

```js
p5.Geometry.prototype._makeTriangleEdges = function () {
  //this.edges.length = 0;
  
  //if (Array.isArray(this.strokeIndices)) {
 //   for (var i = 0, max = this.strokeIndices.length; i < max; i++) {
  //    this.edges.push(this.strokeIndices[i]);
 //   }
 // } else {
  if (this.edges.length === 0) {
    for (var j = 0; j < this.faces.length; j++) {
      this.edges.push([this.faces[j][0],
      this.faces[j][1]]);
      this.edges.push([this.faces[j][1],
      this.faces[j][2]]);
      this.edges.push([this.faces[j][2],
      this.faces[j][0]]);
    }
  }
  return this;
};
```

For example, here in the box looks like this:
```js
      //using strokeIndices instead of faces for strokes
      //to avoid diagonal stroke lines across face of box
      this.edges = [
        [0, 1],
        [1, 3],
        [3, 2],
        [6, 7],
        [8, 9],
        [9, 11],
        [14, 15],
        [16, 17],
        [17, 19],
        [18, 19],
        [20, 21],
        [22, 23]
      ];
```

I made a patch that implements these and the edges are drawn without any problem.
[patch_model](https://editor.p5js.org/dark_fox/sketches/lxAi3Levh)

```js
function setup(){
  createCanvas(600, 600, WEBGL);
  stroke(255);
  fill(128, 64, 32);
  strokeWeight(3);
  background(0);

  rect(-60,-60,120,120);

  translate(0, 200, 0);
  arc(0, 0, 160, 160, 0, PI*1.5, PIE, 40);
  
  translate(200, -200);
  rotateX(PI*0.3);
  box(80);
  resetMatrix();

  translate(0, -200, 0);
  triangle(0, 0, 100, -100, 100, 100);

  translate(-200, 200);
  sphere(100);
}
```

![gottani](https://user-images.githubusercontent.com/39549290/235028586-8c856120-e3f2-4978-92e6-1d45220f6d58.png)

So I would like to do it that way, but if there is a serious reason to use strokeIndices, this suggestion may be inappropriate.

**Comment by inaridarkfox4231** [comment]
Alternatively, it may be smarter to change as follows and not call it in the first place if you prepare edges yourself.

```js
p5.Geometry.prototype._makeTriangleEdges = function () {
  this.edges.length = 0; // may not be necessary...

  for (var j = 0; j < this.faces.length; j++) {
    this.edges.push([this.faces[j][0],
    this.faces[j][1]]);
    this.edges.push([this.faces[j][1],
    this.faces[j][2]]);
    this.edges.push([this.faces[j][2],
    this.faces[j][0]]);
  }

  return this;
};
```

In this case, even in the model function, it is necessary to change the specifications so that _makeTriangleEdges() is not called when the length of edges is positive.
```js
p5.prototype.model = function(model) {
  this._assert3d('model');
  p5._validateParameters('model', arguments);
  if (model.vertices.length > 0) {
    if (!this._renderer.geometryInHash(model.gid)) {

      if (model.edges.length === 0) {
        model._makeTriangleEdges();
      }

      model._edgesToVertices();
      this._renderer.createBuffers(model.gid, model);
    }

    this._renderer.drawBuffers(model.gid);
  }
};
```

**Comment by davepagurek** [comment]
I think this is a good idea, I also ran into the same issue as you in the past! I like the simplicity of directly using the `edges` data structure instead of having two different ways of creating edges (`edges` and `strokeIndices`.) Since neither interface is publicly documented, I wouldn't consider removing `strokeIndices` as a breaking change -- I also mentioned on Twitter, but ideally in the future our main public API would be using existing immediate mode commands (https://github.com/processing/p5.js/issues/5393) so that this advanced API would be mostly for internal usage anyway.

**Comment by inaridarkfox4231** [comment]
Well, it may not make much sense to fix this inconsistency... However, since I don't know when the API will be formulated, I would like to fix it for the time being, so I would like to create a pull request with the following content:

- replace "strokeIndices" with "edges" in arc, box, triangle, rect and avoid calling _makeTriangleEdges()
- In _makeTriangleEdges(), omit the processing performed for strokeIndices
- In model(), construct edges from faces only when edges.length is 0.

I think it would be confusing if there are two ways to define edges when creating an API, so I think it's not a waste to combine them.

**Comment by davepagurek** [comment]
agreed, consolidating to just `edges` sounds good! I'll assign this to you.
