### ISSUE TITLE
The problem that lights() is not able to specify gray properly

### ISSUE THREAD

**Issue by inaridarkfox4231** [processing/p5.js#6127]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [X] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

1.6.0

### Web browser and version

Chrome

### Operating System

Windows11

### Steps:
1. Specify colorMode(RGB,1);
2. Using lights() in webgl
3. The color of the cube becomes pure white instead of gray.

### Snippet:

```js
function setup() {
  createCanvas(400, 400, WEBGL);
  background(255);
  colorMode(RGB, 1);
  lights();
  rotateX(PI/3);
  rotateY(PI/3);
  box(100);
}
```
![lights_bug1](https://user-images.githubusercontent.com/39549290/235650822-cee519d1-a8d0-47da-a63c-53a760066ff7.png)

```js
function setup() {
  createCanvas(400, 400, WEBGL);
  background(255);
  colorMode(RGB, 512);
  lights();
  rotateX(PI/3);
  rotateY(PI/3);
  box(100);
}
```
![lights_bug2](https://user-images.githubusercontent.com/39549290/235650944-c916b391-3ae9-4c38-8232-b615a65f469d.png)

This is caused by not considering the upper limit specified by colorMode() when specifying gray.
In addition, in the case of HSB and HSL, the maximum value is applied, but with this it becomes pure white.
```js
p5.prototype.lights = function() {
  this._assert3d('lights');
  // only restore the colorMode to default if it is not in default already
  if (this._colorMode === constants.RGB) {
    this.ambientLight(128, 128, 128);
    this.directionalLight(128, 128, 128, 0, 0, -1);
  } else {
    const maxBright = this._colorMaxes[this._colorMode][2];
    this.ambientLight(0, 0, maxBright);
    this.directionalLight(0, 0, maxBright, 0, 0, -1);
  }
  return this;
};
```

This problem can be solved by explicitly specifying the color to be specified in RGB as follows.
```js
p5.prototype.lights = function() {
  this._assert3d('lights');
  // Both specify gray by default.
  const grayColor = color("rgb(128,128,128)");
  this.ambientLight(grayColor);
  this.directionalLight(grayColor, 0, 0, -1);
  return this;
};
```

**Comment by davepagurek** [comment]
Good catch!
