### ISSUE TITLE
Problem with p5.Element.size() in Chrome/Chromium

### ISSUE THREAD

**Issue by xiatianyu** [processing/p5.js#613]
After trying out [this example](https://github.com/processing/p5.js/wiki/Beyond-the-canvas#user-content-creating-html-images) from the *Beyond the Canvas* tutorial, I discovered that setting either the width or height argument of the [`p5.Element.size()`](http://p5js.org/reference/#/p5.Element/size) function to `AUTO` renders the affected `<img>` element invisible :see_no_evil: in Chrome or Chromium, though everything works fine in Firefox. The failed tests were made in Chrome Version 42.0.2311.135 /w Windows 8.1 Pro (64-bit) and Chromium Version 41.0.2272.76 /w Ubuntu 14.10 (64-bit). Viewing the elements using the Chrome DevTools discloses the reason behind: whichever argument set to `AUTO` actually becomes zero. That is, following the aforementioned example and calling `img.size(200, AUTO);` will result in an `<img>` element with `width="200" height="0"`.

**Comment by NPN** [comment]
When ```img.set(200, AUTO)``` is called, ```img``` is still loading so both ```height``` and ```width``` are zero. Trying to scale a ```0x0``` pixel picture results in the height getting set to ```NaNpx```, which is basically ```0px```.

```createImg``` should allow a callback function to be passed in so it's possible to know when the image is loaded and ready to be used (see #561 and #578).

**Comment by lmccart** [comment]
closed with https://github.com/processing/p5.js/commit/9015ffe3eab19c155e42a1dc7be381974fc689be

**Comment by freder** [comment]
@lmccart @futuremarc 
this only works though if the `alt` argument is provided, which should be optional.

**Comment by futuremarc** [comment]
Hey that's a good call. I'll add support for this

**Comment by futuremarc** [comment]
Actually, you can pass in a function to either the 1st or 2nd arg, so you dont need to provide an `alt` tag

**Comment by freder** [comment]
oh, my bad: updated only p5.js and not p5.dom.js — so I was using an older version.
