### ISSUE TITLE
Allow for objects to be sorted if first element of object is a sortable value.

### ISSUE THREAD

**Issue by thecodingcookery** [processing/p5.js#6136]
### Increasing Access

I think that it may be helpful to allow for objects to be sorted if the first element of the object is a sortable value. Like if you wanted to sort an array of objects and each object has an ID. 

### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [X] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### Feature request details

Maybe it could look something like this:

```
let arr = ["def", "abc", "ghi"];
let arr2 = [{name: "def"}, {name: "abc"}, {name: "ghi"}];
let arr3 = [{id: 23}, {id: 15}, {id: 5}];

function setup() {
  
  // Words
  console.log(arr);
  arr.sort();
  console.log(arr);
  
  // Objects with text
  console.log(arr2);
  arr2.sort();
  console.log(arr2);
  
  // Objects with ids
  console.log(arr3);
  arr2.sort();
  console.log(arr3);
  
  }
```

This may be confusing for some people, so perhaps instead of that we could have a different function if necessary?:

```
 arr2.sortObjects();
 arr3.sortObjects();
```

EDIT: Actually, now that I think about it, the sort function is part of JavaScript. So maybe it could be this:

```
 sortObjects(arr2);
 sortObjects(arr3);
```

Or:
```
 sortObjects(arr2, "id");
 sortObjects(arr3, "id");
```

**Comment by limzykenneth** [comment]
Object property ordering in JS is quite complex and also not uniform in terms of specification versions, built in functions support, and browser implementation, so it is usually best practice to not rely on object properties having any sort of fixed order, especially given that sometimes the first property we get is not necessarily the first element set in the object (eg. sometimes they are sorted alphabetically). 

Which is a long way to say there isn't really an idea of first element of an object in Javascript so we cannot sort array of objects that way with consistency. With this kind of sorting need, it is recommended to use the native array sort function with a comparator callback function: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort.

Do note that the p5.js `sort()` function has been deprecated in favour of the native JS sort function mentioned above which provides more flexibility and usability. Do have a try using that instead.
