### ISSUE TITLE
_orbit() inside orbitControl() rewrites the up vector information of the camera

### ISSUE THREAD

**Issue by inaridarkfox4231** [processing/p5.js#6147]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

latest version

### Web browser and version

Microsoft Edge

### Operating System

Windows11

### Steps:
1. set camera(400, 400, 400, 0, 0, 0, 0, 0, -1), set the up vector in the negative z direction
2. Write a simple code that draws a plane parallel to the xy plane and a cube on it
3. I expect to rotate around the z-axis, but the up vector is rewritten to rotate around the y-axis.

### Snippet:

```js

function setup(){
  createCanvas(windowWidth, windowHeight, WEBGL);
  camera(400, 400, 400, 0, 0, 0, 0, 0, -1);
}
function draw(){
  background(0);
  orbitControl();
  noStroke();
  lights();
  plane(400);
  translate(0, 0, 100);
  box(90);
  debugMode(AXES);
}
```

https://github.com/processing/p5.js/assets/39549290/ab31d147-29b5-432b-bcde-8b09fd8c4146

The cause is that _orbit() was written assuming the camera's up vector is parallel to the y-axis.
So even if you prepare a camera whose up vector is not parallel to the y-axis, calling orbitControl() will force the up vector to be rewritten.

[_orbit()](https://github.com/processing/p5.js/blob/main/src/webgl/p5.Camera.js#L1719)
```js
  this.camera(
    _x + this.centerX,
    _y + this.centerY,
    _z + this.centerZ,
    this.centerX,
    this.centerY,
    this.centerZ,
    0,
    newUpY,
    0
  );
```

This is inconvenient. This is because you may want to draw your sketch with the z-axis as the direction of gravity. When specifying a point on the plane, if this is the xz plane or zx plane, it is inconvenient to insert an extra 0 between them.

Also, for example, in school classes, we are familiar with the composition of the xy plane and the z axis extending perpendicular to it, but in that case it would be more natural to be able to rotate around the z axis.

In the meantime, even in the sketch that draws the plane and the cube prepared in the revision of orbitControl(), it purposely calls rotateX(PI/2) so that the plane rotates in the horizontal direction. It is inconvenient that the rotation axis is fixed.
[newOrbitControl](https://openprocessing.org/sketch/1924658)
```js
function draw() {
  orbitControl();

  background(0);
  const mat = this._renderer.uMVMatrix.mat4;
  directionalLight(color("white"), -mat[2], -mat[6], -mat[10]);
  ambientLight(64);
  specularMaterial(64);
  shininess(40);
  
  rotateX(PI/2); // rotateX is called
  fill("red");
  plane(200);
  fill("orange");
  box(80);
}
```

But it's already fixed. Check out the demo below.
[tou_fu](https://openprocessing.org/sketch/1929184)

https://github.com/processing/p5.js/assets/39549290/a1beedc7-2d2c-4bae-ad53-6e65364b97be

Using debug mode makes it easier to understand that the negative direction of the z-axis is the up vector. The direction of rotation for horizontal operation by orbitControl() is perpendicular to the z-axis. Even with the up vector, it is only multiplied by -1 in vertical rotation, and does not change any further.

Here is the code.
```js
p5.Camera.prototype._orbit = function (dTheta, dPhi, dRadius) {
  // Calculate the vector and its magnitude from the center to the viewpoint
  const diffX = this.eyeX - this.centerX;
  const diffY = this.eyeY - this.centerY;
  const diffZ = this.eyeZ - this.centerZ;
  let camRadius = Math.hypot(diffX, diffY, diffZ);
  // front vector.
  const front = new p5.Vector(diffX, diffY, diffZ).normalize();
  // up vector.
  const up = new p5.Vector(this.upX, this.upY, this.upZ).normalize(); // y-axis
  // side vector. (Right when viewed from the front)
  const side = new p5.Vector.cross(up, front).normalize(); // x-axis
  // verticalVector.
  const vertical = new p5.Vector.cross(side, up).normalize(); // z-axis
  // calculate camPhi (Rise angle when up is regarded as 0)
  let camPhi = Math.acos(Math.max(-1, Math.min(1, p5.Vector.dot(front, up))));
  // calculate camTheta (The amount of rotation in the direction of side when vertical is 0)
  let camTheta = Math.atan2(p5.Vector.dot(front, side), p5.Vector.dot(front, vertical));

  // update camRadius
  camRadius *= Math.pow(10, dRadius);
  // prevent zooming through the center:
  if (camRadius < this.cameraNear) {
    camRadius = this.cameraNear;
  }
  if (camRadius > this.cameraFar) {
    camRadius = this.cameraFar;
  }

  // update eye vector
  camTheta += dTheta;
  camPhi += dPhi;
  front.x = up.x * cos(camPhi) + (vertical.x * cos(camTheta) + side.x * sin(camTheta)) * sin(camPhi);
  front.y = up.y * cos(camPhi) + (vertical.y * cos(camTheta) + side.y * sin(camTheta)) * sin(camPhi);
  front.z = up.z * cos(camPhi) + (vertical.z * cos(camTheta) + side.z * sin(camTheta)) * sin(camPhi);
  this.eyeX = camRadius * front.x + this.centerX;
  this.eyeY = camRadius * front.y + this.centerY;
  this.eyeZ = camRadius * front.z + this.centerZ;

  // update up vector
  if(camPhi <= 0 || camPhi >= Math.PI){
    up.mult(-1);
  }

  // update camera
  this.camera(
    this.eyeX, this.eyeY, this.eyeZ,
    this.centerX, this.centerY, this.centerZ,
    up.x, up.y, up.z
  );
};
```

An orthonormal basis is constructed from the front vector, which is the normalization of the vector directed from the center to the viewpoint, and the up vector of the camera, and the position of the viewpoint and the up vector are updated based on this. This just multiplies the up vector by plus or minus 1, leaving the axis unchanged.

I would like to create a pull request with this content. I would like to receive a review as there may be some shortcomings in my code.

**Comment by inaridarkfox4231** [comment]
I understand that this may change the behavior of some sketches.
It changes the behavior when using orbitControl() when the camera's up vector is not the default, so of course the behavior will change in such cases.
However, I don't think the user would want the behavior of the up vector being rewritten the moment orbitControl() is executed, causing the field of view to change unnaturally, so I decided to propose this.

I also understand that the specification of _orbit() will be rewritten, so some unit test results will need to be changed.

**Comment by davepagurek** [comment]
> I understand that this may change the behavior of some sketches.

I think if we preserve the behaviour of being able to spin end over end in all axes, then this is a worthwhile change! I think you're probably right about the current behaviour for other up vectors to not necessarily be the most desired.

I haven't looked at your code examples yet to check the math everything, I'll take a closer look when I get the chance, but I agree with your idea so feel free to make a PR for this in the mean time!

**Comment by inaridarkfox4231** [comment]
I didn't explain enough, so I would like to supplement.

What I want to do is fix the behavior that the up vector is rewritten unnaturally. I am not going to do more than that.

The assumed case is also the default, or only when the up vector is parallel to the z-axis. However, no matter what the up vector is (of course you can't choose a direction parallel to the line of sight), I think it will behave naturally.

I would like to create a pull request.
If I need to change more than what is implemented here, I will consider it again. However, as long as this specification change does not affect the behavior using the default camera at all, I think there is no problem in passing this..

**Comment by inaridarkfox4231** [comment]
> I understand that this may change the behavior of some sketches.

When I say that some sketches are affected, this means that any sketch that uses a camera that is not the default camera and that uses an up vector that is not parallel to the y-axis will be affected.

And what happens when you run orbitControl() on such a sketch now is that in the first frame the up vector gets corrupted and the view changes unnaturally like in that demo. I don't think users want this, so I want to fix it, that's all.

**Comment by inaridarkfox4231** [comment]
There was a fatal bug that copy() did not copy upX, upY, upZ, so I will fix it.

What I felt after modifying orbitControl() so far is that there are too many specifications for the camera that are based on the default situation, and I think that it has lost its flexibility.

Of course there are not that many cases. It would be about the case where the bottom of the z-axis is the bottom. The problem is that it cannot be handled.

**Comment by inaridarkfox4231** [comment]
I had a misunderstanding. We haven't messed with the default camera behavior, so I may not need to change your existing unit tests.
(might get an error about the difference between 0 and -0, but...)
I'd also add a test to make sure that _orbit() doesn't rewrite the up vector parallel to the y-axis.
