### ISSUE TITLE
CSP violation `unsafe-eval`

### ISSUE THREAD

**Issue by unindented** [processing/p5.js#6151]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [X] Other (specify if possible)

### p5.js version

1.6.0

### Web browser and version

Any browser

### Operating System

Any OS

### Steps:

1. Configure a website to emit Content Security Policy headers that don't allow `unsafe-eval`
2. Include p5.js v1.6.0 in one of the pages
3. See the following error:

```
Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy: "script-src 'self'".
```

<img width="792" alt="Screenshot 2023-05-20 at 08 29 20" src="https://github.com/processing/p5.js/assets/69485/90882576-bcad-4a4f-af01-af7a58a7af27">

### Snippet:

N/A

**Comment by davepagurek** [comment]
It looks like this is part of the innards of Babel: https://stackoverflow.com/q/65191809 The comments in this StackOverflow mention either moving away from Babel or find-and-replacing this bit of code away (which also sounds kind of brittle and maybe not something we want to do.) I'm guessing for now we also aren't really able to move away from Babel, so maybe we should table this issue for now and be aware of it if we ever consider other build processes. I'm going to close this issue for now for organizational purposes but let me know if I missed anything or you find any new information that might make this more feasible to fix in the short term!

**Comment by limzykenneth** [comment]
I plan on revisiting the builds for both p5.js and p5.sound.js when I have a bit more time (read a month or two later), might look into this when I do so as well.
