### ISSUE TITLE
Failing test: "Files p5.prototype.loadJSON should allow json to override jsonp in 3rd param"

### ISSUE THREAD

**Issue by dhowe** [processing/p5.js#616]
I may have things setup incorrectly, but I get the error below when I try to run the tests via 'grunt mocha'. My guess was that google was rejecting the userAgent (it runs ok from the browser), but I wasn't able to confirm this. When I grab the json manually from google and load if from a file ('http://localhost:9001/unit/input/google.json'), the test is ok.

````
$ grunt mocha
Running "mocha:test" (mocha) task
Testing: test/test.html
  
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․

  269 passing (2s)
  1 failing

  1) Files p5.prototype.loadJSON should allow json to override jsonp in 3rd param:
     timeout of 2000ms exceeded

>> 1/270 tests failed (2.49s)
Warning: Task "mocha:test" failed. Use --force to continue.

Aborted due to warnings.

````

**Comment by dhowe** [comment]
When I run via the browser, I get different errors:

![screen shot 2015-05-09 at 5 25 19 pm](https://cloud.githubusercontent.com/assets/737638/7549633/9700a3e0-f670-11e4-9b68-1e17bf45d139.png)

**Comment by lmccart** [comment]
Hm, it could just be [this test](https://github.com/processing/p5.js/blob/master/test/unit/input/files.js#L62). I've noticed it sometimes fails when there's a slow internet connection because it's hitting an external server. If you comment this one out, does it work correctly? If so, I'd suggest doing that and making a note that we need to make a better test for jsonp.

**Comment by dhowe** [comment]
Yes, I saw that... and as I said, it runs OK in the browser, which together with the fact that I have a 300mb line here, makes me think its not the speed. I tried increasing the timeout and changing the userAgent in the Gruntfile, but neither seemed to work:
````
    mocha: {
      test: {
        src: ['test/**/*.html'],
        options: {
          reporter: reporter,
          run: true,
          log: true,
          logErrors: true,
          timeout: 5000,
          page: { 
             settings: { 
                 userAgent: 'Mozilla...',
             },  
           }, 
        }
      },
    },
````
Any thoughts on this?

**Comment by lmccart** [comment]
hm, digging into it more, could it be this change:
https://github.com/processing/p5.js/blob/master/src/input/files.js#L97

looks like previously it would have defaulted to jsonp with the https in the url, but now it defaults always to json. perhaps coming from the browser vs from the tests reacts differently to this? we could return to the previous json vs jsonp test, I forget why exactly it was taken out.

**Comment by dhowe** [comment]
not a big deal, just wanted to make sure I was setup correctly...  also, starting the connect server is necessary before running 'grunt mocha', yes? if so, I will update the readme and submit a pull

**Comment by lmccart** [comment]
hm, starting the connect server?

**Comment by lmccart** [comment]
also -- I've never run `grunt mocha`, I usually run `grunt` or `grunt test`. I just tried running `grunt mocha` and noticed that this fails, though the other two work.

**Comment by dhowe** [comment]
I think you need to add a #4 to the directions:
````
...
3. Link to the src and test files in `test.html`. 
4. Run the connect server. ```grunt connect -keepalive```
5. Run the tests with `grunt mocha`.

**Comment by lmccart** [comment]
hm, I've never had to run the connect server, I wonder why. perhaps it would be good to add this step as optional, to be tried if step 5 fails?

**Comment by dhowe** [comment]
I think 'grunt test' starts the server automatically, while 'grunt mocha' doesn't.. so either way fixes it :)

**Comment by lmccart** [comment]
aha I see. ok I think we're set then with the updated `grunt test` line in the docs. thanks for catching this, sorry for the trouble.
