### ISSUE TITLE
Chinese translation in Reference pages

### ISSUE THREAD

**Issue by OCCOHOCOREX** [processing/p5.js#6161]
### Topic

Hi everyone.
I am going to contribute sth for Chinece translation. Has anyone encount any bad or wrong translation in reference? Please inform me. 
For example, bad Chinese description of a function, or incorrect translation.
Thanks.

**Comment by Qianqianye** [comment]
Thanks @OCCOHOCOREX for offering help. We are currently working on a project to reorganize and update the p5.js documentations, so we will temporarily pause the translation effort for the Reference page until the documentation update is complete. To avoid any confusion, I will close this issue for now. We will revisit the issues labeled '[Documentation](https://github.com/processing/p5.js/labels/Documentation)' or open a new issue about translation helps we need later.

Please feel free to browse other [open issues](https://github.com/processing/p5.js/issues) and see if there is anything you'd like to help with. If you need help with any issues that you'd like to work on, please let us know in a comment within the respective issue. Thanks!
