### ISSUE TITLE
Problem with loadImage() from version 0.10.0 onwards

### ISSUE THREAD

**Issue by piecesofuk** [processing/p5.js#6164]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [X] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [X] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

0.10.0 and later

### Web browser and version

Chrome Version 113.0.5672.134 (Official Build) (64-bit)

### Operating System

Google Chrome OS Version 113.0.5672.134 (Official Build) (64-bit)

### Steps:
I was checking some of my old sketches from a few years back which load images from Wikimedia Commons. They were working fine: the sketch rendered the images to the canvas. But when I updated p5 to the latest version no images were rendered. I narrowed it down to the problem occurring between releases 0.9.0 and 0.10.0. Any release 0.9.0 and earlier works fine and the images are rendered; any release from 0.10.0 onwards and the images are not rendered.
Here's a [basic sketch that demonstrates the problem](https://editor.p5js.org/piecesofuk/sketches/stgrFjOcY). If p5.js version 0.9.0 is used then a dog is rendered to the canvas, if the version is changed to 0.10.0 (in index.html) or later nothing appears, the p5 code...

### Snippet:

```js

let img;

function preload() {
  img = loadImage("https://upload.wikimedia.org/wikipedia/commons/1/13/Icon_bicolour_dog.gif");
}
function setup() {
  createCanvas(400, 400);
}

function draw() {
  background(img);
}
```

**Comment by limzykenneth** [comment]
I think this may have to do with the GIF loading change to support animated GIFs. @stalgiag Perhaps you can have a look?

**Comment by stalgiag** [comment]
Wow! I could've sworn we had a way of handling static images. It is hard for me to believe that after dozens of contributors writing and reviewing code for animated gif support, no one thought to test a static GIF.

None of the GIF methods are relevant for a single-frame GIF so ideally, [the code on this path should be executed](https://github.com/processing/p5.js/blob/e4f9d6eca9cee63708e31363002c2513f6a3cdbf/src/image/loading_displaying.js#L113) if there is only one frame.  This should be possible with some rearranging.

**Comment by ozramos** [comment]
Hi! Is anyone assigned to this? I would like to solve this as my first contribution!

**Comment by davepagurek** [comment]
Thanks @ozramos! I'll assign you.
