### ISSUE TITLE
Preload function seems broken for me

### ISSUE THREAD

**Issue by hanswillem** [processing/p5.js#617]
Hi, 

For me the preload function doesn't seem to get called. Am I missing something? I use the latest version of p5 (version 0.4.4 April 24, 2015). My code is here: https://goo.gl/0CvfUm

Grtz!

**Comment by therewasaguy** [comment]
Hey @hanswillem, looks like you spelled it "peload," it's just missing the "r"

**Comment by hanswillem** [comment]
The missing 'r' was a mistake on my side, but even with spelled as 'function preload', the function doesn't seem to work for me. Any ideas?

**Comment by hanswillem** [comment]
ahw... scratch that... fixed it.

Grtz!
