### ISSUE TITLE
Add a style guide for writing and code in the p5.js docs

### ISSUE THREAD

**Issue by nickmcintyre** [processing/p5.js#6178]
### Topic

Hello! I propose creating a style guide for written explanations and code snippets. My goal is to ensure that all Reference and Example pages are clear and consistent. I plan to edit the [Contributing Documentation](https://github.com/processing/p5.js/blob/main/contributor_docs/contributing_documentation.md) guide to include a remix of the [Ruby on Rails API documentation guidelines](https://guides.rubyonrails.org/api_documentation_guidelines.html).

# Writing

I'll follow the new writing style guide as I edit documentation over the coming months. The following references will be top of mind:

- Overview: [Write the Docs](https://www.writethedocs.org/)
- General: [Red Hat Supplementary Style Guide](https://redhat-documentation.github.io/supplementary-style-guide/)
- Accessibility: [MDN What is accessibility?](https://developer.mozilla.org/en-US/docs/Learn/Accessibility/What_is_accessibility)
- Reducing Bias: [WordPress Inclusivity](https://make.wordpress.org/docs/style-guide/general-guidelines/inclusivity/)

I'll use the [Hemingway Editor](https://hemingwayapp.com/) to ensure that the documentation uses simple language.

# Code

I propose following the [Airbnb JavaScript Style Guide](https://github.com/airbnb/javascript) for code snippets. I also plan to use [Prettier](https://prettier.io/) to format code so that it matches the output of the p5 Editor's "Tidy" button.

I'd love to incorporate folks' suggestions as I draft the style guide. @davepagurek @limzykenneth @Qianqianye @raclim what do y'all think about testing this idea in a couple of steps?  I can start by drafting the style guide. Then we can try an example of how the guide would change the Reference pages for 2D Primitives.

**Comment by Qianqianye** [comment]
Thanks @nickmcintyre for initiating this discussion. To share some context, Nick is the p5.js [2023 Season of Docs](https://medium.com/@ProcessingOrg/announcing-google-season-of-docs-2023-bd37736995ed) technical writer working on [improving the Reference and Example page](https://github.com/processing/p5.js/wiki/Season-of-Docs-2023-Organization-Application:-p5.js) on p5.js website. Nick will work with mentor @davepagurek and advisor [Jaleesa](https://twitter.com/JaleesaT) till the end of October this year.

I think it'd be great to include the style guide in the [contributor_docs](https://github.com/processing/p5.js/tree/main/contributor_docs) folder in this repo. The current [design_principles.md](https://github.com/processing/p5.js/blob/main/contributor_docs/design_principles.md) file might be a good reference for the style guide.

I will also invite @SableRaf to this discussion to share some style guide related experience from Processing. Thanks!

**Comment by limzykenneth** [comment]
@nickmcintyre A quick note before I look into the relevant parts more, prettier was previously included as part of our toolchain but has been deliberately removed because of several reasons. The first is that its very slow, especially on a larger codebase such as ours. The other reason is that some of its formatting rules create excessive noise in the codebase (eg. adding lots of brackets) and can make things very hard to read, ignoring selectively also adds a lot of noise throughout the codebase.

The alternative we go with is to use eslint-fix which also means we can have more control over details as well as using a tool we are already using without needing to bring in another one.

**Comment by davepagurek** [comment]
Thanks @nickmcintyre! I think those steps sound good. For @limzykenneth's point, maybe we can manually format the examples for now so we have to worry yet about updating project configuration.

**Comment by SableRaf** [comment]
Thanks @nickmcintyre for the writeup and great references! I'll ping @willybobilly who is working this GSoC on implementing friendlier error messages in Processing 4 as these are connected topics.

**Comment by SableRaf** [comment]
Thanks @nickmcintyre for the writeup and great references! I'll ping @WillRabalais04 who is working this GSoC on implementing friendlier error messages in Processing 4 as these are connected topics.

**Comment by nickmcintyre** [comment]
@limzykenneth I appreciate the context around tooling. I read through the [Steward Guidelines](https://github.com/processing/p5.js/blob/main/contributor_docs/steward_guidelines.md) and broke a few Reference samples to get a sense of how `npm run lint:samples` works. Glad this is already in place! I'll open a separate issue in the website repo for linting the [Examples](https://github.com/processing/p5.js-website/tree/main/src/data/examples/en).

And good suggestion @davepagurek. I'll code in the p5 Editor before running samples and examples through ESLint.

**Comment by nickmcintyre** [comment]
Resolved by #6206
