### ISSUE TITLE
Grunt yuidoc tests fail when running "npm test"

### ISSUE THREAD

**Issue by Ayush23Dash** [processing/p5.js#6181]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [X] Other (specify if possible)

### p5.js version

1.6.0

### Web browser and version

Google Chrome 113.0.5672.126 (Official Build) (arm64) 

### Operating System

MacOSX Version 13.2.1(Apple M2 Pro)

### Steps:
1. Clone p5.js repo
2. Run `npm ci`
3. Create a new branch from main
4.  Run `npm test`

### Snippet:

<img width="1139" alt="Screenshot 2023-06-04 at 3 42 23 PM" src="https://github.com/processing/p5.js/assets/40827680/8fdfcec7-a4d9-457b-84c8-39ede2bc63df">

### Note:
While initially setting up p5.js on local, we are not able to run it locally and set up p5.js locally in order to test our changes as one of the initial test fails.

**Comment by limzykenneth** [comment]
Hi, what is the node.js and npm versions you are using?

**Comment by Ayush23Dash** [comment]
Hi @limzykenneth :
Node Version : 18.16.0
Npm Version : 9.6.7

**Comment by limzykenneth** [comment]
I'm not able to replicate this, can you perhaps try running the setup on a different machine if you have access to one?

**Comment by Ayush23Dash** [comment]
Hey @limzykenneth , I tried it on an intel chip powered macbook and it compiled and ran as expected.
I opened an issue for discussion on the said problem [here](https://github.com/processing/p5.js/issues/6202).

**Comment by Qianqianye** [comment]
Thanks @Ayush23Dash and @limzykenneth. I will close this issue for now since we have continued the discussion at issue #6202.
