### ISSUE TITLE
WEBGL anti-aliasing different rendering results regarding anti-aliasing/alpha blending in latest p5.js version

### ISSUE THREAD

**Issue by mheesakkers** [processing/p5.js#6182]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

1.6.0

### Web browser and version

Chrome (Official Build) (x86_64) 

### Operating System

Mac 13.3.1 (a) 

### Steps to reproduce this

I created a [topic](https://discourse.processing.org/t/color-mixing-shader-produces-different-results-in-p5-js-editor-versus-local-environment/42133/3) about this on Processing's discourse about my problem because I thought I was doing something wrong.

In short. I created a shader program in the p5.js editor that does color mixing (also transparancy) using spectral.js. When I tried implementing that shader in my local project I got some weird anti-aliasing artefacts. After a lot of digging I saw that the online editor uses the p5.js 1.4.1 version and I was running the latest version 1.6.0 locally. Changing the library version to an older one resolved my issue.

**Result comparison (zoomed-in)**
![Bugfixing](https://github.com/processing/p5.js/assets/5702106/ff8c9f64-4398-4924-b08f-0242f59ce550)
On the left using p5.js 1.41, on the right p5.js version 1.6.0

See link to the program in the p5.js editor:
[Link to shader program in p5.js editor](https://editor.p5js.org/Misha.studio/sketches/tc1g8jhMr)

### Steps:
1. Go to index.html and change the p5.js version inside the head tag of index.html to 1.6.0
2. Run the sketch and see the anti-aliasing artefacts
3. Change the version back to 1.4.1
4. Run the sketch and see a nice and clean looking result

I'm not that technical so I could not provide where the culprit in the p5.js library would be or if this would be the expected behaviour. Hope this can be fixed in the latest version of p5.js.

**Comment by aferriss** [comment]
There were a few changes related to webGL alpha handling in the past 6mos, which may account for why you're not seeing the issue on older versions of p5. Probably something unintended found it's way in, blending is a difficult area to debug.

#5683 
#5917 
#5794 

Maybe @davepagurek can help to debug.

**Comment by aferriss** [comment]
Seems like this is likely a pre-multiplied alpha issue, so I think adding this line to the end of your shader might fix things, though we should still look into the root cause here.

`gl_FragColor.rgb /= 1.0/gl_FragColor.a;`

**Comment by aferriss** [comment]
I think this is likely a pre-multiplied alpha issue, so adding the following line to the end of your shader should hopefully fix things:
```
gl_FragColor.rgb /= 1.0/gl_FragColor.a;
```

We should definitely still look into why this is happening though.

**Comment by davepagurek** [comment]
Thanks @aferriss for the quick reply, this is indeed caused by premultiplied alpha!

In your sketch, if I switch to v1.6.0, it looks normal to me if I replace the end of your main routine with this:
```glsl
  if (col.a > 0.0) {
    col.rgb *= col.a;
    gl_FragColor = col;
  } else {
    discard;
  }
```

This was an intentional change introduced in https://github.com/processing/p5.js/pull/5917 to change the way we store colors on canvas. It unfortunately means that shaders written before that change will need to be updated to work with the new version, but as a consequence, alpha blending and antialiasing that was not able to work correctly before now is able to work, so we opted to make a breaking change in order to enable all those features to work in future versions.

**Comment by mheesakkers** [comment]
Thanks both (@davepagurek / @aferriss ) for the quick replies. I tried adding the multiplying by alpha to my shader using version 1.6.0. The result gets better but when I zoom-in the result is still different, a bit more jagged. See:
![Bugfixing 2](https://github.com/processing/p5.js/assets/5702106/f749354f-9028-413f-b820-02db3ce53e3f)

Link to sketch
https://editor.p5js.org/Misha.studio/sketches/w6YnJlHG7

**Comment by mheesakkers** [comment]
Thanks for diving into this and explaining what is happening! - I think I understand right now what's going on and indeed your proposed addition to the shader code gives a result that is closer to the 1.4.1 result. I think I stick to the 1.4.1 version for now because it's slightly smoother. Should I close this issue?
