### ISSUE TITLE
Make the value obtained by angleBetween() more accurate

### ISSUE THREAD

**Issue by inaridarkfox4231** [processing/p5.js#6204]
### Topic

I don't think this behavior is a bug, so I'm hesitant to raise an issue with a bug, so I'll call it Discussion.

In the calculation of angleBetween(), we use the value obtained by dividing the inner product by the product of the magnitudes. This may result in values ​​that are not exactly 1 or -1 when they should be. To prevent this, the current method uses to clamp at -1 and 1.

```js
p5.Vector.prototype.angleBetween = function angleBetween(v) {
  var dotmagmag = this.dot(v) / (this.mag() * v.mag());
  // Mathematically speaking: the dotmagmag variable will be between -1 and 1
  // inclusive. Practically though it could be slightly outside this range due
  // to floating-point rounding issues. This can make Math.acos return NaN.
  //
  // Solution: we'll clamp the value to the -1,1 range
  var angle;
  angle = Math.acos(Math.min(1, Math.max( - 1, dotmagmag)));
  angle = angle * Math.sign(this.cross(v).z || 1);
  if (this.isPInst) {
    angle = this._fromRadians(angle);
  }
  return angle;
};
```
However, this will work if it goes outside [-1,1], but not if it goes inside.

```js
  const v = createVector(219, 560);
  const w = createVector(-219, -560);
  console.log(v.angleBetween(w)); // 3.141592638688632, not accurate.
  console.log(Math.PI);           // 3.141592653589793
  v.set(288, 814);
  w.set(288, 814);
  console.log(v.angleBetween(w)); // 1.4901161193847656e-8, not zero.
```
Of course, if it is accurate to some extent, it can be used for practical use, so there is no problem, but I do not think it is desirable to produce inaccurate values ​​in calculations that clearly result in 0 or PI.

There are three ways to find the angle. A method using acos, a method using asin, and a method using atan2. In the case of acos, the value will be inaccurate near 0 or PI like this. There is also a method using asin, but it must divide cases by the sign of inner product, and the value will be inaccurate near PI/2.

So, I would like to suggest a way to use atan2.

```js
p5.Vector.prototype.angleBetween = function angleBetween(v) {
  const magSqMult = this.magSq() * v.magSq();
  // Returns NaN if either vector is the zero vector.
  if (magSqMult === 0) {
    return NaN;
  }
  const u = this.cross(v);
  // The dot product computes the cos value, and the cross product computes
  // the sin value. Find the angle based on them. In addition, in the case of
  // 2D vectors, a sign is added according to the direction of the vector.
  let angle = Math.atan2(u.mag(), this.dot(v)) * Math.sign(u.z || 1);
  if (this.isPInst) {
    angle = this._fromRadians(angle);
  }
  return angle;
};
```
This way, the values ​​will always be correct in cases where the angle is clearly 0 or PI. Also, you don't need to limit the values ​​with -1 or 1.
Regarding the calculation load, the calculation of mag(), which was twice, has been reduced to one. Also, the cross product calculation is used in the current specification, so there is no load difference there.

Also, in comparing the calculation results of calculating the angle with cos(t) and sin(t), this one is slightly better.
```js
function setup() {
  createCanvas(400, 400);
  
  let angle0IsTrue = 0;
  let angle1IsTrue = 0;
  const N = 2000;
  
  for(let i=0; i<N; i++){
    const v0 = createVector(1, 0);
    const v1 = createVector(cos(Math.PI*i/N), sin(Math.PI*i/N));
    const angle0 = v0.angleBetween(v1);
    const angle1 = v0.angleBetweenRemake(v1); // remake version
    if(angle0 === Math.PI*i/N) angle0IsTrue++;
    if(angle1 === Math.PI*i/N) angle1IsTrue++;
  }
  console.log("angle0: " + angle0IsTrue + ", angle1: " + angle1IsTrue);
  if(angle0IsTrue > angle1IsTrue){
    console.log("angle0 is win.");
  }else if(angle1IsTrue > angle0IsTrue){
    console.log("angle1 is win");
  }else{
    console.log("draw.");
  }
  // angle0: 1499, angle1: 1773 
  // angle1 is win
}
```
And, there is no particular reason to change the behavior when one of them is a zero vector, so we will continue to use NaN.

I would like to suggest this.

**Comment by inaridarkfox4231** [comment]
I'm not sure about the performance, but the only difference is that u is prepared as a const. If this is bad, should I calculate u.z directly?
Also, I'm not familiar with the difference in computation speed between acos and atan2.

**Comment by inaridarkfox4231** [comment]
Of course, there is no need to take magSq() originally. Because Math.atan2 has exception handling that makes Math.atan2(0,0) zero. But p5.js wants undefined values ​​to be NaN, so changing this would be a breaking change. This is calculated to avoid it.

**Comment by inaridarkfox4231** [comment]
Also, the last comparison was superfluous. It is not necessary because the error is so small that it does not matter at all in practice.

**Comment by inaridarkfox4231** [comment]
If the calculation speed of atan2 seems to be a problem, I think there is also a way to check the size of the cross product as follows so that the result is at least correct when the cross product is a zero vector.

In this case, if it becomes NaN, the result will be Math.PI unless it is checked first, so it is necessary to check in advance whether it will be NaN.

```js
p5.Vector.prototype.angleBetween = function angleBetween(v) {
  var dotmagmag = this.dot(v) / (this.mag() * v.mag());
  if (isNaN(dotmagmag)) return NaN;
  // Mathematically speaking: the dotmagmag variable will be between -1 and 1
  // inclusive. Practically though it could be slightly outside this range due
  // to floating-point rounding issues. This can make Math.acos return NaN.
  //
  // Solution: we'll clamp the value to the -1,1 range
  var angle;
  angle = Math.acos(Math.min(1, Math.max(-1, dotmagmag)));
  // If the cross product results in a zero vector, the result should always be 0 or PI,
  // so treat it as such.
  const u = this.cross(v);
  if (u.magSq() === 0) {
    angle = (angle < Math.PI * 0.5 ? 0 : Math.PI);
  }
  angle = angle * Math.sign(u.z || 1);
  if (this.isPInst) {
    angle = this._fromRadians(angle);
  }
  return angle;
};
```

It's unnatural not to return an exact value when it's obviously parallel, so I think it's necessary to make some modifications.

**Comment by inaridarkfox4231** [comment]
Personally, I think that atan2 is better because atan2 is more accurate, but it is difficult because calculation speed is also important.

**Comment by inaridarkfox4231** [comment]
I tested it.
First, prepare three types of angleBetween(). The original angleBetween(), angleBetween1() and angleBetween2().

angleBetween1() is a version that requires that the result be 0 or PI if the cross product is a zero vector.
```js
angleBetween1(v) {
  var dotmagmag = this.dot(v) / (this.mag() * v.mag());
  if (isNaN(dotmagmag)) return NaN;
  // Mathematically speaking: the dotmagmag variable will be between -1 and 1
  // inclusive. Practically though it could be slightly outside this range due
  // to floating-point rounding issues. This can make Math.acos return NaN.
  //
  // Solution: we'll clamp the value to the -1,1 range
  var angle;
  angle = Math.acos(Math.min(1, Math.max(-1, dotmagmag)));
  // If the cross product is a zero vector, the result should always be 0 or PI,
  // so treat it as such.
  const u = this.cross(v);
  if (u.magSq() === 0) {
    angle = (angle < Math.PI * 0.5 ? 0 : Math.PI);
  }
  angle = angle * Math.sign(u.z || 1);
  if (this.isPInst) {
    angle = this._fromRadians(angle);
  }
  return angle;
};
```

angleBetween2() uses atan2() to calculate the angle. It's what was suggested above in this issue.
```js
angleBetween2(v) {
  const magSqMult = this.magSq() * v.magSq();
  // Returns NaN if either vector is the zero vector.
  if (magSqMult === 0) {
    return NaN;
  }
  const u = this.cross(v);
  // The dot product computes the cos value, and the cross product computes
  // the sin value. Find the angle based on them. In addition, in the case of
  // 2D vectors, a sign is added according to the direction of the vector.
  let angle = Math.atan2(u.mag(), this.dot(v)) * Math.sign(u.z || 1);
  if (this.isPInst) {
    angle = this._fromRadians(angle);
  }
  return angle;
};
```

For each of these functions, we loop: Execute 10000 calculations 60 or 120 times and take the average, and compare them.

```js
let vectors = [];
let average = 0;
let counts = 0;

function setup() {
  createCanvas(400, 400);
  for(let i=0; i<20000; i++){
    vectors.push(p5.Vector.random3D());
  }
}
function draw(){
  for(let i=0; i<10000; i++){
    const v0 = vectors[i];
    const v1 = vectors[i+10000];
    const a = v0.angleBetween(v1);
    //const a = v0.angleBetween1(v1);
    //const a = v0.angleBetween2(v1);
  }
  average += frameRate();
  counts++;
  // 60 or 120.
  if(counts === 120){
    console.log(average/120);
    noLoop();
  }
}
```
Here are the results:

angleBetween():   60 times: 56.607274733844555,  120 times: 57.94693977484062
angleBetween1(): 60 times: 56.83747343968334,    120 times: 58.21694850715869
angleBetween2(): 60 times: 57.142751629274144,  120 times: 58.26010689846703

I think it's within the margin of error because it's done 10000 times. 100000 times or 1000000 times may be different, but I don't think there is much difference.

I don't think it will be significantly heavier.

In addition, the above calculation was executed without charging the computer carelessly.
After charging properly, I tested it only once in 100000 times. result:

angleBetween():   59.48053584022791
angleBetween1(): 59.38623156869184
angleBetween2(): 59.440992383693214

If the results are accurate even though there is not such a difference, I think it is better to adopt it.

**Comment by davepagurek** [comment]
Thanks for doing those tests, that's great that this one ends up fastest!
