### ISSUE TITLE
There are some broken DOM Extension tutorials

### ISSUE THREAD

**Issue by jshaw** [processing/p5.js#621]
There are some broken DOM Extension tutorials located in examples/tutorials/DOM-extensions. It looks as though they are using some deprecated functions. I am working my way thought them and updating to the current functions in the p5.dom.js addon. I will commit make a PR once these are updated.

**Comment by lmccart** [comment]
thanks!

**Comment by jshaw** [comment]
@lmccart I've gone through all DOM examples and fixed any outdated tutorials except ones which was using the global function "context" to change which "element" to reference since the last canvas draw. 

An example of this function all is in the /examples/tutorials/DOM-extensions/4/sketch.js. Has this function been renamed? I've tried looking through the commit history of the repo but couldn't find what i was looking for -- i assumed the naming was updated.

any guidance would be great, thanks!

**Comment by lmccart** [comment]
thanks @jshaw. the `context()` function has been removed completely as we no longer have the concept of (or support for) multiple drawing canvases in one sketch. all drawing commands will apply to the single, main canvas. in general, these examples are sort of outdated and more for testing purposes than reference. the whole examples folder should really be cleaned up or removed completely. something we will look into next week at the contributors conference!

**Comment by ccheaton** [comment]
This is probably the same issue. There are some broken demos:

http://p5js.org/examples/demos/Hello_P5_Flocking.php
http://p5js.org/examples/demos/Hello_P5_Drawing.php

The Chrome console shows the following error for both:

`Uncaught Error: [object Arguments]is not a valid color representation.`

I just started looking at p5.js about 5 minutes ago, but I'll poke around when I have a minute and see if I can figure out what's going wrong. :)

**Comment by ccheaton** [comment]
This appears to be fixed today on the p5.js website. For what it's worth, fill calls with two parameters were the source of the problem, for example.

`fill(0, 10);`

**Comment by futuremarc** [comment]
all are now fixed

**Comment by lmccart** [comment]
:)
