### ISSUE TITLE
Edit docs for color

### ISSUE THREAD

**Issue by nickmcintyre** [processing/p5.js#6219]
### Increasing Access

I want to simplify the inline documentation for creating, reading, and setting color. There's also an opportunity to make the wording more consistent. Doing so would increase [cognitive accessibility](https://developer.mozilla.org/en-US/docs/Web/Accessibility/Cognitive_accessibility). It would also make documentation more approachable for young learners.

### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [X] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### Feature enhancement details

I'll make line edits to the inline documentation for this subset of the API.

**Comment by zelf0** [comment]
Can I help with this?

**Comment by nickmcintyre** [comment]
Sure! I'll open a pull request with the first batch of edits in a moment. This will give you a sense of how we're approaching the task.

In the meantime, please have a look at the guide for [contributing documentation](https://github.com/processing/p5.js/blob/main/contributor_docs/contributing_documentation.md) and the [documentation style guide](https://github.com/processing/p5.js/blob/main/contributor_docs/documentation_style_guide.md).

**Comment by nickmcintyre** [comment]
The next set of functions I had in mind are from the Setting section of the [p5.js Reference](https://p5js.org/reference/):

[background()](https://p5js.org/reference/#/p5/background)
[clear()](https://p5js.org/reference/#/p5/clear)
[colorMode()](https://p5js.org/reference/#/p5/colorMode)
[fill()](https://p5js.org/reference/#/p5/fill)
[noFill()](https://p5js.org/reference/#/p5/noFill)
[noStroke()](https://p5js.org/reference/#/p5/noStroke)
[stroke()](https://p5js.org/reference/#/p5/stroke)
[erase()](https://p5js.org/reference/#/p5/erase)
[noErase()](https://p5js.org/reference/#/p5/noErase)

I start by copying the current documentation into the [Hemingway Editor](https://hemingwayapp.com/). This helps me to identify complex sentences. It also lets me gauge the simplicity of my edits. I do my best to land around Grade 7.

**Comment by zelf0** [comment]
Great, looked at your pull request and will make a similar PR with edits to src/color/setting.js

**Comment by nickmcintyre** [comment]
The `color()` function hasn't changed. That note didn't seem necessary after reorganizing a bit.

**Comment by zelf0** [comment]
Here's my current progress: [https://github.com/processing/p5.js/compare/main...zelf0:p5.js:edit-color-inline](https://github.com/processing/p5.js/compare/main...zelf0:p5.js:edit-color-inline). I'm new to contributing so I may be doing something incorrectly.

**Comment by zelf0** [comment]
Thanks so much for the feedback, I just committed a few tweaks

**Comment by zelf0** [comment]
Finished the 9 setting functions. Let me know if it looks good and I should submit a PR. [https://github.com/processing/p5.js/compare/main...zelf0:p5.js:edit-color-inline](https://github.com/processing/p5.js/compare/main...zelf0:p5.js:edit-color-inline)

**Comment by zelf0** [comment]
Should I submit a pull request?

**Comment by nickmcintyre** [comment]
These look good! Please go ahead and submit a PR. I'll probably edit them a bit after merging and will tag you to discuss the changes.

For a little perspective, I'm writing a calculus book and receive large batches of edits from my editor. We iterated on the opening chapters a few times before we settled on a style. I'm going to revisit some of my earlier edits to the p5.js docs based on ideas I'm borrowing from you.

**Comment by zelf0** [comment]
Oh also, I noticed we were changing variable declarations in the examples from let to const, so I was doing that as well where applicable, but then I saw in the [inline documentation guide](https://github.com/processing/p5.js/blob/main/contributor_docs/inline_documentation.md) says to define all variables with let in code samples, so now I'm wondering whether to change them or not.

**Comment by nickmcintyre** [comment]
Thanks for pointing this out. Using `let` feels like the right call--please do so. I'll update the style guide later today.

**Comment by nickmcintyre** [comment]
Thanks for your help @zelf0!
