### ISSUE TITLE
Poor Firefox Performance

### ISSUE THREAD

**Issue by ncthbrt** [processing/p5.js#622]
P5 performance with Mozilla Firefox is rather slow.  Even on the home page, I've noticed a significant performance difference between the two platforms.

Rendering is also inconsistent between Chrome & Firefox. For example, in this game:
http://globalgamejam.org/2015/games/spirit-level
The buildings were randomly generated from a number of template building blocks. It took quite some care to edit the templates so that anti-aliasing wouldn't create gaps between the blocks, on Chrome, this rendered perfectly, yet on FF, there were ugly gaps between the images. Again the performance was also not on par with chrome.  Is this fantastic new library receiving any Firefox love?

This is consistent behavior across platforms (Windows, Mac & Linux)

This is exemplified by the following page (which was linked to earlier): http://jsfiddle.net/auzsp75y/

**Comment by lmccart** [comment]
hi @ncthbrt thanks for the feedback. we are about to do a round of performance optimizations and enhancements this summer we will be sure to look into this.

however, i do ask that you please be careful about using words like "abysmal" etc. this is a volunteer driven project and everyone is doing their best, so it can be discouraging when someone is very negative about the effort.

**Comment by ncthbrt** [comment]
I apologise.  Better?

**Comment by lmccart** [comment]
thanks @ncthbrt! I completely understand your concern, you're right, we've been focused heavily on chrome but not intentionally, mostly just because this is the primary browser of a few main contributors. we will be sure to look into this, if not this week, over the summer. we're aiming to remove that "beta" label from the logo and a big part of that is making sure it runs well across platforms.

**Comment by christinedt** [comment]
The slow performance on Firefox is due largely to the fact that Firefox's browser engine renders the HTML5 canvas more slowly than Chrome does. Unfortunately, canvas is a pretty crucial part of p5.js so I'm not sure how much speed can be helped from our end. 

However, image rendering might be something we can fix. @ncthbrt I am unable to load your game on Firefox, would you happen to have any screenshots of the anti-aliasing differences in Chrome and Firefox?

**Comment by lmccart** [comment]
Feeback re: Firefox duly noted. Thanks for looking into this @christinedt. I'm going to close this one as I think it is covered more generally by #331. I'll link this thread there so we remember to check it out on FF as well.
