### ISSUE TITLE
doubleClicked() doesn't seem to work in examples in offline docs

### ISSUE THREAD

**Issue by davepagurek** [processing/p5.js#6252]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [X] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

main branch

### Web browser and version

Firefox 114

### Operating System

MacOS 12.5.1

### Steps:
1. Run `grunt yui:dev`
2. Navigate to http://127.0.0.1:9001/docs/reference/#/p5/doubleClicked
3. Try double clicking on the example

This is tested in both Chrome and Firefox.

The same example code + p5 built from the main branch works in the web editor: https://editor.p5js.org/davepagurek/sketches/uOPnKQ1U7

I'm not sure if this applies to the p5 website too, but it's worth checking to make sure.

**Comment by abhi6004** [comment]
![Screenshot 2023-07-06 121208](https://github.com/processing/p5.js/assets/97073671/58c450cc-9bfb-4750-a858-fad802b970cd)
![Screenshot 2023-07-06 121235](https://github.com/processing/p5.js/assets/97073671/e7a619ca-c7cb-488e-9531-4542555839d8)

**Comment by abhi6004** [comment]
@davepagurek   in a above image you can see that when i change in a size its work proper but when i double click on example its color not change in to pink and it's default color is also black but in a code i set a red so yeah  doubleClicked() its not work proper

**Comment by abhi6004** [comment]
@limzykenneth assign me this issue i want to work on this issue

**Comment by abhi6004** [comment]
@davepagurek Hey, we can do discuss about this issue for better way of approach for solve the issue

**Comment by abhi6004** [comment]
@davepagurek @limzykenneth 
![Screenshot 2023-07-06 135659](https://github.com/processing/p5.js/assets/97073671/cb179c15-2292-458d-9119-11779be3b945)
![Screenshot 2023-07-06 135714](https://github.com/processing/p5.js/assets/97073671/05bad308-b5cd-49b5-8bb6-ba3e6e16f84c)
![Screenshot 2023-07-06 135747](https://github.com/processing/p5.js/assets/97073671/80df8e4d-d537-43cb-bf03-7179bc2fa505)

**Comment by abhi6004** [comment]
in a above image you can see code is run proper in a editor but yeah in a case of a docs doubleClicked() example is not work

**Comment by sdivyanshu90** [comment]
Changing the variable `value` with some other variable helps. The variable value is conflicting with a reserved function name in p5.js.

**Comment by Artimus100** [comment]
is this issue still up to be resolved??

**Comment by davepagurek** [comment]
@Artimus100 I think so, but try to reproduce it yourself too to double check!

**Comment by Artimus100** [comment]
on it!!

**Comment by Artimus100** [comment]
@davepagurek yes the doubleClicked() doesnt work as expected.

**Comment by Artimus100** [comment]
@davepagurek  could you assign this issue to me??

**Comment by Artimus100** [comment]
@davepagurek its done!!

**Comment by limzykenneth** [comment]
Fixed by #6685
