### ISSUE TITLE
Change distance interpolation in p5.Camera.slerp() from linear interpolation to logarithmic interpolation

### ISSUE THREAD

**Issue by inaridarkfox4231** [processing/p5.js#6257]
### Topic

Thanks for implementing p5.Camera.slerp(). However, there was one point that bothered me, so I would like to ask to correct it. It's about how the scale is interpolated.

In the current specification of p5.Camera.slerp(), the distance between the eye and the center is linearly interpolated. In the case of ortho() as well, the elements of the projection matrix related to scale are linearly interpolated.

```js
  if (this.projMatrix.mat4[15] !== 0) {
    this.projMatrix.mat4[0] =
      (1 - amt) * cam0.projMatrix.mat4[0] + amt * cam1.projMatrix.mat4[0];
    this.projMatrix.mat4[5] =
      (1 - amt) * cam0.projMatrix.mat4[5] + amt * cam1.projMatrix.mat4[5];
    // If the camera is active, make uPMatrix reflect changes in projMatrix.
    if (this._isActive()) {
      this._renderer.uPMatrix.mat4 = this.projMatrix.mat4.slice();
    }
  }
  /* ~~~~~~~~ */
  // Calculate the distance between eye and center for each camera.
  // Then linearly interpolate them by amt.
  const dist0 = p5.Vector.dist(eye0, center0);
  const dist1 = p5.Vector.dist(eye1, center1);
  const lerpedDist = (1 - amt) * dist0 + amt * dist1;
```

However, this causes problems when running programs such as:

[logarithmic interpolation](https://editor.p5js.org/dark_fox/sketches/ieOg7Lcy7)
```js
let cam,cam0,cam1;
function setup(){
  createCanvas(400, 400, WEBGL);

  cam = createCamera();
  cam.camera(200,200,200,0,0,0,0,0,-1);
  cam.perspective(PI/3,width/height,0.1,1000);
  //cam.ortho(-200,200,-200,200,0.1,1000);

  cam0 = createCamera();
  cam0.set(cam);

  cam1 = createCamera();
  cam1.set(cam);
  cam1.camera(50,50,50,0,0,0,0,0,-1);
  //cam1.ortho(-50,50,-50,50,0.1,1000);
  
  setCamera(cam);
}

function draw(){
  noStroke();
  directionalLight(color("gray"),-9,-6,-1);
  ambientLight(color("gray"));
  fill("white");
  ambientMaterial("white");
  
  background(255);
  const p = frameCount % 60 / 60;
  cam.slerp(cam0, cam1, p);
  
  for(let i=0;i<8;i++){
    translate(0,-800,0);box(800);translate(0,800,0);
    translate(-800,0,0);box(800);translate(800,0,0);
    translate(0,0,-800);box(800);translate(0,0,800);
    scale(1/4);
  }
}
```

https://github.com/processing/p5.js/assets/39549290/1716a312-a336-422b-a014-54379a50cc07

This code runs to varying the distance from the center from 200 to 50 with slerp(). What I'm drawing is multiple cubes arranged to get smaller with the same scale change. 200 and 50 look the same, so if amt varies between 0 and 1, it's natural to connect smoothly. However, due to linear interpolation, strange easing is applied and the movement is unnatural.

So, rewrite the distance interpolation as:
```js
  const dist0 = p5.Vector.dist(eye0, center0);
  const dist1 = p5.Vector.dist(eye1, center1);
  //const lerpedDist = (1 - amt) * dist0 + amt * dist1;
  const lerpedDist = dist0 * Math.pow(dist1 / dist0, amt);
```
This is a linear interpolation based on logarithms. This makes the movement smoother.
This code prepares and uses slerp2() modified in that way.

https://github.com/processing/p5.js/assets/39549290/8672289a-8e7c-4b14-a0a8-3d63465d54d0

Also, since it is logarithmic, the distance change when out-of-range referencing is more naturally. With linear interpolation the viewpoint jumps over the center, view is collapse. The difference in behavior between slerp() and slerp2() when amt changes from 0 to 2 is shown below:

https://github.com/processing/p5.js/assets/39549290/d8674e74-8eea-4d22-8f0f-ea8ef8769d24

It is natural that the change in eye position and center position is linear. However, as for the distance of them, I think it is natural to change logarithmically. For example, I modified orbitControl()'s specification to change the distance between the viewpoint and the center logarithmically. This is to ensure similar behavior regardless of scale.
For ortho() as well, I think it's better to make the change logarithmic.

```js
  // For this cameras is ortho, assume that cam0 and cam1 are also ortho
  // and interpolate the elements of the projection matrix.
  if (this.projMatrix.mat4[15] !== 0) {
    this.projMatrix.mat4[0] =
      cam0.projMatrix.mat4[0] *
      Math.pow(cam1.projMatrix.mat4[0] / cam0.projMatrix.mat4[0], amt);
    this.projMatrix.mat4[5] =
      cam0.projMatrix.mat4[5] *
      Math.pow(cam1.projMatrix.mat4[5] / cam0.projMatrix.mat4[5], amt);
    // If the camera is active, make uPMatrix reflect changes in projMatrix.
    if (this._isActive()) {
      this._renderer.uPMatrix.mat4 = this.projMatrix.mat4.slice();
    }
  }
```

[orthoGraphicCamera](https://editor.p5js.org/dark_fox/sketches/aJdfA9Fp_)

https://github.com/processing/p5.js/assets/39549290/64ffdadc-85a6-4bd0-8eb8-c827d5624a98

This spec change does not detract from the appearance of scale changes in situations such as resetting orbitControl().
So I would like to change the specification like this.
Along with this, I would like to change some unit tests as well.
I'd also like to add a unit test for the third argument of _orbit(). Because it is natural that 3rd argument is also linear like the other arguments.

**Comment by davepagurek** [comment]
That's a good catch, I didn't think about the scale values in the matrix. Your proposal makes sense to me!

**Comment by inaridarkfox4231** [comment]
Thanks for reply! I followed EasyCam for linear interpolation, but logarithmic interpolation made more sense...
I didn't realize it because I didn't have the idea of ​​using it for an infinite loop animation.
I checked with the demo of orbitControl(), but there was no sense of incongruity even with logarithmic interpolation, so I would like to change to this specification.
