### ISSUE TITLE
Add complexity labels to issues in order to direct new developers to things they might be able to help with

### ISSUE THREAD

**Issue by lpil** [processing/p5.js#626]
One of the things I really like about the [elixir](http://github.com/elixir-lang/elixir) project is that they label issues with complexity. Because of this I was able to turn my enthusiasm for the project into a small but useful contribution.

Would it be possible to do something similar for p5.js? I enjoy contributing where I can, but with a system like this it's hard to know where to begin.

Cheers,
Louis

**Comment by kjhollen** [comment]
The elixir tags are great. @sarahgp, @workergnome, and @christinedt are updating all the issues according [this proposed schema.](https://github.com/processing/p5.js/wiki/Issues) It includes a set of tags for identifying issues that might be good for folks looking to get started contributing to the project.

**Comment by lpil** [comment]
Great, thank you.

My only reservation is that perhaps "bite size" isn't clear enough. A word such as "starter" or "beginner" might be clearer, especially for those who are not native English speakers

**Comment by workergnome** [comment]
Beginner works for me.  Will change.

**Comment by workergnome** [comment]
There are a bunch of things tagged "ENHANCEMENT".  Should these be tagged "Severity:Feature" instead?

**Comment by lmccart** [comment]
sounds right

**Comment by kadamwhite** [comment]
Feature and Regression feel like statuses, not severity -- you can have both severe and minor regressions, ditto simple or major features

**Comment by sarahgp** [comment]
So it seems like simple / major feature division would be better served by the level indicator and maybe "severity" isn't the best label. But distinguishing a critical bug from a feature "bug" does seem to make sense as it is.

**Comment by lmccart** [comment]
"priority"?

**Comment by workergnome** [comment]
Refactored these, to match the new code structure and to move feature and regression into statuses.  

If anyone has any more input, we can reopen this, but I think we're good to go with this!
