### ISSUE TITLE
slerp does not exist

### ISSUE THREAD

**Issue by HoodieCoder05** [processing/p5.js#6267]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [X] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

0.7.3

### Web browser and version

Opera One(version: 100.0.4815.20)

### Operating System

Linux Ubuntu 22.04

### Steps to reproduce this

`let a = createVector(1, 0);`
`let b = createVector(0, 1);`
`a.slerp(b, 0.5);`
![Screenshot from 2023-07-12 20-08-34](https://github.com/processing/p5.js/assets/63017982/8dc68cec-5009-4818-a94a-d0acfe589f91)

**Comment by limzykenneth** [comment]
Hi @HoodieCoder05, 0.7.3 is a very old version of p5.js, `slerp` has only been implemented in the latest 1.7.0 version and not available in the older versions. Thanks!
