### ISSUE TITLE
Setting the theme color of the window

### ISSUE THREAD

**Issue by felixbade** [processing/p5.js#6270]
### Increasing Access

Unsure

### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [X] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [X] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### Feature request details

A function to set the [theme color](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name/theme-color) of the web page. This is currently [supported by only Safari](https://caniuse.com/?search=theme%20color), but it is [an approved web standard](https://html.spec.whatwg.org/multipage/semantics.html#meta-theme-color).

The purpose is to make full-window p5.js applications feel more immersive and web-native. Especially for situations where the background color of the canvas is changing (either slowly or suddenly), this would make the experience next level.

The function would
- take a p5 color as input (similar to e.g. `fill`, `background`)
- find and edit a `meta[name=theme-color]` tag if present
- create the tag if not present

As a name I suggest either `setThemeColor` (since the meta tag is called theme color) or `setTheme` (like we have `background`, not `backgroundColor`).

I can work on this myself if this feature would be desirable for p5. I would like to first open discussion whether this should be included or not.

**Comment by limzykenneth** [comment]
Until this feature is supported by a wider variety of browsers, I don't recommend implementing this as it will not cover p5.js' [browser support goal](https://github.com/processing/p5.js/blob/main/contributor_docs/supported_browsers.md).

**Comment by felixbade** [comment]
Ok, thank you for the answer! I will close this issue and this can be reopened once the lack of wide browser support is no longer an issue.
