### ISSUE TITLE
nf() print undefined when [right] parameter set to 0

### ISSUE THREAD

**Issue by e-coucou** [processing/p5.js#6273]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [X] Other (specify if possible)

### p5.js version

@1.07

### Web browser and version

ARC, SAFARI, FIREFOX

### Operating System

MacOSX

### Steps:
    let num = 123.45;
    text(nf(num,0,0)+" ms",5,45);

### Snippet:

123.undefined

// Paste your code here :)

```

**Comment by Qianqianye** [comment]
Thanks @e-coucou. The bug is now fixed in PR #6291.

**Comment by Qianqianye** [comment]
@all-contributors please add @e-coucou for bug
