### ISSUE TITLE
Color Alpha bug

### ISSUE THREAD

**Issue by Tosuner51** [processing/p5.js#6278]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [X] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

n/a

### Web browser and version

v1.7.0

### Operating System

MacOs

### Steps:
1.Color alpha mode dont healty working.Sama surface dont accept opacity.
2...
3....

### Snippet:

```js

// Paste your code here :)
function setup() {
  createCanvas(400, 400, WEBGL);
}

function draw() {
  orbitControl(3);
  background(220);
  
  translate(0, 60, 0);
  fill(0, 250, 0 , 50);
  //push();
  //rotateZ(frameCount * 0.01);
  //rotateX(frameCount * 0.01);
  box(50, 50, 50);
  
  translate(0, -120, 100);
  fill(0, 0, 250 , 50);
  //push();
  //rotateZ(frameCount * 0.01);
  //rotateX(frameCount * 0.01);
  box(50, 50, 50);
  translate(0, 0, 0);
  
  fill(250, 0, 0,128);
  beginShape();
    vertex(-100,100,50);
    vertex(-100,-100,50);
    vertex(100,-100,50);
    vertex(100,100,50);
  endShape(CLOSE);
  
  beginShape();
    vertex(-100,100,-200);
    vertex(-100,-100,-200);
    vertex(100,-100,-200);
    vertex(100,100,-200);
  endShape(CLOSE);
  
  beginShape();
    vertex(-100,100,50);
    vertex(-100,-100,50);
    vertex(-100,-100,-200);
    vertex(-100,100,-200);
  endShape(CLOSE);
  //push();
  //rotateZ(frameCount * 0.01);
  //rotateX(frameCount * 0.01);
  //box(70, 70, 70);
  //pop();
  
  

}

```

**Comment by davepagurek** [comment]
Hi! I think this is the same bug as https://github.com/processing/p5.js/issues/3736 so for organizational purposes I'm going to close this issue and move discussion to there. Let me know if there's something I missed though!
