### ISSUE TITLE
GitHub is typed inconsistently across Contributor Docs

### ISSUE THREAD

**Issue by SilasVM** [processing/p5.js#6282]
### Contributor Docs Consistent Typo

Hey, I'm first time contributor, and as I was reading through the Contributor Docs I noticed that GitHub is spelled out with multiple capitalization variations. I saw 'Github', 'github', and some properly typed GitHub. I was wondering if I would be able to open a pull request to fix this across all the contributor docs, or if I should make multiple pull requests fixing one document at a time.

I've noticed this issue across multiple sections of this page: [Contributor Docs](https://p5js.org/contributor-docs/)

**Comment by Qianqianye** [comment]
Thanks @SilasVM for catching it. Yes, please go ahead and open a pull request.
