### ISSUE TITLE
Grammatical Issues in Contributor Guidelines

### ISSUE THREAD

**Issue by thatguyseven** [processing/p5.js#6292]
### Topic

Hello, I noticed a few grammatical errors in the contributor guidelines while reading it that I wanted to correct: 

>  - In the "Found a bug" section, the word 'uch' in the following paragraph should be 'such'.
![Uch to Such](https://github.com/processing/p5.js/assets/137221692/297eadcc-d3dc-4f4a-8f00-36a2ac900ec1)

> - In the same section, there should be a comma following the word 'fixing' in the following sentence.
![Comma following fixing](https://github.com/processing/p5.js/assets/137221692/78ff9777-25e7-470c-85b0-ecefab7a6910)

> - In the "Discuss and amend" section, the word 'your' should be capitalized to keep it consistent with the capitalization theme. 
![Capitalize your](https://github.com/processing/p5.js/assets/137221692/35dbaa83-04f8-4743-b2f2-b0e6ebded2f4)
I am a bit unsure about this one, so please let me know if this is correct or not.

**Comment by Qianqianye** [comment]
Thanks @thatguyseven for catching the typos. 

> * In the "Found a bug" section, the word 'uch' in the following paragraph should be 'such'.

I believe this should be 'much'.

The other two suggested fixes look good. Please go ahead and open a pull request. Thank you.
