### ISSUE TITLE
Incorrect lines when applying a stroke to geometry built without initial stroke

### ISSUE THREAD

**Issue by davepagurek** [processing/p5.js#6318]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

main branch

### Web browser and version

Firefox 114

### Operating System

MacOS 12.5.1

### Steps:
1. Set `noStroke()`
2. Build some geometry using `buildGeometry()`
3. Set `stroke(0)`
4. Draw the geometry with `model()`

You end up with the fill triangles getting strokes rather than the contours passed in between `beginShape()` and `endShape()`.

I'm not 100% sure if this should be considered a bug or not, but the result feels unexpected enough that I'm leaning towards treating it like one? Fixing this would mean always storing stroke info to p5.Geometry being built even if there is currently no stroke set, since one can add one back later, although this could lower performance when building the geometry. Maybe that's OK though since building geometry is a one-time upfront cost?

### Snippet:

```js
let geom

function setup() {
  createCanvas(300, 300, WEBGL);
  
  // Comment this out to make it work
  noStroke()
  geom = buildGeometry(() => {
    beginShape()
    for (let i = 0; i < 10; i++) {
      const angle = i/10 * TWO_PI
      vertex(100*cos(angle), 100*sin(angle))
    }
    beginContour()
    for (let i = 0; i < 10; i++) {
      const angle = -i/10 * TWO_PI
      vertex(20*cos(angle), 20*sin(angle))
    }
    endContour()
    endShape(CLOSE)
  })
}

function draw() {
  background('red')
  fill('white')
  stroke('black')
  model(geom)
}
```

With `noStroke()` before `buildGeometry()`:
![image](https://github.com/processing/p5.js/assets/5315059/0e8a75d6-7493-4780-a876-7fce55134680)

With a stroke in `buildGeometry()`:
![image](https://github.com/processing/p5.js/assets/5315059/abe3e998-a046-4a66-816c-f2c85d1ff249)

**Comment by Artimus100** [comment]
hello @davepagurek is this still up to solve!? seems interesting

**Comment by davepagurek** [comment]
This is still open! I believe it's happening because we don't add strokes in p5.GeometryBuilder here https://github.com/processing/p5.js/blob/main/src/webgl/GeometryBuilder.js#L68 if the user is not drawing with strokes enabled. Later on, if one turns on strokes and a geometry does not yet have any, something is generating edges based on the triangles.

Maybe we need to just add strokes regardless? We should benchmark how much extra runtime cost that adds for large shapes though.

**Comment by Artimus100** [comment]
@davepagurek Sorry for taking so long to reply, ill look into it!!
could you assign it to me!?

**Comment by Artimus100** [comment]
@davepagurek  sure im on it!!  
     
sorry for being late!!

**Comment by davepagurek** [comment]
No worries, thanks! I'll assign this to you.

**Comment by Artimus100** [comment]
im a bit confused here could you give me some initial steps here? @davepagurek

**Comment by Artimus100** [comment]
@davepagurek  again im sorry for being so late but i have a pr please review it!?
      
   -Thank You

**Comment by perminder-17** [comment]
This issue is resolved by https://github.com/processing/p5.js/pull/7287. Thanks everyone for their inputs. :)
