### ISSUE TITLE
Assign colour to individual options

### ISSUE THREAD

**Issue by jimenez537** [processing/p5.js#6333]
### Topic

I would like to assign a different colour to each item in a dropdown list.  Maybe using .style('color','red')

modified from reference:

let sel;

function setup() {
  textAlign(CENTER);
  background(200);
  sel = createSelect();
  //sel.style('color','red') <--changes color of whole list
  sel.position(10, 10);
  sel.option('pear','red');//does nothing
  sel.option('kiwi');
  sel.option('grape');
  
  sel.selected('kiwi');
  sel.changed(mySelectEvent);
}

function mySelectEvent() {
  let item = sel.value();
  
  background(200);
  text('It is a ' + item + '!', 50, 50);
}

**Comment by Qianqianye** [comment]
Hi, the GitHub issues here are a good place for bugs and issues with the p5.js library itself. For questions about writing your own code, the [forum](https://discourse.processing.org/c/p5js/10) and [p5.js Discord](https://discord.gg/SHQ8dH25r9) help channel are the best place to post. Thanks!

**Comment by jimenez537** [comment]
thank you.  with full respect, I noticed an anomaly with being able to disable options in a list and having ableing options not recognized on the same list.  It makes no sense to me and may indicate an inconsistency.  I could not find anything online in regards to this issue.  Once again, I did not mean to waste time and am thankful for your reply.

**Comment by Qianqianye** [comment]
Thanks @jimenez537 for following up. Maybe you can open a new issue about '[Existing Feature Enhancement](https://github.com/processing/p5.js/issues/new?assignees=&labels=Enhancement&projects=&template=existing-feature-enhancement.yml)' for the feature improvement you mentioned. You can read more instructions of opening issues in the [contributor guideline](https://github.com/processing/p5.js/blob/main/contributor_docs/contributor_guidelines.md#existing-feature-enhancement).
Please let us know if you need any support or clarification. Thank you!
