### ISSUE TITLE
Contributor avatars are cut out in README file

### ISSUE THREAD

**Issue by Qianqianye** [processing/p5.js#6337]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [X] Other (specify if possible)

### Steps to reproduce this

In the [Contributors](https://github.com/processing/p5.js#contributors) session of the README file, the most right profiles are cut out, the avatar size are not even (see screenshot below). The avatar grid can be 'scrolled 'horizontally. At the [All Contributor](https://github.com/all-contributors/all-contributors#contributors-) GitHub repo, the avatars are not cut out, though the size is not even as well.

<img width="945" alt="image" src="https://github.com/processing/p5.js/assets/18587130/c636a9c1-bbdd-4b80-9c13-cf573c6259bf">

In [.all-contributorsrc](https://github.com/processing/p5.js/blob/main/.all-contributorsrc) file, the image size is set in this [line](https://github.com/processing/p5.js/blob/e8967e4bf4911e572a5008ee49d45bdf07b61e4a/.all-contributorsrc#L7C1-L7C20) below:
```js
  "imageSize": 100,
```

Wondering if @gr2m might have any thoughts on it? Thanks.

**Comment by gr2m** [comment]
thank you for pinging me Q, I'll look into it

**Comment by gr2m** [comment]
The problems seems to be that some of the names make the columns wider than the 100px images. If I edit the HTML directly and remove all but the first two columns it works as it should: 

![Image](https://github.com/processing/p5.js/assets/39992/6c69a10c-1b60-4381-9670-878b8de6cb2a)

I would suggest we make the images 120px wide and only render 6 pictures per row, that should render nicely. Would that work?

**Comment by gr2m** [comment]
https://github.com/processing/p5.js/pull/6341

**Comment by gr2m** [comment]
> less than the 'code-contributor' count at the side bar (screenshot below)

where is that from? I cannot find it?

> Is there a recommended way to check the non-added 'code-contributors' and add them to the all contributor list?

There is no simple way to add many folks with many contributions at once yet, but I can try to use the all-contributors CLI for it. I can also write a script to compare the users added to the all contributors list and whatever the Contributors from your screenshot is

**Comment by gr2m** [comment]
ahh sorry I know now what that screenshot is :) Let me look into it

**Comment by gr2m** [comment]
Here is a script to get all repository contributors logins:
https://runkit.com/gr2m/get-all-repository-contributors-logins

<details><summary>result</summary>

lmccart, allcontributors[bot], outofambit, Spongman, stalgiag, limzykenneth, therewasaguy, davepagurek, Qianqianye, inaridarkfox4231, montoyamoraga, indefinit, evhan55, dhowe, shiffman, sanketsingh24, kjhollen, asukaminato0721, jesi-rgb, wong-justin, almchung, akshay-99, toolness, Aloneduckling, futuremarc, AidanNelson, vijithassar, meiamsome, ecridge, aferriss, ihsavru, hsab, kadamwhite, mindofmatthew, dependabot[bot], Jared-Sprague, JetStarBlues, nickmcintyre, Zalastax, AdilRabbani, workergnome, mikewesthad, thethp, bomoko, hackertron, Ajayneethikannan, lm-n, weslord, jatin33, aditya-shrivastavv, fenilgandhi, DarkPrince304, codeanticode, jshaw, Zearin, TanviKumar, willmartian, abhinavsagar, kevinbarabash, L05, manpreeeeeet, OhJia, zelf0, ShenpaiSharma, bobholt, tawez, MostafaEwis, sarahghp, tau-, stinedec, bansalnitish, mojosoeun, OleksiiBulba, brightredchilli, austince, min-kim42, hkirat, SanjaySinghRajpoot, stellartux, GoToLoop, reejuBhattacharya, hrishit, singhvisha, CleezyITP, mgold, xyfeng, stampyzfanz, siv2r, vipulrawat, DivyamAhuja, yinhwa, PaliwalSparsh, CrypticGuy, tafsiri, taseenb, banditelol, sixhat, m90, munusshih, smrghsh, dhruvs009, ffd8, JithinKS97, hellonearthis, yukienomiya, AryanKoundal, fal-works, jmandel1027, nthe, sawaisinghh, KKVANONYMOUS, AnuragGupta93, Prateek93a, Ucodia, vedhant, idontknowjs, coreygo, darbicus, constanceyu, russomf, limikael, dhoizner, ozramos, ghalestrilo, aatishb, thatguyseven, calebfoss, chiunhau, zaerl, eltociear, quinton-ashley, LadySith, tstefanich, Ayush23Dash, duskvirkus, Brahvim, JunShern, ctlusto, DoubleJump, kaganjd, xujenna, jeong, alterebro, keho98, max0410, nikhilhvr, Rahulm2310, wxs, micuat, eJohnstonePhd1991, sakshamsaxena, SilasVM, anagondesign, akashraj9828, dummyAccount22, msub2, EndBug, hscdl, dexter1691, DonKarlssonSan, J-888, KevinGrajeda, LisaMabley, Luxapodular, cambridgemike, nsmarino, peilingjiang, Prateek462003, raclim, SachinVarghese, antiboredom, scottgarner, diwi, aLyonsGH, anpanring, digitalfrost, reijovosu, ggorlen, Amethystix, seagalputra, sz245, ismailnamdar, joshuaalm, linnhallonqvist, arihantparsoya, aceslowman, endurance21, awelles, Acha0203, islemaster, brysonian, epramer-godaddy, gregsadetsky, haideralipunjabi, jtnimoy, wxactly, JimishF, JoeCastor, lawreka, kennethdmiller3, leslieyip02, AliLordLoss, maddyfisher, marcusparsons, minortext, njoubert, iamrajiv, samdelong, sm7515, piinthecloud, iamutkarshtiwari, ykabusalah, agrshch, emclaren, fisherdiede, Neilblaze, nicu-chiciuc, paollabd, shinytang6, sparshg, yogitheboss, Gaweph, stevengreens10, verma-varsha, nikolas, hamoid, aditya-siddheshwar, aemonm, ameybhavsar24, AndrasGardos, anniemckinnon, radialglo, Aqmalp99, iashris, BharathKumarRavichandran, carolinehermans, crecord, stu01509, connieliu0, danarmulder, kant, Decoy4ever, DavidWeiss2, FreddieRa, Gracia-zhang, gr2m, guilhermesilveira, jpdutoit, JaiKotia, awarua, plural, JuanIrache, junagao, justinsunho, kate-grant, katiejliu, OsakaStarbux, LakshSingla, Nekzuris, maxdevjs, nthitz, niki-ito, oshoham, pmarsh-scottlogic, robynitp, r21nomi, sk1122, polyrhythmatic, sheamusburns, Siphonophora, stormCup, Stefterv, Swapnil-2001, two-ticks, bekicot, yifanmai, yutinglu413, zenozeng, zoeingram, ashu8912, cacoollib, darkcoderrises, jhongover9000, jjkaufman, kroko, liampuk, nully0x, nakul-shahdadpuri, nebbles, odm275, risingBirdSong, satyasaibhushan, smilee, wmmnola, xty, zoalst, aaronccasanova, AkashGutha, ajspadial, hydrosquall, 13sfaith, shakeabi, N4M3L355, acasmith, adwaith007, tito21, al6862, AndrasGG, IamEzio, arbaaz, ArshM17, kangashley, code4humanity, a-y-u-s-h, beau-muylle, bmoren, brmscheiner, rbwendt, Benjamin-Davies, dabe, BerfinA, Bernice55231, etrepum, bwhitman, bryanrtboy, bulkan, caitelatte, calebegg, Maikuolan, camilleroux, REAS, quinox, chechenxu, ChinmayKadam172, ChrisJohnRyan, b4ux1t3, christhomson, cdfuller, frewsxcv, cosmeoes, daniel-michel, dansarno, meodai, dwight9339, sansumbrella, frigorific44, demc, cotsog, edbrannin, with-a-k, GABBAR1947, glneto

</details>

**Comment by gr2m** [comment]
I updated the script to also load users from the `.all-contributorsrc` file and to log out the diff:
https://runkit.com/gr2m/get-all-repository-contributors-logins/2.0.0

> 136 code contributors missing in .all-contributorsrc file

<details><summary>logins of missing code contributors</summary>

13sfaith, Acha0203, AdilRabbani, AidanNelson, Ajayneethikannan, AkashGutha, AliLordLoss, Amethystix, AndrasGG, AndrasGardos, Aqmalp99, ArshM17, Benjamin-Davies, BerfinA, Bernice55231, ChrisJohnRyan, GABBAR1947, Gracia-zhang, J-888, JaiKotia, JithinKS97, JoeCastor, JuanIrache, JunShern, LadySith, LakshSingla, Maikuolan, N4M3L355, Neilblaze, OleksiiBulba, Prateek93a, SachinVarghese, Siphonophora, Stefterv, a-y-u-s-h, aaronccasanova, acasmith, aditya-siddheshwar, adwaith007, aemonm, allcontributors[bot], anagondesign, arbaaz, arihantparsoya, asukaminato0721, awarua, beau-muylle, bekicot, brmscheiner, bryanrtboy, bulkan, bwhitman, cacoollib, caitelatte, calebegg, cdfuller, constanceyu, cosmeoes, cotsog, dabe, danarmulder, demc, dependabot[bot], dhoizner, digitalfrost, diwi, dummyAccount22, duskvirkus, eJohnstonePhd1991, edbrannin, emclaren, epramer-godaddy, etrepum, fal-works, frewsxcv, glneto, gr2m, hellonearthis, hscdl, iashris, idontknowjs, ihsavru, jatin33, jeong, jesi-rgb, jhongover9000, jmandel1027, junagao, kangashley, kant, leslieyip02, linnhallonqvist, m90, maddyfisher, manpreeeeeet, meodai, micuat, min-kim42, minortext, nebbles, nikhilhvr, niki-ito, nikolas, nully0x, odm275, paollabd, quinox, r21nomi, rbwendt, reijovosu, risingBirdSong, sarahghp, seagalputra, shakeabi, sheamusburns, shinytang6, smrghsh, stalgiag, stellartux, stormCup, stu01509, sz245, tau-, tawez, tito21, vedhant, verma-varsha, vipulrawat, with-a-k, wmmnola, xty, xujenna, yifanmai, yinhwa, ykabusalah, zoalst

</details>

**Comment by gr2m** [comment]
Actually, this feature is built into the CLI 🤣 

```
npx all-contributors-cli check
```

docs: https://allcontributors.org/docs/en/cli/usage#all-contributors-check

**Comment by gr2m** [comment]
ready: https://github.com/processing/p5.js/pull/6349
