### ISSUE TITLE
Second textureMode() example stopped working

### ISSUE THREAD

**Issue by davepagurek** [processing/p5.js#6365]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

1.7.0

### Web browser and version

Firefox 114

### Operating System

MacOS 12.5.1

### Steps:
Go to the second example here: https://p5js.org/reference/#/p5/textureMode

The first example shows an image; the second one shows a grey canvas:

<img width="927" alt="image" src="https://github.com/processing/p5.js/assets/5315059/3c0f2893-8804-48a1-ac68-e8b3a20a4d1a">

### Snippet:

```js
let img;

function preload() {
  img = loadImage('assets/laDefense.jpg');
}

function setup() {
  createCanvas(100, 100, WEBGL);
  describe('quad with a texture, mapped using image coordinates');
}

function draw() {
  texture(img);
  textureMode(IMAGE);
  beginShape();
  vertex(-50, -50, 0, 0);
  vertex(50, -50, img.width, 0);
  vertex(50, 50, img.width, img.height);
  vertex(-50, 50, 0, img.height);
  endShape();
}
```

**Comment by inaridarkfox4231** [comment]
This problem does not occur in 1.5.0, but seems to occur in 1.6.0 and later.

![資料1](https://github.com/processing/p5.js/assets/39549290/0feba97e-65bb-4975-977d-9c95460f0fba)

![資料2](https://github.com/processing/p5.js/assets/39549290/a20e2060-beec-4246-9f3d-fb81b9b55817)

In addition, it doesn't seem to occur when beginShape(QUADS) is used. (version is 1.6.0)

![資料3](https://github.com/processing/p5.js/assets/39549290/037afeaf-30e0-4f22-88d2-f28b363a5974)

[sample code](https://editor.p5js.org/dark_fox/sketches/CznjHVRQ8)

**Comment by davepagurek** [comment]
I wonder if that means the information is getting list in the TESS process. Thanks for narrowing this down @inaridarkfox4231!
