### ISSUE TITLE
Impossible to load multiple p5.Geometry models

### ISSUE THREAD

**Issue by mikima** [processing/p5.js#6378]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

1.7.0

### Web browser and version

116.0.5845.110 (Official Build) (x86_64) 

### Operating System

MacOSX 12.6.6

### Steps:
1. create a first `p5.Geometry`
2. create a second `p5.Geometry`, different from the first one
3. draw the first `p5.Geometry` using the function `model(myGeometry)`
4. draw the second `p5.Geometry` using the function `model(myGeometry2)`

Both the times will be loaded the first geometry. Translations, scales, applies correctly, but displaying only the first geometry

### Snippet:

Readapting the [tutorial on p5.Geometry](https://p5js.org/learn/getting-started-in-webgl-custom-geometry.html#proceduralGeometry), here is an example of the problem:
https://editor.p5js.org/mikima/sketches/2jcVedrXC

**Comment by inaridarkfox4231** [comment]
It can be solved by defining the gid properly.

use gid:

![use_gid](https://github.com/processing/p5.js/assets/39549290/b17979f5-b281-406d-9cc9-2a4ace467587)

don't use gid:

![use_nogid](https://github.com/processing/p5.js/assets/39549290/4944a770-41ea-4bd6-bc78-973e27f963f8)

If you apply model() without defining a gid, the p5.js library cannot distinguish between models and will only draw the first registered geometry. If you want to draw different geometries with the model function, you need to define a different gid appropriate for each.

When drawing geometry loaded using loadModel(), a gid is automatically assigned, so this problem does not occur.

**Comment by mikima** [comment]
I see! thanks! So it's more a matter of documentation. Should i close the issue?

**Comment by inaridarkfox4231** [comment]
If there is no problem, I think you can close it...

**Comment by inaridarkfox4231** [comment]
OK. Please close this. Please close.

**Comment by mikima** [comment]
For some reasons the solving comment has been deleted, I'll re-add it here for future memory.

The key is to set a different `gid` for each geometry:
![unnamed](https://github.com/processing/p5.js/assets/907536/b7bf73f8-ee69-48d8-ba7c-d91550923fdc)

**Comment by Qianqianye** [comment]
Thanks @mikima.
