### ISSUE TITLE
Quad adds a diagonal line in WEBGL.

### ISSUE THREAD

**Issue by StevesMakerspace** [processing/p5.js#6383]
### p5.js version

1.7.0

### What is your operating system?

Windows

### Web browser and version

Edge 115.0.1901.203 

### Actual Behavior

When using WEBGL, quad function with stroke add a diagonal line through the center of the quad.

### Expected Behavior

Quad with an outline but no diagonal line.

### Steps to reproduce

function setup() {
  createCanvas(500, 500, WEBGL);
  translate(-width / 2, -height / 2);
  background(150);
  strokeWeight(3);
  quad(30, 320, 185, 220, 205, 375, 50,405);
}

**Comment by davepagurek** [comment]
Thanks @raclim!

**Comment by nsundriyal62** [comment]
thanks for assigning 
i am working on it

**Comment by Qianqianye** [comment]
Hi @nsundriyal62, thanks for offering help. Just to follow up on this issue, please let us know if you need any support to fix this bug.

**Comment by nsundriyal62** [comment]
@Qianqianye sorry to say but i forgot to work on this issue
actually i marked all assign issue as done and never remind about this one

i am working on it.

thanks for your help.

gonna raise a pr asap

**Comment by nsundriyal62** [comment]
@Qianqianye hello there

i tried a lot to understand the codebase and my whole day passes only setting up and and switching between multiple files.
i am new to this open source and solving this seems very difficult.

i think i am not able to solve this bug.................  :(

so you can unassign this issue 


sorry for taking so much time and this failure
maybe someone else can do it better 

thanks for your time and offering help.

see u

**Comment by Qianqianye** [comment]
Thanks @nsundriyal62 for all of your effort. We are in the process of improving the p5.js WebGL contribution documentation to make contributing to WebGL issues easier in the future. Meanwhile, please feel free to have a look at [open issues](https://github.com/processing/p5.js/issues) on p5.js if you'd like to contribute to another issue. Thanks!
