### ISSUE TITLE
`shader.setUniform` does not work in `setup()`

### ISSUE THREAD

**Issue by wong-justin** [processing/p5.js#6385]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

1.7.0

### Web browser and version

Chromium v 108.0, Firefox 117.0

### Operating System

Windows 10

### Steps:
1. Create a shader in `setup()`
2. Pass a uniform to the shader in `setup()` as well
3. Run (no `draw()`)

Expected result: uniform contains value from sketch. 

Actual result: uniform remains uninitialized

### Snippet:

Copied from [this sketch](https://editor.p5js.org/jwong/sketches/AOpGEj5PB):
```js
function setup() {
  createCanvas(400, 400, WEBGL)
  
  s = createShader(`
    uniform mat4 uModelViewMatrix;
    uniform mat4 uProjectionMatrix;
    attribute vec3 aPosition;
    attribute vec2 aTexCoord;
    varying vec2 vTexCoord;
    
    void main() {
      vTexCoord = aTexCoord;
      vec4 positionVec4 = vec4(aPosition, 1.0);
      gl_Position = uProjectionMatrix * uModelViewMatrix * positionVec4;
    }
  `,`
    precision highp float;
    varying vec2 vTexCoord;

    uniform float redChannel;

    void main() {
      gl_FragColor = vec4(redChannel, 0.0, 0.0, 1.0);
    }`)
  
  shader(s)
  rect(-width / 2, -height / 2, width, height)
  s.setUniform('redChannel', 1)
}
// setUniform() won't work in setup()...
// So for this to actually work, uncomment below
// 
// function draw() {
//   rect(-width / 2, -height / 2, width, height)
//   s.setUniform('redChannel', 1)
// }
```

This doesn't occur with the new function `createFilterShader()`, even though it's also calling `setUniform` behind the scenes. [Example sketch working with `createFilterShader`](https://editor.p5js.org/jwong/sketches/T96caQxWq), and same idea even though it's a `sampler2D` uniform instead of a `float`.

I don't have a good guess about the cause or solution. Sort of a minor issue though.

**Comment by inaridarkfox4231** [comment]
It seems to be reflected properly if you draw the rect after executing setUniform(). what is the bug? I do not know.

![tfbyrygftyr7rhy](https://github.com/processing/p5.js/assets/39549290/35707fbb-3129-4416-85de-b3132184d3ea)

**Comment by wong-justin** [comment]
Oops, that's right. Thanks!
