### ISSUE TITLE
Typos in example for `textFont`

### ISSUE THREAD

**Issue by meezwhite** [processing/p5.js#6400]
### Most appropriate sub-area of p5.js?

Typography

### p5.js version

1.7.0

### Steps to reproduce this

Notice the typos in the example for `textFont`. There should't be a `.` in front of `strokeWeight(0)` and `textSize(10)`.

Furthermore, the `;` is missing after `fill(0)` and  `strokeWeight(0)`.

https://github.com/processing/p5.js/blob/1c2273d6c9113b8ae279de8f0921fabebbc87095/src/typography/loading_displaying.js#L263-L266

See reference: https://p5js.org/reference/#/p5/textFont

**Comment by Qianqianye** [comment]
Thanks @meezwhite! I'm tagging @nickmcintyre, who's the technical writer working on the reference page, to take a look at this.

**Comment by meezwhite** [comment]
@Qianqianye thanks! I only opened an issue because I wasn't sure about the process concerning such small typos. (see #6305)

Would have fixed it myself, if it was okay.

**Comment by nickmcintyre** [comment]
Thanks for including @Qianqianye, and for the quick fix @meezwhite!

@meezwhite what do you think about opening another issue to add a guideline about chaining to the [style guide](https://github.com/processing/p5.js/blob/main/contributor_docs/documentation_style_guide.md)?

```javascript
// Nope.
fill(0)
  .strokeWeight(0)
  .textSize(10);

// Nope.
fill(0).strokeWeight(0).textSize(10);

// Yep.
fill(0);
strokeWeight(0);
textSize(10);
```

**Comment by meezwhite** [comment]
@all-contributors please add @meezwhite for doc
