### ISSUE TITLE
There should be a friendly error when calling `createCapture` with no webcam

### ISSUE THREAD

**Issue by lindapaiste** [processing/p5.js#6402]
### Increasing Access

It can be confusing if a user is looking at an example code which doesn't do anything.

### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [X] Friendly Errors
- [ ] Other (specify if possible)

### Feature enhancement details

When I call `createCapture(VIDEO)` on a device which does not have a webcam, I see a message in the console which is not particularly friendly.
>DOMException: Requested device not found

This is actually not an error.  `createCapture` still returns a `p5.Element`.

This example code will run with no webcam, it just won't do anything -- it creates a transparent image.
```
let capture;

function setup() {
  createCanvas(100, 100);
  capture = createCapture(VIDEO);
  capture.hide();
}

function draw() {
  image(capture, 0, 0, width, width * capture.height / capture.width);
  filter(INVERT);
}
```

Other examples on the [reference page](https://p5js.org/reference/#/p5/createCapture) do have errors.
![image](https://github.com/processing/p5.js/assets/28965286/be1fd573-ec19-4709-b598-a4e8f8f9e168)

**Comment by ayushanand308** [comment]
We can have something like "No webcam found on this device" instead of the current error message to let the users know that the code is working fine but there is simply no webcam to capture video from.

**Comment by Qianqianye** [comment]
Thanks @lindapaiste and @ayushanand308. I'm inviting the FES GSoC contributor @Ayush23Dash and mentors @almchung @nbriz to this discussion.

**Comment by Ayush23Dash** [comment]
Yup, I agree with @ayushanand308 and believe so that we can add an error for the same, also it would be great if we add one more error for Camera Permission denied. 
Currently it shows :
`DOMException: Permission denied`
error, which is somehow descriptive but adding a Friendly Message to it would also be great.

**Comment by Qianqianye** [comment]
Thanks @Ayush23Dash! What do you think, @almchung and @nbriz?
We can add these error message if they are approved by two FES stewards and GSoC mentors/contributor.

**Comment by ayushanand308** [comment]
@Ayush23Dash Should I begin working on this and submit a pull request?

**Comment by Qianqianye** [comment]
Thanks @ayushanand308 for the follow up. Please go ahead and submit a PR.
Meanwhile, I'm inviting the new FES stewards to this discussion @richardegil, @itsjoopark, @hannahvy, @bisabi-01, @singshris. Please feel free to leave comments or questions. Thank you.

**Comment by richardegil** [comment]
I agree with this. For the permission denied error may I suggest the following: "Camera detected but permission to it has been denied."

**Comment by Garima3110** [comment]
Hii everyone, I am just a beginner to open source. I know a bit of javascript but still learning. I would  like to address this issue , could you please help  me through the process?!

**Comment by Qianqianye** [comment]
Hi @Garima3110. Below are three contributor documentation that you might find helpful:

- [Contributor Guidelines](https://github.com/processing/p5.js/blob/main/contributor_docs/contributor_guidelines.md)
- [🌸 p5.js Friendly Error System (FES)](https://github.com/processing/p5.js/blob/main/contributor_docs/friendly_error_system.md)
- [FES Reference and Notes from Developers](https://github.com/processing/p5.js/blob/main/contributor_docs/fes_reference_dev_notes.md)

I will suggest going through the three docs and leave comments here if you have any questions. We are in the process of updating our contributor documentation, so please feel free to let us know how we can improve the docs to make it easier for contributors to get started. Thank you!

**Comment by Garima3110** [comment]
I think in this case we just need to check for the condition :
 `  
 if (!navigator.mediaDevices || !navigator.mediaDevices.getUserMedia) {
    throw new Error("Your browser does not support webcam access.");
  }`
  
  @Ayush23Dash  It would be great if you could tell me whether I am going in the right direction or not?!

**Comment by ayushanand308** [comment]
@Garima3110 The line of code you provided is a standard JS error throw statement, and it will result in a regular error being thrown, not a friendly error.

**Comment by mdb0** [comment]
Since there isn't much update i would like to work on this issue
