### ISSUE TITLE
Support saveCanvas with framebuffer inputs

### ISSUE THREAD

**Issue by aferriss** [processing/p5.js#6404]
### Increasing Access

Allowing saveCanvas to accept a framebuffer input makes the api simpler and could help reduce confusion for newer users. If we don't add the feature, adding a warning would help alert users to the current limitations of the library in a friendlier way.

### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### Feature request details

I was wondering if we should consider allowing the `saveCanvas` function to accept framebuffers as inputs, so that a user could save the output of a framebuffer directly without first needing to draw it. 

Currently trying this throws an error, so maybe at the very least we could add a warning that alerts users that framebuffers aren't accepted as parameters in the `saveCanvas` function.

Here's an example sketch
https://editor.p5js.org/aferriss/sketches/h3vtY-SlK

**Comment by davepagurek** [comment]
The ability to save a framebuffer makes sense! I see that `saveCanvas` can accept a `p5.Element|HTMLCanvasElement` and `p5.Graphics` extends `p5.Element`. I also see that `p5.Image` has a `save` method, allowing you to call `yourImage.save()` directly. Should we be adding a method version in addition to the global function version?

**Comment by Qianqianye** [comment]
I agree that allowing saveCanvas to accept a framebuffer input makes sense. Please feel free to go ahead and make a PR when you are ready @aferriss @davepagurek. Thanks!

**Comment by aferriss** [comment]
Yes, I think adding a save function directly on the framebuffer object makes sense as well, good call out!
