### ISSUE TITLE
Glitch in arc stroke with certain parameters

### ISSUE THREAD

**Issue by JuanIrache** [processing/p5.js#6412]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [X] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

1.7.0

### Web browser and version

Chrome 116.0.5845.187 (and others)

### Operating System

At least MacOS Ventura

### Steps to reproduce this

When drawing an Arc with a thick stroke and using start and stop values near zero (but not exactly zero), the stroke is no longer the outside of an arc, but a large dot. This seems to only happen with certain stroke weight, arc size, and start and stop value combinations. Removing decimals tends to fix it sometimes, but there isn't a safe number of decimals you can send it to make sure this won't happen (I have seen it with fewer than 3, which is a problem when drawing with precision).

### minimal example:

https://editor.p5js.org/JuanIrache/sketches/6BgBU7113

Is there a way to send the arc function safe start and stop numbers? I'm investigating but would appreciate additional insights.

**Comment by JuanIrache** [comment]
Another example looking at the Renderer2D.prototype.arc function, it seems a single _curves_ like this one is fine:

```
[{
    ax: 1.0000000,
    ay: 0.0000000,
    bx: 1.0000000,
    by: 0.000104**8**,
    cx: 1.0000000,
    cy: 0.0002097,
    dx: 1.0000000,
    dy: 0.000314**5**
}]
```

But this one draws the glitchy dot: 

```
[{
    ax: 1.0000000,
    ay: 0.0000000,
    bx: 1.0000000,
    by: 0.000104**9**,
    cx: 1.0000000,
    cy: 0.0002097,
    dx: 1.0000000,
    dy: 0.000314**6**
}]
```

In both cases, the other values involved in drawing the ctx path. rx and ry are 112.38400000000001, and x and y are zero.

**Comment by davepagurek** [comment]
This seems to be a Chromium bug, as it doesn't happen in Firefox. Maybe worth filing an issue there so they know?

**Comment by JuanIrache** [comment]
I'm trying to create a minimal example that doesn't involve p5, just context shapes, so the problem is more obvious to the Chromium team, but I'm failing so far.

**Comment by JuanIrache** [comment]
Let's see if this gets things going: https://bugs.chromium.org/p/chromium/issues/detail?id=1483515

I think for now we should avoid sending very small differences between start and stop to p5's arc()

**Comment by limzykenneth** [comment]
@JuanIrache The Chromium issue seems to be getting some traction from the team there. I'll close this issue for now but do let us know if you need more support with that. Thanks.
