### ISSUE TITLE
remove() example is broken

### ISSUE THREAD

**Issue by workergnome** [processing/p5.js#642]
<http://p5js.org/reference/#/p5/remove> does not work.  Nothing appears on the screen, and the expected behavior is to see a circle, and that the sketch removes itself on mouse click.

**Comment by lmccart** [comment]
does the example code not work, or is it just not showing up on this page? this is one of the examples that is set to be code display only (not live running).

**Comment by workergnome** [comment]
Ah—I hadn't realized that display-only examples were an option.

Event so, I haven't been able to get this example to work—but part of that might be that it's drawing an ellipse with a zero radius, so it doesn't appear to draw anything at all.

Perhaps:
```javascript
function draw() {
  ellipse(50, 50, 10, 10);
}

function mousePressed() {
  remove(); // remove whole sketch on mouse press
}
```

as a simpler example?  That code works for me.

**Comment by lmccart** [comment]
ah yeah, that works. i'll make the change

**Comment by Hari-15** [comment]
the remove p5 function does not work in my code

**Comment by Hari-15** [comment]
function keyTyped() {
  if (key === 'd') {
      x_orange = x_orange+50;
      image(orange, x_orange, y_orange, 100, 100)
      orange.remove();
  }

  if (key === 'a') {
    x_orange = x_orange-50;
    image(orange, x_orange, y_orange, 100, 100);
  }
}

**Comment by Hari-15** [comment]
<!DOCTYPE html>
<html>
 <head>
   <title>Fruit Fight</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.0.0/p5.js"></script>

    <link rel = 'stylesheet' href = 'style_1.css'>
 </head>

**Comment by Hari-15** [comment]
i doubt it works in anything now

**Comment by Hari-15** [comment]
i'm making a game where you are an orange trying to dodge a whole bunch of apples
