### ISSUE TITLE
I can see the page body/background through the image and canvas

### ISSUE THREAD

**Issue by peeter2** [processing/p5.js#6435]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [X] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [X] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### Steps:
1. draw an image on canvas
2. draw a second image that is semi-transparent (png) overlapping the first image
3. you can see through the first image all the way back to the page body background, even though the first image is 100% opaque. Also the canvas has a gray background color drawn on it, even that doesn't stop seeing through it, through the images.

### Snippet:

live demo:
https://editor.p5js.org/shangtsung/full/t7revfa38

You can click the button to toggle the page background to see more clearly what I'm talking about.

What can be done to fix this issue?

```

**Comment by limzykenneth** [comment]
I think this might be a blend mode problem. Will need to look into it further.

**Comment by peeter2** [comment]
I have tried to test it with all the blend modes, but did not find one that would work as expected. The first (opaque) image should not be seen through the part where the semi transparent image overlaps. It seems as if it has a crossfade effect - when the transparent image on top of it has 50% transparency, the image area underneath also is 50% transparent... When the top image is 25% transparent, the below image has also 25% transparency (75% opacity).

I hope this will be fixed soon. Thank you.

**Comment by davepagurek** [comment]
@peeter2 Can you try upgrading your sketch to the latest p5 version, 1.7.0? You're on 0.9.0, and WebGL alpha blending had a number of bugs that have since been fixed.

**Comment by davepagurek** [comment]
It looks like this is fixed on the latest version: https://editor.p5js.org/davepagurek/sketches/UDzDH78ne

I'm going to close this for organizational purposes, but let me know if I missed anything and we can reopen!
