### ISSUE TITLE
texturemode(IMAGE) not working

### ISSUE THREAD

**Issue by peeter2** [processing/p5.js#6437]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [X] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### Steps:
1. Check out the reference page: https://p5js.org/reference/#/p5/textureMode
2. You can see that the shape does not have any texture. Seems to be filled with a single color.

What can be done to fix this? It worked fine in p5.js version 0.9.0.

Thanks

**Comment by aferriss** [comment]
Hi @peeter2 , I just checked this in the current main build of p5 and it seems to be fixed. You can take a look at a built binary here. 
https://editor.p5js.org/aferriss/sketches/gncwMBiWz

**Comment by peeter2** [comment]
Thanks. That build in your sample seems to be using version 1.7.0 as I see in the p5.js file and seems to work fine.
Hopefully it will also be fixed in the latest CDN file, which currently is not working:
https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.7.0/p5.js

**Comment by aferriss** [comment]
I'm not sure why it says 1.7, but I just built that file from source this morning. Maybe that versioning comment is not being updated correctly

**Comment by limzykenneth** [comment]
@peeter2 Just to clarify, the version @aferriss used in the sketch shared is built from the latest main branch of this repo, not 1.7.0. The changes made between 1.7.0 and the main branch has not been released yet and so isn't yet available (but will be once we make a new release, probably soon).

**Comment by davepagurek** [comment]
@limzykenneth is that still happening on the latest main build? it looks like the issue was already captured and solved: https://github.com/processing/p5.js/issues/6365

Context loss should probably be opened as a separate issue if that's the remaining one

**Comment by limzykenneth** [comment]
I'll see if I can test if it is working on the main build, but I would supposed it is probably fixed in #6365 in this case. @peeter2 Can you confirm this is the issue you are seeing on the reference page?

@davepagurek The context loss one is a bit random and tends to follow a short hang of the browser, not very replicable so if you are not seeing it, it may not be a problem.

**Comment by peeter2** [comment]
Yes, the second example on the reference page shows a blank gray canvas: https://p5js.org/reference/#/p5/textureMode
It should show the image on the canvas, just like in this sketch:

> Hi @peeter2 , I just checked this in the current main build of p5 and it seems to be fixed. You can take a look at a built binary here. https://editor.p5js.org/aferriss/sketches/gncwMBiWz

Looking forward to the fixed release.
