### ISSUE TITLE
Support mirrored video for createCapture

### ISSUE THREAD

**Issue by ziyuan-linn** [processing/p5.js#6441]
### Increasing Access

For many creative coding projects that involve the webcam, we want to display the horizontally flipped webcam footage rather than the original footage. The flipped footage resembles a mirror and therefore provides a more natural interaction. This feature would give people with little or no prior experience in creative coding an intuitive way to mirror the webcam footage.

### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [X] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### Feature request details

This feature would give users an option to mirror the webcam video. Some potential interfaces :
```javascript
function setup() {
  capture = createCapture(VIDEO);
  mirroredcCpture = mirrorCapture(capture);
}
```
or alternatively
```javascript
function setup() {
  mirroedCapture = createCapture(VIDEO, { flipped: true });
}
```

Unlike using functions like `scale(-1, 1)` which doesn't change the original video element, this feature would return a new video element. This would be easier to use than `scale`, which often results in things getting drawn to unexpected places and text being inverted. This feature would especially be helpful to the ml5 community since we could run prediction directly on the mirrored video element rather than trying to manually mirror both the video and the outputted data. 

Here is a link to the [discussion](https://github.com/ml5js/ml5-next-gen/issues/44) about this feature in the ml5 repo.

@shiffman Please feel free to add anything I missed :}

**Comment by reksono-j** [comment]
Hi, I think this is a good addition and seems like it should be straight forward. I've never contributed before, but I'm going to take a crack at it.

**Comment by Qianqianye** [comment]
Thanks @ziyuan-linn for brining up this issue. I'm inviting the p5.js DOM stewards to this discussion to share you thoughts or questions about feature request @SarveshLimaye, @SoundaryaKoutharapu, @ramya202000, @BamaCharanChhandogi, @Obi-Engine10, @MarceloGoncalves, @hiddenenigma. Thank you!

**Comment by limzykenneth** [comment]
Just want to bring up from the discussion in ml5 here as well, the current hacky but efficient way to deal with this is through drawing the capture feed onto a p5.Graphics and flipping it with `scale(1, -1)`. For internal implementation we need something at least as performant and not operating on the pixels array. I'm not sure if there are any browser API already available that can help with this but it's worth looking into.

**Comment by davepagurek** [comment]
I believe `createCapture()` returns a `p5.MediaElement`. For these, we already internally draw them to a canvas in `_ensureCanvas` and then use that when rendering them: https://github.com/processing/p5.js/blob/95b82ea1d5a6264f8bb9acbc71b6e49104ac9522/src/dom/dom.js#L3222

So potentially we could do the flipping in there when we draw it, which wouldn't be much additional cost?

**Comment by Vishal2002** [comment]
I want to know more about this feature from @ziyuan-linn, can you elaborate more on this if possible ?

**Comment by Vishal2002** [comment]
Is it still open to contribute if yes then I have done what said.

**Comment by shiffman** [comment]
Wow, super excited to see this get merged, thank you @Vishal2002! This will really help with the ml5.js examples!

**Comment by Vishal2002** [comment]
> Wow, super excited to see this get merged, thank you @Vishal2002! This will really help with the ml5.js examples!

Thank you @shiffman It's my pleasure to work on this issue.

**Comment by MarcoHess** [comment]
I have a question on how this is now supposed to work with the machine vision. I was trying some experiments using a webcam and poseNet but if I follow the example from the documentation with const flippedImage = ml5.flipImage(input); in the draw() function, yes I can flip the image but the poseNet still uses the original video stream to perform the pose detection and as such what I now draw on the canvas is the non mirrored pose detection on the mirrored image. 

What would I need to do to input the mirrored video stream (as opposed to just a single image) into the poseNet pose detection?

```
function setup() {
  createCanvas(canvas_width, canvas_height);
  video = createCapture(VIDEO);
  video.size(width, height);
  // How do I mirror the video here to supply to poseNet?
  poseNet = ml5.poseNet(video, modelReady);
  poseNet.on("pose", function (results) {
    poses = results;
  });
  video.hide();
}
```

**Comment by shiffman** [comment]
Hi @MarcoHess, this is being addressed in the next version of ml5.js, due to be released soon, follow along here: https://github.com/ml5js/ml5-next-gen/pull/127
