### ISSUE TITLE
Edit typography docs to align with style guide

### ISSUE THREAD

**Issue by nickmcintyre** [processing/p5.js#6449]
### Increasing Access

Writing with plain, consistent language increases cognitive accessibility. It's also more welcoming to younger members of the community.

### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [X] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### Feature enhancement details

I'll edit the inline documentation and code samples for each function in the [typography group](https://p5js.org/reference/#group-Typography).

**Comment by EarthIsHeaven** [comment]
Hey @nickmcintyre can i work on this issue ?

**Comment by nickmcintyre** [comment]
Sure @EarthIsHeaven! The more eyes we have on these edits the better. How about reviewing my most recent pull request to get started?

Here's how I build and test documentation locally. This workflow assumes you have [nvm](https://github.com/nvm-sh/nvm) installed on macOS or Linux.

```bash
# Install the LTS version of node and use it.
nvm install --lts
nvm use --lts

# Make a folder for docs and navigate to it.
mkdir docs && cd docs

# Clone Nick's fork of the p5.js repo.
git clone https://github.com/nickmcintyre/p5.js

# Clone the p5.js-website repo.
git clone https://github.com/processing/p5.js-website

# Navigate to the p5.js directory.
cd p5.js
# Check out the branch under review.
git checkout sod-typography-load-display
# Generate data for the API reference.
npm install
npx grunt lint:samples

# Navigate to the p5.js-website directory.
cd ../p5.js-website
# Copy data for the API reference.
cp ../p5.js/docs/reference/data* src/templates/pages/reference
# Build a draft of the website.
npm install
npm run build

# Navigate to the directory with the built website.
cd dist
# Serve the website on localhost:8000.
python3 -m http.server
```

**Comment by skbhagat0502** [comment]
Hi @nickmcintyre I am working on this issue.

**Comment by nickmcintyre** [comment]
@skbhagat0502 thanks for offering to help out! I'll make another pull request with edits soon and will tag you to review.

**Comment by nickmcintyre** [comment]
@skbhagat0502 I could really use your help with reviews. It's my job to edit the entire API reference through the end of the year. I'd love to incorporate any feedback you may have!

**Comment by nickmcintyre** [comment]
@harshsharma-11 yep! There's a [p5.js Discord[https://discord.gg/SHQ8dH25r9] and [Processing Discourse](https://discourse.processing.org/).
