### ISSUE TITLE
Race Condition when using reverse() BUG

### ISSUE THREAD

**Issue by Luxapodular** [processing/p5.js#646]
Hi all, 
When creating an example for the reverse() function, I noticed that this simple function:

    function setup() {
        var myArray = new Array("A", "B", "C");
        print(myArray); // ["A","B","C"]
        var a = reverse(myArray);
    }

sometimes returns,
    ["A","B","C"]
and other times returns.
    ["C","B","A"]

It seems that it is sometimes performing the reverse() prior to the print statement. I'm not sure how to tackle this one.

**Comment by workergnome** [comment]
Looking at this with @Luxapodular, it looks like console.log isn't synchronous.   

```javascript

p5.prototype.print = function(args){
  var newArgs = JSON.parse(JSON.stringify(args));
  console.log(newArgs);
}

```

Is horrid, performancewise, but it handles deep clones of objects and works.

**Comment by workergnome** [comment]
@Luxapodular, do you want to make a pull request, or should I?

**Comment by kadamwhite** [comment]
@Luxapodular What browser are you observing this in?

**Comment by kadamwhite** [comment]
`console.log` is synchronous, but the rendering of the log statements is not -- so by the time the render loop runs in dev tools, the value may have been updated and console.log's reference to the requested array will be updated with new values. More info here: http://stackoverflow.com/questions/7389069/console-log-object-at-current-state they come to the same conclusion @workergnome does.

Quoting @bobholt after discussing this issue with him: "some sort of string conversion before logging is probably the right thing to do, performance-be-damned". However, [circular objects](http://stackoverflow.com/questions/1493453/example-of-a-circular-reference-in-javascript) will not be able to be serialized. @mzgoddard suggests we could pull in something like the [`util.inspect` method](https://github.com/defunctzombie/node-util/blob/master/util.js#L125-L149) from Node's JS, which should work around that issue... but that's pretty heavy-duty as a solution goes.

**Comment by Luxapodular** [comment]
Hi @kadamwhite, @workergnome and I observed this in the desktop editor and safari. Chrome seemed to work synchronously however. We'll be submitting a pull request which includes the string conversion prior to the console.log() call in a bit, as it should work as a fairly effective patch for now.

**Comment by kadamwhite** [comment]
@Luxapodular +1! I just posted the idea about `util.inherit` in case this issue ever comes up again in the future.

**Comment by workergnome** [comment]
Thanks, everyone!
