### ISSUE TITLE
Contributor docs website not functioning (https://p5js.org/contributor-docs/#/)

### ISSUE THREAD

**Issue by deveshidwivedi** [processing/p5.js#6492]
### Topic

Hi, I tried going through the contributor docs several times but it's been showing "404 - not found". Here's screenshots:
<img width="960" alt="contri-docs" src="https://github.com/processing/p5.js/assets/120312681/e73e3768-4f6f-4bbd-a1f6-3c48bfd543b3">
(https://p5js.org/contributor-docs/#/)
<img width="948" alt="Screenshot 2023-10-24 084832" src="https://github.com/processing/p5.js/assets/120312681/99ee80aa-e6df-4b68-9af6-06242b6e3a38">
(https://p5js.org/contributor-docs/#/contributor_guidelines?id=quick-get-started-for-developers)

I'm new here and looking forward to being an active part of the community. Thank you!

**Comment by limzykenneth** [comment]
It is likely your ISP is DNS blocking the Github resource required to run the contributor docs site: https://github.com/processing/p5.js-website/issues/1345#issuecomment-1755192930. Changing your DNS to a third party provider should solve this.

**Comment by deveshidwivedi** [comment]
sure, thank you!
