### ISSUE TITLE
Canvas becomes strange when using translate() and filter function in 2D mode

### ISSUE THREAD

**Issue by inaridarkfox4231** [processing/p5.js#6502]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

1.8.0

### Web browser and version

Chrome

### Operating System

Windows11

### Steps:
1. createCanvas(600, 600); background(255); noStroke(); fill(0); translate(300, 300); circle(0, 0, 300); 
2. and then, apply filter(BLUR, 5);
3. become looks strange.

### Snippet:

```js
function setup() {
  createCanvas(600, 600);
  background(255);
  noStroke();
  fill(0);
  translate(300, 300);
  circle(0, 0, 300);
  filter(BLUR, 5);
}
```

[2D_BLUR_BUG](https://editor.p5js.org/dark_fox/sketches/Zkm76ER4T)
## version 1.7.0
![BLUR_170](https://github.com/processing/p5.js/assets/39549290/ccd881d4-7bab-4fff-b520-19084e0cb358)

## version 1.8.0
![BLUR_180](https://github.com/processing/p5.js/assets/39549290/1295062f-da5d-466e-8509-ec782c74b805)

**Comment by inaridarkfox4231** [comment]
sorry. This happens with any filter function. So I changed the title.

case INVERT: (version 1.8.0)
![INVERT](https://github.com/processing/p5.js/assets/39549290/bcdeefa2-7e5c-4f11-a477-33db01ceb63e)

**Comment by inaridarkfox4231** [comment]
In addition, the behavior when drawing with lower opacity seems to be different from that in 1.7.0.

[APPLY_FILTER_TO_ALPHA](https://editor.p5js.org/dark_fox/sketches/DZNX2T0MC)

### snipet
```js
let img;

function preload(){
  img = loadImage("https://inaridarkfox4231.github.io/assets/season/summer_small.png");
}
function setup(){
  createCanvas(img.width, img.height);
  background(img, 64);
  filter(~~~);
}
```

## version 1.7.0
![BLUR_64_170](https://github.com/processing/p5.js/assets/39549290/2f548bf9-c223-498e-8c44-42f26cee5ac2)

![INVERT_64_170](https://github.com/processing/p5.js/assets/39549290/d97c5811-d26c-4614-928b-1c03db87eb96)

![OPAQUE_64_170](https://github.com/processing/p5.js/assets/39549290/e89f0cdf-55ab-4ea5-b611-bdd1a6b22bbc)


## version 1.8.0
![BLUR_64_180](https://github.com/processing/p5.js/assets/39549290/c5426562-dbb4-440f-817a-2c18211286ed)

![INVERT_64_180](https://github.com/processing/p5.js/assets/39549290/12a939a2-bc74-4d3f-aa94-c4b675f19d4e)

![OPAQUE_64_180](https://github.com/processing/p5.js/assets/39549290/dd2cea99-d113-418a-bdc8-998bf4493133)


However, if "this" is the future behavior of 2D filter(), this is not considered a bug, so there is no problem.

**Comment by davepagurek** [comment]
It looks like all of the bug behaviour happens here:
https://github.com/processing/p5.js/blob/611941ae36de4a1110ffc1f7ad544c2253df1197/src/webgl/p5.RendererGL.js#L1129-L1133
- We probably shouldn't assume an image mode and should explicitly add `imageMode(CORNER)`
- We probably should clear the canvas first so that we don't blend with the earlier canvas
- Speaking of blending, we should probably not assume a blend mode and explicitly add `blendMode(BLEND)`

**Comment by Garima3110** [comment]
Hey  @davepagurek , I am interested in working on this issue. Could you please add some more context to what you are trying to say through this:
> * We probably shouldn't assume an image mode and should explicitly add `imageMode(CORNER)`
> * We probably should clear the canvas first so that we don't blend with the earlier canvas
> * Speaking of blending, we should probably not assume a blend mode and explicitly add `blendMode(BLEND)`

ThankYou!

**Comment by perminder-17** [comment]
> Hey @davepagurek , I am interested in working on this issue. Could you please add some more context to what you are trying to say through this:
> 
> > * We probably shouldn't assume an image mode and should explicitly add `imageMode(CORNER)`
> > * We probably should clear the canvas first so that we don't blend with the earlier canvas
> > * Speaking of blending, we should probably not assume a blend mode and explicitly add `blendMode(BLEND)`
> 
> ThankYou!

Idk but I think, filter() uses WebGL in the background by default, and I think we are unable to render the shapes in WEBGL background.

**Comment by perminder-17** [comment]
> It looks like all of the bug behaviour happens here:
> 
> https://github.com/processing/p5.js/blob/611941ae36de4a1110ffc1f7ad544c2253df1197/src/webgl/p5.RendererGL.js#L1129-L1133
> 
> * We probably shouldn't assume an image mode and should explicitly add `imageMode(CORNER)`
> * We probably should clear the canvas first so that we don't blend with the earlier canvas
> * Speaking of blending, we should probably not assume a blend mode and explicitly add `blendMode(BLEND)`

Thankyou for your suggestion @davepagurek

**Comment by inaridarkfox4231** [comment]
For reference, here is an example:
Transparency becomes an issue when pasting transparent images. There may not be many examples like this, but if the background is transparent and INVERT is applied, it seems that with the current specifications, it will be colored.

```js
function setup() {
  createCanvas(400, 400);
  let gr=createGraphics(100,100);
  gr.textAlign(CENTER,CENTER);
  gr.textSize(80);
  gr.text("🦊",50,50);
  gr.filter(INVERT);

  background(128);
  image(gr,100,100);
}
```
## version 1.7.0
![INVERT_170](https://github.com/processing/p5.js/assets/39549290/7d6f6940-7f04-496b-ad47-2e2e64203c32)

## version 1.8.0
![INVERT_180](https://github.com/processing/p5.js/assets/39549290/567239f4-76fa-4b7b-baa1-ae511cb2937c)

**Comment by inaridarkfox4231** [comment]
Finally, this is not a bug report, just a chat, but there seems to be a slight difference in the behavior of BLUR when the background is transparent in 2D and webgl.

```js
function setup(){
  createCanvas(400, 400);
  clear();
  textAlign(CENTER, CENTER);
  textSize(180);
  text("🐬",200,200);
  filter(BLUR, 10, true/false);
}
```

## use webglFilter

![FILTER_BLUR_true_2](https://github.com/processing/p5.js/assets/39549290/332d8a03-e895-434a-b5e0-b4cf635a906b)

## not use webglFilter

![FILTER_BLUR_false_2](https://github.com/processing/p5.js/assets/39549290/1cc01b12-77f8-4545-b6a2-3f265decb365)

These are the points that I was concerned about about the filter function that was implemented this time. I'll leave it to you to decide what to do with these. In the p5.js community to which I belong, even the first thing I raised is not considered a bug. So I can't determine whether these are bugs or not. So I'll leave everything to you regarding to handle these.

**Comment by SableRaf** [comment]
Hey @inaridarkfox4231 thanks for your reports. I'd suggest filing separate issues for each unexpected behavior your noticed as they most likely have different causes. This will make it easier to track the issues and possible solutions.

**Comment by inaridarkfox4231** [comment]
I got it. Let's separate the transform issue and transparency issue.
It appears that the problem with the transform operation is on the verge of being resolved.
Therefore, let's have this resolved in the relevant issue.
The transparency issue has nothing to do with that, so let's raise a separate issue.
Thanks,

**Comment by inaridarkfox4231** [comment]
Regarding "blur", I think this is a subjective issue as it is a question of how to define "blur". I can't decide whether or not it should be treated as a bug, so I'll leave everything up to the person who created the specifications.

**Comment by davepagurek** [comment]
I think the blur issue is the same as the transparency one, as it only happens when the background is not fully opaque (adding `background(255)` before `image(...)` looks pretty normal.) we can try to fix that along with the transparency issue.

**Comment by davepagurek** [comment]
For dealing with the transformation of the canvas, I think we need to make sure we call `this._pInst.resetMatrix()` (as opposed to `pg.resetMatrix()` -- the main canvas is the one whose transformations might need to be reset.) We might also need to create a `filterCamera` on the renderer so that we always have around a default camera we can use to avoid the user's camera messing up the position too.

It would be great if we could add some unit tests so we can make sure it works in a few scenarios, and stays working for future changes. Maybe we could have some tests that:
- applies some kind of transformation
- draws a rectangle
- applies the invert filter
- loads pixels
- checks that the colors are correct where the rectangle should be, and maybe in one spot where it isn't.

For the transformations to test, we could have a test case for:
- No transformation
- A translation via `translate(...)`
- A translation via making a camera and calling `cam.move(...)`

**Comment by inaridarkfox4231** [comment]
Also, it doesn't seem to support p5.Framebuffer (it might not be possible in the first place...)
[filter_FBO](https://editor.p5js.org/dark_fox/sketches/SN55k9889)

https://github.com/processing/p5.js/assets/39549290/362b3152-dab9-479b-942e-59ef04a133a4

Maybe I'm applying it wrong, or maybe I shouldn't use it this way.
It may also be resolved automatically if other issues such as transformation are resolved.
So I can't make a judgment on this. I will just state the results.

**Comment by davepagurek** [comment]
I think the framebuffer one is solvable but would mean not applying filters on a separate graphic, and instead using another framebuffer in the same WebGL context. That's something we probably want to look into anyway for filters on WebGL canvases as it'll be faster than using a graphic. Feel free to open an issue for that too if you're interested! Otherwise I'll also get around to filing one at some point.

**Comment by inaridarkfox4231** [comment]
I checked several pull requests related to the development of the filter() specification. I got the impression that the situation to which it would be applied was fixed, and it was just a matter of matching the appearance. However, since image() is a function that draws the board, the effects of transform and blend cannot be avoided. I think that should have been considered.
