### ISSUE TITLE
perspective() documentation needs updating now that the default field of view is different

### ISSUE THREAD

**Issue by davepagurek** [processing/p5.js#6519]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

main branch

### Web browser and version

N/A

### Operating System

N/A

### Steps to reproduce this

In [the reference for `perspective()`](https://p5js.org/reference/#/p5/perspective), we say:

> If no parameters are given, the following default is used: perspective(PI/3, width/height, eyeZ/10, eyeZ*10), where eyeZ is equal to ((height/2) / tan(PI/6)).

This is no longer the case: now, the default `eyeZ` camera field of view is this: https://github.com/processing/p5.js/blob/6b7c51154f3b03f8f7883a32d39962c9cf17ccc8/src/webgl/p5.Camera.js#L1952-L1954

We should mention that we use a fixed location and variable field of view. The default values currently documented shouldn't be fully removed though: if one wants a fixed field of view, we can suggest using those defaults instead.

**Comment by Abjcodes** [comment]
Hey @davepagurek, Can I work on this?

**Comment by davepagurek** [comment]
Thanks @Abjcodes, go ahead!

**Comment by Garima3110** [comment]
Hey @Abjcodes  any update on working on this issue. ? Please let me know if I can help you in any way in addressing this issue.
Thankyou!

**Comment by Abjcodes** [comment]
Hey @davepagurek & @Garima3110. I am not able to locate the documentation file to which the changes are to be made. Can  you help me out to locate the file? Thank you.

**Comment by Garima3110** [comment]
> Hey @davepagurek & @Garima3110. I am not able to locate the documentation file to which the changes are to be made. Can you help me out to locate the file? Thank you.

Well, I think the changes need to be made in the inline documentation written in this file only.

[src/webgl/p5.Camera.js](https://github.com/processing/p5.js/blob/v1.8.0/src/webgl/p5.Camera.js#L119)

@davepagurek Please correct me if I am wrong.
