### ISSUE TITLE
createFilterShader throws an error in 2D mode

### ISSUE THREAD

**Issue by davepagurek** [processing/p5.js#6520]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

1.8.0

### Web browser and version

Firefox 117

### Operating System

macOS 14

### Steps:
1. Create a sketch in 2D mode
2. Create a filter shader with `createFilterShader`

You get an error about only being able to do this in WebGL mode.

This is because initially, we were thinking of letting `createFilterShader` be a way to make custom shaders that can be used in general, not just in `filter`. However, since https://github.com/processing/p5.js/pull/6482, we auto-bind these to the filter graphic anyway.

I propose that we:
1. take out this error so that even 2D users can use custom filter shaders that people make
2. add a separate method (`createCustomFragmentShader`?) to create a normal shader using a default vertex shader

**Comment by SableRaf** [comment]
Hey @davepagurek. This may be a silly question but is there a reason we can't have the `createShader()` and `loadShader()` functions also accept a frag shader as a single argument and automatically call something like your proposed `createCustomFragmentShader` function internally?

**Comment by davepagurek** [comment]
That's not a silly question, I think making `create/loadShader` also accept just a fragment shader would also work for (2)! 

Initially I was thinking that one reason why we might want to have a separate name mentioning a fragment shader is so that we could potentially do the reverse as well, and have another method where you only specify a custom vertex shader (e.g. for this https://openprocessing.org/sketch/1934027) but that's a less common use case, and may be covered better by a more versatile API like https://github.com/processing/p5.js/issues/6144.

**Comment by davepagurek** [comment]
This is closed now thanks to #6559!
