### ISSUE TITLE
erase() and noErase() support in framebuffers

### ISSUE THREAD

**Issue by acamposuribe** [processing/p5.js#6523]
### Topic

I'm trying to execute erase() and noErase() within the framebuffer.begin() and framebuffer.end() functions, but they seem to be ignored. Bug or feature missing?
Thanks in advance!

**Comment by davepagurek** [comment]
Sounds like a bug! Are you able to make a minimal example in a p5 editor sketch to debug with?

**Comment by acamposuribe** [comment]
> Sounds like a bug! Are you able to make a minimal example in a p5 editor sketch to debug with?

Yes! There you have it:
https://editor.p5js.org/acamposuribe/sketches/gaVBVGKu-

The erase() function is erasing the main canvas, rather than the framebuffer.

**Comment by davepagurek** [comment]
If I comment out the last line with the `image()` call, then the black background is still preserved. I think the bug isn't that it's erasing the main canvas, but that `erase` is actually replacing with fully opaque white. Which is definitely still a bug!

**Comment by acamposuribe** [comment]
> If I comment out the last line with the `image()` call, then the black background is still preserved. I think the bug isn't that it's erasing the main canvas, but that `erase` is actually replacing with fully opaque white. Which is definitely still a bug!

Yes, you're definitely right!

**Comment by davepagurek** [comment]
Looks like the bug is here:
https://github.com/processing/p5.js/blob/28740f9cda2e6983bd27c0564cd029fa9241d733/src/webgl/p5.RendererGL.js#L1165

`_applyBlendMode` just updates the WebGL blending to match what p5 has set it to, and doesn't actually take any arguments. I think this should be just `blendMode(REMOVE)`, which seems to work:
https://editor.p5js.org/davepagurek/sketches/DvUOkmTwM

**Comment by acamposuribe** [comment]
This makes the whole framebuffer white, though?

**Comment by davepagurek** [comment]
You're right! Just updated the sketch again, looks like we still have to call `_applyBlendMode()` after setting the blend mode.

**Comment by acamposuribe** [comment]
> You're right! Just updated the sketch again, looks like we still have to call `_applyBlendMode()` after setting the blend mode.

Yes! Although noErase() was not working, because blendMode was not changing to the original one. We need to store the current blendmode and pass it at the end. I made a bad fix:

https://editor.p5js.org/acamposuribe/sketches/rBOTxXyvu

**Comment by davepagurek** [comment]
Thanks! Are you interested in combining the changes in that sketch into a PR?

**Comment by acamposuribe** [comment]
> Thanks! Are you interested in combining the changes in that sketch into a PR?

I'm pretty new to OpenSource. Currently creating a p5 library as a first contribution to the project.
Never made a pull request before....

**Comment by davepagurek** [comment]
If youre interested, I can help walk you through it! We also have a [p5 discord](https://discord.gg/PfYuMAX3Ed) where you can ask questions faster. If you'd rather not though, that's also totally fine!
