### ISSUE TITLE
Image light performance improvements

### ISSUE THREAD

**Issue by davepagurek** [processing/p5.js#6531]
### Increasing Access

https://github.com/processing/p5.js/pull/6255 is now merged and adds new lighting features to p5.

We have not yet spent much time optimizing it. There is potential room to keep the feature working the same, but have it load faster, and also run faster, to let this feature work better on more devices.

### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### Feature enhancement details

Some things we think would be worth doing for sure:
- Calculate diffuse and specular textures in Framebuffers instead of `p5.Graphics`. It is known that keeping everything in the same WebGL context will be faster in general, and will avoid browser issues where it [has trouble with having many WebGL contexts.](https://github.com/processing/p5.js/issues/6212) Additionally, we send `p5.Graphics` data to the GPU every frame when using one in a shader, but don't for `p5.Framebuffer`, so this will save on runtime performance.
- Refine into the number of samples used when creating diffuse/specular textures. It may still look OK if we use fewer samples but apply dithering to the sample locations, which is [a strategy we use in our blur shader.](https://github.com/processing/p5.js/issues/6397)

Less sure changes that need some benchmarking:
- Would it make it run faster to use cubemaps instead of equirectangular textures, which require trig to calculate texture coordinates?

**Comment by Garima3110** [comment]
Hey @davepagurek  , I am interested in working on  this issue. Thank you!

**Comment by davepagurek** [comment]
@Garima3110 if you're interested in handling the cubemap part, maybe we can split that out into a separate issue so we know what parts are being worked on? I'm realizing that any of the bullet points mentioned in the original issue could probably be done independently without needing to do all of them at once.

**Comment by Garima3110** [comment]
> @Garima3110 if you're interested in handling the cubemap part, maybe we can split that out into a separate issue so we know what parts are being worked on? I'm realizing that any of the bullet points mentioned in the original issue could probably be done independently without needing to do all of them at once.

Yeah sure  @davepagurek , we can do that..!!

**Comment by Garima3110** [comment]
> ### Increasing Access

@davepagurek should I open separate issues for the bullet points mentioned or you would do that?

**Comment by perminder-17** [comment]
> ### Increasing Access
> #6255 is now merged and adds new lighting features to p5.
> 
> We have not yet spent much time optimizing it. There is potential room to keep the feature working the same, but have it load faster, and also run faster, to let this feature work better on more devices.
> 
> ### Most appropriate sub-area of p5.js?
> * [ ]  Accessibility
> * [ ]  Color
> * [ ]  Core/Environment/Rendering
> * [ ]  Data
> * [ ]  DOM
> * [ ]  Events
> * [ ]  Image
> * [ ]  IO
> * [ ]  Math
> * [ ]  Typography
> * [ ]  Utilities
> * [x]  WebGL
> * [ ]  Build Process
> * [ ]  Unit Testing
> * [ ]  Internalization
> * [ ]  Friendly Errors
> * [ ]  Other (specify if possible)
> 
> ### Feature enhancement details
> Some things we think would be worth doing for sure:
> 
> * Calculate diffuse and specular textures in Framebuffers instead of `p5.Graphics`. It is known that keeping everything in the same WebGL context will be faster in general, and will avoid browser issues where it [has trouble with having many WebGL contexts.](https://github.com/processing/p5.js/issues/6212) Additionally, we send `p5.Graphics` data to the GPU every frame when using one in a shader, but don't for `p5.Framebuffer`, so this will save on runtime performance.
> * Refine into the number of samples used when creating diffuse/specular textures. It may still look OK if we use fewer samples but apply dithering to the sample locations, which is [a strategy we use in our blur shader.](https://github.com/processing/p5.js/issues/6397)
> 
> Less sure changes that need some benchmarking:
> 
> * Would it make it run faster to use cubemaps instead of equirectangular textures, which require trig to calculate texture coordinates?

Hi @davepagurek , your time optimization approach really looks good to me. I'm thinking of using `createFramebuffer` directly instead of `createGraphics` and structuring everything within `draw()`, or possibly employing `begin()` and `end()`. Do you believe this is the right path, or does implementing p5.framebuffer require some additional steps?

**Comment by perminder-17** [comment]
I am working on this issue.

**Comment by Garima3110** [comment]
> I am working on this issue.

Since I was already working on the cubemap part , please be specific which parts are you working on..???

**Comment by Garima3110** [comment]
> > I am working on this issue.
> 
> Since I was already working on the cubemap part , please be specific which parts are you working on..???



> > I am working on this issue.
> 
> Since I was already working on the cubemap part , please be specific which parts are you working on..???
>Also please notice that i had already shown interest in solving this issue prior to u. So according to the code of conduct of contributing to p5, this seems wrong to me. Hope you understand and do not repeat the same later on . Providing your suggestions is totally fine ..!

**Comment by Garima3110** [comment]
> > > I am working on this issue.
> > 
> > 
> > Since I was already working on the cubemap part , please be specific which parts are you working on..???
> 
> > > I am working on this issue.
> > 
> > 
>  Since I was already working on the cubemap part , please be specific which parts are you working on..???
>  Also please notice that i had already shown interest in solving this issue prior to u. So according to the code of conduct of contributing to p5, this seems wrong to me. Hope you understand and do not repeat the same later on . Providing your suggestions is totally fine ..!

**Comment by perminder-17** [comment]
> > > I am working on this issue.
> 
> > >
> 
> Also please notice that i had already shown interest in solving this issue prior to u. So according to the code of conduct of contributing to p5, this seems wrong to me. Hope you understand and do not repeat the same later on . Providing your suggestions is totally fine ..!

Oohk I am sorry.

**Comment by perminder-17** [comment]
> > I am working on this issue.
> 
> Since I was already working on the cubemap part , please be specific which parts are you working on..???

Okay, so I was going to implement framebuffer for diffuse and specular textures instead of p5.graphics.

**Comment by perminder-17** [comment]
> > > I am working on this issue.
> 
> > >
> 
> Also please notice that i had already shown interest in solving this issue prior to u. So according to the code of conduct of contributing to p5, this seems wrong to me. Hope you understand and do not repeat the same later on . Providing your suggestions is totally fine ..!

My intentions are not to break any of the code of conduct. As you mentioned above you are handling cubemaps part so i think filing a seperate issue will be a good option for covering this. Maybe we can implement framebuffer in this issue. 

Let me know what's your call on this @Garima3110

**Comment by Garima3110** [comment]
@davepagurek 

> @Garima3110 if you're interested in handling the cubemap part, maybe we can split that out into a separate issue so we know what parts are being worked on? I'm realizing that any of the bullet points mentioned in the original issue could probably be done independently without needing to do all of them at once.

In view of this , I have opened separate issue for every idea suggested by @davepagurek so that every issue is solved separately. Thankyou..!
I hope this looks good to you  @davepagurek !!

**Comment by davepagurek** [comment]
Thanks for making those issues @Garima3110! I'll close this issue so we can just use those ones. @perminder-17, I'll assign the framebuffer one to you.
