### ISSUE TITLE
Replace `hypot()` in calculation.js with `Math.hypot()`

### ISSUE THREAD

**Issue by GregStanton** [processing/p5.js#6536]
### Increasing Access

Currently, calculation.js contains about 40 lines of code that are no longer necessary due to browser updates. Removing unnecessary complexity makes it easier for contributors to work with the codebase.

### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [x] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### Feature enhancement details

**Problem:**
The [`hypot()`](https://github.com/processing/p5.js/blob/v1.8.0/src/math/calculation.js#L733) function [was added to calculation.js in 2016](https://github.com/processing/p5.js/commit/bd57c6e2f9e4ee568dd6032538203644d3cb2fa8). Its job is to call the native `Math.hypot()` if it's supported and to provide a fallback function if not. At the time, [`Math.hypot()` was relatively new](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/hypot#browser_compatibility), but it's now been widely supported for close to a decade and is already used directly in [3d_primitives.js](https://github.com/processing/p5.js/blob/17304ce9e9ef3f967bd828102a51b62a2d39d4f4/src/webgl/3d_primitives.js#L1791), [interaction.js](https://github.com/processing/p5.js/blob/17304ce9e9ef3f967bd828102a51b62a2d39d4f4/src/webgl/interaction.js#L182), and [p5.Camera.js](https://github.com/processing/p5.js/blob/17304ce9e9ef3f967bd828102a51b62a2d39d4f4/src/webgl/p5.Camera.js#L2096). The `hypot()` code now adds unnecessary complexity and performs an unnecessary check every time `dist()` or `mag()` is called (these functions call `hypot()` internally).

**Solution:**
Remove `hypot()` from calculation.js and replace calls to it (from the definitions of [`dist()`](https://github.com/processing/p5.js/blob/17304ce9e9ef3f967bd828102a51b62a2d39d4f4/src/math/calculation.js#L173)) and [`mag()`](https://github.com/processing/p5.js/blob/17304ce9e9ef3f967bd828102a51b62a2d39d4f4/src/math/calculation.js#L342)) with calls to `Math.hypot()`.

**Comment by Garima3110** [comment]
Hey @GregStanton  I would like to work on this issue.
Thank you..!

**Comment by GregStanton** [comment]
That's great @Garima3110! Thank you!

**Comment by manishjha-04** [comment]
hey is the issue assigned? I would like to work on this issue!!

**Comment by diyaayay** [comment]
Hey @GregStanton 
I would like to work on this issue. 
Thankyou.

**Comment by GregStanton** [comment]
Thanks @diyaayay! I left [a review](https://github.com/processing/p5.js/pull/6537#pullrequestreview-1721540425). Just waiting on the maintainers now to take the next steps.

**Comment by limzykenneth** [comment]
Thanks @diyaayay for the PR. Just want to note that @Garima3110 had indicated intention to fix this first and my preference is to allow people to take their time working on an issue without needing to worry about getting it done quickly. In the future I would prefer prioritizing those who has indicated intention to work on an issue and defer until the original contributor indicated they are no longer willing to work on it or if sufficient time has passed (at least one month). Thanks!

**Comment by diyaayay** [comment]
Hey @limzykenneth , Thankyou for letting me know. This was my first time at open source contributions. Will surely keep the code of conduct from now onwards. Thanks!

**Comment by Garima3110** [comment]
> Thanks @diyaayay for the PR. Just want to note that @Garima3110 had indicated intention to fix this first and my preference is to allow people to take their time working on an issue without needing to worry about getting it done quickly. In the future I would prefer prioritizing those who has indicated intention to work on an issue and defer until the original contributor indicated they are no longer willing to work on it or if sufficient time has passed (at least one month). Thanks!

Thanks @limzykenneth !
