### ISSUE TITLE
Pan y-axis inverted in frameBuffer

### ISSUE THREAD

**Issue by wagedu** [processing/p5.js#6538]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

1.8.0

### Web browser and version

Any

### Operating System

Any

### Steps:
1. Use framebuffer with orbitControl inside
2. Drag clicking right mouse button
3.

### Snippet:

```js
let layer;
function setup() {
  createCanvas(400, 400, WEBGL);
  layer = createFramebuffer();
}

function draw() {
  layer.begin();
  orbitControl();
  background(220);
  sphere(150);
  layer.end();
  image(layer,-width/2,-height/2)
}

```

**Comment by davepagurek** [comment]
Cameras on framebuffers will have `yScale = -1`: https://github.com/processing/p5.js/blob/17304ce9e9ef3f967bd828102a51b62a2d39d4f4/src/webgl/p5.Framebuffer.js#L30

So we probably just need to multiply by that property of the active camera when updating using `oribtControl`

**Comment by perminder-17** [comment]
https://editor.p5js.org/aman12345/sketches/89htfYFM8 

Is this the expected behaviour?

**Comment by davepagurek** [comment]
That looks good to me @perminder-17!

**Comment by perminder-17** [comment]
> That looks good to me @perminder-17!

Let me make a PR then.
