### ISSUE TITLE
suggestion about createCanvas argument naming

### ISSUE THREAD

**Issue by micuat** [processing/p5.js#6548]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

1.8.0

### Steps to reproduce this

I'm a bit confused about the arguments of `createCanvas`.

In this part where detecting the case `createCanvas(w, h, canvas)`:

https://github.com/processing/p5.js/blob/8e97213d0e520c784449b6735394b6186698e58f/src/core/rendering.js#L76-L81

I think instead of the variable `renderer` (which is not used afterwards), the constant should be assigned to `r`. Furthermore, to me it makes sense to rename the arguments to `createCanvas(w, h, ...args)` or so and unpack it later to avoid duplication of `r`, `renderer` and so on.

The change seemed to be introduced with this PR (nevertheless I really love this feature) https://github.com/processing/p5.js/pull/6229

**Comment by Sejal1411** [comment]
would like to work on this issue. Please assign!
