### ISSUE TITLE
nf( ); Does not seem to be truncating numbers / nfp( ); Returns "[object Arguments]"

### ISSUE THREAD

**Issue by piinthecloud** [processing/p5.js#655]
nf( ); seems to be returning a string, but isn't truncating numbers on the right. See return value below:
            >  nf(2.123456, 2, 2);
            >  "02.123456"

nfp( );, which uses nf( ); always returns the string "[object Arguments]":
            >   nfp(2.12345, 1, 1);
            >  "[object Arguments]"

nfs( ); also uses nf( ); and does not return expected results.

**Comment by workergnome** [comment]
Looking into this now.

**Comment by mxchelle** [comment]
I got the 2 nf bugs down, but I opened another thread that talks about how documentation doesn't fit the functionality of the nf family (https://github.com/processing/p5.js/issues/686)

**Comment by workergnome** [comment]
I believe @mxchelle has resolved all of these issues—can you confirm?

**Comment by lmccart** [comment]
just about to merge it in

**Comment by workergnome** [comment]
Sorry!  Getting overexcited.  :blush:

**Comment by lmccart** [comment]
just reviewed the code and tested the examples above. seems all good, thanks everyone
