### ISSUE TITLE
suggestion for changes in createcanvas method's arguments

### ISSUE THREAD

**Issue by aatiw** [processing/p5.js#6551]
### Increasing Access

unsure

### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [X] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### Feature enhancement details

Refactor the code to use a more descriptive parameter by renaming the arguments and using the rest parameter (...args). This can enhance code readability.
![Screenshot 2023-11-11 192808](https://github.com/processing/p5.js/assets/114896288/d2228bc8-d47a-49d3-8202-d1f91b728a68)

this issue is similar to #6548 .

**Comment by Jaivignesh-afk** [comment]
Can i work on this issue?

**Comment by davepagurek** [comment]
Hi! Could you clarify how this issue differs from #6548? It sounds like they are both identifying the same problem, are you suggesting a different solution?

**Comment by limzykenneth** [comment]
Closing in favour of #6548
