### ISSUE TITLE
image filter doesnt work

### ISSUE THREAD

**Issue by CharStiles** [processing/p5.js#656]
image(img, 0, 0);
  filter(BLUR,5);

on the desktop IDE It works for a second then it increases blur, then crashes . Only will add any filter at all if there is a second parameter (or seems not to work, there might be no default?) no second parameter, it doesnt crash, but there is no change in picture.

Other filters have same effect. Some will just look glitchy before crashing (Erode, opaque, posterize, dilate)

On the website none load

**Comment by lmccart** [comment]
is this bug only with the IDE? looks like they are loading on the website right now. if so, let's close it and move it over here: https://github.com/lmccart/p5.js-editor
