### ISSUE TITLE
Incorrect reference to constants file in p5.Geometry

### ISSUE THREAD

**Issue by limzykenneth** [processing/p5.js#6566]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### Steps to reproduce this

In p5.Geometry.js, the internal constants are not [referenced](https://github.com/processing/p5.js/blob/main/src/webgl/p5.Geometry.js#L12) from the `../core/constants` file correct but instead refers to just "constants" which will not resolve correctly.

**Comment by diyaayay** [comment]
Hey, 
I would like to work on this issue. 
Thanks.

**Comment by limzykenneth** [comment]
@diyaayay You can go ahead with a fix. Thanks.

**Comment by davepagurek** [comment]
Thanks for catching this! Any idea why tests still passed? I'm surprised this didn't trigger a compilation error of some kind

**Comment by limzykenneth** [comment]
I believe it basically assumes that `"constants"` is a global variable or otherwise available in the enrivonment and so would more or less leave it as it. I only found this when rebasing my Rollup branch on `main` here and found that it is complaining and trying to find a global variable called `constants`.
