### ISSUE TITLE
Typo in JSDoc of the createVector method

### ISSUE THREAD

**Issue by cabbage63** [processing/p5.js#6569]
### Topic

I found a typo in the JSDoc of `createVector` method in src/math/math.js.
It seems to have an effect on p5.js web reference. (Unnecessary backquote is printed.)
If you don't mind, I'll create a pull request for this issue.

https://github.com/processing/p5.js/blob/main/src/math/math.js#L24

![image](https://github.com/processing/p5.js/assets/7237868/9f2ab7ea-22e0-4219-b955-99e5b89be447)

**Comment by cabbage63** [comment]
@nickmcintyre 
Thank you.
I've created a PR to fix this issue.
Please check that when you have time.

https://github.com/processing/p5.js/pull/6574

**Comment by nickmcintyre** [comment]
Nice work @cabbage63!
