### ISSUE TITLE
Friendly Error Messaging for unsupported browsers

### ISSUE THREAD

**Issue by workergnome** [processing/p5.js#657]
As part of our browser detection, we have discovered the desire to display to viewers of p5.js sketches messaging about used features that are not supported by their browser.

We would like these messages to be user-facing, to be able to be disabled by the developer, to have their text have friendly defaults, and to have the messaging customizable by the developer.

We should consider how to detect usage of a feature (webgl, web audio, etc) by a p5.js sketch.

An initial suggestion was to overlay a DOM element over the sketch, that fades out over time.

Suggestions?  Discussions?

**Comment by kadamwhite** [comment]
Sounds like a good plan! Initial thoughts :

- an overlay sounds good, but the canvas could be a lot of sizes -- possibly better to have it fixed to the viewport instead 
- should we provide internationalization for the default messages? I'm inclined to think that letting developers set their own is sufficient, but wanted to think out loud to see what everyone else thought

**Comment by crhallberg** [comment]
Is the idea that you'd an overlay if your browser doesn't support a feature at all or only when that feature is used in the sketch being run?

**Comment by workergnome** [comment]
pinging @therewasaguy, who proposed the initial idea.

**Comment by lmccart** [comment]
aggregated into https://github.com/processing/p5.js/issues/971
