### ISSUE TITLE
The text in example diagram for p5.SoundRecorder() is not properly visible, when recording is stopped.

### ISSUE THREAD

**Issue by Garima3110** [processing/p5.js#6570]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [X] Other (specify if possible)

### p5.js version

v1.8.0

### Web browser and version

119.0.6045.160

### Operating System

Windows 11 Version 22H2

### Steps:
1.Navigate to this link : https://p5js.org/reference/#/p5.SoundRecorder
2.Then tap on the example diagram, record something and again tap the diagram to see the problem.

### Actual Behavior

<img width="177" alt="image" src="https://github.com/processing/p5.js-website/assets/110815240/4313574f-2ac4-4b07-be47-d2da13b97cd5">

### Expected Behavior

The displayed text should be aligned in the center so that it is clearly visible, when the recording is stopped.

### Would you like to work on the issue?

Yes , I would like to work on this issue.

**Comment by davepagurek** [comment]
Hi! The spot to fix this is not in the p5.js repo, but [in the p5.js-sound repo.](https://github.com/processing/p5.js-sound) The version of the sound library in this repo will get overwritten with the content from that repo every time we make a new release. Could you make your change in there instead?

**Comment by Garima3110** [comment]
> Hi! The spot to fix this is not in the p5.js repo, but [in the p5.js-sound repo.](https://github.com/processing/p5.js-sound) The version of the sound library in this repo will get overwritten with the content from that repo every time we make a new release. Could you make your change in there instead?

Yeah sure @davepagurek ! Didn't know about this , my aplologies.

**Comment by davepagurek** [comment]
no problem!
