### ISSUE TITLE
[v1.8.0] p5.js framerate fps cross-browser artificial caps and inconsistencies

### ISSUE THREAD

**Issue by christopherball** [processing/p5.js#6572]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [X] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

1.8.0

### Web browser and version

Brave 1.60.114, Chrome 119.0.6045.159, Safari 17.1

### Operating System

MacOS Ventura 13.6.1

### Steps:
1. Take my very basic example code below that includes some minor logging comparisons.
2. Run it on any of the browsers (refresh between FPS code changes) I've specified in this ticket, adjusting the `desiredFPS` value between 20, 60, and 100 (I have a brand new mac with a 100hz display monitor).
3. Take note of two things: a) The differences in FPS measurement between both logged forms.  b) The very odd artificial FPS cap that appears approximately the same between browsers at or anywhere near a setting of 60, even though my system can easily render 100fps as it shows in the final screenshot.

### Snippet:

```js

import p5 from "p5";

class Sketch extends p5 {
  constructor() {
    super(() => {});
  }

  setup() {
    this.createCanvas(400, 400);
    const desiredFPS = 20;
    this.frameRate(desiredFPS);
    console.log(
      "Setup includes initialization of framerate(" + desiredFPS + ")..."
    );
  }

  draw() {
    this.background(220);
    this.ellipse(50, 50, 80, 80);

    if (this.frameCount % 100 == 0) this.fpsLogger();
  }

  fpsLogger() {
    console.log(
      "frameCount / (millis() / 1000.0): " +
        this.frameCount / (this.millis() / 1000.0)
    );
    console.log("frameRate: " + this.frameRate());
  }
}

window.sketch = new Sketch();

```
Setting `frameRate(20)` (No major issues at this low framerate...keep scrolling...)
![image](https://github.com/processing/p5.js/assets/5790394/d53c7cda-2f5e-4036-8ecc-300501e5c281)

Setting `frameRate(60)` (Why am I only getting ~50fps across any browsers?)
![image](https://github.com/processing/p5.js/assets/5790394/da034f86-18e6-47d9-b6eb-fd9e6a60f5c5)

Setting `frameRate(100)` (Clearly attaining 100fps is not a problem...)
![image](https://github.com/processing/p5.js/assets/5790394/c4819546-422f-4162-976e-3b6fe1e9eea3)

**Comment by davepagurek** [comment]
Not a definitive answer but a theory: it's very hard to hit a consistent frame rate in the browser that isn't a whole number multiple of the display rate. p5 uses `requestAnimationFrame` to run a callback every time the browser repaints the screen. 100fps is ok: p5 just draws at the same rate as the screen. 50fps is also ok: p5 just draws every second frame. I assume 25 would be ok too, since it just draws once every four frames. Something like 60 is harder, and we'd only be able to hit 60fps *on average* by trying to draw too fast or two slow repeatedly to get as close as possible. Our algorithm for doing that isn't super advanced, and that's why it doesn't hit it exactly.

**Comment by davepagurek** [comment]
See this related issue, which notices a cap at 30fps, which is also a whole number multiple of a display that runs at 60Hz: https://github.com/processing/p5.js/issues/5450

**Comment by christopherball** [comment]
I believe I follow your theory.  From a js framework perspective, being locked into a whole number multiple of the refresh rate of the monitor (by default, a whole number multiple **at or below** 60), is _very_ misleading and personally caused me to move onto other seemingly more performant frameworks originally, only to come back a while later to investigate how even fragment shaders performing simple tasks were hitting the same low fps.

My original thought at the time was, if p5.js can't even hit the default 60fps setting for basic tasks, there's no point in setting it any higher.  Clearly my assumption was incorrect because of my higher refresh rate and I luckily tried setting frameRate() to said refresh rate.  I suggest two things:

1. In the short term, an update to the [documentation for framerate](https://p5js.org/reference/#/p5/frameRate) is likely warranted to very clearly articulate this nuanced behavior so that users don't abandon the framework or view it as under performant, or worse, assume their own hardware is inadequate.
2. Longer term, it would certainly be sweet if the `requestAnimationFrame` logic was decoupled from the monitor refresh rate so that this confusion could be eradicated entirely.

**Comment by davepagurek** [comment]
What did you end up switching to out of curiosity? I wonder if they either don't use requestAnimationFrame (e.g. with timers, not in sync with the monitor refresh rate, but may have extra overhead from the extra repaints) or implemented better logic to schedule their renders across those whole number multiples.

**Comment by christopherball** [comment]
> What did you end up switching to out of curiosity?

I've been giving pixi.js a go for a bit, as it has a reputation as being very performant for 2d-related tasks.  My only real reason for taking another look at p5.js was I honestly prefer the way the library is organized and the enthusiastic community.

**Comment by limzykenneth** [comment]
Pixi.js is also using [`requestAnimationFrame`](https://github.com/pixijs/pixijs/blob/c04c09c50874fef9296555af23e25fe58cc808a9/packages/ticker/src/Ticker.ts#L133) and also doesn't [recommend](https://pixijs.com/guides/basics/render-loop?_highlight=render&_highlight=loop#frame-rates) trying to draw faster than the screen refresh rate. Other libraries like Three.js don't even provide animation loop and in all their examples uses `requestAnimationFrame` as well. Pixi.js also contains the following advice:

>  Just be aware that due to the complex environment, your project cannot guarantee a given FPS.

`requestAnimationFrame` is not likely to be decoupled from the screen refresh rate as the reasoning for it is to have a consistent API to draw things (both on canvas and painting HTML elements) which don't make sense to be done at a rate faster than the screen refresh rate (eg. updating a HTML element multiple times between two ticks of the monitor will only cause the last update to actually be shown while still needing to pay the CPU cost of updating the DOM multiple times, which is super inefficient).

Given screen refresh rate being a consistent value, it becomes ambiguous what a lower framerate means. Discussions in #5354 is actually pretty useful and the example [sketch](https://editor.p5js.org/delphi1024/sketches/lF1shtB_L) is really good for demonstrating what actually happens.

JS being a single threaded async environment make it not possible to provide a separate `update` and `draw` loop like what some game engine may provide. I believe the confusion stems from game engine often report frame rate of the `update` loop which can be more or less uncapped/consistent for any value while the actual painting still happens at screen refresh rate anyway. Web Workers in theory make JS multi threaded but communication between the main thread and the worker is evented still so the timing will not likely be precise and I've never seen any JS libraries attempt these kinds of exotic setup.

We can definitely reword the documentation but I would like to make sure we really clear up the overall behavior so we don't keep circling back for frame rate issues.

**Comment by christopherball** [comment]
> Pixi.js is also using [requestAnimationFrame](https://github.com/pixijs/pixijs/blob/c04c09c50874fef9296555af23e25fe58cc808a9/packages/ticker/src/Ticker.ts#L133) and also doesn't [recommend](https://pixijs.com/guides/basics/render-loop#frame-rates) trying to draw faster than the screen refresh rate.

I haven't tried to draw faster than my screen refresh rate to be clear.  Adding a couple examples to the documentation and an explicit mention of the "whole number multiples of your monitor display rate" constraint would go a long way here.
