### ISSUE TITLE
Different results are obtained when drawing in TESS mode using begin-endShape in WEBGL

### ISSUE THREAD

**Issue by inaridarkfox4231** [processing/p5.js#6573]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

1.8.0

### Web browser and version

Chrome

### Operating System

Windows11

### Steps:
1. Perform drawing with TESS using begin~endShape()
2. When you run this in 1.8.0, even-odd is not applied and the whole becomes one mesh.
3.But in 1.7.0 it looks like even-odd has been applied and there are holes.

### Snippet:

[TESS_BUG?](https://openprocessing.org/sketch/2098354)
```js

function setup() {
  createCanvas(400, 400, WEBGL);

  noStroke();
  fill(255);
  background(0);

  beginShape();
  vertex(160*0.7, -160*0.3);
  for(let i = 0; i <= 800; i++){
    let index = i;
    const t = TAU * index / 800;
    const x = 160 * (0.7*cos(5*t) - 0.3*sin(4*t));
    const y = 160 * (0.7*sin(5*t) - 0.3*cos(4*t));
    vertex(x, y);
  }
  vertex(160*0.7, -160*0.3);
  endShape();
}

```

## version 1.7.0

![ばぐ？2](https://github.com/processing/p5.js/assets/39549290/5cef11cf-a8d0-42b8-90bb-c787f2275577)

## version 1.8.0

![ばぐ？1](https://github.com/processing/p5.js/assets/39549290/bb69a479-f635-434d-b68a-9601c8397212)

I'm not sure about the cause of this. Did the specification change make this one correct? Or is there some easy way to achieve the previous behavior? With that, I would like to raise an issue.

I decided to treat this as a bug because the default behavior is different.

I don't have the time to work on this, so if this is behavior that needs to be fixed, I'll leave it to someone who is willing to fix it.

**Comment by inaridarkfox4231** [comment]
Even if this is a bug or not, I don't want the behavior to be different, so the following code uses 1.7.0.

[3D Drawing](https://openprocessing.org/sketch/1892891)

**Comment by perminder-17** [comment]
I think this is a bug,  I've noticed something off lately and I'm wondering if it might be a bug. Specifically, we seem to be facing some issues in WebGL mode, though I'm not entirely sure. I wanted to reach out and get your thoughts on this @davepagurek
 
![circle non-webgl](https://github.com/processing/p5.js/assets/127239756/2efdd53a-c956-44f7-aa39-71f7a159032f)
Circle Non-WEBGL
![circle webgl](https://github.com/processing/p5.js/assets/127239756/7e7d66da-9d90-48c3-bdf3-f72e3ceacb6b)

Do you think this is a bug, and something related to this issue?

**Comment by davepagurek** [comment]
@perminder-17 are you showing the edges on the circle as the bug? I think that particular bit is not a regression, but a separate issue, where [you can supply the `detail` parameter for `ellipse`](https://p5js.org/reference/#/p5/ellipse) but not for `circle`. Adding that parameter is a separate issue (worth filing and fixing if you're interested!)

For the `TESS` behaviour, this was intentionally changed [to match 2D mode's rendering.](https://editor.p5js.org/davepagurek/sketches/OgW62t09T) I think changing the winding order is a valid use though, how would you feel about adding something like `windingRule(NONZERO)` and `windingRule(EVENODD)`? This is how we currently initialize `libtess`, we could move this to happen before each tesselation we do based on the current rule:
https://github.com/processing/p5.js/blob/cab0ff1d039ecc28b0ab4e1fbfeced200b13db9a/src/webgl/p5.RendererGL.js#L2309-L2312

**Comment by inaridarkfox4231** [comment]
I see! It was unnatural for the behavior to be different from 2D, so they fixed it. I got it. It's not a bug. I'll close this issue.

**Comment by inaridarkfox4231** [comment]
There are a lot of issues that need to be addressed, so if it's not a bug, there's probably no need to discuss it any further.

**Comment by inaridarkfox4231** [comment]
@perminder-17 I would appreciate it if you could refrain from bringing up unrelated topics and causing confusion. Please think carefully about what is being discussed in this issue before commenting.

**Comment by davepagurek** [comment]
@inaridarkfox4231 I'm thinking of adding something like this https://github.com/processing/p5.js/issues/6576 to make it easier to catch regressions, let me know if you think that would help or if you have any suggestions!
