### ISSUE TITLE
Add visual tests to prevent regressions

### ISSUE THREAD

**Issue by davepagurek** [processing/p5.js#6576]
### Topic

This is something I've been thinking of adding to our test suite, but I wanted to make an issue to discuss it first so that when I get around to adding it, it can incorporate any feedback and suggestions people have.

## Motivation

- It's pretty hard to make changes and make sure we haven't broken *something*
- We have a good set of tests, but many of these tests are brittle because they don't check that sketches look the way we expect, they check via proxy: sometimes they check one or two pixels, other times they check that p5 internals are in an expected state
- Writing unit tests that check proxy outcomes like internal state are harder to write than test sketches, which is something contributors are already familiar with

## What are visual tests?

These would be a series of small sketches that we write when we add new features. The idea is that they look correct right now, so we save an image of what they look like. Then, when future changes are made, we can run them again and make sure they still look like that saved image.

## Design

I'm thinking of implementing something like this:

You write test cases with a custom test wrapper function:
```js
testVisual('drawing a circle', (p5, screenshot) => {
  p5.setup = function() {
    createCanvas(100, 100);
  }
  p5.draw = function() {
    p5.fill('red');
    p5.circle(p5.width/2, p5.height/2, 20);
    screenshot(); // This is like `done()` in normal tests
  }
})
```

Under the hood, this translates into something like:
```js
function testVisual(name, callback) {
  test('[visual] ' + name, () => {
    const myp5 = new p5();
    return new Promise((resolve) => {
      callback(myp5, resolve);
    }).then(() => {
      // TODO: take screenshot and follow the logic below
    });
  });
}
```

Once the `screenshot` method is called, we:
- Call `canvas.toDataURL()` on the underlying canvas element
- Check for a file in a screenshots folder matching the name of the test case
  - If the file does not yet exist and we're in the CI runner, fail the test case
  - If the file does not yet exist and we're running locally, write the image to a png file with the expected name.
  - If the file does exist, load it, and compare each pixel. Pass the test case if every pixel value is the same within a small threshold (e.g. 2/255)

Ideally, I'd also add a page in the `grunt yui:dev` server to easily see the saved images and to rerun tests, but as a first step, these would just get run as part of the normal test suite, where you can use the existing test filtering to `grep` for `[visual]` to just run visual tests.

## Open questions

- The threshold might need some change based on how different it ends up being on different systems. Maybe we don't need EACH pixel to be the same, as long as like 99% of them are the same? That might need some trial and error since I don't yet know how exact we can expect results to be (or how big a change regressions generally cause.)
- How slow is it to run this for a lot of images on Github's test runner? Do we need to resize images down to something small (20x20?) before comparing so we loop over fewer pixels?

**Comment by davepagurek** [comment]
I believe someone (@limzykenneth?) mentioned the p5.js-svg test suite as an example of a good visual presentation of these sorts of tests: http://zenozeng.github.io/p5.js-svg/test/

**Comment by limzykenneth** [comment]
The p5.js-svg test is pretty good and along the lines of what I'm thinking of, ie. more of a web page where visual inspection can be done, this is also useful for non-static visual test.

The implementation you come up with looks pretty good and can be a place to start while two things to consider:

1. As you identified, there could be minor pixel level differences between runs that make exact comparison not possible, a fuzzy comparison will likely be needed for automated tests. Cross browser rendering differences could potentially cause issues as well.
2. For animated test (eg. testing behavior over multiple frames) we'll probably need multiple screenshots, but shouldn't be that hard to implement

Having lots of test cases over many images might be too slow depending on how fast GitHub Actions run whatever we implement and also how much memory it may take. It might be easier to create this as kind of a manual test suite that runs a server that serves a test page similar to p5.js-svg test that we can check manually, and we can worry about CI as a next step.

In the future I'm potentially investigating using Vitest for the test suite so something that can easily be migrated over in terms of implementation would be great as well.

**Comment by GregStanton** [comment]
This is exciting! I've been thinking and reading a little about this topic, and it [came up in a separate issue](https://github.com/processing/p5.js/issues/6485#issuecomment-1783671690) I posted. 

Here are a few resources I came across that might be helpful, based on a quick glance:
* [Awesome Visual Regression Testing (resource list)](https://github.com/mojoaxel/awesome-regression-testing)
* [Resemble.js (image comparison designed for visual regression testing)](https://github.com/rsmbl/Resemble.js) and associated [online tool](https://rsmbl.github.io/Resemble.js/)
* [pixelmatch (popular, inspired by Resemble.js, about 150 lines of code, seems to offer special features)](https://github.com/mapbox/pixelmatch)
* [JIMP](https://github.com/jimp-dev/jimp) (used by [Nightwatch.js](https://nightwatchjs.org/guide/writing-tests/visual-regression-testing.html) to do the image comparison for visual regression testing)
* [Blog article that discusses issues like a standardized test environment](https://www.shakacode.com/blog/flaky-visual-regression-tests-and-what-to-do-about-them/)
* [Visual Regression Testing Tutorial: Comprehensive Guide With Best Practices](https://www.lambdatest.com/learning-hub/visual-regression-testing)

There may be other resources that are better or more relevant, but some of these (e.g. Resemble.js and pixelmatch) might not come up in a cursory search, and they might help with handling thresholds and related issues.
