### ISSUE TITLE
Commit ccf7764 affects either background() or createCanvas() to load only default background canvas size (100, 100), though rest of sketch loads in full canvas size.

### ISSUE THREAD

**Issue by AmundsenJunior** [processing/p5.js#658]
I use https://raw.githubusercontent.com/processing/p5.js/master/lib/p5.js as my CDN for all my CodePen sketches, and noticed that createCanvas no longer works correctly as of today.

Regardless of arguments to the createCanvas function, it builds the default (100, 100) size of the background(), while the rest of my sketch runs correctly in the full canvas.

The following message appears twice in console.log on my browser when I load the p5.js file from commit ccf7764 into the page:
```
  "pixel density is " 1                                                   p5.js:6094:4
```

Take a look at the sketch in which I'm testing this (http://codepen.io/AmundsenJunior/pen/xGEQBK?editors=101). I currently have the p5.js source file actively loading from commit ccf7764, resulting in the (100, 100) background. If you uncomment the p5.js source file from the previous commit, b2e2f70, the background will load with the rest of the sketch filling the canvas.

**Comment by lmccart** [comment]
ahh a dev branch was accidentally merged into master, apologies! currently working on a rollback, should be up shortly. i'd recommend using the most recent version before this one for now. thanks for the detailed issue writeup.

**Comment by lmccart** [comment]
ok, restored

**Comment by AmundsenJunior** [comment]
Excellent, thanks @lmccart ! Even just seeing this process has got me interested in eventually contributing on p5 development.

Cheers!
