### ISSUE TITLE
Refining the number of samples used when creating diffuse and specular textures. 

### ISSUE THREAD

**Issue by Garima3110** [processing/p5.js#6586]
### Increasing Access

The goal is to find an optimal configuration that ensures smooth execution on various devices while maintaining an acceptable level of visual fidelity. This optimization process is essential for enhancing the overall performance of the feature as ideated by @davepagurek in issue #6531

### Most appropriate sub-area of p5.js?

- [X] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### Feature enhancement details

Refine into the number of samples used when creating diffuse/specular textures. It may still look OK if we use fewer samples but apply dithering to the sample locations, which is [a strategy we use in our blur shader.](https://github.com/processing/p5.js/issues/6397)

**Comment by sudhanshuv1** [comment]
I want to work on this issue. Which files do we have to make changes in specifically?

**Comment by davepagurek** [comment]
Thanks @sudhanshuv1! The way to test this is to try measuring the time it takes to call `imageLight()` for the first time using different numbers of samples in these spots, and how smooth the results look:
https://github.com/processing/p5.js/blob/773eb0d4aaee30238b15d53c955272ac6c53d806/src/webgl/shaders/imageLightDiffused.frag#L51-L56
https://github.com/processing/p5.js/blob/773eb0d4aaee30238b15d53c955272ac6c53d806/src/webgl/shaders/imageLightSpecular.frag#L49

One other thing that can improve performance for specular textures in WebGL2 is here: https://github.com/processing/p5.js/blob/773eb0d4aaee30238b15d53c955272ac6c53d806/src/webgl/shaders/imageLightSpecular.frag#L89
This is working around having no bitwise operations in WebGL1. We can probably replace its implementation with a more efficient version if we're using WebGL2:
```glsl
float VanDerCorput(int n, int base)
{
#ifdef WEBGL2

    uint bits = uint(n);
    bits = (bits << 16u) | (bits >> 16u);
    bits = ((bits & 0x55555555u) << 1u) | ((bits & 0xAAAAAAAAu) >> 1u);
    bits = ((bits & 0x33333333u) << 2u) | ((bits & 0xCCCCCCCCu) >> 2u);
    bits = ((bits & 0x0F0F0F0Fu) << 4u) | ((bits & 0xF0F0F0F0u) >> 4u);
    bits = ((bits & 0x00FF00FFu) << 8u) | ((bits & 0xFF00FF00u) >> 8u);
    return float(bits) * 2.3283064365386963e-10; // / 0x100000000

#else

  float invBase = 1.0 / float(base);
  float denom = 1.0;
  float result = 0.0;


  for (int i = 0; i < 32; ++i)
  {
        if (n > 0)
        {
        denom = mod(float(n), 2.0);
        result += denom * invBase;
        invBase = invBase / 2.0;
        n = int(float(n) / 2.0);
        }
  }


  return result;

#endif
}
```

**Comment by davepagurek** [comment]
oh I think you might have to take your end time measurement after you draw the sphere, since that's when it evaluates all the image light.

Thanks for your tests so far, this looks great! I'm guessing we'll end up going to the lower sample counts that you recommend, but we can measure the time again first just to see how much of a gain we're getting.

We do some sample dithering in the blur shader here, maybe you can try doing something like this in the image light shaders too? https://github.com/processing/p5.js/blob/37d3324b457b177319ed65468201f2806a66eff5/src/webgl/shaders/filters/blur.frag#L50

**Comment by sudhanshuv1** [comment]
Hey @davepagurek 👋, as you suggested, I took the end time measurement after the sphere was drawn. When I used the values `sampleDelta=0.100; SAMPLE_COUNT=16`, I could achieve a gain of about 2 sec. Further decrement in number of samples didn't result in significant time gain, as is evident from this data I gathered:

![time](https://github.com/processing/p5.js/assets/148856416/732246e6-012f-4410-806a-e5ccd22a6f90)

I tried to apply dithering using the same random function that is used in the blur filter [here](https://github.com/processing/p5.js/blob/main/src/webgl/shaders/filters/blur.frag), and tested the results using this code in `imageLightDiffused.frag`: 


```
float random(vec2 p) {
  vec3 p3  = fract(vec3(p.xyx) * .1031);
  p3 += dot(p3, p3.yzx + 33.33);
  return fract((p3.x + p3.y) * p3.z);
}

void main()
{   	 
  float phi = vTexCoord.x * 2.0 * PI;
  float theta = vTexCoord.y * PI;
  float x = sin(theta) * cos(phi);
  float y = sin(theta) * sin(phi);
  float z = cos(theta);
  vec3 normal = vec3( x, y, z);

	vec3 irradiance = vec3(0.0);  
	vec3 up	= vec3(0.0, 1.0, 0.0);
	vec3 right = normalize(cross(up, normal));
	up = normalize(cross(normal, right));

	const float sampleDelta = 0.100;
	float nrSamples = 0.0;
  
	for(float phi = 0.0; phi < 2.0 * PI; phi += sampleDelta)
	{
    for(float theta = 0.0; theta < ( 0.5 ) * PI; theta += sampleDelta)
    {
      // spherical to cartesian (in tangent space) // tangent space to world // add each sample result to irradiance
      float x = sin(theta) * cos(phi);
      float y = sin(theta) * sin(phi);
      float z = cos(theta);
      vec3 tangentSample = vec3( x, y, z);

      float randomOffset = mix(-0.1, 0.1, random(gl_FragCoord.xy));                          

      vec3 sampleVec = tangentSample.x * right + tangentSample.y * up + tangentSample.z * normal + randomOffset;
      irradiance += (texture2D(environmentMap, nTOE(sampleVec)).xyz) * cos(theta) * sin(theta);
      nrSamples++;
    }
	}
	// divide by the total number of samples taken, giving us the average sampled irradiance.
	irradiance = PI * irradiance * (1.0 / float(nrSamples )) ;
  
 
	gl_FragColor = vec4(irradiance, 1.0);
}
```

Dithering made the image brighten up a bit, but the difference wasn't noteworthy until the number of samples were reduced significantly, e.g., the dithered image became much smoother when the values were `sampleDelta=0.250; SAMPLE_COUNT=16` :

![MixCollage-02-Dec-2023-08-30-PM-1355](https://github.com/processing/p5.js/assets/148856416/0d43f0fd-43de-4238-9c2c-12db6cfab654)

But dithering didn't make much of a difference with `sampleDelta=0.100`,  it just made the image somewhat lighter. Please let me know if the results look satisfactory, or any improvements that can be made.

**Comment by davepagurek** [comment]
Sorry for the delay, nice work! I think the dithering looks much better than with no dithering, and is worth the extra time it takes. Would you be interested in making a PR with your changes?

**Comment by sudhanshuv1** [comment]
I am interested in making a PR, I will update the sample numbers to 'sampleDelta=0.100; SAMPLE_COUNT=16' and also replace the implementation of `vanDerCorput` in [p5.js/src/webgl/shaders/imageLightSpecular.frag](https://github.com/processing/p5.js/blob/773eb0d4aaee30238b15d53c955272ac6c53d806/src/webgl/shaders/imageLightSpecular.frag#L89) with the more efficient version in case of WEBGL2. Thanks!
