### ISSUE TITLE
Canvas2D warning in console when using mask() function

### ISSUE THREAD

**Issue by ziyuan-linn** [processing/p5.js#6592]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [X] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

1.8.0

### Web browser and version

Chrome 119.0.6045.160

### Operating System

Windows 11

### Steps:
1. Create a p5 image and a p5 video object.
2. In draw(), mask the image onto the video using the mask function.
3. Check the console for the warning: "Canvas2D: Multiple readback operations using getImageData are faster with the willReadFrequently attribute set to true."

### Snippet:

```js

let video;
let maskImage;

function setup() {
  createCanvas(400, 400);
  video = createCapture(VIDEO);
  maskImage = createImage(400, 400);
}

function draw() {
  video.mask(maskImage);
}

```

**Comment by diyaayay** [comment]
Hey,
I would like to work on this issue.
Thanks.

**Comment by ziyuan-linn** [comment]
Thank you for the info!
