### ISSUE TITLE
Lines Drawing Half-Pixel Off

### ISSUE THREAD

**Issue by crhallberg** [processing/p5.js#660]
1 pixel wide lines (maybe all lines) are drawing .5 pixels up and left of their proper position.

Maybe fixed by WebGL.

```JS
function setup() {
  createCanvas(800, 400);
}

function draw() {
  background(0);

  noFill();
  stroke(255);

  // Centering squares
  rect(198, 198, 4, 4); // border crisp
  rect(598, 198, 4, 4); // border crisp

  line(100, 200, 300, 200);
  line(200, 100, 200, 300); // lines blurred
  rect(150, 150, 100, 100); // border crisp

  push();
  translate(400.5, .5);
  line(100, 200, 300, 200);
  line(200, 100, 200, 300); // lines crisp
  rect(150, 150, 100, 100); // border blurred
  pop();
}
```

**Comment by crhallberg** [comment]
Found the solution in `rect()`. If the stroke weight is odd, offset 0.5 pixels.

Commit: https://github.com/processing/p5.js/commit/6201e4feca29d496a6b165ca2fa3bc182e4606e9

**Comment by lmccart** [comment]
ah yes. i'm not convinced this is totally necessary though. i think the idea was to make lines crisper but does it just add more confusion?
