### ISSUE TITLE
Adding new Feature of mouse interactions

### ISSUE THREAD

**Issue by nandini584** [processing/p5.js#6605]
### Increasing Access

Usually we see that mouse and pointer interactions are a bit difficult to implement in code, how about we provide access to some of the most common mouse interactions? We can also allow users to create their own custom interactions.

I would like to know your insights on this. We can make things a lot simpler for frontend developers and can aim to simplify what gsap does.

### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### Feature request details

Simple code or template for 1 line use "methods" for cursor interaction 
Custom cursor interactions with already made components in our library 
User can use our custom cursor or make their own

**Comment by nandini584** [comment]
I would like to work on this issue....

**Comment by ranaaditya** [comment]
Hi @nandini584 , thanks for raising this feature request, do you have any idea in mind how you are going to do this in code? 

i am interested about creating the the custom interactions, how you are going to do that ? 

@lmccart @outofambit 

Thanks !

**Comment by outofambit** [comment]
tagging @limzykenneth @TanviKumar @jeanetteandrews (a few of the stewards for this area) for their thoughts on this

**Comment by limzykenneth** [comment]
Hi @nandini584, I'm not sure what you are referring to with mouse and pointer interactions. Can you perhaps come up with an example or more concrete explanation? Thanks.

**Comment by nandini584** [comment]
@limzykenneth 
I am sharing the link of some examples you can look at 

[https://qodeinteractive.com/magazine/examples-of-imaginative-mouse-cursor-design/#pest-stop-boys](Link)

**Comment by limzykenneth** [comment]
I'm afraid I still don't understand, the blob following the mouse cursor can be achieved with drawing the blob based on the `mouseX` and `mouseY` values, the hover effect can be achieved similarly in canvas or if interacting with DOM elements with `mouseOver()`.

**Comment by nandini584** [comment]
oh okay, I understand now. I am sorry It must be the issue from my part in understanding the functionality of this. Thank you for your time.
