### ISSUE TITLE
The language and Hello {name} does not close ,when clicked randomly on viewport 

### ISSUE THREAD

**Issue by ujjwaleee26** [processing/p5.js#6616]
### Most appropriate sub-area of p5.js?

- [X] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [X] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### Web browser and version

Safari

### Operating System

MacOSX

### Steps:
1.
2.
3.

### Snippet:

```js

// Paste your code here :)

```

**Comment by ujjwaleee26** [comment]
@all-contributors please add @ujjwaleee26  for Web editor

**Comment by ujjwaleee26** [comment]
@all-contributors please add @ujjwaleee26  for code

**Comment by limzykenneth** [comment]
Hi @ujjwaleee26, I'm not exactly sure what you mean with this issue, please fill out the issue template so that we can better understand what the problem you are having is. Thanks.
