### ISSUE TITLE
Due to #6216, If ortho() is used without arguments, drawing may fail in some cases

### ISSUE THREAD

**Issue by inaridarkfox4231** [processing/p5.js#6621]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

1.9.0

### Web browser and version

Chrome

### Operating System

Windows11

### Steps:
1. Run ortho() in webgl mode on a 400x400 canvas.
2. execute box(100).
3. box is disappear.

### Snippet:

```js
function setup() {
  createCanvas(400, 400, WEBGL);
  ortho();
}

function draw() {
  background(220);
  box(100);
}
```

## 1.8.0
![おーそ2](https://github.com/processing/p5.js/assets/39549290/316bb60c-4fd6-4a32-88cd-4523508c449e)

## 1.9.0
![オーソ1](https://github.com/processing/p5.js/assets/39549290/75efa9da-ed0c-4785-9c29-c630f4d5e00b)

The cause is that the default settings of the camera have been changed due to #6216.
The inconsistency occurs because the default settings for ortho() are still the same as before.
I would like to wait for the solution from someone who is interested.

**Comment by diyaayay** [comment]
Hey, I would like to work on this issue.

**Comment by inaridarkfox4231** [comment]
I think it will be easier for the reviewer to help if you can provide a concrete plan on how to fix it.

**Comment by diyaayay** [comment]
@inaridarkfox4231 I will post it as soon as possible.

**Comment by inaridarkfox4231** [comment]
OK. But I'm not a reviewer...sorry.

**Comment by inaridarkfox4231** [comment]
I think I didn't explain it enough, so I'll add more.

The cause is that the far value of ortho() depends on the canvas size. I think you should correct this part.
[ortho](https://github.com/processing/p5.js/blob/main/src/webgl/p5.Camera.js#L898)
The default value of eyeZ is determined here. It 's 800.
[_computeCameraDefaultSettings](https://github.com/processing/p5.js/blob/main/src/webgl/p5.Camera.js#L1959)
This value is too large, causing the camera to be too far away.

Changing the default value of ortho() will affect unit tests.
[ortho() with no parameters specified (sets default)](https://github.com/processing/p5.js/blob/0569c021b3946088f7db3b78b814c162d8133c80/test/unit/webgl/p5.Camera.js#L653C10-L653C10)
So we'll have to fix this as well.

Or there are other solutions. Eliminate this unit test and clearly state in the reference, "Do not use ortho() without arguments." This will prevent users from using ortho() with no arguments, which will prevent the bug from occurring. It would also be a good idea to provide a friendly error. Of course, you need to clearly state in the reference that eyeZ is 800. Otherwise, the user will not be able to decide how to set far value.

It is up to the contributor to decide how to resolve it. My work is just to present ideas.

**Comment by diyaayay** [comment]
@inaridarkfox4231 I tried changing the default far value and increasing it by a factor of 2.
`far = Math.max(this._renderer.width, this._renderer.height)*2;`

And these are the results:
Before:
![Screenshot 2023-12-14 113843](https://github.com/processing/p5.js/assets/110971977/c671c581-4707-49e8-bc83-a127839c78de)


After `far = Math.max(this._renderer.width, this._renderer.height)*2;`   :


![Screenshot 2023-12-14 114026](https://github.com/processing/p5.js/assets/110971977/b1942d6c-ac36-4afa-a0bf-57a7f12cac66)



Do you think this could be a possible solution to kkep using ortho without arguments?

**Comment by inaridarkfox4231** [comment]
I think it's a good idea. I am not authorized to review. Please wait for a reviewer to find it.

**Comment by inaridarkfox4231** [comment]
I think that method will probably fail when the canvas size is small (100x100, for example), so I think another method is better.

**Comment by inaridarkfox4231** [comment]
Currently, the eyeZ value is fixed at 800 when no camera is specified. Therefore, you could consider specifying far value much larger than 800, such as 1600 or 8000.

Of course, if we specify it with the camera function, we can just set the far value accordingly, so there is no problem. The problem here is what happens when we don't use it. In that case, eyeZ will be 800, and drawing may fail in some cases. The purpose is to avoid that.

**Comment by diyaayay** [comment]
I tried adjusting for more values, and it turns out `far = Math.max(this._renderer.width, this._renderer.height)*8;` works for as small as (100*100), since the eyeZ value is 800. For the safer side, instead of *8, we can consider an even larger factor as it would cater to the canvas smaller than (100*100), which I'm not quite clear about if we can settle onto a certain low limit of canvas size. For the safer side, I tried `far = Math.max(this._renderer.width, this._renderer.height)*10;` which works for canvas sizes as small as (80*80). Do you think settling onto a factor value, that shows the drawing for smaller canvas up to a certain limit can be the solution?

**Comment by diyaayay** [comment]
I will also look into changing the eyeZ value as suggested by  @inaridarkfox4231.

**Comment by inaridarkfox4231** [comment]
I think any value is fine. I'll leave the rest to the reviewer.

**Comment by inaridarkfox4231** [comment]
The easiest solution I can think of is to add 800 to the current value.
```js
    if (far === undefined)
      far = Math.max(this._renderer.width, this._renderer.height) + 800;
```

**Comment by diyaayay** [comment]
```
function setup() {
  createCanvas(100, 100, WEBGL);
  ortho();
}

function draw() {
  background(220);
  box(50);
}
```
![snipfinal1](https://github.com/processing/p5.js/assets/110971977/f46f5200-8c22-47b9-9c42-bb08695c992f)


```
function setup() {
  createCanvas(400, 400, WEBGL);
  ortho();
}

function draw() {
  background(220);
  box(50);
}
```

![snipdinal2](https://github.com/processing/p5.js/assets/110971977/f0b288f1-5e85-4866-8137-7ddef0e7a9e9)


Changes Made:
`if (far === undefined)
      far = Math.max(this._renderer.width, this._renderer.height) + 800;`
      
 @davepagurek What do you think?

**Comment by davepagurek** [comment]
I think shifting the far plane by 800 works, thanks for the suggestion @inaridarkfox4231 and for testing it out @diyaayay!
