### ISSUE TITLE
Replace console.error with friendly error system

### ISSUE THREAD

**Issue by shashank-iitbhu** [processing/p5.js#6630]
### Increasing Access

Many functions inside `src/webgl` and `lib/addons` currently uses `console.error` to report errors. It would be more user-friendly and consistent with the p5.js environment to replace these calls with the friendly error system (FES).

### Most appropriate sub-area of p5.js?

- [X] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [X] Friendly Errors
- [ ] Other (specify if possible)

### Feature enhancement details

For example, take `parseASCIISTL` function in `webgl/loading.js`,
I have triggered an error condition and the results,
<br></br>
with console.error:
<img width="726" alt="Screenshot 2023-12-13 at 10 41 06 PM" src="https://github.com/processing/p5.js/assets/134289475/f310ad84-a65e-48d1-abdd-72c18cc874cb">
<br></br>
with FES:
<img width="720" alt="Screenshot 2023-12-13 at 10 42 01 PM" src="https://github.com/processing/p5.js/assets/134289475/9231a973-832a-424a-a522-f4e230b2829a">
It would be more user-friendly and consistent with the p5.js environment to replace these calls with the friendly error system (FES).

**Comment by shashank-iitbhu** [comment]
@davepagurek if you can review this. I am willing to work on this issue. Please assign.

**Comment by ranjanmangla1** [comment]
can I get to work on this issue? this will be my first contribution in processing community

**Comment by omsharma29** [comment]
is this issue solved or it is still there?


> can I get to work on this issue? this will be my first contribution in processing community

**Comment by omsharma29** [comment]
where to find this issue I forked the code base in local system??

**Comment by samrudh3125** [comment]
Do we also have to change the throw new error keywords or only the console.error

**Comment by samrudh3125** [comment]
@shashank-iitbhu please accept the pull request

**Comment by vaishnavi192** [comment]
@davepagurek Hey I would like to work on this issue. Can you assign me?

**Comment by perminder-17** [comment]
Thanks for opening this issue. However, that's not exactly how it works. For example, when I use `console.err(e)`, it means I’m unsure of what’s happening or what kind of error might be occurring, and we get a line from the p5.js library. Friendly errors, on the other hand, are designed to be more helpful to the user. They point out the specific line in your code where the issue happened and even suggest possible solutions. These errors are not only formatted clearly but also provide guidance. You can see an example below where both an error message and a friendly error message are shown.

![image](https://github.com/user-attachments/assets/bcf7b124-60e8-424b-8dd7-23676303c3f1)


And also, when we are using `console.error(maybe your error message)` in your sketch, it probably mean we need to show it in an error format.

So, I need to close this issue.
