### ISSUE TITLE
arrayCopy needs better error checking

### ISSUE THREAD

**Issue by kjhollen** [processing/p5.js#666]
arrayCopy produces unexpected results if the arguments provided don't match what's expected.

I accidentally encountered this while running an example shared in Issue #478 (while fixing spin-off issue #632). It eventually produces an error that the call stack is too deep.

<code><pre>var good = [1,2,3,4];
var bad;
function setup() {
  bad = loadImage("cat.jpg");
}

function draw() {
  bad.loadPixels();
  print(good);
  print(good.slice(0));
  print(bad.pixels);
  print(bad.pixels.slice(0));
  arrayCopy(bad.pixels, good); // call stack too deep
}</pre></code>

**Comment by workergnome** [comment]
@mxchelle, @lmccart: I apologize if I'm missing something, but the pull request for this was closed without merging, and I don't see a comment about it.  I seem to recall that there was a second pull request, but I couldn't find it.  

Is this still an outstanding issue?

Thank you all!

**Comment by lmccart** [comment]
as I recall, we decided to change this so the method used friendly errors rather than throwing errors that would take down the sketch. we closed the pull request in the meantime until this was updated. does this seem reasonable? i'm not sure what our general philosophy around using friendly errors vs throwing errors is exactly.

**Comment by workergnome** [comment]
Aaah, gotcha.  I vaguely remembered a conversation about it, but I couldn't find it.  It might have happened (gasp) in person.

That sounds reasonable.   I don't know what our philosophy is, but we should think about it...

@mxchelle, are you still interested in completing this?

**Comment by sakshamsaxena** [comment]
@almchung Ya think this is addressed already? Or needs some attention ? :sweat_smile:

**Comment by almchung** [comment]
@sakshamsaxena thank for mentioning this! I will take a look at this.

**Comment by lmccart** [comment]
this should be covered with validateParameters()
