### ISSUE TITLE
Enhancing Code Accessibility and Copy Experience: Proposed UI Styling for Improved User Interaction

### ISSUE THREAD

**Issue by gauravsingh94** [processing/p5.js#6663]
### Increasing Access

**Existing Feature**

In this website the way we are showing the code is hard to understand for the user code here and when he want to copy this code for the website he have select the entire code in order to copy the code which user experience.

![Pasted image 1](https://github.com/processing/p5.js/assets/99260988/4081c48c-e752-4ff3-8726-d97ee99e7823)

### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [X] Other (specify if possible)

### Feature enhancement details

For increaseing the user experience i want to add the styling like the
it is the demo ui i have created i would like to implement like this such that user can see the code in this way when  he  click on the copy button he can copy the entire code into his clipboard.

**Demo Ui**

![Pasted image](https://github.com/processing/p5.js/assets/99260988/d2a57e08-3906-4281-8c58-70ac3fba136c)

It is demo , i will make the design which matches with the website.

If you all like my suggesting please assign this issue to me so that i would start working on it.
Please provide you suggestion and feedback for this one.

**Comment by lindapaiste** [comment]
I'm confused, doesn't it currently have the edit/reset/copy buttons?
![image](https://github.com/processing/p5.js/assets/28965286/98e7ec0a-aca6-417f-8650-264b44097f54)

**Comment by gauravsingh94** [comment]
When running the website locally, I do not see those highlights; however, when using p5js.org, they are visible. I have already begun working on resolving this issue 😢.

> I'm confused, doesn't it currently have the edit/reset/copy buttons? ![image](https://private-user-images.githubusercontent.com/28965286/292925479-98e7ec0a-aca6-417f-8650-264b44097f54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2MzU5NDgsIm5iZiI6MTcwMzYzNTY0OCwicGF0aCI6Ii8yODk2NTI4Ni8yOTI5MjU0NzktOThlN2VjMGEtYWNhNi00MTdmLTg2NTAtMjY0YjQ0MDk3ZjU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDAwMDcyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0ZWRkNDBiNDM5YTljNjEyMjA3YTJiZmE4MWFiMGM2ZWU5ZTdiNzJlNDc4MGQ4NjA3MjZhZTNkMDk3MmQ4NDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.32PSoyDJTYDpf6fjgEoOXt_khB7gYKdMoXus2Pg3xsU)
