### ISSUE TITLE
Callback in functions freezing preload

### ISSUE THREAD

**Issue by therewasaguy** [processing/p5.js#668]
Preload freezes when a callback is passed in to one of its functions. This includes JSONP.

Would moving to promises help? Preload functions could do callbacks with a chain of ``then()``s?

**Comment by therewasaguy** [comment]
Another test case from @xyfeng 

```
function setup() {
loadFont('./assets/fonts/AvenirNextLTPro-Demi.otf', drawText);
}

function drawText(font) {
fill('#ED225D');
textFont(font, 36);
text('p5*js', 10, 50);
}
```

**Comment by lmccart** [comment]
it would help, i just wonder if it's worth wrapping promises into p5.js just to support this one situation that is not actually an intended use. if you're using callbacks there's no need to use preload at all. would it be better just to make the documentation clearer? use preload() *or* use a callback?

**Comment by brysonian** [comment]
I agree, are there any reasonable use cases for using callbacks in preload?

**Comment by workergnome** [comment]
I think the documentation change would help—but you might also have to do a check and throw an error if you do pass in a callback with preload—otherwise it just hangs, and not in an obvious way.

**Comment by lmccart** [comment]
any suggestions on how this check might be done? the problem I'm running into is that we don't necessarily know the signature for various methods in preload. I supposed we could do some basic check for the ones we do know about (like checking for a function passed as a parameter), but libraries can register their own preload methods, and these might vary widely.

**Comment by lmccart** [comment]
fixed with https://github.com/processing/p5.js/pull/956
