### ISSUE TITLE
Broken link to fes_reference_dev_notes.md in the documentation

### ISSUE THREAD

**Issue by PracDuckling** [processing/p5.js#6691]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [X] Friendly Errors
- [ ] Other (specify if possible)

### Steps to reproduce this

There is a broken link in [this file](https://github.com/processing/p5.js/blob/fe33439ff3d46d59ca97032ec73de7a308508190/contributor_docs/friendly_error_system.md#understanding-how-fes-works). The link should open [this file](https://github.com/processing/p5.js/tree/main/src/core/friendly_errors#fes-reference-and-notes-from-developers) but we get a 404 page instead.

The link `FES Reference + Dev Notes` is broken
![image](https://github.com/processing/p5.js/assets/68885144/21bccb4a-6cf8-4c5b-aa0e-ed1c4bd8b368)

404 page
![image](https://github.com/processing/p5.js/assets/68885144/2e1f6978-8f89-4d66-aa27-dbdbd20edc65)

Correct file
<img width="808" alt="image" src="https://github.com/processing/p5.js/assets/68885144/6555b063-e128-4c55-85ad-e2661f530d13">

**Comment by pankaj-2503** [comment]
attached the pr link it  at  https://github.com/processing/p5.js/pull/6704

**Comment by AmreshSrivastava** [comment]
![Screenshot (2)](https://github.com/processing/p5.js/assets/129481499/f819d66c-ef50-45b2-8882-37bb0f93f101)
Working!

**Comment by AmreshSrivastava** [comment]
can u please add me in the list of contributor.
