### ISSUE TITLE
Incorrect example in the reference page for acos()

### ISSUE THREAD

**Issue by sudhanshuv1** [processing/p5.js#6696]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [X] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

1.9.0

### Web browser and version

Google Chrome 120.0.6099.200 (Official Build) (64-bit) 

### Operating System

Windows 10 Pro Version 22H2

### Steps:
1. Visit the reference page for `acos()` - https://p5js.org/reference/#/p5/acos
2. It has 2 examples - both with the same output, although it is clear from the `describe` function of the second example that it is supposed to have a different output:

![acos](https://github.com/processing/p5.js/assets/148856416/a673993f-b762-4f67-9f4e-0e903545c9eb)

I want to work on this issue!

**Comment by sumanbalayar08** [comment]
I wanna solve this issue. Can you help me assign this issue?
