### ISSUE TITLE
merge outstanding p5jsconf changes before 3pm on Friday

### ISSUE THREAD

**Issue by kjhollen** [processing/p5.js#670]
On Friday the core/devops team will reorganize some of the core libraries. We'll be moving a lot of code (including documentation) around, so it's best if we can get everyone to merge what they've been working on this week before that work starts.

See [preparing a pull request](https://github.com/processing/p5.js/wiki/Preparing-a-pull-request) for more details.

**Comment by workergnome** [comment]
We did it!  Thanks, everyone.
