### ISSUE TITLE
 Error: Local Npm module 'grunt-contrib-compress' not found

### ISSUE THREAD

**Issue by Shyam-Raghuwanshi** [processing/p5.js#6706]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [X] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

1.9.0

### Web browser and version

google

### Operating System

WSL-UBUNTU

### Steps:
1. run `npm run build`
you can see the issue

images

![Screenshot 2024-01-07 151929](https://github.com/processing/p5.js/assets/94217498/bf65a922-9d93-47c3-85ec-f9aa28db4b76)

**Comment by TheArchitect19** [comment]
First run npm run docs
then run npm run docs:dev
then run npm run test
then build it
then run npm run dev
