### ISSUE TITLE
Changing Snake Movement Controls and Canvas Focus Behavior

### ISSUE THREAD

**Issue by 0Kaju12** [processing/p5.js#6715]
### Actual Behavior

**Description**

In the example

I encountered an issue in the Snake game implementation where the movement controls are set to 'i', 'j', 'k', 'l', and the canvas doesn't receive focus automatically when the game starts. I propose to enhance the game by:

**Changing Movement Controls:**
Modify the control scheme to use 'w', 'a', 's', 'd' along with arrow keys for the snake's movement to improve user experience.

**Auto-Focus Canvas on Game Start:**
Ensure the canvas receives focus automatically when the game starts, allowing immediate keyboard interaction without requiring a click on the canvas.

This enhancement aims to provide a more intuitive control scheme and ensure a seamless gaming experience.

![Screenshot (1203)](https://github.com/processing/p5.js-web-editor/assets/97822692/5ef6a530-d5fb-4ed7-8490-b1c3484e3f4e)

Uploading p5.js Web Editor _ Interaction_ snake - Google Chrome 2024-01-06 01-20-14.mp4…

### Expected Behavior

The game should support 'w', 'a', 's', 'd' and arrow keys for movement, and the canvas should automatically receive focus when the game starts, enabling immediate keyboard interaction without the need for clicking on the canvas.

### Steps to reproduce

[]https://editor.p5js.org/p5/sketches/Interaction:_snake
- Run the Snake game.
- Observe that the controls are currently set to 'i', 'j', 'k', 'l'.
- Note that the canvas does not automatically receive focus on game start.

**Comment by limzykenneth** [comment]
Actually in this case I'm wondering wouldn't straight up arrow keys instead of WASD or IJKL be more intuitive for this keyboard only game?

**Comment by JainilModi25** [comment]
Yes, the arrow keys could be a better choice too. Although now I am wondering what if the creators of the game actually set the controls to i,j,k,l because of a particular reason? Might be that it was affecting/breaking some other things? Would love to hear from the creator/maintainers!

**Comment by limzykenneth** [comment]
@calebfoss I believe you have been looking into the examples recently, if you have the capacity would you mind having a look at this one and advice on whether we should go with WASD or arrow keys, or other resolutions?

**Comment by calebfoss** [comment]
@limzykenneth I revised this example as part of the larger examples revision project:  https://github.com/processing/p5.js-example/blob/main/examples/10_Games/02_Snake.js
Among other changes, the example now uses arrow keys and includes a start screen to direct users to click the canvas for focus. Since this version will be included in the new website, I think this issue can be closed.

**Comment by limzykenneth** [comment]
Thanks @calebfoss, I'll close this but also deep thanks for everyone who looked into this.
