### ISSUE TITLE
Error when using saveGif() in instance mode and WEBGL mode

### ISSUE THREAD

**Issue by ChimiSeanGa** [processing/p5.js#6724]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [X] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

1.9.0

### Web browser and version

Safari 17.1

### Operating System

macOS Sonoma 14.1.1

### Steps:
1. Run a sketch in instance mode and in WEBGL mode
2. Add a `saveGif()` command anywhere
3. Upon calling `saveGif()`, an error will be thrown saying `ReferenceError: Can't find variable: height`

### Snippet:

```js

let sketch = function(p) {
  p.setup = function() {
    p.createCanvas(500, 500, p.WEBGL);
  };

  p.draw = function() {
  };
  
  p.keyPressed = function() {
    if (p.key === 's') {
      p.saveGif('test', 5);
    }
  }
};

let myp5 = new p5(sketch);

```

You can run this in the web editor as well. If you remove the `p.WEBGL` parameter, `saveGif()` works just fine.

**Comment by mohitbalwani** [comment]
Thanks for reporting the issue @ChimiSeanGa! I spent some time on this issue and found that we were not passing the width and height to the function. I made those changes and created PR #6726 which should resolve this issue.
