### ISSUE TITLE
Feature : Scroll to Top Button for Improved User Experience

### ISSUE THREAD

**Issue by antriksh-9** [processing/p5.js#6736]
### Increasing Access

Unsure

### Most appropriate sub-area of p5.js?

- [x] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [x] DOM
- [x] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### Feature request details

On processing [website](https://p5js.org/) a back-to-top button isn't present which is a common website feature.

I propose adding a "Scroll to Top" button that becomes visible as the user scrolls down the website page.
Tapping this button would smoothly scroll the user back to the top, providing a convenient and efficient way to navigate lengthy content.

I want to work on this issue.

**Comment by antriksh-9** [comment]
Hey @limzykenneth What type of issue we are currently targeting to work on?

**Comment by limzykenneth** [comment]
Have a look at the current open issues in the p5.js repo. Thanks.
