### ISSUE TITLE
touchEnded triggers twice among other issues with touchEnded/mouseReleased on mobile

### ISSUE THREAD

**Issue by RandomGamingDev** [processing/p5.js#6737]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [X] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

1.9.0

### Web browser and version

120.0.6099.210

### Operating System

Android

### Steps:
1. Have touchEnded() or mouseReleased() on mobile

Here's a sketch demonstrating it
https://editor.p5js.org/PotatoBoy/sketches/MTUuPrS8T

On touchscreen
- mouseReleased and touchEnded both trigger if they're both present (same for mouseReleased)
- If either is without the other it triggers twice

**Comment by davepagurek** [comment]
Btw do your PRs also address this https://github.com/processing/p5.js/issues/6030 or do you think there are other event handlers that also need a fix?

**Comment by RandomGamingDev** [comment]
> Btw do your PRs also address this https://github.com/processing/p5.js/issues/6030 or do you think there are other event handlers that also need a fix?

Yeah it also addresses that. I didn't notice that there was another issue with the same problem lol <br/>
Although, considering the fact that this issue happened with 2 pairs of event handlers I think we should check how the other event handlers fare on touch screen just in case. It's quite possible that a lot of them have unforseen bugs just like this one.
