### ISSUE TITLE
The foundation section in the reference section should have var keyword too though it is not used by developers today but still

### ISSUE THREAD

**Issue by MohammadHarish52** [processing/p5.js#6742]
### Increasing Access

I don't know if it will increase the access or not but , we have to at least respect ECMAScript standards.

### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [X] Other (specify if possible)

### Feature enhancement details

Should Add the var keyword in the Foundation list too in the reference section

**Comment by limzykenneth** [comment]
Hi @MohammadHarish52, the Foundation seciton of the reference is not meant to be comprehensive since there is so much more of EcmaScript that is not included there, and if `var` is not commonly used nor really recommended, there is a good case for not including it here I think.

**Comment by nickmcintyre** [comment]
Thanks for bringing this up @MohammadHarish52! I agree with @limzykenneth. Most style guides, including our own, advise against using `var`.

More generally, the Foundation section doesn't aim to recreate resources such as MDN or the ECMAScript standard. It's meant to cover the language features commonly used by beginners. We're in the process of revising this section of the docs to match our code style guide for documentation.

**Comment by MohammadHarish52** [comment]
> Hi @MohammadHarish52, the Foundation section of the reference is not meant to be comprehensive since there is so much more of ECMAScript that is not included there, and if `var` is not commonly used nor really recommended, there is a good case for not including it here I think.

Well i Think you have it very well answered now, thanks for the explanation.

**Comment by MohammadHarish52** [comment]
> Thanks for bringing this up @MohammadHarish52! I agree with @limzykenneth. Most style guides, including our own, advise against using `var`.
> 
> More generally, the Foundation section doesn't aim to recreate resources such as MDN or the ECMAScript standard. It's meant to cover the language features commonly used by beginners. We're in the process of revising this section of the docs to match our code style guide for documentation.

Yes my question is very well answered now
