### ISSUE TITLE
p5.Vector.d.ts: Can **class Vector** be changed to **interface Vector** declaration?

### ISSUE THREAD

**Issue by yanglebupt** [processing/p5.js#6768]
### Topic

In order to expand the `static properties` on the class Vector, it seems necessary to change the `class declaration` to `interface declaration` in `p5.Vector.d.ts` file.
<img width="875" alt="屏幕截图 2024-01-25 215254" src="https://github.com/processing/p5.js/assets/139488963/4ef10918-cc01-4604-9672-244872adf13e">

**Comment by lindapaiste** [comment]
It’s definitely a `class` and should stay a `class`. 

If you explain what you are trying to achieve then I might be able to help you.  `static` properties would go on the `VectorConstructor` type, whereas the `Vector` type describes the type of each instance of the class.

**Comment by limzykenneth** [comment]
Types for p5.js is maintained externally at: https://github.com/p5-types/p5.ts. This issue should probably be filed there. I'll close this for now.
