### ISSUE TITLE
 Add Downloadable .obj File Support for p5.Geometry shapes

### ISSUE THREAD

**Issue by diyaayay** [processing/p5.js#6769]
### Increasing access

Feature Request:
The current proposal aims to enhance the reusability of 3D models created using p5.Geometry by adding support for downloadable .obj files. This feature would empower users to export their 3D creations in a format compatible with various 3D software, such as Blender, and facilitate cross-platform usage. As .obj files are pretty straightforward, this could be achievable by using the current array properties of p5.Geometry.

### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Build process
- [ ] Unit testing
- [ ] Internationalization
- [ ] Friendly errors
- [ ] Other (specify if possible)

### Feature request details

There is a way of collecting shapes in p5.Geometry with buildGeometry.
By iterating over the vertices and faces of the geometry and then converting them to string format supported by .obj files, the functionality of downloadable obj files can be achieved.

**Comment by diyaayay** [comment]
I'm working on this issue.

**Comment by Prateek-Fst** [comment]
Implement functionality to export p5.Geometry as downloadable .obj files.
// This will enhance reusability by allowing users to use their 3D creations in external 3D software.
// I'm interested in working on this feature. Any guidance or collaboration is welcome!
