### ISSUE TITLE
Add guideline about chaining to style guide

### ISSUE THREAD

**Issue by meezwhite** [processing/p5.js#6797]
### Increasing access

Improve style guide to prevent future inconsistencies in docs.

### Most appropriate sub-area of p5.js?

- Contributor Docs ([style guide](https://github.com/processing/p5.js/blob/main/contributor_docs/documentation_style_guide.md))

### Feature enhancement details

In reference to https://github.com/processing/p5.js/issues/6400#issuecomment-1709419148, as proposed by @nickmcintyre, to add guideline about chaining functions to styleguide.

```js
// Nope.
fill(0)
  .strokeWeight(0)
  .textSize(10);

// Nope.
fill(0).strokeWeight(0).textSize(10);

// Yep.
fill(0);
strokeWeight(0);
textSize(10);
```

**Comment by Anayverma** [comment]
Hey @meezwhite I would like to work on this issue. Please assign it to me.

**Comment by limzykenneth** [comment]
Yes I think that is fine to add, @meezwhite you can go ahead with a PR if you like.
