### ISSUE TITLE
cursor() - the image not displayed as the cursor

### ISSUE THREAD

**Issue by shawnwz** [processing/p5.js#6804]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [X] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build process
- [ ] Unit testing
- [ ] Internationalization
- [ ] Friendly errors
- [X] Other (specify if possible)

### p5.js version

1.9.0

### Web browser and version

Google Chrome 121.0.6167.139

### Operating system

Mac

### Steps to reproduce this

reference to https://p5js.org/reference/#/p5/cursor

`If the path to an image is passed, as in cursor('assets/target.png'), then the image will be used as the cursor`

acctually the image is not used as the cursor 

I tested 

cursor(CROSS) is working
cursor('https://avatars0.githubusercontent.com/u/1617169?s=16')  is working

BUT  cursor("assets/erasers/64-eraser.png") is NOT working

**Comment by Qianqianye** [comment]
Hi @shawnwz, to help us better understand this, could you provide a [p5.js web editor](https://editor.p5js.org/) link that includes a code snippet illustrating the issue? Thanks!

**Comment by haroon10725** [comment]
Hi @Qianqianye this is the code snippet illustrating the issue. [https://editor.p5js.org/haroongondal347/sketches/7JyYWZwMY](p5.js web editor)

**Comment by haroon10725** [comment]
Hey @davepagurek Can I work on this?

**Comment by davepagurek** [comment]
Thanks @haroon10725, I'll assign it to you!
