### ISSUE TITLE
[p5.js 2.0 RFC Proposal]: Publish original proposals through new proposal form

### ISSUE THREAD

**Issue by GregStanton** [processing/p5.js#6813]
### Increasing access

This change would enable the community to provide feedback on the original RFC proposals. It would also give them the opportunity to express their interest in helping with implementations.

### Which types of changes would be made?

- [ ] Breaking change (Add-on libraries or sketches will work differently even if their code stays the same.)
- [X] Systemic change (Many features or contributor workflows will be affected.)
- [ ] Overdue change (Modifications will be made that have been desirable for a long time.)
- [ ] Unsure (The community can help to determine the type of change.)

### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build process
- [ ] Unit testing
- [ ] Internationalization
- [ ] Friendly errors
- [X] Other (specify if possible)

### What's the problem?

In Issue #6678, an emphasis has been placed on the importance of community feedback; however, in nine of the ten original proposal categories, there is no viable way for the community to provide this feedback. Those nine categories are listed below:

* [Build and test system](https://github.com/processing/p5.js/blob/dev-2.0/rfc_p5js_2.md#build-and-test-system)
* [Refactors](https://github.com/processing/p5.js/blob/dev-2.0/rfc_p5js_2.md#refactors)
* [Modular](https://github.com/processing/p5.js/blob/dev-2.0/rfc_p5js_2.md#modular)
* [Libraries](https://github.com/processing/p5.js/blob/dev-2.0/rfc_p5js_2.md#libraries)
* [Renderers](https://github.com/processing/p5.js/blob/dev-2.0/rfc_p5js_2.md#renderers)
* [Algorithm Changes](https://github.com/processing/p5.js/blob/dev-2.0/rfc_p5js_2.md#algorithm-changes)
* [Reference](https://github.com/processing/p5.js/blob/dev-2.0/rfc_p5js_2.md#reference)
* [Typography](https://github.com/processing/p5.js/blob/dev-2.0/rfc_p5js_2.md#typography)
* [Misc](https://github.com/processing/p5.js/blob/dev-2.0/rfc_p5js_2.md#misc)

Specifically, it was observed early on that [the discussion in that issue is too hard to navigate](https://github.com/processing/p5.js/issues/6678#issuecomment-1880201877). Since then, the discussion has only become harder to navigate.

### What's the solution?

Since the RFC was originally released, we've developed [a new proposal form](https://github.com/processing/p5.js/issues/new?assignees=&labels=p5.js+2.0&projects=&template=1-p5.js-2.0-RFC-proposal.yml&title=%5Bp5.js+2.0+RFC+Proposal%5D%3A+) dedicated specifically to gathering feedback on proposals for p5.js 2.0. We've already begun inviting more of the community to participate, including through [a banner announcement on the Processing Discourse](https://discourse.processing.org/). _All that's left is to publish the original RFC proposals with the new form._

In the one case (out of ten) where an original proposal was submitted through the form, as [Issue #6767](https://github.com/processing/p5.js/issues/6767), the community immediately helped to flesh it out and rapidly iterated on [the original idea](https://github.com/processing/p5.js/blob/dev-2.0/rfc_p5js_2.md#async).

### Pros (updated based on community comments)

1. Increases accessibility of the p5.js 2.0 effort.
2. Accelerates progress on a range of important proposals. 
3. Helps the community to determine which proposals to accept.
4. Provides an easy way to record the decision-making process (the final RFC can link to the discussion for each proposal).
5. Aids project management (accepted proposals can be organized via the [p5.js 2.0 GitHub project](https://github.com/orgs/processing/projects/21/views/2)).
6. Facilitates upgrade guidance. [^1]
7. Makes the final RFC easier to read by providing a common format for proposals. [^2]

[^1]: This idea is based on [a comment](https://github.com/processing/p5.js/issues/6678#issuecomment-1931121505) from @kjhollen. For example, proposal authors might be asked to write "user-impact summaries," which would describe how the changes will directly affect users. These summaries could then be used to develop user-friendly guidance on how to manage the upgrade (e.g. as blog posts or videos, similar to [when the p5.js Web Editor was rolled out](https://medium.com/processing-foundation/hello-p5-js-web-editor-b90b902b74cf)).
[^2]: For each proposal submitted through the issue form, the access statement, problem statement, and solution statement can be copied into the RFC, along with a link to the issue for anyone who wants to see the full discussion. Proposals that are accepted for p5.js 2.0 can go into one category, and proposals that aren't accepted can go into another (it will be useful to have a record to indicate why proposals weren't accepted, and in some cases, proposals that aren't accepted for p5.js 2.0 may still be implemented after its release).

### Cons (updated based on community comments)

Publishing the original proposals through the proposal form requires time, since in some cases key information such as accessibility statements may be missing. However, adding that information is arguably necessary, so this doesn't seem like an additional cost.

### Proposal status

Under review

**Comment by GregStanton** [comment]
If anyone is interested in fleshing out one of the original proposals and submitting it through the new proposal form, please leave a comment! If anyone has questions about how this would work, please don't hesitate to ask here. **To get things started, I'm inviting stewards from areas that seem relevant, along with a few others who I think may be interested.**

### [Build and test system](https://github.com/processing/p5.js/blob/dev-2.0/rfc_p5js_2.md#build-and-test-system)
@limzykenneth

### [Refactors](https://github.com/processing/p5.js/blob/dev-2.0/rfc_p5js_2.md#refactors)
@mohitbalwani, @calebfoss, @cosmicbhejafry, @apoorva-a98, @tedkmburu, @Zarkv, @SkylerW99, @itsjoopark, @hannahvy, @nhasalajoshi

### [Modules](https://github.com/processing/p5.js/blob/dev-2.0/rfc_p5js_2.md#modular)
@jeffscottward, @davepagurek, @asukaminato0721, @lindapaiste 

### [Libraries](https://github.com/processing/p5.js/blob/dev-2.0/rfc_p5js_2.md#libraries)
Maybe contributors who've developed add-on libraries would be interested to help here? For now, I'll just list a few add-on library developers who seem to be active in the community.

@nickmcintyre, @quinton-ashley, @peilingjiang, @yining1023, @cvalenzuela, @bmoren, @davepagurek, @rev3rend, @two-ticks, @calebfoss, @stalgiag, @dhowe

### [Renderers](https://github.com/processing/p5.js/blob/dev-2.0/rfc_p5js_2.md#renderers)
@davepagurek, @ChihYungChang, @teragramgius, @tuminzee, @Zarkv, @robin-haxx, @Gaurav-1306

### [Algorithm Changes](https://github.com/processing/p5.js/blob/dev-2.0/rfc_p5js_2.md#algorithm-changes)
These are related to color and math.

@paulaxisabel, @SoundaryaKoutharapu, @mrbrack, @TJ723, @Zarkv, @SkylerW99, @ramya202000, @hannahvy, @robin-haxx, @hiddenenigma, @ericnlchen, @ChihYungChang, @bsubbaraman, @albertomancia, @JazerUCSB, @tedkmburu, @perminder-17, @Obi-Engine10, @jeanetteandrews

### [Reference](https://github.com/processing/p5.js/blob/dev-2.0/rfc_p5js_2.md#reference)
@asukaminato0721, @SoundaryaKoutharapu, @richardegil, @hannahvy, @bayomayo

### [Typography](https://github.com/processing/p5.js/blob/dev-2.0/rfc_p5js_2.md#typography)
@dhowe, @paulaxisabel, @SarveshLimaye, @SkylerW99, @BamaCharanChhandogi, @Obi-Engine10, @hannahvy, @singshris, @hiddenenigma

### [Misc](https://github.com/processing/p5.js/blob/dev-2.0/rfc_p5js_2.md#misc)
I know @nickmcintyre has provided feedback on some of this (e.g. `p5.Table`).

**Comment by dhowe** [comment]
@GregStanton how does one comment on the document above, or is the idea to move these into separate RFCs? And if so, where is the list of current RFCs under discussion ? 

It feels like there is a ton of good work in progress for v2.0, but coming back after a couple of weeks, I'm confused about which documents/issues are live/current and where to focus my attention...

**Comment by limzykenneth** [comment]
@dhowe The idea is to create RFC issues for them as they currently lives in the full RFC document I put together. It is a bit tricky to manage at this point and we don't have the capacity to organize very much at this point, I eventually will use the GitHub project tracker to keep track of all proposals and it will serve as the single source of truth for RFC statuses.

**Comment by GregStanton** [comment]
Hi @dhowe! Thanks so much for your questions. Answering them will help clarify the process for everyone, so I'll add a few points to the explanation from @limzykenneth. If anything is still unclear, please let me know!

### "Is the idea to move these into separate RFCs?"

Yes. The goal of this proposal (#6813) is to use [the "p5.js 2.0 RFC Proposal" form](https://github.com/processing/p5.js/issues/new?assignees=&labels=p5.js+2.0&projects=&template=1-p5.js-2.0-RFC-proposal.yml&title=%5Bp5.js+2.0+RFC+Proposal%5D%3A+) to create separate GitHub issues from each of the proposals in [the Markdown version of the RFC](https://github.com/processing/p5.js/blob/dev-2.0/rfc_p5js_2.md).

### "How does one comment on the document above..."
Moving the proposals form a Markdown document to separate GitHub issues, as indicated above, will make it possible for community members to add comments. It will also make all proposals accessible from one place.

### "And if so, where is the list of current RFCs under discussion?"

Recent proposals can be accessed by performing a search for [issues with the "p5.js 2.0" label](https://github.com/processing/p5.js/issues?q=is%3Aissue+label%3A%22p5.js+2.0%22+).[^1] The original set of proposals in the Markdown document will not appear in the search results until we convert them to GitHub issues.

### "I'm confused about which documents/issues are live/current..."

As I write this, the lists provided in issue #6678, in [the GitHub project for p5.js 2.0](https://github.com/orgs/processing/projects/21/views/2), and in [the Markdown version of the RFC](https://github.com/processing/p5.js/blob/dev-2.0/rfc_p5js_2.md) are all outdated. Using the "p5.js 2.0" issue label, as described above, is your best bet for an updated list of live issues.

### "And where to focus my attention..."

If you want to help with the current issue (#6813) by converting a Markdown proposal to a GitHub issue, that'd be a big help. More generally, you can check the body of issue #6678 for an overview of the effort toward p5.js 2.0; just remember that the list of issues provided there is outdated.

[^1]: You may notice that some issues that carry the green "p5.js 2.0" label do not include "[p5.js 2.0 RFC Proposal]" in the title; that's because some proposals were submitted before the "p5.js 2.0 RFC Proposal" form was created.

**Comment by limzykenneth** [comment]
This has been completed
