### ISSUE TITLE
Beginning of WebGL curves don't have a cap since v1.8

### ISSUE THREAD

**Issue by davepagurek** [processing/p5.js#6816]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Build process
- [ ] Unit testing
- [ ] Internationalization
- [ ] Friendly errors
- [ ] Other (specify if possible)

### p5.js version

1.8.0 through to 1.9.0

### Web browser and version

Firefox 117

### Operating system

MacOS 14.2.1

### Steps:
1. Draw a curve with `beginShape`, `vertex`, and `quadraticVertex` in WebGL mode
2. Note that only one end has a cap instead of both
3. Try setting the version back to 1.7 to see the expected value

Expected:
![image](https://github.com/processing/p5.js/assets/5315059/bfba9156-e71d-4aeb-bf9e-90c78b0581cf)

Actual result:
![image](https://github.com/processing/p5.js/assets/5315059/95431bae-8bf0-46e1-bfaa-6610842bf993)

### Snippet:

```js

function setup() {
  createCanvas(400, 400, WEBGL);
  background(255)
  noFill()
  stroke(0)
  strokeWeight(20)
  translate(-width/2, -height/2)
  beginShape()
  vertex(20, 20)
  quadraticVertex(
    280, 200,
    100, 380
  )
  endShape()
}

```

https://editor.p5js.org/davepagurek/sketches/ILIzcUpnt

**Comment by diyaayay** [comment]
May I have a go at this? Would like to work on it.

**Comment by diyaayay** [comment]
May I have a go at this? Would like to work on it.

**Comment by davepagurek** [comment]
Thanks! I'll assign this to you.
