### ISSUE TITLE
TextToPoints() ignores text alignment

### ISSUE THREAD

**Issue by araid** [processing/p5.js#6893]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [X] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build process
- [ ] Unit testing
- [ ] Internationalization
- [ ] Friendly errors
- [ ] Other (specify if possible)

### p5.js version

1.9.1

### Web browser and version

Chrome 122.0.6261.129

### Operating system

macOS

### Steps:
1. Load an external font
2. Define a multiline text string (use the character `\n`)
3. Call `textAlign(CENTER, BASELINE)` and then `textToPoints` on that string.
4. Observe how the points are always left-aligned.

### Snippet:

see https://editor.p5js.org/araid/sketches/S7DRlqtvP 

```js

let pts;
let font;
let str = 'Text\nto\npoints';

function preload(){
  font = loadFont('Inter-Black.otf');
}

function setup() {
  createCanvas(600, 600);
  
  textAlign(LEFT, BASELINE);
  textAlign(CENTER, BASELINE); // this doesn't work
  textSize(80);
  textFont(font);
  
  pts = font.textToPoints(str, 200, 0, 80, {
    sampleFactor: 0.25
  });
}

function draw() {
  background(200);
  translate(20, 140);
  
  // draw text
  fill(255);
  text(str, 200, 0);
  
  // draw points
  fill(28);
  noStroke();
  
  for(let i =0; i< pts.length; i++){
    ellipse(pts[i].x, pts[i].y, 2,2); 
  }
}
```

**Comment by RuimingShen** [comment]
This is not a bug from p5 code, it is an issue from textAlign property. Please reach out to developers for textAlign for this problem! More info can be found here Link[https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/textAlign]

**Comment by dhowe** [comment]
To provide some clarity, when textToPoints() was initially written, it did not include support for multiple text lines. If you needed multiple lines, you would call it multiple times. At some point, support for splitting a string on line breaks was added, but without support for the various alignments. Fixing this would only require (I think) using the existing _handleAlignment() function from [textBounds()](https://github.com/processing/p5.js/blob/main/src/typography/p5.Font.js#L585) in textToPoints() as well

**Comment by mathewpan2** [comment]
I'd like to work on this.
