### ISSUE TITLE
Dead Link in README.md

### ISSUE THREAD

**Issue by kaiserarg** [processing/p5.js#6930]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build process
- [ ] Unit testing
- [ ] Internationalization
- [ ] Friendly errors
- [X] Other (specify if possible)

### p5.js version

1.9.2

### Web browser and version

Chrome

### Operating system

Windows 11

### Steps:
There is a broken link under the "Stewards" section in the README file. The link is for the file organization.md which does not exist in the contributor_docs directory anymore. This issue also extends into certain translations of README. 

Is this file supposed to exist or is it removed now? In any case, please let me know and I would love to submit a PR to fix this issue on the README. Thanks!

See below for screenshots

### Details about the bug:
<img width="888" alt="Screenshot 2024-04-01 at 3 38 22 PM" src="https://github.com/processing/p5.js/assets/82423742/f9d5a311-7036-47da-8093-a1bc92a9d23e">

<img width="1092" alt="Screenshot 2024-04-01 at 2 20 41 PM" src="https://github.com/processing/p5.js/assets/82423742/dcd33b56-ae3e-4a4a-9aa7-5d6dc40fa4e7">

**Comment by devharipragaz007** [comment]
is the issue still open? Can I work on this?
