### ISSUE TITLE
DOM element position not always absolute

### ISSUE THREAD

**Issue by molleindustria** [processing/p5.js#694]
I run into a somewhat trivial but maddening issue while working on the examples.
The Element.position(x,y); function is advertised as "Sets the position of the element relative to (0, 0) of the window."

However in CSS an absolutely positioned child of a relatively positioned element will inherit the parent's offset. That explains why the example here positions the canvas at 50, 100 from the corner of the example container:
http://p5js.org/reference/#/p5.Element/position
(right now the canvas is not visible, you have draw something to see it)

A solution could be to subtract the offset of the parent. This seems to work but I don't know if it breaks other things:

p5.Element.prototype.position = function(x, y) {
    this.elt.style.position = 'absolute';
    var offset = $(this.elt).parent().offset();
    this.elt.style.left = (x-offset.left)+'px';
    this.elt.style.top = (y-offset.top)+'px';
    return this;
  };

**Comment by workergnome** [comment]
Rockin!
