### ISSUE TITLE
import p5 sound in next js

### ISSUE THREAD

**Issue by ayushi15092002** [processing/p5.js#6973]
### Topic

when I'm importing p5 sound in next js, getting error ( ReferenceError: window is not defined )

I want to know how to import it in next js and rightly use it?

**Comment by limzykenneth** [comment]
Hi, importing p5.js or p5 sound to be bundled as part of a larger client code base is not something that is tested nor necessarily supported, at least at this stage.

In general, if you need help with your own code, please direct your questions to the [forum](https://discourse.processing.org) or [Discord](https://discord.com/invite/SHQ8dH25r9). We use GitHub issues mainly for bug reports and feature requests only. Thanks!
