### ISSUE TITLE
[Question] how to apply data into p5.js?

### ISSUE THREAD

**Issue by yealicjswo** [processing/p5.js#6977]
### Topic

I wonder how to apply data(.csv, .xlsx,, or cloud..?) into p5.js??? if someone know about it, please share with me.

**Comment by yealicjswo** [comment]
@nickmcintyre thank you, will refer the link you share. and, I want to join the p5.js Discord, but I can't join it. so When you have time, can you check the issue..??

**Comment by nickmcintyre** [comment]
Oops, sorry about that @yealicjswo! Try https://discord.gg/YS8UfBbS

**Comment by yealicjswo** [comment]
@nickmcintyre ok, it did. thanks
