### ISSUE TITLE
Missing backtick in documentation for `loadModel`

### ISSUE THREAD

**Issue by aGuyWhoMadeGames** [processing/p5.js#6995]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [X] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build process
- [ ] Unit testing
- [ ] Internationalization
- [ ] Friendly errors
- [ ] Other (specify if possible)

### p5.js version

1.9.3

### Web browser and version

n/a

### Operating system

n/a

### Steps to reproduce this

There is a missing backtick in the Documentation page for `loadModel()`.
Is says this:

Paths to local files should be relative, as in `loadModel('assets/model.obj'). URLs such as `'https://example.com/model.obj'` may be blocked due to browser security.

but it should say:

Paths to local files should be relative, as in `loadModel('assets/model.obj')`. URLs such as `'https://example.com/model.obj'` may be blocked due to browser security.

**Comment by nickmcintyre** [comment]
Good catch @aGuyWhoMadeGames!
