### ISSUE TITLE
canvas doesn't load, no error thrown when invalid parameter passed to `textWrap()`

### ISSUE THREAD

**Issue by rbstrachan** [processing/p5.js#6997]
### Most appropriate sub-area of p5.js?

- [x] Core/Environment/Rendering
- [x] Typography
- [x] Friendly errors

### p5.js version

1.9.2

### Web browser and version

Firefox 125.0.2

### Operating system

Linux Ubuntu 22.04 LTS

### Steps
1. Create a new project.
2. Pass an invalid parameter, such as a number or string, to `textWrap()` in `setup()`.

### Snippet

```js
function setup() {
  createCanvas(400, 400);
  textWrap(50);
}
```

### Notes
When I first tried to use `textWrap()`, I wrongly assumed it took the maximum width, in pixels, of the text before wrapping occurred, so I did something like `textWrap(width * 2 / 3);`. The canvas disappeared and no error was given. I believe I've seen this behavior before with other methods but I can't remember which ones.

**Comment by rbstrachan** [comment]
It seems that the `textWrap()` method definition ([src/typography/attributes.js#L541](https://github.com/processing/p5.js/blob/23ac24b2058e17a2daaec72e63b5823d44f3e5ac/src/typography/attributes.js#L541)) does do a simple `if then` check to `throw` an error, but doesn't use `p5._validateParameters()`.

**Comment by limzykenneth** [comment]
@rbstrachan Issue is as you identified and using `p5._validateParameters()` does solve the issue as intended. However, there are some unit test related issue that was left uncaught for awhile and I need to fix that before fixing this. Will try to do so today. Thanks.
