### ISSUE TITLE
`p5.prototype.clearStorage` clears all items for the current domain, instead of items set with `storeItem` only

### ISSUE THREAD

**Issue by IronBlood** [processing/p5.js#7003]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [X] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build process
- [ ] Unit testing
- [ ] Internationalization
- [ ] Friendly errors
- [ ] Other (specify if possible)

### Steps to reproduce this

Code with comments are shown below. There should be a better way to handle with it, to avoid removing data set by other libraries or developers.

```javascript
/**
 *
 * Clears all local storage items set with storeItem()
 * for the current domain.
 *
 * @method clearStorage
 * @for p5
 *
 */
p5.prototype.clearStorage = function() {
  localStorage.clear();
};
```

**Comment by seralichtenhahn** [comment]
@IronBlood I agree, `clearStorage()` should only remove items set by `storeItem()`. I can see that `storeItem()` also sets an additional item where the type of the value is stored. These helper items are all suffixed with `"p5TypeID"`. That means there is a way of easily identifying all items set by `storeItem()`. 

I'm happy to open a PR with the implementation @limzykenneth

**Comment by limzykenneth** [comment]
@seralichtenhahn You can go ahead with a fix to match the documented behaviour. Thanks.
