### ISSUE TITLE
Incorrect display of extended unicode characters with text() and println()

### ISSUE THREAD

**Issue by golanlevin** [processing/p5.js#701]
Unicode characters in output should resemble Unicode characters in input, but currently don't. 

I wanted to display the [degree symbol](http://en.wikipedia.org/wiki/Degree_symbol "degree symbol") (°, U+00B0) in a p5.js canvas, using the text() command. Pasting the symbol into code in the IDE presented no problem. However, the symbol does not display correctly, whether on the canvas or in the console: 

```
var foo =  "It is 30° outside";
text (foo, 20,20); 
println (foo);
```

This produces the result: 
```
It is 30Â° outside
```

A provisional fix was to use the Javascript Unicode representation for the degree symbol, '\xB0'. However I think this will really trap novice programmers. 
```
  var foo = "It is 30\xB0 outside";
  text(foo, 20, 20);
  println(foo);
```

**Comment by workergnome** [comment]
I have also seen this—at least for me, it seemed to happen when running locally, but not when running on a server.

Not sure why, but that's another area to explore?

**Comment by workergnome** [comment]
Got it.  

```
  <meta charset="UTF-8">
```

needs to be added to the default sketch HTML for this to work.

**Comment by workergnome** [comment]
@lmccart fixed this in the deploy/release code—it will appear in the next released version of p5.js.
