### ISSUE TITLE
Is the index missing in `setName` from `p5.XML`?

### ISSUE THREAD

**Issue by IronBlood** [processing/p5.js#7019]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [X] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build process
- [ ] Unit testing
- [ ] Internationalization
- [ ] Friendly errors
- [ ] Other (specify if possible)

### Steps to reproduce this

The source code is shown below:

```javascript
  setName(name) {
    const content = this.DOM.innerHTML;
    const attributes = this.DOM.attributes;
    const xmlDoc = document.implementation.createDocument(null, 'default');
    const newDOM = xmlDoc.createElement(name);
    newDOM.innerHTML = content;
    for (let i = 0; i < attributes.length; i++) {
      newDOM.setAttribute(attributes[i].nodeName, attributes.nodeValue);
    }
    this.DOM = newDOM;
  }
```

Should it be `newDOM.setAttribute(attributes[i].nodeName, attributes[i].nodeValue);` instead? This line was introduce from the commit db90f55eb92b2b3f7aada01eb723bd485ca59597.

**Comment by limzykenneth** [comment]
It looks like the index is indeed missing from the reference to `attributes`, you can file a PR to fix this if you like.
