### ISSUE TITLE
How to change color of all circles?? 

### ISSUE THREAD

**Issue by yealicjswo** [processing/p5.js#7035]
### Topic

I would like to add color(any color I want) of whole dot while I test with 'for' loops example.
so, Is there an any solution for applying color of all circles??

function setup() {
  createCanvas(600, 600);
}

function draw() {
  background(240);
  let space = 10;
  strokeWeight(4);

  for (let x = space; x < 600; x += space) {
    // Loop from the top to the bottom.
    for (let y = space; y < 600; y += space) {
      point(x, y);
    }
  }
}

<img width="1501" alt="Screen Shot 2024-05-13 at 5 16 28 PM" src="https://github.com/processing/p5.js/assets/80077503/ed806ce6-6cc3-42b4-b4d3-337b89712b2b">

**Comment by limzykenneth** [comment]
Hi @yealicjswo you can use the [`stroke()` function](https://p5js.org/reference/#/p5/stroke) like the below:

```js
function setup() {
  createCanvas(600, 600);
}

function draw() {
  background(240);
  let space = 10;
  strokeWeight(4);
  stroke(255, 0, 0);

  for (let x = space; x < 600; x += space) {
    // Loop from the top to the bottom.
    for (let y = space; y < 600; y += space) {
      point(x, y);
    }
  }
}
```

If you need help with your own code, please direct your questions to the [forum](https://discourse.processing.org) or [Discord](https://discord.com/invite/SHQ8dH25r9). We use GitHub issues mainly for bug reports and feature requests only. Thanks!

**Comment by yealicjswo** [comment]
@limzykenneth thanks! I will make sure to ask an question(for my own code) in the forum and Discord.
