### ISSUE TITLE
`p5.Framebuffer.remove()` doesn't remove some resources 

### ISSUE THREAD

**Issue by nickmcintyre** [processing/p5.js#7048]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Build process
- [ ] Unit testing
- [ ] Internationalization
- [ ] Friendly errors
- [ ] Other (specify if possible)

### p5.js version

1.9.3

### Web browser and version

Chrome 124.0.6367.208

### Operating system

macOS 14.4.1

### Steps:
1. Call `myBuffer.remove()`.
2. Call `print(myBuffer)` or use `myBuffer` elsewhere.

### Snippet:

```js
function doubleClicked() {
  myBuffer.remove();

  // Should this be empty-ish?
  print(myBuffer);
}
```

Here's the [sketch](https://editor.p5js.org/mcintyre/sketches/r5HSggb--) for reference.

Does `myBuffer` have to be nullified in order for its resources to be garbage collected? It seems like the only other reference is cleared [here](https://github.com/processing/p5.js/blob/v1.9.3/src/webgl/p5.Framebuffer.js#L791).

Maybe too in-the-weeds, but if there's another reference somewhere in the sketch, then the resources are never fully freed.

**Comment by davepagurek** [comment]
The method is only intended to remove its *GPU* resources, which have to be manually cleaned up. All JS resources will be garbage collected as long as nothing else refers to it. That means to fully remove a framebuffer and its CPU resources, you'd have to do:
```js
myBuffer.remove()
myBuffer = undefined
```

That said, there isn't much stored on the CPU, so it's less of a concern than cleaning up the GPU bits, where it stores the texture data.

**Comment by nickmcintyre** [comment]
That makes sense; just made some edits in #7044 to reflect this.
