### ISSUE TITLE
missing link in documentation_style_guide.md

### ISSUE THREAD

**Issue by lottihill** [processing/p5.js#7050]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build process
- [ ] Unit testing
- [ ] Internationalization
- [ ] Friendly errors
- [X] Documentation

### p5.js version

1.9.3

### Web browser and version

chrome 124.0.6367.156

### Operating system

windows 11 v 22H2

### Steps:
go to https://github.com/processing/p5.js/blob/main/contributor_docs/documentation_style_guide.md#yuidoc

'Use the idioms recommended in this guide' is missing the link it is referring to.

**Comment by Qianqianye** [comment]
Thanks @lottihill. Closing this PR because it's fixed in https://github.com/processing/p5.js/pull/7053
