### ISSUE TITLE
Improve the grunt watch task

### ISSUE THREAD

**Issue by workergnome** [processing/p5.js#706]
Currently, grunt watch is painfully slow.  (on a pain scale of 1..10, a 2.  Boo-boo, not appendicitis).  

We should look into using things like [grunt-newer](https://github.com/tschaub/grunt-newer) and [grunt-concurrent](https://github.com/sindresorhus/grunt-concurrent) to improve this. 

This will also involve transitioning the test framework to test the individual modules, not the complete library, which may be a larger problem than we think.

**Comment by kadamwhite** [comment]
I'm interested in the challenge of making the framework test individual modules, but that may require some more re-architecture. @lmccart when do you expect the in-flight architecture changes you mentioned yesterday will be compete?

**Comment by lmccart** [comment]
they are complete for now... we might do more to further package up modules in the future, but at least the file structure makes more sense now.

**Comment by dhowe** [comment]
we might also want to move doc-creation (2 tasks) outside of watch

**Comment by workergnome** [comment]
@dhowe, `grunt watch:main` doesn't run the docs generation, and it should be a tiny bit faster now.

**Comment by dhowe** [comment]
much appreciated

**Comment by lmccart** [comment]
are we set here, or is there more to be done?

**Comment by kadamwhite** [comment]
Set for now, I think? I can make it faster but we're not quite ready for that yet

**Comment by lmccart** [comment]
ok great, let's reopen when we're ready for more action here.
