### ISSUE TITLE
When using callbacks in loading files instead of preload function, missing function draw() will cause an error

### ISSUE THREAD

**Issue by xyfeng** [processing/p5.js#708]
Below will not work
-----------------------------
function setup() {
  loadFont('./assets/fonts/AvenirNextLTPro-Demi.otf', drawText);
}

function drawText(font) {
  fill('#ED225D');
  textFont(font, 36);
  text('p5*js', 10, 50);
}

**Comment by therewasaguy** [comment]
I've got the same issue over here: https://github.com/processing/p5.js/issues/668 - I'll close this one to consolidate
