### ISSUE TITLE
a typo in createCanvas() reference？

### ISSUE THREAD

**Issue by AtErSi02** [processing/p5.js#7123]
### Topic

![屏幕截图 2024-07-08 150317](https://github.com/processing/p5.js-website/assets/73993198/71ea6997-878b-4d32-b49d-8ea6c64e0391)
it seems like this should be height instead of width

**Comment by Qianqianye** [comment]
Thanks @AtErSi02. I'm tagging @nickmcintyre to take a look.

**Comment by nickmcintyre** [comment]
Good catch @AtErSi02!
