### ISSUE TITLE
Reference page of Quad (2D Primitives)

### ISSUE THREAD

**Issue by jazerchand** [processing/p5.js#7124]
### Topic

This may be a gap in my understanding or a mistake on the reference page. Need help.

The quad drawn in 3D space, accepts two optional parameters - detailX and detailY, on the reference page it's mentioned that the default is 25, 25. 
<img width="877" alt="Screenshot" src="https://github.com/processing/p5.js-website/assets/14163566/b0e44668-8fa8-46da-a61e-c5070e3b85f7">

But the default seems to be 2,2 as when I input 25,25 at the end, something changes. Could someone please confirm/clarify?

**Comment by Qianqianye** [comment]
Thanks @jazerchand. I'm tagging @nickmcintyre to take a look.

**Comment by nickmcintyre** [comment]
Good catch @jazerchand! Looks like they're both [2 by default](https://github.com/processing/p5.js/blob/f397e2d480ea11ef944f1e24709dda72bb9d4c5f/src/webgl/3d_primitives.js#L2768).

**Comment by Abhinavcode13** [comment]
Where are the actual documentation for this one?
cc: @nickmcintyre, @Qianqianye.

**Comment by nickmcintyre** [comment]
[Here](https://github.com/processing/p5.js/blob/f397e2d480ea11ef944f1e24709dda72bb9d4c5f/src/core/shape/2d_primitives.js#L937) ya go!

**Comment by Abhinavcode13** [comment]
> [Here](https://github.com/processing/p5.js/blob/f397e2d480ea11ef944f1e24709dda72bb9d4c5f/src/core/shape/2d_primitives.js#L937) ya go!

Thanks a lot! @nickmcintyre
