### ISSUE TITLE
textWidth gives wrong value on setup function

### ISSUE THREAD

**Issue by pvzzombs** [processing/p5.js#7128]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [X] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build process
- [ ] Unit testing
- [ ] Internationalization
- [ ] Friendly errors
- [ ] Other (specify if possible)

### p5.js version

1.9.4

### Web browser and version

Brave 1.67.123 Chromium: 126.0.6478.126 (Official Build) (64-bit) 

### Operating system

Windows 10

### Snippet:

```js

var str = "press space to restart";
var w;

function setup() {
  createCanvas(100, 100);
  w = textWidth(str);
  console.log(w);
}

function draw() {
  str = "press space to restart";
  w = textWidth(str);
  console.log(w);
  noLoop();
}

```

**Comment by pvzzombs** [comment]
Replication link: [JSFiddle](https://jsfiddle.net/pbr9ednt/).
This issue is similar to issue [52](https://github.com/processing/p5.js/issues/52/).

**Comment by dhowe** [comment]
interestingly this only seems to happen using `var` not `let`

**Comment by morozgrafix** [comment]
agree with @dhowe Here is a small sketch to illustrate the point regarding using `str` as variable name, since it's a reserved word for built-in function of p5.js

```javascript
var s = "press space to restart";
var w;
var w1;

function setup() {
  createCanvas(100, 100);
  w = textWidth(s);
  w1 = textWidth(str);
  console.log(w);
  console.log(w1);
  console.log(str)
}

function draw() {
  s = "press space to restart";
  w = textWidth(s);
  w1 = textWidth(str);
  console.log(w);
  console.log(w1);
  console.log(str);
  noLoop();
}
```

Console output:
```
115.3828125
139.41796875
ƒ bound () {}
<constructor>: "Function"
name: "Function"
115.3828125
139.41796875
ƒ bound () {}
<constructor>: "Function"
name: "Function"
```
