### ISSUE TITLE
Text-based canvas accessibility throws error on out-of-Y-bounds shapes

### ISSUE THREAD

**Issue by bojidar-bg** [processing/p5.js#7130]
### Most appropriate sub-area of p5.js?

- [X] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build process
- [ ] Unit testing
- [ ] Internationalization
- [ ] Friendly errors
- [ ] Other (specify if possible)

### p5.js version

1.9.4

### Web browser and version

Firefox 127.0.2

### Operating system

Arch Linux

### Steps:
1. Create a new sketch in the web editor. (or use this one: <https://editor.p5js.org/bojidar-bg/sketches/mHXQgF7Sw>)
2. Add a shape that is out-of-bounds on the Y axis, e.g. `rect(200, 450, 10, 10)`
3. Enable Table-text canvas accessibility in the editor's settings (Big cog wheel top right / Accessibility / Accessible text-based canvas / Table-text)
4. Run the sketch.
5. Observe `TypeError: cells[ingredients[x][y].loc.locY] is undefined`; coming from: https://github.com/processing/p5.js/blob/f397e2d480ea11ef944f1e24709dda72bb9d4c5f/src/accessibility/gridOutput.js#L66

### Snippet:

```js
function setup() {
  createCanvas(400, 400);
}
function draw() {
  background(220);
  rect(200, 450, 10, 10)
}
```

**Comment by KamiNoAnt** [comment]
Having Plain-Text checked or both causes the same issue

**Comment by bojidar-bg** [comment]
Actually, I can't reproduce the issue with plan-text accessibility checked, after refreshing the page. Might be something to it however, so, mm, changed the title.

**Comment by KamiNoAnt** [comment]
I think it is weaker with Plain-Text. Maybe you need more shapes, that are out of bounds or shapes that are really far away from the canvas

**Comment by bojidar-bg** [comment]
Hm.. might be worth splitting the plain-text bug into a separate issue, since it's probably caused by a different part of p5.js's code.

**Comment by limzykenneth** [comment]
Thanks @bojidar-bg. Just to confirm, is this an editor specific issue or a bug with p5.js itself?

**Comment by bojidar-bg** [comment]
@limzykenneth Well.. no idea how to turn text-based canvas accessibility on from the sketch itself, but I'm pretty sure the culprit is in p5.js's code and not in the editor's code.

**Comment by limzykenneth** [comment]
Ok I'm able to replicate this locally as well. The problem is likely due to the `rect` being drawn offscreen and the accessibility feature (which is the `gridOutput()` function) tries to index a grid that is out of index bounds. I'll try to look into this this week for a fix.

**Comment by limzykenneth** [comment]
@KamiNoAnt What you describe sounds like a different issue, can you open another issue for it? Thanks.

**Comment by HectorDev309** [comment]
I had this same issue, I managed to solve it by adding `gridOutput = function(){}` inside the `setup()` function, of course you are literally making a built-in function unusable, but I never had to use it, so it works for me
