### ISSUE TITLE
Inconsistent instance mode canvas sizing

### ISSUE THREAD

**Issue by Evorage0** [processing/p5.js#7133]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [X] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build process
- [ ] Unit testing
- [ ] Internationalization
- [ ] Friendly errors
- [ ] Other (specify if possible)

### p5.js version

1.9.4

### Web browser and version

126.0.6478.127

### Operating system

Windows

### Steps to reproduce this

https://editor.p5js.org/bensgilbert/sketches/MTYSOOCSv

Run the sketch
Resize the preview window (it's easier to see if you increase it's size)
Check the console output

This bug has been confirmed on MS Edge (Chromium) and Firefox leading me to believe it's a cross browser problem with p5
Discord chain: https://discordapp.com/channels/836700474425475088/1007853564363817060/1263206263395848282

**Comment by Evorage0** [comment]
Uploading localhost_5173_projects - Profile 1 - Microsoft​ Edge 2024-07-17 19-58-57.mp4…

**Comment by Evorage0** [comment]
https://github.com/user-attachments/assets/e9188ebe-1acf-407a-a7df-1b426e1743c7

**Comment by davepagurek** [comment]
I wonder if this is breaking it for multiple p5 instances: https://github.com/processing/p5.js/blob/2a86e709f7a285a812776bac9ed7eca871311661/src/core/environment.js#L678

It looks like the only other time we set `windowWidth`/`windowHeight` is on a resize, so if the resize happens between instances existing, maybe it just keeps using the default old values?

If that's the case, it seems like we need to update those values here before calling `preload` or `setup`: https://github.com/processing/p5.js/blob/2a86e709f7a285a812776bac9ed7eca871311661/src/core/main.js#L361
