### ISSUE TITLE
Wrong definition for circle on the reference for the `circle()` function.

### ISSUE THREAD

**Issue by apoullet** [processing/p5.js#7141]
### Most appropriate sections of the p5.js website?

Reference

### What is your operating system?

Linux

### Web browser and version

Firefox 124.0.1

### Actual Behavior

![Screenshot from 2024-07-21 13-53-34](https://github.com/user-attachments/assets/7d403ec6-5d87-4ede-8ecf-c085077d7d4c)
This might be my own misinterpretation, but "Every point on the circle's edge is the same distance, d, from its center" right after defining `d` as the diameter seems wrong. It feels like it was meant to be "..is the same distance, **d / 2**, from its center".

### Expected Behavior

Reword the definition of  a circle to use the radius as the distance between any point of the circle and its center.

### Steps to reproduce

Go to this page: https://p5js.org/reference/p5/circle/

### Would you like to work on the issue?

Happy to put in the fix for this. Apologies if there is another place to report issues like these, I couldn't find one more appropriate.

**Comment by Qianqianye** [comment]
Thanks @apoullet for pointing this out. This issue is fixed in this PR #7110, which will go live after our upcoming p5.js release in a two weeks or so.
