### ISSUE TITLE
missing concat-files module?

### ISSUE THREAD

**Issue by molleindustria** [processing/p5.js#715]
While implementing the inline examples I'm running a "grunt watch yui" to rebuild a local copy of the reference at every change.
However since I synchronized to the current master I get an error:

Running "requirejs:p5_unminified" (requirejs) task
Warning: There was an error while processing your done function: "Error: Cannot find module 'concat-files'" Use --force to continue.

I tried to install concat-files it with all variations of:
sudo npm install concat-files -g

But the error persists. What am I missing?
:(

**Comment by lmccart** [comment]
this was added recently with the type stuff
it should be fixed if you just run `npm install` again

**Comment by molleindustria** [comment]
Yay it works now!

**Comment by lmccart** [comment]
great
