### ISSUE TITLE
Strange behavior of clips with three successive ellipses/circles

### ISSUE THREAD

**Issue by Coupechoux** [processing/p5.js#7158]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [X] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build process
- [ ] Unit testing
- [ ] Internationalization
- [ ] Friendly errors
- [ ] Other (specify if possible)

### p5.js version

1.9.4

### Web browser and version

Firefox 128.0.3

### Operating system

Windows 64-bit

### Steps:
1. Begin a clip.
2. Draw one shape followed by two circles (or ellipses) in the clip.
3. End the clip.

The resulting clip contains the first shape and the two circles AND an unwanted polygon created from the rightmost points of the circles.

### Snippet:

```js
function setup() {
    createCanvas(400, 400);
    background(0);
    beginClip();
    circle(100, 100, 100);
    circle(300, 100, 100);
    // square(250, 250, 100);
    circle(100, 300, 100);
    endClip();
    background(255);
}
```
Left image : 3 circles
Right image : 2 circles + 1 square + 1 circle
![untitled](https://github.com/user-attachments/assets/52f53faa-010a-4751-8e7b-7be2ce8b62dd)

**Comment by inaridarkfox4231** [comment]
The same problem occurs with clip(), which is based on the original javascript, so it seems that p5.js is not the cause.

![frdfefedclip](https://github.com/user-attachments/assets/797f2c82-074a-4e20-ad4b-55cf2073e1eb)

```js
function setup() {
  createCanvas(400, 400);
  const ctx = drawingContext;
  ctx.fillStyle = "black";
  ctx.fillRect(0, 0, 400, 400);
  ctx.beginPath();
  ctx.arc(100,100,50,50,0,2*PI);
  ctx.arc(100,300,50,50,0,2*PI);
  ctx.arc(300,300,50,50,0,2*PI);
  ctx.clip();
  ctx.fillStyle = "white";
  ctx.fillRect(0, 0, 400, 400);
}
```

**Comment by inaridarkfox4231** [comment]
It doesn't seem to occur with webgl.

![efdgerdgert4er](https://github.com/user-attachments/assets/7940e118-02bd-40ff-9f05-7d2b8c5f356c)

```js
function setup() {
  createCanvas(400, 400,WEBGL);
  noStroke();
  translate(-200,-200);
  background(0);
  beginClip();
  circle(100, 100, 100);
  circle(300, 100, 100);
  //square(250, 250, 100);
  circle(100, 300, 100);
  endClip();
  translate(200,200);
  fill(255);
  plane(400);
}
```

**Comment by inaridarkfox4231** [comment]
In order to investigate the 2D situation, I tried combining the methods of drawing a circle using moveTo() and lineTo().

![dfedgrdclip](https://github.com/user-attachments/assets/99353bfc-6fcc-43a2-9947-c1dfff56ce6d)

As a result, I found that this problem does not occur depending on the combination.

```js
const drawFlag0 = [1,1,1]; // failure.
const drawFlag1 = [1,1,0]; // success.
const drawFlag2 = [1,0,1]; // success.
const drawFlag3 = [0,1,1]; // failure.
const drawFlag4 = [1,0,0]; // success.
const drawFlag5 = [0,1,0]; // success.
const drawFlag6 = [0,0,1]; // success.
const drawFlag7 = [0,0,0]; // success.

function setup() {
  createCanvas(400, 400);
  const ctx = drawingContext;
  ctx.fillStyle = "black";
  ctx.fillRect(0, 0, 400, 400);
  ctx.beginPath();

  const drawFlag = drawFlag1;

  const addArc = (flag, cx, cy, flagIndex) => {
    if(flag[flagIndex]){
      ctx.arc(cx,cy,50,50,0,2*PI);
    }else{
      for(let i=0;i<=400;i++){
        let t = TAU*i/400;
        let x = cx+50*cos(t);
        let y = cy+50*sin(t);
        if(i===0){ctx.moveTo(x,y)}else{ctx.lineTo(x,y)}
      }
    }
  }

  addArc(drawFlag, 100,100,0);
  addArc(drawFlag, 300,100,1);
  addArc(drawFlag, 100,300,2);

  ctx.clip();
  ctx.fillStyle = "white";
  ctx.fillRect(0, 0, 400, 400);
}
```
The problem only occurs for drawFlag0 and drawFlag3. For example, if you draw first two circles with arc(), and draw the last circle using moveTo() and lineTo(), strange triangles will not appear. I don't know the cause.

Using this as a reference, when I drew first two circles with circle(), and only the last circle using beginShape() and endShape() in p5.js, no strange triangles appeared.

![rtgredfgrgrfclip](https://github.com/user-attachments/assets/3756cfd7-c07a-4710-b29b-a05bf7dc419b)

```js
function setup() {
  createCanvas(400, 400);
  background(0);
  beginClip();
  circle(100, 100, 100);
  circle(300, 100, 100);
  // square(250, 250, 100);
  //circle(100, 300, 100);
  beginShape();
  for(let i=0;i<=400;i++){
    t=TAU*i/400;
    vertex(100+50*cos(t),300+50*sin(t));
  }
  endShape();
  endClip();
  background(255);
}
```

**Comment by AaratiAkkapeddi** [comment]
Hi! I'd love to help with this task

**Comment by inaridarkfox4231** [comment]
Although it is not a solution, but if you write the last circle using beginShape(), the problem does not seem to occur.

![rtgredfgrgrfclip](https://github.com/user-attachments/assets/0d2805c3-8c3d-405b-91ad-f6c398d936d1)
