### ISSUE TITLE
Image light orientation inconsistent with panorama

### ISSUE THREAD

**Issue by Martin-Lorentzon** [processing/p5.js#7167]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Build process
- [ ] Unit testing
- [ ] Internationalization
- [ ] Friendly errors
- [ ] Other (specify if possible)

### p5.js version

v1.10.0 July 31, 2024

### Web browser and version

Microsoft Edge Version 127.0.2651.98 (Official build) (64-bit)

### Operating system

Windows 10

### Steps:
1. Run the project
2. Take note of the image light- and panorama orientation

### Snippet:

```js
let sceneScale;
let sceneTranslation;
let env

let img;
let teaport;

function preload() {
  img = loadImage("https://p5js.org/assets/outdoor_spheremap.jpg");
  teapot = loadModel("https://p5js.org/assets/teapot.obj");
}

function setup() {
  sceneScale = createVector(100, -100, 100);
  sceneTranslation = createVector(0, -1.5, 0);

  createCanvas(640, 360, WEBGL);
  noStroke(); // Disables the wireframe.
  
  const cnv = createGraphics(400, 200)
  cnv.background(0)
  cnv.noStroke()
  cnv.fill(255)
  cnv.rect(0, 0, 200, 200)
  env = cnv.get()
  cnv.remove()
}

function draw() {
  // Set the background colour.
  // background('white');

  // Set the background panorama.
  panorama(env);

  // Transform the scene.
  scale(sceneScale);
  translate(sceneTranslation);

  // Enable orbiting with the mouse.
  orbitControl();

  // Create an ambient light.
  // ambientLight(50);

  // Create a directional light.
  let c = color("white");
  let lightDir = createVector(0, 1, 0);
  directionalLight(c, lightDir);

  // Create an image light.
  imageLight(env);

  // Add a specular material.
  specularMaterial(255);
  shininess(100);
  metalness(300);
  fill(150)

  // Draw the model.
  model(teapot);
}
```

**Comment by davepagurek** [comment]
Here's a live example: https://editor.p5js.org/davepagurek/sketches/0smDG7pB_

<img width="637" alt="image" src="https://github.com/user-attachments/assets/dcbe8ac3-7971-4ce7-b97e-e6c28b8207b9">

<img width="638" alt="image" src="https://github.com/user-attachments/assets/0f0c1d76-a4b4-49ee-9509-d0822e380660">

<img width="638" alt="image" src="https://github.com/user-attachments/assets/14bbf72f-3022-48d8-8dcb-f58d13f9779d">

**Comment by perminder-17** [comment]
Sorry for the oversight, as @davepagurek mentioned there's a 90-degree rotation difference between imageLight() and panorama. This can be easily fixed by adding an offset to either one of them.

If someone is thinking of adding an offset to panorama, it's using the sphereMapping algorithm used here.

https://github.com/processing/p5.js/blob/main/src/webgl/shaders/sphereMapping.frag#L18

By fixing the y-axis it could be solved I think.

![Screenshot from 2024-08-12 23-35-52](https://github.com/user-attachments/assets/87077b16-78f6-44ce-9850-4591cd1fc3e9)

Maybe we can add just these lines after line 18 to solve this

```js
    float temp = rotatedNormal.z;
    rotatedNormal.z = rotatedNormal.x;
    rotatedNormal.x = -temp;
```

Hope this helps, thanks:)

**Comment by davepagurek** [comment]
@all-contributors please add @Martin-Lorentzon for bug
