### ISSUE TITLE
Mobile: text near horizontal canvas edges is not displayed

### ISSUE THREAD

**Issue by andswitch** [processing/p5.js#7197]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [X] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Build process
- [ ] Unit testing
- [ ] Internationalization
- [ ] Friendly errors
- [ ] Other (specify if possible)

### p5.js version

v1.10.0

### Web browser and version

Firefox 129.0.2

### Operating system

Android 14

### Steps to reproduce this

See: https://editor.p5js.org/andswitch/full/AG2VAULBB

On desktop all 6 words are displayed.
On mobile only "OR" and "NOT" are displayed.

As a workaround you can render text in the center of a framebuffer and then render the framebuffer on the canvas.

**Comment by mahi6299** [comment]
Hi @andswitch ! I want to contribute on this issue. Please assign me.
