### ISSUE TITLE
Get Started link in the project README gives a 404

### ISSUE THREAD

**Issue by ibrand** [processing/p5.js#7208]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build process
- [ ] Unit testing
- [ ] Internationalization
- [ ] Friendly errors
- [X] Other: Onboarding **Documentation**

### p5.js version

1.10

### Web browser and version

Firefox 129.0.1 though it would impact all browsers

### Operating system

Mac OSX and all others

### Steps:
1. Visit the main repo and [scroll down the README](https://github.com/processing/p5.js?tab=readme-ov-file#p5js) to the get started link.
2. Clicking that link surfaces this page: https://p5js.org/get-started which is a 404

### Solution:
I'm pretty sure the link should link to: https://p5js.org/tutorials/get-started/ if you all agree, I'll submit a PR to update it

**Comment by willallstet** [comment]
I can fix this right now!

**Comment by willallstet** [comment]
I agree!

**Comment by davepagurek** [comment]
Thanks, feel free to open a PR!

**Comment by willallstet** [comment]
[Pull request open!](https://github.com/willallstet/p5.js/pull/2)

**Comment by villares** [comment]
could someone please think of a solution to the same broken link inside hello.p5js.org interactive presentation?
Maybe a redirection would help? (as it is harder to edit the link there) https://github.com/processing/p5.js-website/issues/479

**Comment by ibrand** [comment]
@all-contributors please add @ibrand  for bug
