### ISSUE TITLE
linePerspective breaks with push pop

### ISSUE THREAD

**Issue by TiborUdvari** [processing/p5.js#7209]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Build process
- [ ] Unit testing
- [ ] Internationalization
- [ ] Friendly errors
- [ ] Other (specify if possible)

### p5.js version

1.9.2

### Steps to reproduce this

I took the [linePerspective example](https://p5js.org/reference/p5/linePerspective/) and added `push` and `pop` around the block of drawing boxes. When toggling linePerspective, the strokes inside the the push pop boundary are not being affected. I added another box (green) outside the boundary, which seems to get affected correctly.
https://editor.p5js.org/TiborUdvari/sketches/NcnxLpEum

I think the big issue is that in the current state anything inside a push-pop boundary will have linePerspective on. 

This noticed this with v1.9.2 for p5.xr as it was using a custom camera and thus uniform strokes (cf snippet below). As there seem to be some issues with the line rendering as I mentioned here #7200, I wanted to get this mode working first.

p5.shader v1.9.1
```js
    if (this.isStrokeShader()) {
      if (this._renderer._curCamera.cameraType === 'default') {
        // strokes scale up as they approach camera, default
        this.setUniform('uPerspective', 1);
      } else {
        // strokes have uniform scale regardless of distance from camera
        this.setUniform('uPerspective', 0);
      }
    }
```

p5.shader v1.9.2
```js
this.setUniform('uPerspective', this._renderer._curCamera.useLinePerspective ? 1 : 0);
```

Right now the useLinePerspective always sends in true for things inside push pop, I can't quite understand why just yet.

**Comment by davepagurek** [comment]
Good catch! I think we may be missing this property in [`p5.Camera::set`](https://github.com/processing/p5.js/blob/0b01116011758ac4fef59d053490e54a91e05720/src/webgl/p5.Camera.js#L3300) and [`p5.Camera::copy`](https://github.com/processing/p5.js/blob/0b01116011758ac4fef59d053490e54a91e05720/src/webgl/p5.Camera.js#L3648), so saving and restoring that property isn't working. I suspect adding it to those two spots should fix this!

**Comment by TiborUdvari** [comment]
Yes, that's the problem. I'll do a PR tomorrow to fix it.
