### ISSUE TITLE
p5.Graphics _resizeHelper() is currently undefined in Graphics3D

### ISSUE THREAD

**Issue by indefinit** [processing/p5.js#722]
Resize function in p5.Graphics currently calls _resizeHelper() which is defined in Graphics2D only.  
https://github.com/processing/p5.js/blob/8d0abfde6eeffcd2225c23bdeeded4eb7577f984/src/core/p5.Graphics.js#L53

I think perhaps a less error-prone way to write this would be to instead override the method in Graphics2D like so:
```
p5.Graphics2D.prototype.resize = function(w,h){
    p5.Graphics.prototype.resize.call(this);
    this._resizeHelper();
};
```
Also, maybe we can reduce a couple lines of code since we can include inline with the prototype resize function.  When implementing the same method in Graphics3d, it would look something like this:
```
    gl.viewport(0, 0, gl.canvas.width, gl.canvas.height);
```

**Comment by lmccart** [comment]
thanks @indefinit I believe this has been fixed.
