### ISSUE TITLE
ImageMode(CENTER)  does not work when the image drawing starts from position 0 , 0  

### ISSUE THREAD

**Issue by Forchapeatl** [processing/p5.js#7231]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [X] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build process
- [ ] Unit testing
- [ ] Internationalization
- [ ] Friendly errors
- [ ] Other (specify if possible)

### p5.js version

1.10.0

### Web browser and version

Google Chrome Version 119.0.6045.199 (Official Build) (64-bit)

### Operating system

Linux

### Steps to reproduce this

Bug:
![image](https://github.com/user-attachments/assets/6b87243c-5b12-41b8-92fd-1628865b5159)

Expected Results 

![image](https://github.com/user-attachments/assets/7b5b849f-f8dd-4866-8517-8b94798e57a7)

### Steps:
1. load an image 
2. Set the imageMode to Center  `  imageMode(CENTER);`
3. Let drawing begin at  0 , 0  `  image(img, 0, 0, 100, 100);`

### Snippet:

```js

let img;

// Load the image.
function preload() {
  img = loadImage('https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/June_odd-eyed-cat_cropped.jpg/100px-June_odd-eyed-cat_cropped.jpg');
}

function setup() {
  createCanvas(100, 100);

  background(200);

  // Use CENTER mode.
  imageMode(CENTER);

  // Display the image.
  image(img, 0, 0, 100, 100);

  describe('A square image of a brick wall is drawn on a gray square.');
}
```

To see the expected results , comment out this line `  imageMode(CENTER);
`

**Comment by willallstet** [comment]
To my eye, this seems to be working correctly. If I understand correctly,[ using imageMode(CENTER) makes the point of reference for drawing an image at its center](https://p5js.org/reference/p5/imageMode/) rather than centering the image on the canvas. So, if you place the photo at 0,0, the image's center will be 0 pixels from the top left and 0 pixels from the left. Instead, you may want to use imageMode(CORNERS) and place it at 0,0.

**Comment by membralala** [comment]
Hey @Forchapeatl, 

Someone might correct me, but as far as I understand, what you described might be the intended behaviour for `imageMode(CENTER)`. According to the [Reference](https://p5js.org/reference/p5/imageMode/) the CENTER mode should interpret the first two arguments as x-y-coordinates of the center of the image. So according to your code snippet, the image center should be at position (0, 0), which looks like it is. 
To get to your expected result you might try either use `imageMode(CORNER)` (which is the default imageMode) or 
```
// Use CENTER mode.
imageMode(CENTER);
// Display image centered on the canvas.
image(img, width/2, height/2, 100, 100);
```

**Comment by Forchapeatl** [comment]
Thanks everyone .
