### ISSUE TITLE
Fix broken link for p5js references in FES Messages in console

### ISSUE THREAD

**Issue by computationalmama** [processing/p5.js#7244]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build process
- [ ] Unit testing
- [ ] Internationalization
- [X] Friendly errors
- [ ] Other (specify if possible)

### p5.js version

1.10.0

### Web browser and version

128.0.6613.119 (Official Build) (arm64) 

### Operating system

MacOSX Sonoma 14.5

### Steps:
1. Test simple shape function like `circle(100,100, )` - intentionally not added diameter parameter
2. Run sketch - open console
3. FES message shows wrong reference link (still links to archive p5js website not the new one)

_**NOTE: This error shows up in locally run sketch and in the p5.js web editor**_

Old links for reference was http://p5js.org/reference/#/p5/circle and now with the revamped website it should be https://p5js.org/reference/p5/circle/

![FESlink2](https://github.com/user-attachments/assets/4dec494f-71d1-4123-8db8-6aa6b0dceb04)

![FESlink1](https://github.com/user-attachments/assets/3a24ad85-5503-4241-bfc0-f0671ffadc1c)

### Solution 
Requires a small edit in the FES core file `src/core/friendly_errors/fes_core.js` and possibly `src/core/friendly_errors/sketch_reader.js` 

**Reference links here**
https://github.com/processing/p5.js/blob/ada3c05da35bb8daf3b9d0ca1dc5713bff0b95c1/src/core/friendly_errors/fes_core.js#L148

https://github.com/processing/p5.js/blob/ada3c05da35bb8daf3b9d0ca1dc5713bff0b95c1/src/core/friendly_errors/sketch_reader.js#L70

### Snippet:

I believe this is the change needed - but I would need some guidance to share the PR for this. 

```js
// line 147 
//Whenever func having p5.[Class] is encountered, we need to have the error link as mentioned below else different link
funcName.startsWith('p5.')  ?
   msgWithReference = `${message} (https://p5js.org/reference/${referenceSection}.${funcName})` :
   msgWithReference = `${message} (https://p5js.org/reference/${referenceSection}/${funcName})`;
    
```

**Comment by yashsaraswat2004** [comment]
Please assign this issue to me

**Comment by Qianqianye** [comment]
Thanks @computationalmama. Tagging the active FES contributors @sproutleaf @limzykenneth @davepagurek to take a look at this issue as well

**Comment by davepagurek** [comment]
We have this issue on the website repo that might handle this: https://github.com/processing/p5.js-website/issues/487

So far I think discussion has just been about doing it via Astro, but DNS options are interesting too, and worth bringing up! I'm less familiar with the website's setup outside of astro (I think we host with github pages, is that in conjunction with cloudflare? do we have other dns configuration ability?) but getting a redirect somehow would be helpful.

**Comment by limzykenneth** [comment]
I think if Astro can handle it, it would be my preference. I use Cloudflare a lot in my other stuff and while I like it, it has some limits on the number of page rules and it is a bit opaque.

The setup of the website is that the site server is essentially GitHub Pages serve statically, then Cloudflare is the DNS provider pointing an A record to GitHub Pages that does the relevant reverse proxying. The traffic is routed through Cloudflare's servers for caching, security, and if we want to some customizability such as Page Rules.
