### ISSUE TITLE
Make long lines in documentation examples wrap automatically?

### ISSUE THREAD

**Issue by dhowe** [processing/p5.js#726]
not sure if this is a website issue
and not sure if its possible, but would be good to avoid cases like below (which are less than 80 chars):

![screen shot 2015-06-01 at 2 46 02 pm](https://cloud.githubusercontent.com/assets/737638/7920687/a03dedea-086e-11e5-9b52-291756f0928f.png)

**Comment by workergnome** [comment]
Hmm.  I'm used to seeing horizontal scrolling on inline code examples, but I don't know if that's a technical constraint or tradition.  Worth looking into.

**Comment by dhowe** [comment]
yes, that seems like a better solution than autowrap...

**Comment by jedahan** [comment]
I've also seen the width of code examples go to 100% when moused over, which was pretty slick and still readable...

**Comment by workergnome** [comment]
Rockin'.  I think this *is* a website issue—I'll move it over there.  I like @jedahan's idea the best of the options we've thought of, perhaps paired with scrolling for *ridiculously* long examples?
