### ISSUE TITLE
Hi, Haskell support?

### ISSUE THREAD

**Issue by jaypowers** [processing/p5.js#7286]
### Increasing access

Hi, I'm no elietest Haskell developer, lol. Maybe I'll add an addon eventually. Not a parser for Haskell, but I'd like to contribute something like Haskell+p5js. It's beyond me, but LaTeX support in some relationship to this would be really cool. Lastly, LaTex+Haskell+p5js???

### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build process
- [ ] Unit testing
- [ ] Internationalization
- [ ] Friendly errors
- [X] Other (specify if possible)

### Feature request details

If I can, and I probably can't. I'd love love love to add a Haskell parser, ie. "let code = "<some haskell code>". I realize this particular thing may not be possible, at least not for me. Any suggestions (except just "link a haskell.js") I'd love to hear.

**Comment by jaypowers** [comment]
Thanks!

Yes, I would think someone may have, I’ll probably do research on it later!

Just a side note, I’m thinking it could be done w/o eval() or system calls,
I do think it would be cool and beneficial either way. Yes, if I were to
make it p5 add on library seems proper.

Thanks again for your comments!

**Comment by davepagurek** [comment]
Since this won't be a core feature, I'm going to close this issue for organizational purposes, but we have a p5 discord you can join if need any advice while making the library, or need any debugging help! https://discord.gg/SHQ8dH25r9
