### ISSUE TITLE
 Integration with d3

### ISSUE THREAD

**Issue by workergnome** [processing/p5.js#730]
At Eyeo, I had a great conversation with @sciutoalex, who is interested in seeing if he can construct a library that allows p5 sketches to integrate with (or instantiate) d3 sketches.  In particular, we're interested in using the d3 [dispatch](https://github.com/mbostock/d3/wiki/Internals) functionality. @sarahgp, I know that you're a d3 expert, do you have any thoughts?

Anyone else, input, requests, ideas for how this could be useful?  My feeling is that this is not core functionality, but that refining this and perhaps fleshing out some of the requirements here could be useful.

@sciutoalex, you should also check out the [existing documentation](https://github.com/processing/p5.js/wiki/Libraries) on how external libraries work.  I'm also happy to answer any questions that you have about how to get started, or direct you towards other people who know more than I do.

**Comment by sepans** [comment]
I thought d3.js dispatch was using custom Javascript events under the hood but [it seems](https://github.com/mbostock/d3/blob/master/src/event/dispatch.js) it doesn't. If this feature is intended to facilitate d3-p5 communication why not use [Javascript custom events](https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Creating_and_triggering_events)?

**Comment by workergnome** [comment]
Looks like there's not IE support yet for Custom Events.  Also, I wonder if using d3 events would be more intuitive for d3 users.  @sciutoalex: opinions?

**Comment by SciutoAlex** [comment]
I don't think D3 dispatches are too commonly used by most D3 users. There is nice documentation and [one example](http://bl.ocks.org/mbostock/5872848) from Mike Bostock. I have never used Javascript custom events.

I would follow either of your lead on this. I was thinking the plugin could create a few custom dispatches that the user would add to their D3 code and then the plugin would transmit that back to the p5 sketch. Alternatively, D3 does a great job doing the boring work of making [axes, shapes, and controls](https://github.com/mbostock/d3/wiki/SVG). Could there be a way for a p5 user to layer an svg axes above their sketch?

Thanks!

**Comment by shiffman** [comment]
adding @alignedleft in case he has some some ideas/thoughts re: d3 and p5

**Comment by sarahgp** [comment]
Yeah, I am definitely not expert enough to have an opinion on this. What is the use case, exactly?

**Comment by sepans** [comment]
I think the reason behind introducing dispatch in d3.js was to make it more 'light-weight' and not use DOM events which bubble up through DOM tree, creating extra overhead. It more looks like a communication channel which receivers subscribe to it (like sockets).

@workergnome Good catch. Though there are cross browser [solutions](http://blog.garstasio.com/you-dont-need-jquery/events/#sending-custom-events) for custom events.

I can think of a few different ways of integration d3-p5:
* Communication (which doesn't necessarily need p5 support. We can create some examples that does that)
* Using D3 Utilities like scales etc. in p5 (same as above)
* Manipulating elements or drawing things like axes as @SciutoAlex mentioned (Depends on p5.js SVG [support](https://github.com/processing/p5.js/issues/45))

Would love to know more thoughts on this.

PS: [This](http://bocoup.com/weblog/d3js-and-canvas) post by @iros about d3 in canvas mode is also very illuminating.

**Comment by alignedleft** [comment]
I have never used D3 dispatches, but I agree that, in theory, supporting this in a friendly way would be a nice way to encourage interaction between the two libraries. I would anticipate confusion when handing different portions of tasks to p5 and d3.  For example:  A slider changes value, and d3 should handle something in response, while p5 does something else.  Is it more p5-like to let p5 listen for that event (and handle it) or let d3 listen (and handle it)?  

Either way, this is probably not a common scenario, but definitely I see value in getting both tools to talk to each other more smoothly.  Lots of people will want to use d3 for the data loading/parsing/manipulation/calculations and p5 for drawing.

**Comment by SciutoAlex** [comment]
Over the weekend, I put together a loose communication system for p5-D3 communication. You can see an example [here](http://sciutoalex.github.io/p5d3-connect/examples/examples.html). This example uses d3.dispatch() to communicate events and an associated data object. I would have liked to include a `function d3EventFired()` similar to `function mouseMoved()`, but I wasn't able to figure that out.

On the p5 side, the plugin works like:
<pre>
var d3Module = p.D3Connect([typesOfEvents]);
var receivedData = d3Module.getValue(type); //receiving data from D3
d3Module.setValue(type, optionalData); //sending to D3. 
</pre>

On the D3 side, the plugin works like:
<pre>
p5connect.type(100-pos.y);
p5connect.on(type, eventHandler);
</pre>
I was thinking about further integrations, but I think one-off D3 functions, like using its color object or using scales, is easier to just use the D3 object instead of forcing it into a plugin. Is that a reasonable thought?

**Comment by kadamwhite** [comment]
I'm not sure I understand the goal of this: is it to let you control d3 through p5 commands, or is it a way to use parts of d3 and parts of p5 together in the same project?

Please take this with a grain of salt because I'm not clear on the intent of this issue, but both d3 and p5 have a lot of surface area, and a lot of distinct idioms -- it might be more broadly helpful to have examples (maybe in the "cookbook" style, with solutions to particular problems) of how to use p5 and d3 together than it would be to create a plugin to do any specific integration.

**Comment by sepans** [comment]
@kadamwhite +1

**Comment by alignedleft** [comment]
@kadamwhite +1

@SciutoAlex what you put together is valuable, but conceptually (and this is for me only), it is confusing to think about D3 and p5 handing information "off" to each other. Aren't they both JavaScript, and both in the browser? Of course, D3 has its own unique ways of storing data (bound to elements), but other than that, these are not two tools operating in distinct environments.

This is just me thinking out loud, but I think I would vote for something that encourages this co-existence (more philosophically) rather than pretending they are separate.

Maybe what we need here are some use cases.  It is still hard for me to imagine when someone would want to do this, except for a simple example: D3 loading/parsing data, and p5 grabbing it to visualize it.

**Comment by sepans** [comment]
I ported a d3.js [example](http://bl.ocks.org/mbostock/3048450) which uses histogram layout into p5.js, trying to take maximum advantage of d3.js utilities while sticking to p5.js for rendering ('surface area' and  'idioms' to use @kadamwhite words).

Codepen [here](http://codepen.io/sepans/pen/LVLyNY)

The resulting code, to my own surprise, has literally zero coupling between d3.js and p5.js, and without any cryptic hacks. So practically speaking, it is not a bad idea to create more of these 'cookbook' style examples.

The only lost piece is the axis as @SciutoAlex mentioned before, which I cannot think of a way of implementing it without dirty hacks or mingling d3 and p5 together, or doing all low level calculations without using d3. 

I didn't put much thought into choosing d3 examples so any suggestions are very helpful.

**Comment by SciutoAlex** [comment]
I think the cookbook of ways to combine is a good approach. @sepans, I think it is easier for users to use D3's functions directly instead of interpreting them through some kind of library. It might also be a pretty short cookbook, based on how straight-forward @sepans was.

Would a github repo be a good place for these kinds of examples? Also, I'm curious what @workergnome thinks.

**Comment by sepans** [comment]
Another example: [Voronoi layout](http://codepen.io/sepans/pen/Qbgaby)

**Comment by SciutoAlex** [comment]
@sepans, here's an example with mouse interaction and animation: http://codepen.io/anon/pen/YXQdqR

Replaces the draw() loop with d3.timer(). Draw loop works, but d3.timer() gives slightly smoother transitions.

**Comment by sepans** [comment]
Thats great @SciutoAlex, thought it is more useful for advanced users who are familiar with advanced techniques such as 'custom' in-memory elements, and not afraid of mixing up d3 and p5 paradigms.

**Comment by workergnome** [comment]
Hi, everyone.  @SciutoAlex—thank you so much for running with this!  These are exactly the conversations that I was hoping would come out of this, and your example is fantastic.

@sepans—I don't disagree with you.  Once someone knows enough javascript to understand how to integrate these two things together themselves, a library for gluing them together might become...trivial is the wrong word, but more constraining than useful, perhaps?

The people that I'm most interested in helping are the people who know that "you can do things in D3", and want to understand how best to use them together.  I think that a cookbook of examples, like the ones that you guys have put together is fantastic.  

Is everyone on board with turning this into a tutorial or blog post, instead of a plugin?  It seems like in the examples here, we have a really nice progression from basic to advanced.

**Comment by SciutoAlex** [comment]
@workergnome would a Github repo with examples and introduction work best? That way people could add and update examples as they saw fit?

One more example. Axes are a big issue, clearly. And example methods for converting D3 axes into understandable functions for p5 users would be really useful. To that end, here's an [example](http://codepen.io/SciutoAlex/pen/OVjVdO) that takes a D3 axis object and produces two methods `drawTicks(tickText)` and `drawConnectingLine(startPos, endPos)`. The user can then add in p5 draw commands and the function will automatically align and draw them. The custom DOM functions are hidden from the user.
![screen shot 2015-06-14 at 3 38 53 pm](https://cloud.githubusercontent.com/assets/1485679/8150766/7b6cd9d0-12ab-11e5-94c7-c5cc1ab3a5ab.png)

**Comment by SciutoAlex** [comment]
Also, I saw this yesterday:
Lynn Cherny ‏@arnicas:
Incredibly tempted to teach p5 for vis - need those d3 scales and axes, though.
https://twitter.com/arnicas/status/609748277295206400

Interesting, practical use case for all this discussion.

**Comment by brysonian** [comment]
It's too bad d3 is written against smash. If it used a proper packaging system it would be possible to just pull in those functions and have at it.

**Comment by arnicas** [comment]
Nice thread - Mike is re-writing d3 as modules right now, to make them independently usable. He's doing scales soon, but they are dependent on other modules he's been working on first (color, etc). 

This will open up a lot of light-weight cross-pollination.  In general I agree with the cookbook approach from Scott, @SciutoAlex, @sepans  - don't make the 2 libs have to "talk to each other" in any fancy way.  We should be able to just use both together with a few good recipe examples for learners.  Seriously looking forward to this, both for teaching and personal use :)

**Comment by sepans** [comment]
@arnicas, @workergnome: I agree. any excessive coupling is against simplicity of p5/processing which is part of its core philosophy.

I also thought about a d3 build to be used as p5 addon but I don't know if it is going to help a lot except saving few kilobytes of exported lib file. I quickly went through the list of modules and except for 'SVG' and 'Behaviours' modules and Core.Selection and Core.Transition and a couple of other submodules, the rest are going to be usable in p5 without any fancy coding. (Even Selection and Transition is also usable in p5, though I think its a little bit too much of intermingling)

**Comment by kadamwhite** [comment]
Thanks so much for weighing in, @arnicas! That's exciting to learn about the d3 modularization, I hadn't known that was coming up.

**Comment by lmccart** [comment]
Not too much to add, just wanted to say this is super rad! A set of examples like this will be really helpful. I think a github repo is a great way to store, it would allow others to contribute other key examples as well.

**Comment by SciutoAlex** [comment]
So, I've never made a github repo that anyone other than me would use. That caveat said, Here's a repo for the p5/D3 cookbook. I added some of the examples in this thread, plus a few more.

https://github.com/SciutoAlex/p5-D3-cookbook

**Comment by workergnome** [comment]
This is freakin' fantastic, @SciutoAlex. Way to take a (poorly) lobbed ball and run with it.  As far as I'm concerned, the next step for this issue is to figure out how to mention this on the p5.js website somewhere.

Any suggestions I have for the examples, I can make on *your* repo.

**Comment by lmccart** [comment]
we don't have a well organized location for contributed examples atm, but i want to make sure people can find this one easily. what do we think about adding a link to it from the tutorials page? http://p5js.org/tutorials/

**Comment by workergnome** [comment]
I think that could be nice—I know that @SciutoAlex is working on making the github repo more example-like, so, if you don't mind, let's leave this open for a couple more days until he gets the redesign he's working on complete?

**Comment by SciutoAlex** [comment]
I'm working on adding a frontend to the repo that's more inviting that the github ui. I think a link to the cookbook homepage would be great. I'll update once I've pushed the changes.

**Comment by lmccart** [comment]
fantastic

**Comment by arnicas** [comment]
Alex, you saw Mike just released the module for d3 scales, right? Cries out for a recipe :)  If you don't get to it, I might play this weekend.

**Comment by SciutoAlex** [comment]
I just saw your tweet. I'm going to rewrite [this example](http://codepen.io/SciutoAlex/pen/warmoy) but for the module. When I get time!

**Comment by alignedleft** [comment]
@SciutoAlex Just jumping in here to say this is great. Totally agree that this may best live outside the official p5 docs, and can stand on its own.

**Comment by sarahgp** [comment]
@SciutoAlex & @sepans, this is great! I ended up using the voronoi example as a base to port the whole mouse interaction & it was super easy & fantastic. Thanks again!

Code is here, if you want to add it to the cookbook: https://github.com/sarahgp/p5-voronoi-background

**Comment by SciutoAlex** [comment]
Thanks @sarahgp! Added it in. Very cool. 

http://sciutoalex.github.io/p5-D3-cookbook/recipes-beginner/voronoi-interactive/

**Comment by sarahgp** [comment]
Awesome! I have two small PRs on that repo now @SciutoAlex.

**Comment by lmccart** [comment]
just cleaning up here, I think this one is pretty set, thanks for all the awesome examples and documentation!

**Comment by alignedleft** [comment]
FYI, D3 4.0 was released today. I just mention that in case it impacts any of the work done by others on this thread! See: https://github.com/d3/d3/releases/v4.0.0
