### ISSUE TITLE
createCapture flipped property in WEBGL

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js#7300]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [X] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Build process
- [ ] Unit testing
- [ ] Internationalization
- [ ] Friendly errors
- [ ] Other (specify if possible)

### p5.js version

1.10.0

### Web browser and version

129.0.6668.72 

### Operating system

Mac

### Steps:
1. Sketch 1 below, the video image is flipped correctly (default renderer)
2. Sketch 2 below, the video image is not flipped correctly (`WEBGL`)

### 2D working example:

```js
let video;

function setup() {
  createCanvas(640, 480);
  video = createCapture(VIDEO, { flipped: true });
  video.hide();
}

function draw() {
  image(video, 0, 0);
}
```

### WEBGL  not working example:

```js
let video;

function setup() {
  createCanvas(640, 480, WEBGL);
  video = createCapture(VIDEO, { flipped: true });
  video.hide();
}

function draw() {
  translate(-width / 2, -height / 2);
  image(video, 0, 0);
}
```

Example 1: left hand is on left

![image](https://github.com/user-attachments/assets/baa81156-0c23-44e8-91b7-ae629ae27d4b)

Example 2: left hand is on right

![image](https://github.com/user-attachments/assets/434257f3-e3e2-4c68-8017-6c3803f2b8c1)

This issue was filed by the IMA class "introduction to machine learning for the arts", thanks to the students who discovered this bug in their homework!!

**Comment by MuktiMishra** [comment]
Hi! I'd like to work on this issue. Could you please assign it to me?
