### ISSUE TITLE
On Firefox, the 1px line() does not align with the 1px line of the rect().

### ISSUE THREAD

**Issue by orbitalchicken** [processing/p5.js#7325]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [X] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build process
- [ ] Unit testing
- [ ] Internationalization
- [ ] Friendly errors
- [ ] Other (specify if possible)

### p5.js version

1.11.0

### Web browser and version

Firefox 131, Chrome 130

### Operating system

Windows and Linux

### Steps to reproduce this

```js
    p.background(255);
    p.noFill();
    p.stroke(0);
    p.strokeWeight(1);
    p.rect(150, 50, 150, 50);
    p.line(100, 50, 150, 50);
```

Firerox on the left, Chrome on the right:
![image](https://github.com/user-attachments/assets/7c454e30-7315-44aa-916f-361cef83a88f)
**On Firefox, the 1px line() does not align with the 1px line of the rect().**

**Comment by gaurav-mehta19** [comment]
would like to work on this please 
\assign

**Comment by orbitalchicken** [comment]
And if you translate(0.5, 0.5) before drawing the line and the rectangle, 
On Firefox, the line become "pixel perfect" (1px wide on a 100% 1K screen) and the rectangle stroke become 2px wide (not ok). 

See the section "**Obtaining crisp lines**" here: source: https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Applying_styles_and_colors

![2024-10-22_00-47](https://github.com/user-attachments/assets/b404928b-65bd-4415-b9d5-762c75ebd20b)

I think that all shapes, (eg. ellipses, triangles, etc) should be analysed and compared on both Chrome and Firefox.

**Comment by orbitalchicken** [comment]
@MuktiMishra Do you use a 4K monitor ? 
In this case it's probably normal that you are not going to "see" the problem.

Here's your code on a standard 1K monitor:

![firefox](https://github.com/user-attachments/assets/6b177e05-1c70-4dde-a4ff-9460010a304c)

![chrome](https://github.com/user-attachments/assets/b27aa136-0e9a-48f3-b873-b5c2d4557ed4)

**Comment by MuktiMishra** [comment]
> @MuktiMishra Do you use a 4K monitor ? In this case it's probably normal that you are not going to "see" the problem.
> 
> Here's your code on a standard 1K monitor:
> 
> Firefox: ![firefox](https://private-user-images.githubusercontent.com/9101553/379789683-6b177e05-1c70-4dde-a4ff-9460010a304c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NzcwNzYsIm5iZiI6MTcyOTc3Njc3NiwicGF0aCI6Ii85MTAxNTUzLzM3OTc4OTY4My02YjE3N2UwNS0xYzcwLTRkZGUtYTRmZi05NDYwMDEwYTMwNGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjRUMTMzMjU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjQzNzc0ODhkYzZmMGI5OTAwZjlkY2UwYTM2Y2NlYzljMDg3NmU0NTQ3NDBlOGU3YzcyZDQ3MWJhZGUzNzJhOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.71flb0lFdZX4iCyxxQsTqDbxtYA3ASfHs40KohEoZq8)
> 
> Chrome: ![chrome](https://private-user-images.githubusercontent.com/9101553/379789687-b27aa136-0e9a-48f3-b873-b5c2d4557ed4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NzcwNzYsIm5iZiI6MTcyOTc3Njc3NiwicGF0aCI6Ii85MTAxNTUzLzM3OTc4OTY4Ny1iMjdhYTEzNi0wZTlhLTQ4ZjMtYjg3My1iNWMyZDQ1NTdlZDQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjRUMTMzMjU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjQ2YmU0OGU3MWI3YTJmYWFhOTc2MmNhNTYxMDU4ZmRmNzkxM2FkZTM2M2QzMDFjZjBkZDI1OTI1NDI5NTIwMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.baEWMr8IXRZ9V6Z4Lm-42LSaaVa79nJGefM0v24-ToY)

@orbitalchicken my bad i didn't tried on high resolution monitor

**Comment by limzykenneth** [comment]
This is not a consistent issue.
On 4K monitor
Firefox (align fine):
![Screenshot 2024-10-24 at 18-33-31 p5 js Web Editor Substantial panama](https://github.com/user-attachments/assets/bafe8b24-34d9-4448-be0b-6a95dad96c34)


Chrome (does not align):
![download](https://github.com/user-attachments/assets/93b8b800-048d-440f-95be-2b41a4f3607e)

On 1440p monitor
Firefox (does not align):
![Screenshot 2024-10-24 at 18-34-16 p5 js Web Editor Substantial panama](https://github.com/user-attachments/assets/7ab003d7-b68c-4a48-9a6c-26b4bb8b9793)

Chrome (does not align):
![download (1)](https://github.com/user-attachments/assets/8bdb24d2-f8d0-4166-8b64-e23d697ede75)

As mentioned in #7317 and #7319, these are the behavior coming from the browsers not something we can fix (eg. you have replicated the same behavior using native canvas API). See also #4269 #5662 #5362 and others. This is a same behavior you'll see if you use the underlying [graphics engine](https://skia.org/) as [well](https://skia.org/docs/dev/design/raster_tragedy/). One way to get around it is to force subpixel drawing by drawing on a `.5` increment if alignment is important, we cannot do this by default as it has other unintended effects as well.

**Comment by limzykenneth** [comment]
Another explanation: https://web.archive.org/web/20200427185029/https://diveintohtml5.info/canvas.html (original site no longer up)

**Comment by GeorgVolkov** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by davepagurek** [comment]
I'm going to close this issue for now, as the variation between browsers in canvas rendering is generally something we don't try to fix in p5, asking individual browsers instead to fix bugs in their 2D canvas implementation. Feel free to keep commenting if there's anything we've missed!
