### ISSUE TITLE
Add sideWalls optional parameter to cylinder()

### ISSUE THREAD

**Issue by blackboxlogic** [processing/p5.js#7338]
### Increasing access

Allow users to render a circle efficiently when working in 3D.

### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Build process
- [ ] Unit testing
- [ ] Internationalization
- [ ] Friendly errors
- [ ] Other (specify if possible)

### Feature request details

cylinder() already has parameters `bottomCap` and `topCap`. But there's no way to just draw the cap(s). I'm suggesting adding another optional parameter `sideWalls` default to true, but when false doesn't draw the side walls of the cylinder.

**Comment by blackboxlogic** [comment]
I didn't see a way to use circle() in 3D space, with webGL. I want to change its xyz, rotate it in 3D, apply lighting etc

**Comment by davepagurek** [comment]
For all 3D shapes, you can call `translate(...)` or `rotate(...)` before your call to `circle()` to change the position and orientation of whatever you're drawing. I believe that should also include normals, so if you enable lighting and materials before drawing the circles, they should apply.

**Comment by blackboxlogic** [comment]
I assumed, read, or misunderstood that 2-D shapes couldn't be used in 3d space. I've verified that `circle()` does exactly what I want. Thank you.

**Comment by davepagurek** [comment]
ok nice! yeah, that's something that maybe could be made clearer in the docs or tutorials too.
