### ISSUE TITLE
fill() throws error with 2 number arguments

### ISSUE THREAD

**Issue by dhowe** [processing/p5.js#735]
To recreate, include the following line in an instance mode sketch:
````
    p.fill(0, 160); // Black with low opacity
````
Note: this may apply to other color functions as well, e.g., stroke(), etc

Error
------------------------------------------------------------------------
Uncaught Error: [object Arguments]is not a valid color representation.amdclean.color_p5Color.p5.Color._getFormattedColor @ p5.js:958amdclean.color_p5Color.p5.Color @ p5.js:605amdclean.color_creating_reading.p5.color @ p5.js:4049amdclean.core_p5Graphics2D.p5.Graphics2D.fill @ p5.js:1748amdclean.color_setting.p5.fill @ p5.js:4169p.setup @ sketch.js:388(anonymous function) @ p5.js:237amdclean.core_core.p5._preload.preloadCallback @ p5.js:221(anonymous function) @ p5.js:5495(anonymous function) @ p5.js:7812r.onload @ p5.js:7812

**Comment by kadamwhite** [comment]
Lovely. Will test with the pre-AMD-cleaned build tomorrow, and see if it's just a consequence of building the library...

**Comment by workergnome** [comment]
Just added a test for this—it looks like a real bug.  Looking into it...

**Comment by lee00678** [comment]
I'm still getting this error. could someone please look into this again? Thanks

**Comment by lmccart** [comment]
this seems to be working ok for me, which version of the library are you using?

**Comment by lee00678** [comment]
I'm sorry my mistake. It's something else in my code going wrong. But error message shows as above. It's working.
