### ISSUE TITLE
Adjust Option Orientation in CreateRadio() reference.

### ISSUE THREAD

**Issue by perminder-17** [processing/p5.js#7366]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [X] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build process
- [ ] Unit testing
- [ ] Internationalization
- [ ] Friendly errors
- [ ] Other (specify if possible)

### Steps:

1. Go to link : https://p5js.org/reference/p5/createRadio/
2. See the reference

In PR https://github.com/processing/p5.js/pull/7315 we noticed,

![image](https://github.com/user-attachments/assets/38358e83-6636-424b-9a27-e98a109204fd)

A proper alignment would be nice to have.

**Comment by devesh-2002** [comment]
Hi. May I take this issue?

**Comment by perminder-17** [comment]
> Hi. May I take this issue?

Sure, I'll assign you.

**Comment by Prajyot05** [comment]
@perminder-17  I have solved the issue, should I raise my PR?
Here's how it looks:
<img width="103" alt="Screenshot 2024-11-08 at 3 26 57 PM" src="https://github.com/user-attachments/assets/d8940980-96e7-4386-98b4-99416b10cbb6">

**Comment by devesh-2002** [comment]
Hi, you can take this issue if you have already worked on it.

**Comment by devesh-2002** [comment]
Hi @Prajyot05 , you can take this issue if you have already worked on it.

**Comment by Prajyot05** [comment]
@devesh-2002 alright, thanks
