### ISSUE TITLE
mouseButton on touch device gives 0 for first click (and for any long presses before the first click)

### ISSUE THREAD

**Issue by eyaler** [processing/p5.js#7397]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build process
- [ ] Unit testing
- [ ] Internationalization
- [ ] Friendly errors
- [ ] Other (specify if possible)

### p5.js version

1.11.1

### Web browser and version

firefox 133 android, chrome 131 android

### Operating system

android

### Steps to reproduce this

mouseButton on touch device gives 0 for first click (and for any long presses before the first click). only presses after that first click give 'left'.

### Steps:
1. run on a touch device
2. note that the first click shows mouseButton value to be 0
3. note that only on second click it changes to 'left'
4. rerun and now do long presses instead of clicks. note that the value is 0 until you do the second click

### Snippet:

```js

function setup() {
  createCanvas(100, 100)
}

function touchStarted() {
  background(200)
  text(mouseButton, 50, 50)
}

```

or run [this](https://editor.p5js.org/eyaler/sketches/yCvcoFYI7)

**Comment by eyaler** [comment]
@wayneharish10 thanks! Due to https://github.com/processing/p5.js/issues/7195 I cannot use mousePressed(). IIUC, it would only be called on release for short click and not at all for long press. I am actually calling mousePressed() my self from touchStart() to overcome that, and allow a unified interface.

**Comment by davepagurek** [comment]
This looks like something that might get resolved in p5 2.0 due to this change https://github.com/processing/p5.js/pull/7378 which handles both mouse and touch events using the browser's pointer API rather than trying to handle both separately.

**Comment by wayneharish10** [comment]
Thanks @davepagurek. Saw the changes made in #7378 myself and I think it'll do.

**Comment by davepagurek** [comment]
I'm going to close this now that #7378 is merged, thanks everyone!
