### ISSUE TITLE
Text Line Number function

### ISSUE THREAD

**Issue by emilepainchaud** [processing/p5.js#7401]
### Increasing access

I think that would make p5 more accessible for designers like me who are used to work with paragraphs containing multiple lines!

### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [X] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build process
- [ ] Unit testing
- [ ] Internationalization
- [ ] Friendly errors
- [ ] Other (specify if possible)

### Feature request details

Hi! I was trying to create a textbox width a rectangle that surrounds it. When my string is short, I can simply use the textWidth function to get the width, but my string is longer and has returns, it gets bit complicated to get both the width and the height of the text displayed on screen.

So I wrote this function to get the number of lines (so that I can use that number to multiply the height for one line of text by the number of lines so I have my nice rectangle surrounding my textbox) :

`function getLineNb(txt, maxWidth) {
  let totalWidth = 0;
  let lineNb = 1;
  for (let i = 0; i < txt.length; i++) {
    totalWidth = totalWidth + textWidth(txt[i]);
    if (totalWidth >= maxWidth || txt[i] === "\n") {
      lineNb = lineNb + 1;
      totalWidth = textWidth(txt[i]);
    }
  }
  return lineNb;
}`

It doesn't output the right number when the maxWidth is very small though, so it should be reworked.

Maybe this could be a new feature inside P5!

**Comment by Deathnote45** [comment]
Hi, Can I contribute on this issue??

**Comment by dhowe** [comment]
Can you provide an example sketch of what you are hoping to do, so we can see  the functionality ? thanks

**Comment by Deathnote45** [comment]
> Can you provide an example sketch of what you are hoping to do, so we can see the functionality ? thanks

should I explain it here?

**Comment by emilepainchaud** [comment]
Sure! Here is an example on the function in context : https://editor.p5js.org/emilepainchaud.qc.ca/sketches/IeskHCGtd

**Comment by dhowe** [comment]
Just to be clear, you are talking about multiline text in general, or specifically on DOM elements like buttons and textareas ?

**Comment by davepagurek** [comment]
For what it's worth, I've been copy and pasting around this snippet to add `\n`s into a string where text would wrap at a given width. Possibly a little more versatile than just getting the number of lines? https://gist.github.com/davepagurek/c9cfd12f91c571e86c5c1b9ed091a2d9

**Comment by dhowe** [comment]
FYI, explicit new lines are in the API for v2.0

**Comment by dhowe** [comment]
To summarise the use-case here is for an API function that returns the height of a multiline text block (also the number of lines?), without drawing it.

In v2.0 the `textBounds()` function will give the width and height of a multiline string. Similarly `fontBounds()` will give the max bounds for the font (ignoring whether the string contains ascenders and descenders). The latter plus a bit of division by the leading would give the number of lines. 

Let me know if anything else is needed
