### ISSUE TITLE
Deprecated noSmooth()

### ISSUE THREAD

**Issue by chrsmlls333** [processing/p5.js#741]
This warning appears in Chrome Javascript Console as a warning. Noticed that the src doesn't use the suggested function. Warning might be unavoidable as we maintain support for older platforms but the new function should be added.

```
'CanvasRenderingContext2D.webkitImageSmoothingEnabled' is deprecated. Please use 'CanvasRenderingContext2D.imageSmoothingEnabled' instead.
```

**Comment by workergnome** [comment]
Thanks!  We should look into a check to use the non-prefixed function if available.

**Comment by workergnome** [comment]
See #588 for previous discussion—this will need a check for safari/chrome, for sure.
