### ISSUE TITLE
find a webgl rendering edge with cap problem.

### ISSUE THREAD

**Issue by mahaidong** [processing/p5.js#7412]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Build process
- [ ] Unit testing
- [ ] Internationalization
- [ ] Friendly errors
- [ ] Other (specify if possible)

### p5.js version

1.19

### Steps:
https://editor.p5js.org/mahaidong/sketches/5YL2WBTu7

### Snippet:

```js
      const prevColor = (this.vertexStrokeColors.length > 0 && prevEdge)
        ? this.vertexStrokeColors.slice(
          prevEdge[1] * 4,
          (prevEdge[1] + 1) * 4
        )
        : [0, 0, 0, 0];

// we need  prevColor for prevEdge
            this._addJoin(
              this.vertices[prevEdge[1]],
              lastValidDir,
              existingCap.dir.copy().mult(-1),
              prevColor
            );
```

**Comment by davepagurek** [comment]
Fixed by #7413
