### ISSUE TITLE
Add support for drawing shadows like in q5.js

### ISSUE THREAD

**Issue by mvicky2592** [processing/p5.js#7418]
### Increasing access

Unsure

### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [X] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build process
- [ ] Unit testing
- [ ] Internationalization
- [ ] Friendly errors
- [ ] Other (specify if possible)

### Feature request details

hello!

I just saw that functions for drawing shadows were added to q5.js last week

https://q5js.org/learn/#shadow

I'm wondering will these will be added to p5.js as well?

**Comment by ksen0** [comment]
Hi @mvicky2592!

I’ll close this one for now, as I see there is already another ongoing discussion related to blur support in p5.js: https://github.com/processing/p5.js/issues/4619 

Although feature proposals are welcome, it’s important that in the future they explain how the proposed feature enhancement will help p5.js [increase access](https://p5js.org/contribute/access/) for people historically marginalized in the field of creative arts or technology.
