### ISSUE TITLE
[p5.js 2.0 RFC Proposal]: Be fully compatible with popular tools as Vite and Vercel

### ISSUE THREAD

**Issue by ejgutierrez74** [processing/p5.js#7423]
### Increasing access

By now is a headache to get to work p5.js libraries in Vite, and when i got to work in Vite, then it doesnt work in Vercel...
So would be nice that same tutorial or examples would work in local vite, and Vercel.

Thanks

### Which types of changes would be made?

- [ ] Breaking change (Add-on libraries or sketches will work differently even if their code stays the same.)
- [ ] Systemic change (Many features or contributor workflows will be affected.)
- [ ] Overdue change (Modifications will be made that have been desirable for a long time.)
- [X] Unsure (The community can help to determine the type of change.)

### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [X] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [X] Build process
- [ ] Unit testing
- [ ] Internationalization
- [ ] Friendly errors
- [ ] Other (specify if possible)

### What's the problem?

Make p5.js work in Vite and Vercel is a headache

### What's the solution?

One way of working and writing code, fully compatible with Vite and Vercel

### Pros (updated based on community comments)

- Using standard of industry tools like vite, vercel

### Cons (updated based on community comments)

None so far

### Proposal status

Under review

**Comment by limzykenneth** [comment]
@ejgutierrez74 This is already in the works and mostly done with https://github.com/processing/p5.js/issues/7013
