### ISSUE TITLE
`erase()` is broken for versions past `1.9.0`

### ISSUE THREAD

**Issue by RandomGamingDev** [processing/p5.js#7442]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [X] Color
- [X] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Build process
- [ ] Unit testing
- [ ] Internationalization
- [ ] Friendly errors
- [ ] Other (specify if possible)

### p5.js version

1.9.1+

### Web browser and version

Firefox 133.0.3 & Chromium 131.0.6778.85

### Operating system

Debian 12

### Steps:
1. Draw something to a framebuffer
2. Erase something from the frame buffer by drawing a shape using `erase()`
3. Draw the frame buffer to the canvas and watch as the parts of the frame buffer meant to still have colors get turned transparent through the canvas and the transparent area including the part that was meant to be erased turn into the background color of the canvas.

### Snippet:

```js
let b;
function setup() {
  createCanvas(400, 400, WEBGL);
  b = createFramebuffer();
}

function draw() {
  background(0);
  
  b.begin()
  {
    fill(255,0,0)
    noStroke()
    rect(-100,-100,200,200)

    erase()       // This is Erasing the Main Canvas, rather than the framebuffer
    circle(0,0,100)
    noErase()
  }
  b.end()
  
  image(b,-200,-200)
}
```

Related to issue #6523 where `erase()` wouldn't work at all. It was originally fixed, but in versions past `1.9.0` it's now broken in the way described above instead of no longer functioning.

**Comment by davepagurek** [comment]
Just merged in https://github.com/processing/p5.js/pull/7443, this should be good in 2.0 now!
