### ISSUE TITLE
Friendly Error Messaging should show sketch line number

### ISSUE THREAD

**Issue by dhowe** [processing/p5.js#750]
rather than compiled p5.js (or p5.min.js) line number, or at least show stacktrace

![screen shot 2015-06-15 at 2 42 44 pm](https://cloud.githubusercontent.com/assets/737638/8154481/3f97346a-136d-11e5-8396-ca17c4edc9dc.png)

**Comment by crhallberg** [comment]
I was unable to find a cross-browser way to get the stacktrace. My plan is to detect if [stacktrace.js](http://www.stacktracejs.com/) is available and use that. So if a user needs a little more help they can include it.

It may be light enough to package with p5.js and leave out of p5.min.js.

**Comment by lmccart** [comment]
aggregate into https://github.com/processing/p5.js/issues/971
