### ISSUE TITLE
p5.Element.mouseDragged

### ISSUE THREAD

**Issue by debone** [processing/p5.js#752]
Hello,
I started with this example of [mouseDragged](http://p5js.org/reference/#/p5/mouseDragged), tried to attach it to a `p5.Element` and I found out that there is no `p5.Element.mouseDragged` defined.
Am I missing something?

**Comment by lmccart** [comment]
`mouseDragged()` is not intended to be attached to an p5.Element, it is a global method that is fired anytime the mouse is dragged on the page. if you want to include element specific listeners, you can add the p5.DOM library. I don't think there is a `mouseDragged()` method though.

**Comment by debone** [comment]
Sorry, my intention was not to use the global method. My first thought was equality between global and p5.Element events, that's why I created the issue.
You mentioned p5.DOM but I think all mouse and touch events are created on p5.js and not on p5.DOM, [here](https://github.com/processing/p5.js/blob/master/lib/p5.js#L1003-L1101).

 I will use the `p5.Element.attachListener` instead, thanks for the answer!
