### ISSUE TITLE
arc() does not work with createGraphics()

### ISSUE THREAD

**Issue by ccheaton** [processing/p5.js#753]
If you try to draw using `arc()` to an off-screen graphic buffer, instantiated with `createGraphics()`, it fails to draw and throws an error "TypeError: Cannot read property 'forEach' of undefined," on line 1896 of p5.js. 

Example code (modified from the code on the [`createGraphics()`](http://p5js.org/reference/#/p5/createGraphics) reference page:

```
var pg;
function setup() {
  createCanvas(100, 100);
  pg = createGraphics(100, 100);
  angleMode(DEGREES);
}
function draw() {
  background(200);
  pg.background(100);
  pg.noStroke();
  pg.arc(0,0, 50, 50,0,-90);
  image(pg, 50, 50);
  image(pg, 0, 0, 50, 50);
}
```

**Comment by joecridge** [comment]
I'm working on the arc implementation at the moment so I'll take a look at this as well.

**Comment by ccheaton** [comment]
Awesome, thanks! I recently made a sketch that is based entirely on arcs, if it would help you test. The [code is here](https://github.com/ccheaton/p5js_sketches/blob/master/golden/sketch.js) with the arc drawing on [line 318](https://github.com/ccheaton/p5js_sketches/blob/master/golden/sketch.js#L318). They're drawn recursively and you can set the number on [line 21](https://github.com/ccheaton/p5js_sketches/blob/master/golden/sketch.js#L21). [Here it is running](http://ccheaton.github.io/static/pages/golden.html).
