### ISSUE TITLE
Sending a p5.Graphics object into image() spams the console with warnings, reducing performance

### ISSUE THREAD

**Issue by ccheaton** [processing/p5.js#755]
If you run the [`createGraphics()` example](http://p5js.org/reference/#/p5/createGraphics) code locally and open your Chrome developer tools, you'll see the following repeated many times:

> p5.js says: image was expecting a p5.image for parameter #1, received [object Object] instead. image takes different numbers of parameters depending on what you want to do. Click this link to learn more: [http://p5js.org/reference/#p5/image]

![screen shot 2015-06-16 at 9 38 24 pm](https://cloud.githubusercontent.com/assets/205364/8198114/170a6590-1470-11e5-9c6a-28cc26834819.png)

This causes serious performance issues on my computer, spinning up the fan, etc...

The code I used to reproduce it is:

```javascript
var pg;
function setup() {
  createCanvas(100, 100);
  pg = createGraphics(100, 100);
}
function draw() {
  background(200);
  pg.background(100);
  pg.ellipse(pg.width/2, pg.height/2, 50, 50);
  image(pg, 50, 50);
  image(pg, 0, 0, 50, 50);
}
```

**Comment by lmccart** [comment]
looks like we are missing support for p5.Graphics arg in the validateArguments check, it should be something more like this.

```
    this._validateParameters('image', arguments, [
      [
        'p5.Graphics',
        'Number',
        'Number'
      ],
      [
        'p5.Image',
        'Number',
        'Number',
        'Number',
        'Number'
      ],
      [
        'p5.Graphics',
        'Number',
        'Number'
      ],
      [
        'p5.Graphics',
        'Number',
        'Number',
        'Number',
        'Number'
      ]
    ]);
```

however, this still create the warning unless the p5.Image block is removed completely.

@crhallberg any thoughts on what might need to change about the validateArguments function?

**Comment by lmccart** [comment]
@ccheaton in the meantime, you can use p5.min.js file which doesn't have this error checking.

**Comment by ccheaton** [comment]
@lmccart Thanks. I've been trying to stick with the unminified version to familiarize myself with the codebase, in hopes of contributing in the future. I'll stick with p5.min.js for anything meant for production.
