### ISSUE TITLE
request for comments: graphics resizing and defaults in 2d and 3d modes

### ISSUE THREAD

**Issue by indefinit** [processing/p5.js#757]
(loosely related to issues #753  and #754 )

I'm tweaking the default graphics context flow a bit in order to fix a bug we discovered in the 3D context rendering. The bug:  The Graphics.resize method is getting called after Graphics3D context is instantiated and therefore gl context is not receiving override width and height values. 

Before I submit a PR, I was wondering if I could get a gut check on the use cases for functions
```createGraphics``` as well as ```createCanvas```, as it may affect the simplification of this code.

My understanding is that we prefer the user call ```createCanvas(width,height, renderer)``` **once** per pInstance in ```setup()```, and doing so will create a default canvas / graphics context. 

```createGraphics```, however, can be used multiple times in ```setup()```, and is independent of a default canvas instance.  It will create either a 2d or 3d rendering context, using the canvas2D, webgl, or SVG(?) apis.  The benefits of createGraphics in this case would be that the user can choose whether this context is an off screen render or on-screen (ie. "painted onto the canvas").  Am I missing other important use cases?

**Comment by lmccart** [comment]
that all sounds right to me

**Comment by indefinit** [comment]
Ok cool.  Are there any potential use cases where someone would want to draw in both Graphics2D and Graphics3D in the same pInst?

**Comment by lmccart** [comment]
The only thing I could think of would be creating some sort of texture in graphics2d and applying it to something in graphics3d?

**Comment by shiffman** [comment]
This also sounds right on to me.  I would say that one of the things I like about Processing's renderers is the ability for users to mix 2D and 3D ideas without really feeling like they are doing anything weird or different.   This isn't to say that more than one renderer is needed per "sketch" (it isn't), but to keep the feeling that not much has changed in terms of code/API from one renderer to the other.  I know we've discussed this before . . . .

I have seen use cases in Processing where users use a 2D offscreen context as a texture with a 3D renderer, i.e. `createGraphics()` 2D and `createCanvas()` 3D.  The inverse is more rare, but also does come up from time to time.  So would be nice to support that as you say.

**Comment by indefinit** [comment]
Ok, good to know.  Thanks for the comments!

**Comment by lmccart** [comment]
closing this because it looks like we're set here? please reopen if i'm mistaken!
