### ISSUE TITLE
p5.js website - Internationalization

### ISSUE THREAD

**Issue by mayaman26** [processing/p5.js#762]
Hi all,

I am working on rebuilding the p5.js website using Node this summer & am currently focusing on Internationalization (i18n) using Handlbars & yml files. I am having trouble finding a way to change the value of the language key when a button is clicked (change the value of the yml front matter to "en" or "es"). If I hardcode it, the translation works great, but I want this to be an automatic process when the user clicks a button. If anyone has any suggestions on this or another method of internationalization, I would really appreciate your input! The github repo is linked below.

https://github.com/mayaman26/p5js-website

Thanks!

**Comment by futuremarc** [comment]
Are the buttons making POST requests?

**Comment by mayaman26** [comment]
Not as I have it now. I just updated it so that I have the buttons changing a variable 'language' from "es" to "en". That variable is used to choose which yml file the data is pulled from. I know the variable value is changing from the console, but the actual element on the page is not changing with it as it should be. It works when I make a change then restart the server, so maybe it has to completely restart to register the change in the handlebar helper function?
