### ISSUE TITLE
canvas doesn't appear, stuck with a message "loading..."

### ISSUE THREAD

**Issue by kindlychung** [processing/p5.js#763]
Code the "beyond canvas" tutorial seems to cause trouble:

    var canvas;

    function setup() {
        // We are still calling createCanvas like in the past, but now 
        // we are storing the result as a variable. This way we can 
        // call methods of the element, to set the position for instance.
        canvas = createCanvas(600, 400);

        // Here we call methods of each element to set the position 
        // and id, try changing these values.
        // Use the inspector to look at the HTML generated from this 
        // code when you load the sketch in your browser.
        canvas.position(300, 50);
        canvas.class("lemon");
    }

    function draw() {
        // These commands are applied to the graphics canvas as normal.
        background(220, 180, 200);
        ellipse(width/2, height/2, 100, 100);
        ellipse(width/4, height/2, 50, 50);
    }

If I comment out the "canvas.position..." line, then things work fine.

OS X 10.10, google chrome 43

**Comment by shiffman** [comment]
This will all change as #645 is implemented, but you just need to make sure you have `p5.dom` included in your imports, i.e.

```
<script language="javascript" src="p5.dom.js">
```

Being stuck on "loading. . . " often means there's an error and you can check the JS console for more.
