### ISSUE TITLE
Several textAlign problems

### ISSUE THREAD

**Issue by pepeberba** [processing/p5.js#765]
I followed the same example found in https://www.processing.org/reference/textAlign_.html which has the following output in Processing.
![image](https://cloud.githubusercontent.com/assets/6505743/8304118/fda0f40a-19d5-11e5-846e-862e60e2694b.png)

function draw(){
	background(0);
	stroke(153);
	textSize(11);
	textAlign(CENTER, BOTTOM);
	line(0, 30, width, 30);
	text("CENTER,BOTTOM", 50, 30);
	textAlign(CENTER, CENTER);
	line(0, 50, width, 50);
	text("CENTER,CENTER", 50, 50);
	textAlign(CENTER, TOP);
	line(0, 70, width, 70);
	text("CENTER,TOP", 50, 70);
}

which in p5 produces 
![image](https://cloud.githubusercontent.com/assets/6505743/8304103/e157d71e-19d5-11e5-82b1-37ce6989a4c7.png)

**Comment by pepeberba** [comment]
Alignment also doesn't work when the text wraps within the text box. For (RIGHT and CENTER)

s = "The quick brown fox jumped over the lazy dog.";
textAlign(CENTER);
fill(50);
text(s, 10, 10, 70, 80); // Text wraps within text box

![image](https://cloud.githubusercontent.com/assets/6505743/8304408/156e5f6c-19d8-11e5-89e2-2fb08481ac49.png)

**Comment by dhowe** [comment]
Question: do you get the same results when using an opentype font?

```javascript
    var font;
    function preload()
    {
        font = loadFont("fonts/SourceSansPro.otf");
    }

    function setup()
    {
        createCanvas(600, 400);
        textFont(font);
        ...
    }

**Comment by pepeberba** [comment]
Sorry my bad. I was using https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.4.5/p5.js (which doesn't have loadFont()) , but when using the latest lib/p5.js it works fine.

**Comment by lmccart** [comment]
sorry about that, working on packaging a new release today!
