### ISSUE TITLE
text() does not follow rectMode()

### ISSUE THREAD

**Issue by pepeberba** [processing/p5.js#766]
The rectangle that the text box uses in text() always uses CORNER, even if rectMode is set to CENTER.

**Comment by dhowe** [comment]
This is not fully clear to me -- do you have some test code I can try with?

**Comment by pepeberba** [comment]
rectMode(CENTER);
s = "The quick brown fox jumped over the lazy dog.";
fill(50);
text(s, 10, 10, 70, 80); // Text wraps within text box

rectMode(CORNER);
s = "The quick brown fox jumped over the lazy dog.";
fill(50);
text(s, 10, 10, 70, 80); // Text wraps within text box

Generated using p5.js
![image](https://cloud.githubusercontent.com/assets/6505743/8313131/6e16b764-1a13-11e5-9f8e-b39370992664.png)

Generated using Processing
![image](https://cloud.githubusercontent.com/assets/6505743/8313162/a5e700fe-1a13-11e5-995f-7c2f110799c7.png)

**Comment by dhowe** [comment]
Great, thanks. And is this also the case with opentype fonts, as well as system fonts?

**Comment by pepeberba** [comment]
Unlike my problem with #765, it seems that it doesn't work for both opentype fonts as well as system fonts, even with the latest lib/p5.js

**Comment by dhowe** [comment]
@xyfeng do you want to take a look at this, as maestro of textual alignment?

**Comment by xyfeng** [comment]
@dhowe @pepeberba I submitted a fix ;)

**Comment by lmccart** [comment]
closed with https://github.com/processing/p5.js/pull/772
