### ISSUE TITLE
Running the tests now print friendly debugging statements

### ISSUE THREAD

**Issue by workergnome** [processing/p5.js#773]
Everytime I run the test suite, I get

```
%c> p5.js says: Welcome! This is your friendly debugger. To turn me off switch to using “p5.min.js”. background-color:transparent;color:#ED225D; background-color:#ED225D;color:white;
%c> p5.js says: It looks like there was a problem loading your image. Try checking if the file path%c [file:///Users/david/Documents/opensource/p5.js/test/invalid%20path] %cis correct, hosting the image online, or running a local server.%c[https://github.com/processing/p5.js/wiki/Local-server] background-color:#C83C00;color:#FFF; background-color:transparent;color:#C83C00; background-color:#C83C00;color:#FFF; background-color:transparent;color:#C83C00;
``

in my console.  We should probably test for their presence, but not print them to the console.

**Comment by lmccart** [comment]
this isn't actually testing friendly errors, it's testing a different function (loadJSON I think). the method is supposed to fail to pass the test. i'm not sure why we're seeing the friendly errors here. I switched test.html to use p5.min.js but this doesn't seem to remove the errors, though using the min version normally does. anyone have thoughts about what could be happening here? I don't actually know how the checking between p5.js vs p5.min.js works and how the friendly errors are removed in the min case, can anyone explain?

**Comment by workergnome** [comment]
To remove this from the .min, we're appending blank functions to the end of the .min file As part of the grunt process.

https://github.com/processing/p5.js/blob/master/Gruntfile.js#L298-L299

I will look into why we're seeing these errors later today, but I think for those errors we need to wrap them in a lambda and check for the console message as part of the error handling.  (late for a bus—can't be more clear!)

**Comment by kadamwhite** [comment]
Taking a look at this now. The stub-out-in-minified approach will miss cases where p5 is consumed as a module, vs a global; I am investigating alternative solutions.
