### ISSUE TITLE
event naming - onDeviceMove(), onDeviceTurn()

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js#777]
This is a very nitpicky comment and I'm not sure exactly of its appropriateness of a thread here, but as I was looking through some stuff I noticed the (awesome) new mobile work from #557.  The Processing convention has always been to keep function names to two words if possible.  And mouse events we have are `mousePressed()`, `mouseMove()`, etc. instead of `onMousePressed()`, `onMouseMove()`.  So I wonder if it might be cleaner / more consistent to change these to:

```
function deviceMove() {

}

function deviceTurn() {

}
```

This may also apply to some new DOM events that @futuremarc and I have been discussing for `<input>` elements.

**Comment by lmccart** [comment]
i agree this makes sense. however i think it should be deviceMoved and deviceTurned to match keyPressed and mouseMoved etc.

**Comment by lmccart** [comment]
pinging @OhJia

**Comment by OhJia** [comment]
@lmccart @shiffman I changed the names to deviceMoved() and deviceTurned() in acceleration.js. I'll send PR in a bit.

**Comment by lmccart** [comment]
closed with #796
