### ISSUE TITLE
eval alternative help? (working on preload)

### ISSUE THREAD

**Issue by lmccart** [processing/p5.js#779]
Ok, here goes, apologies this may be impossible to follow. I realize this would be better to ask someone in person, but I didn't have anyone around to ask. It might be a better question for stackoverflow, but I am also looking for input more generally about strategy around `preload()`. (Related to #668 and #738.)

The short and general version is just a JS question... if you can do this:
```javascript
var myObj = {
  myMethod: function() { // do stuff; }
}
var methodName = 'myMethod';
myObj[methodName]();
```

what is the right way to do something like this?
```javascript
var myObj = {
  myMethod: function() { // do stuff; }
}
var objectName = 'myObj';
[objectName].myMethod();
```

Specifically, I'm trying to change the way that `preload` works. Right now there are a list of p5 functions that will cause the program to wait to go on to `setup` until they have returned. These methods are stored in an array like this (https://github.com/processing/p5.js/blob/master/src/core/core.js#L486):
```javascript
  p5.prototype._preloadMethods = [
    'loadJSON',
    'loadImage',
    'loadStrings',
    'loadXML',
    'loadShape',
    'loadTable',
    'loadFont',
  };
```

If you'd like to add a function to this list from an addon library, you can use the `registerPreloadMethod`, which adds it to the array (https://github.com/processing/p5.js/blob/master/src/core/core.js#L498):
```javascript
  p5.prototype.registerPreloadMethod = function(f) {
    p5.prototype._preloadMethods.push(f)
  };
```

Then there is a line that calls the function as a method of the p5 object (https://github.com/processing/p5.js/blob/master/src/core/core.js#L259): 
```javascript
    this._preload = function (func, args) {
      // stuff
      return return p5.prototype[func].apply(context, args);
    }
```

However, this assumes that all of the preload functions are methods of the p5 object. In some cases with libraries, it would be useful to add a function that is not a method of the p5 object, and to specify the object instead. So I began attempting to store this object as a string.

```javascript
  p5.prototype._preloadMethods = {
    'loadJSON': 'p5',
    'loadImage': 'p5',
    'loadStrings': 'p5',
    'loadXML': 'p5',
    'loadShape': 'p5',
    'loadTable': 'p5',
    'loadFont': 'p5'
  };

  p5.prototype.registerPreloadMethod = function(f, o) {
    if (!p5.prototype._preloadMethods.hasOwnProperty(f)) {
      p5.prototype._preloadMethods[f] = o;
    }
  };
```

When it came to calling the preload object, I changed that [line](https://github.com/processing/p5.js/blob/master/src/core/core.js#L259) to something like this:
```javascript
    this._preload = function (func, obj, args) {
      // stuff
      var f_obj;
      eval('f_obj = '+obj);
      return f_obj.prototype[func].apply(context, args);
    }
```

Which did work. However, I know that `eval()` is probably not a good idea, and the linter complains. So, I am wondering what a better solution would be? Would it be better to just switch to using promises to handle preload?

**Comment by shiffman** [comment]
I am absolutely the least qualified to answer this, but looking at this part of your post:

```javascript
var myObj = {
  myMethod: function() { // do stuff; }
}
var objectName = 'myObj';
[objectName].myMethod(); 
```

That last line will work as follows:

```javascript
window[objectName].myMethod();
```

Though technically I think this would be better in terms of scope?

```javascript
this[objectName].myMethod();
```

Does this help?

**Comment by lmccart** [comment]
ahh yes! thank you!
