### ISSUE TITLE
Integrate OpenType into built library?

### ISSUE THREAD

**Issue by kadamwhite** [processing/p5.js#781]
@dhowe Back in May we looked at issues relating to AMDClean and OpenType that required us to concatenate the files vs including opentype directly. I'd like to understand better how we're using OpenType within p5, so that (in our new, post-#776 browserify world) we can return to this issue and better integrate the two if appropriate.

**Comment by dhowe** [comment]
So we're using opentype to load and parse .ttf and .otf fonts, and to access metrics and path/curve data for these. The intention of the temporary pre-#776 grunt fix was to avoid needing a 2nd "src" tag in the browser html.

**Comment by kadamwhite** [comment]
@dhowe Would you be able to take a look at this, or talk me through where we use opentype so that I could take a swing at it?

We could also conceivably switch to declaring opentype.js as an NPM dependency, rather than maintaining the externals directory, as we do with reqwest.

**Comment by dhowe** [comment]
Well, we use the library throughout the typography module (I can list the files if that's useful). But an NPM dependency makes sense to me, especially if we're already doing that for reqwest: https://www.npmjs.com/package/opentype.js.

**Comment by kadamwhite** [comment]
This may be blocking #818 since it means we end up with two UMD definitions in one file. I'm putting together a PR to require opentype into the constructed bundle. This would mean opentype would no longer be a global, however, so it could only be used by an end user via p5's interface (`loadFont` etc)—this seems fine to me, but I thought I'd raise it just in case.

**Comment by dhowe** [comment]
I'm assuming you mean any exposed functions in the library (for example, we now expose p5.Font.textBounds(), which is not actually part of the official p5 API (or p5's direct interface). If so, then this seems fine to me as well.

**Comment by kadamwhite** [comment]
I think we're discussing the same thing, but as I'm less familiar with the font module I'm not 100%. Do you have some tests that you could do or recommend I do to verify things are copacetic?

**Comment by dhowe** [comment]
Maybe a bit of a larger task, but something I've done in the past is to check access to the entire API as part of a test set; so there might be a JSON file with a list of objects and the functions/variables/constants they expose, and the test can simply check each is defined and has the correct type (you might also test that private elements are *not* visible). The idea being that you can do devops-type refactoring more safely, but it can also be useful for documentation (we may already have something like this for use in the web reference...)

**Comment by dhowe** [comment]
Note that I am now getting a new exception in the the previously existing unit tests for p5.loadFont(). The fact that the test is still passing is a different problem that I will look at...

![screen shot 2015-07-27 at 1 52 23 pm](https://cloud.githubusercontent.com/assets/737638/8899639/90e5b39c-3469-11e5-9160-0f3e5e88558c.png)
