### ISSUE TITLE
Properly stub out methods in minified files

### ISSUE THREAD

**Issue by kadamwhite** [processing/p5.js#785]
We attempt to suppress two methods, `_friendlyFileLoadError` and `_validateParameters`, when we build the minified file. The manner in which we're stubbing these methods doesn't actually have an effect in some circumstances, specifically when we require P5 via AMD or CommonJS require calls, vs depending on it as a global.

One option is to move these methods to their own module, then have browserify create two builds, one for the unminified source that works as-is and another that stubs out these modules, and only minify the latter build. This way they'll be properly disabled no matter how p5 is called, and may save us a byte or two in the process.

**Comment by lmccart** [comment]
addressed with https://github.com/processing/p5.js/pull/2302
