### ISSUE TITLE
p5 website rebuild to support i18n

### ISSUE THREAD

**Issue by mayaman** [processing/p5.js#793]
I have the beginnings of the new p5.js website built using Node up and running here: https://github.com/mayaman26/p5js-website

Currently, there are buttons at the top of the page to navigate between an english and spanish version. Eventually, the idea is that all of the text on the site will be stored in yml (a more readable alternative to json) files and be accessed using a handlebar helper and key corresponding to the string stored in the data file. 

If you have any suggestions/comments/questions about the internationalization method/site in general please let me know or feel free to contribute!

**Comment by lmccart** [comment]
closing this as it's not directly related to p5.js library, but @mayaman has made great progress on this this summer and you can follow in the link above. stay tuned this fall for a documentation drive focused on translation and internationalization in preparation for i18n website rollout later this year!
