### ISSUE TITLE
Additional DOM interface elements

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js#794]
I've been working on some quick and dirty sketches recently that make use of additional DOM elements not wrapped specifically for p5.js.  This falls into the category of "How much DOM stuff do we support and when should we send someone somewhere else?"  At the moment, I think some additional code to wrap additional interface/form elements (checkbox, dropdown, radio button) might be useful.

Here's a sketch that demonstrates something I imagine teaching:

http://shiffman.net/p5/p5js/input/

The raw guts of this using p5.js and native JS is here:

https://github.com/shiffman/shiffman.github.io/blob/master/p5/p5js/input/js/sketch.js

Some ideas for how this could be wrapped (if we decide to do so) in p5.js here:

https://gist.github.com/shiffman/7549e5225c042ee25a80

This issue is intended to start a discussion with @futuremarc as part of his GSoC work.  We may ultimately discuss more offline but I'd love for anyone who would like a chance to weigh in to feel free.

Thanks!

**Comment by brysonian** [comment]
I think having more form elements would be handy. I wonder though if the ideas you sketch are too specific? For example, checkboxes can have a value beyond just checked or not (imagine a "select colors you like" list of options). Perhaps for input elements there could be a `value()` method that returns the value for the input? In the case of a select this would be the value of the option that is chosen, in the case of a checkbox the value of the checked item. One odd case would be a select box with multiple selection enabled, and a checkbox that is part of a set of boxes all of whom have the same name. Perhaps just return an array of all selected values in that case, with a documentation note about that.

**Comment by futuremarc** [comment]
@shiffman Right. I like your gist examples a lot. 

@brysonian p5 elements already have `value()`, which returns its value which is useful for say the slider element.

**Comment by dhowe** [comment]
A drop-down list would certainly be useful ... Also a way to set properties on the elements (width, height, font-size, etc.) on the existing input object

**Comment by futuremarc** [comment]
I've been working on these and related; will be done soon!

**Comment by dhowe** [comment]
:+1:

**Comment by benrigby007** [comment]
Plus plus to being able to set properties on elements. 

I've been playing a lot with the slider recently - and would find it very useful to be able to easily adjust the thumb style, track style, tickmarks (on/off), range, tooltips, easing. Would save extensive fiddling with the CSS (or using an external library). Ie: to get to something more like this: http://refreshless.com/nouislider/examples/.

**Comment by oolong** [comment]
Can I ask what's the status of this at the moment? The DOM library seems to include createSelect already, but although it's listed, it's not really documented - it was only by digging and finding this thread that I discovered there was a way to add options without writing my own addOption function! And while the option method seems to work, it looks like select doesn't...?

**Comment by shiffman** [comment]
@oolong, I'm about to file a couple new issues and @lmccart and @futuremarc are planning to meet this week to discuss p5.dom so more work will be happening soon!

**Comment by lmccart** [comment]
continuing the discussion now in #932.
