### ISSUE TITLE
set() doesn't work with zoomed canvas

### ISSUE THREAD

**Issue by molleindustria** [processing/p5.js#798]
Easy to reproduce. Go here:
http://p5js.org/reference/#/p5/set
The examples don't work if the canvas is created when the zoom is different than 100%, 200% 300% etc.

You can test it by zooming the browser in or out with control +/- or view > zoom > zoom in, and refreshing the page (I don't know about you but I constantly adjust the zoom).

It looks like the imageData array is populated correctly but when it gets to the pixel update here:
https://github.com/processing/p5.js/blob/dbef89fdaa6c94648c534b4a0e869b63611e63c9/src/core/p5.Renderer2D.js#L320

if the zoom is not a multiple of 100% the pixel density is going to be a floating point number (e.g. 2.5 for a 250% zoom) and when you try to access an array with floats (e.g. ctx.pixels[2.5]) javascript doesn't simply round or truncate because apparently all arrays are objects and indexes are treated like strings *-*mindblown*-*

So I think the idx equation above needs to be tweaked but I'm not sure how.

**Comment by kjhollen** [comment]
Good catch. Hmm. I've been thinking about this one on and off over the last month and still haven't come up with an elegant idea for resolving the floating point pixel densities.

We could do a partial "fix" that rounds the pixel density in the single pixel case (the one that you linked), but it still won't look right if you're trying to loop over a grid of pixels in a sketch and calling `set()` on each one.

I'm stuck, but just thought I'd post a comment in case others had any ideas!

**Comment by lmccart** [comment]
I believe this was fixed to a reasonable extent (as @kjhollen describes above), with this here: https://github.com/processing/p5.js/pull/1052.

**Comment by kjhollen** [comment]
Rad! Thanks @toolness :)

**Comment by toolness** [comment]
No problem @kjhollen, glad I could help!
