### ISSUE TITLE
Decision: use Sizzle for DOM element selection?

### ISSUE THREAD

**Issue by kadamwhite** [processing/p5.js#800]
Per the conversation in #645, the [Sizzle](https://github.com/jquery/sizzle) project provides a very fast DOM element query syntax that balances high ease-of-use (more or less complete CSS selector parity) with performance. We should consider whether p5 should bundle Sizzle in order to make the DOM selector methods as straightforward (and transferable to other tools like jQuery itself) as possible.

Pros:

- Much more complete selector engine than what we currently provide, that optimizes for the fastest native method for the provided query
- Works the same as jQuery and all jQuery-derived libraries, so skills are transferrable
- They've solved most of the problems we're trying to address in our own DOM selector implementation, so we don't need to reinvent the wheel

Cons:

- Adds ~20kb minified to the project (file size is not a primary value, but worth noting)
- May be "overkill" vs the "training wheels" metaphor that was presented for p5's DOM functionality
- Encourages a jQuery/CSS mentality around element selection, vs the native DOM apis that it abstracts like getElementById and querySelectorAll

**Comment by toolness** [comment]
I'm very new to this conversation, so this may have been mentioned already, but I think it's worth looking at what lightweight alternatives to jQuery are doing. For instance, [Zepto](http://zeptojs.com/) largely relies on [`document.querySelectorAll()`](http://caniuse.com/#feat=queryselector) to do the heavy lifting, and consequently its jQuery-compatible selector engine weighs in at only 85 lines of code (including comments):

https://github.com/madrobby/zepto/blob/master/src/selector.js

I think the main tradeoff here is dropping support for the really old browsers (IE6 and IE7) that Sizzle was originally designed for, but I'm not sure.

**Comment by lmccart** [comment]
for organizational purposes, I'm going to close this one for now... it doesn't seem like there's a lot of immediate energy to move in this direction, and things seem relatively stable with p5.dom, but it may be something we revisit in the future.
