### ISSUE TITLE
cross-domain images loading. An work around.

### ISSUE THREAD

**Issue by v-k-** [processing/p5.js#802]
Hi. while trying to deal with cross domain loading images, I got this amazing hack by @GoToLoop in processing's forum. Maybe you guys would like to have a look:

http://forum.processing.org/two/discussion/11608/i-can-t-display-images-dynamically-loaded-from-web-with-p5-js-always-a-cross-domain-issue

an working test:

http://kubrusly.com/twtest/tainted/

**Comment by lmccart** [comment]
thanks @v-k-, this is interesting! @shiffman I seem to recall you mentioning something like this, is this something we should consider adding to the library? I worry that it feels a little hacky. but it would be useful functionality.

**Comment by shiffman** [comment]
This is the relevant thread from before: https://github.com/processing/p5.js/issues/561.  Is the use of `createImg()` a good solution here?

**Comment by lmccart** [comment]
I'm not hearing much affirmation for building this into the library so I think it is best left as a useful workaround in the forum for now. Thanks @v-k- for bringing it up, and we will wait and see, if image loading does turn out to be an issue a lot of people are running into we can reopen this one.

**Comment by atduskgreg** [comment]
FWIW, I'm hitting this issue right now. And the example workaround posted on the forum isn't working for me when I try to adapt it to instance mode.

**Comment by dhowe** [comment]
This is a hack to be sure, but I might argue for including it in the library (assuming it works in instance mode). In the teaching context, it is very distracting to have to discuss cross-domain security models for students who simply want to show an image in their sketch.

**Comment by siusoon** [comment]
I'm hitting this issue now too. createImg() works partially for loading cross domain image if you just plan to display the image, but if you want to do loadpixels  e.g 
```
img = createImg('http://xxxxx.jpg', 'test);    //assume this is an API link that you get the image URL on the fly, and you can't preload the image
img.hide();
image(img, x,y);
img.loadPixels();
```
this won't work
