### ISSUE TITLE
'grunt watch' fails due to missing task

### ISSUE THREAD

**Issue by dhowe** [processing/p5.js#804]
Removing that task from the array appears to fix the problem, but I'll leave this for the author...

![screen shot 2015-07-12 at 3 01 26 pm](https://cloud.githubusercontent.com/assets/737638/8636823/e011514c-28a7-11e5-8413-273dc74eb195.png)

**Comment by dhowe** [comment]
Actually what I think we want is something closer to this:
````js
    watch: {
      // Watch the codebase for changes
      main: {
        files: ['src/**/*.js'],
        tasks: ['newer:jshint:source','browserify', 'concat', 'uglify', 'requirejs','mocha'],
        ...

**Comment by lmccart** [comment]
hey @dhowe, forgive me, I don't usually use grunt watch so I'm not sure exactly what should be in there. should it just be the same as the default grunt task? or does grunt watch have less in there?
default is  `['connect', 'jshint', 'jscs', 'build', 'mocha']`

**Comment by dhowe** [comment]
I usually don't lint during a 'watch', but I think its OK (either way) for a default...

**Comment by lmccart** [comment]
@kadamwhite I was going to make this change, but I wondered if you had last worked on this part and have a better sense what's happening with this task and might want to take a look?

**Comment by kadamwhite** [comment]
@lmccart I'm happy to make this change this evening, if you want to tackle it now though be my guest, I can review :)

**Comment by lmccart** [comment]
ok not totally sure I got it right, but an attempt..

**Comment by kadamwhite** [comment]
Looks good to me—linting during a watch is pretty common, and if the linter fails (if there's a syntax error) it won't try to run the tests, which should save turnaround time.

**Comment by lmccart** [comment]
great, thanks for looking it over
