### ISSUE TITLE
rotate p5.Element not implemented?

### ISSUE THREAD

**Issue by poemusica** [processing/p5.js#807]
Hello p5 folks, 

This is an issue with the p5.dom library. (Sorry if this is the wrong place to report. I couldn't find a separate repo for p5.dom and it sounds like you guys maintain it.)

### Problem
The code in the following example does not work:
http://p5js.org/reference/#/p5.Element/rotate
More generally, cannot rotate any p5.Element. 

### Attempt 1
Using this version p5.dom:
https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.4.6/addons/p5.dom.js
produces the error:
Uncaught TypeError: cnv.rotate is not a function

The same error occurs when trying to rotate any p5.Element. It seems that this method is not implemented in version 0.4.6 of p5.dom (currently hosted on cdnjs.com).

### Attempt 2
Using an alternate version of p5.dom (on github):
https://github.com/processing/p5.js/blob/master/lib/addons/p5.dom.js
(latest commit 998e10187e3727969b5ca3d136076aa927eeb0c1)
does not produce an error in the Chrome devtools console, but also does not produce the desired effect. (The canvas doesn't rotate.) However, p5.Elements (such as those created by createDiv()) can be rotated.

**Comment by lmccart** [comment]
sorry about the mistake in the documentation, this will be in the next version coming out tomorrow.

**Comment by poemusica** [comment]
Yay! Thanks for the update!

**Comment by futuremarc** [comment]
Actually the canvas currently isn't being wrapped in a p5 Element so you won't be able to manipulate it. I was actually thinking about this, shouldn't we want to return the canvas in a p5 Element whenever one is created?

@poemusica You're right though, the examples in the upcoming documentation wouldn't work without first wrapping the canvas.

**Comment by rfpuyana** [comment]
Trying to use rotate() but is not working. The example in p5js.org is not working either. 
I am using v0.5.1
