### ISSUE TITLE
text wrapping doesn't work correctly

### ISSUE THREAD

**Issue by lee00678** [processing/p5.js#809]
when the text length exceed the given display area (when given the two more variables for width and height), the text got pushed out of the display area.

**Comment by dhowe** [comment]
thanks lee -- can you supply us with a simple test (a screenshot would be great too) so we can verify this?

**Comment by lee00678** [comment]
I used the reference page as an example. 
if you change some variables in the second example, the text is being pushed down.
![textarea](https://cloud.githubusercontent.com/assets/5026041/8704621/dda7bb84-2ad8-11e5-8dfc-074db1b0712f.png)

http://p5js.org/reference/#/p5/text

HTH
Qian

**Comment by lmccart** [comment]
closed with https://github.com/processing/p5.js/pull/812#issuecomment-122123375
