### ISSUE TITLE
Frame ghosting

### ISSUE THREAD

**Issue by jadnco** [processing/p5.js#814]
Noticed this on the main website. Previous frames are faintly visible, even as the background is redrawn. Not sure if this is specific to the featured animation.

![screenshot 2015-07-20 01 56 41](https://cloud.githubusercontent.com/assets/6766444/8771163/3503d414-2e83-11e5-9e8a-e3f8bd5e3adb.jpg)

**Comment by lmccart** [comment]
yes this is intended. are you noticing it elsewhere?

**Comment by jadnco** [comment]
My apologies. No, I haven't noticed it anywhere else.
