### ISSUE TITLE
Unable to save() or saveCanvas()

### ISSUE THREAD

**Issue by justinpoiroux** [processing/p5.js#817]
Both functions return errors: Uncaught TypeError: filename.indexOf is not a function.

Doesn't work in neither setup() nor draw().

My thread on processing forum: http://forum.processing.org/two/discussion/11786/save-not-working-on-any-canvas

**Comment by futuremarc** [comment]
Interesting, looks like you're right. For me saveCanvas() is throwing

`Uncaught TypeError: cnv.toDataURL is not a function`.

**Comment by lmccart** [comment]
woops this got fixed in the latest version 0.4.7 but for some reason this version isn't showing up on the downloads page. can you try this one here: https://github.com/processing/p5.js/releases/tag/0.4.7 and see if you still have an issue?

**Comment by sunwangshu** [comment]
Still can't save with saveCanvas

**Comment by sunwangshu** [comment]
Well, can't save canvas when it runs in the p5 editor version 0.5.5, but all fine in Safari and Chrome browser.

**Comment by lmccart** [comment]
you can post issues for the editor here:
https://github.com/processing/p5.js-editor
