### ISSUE TITLE
loadImage() blocked by Cross-Origin Resource Sharing Policy

### ISSUE THREAD

**Issue by KevinGutowski** [processing/p5.js#822]
Not quite sure if its just me or if its a larger issue but I can't seem to load images properly. When using Chrome [just downloaded it -  44.0.2403.107 (64-bit)] I get this error. It loads just fine in Safari.

<img width="1051" alt="screen shot 2015-07-24 at 8 54 46 pm" src="https://cloud.githubusercontent.com/assets/4199296/8887789/8127e4fe-3246-11e5-8ce3-186bfe0e41d3.png">

with this code:

```javascript
var bg;

function setup() {
	devicePixelScaling(3.0);
	createCanvas(windowWidth, windowHeight);

	loadImage("img/bg1.jpeg", function(bg) {
		image(bg,0,0);
	});
}
```

as well as this code:
```javascript
var bg;

function preload() {
	bg = loadImage("img/bg1.jpeg")
}

function setup() {
	devicePixelScaling(3.0);
	createCanvas(windowWidth, windowHeight);
        image(bg,0,0);
}
```

**Comment by spasmsaps** [comment]
@KevinGutowski Chrome does not allow loading local files by default, see:
http://www.chrome-allow-file-access-from-file.com/
Or set up a local server:
https://github.com/processing/p5.js/wiki/Local-server

**Comment by KevinGutowski** [comment]
Ah thanks for the help. Could be useful to post on the website.

**Comment by lmccart** [comment]
thanks we'll add this information to the reference.

**Comment by dhowe** [comment]
I don't see this in the reference, nor do I see a ticket for it (plus it seems very confusing for students)...
