### ISSUE TITLE
determine minimum browser support

### ISSUE THREAD

**Issue by lmccart** [processing/p5.js#83]
definitely canvas
ECMAScript5?

make spec clear to users,
also make clear that anyone trying to view work would need minimum browser also.

**Comment by kadamwhite** [comment]
I'd like to revisit this issue: [this supported browsers wiki page](https://github.com/processing/p5.js/wiki/Supported-browsers) is empty, and that makes it difficult to reason about how to approach issues when refactoring the code. `.map`, e.g., would clean up several areas of code and is available in IE9 and up, but until we officially make a decision it seems premature to make those changes.

**Comment by lmccart** [comment]
hey thanks for bringing this up again @kadamwhite. I think the unofficial stance we've been taking is supporting the last two most recent versions (current and last before that). with a goal of failing gracefully when possible for older browsers. does that seem reasonable? this would let us use `.map` definitely.

**Comment by kadamwhite** [comment]
@lmccart Thanks for the response! I take it this would mean IE >= 10, Chrome >= 40, Firefox >= 35, etc — does this also mean Android >= 4 and iOS >= 7, or do we want to do something different for mobile?

**Comment by workergnome** [comment]
We've decided on this!  Current-1.

See https://github.com/processing/p5.js/wiki/Supported-browsers for more info.

We're trying to figure out how to display friendly messages to users who have unsupported browsers.  I'll open a new issue for that.

**Comment by islemaster** [comment]
For anyone running across this thread frustrated by the dead link above, the most recent resource I've found is [developer_docs/supported_browsers.md](https://github.com/processing/p5.js/blob/master/developer_docs/supported_browsers.md).
