### ISSUE TITLE
Unit test still passing with exception

### ISSUE THREAD

**Issue by dhowe** [processing/p5.js#830]
/p5.js/test/test.html?grep=Files%20loadFont()%20in%20Preload

**Comment by kadamwhite** [comment]
What branch is this reported against? #827 may address it; on that branch I get this result:
![image](https://cloud.githubusercontent.com/assets/442115/8900265/143b884c-33f3-11e5-947b-3a9b48c86357.png)

**Comment by lmccart** [comment]
was this fixed with https://github.com/processing/p5.js/pull/835? go ahead and close this issue if so.
