### ISSUE TITLE
p5 on mobile devices

### ISSUE THREAD

**Issue by OhJia** [processing/p5.js#836]
I'm focusing on p5 uses for mobile devices. Have you encountered any issues while using p5 on mobile browsers or with native wrapper such as Phonegap? Are there any mobile specific capabilities that would be useful for students? More specifically I'm working on the following and would love to get some feedback and suggestions. 

### Setups for mobile browser and Phonegap 
The goal is to make it as beginner friendly as possible. I've created a super rough draft of documenting various setup tools and methods in [this wiki](https://github.com/OhJia/p5Mobile/wiki/Workflows). 

### Mobile performance and compatibility
- One of the performance issue is that interactions become very slow on mobile when the canvas gets scaled. @lmccart had mentioned that there could be a 1024px threshold on canvases with mobile rendering. Perhaps there could be a default set for mobile that wouldn't go over 1024px. Thanks for bringing this up @futuremarc
- Testing on different devices

### Mobile specific events and access
Here are some. Feel free to add to this or if there are already beginner friendly ways to do these please let me know!
- double tap
- swipe left/right
- shake detection
- pinch
- access to front and back camera 
- access to photos and contacts

I've listed more ideas for mobile specific setup, interactions, and events on hackpad. You can see them [here](https://hackpad.com/p5-mobile-ideas-and-functions-wszQ3c4bHGg).

**Comment by shiffman** [comment]
This is great!  In particular, the workflows wiki you posted is super helpful.  This is a major stumbling block I see often in class -- how to easily get something running on a device for testing and be able to quickly iterate changes and get console access for debugging.    I am wondering about possibilities for integrating with the IDE.  For example, an ideal scenario is having a "run on device" button in the IDE where the sketch runs on the device, but console output is still piped into the IDE itself (this is similar to the Processing Android model).  Is this a total fantasy?  cc @antiboredom

**Comment by OhJia** [comment]
@shiffman @antiboredom An IDE "run on device" button would be amazing! Would love to help with this. @therewasaguy had mentioned a "run on device" like feature for the web IDE as well. Alternatively, for mobile browser sketches, a url that gets generated and sent to device could be an easy implementation(?)

**Comment by futuremarc** [comment]
Perhaps a 'run on mobile button' could just start up a local server and spit out the IP which you should connect to on your mobile. Actually, sorry for not knowing this, but do we expect students to start up local servers even when using the IDE?

**Comment by lmccart** [comment]
@OhJia is it ok if we close this one as it seems you're past the initial brainstorming and suggestion gathering phase? If others have more ideas for features or changes they can continue to open individual issues for them. But for housekeeping sake, I think it's helpful to close larger general issues/questions like this one once they've served their purpose. What do you think?

**Comment by badrrada** [comment]
@OhJia are these events function or variables ??

    

> **double tap
>     swipe left/right
>     shake detection
>     pinch
>     access to front and back camera
>     access to photos and contacts**
