### ISSUE TITLE
touchevents on mobile fullscreen

### ISSUE THREAD

**Issue by whichlight** [processing/p5.js#839]
Hey there! I'm having trouble with touchevents on mobile when I'm working with fullscreen. If i specify the window size it works fine, but if i go fullscreen it doesn't.  On desktop fullscreen works great. Here is a repo where I did a test: https://github.com/whichlight/p5-fullscreen

Renderings not based on touch events (the line in the center) work on mobile or desktop. Renderings depending on touch events dont show up on mobile. This may have been adressed already, apologies if it has.  If that's the case please point me to an example I can test out.  Thanks!!

**Comment by OhJia** [comment]
Hi @whichlight, should work if you use touchX instead of mouseX. Try this on your mobile device: http://bit.ly/1g8h17S The code is the same as your repo except touchX.

**Comment by whichlight** [comment]
omggggg yay. Hmm, I was trying to recreate an earlier issue I had, but this is working absolutely wonderfully. Thank you so much :D

**Comment by lmccart** [comment]
cool, glad that worked. I thought at one point though, mouseX would just work on mobile, just as touchX would work with mouse, so you don't have to change it up from one to the other. I can look into this.

**Comment by OhJia** [comment]
@lmccart I haven't tried mouseX on mobile. I can also try it on different devices.

**Comment by Mottie** [comment]
Maybe it would be better to go use [pointer events](http://www.w3.org/TR/pointerevents/)? Check out [jQuery's PEP](https://github.com/jquery/PEP) (Pointer Events Polyfill) repository; and no, it is not dependent on jQuery.

**Comment by whichlight** [comment]
omg. @Mottie  i've been dreaming of something like pointer events to exist. this is really cool, thanks so much! I will play with it
