### ISSUE TITLE
If setup isn't present p5 doesn't initialize?

### ISSUE THREAD

**Issue by togakangaroo** [processing/p5.js#840]
This is confusing to me.

I created a simple page wanting to play with things in the console. Despite me loading all files properly in the correct order, none of the global processing methods were available. In order for them to be available I had to create a `window.setup = function() {}` in a script tag soon *after* the p5. 

This is very confusing and I'm not sure what the underlying mechanism is at all (I assume a `setTimeout` scans for this method..) Can this mechanism and requirement please get documented?

**Comment by lmccart** [comment]
thanks for the feedbakc @togakangaroo and apologies for the confusion. I documented this [here](rocessing/p5.js/wiki/Frequently-Asked-Questions#is-setup-and-draw-required-when-are-they-called-what-is-the-page-load-order) please let me know if there's anything you feel is missing or still not clear!
