### ISSUE TITLE
Is it possible to add two SoundFiles?

### ISSUE THREAD

**Issue by togakangaroo** [processing/p5.js#841]
Trying to figure out if I can add two SoundFile objects to create a single one. Can't find anything in the docs but it seems like it should be possible...

**Comment by therewasaguy** [comment]
Hey @togakangaroo, could you provide more details about what you're trying to do?

It sounds like you're talking about a sampler that can play two different files. For this you could just use two SoundFile objects. You could wrap them in your own "sampler" object if you want them to behave as one object.

p5.sound has its own github repo / issues thread so please post to https://github.com/processing/p5.js-sound/issues if you'd like to continue the discussion.
