### ISSUE TITLE
new windows build of p5 editor

### ISSUE THREAD

**Issue by lmccart** [processing/p5.js#843]
Hi everyone, I wanted to spread the word that there is a build of the p5 editor for windows now available.
We're working hard to get this in good shape for anyone that may be teaching with it this fall. If you have a chance to try it out and [report any feedback or bugs](https://github.com/processing/p5.js-editor/issues), it would be so helpful!

https://github.com/processing/p5.js-editor/releases/tag/v0.3.2
(click the p5-editor-experimental-windows.zip  to download)

**Comment by alanJoe** [comment]
load and play sound can not run as  expected

**Comment by alanJoe** [comment]
859: Uncaught not ready to play file, buffer has yet to load. Try preload()

**Comment by alanJoe** [comment]
proload neither

**Comment by futuremarc** [comment]
Awesome! Much, much needed for classes!
