### ISSUE TITLE
performance degrade on mobile device when multiple sound files loaded

### ISSUE THREAD

**Issue by faytom** [processing/p5.js#845]
i am developing a music rhythm game with p5js. When i try to run the game on some android devices and iphone5, it was experiencing a significant performance drop, the frame rate dropped below 30fps. refer to: https://github.com/faytom/musicgame/blob/master/mg/sketch.js#L175 I also checked out the timeline tool provided by chrome. It took most of the time to process audio within each frame. can anyone help me with it?

**Comment by lmccart** [comment]
hey @faytom this seems like it is specifically sound related, do you mind posting it here: https://github.com/processing/p5.js-sound/issues? however, it would probably be easier to fix if you could narrow it down to a simpler test case that shows the issue, is this possible? 

if this is more of a general code / debugging question then the best place for that would actually be the forum: forum.processing.org/two/categories/p5-js.

**Comment by faytom** [comment]
@lmccart thanks for your information. I was just so lost when a problem occurred.
