### ISSUE TITLE
 p5.js says: You wrote rect(X,X,X,X,X,X,X,X)

### ISSUE THREAD

**Issue by zenozeng** [processing/p5.js#851]
![2015-08-09 08 07 55](https://cloud.githubusercontent.com/assets/2544489/9152888/298669f8-3e6e-11e5-9d42-bf577633525a.png)

I use `rect(30, 20, 55, 55, 20, 15, 10, 5)` to draw round rect, but p5.js gives me this warning:
```
> p5.js says: You wrote rect(X,X,X,X,X,X,X,X). 
rect was expecting 9 parameters. 
Try rect(X,X,X,X,X,X,X,X,X). 
rect takes different numbers of parameters depending on what you want to do. 
Click this link to learn more:  [http://p5js.org/reference/#p5/rect]
```

**Comment by crhallberg** [comment]
Just to clarify before I fix, is there a valid 9 parameter use for rect()?

**Comment by lmccart** [comment]
I don't think so..
http://p5js.org/reference/#p5/rect

**Comment by crhallberg** [comment]
Alright! 9 reduced to 8. Pushing now.

**Comment by crhallberg** [comment]
https://github.com/processing/p5.js/commit/1c69f65235ce4bd15b3b5c4f348bc25b9622f988
