### ISSUE TITLE
Instead of recommending apache how about a node server?

### ISSUE THREAD

**Issue by greggman** [processing/p5.js#853]
Apache seems like overkill and running it on OSX (as in the instructions) means your machine is now running a server all the time in the background and open to being owned unless you remember to turn it off. It's also a not very approachable in terms of configuration and tell it where to server files from.

An alternative is node. Just 3 simple steps

1.  [Download and Install node.js](http://nodejs.org/download)
2.  Open a terminal or command prompt 
3.  On OSX/Linux type

        sudo npm install -g http-server

    On Windows type (you might need to open the command prompt as admin)

        npm install -g http-server
 
Done! 

Now, anytime you want to run a server just cd to the folder you want to serve and type `http-server` and then go to `http://localhost:8080` in your browser. It's just as easy as the python method but the node server is very fast. It has no problem streaming video for example, something the python server fails at.

Thoughts? Should I edit the wiki?

**Comment by lmccart** [comment]
I think the python simple server is about similar complexity (https://github.com/processing/p5.js/wiki/Local-server#python-simplehttpserver), but it's great to have multiple options so please feel free to add these node instructions to the wiki!

**Comment by sepans** [comment]
+1 python: Mac OS and most linux distributions [and maybe even windows 10](https://windows.uservoice.com/forums/265757-windows-feature-suggestions/suggestions/6693586-ship-python-3-and-python-2-with-windows-10) have python pre-installed.
-1 apache: It has one extra step (copying files or changing DocumentRoot) to run examples.

**Comment by greggman** [comment]
I was suggesting node as an alternative to both python and apache. Python's simple server has well known problems. It's very slow. Sometime it pauses for 3-30 seconds trying to serve stuff. It sucks at serving anything more than a few 10s of k. Try to serve an .mp3, .ogg, .mp4, .wp8 and it will fail. It also can't stream.

Anyway I'll add node to the wiki.

**Comment by kadamwhite** [comment]
I definitely feel like we should note the security caveat to the Apache recommendation. Long-term I want to try to make [p5-cli](https://github.com/kadamwhite/p5-cli) more robust so that it can be a more reasonable alternative to other Node-based HTTP server mechanisms.

**Comment by lmccart** [comment]
Great point, @greggman if you'd like to add a note about the security risks with running apache to the wiki as well that'd be wonderful.
