### ISSUE TITLE
save() function does not work on graphics buffers

### ISSUE THREAD

**Issue by sterlingcrispin** [processing/p5.js#854]
this should work according to the documentation but it doesn't :(
http://p5js.org/reference/#/p5/save

function setup() {
  createCanvas(windowWidth, windowHeight);
}

function draw() {
  // draw stuff here
  ellipse(width/2, height/2, 50, 50);

  test = createGraphics(100,100);
  test.background(255, 0, 0);
  save(test, 'lolbroken.jpg');
}

**Comment by lmccart** [comment]
just pushed a fix, however, it's recommended that you don't call `save()` inside draw if it's looping as it will try to open a save dialog every frame.

**Comment by sterlingcrispin** [comment]
awesome thanks!
