### ISSUE TITLE
calling .mask() on a Renderer object and calling .get() on video capture (element object)?

### ISSUE THREAD

**Issue by jsphweid** [processing/p5.js#855]
Just a few quick things that I thought were simply my novice misunderstandings but may be actual issues.

.mask() seems to only work with actual image files and not graphics. I was trying to use it to whiten out a section around a structure that is generated. Neither the structure nor the mask are image files, but generated and change. When I use .mask() on a graphics object (renderer), I get: "Uncaught TypeError: myFront.mask is not a function"

.get() seems to only work with image objects as well and it seems to not work on a capture stream. I could do this easily in Processing but not P5JS. I get the error: "Uncaught TypeError: Cannot read property 'get' of undefined" when attempting to use .get() on a video capture.

See the end of this discussion on the Processing forums. GoToLoop actually knows what he's talking about (I think...): http://forum.processing.org/two/discussion/comment/48731/#Comment_48731

Not sure if these things are my ignorance, problems, or part of the intended design.

**Comment by lmccart** [comment]
yes, this is correct, `mask()` works only with images, in line with the processing implementation: https://processing.org/reference/PImage_mask_.html

the `get()` with capture issue was indeed a bug and should be fixed with the change i just pushed.

**Comment by jsphweid** [comment]
Thanks for fixing. But actually... Is it even possible to use get() like .get() on a webcam stream or image or does it just retrieve from the primary canvas only? It's cool to pick/track particular pixels from a video stream, without displaying the entire stream.
