### ISSUE TITLE
Browser compatibility issue due to String.prototype.repeat()

### ISSUE THREAD

**Issue by zenozeng** [processing/p5.js#858]
I notice that String.prototype.repeat() was used in error_helper.
https://github.com/processing/p5.js/blob/dbef89fdaa6c94648c534b4a0e869b63611e63c9/src/core/error_helpers.js#L142

However, this method is new tech (part of es6), so seems that IE and Safari did not support it.
Maybe we can provide p5.prototype._repeat and use something like `Array(n+1).join(str)` or simply apply MDN's polyfill?

See also: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/repeat

**Comment by lmccart** [comment]
good catch, I suggest we just use the array join method for this, do you want to submit a PR?

**Comment by zenozeng** [comment]
OK, I will pull a request later.

**Comment by zenozeng** [comment]
Should I provide p5.prototype._repeat or just replace string.repeat with inline function?

**Comment by lmccart** [comment]
I'd say just repeat the string.repeat call with a non-ES6 call, adding another method just for repeat seems a little overkill right now.

**Comment by zenozeng** [comment]
@lmccart See https://github.com/processing/p5.js/pull/862.
