### ISSUE TITLE
webgl: box() function parameters under 100 make box disappear 

### ISSUE THREAD

**Issue by indefinit** [processing/p5.js#864]
example code to reproduce bug:
in sketch.js

```
function setup(){
  createCanvas(windowWidth, windowHeight, 'webgl');

}
function draw(){
  background(255);
  box(100); //draws large box in center of screen
  //box(99); // hey, wha happened?!
}
```

**Comment by karenpeng** [comment]
I think it's due to the camera position. You could put the scene away from the z axis to make things show up.
In the new update, camera is a function that user could controlled.

**Comment by karenpeng** [comment]
now there is a defaulted camera in 800 along the z axis, this should be fine.
