### ISSUE TITLE
friendly error if data (JSON) is invalid?

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js#870]
I noticed that if you try to load invalid JSON, no error is thrown or reported.  If I run the following code with invalid JSON in `file.json`, the callback never triggers. 

```javascript
function setup() {
  loadJSON("file.json", function(data) {
    println("Data loaded.");
    println(data);
  });
}
```

I'm guessing there's likely a way I could pass a function to handle errors, but I think for beginners it would be nice to throw some sort of `invalid JSON` message to the console. (I personally was confused for a while debugging and didn't notice that I had a typo in the test JSON file for my example.)

**Comment by Jared-Sprague** [comment]
@shiffman yep you're right, there is no validation of the json before it starts parsing it.  I'll work on a fix for this.

**Comment by lmccart** [comment]
I'd suggest just using `console.log()` to print a message right now, rather than hooking into the friendly error system, as the FEs are still very much in progress and it'd be good to get all the details with that ironed out first before we add more uses of it.

**Comment by Jared-Sprague** [comment]
Good to know thanks!  I'll just console.log

**Comment by Jared-Sprague** [comment]
@lmccart @shiffman After looking into this, reqwest provides a builtin error handler that you can provide a callback for when there is an error which we weren't using.  I added an error callback, and console.log the error message and detailed error message when there is an error. e.g. " Could not parse JSON in response 
JSON.parse: expected property name or '}' at line 3 column 5 of the JSON data"  See attached screen shot:

![screenshot from 2015-10-04 14 42 05](https://cloud.githubusercontent.com/assets/3926730/10269479/e3b7e9c8-6aa6-11e5-8697-de4b81af9d7b.png)

Pull request: https://github.com/processing/p5.js/pull/967

**Comment by lmccart** [comment]
closed with https://github.com/processing/p5.js/pull/967
