### ISSUE TITLE
print() opens print dialog

### ISSUE THREAD

**Issue by sawula** [processing/p5.js#871]
This code causes a print dialog box to open up.  It happens whether I try to run it directly or via a SimpleHTTPServer using either Chrome or Firefox.

```
var periodsRows;
function preload(){
  periodsRows = loadStrings('assets/periods.txt');
}

print(periodsRows);
```

When I comment out the `print` line, I don't get a print dialog box.  Maybe I don't have my data file set up correctly, but I still think it shouldn't be doing this!

**Comment by p5k12** [comment]
Ah.  It's because `print()` was outside of `setup()` or `draw()`.

**Comment by lmccart** [comment]
ah yes, this is right. `print` is a browser native function, so if you call it outside of a p5 function, it will default to that behavior.

**Comment by fepegar** [comment]
I tried to print a blank line doing `print()` in a function of a class, in the web editor. I call that function (method? I'm a Python person) in `draw()`. I do
```javascript
print(vx)
print(vy)
print()
```

Now the print dialog keeps popping up and can't modify my sketch, which I guess I'm losing forever (no big deal in this case). Auto-refresh is enabled and I cannot change it either.

Is this expected? I wish the editor had warned me of this behavior or something.

Please lmk if I should open a new issue for this.

**Comment by lmccart** [comment]
@fepegar the last line should be `print('\n')`
Calling `print()` without any arguments invokes the [`window.print()`](https://developer.mozilla.org/en-US/docs/Web/API/Window/print) function which opens the print dialog.

@L05 let's add a line to the [print()](https://p5js.org/reference/#/p5/print) documentation that says:

> Calling `print()` without any arguments invokes the [`window.print()`](https://developer.mozilla.org/en-US/docs/Web/API/Window/print) function which opens the print dialog. To print a blank line you can write print('\n').

**Comment by fronofro** [comment]
Slightly different issue if you are using the p5js web editor and have auto-refresh on and type out print() before you put something in it you will get stuck in an endless loop of the print dialog showing up. Perhaps you should need to set a specific parameter for that default functionality to be called.

**Comment by fepegar** [comment]
@fronofro [I had the same problem](https://github.com/processing/p5.js/issues/871#issuecomment-420091527).

**Comment by lmccart** [comment]
ah interesting, @fronofro or @fepegar could one of you post this on the p5.js web editor issues: https://github.com/processing/p5.js-web-editor/issues

**Comment by fepegar** [comment]
@catarak @lmccart 

Where should the issue be opened?
https://github.com/processing/p5.js-web-editor/issues/614#issuecomment-379342235

https://github.com/processing/p5.js/issues/2765

**Comment by lmccart** [comment]
note the issue is the one mentioned here: https://github.com/processing/p5.js/issues/871#issuecomment-443082621

**Comment by catarak** [comment]
@fepegar you can go ahead and post this as an issue in the web editor. i'm honestly not sure how to approach this issue/what a solution looks like though!

**Comment by fronofro** [comment]
@fepegar @lmccart @catarak looks like this issue was brought up in: https://github.com/processing/p5.js-web-editor/issues/743

Seems like their suggestion of needing a parameter to run the default print() functionality makes sense to avoid this.

**Comment by catarak** [comment]
@fronofro i think the issue here is not that there isn't a solution, but it's a thing that can be triggered accidentally, which is impossible to close if it's in the draw loop. this might be one of those cases where the solution might just be to leave it. not sure though!
