### ISSUE TITLE
rect was expecting 9 parameters?

### ISSUE THREAD

**Issue by KouichiMatsuda** [processing/p5.js#872]
rect(10, 10, 80, 80, 0, 0, 0, 0);

function setup() {
  rect(10, 10, 80, 80, 0, 0, 0, 0);
}

function draw() {
}

This code causes the following message:

p5.js says: You wrote rect(X,X,X,X,X,X,X,X). rect was expecting 9 parameters. Try rect(X,X,X,X,X,X,X,X,X). rect takes different numbers of parameters depending on what you want to do. Click this link to learn more: p5js.org/reference/#p5/rect

I could append the extra 9th parameter such as,  rect(10, 10, 80, 80, 0, 0, 0, 0, 1);  
What's the 9th one?

**Comment by zenozeng** [comment]
@KouichiMatsuda Which version of p5.js you are using? It should be fixed in https://github.com/processing/p5.js/commit/1c69f65235ce4bd15b3b5c4f348bc25b9622f988.
See also: https://github.com/processing/p5.js/issues/851

**Comment by KouichiMatsuda** [comment]
Thanks.
I was using p5.js in "p5.js editor".
It might be old one.
I replaced it with the latest p5.js. It works well.

**Comment by lmccart** [comment]
great, glad you figured it out. sorry about this, we are working on improving the friendly error functionality currently.
