### ISSUE TITLE
Browsers drive me mad!

### ISSUE THREAD

**Issue by jimrolland** [processing/p5.js#873]
Hello,
I put a processing sketch thanks to P5.js on my website : 
http://franetjim.free.fr/indian.html
It works fine with Chrome but the screen remains blank with IE11 and Safari...
On Firefox, it works but the sound is strange.
Do you have any idea of what could cause the issue?
Thanks to all,
Jim

**Comment by lmccart** [comment]
hm it's showing up for me in safari, I haven't checked the other browsers. it could have to do with using some functionality that isn't yet supported in the browser you're using. in general, p5.js is made to support the two most recent versions of common browsers. you could take a look at http://caniuse.com/ to see if this gives you any clue.

in general, this is a better question for the forum: http://forum.processing.org/two/categories/p5-js. issues posted here need to be a little more specific -- things we can see aren't working from a focused example that we can then work on fixing. if something like that comes out of your debugging of this project, please feel free to open new issues here!
