### ISSUE TITLE
offline interactive reference

### ISSUE THREAD

**Issue by futuremarc** [processing/p5.js#878]
So I'm using FileSaver.js to grab the generated reference page as an .xhtml file and using jszip.js to wrap up all the corresponding dependencies. This gives us a wonderful downloadable interactive reference. 

Any idea where to implement this feature within the reference?

**Comment by lmccart** [comment]
ah this is so exciting and desperately needed! in terms of build, I think it would be amazing if it were somehow built into the docs generation process, so each time the docs are updated, theres a new static version is created as well. https://github.com/processing/p5.js/blob/master/Gruntfile.js#L107 I'm not sure offhand the best way to do this though.

in terms of placement on the website, maybe we add a link at the bottom of the [reference](http://p5js.org/reference/) page to the full download zip?

**Comment by shiffman** [comment]
It would be lovely to package the reference with the p5.js editor and implement a "find in reference" option a la Processing (select a function name --> right-click to "find in reference").  @antiboredom, reasonable to implement?

**Comment by peteruithoven** [comment]
Could a inclusion into devdocs.io be useful? This could give you the offline support. 
I have suggested adding p5.js on: https://trello.com/c/PVnfdeaN/26-suggest-new-docs-here

**Comment by lmccart** [comment]
hey @futuremarc I think it's really important to finish this one up since it could be a significant hurdle for those with slow internet connections. could you give me an update on where you're at and i can take it from there? i know you got pretty far and i don't want to duplicate your effort. thanks!

**Comment by toolness** [comment]
I'm excited about supporting this feature too, and would love to help out if needed.

**Comment by futuremarc** [comment]
update on this: so without changing how our backend works I was able to zip the libraries and dependencies along with the html dump of the reference, but no linked pages would be saved. If we were using npm theres a package called wget that would do exactly what we need.  

My next step is to look into building it with the grunt build process. However this doesnt address the issue of how slow the Reference loads at p5js.org; we should be thinking about a different way to generate the docs or having them generated beforehand as static files.

Anyone have any other advice or thoughts on changing the way we build the reference?

**Comment by lmccart** [comment]
thanks for looking into this @futuremarc. I agree, we should look into building the reference as static files. i'm going to close this issue, and we can continue discussion here: https://github.com/processing/p5.js-website/issues/143
