### ISSUE TITLE
DOM centering?

### ISSUE THREAD

**Issue by futuremarc** [processing/p5.js#879]
Hi guys,

Since centering things (especially vertically) in the DOM is such a pain I've written a `center()` function on the `p5.Element` that makes it fast and sexy to center elements to their parents.

It takes 1 arg with 3 options, 'horizontal', 'vertical', and 'both'; which aligns the element centered respectively. If no args then 'both' is assumed. Works for both text and nontext.  If no parent is defined it centers to the body.

Using it looks something like this:

 ```

b = createButton('HIT ME').center();
d = createDiv('HALFWAY UP').center('vertical');

```

For me when working with p5.dom this is always an issue, just wondering about everyone's thoughts on including it natively in p5.dom

**Comment by kadamwhite** [comment]
Centering, especially vertically, is definitely a pain-point in DOM work. I haven't been involved in the `p5.dom` implementation, but if we don't decide to include this it would still probably be good to have a link (or the entire code, if it's small—do you have a link to that function's implementation?) in the documentation!

Not related to the functionality, btw, but it might be good to avoid using "sexy" as a code descriptor; can feel non-inclusive depending on who's reading.
