### ISSUE TITLE
Uncaught TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by timcampix** [processing/p5.js#881]
Hi, there is an issue with the p5.js (both the file and the cdn and p5.min.js).  No matter how many times I followed one of the p5 tutoriasl, I keep getting an error that says "Uncaught TypeError: Cannot read property 'apply' of undefined". On p5,  the console is detecting an error on line 11101 and for p5.min,  on line 5.  When I used the previous version of p5.min.js, it works completely fine. Let me know if you need more details.
![p5 js error](https://cloud.githubusercontent.com/assets/5864119/9594165/af314820-5025-11e5-81db-3f2c103b0552.PNG)

**Comment by timcampix** [comment]
I don't know if this is useful but the tutorial that I was working on is: http://p5js.org/reference/#/p5.FFT
except I replaced the file with my own mp3 on line 2. 
It seems like there is a conflict with preLoad function.

**Comment by lmccart** [comment]
hey, can you test with the newest release when you get a chance and see if it's still a problem? https://github.com/processing/p5.js/releases/tag/0.4.9 thanks!

**Comment by timcampix** [comment]
Tested both p5.js and p5.min.js and it is working problem without any
issue! Thank you for getting back to me so quickly!

Take care,
timcampix

**Comment by lmccart** [comment]
great thanks for testing!
