### ISSUE TITLE
blendMode(ADD)

### ISSUE THREAD

**Issue by AlejandroMoscoso** [processing/p5.js#882]
Hey there! I wanted to use blendMode(ADD) but it seems it's not working because, as the console said, it's not defined. Any suggestion?

**Comment by jedahan** [comment]
Can you share the example code you are trying to run?

**Comment by AlejandroMoscoso** [comment]
Sure, this is what I've been trying out:

var front;  
var back;  
var bolas = []; // Array Bola objects

// Images
function preload()
{
  front = loadImage('assets/bolaColFront.png');
  back = loadImage('assets/bolaColBack.png');
}

function setup() 
{
  createCanvas( windowWidth, windowHeight );
  colorMode(HSB, 360, 100, 100);
  noStroke();

  // Create objects
  for (var i=0; i<50; i++) {
    bolas.push(new Bola());
  }
}

function draw() 
{
  background(5);
  smooth();

  for (var i=0; i<bolas.length; i++) {
    bolas[i].move();
    bolas[i].display();
  }
}

function windowResized() 
{
  resizeCanvas(windowWidth, windowHeight);
}

// Bola class
function Bola() 
{
  this.diameter = random(90, 190);
  this.radRan = random(1.4, 3);
  this.radius = this.diameter/this.radRan;
  var loc = createVector(random(width), random(height/4, height-height/4));
  var vel = createVector(random(-.3,.3),random(-.1,.1));
  var newSize = random(1.5, 2.5);
  var newSize2 = random(1.5, 2.5);

  this.move = function() 
  {
    loc.add(vel);
  };

  this.display = function() 
  {
      blendMode(SCREEN);
      imageMode(CENTER);
      image(back, loc.x, loc.y, this.diameter, this.diameter);
      image(front, loc.x, loc.y, this.radius, this.radius);   
  };

}

![bolacolback](https://cloud.githubusercontent.com/assets/12812370/9609742/b317620c-50d5-11e5-813c-7cf74aff1997.png)
![bolacolfront](https://cloud.githubusercontent.com/assets/12812370/9609743/b31a3298-50d5-11e5-94f4-a8d6e6b1a5f6.png)

**Comment by lmccart** [comment]
hm I'm not able to reproduce this, can you tell us the version of the lib you're using and the browser version? 
<img width="1333" alt="screen shot 2015-09-01 at 2 51 32 pm" src="https://cloud.githubusercontent.com/assets/191056/9613382/0165c02e-50b9-11e5-90c6-bdbaffeaefa2.png">

**Comment by AlejandroMoscoso** [comment]
I was using v.3.7 and it didn't work. I've just dowloaded the last version and now everything is ok. Im not sure what happend. Thank you very much!

**Comment by lmccart** [comment]
great
