### ISSUE TITLE
windowWidth and windowHeight do not work on iOS safari

### ISSUE THREAD

**Issue by bmoren** [processing/p5.js#884]
displayWidth/Height do work fine

**Comment by lmccart** [comment]
interesting... will check it out.
just wondering, @OhJia did you run into this at all with your mobile work?

**Comment by lmccart** [comment]
hm I'm not able to reproduce. running this code, I get the following:
```javascript
function setup() {
  console.log("setup", windowWidth, windowHeight);
}
// prints: "setup",980,1409
```

can you tell me which version iOS and iPhone you are testing with?

**Comment by bmoren** [comment]
iPhone5, iOS 8.3
I'm getting nothing to return

here is the sketch that I discovered the issue with:

```

function setup() {
	//createCanvas(displayWidth, displayHeight); //works!
	createCanvas(windowWidth, windowHeight); //does not work
	noStroke();
}

function draw() {
	background(0);
	fill(255, 0, 0);
 
 for(i = 0; i<touches.length; i++){
 	ellipse(touches[i].x, touches[i].y, 100, 100);
 }
 fill(50);
 textSize(180);
 textAlign(CENTER);
 text(touches.length, width/2, height/2);
}

```

**Comment by limzykenneth** [comment]
@bmoren I've just tested the sketch on my iPhone 5, iOS 8.4.1 with Safari and oddly enough, `windowWidth` and `windowHeight` works as intended while `displayWidth` and `displayHeight` is giving me a tiny version of the sketch.

Here's screenshots for sketch using `displayWidth` and `displayHeight`

![img_3564](https://cloud.githubusercontent.com/assets/7543950/9839188/97753022-5a69-11e5-8c37-86eafffb2e10.PNG)

![img_3563](https://cloud.githubusercontent.com/assets/7543950/9839189/9e716346-5a69-11e5-986c-44f7f68e7c78.PNG)

On the other hand, the console messages when doing `console.log("window: ", windowWidth, windowHeight)` etc. in the setup function gives me this:

![screen shot 2015-09-13 at 10 41 49 pm](https://cloud.githubusercontent.com/assets/7543950/9839207/e5b8debe-5a69-11e5-9f6b-fb11a32e2a4d.png)

What I think is happening in my case is that iOS and Safari have different figures when referring to the window size and display size (different dpi or something). Might be a OS/browser specific problem I'm not sure.

**Comment by mattdesl** [comment]
(Gonna leave this here for anyone still struggling with this...)

I can't reproduce the bug on my iPhone5S (iOS 9.2.1) but it sounds like it may be related to this:
https://github.com/bigwheel-framework/bigwheel/issues/25#issuecomment-145083388

You can try adding the following to head of your `index.html` that you use with your p5js sketch:

```html
<head>
  <meta name="viewport" content="shrink-to-fit=0">
  <!-- other meta / title / script tags below -->
  ...
</head>
```

(I recommend this over `document.documentElement.clientWidth` since it may report a different size than `windowWidth`, e.g. inside of a Twitter browser)

**Comment by tstefanich** [comment]
Yeah you can get this to look correct with the right <meta > tag I used 
```<meta name="viewport" content="width=device-width, initial-scale=1">```

This is working "correctly".... its more of a question if something gets added to p5 to make this easier/more seamless for individuals. 

1) either add this meta tag automatically to the index file 
```
var metaTag=document.createElement('meta');
metaTag.name = "viewport"
metaTag.content = "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"
document.getElementsByTagName('head')[0].appendChild(metaTag);
```

2) Do some simple math to display sizes based on pixelRaio 
```
if(window.devicePixelRatio !== undefined) {
    dpr = window.devicePixelRatio;
} else {
    dpr = 1;
}
var screen_width = window.screen.width * dpr;
var screen_height = window.screen.height * dpr;
```

But these will look different
![screenshot 2017-01-27 12 39 01](https://cloud.githubusercontent.com/assets/810727/22387346/03e762d2-e490-11e6-9e46-fd5321f88306.png)
![screenshot 2017-01-27 12 47 50](https://cloud.githubusercontent.com/assets/810727/22387347/069e04a4-e490-11e6-924e-0d85bb84f79f.png)

..........

Maybe something like this gets added to p5... (this is mostly pseudo code) but I think this is ideological/conceptual/framework question...

```
if(window.devicePixelRatio > 1) {
  if(mobile){
     if(metatag.viewport){
          var metaTag=document.createElement('meta');
          metaTag.name = "viewport"
          metaTag.content = "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"
          document.getElementsByTagName('head')[0].appendChild(metaTag);
     }
   }
}

**Comment by lmccart** [comment]
I like the idea but I worry a little about doing too much magic behind the scenes. Generally we're trying to leave as much default browser behavior in place as possible. Maybe what is needed is a tutorial on p5 for mobile and this would be one element of that?

**Comment by limzykenneth** [comment]
I think we can add the meta tag into the example index.html and also into the web editor. I usually use them as part of a boilerplate and never really thought about them because they are the inelegant part of the browser I don't want to personally deal with...

**Comment by bmoren** [comment]
@limzykenneth I think including them is a great idea and would solve this issue entirely. I always forget to include it / present it to my students and after class is over inevitably have a :man_facepalming: moment before sending out an after the fact reminder 😃

**Comment by lmccart** [comment]
ok I'm into that. I guess I was thinking you wouldn't want this in by default, but I guess there's no harm right?

**Comment by bmoren** [comment]
Yeah it seems like the best solution and I'd say the majority of the time it's the 'expected behavior' to have the element scale by default rather than show up as a small thing that the browser is trying to figure out. It kind of reminds me of the border box css property, where the behavior which most seems like it would be the default must be turned on manually.

I agree that this should not be baked into p5 itself but rather thought about like the removal of the default body margins and padding in the example.
