### ISSUE TITLE
text rendering on off-screen p5.Renderer ignores textSize() and fill()

### ISSUE THREAD

**Issue by JobLeonard** [processing/p5.js#886]
Hope this isn't a duplicate, quick search didn't show this issue being reported before.

Minimal example:

````
var pg;
function setup() {
  createCanvas(100, 100);
  pg = createGraphics(100, 100);
}
function draw() {
  pg.background(100);
  pg.fill(200);
  pg.noStroke();
  pg.textSize(50);
  pg.textAlign(CENTER, CENTER);
  pg.text("Test", width/2, height/2);
  image(pg, 0, 0);
}
````

**Comment by lmccart** [comment]
aha good catch. will look into it in the next week unless someone else gets there first :)

**Comment by lmccart** [comment]
after a little more investigation, I see there's a slightly bigger refactor that needs to occur here. currently, we are storing properties related to stroke, fill, textSize, etc on the p5.prototype object. we should instead store them on the p5.Renderer.prototype object, which is extended by both the 2D and 3D renderers. the p5 object should not be dealing with rendering properties at all, instead just passing the top level call onto this._graphics. I'll work on this over the next week or so.

**Comment by JobLeonard** [comment]
Awesome to see that you pick this up so quickly! :+1: (I obviously got a use-case for it, otherwise I wouldn't have found it)

Didn't expect it would result in a big refactor though; figured it was just a minor encapsulation bug somewhere.

**Comment by lmccart** [comment]
fixed with https://github.com/processing/p5.js/pull/895
