### ISSUE TITLE
print() outside setup/draw opens print dialog box

### ISSUE THREAD

**Issue by jefarrell** [processing/p5.js#887]
Calling the print() function outside of the setup() or draw() functions (Either standalone, or in custom functions) opens the browser Print dialog box when the sketch is run.  

    function setup() {
        //print("hello");  works fine
    }

    function draw() {
         //print("hello");  works fine
    }

    //print("hello"); opens print window

    function testing() {
        //print("hello"); opens print window
    }

If print() is in a callback function referenced in setup() or draw(), it works correctly.  

    function setup() {
        var url="exampleurl.com/test.json"
        data = loadJSON(url,loader);
    }

    function loader(Object){
        //print("hello") works fine
    }

**Comment by lmccart** [comment]
I believe this is correct behavior?

**Comment by antiboredom** [comment]
I think p5 should probably just completely overwrite the built in print - it's a bit confusing that the same function name would to two different things based on where it's called from.
