### ISSUE TITLE
"More than one parameter can be passed into the function by separating them with commas"

### ISSUE THREAD

**Issue by KouichiMatsuda** [processing/p5.js#888]
The reference says "The print() function writes to the console area of your browser.  ... snip .. More than one parameter can be passed into the function by separating them with commas."

More than one parameter can "not" be passed with comma.  Am I missing something?
Let's try:

function setup() {
  print(width, height);
}

function draw() {
  
}

**Comment by lmccart** [comment]
Sorry, the documentation is incorrect. parameters should be joined by using `+`. Something like `print("The value of x is "+x);` I've updated the documentation it should be fixed with the next push to the website.
