### ISSUE TITLE
accelerationX, accelerationY, and accelerationZ are incorrect.

### ISSUE THREAD

**Issue by KouichiMatsuda** [processing/p5.js#891]
The reference says 
> “accelerationX 
> Description
> The system variable accelerationX always contains the acceleration of the device along the x axis. 
> Value is represented as meters per second square.”

This is incorrect (also accelerationY and accelerationZ).

The accelerationX contains the amount of rotation (in degrees) around the x-axis (accelerationY is the one around y-axis, and accelerationZ is the one around z-axis). In terms of  axis, see http://www.w3.org/TR/orientation-event/ .

This is because the current p5.js code overwrites accelerationXYZ variables with the amount of rotation around xyz-axis.
```javascript
p5.prototype._ondeviceorientation = function (e) {
  this._setProperty('accelerationX', e.beta);
  this._setProperty('accelerationY', e.gamma);
  this._setProperty('accelerationZ', e.alpha);
};
```
I checked the values using my Android phones and iPad. Both reported the rotations, not accelerations. Let’s try the followings.
```javascript
function setup() {
  devicePixelScaling(false);
  createCanvas(windowWidth, windowHeight);
  background(200);
  textSize(50);
}

function draw() {
  background(200);
  text("ax: " + accelerationX, 100, 100);
  text("ay: " + accelerationY, 100, 150);
  text("az: " + accelerationZ, 100, 200);
}
```
You can check what are reported by using the following HTML.
```javascript
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" charset="UTF8" />
<script type="text/javascript">
window.addEventListener("devicemotion", function(e) {
  var result=document.getElementById("mot");

  var ax = e.acceleration.x;
  var ay = e.acceleration.y;
  var az = e.acceleration.z;

  result.innerHTML = "Acceleration (m/s^2)<br />"+
  "ax: "+ ax.toFixed(3) +"<br />" +
  "ay: "+ ay.toFixed(3) +"<br />" + 
  "az: "+ az.toFixed(3);
});

window.addEventListener("deviceorientation", function(e) {
  var result=document.getElementById("ori");

  var alpha = e.alpha; // orientation
  var beta = e.beta; // pitch
  var gamma = e.gamma; // roll

  result.innerHTML = "Orientation (degrees)<br />"+
  "alpha: "+ alpha.toFixed(3) +"<br />" +
  "beta: "+ beta.toFixed(3) +"<br />" + 
  "gamma: "+ gamma.toFixed(3);
});
</script>
</head>
<body>
<div id="ori"></div>
<div id="mot"></div>
</body>
</html>
```
One solution is that the system variables for the rotations should be supported, such as "alpha", "beta", and "gamma", more meaningfully "orientation", "roll", and "pitch", or "rotationX", "rotationY", and "rotationZ".

In the solution, the following code in p5.js should be modified as follows (the commented lines are original codes).
```javascript
p5.prototype._ondeviceorientation = function (e) {
  // this._setProperty('accelerationX', e.beta);
  // this._setProperty('accelerationY', e.gamma);
  // this._setProperty('accelerationZ', e.alpha);
  this._setProperty('beta', e.beta); // or pitch, rotationX
  this._setProperty('roll', e.gamma); // or rollm rotationY
  this._setProperty('alpha', e.alpha); // or orientation, rotationZ
  this._handleMotion();
};
p5.prototype._ondevicemotion = function (e) {
  this._setProperty('accelerationX', e.acceleration.x * 2);
  this._setProperty('accelerationY', e.acceleration.y * 2);
  this._setProperty('accelerationZ', e.acceleration.z * 2);
  this._handleMotion();
};
p5.prototype._onMozOrientation = function (e) {
  this._setProperty('accelerationX', e.x);
  this._setProperty('accelerationY', e.y);
  this._setProperty('accelerationZ', e.z);
  this._handleMotion();
};
p5.prototype._handleMotion = function() {
  if (window.orientation === 90 || window.orientation === -90) {
    this._setProperty('deviceOrientation', 'landscape');
  } else if (window.orientation === 0) {
    this._setProperty('deviceOrientation', 'portrait');
  } else if (window.orientation === undefined) {
    this._setProperty('deviceOrientation', 'undefined');
  }
  var deviceMoved = this.deviceMoved || window.deviceMoved;
  if (typeof deviceMoved === 'function')  {
    //    if (Math.abs(this.accelerationX - this.pAccelerationX) > move_threshold ||
    //      Math.abs(this.accelerationY - this.pAccelerationY) > move_threshold ||
    //      Math.abs(this.accelerationZ - this.pAccelerationZ) > move_threshold) {
    if (Math.abs(this.beta - this.pbeta) > move_threshold ||
      Math.abs(this.gamma - this.pgamma) > move_threshold ||
      Math.abs(this.alpha - this.palpha) > move_threshold) {
      deviceMoved();
    }
  }
  var deviceTurned = this.deviceTurned || window.deviceTurned;
  if (typeof deviceTurned === 'function') {
    var max_val = 0;
    // if (Math.abs(this.accelerationX) > max_val) {
    //     max_val = this.accelerationX;
    if (Math.abs(this.gamma) > max_val) {
      max_val = this.gamma;

      new_max_axis = 'x';
    }
    //    if (Math.abs(this.accelerationY) > max_val) {
    //      max_val = this.accelerationY;
    if (Math.abs(this.beta) > max_val) {
      max_val = this.beta;

      new_max_axis = 'y';
    }
    // if (Math.abs(this.accelerationZ) > max_val) {
    if (Math.abs(this.alpha) > max_val) {
      new_max_axis = 'z';
    }
    // if (old_max_axis !== '' && old_max_axis !== new_max_axis) {
    if (old_max_axis !== '' && Math.abs(max_val) >= 90) {
      deviceTurned(new_max_axis);

    }
    old_max_axis = new_max_axis;
  }
  var deviceShaken = this.deviceShaken || window.deviceShaken;
  if (typeof deviceShaken === 'function') {
    var accelerationChangeX;
    var accelerationChangeY;
    // Add accelerationChangeZ if acceleration change on Z is needed
    if (this.pAccelerationX !== null) {
      accelerationChangeX = Math.abs(this.accelerationX - this.pAccelerationX);
      accelerationChangeY = Math.abs(this.accelerationY - this.pAccelerationY);
    }
    if (accelerationChangeX + accelerationChangeY > shake_threshold) {
      deviceShaken();
    }
  }
};
```

**Comment by lmccart** [comment]
thanks @KouichiMatsuda, @OhJia  and I will take a look at this one this week. fyi, rather than describing the bug severity in the issue name, you can use the labels "severity:x" to tag them. this way we can see more clearly what the issue relates to from the title.

**Comment by KouichiMatsuda** [comment]
Thanks. I got it.

**Comment by OhJia** [comment]
It seems that when the e.alpha value changes the e.acceleration.x value also change and so on with the other two values (on my iPhone 6/iOS 8). It would be more accurate to separate out rotationXYZ from accelerationXYZ, but I wonder how useful accelerationXYZ would be then when used in sketches. Maybe it would be sufficient to update the description for accelerationXYZ. @johnpasquarello What do you think?

**Comment by johnpasquarello** [comment]
I can imagine that having the acceleration values might be nice for detecting something like a shake which doesn't inherently have any rotational movement. 

If it isn't enormously difficult it seems that having both rotationXYZ and accelerationXYZ would be the most flexible solution.

**Comment by lmccart** [comment]
@OhJia I think your intuition to stick with just accelerationXYZ for now makes sense. having both sets might just add confusion for beginners. we should just be very clear in the documentation about what this is actually measuring. do you want so submit a PR for this when you get a chance?

**Comment by KouichiMatsuda** [comment]
> Maybe it would be sufficient to update the description for accelerationXYZ.
In this case, the name of the system variables should be also changed from accelerarionXYZ to rotationXYZ.
This is because the "rotation" (degrees) is not "acceleration" (m/s^2).
The word "acceleration" is very confusing for beginners, including me.
When I used the current implementation of accelerationXYZ, I was wondering whey they are showing non-zero values even if I put my phone on the desk. In the case, "acceleration"XYZ should be zero.

**Comment by lmccart** [comment]
@KouichiMatsuda thanks for clarifying, I think previously I didn't fully understand the discrepancy as I haven't worked much with this particular functionality. @OhJia would changing the name to rotation make sense?

**Comment by KouichiMatsuda** [comment]
> I wonder how useful accelerationXYZ would be then when used in sketches.

Technically, if you expose the accelerationXYZ (m/s^2) to sketches, programmers can use them to guess what a user is doing, such as walking, jumping, taking a drive, and taking a train. This could cause very interesting mobile applications. 

Thanks,

**Comment by lmccart** [comment]
closed with https://github.com/processing/p5.js/pull/937
