### ISSUE TITLE
Slider arguments

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js#892]
I noticed today that sliders break if you pass in "incorrect" values for the min, max, and initial value parameters.  For example:

```javascript
// This renders the slider inoperable
createSlider(0, 100, 255);
```

Also, giving an initial value of 0 seems to break the starting value.

```javascript
// Initial value starts at 50
createSlider(0, 100, 0);
```

![screen shot 2015-09-05 at 11 49 15 am](https://cloud.githubusercontent.com/assets/191758/9700047/2965898e-53c4-11e5-9d5e-f80725969d8a.png)

**Comment by futuremarc** [comment]
I'll work on this right away!

**Comment by futuremarc** [comment]
I can't seem to recreate your first issue... works for me: 

<img width="1418" alt="screen shot 2015-09-05 at 12 10 43 pm" src="https://cloud.githubusercontent.com/assets/8646752/9700157/538028ca-53c7-11e5-95ec-a9a0581e2e95.png">

**Comment by futuremarc** [comment]
Seems like when the '0' is evaluating to `false`, so its never actually setting the value of the element if '0' is passed in! I'll send a PR

**Comment by lmccart** [comment]
fixed with https://github.com/processing/p5.js/pull/940
