### ISSUE TITLE
textWidth not working with custom font

### ISSUE THREAD

**Issue by lmccart** [processing/p5.js#894]
It works ok if the `textFont()` line is commented out.
```javascript
  var font;
  function preload() {
    font = loadFont("SourceSansPro-Regular.otf");
  };
  function setup() {
    createCanvas(240, 160);
    textFont(font);
    var s = "What's the width of this line?";
    var w = textWidth(s); // returns NaN
    text(s, 10, 30);
    rect(10, 30, w, 2);
    text("width: " + w, 10, 60);
  };
```

I've been tracking this down, the problem looks like it could be here:
https://github.com/processing/p5.js/blob/master/src/typography/p5.Font.js#L127

Maybe something having to do with calling `Math.min()` on an array?

**Comment by lmccart** [comment]
sorry, that was incorrect, those lines are fine. the issue is that the `xCoords` and `yCoords` arrays have NaN values in them. will investigate further...

**Comment by lmccart** [comment]
ok I've tracked it down to this line:
https://github.com/processing/p5.js/blob/master/src/typography/p5.Font.js#L122

but I'm not sure what change to make. it seems that `.advanceWidth` is not a property of the `charToGlyph` object returned sometimes.

**Comment by dhowe** [comment]
I see a different error when I debug this, specifically the attempt to reference _isOpenType() from a _pInst (line 1183):

         if (this._pInst._isOpenType())  

#899 fixes this, but seems a bit strange I'm not seeing the same issue as @lmmcart

**Comment by lmccart** [comment]
that removed the error message but I'm still seeing `NaN` for the example above. are you getting a number value?

**Comment by dhowe** [comment]
strange

![screen shot 2015-09-09 at 4 27 28 am](https://cloud.githubusercontent.com/assets/737638/9746556/2bdb5f24-56ab-11e5-8f43-31c5c2876802.png)

**Comment by lmccart** [comment]
interesting.. and this is with the most recent code pulled in? i wonder if i broke something in the variable rearrangement. or maybe it could have something to do with the font file i'm using (seems unlikely...)?

**Comment by dhowe** [comment]
I'm wondering if we are working with different versions of opentype:

├── opentype.js@0.4.9

**Comment by lmccart** [comment]
i believe so... 
<img width="500" alt="screen shot 2015-09-08 at 4 41 02 pm" src="https://cloud.githubusercontent.com/assets/191056/9746880/7477d270-5648-11e5-914d-eafc596ca3db.png">

i'm running the example out of /examples/p5.Font/custom so the font file should be the same too.

**Comment by dhowe** [comment]
Can you check with:
````
 $ npm ls | grep opentype

**Comment by dhowe** [comment]
So I've recreated the issue after pulling the current code, so it seems a recent change... I'll take a look

**Comment by lmccart** [comment]
fixed with https://github.com/processing/p5.js/pull/901
