### ISSUE TITLE
placement of type methods

### ISSUE THREAD

**Issue by lmccart** [processing/p5.js#897]
I noticed that [`/src/typography/attributes.js`](https://github.com/processing/p5.js/blob/master/src/core/p5.Renderer.js#L71) passes through arguments to call the underlying methods in [`/src/core/p5.Renderer.js`](https://github.com/processing/p5.js/blob/master/src/core/p5.Renderer.js#L71). However, the argument checking to determine whether the function is being called as a setter or getter is done in `p5.Renderer`. 

This causes a problem in cases like `textSize` (see [top level API call](https://github.com/processing/p5.js/blob/master/src/typography/attributes.js#L90) and [underlying method](https://github.com/processing/p5.js/blob/master/src/core/p5.Renderer.js#L123) where there is an argument specified. What's happening is this pass through actually passes an argument `[undefined]` so the [`arguments.length`](https://github.com/processing/p5.js/blob/master/src/core/p5.Renderer.js#L125) check fails because it has length one, even though no arg was intended. 

In https://github.com/processing/p5.js/pull/895 I fixed this by checking that `arguments[0]` is defined, but I think the better solution would be to move this checking to the top level. Alternatively, we could change the way we are calling the method so that `undefined` does not get wrapped into an arguments array.

This would align more closely to the way other p5 methods are called, where the arguments are first checked, then the p5.Renderer method is called. (example: [rect](https://github.com/processing/p5.js/blob/master/src/core/2d_primitives.js#L409)).

@dhowe thoughts? :)

**Comment by dhowe** [comment]
Uggh, that is sloppy. So the options are to a) do argument checking in the top-level function (as you suggest) or b) use apply to pass the arguments correctly:

  return this._graphics.textSize.apply(this._graphics, arguments);

My instinct is to prefer option b) though I"m happy to be overruled. With option a), we get the following code in the top-level call:

````javascript
p5.prototype.textSize = function(theSize) {
  if (arguments.length)
    return this._graphics.textSize(arguments[0]);
  else {
    return this._graphics.textSize();
  }
};
````

**Comment by lmccart** [comment]
yes, agree, let's go with b (using apply). I suggested option a because it matches what we have going on with methods like `triangle()` etc, but really when I was looking at it yesterday it seemed to make more sense to convert these so all drawing related stuff including param checking is encapsulated in the renderers and not handled by `p5.prototype`. 

so I suppose that is a larger project for another day, but if you want to ahead with converting the type methods using apply, that would be fantastic!

**Comment by lmccart** [comment]
closed with https://github.com/processing/p5.js/pull/900
