### ISSUE TITLE
Problem whit get() method?

### ISSUE THREAD

**Issue by andrusenn** [processing/p5.js#898]
Using get(x,y) on version 0.4.9 

Chrome error on line 13453 of p5.js:
"Uncaught TypeError: Cannot read property 'width' of undefined"
```javascript
p5.Renderer2D._copyHelper =
function (srcImage, sx, sy, sw, sh, dx, dy, dw, dh) {
  var s = srcImage.canvas.width / srcImage.width;
  this.drawingContext.drawImage(srcImage.canvas,
    s * sx, s * sy, s * sw, s * sh, dx, dy, dw, dh);
};
```
Firefox error on line 13478
"this.pixels undefined...

**Comment by lmccart** [comment]
could you please provide a minimal code example we can use to reproduce the problem and test again?

**Comment by andrusenn** [comment]
```javascript
function setup() {
    createCanvas(windowWidth, windowHeight);
    background(0);
}

function draw() {
    background(0);
    // Getting color on mouse position
    var col = get(mouseX,mouseY);
    // or 
    // var col = get(100,100);
    console.log(col);
}
```

**Comment by mariuswatz** [comment]
I am getting an identical error, and to make it stranger it works in one code setup (testing) and not another (obfuscated production code, maintained by another coder.) To be specific, these lines:

```
		p.loadPixels();
		var c=p.get(p.mouseX,p.mouseY);
```

Cause this message:

```
Uncaught TypeError: Cannot read property '2592360' of undefined
```

in this part of p5.Renderer2D.get():

```
if (w === 1 && h === 1){

    var imageData = this.drawingContext.getImageData(x * pd, y * pd, w, h);
    var data = imageData.data;
    var pixels = [];

    for (var i = 0; i < data.length; i += 4) {
      pixels.push(data[i], data[i+1], data[i+2], data[i+3]);
    }

    return pixels;
  }
```

Sidenote: It looks like the production code gets optimized to the statement below in lieu of the above. I'm not sure if that creates an issue, but that is the difference between the production and test setup.

```
if(1===c&&1===e)return[this.pixels[4*f*(b*this.width+a)],this.pixels[f*(4*(b*this.width+a)+1)],this.pixels[f*(4*(b*this.width+a)+2)],this.pixels[f*(4*(b*this.width+a)+3)]];
```

**Comment by lmccart** [comment]
@andrusenn the newest should resolve your issue.
@mariuswatz do you want to give this new version a try? I've posted a built copy here: http://p5js.org/test/p5.js

**Comment by jsphweid** [comment]
I wonder if get() can even be used like .get() (using as a method for a video capture, for instance).

As above, I've never really gotten get() to work but my use is something as basic and it doesn't work.

Say I have a var capture that is a webcam feed
`createCapture(VIDEO)`

and

`.size(320, 240)`

If I go:

`var c = capture.get(40, 40)`

and print c to the console, all I get is an array: [undefined, undefined, undefined, undefined]

**Comment by andrusenn** [comment]
Comment: Using test version (http://p5js.org/test/p5.js) return [undefined, undefined, undefined, undefined], calling loadPixels() before, fix the problem. But i guess that the goal is using only get()

```javascript
function draw(){
    background(255);
    loadPixels(); // Fill pixels array
    var c = get(mouseX,mouseY);
    console.log(c);
    // print [255,255,255,255]
}

```

**Comment by lmccart** [comment]
woops, thanks. adding this call by default in `get()` now.

**Comment by lmccart** [comment]
@jsphweid this newest patch should fix `get()` for `createCapture()` and images as well.
