### ISSUE TITLE
Add in angleMode (for switching between degrees and radians)

### ISSUE THREAD

**Issue by jeresig** [processing/p5.js#91]
We added in an `angleMode` global which had settings of `"degrees"` and `"radians"` (which would switch all angle-based operations between these two states). (By default the browser does all angles in radians, which was confusing for our users.)

The commit where we added this in Processing.js:
https://github.com/Khan/processing-js/commit/33744d1499da1e7219ebce60b3aff03a42c932a2

**Comment by Ikersfletch** [comment]
I just define a variable named "ratio" and give it the value of (PI/180) and then multiply my degrees by it. According to math and testing, it works
