### ISSUE TITLE
Can we put distribution files into the repo?

### ISSUE THREAD

**Issue by PeterDaveHello** [processing/p5.js#911]
Hi there, I'm Peter from [cdnjs](https://cdnjs.com), I found that since 0.4.7, there is no p5.min.js and p5.js in [lib](https://github.com/processing/p5.js/tree/master/lib) folder, I wonder if we can add it back, or create a dist folder, so that our auto-updater can grab latest p5.js easily! (The auto-updater fetch files by take each tag as a version and checkout the files in that commit)

By the way, you can browse p5.js on cdnjs by this url :smile: : https://cdnjs.com/#q=p5.js

**Comment by lmccart** [comment]
hi @PeterDaveHello, we had a really long discussion about this and have decided not to host the built file in the repo anymore as it causes a lot of confusion when we are merging in changes between releases. I thought that the auto-updated was based on npm, does it not pull from there? maybe I misunderstood. the built files are also available through the releases links, for example: https://github.com/processing/p5.js/releases/download/0.4.10/p5.js. does this help?

**Comment by PeterDaveHello** [comment]
yeah, we can use npm auto-update, currently via git, but not support GitHub release page.

**Comment by lmccart** [comment]
beautiful, npm auto-update would be ideal. do I need to change anything in the p5 config with cdnjs to make this work?

**Comment by PeterDaveHello** [comment]
I think a can take it, thanks!
