### ISSUE TITLE
RFC: rename this._graphics to this._renderer

### ISSUE THREAD

**Issue by indefinit** [processing/p5.js#913]
Wanted to get a gut check on this before embarking on a little rename/refactor adventure.  Does anyone have any objections to renaming the p5 Object property ```_graphics``` to ```_renderer``` ?  Since the refactor to p5.Renderer3D and p5.Renderer2D from their GraphicsXD equivalents, I think that referencing a _renderer property will keep the core consistent with the existing api as well as more readable to new contributors.

**Comment by lmccart** [comment]
yes, agree! this is a leftover from before we renamed to p5.RendererX.

**Comment by indefinit** [comment]
ok cool. PR coming up.

**Comment by lmccart** [comment]
closed with https://github.com/processing/p5.js/pull/914
