### ISSUE TITLE
Directory name incompatible with Windows filename restrictions

### ISSUE THREAD

**Issue by kennethdmiller3** [processing/p5.js#917]
On Windows, Git cannot pull the example "examples/3d/material/specular:ambient" due to the ':' embedded in the name.

This first showed up in commit 8676f796a092c74ab6a8da87ab08ddc6e08ecfb3

**Comment by lmccart** [comment]
whoops, should be fixed now. thanks!

**Comment by kennethdmiller3** [comment]
Fix confirmed. :)
