### ISSUE TITLE
Apparent bug loading an image

### ISSUE THREAD

**Issue by dfunkadelica** [processing/p5.js#921]
I'm having trouble loading an image.  I simplified the project to just load the image and it still wont load.  I tried the code in different configurations, following the reference library on the P5.js site, the reference here:  http://coursescript.com/notes/interactivecomputing/images/, as well as pasting in the example code and changing the name of the image to my own.  The path to my image also appears to be correct, the image is saved in my sketch folder.
```
var img;

function setup() {
  createCanvas(500, 500);
  img = loadImage("man_in_tree.png");
}

function draw() {
  background(255, 255, 255);
  image(img, 0, 0);
}
```
The image also doesn't load on the example for the [image](http://p5js.org/reference/#p5/imageMode) explanation pages

19413: Uncaught TypeError: Cannot read property '_imageMode' of undefined

**Comment by lmccart** [comment]
yikes, sorry about that! I just pushed a fix, I'll publish a new version tonight that incorporates this.

**Comment by therewasaguy** [comment]
possibly related to https://github.com/processing/p5.js/pull/914 ? I'm playing with this now, changing ``this._graphics`` to ``this._renderer`` in src/image/loading_displaying.js seems to be working

**Comment by therewasaguy** [comment]
ah thanks @lmccart !

**Comment by lmccart** [comment]
indeed, looks like a couple files got missed in the changeover, we should be all good now.

**Comment by JonMacPhers** [comment]
Hey I'm having this same issue and I'm not sure why? Can't seem to load any images, the examples you've posted aren't working either :'(
