### ISSUE TITLE
Recursion Example in environment is not an example of recursion

### ISSUE THREAD

**Issue by pippinbarr** [processing/p5.js#925]
The Recursion Example in the downloadable environment (v0.5.2) is an example of using function calls to repeat work, rather than recursion. This example does not seem to appear on the website.

I don't know if this is overly picky, but it might confuse some learners about the nature of recursion (I'm teaching a course that involves some introductory programming).

**Comment by lmccart** [comment]
thanks @pippinbarr, I've posted this on the editor repo https://github.com/processing/p5.js-editor/issues/157
