### ISSUE TITLE
canvas resolution on mobile browsers, safari and chrome

### ISSUE THREAD

**Issue by whichlight** [processing/p5.js#927]
Hey all! I don't think I saw this issue come up yet. Basically I'm working on sketches to work on desktop and mobile. The think I'm noticing is that the canvas resolution is different between mobile browsers. On Chrome things looked zoomed in, on safari it looks closer to how it would be on desktop. I see this through the difference of line width even thought strokeweight is the same.  I'm going to mess with setting canvas size vs styling the canvas to play with changing the resolution, but I thought I'd check in first to see if there was an attribute I should look at that I may be missing. My goal is to define parameters to make the sketches similar across screens.

Here is the sketch: https://github.com/whichlight/p5-fullscreen/blob/master/sketch.js

Ex. 

chrome: 
![img_2681](https://cloud.githubusercontent.com/assets/621697/9977734/a93eebe8-5edf-11e5-941d-34e1d1a9124d.PNG)
safari: 
![img_2682](https://cloud.githubusercontent.com/assets/621697/9977735/a93f01d2-5edf-11e5-959d-ae841618557a.PNG)

thank you!!

**Comment by whichlight** [comment]
I was reading a post on mobile game graphics and they mentioned viewport stuff. I can't seem to find the article now, but including this line in my header made the rendering in safari and chrome consistent. https://github.com/whichlight/p5-fullscreen/blob/master/index.html#L5. It may have been something else, but I'm not having the issue anymore.

**Comment by limzykenneth** [comment]
@whichlight I couldn't test this so I didn't reply to this before, but judging by your solution it does seem to be viewport problem. You might want a look at the various `<meta>` tags available which solved some problems, many of which I don't understand but still use as well. Bootstrap have a neat header section which I used for my own boilerplate even though I don't use Bootstrap.
