### ISSUE TITLE
text extends beyond bounding box 

### ISSUE THREAD

**Issue by dhowe** [processing/p5.js#928]
@xyfeng different behavior than Processing, yes? See below

![screen shot 2015-09-20 at 3 53 33 pm](https://cloud.githubusercontent.com/assets/737638/9979778/1ab77206-5fb0-11e5-9290-84c7e24a78ec.png)

````js
    var words = "How much digital information (or ‘data’) do you think exists about you? What kind of digital information or data has been created about your identity, your social networks, and your habits when you use digital services—like Facebook and Google—and devices, like your phone and computer? How does this connect to (and reflect) who you are and what you do online and offline? If someone wanted to investigate you, what could they figure out from the digital data that exists about you?";

    function setup() {

        createCanvas(400, 400);
        textFont("Arial", 18);
        background(200);
        rect(20, 50, 350, 230);
        text(words, 20, 50, 350, 230);
    }

**Comment by rddill-IBM** [comment]
Seeing same issue, running FireFox , Safari & Chrome on Mac. No difference between browsers.

**Comment by xyfeng** [comment]
Sorry for the late reply. I'm traveling in Europe this week.

I think we probably should change it to keep it consistence with processing. 
Here is the actual drawing function:
https://github.com/processing/p5.js/blob/master/src/core/p5.Renderer2D.js#L1052-L1155

When we rendering each line, we can add a compare function to see if it's outside of the box.

@dhowe, do you mind making this quick update? If you are busy, I can try to fix it sometime next week.

**Comment by dhowe** [comment]
no worries, got it

**Comment by lmccart** [comment]
fixed with https://github.com/processing/p5.js/pull/939
