### ISSUE TITLE
Additional p5.dom questions

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js#932]
@lmccart, @futuremarc, and I will be meeting this week to discuss p5.dom.  This issue is something of a follow up to #794, and likely needs to be broken out into separate issues.  But I'm using it as a way of keeping some notes as I prepare examples for my [A2Z](https://github.com/shiffman/A2Z-F15) class which makes heavy use of the DOM library.  After our discussion Tuesday, we can clean-up / re-organize the issues.

1.  Here are some dom elements we haven't wrapped yet to consider
  * `<textarea>`
  * `<input type="radio">radio button</input>`

2. The `changed()` event is working great.  However, I've noticed that for text input and sliders the native JS `change` event only fires when the browser considers to user to have "finished" their action, i.e. mouse released for a slider and hitting enter for an input field.  In the context of "creative coding sketching", it's often useful to register each and every key stroke and the slider's updates in real-time.  This can be achieved with `draw()`, but in my "no canvas", examples I'm doing the following:

```javascript
slider.elt.addEventListener('input', function() {
 // handle the slider "input" event
});

input.elt.addEventListener('input', function() {
  // handle each keystroke in text input
});
```

I'm not sure if we should map our `changed()` to `input` in this context (dangerous precedent) or create a new handler.

As I think of / discover more things I'll add to the comments here.

**Comment by brysonian** [comment]
Not sure if this goes here, but i had a thought the other day that we could use [cash.js](https://github.com/kenwheeler/cash) to do some of the dom tasks and gain some extra functionality, and also replace reqwest and use it for ajax. Main advantages would be to get a lot more jquery-compatable dom manipulation and shave off a few k of file size. Just a thought.

**Comment by shiffman** [comment]
We are meeting and resolving these, I am going to close this issue and open new individual ones for each item.
