### ISSUE TITLE
checkBox accessed via select() does not have checked() function available

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js#933]
This is working for me:

```javascript
var checkbox = createCheckbox('test checkbox');
println(checkbox.checked());
```

However, with the following:

```html
<input type = "checkbox" id = "test">test checkbox</input>
```

```javascript
var checkbox = select('#test');
println(checkbox.checked());
```

The `checked()` method is not recognized.

**Comment by lmccart** [comment]
The todo here is to detect which type of HTML element was found and wrap it in the corresponding p5.X (ie `p5.Element` as base case, but maybe `p5.MediaElement`, `p5.CheckBox`, etc).

**Comment by DarkPrince304** [comment]
Should this also be done for `createSelect()` and `createRadio()` as well?

I have implemented the `createRadio()` in this PR by the way #1015.
