### ISSUE TITLE
scale() doesn't scale 3d objects

### ISSUE THREAD

**Issue by mindofmatthew** [processing/p5.js#943]
I've noticed that the scale transformation doesn't seem to work on 3d objects. For example:

```
sphere(80, 80, 80);
```
and
```
scale(2, 2, 2);
sphere(80, 80, 80);
```
both display spheres of the same size. The lighting on the scaled sphere is a bit darker—is it possible that the camera's position is scaling along with the objects, but the lighting isn't or something?

**Comment by indefinit** [comment]
Hmm, at first glance it looks like the matrix mults aren't applied in the right order.  I'll dig deeper and let you know my findings.

**Comment by indefinit** [comment]
Ok, found and fixed the issue.  Looks like the bug had to do with arguments checking and their values not being passed into the matrix math func properly.  Once the PR is merged, you should be able to do:

```
scale(2,2,2);
sphere(80,80,80);
```  

or  similarly:
```
scale(2);
sphere(80);
```
with as-expected results.
See #945 for details.

**Comment by lmccart** [comment]
fixed with https://github.com/processing/p5.js/pull/945
