### ISSUE TITLE
load* functions can't use callbacks in preload()

### ISSUE THREAD

**Issue by Jared-Sprague** [processing/p5.js#949]
I know only load functions should be in `preload()`, but are success callbacks blocked by design too?

```javaScript
function preload() {  // preload() runs once
  img = loadImage('assets/laDefense.jpg', function() {console.log('loaded');});
}

// setup() will never run
```

**Comment by Jared-Sprague** [comment]
I found the root cause of this bug.  Almost done with a fix.

**Comment by lmccart** [comment]
awesome, thanks for looking into it!

**Comment by Jared-Sprague** [comment]
@lmccart See PR: https://github.com/processing/p5.js/pull/956

The problem was that the decrementPreload function was getting pushed on the argument list for load functions but when a callback was supplied, decrementPreload would never get called.  I added logic to the load functions to separate the success and failure callbacks from the decrementPreload function which will always be the last argment when in preload.

**Comment by Jared-Sprague** [comment]
@lmccart I added a bunch of new unit tests for loadFont and loadImage that tests calling these functions in preload with and without success callbacks.  There was actually a TODO in the font_loading.js unit test from @dhowe that said `// TODO: actually test loading from within preload`.  Well now that's done!

**Comment by Jared-Sprague** [comment]
Pull request was merged so closing this. Thanks!
