### ISSUE TITLE
Slow rendering with certain .ttf fonts

### ISSUE THREAD

**Issue by dhowe** [processing/p5.js#950]
A relatively minimal example from a student ([img](http://rednoise.org/~dhowe/ftp/01.png) and [font](http://rednoise.org/~dhowe/ftp/F2U_Scratch.ttf) links). This problem does not show up with several other .otf and .ttf fonts that I tried.

``` js
    var img1, move = 1, direction1 = 1, time = 0, font2;

    function preload() {
      img1 = loadImage("01.png");
      font2 = loadFont('F2U_Scratch.ttf');
    }

    function setup() {
      createCanvas(400, 600);
    }

    function draw() {
      background(200);
      image(img1, 50, 300 + move, 150, 850);
      move = move + direction1;
      if (move == 100 || move == -100)
        direction1 = direction1 * -1;

      fill(255);
      if (++time % 20 != 0 && time % 20 <= 10)
        strokeWeight(2);

      textFont(font2);
      textSize(50);
      stroke(255);
      text("GOOD NIGHT", 192, 470);
    }
```

Performance:

![screen shot 2015-09-29 at 7 15 34 pm](https://cloud.githubusercontent.com/assets/737638/10164733/d4ee5678-66ed-11e5-9491-fd3cdfa3f6cc.png)

**Comment by dhowe** [comment]
a first hypothesis is that the cause is the number and/or complexity of the font-paths (which will vary from font to font)

**Comment by Spongman** [comment]
yeah, i'm seeing 86% in `closePath` alone i doubt there's much that can be done here.

![image](https://user-images.githubusercontent.com/1088194/52871841-d2075380-30ff-11e9-8c2c-9dfa3d3cb104.png)

**Comment by dhowe** [comment]
that seems strange... I wonder if we can recreate a minimal test of this using only opentype.js

**Comment by Spongman** [comment]
maybe. i think it may be just that it's a really complicated font. i loaded it into the Windows system font viewer, and it pegs a CPU core just rendering a few lines of it.

**Comment by Qianqianye** [comment]
This issue is similar to the one at [3435](https://github.com/processing/p5.js/issues/3435), so I am closing it for organization purpose. Thank you!
