### ISSUE TITLE
Implement input event for slider and text input field

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js#953]
Continuing the discussion about `"change"` vs. `"input"` events from #932. . . 

We tried to think of a better name than `input` but in the end, we decided it's best to just use the "real" name that JavaScript uses.  So in addition to `changed()`, we'll also add `input()` as an event handler for slider and text input elements.   This will allow for "real-time" tracking of typing and sliding.

The alternative is making up event names like `slide()` (slid?) for a slider and `typed()` for text input.  Let's stick with `input()`?

**Comment by lmccart** [comment]
closed with https://github.com/processing/p5.js/pull/982
