### ISSUE TITLE
alert("message") causes issues

### ISSUE THREAD

**Issue by jonleung** [processing/p5.js#957]
[This code with an alert has issues](http://jsbin.com/yumape/13/edit?html,js,output)

- Press up to go to the top of the screen. When the piece resets, it keeps going up.

[This code WITHOUT an alert does NOT have issues](http://jsbin.com/yumape/14/edit?html,js,output)

- Press up to go to the top of the screen. When the piece resets, it DOES NOT keep going up.

**Comment by lmccart** [comment]
hey @jonleung could you please post a simplified example isolating the broken behavior? it's hard to debug a whole sketch. also, this sketch uses p5.play, could you remove this and have your example just show the error using p5.js library?

**Comment by jonleung** [comment]
Thanks @lmccart, sorry about the unclear issue!

[This JS Bin should illustrate the issue more clearly](http://jsbin.com/yumape/39/edit?html,js,output)

Here is a screenshot of what the JS Bin looks like:

![image](https://cloud.githubusercontent.com/assets/654941/10254329/c717b844-68f7-11e5-88c3-b4dbde342641.png)

**Comment by limzykenneth** [comment]
I see the problem on Chrome and Opera but not on Firefox and Safari so I think it's a Chromium based browser specific problem. Might be due to the way Chromium based browser handle alert popup and focus/blur of the p5 sketch I'm not sure.

**Comment by jonleung** [comment]
@limzykenneth @lmccart, is there something else that I might be able to use instead of `alert()` to easily display a message like "Game Over!" on the screen?

Thanks!

**Comment by limzykenneth** [comment]
@jonleung There's quite a few ways to do it if displaying it directly as a webpage element is something you would consider. Displaying as a message box might end up with the same problem you have here.

To simply display a message and I assume you want it to perhaps fade out or something similar, you can check out p5.dom.js, maybe the `createP()` function and `show()`, `hide()`. A DOM manipulation library like jQuery can also easily accomplish this but it depends on how familiar you are with it.

**Comment by lmccart** [comment]
thanks for the simplified example @jonleung. it looks like @limzykenneth is correct, this is due to chrome. in chrome, if you pop up an alert, the 'onblur' event is fired (meaning the page loses focus) until you click on the page again. if in that time you release the key, the 'keyup' event does not get received by the window because it's in the blurred/nonfocused state. I think @limzykenneth's suggestions above are good workarounds. alternatively, you could avoid using `keyIsDown()` and instead check using `keyIsPressed` and `key`, something like this:

```javascript
if (keyIsPressed) {
  if (key == UP_ARROW) {
    // move up
  }
  // etc
}

a little more here:
https://code.google.com/p/chromium/issues/detail?id=439484
