### ISSUE TITLE
No references available

### ISSUE THREAD

**Issue by KlarY** [processing/p5.js#961]
Neither API page in wiki nor Reference page in p5js.prg is available

**Comment by limzykenneth** [comment]
It is alright on my side. Both of them should be linking to the same page: http://p5js.org/reference/ 

Can you describe the problem a bit more? Do you get any errors or a blank page etc.?

**Comment by lmccart** [comment]
I'm not able to reproduce and no one else has mentioned problem so I'm closing this for now.
