### ISSUE TITLE
p5's debugger in browser-console bug when loading a string

### ISSUE THREAD

**Issue by fraco** [processing/p5.js#962]
Even though STRING LOADS CORRECTLY, the p5 debugger in browser's console prompts: 
p5.js says: It looks like there was a problem loading your text file. Try checking if the file path [assets/silentEs.txt] is correct, or running a local server.

Running local server in Chrome 45.0.2454.101, using Sublime Text 2, Mac OSX 10.9.5

![screen shot 2015-10-02 at 2 40 09 pm](https://cloud.githubusercontent.com/assets/1208842/10254854/62f5855e-6914-11e5-9395-8a57883e7692.png)

**Comment by Jared-Sprague** [comment]
The reason this is happening is because p5 defines a callback when the ready state of the file changes. Immediately after you try to open it it's not ready yet, so you get this error.  When the file is ready the ready state changes again and p5 parses the file into the array.  I think you can just ignore this error if your file is still loading.  But I think there should be some logic in loadStrings() that doesn't display this error when it's in the process of loading a file, and only when the file really couldn't be loaded.

```javascript
  req.open('GET', path, true);
  req.onreadystatechange = function () {
    if (req.readyState === 4 && (req.status === 200 )) {
      var arr = req.responseText.match(/[^\r\n]+/g);
      for (var k in arr) {
        ret[k] = arr[k];
      }
      if (typeof callback !== 'undefined') {
        callback(ret);
      }
      if ((callback !== decrementPreload) &&
        (typeof decrementPreload === 'function')) {
        decrementPreload();
      }
    }
    else{
      p5._friendlyFileLoadError(3,path);
    }
  };
```

**Comment by Jared-Sprague** [comment]
Did some more research.  Here are the ready states:
http://www.w3schools.com/ajax/ajax_xmlhttprequest_onreadystatechange.asp

I think right after you call `req.open()` the readystate == 2 || 3.   So I think this code should be revised to this:

```javascript
  req.open('GET', path, true);
  req.onreadystatechange = function () {
    if (req.readyState === 4)) {
      if (req.status === 200) {
        var arr = req.responseText.match(/[^\r\n]+/g);
        for (var k in arr) {
          ret[k] = arr[k];
        }
        if (typeof callback !== 'undefined') {
          callback(ret);
        }
        if ((callback !== decrementPreload) &&
          (typeof decrementPreload === 'function')) {
          decrementPreload();
        }
    } else{
      p5._friendlyFileLoadError(3,path);
    }
  };
```

**Comment by crhallberg** [comment]
Please do! I think you may be missing a closing bracket before your else, but it could just be my phone.

**Comment by Jared-Sprague** [comment]
Ok! I'll submit a PR for this as soon as my current PR is closed or merged.

**Comment by lmccart** [comment]
closed with https://github.com/processing/p5.js/pull/970/files
