### ISSUE TITLE
Serialserver implementation never closes port

### ISSUE THREAD

**Issue by tigoe** [processing/p5.js#964]
When you use p5.serialport in the editor (0.5.4 or later) the serialport in the serialserver is never closed when you stop the sketch. The problem with this is that, when you restart the sketch, the port you opened previously is still open. This causes problems for other applications attempting to open the port (like Arduino IDE). It also makes it impossible to choose a new port.

See p5.serialport PR #10 (https://github.com/vanevery/p5.serialport/pull/10) for an example of this in action.

**Comment by lmccart** [comment]
reposted here https://github.com/processing/p5.js-editor/issues/168
