### ISSUE TITLE
All canvases have the same id

### ISSUE THREAD

**Issue by ericsoco** [processing/p5.js#965]
When creating multiple p5 instances on one page (using "instance mode"), each of their canvases is given the same id, `defaultCanvas`. While it's easy enough to set the id of each canvas (`p.canvas.id = 'foo'), having multiple DOM elements with the same id might cause unexpected side effects.

Maybe the `defaultCanvas` id should iterate automatically (e.g. `p5Canvas1`, `p5Canvas2`) as new canvases are created? Should definitely leave `defaultCanvas` alone tho, to avoid breaking existing non-instance mode sketches.

**Comment by lmccart** [comment]
note that this only works in 2d mode, I didn't want to touch 3d mode until we've fixed #998. ideally it could be addressed at the same time.
