### ISSUE TITLE
Update documentation statements that say you can't use callbacks in preload()

### ISSUE THREAD

**Issue by Jared-Sprague** [processing/p5.js#966]
Now that my PR https://github.com/processing/p5.js/pull/956 has been merged, and success callbacks can now be used in preload(),  we can update the documentation that says you can't.  For example:  http://p5js.org/reference/#/p5/loadJSON  remove the "Outside preload(), you may supply a callback function to handle the object" line.  

I'll update the docs and submit a PR soon!

**Comment by Jared-Sprague** [comment]
Pull request: https://github.com/processing/p5.js/pull/967

**Comment by lmccart** [comment]
closed with #967
