### ISSUE TITLE
Setting headers for httpGet() / httpDo()

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js#968]
This I think follows up on the discussion in #385.   We added `httpGet()`, `httpPost()`, and `httpDo()` to handle generic HTTP Requests and the functions are working great for me.  For one of my examples for [A2Z week 4](https://github.com/shiffman/A2Z-F15/tree/gh-pages/week4) I need to add a header to the request for authentication.  I'm able to get this to work with JQuery as follows (the API here is [Clarifai](http://www.clarifai.com/)).

``` javascript
  $.ajax({
    url: 'https://api.clarifai.com/v1/tag/',
    type: 'GET',
    beforeSend: function(xhr) {
      xhr.setRequestHeader('Authorization', 'Bearer ACCESS_TOKEN');
    },
    data: {
      url: 'http://www.clarifai.com/img/metro-north.jpg'
    },
    success: function (response) { 
      console.log(response);
    },
    error: function (err) { 
      console.log(err);
    },
  });
```

`httpDo()` does everything above with the exception of `beforeSend`.   My question is:

Is an optional argument for headers something we should add to our API or is this a scenario beyond the scope of p5?

**Comment by lmccart** [comment]
I think potentially we could add it only to `httpDo()` which is already our base case http method (the put and get methods call this under the hood). we could also think about supporting passing in an arg object similar to jquery just for this one. but I do worry that might be opening a large can of wormy api discussions...

**Comment by brysonian** [comment]
Maybe passing an object just treats it as a direct wrapper for `reqwest`? I also notice it is missing an error callback, if something goes wrong in the request it'll be really hard to debug. Should we add another callback? Break existing api and pass the first arg as err (which is consistent with node-style) or maybe just pass a second success arg?

**Comment by shiffman** [comment]
I think if reqwest accepts an object, this could be something of a hidden advanced feature, i.e. if you want these advanced features just make the object yourself and pass it in.  We could do this with `httpDo()` only as @lmccart suggests.  

I think having an optional "error" callback would be useful.  Is there a discussion about this with `loadJSON()` or does this already exist and I just missed it (as often seems to be the case)?

I can open a separate issue, and would suggest something like:

```javascript
loadJSON(url, callback); 
loadJSON(url, callback, errorCallback);  // 3rd arg optional
```

**Comment by lmccart** [comment]
I think this makes sense!

**Comment by vorg** [comment]
It seems like  https://github.com/processing/p5.js/commit/779318ab021a6073f2218617ac1579838111fe73 added support for objects but there is still no way to set HTTP headers like Accept or Content-Type?

**Comment by brysonian** [comment]
I was thinking about p5 and http this the other day. Perhaps it is time to replace reqwest with a newer API like [fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API)? We could use [github's polyfill](https://github.com/github/fetch) for the couple of browsers that don't have it yet. Only catch is that we would also need a promise polyfill like [this](https://github.com/taylorhakes/promise-polyfill) though having promises around isn't such a bad idea anyway. 

Doesn't address your immediate concern @vorg but it would be easy to fold that in.

**Comment by lmccart** [comment]
@brysonian I think this makes sense, promises might solve some of our preload() woes as well. I'm opening a new issue to look at this.

@vorg I'll take a look into header support as well.

**Comment by lmccart** [comment]
this will be possible in the next release https://github.com/processing/p5.js/pull/1812
