### ISSUE TITLE
Can I add .idea to .gitignore?

### ISSUE THREAD

**Issue by Jared-Sprague** [processing/p5.js#969]
Anyone mind if I add .idea to .gitignore for WebStorm users?

**Comment by lmccart** [comment]
yes I think this is fine, go for it

**Comment by lmccart** [comment]
closed with https://github.com/processing/p5.js/pull/970/files

**Comment by kadamwhite** [comment]
This is a very good idea for popular editors like sublime and webstorm, but for future reference custom ignore files can be added to the file `.git/info/exclude` within the project's `.git` folder

**Comment by lmccart** [comment]
ah cool, thanks!
