### ISSUE TITLE
make sure that mouseX/Y and touchX/Y coords align and that events are falling back to mouse or touch

### ISSUE THREAD

**Issue by Jared-Sprague** [processing/p5.js#972]
I've run into this a few times: create something interactive in p5, then I have to put some hacky logic or an external library to decide to use touchX, touchY or mouseX, mouseY. 

It would be suuuuper nice if p5 had a global isMobile similar to:
https://github.com/kaimallea/isMobile

Or is there another method that people use for detecting mobile devices in p5 that I'm missing?

I'm happy to volunteer if this is something people think would be useful.

Thanks!

**Comment by lmccart** [comment]
the way it's actually supposed to work is, mouseX/Y and touchX/Y and mousePressed/touchStarted, mouseDragged/touchMoved, mouseReleased/touchEnded should be interchangeable. so if you use touchX/Y in your sketch, it should fallback to mouseX/Y when touch is not available. if you define mousePressed, this should be fired on touchStarted as well as long as touchStarted is not defined also, etc. at one point this was working but it may have gotten broken at some point.

in the shortterm, you could write code like this:
```javascript
function draw() {
  x = mouseX || touchX;
  y = mouseY || touchY;
  ellipse(x, y, 50, 50);
}

var mousePressed = touchStarted = function() {
  print("pressed or touched");
}
```

I'm not sure about the isMobile variable. I suppose it wouldn't hurt, but I'd really like to focus on getting the current API fully functional before we extend it further. in this case, that would mean getting the mouse/touch fallbacks to work properly.

**Comment by Jared-Sprague** [comment]
@lmccart Thanks for the reply!  Yeah if when using a mouse touchX/Y === mouseX/Y  then it would be no problem, but their values we're often different when using a mouse.  Which is why I started only using touchX/Y if I was on a mobile device and mouseX/Y if not.

**Comment by lmccart** [comment]
I'm updating the title to reflect the fact that mouseX/Y === touchX/Y needs to be checked and probably fixed.
