### ISSUE TITLE
Possible Bug in somewhere in commit e5d82c9722fc2d328207c718cfd90e07191989e8

### ISSUE THREAD

**Issue by Jared-Sprague** [processing/p5.js#976]
@lmccart I started getting images drawing outside of the canvas (see attached screenshot) and an error when I call text() that says "TypeError: this._renderer.textLeading.apply is not a function".

I started reverting commits until I found the one that fixes both problems when I revert it:
https://github.com/processing/p5.js/commit/e5d82c9722fc2d328207c718cfd90e07191989e8

I will continue to try to debug this.

![screenshot from 2015-10-05 15 55 05](https://cloud.githubusercontent.com/assets/3926730/10291758/815e8d76-6b79-11e5-9fe6-bbee0337a5e7.png)

**Comment by lmccart** [comment]
whoops thats my bad, let me push a fix, on sec

**Comment by lmccart** [comment]
can you try again now with the latest? I think it should be fixed... if not, will you send me the example code you're using and I can look into it further.

**Comment by Jared-Sprague** [comment]
@lmccart 
Just prepending the mapping with a '_' fixed the problem for me:

```JavaScript
  for(var prop in lastS){
    this._renderer['_' + prop] = lastS[prop];
  }
```

Is that the change you pushed?

**Comment by Jared-Sprague** [comment]
@lmccart Yep your change fixes it! I guess it's exactly the same thing I did only in push instead of pop, as long as they match :)
