### ISSUE TITLE
deviceMoved in 0.4.14 might be against the reference or the reference should be changed.

### ISSUE THREAD

**Issue by KouichiMatsuda** [processing/p5.js#984]
Thanks to the latest implementation, rotationXYZ works well. 
However, the implementation of deviceMoved() might be against the reference or are you going to change the reference?

The comments in the code and the reference says as follows:
```javascript
/**
 * The deviceMoved() function is called when the devices orientation changes
 * by more than the threshold value.
```
However, the implementation of deviceMoved() is called when the device orientation changes but it's **also called** when the device orientation **doesn't change** AND the device **moves along** with x, y, or z axis. 

I think one solution is to rewrite the reference as follows:
"The deviceMoved() function is called when the devices **move** by more than the threshold value."

I think this might be a good idea but in this case one bad news is that deviceShaken() might provide almost same behavior as that of deviceMoved (I'll describe this later).

You can use the following code to check "deviceMoved() is called when the orientation **doesn't** change". After loading it, when you move the device along with x, y, or z axis, the ball moves. For instance, you put your phone on a desk and hit its top side by a finger. The ball moves even if the phone **orientation** doesn't change.

```javascript
// DeviceMoved
var x, y;

function setup() {
  devicePixelScaling(false);
  createCanvas(windowWidth, windowHeight);
  x = width / 2; y = height / 2; // center position
  fill("red");
}

function draw() {

}

function deviceMoved(){
  x += rotationY; // Moves to X
  y += rotationX; // Moved to Y
  ellipse(x, y, 80, 80); // Draw a ball
}
```

This is because the code for deviceMoved() in p5.js might do that:

```javascript
p5.prototype._ondeviceorientation = function (e) {
  this._setProperty('rotationX', e.beta);
  this._setProperty('rotationY', e.gamma);
  this._setProperty('rotationZ', e.alpha);
  this._handleMotion();
};
p5.prototype._ondevicemotion = function (e) {
  this._setProperty('accelerationX', e.acceleration.x * 2);
  this._setProperty('accelerationY', e.acceleration.y * 2);
  this._setProperty('accelerationZ', e.acceleration.z * 2);
  this._handleMotion();
};
p5.prototype._handleMotion = function() {
             ... snip
  var deviceMoved = this.deviceMoved || window.deviceMoved;
  if (typeof deviceMoved === 'function') {
    if (Math.abs(this.accelerationX - this.pAccelerationX) > move_threshold ||
      Math.abs(this.accelerationY - this.pAccelerationY) > move_threshold ||
      Math.abs(this.accelerationZ - this.pAccelerationZ) > move_threshold) {
      deviceMoved();
    }
  }
  var deviceTurned = this.deviceTurned || window.deviceTurned;
          ... snip
```
The code in _handleMotion (deviceMoved part) still checks accelerationXYZ **not** rotationXYZ. This might cause the  "deviceMoved() is called when the orientation **doesn't** change." 

I think rewriting the reference as I did might be a good idea but, in this case, deviceShaken() provides almost same behavior. You can use deviceShaken() as "deviceMoved" by just adding  "setShakeThreshold(0.5);" in setup(). The 0.5 is the  default threshold value for deviveMoved(). The following is the sample code. This program can roll a boll by rotating your phone even if you don't "shake" it. This behavior might be almost same as deviceMoved(). 

```javascript
// DeviceShaken
var x, y;

function setup() {
  devicePixelScaling(false);
  createCanvas(windowWidth, windowHeight);
  x = width / 2; y = height / 2; // center position
  fill("red");
  setShakeThreshold(0.5);  // *** Please note that this line is added 
}

function draw() {

}

function deviceShaken(){ // *** Please note that the function name is changed ***
  x += rotationY; // Moves to X
  y += rotationX; // Moved to Y
  ellipse(x, y, 80, 80); // Draw a ball
}
```
This is because the code of deviceMoved() and deviceShake() is almost same.
```javascript
p5.prototype._handleMotion = function() {
             ... snip
  var deviceMoved = this.deviceMoved || window.deviceMoved;
  if (typeof deviceMoved === 'function') {
    if (Math.abs(this.accelerationX - this.pAccelerationX) > move_threshold ||
      Math.abs(this.accelerationY - this.pAccelerationY) > move_threshold ||
      Math.abs(this.accelerationZ - this.pAccelerationZ) > move_threshold) {
      deviceMoved();
    }
  }
             ... snip
  var deviceShaken = this.deviceShaken || window.deviceShaken;
  if (typeof deviceShaken === 'function') {
    var accelerationChangeX;
    var accelerationChangeY;
    // Add accelerationChangeZ if acceleration change on Z is needed
    if (this.pAccelerationX !== null) {
      accelerationChangeX = Math.abs(this.accelerationX - this.pAccelerationX);
      accelerationChangeY = Math.abs(this.accelerationY - this.pAccelerationY);
    }
    if (accelerationChangeX + accelerationChangeY > shake_threshold) {
      deviceShaken();
    }
```
In this code, if "move_thresthold" and "shake_threshold" hold the same value, such as 0.5, both the condition statements return **true** in most cases.
```javascript
In deviceMoved,
     if (Math.abs(this.accelerationX - this.pAccelerationX) > move_threshold
In deviceShaken,
     if (accelerationChangeX + accelerationChangeY > shake_threshold
```

I think that this type of "rotation" behavior could be a kind of "shaken" behavior (unfortunately I'm not a native speaker. I might be incorrect). So I think there might be two solutions:

1. Rewriting the reference to change "devices orientation changes" to "devices move"
2. Rewriting the code for deiviceMoved() by using rotationXYZ.

I think Solution 1 might not be so bad idea if you can ignore that deviceMoved() and deviceShaken() have a similar meaning. Also, it might be difficult to distill only "shaken behaviors" from those of users by phone.

Thank you for your reading my long report.
 
Regards,

**Comment by limzykenneth** [comment]
I agree with going for solution 1 as I think that is a bit more intuitive while rotating the device also often triggers the accelerometer to register movement as well.

I'm thinking maybe deviceShaken can be slightly rewritten so it actually looks for back and forth movement instead of just a threshold acceleration value.

**Comment by KouichiMatsuda** [comment]
Thank you for your comment.

In solution 1, deviceMoved should be modified because `move_threshold` in current implementation might lose its meaning. I think the first intention of **`move_threshold`** is to specify the angle of rotation per a frame (**in degrees**). So if a programmer wants to call deviceMoved() when a user tilts a phone greatly, the programmer can just specify a large value to `move_threshold` using setMoveThreshold().

However, the current implementation might not be able to do such a fine control intuitively because I think the following condition statement doesn't allow that.
````javascript
In deviceMoved,
     if (Math.abs(this.accelerationX - this.pAccelerationX) > move_threshold
````
`this.accelerationX` and `this.pAccelerationX` is in **m/s^2, not** degree nor **angular** acceleration. So if a programmer wants to realize what I mentioned in the above, she/he needs to convert the angle of rotation, which she/he wants to specify, into m/s^2 by her/his hand. This might not be intuitive, I think.

I think there are three solutions on this issue:

 1.1 p5.js code does the conversion in behalf of the programmer.
 1.2 The code for deviceMoved should be modified as something like:
````javascript
  var deviceMoved = this.deviceMoved || window.deviceMoved;
  if (typeof deviceMoved === 'function') {
    if (Math.abs(this.accelerationX - this.pAccelerationX) > move_threshold ||
      Math.abs(this.accelerationY - this.pAccelerationY) > move_threshold ||
      Math.abs(this.accelerationZ - this.pAccelerationZ) > move_threshold) {
      deviceMoved();
    }
    if (Math.abs(this.rotationX - this.pRotationX) > rotate_threshold ||
      Math.abs(this.rotationY - this.pRotationY) > rotate_threshold ||
      Math.abs(this.rotationZ - this.pRotationZ) > rotate_threshold) {
      deviceMoved();
  }
````
 1.3 p5.js gives up supporting such a fine control on deviceMoved().

In solution 1.2, setMoveThreshold() might have two arguments to specify `move_threshold` and `rotate_threshold`.

Regards,

**Comment by limzykenneth** [comment]
Hmm...I think that `move_threshold` is working as I expected it to which is setting a threshold for detecting of a device has moved ie. whether it has moved along a table flat or being rotated. The overall effect is when the device is moved, the amount which it have moved (the linear acceleration) will be compared against the threshold and if it is greater, call the function.

It is interesting to think of adding the rotation logic to it but having the user set 2 variables for the threshold can be a bit too much. I think maybe it can be condensed into a single threshold value which converts internally. However I wonder if the rotation comparison logic is really needed:

```
if (Math.abs(this.rotationX - this.pRotationX) > rotate_threshold ||
      Math.abs(this.rotationY - this.pRotationY) > rotate_threshold ||
      Math.abs(this.rotationZ - this.pRotationZ) > rotate_threshold) {
      deviceMoved();
  }
```

At least on lower threshold, the deviceMoved function will be called regardless of whether it is moved or rotated. At higher threshold, then maybe the rotation not triggering this event is intended.

I'm not sure, let me know what you think.

**Comment by KouichiMatsuda** [comment]
Sorry, my post was a little bit confusing.
 
The current implementation deviceMoved() is called by two type of phone's movement.
(1) translation along with x, y, or z axis
(2) rotation around x, y, z axis.
 
My point is how move_threshold behaves among multiple devices. The move_threshold equally works in (1) among multiple devices. However it might not equally work in (2) among them.
 
This is because a rotational acceleration (not "angular" acceleration) changes depending on its radius of rotation. For instance, if you rotates a device by 60 degrees, the acceleration generated by a tablet whose width is 18cm (radius is 9cm?) might be larger than of phone whose width is 6 cm(radisu is 3cm?). 

In addition, the location of accelerometer on a device might be varied among devices. For instance, iPad mounts the sensor on its right-side, not in its center. Its location would also  affect the acceleration. The case where it is mounted on the center of a device causes different results than the case mounted on the right-side of a device in rotating a device in a same degree . 
 
This means that if you specify a value in move_threshold, when deviceMoved() is called might be varied from device to device in rotating them.  In a single device, move_threshold would work well as a programmer expects but the same move_threshold value might works differently in multiple devices (lower value works well but higher value might case this issue).
 
The current implementation might cause a single application behaves differently in multiple devices.
 
So I think it might be OK to ignore issue on (2), i.e. a meaning of move_threshold is device-size-dependent, because it's often cases that a programmer wants to know when a device is moved.
 
In such a sense, the following my solution 1.2 was incorrect. The first condition statement could easily override the second one. So the second condition does not make sense in case of using it with accelerationXYZ.
 
````JavaScript
  var deviceMoved = this.deviceMoved || window.deviceMoved;
  if (typeof deviceMoved === 'function') {
    if (Math.abs(this.accelerationX - this.pAccelerationX) > move_threshold || // *** 1st condition
      Math.abs(this.accelerationY - this.pAccelerationY) > move_threshold ||
      Math.abs(this.accelerationZ - this.pAccelerationZ) > move_threshold) {
      deviceMoved();
    }
    if (Math.abs(this.rotationX - this.pRotationX) > rotate_threshold || // ** 2nd condition
      Math.abs(this.rotationY - this.pRotationY) > rotate_threshold ||
      Math.abs(this.rotationZ - this.pRotationZ) > rotate_threshold) {
      deviceMoved();
  }
````
 
If you are interested in a system function which can provide a fine control on a device's rotation movement. You can provide devideRotated() or deviceTiled() and a system variable rotate_threshold or tilt_threshold. As you can imagine, the code is something like the following.
 
````JavaScript
  var deviceRotated = this.deviceRotated || window.deviceRotated;
  if (typeof deviceRotated === 'function') {
    if (Math.abs(this.rotationX - this.pRotationX) > rotate_threshold ||
      Math.abs(this.rotationY - this.pRotationY) > rotate_threshold ||
      Math.abs(this.rotationZ - this.pRotationZ) > rotate_threshold) {
      deviceRotated();
  }
````
 
In this case, rotate_threshold equally works among multiple devices, even if the size of a device is different.

Regards,

**Comment by limzykenneth** [comment]
Sorry! I get what you mean now. Your analysis is correct and I think it is ok to ignore the issue on (2) as well because we either change the implementation of deviceMoved to look for rotation (which I think is confusing) or do some extra checks (which will complicate matters even more). 

I think in most use cases the deviceMoved method should work as intended, exception being when the device is only tilted as you mentioned. It shouldn't be a big problem but I think the documentation really needs changing as it is incorrect.

I'm quite happy to implement the deviceRotated method but I wonder if this method is something a user can readily write on their own and doesn't require p5 to implement it. I mean most likely is that a user is just going to look for rotation along one axis so they can just do `abs(rotationX-pRotationX) > threshold` without checking the other axis to complicate matters. I might be second guessing I'm not sure. : )

**Comment by KouichiMatsuda** [comment]
Thanks. You should write the document to help beginners not to make them confusing.

About deviceRotated(), I'm also wondering. 
I think p5.js is still young, its version is still 0.4.15, so it has many chances to introduce a system function such as, deviceRoated() in the future. Currently it needs more considerations and p5.js has other many issues, such as #958 :-). If the need comes, we should discuss it, again.

Regards,

**Comment by lmccart** [comment]
closed with https://github.com/processing/p5.js/pull/992
