### ISSUE TITLE
Missing features in WebGL

### ISSUE THREAD

**Issue by ericsoco** [processing/p5.js#986]
So, I just tried using 'webgl' as my renderer, and stumbled across some things:

- `blendMode` is not supported.
- `clear` is not supported....

Then I started googling, and found out that WebGL in p5js is apparently like 24 hours old?
So: :fireworks: :+1: :100: :exclamation:

But also --

- maybe it would be good to point to [this page](https://github.com/processing/p5.js/wiki/Getting-started-with-WebGL-in-p5) from [this page](http://p5js.org/reference/#/p5/createCanvas)
- and maybe also to have a blog posty kind of thing talking about what is and is not supported in WebGL (tho of course this is changing rapidly I assume?)
- and maybe also to have a more verbose error message that's better for people who aren't familiar with the concept of renderers; currently I see `this._renderer.clear is not a function`, but `'webgl' does not support 'clear'` might be better.

One last note, this thing is open source amirite? And I know JS and Processing, so...maybe I should assign this to myself :neckbeard: Will see if I can get to this before anyone else does.

Congrats on p5js (I'm a new convert) and on WebGL up in it!

**Comment by indefinit** [comment]
Hi Eric,

Thanks for your interest in Webgl! Indeed the official Webgl renderer is still in its early stages and also in rapid development.  As such if you see a feature like blendMode or clear, that you'd like to tackle, by all means go at it and submit a PR.  We've tried our best to have feature parity across 2d and 3d with friendly error messages as fallback for those functions not yet implemented in Webgl but it looks like this one slipped through the cracks.

I added a section at the end of the getting started doc with the big ticket items- obj import, custom shaders, more lighting, etc. but it's really meant to show a high level overview, and hopefully a starting point for additional 3d features in the future.  We definitely welcome small feature additions as well as bug fixes.

**Comment by lmccart** [comment]
thanks for your enthusiasm @ericsoco. as @indefinit mentions, the section at the end of the getting started doc outlines the roadmap and todos. for organization sake, I would suggest we close this issue as it is very general, and allow the 3D functionality to continue to develop for a bit before logging issues for specific missing items unless they are bugs.

**Comment by indefinit** [comment]
Works for me.

On Mon, Oct 12, 2015 at 2:48 PM, Lauren McCarthy <notifications@github.com>
wrote:

> thanks for your enthusiasm @ericsoco <https://github.com/ericsoco>. as
> @indefinit <https://github.com/indefinit> mentions, the section at the
> end of the getting started doc outlines the roadmap and todos. for
> organization sake, I would suggest we close this issue as it is very
> general, and allow the 3D functionality to continue to develop for a bit
> before logging issues for specific missing items unless they are bugs.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/processing/p5.js/issues/986#issuecomment-147489256>.
>



-- 

Kevin Siwoff
// http://kevinsiwoff.com // Instagram: @kevinsiwoff
<http://instagram.com/kevinsiwoff/> //
