### ISSUE TITLE
text() call generates error

### ISSUE THREAD

**Issue by mikegomezg** [processing/p5.js#987]
Why do I get this result... 

![image](https://cloud.githubusercontent.com/assets/6961984/10319607/188dafce-6c3d-11e5-98ad-1d70a0758f06.png)

...from this code: 

function setup() {
    createCanvas(200, 200);
    fill(0);
    textSize(12);
    textFont("Arial");
    text("Times New Roman", 12, 30);
}

**Comment by lmccart** [comment]
this should be fixed in the most recent version, coming up in just a few minutes, stand by!

**Comment by mikegomezg** [comment]
Thank you!
