### ISSUE TITLE
p5.dom event cancellation

### ISSUE THREAD

**Issue by kylemcdonald** [processing/p5.js#988]
I would like to keep an event in an child element from propagating to it's parent element. I tried returning false from the child element callback, as in the following example:

```html
<p id="parent">Hello <span id="child">World</span></p>
<script>
function setup() {
  noCanvas();
  select('#parent').mousePressed(function() {
    console.log('parent');
  })
  select('#child').mousePressed(function() {
    console.log('child');
    return false;
  })
}
</script>
```

But when I click on the child I see in the console:

```
child
parent
```

**Comment by sepans** [comment]
I don't know if p5.js provides another mechanism to do that but pure Javascript's ``e.stopPropagation()`` should work:
<pre>
select('#child').mousePressed(function(e) {
    console.log('child');
    e.stopPropagation();
    
 })
</pre>
[code pen](http://codepen.io/sepans/pen/JYNBPa)

**Comment by kylemcdonald** [comment]
that works! when the solution is that short, i agree that p5 doesn't need to provide another mechanism.

**Comment by futuremarc** [comment]
great! thanks for the solution as well
