### ISSUE TITLE
Element.position() should support AUTO

### ISSUE THREAD

**Issue by futuremarc** [processing/p5.js#990]

**Comment by futuremarc** [comment]
createImg() as well

**Comment by shiffman** [comment]
Just making a note that the syntax I was trying to do is:

```javascript
var img = createImg(url);
img.size(200, AUTO);
```

Is this right?

**Comment by futuremarc** [comment]
yes!

**Comment by lmccart** [comment]
this actually does work, it's just that at the point you're calling it in the example above, the image hasn't loaded yet and so it registers width/height as 0 still. if you pass the size() call in through a callback function, it behaves properly:

```javascript
function setup() {
  noCanvas();
  var img = createImg('https://i.ytimg.com/vi/tntOCGkgt98/maxresdefault.jpg', function() {
    img.size(200, AUTO);
  });
}
```

**Comment by shiffman** [comment]
ah, of course, thanks @lmccart
