### ISSUE TITLE
mouseIsPressed is not understood correctly by chrome

### ISSUE THREAD

**Issue by swirly** [processing/p5.js#996]
Try the two versions of the same code for example 
-------------------
function mousePressed() {
        if (mouseButton == LEFT ) {
            ellipse(mouseX,mouseY,random(40,150),80);
        }
        if (mouseButton == RIGHT ) {
            background(random(180,255),random(180,255),random(180,255));
        }
}
--------------------
works as intended in chrome and firefox
but
--------------------
function draw() {
    // Cette fonction sera utilisée pour dessiner sur l'espace de dessin
    if (mouseIsPressed) {
        if (mouseButton == LEFT ) {
            ellipse(mouseX,mouseY,random(40,150),80);
        }
        if (mouseButton == RIGHT ) {
            background(random(180,255),random(180,255),random(180,255));
        }
    }    
}
----------
works as intended in firefox but not at all in chrome. In chrome, mouseIsPressed stay true for a while on left mouse button, and stay as long as you don't reclick for right button !!!!

Maybe it's a chrome specific javascript problem. But because I use brackets for the previews with my pupils, it's annoying.

**Comment by swirly** [comment]
more information.

It seems that chrome is "very" sensitive. When fireofx finds "one" click, chromes find 4 ou 5, 3 if i'm particulary light on the mouse button. wooh!

for the right click that was really stuck, adding a 

oncontextmenu=" event.preventDefault();"

on body prevents the contextual menu from popping out and make the right click behaves as the left (3 to 5 colors change instead of one)

**Comment by lmccart** [comment]
`mouseIsPressed` is a variable that changes state depending on whether the mouse is pressed. since draw runs at 60fps by default, it may stay true for multiple calls to draw. if you want a one time event to occur, it's best to use the `mousePressed()` function, that is fired once per mouse press.
http://p5js.org/reference/#p5/mousePressed

**Comment by swirly** [comment]
Agreed. But for the right click, it stays to true as long as you don't click once more, wich is not a fps problem.

This really should be treated as a bug.

**Comment by lmccart** [comment]
ah I see. it looks like in chrome, right clicking opens the context menu, which takes focus away from the program. when I added an attribute to prevent the menu to my body tag, all seemed to work ok: `<body oncontextmenu="return false;">`
