### ISSUE TITLE
Normal mapping for webgl sphere object is not correct

### ISSUE THREAD

**Issue by questacian** [processing/p5.js#999]
Discovered a problem when trying to map a globe texture to the webgl sphere primitive.

Normal map does not behave correctly at seam.

When mapping a simple grid texture to the sphere, the normal map shows up like this:

<img width="597" alt="screen shot 2015-10-12 at 10 36 06 pm" src="https://cloud.githubusercontent.com/assets/14141819/10444295/f198aa18-7132-11e5-8191-4d414c5c27b2.png">
<img width="599" alt="screen shot 2015-10-12 at 10 35 53 pm" src="https://cloud.githubusercontent.com/assets/14141819/10444297/f3dd2d80-7132-11e5-8b7a-e96a3629a873.png">

Code:

```
var img;

function setup() {
  createCanvas(600, 600, WEBGL);
  img = loadImage("assets/grid.jpg");
}

function draw() {
  background(0);
  texture(img);
  sphere(300, 50)
}
```

**Comment by indefinit** [comment]
@questacian thanks for filing.  I'll take a look and get back to you.  Curious, this shouldn't make much of a difference in terms of normal mapping but is "grid.jpg" a power of two texture size?

**Comment by questacian** [comment]
Here is a screenshot of the grid at 1024 X 1024 mapped to a sphere.

<img width="590" alt="screen shot 2015-10-15 at 12 32 28 pm" src="https://cloud.githubusercontent.com/assets/14141819/10520596/fca7bb08-7338-11e5-98e6-d12cafd541e7.png">

**Comment by karenpeng** [comment]
Hi, thanks for pointing it out. My guess is the merge of vertices mess up with the uvs. Will look into it!

**Comment by questacian** [comment]
Karen,

Thanks for the follow through.  Ideally the seam line should run from the
exact topmost vertex (north pole) to the exact lowermost vertex (south
pole) along a single vertical edge (line of longitude).  I have a
background in 3D animation so I've UV mapped my fair share of spheres.  :-)

Cheers-

-Quest
